// Comprehensive list of all countries with localized names
export interface Country {
  code: string;
  names: {
    de: string;
    en: string;
  };
}

export const COUNTRIES: Country[] = [
  { code: "AF", names: { de: "Afghanistan", en: "Afghanistan" } },
  { code: "AL", names: { de: "Albanien", en: "Albania" } },
  { code: "DZ", names: { de: "Algerien", en: "Algeria" } },
  { code: "AD", names: { de: "Andorra", en: "Andorra" } },
  { code: "AO", names: { de: "Angola", en: "Angola" } },
  { code: "AG", names: { de: "Antigua und Barbuda", en: "Antigua and Barbuda" } },
  { code: "AR", names: { de: "Argentinien", en: "Argentina" } },
  { code: "AM", names: { de: "Armenien", en: "Armenia" } },
  { code: "AU", names: { de: "Australien", en: "Australia" } },
  { code: "AT", names: { de: "Österreich", en: "Austria" } },
  { code: "AZ", names: { de: "Aserbaidschan", en: "Azerbaijan" } },
  { code: "BS", names: { de: "Bahamas", en: "Bahamas" } },
  { code: "BH", names: { de: "Bahrain", en: "Bahrain" } },
  { code: "BD", names: { de: "Bangladesch", en: "Bangladesh" } },
  { code: "BB", names: { de: "Barbados", en: "Barbados" } },
  { code: "BY", names: { de: "Belarus", en: "Belarus" } },
  { code: "BE", names: { de: "Belgien", en: "Belgium" } },
  { code: "BZ", names: { de: "Belize", en: "Belize" } },
  { code: "BJ", names: { de: "Benin", en: "Benin" } },
  { code: "BT", names: { de: "Bhutan", en: "Bhutan" } },
  { code: "BO", names: { de: "Bolivien", en: "Bolivia" } },
  { code: "BA", names: { de: "Bosnien und Herzegowina", en: "Bosnia and Herzegovina" } },
  { code: "BW", names: { de: "Botswana", en: "Botswana" } },
  { code: "BR", names: { de: "Brasilien", en: "Brazil" } },
  { code: "BN", names: { de: "Brunei", en: "Brunei" } },
  { code: "BG", names: { de: "Bulgarien", en: "Bulgaria" } },
  { code: "BF", names: { de: "Burkina Faso", en: "Burkina Faso" } },
  { code: "BI", names: { de: "Burundi", en: "Burundi" } },
  { code: "CV", names: { de: "Kap Verde", en: "Cabo Verde" } },
  { code: "KH", names: { de: "Kambodscha", en: "Cambodia" } },
  { code: "CM", names: { de: "Kamerun", en: "Cameroon" } },
  { code: "CA", names: { de: "Kanada", en: "Canada" } },
  { code: "CF", names: { de: "Zentralafrikanische Republik", en: "Central African Republic" } },
  { code: "TD", names: { de: "Tschad", en: "Chad" } },
  { code: "CL", names: { de: "Chile", en: "Chile" } },
  { code: "CN", names: { de: "China", en: "China" } },
  { code: "CO", names: { de: "Kolumbien", en: "Colombia" } },
  { code: "KM", names: { de: "Komoren", en: "Comoros" } },
  { code: "CG", names: { de: "Kongo", en: "Congo" } },
  { code: "CR", names: { de: "Costa Rica", en: "Costa Rica" } },
  { code: "HR", names: { de: "Kroatien", en: "Croatia" } },
  { code: "CU", names: { de: "Kuba", en: "Cuba" } },
  { code: "CY", names: { de: "Zypern", en: "Cyprus" } },
  { code: "CZ", names: { de: "Tschechien", en: "Czechia" } },
  { code: "DK", names: { de: "Dänemark", en: "Denmark" } },
  { code: "DJ", names: { de: "Dschibuti", en: "Djibouti" } },
  { code: "DM", names: { de: "Dominica", en: "Dominica" } },
  { code: "DO", names: { de: "Dominikanische Republik", en: "Dominican Republic" } },
  { code: "EC", names: { de: "Ecuador", en: "Ecuador" } },
  { code: "EG", names: { de: "Ägypten", en: "Egypt" } },
  { code: "SV", names: { de: "El Salvador", en: "El Salvador" } },
  { code: "GQ", names: { de: "Äquatorialguinea", en: "Equatorial Guinea" } },
  { code: "ER", names: { de: "Eritrea", en: "Eritrea" } },
  { code: "EE", names: { de: "Estland", en: "Estonia" } },
  { code: "SZ", names: { de: "Eswatini", en: "Eswatini" } },
  { code: "ET", names: { de: "Äthiopien", en: "Ethiopia" } },
  { code: "FJ", names: { de: "Fidschi", en: "Fiji" } },
  { code: "FI", names: { de: "Finnland", en: "Finland" } },
  { code: "FR", names: { de: "Frankreich", en: "France" } },
  { code: "GA", names: { de: "Gabun", en: "Gabon" } },
  { code: "GM", names: { de: "Gambia", en: "Gambia" } },
  { code: "GE", names: { de: "Georgien", en: "Georgia" } },
  { code: "DE", names: { de: "Deutschland", en: "Germany" } },
  { code: "GH", names: { de: "Ghana", en: "Ghana" } },
  { code: "GR", names: { de: "Griechenland", en: "Greece" } },
  { code: "GD", names: { de: "Grenada", en: "Grenada" } },
  { code: "GT", names: { de: "Guatemala", en: "Guatemala" } },
  { code: "GN", names: { de: "Guinea", en: "Guinea" } },
  { code: "GW", names: { de: "Guinea-Bissau", en: "Guinea-Bissau" } },
  { code: "GY", names: { de: "Guyana", en: "Guyana" } },
  { code: "HT", names: { de: "Haiti", en: "Haiti" } },
  { code: "HN", names: { de: "Honduras", en: "Honduras" } },
  { code: "HU", names: { de: "Ungarn", en: "Hungary" } },
  { code: "IS", names: { de: "Island", en: "Iceland" } },
  { code: "IN", names: { de: "Indien", en: "India" } },
  { code: "ID", names: { de: "Indonesien", en: "Indonesia" } },
  { code: "IR", names: { de: "Iran", en: "Iran" } },
  { code: "IQ", names: { de: "Irak", en: "Iraq" } },
  { code: "IE", names: { de: "Irland", en: "Ireland" } },
  { code: "IL", names: { de: "Israel", en: "Israel" } },
  { code: "IT", names: { de: "Italien", en: "Italy" } },
  { code: "CI", names: { de: "Elfenbeinküste", en: "Ivory Coast" } },
  { code: "JM", names: { de: "Jamaika", en: "Jamaica" } },
  { code: "JP", names: { de: "Japan", en: "Japan" } },
  { code: "JO", names: { de: "Jordanien", en: "Jordan" } },
  { code: "KZ", names: { de: "Kasachstan", en: "Kazakhstan" } },
  { code: "KE", names: { de: "Kenia", en: "Kenya" } },
  { code: "KI", names: { de: "Kiribati", en: "Kiribati" } },
  { code: "KW", names: { de: "Kuwait", en: "Kuwait" } },
  { code: "KG", names: { de: "Kirgisistan", en: "Kyrgyzstan" } },
  { code: "LA", names: { de: "Laos", en: "Laos" } },
  { code: "LV", names: { de: "Lettland", en: "Latvia" } },
  { code: "LB", names: { de: "Libanon", en: "Lebanon" } },
  { code: "LS", names: { de: "Lesotho", en: "Lesotho" } },
  { code: "LR", names: { de: "Liberia", en: "Liberia" } },
  { code: "LY", names: { de: "Libyen", en: "Libya" } },
  { code: "LI", names: { de: "Liechtenstein", en: "Liechtenstein" } },
  { code: "LT", names: { de: "Litauen", en: "Lithuania" } },
  { code: "LU", names: { de: "Luxemburg", en: "Luxembourg" } },
  { code: "MG", names: { de: "Madagaskar", en: "Madagascar" } },
  { code: "MW", names: { de: "Malawi", en: "Malawi" } },
  { code: "MY", names: { de: "Malaysia", en: "Malaysia" } },
  { code: "MV", names: { de: "Malediven", en: "Maldives" } },
  { code: "ML", names: { de: "Mali", en: "Mali" } },
  { code: "MT", names: { de: "Malta", en: "Malta" } },
  { code: "MH", names: { de: "Marshallinseln", en: "Marshall Islands" } },
  { code: "MR", names: { de: "Mauretanien", en: "Mauritania" } },
  { code: "MU", names: { de: "Mauritius", en: "Mauritius" } },
  { code: "MX", names: { de: "Mexiko", en: "Mexico" } },
  { code: "FM", names: { de: "Mikronesien", en: "Micronesia" } },
  { code: "MD", names: { de: "Moldawien", en: "Moldova" } },
  { code: "MC", names: { de: "Monaco", en: "Monaco" } },
  { code: "MN", names: { de: "Mongolei", en: "Mongolia" } },
  { code: "ME", names: { de: "Montenegro", en: "Montenegro" } },
  { code: "MA", names: { de: "Marokko", en: "Morocco" } },
  { code: "MZ", names: { de: "Mosambik", en: "Mozambique" } },
  { code: "MM", names: { de: "Myanmar", en: "Myanmar" } },
  { code: "NA", names: { de: "Namibia", en: "Namibia" } },
  { code: "NR", names: { de: "Nauru", en: "Nauru" } },
  { code: "NP", names: { de: "Nepal", en: "Nepal" } },
  { code: "NL", names: { de: "Niederlande", en: "Netherlands" } },
  { code: "NZ", names: { de: "Neuseeland", en: "New Zealand" } },
  { code: "NI", names: { de: "Nicaragua", en: "Nicaragua" } },
  { code: "NE", names: { de: "Niger", en: "Niger" } },
  { code: "NG", names: { de: "Nigeria", en: "Nigeria" } },
  { code: "KP", names: { de: "Nordkorea", en: "North Korea" } },
  { code: "MK", names: { de: "Nordmazedonien", en: "North Macedonia" } },
  { code: "NO", names: { de: "Norwegen", en: "Norway" } },
  { code: "OM", names: { de: "Oman", en: "Oman" } },
  { code: "PK", names: { de: "Pakistan", en: "Pakistan" } },
  { code: "PW", names: { de: "Palau", en: "Palau" } },
  { code: "PS", names: { de: "Palästina", en: "Palestine" } },
  { code: "PA", names: { de: "Panama", en: "Panama" } },
  { code: "PG", names: { de: "Papua-Neuguinea", en: "Papua New Guinea" } },
  { code: "PY", names: { de: "Paraguay", en: "Paraguay" } },
  { code: "PE", names: { de: "Peru", en: "Peru" } },
  { code: "PH", names: { de: "Philippinen", en: "Philippines" } },
  { code: "PL", names: { de: "Polen", en: "Poland" } },
  { code: "PT", names: { de: "Portugal", en: "Portugal" } },
  { code: "QA", names: { de: "Katar", en: "Qatar" } },
  { code: "RO", names: { de: "Rumänien", en: "Romania" } },
  { code: "RU", names: { de: "Russland", en: "Russia" } },
  { code: "RW", names: { de: "Ruanda", en: "Rwanda" } },
  { code: "KN", names: { de: "St. Kitts und Nevis", en: "Saint Kitts and Nevis" } },
  { code: "LC", names: { de: "St. Lucia", en: "Saint Lucia" } },
  { code: "VC", names: { de: "St. Vincent und die Grenadinen", en: "Saint Vincent and the Grenadines" } },
  { code: "WS", names: { de: "Samoa", en: "Samoa" } },
  { code: "SM", names: { de: "San Marino", en: "San Marino" } },
  { code: "ST", names: { de: "São Tomé und Príncipe", en: "Sao Tome and Principe" } },
  { code: "SA", names: { de: "Saudi-Arabien", en: "Saudi Arabia" } },
  { code: "SN", names: { de: "Senegal", en: "Senegal" } },
  { code: "RS", names: { de: "Serbien", en: "Serbia" } },
  { code: "SC", names: { de: "Seychellen", en: "Seychelles" } },
  { code: "SL", names: { de: "Sierra Leone", en: "Sierra Leone" } },
  { code: "SG", names: { de: "Singapur", en: "Singapore" } },
  { code: "SK", names: { de: "Slowakei", en: "Slovakia" } },
  { code: "SI", names: { de: "Slowenien", en: "Slovenia" } },
  { code: "SB", names: { de: "Salomonen", en: "Solomon Islands" } },
  { code: "SO", names: { de: "Somalia", en: "Somalia" } },
  { code: "ZA", names: { de: "Südafrika", en: "South Africa" } },
  { code: "KR", names: { de: "Südkorea", en: "South Korea" } },
  { code: "SS", names: { de: "Südsudan", en: "South Sudan" } },
  { code: "ES", names: { de: "Spanien", en: "Spain" } },
  { code: "LK", names: { de: "Sri Lanka", en: "Sri Lanka" } },
  { code: "SD", names: { de: "Sudan", en: "Sudan" } },
  { code: "SR", names: { de: "Suriname", en: "Suriname" } },
  { code: "SE", names: { de: "Schweden", en: "Sweden" } },
  { code: "CH", names: { de: "Schweiz", en: "Switzerland" } },
  { code: "SY", names: { de: "Syrien", en: "Syria" } },
  { code: "TW", names: { de: "Taiwan", en: "Taiwan" } },
  { code: "TJ", names: { de: "Tadschikistan", en: "Tajikistan" } },
  { code: "TZ", names: { de: "Tansania", en: "Tanzania" } },
  { code: "TH", names: { de: "Thailand", en: "Thailand" } },
  { code: "TL", names: { de: "Osttimor", en: "Timor-Leste" } },
  { code: "TG", names: { de: "Togo", en: "Togo" } },
  { code: "TO", names: { de: "Tonga", en: "Tonga" } },
  { code: "TT", names: { de: "Trinidad und Tobago", en: "Trinidad and Tobago" } },
  { code: "TN", names: { de: "Tunesien", en: "Tunisia" } },
  { code: "TR", names: { de: "Türkei", en: "Turkey" } },
  { code: "TM", names: { de: "Turkmenistan", en: "Turkmenistan" } },
  { code: "TV", names: { de: "Tuvalu", en: "Tuvalu" } },
  { code: "UG", names: { de: "Uganda", en: "Uganda" } },
  { code: "UA", names: { de: "Ukraine", en: "Ukraine" } },
  { code: "AE", names: { de: "Vereinigte Arabische Emirate", en: "United Arab Emirates" } },
  { code: "GB", names: { de: "Vereinigtes Königreich", en: "United Kingdom" } },
  { code: "US", names: { de: "Vereinigte Staaten", en: "United States" } },
  { code: "UY", names: { de: "Uruguay", en: "Uruguay" } },
  { code: "UZ", names: { de: "Usbekistan", en: "Uzbekistan" } },
  { code: "VU", names: { de: "Vanuatu", en: "Vanuatu" } },
  { code: "VA", names: { de: "Vatikanstadt", en: "Vatican City" } },
  { code: "VE", names: { de: "Venezuela", en: "Venezuela" } },
  { code: "VN", names: { de: "Vietnam", en: "Vietnam" } },
  { code: "YE", names: { de: "Jemen", en: "Yemen" } },
  { code: "ZM", names: { de: "Sambia", en: "Zambia" } },
  { code: "ZW", names: { de: "Simbabwe", en: "Zimbabwe" } },
];

// Get countries with localized names, sorted alphabetically
export function getLocalizedCountries(locale: string): { code: string; name: string }[] {
  const lang = locale.startsWith("de") ? "de" : "en";
  
  return COUNTRIES
    .map((country) => ({
      code: country.code,
      name: country.names[lang] || country.names.en,
    }))
    .sort((a, b) => a.name.localeCompare(b.name, locale));
}

// Prioritized countries for German-speaking regions (shown first)
export const PRIORITY_COUNTRIES = ["DE", "AT", "CH"];

export function getLocalizedCountriesWithPriority(locale: string): { code: string; name: string }[] {
  const allCountries = getLocalizedCountries(locale);
  
  const prioritized = allCountries.filter(c => PRIORITY_COUNTRIES.includes(c.code));
  const rest = allCountries.filter(c => !PRIORITY_COUNTRIES.includes(c.code));
  
  return [...prioritized, ...rest];
}
