// Comprehensive Games Library for all event types
// 200+ games covering JGA, Family, Wedding, Birthday, Team Events, and more

export type GameCategory = 
  | 'jga_games'
  | 'family_games'
  | 'wedding_games'
  | 'party_games'
  | 'outdoor_games'
  | 'team_games'
  | 'icebreaker'
  | 'kids_friendly';

export type EventType = 'bachelor' | 'bachelorette' | 'wedding' | 'birthday' | 'family' | 'team' | 'trip' | 'other';

export type Difficulty = 'easy' | 'medium' | 'hard';

export interface GameItem {
  id: string;
  nameKey: string;
  descriptionKey: string;
  instructionsKey: string;
  emoji: string;
  categories: GameCategory[];
  eventTypes: EventType[];
  difficulty: Difficulty;
  groupSize: { min: number; max?: number };
  duration: string;
  materials?: string[];
  tags: string[];
  isKidsFriendly: boolean;
  isAlcoholRelated: boolean;
  isClassic?: boolean;
}

// JGA Games (50 games)
const jgaGames: GameItem[] = [
  {
    id: 'bingo_tasks',
    nameKey: 'gamesLibrary.games.bingo_tasks.name',
    descriptionKey: 'gamesLibrary.games.bingo_tasks.description',
    instructionsKey: 'gamesLibrary.games.bingo_tasks.instructions',
    emoji: '📋',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '60-120min',
    materials: ['Bingo-Karten', 'Stifte'],
    tags: ['outdoor', 'challenge', 'classic'],
    isKidsFriendly: false,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'drink_roulette',
    nameKey: 'gamesLibrary.games.drink_roulette.name',
    descriptionKey: 'gamesLibrary.games.drink_roulette.description',
    instructionsKey: 'gamesLibrary.games.drink_roulette.instructions',
    emoji: '🎰',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'easy',
    groupSize: { min: 3, max: 15 },
    duration: '30-60min',
    materials: ['Roulette-Rad', 'Getränke'],
    tags: ['drinking', 'party'],
    isKidsFriendly: false,
    isAlcoholRelated: true
  },
  {
    id: 'who_am_i',
    nameKey: 'gamesLibrary.games.who_am_i.name',
    descriptionKey: 'gamesLibrary.games.who_am_i.description',
    instructionsKey: 'gamesLibrary.games.who_am_i.instructions',
    emoji: '🎭',
    categories: ['jga_games', 'icebreaker'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '20-40min',
    materials: ['Haftnotizen', 'Stifte'],
    tags: ['guessing', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'flunkyball',
    nameKey: 'gamesLibrary.games.flunkyball.name',
    descriptionKey: 'gamesLibrary.games.flunkyball.description',
    instructionsKey: 'gamesLibrary.games.flunkyball.instructions',
    emoji: '🍺',
    categories: ['jga_games', 'outdoor_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'medium',
    groupSize: { min: 6, max: 20 },
    duration: '30-60min',
    materials: ['Ball', 'Flasche', 'Getränke'],
    tags: ['outdoor', 'drinking', 'team'],
    isKidsFriendly: false,
    isAlcoholRelated: true
  },
  {
    id: 'beer_pong',
    nameKey: 'gamesLibrary.games.beer_pong.name',
    descriptionKey: 'gamesLibrary.games.beer_pong.description',
    instructionsKey: 'gamesLibrary.games.beer_pong.instructions',
    emoji: '🏓',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 8 },
    duration: '20-45min',
    materials: ['Tisch', 'Becher', 'Tischtennisbälle', 'Bier'],
    tags: ['drinking', 'classic', 'competition'],
    isKidsFriendly: false,
    isAlcoholRelated: true,
    isClassic: true
  },
  {
    id: 'groom_bride_quiz',
    nameKey: 'gamesLibrary.games.groom_bride_quiz.name',
    descriptionKey: 'gamesLibrary.games.groom_bride_quiz.description',
    instructionsKey: 'gamesLibrary.games.groom_bride_quiz.instructions',
    emoji: '📝',
    categories: ['jga_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 30 },
    duration: '15-30min',
    materials: ['Fragebogen', 'Stifte'],
    tags: ['quiz', 'personal'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'truth_or_dare',
    nameKey: 'gamesLibrary.games.truth_or_dare.name',
    descriptionKey: 'gamesLibrary.games.truth_or_dare.description',
    instructionsKey: 'gamesLibrary.games.truth_or_dare.instructions',
    emoji: '🔥',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'medium',
    groupSize: { min: 3, max: 15 },
    duration: '30-60min',
    materials: ['Optional: Flasche zum Drehen'],
    tags: ['challenge', 'fun', 'adult'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'kiss_challenge',
    nameKey: 'gamesLibrary.games.kiss_challenge.name',
    descriptionKey: 'gamesLibrary.games.kiss_challenge.description',
    instructionsKey: 'gamesLibrary.games.kiss_challenge.instructions',
    emoji: '💋',
    categories: ['jga_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'hard',
    groupSize: { min: 2, max: 10 },
    duration: '60-120min',
    materials: ['Lippenstift', 'T-Shirt'],
    tags: ['challenge', 'outdoor', 'bold'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'selfie_mission',
    nameKey: 'gamesLibrary.games.selfie_mission.name',
    descriptionKey: 'gamesLibrary.games.selfie_mission.description',
    instructionsKey: 'gamesLibrary.games.selfie_mission.instructions',
    emoji: '📸',
    categories: ['jga_games', 'outdoor_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 20 },
    duration: '60-180min',
    materials: ['Smartphones', 'Aufgabenliste'],
    tags: ['outdoor', 'photo', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'costume_tasks',
    nameKey: 'gamesLibrary.games.costume_tasks.name',
    descriptionKey: 'gamesLibrary.games.costume_tasks.description',
    instructionsKey: 'gamesLibrary.games.costume_tasks.instructions',
    emoji: '👗',
    categories: ['jga_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'medium',
    groupSize: { min: 3, max: 15 },
    duration: '30-120min',
    materials: ['Kostüme', 'Accessoires'],
    tags: ['costume', 'fun', 'embarrassing'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'bucket_list',
    nameKey: 'gamesLibrary.games.bucket_list.name',
    descriptionKey: 'gamesLibrary.games.bucket_list.description',
    instructionsKey: 'gamesLibrary.games.bucket_list.instructions',
    emoji: '✅',
    categories: ['jga_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'medium',
    groupSize: { min: 2, max: 20 },
    duration: '120-480min',
    materials: ['Bucket-Liste'],
    tags: ['adventure', 'challenge', 'memorable'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'karaoke_battle',
    nameKey: 'gamesLibrary.games.karaoke_battle.name',
    descriptionKey: 'gamesLibrary.games.karaoke_battle.description',
    instructionsKey: 'gamesLibrary.games.karaoke_battle.instructions',
    emoji: '🎤',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '60-120min',
    materials: ['Karaoke-Anlage/App', 'Mikrofon'],
    tags: ['singing', 'fun', 'party'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'city_rally',
    nameKey: 'gamesLibrary.games.city_rally.name',
    descriptionKey: 'gamesLibrary.games.city_rally.description',
    instructionsKey: 'gamesLibrary.games.city_rally.instructions',
    emoji: '🗺️',
    categories: ['jga_games', 'outdoor_games', 'team_games'],
    eventTypes: ['bachelor', 'bachelorette', 'team'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 30 },
    duration: '120-240min',
    materials: ['Aufgabenkarten', 'Stadtplan'],
    tags: ['outdoor', 'adventure', 'team'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'photo_scavenger_hunt',
    nameKey: 'gamesLibrary.games.photo_scavenger_hunt.name',
    descriptionKey: 'gamesLibrary.games.photo_scavenger_hunt.description',
    instructionsKey: 'gamesLibrary.games.photo_scavenger_hunt.instructions',
    emoji: '📷',
    categories: ['jga_games', 'outdoor_games', 'team_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday', 'team'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 30 },
    duration: '60-180min',
    materials: ['Smartphones', 'Foto-Liste'],
    tags: ['photo', 'outdoor', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'team_olympiad',
    nameKey: 'gamesLibrary.games.team_olympiad.name',
    descriptionKey: 'gamesLibrary.games.team_olympiad.description',
    instructionsKey: 'gamesLibrary.games.team_olympiad.instructions',
    emoji: '🏆',
    categories: ['jga_games', 'outdoor_games', 'team_games'],
    eventTypes: ['bachelor', 'bachelorette', 'team', 'family'],
    difficulty: 'medium',
    groupSize: { min: 6, max: 50 },
    duration: '120-240min',
    materials: ['Verschiedene Spielmaterialien'],
    tags: ['competition', 'outdoor', 'sports'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'boot_camp',
    nameKey: 'gamesLibrary.games.boot_camp.name',
    descriptionKey: 'gamesLibrary.games.boot_camp.description',
    instructionsKey: 'gamesLibrary.games.boot_camp.instructions',
    emoji: '💪',
    categories: ['jga_games', 'outdoor_games', 'team_games'],
    eventTypes: ['bachelor', 'bachelorette', 'team'],
    difficulty: 'hard',
    groupSize: { min: 4, max: 20 },
    duration: '60-120min',
    materials: ['Sportkleidung', 'Trainingsutensilien'],
    tags: ['fitness', 'challenge', 'outdoor'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'cocktail_contest',
    nameKey: 'gamesLibrary.games.cocktail_contest.name',
    descriptionKey: 'gamesLibrary.games.cocktail_contest.description',
    instructionsKey: 'gamesLibrary.games.cocktail_contest.instructions',
    emoji: '🍹',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 15 },
    duration: '45-90min',
    materials: ['Zutaten', 'Shaker', 'Gläser'],
    tags: ['creative', 'drinking', 'fun'],
    isKidsFriendly: false,
    isAlcoholRelated: true
  },
  {
    id: 'wine_tasting',
    nameKey: 'gamesLibrary.games.wine_tasting.name',
    descriptionKey: 'gamesLibrary.games.wine_tasting.description',
    instructionsKey: 'gamesLibrary.games.wine_tasting.instructions',
    emoji: '🍷',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 20 },
    duration: '60-120min',
    materials: ['Weine', 'Bewertungsbögen', 'Augenbinden'],
    tags: ['tasting', 'elegant', 'fun'],
    isKidsFriendly: false,
    isAlcoholRelated: true
  },
  {
    id: 'tshirt_design',
    nameKey: 'gamesLibrary.games.tshirt_design.name',
    descriptionKey: 'gamesLibrary.games.tshirt_design.description',
    instructionsKey: 'gamesLibrary.games.tshirt_design.instructions',
    emoji: '👕',
    categories: ['jga_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 20 },
    duration: '30-60min',
    materials: ['T-Shirts', 'Textilfarben', 'Pinsel'],
    tags: ['creative', 'keepsake', 'group'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'embarrassing_songs',
    nameKey: 'gamesLibrary.games.embarrassing_songs.name',
    descriptionKey: 'gamesLibrary.games.embarrassing_songs.description',
    instructionsKey: 'gamesLibrary.games.embarrassing_songs.instructions',
    emoji: '🎵',
    categories: ['jga_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'medium',
    groupSize: { min: 3, max: 15 },
    duration: '15-30min',
    materials: ['Musikbox'],
    tags: ['singing', 'embarrassing', 'fun'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'dare_dice',
    nameKey: 'gamesLibrary.games.dare_dice.name',
    descriptionKey: 'gamesLibrary.games.dare_dice.description',
    instructionsKey: 'gamesLibrary.games.dare_dice.instructions',
    emoji: '🎲',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 3, max: 12 },
    duration: '30-60min',
    materials: ['Aufgaben-Würfel'],
    tags: ['random', 'challenge', 'fun'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'never_have_i_ever',
    nameKey: 'gamesLibrary.games.never_have_i_ever.name',
    descriptionKey: 'gamesLibrary.games.never_have_i_ever.description',
    instructionsKey: 'gamesLibrary.games.never_have_i_ever.instructions',
    emoji: '🙈',
    categories: ['jga_games', 'party_games', 'icebreaker'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 15 },
    duration: '20-45min',
    materials: ['Optional: Getränke'],
    tags: ['confessions', 'fun', 'group'],
    isKidsFriendly: false,
    isAlcoholRelated: true
  },
  {
    id: 'ring_search_pasta',
    nameKey: 'gamesLibrary.games.ring_search_pasta.name',
    descriptionKey: 'gamesLibrary.games.ring_search_pasta.description',
    instructionsKey: 'gamesLibrary.games.ring_search_pasta.instructions',
    emoji: '🍝',
    categories: ['jga_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 10 },
    duration: '10-20min',
    materials: ['Schüssel', 'Nudeln', 'Ring'],
    tags: ['messy', 'funny', 'competition'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'toilet_paper_dress',
    nameKey: 'gamesLibrary.games.toilet_paper_dress.name',
    descriptionKey: 'gamesLibrary.games.toilet_paper_dress.description',
    instructionsKey: 'gamesLibrary.games.toilet_paper_dress.instructions',
    emoji: '🧻',
    categories: ['jga_games'],
    eventTypes: ['bachelorette'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 15 },
    duration: '20-30min',
    materials: ['Toilettenpapier'],
    tags: ['creative', 'funny', 'bridal'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'balloon_dance',
    nameKey: 'gamesLibrary.games.balloon_dance.name',
    descriptionKey: 'gamesLibrary.games.balloon_dance.description',
    instructionsKey: 'gamesLibrary.games.balloon_dance.instructions',
    emoji: '🎈',
    categories: ['jga_games', 'party_games', 'wedding_games'],
    eventTypes: ['bachelor', 'bachelorette', 'wedding', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 30 },
    duration: '10-20min',
    materials: ['Luftballons', 'Musik'],
    tags: ['dance', 'fun', 'active'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'limbo_competition',
    nameKey: 'gamesLibrary.games.limbo_competition.name',
    descriptionKey: 'gamesLibrary.games.limbo_competition.description',
    instructionsKey: 'gamesLibrary.games.limbo_competition.instructions',
    emoji: '🕺',
    categories: ['jga_games', 'party_games', 'wedding_games'],
    eventTypes: ['bachelor', 'bachelorette', 'wedding', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 30 },
    duration: '15-30min',
    materials: ['Limbo-Stange', 'Musik'],
    tags: ['dance', 'competition', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'pinata',
    nameKey: 'gamesLibrary.games.pinata.name',
    descriptionKey: 'gamesLibrary.games.pinata.description',
    instructionsKey: 'gamesLibrary.games.pinata.instructions',
    emoji: '🪅',
    categories: ['jga_games', 'party_games', 'kids_friendly'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 3, max: 20 },
    duration: '15-30min',
    materials: ['Piñata', 'Stock', 'Augenbinde'],
    tags: ['fun', 'surprise', 'candy'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'mystery_box',
    nameKey: 'gamesLibrary.games.mystery_box.name',
    descriptionKey: 'gamesLibrary.games.mystery_box.description',
    instructionsKey: 'gamesLibrary.games.mystery_box.instructions',
    emoji: '📦',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'medium',
    groupSize: { min: 3, max: 15 },
    duration: '20-40min',
    materials: ['Boxen', 'Verschiedene Gegenstände'],
    tags: ['guessing', 'sensory', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'hat_challenges',
    nameKey: 'gamesLibrary.games.hat_challenges.name',
    descriptionKey: 'gamesLibrary.games.hat_challenges.description',
    instructionsKey: 'gamesLibrary.games.hat_challenges.instructions',
    emoji: '🎩',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 20 },
    duration: '60-180min',
    materials: ['Hut', 'Aufgabenzettel'],
    tags: ['random', 'challenge', 'ongoing'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'photo_booth',
    nameKey: 'gamesLibrary.games.photo_booth.name',
    descriptionKey: 'gamesLibrary.games.photo_booth.description',
    instructionsKey: 'gamesLibrary.games.photo_booth.instructions',
    emoji: '🖼️',
    categories: ['jga_games', 'party_games', 'wedding_games'],
    eventTypes: ['bachelor', 'bachelorette', 'wedding', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 50 },
    duration: 'ganzen Abend',
    materials: ['Kamera/Handy', 'Requisiten', 'Hintergrund'],
    tags: ['photo', 'fun', 'keepsake'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'speed_dating',
    nameKey: 'gamesLibrary.games.speed_dating.name',
    descriptionKey: 'gamesLibrary.games.speed_dating.description',
    instructionsKey: 'gamesLibrary.games.speed_dating.instructions',
    emoji: '⚡',
    categories: ['jga_games', 'icebreaker'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'easy',
    groupSize: { min: 6, max: 20 },
    duration: '30-60min',
    materials: ['Timer', 'Tische/Stühle'],
    tags: ['icebreaker', 'fun', 'social'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'who_knows_best',
    nameKey: 'gamesLibrary.games.who_knows_best.name',
    descriptionKey: 'gamesLibrary.games.who_knows_best.description',
    instructionsKey: 'gamesLibrary.games.who_knows_best.instructions',
    emoji: '💑',
    categories: ['jga_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '20-40min',
    materials: ['Fragebogen', 'Stifte'],
    tags: ['quiz', 'friendship', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'charades',
    nameKey: 'gamesLibrary.games.charades.name',
    descriptionKey: 'gamesLibrary.games.charades.description',
    instructionsKey: 'gamesLibrary.games.charades.instructions',
    emoji: '🎭',
    categories: ['jga_games', 'party_games', 'family_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday', 'family'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '30-60min',
    materials: ['Begriffskarten'],
    tags: ['acting', 'classic', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'activity',
    nameKey: 'gamesLibrary.games.activity.name',
    descriptionKey: 'gamesLibrary.games.activity.description',
    instructionsKey: 'gamesLibrary.games.activity.instructions',
    emoji: '🎯',
    categories: ['jga_games', 'party_games', 'family_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday', 'family'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 16 },
    duration: '45-90min',
    materials: ['Activity-Spiel'],
    tags: ['board game', 'classic', 'team'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'taboo',
    nameKey: 'gamesLibrary.games.taboo.name',
    descriptionKey: 'gamesLibrary.games.taboo.description',
    instructionsKey: 'gamesLibrary.games.taboo.instructions',
    emoji: '🤐',
    categories: ['jga_games', 'party_games', 'family_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday', 'family'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 12 },
    duration: '30-60min',
    materials: ['Tabu-Karten', 'Timer'],
    tags: ['word game', 'classic', 'team'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'pictionary',
    nameKey: 'gamesLibrary.games.pictionary.name',
    descriptionKey: 'gamesLibrary.games.pictionary.description',
    instructionsKey: 'gamesLibrary.games.pictionary.instructions',
    emoji: '🎨',
    categories: ['jga_games', 'party_games', 'family_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday', 'family'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 16 },
    duration: '30-60min',
    materials: ['Papier', 'Stifte', 'Timer'],
    tags: ['drawing', 'classic', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'cards_against',
    nameKey: 'gamesLibrary.games.cards_against.name',
    descriptionKey: 'gamesLibrary.games.cards_against.description',
    instructionsKey: 'gamesLibrary.games.cards_against.instructions',
    emoji: '🃏',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 12 },
    duration: '30-90min',
    materials: ['Cards Against Humanity'],
    tags: ['card game', 'adult', 'humor'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'rage_cage',
    nameKey: 'gamesLibrary.games.rage_cage.name',
    descriptionKey: 'gamesLibrary.games.rage_cage.description',
    instructionsKey: 'gamesLibrary.games.rage_cage.instructions',
    emoji: '🍻',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'medium',
    groupSize: { min: 6, max: 12 },
    duration: '20-40min',
    materials: ['Becher', 'Bälle', 'Getränke'],
    tags: ['drinking', 'fast-paced', 'party'],
    isKidsFriendly: false,
    isAlcoholRelated: true
  },
  {
    id: 'flip_cup',
    nameKey: 'gamesLibrary.games.flip_cup.name',
    descriptionKey: 'gamesLibrary.games.flip_cup.description',
    instructionsKey: 'gamesLibrary.games.flip_cup.instructions',
    emoji: '🥤',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '15-30min',
    materials: ['Plastikbecher', 'Tisch', 'Getränke'],
    tags: ['drinking', 'team', 'fast'],
    isKidsFriendly: false,
    isAlcoholRelated: true
  },
  {
    id: 'murder_mystery',
    nameKey: 'gamesLibrary.games.murder_mystery.name',
    descriptionKey: 'gamesLibrary.games.murder_mystery.description',
    instructionsKey: 'gamesLibrary.games.murder_mystery.instructions',
    emoji: '🔪',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'hard',
    groupSize: { min: 6, max: 12 },
    duration: '120-240min',
    materials: ['Murder Mystery Set', 'Kostüme'],
    tags: ['roleplay', 'mystery', 'immersive'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'escape_room_diy',
    nameKey: 'gamesLibrary.games.escape_room_diy.name',
    descriptionKey: 'gamesLibrary.games.escape_room_diy.description',
    instructionsKey: 'gamesLibrary.games.escape_room_diy.instructions',
    emoji: '🔐',
    categories: ['jga_games', 'team_games'],
    eventTypes: ['bachelor', 'bachelorette', 'team', 'birthday'],
    difficulty: 'hard',
    groupSize: { min: 4, max: 10 },
    duration: '60-90min',
    materials: ['Rätsel', 'Schlösser', 'Hinweise'],
    tags: ['puzzle', 'team', 'challenge'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'casino_night',
    nameKey: 'gamesLibrary.games.casino_night.name',
    descriptionKey: 'gamesLibrary.games.casino_night.description',
    instructionsKey: 'gamesLibrary.games.casino_night.instructions',
    emoji: '🎰',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'medium',
    groupSize: { min: 6, max: 30 },
    duration: '120-240min',
    materials: ['Spielkarten', 'Chips', 'Spieltische'],
    tags: ['gambling', 'theme', 'elegant'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'drag_race',
    nameKey: 'gamesLibrary.games.drag_race.name',
    descriptionKey: 'gamesLibrary.games.drag_race.description',
    instructionsKey: 'gamesLibrary.games.drag_race.instructions',
    emoji: '💄',
    categories: ['jga_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 12 },
    duration: '60-120min',
    materials: ['Make-up', 'Kostüme', 'Musik'],
    tags: ['makeover', 'performance', 'fun'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'dance_off',
    nameKey: 'gamesLibrary.games.dance_off.name',
    descriptionKey: 'gamesLibrary.games.dance_off.description',
    instructionsKey: 'gamesLibrary.games.dance_off.instructions',
    emoji: '💃',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday', 'wedding'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 30 },
    duration: '20-45min',
    materials: ['Musik', 'Tanzfläche'],
    tags: ['dance', 'competition', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'lip_sync_battle',
    nameKey: 'gamesLibrary.games.lip_sync_battle.name',
    descriptionKey: 'gamesLibrary.games.lip_sync_battle.description',
    instructionsKey: 'gamesLibrary.games.lip_sync_battle.instructions',
    emoji: '👄',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '30-60min',
    materials: ['Musik', 'Mikrofon (Requisite)'],
    tags: ['performance', 'fun', 'music'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'twerk_contest',
    nameKey: 'gamesLibrary.games.twerk_contest.name',
    descriptionKey: 'gamesLibrary.games.twerk_contest.description',
    instructionsKey: 'gamesLibrary.games.twerk_contest.instructions',
    emoji: '🍑',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'medium',
    groupSize: { min: 3, max: 15 },
    duration: '15-30min',
    materials: ['Musik'],
    tags: ['dance', 'bold', 'party'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'pole_dance_intro',
    nameKey: 'gamesLibrary.games.pole_dance_intro.name',
    descriptionKey: 'gamesLibrary.games.pole_dance_intro.description',
    instructionsKey: 'gamesLibrary.games.pole_dance_intro.instructions',
    emoji: '💃',
    categories: ['jga_games'],
    eventTypes: ['bachelorette'],
    difficulty: 'hard',
    groupSize: { min: 4, max: 12 },
    duration: '60-90min',
    materials: ['Pole Dance Studio'],
    tags: ['fitness', 'bold', 'workshop'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'strip_poker_light',
    nameKey: 'gamesLibrary.games.strip_poker_light.name',
    descriptionKey: 'gamesLibrary.games.strip_poker_light.description',
    instructionsKey: 'gamesLibrary.games.strip_poker_light.instructions',
    emoji: '♠️',
    categories: ['jga_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'hard',
    groupSize: { min: 4, max: 8 },
    duration: '30-60min',
    materials: ['Spielkarten'],
    tags: ['adult', 'bold', 'intimate'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'dirty_minds_quiz',
    nameKey: 'gamesLibrary.games.dirty_minds_quiz.name',
    descriptionKey: 'gamesLibrary.games.dirty_minds_quiz.description',
    instructionsKey: 'gamesLibrary.games.dirty_minds_quiz.instructions',
    emoji: '🧠',
    categories: ['jga_games', 'party_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 15 },
    duration: '20-40min',
    materials: ['Quizfragen'],
    tags: ['quiz', 'adult', 'humor'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'last_night_freedom',
    nameKey: 'gamesLibrary.games.last_night_freedom.name',
    descriptionKey: 'gamesLibrary.games.last_night_freedom.description',
    instructionsKey: 'gamesLibrary.games.last_night_freedom.instructions',
    emoji: '🌙',
    categories: ['jga_games'],
    eventTypes: ['bachelor', 'bachelorette'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 20 },
    duration: 'ganzen Abend',
    materials: ['Aufgabenliste'],
    tags: ['comprehensive', 'memorable', 'adventure'],
    isKidsFriendly: false,
    isAlcoholRelated: true
  }
];

// Family Games (40 games)
const familyGames: GameItem[] = [
  {
    id: 'family_feud',
    nameKey: 'gamesLibrary.games.family_feud.name',
    descriptionKey: 'gamesLibrary.games.family_feud.description',
    instructionsKey: 'gamesLibrary.games.family_feud.instructions',
    emoji: '🏆',
    categories: ['family_games'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 6, max: 20 },
    duration: '30-60min',
    materials: ['Fragebogen', 'Buzzers'],
    tags: ['tv show', 'quiz', 'team'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'scavenger_hunt',
    nameKey: 'gamesLibrary.games.scavenger_hunt.name',
    descriptionKey: 'gamesLibrary.games.scavenger_hunt.description',
    instructionsKey: 'gamesLibrary.games.scavenger_hunt.instructions',
    emoji: '🔍',
    categories: ['family_games', 'outdoor_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 30 },
    duration: '30-90min',
    materials: ['Aufgabenliste', 'Preise'],
    tags: ['outdoor', 'adventure', 'all ages'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'family_bingo',
    nameKey: 'gamesLibrary.games.family_bingo.name',
    descriptionKey: 'gamesLibrary.games.family_bingo.description',
    instructionsKey: 'gamesLibrary.games.family_bingo.instructions',
    emoji: '📋',
    categories: ['family_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 30 },
    duration: '20-40min',
    materials: ['Bingo-Karten', 'Marker', 'Preise'],
    tags: ['classic', 'all ages', 'luck'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'memory_challenge',
    nameKey: 'gamesLibrary.games.memory_challenge.name',
    descriptionKey: 'gamesLibrary.games.memory_challenge.description',
    instructionsKey: 'gamesLibrary.games.memory_challenge.instructions',
    emoji: '🧠',
    categories: ['family_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 8 },
    duration: '15-30min',
    materials: ['Memory-Karten'],
    tags: ['memory', 'concentration', 'quiet'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'family_quiz',
    nameKey: 'gamesLibrary.games.family_quiz.name',
    descriptionKey: 'gamesLibrary.games.family_quiz.description',
    instructionsKey: 'gamesLibrary.games.family_quiz.instructions',
    emoji: '📝',
    categories: ['family_games'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 30 },
    duration: '30-60min',
    materials: ['Quizfragen', 'Buzzer'],
    tags: ['knowledge', 'generations', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'time_capsule',
    nameKey: 'gamesLibrary.games.time_capsule.name',
    descriptionKey: 'gamesLibrary.games.time_capsule.description',
    instructionsKey: 'gamesLibrary.games.time_capsule.instructions',
    emoji: '📦',
    categories: ['family_games'],
    eventTypes: ['family', 'wedding', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 50 },
    duration: '30-60min',
    materials: ['Behälter', 'Papier', 'Erinnerungsstücke'],
    tags: ['meaningful', 'keepsake', 'memories'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'sack_race',
    nameKey: 'gamesLibrary.games.sack_race.name',
    descriptionKey: 'gamesLibrary.games.sack_race.description',
    instructionsKey: 'gamesLibrary.games.sack_race.instructions',
    emoji: '🛍️',
    categories: ['family_games', 'outdoor_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 30 },
    duration: '15-30min',
    materials: ['Säcke', 'Markierung für Ziellinie'],
    tags: ['outdoor', 'race', 'classic'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'egg_and_spoon',
    nameKey: 'gamesLibrary.games.egg_and_spoon.name',
    descriptionKey: 'gamesLibrary.games.egg_and_spoon.description',
    instructionsKey: 'gamesLibrary.games.egg_and_spoon.instructions',
    emoji: '🥚',
    categories: ['family_games', 'outdoor_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 30 },
    duration: '15-30min',
    materials: ['Eier', 'Löffel'],
    tags: ['outdoor', 'balance', 'classic'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'can_knockdown',
    nameKey: 'gamesLibrary.games.can_knockdown.name',
    descriptionKey: 'gamesLibrary.games.can_knockdown.description',
    instructionsKey: 'gamesLibrary.games.can_knockdown.instructions',
    emoji: '🥫',
    categories: ['family_games', 'outdoor_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 20 },
    duration: '15-30min',
    materials: ['Dosen', 'Bälle'],
    tags: ['outdoor', 'aim', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'kubb',
    nameKey: 'gamesLibrary.games.kubb.name',
    descriptionKey: 'gamesLibrary.games.kubb.description',
    instructionsKey: 'gamesLibrary.games.kubb.instructions',
    emoji: '🪓',
    categories: ['family_games', 'outdoor_games'],
    eventTypes: ['family', 'birthday', 'team'],
    difficulty: 'medium',
    groupSize: { min: 2, max: 12 },
    duration: '30-60min',
    materials: ['Kubb-Set'],
    tags: ['outdoor', 'strategy', 'viking'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'boccia',
    nameKey: 'gamesLibrary.games.boccia.name',
    descriptionKey: 'gamesLibrary.games.boccia.description',
    instructionsKey: 'gamesLibrary.games.boccia.instructions',
    emoji: '⚪',
    categories: ['family_games', 'outdoor_games'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 12 },
    duration: '30-60min',
    materials: ['Boccia-Kugeln'],
    tags: ['outdoor', 'precision', 'relaxed'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'tug_of_war',
    nameKey: 'gamesLibrary.games.tug_of_war.name',
    descriptionKey: 'gamesLibrary.games.tug_of_war.description',
    instructionsKey: 'gamesLibrary.games.tug_of_war.instructions',
    emoji: '🪢',
    categories: ['family_games', 'outdoor_games', 'team_games'],
    eventTypes: ['family', 'birthday', 'team'],
    difficulty: 'easy',
    groupSize: { min: 6, max: 30 },
    duration: '10-20min',
    materials: ['Seil', 'Markierung'],
    tags: ['strength', 'team', 'outdoor'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'relay_race',
    nameKey: 'gamesLibrary.games.relay_race.name',
    descriptionKey: 'gamesLibrary.games.relay_race.description',
    instructionsKey: 'gamesLibrary.games.relay_race.instructions',
    emoji: '🏃',
    categories: ['family_games', 'outdoor_games', 'team_games'],
    eventTypes: ['family', 'birthday', 'team'],
    difficulty: 'easy',
    groupSize: { min: 8, max: 40 },
    duration: '20-40min',
    materials: ['Staffelstab'],
    tags: ['running', 'team', 'outdoor'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'water_balloon',
    nameKey: 'gamesLibrary.games.water_balloon.name',
    descriptionKey: 'gamesLibrary.games.water_balloon.description',
    instructionsKey: 'gamesLibrary.games.water_balloon.instructions',
    emoji: '💧',
    categories: ['family_games', 'outdoor_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 30 },
    duration: '20-40min',
    materials: ['Wasserbomben'],
    tags: ['outdoor', 'summer', 'wet'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'cooking_together',
    nameKey: 'gamesLibrary.games.cooking_together.name',
    descriptionKey: 'gamesLibrary.games.cooking_together.description',
    instructionsKey: 'gamesLibrary.games.cooking_together.instructions',
    emoji: '👨‍🍳',
    categories: ['family_games', 'team_games'],
    eventTypes: ['family', 'team', 'birthday'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 16 },
    duration: '90-180min',
    materials: ['Küche', 'Zutaten'],
    tags: ['cooking', 'cooperative', 'creative'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'puzzle_race',
    nameKey: 'gamesLibrary.games.puzzle_race.name',
    descriptionKey: 'gamesLibrary.games.puzzle_race.description',
    instructionsKey: 'gamesLibrary.games.puzzle_race.instructions',
    emoji: '🧩',
    categories: ['family_games', 'team_games'],
    eventTypes: ['family', 'birthday', 'team'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 20 },
    duration: '30-60min',
    materials: ['Puzzles (gleiche Größe)'],
    tags: ['puzzle', 'competition', 'quiet'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'campfire_stories',
    nameKey: 'gamesLibrary.games.campfire_stories.name',
    descriptionKey: 'gamesLibrary.games.campfire_stories.description',
    instructionsKey: 'gamesLibrary.games.campfire_stories.instructions',
    emoji: '🔥',
    categories: ['family_games'],
    eventTypes: ['family', 'trip'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '30-90min',
    materials: ['Lagerfeuer'],
    tags: ['storytelling', 'evening', 'cozy'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'hide_and_seek',
    nameKey: 'gamesLibrary.games.hide_and_seek.name',
    descriptionKey: 'gamesLibrary.games.hide_and_seek.description',
    instructionsKey: 'gamesLibrary.games.hide_and_seek.instructions',
    emoji: '👀',
    categories: ['family_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 3, max: 15 },
    duration: '20-40min',
    materials: [],
    tags: ['classic', 'outdoor', 'active'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'tag',
    nameKey: 'gamesLibrary.games.tag.name',
    descriptionKey: 'gamesLibrary.games.tag.description',
    instructionsKey: 'gamesLibrary.games.tag.instructions',
    emoji: '🏃',
    categories: ['family_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '15-30min',
    materials: [],
    tags: ['running', 'classic', 'active'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'pot_hitting',
    nameKey: 'gamesLibrary.games.pot_hitting.name',
    descriptionKey: 'gamesLibrary.games.pot_hitting.description',
    instructionsKey: 'gamesLibrary.games.pot_hitting.instructions',
    emoji: '🥘',
    categories: ['family_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 15 },
    duration: '15-30min',
    materials: ['Topf', 'Kochlöffel', 'Augenbinde', 'Süßigkeiten'],
    tags: ['birthday', 'classic', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'telephone',
    nameKey: 'gamesLibrary.games.telephone.name',
    descriptionKey: 'gamesLibrary.games.telephone.description',
    instructionsKey: 'gamesLibrary.games.telephone.instructions',
    emoji: '🤫',
    categories: ['family_games', 'kids_friendly', 'icebreaker'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 6, max: 20 },
    duration: '10-20min',
    materials: [],
    tags: ['classic', 'funny', 'communication'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'musical_chairs',
    nameKey: 'gamesLibrary.games.musical_chairs.name',
    descriptionKey: 'gamesLibrary.games.musical_chairs.description',
    instructionsKey: 'gamesLibrary.games.musical_chairs.instructions',
    emoji: '🪑',
    categories: ['family_games', 'kids_friendly', 'party_games'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 5, max: 20 },
    duration: '15-30min',
    materials: ['Stühle', 'Musik'],
    tags: ['classic', 'music', 'competitive'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'chocolate_game',
    nameKey: 'gamesLibrary.games.chocolate_game.name',
    descriptionKey: 'gamesLibrary.games.chocolate_game.description',
    instructionsKey: 'gamesLibrary.games.chocolate_game.instructions',
    emoji: '🍫',
    categories: ['family_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 15 },
    duration: '15-30min',
    materials: ['Schokolade', 'Würfel', 'Messer', 'Gabel', 'Verkleidung'],
    tags: ['funny', 'eating', 'birthday'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'cotton_blowing',
    nameKey: 'gamesLibrary.games.cotton_blowing.name',
    descriptionKey: 'gamesLibrary.games.cotton_blowing.description',
    instructionsKey: 'gamesLibrary.games.cotton_blowing.instructions',
    emoji: '☁️',
    categories: ['family_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 10 },
    duration: '10-20min',
    materials: ['Wattebausch', 'Tisch'],
    tags: ['simple', 'fun', 'competition'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'mummy_wrap',
    nameKey: 'gamesLibrary.games.mummy_wrap.name',
    descriptionKey: 'gamesLibrary.games.mummy_wrap.description',
    instructionsKey: 'gamesLibrary.games.mummy_wrap.instructions',
    emoji: '🧻',
    categories: ['family_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '10-20min',
    materials: ['Toilettenpapier'],
    tags: ['funny', 'race', 'team'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'treasure_hunt',
    nameKey: 'gamesLibrary.games.treasure_hunt.name',
    descriptionKey: 'gamesLibrary.games.treasure_hunt.description',
    instructionsKey: 'gamesLibrary.games.treasure_hunt.instructions',
    emoji: '💎',
    categories: ['family_games', 'kids_friendly', 'outdoor_games'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 20 },
    duration: '30-90min',
    materials: ['Schatzkarte', 'Hinweise', 'Schatz'],
    tags: ['adventure', 'outdoor', 'exciting'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'mini_golf',
    nameKey: 'gamesLibrary.games.mini_golf.name',
    descriptionKey: 'gamesLibrary.games.mini_golf.description',
    instructionsKey: 'gamesLibrary.games.mini_golf.instructions',
    emoji: '⛳',
    categories: ['family_games', 'outdoor_games'],
    eventTypes: ['family', 'birthday', 'trip'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 10 },
    duration: '45-90min',
    materials: ['Minigolf-Anlage'],
    tags: ['sport', 'outdoor', 'all ages'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'bowling',
    nameKey: 'gamesLibrary.games.bowling.name',
    descriptionKey: 'gamesLibrary.games.bowling.description',
    instructionsKey: 'gamesLibrary.games.bowling.instructions',
    emoji: '🎳',
    categories: ['family_games'],
    eventTypes: ['family', 'birthday', 'team'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 8 },
    duration: '60-120min',
    materials: ['Bowlingbahn'],
    tags: ['sport', 'indoor', 'competition'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'frisbee',
    nameKey: 'gamesLibrary.games.frisbee.name',
    descriptionKey: 'gamesLibrary.games.frisbee.description',
    instructionsKey: 'gamesLibrary.games.frisbee.instructions',
    emoji: '🥏',
    categories: ['family_games', 'outdoor_games'],
    eventTypes: ['family', 'birthday', 'trip'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 20 },
    duration: '20-60min',
    materials: ['Frisbee'],
    tags: ['outdoor', 'active', 'casual'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'kite_flying',
    nameKey: 'gamesLibrary.games.kite_flying.name',
    descriptionKey: 'gamesLibrary.games.kite_flying.description',
    instructionsKey: 'gamesLibrary.games.kite_flying.instructions',
    emoji: '🪁',
    categories: ['family_games', 'outdoor_games', 'kids_friendly'],
    eventTypes: ['family'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 15 },
    duration: '30-90min',
    materials: ['Drachen'],
    tags: ['outdoor', 'windy', 'relaxing'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'bubble_contest',
    nameKey: 'gamesLibrary.games.bubble_contest.name',
    descriptionKey: 'gamesLibrary.games.bubble_contest.description',
    instructionsKey: 'gamesLibrary.games.bubble_contest.instructions',
    emoji: '🫧',
    categories: ['family_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 15 },
    duration: '15-30min',
    materials: ['Seifenblasen-Sets'],
    tags: ['outdoor', 'magical', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'photo_safari',
    nameKey: 'gamesLibrary.games.photo_safari.name',
    descriptionKey: 'gamesLibrary.games.photo_safari.description',
    instructionsKey: 'gamesLibrary.games.photo_safari.instructions',
    emoji: '📸',
    categories: ['family_games', 'outdoor_games'],
    eventTypes: ['family', 'trip'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 20 },
    duration: '60-180min',
    materials: ['Kameras/Smartphones', 'Themen-Liste'],
    tags: ['photo', 'nature', 'exploration'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'geocaching',
    nameKey: 'gamesLibrary.games.geocaching.name',
    descriptionKey: 'gamesLibrary.games.geocaching.description',
    instructionsKey: 'gamesLibrary.games.geocaching.instructions',
    emoji: '🗺️',
    categories: ['family_games', 'outdoor_games'],
    eventTypes: ['family', 'trip'],
    difficulty: 'medium',
    groupSize: { min: 2, max: 10 },
    duration: '60-180min',
    materials: ['Smartphone mit App', 'GPS'],
    tags: ['adventure', 'outdoor', 'technology'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'crafting',
    nameKey: 'gamesLibrary.games.crafting.name',
    descriptionKey: 'gamesLibrary.games.crafting.description',
    instructionsKey: 'gamesLibrary.games.crafting.instructions',
    emoji: '✂️',
    categories: ['family_games', 'kids_friendly'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 2, max: 15 },
    duration: '30-90min',
    materials: ['Bastelmaterial'],
    tags: ['creative', 'quiet', 'artistic'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'talent_show',
    nameKey: 'gamesLibrary.games.talent_show.name',
    descriptionKey: 'gamesLibrary.games.talent_show.description',
    instructionsKey: 'gamesLibrary.games.talent_show.instructions',
    emoji: '⭐',
    categories: ['family_games', 'party_games'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 30 },
    duration: '60-120min',
    materials: ['Bühne/Bereich'],
    tags: ['performance', 'talent', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'millionaire_family',
    nameKey: 'gamesLibrary.games.millionaire_family.name',
    descriptionKey: 'gamesLibrary.games.millionaire_family.description',
    instructionsKey: 'gamesLibrary.games.millionaire_family.instructions',
    emoji: '💰',
    categories: ['family_games'],
    eventTypes: ['family', 'birthday'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 20 },
    duration: '45-90min',
    materials: ['Fragen', 'Buzzer'],
    tags: ['quiz', 'tv show', 'knowledge'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'escape_room_family',
    nameKey: 'gamesLibrary.games.escape_room_family.name',
    descriptionKey: 'gamesLibrary.games.escape_room_family.description',
    instructionsKey: 'gamesLibrary.games.escape_room_family.instructions',
    emoji: '🔐',
    categories: ['family_games', 'team_games'],
    eventTypes: ['family', 'birthday', 'team'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 8 },
    duration: '60-90min',
    materials: ['Escape Room Set'],
    tags: ['puzzle', 'teamwork', 'exciting'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'treehouse_build',
    nameKey: 'gamesLibrary.games.treehouse_build.name',
    descriptionKey: 'gamesLibrary.games.treehouse_build.description',
    instructionsKey: 'gamesLibrary.games.treehouse_build.instructions',
    emoji: '🏠',
    categories: ['family_games', 'outdoor_games'],
    eventTypes: ['family'],
    difficulty: 'hard',
    groupSize: { min: 2, max: 8 },
    duration: '240min+',
    materials: ['Holz', 'Werkzeug', 'Baum'],
    tags: ['project', 'outdoor', 'building'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  }
];

// Wedding Games (35 games)
const weddingGames: GameItem[] = [
  {
    id: 'shoe_game',
    nameKey: 'gamesLibrary.games.shoe_game.name',
    descriptionKey: 'gamesLibrary.games.shoe_game.description',
    instructionsKey: 'gamesLibrary.games.shoe_game.instructions',
    emoji: '👠',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 2 },
    duration: '15-20min',
    materials: ['Stühle', 'Schuhe des Paares'],
    tags: ['classic', 'couple', 'funny'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'marriage_test',
    nameKey: 'gamesLibrary.games.marriage_test.name',
    descriptionKey: 'gamesLibrary.games.marriage_test.description',
    instructionsKey: 'gamesLibrary.games.marriage_test.instructions',
    emoji: '💍',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 2 },
    duration: '20-30min',
    materials: ['Fragen', 'Aufgaben'],
    tags: ['classic', 'funny', 'challenge'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'wedding_bingo',
    nameKey: 'gamesLibrary.games.wedding_bingo.name',
    descriptionKey: 'gamesLibrary.games.wedding_bingo.description',
    instructionsKey: 'gamesLibrary.games.wedding_bingo.instructions',
    emoji: '📋',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: 'während der Feier',
    materials: ['Bingo-Karten', 'Stifte'],
    tags: ['icebreaker', 'ongoing', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'balloon_dancing',
    nameKey: 'gamesLibrary.games.balloon_dancing.name',
    descriptionKey: 'gamesLibrary.games.balloon_dancing.description',
    instructionsKey: 'gamesLibrary.games.balloon_dancing.instructions',
    emoji: '🎈',
    categories: ['wedding_games', 'party_games'],
    eventTypes: ['wedding', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 6, max: 50 },
    duration: '10-20min',
    materials: ['Luftballons', 'Musik'],
    tags: ['dance', 'fun', 'competition'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'bouquet_toss',
    nameKey: 'gamesLibrary.games.bouquet_toss.name',
    descriptionKey: 'gamesLibrary.games.bouquet_toss.description',
    instructionsKey: 'gamesLibrary.games.bouquet_toss.instructions',
    emoji: '💐',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 3 },
    duration: '5-10min',
    materials: ['Brautstrauß'],
    tags: ['tradition', 'classic', 'exciting'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'garter_toss',
    nameKey: 'gamesLibrary.games.garter_toss.name',
    descriptionKey: 'gamesLibrary.games.garter_toss.description',
    instructionsKey: 'gamesLibrary.games.garter_toss.instructions',
    emoji: '👰',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 3 },
    duration: '5-10min',
    materials: ['Strumpfband'],
    tags: ['tradition', 'classic', 'men'],
    isKidsFriendly: false,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'newspaper_dance',
    nameKey: 'gamesLibrary.games.newspaper_dance.name',
    descriptionKey: 'gamesLibrary.games.newspaper_dance.description',
    instructionsKey: 'gamesLibrary.games.newspaper_dance.instructions',
    emoji: '📰',
    categories: ['wedding_games', 'party_games'],
    eventTypes: ['wedding', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 30 },
    duration: '15-25min',
    materials: ['Zeitungen', 'Musik'],
    tags: ['dance', 'couples', 'shrinking'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'kiss_marathon',
    nameKey: 'gamesLibrary.games.kiss_marathon.name',
    descriptionKey: 'gamesLibrary.games.kiss_marathon.description',
    instructionsKey: 'gamesLibrary.games.kiss_marathon.instructions',
    emoji: '💋',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 2 },
    duration: '5-15min',
    materials: ['Timer'],
    tags: ['romantic', 'couple', 'sweet'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'wedding_abc',
    nameKey: 'gamesLibrary.games.wedding_abc.name',
    descriptionKey: 'gamesLibrary.games.wedding_abc.description',
    instructionsKey: 'gamesLibrary.games.wedding_abc.instructions',
    emoji: '🔤',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: '30-60min',
    materials: ['Papier', 'Stifte'],
    tags: ['creative', 'keepsake', 'group'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'guest_lottery',
    nameKey: 'gamesLibrary.games.guest_lottery.name',
    descriptionKey: 'gamesLibrary.games.guest_lottery.description',
    instructionsKey: 'gamesLibrary.games.guest_lottery.instructions',
    emoji: '🎟️',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 20 },
    duration: '15-30min',
    materials: ['Lose', 'Preise'],
    tags: ['prizes', 'excitement', 'luck'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'polaroid_guestbook',
    nameKey: 'gamesLibrary.games.polaroid_guestbook.name',
    descriptionKey: 'gamesLibrary.games.polaroid_guestbook.description',
    instructionsKey: 'gamesLibrary.games.polaroid_guestbook.instructions',
    emoji: '📷',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: 'während der Feier',
    materials: ['Polaroid-Kamera', 'Gästebuch', 'Stifte'],
    tags: ['keepsake', 'photo', 'memories'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'wish_tree',
    nameKey: 'gamesLibrary.games.wish_tree.name',
    descriptionKey: 'gamesLibrary.games.wish_tree.description',
    instructionsKey: 'gamesLibrary.games.wish_tree.instructions',
    emoji: '🌳',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: 'während der Feier',
    materials: ['Dekobaum', 'Karten', 'Stifte', 'Bänder'],
    tags: ['wishes', 'keepsake', 'decorative'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'date_night_jar',
    nameKey: 'gamesLibrary.games.date_night_jar.name',
    descriptionKey: 'gamesLibrary.games.date_night_jar.description',
    instructionsKey: 'gamesLibrary.games.date_night_jar.instructions',
    emoji: '🫙',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: 'während der Feier',
    materials: ['Glas', 'Karten', 'Stifte'],
    tags: ['ideas', 'future', 'keepsake'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'advice_cards',
    nameKey: 'gamesLibrary.games.advice_cards.name',
    descriptionKey: 'gamesLibrary.games.advice_cards.description',
    instructionsKey: 'gamesLibrary.games.advice_cards.instructions',
    emoji: '💌',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: 'während der Feier',
    materials: ['Karten', 'Stifte', 'Box'],
    tags: ['advice', 'keepsake', 'heartfelt'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'couple_quiz',
    nameKey: 'gamesLibrary.games.couple_quiz.name',
    descriptionKey: 'gamesLibrary.games.couple_quiz.description',
    instructionsKey: 'gamesLibrary.games.couple_quiz.instructions',
    emoji: '📝',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: '20-30min',
    materials: ['Fragebogen', 'Stifte'],
    tags: ['quiz', 'fun', 'interactive'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'wedding_limbo',
    nameKey: 'gamesLibrary.games.wedding_limbo.name',
    descriptionKey: 'gamesLibrary.games.wedding_limbo.description',
    instructionsKey: 'gamesLibrary.games.wedding_limbo.instructions',
    emoji: '🕺',
    categories: ['wedding_games', 'party_games'],
    eventTypes: ['wedding', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 5, max: 50 },
    duration: '15-30min',
    materials: ['Limbo-Stange', 'Musik'],
    tags: ['dance', 'fun', 'party'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'musical_chairs_wedding',
    nameKey: 'gamesLibrary.games.musical_chairs_wedding.name',
    descriptionKey: 'gamesLibrary.games.musical_chairs_wedding.description',
    instructionsKey: 'gamesLibrary.games.musical_chairs_wedding.instructions',
    emoji: '🪑',
    categories: ['wedding_games', 'party_games'],
    eventTypes: ['wedding', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 6, max: 20 },
    duration: '15-25min',
    materials: ['Stühle', 'Musik'],
    tags: ['classic', 'fun', 'music'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'conga_line',
    nameKey: 'gamesLibrary.games.conga_line.name',
    descriptionKey: 'gamesLibrary.games.conga_line.description',
    instructionsKey: 'gamesLibrary.games.conga_line.instructions',
    emoji: '🐍',
    categories: ['wedding_games', 'party_games'],
    eventTypes: ['wedding', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: '5-15min',
    materials: ['Musik'],
    tags: ['dance', 'group', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'wedding_karaoke',
    nameKey: 'gamesLibrary.games.wedding_karaoke.name',
    descriptionKey: 'gamesLibrary.games.wedding_karaoke.description',
    instructionsKey: 'gamesLibrary.games.wedding_karaoke.instructions',
    emoji: '🎤',
    categories: ['wedding_games', 'party_games'],
    eventTypes: ['wedding', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 5 },
    duration: '60-120min',
    materials: ['Karaoke-Anlage'],
    tags: ['singing', 'party', 'entertainment'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'first_dance_game',
    nameKey: 'gamesLibrary.games.first_dance_game.name',
    descriptionKey: 'gamesLibrary.games.first_dance_game.description',
    instructionsKey: 'gamesLibrary.games.first_dance_game.instructions',
    emoji: '💃',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'medium',
    groupSize: { min: 2 },
    duration: '5-10min',
    materials: ['Musik'],
    tags: ['dance', 'couple', 'surprise'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'mr_mrs_quiz',
    nameKey: 'gamesLibrary.games.mr_mrs_quiz.name',
    descriptionKey: 'gamesLibrary.games.mr_mrs_quiz.description',
    instructionsKey: 'gamesLibrary.games.mr_mrs_quiz.instructions',
    emoji: '🤵👰',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 2 },
    duration: '15-25min',
    materials: ['Fragen', 'Paddle/Schilder'],
    tags: ['quiz', 'couple', 'funny'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'wedding_photo_challenge',
    nameKey: 'gamesLibrary.games.wedding_photo_challenge.name',
    descriptionKey: 'gamesLibrary.games.wedding_photo_challenge.description',
    instructionsKey: 'gamesLibrary.games.wedding_photo_challenge.instructions',
    emoji: '📸',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: 'während der Feier',
    materials: ['Foto-Aufgaben', 'Smartphones'],
    tags: ['photo', 'interactive', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'guest_interview',
    nameKey: 'gamesLibrary.games.guest_interview.name',
    descriptionKey: 'gamesLibrary.games.guest_interview.description',
    instructionsKey: 'gamesLibrary.games.guest_interview.instructions',
    emoji: '🎙️',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 20 },
    duration: '30-60min',
    materials: ['Mikrofon', 'Kamera'],
    tags: ['video', 'memories', 'interactive'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'love_story_reading',
    nameKey: 'gamesLibrary.games.love_story_reading.name',
    descriptionKey: 'gamesLibrary.games.love_story_reading.description',
    instructionsKey: 'gamesLibrary.games.love_story_reading.instructions',
    emoji: '📖',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: '10-20min',
    materials: ['Geschichte'],
    tags: ['romantic', 'story', 'touching'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'wedding_tombola',
    nameKey: 'gamesLibrary.games.wedding_tombola.name',
    descriptionKey: 'gamesLibrary.games.wedding_tombola.description',
    instructionsKey: 'gamesLibrary.games.wedding_tombola.instructions',
    emoji: '🎁',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 20 },
    duration: '20-40min',
    materials: ['Lose', 'Preise', 'Trommel'],
    tags: ['prizes', 'excitement', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'ring_warming',
    nameKey: 'gamesLibrary.games.ring_warming.name',
    descriptionKey: 'gamesLibrary.games.ring_warming.description',
    instructionsKey: 'gamesLibrary.games.ring_warming.instructions',
    emoji: '💍',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: 'während Zeremonie',
    materials: ['Ringe', 'Band'],
    tags: ['ceremony', 'meaningful', 'blessing'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'anniversary_dance',
    nameKey: 'gamesLibrary.games.anniversary_dance.name',
    descriptionKey: 'gamesLibrary.games.anniversary_dance.description',
    instructionsKey: 'gamesLibrary.games.anniversary_dance.instructions',
    emoji: '💑',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: '10-15min',
    materials: ['Musik'],
    tags: ['dance', 'touching', 'couples'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'bride_stealing',
    nameKey: 'gamesLibrary.games.bride_stealing.name',
    descriptionKey: 'gamesLibrary.games.bride_stealing.description',
    instructionsKey: 'gamesLibrary.games.bride_stealing.instructions',
    emoji: '🏃‍♀️',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'medium',
    groupSize: { min: 10 },
    duration: '30-60min',
    materials: [],
    tags: ['tradition', 'fun', 'german'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'bridal_shoe_hiding',
    nameKey: 'gamesLibrary.games.bridal_shoe_hiding.name',
    descriptionKey: 'gamesLibrary.games.bridal_shoe_hiding.description',
    instructionsKey: 'gamesLibrary.games.bridal_shoe_hiding.instructions',
    emoji: '👟',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 5 },
    duration: '15-30min',
    materials: ['Brautschuh'],
    tags: ['tradition', 'fun', 'ransom'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'piggy_bank_game',
    nameKey: 'gamesLibrary.games.piggy_bank_game.name',
    descriptionKey: 'gamesLibrary.games.piggy_bank_game.description',
    instructionsKey: 'gamesLibrary.games.piggy_bank_game.instructions',
    emoji: '🐷',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 10 },
    duration: '15-30min',
    materials: ['Spardosen', 'Schilder'],
    tags: ['money', 'fun', 'interactive'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'wedding_bet',
    nameKey: 'gamesLibrary.games.wedding_bet.name',
    descriptionKey: 'gamesLibrary.games.wedding_bet.description',
    instructionsKey: 'gamesLibrary.games.wedding_bet.instructions',
    emoji: '🎲',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'medium',
    groupSize: { min: 10 },
    duration: '20-40min',
    materials: ['Wetten', 'Aufgaben'],
    tags: ['betting', 'challenge', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'song_request_cards',
    nameKey: 'gamesLibrary.games.song_request_cards.name',
    descriptionKey: 'gamesLibrary.games.song_request_cards.description',
    instructionsKey: 'gamesLibrary.games.song_request_cards.instructions',
    emoji: '🎵',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 20 },
    duration: 'während der Feier',
    materials: ['Karten', 'Stifte', 'Box'],
    tags: ['music', 'interactive', 'party'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'wedding_time_capsule',
    nameKey: 'gamesLibrary.games.wedding_time_capsule.name',
    descriptionKey: 'gamesLibrary.games.wedding_time_capsule.description',
    instructionsKey: 'gamesLibrary.games.wedding_time_capsule.instructions',
    emoji: '📦',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 2 },
    duration: '30-60min',
    materials: ['Behälter', 'Erinnerungsstücke'],
    tags: ['keepsake', 'meaningful', 'future'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'congratulation_line',
    nameKey: 'gamesLibrary.games.congratulation_line.name',
    descriptionKey: 'gamesLibrary.games.congratulation_line.description',
    instructionsKey: 'gamesLibrary.games.congratulation_line.instructions',
    emoji: '🐍',
    categories: ['wedding_games'],
    eventTypes: ['wedding'],
    difficulty: 'easy',
    groupSize: { min: 20 },
    duration: '20-40min',
    materials: [],
    tags: ['tradition', 'greeting', 'organized'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  }
];

// Icebreaker Games (20 games)
const icebreakerGames: GameItem[] = [
  {
    id: 'two_truths_lie',
    nameKey: 'gamesLibrary.games.two_truths_lie.name',
    descriptionKey: 'gamesLibrary.games.two_truths_lie.description',
    instructionsKey: 'gamesLibrary.games.two_truths_lie.instructions',
    emoji: '🤥',
    categories: ['icebreaker'],
    eventTypes: ['team', 'family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '15-30min',
    materials: [],
    tags: ['getting to know', 'fun', 'guessing'],
    isKidsFriendly: true,
    isAlcoholRelated: false,
    isClassic: true
  },
  {
    id: 'speed_meeting',
    nameKey: 'gamesLibrary.games.speed_meeting.name',
    descriptionKey: 'gamesLibrary.games.speed_meeting.description',
    instructionsKey: 'gamesLibrary.games.speed_meeting.instructions',
    emoji: '⚡',
    categories: ['icebreaker', 'team_games'],
    eventTypes: ['team', 'wedding'],
    difficulty: 'easy',
    groupSize: { min: 8, max: 30 },
    duration: '20-40min',
    materials: ['Timer', 'Stühle'],
    tags: ['networking', 'fast-paced', 'social'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'human_bingo',
    nameKey: 'gamesLibrary.games.human_bingo.name',
    descriptionKey: 'gamesLibrary.games.human_bingo.description',
    instructionsKey: 'gamesLibrary.games.human_bingo.instructions',
    emoji: '📋',
    categories: ['icebreaker', 'team_games'],
    eventTypes: ['team', 'wedding', 'family'],
    difficulty: 'easy',
    groupSize: { min: 10, max: 50 },
    duration: '20-40min',
    materials: ['Bingo-Karten', 'Stifte'],
    tags: ['networking', 'fun', 'social'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'find_someone_who',
    nameKey: 'gamesLibrary.games.find_someone_who.name',
    descriptionKey: 'gamesLibrary.games.find_someone_who.description',
    instructionsKey: 'gamesLibrary.games.find_someone_who.instructions',
    emoji: '🔍',
    categories: ['icebreaker'],
    eventTypes: ['team', 'wedding', 'family'],
    difficulty: 'easy',
    groupSize: { min: 10, max: 50 },
    duration: '15-30min',
    materials: ['Listen', 'Stifte'],
    tags: ['networking', 'active', 'social'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'common_ground',
    nameKey: 'gamesLibrary.games.common_ground.name',
    descriptionKey: 'gamesLibrary.games.common_ground.description',
    instructionsKey: 'gamesLibrary.games.common_ground.instructions',
    emoji: '🤝',
    categories: ['icebreaker', 'team_games'],
    eventTypes: ['team', 'family'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 30 },
    duration: '15-25min',
    materials: ['Papier', 'Stifte'],
    tags: ['bonding', 'discussion', 'team'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'story_cubes',
    nameKey: 'gamesLibrary.games.story_cubes.name',
    descriptionKey: 'gamesLibrary.games.story_cubes.description',
    instructionsKey: 'gamesLibrary.games.story_cubes.instructions',
    emoji: '🎲',
    categories: ['icebreaker', 'family_games'],
    eventTypes: ['team', 'family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 3, max: 12 },
    duration: '15-30min',
    materials: ['Story Cubes'],
    tags: ['storytelling', 'creative', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'name_ball',
    nameKey: 'gamesLibrary.games.name_ball.name',
    descriptionKey: 'gamesLibrary.games.name_ball.description',
    instructionsKey: 'gamesLibrary.games.name_ball.instructions',
    emoji: '🏐',
    categories: ['icebreaker'],
    eventTypes: ['team', 'family'],
    difficulty: 'easy',
    groupSize: { min: 6, max: 30 },
    duration: '10-20min',
    materials: ['Ball'],
    tags: ['names', 'active', 'simple'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'word_association',
    nameKey: 'gamesLibrary.games.word_association.name',
    descriptionKey: 'gamesLibrary.games.word_association.description',
    instructionsKey: 'gamesLibrary.games.word_association.instructions',
    emoji: '💭',
    categories: ['icebreaker', 'party_games'],
    eventTypes: ['team', 'family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '10-20min',
    materials: [],
    tags: ['quick', 'fun', 'words'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'personality_quiz',
    nameKey: 'gamesLibrary.games.personality_quiz.name',
    descriptionKey: 'gamesLibrary.games.personality_quiz.description',
    instructionsKey: 'gamesLibrary.games.personality_quiz.instructions',
    emoji: '🧬',
    categories: ['icebreaker'],
    eventTypes: ['team', 'family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 30 },
    duration: '20-40min',
    materials: ['Fragebogen'],
    tags: ['personality', 'discussion', 'insight'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'desert_island',
    nameKey: 'gamesLibrary.games.desert_island.name',
    descriptionKey: 'gamesLibrary.games.desert_island.description',
    instructionsKey: 'gamesLibrary.games.desert_island.instructions',
    emoji: '🏝️',
    categories: ['icebreaker'],
    eventTypes: ['team', 'family'],
    difficulty: 'easy',
    groupSize: { min: 3, max: 20 },
    duration: '15-30min',
    materials: [],
    tags: ['discussion', 'hypothetical', 'revealing'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'would_you_rather',
    nameKey: 'gamesLibrary.games.would_you_rather.name',
    descriptionKey: 'gamesLibrary.games.would_you_rather.description',
    instructionsKey: 'gamesLibrary.games.would_you_rather.instructions',
    emoji: '🤔',
    categories: ['icebreaker', 'party_games'],
    eventTypes: ['team', 'family', 'birthday', 'bachelor', 'bachelorette'],
    difficulty: 'easy',
    groupSize: { min: 3, max: 20 },
    duration: '15-30min',
    materials: ['Fragen'],
    tags: ['choices', 'discussion', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'rose_bud_thorn',
    nameKey: 'gamesLibrary.games.rose_bud_thorn.name',
    descriptionKey: 'gamesLibrary.games.rose_bud_thorn.description',
    instructionsKey: 'gamesLibrary.games.rose_bud_thorn.instructions',
    emoji: '🌹',
    categories: ['icebreaker', 'team_games'],
    eventTypes: ['team', 'family'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '15-30min',
    materials: [],
    tags: ['reflection', 'sharing', 'meaningful'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'hot_seat',
    nameKey: 'gamesLibrary.games.hot_seat.name',
    descriptionKey: 'gamesLibrary.games.hot_seat.description',
    instructionsKey: 'gamesLibrary.games.hot_seat.instructions',
    emoji: '🔥',
    categories: ['icebreaker'],
    eventTypes: ['team', 'bachelor', 'bachelorette'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 15 },
    duration: '20-40min',
    materials: ['Stuhl'],
    tags: ['questions', 'spotlight', 'revealing'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'one_word_story',
    nameKey: 'gamesLibrary.games.one_word_story.name',
    descriptionKey: 'gamesLibrary.games.one_word_story.description',
    instructionsKey: 'gamesLibrary.games.one_word_story.instructions',
    emoji: '📖',
    categories: ['icebreaker', 'family_games'],
    eventTypes: ['team', 'family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 15 },
    duration: '10-20min',
    materials: [],
    tags: ['creative', 'cooperative', 'funny'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'human_knot',
    nameKey: 'gamesLibrary.games.human_knot.name',
    descriptionKey: 'gamesLibrary.games.human_knot.description',
    instructionsKey: 'gamesLibrary.games.human_knot.instructions',
    emoji: '🧶',
    categories: ['icebreaker', 'team_games'],
    eventTypes: ['team'],
    difficulty: 'medium',
    groupSize: { min: 6, max: 15 },
    duration: '10-20min',
    materials: [],
    tags: ['physical', 'teamwork', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'alphabet_introduction',
    nameKey: 'gamesLibrary.games.alphabet_introduction.name',
    descriptionKey: 'gamesLibrary.games.alphabet_introduction.description',
    instructionsKey: 'gamesLibrary.games.alphabet_introduction.instructions',
    emoji: '🔤',
    categories: ['icebreaker'],
    eventTypes: ['team', 'family'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 26 },
    duration: '15-25min',
    materials: [],
    tags: ['names', 'creative', 'memory'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'interview_pairs',
    nameKey: 'gamesLibrary.games.interview_pairs.name',
    descriptionKey: 'gamesLibrary.games.interview_pairs.description',
    instructionsKey: 'gamesLibrary.games.interview_pairs.instructions',
    emoji: '👥',
    categories: ['icebreaker', 'team_games'],
    eventTypes: ['team', 'wedding'],
    difficulty: 'easy',
    groupSize: { min: 6, max: 30 },
    duration: '20-40min',
    materials: [],
    tags: ['pairs', 'introduction', 'social'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'favorites_lineup',
    nameKey: 'gamesLibrary.games.favorites_lineup.name',
    descriptionKey: 'gamesLibrary.games.favorites_lineup.description',
    instructionsKey: 'gamesLibrary.games.favorites_lineup.instructions',
    emoji: '📊',
    categories: ['icebreaker'],
    eventTypes: ['team', 'family'],
    difficulty: 'easy',
    groupSize: { min: 6, max: 30 },
    duration: '10-20min',
    materials: [],
    tags: ['active', 'opinions', 'movement'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'emoji_introduction',
    nameKey: 'gamesLibrary.games.emoji_introduction.name',
    descriptionKey: 'gamesLibrary.games.emoji_introduction.description',
    instructionsKey: 'gamesLibrary.games.emoji_introduction.instructions',
    emoji: '😊',
    categories: ['icebreaker'],
    eventTypes: ['team', 'family', 'birthday'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '10-20min',
    materials: ['Smartphone/Papier'],
    tags: ['modern', 'creative', 'fun'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'show_and_tell',
    nameKey: 'gamesLibrary.games.show_and_tell.name',
    descriptionKey: 'gamesLibrary.games.show_and_tell.description',
    instructionsKey: 'gamesLibrary.games.show_and_tell.instructions',
    emoji: '🎒',
    categories: ['icebreaker', 'family_games'],
    eventTypes: ['team', 'family'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '20-40min',
    materials: ['Persönlicher Gegenstand'],
    tags: ['sharing', 'personal', 'meaningful'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  }
];

// Team Games (additional)
const teamGames: GameItem[] = [
  {
    id: 'trust_fall',
    nameKey: 'gamesLibrary.games.trust_fall.name',
    descriptionKey: 'gamesLibrary.games.trust_fall.description',
    instructionsKey: 'gamesLibrary.games.trust_fall.instructions',
    emoji: '🤲',
    categories: ['team_games'],
    eventTypes: ['team'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 20 },
    duration: '15-30min',
    materials: [],
    tags: ['trust', 'team building', 'physical'],
    isKidsFriendly: false,
    isAlcoholRelated: false
  },
  {
    id: 'blind_drawing',
    nameKey: 'gamesLibrary.games.blind_drawing.name',
    descriptionKey: 'gamesLibrary.games.blind_drawing.description',
    instructionsKey: 'gamesLibrary.games.blind_drawing.instructions',
    emoji: '👁️',
    categories: ['team_games'],
    eventTypes: ['team', 'family'],
    difficulty: 'easy',
    groupSize: { min: 4, max: 20 },
    duration: '15-30min',
    materials: ['Papier', 'Stifte', 'Augenbinden'],
    tags: ['communication', 'funny', 'pairs'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'marshmallow_challenge',
    nameKey: 'gamesLibrary.games.marshmallow_challenge.name',
    descriptionKey: 'gamesLibrary.games.marshmallow_challenge.description',
    instructionsKey: 'gamesLibrary.games.marshmallow_challenge.instructions',
    emoji: '🍡',
    categories: ['team_games'],
    eventTypes: ['team'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 24 },
    duration: '18-25min',
    materials: ['Spaghetti', 'Marshmallows', 'Klebeband', 'Schnur'],
    tags: ['building', 'creative', 'competition'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'egg_drop',
    nameKey: 'gamesLibrary.games.egg_drop.name',
    descriptionKey: 'gamesLibrary.games.egg_drop.description',
    instructionsKey: 'gamesLibrary.games.egg_drop.instructions',
    emoji: '🥚',
    categories: ['team_games'],
    eventTypes: ['team'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 24 },
    duration: '30-60min',
    materials: ['Eier', 'Bastelmaterial'],
    tags: ['engineering', 'creative', 'messy'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  },
  {
    id: 'minefield',
    nameKey: 'gamesLibrary.games.minefield.name',
    descriptionKey: 'gamesLibrary.games.minefield.description',
    instructionsKey: 'gamesLibrary.games.minefield.instructions',
    emoji: '💣',
    categories: ['team_games'],
    eventTypes: ['team'],
    difficulty: 'medium',
    groupSize: { min: 4, max: 20 },
    duration: '20-30min',
    materials: ['Hindernisse', 'Augenbinden'],
    tags: ['trust', 'communication', 'guidance'],
    isKidsFriendly: true,
    isAlcoholRelated: false
  }
];

// Export all games combined
export const gamesLibrary: GameItem[] = [
  ...jgaGames,
  ...familyGames,
  ...weddingGames,
  ...icebreakerGames,
  ...teamGames
];

// Helper functions
export const getGamesByCategory = (category: GameCategory): GameItem[] => {
  return gamesLibrary.filter(game => game.categories.includes(category));
};

export const getGamesByEventType = (eventType: EventType): GameItem[] => {
  return gamesLibrary.filter(game => game.eventTypes.includes(eventType));
};

export const getKidsFriendlyGames = (): GameItem[] => {
  return gamesLibrary.filter(game => game.isKidsFriendly);
};

export const getAlcoholFreeGames = (): GameItem[] => {
  return gamesLibrary.filter(game => !game.isAlcoholRelated);
};

export const getGamesByDifficulty = (difficulty: Difficulty): GameItem[] => {
  return gamesLibrary.filter(game => game.difficulty === difficulty);
};

export const getClassicGames = (): GameItem[] => {
  return gamesLibrary.filter(game => game.isClassic);
};

export const searchGames = (query: string): GameItem[] => {
  const lowerQuery = query.toLowerCase();
  return gamesLibrary.filter(game => 
    game.id.includes(lowerQuery) ||
    game.tags.some(tag => tag.includes(lowerQuery))
  );
};

export const getGameById = (id: string): GameItem | undefined => {
  return gamesLibrary.find(game => game.id === id);
};

export const getRandomGame = (filters?: {
  category?: GameCategory;
  eventType?: EventType;
  kidsFriendly?: boolean;
  alcoholFree?: boolean;
}): GameItem | undefined => {
  let filteredGames = [...gamesLibrary];
  
  if (filters?.category) {
    filteredGames = filteredGames.filter(g => g.categories.includes(filters.category!));
  }
  if (filters?.eventType) {
    filteredGames = filteredGames.filter(g => g.eventTypes.includes(filters.eventType!));
  }
  if (filters?.kidsFriendly) {
    filteredGames = filteredGames.filter(g => g.isKidsFriendly);
  }
  if (filters?.alcoholFree) {
    filteredGames = filteredGames.filter(g => !g.isAlcoholRelated);
  }
  
  if (filteredGames.length === 0) return undefined;
  
  return filteredGames[Math.floor(Math.random() * filteredGames.length)];
};
