import { ThisOrThatPair } from './thisorthat-content-de';

export const THISORTHAT_PAIRS_PT: ThisOrThatPair[] = [
  // Comida (35)
  { optionA: 'Pizza', optionB: 'Hamburguer', category: 'Comida' },
  { optionA: 'Chocolate', optionB: 'Jujuba', category: 'Comida' },
  { optionA: 'Cafe', optionB: 'Cha', category: 'Comida' },
  { optionA: 'Sushi', optionB: 'Bife', category: 'Comida' },
  { optionA: 'Sorvete', optionB: 'Bolo', category: 'Comida' },
  { optionA: 'Cafe da manha', optionB: 'Jantar', category: 'Comida' },
  { optionA: 'Doce', optionB: 'Salgado', category: 'Comida' },
  { optionA: 'Cozinhar', optionB: 'Pedir delivery', category: 'Comida' },
  { optionA: 'Macarrao', optionB: 'Arroz', category: 'Comida' },
  { optionA: 'Batata frita', optionB: 'Salgadinho', category: 'Comida' },
  { optionA: 'Feijoada', optionB: 'Churrasco', category: 'Comida' },
  { optionA: 'Agua', optionB: 'Refrigerante', category: 'Comida' },
  { optionA: 'Panqueca', optionB: 'Waffle', category: 'Comida' },
  { optionA: 'Pasta de amendoim', optionB: 'Nutella', category: 'Comida' },
  { optionA: 'Maca', optionB: 'Banana', category: 'Comida' },
  { optionA: 'Leite', optionB: 'Leite de aveia', category: 'Comida' },
  { optionA: 'Salada', optionB: 'Sopa', category: 'Comida' },
  { optionA: 'Queijo', optionB: 'Presunto', category: 'Comida' },
  { optionA: 'Churrasco', optionB: 'Fondue', category: 'Comida' },
  { optionA: 'Pipoca', optionB: 'Nachos', category: 'Comida' },
  { optionA: 'Pao de queijo', optionB: 'Croissant', category: 'Comida' },
  { optionA: 'Cerveja', optionB: 'Vinho', category: 'Comida' },
  { optionA: 'Barra de cereal', optionB: 'Barra de chocolate', category: 'Comida' },
  { optionA: 'Pizza congelada', optionB: 'Pizza delivery', category: 'Comida' },
  { optionA: 'Croissant', optionB: 'Rosquinha', category: 'Comida' },
  { optionA: 'Cafe da manha na cama', optionB: 'Cafe da manha na mesa', category: 'Comida' },
  { optionA: 'Comida picante', optionB: 'Comida suave', category: 'Comida' },
  { optionA: 'Comida caseira', optionB: 'Restaurante', category: 'Comida' },
  { optionA: 'Pao integral', optionB: 'Pao branco', category: 'Comida' },
  { optionA: 'Smoothie', optionB: 'Suco natural', category: 'Comida' },
  { optionA: 'Brunch', optionB: 'Lanche da madrugada', category: 'Comida' },
  { optionA: 'Comida asiatica', optionB: 'Comida italiana', category: 'Comida' },
  { optionA: 'Curry', optionB: 'Macarrao', category: 'Comida' },
  { optionA: 'Vegetariano', optionB: 'Amante de carne', category: 'Comida' },
  { optionA: 'Acai', optionB: 'Brigadeiro', category: 'Comida' },
  // Viagem (35)
  { optionA: 'Praia', optionB: 'Montanha', category: 'Viagem' },
  { optionA: 'Aviao', optionB: 'Viagem de carro', category: 'Viagem' },
  { optionA: 'Hotel', optionB: 'Camping', category: 'Viagem' },
  { optionA: 'Verao', optionB: 'Inverno', category: 'Viagem' },
  { optionA: 'Europa', optionB: 'Asia', category: 'Viagem' },
  { optionA: 'Viagem urbana', optionB: 'Ferias na natureza', category: 'Viagem' },
  { optionA: 'Viajar sozinho', optionB: 'Viagem em grupo', category: 'Viagem' },
  { optionA: 'Acordar cedo', optionB: 'Dormir ate tarde', category: 'Viagem' },
  { optionA: 'Mochilao', optionB: 'All-inclusive', category: 'Viagem' },
  { optionA: 'Cruzeiro', optionB: 'Safari', category: 'Viagem' },
  { optionA: 'Nova York', optionB: 'Toquio', category: 'Viagem' },
  { optionA: 'Deserto', optionB: 'Floresta tropical', category: 'Viagem' },
  { optionA: 'Trem', optionB: 'Navio', category: 'Viagem' },
  { optionA: 'Aventura', optionB: 'Relaxamento', category: 'Viagem' },
  { optionA: 'Espanha', optionB: 'Italia', category: 'Viagem' },
  { optionA: 'Ferias de ski', optionB: 'Ferias de surf', category: 'Viagem' },
  { optionA: 'Primavera', optionB: 'Outono', category: 'Viagem' },
  { optionA: 'Aurora boreal', optionB: 'Por do sol na praia', category: 'Viagem' },
  { optionA: 'Parque de diversoes', optionB: 'Spa', category: 'Viagem' },
  { optionA: 'Hostel', optionB: 'Airbnb', category: 'Viagem' },
  { optionA: 'Mala', optionB: 'Mochila', category: 'Viagem' },
  { optionA: 'Janela', optionB: 'Corredor', category: 'Viagem' },
  { optionA: 'Reservar cedo', optionB: 'Ultima hora', category: 'Viagem' },
  { optionA: 'Mergulho', optionB: 'Trilha', category: 'Viagem' },
  { optionA: 'Veneza', optionB: 'Paris', category: 'Viagem' },
  { optionA: 'Bar de praia', optionB: 'Chale na montanha', category: 'Viagem' },
  { optionA: 'Nascer do sol', optionB: 'Por do sol', category: 'Viagem' },
  { optionA: 'Dica secreta', optionB: 'Ponto turistico', category: 'Viagem' },
  { optionA: 'Motorhome', optionB: 'Hotel de luxo', category: 'Viagem' },
  { optionA: 'Aventura na selva', optionB: 'Safari no deserto', category: 'Viagem' },
  { optionA: 'Caribe', optionB: 'Escandinavia', category: 'Viagem' },
  { optionA: 'Trem noturno', optionB: 'Voo noturno', category: 'Viagem' },
  { optionA: 'Viagem cultural', optionB: 'Viagem de festa', category: 'Viagem' },
  { optionA: 'Islandia', optionB: 'Havai', category: 'Viagem' },
  // Estilo de vida (40)
  { optionA: 'Netflix', optionB: 'YouTube', category: 'Estilo de vida' },
  { optionA: 'Matutino', optionB: 'Noturno', category: 'Estilo de vida' },
  { optionA: 'Cachorro', optionB: 'Gato', category: 'Estilo de vida' },
  { optionA: 'iPhone', optionB: 'Android', category: 'Estilo de vida' },
  { optionA: 'Instagram', optionB: 'TikTok', category: 'Estilo de vida' },
  { optionA: 'Ler um livro', optionB: 'Ouvir podcast', category: 'Estilo de vida' },
  { optionA: 'Academia', optionB: 'Corrida', category: 'Estilo de vida' },
  { optionA: 'Cidade', optionB: 'Interior', category: 'Estilo de vida' },
  { optionA: 'Dinheiro', optionB: 'Cartao', category: 'Estilo de vida' },
  { optionA: 'Dormir cedo', optionB: 'Coruja noturna', category: 'Estilo de vida' },
  { optionA: 'Compras online', optionB: 'Compras na loja', category: 'Estilo de vida' },
  { optionA: 'Ouvir musica', optionB: 'Assistir series', category: 'Estilo de vida' },
  { optionA: 'Banheira', optionB: 'Chuveiro', category: 'Estilo de vida' },
  { optionA: 'Tenis', optionB: 'Sapato social', category: 'Estilo de vida' },
  { optionA: 'Minimalista', optionB: 'Colecionador', category: 'Estilo de vida' },
  { optionA: 'Extrovertido', optionB: 'Introvertido', category: 'Estilo de vida' },
  { optionA: 'Planejar', optionB: 'Ser espontaneo', category: 'Estilo de vida' },
  { optionA: 'Videogame', optionB: 'Jogo de tabuleiro', category: 'Estilo de vida' },
  { optionA: 'Festival', optionB: 'Show', category: 'Estilo de vida' },
  { optionA: 'Republica', optionB: 'Morar sozinho', category: 'Estilo de vida' },
  { optionA: 'Aprender a cozinhar', optionB: 'Aprender um instrumento', category: 'Estilo de vida' },
  { optionA: 'Tatuagem', optionB: 'Piercing', category: 'Estilo de vida' },
  { optionA: 'Home office', optionB: 'Escritorio', category: 'Estilo de vida' },
  { optionA: 'Spotify', optionB: 'Apple Music', category: 'Estilo de vida' },
  { optionA: 'Praticar esporte', optionB: 'Assistir esporte', category: 'Estilo de vida' },
  { optionA: 'Carro eletrico', optionB: 'Carro classico', category: 'Estilo de vida' },
  { optionA: 'Cinema', optionB: 'Teatro', category: 'Estilo de vida' },
  { optionA: 'Livro', optionB: 'Audiolivro', category: 'Estilo de vida' },
  { optionA: 'Yoga', optionB: 'Crossfit', category: 'Estilo de vida' },
  { optionA: 'Autonomo', optionB: 'Empregado', category: 'Estilo de vida' },
  { optionA: 'Cidade grande', optionB: 'Cidade pequena', category: 'Estilo de vida' },
  { optionA: 'Animal de estimacao', optionB: 'Planta', category: 'Estilo de vida' },
  { optionA: 'Analogico', optionB: 'Digital', category: 'Estilo de vida' },
  { optionA: 'Escrito a mao', optionB: 'Digitado', category: 'Estilo de vida' },
  { optionA: 'Aposentadoria antecipada', optionB: 'Emprego dos sonhos pra sempre', category: 'Estilo de vida' },
  { optionA: 'Pessoa de verao', optionB: 'Pessoa de inverno', category: 'Estilo de vida' },
  { optionA: 'Mesa baguncada', optionB: 'Mesa arrumada', category: 'Estilo de vida' },
  { optionA: 'Ser barulhento', optionB: 'Ser quieto', category: 'Estilo de vida' },
  { optionA: 'Acordar cedo', optionB: 'Ficar ate tarde', category: 'Estilo de vida' },
  { optionA: 'Show ao vivo', optionB: 'Festival', category: 'Estilo de vida' },
  // Engracado (40)
  { optionA: 'Nunca mais chocolate', optionB: 'Nunca mais queijo', category: 'Engracado' },
  { optionA: 'Sempre cedo demais', optionB: 'Sempre atrasado', category: 'Engracado' },
  { optionA: 'Ser invisivel', optionB: 'Poder voar', category: 'Engracado' },
  { optionA: 'Ler mentes', optionB: 'Viajar no tempo', category: 'Engracado' },
  { optionA: 'Sem celular', optionB: 'Sem dormir', category: 'Engracado' },
  { optionA: '10 cachorros', optionB: '10 gatos', category: 'Engracado' },
  { optionA: 'Sempre falar alto', optionB: 'Sempre sussurrar', category: 'Engracado' },
  { optionA: 'Nunca mais pizza', optionB: 'Nunca mais musica', category: 'Engracado' },
  { optionA: 'Apocalipse zumbi', optionB: 'Invasao alienigena', category: 'Engracado' },
  { optionA: 'Ser gigante', optionB: 'Ser anao', category: 'Engracado' },
  { optionA: 'Viver no passado', optionB: 'Viver no futuro', category: 'Engracado' },
  { optionA: 'Viver na lua', optionB: 'Viver debaixo d\'agua', category: 'Engracado' },
  { optionA: 'So cantar em vez de falar', optionB: 'So dancar em vez de andar', category: 'Engracado' },
  { optionA: 'Superforce', optionB: 'Supervelocidade', category: 'Engracado' },
  { optionA: 'Ser eternamente jovem', optionB: 'Ser infinitamente rico', category: 'Engracado' },
  { optionA: 'Sempre falar a verdade', optionB: 'Sempre mentir', category: 'Engracado' },
  { optionA: 'So comida fria', optionB: 'So bebida quente', category: 'Engracado' },
  { optionA: 'Andar pra tras', optionB: 'Falar tudo ao contrario', category: 'Engracado' },
  { optionA: 'Musico famoso', optionB: 'Ator famoso', category: 'Engracado' },
  { optionA: 'Viver em um filme', optionB: 'Viver em um videogame', category: 'Engracado' },
  { optionA: 'Sem internet por 1 ano', optionB: 'Sem celular por 1 ano', category: 'Engracado' },
  { optionA: 'Chuva todo dia', optionB: '40 graus todo dia', category: 'Engracado' },
  { optionA: 'Sempre segunda-feira', optionB: 'Sempre domingo', category: 'Engracado' },
  { optionA: 'Ferias infinitas', optionB: 'Emprego dos sonhos', category: 'Engracado' },
  { optionA: 'Teletransporte', optionB: 'Viagem no tempo', category: 'Engracado' },
  { optionA: 'So voar', optionB: 'Respirar debaixo d\'agua', category: 'Engracado' },
  { optionA: 'Esquecer tudo', optionB: 'Lembrar de tudo', category: 'Engracado' },
  { optionA: 'Nunca mais dormir', optionB: 'Nunca mais comer', category: 'Engracado' },
  { optionA: 'Falar com animais', optionB: 'Falar todos os idiomas', category: 'Engracado' },
  { optionA: 'Viver em um musical', optionB: 'Viver em um filme de terror', category: 'Engracado' },
  { optionA: 'Sempre verao', optionB: 'Sempre outono', category: 'Engracado' },
  { optionA: 'Casa enorme', optionB: 'Casa pequena na praia', category: 'Engracado' },
  { optionA: '100 patos', optionB: '1 cavalo do tamanho de um pato', category: 'Engracado' },
  { optionA: 'Viver na idade da pedra', optionB: 'Viver no ano 3000', category: 'Engracado' },
  { optionA: 'Ser super-heroi', optionB: 'Ser supervilao', category: 'Engracado' },
  { optionA: 'Sempre a roupa certa', optionB: 'Sempre a comida certa', category: 'Engracado' },
  { optionA: 'Tudo em camera lenta', optionB: 'Tudo acelerado', category: 'Engracado' },
  { optionA: 'Nunca mais cozinhar', optionB: 'Nunca mais limpar', category: 'Engracado' },
  { optionA: 'Bater um recorde mundial', optionB: 'Ganhar na loteria', category: 'Engracado' },
  { optionA: 'Sempre certo', optionB: 'Sempre feliz', category: 'Engracado' },
  // Filosofico (35)
  { optionA: 'Amor sem dinheiro', optionB: 'Dinheiro sem amor', category: 'Filosofico' },
  { optionA: 'Saber tudo', optionB: 'Poder fazer tudo', category: 'Filosofico' },
  { optionA: 'Mudar o passado', optionB: 'Ver o futuro', category: 'Filosofico' },
  { optionA: 'Viver muito', optionB: 'Viver intensamente', category: 'Filosofico' },
  { optionA: 'Razao', optionB: 'Coracao', category: 'Filosofico' },
  { optionA: 'Liberdade', optionB: 'Seguranca', category: 'Filosofico' },
  { optionA: 'Talento', optionB: 'Esforco', category: 'Filosofico' },
  { optionA: 'Verdade', optionB: 'Felicidade', category: 'Filosofico' },
  { optionA: 'Poder esquecer', optionB: 'Nunca esquecer', category: 'Filosofico' },
  { optionA: 'Fama', optionB: 'Anonimato', category: 'Filosofico' },
  { optionA: 'Muitos amigos', optionB: 'Um melhor amigo', category: 'Filosofico' },
  { optionA: 'Poder', optionB: 'Sabedoria', category: 'Filosofico' },
  { optionA: 'Memoria perfeita', optionB: 'Criatividade perfeita', category: 'Filosofico' },
  { optionA: 'Sempre ter razao', optionB: 'Sempre ser feliz', category: 'Filosofico' },
  { optionA: 'So dar', optionB: 'So receber', category: 'Filosofico' },
  { optionA: 'Salvar o mundo', optionB: 'Salvar sua familia', category: 'Filosofico' },
  { optionA: 'Sucesso', optionB: 'Satisfacao', category: 'Filosofico' },
  { optionA: 'Beleza', optionB: 'Inteligencia', category: 'Filosofico' },
  { optionA: 'Confianca', optionB: 'Respeito', category: 'Filosofico' },
  { optionA: 'Coragem', optionB: 'Paciencia', category: 'Filosofico' },
  { optionA: 'Conhecer a solidao', optionB: 'Nunca ficar sozinho', category: 'Filosofico' },
  { optionA: 'Poder errar', optionB: 'Nunca falhar', category: 'Filosofico' },
  { optionA: 'Controlar tudo', optionB: 'Aceitar tudo', category: 'Filosofico' },
  { optionA: 'Saude', optionB: 'Riqueza', category: 'Filosofico' },
  { optionA: 'Paixao', optionB: 'Estabilidade', category: 'Filosofico' },
  { optionA: 'Saber tudo e ser triste', optionB: 'Nao saber nada e ser feliz', category: 'Filosofico' },
  { optionA: 'Ser inesquecivel', optionB: 'Ser imortal', category: 'Filosofico' },
  { optionA: 'Passado perfeito', optionB: 'Futuro perfeito', category: 'Filosofico' },
  { optionA: 'Energia infinita', optionB: 'Tempo infinito', category: 'Filosofico' },
  { optionA: 'So fazer o bem', optionB: 'So ser honesto', category: 'Filosofico' },
  { optionA: 'Perder tudo e recomeccar', optionB: 'Nao poder mudar nada', category: 'Filosofico' },
  { optionA: 'Paz interior', optionB: 'Sucesso externo', category: 'Filosofico' },
  { optionA: 'Sempre ser o melhor', optionB: 'Sempre ser o mais querido', category: 'Filosofico' },
  { optionA: 'Poder ajudar os outros', optionB: 'Poder ajudar a si mesmo', category: 'Filosofico' },
  { optionA: 'Sentir tudo', optionB: 'Nao sentir nada', category: 'Filosofico' },
];
