import { ThisOrThatPair } from './thisorthat-content-de';

export const THISORTHAT_PAIRS_AR: ThisOrThatPair[] = [
  // طعام (35)
  { optionA: 'بيتزا', optionB: 'برغر', category: 'طعام' },
  { optionA: 'شوكولاتة', optionB: 'حلوى', category: 'طعام' },
  { optionA: 'قهوة', optionB: 'شاي', category: 'طعام' },
  { optionA: 'سوشي', optionB: 'ستيك', category: 'طعام' },
  { optionA: 'آيس كريم', optionB: 'كعكة', category: 'طعام' },
  { optionA: 'فطور', optionB: 'عشاء', category: 'طعام' },
  { optionA: 'حلو', optionB: 'مالح', category: 'طعام' },
  { optionA: 'الطبخ', optionB: 'الطلب من المطعم', category: 'طعام' },
  { optionA: 'معكرونة', optionB: 'أرز', category: 'طعام' },
  { optionA: 'بطاطس مقلية', optionB: 'شيبس', category: 'طعام' },
  { optionA: 'شاورما', optionB: 'فلافل', category: 'طعام' },
  { optionA: 'ماء', optionB: 'عصير ليمون', category: 'طعام' },
  { optionA: 'بان كيك', optionB: 'وافل', category: 'طعام' },
  { optionA: 'زبدة الفول السوداني', optionB: 'نوتيلا', category: 'طعام' },
  { optionA: 'تفاح', optionB: 'موز', category: 'طعام' },
  { optionA: 'حليب', optionB: 'حليب الشوفان', category: 'طعام' },
  { optionA: 'سلطة', optionB: 'شوربة', category: 'طعام' },
  { optionA: 'جبن', optionB: 'لحم', category: 'طعام' },
  { optionA: 'شواء', optionB: 'فوندو', category: 'طعام' },
  { optionA: 'فشار', optionB: 'ناتشوز', category: 'طعام' },
  { optionA: 'خبز عربي', optionB: 'كرواسون', category: 'طعام' },
  { optionA: 'عصير', optionB: 'كولا', category: 'طعام' },
  { optionA: 'بار حبوب', optionB: 'بار شوكولاتة', category: 'طعام' },
  { optionA: 'بيتزا مجمدة', optionB: 'بيتزا توصيل', category: 'طعام' },
  { optionA: 'كرواسون', optionB: 'دونات', category: 'طعام' },
  { optionA: 'فطور في السرير', optionB: 'فطور على الطاولة', category: 'طعام' },
  { optionA: 'أكل حار', optionB: 'أكل خفيف', category: 'طعام' },
  { optionA: 'طبخ منزلي', optionB: 'مطعم', category: 'طعام' },
  { optionA: 'خبز أسمر', optionB: 'خبز أبيض', category: 'طعام' },
  { optionA: 'سموذي', optionB: 'عصير طازج', category: 'طعام' },
  { optionA: 'برنش', optionB: 'وجبة منتصف الليل', category: 'طعام' },
  { optionA: 'أكل آسيوي', optionB: 'أكل إيطالي', category: 'طعام' },
  { optionA: 'كباب', optionB: 'منسف', category: 'طعام' },
  { optionA: 'نباتي', optionB: 'محب اللحوم', category: 'طعام' },
  { optionA: 'بقلاوة', optionB: 'كنافة', category: 'طعام' },
  // سفر (35)
  { optionA: 'شاطئ', optionB: 'جبال', category: 'سفر' },
  { optionA: 'طائرة', optionB: 'رحلة بالسيارة', category: 'سفر' },
  { optionA: 'فندق', optionB: 'تخييم', category: 'سفر' },
  { optionA: 'صيف', optionB: 'شتاء', category: 'سفر' },
  { optionA: 'أوروبا', optionB: 'آسيا', category: 'سفر' },
  { optionA: 'رحلة مدينة', optionB: 'إجازة في الطبيعة', category: 'سفر' },
  { optionA: 'السفر وحيدا', optionB: 'رحلة جماعية', category: 'سفر' },
  { optionA: 'الاستيقاظ باكرا', optionB: 'النوم حتى وقت متأخر', category: 'سفر' },
  { optionA: 'حقيبة ظهر', optionB: 'كل شيء شامل', category: 'سفر' },
  { optionA: 'رحلة بحرية', optionB: 'سفاري', category: 'سفر' },
  { optionA: 'نيويورك', optionB: 'طوكيو', category: 'سفر' },
  { optionA: 'صحراء', optionB: 'غابة مطيرة', category: 'سفر' },
  { optionA: 'قطار', optionB: 'سفينة', category: 'سفر' },
  { optionA: 'مغامرة', optionB: 'استرخاء', category: 'سفر' },
  { optionA: 'إسبانيا', optionB: 'إيطاليا', category: 'سفر' },
  { optionA: 'إجازة تزلج', optionB: 'إجازة ركوب أمواج', category: 'سفر' },
  { optionA: 'ربيع', optionB: 'خريف', category: 'سفر' },
  { optionA: 'شفق قطبي', optionB: 'غروب على البحر', category: 'سفر' },
  { optionA: 'مدينة ملاهي', optionB: 'منتجع صحي', category: 'سفر' },
  { optionA: 'نزل', optionB: 'إير بي إن بي', category: 'سفر' },
  { optionA: 'حقيبة سفر', optionB: 'حقيبة ظهر', category: 'سفر' },
  { optionA: 'مقعد النافذة', optionB: 'مقعد الممر', category: 'سفر' },
  { optionA: 'الحجز المبكر', optionB: 'اللحظة الأخيرة', category: 'سفر' },
  { optionA: 'غوص', optionB: 'تسلق جبال', category: 'سفر' },
  { optionA: 'البندقية', optionB: 'باريس', category: 'سفر' },
  { optionA: 'بار على الشاطئ', optionB: 'كوخ جبلي', category: 'سفر' },
  { optionA: 'شروق الشمس', optionB: 'غروب الشمس', category: 'سفر' },
  { optionA: 'مكان سري', optionB: 'معلم سياحي', category: 'سفر' },
  { optionA: 'سيارة متنقلة', optionB: 'فندق فاخر', category: 'سفر' },
  { optionA: 'مغامرة في الغابة', optionB: 'سفاري في الصحراء', category: 'سفر' },
  { optionA: 'الكاريبي', optionB: 'الدول الاسكندنافية', category: 'سفر' },
  { optionA: 'قطار ليلي', optionB: 'رحلة ليلية', category: 'سفر' },
  { optionA: 'رحلة ثقافية', optionB: 'رحلة حفلات', category: 'سفر' },
  { optionA: 'أيسلندا', optionB: 'هاواي', category: 'سفر' },
  { optionA: 'تخييم عند البحيرة', optionB: 'بيت شجرة في الغابة', category: 'سفر' },
  // نمط حياة (40)
  { optionA: 'نتفليكس', optionB: 'يوتيوب', category: 'نمط حياة' },
  { optionA: 'شخص صباحي', optionB: 'شخص ليلي', category: 'نمط حياة' },
  { optionA: 'كلب', optionB: 'قطة', category: 'نمط حياة' },
  { optionA: 'آيفون', optionB: 'أندرويد', category: 'نمط حياة' },
  { optionA: 'إنستغرام', optionB: 'تيك توك', category: 'نمط حياة' },
  { optionA: 'قراءة كتاب', optionB: 'سماع بودكاست', category: 'نمط حياة' },
  { optionA: 'صالة رياضية', optionB: 'ركض', category: 'نمط حياة' },
  { optionA: 'المدينة', optionB: 'الريف', category: 'نمط حياة' },
  { optionA: 'نقد', optionB: 'بطاقة', category: 'نمط حياة' },
  { optionA: 'النوم باكرا', optionB: 'بومة الليل', category: 'نمط حياة' },
  { optionA: 'تسوق إلكتروني', optionB: 'تسوق من المحل', category: 'نمط حياة' },
  { optionA: 'سماع موسيقى', optionB: 'مشاهدة مسلسلات', category: 'نمط حياة' },
  { optionA: 'حوض استحمام', optionB: 'دش', category: 'نمط حياة' },
  { optionA: 'حذاء رياضي', optionB: 'حذاء أنيق', category: 'نمط حياة' },
  { optionA: 'بسيط', optionB: 'جامع', category: 'نمط حياة' },
  { optionA: 'اجتماعي', optionB: 'انطوائي', category: 'نمط حياة' },
  { optionA: 'التخطيط', optionB: 'العفوية', category: 'نمط حياة' },
  { optionA: 'ألعاب فيديو', optionB: 'ألعاب لوحية', category: 'نمط حياة' },
  { optionA: 'مهرجان', optionB: 'حفلة', category: 'نمط حياة' },
  { optionA: 'سكن مشترك', optionB: 'السكن وحيدا', category: 'نمط حياة' },
  { optionA: 'تعلم الطبخ', optionB: 'تعلم آلة موسيقية', category: 'نمط حياة' },
  { optionA: 'وشم', optionB: 'ثقب', category: 'نمط حياة' },
  { optionA: 'عمل من البيت', optionB: 'مكتب', category: 'نمط حياة' },
  { optionA: 'سبوتيفاي', optionB: 'آبل ميوزك', category: 'نمط حياة' },
  { optionA: 'ممارسة الرياضة', optionB: 'مشاهدة الرياضة', category: 'نمط حياة' },
  { optionA: 'سيارة كهربائية', optionB: 'سيارة كلاسيكية', category: 'نمط حياة' },
  { optionA: 'سينما', optionB: 'مسرح', category: 'نمط حياة' },
  { optionA: 'كتاب', optionB: 'كتاب صوتي', category: 'نمط حياة' },
  { optionA: 'يوغا', optionB: 'كروسفت', category: 'نمط حياة' },
  { optionA: 'عمل حر', optionB: 'موظف', category: 'نمط حياة' },
  { optionA: 'مدينة كبيرة', optionB: 'مدينة صغيرة', category: 'نمط حياة' },
  { optionA: 'حيوان أليف', optionB: 'نبتة', category: 'نمط حياة' },
  { optionA: 'تناظري', optionB: 'رقمي', category: 'نمط حياة' },
  { optionA: 'مكتوب بخط اليد', optionB: 'مطبوع', category: 'نمط حياة' },
  { optionA: 'تقاعد مبكر', optionB: 'وظيفة الأحلام للأبد', category: 'نمط حياة' },
  { optionA: 'شخص صيفي', optionB: 'شخص شتوي', category: 'نمط حياة' },
  { optionA: 'مكتب فوضوي', optionB: 'مكتب مرتب', category: 'نمط حياة' },
  { optionA: 'صاخب', optionB: 'هادئ', category: 'نمط حياة' },
  { optionA: 'الاستيقاظ باكرا', optionB: 'السهر', category: 'نمط حياة' },
  { optionA: 'حفلة حية', optionB: 'مهرجان', category: 'نمط حياة' },
  // مضحك (40)
  { optionA: 'وداعا شوكولاتة للأبد', optionB: 'وداعا جبن للأبد', category: 'مضحك' },
  { optionA: 'دائما مبكر', optionB: 'دائما متأخر', category: 'مضحك' },
  { optionA: 'أن تكون غير مرئي', optionB: 'أن تستطيع الطيران', category: 'مضحك' },
  { optionA: 'قراءة الأفكار', optionB: 'السفر عبر الزمن', category: 'مضحك' },
  { optionA: 'بدون هاتف', optionB: 'بدون نوم', category: 'مضحك' },
  { optionA: '١٠ كلاب', optionB: '١٠ قطط', category: 'مضحك' },
  { optionA: 'التحدث بصوت عال دائما', optionB: 'الهمس دائما', category: 'مضحك' },
  { optionA: 'وداعا بيتزا للأبد', optionB: 'وداعا موسيقى للأبد', category: 'مضحك' },
  { optionA: 'نهاية العالم بالزومبي', optionB: 'غزو فضائي', category: 'مضحك' },
  { optionA: 'أن تكون عملاقا', optionB: 'أن تكون قزما', category: 'مضحك' },
  { optionA: 'العيش في الماضي', optionB: 'العيش في المستقبل', category: 'مضحك' },
  { optionA: 'العيش على القمر', optionB: 'العيش تحت الماء', category: 'مضحك' },
  { optionA: 'الغناء بدل الكلام', optionB: 'الرقص بدل المشي', category: 'مضحك' },
  { optionA: 'قوة خارقة', optionB: 'سرعة خارقة', category: 'مضحك' },
  { optionA: 'البقاء شابا للأبد', optionB: 'أن تكون غنيا بلا حدود', category: 'مضحك' },
  { optionA: 'قول الحقيقة دائما', optionB: 'الكذب دائما', category: 'مضحك' },
  { optionA: 'أكل بارد فقط', optionB: 'شرب ساخن فقط', category: 'مضحك' },
  { optionA: 'المشي للخلف', optionB: 'التحدث بالعكس', category: 'مضحك' },
  { optionA: 'موسيقي مشهور', optionB: 'ممثل مشهور', category: 'مضحك' },
  { optionA: 'العيش في فيلم', optionB: 'العيش في لعبة فيديو', category: 'مضحك' },
  { optionA: 'بدون إنترنت سنة', optionB: 'بدون هاتف سنة', category: 'مضحك' },
  { optionA: 'مطر كل يوم', optionB: '٤٠ درجة كل يوم', category: 'مضحك' },
  { optionA: 'دائما يوم الاثنين', optionB: 'دائما يوم الأحد', category: 'مضحك' },
  { optionA: 'إجازة بلا نهاية', optionB: 'وظيفة الأحلام', category: 'مضحك' },
  { optionA: 'التنقل الآني', optionB: 'السفر عبر الزمن', category: 'مضحك' },
  { optionA: 'الطيران فقط', optionB: 'التنفس تحت الماء', category: 'مضحك' },
  { optionA: 'نسيان كل شيء', optionB: 'تذكر كل شيء', category: 'مضحك' },
  { optionA: 'عدم النوم أبدا', optionB: 'عدم الأكل أبدا', category: 'مضحك' },
  { optionA: 'التحدث مع الحيوانات', optionB: 'التحدث بكل اللغات', category: 'مضحك' },
  { optionA: 'العيش في مسرحية غنائية', optionB: 'العيش في فيلم رعب', category: 'مضحك' },
  { optionA: 'صيف دائم', optionB: 'خريف دائم', category: 'مضحك' },
  { optionA: 'بيت ضخم', optionB: 'بيت صغير على البحر', category: 'مضحك' },
  { optionA: '١٠٠ بطة', optionB: 'حصان بحجم بطة', category: 'مضحك' },
  { optionA: 'العيش في العصر الحجري', optionB: 'العيش في سنة ٣٠٠٠', category: 'مضحك' },
  { optionA: 'أن تكون بطلا خارقا', optionB: 'أن تكون شريرا خارقا', category: 'مضحك' },
  { optionA: 'دائما الملابس المناسبة', optionB: 'دائما الأكل المناسب', category: 'مضحك' },
  { optionA: 'كل شيء بالتصوير البطيء', optionB: 'كل شيء بالتصوير السريع', category: 'مضحك' },
  { optionA: 'عدم الطبخ أبدا', optionB: 'عدم التنظيف أبدا', category: 'مضحك' },
  { optionA: 'تحطيم رقم قياسي عالمي', optionB: 'الفوز باليانصيب', category: 'مضحك' },
  { optionA: 'دائما على حق', optionB: 'دائما سعيد', category: 'مضحك' },
  // فلسفي (35)
  { optionA: 'حب بلا مال', optionB: 'مال بلا حب', category: 'فلسفي' },
  { optionA: 'معرفة كل شيء', optionB: 'القدرة على فعل كل شيء', category: 'فلسفي' },
  { optionA: 'تغيير الماضي', optionB: 'رؤية المستقبل', category: 'فلسفي' },
  { optionA: 'العيش طويلا', optionB: 'العيش بكثافة', category: 'فلسفي' },
  { optionA: 'العقل', optionB: 'القلب', category: 'فلسفي' },
  { optionA: 'الحرية', optionB: 'الأمان', category: 'فلسفي' },
  { optionA: 'الموهبة', optionB: 'الاجتهاد', category: 'فلسفي' },
  { optionA: 'الحقيقة', optionB: 'السعادة', category: 'فلسفي' },
  { optionA: 'القدرة على النسيان', optionB: 'عدم النسيان أبدا', category: 'فلسفي' },
  { optionA: 'الشهرة', optionB: 'إخفاء الهوية', category: 'فلسفي' },
  { optionA: 'أصدقاء كثيرون', optionB: 'صديق واحد مقرب', category: 'فلسفي' },
  { optionA: 'القوة', optionB: 'الحكمة', category: 'فلسفي' },
  { optionA: 'ذاكرة مثالية', optionB: 'إبداع مثالي', category: 'فلسفي' },
  { optionA: 'دائما على حق', optionB: 'دائما سعيد', category: 'فلسفي' },
  { optionA: 'العطاء فقط', optionB: 'الأخذ فقط', category: 'فلسفي' },
  { optionA: 'إنقاذ العالم', optionB: 'إنقاذ عائلتك', category: 'فلسفي' },
  { optionA: 'النجاح', optionB: 'الرضا', category: 'فلسفي' },
  { optionA: 'الجمال', optionB: 'الذكاء', category: 'فلسفي' },
  { optionA: 'الثقة', optionB: 'الاحترام', category: 'فلسفي' },
  { optionA: 'الشجاعة', optionB: 'الصبر', category: 'فلسفي' },
  { optionA: 'معرفة الوحدة', optionB: 'عدم البقاء وحيدا أبدا', category: 'فلسفي' },
  { optionA: 'حق الخطأ', optionB: 'عدم الفشل أبدا', category: 'فلسفي' },
  { optionA: 'التحكم بكل شيء', optionB: 'قبول كل شيء', category: 'فلسفي' },
  { optionA: 'الصحة', optionB: 'الثروة', category: 'فلسفي' },
  { optionA: 'الشغف', optionB: 'الاستقرار', category: 'فلسفي' },
  { optionA: 'معرفة كل شيء والحزن', optionB: 'جهل كل شيء والسعادة', category: 'فلسفي' },
  { optionA: 'أن تكون لا تُنسى', optionB: 'أن تكون خالدا', category: 'فلسفي' },
  { optionA: 'ماض مثالي', optionB: 'مستقبل مثالي', category: 'فلسفي' },
  { optionA: 'طاقة لا نهائية', optionB: 'وقت لا نهائي', category: 'فلسفي' },
  { optionA: 'فعل الخير فقط', optionB: 'الصدق فقط', category: 'فلسفي' },
  { optionA: 'خسارة كل شيء والبدء من جديد', optionB: 'عدم القدرة على تغيير أي شيء', category: 'فلسفي' },
  { optionA: 'السلام الداخلي', optionB: 'النجاح الخارجي', category: 'فلسفي' },
  { optionA: 'دائما الأفضل', optionB: 'دائما الأكثر شعبية', category: 'فلسفي' },
  { optionA: 'القدرة على مساعدة الآخرين', optionB: 'القدرة على مساعدة نفسك', category: 'فلسفي' },
  { optionA: 'الشعور بكل شيء', optionB: 'عدم الشعور بأي شيء', category: 'فلسفي' },
];
