export interface ThisOrThatPair {
  optionA: string;
  optionB: string;
  category: string;
}

export const THISORTHAT_PAIRS_IT: ThisOrThatPair[] = [
  // Cibo (35)
  { optionA: 'Pizza', optionB: 'Hamburger', category: 'Cibo' },
  { optionA: 'Cioccolato', optionB: 'Caramelle gommose', category: 'Cibo' },
  { optionA: 'Caffe', optionB: 'Te', category: 'Cibo' },
  { optionA: 'Sushi', optionB: 'Bistecca', category: 'Cibo' },
  { optionA: 'Gelato', optionB: 'Torta', category: 'Cibo' },
  { optionA: 'Colazione', optionB: 'Cena', category: 'Cibo' },
  { optionA: 'Dolce', optionB: 'Salato', category: 'Cibo' },
  { optionA: 'Cucinare', optionB: 'Ordinare', category: 'Cibo' },
  { optionA: 'Pasta', optionB: 'Riso', category: 'Cibo' },
  { optionA: 'Patatine fritte', optionB: 'Chips', category: 'Cibo' },
  { optionA: 'Carbonara', optionB: 'Amatriciana', category: 'Cibo' },
  { optionA: 'Acqua', optionB: 'Limonata', category: 'Cibo' },
  { optionA: 'Pancake', optionB: 'Waffle', category: 'Cibo' },
  { optionA: 'Burro di arachidi', optionB: 'Nutella', category: 'Cibo' },
  { optionA: 'Mela', optionB: 'Banana', category: 'Cibo' },
  { optionA: 'Latte', optionB: 'Latte vegetale', category: 'Cibo' },
  { optionA: 'Insalata', optionB: 'Minestra', category: 'Cibo' },
  { optionA: 'Formaggio', optionB: 'Prosciutto', category: 'Cibo' },
  { optionA: 'Grigliata', optionB: 'Fonduta', category: 'Cibo' },
  { optionA: 'Popcorn', optionB: 'Nachos', category: 'Cibo' },
  { optionA: 'Focaccia', optionB: 'Croissant', category: 'Cibo' },
  { optionA: 'Birra', optionB: 'Vino', category: 'Cibo' },
  { optionA: 'Barretta di cereali', optionB: 'Barretta di cioccolato', category: 'Cibo' },
  { optionA: 'Pizza surgelata', optionB: 'Pizza consegnata', category: 'Cibo' },
  { optionA: 'Croissant', optionB: 'Ciambella', category: 'Cibo' },
  { optionA: 'Colazione a letto', optionB: 'Colazione a tavola', category: 'Cibo' },
  { optionA: 'Cibo piccante', optionB: 'Cibo delicato', category: 'Cibo' },
  { optionA: 'Cucinato in casa', optionB: 'Ristorante', category: 'Cibo' },
  { optionA: 'Pane integrale', optionB: 'Pane bianco', category: 'Cibo' },
  { optionA: 'Frullato', optionB: 'Spremuta fresca', category: 'Cibo' },
  { optionA: 'Brunch', optionB: 'Spuntino di mezzanotte', category: 'Cibo' },
  { optionA: 'Asiatico', optionB: 'Italiano', category: 'Cibo' },
  { optionA: 'Curry', optionB: 'Pasta', category: 'Cibo' },
  { optionA: 'Vegetariano', optionB: 'Amante della carne', category: 'Cibo' },
  { optionA: 'Caramelle', optionB: 'Liquirizia', category: 'Cibo' },
  // Viaggi (35)
  { optionA: 'Spiaggia', optionB: 'Montagna', category: 'Viaggi' },
  { optionA: 'Volare', optionB: 'Viaggio in auto', category: 'Viaggi' },
  { optionA: 'Hotel', optionB: 'Campeggio', category: 'Viaggi' },
  { optionA: 'Estate', optionB: 'Inverno', category: 'Viaggi' },
  { optionA: 'Europa', optionB: 'Asia', category: 'Viaggi' },
  { optionA: 'Citta', optionB: 'Natura', category: 'Viaggi' },
  { optionA: 'Viaggiare da soli', optionB: 'Viaggio di gruppo', category: 'Viaggi' },
  { optionA: 'Svegliarsi presto', optionB: 'Dormire fino a tardi', category: 'Viaggi' },
  { optionA: 'Zaino in spalla', optionB: 'All-Inclusive', category: 'Viaggi' },
  { optionA: 'Crociera', optionB: 'Safari', category: 'Viaggi' },
  { optionA: 'New York', optionB: 'Tokyo', category: 'Viaggi' },
  { optionA: 'Deserto', optionB: 'Foresta pluviale', category: 'Viaggi' },
  { optionA: 'Treno', optionB: 'Nave', category: 'Viaggi' },
  { optionA: 'Avventura', optionB: 'Relax', category: 'Viaggi' },
  { optionA: 'Spagna', optionB: 'Italia', category: 'Viaggi' },
  { optionA: 'Vacanza sulla neve', optionB: 'Vacanza al mare', category: 'Viaggi' },
  { optionA: 'Primavera', optionB: 'Autunno', category: 'Viaggi' },
  { optionA: 'Aurora boreale', optionB: 'Tramonto sul mare', category: 'Viaggi' },
  { optionA: 'Parco divertimenti', optionB: 'Centro benessere', category: 'Viaggi' },
  { optionA: 'Ostello', optionB: 'Airbnb', category: 'Viaggi' },
  { optionA: 'Valigia', optionB: 'Zaino', category: 'Viaggi' },
  { optionA: 'Posto finestrino', optionB: 'Posto corridoio', category: 'Viaggi' },
  { optionA: 'Prenotare in anticipo', optionB: 'Last Minute', category: 'Viaggi' },
  { optionA: 'Immersioni', optionB: 'Trekking', category: 'Viaggi' },
  { optionA: 'Venezia', optionB: 'Parigi', category: 'Viaggi' },
  { optionA: 'Bar sulla spiaggia', optionB: 'Rifugio in montagna', category: 'Viaggi' },
  { optionA: 'Alba', optionB: 'Tramonto', category: 'Viaggi' },
  { optionA: 'Posto nascosto', optionB: 'Attrazione turistica', category: 'Viaggi' },
  { optionA: 'Camper', optionB: 'Hotel di lusso', category: 'Viaggi' },
  { optionA: 'Avventura nella giungla', optionB: 'Safari nel deserto', category: 'Viaggi' },
  { optionA: 'Caraibi', optionB: 'Scandinavia', category: 'Viaggi' },
  { optionA: 'Treno notturno', optionB: 'Volo notturno', category: 'Viaggi' },
  { optionA: 'Viaggio culturale', optionB: 'Viaggio festaiolo', category: 'Viaggi' },
  { optionA: 'Islanda', optionB: 'Hawaii', category: 'Viaggi' },
  { optionA: 'Tenda al lago', optionB: 'Casa sull\'albero', category: 'Viaggi' },
  // Stile di vita (40)
  { optionA: 'Netflix', optionB: 'YouTube', category: 'Stile di vita' },
  { optionA: 'Mattiniero', optionB: 'Nottambulo', category: 'Stile di vita' },
  { optionA: 'Cane', optionB: 'Gatto', category: 'Stile di vita' },
  { optionA: 'iPhone', optionB: 'Android', category: 'Stile di vita' },
  { optionA: 'Instagram', optionB: 'TikTok', category: 'Stile di vita' },
  { optionA: 'Leggere un libro', optionB: 'Ascoltare un podcast', category: 'Stile di vita' },
  { optionA: 'Palestra', optionB: 'Corsa', category: 'Stile di vita' },
  { optionA: 'Citta', optionB: 'Campagna', category: 'Stile di vita' },
  { optionA: 'Contanti', optionB: 'Carta', category: 'Stile di vita' },
  { optionA: 'A letto presto', optionB: 'Nottambulo', category: 'Stile di vita' },
  { optionA: 'Shopping online', optionB: 'Comprare in negozio', category: 'Stile di vita' },
  { optionA: 'Ascoltare musica', optionB: 'Guardare serie', category: 'Stile di vita' },
  { optionA: 'Vasca da bagno', optionB: 'Doccia', category: 'Stile di vita' },
  { optionA: 'Sneaker', optionB: 'Scarpe eleganti', category: 'Stile di vita' },
  { optionA: 'Minimalista', optionB: 'Collezionista', category: 'Stile di vita' },
  { optionA: 'Estroverso', optionB: 'Introverso', category: 'Stile di vita' },
  { optionA: 'Pianificare', optionB: 'Essere spontaneo', category: 'Stile di vita' },
  { optionA: 'Videogiochi', optionB: 'Giochi da tavolo', category: 'Stile di vita' },
  { optionA: 'Festival', optionB: 'Concerto', category: 'Stile di vita' },
  { optionA: 'Coinquilini', optionB: 'Vivere da soli', category: 'Stile di vita' },
  { optionA: 'Imparare a cucinare', optionB: 'Imparare uno strumento', category: 'Stile di vita' },
  { optionA: 'Tatuaggio', optionB: 'Piercing', category: 'Stile di vita' },
  { optionA: 'Lavoro da casa', optionB: 'Ufficio', category: 'Stile di vita' },
  { optionA: 'Spotify', optionB: 'Apple Music', category: 'Stile di vita' },
  { optionA: 'Fare sport', optionB: 'Guardare sport', category: 'Stile di vita' },
  { optionA: 'Auto elettrica', optionB: 'Auto d\'epoca', category: 'Stile di vita' },
  { optionA: 'Svegliarsi presto', optionB: 'Andare a letto tardi', category: 'Stile di vita' },
  { optionA: 'Cinema', optionB: 'Teatro', category: 'Stile di vita' },
  { optionA: 'Libro', optionB: 'Audiolibro', category: 'Stile di vita' },
  { optionA: 'Concerto dal vivo', optionB: 'Festival', category: 'Stile di vita' },
  { optionA: 'Yoga', optionB: 'Crossfit', category: 'Stile di vita' },
  { optionA: 'Freelance', optionB: 'Dipendente', category: 'Stile di vita' },
  { optionA: 'Grande citta', optionB: 'Piccola citta', category: 'Stile di vita' },
  { optionA: 'Animale domestico', optionB: 'Pianta', category: 'Stile di vita' },
  { optionA: 'Analogico', optionB: 'Digitale', category: 'Stile di vita' },
  { optionA: 'Scritto a mano', optionB: 'Digitato', category: 'Stile di vita' },
  { optionA: 'Pensione anticipata', optionB: 'Lavoro dei sogni per sempre', category: 'Stile di vita' },
  { optionA: 'Tipo estivo', optionB: 'Tipo invernale', category: 'Stile di vita' },
  { optionA: 'Scrivania caotica', optionB: 'Scrivania ordinata', category: 'Stile di vita' },
  { optionA: 'Essere rumoroso', optionB: 'Essere silenzioso', category: 'Stile di vita' },
  // Divertente (40)
  { optionA: 'Mai piu cioccolato', optionB: 'Mai piu formaggio', category: 'Divertente' },
  { optionA: 'Sempre in anticipo', optionB: 'Sempre in ritardo', category: 'Divertente' },
  { optionA: 'Essere invisibile', optionB: 'Poter volare', category: 'Divertente' },
  { optionA: 'Leggere il pensiero', optionB: 'Viaggiare nel tempo', category: 'Divertente' },
  { optionA: 'Senza telefono', optionB: 'Senza sonno', category: 'Divertente' },
  { optionA: '10 cani', optionB: '10 gatti', category: 'Divertente' },
  { optionA: 'Parlare sempre forte', optionB: 'Sussurrare sempre', category: 'Divertente' },
  { optionA: 'Mai piu pizza', optionB: 'Mai piu musica', category: 'Divertente' },
  { optionA: 'Apocalisse zombie', optionB: 'Invasione aliena', category: 'Divertente' },
  { optionA: 'Essere un gigante', optionB: 'Essere un nano', category: 'Divertente' },
  { optionA: 'Vivere nel passato', optionB: 'Vivere nel futuro', category: 'Divertente' },
  { optionA: 'Vivere sulla Luna', optionB: 'Vivere sott\'acqua', category: 'Divertente' },
  { optionA: 'Solo cantare invece di parlare', optionB: 'Solo ballare invece di camminare', category: 'Divertente' },
  { optionA: 'Superforza', optionB: 'Supervelocita', category: 'Divertente' },
  { optionA: 'Restare giovane per sempre', optionB: 'Essere infinitamente ricco', category: 'Divertente' },
  { optionA: 'Dire sempre la verita', optionB: 'Mentire sempre', category: 'Divertente' },
  { optionA: 'Solo cibo freddo', optionB: 'Solo bevande calde', category: 'Divertente' },
  { optionA: 'Camminare all\'indietro', optionB: 'Parlare al contrario', category: 'Divertente' },
  { optionA: 'Musicista famoso', optionB: 'Attore famoso', category: 'Divertente' },
  { optionA: 'Vivere in un film', optionB: 'Vivere in un videogioco', category: 'Divertente' },
  { optionA: 'Niente internet per 1 anno', optionB: 'Niente telefono per 1 anno', category: 'Divertente' },
  { optionA: 'Pioggia ogni giorno', optionB: '40 gradi ogni giorno', category: 'Divertente' },
  { optionA: 'Sempre lunedi', optionB: 'Sempre domenica', category: 'Divertente' },
  { optionA: 'Vacanza infinita', optionB: 'Lavoro dei sogni', category: 'Divertente' },
  { optionA: 'Teletrasporto', optionB: 'Viaggio nel tempo', category: 'Divertente' },
  { optionA: 'Solo volare', optionB: 'Respirare sott\'acqua', category: 'Divertente' },
  { optionA: 'Dimenticare tutto', optionB: 'Ricordare tutto', category: 'Divertente' },
  { optionA: 'Non dormire mai', optionB: 'Non mangiare mai', category: 'Divertente' },
  { optionA: 'Parlare con gli animali', optionB: 'Parlare tutte le lingue', category: 'Divertente' },
  { optionA: 'Vivere in un musical', optionB: 'Vivere in un film horror', category: 'Divertente' },
  { optionA: 'Sempre estate', optionB: 'Sempre autunno', category: 'Divertente' },
  { optionA: 'Casa enorme', optionB: 'Casetta sulla spiaggia', category: 'Divertente' },
  { optionA: '100 anatre', optionB: '1 cavallo grande come un\'anatra', category: 'Divertente' },
  { optionA: 'Eta della pietra', optionB: 'Anno 3000', category: 'Divertente' },
  { optionA: 'Essere un supereroe', optionB: 'Essere un supercattivo', category: 'Divertente' },
  { optionA: 'Sempre l\'outfit giusto', optionB: 'Sempre il cibo giusto', category: 'Divertente' },
  { optionA: 'Tutto al rallentatore', optionB: 'Tutto accelerato', category: 'Divertente' },
  { optionA: 'Mai piu cucinare', optionB: 'Mai piu pulire', category: 'Divertente' },
  { optionA: 'Record mondiale', optionB: 'Vincere alla lotteria', category: 'Divertente' },
  { optionA: 'Senza braccia', optionB: 'Senza gambe', category: 'Divertente' },
  // Filosofico (35)
  { optionA: 'Amore senza soldi', optionB: 'Soldi senza amore', category: 'Filosofico' },
  { optionA: 'Sapere tutto', optionB: 'Saper fare tutto', category: 'Filosofico' },
  { optionA: 'Cambiare il passato', optionB: 'Vedere il futuro', category: 'Filosofico' },
  { optionA: 'Vivere a lungo', optionB: 'Vivere intensamente', category: 'Filosofico' },
  { optionA: 'Testa', optionB: 'Cuore', category: 'Filosofico' },
  { optionA: 'Liberta', optionB: 'Sicurezza', category: 'Filosofico' },
  { optionA: 'Talento', optionB: 'Impegno', category: 'Filosofico' },
  { optionA: 'Verita', optionB: 'Felicita', category: 'Filosofico' },
  { optionA: 'Poter dimenticare', optionB: 'Non dimenticare mai', category: 'Filosofico' },
  { optionA: 'Fama', optionB: 'Anonimato', category: 'Filosofico' },
  { optionA: 'Tanti amici', optionB: 'Un migliore amico', category: 'Filosofico' },
  { optionA: 'Potere', optionB: 'Saggezza', category: 'Filosofico' },
  { optionA: 'Memoria perfetta', optionB: 'Creativita perfetta', category: 'Filosofico' },
  { optionA: 'Avere sempre ragione', optionB: 'Essere sempre felice', category: 'Filosofico' },
  { optionA: 'Solo dare', optionB: 'Solo ricevere', category: 'Filosofico' },
  { optionA: 'Salvare il mondo', optionB: 'Salvare la tua famiglia', category: 'Filosofico' },
  { optionA: 'Successo', optionB: 'Soddisfazione', category: 'Filosofico' },
  { optionA: 'Bellezza', optionB: 'Intelligenza', category: 'Filosofico' },
  { optionA: 'Fiducia', optionB: 'Rispetto', category: 'Filosofico' },
  { optionA: 'Coraggio', optionB: 'Pazienza', category: 'Filosofico' },
  { optionA: 'Conoscere la solitudine', optionB: 'Non essere mai solo', category: 'Filosofico' },
  { optionA: 'Poter sbagliare', optionB: 'Non fallire mai', category: 'Filosofico' },
  { optionA: 'Controllare tutto', optionB: 'Accettare tutto', category: 'Filosofico' },
  { optionA: 'Salute', optionB: 'Ricchezza', category: 'Filosofico' },
  { optionA: 'Passione', optionB: 'Stabilita', category: 'Filosofico' },
  { optionA: 'Sapere tutto ed essere triste', optionB: 'Non sapere nulla ed essere felice', category: 'Filosofico' },
  { optionA: 'Essere indimenticabile', optionB: 'Essere immortale', category: 'Filosofico' },
  { optionA: 'Il passato perfetto', optionB: 'Il futuro perfetto', category: 'Filosofico' },
  { optionA: 'Energia infinita', optionB: 'Tempo infinito', category: 'Filosofico' },
  { optionA: 'Fare solo del bene', optionB: 'Essere solo onesto', category: 'Filosofico' },
  { optionA: 'Perdere tutto e ricominciare', optionB: 'Non poter cambiare nulla', category: 'Filosofico' },
  { optionA: 'Pace interiore', optionB: 'Successo esteriore', category: 'Filosofico' },
  { optionA: 'Essere sempre il migliore', optionB: 'Essere sempre il piu amato', category: 'Filosofico' },
  { optionA: 'Poter aiutare gli altri', optionB: 'Poter aiutare se stessi', category: 'Filosofico' },
  { optionA: 'Sentire tutto', optionB: 'Non sentire nulla', category: 'Filosofico' },
];
