export interface ThisOrThatPair {
  optionA: string;
  optionB: string;
  category: string;
}

export const THISORTHAT_PAIRS: ThisOrThatPair[] = [
  // Food (25)
  { optionA: 'Pizza', optionB: 'Burger', category: 'Food' },
  { optionA: 'Chocolate', optionB: 'Gummy Bears', category: 'Food' },
  { optionA: 'Coffee', optionB: 'Tea', category: 'Food' },
  { optionA: 'Sushi', optionB: 'Steak', category: 'Food' },
  { optionA: 'Ice Cream', optionB: 'Cake', category: 'Food' },
  { optionA: 'Breakfast', optionB: 'Dinner', category: 'Food' },
  { optionA: 'Sweet', optionB: 'Salty', category: 'Food' },
  { optionA: 'Cooking', optionB: 'Ordering in', category: 'Food' },
  { optionA: 'Pasta', optionB: 'Rice', category: 'Food' },
  { optionA: 'Fries', optionB: 'Chips', category: 'Food' },
  { optionA: 'Hot Dog', optionB: 'Taco', category: 'Food' },
  { optionA: 'Water', optionB: 'Soda', category: 'Food' },
  { optionA: 'Pancakes', optionB: 'Waffles', category: 'Food' },
  { optionA: 'Peanut Butter', optionB: 'Nutella', category: 'Food' },
  { optionA: 'Apple', optionB: 'Banana', category: 'Food' },
  { optionA: 'Milk', optionB: 'Oat Milk', category: 'Food' },
  { optionA: 'Salad', optionB: 'Soup', category: 'Food' },
  { optionA: 'Cheese', optionB: 'Ham', category: 'Food' },
  { optionA: 'BBQ', optionB: 'Fondue', category: 'Food' },
  { optionA: 'Popcorn', optionB: 'Nachos', category: 'Food' },
  { optionA: 'Bagel', optionB: 'Croissant', category: 'Food' },
  { optionA: 'Beer', optionB: 'Wine', category: 'Food' },
  { optionA: 'Granola Bar', optionB: 'Candy Bar', category: 'Food' },
  { optionA: 'Frozen Pizza', optionB: 'Delivery Pizza', category: 'Food' },
  { optionA: 'Croissant', optionB: 'Donut', category: 'Food' },
  // Travel (25)
  { optionA: 'Beach', optionB: 'Mountains', category: 'Travel' },
  { optionA: 'Flying', optionB: 'Road Trip', category: 'Travel' },
  { optionA: 'Hotel', optionB: 'Camping', category: 'Travel' },
  { optionA: 'Summer', optionB: 'Winter', category: 'Travel' },
  { optionA: 'Europe', optionB: 'Asia', category: 'Travel' },
  { optionA: 'City Trip', optionB: 'Nature Getaway', category: 'Travel' },
  { optionA: 'Solo Travel', optionB: 'Group Trip', category: 'Travel' },
  { optionA: 'Early Riser', optionB: 'Sleeping In', category: 'Travel' },
  { optionA: 'Backpacking', optionB: 'All-Inclusive', category: 'Travel' },
  { optionA: 'Cruise', optionB: 'Safari', category: 'Travel' },
  { optionA: 'New York', optionB: 'Tokyo', category: 'Travel' },
  { optionA: 'Desert', optionB: 'Rainforest', category: 'Travel' },
  { optionA: 'Train Journey', optionB: 'Cruise', category: 'Travel' },
  { optionA: 'Adventure', optionB: 'Relaxation', category: 'Travel' },
  { optionA: 'Spain', optionB: 'Italy', category: 'Travel' },
  { optionA: 'Ski Vacation', optionB: 'Surf Vacation', category: 'Travel' },
  { optionA: 'Spring', optionB: 'Fall', category: 'Travel' },
  { optionA: 'Northern Lights', optionB: 'Ocean Sunset', category: 'Travel' },
  { optionA: 'Theme Park', optionB: 'Spa', category: 'Travel' },
  { optionA: 'Hostel', optionB: 'Airbnb', category: 'Travel' },
  { optionA: 'Suitcase', optionB: 'Backpack', category: 'Travel' },
  { optionA: 'Window Seat', optionB: 'Aisle Seat', category: 'Travel' },
  { optionA: 'Book Early', optionB: 'Last Minute', category: 'Travel' },
  { optionA: 'Scuba Diving', optionB: 'Hiking', category: 'Travel' },
  { optionA: 'Venice', optionB: 'Paris', category: 'Travel' },
  // Lifestyle (25)
  { optionA: 'Netflix', optionB: 'YouTube', category: 'Lifestyle' },
  { optionA: 'Morning Person', optionB: 'Night Owl', category: 'Lifestyle' },
  { optionA: 'Dog', optionB: 'Cat', category: 'Lifestyle' },
  { optionA: 'iPhone', optionB: 'Android', category: 'Lifestyle' },
  { optionA: 'Instagram', optionB: 'TikTok', category: 'Lifestyle' },
  { optionA: 'Read a Book', optionB: 'Listen to a Podcast', category: 'Lifestyle' },
  { optionA: 'Gym', optionB: 'Jogging', category: 'Lifestyle' },
  { optionA: 'City', optionB: 'Countryside', category: 'Lifestyle' },
  { optionA: 'Cash', optionB: 'Card Payment', category: 'Lifestyle' },
  { optionA: 'Early to Bed', optionB: 'Night Owl', category: 'Lifestyle' },
  { optionA: 'Online Shopping', optionB: 'In-Store Shopping', category: 'Lifestyle' },
  { optionA: 'Listen to Music', optionB: 'Watch Shows', category: 'Lifestyle' },
  { optionA: 'Bath', optionB: 'Shower', category: 'Lifestyle' },
  { optionA: 'Sneakers', optionB: 'Dress Shoes', category: 'Lifestyle' },
  { optionA: 'Minimalist', optionB: 'Collector', category: 'Lifestyle' },
  { optionA: 'Extrovert', optionB: 'Introvert', category: 'Lifestyle' },
  { optionA: 'Planner', optionB: 'Spontaneous', category: 'Lifestyle' },
  { optionA: 'Video Games', optionB: 'Board Games', category: 'Lifestyle' },
  { optionA: 'Festival', optionB: 'Concert', category: 'Lifestyle' },
  { optionA: 'Roommates', optionB: 'Living Alone', category: 'Lifestyle' },
  { optionA: 'Learn to Cook', optionB: 'Learn an Instrument', category: 'Lifestyle' },
  { optionA: 'Tattoo', optionB: 'Piercing', category: 'Lifestyle' },
  { optionA: 'Work from Home', optionB: 'Office', category: 'Lifestyle' },
  { optionA: 'Spotify', optionB: 'Apple Music', category: 'Lifestyle' },
  { optionA: 'Play Sports', optionB: 'Watch Sports', category: 'Lifestyle' },
  // Funny (25)
  { optionA: 'No Chocolate Ever Again', optionB: 'No Cheese Ever Again', category: 'Funny' },
  { optionA: 'Always Too Early', optionB: 'Always Too Late', category: 'Funny' },
  { optionA: 'Be Invisible', optionB: 'Be Able to Fly', category: 'Funny' },
  { optionA: 'Read Minds', optionB: 'Time Travel', category: 'Funny' },
  { optionA: 'No Phone', optionB: 'No Sleep', category: 'Funny' },
  { optionA: '10 Dogs', optionB: '10 Cats', category: 'Funny' },
  { optionA: 'Always Shout', optionB: 'Always Whisper', category: 'Funny' },
  { optionA: 'No Pizza Ever Again', optionB: 'No Music Ever Again', category: 'Funny' },
  { optionA: 'Zombie Apocalypse', optionB: 'Alien Invasion', category: 'Funny' },
  { optionA: 'Be a Giant', optionB: 'Be Tiny', category: 'Funny' },
  { optionA: 'Live in the Past', optionB: 'Live in the Future', category: 'Funny' },
  { optionA: 'Live on the Moon', optionB: 'Live Under Water', category: 'Funny' },
  { optionA: 'Only Sing Instead of Talk', optionB: 'Only Dance Instead of Walk', category: 'Funny' },
  { optionA: 'Super Strength', optionB: 'Super Speed', category: 'Funny' },
  { optionA: 'Stay Young Forever', optionB: 'Be Infinitely Rich', category: 'Funny' },
  { optionA: 'Always Tell the Truth', optionB: 'Always Lie', category: 'Funny' },
  { optionA: 'No Arms', optionB: 'No Legs', category: 'Funny' },
  { optionA: 'Only Cold Food', optionB: 'Only Warm Drinks', category: 'Funny' },
  { optionA: 'Walk Backwards', optionB: 'Speak Backwards', category: 'Funny' },
  { optionA: 'Famous Musician', optionB: 'Famous Actor', category: 'Funny' },
  { optionA: 'Live in a Movie', optionB: 'Live in a Video Game', category: 'Funny' },
  { optionA: 'No Internet for a Year', optionB: 'No Phone for a Year', category: 'Funny' },
  { optionA: 'Rain Every Day', optionB: '100 Degrees Every Day', category: 'Funny' },
  { optionA: 'Always Monday', optionB: 'Always Sunday', category: 'Funny' },
  { optionA: 'Endless Vacation', optionB: 'Dream Job', category: 'Funny' },
  // Philosophical (25)
  { optionA: 'Love Without Money', optionB: 'Money Without Love', category: 'Philosophical' },
  { optionA: 'Know Everything', optionB: 'Be Able to Do Everything', category: 'Philosophical' },
  { optionA: 'Change the Past', optionB: 'See the Future', category: 'Philosophical' },
  { optionA: 'Long Life', optionB: 'Intense Life', category: 'Philosophical' },
  { optionA: 'Head', optionB: 'Heart', category: 'Philosophical' },
  { optionA: 'Freedom', optionB: 'Security', category: 'Philosophical' },
  { optionA: 'Talent', optionB: 'Hard Work', category: 'Philosophical' },
  { optionA: 'Truth', optionB: 'Happiness', category: 'Philosophical' },
  { optionA: 'Able to Forget', optionB: 'Never Forget', category: 'Philosophical' },
  { optionA: 'Fame', optionB: 'Anonymity', category: 'Philosophical' },
  { optionA: 'Many Friends', optionB: 'One Best Friend', category: 'Philosophical' },
  { optionA: 'Power', optionB: 'Wisdom', category: 'Philosophical' },
  { optionA: 'Perfect Memory', optionB: 'Perfect Creativity', category: 'Philosophical' },
  { optionA: 'Always Be Right', optionB: 'Always Be Happy', category: 'Philosophical' },
  { optionA: 'Only Give', optionB: 'Only Take', category: 'Philosophical' },
  { optionA: 'Save the World', optionB: 'Save Your Family', category: 'Philosophical' },
  { optionA: 'Success', optionB: 'Contentment', category: 'Philosophical' },
  { optionA: 'Beauty', optionB: 'Intelligence', category: 'Philosophical' },
  { optionA: 'Trust', optionB: 'Respect', category: 'Philosophical' },
  { optionA: 'Courage', optionB: 'Patience', category: 'Philosophical' },
  { optionA: 'Know Loneliness', optionB: 'Never Be Alone', category: 'Philosophical' },
  { optionA: 'Be Allowed to Fail', optionB: 'Never Fail', category: 'Philosophical' },
  { optionA: 'Control Everything', optionB: 'Accept Everything', category: 'Philosophical' },
  { optionA: 'Health', optionB: 'Wealth', category: 'Philosophical' },
  { optionA: 'Passion', optionB: 'Stability', category: 'Philosophical' },

  // New Pairs (60)
  // Food (10)
  { optionA: 'Breakfast in Bed', optionB: 'Breakfast at the Table', category: 'Food' },
  { optionA: 'Spicy Food', optionB: 'Mild Food', category: 'Food' },
  { optionA: 'Home-Cooked', optionB: 'Restaurant', category: 'Food' },
  { optionA: 'Whole Wheat', optionB: 'White Bread', category: 'Food' },
  { optionA: 'Gummy Bears', optionB: 'Licorice', category: 'Food' },
  { optionA: 'Smoothie', optionB: 'Fresh Juice', category: 'Food' },
  { optionA: 'Brunch', optionB: 'Midnight Snack', category: 'Food' },
  { optionA: 'Asian', optionB: 'Italian', category: 'Food' },
  { optionA: 'Curry', optionB: 'Pasta', category: 'Food' },
  { optionA: 'Vegetarian', optionB: 'Meat Lover', category: 'Food' },
  // Travel (10)
  { optionA: 'Beach Bar', optionB: 'Mountain Lodge', category: 'Travel' },
  { optionA: 'Sunrise', optionB: 'Sunset', category: 'Travel' },
  { optionA: 'Hidden Gem', optionB: 'Tourist Hotspot', category: 'Travel' },
  { optionA: 'Camper Van', optionB: 'Luxury Hotel', category: 'Travel' },
  { optionA: 'Jungle Adventure', optionB: 'Desert Safari', category: 'Travel' },
  { optionA: 'Caribbean', optionB: 'Scandinavia', category: 'Travel' },
  { optionA: 'Night Train', optionB: 'Red-Eye Flight', category: 'Travel' },
  { optionA: 'Cultural Trip', optionB: 'Party Trip', category: 'Travel' },
  { optionA: 'Iceland', optionB: 'Hawaii', category: 'Travel' },
  { optionA: 'Camping by the Lake', optionB: 'Treehouse in the Woods', category: 'Travel' },
  // Lifestyle (15)
  { optionA: 'Electric Car', optionB: 'Classic Car', category: 'Lifestyle' },
  { optionA: 'Wake Up Early', optionB: 'Stay Up Late', category: 'Lifestyle' },
  { optionA: 'Cinema', optionB: 'Theater', category: 'Lifestyle' },
  { optionA: 'Book', optionB: 'Audiobook', category: 'Lifestyle' },
  { optionA: 'Live Concert', optionB: 'Festival', category: 'Lifestyle' },
  { optionA: 'Yoga', optionB: 'CrossFit', category: 'Lifestyle' },
  { optionA: 'Self-Employed', optionB: 'Employee', category: 'Lifestyle' },
  { optionA: 'Big City', optionB: 'Small Town', category: 'Lifestyle' },
  { optionA: 'Pet', optionB: 'House Plant', category: 'Lifestyle' },
  { optionA: 'Analog', optionB: 'Digital', category: 'Lifestyle' },
  { optionA: 'Handwritten', optionB: 'Typed', category: 'Lifestyle' },
  { optionA: 'Early Retirement', optionB: 'Dream Job Forever', category: 'Lifestyle' },
  { optionA: 'Summer Person', optionB: 'Winter Person', category: 'Lifestyle' },
  { optionA: 'Messy Desk', optionB: 'Tidy Desk', category: 'Lifestyle' },
  { optionA: 'Being Loud', optionB: 'Being Quiet', category: 'Lifestyle' },
  // Funny (15)
  { optionA: 'Teleportation', optionB: 'Time Travel', category: 'Funny' },
  { optionA: 'Only Fly', optionB: 'Breathe Underwater', category: 'Funny' },
  { optionA: 'Forget Everything', optionB: 'Remember Everything', category: 'Funny' },
  { optionA: 'Never Sleep Again', optionB: 'Never Eat Again', category: 'Funny' },
  { optionA: 'Talk to Animals', optionB: 'Speak Every Language', category: 'Funny' },
  { optionA: 'Live in a Musical', optionB: 'Live in a Horror Movie', category: 'Funny' },
  { optionA: 'Always Summer', optionB: 'Always Autumn', category: 'Funny' },
  { optionA: 'Huge House', optionB: 'Tiny Beach House', category: 'Funny' },
  { optionA: '100 Ducks', optionB: '1 Horse-Sized Duck', category: 'Funny' },
  { optionA: 'Live in the Stone Age', optionB: 'Live in the Year 3000', category: 'Funny' },
  { optionA: 'Be a Superhero', optionB: 'Be a Supervillain', category: 'Funny' },
  { optionA: 'Always the Right Outfit', optionB: 'Always the Right Food', category: 'Funny' },
  { optionA: 'Everything in Slow Motion', optionB: 'Everything in Fast Forward', category: 'Funny' },
  { optionA: 'Never Cook Again', optionB: 'Never Clean Again', category: 'Funny' },
  { optionA: 'Set a World Record', optionB: 'Win the Lottery', category: 'Funny' },
  // Philosophical (10)
  { optionA: 'Know Everything and Be Sad', optionB: 'Know Nothing and Be Happy', category: 'Philosophical' },
  { optionA: 'Be Unforgettable', optionB: 'Be Immortal', category: 'Philosophical' },
  { optionA: 'The Perfect Past', optionB: 'The Perfect Future', category: 'Philosophical' },
  { optionA: 'Infinite Energy', optionB: 'Infinite Time', category: 'Philosophical' },
  { optionA: 'Only Do Good', optionB: 'Only Be Honest', category: 'Philosophical' },
  { optionA: 'Lose Everything and Start Over', optionB: 'Never Change Anything', category: 'Philosophical' },
  { optionA: 'Inner Peace', optionB: 'External Success', category: 'Philosophical' },
  { optionA: 'Always Be the Best', optionB: 'Always Be the Most Liked', category: 'Philosophical' },
  { optionA: 'Help Others', optionB: 'Help Yourself', category: 'Philosophical' },
  { optionA: 'Feel Everything', optionB: 'Feel Nothing', category: 'Philosophical' },
];
