export interface ThisOrThatPair {
  optionA: string;
  optionB: string;
  category: string;
}

export const THISORTHAT_PAIRS_NL: ThisOrThatPair[] = [
  // Eten (35)
  { optionA: 'Pizza', optionB: 'Hamburger', category: 'Eten' },
  { optionA: 'Chocolade', optionB: 'Snoep', category: 'Eten' },
  { optionA: 'Koffie', optionB: 'Thee', category: 'Eten' },
  { optionA: 'Sushi', optionB: 'Biefstuk', category: 'Eten' },
  { optionA: 'IJs', optionB: 'Taart', category: 'Eten' },
  { optionA: 'Ontbijt', optionB: 'Avondeten', category: 'Eten' },
  { optionA: 'Zoet', optionB: 'Zout', category: 'Eten' },
  { optionA: 'Koken', optionB: 'Bestellen', category: 'Eten' },
  { optionA: 'Pasta', optionB: 'Rijst', category: 'Eten' },
  { optionA: 'Patat', optionB: 'Chips', category: 'Eten' },
  { optionA: 'Kroket', optionB: 'Frikandel', category: 'Eten' },
  { optionA: 'Water', optionB: 'Limonade', category: 'Eten' },
  { optionA: 'Pannenkoeken', optionB: 'Wafels', category: 'Eten' },
  { optionA: 'Pindakaas', optionB: 'Nutella', category: 'Eten' },
  { optionA: 'Appel', optionB: 'Banaan', category: 'Eten' },
  { optionA: 'Melk', optionB: 'Havermelk', category: 'Eten' },
  { optionA: 'Salade', optionB: 'Soep', category: 'Eten' },
  { optionA: 'Kaas', optionB: 'Ham', category: 'Eten' },
  { optionA: 'Barbecue', optionB: 'Fondue', category: 'Eten' },
  { optionA: 'Popcorn', optionB: 'Nachos', category: 'Eten' },
  { optionA: 'Stroopwafel', optionB: 'Croissant', category: 'Eten' },
  { optionA: 'Bier', optionB: 'Wijn', category: 'Eten' },
  { optionA: 'Mueslireep', optionB: 'Chocoladereep', category: 'Eten' },
  { optionA: 'Diepvriespizza', optionB: 'Bezorgpizza', category: 'Eten' },
  { optionA: 'Croissant', optionB: 'Donut', category: 'Eten' },
  { optionA: 'Ontbijt op bed', optionB: 'Ontbijt aan tafel', category: 'Eten' },
  { optionA: 'Pittig eten', optionB: 'Mild eten', category: 'Eten' },
  { optionA: 'Zelfgekookt', optionB: 'Restaurant', category: 'Eten' },
  { optionA: 'Volkoren', optionB: 'Wit brood', category: 'Eten' },
  { optionA: 'Smoothie', optionB: 'Vers geperst sap', category: 'Eten' },
  { optionA: 'Brunch', optionB: 'Middernachtsnack', category: 'Eten' },
  { optionA: 'Aziatisch', optionB: 'Italiaans', category: 'Eten' },
  { optionA: 'Curry', optionB: 'Pasta', category: 'Eten' },
  { optionA: 'Vegetarisch', optionB: 'Vleesliefhebber', category: 'Eten' },
  { optionA: 'Drop', optionB: 'Winegums', category: 'Eten' },
  // Reizen (35)
  { optionA: 'Strand', optionB: 'Bergen', category: 'Reizen' },
  { optionA: 'Vliegen', optionB: 'Roadtrip', category: 'Reizen' },
  { optionA: 'Hotel', optionB: 'Kamperen', category: 'Reizen' },
  { optionA: 'Zomer', optionB: 'Winter', category: 'Reizen' },
  { optionA: 'Europa', optionB: 'Azie', category: 'Reizen' },
  { optionA: 'Stedentrip', optionB: 'Natuurvakantie', category: 'Reizen' },
  { optionA: 'Alleen reizen', optionB: 'Groepsreis', category: 'Reizen' },
  { optionA: 'Vroeg opstaan', optionB: 'Uitslapen', category: 'Reizen' },
  { optionA: 'Backpacken', optionB: 'All-Inclusive', category: 'Reizen' },
  { optionA: 'Cruise', optionB: 'Safari', category: 'Reizen' },
  { optionA: 'New York', optionB: 'Tokio', category: 'Reizen' },
  { optionA: 'Woestijn', optionB: 'Regenwoud', category: 'Reizen' },
  { optionA: 'Treinreis', optionB: 'Bootreis', category: 'Reizen' },
  { optionA: 'Avontuur', optionB: 'Ontspanning', category: 'Reizen' },
  { optionA: 'Spanje', optionB: 'Italie', category: 'Reizen' },
  { optionA: 'Skivakantie', optionB: 'Surfvakantie', category: 'Reizen' },
  { optionA: 'Lente', optionB: 'Herfst', category: 'Reizen' },
  { optionA: 'Noorderlicht', optionB: 'Zonsondergang aan zee', category: 'Reizen' },
  { optionA: 'Pretpark', optionB: 'Wellness', category: 'Reizen' },
  { optionA: 'Hostel', optionB: 'Airbnb', category: 'Reizen' },
  { optionA: 'Koffer', optionB: 'Rugzak', category: 'Reizen' },
  { optionA: 'Raamplek', optionB: 'Gangpad', category: 'Reizen' },
  { optionA: 'Vroeg boeken', optionB: 'Last Minute', category: 'Reizen' },
  { optionA: 'Duiken', optionB: 'Wandelen', category: 'Reizen' },
  { optionA: 'Venetie', optionB: 'Parijs', category: 'Reizen' },
  { optionA: 'Strandbar', optionB: 'Berghut', category: 'Reizen' },
  { optionA: 'Zonsopgang', optionB: 'Zonsondergang', category: 'Reizen' },
  { optionA: 'Verborgen parel', optionB: 'Toeristische trekpleister', category: 'Reizen' },
  { optionA: 'Camper', optionB: 'Luxe hotel', category: 'Reizen' },
  { optionA: 'Jungle-avontuur', optionB: 'Woestijnsafari', category: 'Reizen' },
  { optionA: 'Caribisch', optionB: 'Scandinavie', category: 'Reizen' },
  { optionA: 'Nachttrein', optionB: 'Nachtvlucht', category: 'Reizen' },
  { optionA: 'Cultuurreis', optionB: 'Feestreis', category: 'Reizen' },
  { optionA: 'IJsland', optionB: 'Hawaii', category: 'Reizen' },
  { optionA: 'Kamperen bij het meer', optionB: 'Boomhut in het bos', category: 'Reizen' },
  // Leefstijl (40)
  { optionA: 'Netflix', optionB: 'YouTube', category: 'Leefstijl' },
  { optionA: 'Ochtendmens', optionB: 'Nachtmens', category: 'Leefstijl' },
  { optionA: 'Hond', optionB: 'Kat', category: 'Leefstijl' },
  { optionA: 'iPhone', optionB: 'Android', category: 'Leefstijl' },
  { optionA: 'Instagram', optionB: 'TikTok', category: 'Leefstijl' },
  { optionA: 'Boek lezen', optionB: 'Podcast luisteren', category: 'Leefstijl' },
  { optionA: 'Sportschool', optionB: 'Hardlopen', category: 'Leefstijl' },
  { optionA: 'Stad', optionB: 'Platteland', category: 'Leefstijl' },
  { optionA: 'Contant', optionB: 'Pinnen', category: 'Leefstijl' },
  { optionA: 'Vroeg naar bed', optionB: 'Nachtbraker', category: 'Leefstijl' },
  { optionA: 'Online shoppen', optionB: 'In de winkel kopen', category: 'Leefstijl' },
  { optionA: 'Muziek luisteren', optionB: 'Series kijken', category: 'Leefstijl' },
  { optionA: 'Bad', optionB: 'Douche', category: 'Leefstijl' },
  { optionA: 'Sneakers', optionB: 'Nette schoenen', category: 'Leefstijl' },
  { optionA: 'Minimalist', optionB: 'Verzamelaar', category: 'Leefstijl' },
  { optionA: 'Extravert', optionB: 'Introvert', category: 'Leefstijl' },
  { optionA: 'Plannen', optionB: 'Spontaan', category: 'Leefstijl' },
  { optionA: 'Videogames', optionB: 'Bordspellen', category: 'Leefstijl' },
  { optionA: 'Festival', optionB: 'Concert', category: 'Leefstijl' },
  { optionA: 'Samenwonen', optionB: 'Alleen wonen', category: 'Leefstijl' },
  { optionA: 'Leren koken', optionB: 'Instrument leren', category: 'Leefstijl' },
  { optionA: 'Tatoeage', optionB: 'Piercing', category: 'Leefstijl' },
  { optionA: 'Thuiswerken', optionB: 'Kantoor', category: 'Leefstijl' },
  { optionA: 'Spotify', optionB: 'Apple Music', category: 'Leefstijl' },
  { optionA: 'Sporten', optionB: 'Sport kijken', category: 'Leefstijl' },
  { optionA: 'Elektrische auto', optionB: 'Oldtimer', category: 'Leefstijl' },
  { optionA: 'Vroeg op', optionB: 'Laat naar bed', category: 'Leefstijl' },
  { optionA: 'Bioscoop', optionB: 'Theater', category: 'Leefstijl' },
  { optionA: 'Boek', optionB: 'Luisterboek', category: 'Leefstijl' },
  { optionA: 'Liveconcert', optionB: 'Festival', category: 'Leefstijl' },
  { optionA: 'Yoga', optionB: 'Crossfit', category: 'Leefstijl' },
  { optionA: 'Zelfstandig', optionB: 'In loondienst', category: 'Leefstijl' },
  { optionA: 'Grote stad', optionB: 'Klein stadje', category: 'Leefstijl' },
  { optionA: 'Huisdier', optionB: 'Kamerplant', category: 'Leefstijl' },
  { optionA: 'Analoog', optionB: 'Digitaal', category: 'Leefstijl' },
  { optionA: 'Handgeschreven', optionB: 'Getypt', category: 'Leefstijl' },
  { optionA: 'Vroegpensioen', optionB: 'Droombaan voor altijd', category: 'Leefstijl' },
  { optionA: 'Zomertype', optionB: 'Wintertype', category: 'Leefstijl' },
  { optionA: 'Rommelig bureau', optionB: 'Opgeruimd bureau', category: 'Leefstijl' },
  { optionA: 'Luid zijn', optionB: 'Stil zijn', category: 'Leefstijl' },
  // Grappig (40)
  { optionA: 'Nooit meer chocolade', optionB: 'Nooit meer kaas', category: 'Grappig' },
  { optionA: 'Altijd te vroeg', optionB: 'Altijd te laat', category: 'Grappig' },
  { optionA: 'Onzichtbaar zijn', optionB: 'Kunnen vliegen', category: 'Grappig' },
  { optionA: 'Gedachten lezen', optionB: 'Tijdreizen', category: 'Grappig' },
  { optionA: 'Zonder telefoon', optionB: 'Zonder slaap', category: 'Grappig' },
  { optionA: '10 honden', optionB: '10 katten', category: 'Grappig' },
  { optionA: 'Altijd hard praten', optionB: 'Altijd fluisteren', category: 'Grappig' },
  { optionA: 'Nooit meer pizza', optionB: 'Nooit meer muziek', category: 'Grappig' },
  { optionA: 'Zombie-apocalyps', optionB: 'Alien-invasie', category: 'Grappig' },
  { optionA: 'Een reus zijn', optionB: 'Een dwerg zijn', category: 'Grappig' },
  { optionA: 'In het verleden leven', optionB: 'In de toekomst leven', category: 'Grappig' },
  { optionA: 'Op de maan wonen', optionB: 'Onder water wonen', category: 'Grappig' },
  { optionA: 'Alleen zingen in plaats van praten', optionB: 'Alleen dansen in plaats van lopen', category: 'Grappig' },
  { optionA: 'Superkracht: supersterk', optionB: 'Superkracht: supersnel', category: 'Grappig' },
  { optionA: 'Eeuwig jong blijven', optionB: 'Oneindig rijk zijn', category: 'Grappig' },
  { optionA: 'Altijd de waarheid zeggen', optionB: 'Altijd liegen', category: 'Grappig' },
  { optionA: 'Alleen koud eten', optionB: 'Alleen warme dranken', category: 'Grappig' },
  { optionA: 'Achteruit lopen', optionB: 'Alles achterstevoren zeggen', category: 'Grappig' },
  { optionA: 'Beroemde muzikant', optionB: 'Beroemde acteur', category: 'Grappig' },
  { optionA: 'In een film leven', optionB: 'In een videogame leven', category: 'Grappig' },
  { optionA: 'Geen internet voor 1 jaar', optionB: 'Geen telefoon voor 1 jaar', category: 'Grappig' },
  { optionA: 'Elke dag regen', optionB: 'Elke dag 40 graden', category: 'Grappig' },
  { optionA: 'Altijd maandag', optionB: 'Altijd zondag', category: 'Grappig' },
  { optionA: 'Oneindige vakantie', optionB: 'Droombaan', category: 'Grappig' },
  { optionA: 'Teleportatie', optionB: 'Tijdreizen', category: 'Grappig' },
  { optionA: 'Alleen maar vliegen', optionB: 'Onder water ademen', category: 'Grappig' },
  { optionA: 'Alles vergeten', optionB: 'Alles onthouden', category: 'Grappig' },
  { optionA: 'Nooit meer hoeven slapen', optionB: 'Nooit meer hoeven eten', category: 'Grappig' },
  { optionA: 'Met dieren praten', optionB: 'Alle talen spreken', category: 'Grappig' },
  { optionA: 'In een musical leven', optionB: 'In een horrorfilm leven', category: 'Grappig' },
  { optionA: 'Altijd zomer', optionB: 'Altijd herfst', category: 'Grappig' },
  { optionA: 'Reusachtig huis', optionB: 'Klein huisje op het strand', category: 'Grappig' },
  { optionA: '100 eenden', optionB: '1 paard zo groot als een eend', category: 'Grappig' },
  { optionA: 'In de steentijd leven', optionB: 'In het jaar 3000 leven', category: 'Grappig' },
  { optionA: 'Superheld zijn', optionB: 'Superschurk zijn', category: 'Grappig' },
  { optionA: 'Altijd de juiste outfit', optionB: 'Altijd het juiste eten', category: 'Grappig' },
  { optionA: 'Alles in slow motion', optionB: 'Alles in fast forward', category: 'Grappig' },
  { optionA: 'Nooit meer koken', optionB: 'Nooit meer schoonmaken', category: 'Grappig' },
  { optionA: 'Wereldrecord', optionB: 'Loterij winnen', category: 'Grappig' },
  { optionA: 'Geen armen', optionB: 'Geen benen', category: 'Grappig' },
  // Filosofisch (35)
  { optionA: 'Liefde zonder geld', optionB: 'Geld zonder liefde', category: 'Filosofisch' },
  { optionA: 'Alles weten', optionB: 'Alles kunnen', category: 'Filosofisch' },
  { optionA: 'Het verleden veranderen', optionB: 'De toekomst zien', category: 'Filosofisch' },
  { optionA: 'Lang leven', optionB: 'Intens leven', category: 'Filosofisch' },
  { optionA: 'Hoofd', optionB: 'Hart', category: 'Filosofisch' },
  { optionA: 'Vrijheid', optionB: 'Zekerheid', category: 'Filosofisch' },
  { optionA: 'Talent', optionB: 'Inzet', category: 'Filosofisch' },
  { optionA: 'Waarheid', optionB: 'Geluk', category: 'Filosofisch' },
  { optionA: 'Kunnen vergeten', optionB: 'Niets vergeten', category: 'Filosofisch' },
  { optionA: 'Beroemdheid', optionB: 'Anonimiteit', category: 'Filosofisch' },
  { optionA: 'Veel vrienden', optionB: 'Een beste vriend', category: 'Filosofisch' },
  { optionA: 'Macht', optionB: 'Wijsheid', category: 'Filosofisch' },
  { optionA: 'Perfect geheugen', optionB: 'Perfecte creativiteit', category: 'Filosofisch' },
  { optionA: 'Altijd gelijk hebben', optionB: 'Altijd gelukkig zijn', category: 'Filosofisch' },
  { optionA: 'Alleen geven', optionB: 'Alleen nemen', category: 'Filosofisch' },
  { optionA: 'De wereld redden', optionB: 'Je familie redden', category: 'Filosofisch' },
  { optionA: 'Succes', optionB: 'Tevredenheid', category: 'Filosofisch' },
  { optionA: 'Schoonheid', optionB: 'Intelligentie', category: 'Filosofisch' },
  { optionA: 'Vertrouwen', optionB: 'Respect', category: 'Filosofisch' },
  { optionA: 'Moed', optionB: 'Geduld', category: 'Filosofisch' },
  { optionA: 'Eenzaamheid kennen', optionB: 'Nooit alleen zijn', category: 'Filosofisch' },
  { optionA: 'Fouten mogen maken', optionB: 'Nooit falen', category: 'Filosofisch' },
  { optionA: 'Alles controleren', optionB: 'Alles accepteren', category: 'Filosofisch' },
  { optionA: 'Gezondheid', optionB: 'Rijkdom', category: 'Filosofisch' },
  { optionA: 'Passie', optionB: 'Stabiliteit', category: 'Filosofisch' },
  { optionA: 'Alles weten en verdrietig zijn', optionB: 'Niets weten en gelukkig zijn', category: 'Filosofisch' },
  { optionA: 'Onvergetelijk zijn', optionB: 'Onsterfelijk zijn', category: 'Filosofisch' },
  { optionA: 'Het perfecte verleden', optionB: 'De perfecte toekomst', category: 'Filosofisch' },
  { optionA: 'Oneindige energie', optionB: 'Oneindige tijd', category: 'Filosofisch' },
  { optionA: 'Alleen goed doen', optionB: 'Alleen eerlijk zijn', category: 'Filosofisch' },
  { optionA: 'Alles verliezen en opnieuw beginnen', optionB: 'Niets mogen veranderen', category: 'Filosofisch' },
  { optionA: 'Innerlijke rust', optionB: 'Uiterlijk succes', category: 'Filosofisch' },
  { optionA: 'Altijd de beste zijn', optionB: 'Altijd de populairste zijn', category: 'Filosofisch' },
  { optionA: 'Anderen kunnen helpen', optionB: 'Jezelf kunnen helpen', category: 'Filosofisch' },
  { optionA: 'Alles voelen', optionB: 'Niets voelen', category: 'Filosofisch' },
];
