export interface ThisOrThatPair {
  optionA: string;
  optionB: string;
  category: string;
}

export const THISORTHAT_PAIRS: ThisOrThatPair[] = [
  // Essen (25)
  { optionA: 'Pizza', optionB: 'Burger', category: 'Essen' },
  { optionA: 'Schokolade', optionB: 'Gummibaerchen', category: 'Essen' },
  { optionA: 'Kaffee', optionB: 'Tee', category: 'Essen' },
  { optionA: 'Sushi', optionB: 'Steak', category: 'Essen' },
  { optionA: 'Eis', optionB: 'Kuchen', category: 'Essen' },
  { optionA: 'Fruehstueck', optionB: 'Abendessen', category: 'Essen' },
  { optionA: 'Suess', optionB: 'Salzig', category: 'Essen' },
  { optionA: 'Kochen', optionB: 'Bestellen', category: 'Essen' },
  { optionA: 'Pasta', optionB: 'Reis', category: 'Essen' },
  { optionA: 'Pommes', optionB: 'Chips', category: 'Essen' },
  { optionA: 'Doener', optionB: 'Currywurst', category: 'Essen' },
  { optionA: 'Wasser', optionB: 'Limonade', category: 'Essen' },
  { optionA: 'Pfannkuchen', optionB: 'Waffeln', category: 'Essen' },
  { optionA: 'Erdnussbutter', optionB: 'Nutella', category: 'Essen' },
  { optionA: 'Apfel', optionB: 'Banane', category: 'Essen' },
  { optionA: 'Milch', optionB: 'Hafermilch', category: 'Essen' },
  { optionA: 'Salat', optionB: 'Suppe', category: 'Essen' },
  { optionA: 'Kaese', optionB: 'Schinken', category: 'Essen' },
  { optionA: 'Grillen', optionB: 'Fondue', category: 'Essen' },
  { optionA: 'Popcorn', optionB: 'Nachos', category: 'Essen' },
  { optionA: 'Brezel', optionB: 'Croissant', category: 'Essen' },
  { optionA: 'Bier', optionB: 'Wein', category: 'Essen' },
  { optionA: 'Muesliriegel', optionB: 'Schokoriegel', category: 'Essen' },
  { optionA: 'Tiefkuehlpizza', optionB: 'Lieferpizza', category: 'Essen' },
  { optionA: 'Croissant', optionB: 'Donut', category: 'Essen' },
  // Reisen (25)
  { optionA: 'Strand', optionB: 'Berge', category: 'Reisen' },
  { optionA: 'Fliegen', optionB: 'Roadtrip', category: 'Reisen' },
  { optionA: 'Hotel', optionB: 'Camping', category: 'Reisen' },
  { optionA: 'Sommer', optionB: 'Winter', category: 'Reisen' },
  { optionA: 'Europa', optionB: 'Asien', category: 'Reisen' },
  { optionA: 'Staedtetrip', optionB: 'Natururlaub', category: 'Reisen' },
  { optionA: 'Allein reisen', optionB: 'Gruppenreise', category: 'Reisen' },
  { optionA: 'Frueh aufstehen', optionB: 'Ausschlafen', category: 'Reisen' },
  { optionA: 'Backpacking', optionB: 'All-Inclusive', category: 'Reisen' },
  { optionA: 'Kreuzfahrt', optionB: 'Safari', category: 'Reisen' },
  { optionA: 'New York', optionB: 'Tokio', category: 'Reisen' },
  { optionA: 'Wueste', optionB: 'Regenwald', category: 'Reisen' },
  { optionA: 'Zugfahrt', optionB: 'Schiffsreise', category: 'Reisen' },
  { optionA: 'Abenteuer', optionB: 'Entspannung', category: 'Reisen' },
  { optionA: 'Spanien', optionB: 'Italien', category: 'Reisen' },
  { optionA: 'Skiurlaub', optionB: 'Surfurlaub', category: 'Reisen' },
  { optionA: 'Fruehling', optionB: 'Herbst', category: 'Reisen' },
  { optionA: 'Nordlichter', optionB: 'Sonnenuntergang am Meer', category: 'Reisen' },
  { optionA: 'Freizeitpark', optionB: 'Wellness', category: 'Reisen' },
  { optionA: 'Hostel', optionB: 'Airbnb', category: 'Reisen' },
  { optionA: 'Koffer', optionB: 'Rucksack', category: 'Reisen' },
  { optionA: 'Fensterplatz', optionB: 'Gangplatz', category: 'Reisen' },
  { optionA: 'Frueh buchen', optionB: 'Last Minute', category: 'Reisen' },
  { optionA: 'Tauchen', optionB: 'Wandern', category: 'Reisen' },
  { optionA: 'Venedig', optionB: 'Paris', category: 'Reisen' },
  // Lifestyle (25)
  { optionA: 'Netflix', optionB: 'YouTube', category: 'Lifestyle' },
  { optionA: 'Morgenmensch', optionB: 'Nachtmensch', category: 'Lifestyle' },
  { optionA: 'Hund', optionB: 'Katze', category: 'Lifestyle' },
  { optionA: 'iPhone', optionB: 'Android', category: 'Lifestyle' },
  { optionA: 'Instagram', optionB: 'TikTok', category: 'Lifestyle' },
  { optionA: 'Buch lesen', optionB: 'Podcast hoeren', category: 'Lifestyle' },
  { optionA: 'Fitnessstudio', optionB: 'Joggen', category: 'Lifestyle' },
  { optionA: 'Stadt', optionB: 'Land', category: 'Lifestyle' },
  { optionA: 'Bargeld', optionB: 'Kartenzahlung', category: 'Lifestyle' },
  { optionA: 'Frueh ins Bett', optionB: 'Nachtschwaermer', category: 'Lifestyle' },
  { optionA: 'Online-Shopping', optionB: 'Im Laden kaufen', category: 'Lifestyle' },
  { optionA: 'Musik hoeren', optionB: 'Serien schauen', category: 'Lifestyle' },
  { optionA: 'Badewanne', optionB: 'Dusche', category: 'Lifestyle' },
  { optionA: 'Sneaker', optionB: 'Elegante Schuhe', category: 'Lifestyle' },
  { optionA: 'Minimalist', optionB: 'Sammler', category: 'Lifestyle' },
  { optionA: 'Extrovertiert', optionB: 'Introvertiert', category: 'Lifestyle' },
  { optionA: 'Planen', optionB: 'Spontan sein', category: 'Lifestyle' },
  { optionA: 'Videospiele', optionB: 'Brettspiele', category: 'Lifestyle' },
  { optionA: 'Festival', optionB: 'Konzert', category: 'Lifestyle' },
  { optionA: 'WG', optionB: 'Allein wohnen', category: 'Lifestyle' },
  { optionA: 'Kochen lernen', optionB: 'Instrument lernen', category: 'Lifestyle' },
  { optionA: 'Tattoo', optionB: 'Piercing', category: 'Lifestyle' },
  { optionA: 'Homeoffice', optionB: 'Buero', category: 'Lifestyle' },
  { optionA: 'Spotify', optionB: 'Apple Music', category: 'Lifestyle' },
  { optionA: 'Sport treiben', optionB: 'Sport schauen', category: 'Lifestyle' },
  // Lustig (25)
  { optionA: 'Nie wieder Schokolade', optionB: 'Nie wieder Kaese', category: 'Lustig' },
  { optionA: 'Immer zu frueh', optionB: 'Immer zu spaet', category: 'Lustig' },
  { optionA: 'Unsichtbar sein', optionB: 'Fliegen koennen', category: 'Lustig' },
  { optionA: 'Gedanken lesen', optionB: 'Zeitreise', category: 'Lustig' },
  { optionA: 'Ohne Handy', optionB: 'Ohne Schlaf', category: 'Lustig' },
  { optionA: '10 Hunde', optionB: '10 Katzen', category: 'Lustig' },
  { optionA: 'Immer laut reden', optionB: 'Immer fluestern', category: 'Lustig' },
  { optionA: 'Nie wieder Pizza', optionB: 'Nie wieder Musik', category: 'Lustig' },
  { optionA: 'Zombie-Apokalypse', optionB: 'Alien-Invasion', category: 'Lustig' },
  { optionA: 'Riese sein', optionB: 'Zwerg sein', category: 'Lustig' },
  { optionA: 'In der Vergangenheit leben', optionB: 'In der Zukunft leben', category: 'Lustig' },
  { optionA: 'Auf dem Mond leben', optionB: 'Unter Wasser leben', category: 'Lustig' },
  { optionA: 'Nur noch Singen statt Reden', optionB: 'Nur noch Tanzen statt Gehen', category: 'Lustig' },
  { optionA: 'Superkraft: Superstaerke', optionB: 'Superkraft: Superschnelligkeit', category: 'Lustig' },
  { optionA: 'Ewig jung bleiben', optionB: 'Unendlich reich sein', category: 'Lustig' },
  { optionA: 'Immer die Wahrheit sagen', optionB: 'Immer luegen', category: 'Lustig' },
  { optionA: 'Keine Arme', optionB: 'Keine Beine', category: 'Lustig' },
  { optionA: 'Nur noch kaltes Essen', optionB: 'Nur noch warmes Trinken', category: 'Lustig' },
  { optionA: 'Rueckwaerts gehen muessen', optionB: 'Alles rueckwaerts sagen muessen', category: 'Lustig' },
  { optionA: 'Beruehmter Musiker', optionB: 'Beruehmter Schauspieler', category: 'Lustig' },
  { optionA: 'In einem Film leben', optionB: 'In einem Videospiel leben', category: 'Lustig' },
  { optionA: 'Kein Internet fuer 1 Jahr', optionB: 'Kein Handy fuer 1 Jahr', category: 'Lustig' },
  { optionA: 'Jeden Tag Regen', optionB: 'Jeden Tag 40 Grad', category: 'Lustig' },
  { optionA: 'Immer Montag', optionB: 'Immer Sonntag', category: 'Lustig' },
  { optionA: 'Unendlich Urlaub', optionB: 'Traumjob', category: 'Lustig' },
  // Philosophisch (25)
  { optionA: 'Liebe ohne Geld', optionB: 'Geld ohne Liebe', category: 'Philosophisch' },
  { optionA: 'Alles wissen', optionB: 'Alles koennen', category: 'Philosophisch' },
  { optionA: 'Die Vergangenheit aendern', optionB: 'Die Zukunft sehen', category: 'Philosophisch' },
  { optionA: 'Lange leben', optionB: 'Intensiv leben', category: 'Philosophisch' },
  { optionA: 'Kopf', optionB: 'Herz', category: 'Philosophisch' },
  { optionA: 'Freiheit', optionB: 'Sicherheit', category: 'Philosophisch' },
  { optionA: 'Talent', optionB: 'Fleiss', category: 'Philosophisch' },
  { optionA: 'Wahrheit', optionB: 'Glueck', category: 'Philosophisch' },
  { optionA: 'Vergessen koennen', optionB: 'Nichts vergessen', category: 'Philosophisch' },
  { optionA: 'Beruehmtheit', optionB: 'Anonymitaet', category: 'Philosophisch' },
  { optionA: 'Viele Freunde', optionB: 'Ein bester Freund', category: 'Philosophisch' },
  { optionA: 'Macht', optionB: 'Weisheit', category: 'Philosophisch' },
  { optionA: 'Perfektes Gedaechtnis', optionB: 'Perfekte Kreativitaet', category: 'Philosophisch' },
  { optionA: 'Immer Recht haben', optionB: 'Immer gluecklich sein', category: 'Philosophisch' },
  { optionA: 'Nur geben', optionB: 'Nur nehmen', category: 'Philosophisch' },
  { optionA: 'Die Welt retten', optionB: 'Deine Familie retten', category: 'Philosophisch' },
  { optionA: 'Erfolg', optionB: 'Zufriedenheit', category: 'Philosophisch' },
  { optionA: 'Schoenheit', optionB: 'Intelligenz', category: 'Philosophisch' },
  { optionA: 'Vertrauen', optionB: 'Respekt', category: 'Philosophisch' },
  { optionA: 'Mut', optionB: 'Geduld', category: 'Philosophisch' },
  { optionA: 'Einsamkeit kennen', optionB: 'Nie allein sein', category: 'Philosophisch' },
  { optionA: 'Fehler machen duerfen', optionB: 'Nie scheitern', category: 'Philosophisch' },
  { optionA: 'Alles kontrollieren', optionB: 'Alles akzeptieren', category: 'Philosophisch' },
  { optionA: 'Gesundheit', optionB: 'Reichtum', category: 'Philosophisch' },
  { optionA: 'Leidenschaft', optionB: 'Stabilitaet', category: 'Philosophisch' },
];
