export interface ThisOrThatPair {
  optionA: string;
  optionB: string;
  category: string;
}

export const THISORTHAT_PAIRS: ThisOrThatPair[] = [
  // Nourriture (25)
  { optionA: 'Pizza', optionB: 'Burger', category: 'Nourriture' },
  { optionA: 'Chocolat', optionB: 'Bonbons', category: 'Nourriture' },
  { optionA: 'Cafe', optionB: 'The', category: 'Nourriture' },
  { optionA: 'Sushi', optionB: 'Steak', category: 'Nourriture' },
  { optionA: 'Glace', optionB: 'Gateau', category: 'Nourriture' },
  { optionA: 'Petit-dejeuner', optionB: 'Diner', category: 'Nourriture' },
  { optionA: 'Sucre', optionB: 'Sale', category: 'Nourriture' },
  { optionA: 'Cuisiner', optionB: 'Commander', category: 'Nourriture' },
  { optionA: 'Pates', optionB: 'Riz', category: 'Nourriture' },
  { optionA: 'Frites', optionB: 'Chips', category: 'Nourriture' },
  { optionA: 'Croque-monsieur', optionB: 'Kebab', category: 'Nourriture' },
  { optionA: 'Eau', optionB: 'Limonade', category: 'Nourriture' },
  { optionA: 'Crepes', optionB: 'Gaufres', category: 'Nourriture' },
  { optionA: 'Beurre de cacahuete', optionB: 'Nutella', category: 'Nourriture' },
  { optionA: 'Pomme', optionB: 'Banane', category: 'Nourriture' },
  { optionA: 'Lait', optionB: 'Lait d\'avoine', category: 'Nourriture' },
  { optionA: 'Salade', optionB: 'Soupe', category: 'Nourriture' },
  { optionA: 'Fromage', optionB: 'Jambon', category: 'Nourriture' },
  { optionA: 'Barbecue', optionB: 'Fondue', category: 'Nourriture' },
  { optionA: 'Popcorn', optionB: 'Nachos', category: 'Nourriture' },
  { optionA: 'Baguette', optionB: 'Croissant', category: 'Nourriture' },
  { optionA: 'Biere', optionB: 'Vin', category: 'Nourriture' },
  { optionA: 'Barre de cereales', optionB: 'Barre chocolatee', category: 'Nourriture' },
  { optionA: 'Pizza surgelee', optionB: 'Pizza livree', category: 'Nourriture' },
  { optionA: 'Croissant', optionB: 'Donut', category: 'Nourriture' },
  // Voyages (25)
  { optionA: 'Plage', optionB: 'Montagne', category: 'Voyages' },
  { optionA: 'Avion', optionB: 'Road trip', category: 'Voyages' },
  { optionA: 'Hotel', optionB: 'Camping', category: 'Voyages' },
  { optionA: 'Ete', optionB: 'Hiver', category: 'Voyages' },
  { optionA: 'Europe', optionB: 'Asie', category: 'Voyages' },
  { optionA: 'Escapade en ville', optionB: 'Vacances nature', category: 'Voyages' },
  { optionA: 'Voyager seul', optionB: 'Voyage en groupe', category: 'Voyages' },
  { optionA: 'Se lever tot', optionB: 'Faire la grasse matinee', category: 'Voyages' },
  { optionA: 'Sac a dos', optionB: 'Tout compris', category: 'Voyages' },
  { optionA: 'Croisiere', optionB: 'Safari', category: 'Voyages' },
  { optionA: 'New York', optionB: 'Tokyo', category: 'Voyages' },
  { optionA: 'Desert', optionB: 'Foret tropicale', category: 'Voyages' },
  { optionA: 'Voyage en train', optionB: 'Voyage en bateau', category: 'Voyages' },
  { optionA: 'Aventure', optionB: 'Detente', category: 'Voyages' },
  { optionA: 'Espagne', optionB: 'Italie', category: 'Voyages' },
  { optionA: 'Vacances au ski', optionB: 'Vacances de surf', category: 'Voyages' },
  { optionA: 'Printemps', optionB: 'Automne', category: 'Voyages' },
  { optionA: 'Aurores boreales', optionB: 'Coucher de soleil sur la mer', category: 'Voyages' },
  { optionA: 'Parc d\'attractions', optionB: 'Spa', category: 'Voyages' },
  { optionA: 'Auberge de jeunesse', optionB: 'Airbnb', category: 'Voyages' },
  { optionA: 'Valise', optionB: 'Sac a dos', category: 'Voyages' },
  { optionA: 'Hublot', optionB: 'Couloir', category: 'Voyages' },
  { optionA: 'Reserver tot', optionB: 'Derniere minute', category: 'Voyages' },
  { optionA: 'Plongee', optionB: 'Randonnee', category: 'Voyages' },
  { optionA: 'Venise', optionB: 'Paris', category: 'Voyages' },
  // Mode de vie (25)
  { optionA: 'Netflix', optionB: 'YouTube', category: 'Mode de vie' },
  { optionA: 'Matinal', optionB: 'Couche-tard', category: 'Mode de vie' },
  { optionA: 'Chien', optionB: 'Chat', category: 'Mode de vie' },
  { optionA: 'iPhone', optionB: 'Android', category: 'Mode de vie' },
  { optionA: 'Instagram', optionB: 'TikTok', category: 'Mode de vie' },
  { optionA: 'Lire un livre', optionB: 'Ecouter un podcast', category: 'Mode de vie' },
  { optionA: 'Salle de sport', optionB: 'Jogging', category: 'Mode de vie' },
  { optionA: 'Ville', optionB: 'Campagne', category: 'Mode de vie' },
  { optionA: 'Especes', optionB: 'Carte bancaire', category: 'Mode de vie' },
  { optionA: 'Se coucher tot', optionB: 'Noctambule', category: 'Mode de vie' },
  { optionA: 'Shopping en ligne', optionB: 'Shopping en magasin', category: 'Mode de vie' },
  { optionA: 'Ecouter de la musique', optionB: 'Regarder des series', category: 'Mode de vie' },
  { optionA: 'Bain', optionB: 'Douche', category: 'Mode de vie' },
  { optionA: 'Baskets', optionB: 'Chaussures habillees', category: 'Mode de vie' },
  { optionA: 'Minimaliste', optionB: 'Collectionneur', category: 'Mode de vie' },
  { optionA: 'Extraverti', optionB: 'Introverti', category: 'Mode de vie' },
  { optionA: 'Planifier', optionB: 'Etre spontane', category: 'Mode de vie' },
  { optionA: 'Jeux video', optionB: 'Jeux de societe', category: 'Mode de vie' },
  { optionA: 'Festival', optionB: 'Concert', category: 'Mode de vie' },
  { optionA: 'Colocation', optionB: 'Vivre seul', category: 'Mode de vie' },
  { optionA: 'Apprendre a cuisiner', optionB: 'Apprendre un instrument', category: 'Mode de vie' },
  { optionA: 'Tatouage', optionB: 'Piercing', category: 'Mode de vie' },
  { optionA: 'Teletravail', optionB: 'Bureau', category: 'Mode de vie' },
  { optionA: 'Spotify', optionB: 'Apple Music', category: 'Mode de vie' },
  { optionA: 'Faire du sport', optionB: 'Regarder du sport', category: 'Mode de vie' },
  // Drole (25)
  { optionA: 'Plus jamais de chocolat', optionB: 'Plus jamais de fromage', category: 'Drole' },
  { optionA: 'Toujours en avance', optionB: 'Toujours en retard', category: 'Drole' },
  { optionA: 'Etre invisible', optionB: 'Pouvoir voler', category: 'Drole' },
  { optionA: 'Lire les pensees', optionB: 'Voyager dans le temps', category: 'Drole' },
  { optionA: 'Sans telephone', optionB: 'Sans sommeil', category: 'Drole' },
  { optionA: '10 chiens', optionB: '10 chats', category: 'Drole' },
  { optionA: 'Toujours crier', optionB: 'Toujours chuchoter', category: 'Drole' },
  { optionA: 'Plus jamais de pizza', optionB: 'Plus jamais de musique', category: 'Drole' },
  { optionA: 'Apocalypse zombie', optionB: 'Invasion extraterrestre', category: 'Drole' },
  { optionA: 'Etre un geant', optionB: 'Etre minuscule', category: 'Drole' },
  { optionA: 'Vivre dans le passe', optionB: 'Vivre dans le futur', category: 'Drole' },
  { optionA: 'Vivre sur la lune', optionB: 'Vivre sous l\'eau', category: 'Drole' },
  { optionA: 'Chanter au lieu de parler', optionB: 'Danser au lieu de marcher', category: 'Drole' },
  { optionA: 'Super force', optionB: 'Super vitesse', category: 'Drole' },
  { optionA: 'Rester jeune pour toujours', optionB: 'Etre infiniment riche', category: 'Drole' },
  { optionA: 'Toujours dire la verite', optionB: 'Toujours mentir', category: 'Drole' },
  { optionA: 'Sans bras', optionB: 'Sans jambes', category: 'Drole' },
  { optionA: 'Que de la nourriture froide', optionB: 'Que des boissons chaudes', category: 'Drole' },
  { optionA: 'Marcher a reculons', optionB: 'Parler a l\'envers', category: 'Drole' },
  { optionA: 'Musicien celebre', optionB: 'Acteur celebre', category: 'Drole' },
  { optionA: 'Vivre dans un film', optionB: 'Vivre dans un jeu video', category: 'Drole' },
  { optionA: 'Pas d\'internet pendant 1 an', optionB: 'Pas de telephone pendant 1 an', category: 'Drole' },
  { optionA: 'Pluie tous les jours', optionB: '40 degres tous les jours', category: 'Drole' },
  { optionA: 'Toujours lundi', optionB: 'Toujours dimanche', category: 'Drole' },
  { optionA: 'Vacances infinies', optionB: 'Travail de reve', category: 'Drole' },
  // Philosophique (25)
  { optionA: 'Amour sans argent', optionB: 'Argent sans amour', category: 'Philosophique' },
  { optionA: 'Tout savoir', optionB: 'Tout pouvoir faire', category: 'Philosophique' },
  { optionA: 'Changer le passe', optionB: 'Voir le futur', category: 'Philosophique' },
  { optionA: 'Vie longue', optionB: 'Vie intense', category: 'Philosophique' },
  { optionA: 'Tete', optionB: 'Coeur', category: 'Philosophique' },
  { optionA: 'Liberte', optionB: 'Securite', category: 'Philosophique' },
  { optionA: 'Talent', optionB: 'Travail acharne', category: 'Philosophique' },
  { optionA: 'Verite', optionB: 'Bonheur', category: 'Philosophique' },
  { optionA: 'Pouvoir oublier', optionB: 'Ne rien oublier', category: 'Philosophique' },
  { optionA: 'Celebrite', optionB: 'Anonymat', category: 'Philosophique' },
  { optionA: 'Beaucoup d\'amis', optionB: 'Un meilleur ami', category: 'Philosophique' },
  { optionA: 'Pouvoir', optionB: 'Sagesse', category: 'Philosophique' },
  { optionA: 'Memoire parfaite', optionB: 'Creativite parfaite', category: 'Philosophique' },
  { optionA: 'Toujours avoir raison', optionB: 'Toujours etre heureux', category: 'Philosophique' },
  { optionA: 'Ne faire que donner', optionB: 'Ne faire que recevoir', category: 'Philosophique' },
  { optionA: 'Sauver le monde', optionB: 'Sauver sa famille', category: 'Philosophique' },
  { optionA: 'Succes', optionB: 'Contentement', category: 'Philosophique' },
  { optionA: 'Beaute', optionB: 'Intelligence', category: 'Philosophique' },
  { optionA: 'Confiance', optionB: 'Respect', category: 'Philosophique' },
  { optionA: 'Courage', optionB: 'Patience', category: 'Philosophique' },
  { optionA: 'Connaitre la solitude', optionB: 'Ne jamais etre seul', category: 'Philosophique' },
  { optionA: 'Avoir le droit a l\'erreur', optionB: 'Ne jamais echouer', category: 'Philosophique' },
  { optionA: 'Tout controler', optionB: 'Tout accepter', category: 'Philosophique' },
  { optionA: 'Sante', optionB: 'Richesse', category: 'Philosophique' },
  { optionA: 'Passion', optionB: 'Stabilite', category: 'Philosophique' },

  // Nouveaux (60)
  { optionA: 'Petit-dejeuner au lit', optionB: 'Petit-dejeuner a table', category: 'Nourriture' },
  { optionA: 'Nourriture epicee', optionB: 'Nourriture douce', category: 'Nourriture' },
  { optionA: 'Fait maison', optionB: 'Restaurant', category: 'Nourriture' },
  { optionA: 'Pain complet', optionB: 'Pain blanc', category: 'Nourriture' },
  { optionA: 'Bonbons', optionB: 'Reglisse', category: 'Nourriture' },
  { optionA: 'Smoothie', optionB: 'Jus frais', category: 'Nourriture' },
  { optionA: 'Brunch', optionB: 'En-cas de minuit', category: 'Nourriture' },
  { optionA: 'Asiatique', optionB: 'Italien', category: 'Nourriture' },
  { optionA: 'Curry', optionB: 'Pates', category: 'Nourriture' },
  { optionA: 'Vegetarien', optionB: 'Carnivore', category: 'Nourriture' },
  { optionA: 'Bar de plage', optionB: 'Chalet de montagne', category: 'Voyages' },
  { optionA: 'Lever de soleil', optionB: 'Coucher de soleil', category: 'Voyages' },
  { optionA: 'Lieu secret', optionB: 'Lieu touristique', category: 'Voyages' },
  { optionA: 'Camping-car', optionB: 'Hotel de luxe', category: 'Voyages' },
  { optionA: 'Aventure en jungle', optionB: 'Safari dans le desert', category: 'Voyages' },
  { optionA: 'Caraibes', optionB: 'Scandinavie', category: 'Voyages' },
  { optionA: 'Train de nuit', optionB: 'Vol de nuit', category: 'Voyages' },
  { optionA: 'Voyage culturel', optionB: 'Voyage festif', category: 'Voyages' },
  { optionA: 'Islande', optionB: 'Hawai', category: 'Voyages' },
  { optionA: 'Camper au bord du lac', optionB: 'Cabane dans les arbres', category: 'Voyages' },
  { optionA: 'Voiture electrique', optionB: 'Voiture de collection', category: 'Mode de vie' },
  { optionA: 'Se lever tot', optionB: 'Se coucher tard', category: 'Mode de vie' },
  { optionA: 'Cinema', optionB: 'Theatre', category: 'Mode de vie' },
  { optionA: 'Livre', optionB: 'Livre audio', category: 'Mode de vie' },
  { optionA: 'Concert live', optionB: 'Festival', category: 'Mode de vie' },
  { optionA: 'Yoga', optionB: 'CrossFit', category: 'Mode de vie' },
  { optionA: 'Independant', optionB: 'Salarie', category: 'Mode de vie' },
  { optionA: 'Grande ville', optionB: 'Petite ville', category: 'Mode de vie' },
  { optionA: 'Animal de compagnie', optionB: 'Plante verte', category: 'Mode de vie' },
  { optionA: 'Analogique', optionB: 'Numerique', category: 'Mode de vie' },
  { optionA: 'Ecrit a la main', optionB: 'Tape a l\'ordinateur', category: 'Mode de vie' },
  { optionA: 'Retraite anticipee', optionB: 'Travail de reve pour toujours', category: 'Mode de vie' },
  { optionA: 'Personne d\'ete', optionB: 'Personne d\'hiver', category: 'Mode de vie' },
  { optionA: 'Bureau en desordre', optionB: 'Bureau range', category: 'Mode de vie' },
  { optionA: 'Etre bruyant', optionB: 'Etre discret', category: 'Mode de vie' },
  { optionA: 'Teleportation', optionB: 'Voyage dans le temps', category: 'Drole' },
  { optionA: 'Voler uniquement', optionB: 'Respirer sous l\'eau', category: 'Drole' },
  { optionA: 'Tout oublier', optionB: 'Se souvenir de tout', category: 'Drole' },
  { optionA: 'Ne plus jamais dormir', optionB: 'Ne plus jamais manger', category: 'Drole' },
  { optionA: 'Parler aux animaux', optionB: 'Parler toutes les langues', category: 'Drole' },
  { optionA: 'Vivre dans une comedie musicale', optionB: 'Vivre dans un film d\'horreur', category: 'Drole' },
  { optionA: 'Toujours l\'ete', optionB: 'Toujours l\'automne', category: 'Drole' },
  { optionA: 'Enorme maison', optionB: 'Petite maison sur la plage', category: 'Drole' },
  { optionA: '100 canards', optionB: '1 cheval de la taille d\'un canard', category: 'Drole' },
  { optionA: 'Vivre a l\'age de pierre', optionB: 'Vivre en l\'an 3000', category: 'Drole' },
  { optionA: 'Etre un super-heros', optionB: 'Etre un super-vilain', category: 'Drole' },
  { optionA: 'Toujours la bonne tenue', optionB: 'Toujours le bon repas', category: 'Drole' },
  { optionA: 'Tout au ralenti', optionB: 'Tout en accelere', category: 'Drole' },
  { optionA: 'Ne plus jamais cuisiner', optionB: 'Ne plus jamais faire le menage', category: 'Drole' },
  { optionA: 'Record du monde', optionB: 'Gagner au loto', category: 'Drole' },
  { optionA: 'Tout savoir et etre triste', optionB: 'Ne rien savoir et etre heureux', category: 'Philosophique' },
  { optionA: 'Etre inoubliable', optionB: 'Etre immortel', category: 'Philosophique' },
  { optionA: 'Le passe parfait', optionB: 'Le futur parfait', category: 'Philosophique' },
  { optionA: 'Energie infinie', optionB: 'Temps infini', category: 'Philosophique' },
  { optionA: 'Ne faire que le bien', optionB: 'N\'etre qu\'honnete', category: 'Philosophique' },
  { optionA: 'Tout perdre et recommencer', optionB: 'Ne rien changer jamais', category: 'Philosophique' },
  { optionA: 'Paix interieure', optionB: 'Succes exterieur', category: 'Philosophique' },
  { optionA: 'Toujours le meilleur', optionB: 'Toujours le plus aime', category: 'Philosophique' },
  { optionA: 'Aider les autres', optionB: 'S\'aider soi-meme', category: 'Philosophique' },
  { optionA: 'Tout ressentir', optionB: 'Ne rien ressentir', category: 'Philosophique' },
];
