import type { Fact } from './fakeorfact-content-de';

export const FACTS_FR: Fact[] = [
  // Nature et Animaux
  { statement: 'Les pieuvres ont trois cœurs.', isTrue: true, explanation: 'Deux cœurs branchiaux pompent le sang vers les branchies, un cœur principal le pompe dans le corps.', category: 'Nature' },
  { statement: 'Les poissons rouges ont une mémoire de seulement 3 secondes.', isTrue: false, explanation: 'Les poissons rouges peuvent se souvenir de choses pendant des mois — le mythe des 3 secondes est faux.', category: 'Nature' },
  { statement: 'Le miel ne se périme jamais.', isTrue: true, explanation: 'Du miel vieux de 3000 ans a été trouvé dans des tombeaux égyptiens et était encore comestible.', category: 'Nature' },
  { statement: 'Les crocodiles ne peuvent pas lécher avec leur langue.', isTrue: true, explanation: 'La langue d\'un crocodile est attachée au palais et ne peut pas être sortie.', category: 'Nature' },
  { statement: 'Les éléphants sont les seuls animaux qui ne peuvent pas sauter.', isTrue: true, explanation: 'En raison de leur poids et de leur structure osseuse, les éléphants ne peuvent effectivement pas sauter.', category: 'Nature' },
  { statement: 'Les bananes poussent sur des arbres.', isTrue: false, explanation: 'Les bananiers ne sont pas des arbres, mais des plantes herbacées géantes.', category: 'Nature' },
  { statement: 'La foudre peut frapper deux fois au même endroit.', isTrue: true, explanation: 'Les bâtiments élevés comme l\'Empire State Building sont frappés jusqu\'à 100 fois par an.', category: 'Nature' },
  { statement: 'Les dauphins dorment avec un œil ouvert.', isTrue: true, explanation: 'Les dauphins dorment avec une moitié du cerveau et gardent un œil ouvert pour les prédateurs.', category: 'Nature' },
  { statement: 'Les koalas ne boivent pas d\'eau.', isTrue: false, explanation: 'Les koalas boivent rarement de l\'eau car ils tirent l\'humidité des feuilles d\'eucalyptus, mais ils boivent bien quand il fait chaud.', category: 'Nature' },
  { statement: 'Les papillons goûtent avec leurs pieds.', isTrue: true, explanation: 'Les papillons ont des récepteurs gustatifs sur les pieds pour identifier les plantes.', category: 'Nature' },

  // Science
  { statement: 'Le son voyage plus vite que la lumière.', isTrue: false, explanation: 'La lumière voyage à environ 300 000 km/s, le son à seulement environ 343 m/s.', category: 'Science' },
  { statement: 'Le corps humain est composé d\'environ 60% d\'eau.', isTrue: true, explanation: 'Le corps humain est composé de 50 à 75% d\'eau selon l\'âge.', category: 'Science' },
  { statement: 'Vénus tourne dans le sens opposé à la plupart des planètes.', isTrue: true, explanation: 'Vénus a une rotation rétrograde — le soleil s\'y lève à l\'ouest.', category: 'Science' },
  { statement: 'Le verre est un liquide.', isTrue: false, explanation: 'Le verre est un solide amorphe. Le mythe du verre qui coule dans les vieilles fenêtres est faux.', category: 'Science' },
  { statement: 'Un jour sur Vénus est plus long qu\'une année sur Vénus.', isTrue: true, explanation: 'Une rotation dure 243 jours terrestres, une orbite autour du soleil seulement 225 jours terrestres.', category: 'Science' },
  { statement: 'Les humains n\'utilisent que 10% de leur cerveau.', isTrue: false, explanation: 'Les scanners cérébraux montrent que nous utilisons pratiquement toutes les zones du cerveau, mais pas toutes en même temps.', category: 'Science' },
  { statement: 'Les diamants se forment à partir du charbon.', isTrue: false, explanation: 'Les diamants se forment à partir de carbone sous pression extrême, mais pas du charbon — la plupart sont plus anciens que les plantes sur Terre.', category: 'Science' },
  { statement: 'Dans l\'espace, c\'est le silence absolu.', isTrue: true, explanation: 'Le son a besoin d\'un milieu pour se propager. Dans le vide de l\'espace, il n\'y en a pas.', category: 'Science' },
  { statement: 'Le corps humain a plus de bactéries que de cellules propres.', isTrue: true, explanation: 'On estime que le corps contient environ 38 billions de bactéries pour 30 billions de cellules propres.', category: 'Science' },
  { statement: 'L\'eau conduit l\'électricité.', isTrue: false, explanation: 'L\'eau pure ne conduit pas l\'électricité. Ce sont les minéraux et les sels dissous qui la rendent conductrice.', category: 'Science' },

  // Histoire
  { statement: 'Cléopâtre a vécu plus près de l\'alunissage que de la construction des pyramides.', isTrue: true, explanation: 'Les pyramides ont été construites vers 2560 av. J.-C., Cléopâtre a vécu de 69 à 30 av. J.-C., l\'alunissage a eu lieu en 1969.', category: 'Histoire' },
  { statement: 'Napoléon était exceptionnellement petit.', isTrue: false, explanation: 'Napoléon mesurait environ 1,70 m — une taille moyenne pour son époque. Le mythe provient de la propagande britannique.', category: 'Histoire' },
  { statement: 'La Grande Muraille de Chine est visible depuis la Lune.', isTrue: false, explanation: 'Les astronautes confirment que la muraille n\'est pas visible depuis la Lune — elle est trop étroite.', category: 'Histoire' },
  { statement: 'L\'Université d\'Oxford est plus ancienne que l\'Empire aztèque.', isTrue: true, explanation: 'Oxford a été fondée à partir de 1096, l\'Empire aztèque seulement en 1428.', category: 'Histoire' },
  { statement: 'Les Vikings portaient des casques à cornes.', isTrue: false, explanation: 'Les découvertes archéologiques montrent des casques simples sans cornes. Le cliché date du XIXe siècle.', category: 'Histoire' },
  { statement: 'Dans l\'Antiquité, les gens croyaient que la Terre était plate.', isTrue: false, explanation: 'Les anciens Grecs savaient déjà que la Terre était ronde. Ératosthène a même calculé sa circonférence.', category: 'Histoire' },
  { statement: 'La tour Eiffel devait être démolie après 20 ans.', isTrue: true, explanation: 'Elle a été construite en 1889 comme structure temporaire et n\'a survécu que parce qu\'elle était utile comme tour radio.', category: 'Histoire' },
  { statement: 'Le Titanic a été présenté comme insubmersible.', isTrue: false, explanation: 'La White Star Line ne l\'a jamais officiellement qualifié d\'insubmersible. C\'était une exagération de la presse.', category: 'Histoire' },
  { statement: 'Albert Einstein a échoué en mathématiques.', isTrue: false, explanation: 'Einstein avait d\'excellentes notes en mathématiques. Ce mythe est totalement faux.', category: 'Histoire' },
  { statement: 'Les spaghettis à la sauce tomate sont un plat italien traditionnel.', isTrue: false, explanation: 'Les tomates ne sont arrivées en Europe depuis l\'Amérique qu\'au XVIe siècle. Les pâtes traditionnelles étaient assaisonnées autrement.', category: 'Histoire' },

  // Géographie
  { statement: 'La Russie a onze fuseaux horaires.', isTrue: true, explanation: 'De Kaliningrad au Kamtchatka, la Russie s\'étend sur 11 fuseaux horaires.', category: 'Géographie' },
  { statement: 'L\'Amazone est le fleuve le plus long du monde.', isTrue: false, explanation: 'Le Nil avec environ 6 650 km est considéré comme le plus long fleuve, l\'Amazone est le plus volumineux.', category: 'Géographie' },
  { statement: 'L\'Islande n\'a pas de moustiques.', isTrue: true, explanation: 'L\'Islande est l\'un des rares pays au monde sans espèces de moustiques indigènes.', category: 'Géographie' },
  { statement: 'Le Sahara est le plus grand désert du monde.', isTrue: false, explanation: 'L\'Antarctique est le plus grand désert (14 millions de km²). Le Sahara est le plus grand désert chaud.', category: 'Géographie' },
  { statement: 'En Australie, il y a plus de kangourous que d\'humains.', isTrue: true, explanation: 'Il y a environ 50 millions de kangourous pour 26 millions d\'habitants en Australie.', category: 'Géographie' },
  { statement: 'Le Mont Everest est la montagne la plus haute mesurée depuis le centre de la Terre.', isTrue: false, explanation: 'Le Chimborazo en Équateur est le point le plus éloigné du centre de la Terre, car la Terre est plus large à l\'équateur.', category: 'Géographie' },

  // Curiosités
  { statement: 'En Suisse, il est illégal de ne posséder qu\'un seul cochon d\'Inde.', isTrue: true, explanation: 'Les cochons d\'Inde sont des animaux sociaux. Les lois suisses sur la protection des animaux interdisent de les garder seuls.', category: 'Curiosités' },
  { statement: 'Il y a plus d\'étoiles dans l\'univers que de grains de sable sur Terre.', isTrue: true, explanation: 'Estimations : environ 10^24 étoiles dans l\'univers observable, environ 7,5×10^18 grains de sable.', category: 'Curiosités' },
  { statement: 'Un escargot peut dormir jusqu\'à 3 ans.', isTrue: true, explanation: 'Certaines espèces d\'escargots peuvent entrer dans un état de repos prolongé, surtout en période de sécheresse.', category: 'Curiosités' },
  { statement: 'L\'inventeur de la boîte Pringles a été enterré dans une.', isTrue: true, explanation: 'Fredric Baur, l\'inventeur de la boîte Pringles, a été enterré dans une en 2008 à sa demande.', category: 'Curiosités' },
  { statement: 'Les vaches peuvent monter les escaliers, mais pas les descendre.', isTrue: true, explanation: 'En raison de la structure de leurs genoux et de leur champ de vision, les vaches ne peuvent pas descendre les escaliers en toute sécurité.', category: 'Curiosités' },
  { statement: 'Chaque personne avale en moyenne 8 araignées par an dans son sommeil.', isTrue: false, explanation: 'Ce mythe a été inventé en 1993 volontairement comme exemple de fausse information.', category: 'Curiosités' },
  { statement: 'Selon la physique, les bourdons ne devraient pas pouvoir voler.', isTrue: false, explanation: 'Cette rumeur repose sur des calculs erronés. L\'aérodynamique du vol des bourdons est expliquée depuis longtemps.', category: 'Curiosités' },
  { statement: 'Au Japon, il y a une île pleine de chats où ils sont plus nombreux que les humains.', isTrue: true, explanation: 'Aoshima, aussi appelée l\'île aux chats, a un ratio d\'environ 6 chats pour 1 humain.', category: 'Curiosités' },
  { statement: 'La guerre la plus courte de l\'histoire a duré 38 minutes.', isTrue: true, explanation: 'La guerre anglo-zanzibarite de 1896 a duré entre 38 et 45 minutes.', category: 'Curiosités' },
  { statement: 'Les flamants roses sont roses dès la naissance.', isTrue: false, explanation: 'Les flamants naissent gris-blanc et deviennent roses grâce à leur alimentation (crustacés, algues).', category: 'Curiosités' },

  // Technologie
  { statement: 'Le premier iPhone n\'avait pas d\'App Store.', isTrue: true, explanation: 'Le premier iPhone est sorti en 2007, l\'App Store n\'a été lancé qu\'en 2008.', category: 'Technologie' },
  { statement: 'Le premier SMS au monde disait "Merry Christmas".', isTrue: true, explanation: 'Le 3 décembre 1992, Neil Papworth a envoyé le premier SMS avec le texte "Merry Christmas".', category: 'Technologie' },
  { statement: 'WiFi signifie Wireless Fidelity.', isTrue: false, explanation: 'WiFi est un nom de marque et ne signifie rien. Il a été inventé par une société de marketing.', category: 'Technologie' },
  { statement: 'Le premier ordinateur était aussi grand qu\'une pièce.', isTrue: true, explanation: 'L\'ENIAC (1945) pesait 27 tonnes et occupait 167 mètres carrés.', category: 'Technologie' },
  { statement: 'Les e-mails ne consomment pas d\'électricité.', isTrue: false, explanation: 'Chaque e-mail consomme environ 4 g de CO2, car les serveurs et les réseaux ont besoin d\'énergie.', category: 'Technologie' },

  // Nouveaux faits (50)
  { statement: 'Les wombats produisent des crottes en forme de cube.', isTrue: true, explanation: 'Les wombats ont un intestin spécial qui forme des excréments cubiques pour qu\'ils ne roulent pas.', category: 'Nature' },
  { statement: 'La tour Eiffel est plus petite en hiver qu\'en été.', isTrue: true, explanation: 'Avec le froid, le métal se contracte, faisant rétrécir la tour jusqu\'à 15 cm.', category: 'Curiosités' },
  { statement: 'Les vaches ont quatre estomacs.', isTrue: true, explanation: 'Les vaches ont quatre compartiments stomacaux : la panse, le bonnet, le feuillet et la caillette.', category: 'Nature' },
  { statement: 'Une autruche peut courir plus vite qu\'un cheval.', isTrue: true, explanation: 'Les autruches peuvent atteindre 70 km/h, alors que les chevaux atteignent un maximum de 65 km/h.', category: 'Nature' },
  { statement: 'La Terre tourne plus vite qu\'il y a un million d\'années.', isTrue: false, explanation: 'La Terre tourne plus lentement. En raison des forces de marée de la Lune, les jours s\'allongent.', category: 'Science' },
  { statement: 'Venise a plus de ponts qu\'Amsterdam.', isTrue: false, explanation: 'Amsterdam a plus de 1 500 ponts, Venise seulement environ 400.', category: 'Géographie' },
  { statement: 'L\'Amazone se jette dans la mer sans un seul pont.', isTrue: true, explanation: 'Il n\'y a aucun pont traversant l\'Amazone dans son intégralité — il coule à travers une forêt tropicale trop dense.', category: 'Géographie' },
  { statement: 'Les abeilles peuvent reconnaître les visages.', isTrue: true, explanation: 'Des études montrent que les abeilles mellifères peuvent distinguer et reconnaître les visages humains.', category: 'Nature' },
  { statement: 'Mars possède la plus haute montagne du système solaire.', isTrue: true, explanation: 'L\'Olympus Mons sur Mars, avec environ 22 km, est la plus haute montagne connue du système solaire.', category: 'Science' },
  { statement: 'Le chocolat est toxique pour les chiens.', isTrue: true, explanation: 'La théobromine dans le chocolat peut être mortelle pour les chiens, car ils ne peuvent pas la métaboliser.', category: 'Nature' },
  { statement: 'En Australie, les arbres ne perdent pas leurs feuilles, mais leur écorce.', isTrue: true, explanation: 'De nombreuses espèces d\'eucalyptus perdent leur écorce au lieu de leurs feuilles.', category: 'Nature' },
  { statement: 'Le cœur d\'une crevette se trouve dans sa tête.', isTrue: true, explanation: 'Le cœur d\'une crevette se situe effectivement dans sa tête.', category: 'Nature' },
  { statement: 'Le Vatican a le taux de criminalité par habitant le plus élevé au monde.', isTrue: true, explanation: 'Comme le Vatican ne compte qu\'environ 800 habitants, quelques délits suffisent à créer un taux par habitant élevé.', category: 'Curiosités' },
  { statement: 'Un humain peut survivre dans l\'espace en retenant sa respiration.', isTrue: false, explanation: 'Dans le vide, l\'air serait violemment expulsé des poumons. On perdrait connaissance en environ 15 secondes.', category: 'Science' },
  { statement: 'On ne peut plier un papier que 7 fois maximum.', isTrue: false, explanation: 'Bien que ce soit difficile, du papier a déjà été plié 12 fois (avec une feuille suffisamment grande).', category: 'Curiosités' },
  { statement: 'La Grande Muraille de Chine fait plus de 21 000 km de long.', isTrue: true, explanation: 'Avec toutes les murailles secondaires et ramifications, elle mesure au total 21 196 km.', category: 'Histoire' },
  { statement: 'La Finlande a plus de saunas que de voitures.', isTrue: true, explanation: 'La Finlande compte environ 3,3 millions de saunas pour 5,5 millions d\'habitants — plus que de voitures.', category: 'Curiosités' },
  { statement: 'Le cœur d\'une baleine bleue est aussi gros qu\'une petite voiture.', isTrue: true, explanation: 'Le cœur d\'une baleine bleue peut peser jusqu\'à 600 kg et est aussi gros qu\'une Coccinelle Volkswagen.', category: 'Nature' },
  { statement: 'Le soleil est jaune.', isTrue: false, explanation: 'Le soleil est en réalité blanc. Il nous paraît jaune à cause de l\'atmosphère terrestre.', category: 'Science' },
  { statement: 'Les poissons peuvent se noyer.', isTrue: true, explanation: 'S\'il y a trop peu d\'oxygène dans l\'eau, les poissons peuvent effectivement suffoquer.', category: 'Nature' },
  { statement: 'Le Mont Everest grandit d\'environ 4 millimètres par an.', isTrue: true, explanation: 'En raison du mouvement des plaques tectoniques, l\'Himalaya continue de croître.', category: 'Science' },
  { statement: 'Le ketchup était vendu comme médicament au XIXe siècle.', isTrue: true, explanation: 'Dans les années 1830, le ketchup de tomate était vendu comme remède contre la diarrhée.', category: 'Histoire' },
  { statement: 'Le vol le plus court du monde dure 57 secondes.', isTrue: true, explanation: 'Le vol entre Westray et Papa Westray en Écosse dure à peine une minute.', category: 'Curiosités' },
  { statement: 'Les pieuvres ont trois cerveaux.', isTrue: false, explanation: 'Les pieuvres ont neuf cerveaux — un central et un supplémentaire dans chacun des huit bras.', category: 'Nature' },
  { statement: 'Le Brésil tient son nom d\'un arbre.', isTrue: true, explanation: 'Le Brésil tire son nom du bois de brésil (Pau-Brasil), abondant dans la région.', category: 'Histoire' },
  { statement: 'Un colibri peut voler en arrière.', isTrue: true, explanation: 'Les colibris sont les seuls oiseaux qui peuvent réellement voler en arrière.', category: 'Nature' },
  { statement: 'Le nez grandit tout au long de la vie.', isTrue: true, explanation: 'Le nez et les oreilles ne cessent jamais de grandir, car ils sont faits de cartilage.', category: 'Science' },
  { statement: 'Au Japon, il est courant de manger dans la baignoire.', isTrue: false, explanation: 'Au Japon, le bain est considéré comme un lieu de purification. Y manger serait inhabituel.', category: 'Curiosités' },
  { statement: 'L\'estomac humain produit environ 2 litres d\'acide chlorhydrique par jour.', isTrue: true, explanation: 'L\'acide gastrique est assez fort pour dissoudre du métal, mais est protégé par la muqueuse.', category: 'Science' },
  { statement: 'Il y a plus d\'arbres sur Terre que d\'étoiles dans la Voie lactée.', isTrue: true, explanation: 'Il y a environ 3 billions d\'arbres sur Terre, mais seulement 100 à 400 milliards d\'étoiles dans la Voie lactée.', category: 'Nature' },
  { statement: 'La couleur orange a été nommée d\'après le fruit, et non l\'inverse.', isTrue: true, explanation: 'Avant l\'orange, la couleur s\'appelait en anglais "geoluhread" (jaune-rouge). Le fruit a donné son nom à la couleur.', category: 'Curiosités' },
  { statement: 'Les bananes sont radioactives.', isTrue: true, explanation: 'Les bananes contiennent du potassium-40, un isotope radioactif. Mais la radiation est totalement inoffensive.', category: 'Science' },
  { statement: 'Un jour sur Pluton dure plus longtemps qu\'une semaine sur Terre.', isTrue: true, explanation: 'Un jour sur Pluton dure 6,4 jours terrestres — presque une semaine terrestre entière.', category: 'Science' },
  { statement: 'En Suisse, il est interdit de tirer la chasse d\'eau après 22 heures.', isTrue: false, explanation: 'C\'est un mythe très répandu. Il n\'existe pas de telle loi en Suisse.', category: 'Curiosités' },
  { statement: 'Le rire est contagieux parce que le cerveau active les neurones miroirs.', isTrue: true, explanation: 'Les neurones miroirs du cerveau réagissent au rire des autres et déclenchent des réactions similaires.', category: 'Science' },
  { statement: 'La Russie a une superficie plus grande que Pluton.', isTrue: true, explanation: 'La Russie fait 17,1 millions de km², la surface de Pluton n\'est que de 16,7 millions de km².', category: 'Géographie' },
  { statement: 'Une cuillère à café de matière d\'étoile à neutrons pèse 6 milliards de tonnes.', isTrue: true, explanation: 'Les étoiles à neutrons sont si denses qu\'une cuillère à café de leur matière pèse des milliards de tonnes.', category: 'Science' },
  { statement: 'Les chats ont plus d\'os que les humains.', isTrue: true, explanation: 'Les chats ont environ 230 os, les humains seulement 206.', category: 'Nature' },
  { statement: 'L\'océan Atlantique s\'élargit chaque année.', isTrue: true, explanation: 'En raison de la tectonique des plaques, l\'Atlantique s\'élargit d\'environ 2,5 cm par an.', category: 'Science' },
  { statement: 'En Norvège, il existe une ville qui s\'appelle "Hell".', isTrue: true, explanation: 'Hell est un lieu dans la commune de Verdal en Norvège. En hiver, Hell gèle régulièrement.', category: 'Géographie' },
  { statement: 'Les fourmis savent nager.', isTrue: true, explanation: 'La plupart des espèces de fourmis savent nager et forment de petits radeaux lors des inondations.', category: 'Nature' },
  { statement: 'L\'humain partage 60% de son ADN avec une banane.', isTrue: true, explanation: 'Les humains et les bananes partagent effectivement environ 60% de gènes identiques.', category: 'Science' },
  { statement: 'Il pleut de l\'acide sulfurique sur Vénus.', isTrue: true, explanation: 'Les nuages de Vénus sont composés de gouttelettes d\'acide sulfurique, qui s\'évaporent avant d\'atteindre le sol.', category: 'Science' },
  { statement: 'L\'Université d\'Oxford existait avant l\'Empire aztèque et avant la construction du Machu Picchu.', isTrue: true, explanation: 'Oxford a commencé à partir de 1096, l\'Empire aztèque a été fondé en 1428, le Machu Picchu a été construit vers 1450.', category: 'Histoire' },
  { statement: 'Un caméléon change de couleur pour se camoufler.', isTrue: false, explanation: 'Les caméléons changent de couleur principalement pour communiquer et réguler leur température, pas pour se camoufler.', category: 'Nature' },
  { statement: 'L\'odeur de l\'herbe fraîchement coupée est en fait un signal de détresse des plantes.', isTrue: true, explanation: 'Les plantes libèrent des substances chimiques lorsqu\'elles sont blessées — l\'odeur est une réaction de stress.', category: 'Nature' },
  { statement: 'En Suède, il y a un hôtel entièrement fait de glace.', isTrue: true, explanation: 'L\'Icehotel à Jukkasjärvi est reconstruit chaque hiver avec de la glace et de la neige.', category: 'Curiosités' },
  { statement: 'Les araignées peuvent voler.', isTrue: true, explanation: 'Certaines araignées utilisent le "ballooning" — elles se laissent porter par le vent grâce à des fils de soie.', category: 'Nature' },
  { statement: 'La lumière du soleil met 8 secondes pour atteindre la Terre.', isTrue: false, explanation: 'Il faut environ 8 minutes et 20 secondes, pas 8 secondes.', category: 'Science' },
  { statement: 'Un pingouin peut sauter plus haut qu\'une maison.', isTrue: true, explanation: 'C\'est un fait humoristique — les maisons ne peuvent pas sauter, donc le pingouin gagne.', category: 'Curiosités' },
];
