import type { Fact } from './fakeorfact-content-de';

export const FACTS_ES: Fact[] = [
  // Naturaleza y Animales
  { statement: 'Los pulpos tienen tres corazones.', isTrue: true, explanation: 'Dos corazones branquiales bombean sangre a las branquias, un corazón principal la bombea por el cuerpo.', category: 'Naturaleza' },
  { statement: 'Los peces dorados tienen una memoria de solo 3 segundos.', isTrue: false, explanation: 'Los peces dorados pueden recordar cosas durante meses — el mito de los 3 segundos es falso.', category: 'Naturaleza' },
  { statement: 'La miel nunca se echa a perder.', isTrue: true, explanation: 'En tumbas egipcias se encontró miel de 3000 años de antigüedad que aún era comestible.', category: 'Naturaleza' },
  { statement: 'Los cocodrilos no pueden lamer con la lengua.', isTrue: true, explanation: 'La lengua de un cocodrilo está adherida al paladar y no puede sacarse.', category: 'Naturaleza' },
  { statement: 'Los elefantes son los únicos animales que no pueden saltar.', isTrue: true, explanation: 'Debido a su peso y estructura ósea, los elefantes realmente no pueden saltar.', category: 'Naturaleza' },
  { statement: 'Los plátanos crecen en árboles.', isTrue: false, explanation: 'Las plantas de plátano no son árboles, sino plantas herbáceas gigantes.', category: 'Naturaleza' },
  { statement: 'Un rayo puede caer dos veces en el mismo lugar.', isTrue: true, explanation: 'Edificios altos como el Empire State Building son alcanzados hasta 100 veces al año.', category: 'Naturaleza' },
  { statement: 'Los delfines duermen con un ojo abierto.', isTrue: true, explanation: 'Los delfines duermen con una mitad del cerebro y mantienen un ojo abierto para detectar depredadores.', category: 'Naturaleza' },
  { statement: 'Los koalas no beben agua.', isTrue: false, explanation: 'Los koalas rara vez beben agua ya que obtienen humedad de las hojas de eucalipto, pero sí beben cuando hace calor.', category: 'Naturaleza' },
  { statement: 'Las mariposas saborean con los pies.', isTrue: true, explanation: 'Las mariposas tienen receptores gustativos en los pies para identificar plantas.', category: 'Naturaleza' },

  // Ciencia
  { statement: 'El sonido viaja más rápido que la luz.', isTrue: false, explanation: 'La luz viaja a unos 300.000 km/s, el sonido solo a unos 343 m/s.', category: 'Ciencia' },
  { statement: 'El cuerpo humano está compuesto por aproximadamente un 60% de agua.', isTrue: true, explanation: 'El cuerpo humano está compuesto entre un 50-75% de agua según la edad.', category: 'Ciencia' },
  { statement: 'Venus gira en dirección opuesta a la mayoría de los planetas.', isTrue: true, explanation: 'Venus tiene una rotación retrógrada — el sol sale por el oeste allí.', category: 'Ciencia' },
  { statement: 'El vidrio es un líquido.', isTrue: false, explanation: 'El vidrio es un sólido amorfo. El mito del vidrio que fluye en ventanas antiguas es falso.', category: 'Ciencia' },
  { statement: 'Un día en Venus es más largo que un año en Venus.', isTrue: true, explanation: 'Una rotación dura 243 días terrestres, una órbita alrededor del sol solo 225 días terrestres.', category: 'Ciencia' },
  { statement: 'Los humanos solo usan el 10% de su cerebro.', isTrue: false, explanation: 'Las imágenes cerebrales muestran que usamos prácticamente todas las áreas del cerebro, solo que no todas al mismo tiempo.', category: 'Ciencia' },
  { statement: 'Los diamantes se forman a partir del carbón.', isTrue: false, explanation: 'Los diamantes se forman del carbono bajo presión extrema, pero no del carbón — la mayoría son más antiguos que las plantas en la Tierra.', category: 'Ciencia' },
  { statement: 'En el espacio hay silencio absoluto.', isTrue: true, explanation: 'El sonido necesita un medio para propagarse. En el vacío del espacio no hay ninguno.', category: 'Ciencia' },
  { statement: 'El cuerpo humano tiene más bacterias que células propias.', isTrue: true, explanation: 'Se estima que el cuerpo tiene unos 38 billones de bacterias frente a 30 billones de células propias.', category: 'Ciencia' },
  { statement: 'El agua conduce la electricidad.', isTrue: false, explanation: 'El agua pura no conduce electricidad. Solo los minerales y sales disueltos en ella la hacen conductora.', category: 'Ciencia' },

  // Historia
  { statement: 'Cleopatra vivió más cerca del alunizaje que de la construcción de las pirámides.', isTrue: true, explanation: 'Las pirámides se construyeron alrededor del 2560 a.C., Cleopatra vivió del 69 al 30 a.C., el alunizaje fue en 1969.', category: 'Historia' },
  { statement: 'Napoleón era inusualmente bajo.', isTrue: false, explanation: 'Napoleón medía aprox. 1,70 m — normal para su época. El mito surgió de la propaganda británica.', category: 'Historia' },
  { statement: 'La Gran Muralla China es visible desde la Luna.', isTrue: false, explanation: 'Los astronautas confirman que la muralla no es visible desde la Luna — es demasiado estrecha.', category: 'Historia' },
  { statement: 'La Universidad de Oxford es más antigua que el Imperio Azteca.', isTrue: true, explanation: 'Oxford se fundó a partir de 1096, el Imperio Azteca recién en 1428.', category: 'Historia' },
  { statement: 'Los vikingos llevaban cascos con cuernos.', isTrue: false, explanation: 'Los hallazgos arqueológicos muestran cascos sencillos sin cuernos. El cliché proviene del siglo XIX.', category: 'Historia' },
  { statement: 'En la antigüedad la gente creía que la Tierra era plana.', isTrue: false, explanation: 'Ya los antiguos griegos sabían que la Tierra era redonda. Eratóstenes incluso calculó su circunferencia.', category: 'Historia' },
  { statement: 'La Torre Eiffel iba a ser demolida después de 20 años.', isTrue: true, explanation: 'Fue construida en 1889 como estructura temporal y solo sobrevivió porque era útil como torre de radio.', category: 'Historia' },
  { statement: 'El Titanic fue promocionado como insumergible.', isTrue: false, explanation: 'La White Star Line nunca lo llamó oficialmente insumergible. Fue una exageración de la prensa.', category: 'Historia' },
  { statement: 'Albert Einstein suspendió en matemáticas.', isTrue: false, explanation: 'Einstein tenía las mejores notas en matemáticas. Este mito es completamente falso.', category: 'Historia' },
  { statement: 'Los espaguetis con salsa de tomate son un plato italiano tradicional.', isTrue: false, explanation: 'Los tomates no llegaron a Europa desde América hasta el siglo XVI. La pasta tradicional se condimentaba de otra manera.', category: 'Historia' },

  // Geografía
  { statement: 'Rusia tiene once husos horarios.', isTrue: true, explanation: 'Desde Kaliningrado hasta Kamchatka, Rusia se extiende por 11 husos horarios.', category: 'Geografía' },
  { statement: 'El Amazonas es el río más largo del mundo.', isTrue: false, explanation: 'El Nilo con aprox. 6.650 km es considerado el río más largo, el Amazonas es el de mayor caudal.', category: 'Geografía' },
  { statement: 'Islandia no tiene mosquitos.', isTrue: true, explanation: 'Islandia es uno de los pocos países del mundo sin especies de mosquitos autóctonas.', category: 'Geografía' },
  { statement: 'El Sahara es el desierto más grande del mundo.', isTrue: false, explanation: 'La Antártida es el desierto más grande (14 mill. km²). El Sahara es el desierto cálido más grande.', category: 'Geografía' },
  { statement: 'En Australia hay más canguros que personas.', isTrue: true, explanation: 'Hay unos 50 millones de canguros frente a 26 millones de personas en Australia.', category: 'Geografía' },
  { statement: 'El Monte Everest es la montaña más alta medida desde el centro de la Tierra.', isTrue: false, explanation: 'El Chimborazo en Ecuador es el punto más alejado del centro de la Tierra, porque la Tierra es más ancha en el ecuador.', category: 'Geografía' },

  // Curiosidades
  { statement: 'En Suiza es ilegal tener un solo cobaya.', isTrue: true, explanation: 'Los cobayas son animales sociales. Las leyes suizas de protección animal prohíben tenerlos solos.', category: 'Curiosidades' },
  { statement: 'Hay más estrellas en el universo que granos de arena en la Tierra.', isTrue: true, explanation: 'Estimaciones: aprox. 10^24 estrellas en el universo observable, aprox. 7,5×10^18 granos de arena.', category: 'Curiosidades' },
  { statement: 'Un caracol puede dormir hasta 3 años.', isTrue: true, explanation: 'Algunas especies de caracoles pueden entrar en un estado de reposo prolongado, especialmente durante la sequía.', category: 'Curiosidades' },
  { statement: 'El inventor del envase de Pringles fue enterrado en uno.', isTrue: true, explanation: 'Fredric Baur, el inventor del envase de Pringles, fue enterrado en uno en 2008 por deseo propio.', category: 'Curiosidades' },
  { statement: 'Las vacas pueden subir escaleras, pero no bajarlas.', isTrue: true, explanation: 'Debido a la estructura de sus rodillas y su campo de visión, las vacas no pueden bajar escaleras de forma segura.', category: 'Curiosidades' },
  { statement: 'Cada persona se traga un promedio de 8 arañas al año mientras duerme.', isTrue: false, explanation: 'Este mito fue inventado en 1993 a propósito como ejemplo de datos falsos.', category: 'Curiosidades' },
  { statement: 'Según la física, los abejorros no deberían poder volar.', isTrue: false, explanation: 'Este rumor se basa en cálculos erróneos. La aerodinámica del vuelo del abejorro está explicada desde hace tiempo.', category: 'Curiosidades' },
  { statement: 'En Japón hay una isla llena de gatos donde superan en número a los humanos.', isTrue: true, explanation: 'Aoshima, también conocida como la Isla de los Gatos, tiene una proporción de aproximadamente 6:1 gatos por persona.', category: 'Curiosidades' },
  { statement: 'La guerra más corta de la historia duró 38 minutos.', isTrue: true, explanation: 'La guerra anglo-zanzibarí de 1896 duró entre 38 y 45 minutos.', category: 'Curiosidades' },
  { statement: 'Los flamencos son rosados de nacimiento.', isTrue: false, explanation: 'Los flamencos nacen gris-blancos y se vuelven rosados por su alimentación (crustáceos, algas).', category: 'Curiosidades' },

  // Tecnología
  { statement: 'El primer iPhone no tenía App Store.', isTrue: true, explanation: 'El primer iPhone salió en 2007, la App Store no se lanzó hasta 2008.', category: 'Tecnología' },
  { statement: 'El primer SMS del mundo decía "Merry Christmas".', isTrue: true, explanation: 'El 3 de diciembre de 1992, Neil Papworth envió el primer SMS con el texto "Merry Christmas".', category: 'Tecnología' },
  { statement: 'WiFi significa Wireless Fidelity.', isTrue: false, explanation: 'WiFi es un nombre de marca y no significa nada. Fue inventado por una empresa de marketing.', category: 'Tecnología' },
  { statement: 'El primer ordenador era tan grande como una habitación.', isTrue: true, explanation: 'ENIAC (1945) pesaba 27 toneladas y ocupaba 167 metros cuadrados.', category: 'Tecnología' },
  { statement: 'Los correos electrónicos no consumen electricidad.', isTrue: false, explanation: 'Cada correo electrónico consume aprox. 4g de CO2, ya que los servidores y las redes necesitan energía.', category: 'Tecnología' },

  // Nuevos datos (50)
  { statement: 'Los wombats producen heces con forma de cubo.', isTrue: true, explanation: 'Los wombats tienen un intestino especial que da forma cúbica a sus deposiciones para que no rueden.', category: 'Naturaleza' },
  { statement: 'La Torre Eiffel es más baja en invierno que en verano.', isTrue: true, explanation: 'Con el frío, el metal se contrae, haciendo que la torre encoja hasta 15 cm.', category: 'Curiosidades' },
  { statement: 'Las vacas tienen cuatro estómagos.', isTrue: true, explanation: 'Las vacas tienen cuatro compartimentos estomacales: rumen, retículo, omaso y abomaso.', category: 'Naturaleza' },
  { statement: 'Un avestruz puede correr más rápido que un caballo.', isTrue: true, explanation: 'Los avestruces pueden alcanzar hasta 70 km/h, mientras que los caballos llegan a un máximo de 65 km/h.', category: 'Naturaleza' },
  { statement: 'La Tierra gira más rápido que hace un millón de años.', isTrue: false, explanation: 'La Tierra gira más lento. Debido a las fuerzas de marea de la Luna, los días se hacen más largos.', category: 'Ciencia' },
  { statement: 'Venecia tiene más puentes que Ámsterdam.', isTrue: false, explanation: 'Ámsterdam tiene más de 1.500 puentes, Venecia solo unos 400.', category: 'Geografía' },
  { statement: 'El Amazonas desemboca en el mar sin un solo puente.', isTrue: true, explanation: 'No hay ningún puente que cruce todo el Amazonas — fluye a través de selva tropical demasiado densa.', category: 'Geografía' },
  { statement: 'Las abejas pueden reconocer rostros.', isTrue: true, explanation: 'Estudios demuestran que las abejas melíferas pueden distinguir y reconocer rostros humanos.', category: 'Naturaleza' },
  { statement: 'Marte tiene la montaña más alta del sistema solar.', isTrue: true, explanation: 'El Olympus Mons en Marte, con unos 22 km, es la montaña más alta conocida del sistema solar.', category: 'Ciencia' },
  { statement: 'El chocolate es tóxico para los perros.', isTrue: true, explanation: 'La teobromina del chocolate puede ser mortal para los perros, ya que no pueden metabolizarla.', category: 'Naturaleza' },
  { statement: 'En Australia los árboles no pierden hojas, sino corteza.', isTrue: true, explanation: 'Muchas especies de eucalipto mudan su corteza en lugar de sus hojas.', category: 'Naturaleza' },
  { statement: 'El corazón de una gamba está en su cabeza.', isTrue: true, explanation: 'El corazón de una gamba se encuentra efectivamente en su cabeza.', category: 'Naturaleza' },
  { statement: 'El Vaticano tiene la tasa de criminalidad per cápita más alta del mundo.', isTrue: true, explanation: 'Como el Vaticano solo tiene unos 800 habitantes, unos pocos delitos generan una alta tasa per cápita.', category: 'Curiosidades' },
  { statement: 'Una persona puede sobrevivir en el espacio si contiene la respiración.', isTrue: false, explanation: 'En el vacío, el aire sería expulsado de los pulmones con fuerza. Se perdería la consciencia en unos 15 segundos.', category: 'Ciencia' },
  { statement: 'El papel solo se puede doblar un máximo de 7 veces.', isTrue: false, explanation: 'Aunque es difícil, el papel ya se ha doblado 12 veces (con una hoja suficientemente grande).', category: 'Curiosidades' },
  { statement: 'La Gran Muralla China tiene más de 21.000 km de longitud.', isTrue: true, explanation: 'Con todas las murallas secundarias y ramificaciones, mide un total de 21.196 km.', category: 'Historia' },
  { statement: 'Finlandia tiene más saunas que coches.', isTrue: true, explanation: 'Finlandia tiene aprox. 3,3 millones de saunas para 5,5 millones de habitantes — más que coches.', category: 'Curiosidades' },
  { statement: 'El corazón de una ballena azul es tan grande como un coche pequeño.', isTrue: true, explanation: 'El corazón de una ballena azul puede pesar hasta 600 kg y es tan grande como un Volkswagen Escarabajo.', category: 'Naturaleza' },
  { statement: 'El sol es amarillo.', isTrue: false, explanation: 'El sol es en realidad blanco. Nos parece amarillo debido a la atmósfera de la Tierra.', category: 'Ciencia' },
  { statement: 'Los peces pueden ahogarse.', isTrue: true, explanation: 'Si hay muy poco oxígeno en el agua, los peces pueden asfixiarse.', category: 'Naturaleza' },
  { statement: 'El Monte Everest crece unos 4 milímetros al año.', isTrue: true, explanation: 'Debido al movimiento de las placas tectónicas, el Himalaya sigue creciendo.', category: 'Ciencia' },
  { statement: 'El kétchup se vendía como medicina en el siglo XIX.', isTrue: true, explanation: 'En la década de 1830, el kétchup de tomate se vendía como remedio contra la diarrea.', category: 'Historia' },
  { statement: 'El vuelo más corto del mundo dura 57 segundos.', isTrue: true, explanation: 'El vuelo entre Westray y Papa Westray en Escocia dura apenas un minuto.', category: 'Curiosidades' },
  { statement: 'Los pulpos tienen tres cerebros.', isTrue: false, explanation: 'Los pulpos tienen nueve cerebros — uno central y uno adicional en cada uno de los ocho brazos.', category: 'Naturaleza' },
  { statement: 'Brasil lleva el nombre de un árbol.', isTrue: true, explanation: 'Brasil recibe su nombre del palo brasil (Pau-Brasil), abundante en la zona.', category: 'Historia' },
  { statement: 'Un colibrí puede volar hacia atrás.', isTrue: true, explanation: 'Los colibríes son las únicas aves que realmente pueden volar hacia atrás.', category: 'Naturaleza' },
  { statement: 'La nariz crece durante toda la vida.', isTrue: true, explanation: 'La nariz y las orejas nunca dejan de crecer, ya que están hechas de cartílago.', category: 'Ciencia' },
  { statement: 'En Japón es habitual comer en la bañera.', isTrue: false, explanation: 'En Japón el baño se considera un lugar de purificación. Comer en él sería inusual.', category: 'Curiosidades' },
  { statement: 'El estómago humano produce unos 2 litros de ácido clorhídrico al día.', isTrue: true, explanation: 'El ácido gástrico es lo suficientemente fuerte como para disolver metal, pero está protegido por la mucosa.', category: 'Ciencia' },
  { statement: 'Hay más árboles en la Tierra que estrellas en la Vía Láctea.', isTrue: true, explanation: 'Hay unos 3 billones de árboles en la Tierra, pero solo 100-400 mil millones de estrellas en la Vía Láctea.', category: 'Naturaleza' },
  { statement: 'El color naranja recibió su nombre de la fruta, no al revés.', isTrue: true, explanation: 'Antes de la naranja, el color se llamaba en inglés "geoluhread" (amarillo-rojo). La fruta le dio el nombre al color.', category: 'Curiosidades' },
  { statement: 'Los plátanos son radiactivos.', isTrue: true, explanation: 'Los plátanos contienen potasio-40, un isótopo radiactivo. Pero la radiación es completamente inofensiva.', category: 'Ciencia' },
  { statement: 'Un día en Plutón dura más que una semana en la Tierra.', isTrue: true, explanation: 'Un día en Plutón dura 6,4 días terrestres — casi una semana terrestre entera.', category: 'Ciencia' },
  { statement: 'En Suiza no se puede tirar de la cadena después de las 22 horas.', isTrue: false, explanation: 'Esto es un mito muy extendido. No existe tal ley en Suiza.', category: 'Curiosidades' },
  { statement: 'La risa es contagiosa porque el cerebro activa las neuronas espejo.', isTrue: true, explanation: 'Las neuronas espejo del cerebro reaccionan a la risa de otros y desencadenan reacciones similares.', category: 'Ciencia' },
  { statement: 'Rusia tiene una superficie mayor que Plutón.', isTrue: true, explanation: 'Rusia tiene 17,1 mill. km², la superficie de Plutón es de solo 16,7 mill. km².', category: 'Geografía' },
  { statement: 'Una cucharadita de material de estrella de neutrones pesa 6 mil millones de toneladas.', isTrue: true, explanation: 'Las estrellas de neutrones son tan densas que una cucharadita de su material pesa miles de millones de toneladas.', category: 'Ciencia' },
  { statement: 'Los gatos tienen más huesos que los humanos.', isTrue: true, explanation: 'Los gatos tienen aprox. 230 huesos, los humanos solo 206.', category: 'Naturaleza' },
  { statement: 'El Océano Atlántico se hace más ancho cada año.', isTrue: true, explanation: 'Por la tectónica de placas, el Atlántico se ensancha unos 2,5 cm al año.', category: 'Ciencia' },
  { statement: 'En Noruega hay un pueblo que se llama "Hell".', isTrue: true, explanation: 'Hell es un lugar en el municipio de Verdal en Noruega. En invierno, Hell se congela regularmente.', category: 'Geografía' },
  { statement: 'Las hormigas pueden nadar.', isTrue: true, explanation: 'La mayoría de las especies de hormigas pueden nadar y forman pequeñas balsas durante las inundaciones.', category: 'Naturaleza' },
  { statement: 'Los humanos comparten el 60% de su ADN con un plátano.', isTrue: true, explanation: 'Los humanos y los plátanos comparten efectivamente alrededor del 60% de genes idénticos.', category: 'Ciencia' },
  { statement: 'En Venus llueve ácido sulfúrico.', isTrue: true, explanation: 'Las nubes de Venus están formadas por gotitas de ácido sulfúrico, que se evaporan antes de llegar al suelo.', category: 'Ciencia' },
  { statement: 'La Universidad de Oxford existía antes del Imperio Azteca y antes de la construcción de Machu Picchu.', isTrue: true, explanation: 'Oxford comenzó a partir de 1096, el Imperio Azteca se fundó en 1428, Machu Picchu se construyó alrededor de 1450.', category: 'Historia' },
  { statement: 'Un camaleón cambia de color para camuflarse.', isTrue: false, explanation: 'Los camaleones cambian de color principalmente para comunicarse y regular su temperatura, no para camuflarse.', category: 'Naturaleza' },
  { statement: 'El olor a hierba recién cortada es en realidad una señal de auxilio de las plantas.', isTrue: true, explanation: 'Las plantas liberan sustancias químicas cuando son heridas — el olor es una reacción de estrés.', category: 'Naturaleza' },
  { statement: 'En Suecia hay un hotel hecho completamente de hielo.', isTrue: true, explanation: 'El Icehotel en Jukkasjärvi se reconstruye cada invierno con hielo y nieve.', category: 'Curiosidades' },
  { statement: 'Las arañas pueden volar.', isTrue: true, explanation: 'Algunas arañas usan el "ballooning" — se dejan llevar por el viento con hilos de seda.', category: 'Naturaleza' },
  { statement: 'La luz del sol tarda 8 segundos en llegar a la Tierra.', isTrue: false, explanation: 'Tarda aproximadamente 8 minutos y 20 segundos, no 8 segundos.', category: 'Ciencia' },
  { statement: 'Un pingüino puede saltar más alto que una casa.', isTrue: true, explanation: 'Este es un dato humorístico — las casas no pueden saltar, así que el pingüino gana.', category: 'Curiosidades' },
];
