import type { Fact } from './fakeorfact-content-de';

export const FACTS_TR: Fact[] = [
  // Doğa ve Hayvanlar
  { statement: 'Ahtapotların üç kalbi vardır.', isTrue: true, explanation: 'İki solungaç kalbi kanı solungaçlara, bir ana kalp ise vücuda pompalar.', category: 'Doğa' },
  { statement: 'Japon balıklarının hafızası sadece 3 saniyedir.', isTrue: false, explanation: 'Japon balıkları aylarca hatırlayabilir — 3 saniyelik hafıza efsanesi yanlıştır.', category: 'Doğa' },
  { statement: 'Bal asla bozulmaz.', isTrue: true, explanation: 'Mısır mezarlarında bulunan 3000 yıllık balın hâlâ yenilebilir durumda olduğu tespit edilmiştir.', category: 'Doğa' },
  { statement: 'Timsahlar dilleriyle yalayamazlar.', isTrue: true, explanation: 'Timsahın dili damağına yapışıktır ve dışarı çıkarılamaz.', category: 'Doğa' },
  { statement: 'Filler zıplayamayan tek hayvanlardır.', isTrue: true, explanation: 'Ağırlıkları ve kemik yapıları nedeniyle filler gerçekten zıplayamazlar.', category: 'Doğa' },
  { statement: 'Muzlar ağaçlarda yetişir.', isTrue: false, explanation: 'Muz bitkileri ağaç değil, dev otsu bitkilerdir.', category: 'Doğa' },
  { statement: 'Yıldırım aynı yere iki kez düşebilir.', isTrue: true, explanation: 'Empire State Building gibi yüksek binalar yılda 100 keze kadar yıldırım çarpmasına maruz kalır.', category: 'Doğa' },
  { statement: 'Yunuslar bir gözleri açık uyur.', isTrue: true, explanation: 'Yunuslar beynin bir yarısıyla uyur ve avcılara karşı bir gözlerini açık tutarlar.', category: 'Doğa' },
  { statement: 'Koalalar su içmez.', isTrue: false, explanation: 'Koalalar okaliptüs yapraklarından nem aldıkları için nadiren su içerler, ancak sıcak havalarda içerler.', category: 'Doğa' },
  { statement: 'Kelebekler ayaklarıyla tat alır.', isTrue: true, explanation: 'Kelebeklerin ayaklarında bitkileri tanımlayan tat reseptörleri bulunur.', category: 'Doğa' },

  // Bilim
  { statement: 'Ses ışıktan daha hızlı yol alır.', isTrue: false, explanation: 'Işık yaklaşık 300.000 km/s hızla, ses ise yalnızca yaklaşık 343 m/s hızla yol alır.', category: 'Bilim' },
  { statement: 'İnsan vücudunun yaklaşık %60\'ı sudan oluşur.', isTrue: true, explanation: 'İnsan vücudu yaşa bağlı olarak %50-75 oranında sudan oluşur.', category: 'Bilim' },
  { statement: 'Venüs, çoğu gezegenin tersi yönünde döner.', isTrue: true, explanation: 'Venüs\'ün ters yönlü dönüşü vardır — güneş orada batıdan doğar.', category: 'Bilim' },
  { statement: 'Cam bir sıvıdır.', isTrue: false, explanation: 'Cam amorf bir katıdır. Eski pencerelerde camın aktığı efsanesi yanlıştır.', category: 'Bilim' },
  { statement: 'Venüs\'te bir gün, Venüs\'te bir yıldan daha uzundur.', isTrue: true, explanation: 'Bir dönüş 243 Dünya günü sürerken, Güneş\'in etrafındaki yörüngesi sadece 225 Dünya günü sürer.', category: 'Bilim' },
  { statement: 'İnsanlar beyninin yalnızca %10\'unu kullanır.', isTrue: false, explanation: 'Beyin taramaları, beynin neredeyse tüm bölgelerini kullandığımızı gösterir, sadece hepsini aynı anda değil.', category: 'Bilim' },
  { statement: 'Elmaslar kömürden oluşur.', isTrue: false, explanation: 'Elmaslar aşırı basınç altında karbondan oluşur, ancak kömürden değil — çoğu, Dünya\'daki bitkilerden daha eskidir.', category: 'Bilim' },
  { statement: 'Uzayda mutlak sessizlik hüküm sürer.', isTrue: true, explanation: 'Ses yayılmak için bir ortama ihtiyaç duyar. Uzayın boşluğunda böyle bir ortam yoktur.', category: 'Bilim' },
  { statement: 'İnsan vücudunda kendi hücrelerinden daha fazla bakteri bulunur.', isTrue: true, explanation: 'Tahminlere göre vücutta yaklaşık 38 trilyon bakteri ve 30 trilyon kendi hücresi vardır.', category: 'Bilim' },
  { statement: 'Su elektrik iletir.', isTrue: false, explanation: 'Saf su elektrik iletmez. Suda çözünmüş mineraller ve tuzlar onu iletken yapar.', category: 'Bilim' },

  // Tarih
  { statement: 'Kleopatra, piramitlerin inşasından çok Ay\'a inişe daha yakın yaşadı.', isTrue: true, explanation: 'Piramitler yaklaşık MÖ 2560\'ta inşa edildi, Kleopatra MÖ 69-30 yılları arasında yaşadı, Ay\'a iniş 1969\'da gerçekleşti.', category: 'Tarih' },
  { statement: 'Napolyon alışılmadık derecede kısaydı.', isTrue: false, explanation: 'Napolyon yaklaşık 1,70 m boyundaydı — dönemine göre ortalama. Efsane İngiliz propagandasından kaynaklanır.', category: 'Tarih' },
  { statement: 'Çin Seddi Ay\'dan görülebilir.', isTrue: false, explanation: 'Astronotlar, seddin Ay\'dan görülemeyeceğini doğrulamıştır — çok dardır.', category: 'Tarih' },
  { statement: 'Oxford Üniversitesi Aztek İmparatorluğu\'ndan daha eskidir.', isTrue: true, explanation: 'Oxford 1096\'dan itibaren kuruldu, Aztek İmparatorluğu ise ancak 1428\'de.', category: 'Tarih' },
  { statement: 'Vikingler boynuzlu miğfer takardı.', isTrue: false, explanation: 'Arkeolojik buluntular boynuzsuz basit miğferler göstermektedir. Klişe 19. yüzyıldan gelmektedir.', category: 'Tarih' },
  { statement: 'Antik çağda insanlar Dünya\'nın düz olduğunu düşünüyordu.', isTrue: false, explanation: 'Eski Yunanlılar Dünya\'nın yuvarlak olduğunu biliyordu. Eratosthenes çevresini bile hesapladı.', category: 'Tarih' },
  { statement: 'Eyfel Kulesi 20 yıl sonra yıkılacaktı.', isTrue: true, explanation: '1889\'da geçici bir yapı olarak inşa edildi ve yalnızca radyo kulesi olarak işe yaradığı için ayakta kaldı.', category: 'Tarih' },
  { statement: 'Titanic batmaz olarak tanıtılmıştı.', isTrue: false, explanation: 'White Star Line onu hiçbir zaman resmi olarak batmaz olarak adlandırmadı. Bu basının abartısıydı.', category: 'Tarih' },
  { statement: 'Albert Einstein matematikten kalmıştı.', isTrue: false, explanation: 'Einstein matematikte en yüksek notları almıştı. Bu efsane tamamen yanlıştır.', category: 'Tarih' },
  { statement: 'Domates soslu spagetti geleneksel bir İtalyan yemeğidir.', isTrue: false, explanation: 'Domatesler Avrupa\'ya Amerika\'dan ancak 16. yüzyılda geldi. Geleneksel makarna farklı şekilde baharatlanırdı.', category: 'Tarih' },

  // Coğrafya
  { statement: 'Rusya\'nın on bir saat dilimi vardır.', isTrue: true, explanation: 'Kaliningrad\'dan Kamçatka\'ya kadar Rusya 11 saat dilimine yayılır.', category: 'Coğrafya' },
  { statement: 'Amazon dünyanın en uzun nehridir.', isTrue: false, explanation: 'Yaklaşık 6.650 km ile Nil en uzun nehir olarak kabul edilir, Amazon ise en çok su taşıyan nehirdir.', category: 'Coğrafya' },
  { statement: 'İzlanda\'da sivrisinek yoktur.', isTrue: true, explanation: 'İzlanda gerçekten de yerli sivrisinek türü olmayan dünyadaki birkaç ülkeden biridir.', category: 'Coğrafya' },
  { statement: 'Sahra dünyanın en büyük çölüdür.', isTrue: false, explanation: 'Antarktika en büyük çöldür (14 milyon km²). Sahra en büyük sıcak çöldür.', category: 'Coğrafya' },
  { statement: 'Avustralya\'da insandan daha fazla kanguru vardır.', isTrue: true, explanation: 'Avustralya\'da yaklaşık 50 milyon kanguru ve 26 milyon insan bulunmaktadır.', category: 'Coğrafya' },
  { statement: 'Everest Dağı, Dünya\'nın merkezinden ölçüldüğünde en yüksek dağdır.', isTrue: false, explanation: 'Ekvador\'daki Chimborazo, Dünya\'nın merkezine en uzak noktadadır çünkü Dünya ekvatorda daha kalındır.', category: 'Coğrafya' },

  // İlginç Bilgiler
  { statement: 'İsviçre\'de tek bir kobay beslemek yasaktır.', isTrue: true, explanation: 'Kobaylar sosyal hayvanlardır. İsviçre hayvan koruma yasaları tek başına beslemeyi yasaklar.', category: 'İlginç Bilgiler' },
  { statement: 'Evrende, Dünya\'daki kum tanelerinden daha fazla yıldız vardır.', isTrue: true, explanation: 'Tahminler: gözlemlenebilir evrende yaklaşık 10^24 yıldız, yaklaşık 7,5×10^18 kum tanesi.', category: 'İlginç Bilgiler' },
  { statement: 'Bir salyangoz 3 yıla kadar uyuyabilir.', isTrue: true, explanation: 'Bazı salyangoz türleri, özellikle kurak dönemlerde uzun süreli uyku haline geçebilir.', category: 'İlginç Bilgiler' },
  { statement: 'Pringles kutusunun mucidi bir tanesinin içine gömüldü.', isTrue: true, explanation: 'Fredric Baur, Pringles kutusunun mucidi, 2008\'de kendi isteğiyle bir tanesinin içine gömüldü.', category: 'İlginç Bilgiler' },
  { statement: 'İnekler merdiven çıkabilir ama inemez.', isTrue: true, explanation: 'Diz yapıları ve görüş alanları nedeniyle inekler merdivenlerden güvenli şekilde inemez.', category: 'İlginç Bilgiler' },
  { statement: 'Her insan uykuda yılda ortalama 8 örümcek yutar.', isTrue: false, explanation: 'Bu efsane 1993\'te sahte gerçeklere örnek olarak bilerek uydurulmuştur.', category: 'İlginç Bilgiler' },
  { statement: 'Fiziğe göre yaban arıları aslında uçamamalıdır.', isTrue: false, explanation: 'Bu söylenti yanlış hesaplamalara dayanır. Yaban arısı uçuşunun aerodinamiği çoktan açıklanmıştır.', category: 'İlginç Bilgiler' },
  { statement: 'Japonya\'da kedilerin insanlardan çok olduğu bir kedi adası vardır.', isTrue: true, explanation: 'Kedi adası olarak da bilinen Aoshima\'da kedilerin insanlara oranı yaklaşık 6:1\'dir.', category: 'İlginç Bilgiler' },
  { statement: 'Tarihin en kısa savaşı 38 dakika sürmüştür.', isTrue: true, explanation: '1896 İngiliz-Zanzibar Savaşı 38 ile 45 dakika arasında sürmüştür.', category: 'İlginç Bilgiler' },
  { statement: 'Flamingolar doğuştan pembedir.', isTrue: false, explanation: 'Flamingolar gri-beyaz doğar ve besinleri (kabuklu deniz hayvanları, yosunlar) sayesinde pembeye döner.', category: 'İlginç Bilgiler' },

  // Teknoloji
  { statement: 'İlk iPhone\'da App Store yoktu.', isTrue: true, explanation: 'İlk iPhone 2007\'de çıktı, App Store ancak 2008\'de başlatıldı.', category: 'Teknoloji' },
  { statement: 'Dünyanın ilk SMS\'i "Merry Christmas" yazıyordu.', isTrue: true, explanation: '3 Aralık 1992\'de Neil Papworth "Merry Christmas" metnini içeren ilk SMS\'i gönderdi.', category: 'Teknoloji' },
  { statement: 'WiFi, Wireless Fidelity anlamına gelir.', isTrue: false, explanation: 'WiFi bir marka adıdır ve hiçbir şeyin kısaltması değildir. Bir pazarlama firması tarafından yaratılmıştır.', category: 'Teknoloji' },
  { statement: 'İlk bilgisayar bir oda büyüklüğündeydi.', isTrue: true, explanation: 'ENIAC (1945) 27 ton ağırlığındaydı ve 167 metrekare yer kaplıyordu.', category: 'Teknoloji' },
  { statement: 'E-postalar elektrik tüketmez.', isTrue: false, explanation: 'Her e-posta yaklaşık 4 g CO2 üretir çünkü sunucular ve ağlar enerji gerektirir.', category: 'Teknoloji' },

  // Yeni Bilgiler (50)
  { statement: 'Vombatlar küp şeklinde dışkı üretir.', isTrue: true, explanation: 'Vombatların özel bir bağırsak yapısı vardır ve küp biçimli dışkı üretir, böylece yuvarlanmaz.', category: 'Doğa' },
  { statement: 'Eyfel Kulesi kışın yazdan daha kısadır.', isTrue: true, explanation: 'Soğukta metal büzüşür ve kule 15 cm\'ye kadar kısalır.', category: 'İlginç Bilgiler' },
  { statement: 'İneklerin dört midesi vardır.', isTrue: true, explanation: 'İneklerin gerçekten dört mide bölümü vardır: işkembe, börkenek, kırkbayır ve şirden.', category: 'Doğa' },
  { statement: 'Bir devekuşu attan daha hızlı koşabilir.', isTrue: true, explanation: 'Devekuşları saatte 70 km\'ye ulaşabilirken, atlar en fazla 65 km/s hıza çıkar.', category: 'Doğa' },
  { statement: 'Dünya bir milyon yıl öncesine göre daha hızlı dönüyor.', isTrue: false, explanation: 'Dünya daha yavaş dönüyor. Ay\'ın gelgit kuvvetleri nedeniyle günler uzuyor.', category: 'Bilim' },
  { statement: 'Venedik\'te Amsterdam\'dan daha fazla köprü vardır.', isTrue: false, explanation: 'Amsterdam\'da 1.500\'den fazla köprü varken, Venedik\'te yalnızca yaklaşık 400 köprü bulunur.', category: 'Coğrafya' },
  { statement: 'Amazon, üzerinde tek bir köprü olmadan denize dökülür.', isTrue: true, explanation: 'Amazon Nehri\'nin tamamında hiçbir köprü yoktur — çok yoğun yağmur ormanından akar.', category: 'Coğrafya' },
  { statement: 'Arılar yüzleri tanıyabilir.', isTrue: true, explanation: 'Araştırmalar, bal arılarının insan yüzlerini ayırt edebildiğini ve tanıyabildiğini göstermektedir.', category: 'Doğa' },
  { statement: 'Mars, Güneş Sistemi\'ndeki en yüksek dağa sahiptir.', isTrue: true, explanation: 'Mars\'taki Olympus Mons yaklaşık 22 km yüksekliğiyle Güneş Sistemi\'ndeki bilinen en yüksek dağdır.', category: 'Bilim' },
  { statement: 'Çikolata köpekler için zehirlidir.', isTrue: true, explanation: 'Çikolatadaki teobromin köpekler için ölümcül olabilir çünkü onu metabolize edemezler.', category: 'Doğa' },
  { statement: 'Avustralya\'da ağaçlar yapraklarını değil kabuklarını döker.', isTrue: true, explanation: 'Birçok okaliptüs türü yaprakları yerine kabuklarını döker.', category: 'Doğa' },
  { statement: 'Karidessin kalbi başındadır.', isTrue: true, explanation: 'Bir karidesin kalbi gerçekten başında yer alır.', category: 'Doğa' },
  { statement: 'Vatikan, kişi başına düşen suç oranı bakımından dünyanın en yüksek değerine sahiptir.', isTrue: true, explanation: 'Vatikan\'ın yalnızca yaklaşık 800 sakini olduğundan, birkaç suç bile yüksek bir kişi başı orana yol açar.', category: 'İlginç Bilgiler' },
  { statement: 'Bir insan nefesini tutarsa uzayda hayatta kalabilir.', isTrue: false, explanation: 'Boşlukta hava ciğerlerden zorla çekilir. Yaklaşık 15 saniyede bilincini kaybedersiniz.', category: 'Bilim' },
  { statement: 'Kâğıt en fazla 7 kez katlanabilir.', isTrue: false, explanation: 'Zor olsa da kâğıt zaten 12 kez katlanmıştır (yeterince büyük bir kâğıtla).', category: 'İlginç Bilgiler' },
  { statement: 'Çin Seddi 21.000 km\'den uzundur.', isTrue: true, explanation: 'Tüm yan duvarları ve dallanmalarıyla birlikte toplam 21.196 km uzunluğundadır.', category: 'Tarih' },
  { statement: 'Finlandiya\'da arabadan daha fazla sauna vardır.', isTrue: true, explanation: 'Finlandiya\'da 5,5 milyon nüfusa karşı yaklaşık 3,3 milyon sauna vardır — bu arabalardan fazladır.', category: 'İlginç Bilgiler' },
  { statement: 'Mavi balinanın kalbi küçük bir araba büyüklüğündedir.', isTrue: true, explanation: 'Mavi balinanın kalbi 600 kg\'a kadar ağırlığa ulaşabilir ve bir VW Beetle büyüklüğündedir.', category: 'Doğa' },
  { statement: 'Güneş sarıdır.', isTrue: false, explanation: 'Güneş aslında beyazdır. Dünya\'nın atmosferi nedeniyle bize sarı görünür.', category: 'Bilim' },
  { statement: 'Balıklar boğulabilir.', isTrue: true, explanation: 'Suda yeterli oksijen olmadığında balıklar gerçekten boğulabilir.', category: 'Doğa' },
  { statement: 'Everest Dağı her yıl yaklaşık 4 milimetre yükselir.', isTrue: true, explanation: 'Tektonik plaka hareketleri sayesinde Himalayalar hâlâ yükselmektedir.', category: 'Bilim' },
  { statement: 'Ketçap 19. yüzyılda ilaç olarak satılıyordu.', isTrue: true, explanation: '1830\'larda domates ketçabı ishal ilacı olarak satılıyordu.', category: 'Tarih' },
  { statement: 'Dünyanın en kısa uçuşu 57 saniye sürer.', isTrue: true, explanation: 'İskoçya\'da Westray ve Papa Westray arasındaki uçuş sadece bir dakika sürer.', category: 'İlginç Bilgiler' },
  { statement: 'Ahtapotların üç beyni vardır.', isTrue: false, explanation: 'Ahtapotların dokuz beyni vardır — bir merkezi beyin ve sekiz kolun her birinde birer ek beyin.', category: 'Doğa' },
  { statement: 'Brezilya adını bir ağaçtan almıştır.', isTrue: true, explanation: 'Brezilya, bölgede bol miktarda bulunan brezilya ağacından (Pau-Brasil) adını almıştır.', category: 'Tarih' },
  { statement: 'Sinek kuşu geriye doğru uçabilir.', isTrue: true, explanation: 'Sinek kuşları gerçekten geriye doğru uçabilen tek kuşlardır.', category: 'Doğa' },
  { statement: 'Burun ömür boyu büyümeye devam eder.', isTrue: true, explanation: 'Burun ve kulaklar kıkırdaktan oluştuğu için büyümeyi asla bırakmazlar.', category: 'Bilim' },
  { statement: 'Japonya\'da küvette yemek yemek yaygındır.', isTrue: false, explanation: 'Japonya\'da banyo bir arınma yeri olarak görülür. İçinde yemek yemek alışılmadık olurdu.', category: 'İlginç Bilgiler' },
  { statement: 'İnsan midesi günde yaklaşık 2 litre hidroklorik asit üretir.', isTrue: true, explanation: 'Mide asidi metali eritecek kadar güçlüdür, ancak mukoza tabakası tarafından korunur.', category: 'Bilim' },
  { statement: 'Dünya\'da Samanyolu\'ndaki yıldızlardan daha fazla ağaç vardır.', isTrue: true, explanation: 'Dünya\'da yaklaşık 3 trilyon ağaç varken, Samanyolu\'nda yalnızca 100-400 milyar yıldız bulunur.', category: 'Doğa' },
  { statement: 'Turuncu rengi adını meyveden almıştır, tersi değil.', isTrue: true, explanation: 'Portakaldan önce bu renk İngilizce\'de "geoluhread" (sarı-kırmızı) olarak adlandırılıyordu. Meyve renge adını verdi.', category: 'İlginç Bilgiler' },
  { statement: 'Muzlar radyoaktiftir.', isTrue: true, explanation: 'Muzlar radyoaktif bir izotop olan potasyum-40 içerir. Ancak radyasyon tamamen zararsızdır.', category: 'Bilim' },
  { statement: 'Plüton\'da bir gün, Dünya\'da bir haftadan uzundur.', isTrue: true, explanation: 'Plüton\'da bir gün 6,4 Dünya günü sürer — neredeyse tam bir Dünya haftası.', category: 'Bilim' },
  { statement: 'İsviçre\'de saat 22\'den sonra sifon çekmek yasaktır.', isTrue: false, explanation: 'Bu yaygın bir efsanedir. İsviçre\'de böyle bir yasa yoktur.', category: 'İlginç Bilgiler' },
  { statement: 'Gülmek bulaşıcıdır çünkü beyin ayna nöronlarını aktive eder.', isTrue: true, explanation: 'Beyindeki ayna nöronlar başkalarının gülüşüne tepki verir ve benzer tepkilere yol açar.', category: 'Bilim' },
  { statement: 'Rusya\'nın yüz ölçümü Plüton\'dan büyüktür.', isTrue: true, explanation: 'Rusya 17,1 milyon km² iken Plüton\'un yüzeyi yalnızca 16,7 milyon km²\'dir.', category: 'Coğrafya' },
  { statement: 'Bir çay kaşığı nötron yıldızı maddesi 6 milyar ton ağırlığındadır.', isTrue: true, explanation: 'Nötron yıldızları o kadar yoğundur ki bir çay kaşığı maddeleri milyarlarca ton ağırlığındadır.', category: 'Bilim' },
  { statement: 'Kedilerin insanlardan daha fazla kemiği vardır.', isTrue: true, explanation: 'Kedilerin yaklaşık 230 kemiği varken, insanların yalnızca 206 kemiği vardır.', category: 'Doğa' },
  { statement: 'Atlas Okyanusu her yıl genişler.', isTrue: true, explanation: 'Levha tektoniği nedeniyle Atlantik her yıl yaklaşık 2,5 cm genişler.', category: 'Bilim' },
  { statement: 'Norveç\'te "Hell" adında bir yer vardır.', isTrue: true, explanation: 'Hell, Norveç\'in Verdal belediyesinde bir yerleşim yeridir. Kışın Hell düzenli olarak donar.', category: 'Coğrafya' },
  { statement: 'Karıncalar yüzebilir.', isTrue: true, explanation: 'Çoğu karınca türü yüzebilir ve sel sırasında küçük sallar oluşturur.', category: 'Doğa' },
  { statement: 'İnsan DNA\'sının %60\'ını muzla paylaşır.', isTrue: true, explanation: 'İnsanlar ve muzlar gerçekten yaklaşık %60 oranında aynı genleri paylaşır.', category: 'Bilim' },
  { statement: 'Venüs\'te sülfürik asit yağmuru yağar.', isTrue: true, explanation: 'Venüs\'ün bulutları sülfürik asit damlacıklarından oluşur, ancak yere ulaşmadan buharlaşırlar.', category: 'Bilim' },
  { statement: 'Oxford Üniversitesi hem Aztek İmparatorluğu\'ndan hem de Machu Picchu\'nun inşasından önce vardı.', isTrue: true, explanation: 'Oxford 1096\'da başladı, Aztek İmparatorluğu 1428\'de kuruldu, Machu Picchu 1450 civarında inşa edildi.', category: 'Tarih' },
  { statement: 'Bir bukalemun kamuflaj için renk değiştirir.', isTrue: false, explanation: 'Bukalemunlar ağırlıklı olarak iletişim ve sıcaklık düzenlemesi için renk değiştirir, kamuflaj için değil.', category: 'Doğa' },
  { statement: 'Taze biçilmiş çimen kokusu aslında bitkilerin bir acil durum sinyalidir.', isTrue: true, explanation: 'Bitkiler zarar gördüklerinde kimyasal maddeler salgılar — koku bir stres tepkisidir.', category: 'Doğa' },
  { statement: 'İsveç\'te tamamen buzdan yapılmış bir otel vardır.', isTrue: true, explanation: 'Jukkasjärvi\'deki Icehotel her kış buz ve kardan yeniden inşa edilir.', category: 'İlginç Bilgiler' },
  { statement: 'Örümcekler uçabilir.', isTrue: true, explanation: 'Bazı örümcekler "ballooning" kullanır — ipek iplikleri üzerinde rüzgârla taşınırlar.', category: 'Doğa' },
  { statement: 'Güneş ışığının Dünya\'ya ulaşması 8 saniye sürer.', isTrue: false, explanation: 'Yaklaşık 8 dakika 20 saniye sürer, 8 saniye değil.', category: 'Bilim' },
  { statement: 'Bir penguen bir evden daha yükseğe zıplayabilir.', isTrue: true, explanation: 'Bu bir şaka gerçektir — evler zıplayamaz, bu yüzden penguen kazanır.', category: 'İlginç Bilgiler' },
];
