export interface Fact {
  statement: string;
  isTrue: boolean;
  explanation: string;
  category: string;
}

export const FACTS_EN: Fact[] = [
  // Nature & Animals
  { statement: 'Octopuses have three hearts.', isTrue: true, explanation: 'Two branchial hearts pump blood to the gills, while a main heart pumps it through the body.', category: 'Nature' },
  { statement: 'Goldfish have a memory of only 3 seconds.', isTrue: false, explanation: 'Goldfish can remember things for months — the 3-second myth is completely false.', category: 'Nature' },
  { statement: 'Honey never goes bad.', isTrue: true, explanation: '3,000-year-old honey found in Egyptian tombs was still perfectly edible.', category: 'Nature' },
  { statement: 'Crocodiles cannot stick out their tongues.', isTrue: true, explanation: "A crocodile's tongue is attached to the roof of its mouth and cannot be extended.", category: 'Nature' },
  { statement: 'Elephants are the only animals that cannot jump.', isTrue: true, explanation: 'Due to their weight and bone structure, elephants truly cannot jump.', category: 'Nature' },
  { statement: 'Bananas grow on trees.', isTrue: false, explanation: 'Banana plants are not trees — they are giant herbaceous plants.', category: 'Nature' },
  { statement: 'Lightning can strike the same place twice.', isTrue: true, explanation: 'Tall buildings like the Empire State Building get struck up to 100 times per year.', category: 'Nature' },
  { statement: 'Dolphins sleep with one eye open.', isTrue: true, explanation: 'Dolphins sleep with one half of their brain at a time, keeping one eye open to watch for predators.', category: 'Nature' },
  { statement: "Koalas don't drink water.", isTrue: false, explanation: 'Koalas rarely drink water since they get moisture from eucalyptus leaves, but they do drink during heat waves.', category: 'Nature' },
  { statement: 'Butterflies taste with their feet.', isTrue: true, explanation: 'Butterflies have taste receptors on their feet to identify plants.', category: 'Nature' },

  // Science
  { statement: 'Sound travels faster than light.', isTrue: false, explanation: 'Light travels at about 300,000 km/s, while sound only travels at about 343 m/s.', category: 'Science' },
  { statement: 'The human body is about 60% water.', isTrue: true, explanation: 'Depending on age, the human body is 50-75% water.', category: 'Science' },
  { statement: 'Venus spins in the opposite direction of most planets.', isTrue: true, explanation: 'Venus has a retrograde rotation — the sun rises in the west there.', category: 'Science' },
  { statement: 'Glass is a liquid.', isTrue: false, explanation: 'Glass is an amorphous solid. The myth about old window glass flowing is false.', category: 'Science' },
  { statement: 'A day on Venus is longer than a year on Venus.', isTrue: true, explanation: 'One rotation takes 243 Earth days, while one orbit around the Sun takes only 225 Earth days.', category: 'Science' },
  { statement: 'Humans only use 10% of their brain.', isTrue: false, explanation: 'Brain scans show that we use virtually all areas of the brain, just not all at the same time.', category: 'Science' },
  { statement: 'Diamonds are made from coal.', isTrue: false, explanation: 'Diamonds form from carbon under extreme pressure, but not from coal — most are older than plant life on Earth.', category: 'Science' },
  { statement: 'There is absolute silence in space.', isTrue: true, explanation: 'Sound needs a medium to travel through. In the vacuum of space, there is none.', category: 'Science' },
  { statement: 'The human body has more bacteria than its own cells.', isTrue: true, explanation: 'Estimates suggest the body has about 38 trillion bacteria compared to 30 trillion of its own cells.', category: 'Science' },
  { statement: 'Water conducts electricity.', isTrue: false, explanation: 'Pure water does not conduct electricity. Only the dissolved minerals and salts make it conductive.', category: 'Science' },

  // History
  { statement: 'Cleopatra lived closer to the Moon landing than to the building of the pyramids.', isTrue: true, explanation: 'The pyramids were built around 2560 BC, Cleopatra lived 69-30 BC, and the Moon landing was in 1969.', category: 'History' },
  { statement: 'Napoleon was unusually short.', isTrue: false, explanation: 'Napoleon was about 5\'7" — average for his time. The myth originated from British propaganda.', category: 'History' },
  { statement: 'The Great Wall of China is visible from the Moon.', isTrue: false, explanation: 'Astronauts confirm the Wall is not visible from the Moon — it is too narrow.', category: 'History' },
  { statement: 'Oxford University is older than the Aztec Empire.', isTrue: true, explanation: 'Oxford was founded around 1096, while the Aztec Empire was established in 1428.', category: 'History' },
  { statement: 'Vikings wore helmets with horns.', isTrue: false, explanation: 'Archaeological finds show simple helmets without horns. The cliche comes from the 19th century.', category: 'History' },
  { statement: 'In ancient times, people believed the Earth was flat.', isTrue: false, explanation: 'The ancient Greeks already knew the Earth was round. Eratosthenes even calculated its circumference.', category: 'History' },
  { statement: 'The Eiffel Tower was supposed to be torn down after 20 years.', isTrue: true, explanation: 'It was built in 1889 as a temporary structure and only survived because it was useful as a radio tower.', category: 'History' },
  { statement: 'The Titanic was advertised as unsinkable.', isTrue: false, explanation: 'The White Star Line never officially called it unsinkable. That was a media exaggeration.', category: 'History' },
  { statement: 'Albert Einstein failed math in school.', isTrue: false, explanation: 'Einstein had top grades in mathematics. This myth is completely false.', category: 'History' },
  { statement: 'Spaghetti with tomato sauce is a traditional Italian dish.', isTrue: false, explanation: "Tomatoes didn't arrive in Europe from the Americas until the 16th century. Traditional pasta was seasoned differently.", category: 'History' },

  // Geography
  { statement: 'Russia has eleven time zones.', isTrue: true, explanation: 'From Kaliningrad to Kamchatka, Russia spans 11 time zones.', category: 'Geography' },
  { statement: 'The Amazon is the longest river in the world.', isTrue: false, explanation: 'The Nile at about 6,650 km is considered the longest river. The Amazon is the largest by volume.', category: 'Geography' },
  { statement: 'Iceland has no mosquitoes.', isTrue: true, explanation: 'Iceland is actually one of the few countries in the world with no native mosquito species.', category: 'Geography' },
  { statement: 'The Sahara is the largest desert in the world.', isTrue: false, explanation: 'Antarctica is the largest desert (14 million km\u00B2). The Sahara is the largest hot desert.', category: 'Geography' },
  { statement: 'In Australia, there are more kangaroos than people.', isTrue: true, explanation: 'There are about 50 million kangaroos compared to 26 million people in Australia.', category: 'Geography' },
  { statement: 'Mount Everest is the tallest mountain measured from the center of the Earth.', isTrue: false, explanation: "Chimborazo in Ecuador is farthest from Earth's center because the Earth bulges at the equator.", category: 'Geography' },

  // Weird Facts
  { statement: 'In Switzerland, it is illegal to keep just one guinea pig.', isTrue: true, explanation: 'Guinea pigs are social animals. Swiss animal protection laws prohibit keeping them alone.', category: 'Weird Facts' },
  { statement: 'There are more stars in the universe than grains of sand on Earth.', isTrue: true, explanation: 'Estimates: about 10^24 stars in the observable universe, about 7.5x10^18 grains of sand.', category: 'Weird Facts' },
  { statement: 'A snail can sleep for up to 3 years.', isTrue: true, explanation: 'Some snail species can enter a prolonged dormant state, especially during dry periods.', category: 'Weird Facts' },
  { statement: 'The inventor of the Pringles can is buried in one.', isTrue: true, explanation: 'Fredric Baur, the inventor of the Pringles can, was buried in one at his own request in 2008.', category: 'Weird Facts' },
  { statement: 'Cows can walk up stairs but not down them.', isTrue: true, explanation: 'Due to their knee structure and field of vision, cows cannot safely walk down stairs.', category: 'Weird Facts' },
  { statement: 'The average person swallows 8 spiders per year in their sleep.', isTrue: false, explanation: 'This myth was deliberately invented in 1993 as an example of how fake facts spread online.', category: 'Weird Facts' },
  { statement: "According to physics, bumblebees shouldn't be able to fly.", isTrue: false, explanation: 'This rumor is based on flawed calculations. The aerodynamics of bumblebee flight have long been explained.', category: 'Weird Facts' },
  { statement: 'In Japan, there is an island full of cats that outnumber the humans.', isTrue: true, explanation: 'Aoshima, also known as Cat Island, has roughly a 6:1 cat-to-human ratio.', category: 'Weird Facts' },
  { statement: 'The shortest war in history lasted 38 minutes.', isTrue: true, explanation: 'The Anglo-Zanzibar War of 1896 lasted between 38 and 45 minutes.', category: 'Weird Facts' },
  { statement: 'Flamingos are born pink.', isTrue: false, explanation: 'Flamingos are born grey-white and turn pink from their diet of crustaceans and algae.', category: 'Weird Facts' },

  // Technology
  { statement: "The first iPhone didn't have an App Store.", isTrue: true, explanation: 'The first iPhone launched in 2007, but the App Store was not introduced until 2008.', category: 'Technology' },
  { statement: 'The first SMS ever sent said "Merry Christmas".', isTrue: true, explanation: 'On December 3, 1992, Neil Papworth sent the first SMS with the text "Merry Christmas".', category: 'Technology' },
  { statement: 'WiFi stands for Wireless Fidelity.', isTrue: false, explanation: "WiFi is a brand name and doesn't stand for anything. It was coined by a marketing firm.", category: 'Technology' },
  { statement: 'The first computer was as big as a room.', isTrue: true, explanation: 'ENIAC (1945) weighed 27 tons and occupied 167 square meters.', category: 'Technology' },
  { statement: "Emails don't use any electricity.", isTrue: false, explanation: 'Each email produces about 4g of CO2, since servers and networks require energy.', category: 'Technology' },

  // New facts (50)
  { statement: 'Wombats produce cube-shaped poop.', isTrue: true, explanation: 'Wombats have a special intestine that forms cube-shaped droppings so they don\'t roll away.', category: 'Nature' },
  { statement: 'The Eiffel Tower is shorter in winter than in summer.', isTrue: true, explanation: 'The cold causes the metal to contract, making the tower shrink by up to 15 cm.', category: 'Weird Facts' },
  { statement: 'Cows have four stomachs.', isTrue: true, explanation: 'Cows actually have four stomach compartments: the rumen, reticulum, omasum, and abomasum.', category: 'Nature' },
  { statement: 'An ostrich can run faster than a horse.', isTrue: true, explanation: 'Ostriches can reach speeds of up to 70 km/h, while horses max out at about 65 km/h.', category: 'Nature' },
  { statement: 'The Earth spins faster now than it did a million years ago.', isTrue: false, explanation: "The Earth is actually slowing down. Tidal forces from the Moon are making the days longer.", category: 'Science' },
  { statement: 'Venice has more bridges than Amsterdam.', isTrue: false, explanation: 'Amsterdam has over 1,500 bridges, while Venice has only about 400.', category: 'Geography' },
  { statement: 'The Amazon flows into the sea without a single bridge crossing it.', isTrue: true, explanation: 'There is no bridge spanning the entire Amazon — it flows through dense rainforest.', category: 'Geography' },
  { statement: 'Bees can recognize human faces.', isTrue: true, explanation: 'Studies show that honeybees can distinguish and remember human faces.', category: 'Nature' },
  { statement: 'Mars has the tallest mountain in the solar system.', isTrue: true, explanation: 'Olympus Mons on Mars, at about 22 km high, is the tallest known mountain in the solar system.', category: 'Science' },
  { statement: 'Chocolate is poisonous to dogs.', isTrue: true, explanation: "Theobromine in chocolate can be lethal to dogs because they can't metabolize it.", category: 'Nature' },
  { statement: "In Australia, trees don't shed their leaves — they shed their bark.", isTrue: true, explanation: 'Many eucalyptus species shed their bark instead of their leaves.', category: 'Nature' },
  { statement: "A shrimp's heart is located in its head.", isTrue: true, explanation: "A shrimp's heart is indeed located in its head.", category: 'Nature' },
  { statement: 'The Vatican has the highest crime rate per capita in the world.', isTrue: true, explanation: 'Since the Vatican has only about 800 residents, even a few crimes result in a high per-capita rate.', category: 'Weird Facts' },
  { statement: 'A person can survive in space by holding their breath.', isTrue: false, explanation: 'In a vacuum, air would be violently pulled from your lungs. You would lose consciousness in about 15 seconds.', category: 'Science' },
  { statement: 'Paper can only be folded a maximum of 7 times.', isTrue: false, explanation: 'Although difficult, paper has been folded 12 times (with a large enough sheet).', category: 'Weird Facts' },
  { statement: 'The Great Wall of China is over 21,000 km long.', isTrue: true, explanation: 'Including all branches and secondary walls, it measures a total of 21,196 km.', category: 'History' },
  { statement: 'Finland has more saunas than cars.', isTrue: true, explanation: 'Finland has about 3.3 million saunas for 5.5 million people — more than the number of cars.', category: 'Weird Facts' },
  { statement: "A blue whale's heart is the size of a small car.", isTrue: true, explanation: "A blue whale's heart can weigh up to 600 kg and is roughly the size of a VW Beetle.", category: 'Nature' },
  { statement: 'The Sun is yellow.', isTrue: false, explanation: "The Sun is actually white. It appears yellow to us because of Earth's atmosphere.", category: 'Science' },
  { statement: 'Fish can drown.', isTrue: true, explanation: 'If there is too little oxygen in the water, fish can indeed suffocate.', category: 'Nature' },
  { statement: 'Mount Everest grows about 4 millimeters every year.', isTrue: true, explanation: 'Due to tectonic plate movement, the Himalayas are still growing.', category: 'Science' },
  { statement: 'Ketchup was sold as medicine in the 19th century.', isTrue: true, explanation: 'In the 1830s, tomato ketchup was marketed as a remedy for diarrhea.', category: 'History' },
  { statement: 'The shortest flight in the world lasts 57 seconds.', isTrue: true, explanation: 'The flight between Westray and Papa Westray in Scotland takes just under a minute.', category: 'Weird Facts' },
  { statement: 'Octopuses have three brains.', isTrue: false, explanation: 'Octopuses actually have nine brains — one central brain and an additional one in each of their eight arms.', category: 'Nature' },
  { statement: 'Brazil is named after a tree.', isTrue: true, explanation: 'Brazil is named after the Brazilwood tree (Pau-Brasil), which was abundant there.', category: 'History' },
  { statement: 'A hummingbird can fly backwards.', isTrue: true, explanation: 'Hummingbirds are the only birds that can truly fly backwards.', category: 'Nature' },
  { statement: 'Your nose keeps growing your entire life.', isTrue: true, explanation: 'The nose and ears never stop growing because they are made of cartilage.', category: 'Science' },
  { statement: 'In Japan, it is common to eat in the bathtub.', isTrue: false, explanation: 'In Japan, the bath is considered a place of cleanliness. Eating in it would be unusual.', category: 'Weird Facts' },
  { statement: 'The human stomach produces about 2 liters of hydrochloric acid per day.', isTrue: true, explanation: 'Stomach acid is strong enough to dissolve metal, but the stomach lining protects it.', category: 'Science' },
  { statement: 'There are more trees on Earth than stars in the Milky Way.', isTrue: true, explanation: 'There are about 3 trillion trees on Earth, but only 100-400 billion stars in the Milky Way.', category: 'Nature' },
  { statement: 'The color orange was named after the fruit, not the other way around.', isTrue: true, explanation: 'Before the orange fruit, the color was called "geoluhread" (yellow-red) in English. The fruit gave the color its name.', category: 'Weird Facts' },
  { statement: 'Bananas are radioactive.', isTrue: true, explanation: 'Bananas contain potassium-40, a radioactive isotope. However, the radiation is completely harmless.', category: 'Science' },
  { statement: 'A day on Pluto is longer than a week on Earth.', isTrue: true, explanation: 'A Pluto day lasts 6.4 Earth days — nearly an entire Earth week.', category: 'Science' },
  { statement: "In Switzerland, you're not allowed to flush the toilet after 10 PM.", isTrue: false, explanation: 'This is a widespread myth. There is no such law in Switzerland.', category: 'Weird Facts' },
  { statement: 'Laughter is contagious because the brain activates mirror neurons.', isTrue: true, explanation: "Mirror neurons in the brain respond to other people's laughter and trigger similar reactions.", category: 'Science' },
  { statement: 'Russia has a larger surface area than Pluto.', isTrue: true, explanation: "Russia covers 17.1 million km\u00B2, while Pluto's surface area is only 16.7 million km\u00B2.", category: 'Geography' },
  { statement: 'A teaspoon of neutron star material weighs 6 billion tons.', isTrue: true, explanation: 'Neutron stars are so dense that a teaspoon of their material weighs billions of tons.', category: 'Science' },
  { statement: 'Cats have more bones than humans.', isTrue: true, explanation: 'Cats have about 230 bones, while humans have only 206.', category: 'Nature' },
  { statement: 'The Atlantic Ocean is getting wider every year.', isTrue: true, explanation: 'Due to plate tectonics, the Atlantic grows about 2.5 cm wider each year.', category: 'Science' },
  { statement: 'There is a town in Norway called "Hell".', isTrue: true, explanation: 'Hell is a village in the municipality of Verdal in Norway. In winter, Hell regularly freezes over.', category: 'Geography' },
  { statement: 'Ants can swim.', isTrue: true, explanation: 'Most ant species can swim and even form tiny rafts during floods.', category: 'Nature' },
  { statement: 'Humans share 60% of their DNA with bananas.', isTrue: true, explanation: 'Humans and bananas actually share about 60% of identical genes.', category: 'Science' },
  { statement: 'It rains sulfuric acid on Venus.', isTrue: true, explanation: "Venus's clouds are made of sulfuric acid droplets, though they evaporate before reaching the ground.", category: 'Science' },
  { statement: 'Oxford University existed before the Aztec Empire and before Machu Picchu was built.', isTrue: true, explanation: 'Oxford began around 1096, the Aztec Empire was founded in 1428, and Machu Picchu was built around 1450.', category: 'History' },
  { statement: 'A chameleon changes its color for camouflage.', isTrue: false, explanation: 'Chameleons change color mainly for communication and temperature regulation, not for camouflage.', category: 'Nature' },
  { statement: 'The smell of freshly cut grass is actually a distress signal from the plants.', isTrue: true, explanation: 'Plants release chemical compounds when injured — the smell is a stress response.', category: 'Nature' },
  { statement: 'In Sweden, there is a hotel made entirely of ice.', isTrue: true, explanation: 'The Icehotel in Jukkasjarvi is rebuilt every winter from ice and snow.', category: 'Weird Facts' },
  { statement: 'Spiders can fly.', isTrue: true, explanation: 'Some spiders use "ballooning" — they release silk threads and let the wind carry them.', category: 'Nature' },
  { statement: 'Sunlight takes 8 seconds to reach the Earth.', isTrue: false, explanation: 'It takes about 8 minutes and 20 seconds, not 8 seconds.', category: 'Science' },
  { statement: 'A penguin can jump higher than a house.', isTrue: true, explanation: "This is a trick fact — houses can't jump, so the penguin wins by default.", category: 'Weird Facts' },
];
