import type { Fact } from './fakeorfact-content-de';

export const FACTS_NL: Fact[] = [
  // Natuur & Dieren
  { statement: 'Octopussen hebben drie harten.', isTrue: true, explanation: 'Twee kieuwenharten pompen bloed naar de kieuwen, één hoofdhart pompt het door het lichaam.', category: 'Natuur' },
  { statement: 'Goudvissen hebben een geheugen van slechts 3 seconden.', isTrue: false, explanation: 'Goudvissen kunnen zich maandenlang dingen herinneren — de 3-seconden-mythe klopt niet.', category: 'Natuur' },
  { statement: 'Honing kan nooit bederven.', isTrue: true, explanation: 'In Egyptische graven is 3000 jaar oude honing gevonden die nog eetbaar was.', category: 'Natuur' },
  { statement: 'Krokodillen kunnen niet met hun tong likken.', isTrue: true, explanation: 'De tong van een krokodil zit vast aan het gehemelte en kan niet uitgestoken worden.', category: 'Natuur' },
  { statement: 'Olifanten zijn de enige dieren die niet kunnen springen.', isTrue: true, explanation: 'Door hun gewicht en botstructuur kunnen olifanten daadwerkelijk niet springen.', category: 'Natuur' },
  { statement: 'Bananen groeien aan bomen.', isTrue: false, explanation: 'Bananenplanten zijn geen bomen, maar reusachtige kruidachtige planten.', category: 'Natuur' },
  { statement: 'Bliksem kan dezelfde plek twee keer raken.', isTrue: true, explanation: 'Hoge gebouwen zoals het Empire State Building worden elk jaar tot 100 keer getroffen.', category: 'Natuur' },
  { statement: 'Dolfijnen slapen met één oog open.', isTrue: true, explanation: 'Dolfijnen slapen met één hersenhelft en houden één oog open voor roofdieren.', category: 'Natuur' },
  { statement: 'Koala\'s drinken geen water.', isTrue: false, explanation: 'Koala\'s drinken zelden water omdat ze vocht uit eucalyptusbladeren halen, maar bij hitte drinken ze wel degelijk.', category: 'Natuur' },
  { statement: 'Vlinders proeven met hun poten.', isTrue: true, explanation: 'Vlinders hebben smaakreceporen aan hun poten om planten te identificeren.', category: 'Natuur' },

  // Wetenschap
  { statement: 'Geluid reist sneller dan licht.', isTrue: false, explanation: 'Licht reist met ongeveer 300.000 km/s, geluid slechts met ongeveer 343 m/s.', category: 'Wetenschap' },
  { statement: 'Het menselijk lichaam bestaat voor ongeveer 60% uit water.', isTrue: true, explanation: 'Het menselijk lichaam bestaat, afhankelijk van leeftijd, voor 50-75% uit water.', category: 'Wetenschap' },
  { statement: 'Venus draait in de tegenovergestelde richting van de meeste planeten.', isTrue: true, explanation: 'Venus heeft een retrograde rotatie — de zon komt daar in het westen op.', category: 'Wetenschap' },
  { statement: 'Glas is een vloeistof.', isTrue: false, explanation: 'Glas is een amorf vast materiaal. De mythe van vloeiend glas in oude ramen klopt niet.', category: 'Wetenschap' },
  { statement: 'Een dag op Venus is langer dan een jaar op Venus.', isTrue: true, explanation: 'Eén rotatie duurt 243 aardse dagen, één omwenteling om de zon slechts 225 aardse dagen.', category: 'Wetenschap' },
  { statement: 'Mensen gebruiken slechts 10% van hun hersenen.', isTrue: false, explanation: 'Hersenscans tonen aan dat we vrijwel alle delen van de hersenen gebruiken, alleen niet allemaal tegelijk.', category: 'Wetenschap' },
  { statement: 'Diamanten ontstaan uit steenkool.', isTrue: false, explanation: 'Diamanten ontstaan uit koolstof onder extreme druk, maar niet uit steenkool — de meeste zijn ouder dan planten op aarde.', category: 'Wetenschap' },
  { statement: 'In de ruimte heerst absolute stilte.', isTrue: true, explanation: 'Geluid heeft een medium nodig om zich voort te planten. In het vacuüm van de ruimte is dat er niet.', category: 'Wetenschap' },
  { statement: 'Het menselijk lichaam heeft meer bacteriën dan eigen cellen.', isTrue: true, explanation: 'Schattingen geven aan dat het lichaam ongeveer 38 biljoen bacteriën heeft bij 30 biljoen eigen cellen.', category: 'Wetenschap' },
  { statement: 'Water geleidt elektriciteit.', isTrue: false, explanation: 'Zuiver water geleidt geen elektriciteit. Pas de opgeloste mineralen en zouten maken het geleidend.', category: 'Wetenschap' },

  // Geschiedenis
  { statement: 'Cleopatra leefde dichter bij de maanlanding dan bij de bouw van de piramides.', isTrue: true, explanation: 'De piramides werden rond 2560 v.Chr. gebouwd, Cleopatra leefde van 69-30 v.Chr., de maanlanding was in 1969.', category: 'Geschiedenis' },
  { statement: 'Napoleon was ongewoon klein.', isTrue: false, explanation: 'Napoleon was ca. 1,70m lang — gemiddeld voor zijn tijd. De mythe ontstond door Britse propaganda.', category: 'Geschiedenis' },
  { statement: 'De Chinese Muur is zichtbaar vanaf de maan.', isTrue: false, explanation: 'Astronauten bevestigen dat de muur niet zichtbaar is vanaf de maan — hij is te smal.', category: 'Geschiedenis' },
  { statement: 'De Universiteit van Oxford is ouder dan het Aztekenrijk.', isTrue: true, explanation: 'Oxford werd vanaf 1096 gesticht, het Aztekenrijk pas in 1428.', category: 'Geschiedenis' },
  { statement: 'Vikingen droegen helmen met hoorns.', isTrue: false, explanation: 'Archeologische vondsten tonen eenvoudige helmen zonder hoorns. Het cliché stamt uit de 19e eeuw.', category: 'Geschiedenis' },
  { statement: 'In de oudheid dachten mensen dat de aarde plat was.', isTrue: false, explanation: 'Al de oude Grieken wisten dat de aarde rond is. Eratosthenes berekende zelfs haar omtrek.', category: 'Geschiedenis' },
  { statement: 'De Eiffeltoren zou na 20 jaar afgebroken worden.', isTrue: true, explanation: 'Hij werd in 1889 als tijdelijk bouwwerk opgericht en overleefde alleen omdat hij als zendmast nuttig was.', category: 'Geschiedenis' },
  { statement: 'De Titanic werd als onzinkbaar aangeprezen.', isTrue: false, explanation: 'De White Star Line noemde haar nooit officieel onzinkbaar. Dat was een overdrijving van de pers.', category: 'Geschiedenis' },
  { statement: 'Albert Einstein was gezakt voor wiskunde.', isTrue: false, explanation: 'Einstein had topscores voor wiskunde. Deze mythe is volledig onjuist.', category: 'Geschiedenis' },
  { statement: 'Spaghetti met tomatensaus is een traditioneel Italiaans gerecht.', isTrue: false, explanation: 'Tomaten kwamen pas in de 16e eeuw vanuit Amerika naar Europa. Traditionele pasta werd anders gekruid.', category: 'Geschiedenis' },

  // Geografie
  { statement: 'Rusland heeft elf tijdzones.', isTrue: true, explanation: 'Van Kaliningrad tot Kamtsjatka strekt Rusland zich uit over 11 tijdzones.', category: 'Geografie' },
  { statement: 'De Amazone is de langste rivier ter wereld.', isTrue: false, explanation: 'De Nijl met ca. 6.650 km geldt als langste rivier, de Amazone is de waterrijkste.', category: 'Geografie' },
  { statement: 'IJsland heeft geen muggen.', isTrue: true, explanation: 'IJsland is daadwerkelijk een van de weinige landen ter wereld zonder inheemse muggensoorten.', category: 'Geografie' },
  { statement: 'De Sahara is de grootste woestijn ter wereld.', isTrue: false, explanation: 'Antarctica is de grootste woestijn (14 mln. km²). De Sahara is de grootste hete woestijn.', category: 'Geografie' },
  { statement: 'In Australië zijn er meer kangoeroes dan mensen.', isTrue: true, explanation: 'Er zijn ca. 50 miljoen kangoeroes bij 26 miljoen mensen in Australië.', category: 'Geografie' },
  { statement: 'De Mount Everest is de hoogste berg gemeten vanuit het middelpunt van de aarde.', isTrue: false, explanation: 'De Chimborazo in Ecuador is het verst verwijderd van het middelpunt van de aarde, omdat de aarde bij de evenaar dikker is.', category: 'Geografie' },

  // Bijzonderheden
  { statement: 'In Zwitserland is het illegaal om slechts één cavia te houden.', isTrue: true, explanation: 'Cavia\'s zijn sociale dieren. Zwitserse dierenbeschermingswetten verbieden het alleen houden.', category: 'Bijzonderheden' },
  { statement: 'Er zijn meer sterren in het universum dan zandkorrels op aarde.', isTrue: true, explanation: 'Schattingen: ca. 10^24 sterren in het waarneembare universum, ca. 7,5×10^18 zandkorrels.', category: 'Bijzonderheden' },
  { statement: 'Een slak kan tot 3 jaar slapen.', isTrue: true, explanation: 'Sommige slakkensoorten kunnen in een langdurige ruststand vallen, vooral bij droogte.', category: 'Bijzonderheden' },
  { statement: 'De uitvinder van de Pringles-bus is erin begraven.', isTrue: true, explanation: 'Fredric Baur, de uitvinder van de Pringles-bus, werd in 2008 op eigen verzoek erin begraven.', category: 'Bijzonderheden' },
  { statement: 'Koeien kunnen trappen oplopen, maar niet afdalen.', isTrue: true, explanation: 'Door hun kniestructuur en gezichtsveld kunnen koeien niet veilig trappen afdalen.', category: 'Bijzonderheden' },
  { statement: 'Ieder mens slikt gemiddeld 8 spinnen per jaar in tijdens de slaap.', isTrue: false, explanation: 'Deze mythe werd in 1993 opzettelijk verzonnen als voorbeeld van nepfeiten.', category: 'Bijzonderheden' },
  { statement: 'Hommels kunnen volgens de natuurkunde eigenlijk niet vliegen.', isTrue: false, explanation: 'Dit gerucht is gebaseerd op foutieve berekeningen. De aerodynamica van hommelvlucht is allang verklaard.', category: 'Bijzonderheden' },
  { statement: 'In Japan is er een eiland vol katten, waar ze de mensen in aantal overtreffen.', isTrue: true, explanation: 'Aoshima, ook wel katteneiland genoemd, heeft een verhouding van ongeveer 6:1 katten ten opzichte van mensen.', category: 'Bijzonderheden' },
  { statement: 'De kortste oorlog in de geschiedenis duurde 38 minuten.', isTrue: true, explanation: 'De Anglo-Zanzibar oorlog van 1896 duurde tussen de 38 en 45 minuten.', category: 'Bijzonderheden' },
  { statement: 'Flamingo\'s zijn van geboorte roze.', isTrue: false, explanation: 'Flamingo\'s worden grijs-wit geboren en kleuren roze door hun voeding (schaaldieren, algen).', category: 'Bijzonderheden' },

  // Techniek
  { statement: 'De eerste iPhone had geen App Store.', isTrue: true, explanation: 'De eerste iPhone kwam in 2007 uit, de App Store werd pas in 2008 gelanceerd.', category: 'Techniek' },
  { statement: 'Het eerste sms-bericht ter wereld luidde "Merry Christmas".', isTrue: true, explanation: 'Op 3 december 1992 verstuurde Neil Papworth het eerste sms-bericht met de tekst "Merry Christmas".', category: 'Techniek' },
  { statement: 'WiFi staat voor Wireless Fidelity.', isTrue: false, explanation: 'WiFi is een merknaam en staat nergens voor. Het werd bedacht door een marketingbureau.', category: 'Techniek' },
  { statement: 'De eerste computer was zo groot als een kamer.', isTrue: true, explanation: 'ENIAC (1945) woog 27 ton en besloeg 167 vierkante meter.', category: 'Techniek' },
  { statement: 'E-mails verbruiken geen stroom.', isTrue: false, explanation: 'Elke e-mail verbruikt ca. 4g CO2, omdat servers en netwerken energie nodig hebben.', category: 'Techniek' },

  // Nieuwe feiten (50)
  { statement: 'Wombats produceren kubusvormige uitwerpselen.', isTrue: true, explanation: 'Wombats hebben een speciaal darmstelsel dat kubusvormige uitwerpselen vormt, zodat ze niet wegrollen.', category: 'Natuur' },
  { statement: 'De Eiffeltoren is in de winter kleiner dan in de zomer.', isTrue: true, explanation: 'Door de kou krimpt het metaal samen, waardoor de toren tot 15 cm krimpt.', category: 'Bijzonderheden' },
  { statement: 'Koeien hebben vier magen.', isTrue: true, explanation: 'Koeien hebben inderdaad vier maagafdelingen: pens, netmaag, boekmaag en lebmaag.', category: 'Natuur' },
  { statement: 'Een struisvogel kan sneller rennen dan een paard.', isTrue: true, explanation: 'Struisvogels kunnen tot 70 km/u halen, terwijl paarden maximaal 65 km/u bereiken.', category: 'Natuur' },
  { statement: 'De aarde draait sneller dan een miljoen jaar geleden.', isTrue: false, explanation: 'De aarde draait langzamer. Door de getijdenkrachten van de maan worden de dagen langer.', category: 'Wetenschap' },
  { statement: 'Venetië heeft meer bruggen dan Amsterdam.', isTrue: false, explanation: 'Amsterdam heeft meer dan 1.500 bruggen, Venetië slechts ongeveer 400.', category: 'Geografie' },
  { statement: 'De Amazone mondt uit in zee zonder ook maar één brug.', isTrue: true, explanation: 'Er is geen enkele brug over de gehele Amazone — hij stroomt door te dicht regenwoud.', category: 'Geografie' },
  { statement: 'Bijen kunnen gezichten herkennen.', isTrue: true, explanation: 'Studies tonen aan dat honingbijen menselijke gezichten kunnen onderscheiden en herkennen.', category: 'Natuur' },
  { statement: 'Mars heeft de hoogste berg in het zonnestelsel.', isTrue: true, explanation: 'Olympus Mons op Mars is met ongeveer 22 km de hoogste bekende berg in het zonnestelsel.', category: 'Wetenschap' },
  { statement: 'Chocolade is giftig voor honden.', isTrue: true, explanation: 'Theobromine in chocolade kan dodelijk zijn voor honden, omdat ze het niet kunnen afbreken.', category: 'Natuur' },
  { statement: 'In Australië verliezen bomen niet hun bladeren, maar hun bast.', isTrue: true, explanation: 'Veel eucalyptussoorten werpen hun bast af in plaats van hun bladeren.', category: 'Natuur' },
  { statement: 'Het hart van een garnaal zit in zijn hoofd.', isTrue: true, explanation: 'Het hart van een garnaal bevindt zich daadwerkelijk in zijn hoofd.', category: 'Natuur' },
  { statement: 'Het Vaticaan heeft het hoogste misdaadcijfer ter wereld per hoofd van de bevolking.', isTrue: true, explanation: 'Aangezien het Vaticaan slechts ongeveer 800 inwoners heeft, leiden weinig misdrijven tot een hoog per-capita-cijfer.', category: 'Bijzonderheden' },
  { statement: 'Een mens kan in de ruimte overleven als hij zijn adem inhoudt.', isTrue: false, explanation: 'In een vacuüm zou de lucht met geweld uit de longen worden gezogen. Je zou binnen ca. 15 seconden bewusteloos raken.', category: 'Wetenschap' },
  { statement: 'Papier kan maximaal 7 keer gevouwen worden.', isTrue: false, explanation: 'Hoewel het moeilijk is, is papier al 12 keer gevouwen (met een groot genoeg vel).', category: 'Bijzonderheden' },
  { statement: 'De Chinese Muur is meer dan 21.000 km lang.', isTrue: true, explanation: 'Met alle zijmuren en vertakkingen meet hij in totaal 21.196 km.', category: 'Geschiedenis' },
  { statement: 'Finland heeft meer sauna\'s dan auto\'s.', isTrue: true, explanation: 'Finland heeft ca. 3,3 miljoen sauna\'s bij 5,5 miljoen inwoners — dat is meer dan auto\'s.', category: 'Bijzonderheden' },
  { statement: 'Een blauwwalhart is zo groot als een kleine auto.', isTrue: true, explanation: 'Het hart van een blauwe vinvis kan tot 600 kg wegen en is zo groot als een VW Kever.', category: 'Natuur' },
  { statement: 'De zon is geel.', isTrue: false, explanation: 'De zon is eigenlijk wit. Ze lijkt ons geel door de atmosfeer van de aarde.', category: 'Wetenschap' },
  { statement: 'Vissen kunnen verdrinken.', isTrue: true, explanation: 'Als er te weinig zuurstof in het water is, kunnen vissen daadwerkelijk stikken.', category: 'Natuur' },
  { statement: 'De Mount Everest groeit elk jaar ongeveer 4 millimeter.', isTrue: true, explanation: 'Door tektonische plaatbewegingen groeit de Himalaya nog steeds.', category: 'Wetenschap' },
  { statement: 'Ketchup werd in de 19e eeuw als medicijn verkocht.', isTrue: true, explanation: 'In de jaren 1830 werd tomatenketchup verkocht als middel tegen diarree.', category: 'Geschiedenis' },
  { statement: 'De kortste vlucht ter wereld duurt 57 seconden.', isTrue: true, explanation: 'De vlucht tussen Westray en Papa Westray in Schotland duurt slechts een minuut.', category: 'Bijzonderheden' },
  { statement: 'Octopussen hebben drie hersenen.', isTrue: false, explanation: 'Octopussen hebben negen hersenen — één centraal brein en een extra in elk van de acht armen.', category: 'Natuur' },
  { statement: 'Brazilië is vernoemd naar een boom.', isTrue: true, explanation: 'Brazilië is vernoemd naar het brazilhout (Pau-Brasil), dat daar veelvuldig voorkwam.', category: 'Geschiedenis' },
  { statement: 'Een kolibrie kan achteruit vliegen.', isTrue: true, explanation: 'Kolibries zijn de enige vogels die daadwerkelijk achteruit kunnen vliegen.', category: 'Natuur' },
  { statement: 'De neus groeit je hele leven lang.', isTrue: true, explanation: 'Neus en oren houden nooit op met groeien, omdat ze uit kraakbeen bestaan.', category: 'Wetenschap' },
  { statement: 'In Japan is het gebruikelijk om in bad te eten.', isTrue: false, explanation: 'In Japan wordt het bad beschouwd als een plek van reiniging. Eten erin zou ongebruikelijk zijn.', category: 'Bijzonderheden' },
  { statement: 'De menselijke maag produceert dagelijks ongeveer 2 liter zoutzuur.', isTrue: true, explanation: 'Het maagzuur is sterk genoeg om metaal op te lossen, maar wordt beschermd door slijmvlies.', category: 'Wetenschap' },
  { statement: 'Er zijn meer bomen op aarde dan sterren in de Melkweg.', isTrue: true, explanation: 'Er zijn ongeveer 3 biljoen bomen op aarde, maar slechts 100-400 miljard sterren in de Melkweg.', category: 'Natuur' },
  { statement: 'De kleur oranje is vernoemd naar de vrucht, niet andersom.', isTrue: true, explanation: 'Vóór de sinaasappel heette de kleur in het Engels "geoluhread" (geelrood). De vrucht gaf de kleur haar naam.', category: 'Bijzonderheden' },
  { statement: 'Bananen zijn radioactief.', isTrue: true, explanation: 'Bananen bevatten kalium-40, een radioactief isotoop. De straling is echter volkomen onschadelijk.', category: 'Wetenschap' },
  { statement: 'Een dag op Pluto duurt langer dan een week op aarde.', isTrue: true, explanation: 'Een Pluto-dag duurt 6,4 aardse dagen — bijna een hele aardse week.', category: 'Wetenschap' },
  { statement: 'In Zwitserland mag je na 22 uur niet meer doorspoelen.', isTrue: false, explanation: 'Dit is een wijdverbreide mythe. Er bestaat geen dergelijke wet in Zwitserland.', category: 'Bijzonderheden' },
  { statement: 'Lachen is besmettelijk doordat de hersenen spiegelneuronen activeren.', isTrue: true, explanation: 'Spiegelneuronen in de hersenen reageren op het lachen van anderen en veroorzaken soortgelijke reacties.', category: 'Wetenschap' },
  { statement: 'Rusland heeft een groter oppervlak dan Pluto.', isTrue: true, explanation: 'Rusland heeft 17,1 mln. km², het oppervlak van Pluto bedraagt slechts 16,7 mln. km².', category: 'Geografie' },
  { statement: 'Een theelepel neutronenstermateriaal weegt 6 miljard ton.', isTrue: true, explanation: 'Neutronensterren zijn zo dicht dat een theelepel van hun materiaal miljarden tonnen weegt.', category: 'Wetenschap' },
  { statement: 'Katten hebben meer botten dan mensen.', isTrue: true, explanation: 'Katten hebben ca. 230 botten, mensen slechts 206.', category: 'Natuur' },
  { statement: 'De Atlantische Oceaan wordt elk jaar breder.', isTrue: true, explanation: 'Door platentektoniek wordt de Atlantische Oceaan elk jaar ongeveer 2,5 cm breder.', category: 'Wetenschap' },
  { statement: 'In Noorwegen is er een plaats genaamd "Hell".', isTrue: true, explanation: 'Hell is een plaats in de gemeente Verdal in Noorwegen. In de winter vriest Hell regelmatig dicht.', category: 'Geografie' },
  { statement: 'Mieren kunnen zwemmen.', isTrue: true, explanation: 'De meeste mierensoorten kunnen zwemmen en vormen kleine vlotten bij overstromingen.', category: 'Natuur' },
  { statement: 'De mens deelt 60% van zijn DNA met een banaan.', isTrue: true, explanation: 'Mensen en bananen delen daadwerkelijk ongeveer 60% identieke genen.', category: 'Wetenschap' },
  { statement: 'Op Venus regent het zwavelzuur.', isTrue: true, explanation: 'De wolken van Venus bestaan uit zwavelzuurdruppels, die echter vóór de grond verdampen.', category: 'Wetenschap' },
  { statement: 'De Universiteit van Oxford bestond al vóór het Aztekenrijk en de bouw van Machu Picchu.', isTrue: true, explanation: 'Oxford begon vanaf 1096, het Aztekenrijk werd in 1428 gesticht, Machu Picchu rond 1450 gebouwd.', category: 'Geschiedenis' },
  { statement: 'Een kameleon verandert van kleur voor camouflage.', isTrue: false, explanation: 'Kameleons veranderen voornamelijk van kleur voor communicatie en temperatuurregulatie, niet voor camouflage.', category: 'Natuur' },
  { statement: 'De geur van vers gemaaid gras is eigenlijk een noodkreet van planten.', isTrue: true, explanation: 'Planten geven chemische stoffen af wanneer ze beschadigd worden — de geur is een stressreactie.', category: 'Natuur' },
  { statement: 'In Zweden is er een hotel volledig gemaakt van ijs.', isTrue: true, explanation: 'Het Icehotel in Jukkasjärvi wordt elke winter opnieuw opgebouwd uit ijs en sneeuw.', category: 'Bijzonderheden' },
  { statement: 'Spinnen kunnen vliegen.', isTrue: true, explanation: 'Sommige spinnen gebruiken "ballooning" — ze laten zich op zijdedraden door de wind meevoeren.', category: 'Natuur' },
  { statement: 'Het licht van de zon heeft 8 seconden nodig om de aarde te bereiken.', isTrue: false, explanation: 'Het duurt ongeveer 8 minuten en 20 seconden, niet 8 seconden.', category: 'Wetenschap' },
  { statement: 'Een pinguïn kan hoger springen dan een huis.', isTrue: true, explanation: 'Dit is een grapfeit — huizen kunnen helemaal niet springen, dus wint de pinguïn.', category: 'Bijzonderheden' },
];
