export interface WhoAmICharacter {
  name: string;
  category: string;
}

export const WHOAMI_CHARACTERS: WhoAmICharacter[] = [
  // Celebrities (45)
  { name: 'Albert Einstein', category: 'Celebridades' },
  { name: 'Beyonce', category: 'Celebridades' },
  { name: 'Elon Musk', category: 'Celebridades' },
  { name: 'Taylor Swift', category: 'Celebridades' },
  { name: 'Cristiano Ronaldo', category: 'Celebridades' },
  { name: 'Oprah Winfrey', category: 'Celebridades' },
  { name: 'Leonardo DiCaprio', category: 'Celebridades' },
  { name: 'Rihanna', category: 'Celebridades' },
  { name: 'Michael Jordan', category: 'Celebridades' },
  { name: 'Lionel Messi', category: 'Celebridades' },
  { name: 'Adele', category: 'Celebridades' },
  { name: 'Barack Obama', category: 'Celebridades' },
  { name: 'Lady Gaga', category: 'Celebridades' },
  { name: 'David Bowie', category: 'Celebridades' },
  { name: 'Tom Hanks', category: 'Celebridades' },
  { name: 'Ed Sheeran', category: 'Celebridades' },
  { name: 'Marie Curie', category: 'Celebridades' },
  { name: 'Drake', category: 'Celebridades' },
  { name: 'Billie Eilish', category: 'Celebridades' },
  { name: 'Arnold Schwarzenegger', category: 'Celebridades' },
  { name: 'Mozart', category: 'Celebridades' },
  { name: 'Beethoven', category: 'Celebridades' },
  { name: 'Elvis Presley', category: 'Celebridades' },
  { name: 'Michael Jackson', category: 'Celebridades' },
  { name: 'Madonna', category: 'Celebridades' },
  { name: 'Freddie Mercury', category: 'Celebridades' },
  { name: 'Shakira', category: 'Celebridades' },
  { name: 'Eminem', category: 'Celebridades' },
  { name: 'Dua Lipa', category: 'Celebridades' },
  { name: 'Harry Styles', category: 'Celebridades' },
  { name: 'Ariana Grande', category: 'Celebridades' },
  { name: 'Marilyn Monroe', category: 'Celebridades' },
  { name: 'Charlie Chaplin', category: 'Celebridades' },
  { name: 'Steve Jobs', category: 'Celebridades' },
  { name: 'Mark Zuckerberg', category: 'Celebridades' },
  { name: 'Jeff Bezos', category: 'Celebridades' },
  { name: 'Bill Gates', category: 'Celebridades' },
  { name: 'Queen Elizabeth', category: 'Celebridades' },
  { name: 'Nelson Mandela', category: 'Celebridades' },
  { name: 'Cleopatra', category: 'Celebridades' },
  { name: 'Napoleon', category: 'Celebridades' },
  { name: 'Kim Kardashian', category: 'Celebridades' },
  { name: 'LeBron James', category: 'Celebridades' },
  { name: 'Serena Williams', category: 'Celebridades' },
  { name: 'Dwayne Johnson', category: 'Celebridades' },

  // Animals (40)
  { name: 'Elephant', category: 'Animais' },
  { name: 'Dolphin', category: 'Animais' },
  { name: 'Eagle', category: 'Animais' },
  { name: 'Lion', category: 'Animais' },
  { name: 'Penguin', category: 'Animais' },
  { name: 'Gorilla', category: 'Animais' },
  { name: 'Koala', category: 'Animais' },
  { name: 'Shark', category: 'Animais' },
  { name: 'Giraffe', category: 'Animais' },
  { name: 'Flamingo', category: 'Animais' },
  { name: 'Parrot', category: 'Animais' },
  { name: 'Crocodile', category: 'Animais' },
  { name: 'Wolf', category: 'Animais' },
  { name: 'Bear', category: 'Animais' },
  { name: 'Snake', category: 'Animais' },
  { name: 'Ant', category: 'Animais' },
  { name: 'Hummingbird', category: 'Animais' },
  { name: 'Octopus', category: 'Animais' },
  { name: 'Panda', category: 'Animais' },
  { name: 'Kangaroo', category: 'Animais' },
  { name: 'Chameleon', category: 'Animais' },
  { name: 'Turtle', category: 'Animais' },
  { name: 'Butterfly', category: 'Animais' },
  { name: 'Owl', category: 'Animais' },
  { name: 'Sloth', category: 'Animais' },
  { name: 'Horse', category: 'Animais' },
  { name: 'Cat', category: 'Animais' },
  { name: 'Dog', category: 'Animais' },
  { name: 'Frog', category: 'Animais' },
  { name: 'Spider', category: 'Animais' },
  { name: 'Beaver', category: 'Animais' },
  { name: 'Hippopotamus', category: 'Animais' },
  { name: 'Rhinoceros', category: 'Animais' },
  { name: 'Zebra', category: 'Animais' },
  { name: 'Tiger', category: 'Animais' },
  { name: 'Whale', category: 'Animais' },
  { name: 'Squid', category: 'Animais' },
  { name: 'Meerkat', category: 'Animais' },
  { name: 'Cheetah', category: 'Animais' },
  { name: 'Stork', category: 'Animais' },

  // Professions (40)
  { name: 'Astronaut', category: 'Professions' },
  { name: 'Firefighter', category: 'Professions' },
  { name: 'Detective', category: 'Professions' },
  { name: 'Chef', category: 'Professions' },
  { name: 'Pilot', category: 'Professions' },
  { name: 'Doctor', category: 'Professions' },
  { name: 'Teacher', category: 'Professions' },
  { name: 'Police Officer', category: 'Professions' },
  { name: 'Lawyer', category: 'Professions' },
  { name: 'Journalist', category: 'Professions' },
  { name: 'Architect', category: 'Professions' },
  { name: 'Veterinarian', category: 'Professions' },
  { name: 'Mechanic', category: 'Professions' },
  { name: 'Baker', category: 'Professions' },
  { name: 'Dentist', category: 'Professions' },
  { name: 'Librarian', category: 'Professions' },
  { name: 'Actor', category: 'Professions' },
  { name: 'Musician', category: 'Professions' },
  { name: 'Photographer', category: 'Professions' },
  { name: 'Programmer', category: 'Professions' },
  { name: 'Judge', category: 'Professions' },
  { name: 'Ship Captain', category: 'Professions' },
  { name: 'Scuba Diver', category: 'Professions' },
  { name: 'Magician', category: 'Professions' },
  { name: 'Pharmacist', category: 'Professions' },
  { name: 'Florist', category: 'Professions' },
  { name: 'Sports Coach', category: 'Professions' },
  { name: 'Bus Driver', category: 'Professions' },
  { name: 'Painter', category: 'Professions' },
  { name: 'Tailor', category: 'Professions' },
  { name: 'Beekeeper', category: 'Professions' },
  { name: 'Blacksmith', category: 'Professions' },
  { name: 'Gardener', category: 'Professions' },
  { name: 'Taxi Driver', category: 'Professions' },
  { name: 'Mail Carrier', category: 'Professions' },
  { name: 'Waiter', category: 'Professions' },
  { name: 'Hair Stylist', category: 'Professions' },
  { name: 'Carpenter', category: 'Professions' },
  { name: 'Paramedic', category: 'Professions' },
  { name: 'DJ', category: 'Professions' },

  // Movies (40)
  { name: 'Harry Potter', category: 'Filmes' },
  { name: 'Darth Vader', category: 'Filmes' },
  { name: 'Spider-Man', category: 'Filmes' },
  { name: 'Batman', category: 'Filmes' },
  { name: 'James Bond', category: 'Filmes' },
  { name: 'Shrek', category: 'Filmes' },
  { name: 'Elsa (Frozen)', category: 'Filmes' },
  { name: 'Iron Man', category: 'Filmes' },
  { name: 'Gandalf', category: 'Filmes' },
  { name: 'Jack Sparrow', category: 'Filmes' },
  { name: 'Yoda', category: 'Filmes' },
  { name: 'Simba', category: 'Filmes' },
  { name: 'Indiana Jones', category: 'Filmes' },
  { name: 'Forrest Gump', category: 'Filmes' },
  { name: 'Buzz Lightyear', category: 'Filmes' },
  { name: 'Pikachu', category: 'Filmes' },
  { name: 'Mario (Super Mario)', category: 'Filmes' },
  { name: 'Hermione Granger', category: 'Filmes' },
  { name: 'Joker', category: 'Filmes' },
  { name: 'Rocky Balboa', category: 'Filmes' },
  { name: 'Nemo', category: 'Filmes' },
  { name: 'Rapunzel', category: 'Filmes' },
  { name: 'Thanos', category: 'Filmes' },
  { name: 'Gollum', category: 'Filmes' },
  { name: 'Wolverine', category: 'Filmes' },
  { name: 'Superman', category: 'Filmes' },
  { name: 'Dumbledore', category: 'Filmes' },
  { name: 'Thor', category: 'Filmes' },
  { name: 'Luke Skywalker', category: 'Filmes' },
  { name: 'Wonder Woman', category: 'Filmes' },
  { name: 'Black Panther', category: 'Filmes' },
  { name: 'Captain America', category: 'Filmes' },
  { name: 'Hulk', category: 'Filmes' },
  { name: 'Katniss Everdeen', category: 'Filmes' },
  { name: 'Deadpool', category: 'Filmes' },
  { name: 'Terminator', category: 'Filmes' },
  { name: 'E.T.', category: 'Filmes' },
  { name: 'Grinch', category: 'Filmes' },
  { name: 'Groot', category: 'Filmes' },
  { name: 'Minion', category: 'Filmes' },

  // Fairy Tales & Fantasy (40)
  { name: 'Little Red Riding Hood', category: 'Contos de Fadas' },
  { name: 'Cinderella', category: 'Contos de Fadas' },
  { name: 'Snow White', category: 'Contos de Fadas' },
  { name: 'Sleeping Beauty', category: 'Contos de Fadas' },
  { name: 'Pinocchio', category: 'Contos de Fadas' },
  { name: 'Aladdin', category: 'Contos de Fadas' },
  { name: 'Robin Hood', category: 'Contos de Fadas' },
  { name: 'Peter Pan', category: 'Contos de Fadas' },
  { name: 'Dracula', category: 'Contos de Fadas' },
  { name: 'Frankenstein', category: 'Contos de Fadas' },
  { name: 'Santa Claus', category: 'Contos de Fadas' },
  { name: 'Easter Bunny', category: 'Contos de Fadas' },
  { name: 'Tooth Fairy', category: 'Contos de Fadas' },
  { name: 'Rapunzel', category: 'Contos de Fadas' },
  { name: 'Hansel', category: 'Contos de Fadas' },
  { name: 'Gretel', category: 'Contos de Fadas' },
  { name: 'Rumpelstiltskin', category: 'Contos de Fadas' },
  { name: 'Genie (Lamp)', category: 'Contos de Fadas' },
  { name: 'Mermaid', category: 'Contos de Fadas' },
  { name: 'Unicorn', category: 'Contos de Fadas' },
  { name: 'Dragon', category: 'Contos de Fadas' },
  { name: 'Giant', category: 'Contos de Fadas' },
  { name: 'Witch', category: 'Contos de Fadas' },
  { name: 'Fairy', category: 'Contos de Fadas' },
  { name: 'Wizard', category: 'Contos de Fadas' },
  { name: 'Werewolf', category: 'Contos de Fadas' },
  { name: 'Vampire', category: 'Contos de Fadas' },
  { name: 'Ghost', category: 'Contos de Fadas' },
  { name: 'Dwarf', category: 'Contos de Fadas' },
  { name: 'Elf', category: 'Contos de Fadas' },
  { name: 'Troll', category: 'Contos de Fadas' },
  { name: 'Leprechaun', category: 'Contos de Fadas' },
  { name: 'Phoenix', category: 'Contos de Fadas' },
  { name: 'Pegasus', category: 'Contos de Fadas' },
  { name: 'Medusa', category: 'Contos de Fadas' },
  { name: 'Minotaur', category: 'Contos de Fadas' },
  { name: 'Zeus', category: 'Contos de Fadas' },
  { name: 'Hercules', category: 'Contos de Fadas' },
  { name: 'Poseidon', category: 'Contos de Fadas' },
  { name: 'Athena', category: 'Contos de Fadas' },

  // New Celebrities (30+)
  { name: 'Greta Thunberg', category: 'Celebridades' },
  { name: 'Keanu Reeves', category: 'Celebridades' },
  { name: 'Will Smith', category: 'Celebridades' },
  { name: 'Scarlett Johansson', category: 'Celebridades' },
  { name: 'Zendaya', category: 'Celebridades' },
  { name: 'Robert Downey Jr.', category: 'Celebridades' },
  { name: 'Tom Holland', category: 'Celebridades' },
  { name: 'Margot Robbie', category: 'Celebridades' },
  { name: 'Chris Hemsworth', category: 'Celebridades' },
  { name: 'Jennifer Lawrence', category: 'Celebridades' },
  { name: 'Ryan Gosling', category: 'Celebridades' },
  { name: 'Selena Gomez', category: 'Celebridades' },
  { name: 'Bad Bunny', category: 'Celebridades' },
  { name: 'Post Malone', category: 'Celebridades' },
  { name: 'Kylian Mbappe', category: 'Celebridades' },
  { name: 'Lewis Hamilton', category: 'Celebridades' },
  { name: 'Roger Federer', category: 'Celebridades' },
  { name: 'Sandra Bullock', category: 'Celebridades' },
  { name: 'Morgan Freeman', category: 'Celebridades' },
  { name: 'Mahatma Gandhi', category: 'Celebridades' },
  { name: 'Martin Luther King Jr.', category: 'Celebridades' },
  { name: 'Frida Kahlo', category: 'Celebridades' },
  { name: 'Pablo Picasso', category: 'Celebridades' },
  { name: 'Walt Disney', category: 'Celebridades' },
  { name: 'Nikola Tesla', category: 'Celebridades' },
  { name: 'Stephen Hawking', category: 'Celebridades' },
  { name: 'Abraham Lincoln', category: 'Celebridades' },
  { name: 'Rosa Parks', category: 'Celebridades' },
  { name: 'Dolly Parton', category: 'Celebridades' },
  { name: 'Muhammad Ali', category: 'Celebridades' },
  { name: 'Princess Diana', category: 'Celebridades' },

  // New Animals (30+)
  { name: 'Axolotl', category: 'Animais' },
  { name: 'Narwhal', category: 'Animais' },
  { name: 'Llama', category: 'Animais' },
  { name: 'Alpaca', category: 'Animais' },
  { name: 'Otter', category: 'Animais' },
  { name: 'Seal', category: 'Animais' },
  { name: 'Manatee', category: 'Animais' },
  { name: 'Wombat', category: 'Animais' },
  { name: 'Platypus', category: 'Animais' },
  { name: 'Okapi', category: 'Animais' },
  { name: 'Groundhog', category: 'Animais' },
  { name: 'Lemur', category: 'Animais' },
  { name: 'Mole', category: 'Animais' },
  { name: 'Pelican', category: 'Animais' },
  { name: 'Albatross', category: 'Animais' },
  { name: 'Crane', category: 'Animais' },
  { name: 'Pufferfish', category: 'Animais' },
  { name: 'Manta Ray', category: 'Animais' },
  { name: 'Starfish', category: 'Animais' },
  { name: 'Anteater', category: 'Animais' },
  { name: 'Tapir', category: 'Animais' },
  { name: 'Yak', category: 'Animais' },
  { name: 'Ermine', category: 'Animais' },
  { name: 'Lynx', category: 'Animais' },
  { name: 'Cuckoo', category: 'Animais' },
  { name: 'Crab', category: 'Animais' },
  { name: 'Sea Cucumber', category: 'Animais' },
  { name: 'Skunk', category: 'Animais' },
  { name: 'Raccoon', category: 'Animais' },
  { name: 'Hedgehog', category: 'Animais' },
  { name: 'Bald Eagle', category: 'Animais' },

  // New Professions (30+)
  { name: 'Influencer', category: 'Professions' },
  { name: 'YouTuber', category: 'Professions' },
  { name: 'Sommelier', category: 'Professions' },
  { name: 'Stunt Double', category: 'Professions' },
  { name: 'Voice Actor', category: 'Professions' },
  { name: 'Makeup Artist', category: 'Professions' },
  { name: 'Watchmaker', category: 'Professions' },
  { name: 'Goldsmith', category: 'Professions' },
  { name: 'Brewmaster', category: 'Professions' },
  { name: 'Air Traffic Controller', category: 'Professions' },
  { name: 'Geologist', category: 'Professions' },
  { name: 'Archaeologist', category: 'Professions' },
  { name: 'Meteorologist', category: 'Professions' },
  { name: 'Midwife', category: 'Professions' },
  { name: 'Optician', category: 'Professions' },
  { name: 'Pastry Chef', category: 'Professions' },
  { name: 'Notary', category: 'Professions' },
  { name: 'Chimney Sweep', category: 'Professions' },
  { name: 'Glazier', category: 'Professions' },
  { name: 'Roofer', category: 'Professions' },
  { name: 'Mountain Guide', category: 'Professions' },
  { name: 'Lighthouse Keeper', category: 'Professions' },
  { name: 'Puppeteer', category: 'Professions' },
  { name: 'Gondolier', category: 'Professions' },
  { name: 'Curator', category: 'Professions' },
  { name: 'Film Director', category: 'Professions' },
  { name: 'Orchestra Conductor', category: 'Professions' },
  { name: 'Tattoo Artist', category: 'Professions' },
  { name: 'Park Ranger', category: 'Professions' },
  { name: 'Food Critic', category: 'Professions' },
  { name: 'Lumberjack', category: 'Professions' },

  // New Movies (30+)
  { name: 'Dobby', category: 'Filmes' },
  { name: 'Dory', category: 'Filmes' },
  { name: 'Scar', category: 'Filmes' },
  { name: 'Obi-Wan Kenobi', category: 'Filmes' },
  { name: 'Princess Leia', category: 'Filmes' },
  { name: 'Han Solo', category: 'Filmes' },
  { name: 'Neo', category: 'Filmes' },
  { name: 'Loki', category: 'Filmes' },
  { name: 'Olaf', category: 'Filmes' },
  { name: 'Baymax', category: 'Filmes' },
  { name: 'Remy (Ratatouille)', category: 'Filmes' },
  { name: 'Maui (Moana)', category: 'Filmes' },
  { name: 'Lightning McQueen', category: 'Filmes' },
  { name: 'Scooby-Doo', category: 'Filmes' },
  { name: 'SpongeBob', category: 'Filmes' },
  { name: 'Bart Simpson', category: 'Filmes' },
  { name: 'Homer Simpson', category: 'Filmes' },
  { name: 'Pippi Longstocking', category: 'Filmes' },
  { name: 'Catwoman', category: 'Filmes' },
  { name: 'Doctor Strange', category: 'Filmes' },
  { name: 'Aquaman', category: 'Filmes' },
  { name: 'Shazam', category: 'Filmes' },
  { name: 'Gru', category: 'Filmes' },
  { name: 'Optimus Prime', category: 'Filmes' },
  { name: 'John Wick', category: 'Filmes' },
  { name: 'Sherlock Holmes', category: 'Filmes' },
  { name: 'Daenerys Targaryen', category: 'Filmes' },
  { name: 'Jack Skellington', category: 'Filmes' },
  { name: 'Willy Wonka', category: 'Filmes' },
  { name: 'Wednesday Addams', category: 'Filmes' },
  { name: 'Darth Maul', category: 'Filmes' },

  // New Fairy Tales (30+)
  { name: 'Krampus', category: 'Contos de Fadas' },
  { name: 'Baba Yaga', category: 'Contos de Fadas' },
  { name: 'Basilisk', category: 'Contos de Fadas' },
  { name: 'Centaur', category: 'Contos de Fadas' },
  { name: 'Sphinx', category: 'Contos de Fadas' },
  { name: 'Nymph', category: 'Contos de Fadas' },
  { name: 'Griffin', category: 'Contos de Fadas' },
  { name: 'Hydra', category: 'Contos de Fadas' },
  { name: 'Cyclops', category: 'Contos de Fadas' },
  { name: 'Odysseus', category: 'Contos de Fadas' },
  { name: 'Achilles', category: 'Contos de Fadas' },
  { name: 'Perseus', category: 'Contos de Fadas' },
  { name: 'Aphrodite', category: 'Contos de Fadas' },
  { name: 'Ares', category: 'Contos de Fadas' },
  { name: 'Hera', category: 'Contos de Fadas' },
  { name: 'Prometheus', category: 'Contos de Fadas' },
  { name: 'Pandora', category: 'Contos de Fadas' },
  { name: 'Odin', category: 'Contos de Fadas' },
  { name: 'Freya', category: 'Contos de Fadas' },
  { name: 'Fenrir', category: 'Contos de Fadas' },
  { name: 'Big Bad Wolf', category: 'Contos de Fadas' },
  { name: 'Mother Goose', category: 'Contos de Fadas' },
  { name: 'Frog Prince', category: 'Contos de Fadas' },
  { name: 'Goldilocks', category: 'Contos de Fadas' },
  { name: 'Evil Stepmother', category: 'Contos de Fadas' },
  { name: 'Puss in Boots', category: 'Contos de Fadas' },
  { name: 'Jack (Beanstalk)', category: 'Contos de Fadas' },
  { name: 'The Little Prince', category: 'Contos de Fadas' },
  { name: 'Puck', category: 'Contos de Fadas' },
  { name: 'Titania', category: 'Contos de Fadas' },
  { name: 'Paul Bunyan', category: 'Contos de Fadas' },
];
