export interface WhoAmICharacter {
  name: string;
  category: string;
}

export const WHOAMI_CHARACTERS: WhoAmICharacter[] = [
  // Celebrites (45)
  { name: 'Albert Einstein', category: 'Celebrites' },
  { name: 'Beyonce', category: 'Celebrites' },
  { name: 'Elon Musk', category: 'Celebrites' },
  { name: 'Taylor Swift', category: 'Celebrites' },
  { name: 'Cristiano Ronaldo', category: 'Celebrites' },
  { name: 'Zinedine Zidane', category: 'Celebrites' },
  { name: 'Leonardo DiCaprio', category: 'Celebrites' },
  { name: 'Rihanna', category: 'Celebrites' },
  { name: 'Lionel Messi', category: 'Celebrites' },
  { name: 'Adele', category: 'Celebrites' },
  { name: 'Barack Obama', category: 'Celebrites' },
  { name: 'Lady Gaga', category: 'Celebrites' },
  { name: 'David Bowie', category: 'Celebrites' },
  { name: 'Marion Cotillard', category: 'Celebrites' },
  { name: 'Ed Sheeran', category: 'Celebrites' },
  { name: 'Marie Curie', category: 'Celebrites' },
  { name: 'Drake', category: 'Celebrites' },
  { name: 'Billie Eilish', category: 'Celebrites' },
  { name: 'Kylian Mbappe', category: 'Celebrites' },
  { name: 'Mozart', category: 'Celebrites' },
  { name: 'Beethoven', category: 'Celebrites' },
  { name: 'Elvis Presley', category: 'Celebrites' },
  { name: 'Michael Jackson', category: 'Celebrites' },
  { name: 'Madonna', category: 'Celebrites' },
  { name: 'Freddie Mercury', category: 'Celebrites' },
  { name: 'Stromae', category: 'Celebrites' },
  { name: 'Eminem', category: 'Celebrites' },
  { name: 'Dua Lipa', category: 'Celebrites' },
  { name: 'Harry Styles', category: 'Celebrites' },
  { name: 'Ariana Grande', category: 'Celebrites' },
  { name: 'Marilyn Monroe', category: 'Celebrites' },
  { name: 'Charlie Chaplin', category: 'Celebrites' },
  { name: 'Steve Jobs', category: 'Celebrites' },
  { name: 'Coco Chanel', category: 'Celebrites' },
  { name: 'Victor Hugo', category: 'Celebrites' },
  { name: 'Bill Gates', category: 'Celebrites' },
  { name: 'Nelson Mandela', category: 'Celebrites' },
  { name: 'Cleopatre', category: 'Celebrites' },
  { name: 'Napoleon', category: 'Celebrites' },
  { name: 'Edith Piaf', category: 'Celebrites' },
  { name: 'Omar Sy', category: 'Celebrites' },
  { name: 'Jean Dujardin', category: 'Celebrites' },
  { name: 'Aya Nakamura', category: 'Celebrites' },
  { name: 'Antoine de Saint-Exupery', category: 'Celebrites' },
  { name: 'Daft Punk', category: 'Celebrites' },

  // Animaux (40)
  { name: 'Elephant', category: 'Animaux' },
  { name: 'Dauphin', category: 'Animaux' },
  { name: 'Aigle', category: 'Animaux' },
  { name: 'Lion', category: 'Animaux' },
  { name: 'Pingouin', category: 'Animaux' },
  { name: 'Gorille', category: 'Animaux' },
  { name: 'Koala', category: 'Animaux' },
  { name: 'Requin', category: 'Animaux' },
  { name: 'Girafe', category: 'Animaux' },
  { name: 'Flamant rose', category: 'Animaux' },
  { name: 'Perroquet', category: 'Animaux' },
  { name: 'Crocodile', category: 'Animaux' },
  { name: 'Loup', category: 'Animaux' },
  { name: 'Ours', category: 'Animaux' },
  { name: 'Serpent', category: 'Animaux' },
  { name: 'Fourmi', category: 'Animaux' },
  { name: 'Colibri', category: 'Animaux' },
  { name: 'Poulpe', category: 'Animaux' },
  { name: 'Panda', category: 'Animaux' },
  { name: 'Kangourou', category: 'Animaux' },
  { name: 'Cameleon', category: 'Animaux' },
  { name: 'Tortue', category: 'Animaux' },
  { name: 'Papillon', category: 'Animaux' },
  { name: 'Hibou', category: 'Animaux' },
  { name: 'Paresseux', category: 'Animaux' },
  { name: 'Cheval', category: 'Animaux' },
  { name: 'Chat', category: 'Animaux' },
  { name: 'Chien', category: 'Animaux' },
  { name: 'Grenouille', category: 'Animaux' },
  { name: 'Araignee', category: 'Animaux' },
  { name: 'Castor', category: 'Animaux' },
  { name: 'Hippopotame', category: 'Animaux' },
  { name: 'Rhinoceros', category: 'Animaux' },
  { name: 'Zebre', category: 'Animaux' },
  { name: 'Tigre', category: 'Animaux' },
  { name: 'Baleine', category: 'Animaux' },
  { name: 'Calamar', category: 'Animaux' },
  { name: 'Suricate', category: 'Animaux' },
  { name: 'Guepard', category: 'Animaux' },
  { name: 'Cigogne', category: 'Animaux' },

  // Metiers (40)
  { name: 'Astronaute', category: 'Metiers' },
  { name: 'Pompier', category: 'Metiers' },
  { name: 'Detective', category: 'Metiers' },
  { name: 'Cuisinier', category: 'Metiers' },
  { name: 'Pilote', category: 'Metiers' },
  { name: 'Medecin', category: 'Metiers' },
  { name: 'Professeur', category: 'Metiers' },
  { name: 'Policier', category: 'Metiers' },
  { name: 'Avocat', category: 'Metiers' },
  { name: 'Journaliste', category: 'Metiers' },
  { name: 'Architecte', category: 'Metiers' },
  { name: 'Veterinaire', category: 'Metiers' },
  { name: 'Mecanicien', category: 'Metiers' },
  { name: 'Boulanger', category: 'Metiers' },
  { name: 'Dentiste', category: 'Metiers' },
  { name: 'Bibliothecaire', category: 'Metiers' },
  { name: 'Acteur', category: 'Metiers' },
  { name: 'Musicien', category: 'Metiers' },
  { name: 'Photographe', category: 'Metiers' },
  { name: 'Programmeur', category: 'Metiers' },
  { name: 'Juge', category: 'Metiers' },
  { name: 'Capitaine', category: 'Metiers' },
  { name: 'Plongeur', category: 'Metiers' },
  { name: 'Magicien', category: 'Metiers' },
  { name: 'Pharmacien', category: 'Metiers' },
  { name: 'Fleuriste', category: 'Metiers' },
  { name: 'Entraineur sportif', category: 'Metiers' },
  { name: 'Chauffeur de bus', category: 'Metiers' },
  { name: 'Peintre', category: 'Metiers' },
  { name: 'Tailleur', category: 'Metiers' },
  { name: 'Apiculteur', category: 'Metiers' },
  { name: 'Forgeron', category: 'Metiers' },
  { name: 'Jardinier', category: 'Metiers' },
  { name: 'Chauffeur de taxi', category: 'Metiers' },
  { name: 'Facteur', category: 'Metiers' },
  { name: 'Serveur', category: 'Metiers' },
  { name: 'Coiffeur', category: 'Metiers' },
  { name: 'Menuisier', category: 'Metiers' },
  { name: 'Ambulancier', category: 'Metiers' },
  { name: 'DJ', category: 'Metiers' },

  // Films (40)
  { name: 'Harry Potter', category: 'Films' },
  { name: 'Dark Vador', category: 'Films' },
  { name: 'Spider-Man', category: 'Films' },
  { name: 'Batman', category: 'Films' },
  { name: 'James Bond', category: 'Films' },
  { name: 'Shrek', category: 'Films' },
  { name: 'Elsa (La Reine des Neiges)', category: 'Films' },
  { name: 'Iron Man', category: 'Films' },
  { name: 'Gandalf', category: 'Films' },
  { name: 'Jack Sparrow', category: 'Films' },
  { name: 'Yoda', category: 'Films' },
  { name: 'Simba', category: 'Films' },
  { name: 'Indiana Jones', category: 'Films' },
  { name: 'Forrest Gump', category: 'Films' },
  { name: 'Buzz l\'Eclair', category: 'Films' },
  { name: 'Pikachu', category: 'Films' },
  { name: 'Mario (Super Mario)', category: 'Films' },
  { name: 'Hermione Granger', category: 'Films' },
  { name: 'Joker', category: 'Films' },
  { name: 'Rocky Balboa', category: 'Films' },
  { name: 'Nemo', category: 'Films' },
  { name: 'Raiponce', category: 'Films' },
  { name: 'Thanos', category: 'Films' },
  { name: 'Gollum', category: 'Films' },
  { name: 'Wolverine', category: 'Films' },
  { name: 'Superman', category: 'Films' },
  { name: 'Dumbledore', category: 'Films' },
  { name: 'Thor', category: 'Films' },
  { name: 'Luke Skywalker', category: 'Films' },
  { name: 'Wonder Woman', category: 'Films' },
  { name: 'Black Panther', category: 'Films' },
  { name: 'Captain America', category: 'Films' },
  { name: 'Hulk', category: 'Films' },
  { name: 'Katniss Everdeen', category: 'Films' },
  { name: 'Deadpool', category: 'Films' },
  { name: 'Terminator', category: 'Films' },
  { name: 'E.T.', category: 'Films' },
  { name: 'Le Grinch', category: 'Films' },
  { name: 'Groot', category: 'Films' },
  { name: 'Minion', category: 'Films' },

  // Contes et Fantaisie (40)
  { name: 'Le Petit Chaperon rouge', category: 'Contes' },
  { name: 'Cendrillon', category: 'Contes' },
  { name: 'Blanche-Neige', category: 'Contes' },
  { name: 'La Belle au bois dormant', category: 'Contes' },
  { name: 'Pinocchio', category: 'Contes' },
  { name: 'Aladin', category: 'Contes' },
  { name: 'Robin des Bois', category: 'Contes' },
  { name: 'Peter Pan', category: 'Contes' },
  { name: 'Dracula', category: 'Contes' },
  { name: 'Frankenstein', category: 'Contes' },
  { name: 'Pere Noel', category: 'Contes' },
  { name: 'Lapin de Paques', category: 'Contes' },
  { name: 'Fee des dents', category: 'Contes' },
  { name: 'Raiponce', category: 'Contes' },
  { name: 'Hansel', category: 'Contes' },
  { name: 'Gretel', category: 'Contes' },
  { name: 'Nain Tracassin', category: 'Contes' },
  { name: 'Genie de la lampe', category: 'Contes' },
  { name: 'Sirene', category: 'Contes' },
  { name: 'Licorne', category: 'Contes' },
  { name: 'Dragon', category: 'Contes' },
  { name: 'Geant', category: 'Contes' },
  { name: 'Sorciere', category: 'Contes' },
  { name: 'Fee', category: 'Contes' },
  { name: 'Sorcier', category: 'Contes' },
  { name: 'Loup-garou', category: 'Contes' },
  { name: 'Vampire', category: 'Contes' },
  { name: 'Fantome', category: 'Contes' },
  { name: 'Nain', category: 'Contes' },
  { name: 'Elfe', category: 'Contes' },
  { name: 'Troll', category: 'Contes' },
  { name: 'Lutin', category: 'Contes' },
  { name: 'Phenix', category: 'Contes' },
  { name: 'Pegase', category: 'Contes' },
  { name: 'Meduse', category: 'Contes' },
  { name: 'Minotaure', category: 'Contes' },
  { name: 'Zeus', category: 'Contes' },
  { name: 'Hercule', category: 'Contes' },
  { name: 'Poseidon', category: 'Contes' },
  { name: 'Athena', category: 'Contes' },

  // Nouvelles Celebrites (30+)
  { name: 'Greta Thunberg', category: 'Celebrites' },
  { name: 'Keanu Reeves', category: 'Celebrites' },
  { name: 'Will Smith', category: 'Celebrites' },
  { name: 'Scarlett Johansson', category: 'Celebrites' },
  { name: 'Dwayne Johnson', category: 'Celebrites' },
  { name: 'Zendaya', category: 'Celebrites' },
  { name: 'Robert Downey Jr.', category: 'Celebrites' },
  { name: 'Tom Holland', category: 'Celebrites' },
  { name: 'Margot Robbie', category: 'Celebrites' },
  { name: 'Chris Hemsworth', category: 'Celebrites' },
  { name: 'Jennifer Lawrence', category: 'Celebrites' },
  { name: 'Ryan Gosling', category: 'Celebrites' },
  { name: 'Selena Gomez', category: 'Celebrites' },
  { name: 'Bad Bunny', category: 'Celebrites' },
  { name: 'Post Malone', category: 'Celebrites' },
  { name: 'Lewis Hamilton', category: 'Celebrites' },
  { name: 'Serena Williams', category: 'Celebrites' },
  { name: 'Roger Federer', category: 'Celebrites' },
  { name: 'Sandra Bullock', category: 'Celebrites' },
  { name: 'Morgan Freeman', category: 'Celebrites' },
  { name: 'Mahatma Gandhi', category: 'Celebrites' },
  { name: 'Martin Luther King', category: 'Celebrites' },
  { name: 'Frida Kahlo', category: 'Celebrites' },
  { name: 'Pablo Picasso', category: 'Celebrites' },
  { name: 'Walt Disney', category: 'Celebrites' },
  { name: 'Nikola Tesla', category: 'Celebrites' },
  { name: 'Stephen Hawking', category: 'Celebrites' },
  { name: 'Charles de Gaulle', category: 'Celebrites' },
  { name: 'Brigitte Bardot', category: 'Celebrites' },
  { name: 'Moliere', category: 'Celebrites' },
  { name: 'Angele', category: 'Celebrites' },

  // Nouveaux Animaux (30+)
  { name: 'Axolotl', category: 'Animaux' },
  { name: 'Narval', category: 'Animaux' },
  { name: 'Lama', category: 'Animaux' },
  { name: 'Alpaga', category: 'Animaux' },
  { name: 'Loutre', category: 'Animaux' },
  { name: 'Phoque', category: 'Animaux' },
  { name: 'Lamantin', category: 'Animaux' },
  { name: 'Wombat', category: 'Animaux' },
  { name: 'Ornithorynque', category: 'Animaux' },
  { name: 'Okapi', category: 'Animaux' },
  { name: 'Marmotte', category: 'Animaux' },
  { name: 'Lemurien', category: 'Animaux' },
  { name: 'Taupe', category: 'Animaux' },
  { name: 'Pelican', category: 'Animaux' },
  { name: 'Albatros', category: 'Animaux' },
  { name: 'Grue', category: 'Animaux' },
  { name: 'Poisson-globe', category: 'Animaux' },
  { name: 'Raie manta', category: 'Animaux' },
  { name: 'Etoile de mer', category: 'Animaux' },
  { name: 'Fourmilier', category: 'Animaux' },
  { name: 'Tapir', category: 'Animaux' },
  { name: 'Yak', category: 'Animaux' },
  { name: 'Hermine', category: 'Animaux' },
  { name: 'Lynx', category: 'Animaux' },
  { name: 'Coucou', category: 'Animaux' },
  { name: 'Crabe', category: 'Animaux' },
  { name: 'Concombre de mer', category: 'Animaux' },
  { name: 'Moufette', category: 'Animaux' },
  { name: 'Raton laveur', category: 'Animaux' },
  { name: 'Herisson', category: 'Animaux' },
  { name: 'Aigle royal', category: 'Animaux' },

  // Nouveaux Metiers (30+)
  { name: 'Influenceur', category: 'Metiers' },
  { name: 'Youtubeur', category: 'Metiers' },
  { name: 'Sommelier', category: 'Metiers' },
  { name: 'Cascadeur', category: 'Metiers' },
  { name: 'Doubleur', category: 'Metiers' },
  { name: 'Maquilleur', category: 'Metiers' },
  { name: 'Horloger', category: 'Metiers' },
  { name: 'Orfevre', category: 'Metiers' },
  { name: 'Brasseur', category: 'Metiers' },
  { name: 'Controleur aerien', category: 'Metiers' },
  { name: 'Geologue', category: 'Metiers' },
  { name: 'Archeologue', category: 'Metiers' },
  { name: 'Meteorologue', category: 'Metiers' },
  { name: 'Sage-femme', category: 'Metiers' },
  { name: 'Opticien', category: 'Metiers' },
  { name: 'Patissier', category: 'Metiers' },
  { name: 'Notaire', category: 'Metiers' },
  { name: 'Ramoneur', category: 'Metiers' },
  { name: 'Vitrier', category: 'Metiers' },
  { name: 'Couvreur', category: 'Metiers' },
  { name: 'Guide de montagne', category: 'Metiers' },
  { name: 'Gardien de phare', category: 'Metiers' },
  { name: 'Marionnettiste', category: 'Metiers' },
  { name: 'Gondolier', category: 'Metiers' },
  { name: 'Commissaire d\'exposition', category: 'Metiers' },
  { name: 'Realisateur', category: 'Metiers' },
  { name: 'Chef d\'orchestre', category: 'Metiers' },
  { name: 'Tatoueur', category: 'Metiers' },
  { name: 'Garde forestier', category: 'Metiers' },
  { name: 'Critique gastronomique', category: 'Metiers' },
  { name: 'Bucheron', category: 'Metiers' },

  // Nouveaux Films (30+)
  { name: 'Dobby', category: 'Films' },
  { name: 'Dory', category: 'Films' },
  { name: 'Scar', category: 'Films' },
  { name: 'Obi-Wan Kenobi', category: 'Films' },
  { name: 'Princesse Leia', category: 'Films' },
  { name: 'Han Solo', category: 'Films' },
  { name: 'Neo', category: 'Films' },
  { name: 'Loki', category: 'Films' },
  { name: 'Olaf', category: 'Films' },
  { name: 'Baymax', category: 'Films' },
  { name: 'Remy (Ratatouille)', category: 'Films' },
  { name: 'Maui (Vaiana)', category: 'Films' },
  { name: 'Flash McQueen', category: 'Films' },
  { name: 'Scooby-Doo', category: 'Films' },
  { name: 'Bob l\'Eponge', category: 'Films' },
  { name: 'Bart Simpson', category: 'Films' },
  { name: 'Homer Simpson', category: 'Films' },
  { name: 'Fifi Brindacier', category: 'Films' },
  { name: 'Catwoman', category: 'Films' },
  { name: 'Docteur Strange', category: 'Films' },
  { name: 'Aquaman', category: 'Films' },
  { name: 'Shazam', category: 'Films' },
  { name: 'Gru', category: 'Films' },
  { name: 'Optimus Prime', category: 'Films' },
  { name: 'John Wick', category: 'Films' },
  { name: 'Sherlock Holmes', category: 'Films' },
  { name: 'Daenerys Targaryen', category: 'Films' },
  { name: 'Jack Skellington', category: 'Films' },
  { name: 'Willy Wonka', category: 'Films' },
  { name: 'Mercredi Addams', category: 'Films' },
  { name: 'Asterix', category: 'Films' },

  // Nouveaux Contes (30+)
  { name: 'Krampus', category: 'Contes' },
  { name: 'Baba Yaga', category: 'Contes' },
  { name: 'Basilic', category: 'Contes' },
  { name: 'Centaure', category: 'Contes' },
  { name: 'Sphinx', category: 'Contes' },
  { name: 'Nymphe', category: 'Contes' },
  { name: 'Griffon', category: 'Contes' },
  { name: 'Hydre', category: 'Contes' },
  { name: 'Cyclope', category: 'Contes' },
  { name: 'Ulysse', category: 'Contes' },
  { name: 'Achille', category: 'Contes' },
  { name: 'Persee', category: 'Contes' },
  { name: 'Aphrodite', category: 'Contes' },
  { name: 'Ares', category: 'Contes' },
  { name: 'Hera', category: 'Contes' },
  { name: 'Promethee', category: 'Contes' },
  { name: 'Pandore', category: 'Contes' },
  { name: 'Odin', category: 'Contes' },
  { name: 'Freya', category: 'Contes' },
  { name: 'Fenrir', category: 'Contes' },
  { name: 'Le Grand Mechant Loup', category: 'Contes' },
  { name: 'Le Chat botte', category: 'Contes' },
  { name: 'Le Prince Grenouille', category: 'Contes' },
  { name: 'Boucle d\'Or', category: 'Contes' },
  { name: 'La Mechante Maratre', category: 'Contes' },
  { name: 'Le Petit Poucet', category: 'Contes' },
  { name: 'Le Petit Prince', category: 'Contes' },
  { name: 'Barbe-Bleue', category: 'Contes' },
  { name: 'Alice au Pays des Merveilles', category: 'Contes' },
  { name: 'La Belle et la Bete', category: 'Contes' },
  { name: 'Fee Clochette', category: 'Contes' },
];
