export interface WhoAmICharacter {
  name: string;
  category: string;
}

export const WHOAMI_CHARACTERS: WhoAmICharacter[] = [
  // Prominente (45)
  { name: 'Albert Einstein', category: 'Prominente' },
  { name: 'Beyonce', category: 'Prominente' },
  { name: 'Elon Musk', category: 'Prominente' },
  { name: 'Taylor Swift', category: 'Prominente' },
  { name: 'Cristiano Ronaldo', category: 'Prominente' },
  { name: 'Angela Merkel', category: 'Prominente' },
  { name: 'Leonardo DiCaprio', category: 'Prominente' },
  { name: 'Rihanna', category: 'Prominente' },
  { name: 'Michael Jordan', category: 'Prominente' },
  { name: 'Lionel Messi', category: 'Prominente' },
  { name: 'Adele', category: 'Prominente' },
  { name: 'Barack Obama', category: 'Prominente' },
  { name: 'Lady Gaga', category: 'Prominente' },
  { name: 'David Bowie', category: 'Prominente' },
  { name: 'Oprah Winfrey', category: 'Prominente' },
  { name: 'Ed Sheeran', category: 'Prominente' },
  { name: 'Marie Curie', category: 'Prominente' },
  { name: 'Drake', category: 'Prominente' },
  { name: 'Billie Eilish', category: 'Prominente' },
  { name: 'Arnold Schwarzenegger', category: 'Prominente' },
  { name: 'Mozart', category: 'Prominente' },
  { name: 'Beethoven', category: 'Prominente' },
  { name: 'Elvis Presley', category: 'Prominente' },
  { name: 'Michael Jackson', category: 'Prominente' },
  { name: 'Madonna', category: 'Prominente' },
  { name: 'Freddie Mercury', category: 'Prominente' },
  { name: 'Shakira', category: 'Prominente' },
  { name: 'Eminem', category: 'Prominente' },
  { name: 'Dua Lipa', category: 'Prominente' },
  { name: 'Harry Styles', category: 'Prominente' },
  { name: 'Ariana Grande', category: 'Prominente' },
  { name: 'Marilyn Monroe', category: 'Prominente' },
  { name: 'Charlie Chaplin', category: 'Prominente' },
  { name: 'Steve Jobs', category: 'Prominente' },
  { name: 'Mark Zuckerberg', category: 'Prominente' },
  { name: 'Jeff Bezos', category: 'Prominente' },
  { name: 'Bill Gates', category: 'Prominente' },
  { name: 'Queen Elizabeth', category: 'Prominente' },
  { name: 'Nelson Mandela', category: 'Prominente' },
  { name: 'Cleopatra', category: 'Prominente' },
  { name: 'Napoleon', category: 'Prominente' },
  { name: 'Helene Fischer', category: 'Prominente' },
  { name: 'Thomas Mueller', category: 'Prominente' },
  { name: 'Till Schweiger', category: 'Prominente' },
  { name: 'Heidi Klum', category: 'Prominente' },

  // Tiere (40)
  { name: 'Elefant', category: 'Tiere' },
  { name: 'Delfin', category: 'Tiere' },
  { name: 'Adler', category: 'Tiere' },
  { name: 'Loewe', category: 'Tiere' },
  { name: 'Pinguin', category: 'Tiere' },
  { name: 'Gorilla', category: 'Tiere' },
  { name: 'Koala', category: 'Tiere' },
  { name: 'Hai', category: 'Tiere' },
  { name: 'Giraffe', category: 'Tiere' },
  { name: 'Flamingo', category: 'Tiere' },
  { name: 'Papagei', category: 'Tiere' },
  { name: 'Krokodil', category: 'Tiere' },
  { name: 'Wolf', category: 'Tiere' },
  { name: 'Baer', category: 'Tiere' },
  { name: 'Schlange', category: 'Tiere' },
  { name: 'Ameise', category: 'Tiere' },
  { name: 'Kolibri', category: 'Tiere' },
  { name: 'Oktopus', category: 'Tiere' },
  { name: 'Panda', category: 'Tiere' },
  { name: 'Känguru', category: 'Tiere' },
  { name: 'Chamäleon', category: 'Tiere' },
  { name: 'Schildkroete', category: 'Tiere' },
  { name: 'Schmetterling', category: 'Tiere' },
  { name: 'Eule', category: 'Tiere' },
  { name: 'Faultier', category: 'Tiere' },
  { name: 'Pferd', category: 'Tiere' },
  { name: 'Katze', category: 'Tiere' },
  { name: 'Hund', category: 'Tiere' },
  { name: 'Frosch', category: 'Tiere' },
  { name: 'Spinne', category: 'Tiere' },
  { name: 'Biber', category: 'Tiere' },
  { name: 'Nilpferd', category: 'Tiere' },
  { name: 'Nashorn', category: 'Tiere' },
  { name: 'Zebra', category: 'Tiere' },
  { name: 'Tiger', category: 'Tiere' },
  { name: 'Wal', category: 'Tiere' },
  { name: 'Tintenfisch', category: 'Tiere' },
  { name: 'Erdmaennchen', category: 'Tiere' },
  { name: 'Gepard', category: 'Tiere' },
  { name: 'Storch', category: 'Tiere' },

  // Berufe (40)
  { name: 'Astronaut', category: 'Berufe' },
  { name: 'Feuerwehrmann', category: 'Berufe' },
  { name: 'Detektiv', category: 'Berufe' },
  { name: 'Koch', category: 'Berufe' },
  { name: 'Pilot', category: 'Berufe' },
  { name: 'Arzt', category: 'Berufe' },
  { name: 'Lehrer', category: 'Berufe' },
  { name: 'Polizist', category: 'Berufe' },
  { name: 'Anwalt', category: 'Berufe' },
  { name: 'Journalist', category: 'Berufe' },
  { name: 'Architekt', category: 'Berufe' },
  { name: 'Tierarzt', category: 'Berufe' },
  { name: 'Mechaniker', category: 'Berufe' },
  { name: 'Baecker', category: 'Berufe' },
  { name: 'Zahnarzt', category: 'Berufe' },
  { name: 'Bibliothekar', category: 'Berufe' },
  { name: 'Schauspieler', category: 'Berufe' },
  { name: 'Musiker', category: 'Berufe' },
  { name: 'Fotograf', category: 'Berufe' },
  { name: 'Programmierer', category: 'Berufe' },
  { name: 'Richter', category: 'Berufe' },
  { name: 'Kapitaen', category: 'Berufe' },
  { name: 'Taucher', category: 'Berufe' },
  { name: 'Zauberer', category: 'Berufe' },
  { name: 'Apotheker', category: 'Berufe' },
  { name: 'Florist', category: 'Berufe' },
  { name: 'Sporttrainer', category: 'Berufe' },
  { name: 'Busfahrer', category: 'Berufe' },
  { name: 'Maler', category: 'Berufe' },
  { name: 'Schneider', category: 'Berufe' },
  { name: 'Imker', category: 'Berufe' },
  { name: 'Schmied', category: 'Berufe' },
  { name: 'Gaertner', category: 'Berufe' },
  { name: 'Taxifahrer', category: 'Berufe' },
  { name: 'Postbote', category: 'Berufe' },
  { name: 'Kellner', category: 'Berufe' },
  { name: 'Friseur', category: 'Berufe' },
  { name: 'Tischler', category: 'Berufe' },
  { name: 'Rettungssanitaeter', category: 'Berufe' },
  { name: 'DJ', category: 'Berufe' },

  // Filme (40)
  { name: 'Harry Potter', category: 'Filme' },
  { name: 'Darth Vader', category: 'Filme' },
  { name: 'Spider-Man', category: 'Filme' },
  { name: 'Batman', category: 'Filme' },
  { name: 'James Bond', category: 'Filme' },
  { name: 'Shrek', category: 'Filme' },
  { name: 'Elsa (Frozen)', category: 'Filme' },
  { name: 'Iron Man', category: 'Filme' },
  { name: 'Gandalf', category: 'Filme' },
  { name: 'Jack Sparrow', category: 'Filme' },
  { name: 'Yoda', category: 'Filme' },
  { name: 'Simba', category: 'Filme' },
  { name: 'Indiana Jones', category: 'Filme' },
  { name: 'Forrest Gump', category: 'Filme' },
  { name: 'Buzz Lightyear', category: 'Filme' },
  { name: 'Pikachu', category: 'Filme' },
  { name: 'Mario (Super Mario)', category: 'Filme' },
  { name: 'Hermine Granger', category: 'Filme' },
  { name: 'Joker', category: 'Filme' },
  { name: 'Rocky Balboa', category: 'Filme' },
  { name: 'Nemo', category: 'Filme' },
  { name: 'Rapunzel', category: 'Filme' },
  { name: 'Thanos', category: 'Filme' },
  { name: 'Gollum', category: 'Filme' },
  { name: 'Wolverine', category: 'Filme' },
  { name: 'Superman', category: 'Filme' },
  { name: 'Dumbledore', category: 'Filme' },
  { name: 'Thor', category: 'Filme' },
  { name: 'Luke Skywalker', category: 'Filme' },
  { name: 'Wonder Woman', category: 'Filme' },
  { name: 'Black Panther', category: 'Filme' },
  { name: 'Captain America', category: 'Filme' },
  { name: 'Hulk', category: 'Filme' },
  { name: 'Katniss Everdeen', category: 'Filme' },
  { name: 'Deadpool', category: 'Filme' },
  { name: 'Terminator', category: 'Filme' },
  { name: 'E.T.', category: 'Filme' },
  { name: 'Grinch', category: 'Filme' },
  { name: 'Groot', category: 'Filme' },
  { name: 'Minion', category: 'Filme' },

  // Maerchen & Fantasie (40)
  { name: 'Rotkäppchen', category: 'Maerchen' },
  { name: 'Aschenputtel', category: 'Maerchen' },
  { name: 'Schneewittchen', category: 'Maerchen' },
  { name: 'Dornroeschen', category: 'Maerchen' },
  { name: 'Pinocchio', category: 'Maerchen' },
  { name: 'Aladin', category: 'Maerchen' },
  { name: 'Robin Hood', category: 'Maerchen' },
  { name: 'Peter Pan', category: 'Maerchen' },
  { name: 'Dracula', category: 'Maerchen' },
  { name: 'Frankenstein', category: 'Maerchen' },
  { name: 'Weihnachtsmann', category: 'Maerchen' },
  { name: 'Osterhase', category: 'Maerchen' },
  { name: 'Zahnfee', category: 'Maerchen' },
  { name: 'Rapunzel', category: 'Maerchen' },
  { name: 'Haensel', category: 'Maerchen' },
  { name: 'Gretel', category: 'Maerchen' },
  { name: 'Rumpelstilzchen', category: 'Maerchen' },
  { name: 'Dschinn (Flaschengeist)', category: 'Maerchen' },
  { name: 'Meerjungfrau', category: 'Maerchen' },
  { name: 'Einhorn', category: 'Maerchen' },
  { name: 'Drache', category: 'Maerchen' },
  { name: 'Riese', category: 'Maerchen' },
  { name: 'Hexe', category: 'Maerchen' },
  { name: 'Fee', category: 'Maerchen' },
  { name: 'Zauberer', category: 'Maerchen' },
  { name: 'Werwolf', category: 'Maerchen' },
  { name: 'Vampir', category: 'Maerchen' },
  { name: 'Geist', category: 'Maerchen' },
  { name: 'Zwerg', category: 'Maerchen' },
  { name: 'Elf', category: 'Maerchen' },
  { name: 'Troll', category: 'Maerchen' },
  { name: 'Kobold', category: 'Maerchen' },
  { name: 'Phoenix', category: 'Maerchen' },
  { name: 'Pegasus', category: 'Maerchen' },
  { name: 'Medusa', category: 'Maerchen' },
  { name: 'Minotaurus', category: 'Maerchen' },
  { name: 'Zeus', category: 'Maerchen' },
  { name: 'Herkules', category: 'Maerchen' },
  { name: 'Poseidon', category: 'Maerchen' },
  { name: 'Athene', category: 'Maerchen' },
];
