export interface WhoAmICharacter {
  name: string;
  category: string;
}

export const WHOAMI_CHARACTERS_PL: WhoAmICharacter[] = [
  // Slawni (45)
  { name: 'Albert Einstein', category: 'Slawni' },
  { name: 'Beyonce', category: 'Slawni' },
  { name: 'Elon Musk', category: 'Slawni' },
  { name: 'Taylor Swift', category: 'Slawni' },
  { name: 'Cristiano Ronaldo', category: 'Slawni' },
  { name: 'Robert Lewandowski', category: 'Slawni' },
  { name: 'Leonardo DiCaprio', category: 'Slawni' },
  { name: 'Rihanna', category: 'Slawni' },
  { name: 'Michael Jordan', category: 'Slawni' },
  { name: 'Lionel Messi', category: 'Slawni' },
  { name: 'Adele', category: 'Slawni' },
  { name: 'Barack Obama', category: 'Slawni' },
  { name: 'Lady Gaga', category: 'Slawni' },
  { name: 'David Bowie', category: 'Slawni' },
  { name: 'Oprah Winfrey', category: 'Slawni' },
  { name: 'Ed Sheeran', category: 'Slawni' },
  { name: 'Maria Sklodowska-Curie', category: 'Slawni' },
  { name: 'Drake', category: 'Slawni' },
  { name: 'Billie Eilish', category: 'Slawni' },
  { name: 'Arnold Schwarzenegger', category: 'Slawni' },
  { name: 'Mozart', category: 'Slawni' },
  { name: 'Beethoven', category: 'Slawni' },
  { name: 'Elvis Presley', category: 'Slawni' },
  { name: 'Michael Jackson', category: 'Slawni' },
  { name: 'Madonna', category: 'Slawni' },
  { name: 'Freddie Mercury', category: 'Slawni' },
  { name: 'Shakira', category: 'Slawni' },
  { name: 'Fryderyk Chopin', category: 'Slawni' },
  { name: 'Mikolaj Kopernik', category: 'Slawni' },
  { name: 'Jan Pawel II', category: 'Slawni' },
  { name: 'Lech Walesa', category: 'Slawni' },
  { name: 'Iga Swiatek', category: 'Slawni' },
  { name: 'Dawid Podsiadlo', category: 'Slawni' },
  { name: 'Sanah', category: 'Slawni' },
  { name: 'Greta Thunberg', category: 'Slawni' },
  { name: 'Keanu Reeves', category: 'Slawni' },
  { name: 'Will Smith', category: 'Slawni' },
  { name: 'Zendaya', category: 'Slawni' },
  { name: 'Robert Downey Jr.', category: 'Slawni' },
  { name: 'Tom Holland', category: 'Slawni' },
  { name: 'Margot Robbie', category: 'Slawni' },
  { name: 'Adam Mickiewicz', category: 'Slawni' },
  { name: 'Wislawa Szymborska', category: 'Slawni' },
  { name: 'Henryk Sienkiewicz', category: 'Slawni' },
  { name: 'Andrzej Wajda', category: 'Slawni' },
  // Zwierzeta (40)
  { name: 'Slon', category: 'Zwierzeta' },
  { name: 'Delfin', category: 'Zwierzeta' },
  { name: 'Orzel', category: 'Zwierzeta' },
  { name: 'Lew', category: 'Zwierzeta' },
  { name: 'Pingwin', category: 'Zwierzeta' },
  { name: 'Goryl', category: 'Zwierzeta' },
  { name: 'Koala', category: 'Zwierzeta' },
  { name: 'Rekin', category: 'Zwierzeta' },
  { name: 'Zyrafa', category: 'Zwierzeta' },
  { name: 'Flaming', category: 'Zwierzeta' },
  { name: 'Papuga', category: 'Zwierzeta' },
  { name: 'Krokodyl', category: 'Zwierzeta' },
  { name: 'Wilk', category: 'Zwierzeta' },
  { name: 'Niedzwiedz', category: 'Zwierzeta' },
  { name: 'Waz', category: 'Zwierzeta' },
  { name: 'Mrowka', category: 'Zwierzeta' },
  { name: 'Koliber', category: 'Zwierzeta' },
  { name: 'Osmica', category: 'Zwierzeta' },
  { name: 'Panda', category: 'Zwierzeta' },
  { name: 'Kangur', category: 'Zwierzeta' },
  { name: 'Kameleon', category: 'Zwierzeta' },
  { name: 'Zolw', category: 'Zwierzeta' },
  { name: 'Motyl', category: 'Zwierzeta' },
  { name: 'Sowa', category: 'Zwierzeta' },
  { name: 'Leniwiec', category: 'Zwierzeta' },
  { name: 'Kon', category: 'Zwierzeta' },
  { name: 'Kot', category: 'Zwierzeta' },
  { name: 'Pies', category: 'Zwierzeta' },
  { name: 'Zaba', category: 'Zwierzeta' },
  { name: 'Pajak', category: 'Zwierzeta' },
  { name: 'Bobr', category: 'Zwierzeta' },
  { name: 'Hipopotam', category: 'Zwierzeta' },
  { name: 'Nosorozec', category: 'Zwierzeta' },
  { name: 'Zebra', category: 'Zwierzeta' },
  { name: 'Tygrys', category: 'Zwierzeta' },
  { name: 'Wieloryb', category: 'Zwierzeta' },
  { name: 'Surykatka', category: 'Zwierzeta' },
  { name: 'Gepard', category: 'Zwierzeta' },
  { name: 'Bocian', category: 'Zwierzeta' },
  { name: 'Axolotl', category: 'Zwierzeta' },
  // Zawody (40)
  { name: 'Astronauta', category: 'Zawody' },
  { name: 'Strazak', category: 'Zawody' },
  { name: 'Detektyw', category: 'Zawody' },
  { name: 'Kucharz', category: 'Zawody' },
  { name: 'Pilot', category: 'Zawody' },
  { name: 'Lekarz', category: 'Zawody' },
  { name: 'Nauczyciel', category: 'Zawody' },
  { name: 'Policjant', category: 'Zawody' },
  { name: 'Prawnik', category: 'Zawody' },
  { name: 'Dziennikarz', category: 'Zawody' },
  { name: 'Architekt', category: 'Zawody' },
  { name: 'Weterynarz', category: 'Zawody' },
  { name: 'Mechanik', category: 'Zawody' },
  { name: 'Piekarz', category: 'Zawody' },
  { name: 'Dentysta', category: 'Zawody' },
  { name: 'Bibliotekarz', category: 'Zawody' },
  { name: 'Aktor', category: 'Zawody' },
  { name: 'Muzyk', category: 'Zawody' },
  { name: 'Fotograf', category: 'Zawody' },
  { name: 'Programista', category: 'Zawody' },
  { name: 'Sedzia', category: 'Zawody' },
  { name: 'Kapitan', category: 'Zawody' },
  { name: 'Nurek', category: 'Zawody' },
  { name: 'Magik', category: 'Zawody' },
  { name: 'Aptekarz', category: 'Zawody' },
  { name: 'Florysta', category: 'Zawody' },
  { name: 'Trener', category: 'Zawody' },
  { name: 'Kierowca autobusu', category: 'Zawody' },
  { name: 'Malarz', category: 'Zawody' },
  { name: 'Krawiec', category: 'Zawody' },
  { name: 'Pszczelarz', category: 'Zawody' },
  { name: 'Kowal', category: 'Zawody' },
  { name: 'Ogrodnik', category: 'Zawody' },
  { name: 'Taksowkarz', category: 'Zawody' },
  { name: 'Listonosz', category: 'Zawody' },
  { name: 'Kelner', category: 'Zawody' },
  { name: 'Fryzjer', category: 'Zawody' },
  { name: 'Stolarz', category: 'Zawody' },
  { name: 'Ratownik medyczny', category: 'Zawody' },
  { name: 'DJ', category: 'Zawody' },
  // Filmy (40)
  { name: 'Harry Potter', category: 'Filmy' },
  { name: 'Darth Vader', category: 'Filmy' },
  { name: 'Spider-Man', category: 'Filmy' },
  { name: 'Batman', category: 'Filmy' },
  { name: 'James Bond', category: 'Filmy' },
  { name: 'Shrek', category: 'Filmy' },
  { name: 'Elsa (Kraina Lodu)', category: 'Filmy' },
  { name: 'Iron Man', category: 'Filmy' },
  { name: 'Gandalf', category: 'Filmy' },
  { name: 'Jack Sparrow', category: 'Filmy' },
  { name: 'Yoda', category: 'Filmy' },
  { name: 'Simba', category: 'Filmy' },
  { name: 'Indiana Jones', category: 'Filmy' },
  { name: 'Forrest Gump', category: 'Filmy' },
  { name: 'Buzz Astral', category: 'Filmy' },
  { name: 'Pikachu', category: 'Filmy' },
  { name: 'Mario (Super Mario)', category: 'Filmy' },
  { name: 'Hermiona Granger', category: 'Filmy' },
  { name: 'Joker', category: 'Filmy' },
  { name: 'Rocky Balboa', category: 'Filmy' },
  { name: 'Nemo', category: 'Filmy' },
  { name: 'Roszpunka', category: 'Filmy' },
  { name: 'Thanos', category: 'Filmy' },
  { name: 'Gollum', category: 'Filmy' },
  { name: 'Wolverine', category: 'Filmy' },
  { name: 'Superman', category: 'Filmy' },
  { name: 'Dumbledore', category: 'Filmy' },
  { name: 'Thor', category: 'Filmy' },
  { name: 'Luke Skywalker', category: 'Filmy' },
  { name: 'Wonder Woman', category: 'Filmy' },
  { name: 'Black Panther', category: 'Filmy' },
  { name: 'Kapitan Ameryka', category: 'Filmy' },
  { name: 'Hulk', category: 'Filmy' },
  { name: 'Katniss Everdeen', category: 'Filmy' },
  { name: 'Deadpool', category: 'Filmy' },
  { name: 'Terminator', category: 'Filmy' },
  { name: 'E.T.', category: 'Filmy' },
  { name: 'Grinch', category: 'Filmy' },
  { name: 'Groot', category: 'Filmy' },
  { name: 'Minionek', category: 'Filmy' },
  // Basnie i Fantazja (40)
  { name: 'Czerwony Kapturek', category: 'Basnie' },
  { name: 'Kopciuszek', category: 'Basnie' },
  { name: 'Krolewna Sniezka', category: 'Basnie' },
  { name: 'Spiaca Krolewna', category: 'Basnie' },
  { name: 'Pinokio', category: 'Basnie' },
  { name: 'Aladyn', category: 'Basnie' },
  { name: 'Robin Hood', category: 'Basnie' },
  { name: 'Piotrus Pan', category: 'Basnie' },
  { name: 'Dracula', category: 'Basnie' },
  { name: 'Frankenstein', category: 'Basnie' },
  { name: 'Mikolaj', category: 'Basnie' },
  { name: 'Zajaczek Wielkanocny', category: 'Basnie' },
  { name: 'Wrozka Zebuszka', category: 'Basnie' },
  { name: 'Roszpunka', category: 'Basnie' },
  { name: 'Jas', category: 'Basnie' },
  { name: 'Malgosia', category: 'Basnie' },
  { name: 'Titelitury', category: 'Basnie' },
  { name: 'Dzinn', category: 'Basnie' },
  { name: 'Syrenka', category: 'Basnie' },
  { name: 'Jednorozec', category: 'Basnie' },
  { name: 'Smok', category: 'Basnie' },
  { name: 'Olbrzym', category: 'Basnie' },
  { name: 'Czarownica', category: 'Basnie' },
  { name: 'Wrozka', category: 'Basnie' },
  { name: 'Czarodziej', category: 'Basnie' },
  { name: 'Wilkolak', category: 'Basnie' },
  { name: 'Wampir', category: 'Basnie' },
  { name: 'Duch', category: 'Basnie' },
  { name: 'Krasnolудek', category: 'Basnie' },
  { name: 'Elf', category: 'Basnie' },
  { name: 'Troll', category: 'Basnie' },
  { name: 'Krasnal', category: 'Basnie' },
  { name: 'Feniks', category: 'Basnie' },
  { name: 'Pegaz', category: 'Basnie' },
  { name: 'Meduza', category: 'Basnie' },
  { name: 'Minotaur', category: 'Basnie' },
  { name: 'Zeus', category: 'Basnie' },
  { name: 'Herkules', category: 'Basnie' },
  { name: 'Posejdon', category: 'Basnie' },
  { name: 'Atena', category: 'Basnie' },
];
