export interface WhoAmICharacter {
  name: string;
  category: string;
}

export const WHOAMI_CHARACTERS: WhoAmICharacter[] = [
  // Famosos (45)
  { name: 'Albert Einstein', category: 'Famosos' },
  { name: 'Beyonce', category: 'Famosos' },
  { name: 'Elon Musk', category: 'Famosos' },
  { name: 'Taylor Swift', category: 'Famosos' },
  { name: 'Cristiano Ronaldo', category: 'Famosos' },
  { name: 'Shakira', category: 'Famosos' },
  { name: 'Leonardo DiCaprio', category: 'Famosos' },
  { name: 'Rihanna', category: 'Famosos' },
  { name: 'Lionel Messi', category: 'Famosos' },
  { name: 'Adele', category: 'Famosos' },
  { name: 'Bad Bunny', category: 'Famosos' },
  { name: 'Lady Gaga', category: 'Famosos' },
  { name: 'David Bowie', category: 'Famosos' },
  { name: 'Penelope Cruz', category: 'Famosos' },
  { name: 'Ed Sheeran', category: 'Famosos' },
  { name: 'Marie Curie', category: 'Famosos' },
  { name: 'Drake', category: 'Famosos' },
  { name: 'Billie Eilish', category: 'Famosos' },
  { name: 'Rafael Nadal', category: 'Famosos' },
  { name: 'Mozart', category: 'Famosos' },
  { name: 'Beethoven', category: 'Famosos' },
  { name: 'Elvis Presley', category: 'Famosos' },
  { name: 'Michael Jackson', category: 'Famosos' },
  { name: 'Madonna', category: 'Famosos' },
  { name: 'Freddie Mercury', category: 'Famosos' },
  { name: 'Rosalia', category: 'Famosos' },
  { name: 'Eminem', category: 'Famosos' },
  { name: 'Dua Lipa', category: 'Famosos' },
  { name: 'Harry Styles', category: 'Famosos' },
  { name: 'Ariana Grande', category: 'Famosos' },
  { name: 'Marilyn Monroe', category: 'Famosos' },
  { name: 'Charlie Chaplin', category: 'Famosos' },
  { name: 'Steve Jobs', category: 'Famosos' },
  { name: 'Frida Kahlo', category: 'Famosos' },
  { name: 'Pablo Picasso', category: 'Famosos' },
  { name: 'Bill Gates', category: 'Famosos' },
  { name: 'Nelson Mandela', category: 'Famosos' },
  { name: 'Cleopatra', category: 'Famosos' },
  { name: 'Napoleon', category: 'Famosos' },
  { name: 'Gabriel Garcia Marquez', category: 'Famosos' },
  { name: 'Antonio Banderas', category: 'Famosos' },
  { name: 'Paco de Lucia', category: 'Famosos' },
  { name: 'Diego Maradona', category: 'Famosos' },
  { name: 'Selena Gomez', category: 'Famosos' },
  { name: 'Kylian Mbappe', category: 'Famosos' },

  // Animales (40)
  { name: 'Elefante', category: 'Animales' },
  { name: 'Delfin', category: 'Animales' },
  { name: 'Aguila', category: 'Animales' },
  { name: 'Leon', category: 'Animales' },
  { name: 'Pinguino', category: 'Animales' },
  { name: 'Gorila', category: 'Animales' },
  { name: 'Koala', category: 'Animales' },
  { name: 'Tiburon', category: 'Animales' },
  { name: 'Jirafa', category: 'Animales' },
  { name: 'Flamenco', category: 'Animales' },
  { name: 'Loro', category: 'Animales' },
  { name: 'Cocodrilo', category: 'Animales' },
  { name: 'Lobo', category: 'Animales' },
  { name: 'Oso', category: 'Animales' },
  { name: 'Serpiente', category: 'Animales' },
  { name: 'Hormiga', category: 'Animales' },
  { name: 'Colibri', category: 'Animales' },
  { name: 'Pulpo', category: 'Animales' },
  { name: 'Panda', category: 'Animales' },
  { name: 'Canguro', category: 'Animales' },
  { name: 'Camaleon', category: 'Animales' },
  { name: 'Tortuga', category: 'Animales' },
  { name: 'Mariposa', category: 'Animales' },
  { name: 'Buho', category: 'Animales' },
  { name: 'Perezoso', category: 'Animales' },
  { name: 'Caballo', category: 'Animales' },
  { name: 'Gato', category: 'Animales' },
  { name: 'Perro', category: 'Animales' },
  { name: 'Rana', category: 'Animales' },
  { name: 'Arana', category: 'Animales' },
  { name: 'Castor', category: 'Animales' },
  { name: 'Hipopotamo', category: 'Animales' },
  { name: 'Rinoceronte', category: 'Animales' },
  { name: 'Cebra', category: 'Animales' },
  { name: 'Tigre', category: 'Animales' },
  { name: 'Ballena', category: 'Animales' },
  { name: 'Calamar', category: 'Animales' },
  { name: 'Suricata', category: 'Animales' },
  { name: 'Guepardo', category: 'Animales' },
  { name: 'Ciguena', category: 'Animales' },

  // Profesiones (40)
  { name: 'Astronauta', category: 'Profesiones' },
  { name: 'Bombero', category: 'Profesiones' },
  { name: 'Detective', category: 'Profesiones' },
  { name: 'Cocinero', category: 'Profesiones' },
  { name: 'Piloto', category: 'Profesiones' },
  { name: 'Medico', category: 'Profesiones' },
  { name: 'Profesor', category: 'Profesiones' },
  { name: 'Policia', category: 'Profesiones' },
  { name: 'Abogado', category: 'Profesiones' },
  { name: 'Periodista', category: 'Profesiones' },
  { name: 'Arquitecto', category: 'Profesiones' },
  { name: 'Veterinario', category: 'Profesiones' },
  { name: 'Mecanico', category: 'Profesiones' },
  { name: 'Panadero', category: 'Profesiones' },
  { name: 'Dentista', category: 'Profesiones' },
  { name: 'Bibliotecario', category: 'Profesiones' },
  { name: 'Actor', category: 'Profesiones' },
  { name: 'Musico', category: 'Profesiones' },
  { name: 'Fotografo', category: 'Profesiones' },
  { name: 'Programador', category: 'Profesiones' },
  { name: 'Juez', category: 'Profesiones' },
  { name: 'Capitan', category: 'Profesiones' },
  { name: 'Buzo', category: 'Profesiones' },
  { name: 'Mago', category: 'Profesiones' },
  { name: 'Farmaceutico', category: 'Profesiones' },
  { name: 'Florista', category: 'Profesiones' },
  { name: 'Entrenador', category: 'Profesiones' },
  { name: 'Conductor de autobus', category: 'Profesiones' },
  { name: 'Pintor', category: 'Profesiones' },
  { name: 'Sastre', category: 'Profesiones' },
  { name: 'Apicultor', category: 'Profesiones' },
  { name: 'Herrero', category: 'Profesiones' },
  { name: 'Jardinero', category: 'Profesiones' },
  { name: 'Taxista', category: 'Profesiones' },
  { name: 'Cartero', category: 'Profesiones' },
  { name: 'Camarero', category: 'Profesiones' },
  { name: 'Peluquero', category: 'Profesiones' },
  { name: 'Carpintero', category: 'Profesiones' },
  { name: 'Paramedico', category: 'Profesiones' },
  { name: 'DJ', category: 'Profesiones' },

  // Peliculas (40)
  { name: 'Harry Potter', category: 'Peliculas' },
  { name: 'Darth Vader', category: 'Peliculas' },
  { name: 'Spider-Man', category: 'Peliculas' },
  { name: 'Batman', category: 'Peliculas' },
  { name: 'James Bond', category: 'Peliculas' },
  { name: 'Shrek', category: 'Peliculas' },
  { name: 'Elsa (Frozen)', category: 'Peliculas' },
  { name: 'Iron Man', category: 'Peliculas' },
  { name: 'Gandalf', category: 'Peliculas' },
  { name: 'Jack Sparrow', category: 'Peliculas' },
  { name: 'Yoda', category: 'Peliculas' },
  { name: 'Simba', category: 'Peliculas' },
  { name: 'Indiana Jones', category: 'Peliculas' },
  { name: 'Forrest Gump', category: 'Peliculas' },
  { name: 'Buzz Lightyear', category: 'Peliculas' },
  { name: 'Pikachu', category: 'Peliculas' },
  { name: 'Mario (Super Mario)', category: 'Peliculas' },
  { name: 'Hermione Granger', category: 'Peliculas' },
  { name: 'Joker', category: 'Peliculas' },
  { name: 'Rocky Balboa', category: 'Peliculas' },
  { name: 'Nemo', category: 'Peliculas' },
  { name: 'Rapunzel', category: 'Peliculas' },
  { name: 'Thanos', category: 'Peliculas' },
  { name: 'Gollum', category: 'Peliculas' },
  { name: 'Wolverine', category: 'Peliculas' },
  { name: 'Superman', category: 'Peliculas' },
  { name: 'Dumbledore', category: 'Peliculas' },
  { name: 'Thor', category: 'Peliculas' },
  { name: 'Luke Skywalker', category: 'Peliculas' },
  { name: 'Wonder Woman', category: 'Peliculas' },
  { name: 'Black Panther', category: 'Peliculas' },
  { name: 'Capitan America', category: 'Peliculas' },
  { name: 'Hulk', category: 'Peliculas' },
  { name: 'Katniss Everdeen', category: 'Peliculas' },
  { name: 'Deadpool', category: 'Peliculas' },
  { name: 'Terminator', category: 'Peliculas' },
  { name: 'E.T.', category: 'Peliculas' },
  { name: 'Grinch', category: 'Peliculas' },
  { name: 'Groot', category: 'Peliculas' },
  { name: 'Minion', category: 'Peliculas' },

  // Cuentos y Fantasia (40)
  { name: 'Caperucita Roja', category: 'Cuentos' },
  { name: 'Cenicienta', category: 'Cuentos' },
  { name: 'Blancanieves', category: 'Cuentos' },
  { name: 'La Bella Durmiente', category: 'Cuentos' },
  { name: 'Pinocho', category: 'Cuentos' },
  { name: 'Aladino', category: 'Cuentos' },
  { name: 'Robin Hood', category: 'Cuentos' },
  { name: 'Peter Pan', category: 'Cuentos' },
  { name: 'Dracula', category: 'Cuentos' },
  { name: 'Frankenstein', category: 'Cuentos' },
  { name: 'Papa Noel', category: 'Cuentos' },
  { name: 'Raton Perez', category: 'Cuentos' },
  { name: 'Hada Madrina', category: 'Cuentos' },
  { name: 'Rapunzel', category: 'Cuentos' },
  { name: 'Hansel', category: 'Cuentos' },
  { name: 'Gretel', category: 'Cuentos' },
  { name: 'Rumpelstiltskin', category: 'Cuentos' },
  { name: 'Genio de la Lampara', category: 'Cuentos' },
  { name: 'Sirena', category: 'Cuentos' },
  { name: 'Unicornio', category: 'Cuentos' },
  { name: 'Dragon', category: 'Cuentos' },
  { name: 'Gigante', category: 'Cuentos' },
  { name: 'Bruja', category: 'Cuentos' },
  { name: 'Hada', category: 'Cuentos' },
  { name: 'Mago', category: 'Cuentos' },
  { name: 'Hombre Lobo', category: 'Cuentos' },
  { name: 'Vampiro', category: 'Cuentos' },
  { name: 'Fantasma', category: 'Cuentos' },
  { name: 'Enano', category: 'Cuentos' },
  { name: 'Elfo', category: 'Cuentos' },
  { name: 'Trol', category: 'Cuentos' },
  { name: 'Duende', category: 'Cuentos' },
  { name: 'Fenix', category: 'Cuentos' },
  { name: 'Pegaso', category: 'Cuentos' },
  { name: 'Medusa', category: 'Cuentos' },
  { name: 'Minotauro', category: 'Cuentos' },
  { name: 'Zeus', category: 'Cuentos' },
  { name: 'Hercules', category: 'Cuentos' },
  { name: 'Poseidon', category: 'Cuentos' },
  { name: 'Atenea', category: 'Cuentos' },

  // Nuevos Famosos (30+)
  { name: 'Greta Thunberg', category: 'Famosos' },
  { name: 'Keanu Reeves', category: 'Famosos' },
  { name: 'Will Smith', category: 'Famosos' },
  { name: 'Scarlett Johansson', category: 'Famosos' },
  { name: 'Dwayne Johnson', category: 'Famosos' },
  { name: 'Zendaya', category: 'Famosos' },
  { name: 'Robert Downey Jr.', category: 'Famosos' },
  { name: 'Tom Holland', category: 'Famosos' },
  { name: 'Margot Robbie', category: 'Famosos' },
  { name: 'Chris Hemsworth', category: 'Famosos' },
  { name: 'Jennifer Lawrence', category: 'Famosos' },
  { name: 'Ryan Gosling', category: 'Famosos' },
  { name: 'Post Malone', category: 'Famosos' },
  { name: 'Lewis Hamilton', category: 'Famosos' },
  { name: 'Serena Williams', category: 'Famosos' },
  { name: 'Roger Federer', category: 'Famosos' },
  { name: 'Sandra Bullock', category: 'Famosos' },
  { name: 'Morgan Freeman', category: 'Famosos' },
  { name: 'Mahatma Gandhi', category: 'Famosos' },
  { name: 'Martin Luther King', category: 'Famosos' },
  { name: 'Walt Disney', category: 'Famosos' },
  { name: 'Nikola Tesla', category: 'Famosos' },
  { name: 'Stephen Hawking', category: 'Famosos' },
  { name: 'Simon Bolivar', category: 'Famosos' },
  { name: 'Che Guevara', category: 'Famosos' },
  { name: 'Salvador Dali', category: 'Famosos' },
  { name: 'Celia Cruz', category: 'Famosos' },
  { name: 'Pele', category: 'Famosos' },
  { name: 'Jorge Luis Borges', category: 'Famosos' },
  { name: 'Isabel Allende', category: 'Famosos' },
  { name: 'Javier Bardem', category: 'Famosos' },

  // Nuevos Animales (30+)
  { name: 'Axolotl', category: 'Animales' },
  { name: 'Narval', category: 'Animales' },
  { name: 'Llama', category: 'Animales' },
  { name: 'Alpaca', category: 'Animales' },
  { name: 'Nutria', category: 'Animales' },
  { name: 'Foca', category: 'Animales' },
  { name: 'Manati', category: 'Animales' },
  { name: 'Wombat', category: 'Animales' },
  { name: 'Ornitorrinco', category: 'Animales' },
  { name: 'Okapi', category: 'Animales' },
  { name: 'Marmota', category: 'Animales' },
  { name: 'Lemur', category: 'Animales' },
  { name: 'Topo', category: 'Animales' },
  { name: 'Pelicano', category: 'Animales' },
  { name: 'Albatros', category: 'Animales' },
  { name: 'Grulla', category: 'Animales' },
  { name: 'Pez globo', category: 'Animales' },
  { name: 'Mantarraya', category: 'Animales' },
  { name: 'Estrella de mar', category: 'Animales' },
  { name: 'Oso hormiguero', category: 'Animales' },
  { name: 'Tapir', category: 'Animales' },
  { name: 'Yak', category: 'Animales' },
  { name: 'Armino', category: 'Animales' },
  { name: 'Lince', category: 'Animales' },
  { name: 'Cuco', category: 'Animales' },
  { name: 'Cangrejo', category: 'Animales' },
  { name: 'Pepino de mar', category: 'Animales' },
  { name: 'Mofeta', category: 'Animales' },
  { name: 'Mapache', category: 'Animales' },
  { name: 'Erizo', category: 'Animales' },
  { name: 'Condor', category: 'Animales' },

  // Nuevas Profesiones (30+)
  { name: 'Influencer', category: 'Profesiones' },
  { name: 'Youtuber', category: 'Profesiones' },
  { name: 'Sommelier', category: 'Profesiones' },
  { name: 'Doble de riesgo', category: 'Profesiones' },
  { name: 'Doblador de voz', category: 'Profesiones' },
  { name: 'Maquillador', category: 'Profesiones' },
  { name: 'Relojero', category: 'Profesiones' },
  { name: 'Orfebre', category: 'Profesiones' },
  { name: 'Maestro cervecero', category: 'Profesiones' },
  { name: 'Controlador aereo', category: 'Profesiones' },
  { name: 'Geologo', category: 'Profesiones' },
  { name: 'Arqueologo', category: 'Profesiones' },
  { name: 'Meteorologo', category: 'Profesiones' },
  { name: 'Matrona', category: 'Profesiones' },
  { name: 'Optico', category: 'Profesiones' },
  { name: 'Pastelero', category: 'Profesiones' },
  { name: 'Notario', category: 'Profesiones' },
  { name: 'Deshollinador', category: 'Profesiones' },
  { name: 'Vidriero', category: 'Profesiones' },
  { name: 'Tejador', category: 'Profesiones' },
  { name: 'Guia de montana', category: 'Profesiones' },
  { name: 'Farero', category: 'Profesiones' },
  { name: 'Titiritero', category: 'Profesiones' },
  { name: 'Gondolero', category: 'Profesiones' },
  { name: 'Comisario de arte', category: 'Profesiones' },
  { name: 'Director de cine', category: 'Profesiones' },
  { name: 'Director de orquesta', category: 'Profesiones' },
  { name: 'Tatuador', category: 'Profesiones' },
  { name: 'Guardia forestal', category: 'Profesiones' },
  { name: 'Critico gastronomico', category: 'Profesiones' },
  { name: 'Lenador', category: 'Profesiones' },

  // Nuevas Peliculas (30+)
  { name: 'Dobby', category: 'Peliculas' },
  { name: 'Dory', category: 'Peliculas' },
  { name: 'Scar', category: 'Peliculas' },
  { name: 'Obi-Wan Kenobi', category: 'Peliculas' },
  { name: 'Princesa Leia', category: 'Peliculas' },
  { name: 'Han Solo', category: 'Peliculas' },
  { name: 'Neo', category: 'Peliculas' },
  { name: 'Loki', category: 'Peliculas' },
  { name: 'Olaf', category: 'Peliculas' },
  { name: 'Baymax', category: 'Peliculas' },
  { name: 'Remy (Ratatouille)', category: 'Peliculas' },
  { name: 'Maui (Moana)', category: 'Peliculas' },
  { name: 'Rayo McQueen', category: 'Peliculas' },
  { name: 'Scooby-Doo', category: 'Peliculas' },
  { name: 'Bob Esponja', category: 'Peliculas' },
  { name: 'Bart Simpson', category: 'Peliculas' },
  { name: 'Homer Simpson', category: 'Peliculas' },
  { name: 'Pippi Calzaslargas', category: 'Peliculas' },
  { name: 'Catwoman', category: 'Peliculas' },
  { name: 'Doctor Strange', category: 'Peliculas' },
  { name: 'Aquaman', category: 'Peliculas' },
  { name: 'Shazam', category: 'Peliculas' },
  { name: 'Gru', category: 'Peliculas' },
  { name: 'Optimus Prime', category: 'Peliculas' },
  { name: 'John Wick', category: 'Peliculas' },
  { name: 'Sherlock Holmes', category: 'Peliculas' },
  { name: 'Daenerys Targaryen', category: 'Peliculas' },
  { name: 'Jack Skellington', category: 'Peliculas' },
  { name: 'Willy Wonka', category: 'Peliculas' },
  { name: 'Merlina Addams', category: 'Peliculas' },
  { name: 'El Zorro', category: 'Peliculas' },

  // Nuevos Cuentos (30+)
  { name: 'Krampus', category: 'Cuentos' },
  { name: 'Baba Yaga', category: 'Cuentos' },
  { name: 'Basilisco', category: 'Cuentos' },
  { name: 'Centauro', category: 'Cuentos' },
  { name: 'Esfinge', category: 'Cuentos' },
  { name: 'Ninfa', category: 'Cuentos' },
  { name: 'Grifo', category: 'Cuentos' },
  { name: 'Hidra', category: 'Cuentos' },
  { name: 'Ciclope', category: 'Cuentos' },
  { name: 'Odiseo', category: 'Cuentos' },
  { name: 'Aquiles', category: 'Cuentos' },
  { name: 'Perseo', category: 'Cuentos' },
  { name: 'Afrodita', category: 'Cuentos' },
  { name: 'Ares', category: 'Cuentos' },
  { name: 'Hera', category: 'Cuentos' },
  { name: 'Prometeo', category: 'Cuentos' },
  { name: 'Pandora', category: 'Cuentos' },
  { name: 'Odin', category: 'Cuentos' },
  { name: 'Freya', category: 'Cuentos' },
  { name: 'Fenrir', category: 'Cuentos' },
  { name: 'El Lobo Feroz', category: 'Cuentos' },
  { name: 'El Gato con Botas', category: 'Cuentos' },
  { name: 'El Principe Rana', category: 'Cuentos' },
  { name: 'Ricitos de Oro', category: 'Cuentos' },
  { name: 'La Madrastra Malvada', category: 'Cuentos' },
  { name: 'Pulgarcito', category: 'Cuentos' },
  { name: 'El Principito', category: 'Cuentos' },
  { name: 'Don Quijote', category: 'Cuentos' },
  { name: 'Sancho Panza', category: 'Cuentos' },
  { name: 'La Llorona', category: 'Cuentos' },
  { name: 'El Cuco', category: 'Cuentos' },
];
