export interface WhoAmICharacter {
  name: string;
  category: string;
}

export const WHOAMI_CHARACTERS: WhoAmICharacter[] = [
  // Prominente (45)
  { name: 'Albert Einstein', category: 'Prominente' },
  { name: 'Beyonce', category: 'Prominente' },
  { name: 'Elon Musk', category: 'Prominente' },
  { name: 'Taylor Swift', category: 'Prominente' },
  { name: 'Cristiano Ronaldo', category: 'Prominente' },
  { name: 'Angela Merkel', category: 'Prominente' },
  { name: 'Leonardo DiCaprio', category: 'Prominente' },
  { name: 'Rihanna', category: 'Prominente' },
  { name: 'Michael Jordan', category: 'Prominente' },
  { name: 'Lionel Messi', category: 'Prominente' },
  { name: 'Adele', category: 'Prominente' },
  { name: 'Barack Obama', category: 'Prominente' },
  { name: 'Lady Gaga', category: 'Prominente' },
  { name: 'David Bowie', category: 'Prominente' },
  { name: 'Oprah Winfrey', category: 'Prominente' },
  { name: 'Ed Sheeran', category: 'Prominente' },
  { name: 'Marie Curie', category: 'Prominente' },
  { name: 'Drake', category: 'Prominente' },
  { name: 'Billie Eilish', category: 'Prominente' },
  { name: 'Arnold Schwarzenegger', category: 'Prominente' },
  { name: 'Mozart', category: 'Prominente' },
  { name: 'Beethoven', category: 'Prominente' },
  { name: 'Elvis Presley', category: 'Prominente' },
  { name: 'Michael Jackson', category: 'Prominente' },
  { name: 'Madonna', category: 'Prominente' },
  { name: 'Freddie Mercury', category: 'Prominente' },
  { name: 'Shakira', category: 'Prominente' },
  { name: 'Eminem', category: 'Prominente' },
  { name: 'Dua Lipa', category: 'Prominente' },
  { name: 'Harry Styles', category: 'Prominente' },
  { name: 'Ariana Grande', category: 'Prominente' },
  { name: 'Marilyn Monroe', category: 'Prominente' },
  { name: 'Charlie Chaplin', category: 'Prominente' },
  { name: 'Steve Jobs', category: 'Prominente' },
  { name: 'Mark Zuckerberg', category: 'Prominente' },
  { name: 'Jeff Bezos', category: 'Prominente' },
  { name: 'Bill Gates', category: 'Prominente' },
  { name: 'Queen Elizabeth', category: 'Prominente' },
  { name: 'Nelson Mandela', category: 'Prominente' },
  { name: 'Cleopatra', category: 'Prominente' },
  { name: 'Napoleon', category: 'Prominente' },
  { name: 'Helene Fischer', category: 'Prominente' },
  { name: 'Thomas Mueller', category: 'Prominente' },
  { name: 'Till Schweiger', category: 'Prominente' },
  { name: 'Heidi Klum', category: 'Prominente' },

  // Tiere (40)
  { name: 'Elefant', category: 'Tiere' },
  { name: 'Delfin', category: 'Tiere' },
  { name: 'Adler', category: 'Tiere' },
  { name: 'Loewe', category: 'Tiere' },
  { name: 'Pinguin', category: 'Tiere' },
  { name: 'Gorilla', category: 'Tiere' },
  { name: 'Koala', category: 'Tiere' },
  { name: 'Hai', category: 'Tiere' },
  { name: 'Giraffe', category: 'Tiere' },
  { name: 'Flamingo', category: 'Tiere' },
  { name: 'Papagei', category: 'Tiere' },
  { name: 'Krokodil', category: 'Tiere' },
  { name: 'Wolf', category: 'Tiere' },
  { name: 'Baer', category: 'Tiere' },
  { name: 'Schlange', category: 'Tiere' },
  { name: 'Ameise', category: 'Tiere' },
  { name: 'Kolibri', category: 'Tiere' },
  { name: 'Oktopus', category: 'Tiere' },
  { name: 'Panda', category: 'Tiere' },
  { name: 'Känguru', category: 'Tiere' },
  { name: 'Chamäleon', category: 'Tiere' },
  { name: 'Schildkroete', category: 'Tiere' },
  { name: 'Schmetterling', category: 'Tiere' },
  { name: 'Eule', category: 'Tiere' },
  { name: 'Faultier', category: 'Tiere' },
  { name: 'Pferd', category: 'Tiere' },
  { name: 'Katze', category: 'Tiere' },
  { name: 'Hund', category: 'Tiere' },
  { name: 'Frosch', category: 'Tiere' },
  { name: 'Spinne', category: 'Tiere' },
  { name: 'Biber', category: 'Tiere' },
  { name: 'Nilpferd', category: 'Tiere' },
  { name: 'Nashorn', category: 'Tiere' },
  { name: 'Zebra', category: 'Tiere' },
  { name: 'Tiger', category: 'Tiere' },
  { name: 'Wal', category: 'Tiere' },
  { name: 'Tintenfisch', category: 'Tiere' },
  { name: 'Erdmaennchen', category: 'Tiere' },
  { name: 'Gepard', category: 'Tiere' },
  { name: 'Storch', category: 'Tiere' },

  // Berufe (40)
  { name: 'Astronaut', category: 'Berufe' },
  { name: 'Feuerwehrmann', category: 'Berufe' },
  { name: 'Detektiv', category: 'Berufe' },
  { name: 'Koch', category: 'Berufe' },
  { name: 'Pilot', category: 'Berufe' },
  { name: 'Arzt', category: 'Berufe' },
  { name: 'Lehrer', category: 'Berufe' },
  { name: 'Polizist', category: 'Berufe' },
  { name: 'Anwalt', category: 'Berufe' },
  { name: 'Journalist', category: 'Berufe' },
  { name: 'Architekt', category: 'Berufe' },
  { name: 'Tierarzt', category: 'Berufe' },
  { name: 'Mechaniker', category: 'Berufe' },
  { name: 'Baecker', category: 'Berufe' },
  { name: 'Zahnarzt', category: 'Berufe' },
  { name: 'Bibliothekar', category: 'Berufe' },
  { name: 'Schauspieler', category: 'Berufe' },
  { name: 'Musiker', category: 'Berufe' },
  { name: 'Fotograf', category: 'Berufe' },
  { name: 'Programmierer', category: 'Berufe' },
  { name: 'Richter', category: 'Berufe' },
  { name: 'Kapitaen', category: 'Berufe' },
  { name: 'Taucher', category: 'Berufe' },
  { name: 'Zauberer', category: 'Berufe' },
  { name: 'Apotheker', category: 'Berufe' },
  { name: 'Florist', category: 'Berufe' },
  { name: 'Sporttrainer', category: 'Berufe' },
  { name: 'Busfahrer', category: 'Berufe' },
  { name: 'Maler', category: 'Berufe' },
  { name: 'Schneider', category: 'Berufe' },
  { name: 'Imker', category: 'Berufe' },
  { name: 'Schmied', category: 'Berufe' },
  { name: 'Gaertner', category: 'Berufe' },
  { name: 'Taxifahrer', category: 'Berufe' },
  { name: 'Postbote', category: 'Berufe' },
  { name: 'Kellner', category: 'Berufe' },
  { name: 'Friseur', category: 'Berufe' },
  { name: 'Tischler', category: 'Berufe' },
  { name: 'Rettungssanitaeter', category: 'Berufe' },
  { name: 'DJ', category: 'Berufe' },

  // Filme (40)
  { name: 'Harry Potter', category: 'Filme' },
  { name: 'Darth Vader', category: 'Filme' },
  { name: 'Spider-Man', category: 'Filme' },
  { name: 'Batman', category: 'Filme' },
  { name: 'James Bond', category: 'Filme' },
  { name: 'Shrek', category: 'Filme' },
  { name: 'Elsa (Frozen)', category: 'Filme' },
  { name: 'Iron Man', category: 'Filme' },
  { name: 'Gandalf', category: 'Filme' },
  { name: 'Jack Sparrow', category: 'Filme' },
  { name: 'Yoda', category: 'Filme' },
  { name: 'Simba', category: 'Filme' },
  { name: 'Indiana Jones', category: 'Filme' },
  { name: 'Forrest Gump', category: 'Filme' },
  { name: 'Buzz Lightyear', category: 'Filme' },
  { name: 'Pikachu', category: 'Filme' },
  { name: 'Mario (Super Mario)', category: 'Filme' },
  { name: 'Hermine Granger', category: 'Filme' },
  { name: 'Joker', category: 'Filme' },
  { name: 'Rocky Balboa', category: 'Filme' },
  { name: 'Nemo', category: 'Filme' },
  { name: 'Rapunzel', category: 'Filme' },
  { name: 'Thanos', category: 'Filme' },
  { name: 'Gollum', category: 'Filme' },
  { name: 'Wolverine', category: 'Filme' },
  { name: 'Superman', category: 'Filme' },
  { name: 'Dumbledore', category: 'Filme' },
  { name: 'Thor', category: 'Filme' },
  { name: 'Luke Skywalker', category: 'Filme' },
  { name: 'Wonder Woman', category: 'Filme' },
  { name: 'Black Panther', category: 'Filme' },
  { name: 'Captain America', category: 'Filme' },
  { name: 'Hulk', category: 'Filme' },
  { name: 'Katniss Everdeen', category: 'Filme' },
  { name: 'Deadpool', category: 'Filme' },
  { name: 'Terminator', category: 'Filme' },
  { name: 'E.T.', category: 'Filme' },
  { name: 'Grinch', category: 'Filme' },
  { name: 'Groot', category: 'Filme' },
  { name: 'Minion', category: 'Filme' },

  // Maerchen & Fantasie (40)
  { name: 'Rotkäppchen', category: 'Maerchen' },
  { name: 'Aschenputtel', category: 'Maerchen' },
  { name: 'Schneewittchen', category: 'Maerchen' },
  { name: 'Dornroeschen', category: 'Maerchen' },
  { name: 'Pinocchio', category: 'Maerchen' },
  { name: 'Aladin', category: 'Maerchen' },
  { name: 'Robin Hood', category: 'Maerchen' },
  { name: 'Peter Pan', category: 'Maerchen' },
  { name: 'Dracula', category: 'Maerchen' },
  { name: 'Frankenstein', category: 'Maerchen' },
  { name: 'Weihnachtsmann', category: 'Maerchen' },
  { name: 'Osterhase', category: 'Maerchen' },
  { name: 'Zahnfee', category: 'Maerchen' },
  { name: 'Rapunzel', category: 'Maerchen' },
  { name: 'Haensel', category: 'Maerchen' },
  { name: 'Gretel', category: 'Maerchen' },
  { name: 'Rumpelstilzchen', category: 'Maerchen' },
  { name: 'Dschinn (Flaschengeist)', category: 'Maerchen' },
  { name: 'Meerjungfrau', category: 'Maerchen' },
  { name: 'Einhorn', category: 'Maerchen' },
  { name: 'Drache', category: 'Maerchen' },
  { name: 'Riese', category: 'Maerchen' },
  { name: 'Hexe', category: 'Maerchen' },
  { name: 'Fee', category: 'Maerchen' },
  { name: 'Zauberer', category: 'Maerchen' },
  { name: 'Werwolf', category: 'Maerchen' },
  { name: 'Vampir', category: 'Maerchen' },
  { name: 'Geist', category: 'Maerchen' },
  { name: 'Zwerg', category: 'Maerchen' },
  { name: 'Elf', category: 'Maerchen' },
  { name: 'Troll', category: 'Maerchen' },
  { name: 'Kobold', category: 'Maerchen' },
  { name: 'Phoenix', category: 'Maerchen' },
  { name: 'Pegasus', category: 'Maerchen' },
  { name: 'Medusa', category: 'Maerchen' },
  { name: 'Minotaurus', category: 'Maerchen' },
  { name: 'Zeus', category: 'Maerchen' },
  { name: 'Herkules', category: 'Maerchen' },
  { name: 'Poseidon', category: 'Maerchen' },
  { name: 'Athene', category: 'Maerchen' },

  // Neue Prominente (30+)
  { name: 'Greta Thunberg', category: 'Prominente' },
  { name: 'Keanu Reeves', category: 'Prominente' },
  { name: 'Will Smith', category: 'Prominente' },
  { name: 'Scarlett Johansson', category: 'Prominente' },
  { name: 'Dwayne Johnson', category: 'Prominente' },
  { name: 'Zendaya', category: 'Prominente' },
  { name: 'Robert Downey Jr.', category: 'Prominente' },
  { name: 'Tom Holland', category: 'Prominente' },
  { name: 'Margot Robbie', category: 'Prominente' },
  { name: 'Chris Hemsworth', category: 'Prominente' },
  { name: 'Jennifer Lawrence', category: 'Prominente' },
  { name: 'Ryan Gosling', category: 'Prominente' },
  { name: 'Selena Gomez', category: 'Prominente' },
  { name: 'Bad Bunny', category: 'Prominente' },
  { name: 'Post Malone', category: 'Prominente' },
  { name: 'Kylian Mbappe', category: 'Prominente' },
  { name: 'Lewis Hamilton', category: 'Prominente' },
  { name: 'Serena Williams', category: 'Prominente' },
  { name: 'Roger Federer', category: 'Prominente' },
  { name: 'Juergen Klopp', category: 'Prominente' },
  { name: 'Boris Becker', category: 'Prominente' },
  { name: 'Udo Lindenberg', category: 'Prominente' },
  { name: 'Dieter Bohlen', category: 'Prominente' },
  { name: 'Sandra Bullock', category: 'Prominente' },
  { name: 'Morgan Freeman', category: 'Prominente' },
  { name: 'Mahatma Gandhi', category: 'Prominente' },
  { name: 'Martin Luther King', category: 'Prominente' },
  { name: 'Frida Kahlo', category: 'Prominente' },
  { name: 'Pablo Picasso', category: 'Prominente' },
  { name: 'Walt Disney', category: 'Prominente' },
  { name: 'Nikola Tesla', category: 'Prominente' },
  { name: 'Stephen Hawking', category: 'Prominente' },

  // Neue Tiere (30+)
  { name: 'Axolotl', category: 'Tiere' },
  { name: 'Narwal', category: 'Tiere' },
  { name: 'Lama', category: 'Tiere' },
  { name: 'Alpaka', category: 'Tiere' },
  { name: 'Otter', category: 'Tiere' },
  { name: 'Robbe', category: 'Tiere' },
  { name: 'Seekuh', category: 'Tiere' },
  { name: 'Wombat', category: 'Tiere' },
  { name: 'Schnabeltier', category: 'Tiere' },
  { name: 'Okapi', category: 'Tiere' },
  { name: 'Murmeltier', category: 'Tiere' },
  { name: 'Lemur', category: 'Tiere' },
  { name: 'Maulwurf', category: 'Tiere' },
  { name: 'Pelikan', category: 'Tiere' },
  { name: 'Albatros', category: 'Tiere' },
  { name: 'Kranich', category: 'Tiere' },
  { name: 'Chamäleon', category: 'Tiere' },
  { name: 'Kugelfisch', category: 'Tiere' },
  { name: 'Manta-Rochen', category: 'Tiere' },
  { name: 'Seestern', category: 'Tiere' },
  { name: 'Koralle', category: 'Tiere' },
  { name: 'Ameisenfresser', category: 'Tiere' },
  { name: 'Tapir', category: 'Tiere' },
  { name: 'Yak', category: 'Tiere' },
  { name: 'Hermelin', category: 'Tiere' },
  { name: 'Luchs', category: 'Tiere' },
  { name: 'Kuckuck', category: 'Tiere' },
  { name: 'Krabbe', category: 'Tiere' },
  { name: 'Seegurke', category: 'Tiere' },
  { name: 'Chamäleon', category: 'Tiere' },
  { name: 'Stinktier', category: 'Tiere' },

  // Neue Berufe (30+)
  { name: 'Influencer', category: 'Berufe' },
  { name: 'Youtuber', category: 'Berufe' },
  { name: 'Astronaut', category: 'Berufe' },
  { name: 'Sommelier', category: 'Berufe' },
  { name: 'Stuntman', category: 'Berufe' },
  { name: 'Synchronsprecher', category: 'Berufe' },
  { name: 'Maskenbildner', category: 'Berufe' },
  { name: 'Uhrmacher', category: 'Berufe' },
  { name: 'Goldschmied', category: 'Berufe' },
  { name: 'Braumeister', category: 'Berufe' },
  { name: 'Fluglotse', category: 'Berufe' },
  { name: 'Gerichtsvollzieher', category: 'Berufe' },
  { name: 'Geologe', category: 'Berufe' },
  { name: 'Archäologe', category: 'Berufe' },
  { name: 'Meteorologe', category: 'Berufe' },
  { name: 'Bibliothekar', category: 'Berufe' },
  { name: 'Hebamme', category: 'Berufe' },
  { name: 'Optiker', category: 'Berufe' },
  { name: 'Patissier', category: 'Berufe' },
  { name: 'Notar', category: 'Berufe' },
  { name: 'Schornsteinfeger', category: 'Berufe' },
  { name: 'Glaser', category: 'Berufe' },
  { name: 'Dachdecker', category: 'Berufe' },
  { name: 'Bergfuehrer', category: 'Berufe' },
  { name: 'Leuchtturmwaerter', category: 'Berufe' },
  { name: 'Puppenspieler', category: 'Berufe' },
  { name: 'Gondoliere', category: 'Berufe' },
  { name: 'Floessfahrer', category: 'Berufe' },
  { name: 'Kurator', category: 'Berufe' },
  { name: 'Regisseur', category: 'Berufe' },
  { name: 'Dirigent', category: 'Berufe' },
  { name: 'Tatowierer', category: 'Berufe' },

  // Neue Filme (30+)
  { name: 'Gollum', category: 'Filme' },
  { name: 'Dobby', category: 'Filme' },
  { name: 'Dory', category: 'Filme' },
  { name: 'Scar', category: 'Filme' },
  { name: 'Darth Maul', category: 'Filme' },
  { name: 'Obi-Wan Kenobi', category: 'Filme' },
  { name: 'Princess Leia', category: 'Filme' },
  { name: 'Han Solo', category: 'Filme' },
  { name: 'Neo', category: 'Filme' },
  { name: 'Agent Smith', category: 'Filme' },
  { name: 'Loki', category: 'Filme' },
  { name: 'Olaf', category: 'Filme' },
  { name: 'Baymax', category: 'Filme' },
  { name: 'Remy (Ratatouille)', category: 'Filme' },
  { name: 'Maui (Moana)', category: 'Filme' },
  { name: 'Lightning McQueen', category: 'Filme' },
  { name: 'Scooby-Doo', category: 'Filme' },
  { name: 'SpongeBob', category: 'Filme' },
  { name: 'Bart Simpson', category: 'Filme' },
  { name: 'Homer Simpson', category: 'Filme' },
  { name: 'Pippi Langstrumpf', category: 'Filme' },
  { name: 'Catwoman', category: 'Filme' },
  { name: 'Doctor Strange', category: 'Filme' },
  { name: 'Aquaman', category: 'Filme' },
  { name: 'Shazam', category: 'Filme' },
  { name: 'Gru', category: 'Filme' },
  { name: 'Bumblebee', category: 'Filme' },
  { name: 'Optimus Prime', category: 'Filme' },
  { name: 'John Wick', category: 'Filme' },
  { name: 'Mad Max', category: 'Filme' },
  { name: 'Sherlock Holmes', category: 'Filme' },
  { name: 'Daenerys Targaryen', category: 'Filme' },

  // Neue Maerchen (30+)
  { name: 'Krampus', category: 'Maerchen' },
  { name: 'Baba Jaga', category: 'Maerchen' },
  { name: 'Basilisk', category: 'Maerchen' },
  { name: 'Zentaur', category: 'Maerchen' },
  { name: 'Sphinx', category: 'Maerchen' },
  { name: 'Nymphe', category: 'Maerchen' },
  { name: 'Greif', category: 'Maerchen' },
  { name: 'Hydra', category: 'Maerchen' },
  { name: 'Kyklop', category: 'Maerchen' },
  { name: 'Odysseus', category: 'Maerchen' },
  { name: 'Achilles', category: 'Maerchen' },
  { name: 'Perseus', category: 'Maerchen' },
  { name: 'Aphrodite', category: 'Maerchen' },
  { name: 'Ares', category: 'Maerchen' },
  { name: 'Hera', category: 'Maerchen' },
  { name: 'Prometheus', category: 'Maerchen' },
  { name: 'Pandora', category: 'Maerchen' },
  { name: 'Odin', category: 'Maerchen' },
  { name: 'Freya', category: 'Maerchen' },
  { name: 'Fenrir', category: 'Maerchen' },
  { name: 'Rotkäppchens Wolf', category: 'Maerchen' },
  { name: 'Frau Holle', category: 'Maerchen' },
  { name: 'Froschkoenig', category: 'Maerchen' },
  { name: 'Sterntaler', category: 'Maerchen' },
  { name: 'Schneewittchens Stiefmutter', category: 'Maerchen' },
  { name: 'Struwwelpeter', category: 'Maerchen' },
  { name: 'Max und Moritz', category: 'Maerchen' },
  { name: 'Baron Muenchhausen', category: 'Maerchen' },
  { name: 'Der kleine Prinz', category: 'Maerchen' },
  { name: 'Puck', category: 'Maerchen' },
  { name: 'Titania', category: 'Maerchen' },
];
