export interface WhoAmICharacter {
  name: string;
  category: string;
}

export const WHOAMI_CHARACTERS: WhoAmICharacter[] = [
  // Celebrita (45)
  { name: 'Albert Einstein', category: 'Celebrita' },
  { name: 'Beyonce', category: 'Celebrita' },
  { name: 'Elon Musk', category: 'Celebrita' },
  { name: 'Taylor Swift', category: 'Celebrita' },
  { name: 'Cristiano Ronaldo', category: 'Celebrita' },
  { name: 'Sophia Loren', category: 'Celebrita' },
  { name: 'Leonardo DiCaprio', category: 'Celebrita' },
  { name: 'Rihanna', category: 'Celebrita' },
  { name: 'Michael Jordan', category: 'Celebrita' },
  { name: 'Lionel Messi', category: 'Celebrita' },
  { name: 'Adele', category: 'Celebrita' },
  { name: 'Barack Obama', category: 'Celebrita' },
  { name: 'Lady Gaga', category: 'Celebrita' },
  { name: 'David Bowie', category: 'Celebrita' },
  { name: 'Oprah Winfrey', category: 'Celebrita' },
  { name: 'Ed Sheeran', category: 'Celebrita' },
  { name: 'Marie Curie', category: 'Celebrita' },
  { name: 'Drake', category: 'Celebrita' },
  { name: 'Billie Eilish', category: 'Celebrita' },
  { name: 'Arnold Schwarzenegger', category: 'Celebrita' },
  { name: 'Mozart', category: 'Celebrita' },
  { name: 'Beethoven', category: 'Celebrita' },
  { name: 'Elvis Presley', category: 'Celebrita' },
  { name: 'Michael Jackson', category: 'Celebrita' },
  { name: 'Madonna', category: 'Celebrita' },
  { name: 'Freddie Mercury', category: 'Celebrita' },
  { name: 'Shakira', category: 'Celebrita' },
  { name: 'Andrea Bocelli', category: 'Celebrita' },
  { name: 'Roberto Benigni', category: 'Celebrita' },
  { name: 'Monica Bellucci', category: 'Celebrita' },
  { name: 'Valentino Rossi', category: 'Celebrita' },
  { name: 'Luciano Pavarotti', category: 'Celebrita' },
  { name: 'Maneskin', category: 'Celebrita' },
  { name: 'Laura Pausini', category: 'Celebrita' },
  { name: 'Greta Thunberg', category: 'Celebrita' },
  { name: 'Keanu Reeves', category: 'Celebrita' },
  { name: 'Will Smith', category: 'Celebrita' },
  { name: 'Zendaya', category: 'Celebrita' },
  { name: 'Robert Downey Jr.', category: 'Celebrita' },
  { name: 'Tom Holland', category: 'Celebrita' },
  { name: 'Margot Robbie', category: 'Celebrita' },
  { name: 'Leonardo da Vinci', category: 'Celebrita' },
  { name: 'Galileo Galilei', category: 'Celebrita' },
  { name: 'Dante Alighieri', category: 'Celebrita' },
  { name: 'Giuseppe Verdi', category: 'Celebrita' },
  // Animali (40)
  { name: 'Elefante', category: 'Animali' },
  { name: 'Delfino', category: 'Animali' },
  { name: 'Aquila', category: 'Animali' },
  { name: 'Leone', category: 'Animali' },
  { name: 'Pinguino', category: 'Animali' },
  { name: 'Gorilla', category: 'Animali' },
  { name: 'Koala', category: 'Animali' },
  { name: 'Squalo', category: 'Animali' },
  { name: 'Giraffa', category: 'Animali' },
  { name: 'Fenicottero', category: 'Animali' },
  { name: 'Pappagallo', category: 'Animali' },
  { name: 'Coccodrillo', category: 'Animali' },
  { name: 'Lupo', category: 'Animali' },
  { name: 'Orso', category: 'Animali' },
  { name: 'Serpente', category: 'Animali' },
  { name: 'Formica', category: 'Animali' },
  { name: 'Colibri', category: 'Animali' },
  { name: 'Polpo', category: 'Animali' },
  { name: 'Panda', category: 'Animali' },
  { name: 'Canguro', category: 'Animali' },
  { name: 'Camaleonte', category: 'Animali' },
  { name: 'Tartaruga', category: 'Animali' },
  { name: 'Farfalla', category: 'Animali' },
  { name: 'Gufo', category: 'Animali' },
  { name: 'Bradipo', category: 'Animali' },
  { name: 'Cavallo', category: 'Animali' },
  { name: 'Gatto', category: 'Animali' },
  { name: 'Cane', category: 'Animali' },
  { name: 'Rana', category: 'Animali' },
  { name: 'Ragno', category: 'Animali' },
  { name: 'Castoro', category: 'Animali' },
  { name: 'Ippopotamo', category: 'Animali' },
  { name: 'Rinoceronte', category: 'Animali' },
  { name: 'Zebra', category: 'Animali' },
  { name: 'Tigre', category: 'Animali' },
  { name: 'Balena', category: 'Animali' },
  { name: 'Suricato', category: 'Animali' },
  { name: 'Ghepardo', category: 'Animali' },
  { name: 'Cicogna', category: 'Animali' },
  { name: 'Axolotl', category: 'Animali' },
  // Professioni (40)
  { name: 'Astronauta', category: 'Professioni' },
  { name: 'Vigile del fuoco', category: 'Professioni' },
  { name: 'Detective', category: 'Professioni' },
  { name: 'Cuoco', category: 'Professioni' },
  { name: 'Pilota', category: 'Professioni' },
  { name: 'Medico', category: 'Professioni' },
  { name: 'Insegnante', category: 'Professioni' },
  { name: 'Poliziotto', category: 'Professioni' },
  { name: 'Avvocato', category: 'Professioni' },
  { name: 'Giornalista', category: 'Professioni' },
  { name: 'Architetto', category: 'Professioni' },
  { name: 'Veterinario', category: 'Professioni' },
  { name: 'Meccanico', category: 'Professioni' },
  { name: 'Panettiere', category: 'Professioni' },
  { name: 'Dentista', category: 'Professioni' },
  { name: 'Bibliotecario', category: 'Professioni' },
  { name: 'Attore', category: 'Professioni' },
  { name: 'Musicista', category: 'Professioni' },
  { name: 'Fotografo', category: 'Professioni' },
  { name: 'Programmatore', category: 'Professioni' },
  { name: 'Giudice', category: 'Professioni' },
  { name: 'Capitano', category: 'Professioni' },
  { name: 'Subacqueo', category: 'Professioni' },
  { name: 'Mago', category: 'Professioni' },
  { name: 'Farmacista', category: 'Professioni' },
  { name: 'Fiorista', category: 'Professioni' },
  { name: 'Allenatore', category: 'Professioni' },
  { name: 'Autista', category: 'Professioni' },
  { name: 'Pittore', category: 'Professioni' },
  { name: 'Sarto', category: 'Professioni' },
  { name: 'Apicoltore', category: 'Professioni' },
  { name: 'Fabbro', category: 'Professioni' },
  { name: 'Giardiniere', category: 'Professioni' },
  { name: 'Tassista', category: 'Professioni' },
  { name: 'Postino', category: 'Professioni' },
  { name: 'Cameriere', category: 'Professioni' },
  { name: 'Parrucchiere', category: 'Professioni' },
  { name: 'Falegname', category: 'Professioni' },
  { name: 'Paramedico', category: 'Professioni' },
  { name: 'DJ', category: 'Professioni' },
  // Film (40)
  { name: 'Harry Potter', category: 'Film' },
  { name: 'Darth Vader', category: 'Film' },
  { name: 'Spider-Man', category: 'Film' },
  { name: 'Batman', category: 'Film' },
  { name: 'James Bond', category: 'Film' },
  { name: 'Shrek', category: 'Film' },
  { name: 'Elsa (Frozen)', category: 'Film' },
  { name: 'Iron Man', category: 'Film' },
  { name: 'Gandalf', category: 'Film' },
  { name: 'Jack Sparrow', category: 'Film' },
  { name: 'Yoda', category: 'Film' },
  { name: 'Simba', category: 'Film' },
  { name: 'Indiana Jones', category: 'Film' },
  { name: 'Forrest Gump', category: 'Film' },
  { name: 'Buzz Lightyear', category: 'Film' },
  { name: 'Pikachu', category: 'Film' },
  { name: 'Mario (Super Mario)', category: 'Film' },
  { name: 'Hermione Granger', category: 'Film' },
  { name: 'Joker', category: 'Film' },
  { name: 'Rocky Balboa', category: 'Film' },
  { name: 'Nemo', category: 'Film' },
  { name: 'Rapunzel', category: 'Film' },
  { name: 'Thanos', category: 'Film' },
  { name: 'Gollum', category: 'Film' },
  { name: 'Wolverine', category: 'Film' },
  { name: 'Superman', category: 'Film' },
  { name: 'Silente', category: 'Film' },
  { name: 'Thor', category: 'Film' },
  { name: 'Luke Skywalker', category: 'Film' },
  { name: 'Wonder Woman', category: 'Film' },
  { name: 'Black Panther', category: 'Film' },
  { name: 'Capitan America', category: 'Film' },
  { name: 'Hulk', category: 'Film' },
  { name: 'Katniss Everdeen', category: 'Film' },
  { name: 'Deadpool', category: 'Film' },
  { name: 'Terminator', category: 'Film' },
  { name: 'E.T.', category: 'Film' },
  { name: 'Grinch', category: 'Film' },
  { name: 'Groot', category: 'Film' },
  { name: 'Minion', category: 'Film' },
  // Fiabe e Fantasia (40)
  { name: 'Cappuccetto Rosso', category: 'Fiabe' },
  { name: 'Cenerentola', category: 'Fiabe' },
  { name: 'Biancaneve', category: 'Fiabe' },
  { name: 'La Bella Addormentata', category: 'Fiabe' },
  { name: 'Pinocchio', category: 'Fiabe' },
  { name: 'Aladino', category: 'Fiabe' },
  { name: 'Robin Hood', category: 'Fiabe' },
  { name: 'Peter Pan', category: 'Fiabe' },
  { name: 'Dracula', category: 'Fiabe' },
  { name: 'Frankenstein', category: 'Fiabe' },
  { name: 'Babbo Natale', category: 'Fiabe' },
  { name: 'Coniglio di Pasqua', category: 'Fiabe' },
  { name: 'Fatina dei denti', category: 'Fiabe' },
  { name: 'Raperonzolo', category: 'Fiabe' },
  { name: 'Hansel', category: 'Fiabe' },
  { name: 'Gretel', category: 'Fiabe' },
  { name: 'Tremotino', category: 'Fiabe' },
  { name: 'Genio della lampada', category: 'Fiabe' },
  { name: 'Sirena', category: 'Fiabe' },
  { name: 'Unicorno', category: 'Fiabe' },
  { name: 'Drago', category: 'Fiabe' },
  { name: 'Gigante', category: 'Fiabe' },
  { name: 'Strega', category: 'Fiabe' },
  { name: 'Fata', category: 'Fiabe' },
  { name: 'Mago', category: 'Fiabe' },
  { name: 'Lupo mannaro', category: 'Fiabe' },
  { name: 'Vampiro', category: 'Fiabe' },
  { name: 'Fantasma', category: 'Fiabe' },
  { name: 'Nano', category: 'Fiabe' },
  { name: 'Elfo', category: 'Fiabe' },
  { name: 'Troll', category: 'Fiabe' },
  { name: 'Folletto', category: 'Fiabe' },
  { name: 'Fenice', category: 'Fiabe' },
  { name: 'Pegaso', category: 'Fiabe' },
  { name: 'Medusa', category: 'Fiabe' },
  { name: 'Minotauro', category: 'Fiabe' },
  { name: 'Zeus', category: 'Fiabe' },
  { name: 'Ercole', category: 'Fiabe' },
  { name: 'Poseidone', category: 'Fiabe' },
  { name: 'Atena', category: 'Fiabe' },
  { name: 'Totò', category: 'Celebrita' },
  { name: 'Alberto Sordi', category: 'Celebrita' },
  { name: 'Marcello Mastroianni', category: 'Celebrita' },
  { name: 'Federico Fellini', category: 'Celebrita' },
  { name: 'Giulia Bevilacqua', category: 'Celebrita' },
  { name: 'Vasco Rossi', category: 'Celebrita' },
  { name: 'Eros Ramazzotti', category: 'Celebrita' },
  { name: 'Zucchero', category: 'Celebrita' },
  { name: 'Lucio Battisti', category: 'Celebrita' },
  { name: 'Fabrizio De André', category: 'Celebrita' },
  { name: 'Mina', category: 'Celebrita' },
  { name: 'Adriano Celentano', category: 'Celebrita' },
  { name: 'Giorgio Armani', category: 'Celebrita' },
  { name: 'Gianni Versace', category: 'Celebrita' },
  { name: 'Donatella Versace', category: 'Celebrita' },
  { name: 'Miuccia Prada', category: 'Celebrita' },
  { name: 'Roberto Cavalli', category: 'Celebrita' },
  { name: 'Chiara Ferragni', category: 'Celebrita' },
  { name: 'Fedez', category: 'Celebrita' },
  { name: 'Tiziano Ferro', category: 'Celebrita' },
  { name: 'Jovanotti', category: 'Celebrita' },
  { name: 'Gianna Nannini', category: 'Celebrita' },
  { name: 'Renzo Piano', category: 'Celebrita' },
  { name: 'Umberto Eco', category: 'Celebrita' },
  { name: 'Italo Calvino', category: 'Celebrita' },
  { name: 'Alessandro Manzoni', category: 'Celebrita' },
  { name: 'Giuseppe Garibaldi', category: 'Celebrita' },
  { name: 'Cristoforo Colombo', category: 'Celebrita' },
  { name: 'Marco Polo', category: 'Celebrita' },
  { name: 'Michelangelo', category: 'Celebrita' },
  { name: 'Raffaello', category: 'Celebrita' },
  { name: 'Caravaggio', category: 'Celebrita' },
  { name: 'Sandro Botticelli', category: 'Celebrita' },
  { name: 'Gianni Rivera', category: 'Celebrita' },
  { name: 'Paolo Maldini', category: 'Celebrita' },
  { name: 'Francesco Totti', category: 'Celebrita' },
  { name: 'Roberto Baggio', category: 'Celebrita' },
  { name: 'Gianluigi Buffon', category: 'Celebrita' },
  { name: 'Alessandro Del Piero', category: 'Celebrita' },
  { name: 'Marco Tardelli', category: 'Celebrita' },
  { name: 'Federica Pellegrini', category: 'Celebrita' },
  { name: 'Jannik Sinner', category: 'Celebrita' },
  { name: 'Marco Pantani', category: 'Celebrita' },
  { name: 'Tazio Nuvolari', category: 'Celebrita' },
  { name: 'Enzo Ferrari', category: 'Celebrita' },
  { name: 'Maria Montessori', category: 'Celebrita' },
  { name: 'Rita Levi-Montalcini', category: 'Celebrita' },
  { name: 'Guglielmo Marconi', category: 'Celebrita' },
  { name: 'Alessandro Volta', category: 'Celebrita' },
  { name: 'Enrico Fermi', category: 'Celebrita' },
  { name: 'Sofia Goggia', category: 'Celebrita' },
  { name: 'Bebe Vio', category: 'Celebrita' },
  { name: 'Pierfrancesco Favino', category: 'Celebrita' },
  { name: 'Toni Servillo', category: 'Celebrita' },
  { name: 'Paolo Sorrentino', category: 'Celebrita' },
  { name: 'Roberto Saviano', category: 'Celebrita' },
  { name: 'Carlo Conti', category: 'Celebrita' },
  { name: 'Amadeus', category: 'Celebrita' },
  { name: 'Maria De Filippi', category: 'Celebrita' },
  { name: 'Gerry Scotti', category: 'Celebrita' },
  { name: 'Fiorello', category: 'Celebrita' },
  { name: 'Checco Zalone', category: 'Celebrita' },
  { name: 'Sergio Mattarella', category: 'Celebrita' },
  { name: 'Volpe', category: 'Animali' },
  { name: 'Riccio', category: 'Animali' },
  { name: 'Scoiattolo', category: 'Animali' },
  { name: 'Cervo', category: 'Animali' },
  { name: 'Cinghiale', category: 'Animali' },
  { name: 'Pipistrello', category: 'Animali' },
  { name: 'Talpa', category: 'Animali' },
  { name: 'Lontra', category: 'Animali' },
  { name: 'Foca', category: 'Animali' },
  { name: 'Tricheco', category: 'Animali' },
  { name: 'Orca', category: 'Animali' },
  { name: 'Granchio', category: 'Animali' },
  { name: 'Aragosta', category: 'Animali' },
  { name: 'Cavalluccio marino', category: 'Animali' },
  { name: 'Stella marina', category: 'Animali' },
  { name: 'Lumaca', category: 'Animali' },
  { name: 'Ape', category: 'Animali' },
  { name: 'Coccinella', category: 'Animali' },
  { name: 'Libellula', category: 'Animali' },
  { name: 'Grillo', category: 'Animali' },
  { name: 'Cavalletta', category: 'Animali' },
  { name: 'Scorpione', category: 'Animali' },
  { name: 'Mantide', category: 'Animali' },
  { name: 'Pavone', category: 'Animali' },
  { name: 'Cigno', category: 'Animali' },
  { name: 'Anatra', category: 'Animali' },
  { name: 'Oca', category: 'Animali' },
  { name: 'Gallo', category: 'Animali' },
  { name: 'Gallina', category: 'Animali' },
  { name: 'Tacchino', category: 'Animali' },
  { name: 'Pecora', category: 'Animali' },
  { name: 'Capra', category: 'Animali' },
  { name: 'Mucca', category: 'Animali' },
  { name: 'Maiale', category: 'Animali' },
  { name: 'Asino', category: 'Animali' },
  { name: 'Coniglio', category: 'Animali' },
  { name: 'Criceto', category: 'Animali' },
  { name: 'Furetto', category: 'Animali' },
  { name: 'Procione', category: 'Animali' },
  { name: 'Lince', category: 'Animali' },
  { name: 'Leopardo', category: 'Animali' },
  { name: 'Giaguaro', category: 'Animali' },
  { name: 'Puma', category: 'Animali' },
  { name: 'Iena', category: 'Animali' },
  { name: 'Cammello', category: 'Animali' },
  { name: 'Lama', category: 'Animali' },
  { name: 'Alpaca', category: 'Animali' },
  { name: 'Tucano', category: 'Animali' },
  { name: 'Notaio', category: 'Professioni' },
  { name: 'Ingegnere', category: 'Professioni' },
  { name: 'Contadino', category: 'Professioni' },
  { name: 'Pescatore', category: 'Professioni' },
  { name: 'Macellaio', category: 'Professioni' },
  { name: 'Pasticcere', category: 'Professioni' },
  { name: 'Pizzaiolo', category: 'Professioni' },
  { name: 'Barista', category: 'Professioni' },
  { name: 'Cassiere', category: 'Professioni' },
  { name: 'Commesso', category: 'Professioni' },
  { name: 'Infermiere', category: 'Professioni' },
  { name: 'Chirurgo', category: 'Professioni' },
  { name: 'Psicologo', category: 'Professioni' },
  { name: 'Idraulico', category: 'Professioni' },
  { name: 'Elettricista', category: 'Professioni' },
  { name: 'Muratore', category: 'Professioni' },
  { name: 'Imbianchino', category: 'Professioni' },
  { name: 'Scultore', category: 'Professioni' },
  { name: 'Ballerino', category: 'Professioni' },
  { name: 'Cantante', category: 'Professioni' },
  { name: 'Scrittore', category: 'Professioni' },
  { name: 'Stilista', category: 'Professioni' },
  { name: 'Arbitro', category: 'Professioni' },
  { name: 'Calciatore', category: 'Professioni' },
  { name: 'Marinaio', category: 'Professioni' },
  { name: 'Soldato', category: 'Professioni' },
  { name: 'Contabile', category: 'Professioni' },
  { name: 'Gondoliere', category: 'Professioni' },
  { name: 'Scommelier', category: 'Professioni' },
  { name: 'Spazzino', category: 'Professioni' },
  { name: 'Il Padrino', category: 'Film' },
  { name: 'Don Vito Corleone', category: 'Film' },
  { name: 'Rocky Horror', category: 'Film' },
  { name: 'Maximus (Il Gladiatore)', category: 'Film' },
  { name: 'Neo (Matrix)', category: 'Film' },
  { name: 'Jack Dawson (Titanic)', category: 'Film' },
  { name: 'Rose (Titanic)', category: 'Film' },
  { name: 'Hannibal Lecter', category: 'Film' },
  { name: 'Willy Wonka', category: 'Film' },
  { name: 'Mary Poppins', category: 'Film' },
  { name: 'Marty McFly', category: 'Film' },
  { name: 'Capitan Jack (Star Wars)', category: 'Film' },
  { name: 'John Rambo', category: 'Film' },
  { name: 'Pulcinella', category: 'Fiabe' },
  { name: 'Arlecchino', category: 'Fiabe' },
  { name: 'Colombina', category: 'Fiabe' },
  { name: 'Pantalone', category: 'Fiabe' },
  { name: 'La Befana', category: 'Fiabe' },
  { name: 'Il Gatto con gli Stivali', category: 'Fiabe' },
  { name: 'Pollicino', category: 'Fiabe' },
  { name: 'La Sirenetta', category: 'Fiabe' },
];
