export interface WhoAmICharacter {
  name: string;
  category: string;
}

export const WHOAMI_CHARACTERS_NL: WhoAmICharacter[] = [
  // Beroemdheden (45)
  { name: 'Albert Einstein', category: 'Beroemdheden' },
  { name: 'Beyonce', category: 'Beroemdheden' },
  { name: 'Elon Musk', category: 'Beroemdheden' },
  { name: 'Taylor Swift', category: 'Beroemdheden' },
  { name: 'Cristiano Ronaldo', category: 'Beroemdheden' },
  { name: 'Max Verstappen', category: 'Beroemdheden' },
  { name: 'Leonardo DiCaprio', category: 'Beroemdheden' },
  { name: 'Rihanna', category: 'Beroemdheden' },
  { name: 'Michael Jordan', category: 'Beroemdheden' },
  { name: 'Lionel Messi', category: 'Beroemdheden' },
  { name: 'Adele', category: 'Beroemdheden' },
  { name: 'Barack Obama', category: 'Beroemdheden' },
  { name: 'Lady Gaga', category: 'Beroemdheden' },
  { name: 'David Bowie', category: 'Beroemdheden' },
  { name: 'Oprah Winfrey', category: 'Beroemdheden' },
  { name: 'Ed Sheeran', category: 'Beroemdheden' },
  { name: 'Marie Curie', category: 'Beroemdheden' },
  { name: 'Drake', category: 'Beroemdheden' },
  { name: 'Billie Eilish', category: 'Beroemdheden' },
  { name: 'Arnold Schwarzenegger', category: 'Beroemdheden' },
  { name: 'Mozart', category: 'Beroemdheden' },
  { name: 'Beethoven', category: 'Beroemdheden' },
  { name: 'Elvis Presley', category: 'Beroemdheden' },
  { name: 'Michael Jackson', category: 'Beroemdheden' },
  { name: 'Madonna', category: 'Beroemdheden' },
  { name: 'Freddie Mercury', category: 'Beroemdheden' },
  { name: 'Shakira', category: 'Beroemdheden' },
  { name: 'Vincent van Gogh', category: 'Beroemdheden' },
  { name: 'Rembrandt', category: 'Beroemdheden' },
  { name: 'Anne Frank', category: 'Beroemdheden' },
  { name: 'Johan Cruijff', category: 'Beroemdheden' },
  { name: 'Martin Garrix', category: 'Beroemdheden' },
  { name: 'Tiesto', category: 'Beroemdheden' },
  { name: 'Andre Hazes', category: 'Beroemdheden' },
  { name: 'Greta Thunberg', category: 'Beroemdheden' },
  { name: 'Keanu Reeves', category: 'Beroemdheden' },
  { name: 'Will Smith', category: 'Beroemdheden' },
  { name: 'Zendaya', category: 'Beroemdheden' },
  { name: 'Robert Downey Jr.', category: 'Beroemdheden' },
  { name: 'Tom Holland', category: 'Beroemdheden' },
  { name: 'Margot Robbie', category: 'Beroemdheden' },
  { name: 'Willem-Alexander', category: 'Beroemdheden' },
  { name: 'Koningin Maxima', category: 'Beroemdheden' },
  { name: 'Marco Borsato', category: 'Beroemdheden' },
  { name: 'Davina Michelle', category: 'Beroemdheden' },
  // Dieren (40)
  { name: 'Olifant', category: 'Dieren' },
  { name: 'Dolfijn', category: 'Dieren' },
  { name: 'Arend', category: 'Dieren' },
  { name: 'Leeuw', category: 'Dieren' },
  { name: 'Pinguin', category: 'Dieren' },
  { name: 'Gorilla', category: 'Dieren' },
  { name: 'Koala', category: 'Dieren' },
  { name: 'Haai', category: 'Dieren' },
  { name: 'Giraffe', category: 'Dieren' },
  { name: 'Flamingo', category: 'Dieren' },
  { name: 'Papegaai', category: 'Dieren' },
  { name: 'Krokodil', category: 'Dieren' },
  { name: 'Wolf', category: 'Dieren' },
  { name: 'Beer', category: 'Dieren' },
  { name: 'Slang', category: 'Dieren' },
  { name: 'Mier', category: 'Dieren' },
  { name: 'Kolibrie', category: 'Dieren' },
  { name: 'Octopus', category: 'Dieren' },
  { name: 'Panda', category: 'Dieren' },
  { name: 'Kangoeroe', category: 'Dieren' },
  { name: 'Kameleon', category: 'Dieren' },
  { name: 'Schildpad', category: 'Dieren' },
  { name: 'Vlinder', category: 'Dieren' },
  { name: 'Uil', category: 'Dieren' },
  { name: 'Luiaard', category: 'Dieren' },
  { name: 'Paard', category: 'Dieren' },
  { name: 'Kat', category: 'Dieren' },
  { name: 'Hond', category: 'Dieren' },
  { name: 'Kikker', category: 'Dieren' },
  { name: 'Spin', category: 'Dieren' },
  { name: 'Bever', category: 'Dieren' },
  { name: 'Nijlpaard', category: 'Dieren' },
  { name: 'Neushoorn', category: 'Dieren' },
  { name: 'Zebra', category: 'Dieren' },
  { name: 'Tijger', category: 'Dieren' },
  { name: 'Walvis', category: 'Dieren' },
  { name: 'Stokstaartje', category: 'Dieren' },
  { name: 'Jachtluipaard', category: 'Dieren' },
  { name: 'Ooievaar', category: 'Dieren' },
  { name: 'Axolotl', category: 'Dieren' },
  // Beroepen (40)
  { name: 'Astronaut', category: 'Beroepen' },
  { name: 'Brandweerman', category: 'Beroepen' },
  { name: 'Detective', category: 'Beroepen' },
  { name: 'Kok', category: 'Beroepen' },
  { name: 'Piloot', category: 'Beroepen' },
  { name: 'Arts', category: 'Beroepen' },
  { name: 'Leraar', category: 'Beroepen' },
  { name: 'Politieagent', category: 'Beroepen' },
  { name: 'Advocaat', category: 'Beroepen' },
  { name: 'Journalist', category: 'Beroepen' },
  { name: 'Architect', category: 'Beroepen' },
  { name: 'Dierenarts', category: 'Beroepen' },
  { name: 'Monteur', category: 'Beroepen' },
  { name: 'Bakker', category: 'Beroepen' },
  { name: 'Tandarts', category: 'Beroepen' },
  { name: 'Bibliothecaris', category: 'Beroepen' },
  { name: 'Acteur', category: 'Beroepen' },
  { name: 'Muzikant', category: 'Beroepen' },
  { name: 'Fotograaf', category: 'Beroepen' },
  { name: 'Programmeur', category: 'Beroepen' },
  { name: 'Rechter', category: 'Beroepen' },
  { name: 'Kapitein', category: 'Beroepen' },
  { name: 'Duiker', category: 'Beroepen' },
  { name: 'Goochelaar', category: 'Beroepen' },
  { name: 'Apotheker', category: 'Beroepen' },
  { name: 'Bloemist', category: 'Beroepen' },
  { name: 'Sporttrainer', category: 'Beroepen' },
  { name: 'Buschauffeur', category: 'Beroepen' },
  { name: 'Schilder', category: 'Beroepen' },
  { name: 'Kleermaker', category: 'Beroepen' },
  { name: 'Imker', category: 'Beroepen' },
  { name: 'Smid', category: 'Beroepen' },
  { name: 'Tuinman', category: 'Beroepen' },
  { name: 'Taxichauffeur', category: 'Beroepen' },
  { name: 'Postbode', category: 'Beroepen' },
  { name: 'Ober', category: 'Beroepen' },
  { name: 'Kapper', category: 'Beroepen' },
  { name: 'Timmerman', category: 'Beroepen' },
  { name: 'Ambulancebroeder', category: 'Beroepen' },
  { name: 'DJ', category: 'Beroepen' },
  // Films (40)
  { name: 'Harry Potter', category: 'Films' },
  { name: 'Darth Vader', category: 'Films' },
  { name: 'Spider-Man', category: 'Films' },
  { name: 'Batman', category: 'Films' },
  { name: 'James Bond', category: 'Films' },
  { name: 'Shrek', category: 'Films' },
  { name: 'Elsa (Frozen)', category: 'Films' },
  { name: 'Iron Man', category: 'Films' },
  { name: 'Gandalf', category: 'Films' },
  { name: 'Jack Sparrow', category: 'Films' },
  { name: 'Yoda', category: 'Films' },
  { name: 'Simba', category: 'Films' },
  { name: 'Indiana Jones', category: 'Films' },
  { name: 'Forrest Gump', category: 'Films' },
  { name: 'Buzz Lightyear', category: 'Films' },
  { name: 'Pikachu', category: 'Films' },
  { name: 'Mario (Super Mario)', category: 'Films' },
  { name: 'Hermelien Griffel', category: 'Films' },
  { name: 'Joker', category: 'Films' },
  { name: 'Rocky Balboa', category: 'Films' },
  { name: 'Nemo', category: 'Films' },
  { name: 'Rapunzel', category: 'Films' },
  { name: 'Thanos', category: 'Films' },
  { name: 'Gollum', category: 'Films' },
  { name: 'Wolverine', category: 'Films' },
  { name: 'Superman', category: 'Films' },
  { name: 'Perkamentus', category: 'Films' },
  { name: 'Thor', category: 'Films' },
  { name: 'Luke Skywalker', category: 'Films' },
  { name: 'Wonder Woman', category: 'Films' },
  { name: 'Black Panther', category: 'Films' },
  { name: 'Captain America', category: 'Films' },
  { name: 'Hulk', category: 'Films' },
  { name: 'Katniss Everdeen', category: 'Films' },
  { name: 'Deadpool', category: 'Films' },
  { name: 'Terminator', category: 'Films' },
  { name: 'E.T.', category: 'Films' },
  { name: 'De Grinch', category: 'Films' },
  { name: 'Groot', category: 'Films' },
  { name: 'Minion', category: 'Films' },
  // Sprookjes en Fantasie (40)
  { name: 'Roodkapje', category: 'Sprookjes' },
  { name: 'Assepoester', category: 'Sprookjes' },
  { name: 'Sneeuwwitje', category: 'Sprookjes' },
  { name: 'Doornroosje', category: 'Sprookjes' },
  { name: 'Pinokkio', category: 'Sprookjes' },
  { name: 'Aladdin', category: 'Sprookjes' },
  { name: 'Robin Hood', category: 'Sprookjes' },
  { name: 'Peter Pan', category: 'Sprookjes' },
  { name: 'Dracula', category: 'Sprookjes' },
  { name: 'Frankenstein', category: 'Sprookjes' },
  { name: 'Kerstman', category: 'Sprookjes' },
  { name: 'Paashaas', category: 'Sprookjes' },
  { name: 'Tandenfee', category: 'Sprookjes' },
  { name: 'Rapunzel', category: 'Sprookjes' },
  { name: 'Hans', category: 'Sprookjes' },
  { name: 'Grietje', category: 'Sprookjes' },
  { name: 'Repelsteeltje', category: 'Sprookjes' },
  { name: 'Geest uit de lamp', category: 'Sprookjes' },
  { name: 'Zeemeermin', category: 'Sprookjes' },
  { name: 'Eenhoorn', category: 'Sprookjes' },
  { name: 'Draak', category: 'Sprookjes' },
  { name: 'Reus', category: 'Sprookjes' },
  { name: 'Heks', category: 'Sprookjes' },
  { name: 'Fee', category: 'Sprookjes' },
  { name: 'Tovenaar', category: 'Sprookjes' },
  { name: 'Weerwolf', category: 'Sprookjes' },
  { name: 'Vampier', category: 'Sprookjes' },
  { name: 'Spook', category: 'Sprookjes' },
  { name: 'Dwerg', category: 'Sprookjes' },
  { name: 'Elf', category: 'Sprookjes' },
  { name: 'Trol', category: 'Sprookjes' },
  { name: 'Kabouter', category: 'Sprookjes' },
  { name: 'Feniks', category: 'Sprookjes' },
  { name: 'Pegasus', category: 'Sprookjes' },
  { name: 'Medusa', category: 'Sprookjes' },
  { name: 'Minotaurus', category: 'Sprookjes' },
  { name: 'Zeus', category: 'Sprookjes' },
  { name: 'Hercules', category: 'Sprookjes' },
  { name: 'Poseidon', category: 'Sprookjes' },
  { name: 'Athena', category: 'Sprookjes' },
];
