export const STORY_STARTERS: string[] = [
  'Il était une fois, un lundi tout à fait normal, quand...',
  'Personne n\'aurait pensé qu\'aujourd\'hui justement...',
  'Quand l\'horloge sonna minuit, quelque chose d\'inattendu se produisit :',
  'Dans une petite ville au bout du monde vivait...',
  'La lettre arriva sans expéditeur et ne contenait qu\'une phrase :',
  'Tout commença par un bruit étrange dans le réfrigérateur.',
  'Il pleuvait des oursons en gélatine, et personne ne savait pourquoi.',
  'Le nouveau voisin avait un secret qui allait tout changer.',
  'Mon chien me regarda et dit soudainement :',
  'Au grenier, je trouvai une boîte marquée « NE PAS OUVRIR ».',
  'L\'invitation arriva par pigeon voyageur et sentait la cannelle.',
  'Quand je me suis réveillé, un pingouin se tenait à côté de mon lit.',
  'Le supermarché était fermé, alors nous avons dû...',
  'Trois inconnus se retrouvèrent par hasard dans l\'ascenseur et...',
  'Le téléphone sonna. Sur l\'écran s\'afficha : « Tu as 24 heures. »',
  'Le café avait un goût différent aujourd\'hui, et soudain je pouvais...',
  'Quand le dernier invité quitta la fête, nous remarquâmes...',
  'Le GPS dit « Vous êtes arrivé à destination », mais tout ce que je voyais, c\'était...',
  'Dans la salle d\'attente du dentiste, je trouvai un message mystérieux :',
  'Le livreur apporta quelque chose que personne n\'avait commandé :',
  'En pleine réunion, le masque de mon chef tomba — au sens propre.',
  'Le chat ramena quelque chose à la maison qui n\'était définitivement pas normal.',
  'Quand j\'ouvris mon vieux cahier d\'école, un papier en tomba avec...',
  'L\'ascenseur resta coincé entre deux étages, et mon co-passager dit :',
  'À minuit pile, mon téléphone s\'alluma — un message de moi-même.',
  'Les enfants trouvèrent dans le jardin un coffre au trésor qui...',
  'Quand le Wi-Fi tomba en panne, quelque chose d\'incroyable se produisit :',
  'Le chauffeur de taxi se retourna et dit : « Je ne vous emmène pas là-bas. »',
  'Au marché aux puces, je trouvai une lampe — et oui, il y avait un génie dedans.',
  'Le courant coupa, et dans l\'obscurité nous entendîmes...',
  'Mon reflet dans le miroir bougea soudainement différemment de moi.',
  'La dernière page du livre manquait, alors j\'écrivis moi-même :',
  'Mon chien aboya contre le mur — et le mur aboya en retour.',
  'Au bureau des objets trouvés, il y avait un objet qui ne devrait pas exister.',
];

export const STORY_PROMPTS: string[] = [
  'Soudain...',
  'Mais alors...',
  'Personne ne savait que...',
  'Ce que personne ne soupçonnait :',
  'Le lendemain...',
  'En même temps...',
  'Le problème, c\'était que :',
  'Heureusement...',
  'Malheureusement...',
  'Sans prévenir...',
  'Au dernier moment...',
  'Comme par miracle...',
  'Et puis vint le retournement de situation :',
  'Ce qui se passa ensuite était incroyable :',
  'La solution était plus simple que prévu :',
  'Personne n\'aurait cru que...',
  'Au milieu de la nuit...',
  'Surgissant de nulle part...',
  'La vérité, c\'était :',
  'Tout le monde était d\'accord :',
  'À ce moment-là...',
  'Pour couronner le tout...',
  'La seule chose qui manquait encore, c\'était...',
  'À la fin, il s\'avéra que...',
  'Avec un grand fracas...',
  'Pendant que tout le monde dormait...',
  'Le plan était en fait parfait, mais...',
  'Le destin avait d\'autres plans :',
  'Une étrange coïncidence fit que...',
  'Tout à la fin...',
  'C\'est ainsi que...',
  'Et la morale de l\'histoire :',
  'Ce que personne ne savait :',
  'Mais le vrai héros était :',
  'Exactement à ce moment-là...',
  'Derrière le prochain coin...',
  'Tout le monde cria en même temps :',
  'L\'énigme était résolue, mais...',
  'Ce n\'était pas la première fois que...',
  'L\'odeur rappelait...',
  'Juste à temps...',
  'En y regardant de plus près...',
  'Mais personne ne s\'attendait à ce que...',
  'À partir de ce jour...',
  'Il n\'y avait qu\'une seule explication :',
  'La porte s\'ouvrit et derrière se tenait...',
  'Le téléphone sonna pour la troisième fois :',
  'Avec des mains tremblantes...',
  'L\'étranger sourit et dit :',
  'En réalité...',
  'Des années plus tard, on apprit que...',
  'Ça sentait l\'aventure et...',
  'L\'horloge tictaquait fort quand...',
  'Un fort coup à la porte interrompit tout :',
  'La réponse était sous notre nez depuis le début :',
  'Mais ce n\'était que le début...',
  'À la lumière de la lune...',
  'Qui aurait cru que...',
  'C\'était le plus vieux truc du monde :',
  'Tout à coup, tout devint clair :',
  'Et ce fut le moment où tout changea.',
];
