export const STORY_STARTERS: string[] = [
  'Era un lunes completamente normal cuando...',
  'Nadie habria pensado que precisamente hoy...',
  'Cuando el reloj marco la medianoche, paso algo inesperado:',
  'En un pequeno pueblo al borde del mundo vivia...',
  'La carta llego sin remitente y contenia solo una frase:',
  'Todo empezo con un sonido extrano en la nevera.',
  'Llovian ositos de goma, y nadie sabia por que.',
  'El nuevo vecino tenia un secreto que lo cambiaria todo.',
  'Mi perro me miro y de repente dijo:',
  'En el desvan encontre una caja con la etiqueta "NO ABRIR".',
  'La invitacion llego por paloma mensajera y olia a canela.',
  'Cuando me desperte, habia un pinguino al lado de mi cama.',
  'El supermercado estaba cerrado, asi que tuvimos que...',
  'Tres desconocidos se encontraron por casualidad en un ascensor y...',
  'El telefono sono. En la pantalla decia: "Tienes 24 horas."',
  'El cafe sabia diferente hoy, y de repente podia...',
  'Cuando el ultimo invitado se fue de la fiesta, notamos...',
  'El GPS dijo "Ha llegado a su destino", pero todo lo que vi fue...',
  'En la sala de espera del dentista encontre un mensaje misterioso:',
  'El repartidor trajo algo que nadie habia pedido:',
  'En medio de la reunion, la mascara de mi jefe se cayo — literalmente.',
  'El gato trajo algo a casa que definitivamente no era normal.',
  'Cuando abri mi viejo cuaderno del colegio, cayo una nota con...',
  'El ascensor se quedo atrapado entre dos pisos, y mi companero dijo:',
  'A medianoche exacta, mi telefono se ilumino — un mensaje de mi mismo.',
  'Los ninos encontraron un cofre del tesoro en el jardin que...',
  'Cuando se fue el wifi, paso algo increible:',
  'El taxista se dio la vuelta y dijo: "Ahi no le llevo."',
  'En el mercadillo encontre una lampara — y si, habia un genio dentro.',
  'Se fue la luz, y en la oscuridad escuchamos...',
  'Mi reflejo en el espejo de repente se movio de forma diferente a mi.',
  'Faltaba la ultima pagina del libro, asi que escribi la mia:',
  'Mi perro ladro a la pared — y la pared le ladro de vuelta.',
  'En la oficina de objetos perdidos habia un objeto que no deberia existir.',
];

export const STORY_PROMPTS: string[] = [
  'De repente...',
  'Pero entonces...',
  'Nadie sabia que...',
  'Lo que nadie sospechaba:',
  'Al dia siguiente...',
  'Al mismo tiempo...',
  'El unico problema era:',
  'Por suerte...',
  'Desafortunadamente...',
  'Sin previo aviso...',
  'En el ultimo momento...',
  'Como por milagro...',
  'Y entonces llego el giro argumental:',
  'Lo que paso despues fue increible:',
  'La solucion era mas sencilla de lo esperado:',
  'Nadie hubiera esperado que...',
  'En mitad de la noche...',
  'De la nada...',
  'La verdad era:',
  'Todos estaban de acuerdo:',
  'En ese momento...',
  'Para colmo...',
  'Lo unico que faltaba era...',
  'Al final resulto que...',
  'Con un fuerte estruendo...',
  'Mientras todos dormian...',
  'El plan era perfecto, pero...',
  'El destino tenia otros planes:',
  'Una extrana coincidencia llevo a que...',
  'Al final de todo...',
  'Y asi fue como...',
  'Y la moraleja de la historia:',
  'Lo que nadie sabia:',
  'Pero el verdadero heroe era:',
  'En ese preciso momento...',
  'A la vuelta de la esquina...',
  'Todos gritaron a la vez:',
  'El misterio estaba resuelto, pero...',
  'No era la primera vez que...',
  'El olor recordaba a...',
  'Justo a tiempo...',
  'Si mirabas con mas atencion...',
  'Pero nadie habia contado con que...',
  'Desde ese dia...',
  'Solo habia una explicacion:',
  'La puerta se abrio y detras estaba...',
  'El telefono sono por tercera vez:',
  'Con manos temblorosas...',
  'El desconocido sonrio y dijo:',
  'En realidad...',
  'Anos despues se descubrio que...',
  'Olia a aventura y...',
  'El reloj sonaba fuerte cuando...',
  'Un fuerte golpe lo interrumpio todo:',
  'La respuesta estuvo delante de nosotros todo el tiempo:',
  'Pero eso era solo el principio...',
  'A la luz de la luna...',
  'Quien hubiera pensado que...',
  'Era el truco mas viejo del mundo:',
  'De repente todo quedo claro:',
  'Y ese fue el momento en que todo cambio.',
];
