export const STORY_STARTERS_TR: string[] = [
  'Bir zamanlar tamamen normal bir pazartesi gunu, birden...',
  'Kimse bugun boyle bir seyin olacagini dusunmezdi...',
  'Saat gece yarisi vurdiginda beklenmedik bir sey oldu:',
  'Dunyanin ucundaki kucuk bir kasabada yasayan...',
  'Mektup gondericisiz geldi ve icinde sadece bir cumle vardi:',
  'Her sey buzdolabindan gelen garip bir sesle basladi.',
  'Gokten yumusak seker yagiyordu ve kimse nedenini bilmiyordu.',
  'Yeni komsunun her seyi degistirecek bir sirri vardi.',
  'Kopegim bana bakti ve birden soyle dedi:',
  'Tavan arasinda "ACMA" yazan bir kutu buldum.',
  'Davetiye posta guverciniyle geldi ve tarcin kokuyordu.',
  'Uyandığımda yatagimin yaninda bir penguen duruyordu.',
  'Market kapanmisti, bu yuzden mecburen...',
  'Uc yabanci tesadufen asansorde bulustu ve...',
  'Telefon caldi. Ekranda yaziyordu: "24 saatin var."',
  'Kahve bugun farkli geliyordu ve birden yapabiliyordum...',
  'Son misafir partiyi terk ettiginde fark ettik ki...',
  'Navigasyon "Hedefinize ulastiniz" dedi, ama tek gordugum...',
  'Disci bekleme odasinda gizemli bir mesaj buldum:',
  'Kargocilar kimsenin siparis etmedigi bir sey getirdi:',
  'Toplantiinin ortasinda patronumun maskesi dustu — kelimenin tam anlamiyla.',
  'Kedi eve kesinlikle normal olmayan bir sey getirdi.',
  'Eski okul defterimi actigimda icinden bir kagit dustu:',
  'Asansor iki kat arasinda kaldi ve yanımdaki kisi soyle dedi:',
  'Tam gece yarisi telefonum yandi — kendimden bir mesaj.',
  'Cocuklar bahcede icinde su olan bir hazine sandigi buldu...',
  'WiFi kesildiginde inanilmaz bir sey oldu:',
  'Taksici donup soyle dedi: "Sizi oraya goturmuyorum."',
  'Bit pazarinda bir lamba buldum — ve evet, icinde bir cin vardi.',
  'Elektrik kesildi ve karanlikta duyduk ki...',
  'Aynadaki yansimam birden benden farkli hareket etti.',
  'Kitabin son sayfasi eksikti, ben de kendim yazdim:',
  'Kopegim duvara havladi — ve duvar geri havladi.',
  'Kayip esya biirosunda olmamasi gereken bir nesne vardi.',
];

export const STORY_PROMPTS_TR: string[] = [
  'Birden...',
  'Ama sonra...',
  'Kimse bilmiyordu ki...',
  'Kimsenin tahmin edemedigi:',
  'Ertesi gun...',
  'Ayni anda...',
  'Sorun suydu:',
  'Neyse ki...',
  'Maalesef...',
  'Hicbir uyari olmadan...',
  'Son anda...',
  'Mucize gibi...',
  'Ve sonra plot twist geldi:',
  'Sonra olan inanilmazdi:',
  'Cozum sanildigindan daha basitti:',
  'Kimse beklemezdi ki...',
  'Gecenin ortasinda...',
  'Hicbir yerden...',
  'Gercek suydu:',
  'Herkes hemfikirdi:',
  'O anda...',
  'Ustelik...',
  'Eksik olan tek sey...',
  'Sonunda ortaya cikti ki...',
  'Buyuk bir gurultuyle...',
  'Herkes uyurken...',
  'Plan aslinda mukemmeldi, ama...',
  'Kaderin baska planlari vardi:',
  'Garip bir tesaduf soyle olmasina yol acti...',
  'En sonunda...',
  'Boylece...',
  'Ve hikayenin morali:',
  'Kimsenin bilmedigi:',
  'Ama gercek kahraman suydu:',
  'Tam o anda...',
  'Kosenin arkasinda...',
  'Herkes ayni anda bagrdi:',
  'Bulmaca cozulmustu, ama...',
  'Bu ilk kez degildi...',
  'Koku su hatirlatiyordu...',
  'Tam zamaninda...',
  'Daha yakindan bakarsan...',
  'Ama kimse bunu beklemiyordu:',
  'O gunden itibaren...',
  'Tek bir aciklama vardi:',
  'Kapi acildi ve arkasinda duruyordu...',
  'Telefon ucuncu kez caldi:',
  'Titreyen ellerle...',
  'Yabanci gulumsedi ve soyle dedi:',
  'Aslinda...',
  'Yillar sonra ogrenildi ki...',
  'Macera ve su kokuyordu...',
  'Saat yuksek sesle tiklerken...',
  'Guclü bir kapı vurusu her seyi yarida kesti:',
  'Cevap hep burnumuzun dibindeydi:',
  'Ama bu daha baslangicti...',
  'Ayin isiginda...',
  'Kim dusunurdu ki...',
  'Dunyanin en eski oyunuydu:',
  'Birden her sey netlesti:',
  'Ve bu her seyin degistigi andi.',
];
