export const STORY_STARTERS_NL: string[] = [
  'Er was eens op een doodgewone maandag, toen...',
  'Niemand had gedacht dat uitgerekend vandaag...',
  'Toen de klok middernacht sloeg, gebeurde er iets onverwachts:',
  'In een klein stadje aan de rand van de wereld woonde...',
  'De brief kwam zonder afzender en bevatte slechts een zin:',
  'Alles begon met een vreemd geluid in de koelkast.',
  'Het regende gummiberen, en niemand wist waarom.',
  'De nieuwe buurman had een geheim dat alles zou veranderen.',
  'Mijn hond keek me aan en zei plotseling:',
  'Op zolder vond ik een kist met het opschrift "NIET OPENEN".',
  'De uitnodiging kwam per postduif en rook naar kaneel.',
  'Toen ik wakker werd, stond er een pinguin naast mijn bed.',
  'De supermarkt was dicht, dus moesten we...',
  'Drie vreemden ontmoetten elkaar toevallig in de lift en...',
  'De telefoon ging. Op het scherm stond: "Je hebt 24 uur."',
  'De koffie smaakte vandaag anders, en plotseling kon ik...',
  'Toen de laatste gast het feest verliet, merkten we...',
  'De navigatie zei "U bent op de bestemming aangekomen", maar alles wat ik zag was...',
  'In de wachtkamer van de tandarts vond ik een mysterieus bericht:',
  'De pakketbezorger bracht iets dat niemand had besteld:',
  'Midden in de vergadering viel het masker van mijn baas — letterlijk.',
  'De kat bracht iets mee naar huis dat absoluut niet normaal was.',
  'Toen ik mijn oude schoolschrift opensloeg, viel er een briefje uit met...',
  'De lift bleef steken tussen twee verdiepingen, en mijn medepassagier zei:',
  'Om klokslag middernacht lichtte mijn telefoon op — een bericht van mezelf.',
  'De kinderen vonden in de tuin een schatkist die...',
  'Toen het wifi uitviel, gebeurde er iets ongelooflijks:',
  'De taxichauffeur draaide zich om en zei: "Ik breng u daar niet heen."',
  'Op de vlooienmarkt vond ik een lamp — en ja, er zat een geest in.',
  'De stroom viel uit, en in het donker hoorden we...',
  'Mijn spiegelbeeld bewoog plotseling anders dan ik.',
  'De laatste pagina van het boek ontbrak, dus schreef ik zelf:',
  'Mijn hond blafte tegen de muur — en de muur blafte terug.',
  'Bij het gevonden voorwerpen bureau lag een object dat eigenlijk niet zou mogen bestaan.',
];

export const STORY_PROMPTS_NL: string[] = [
  'Plotseling...',
  'Maar toen...',
  'Niemand wist dat...',
  'Wat niemand vermoedde:',
  'De volgende dag...',
  'Tegelijkertijd...',
  'Het probleem was alleen:',
  'Gelukkig...',
  'Helaas...',
  'Zonder waarschuwing...',
  'Op het laatste moment...',
  'Als door een wonder...',
  'En toen kwam de plot twist:',
  'Wat daarna gebeurde was ongelooflijk:',
  'De oplossing was eenvoudiger dan gedacht:',
  'Niemand had verwacht dat...',
  'Midden in de nacht...',
  'Uit het niets...',
  'De waarheid was:',
  'Iedereen was het erover eens:',
  'Op dat moment...',
  'Bovendien...',
  'Het enige dat nog ontbrak was...',
  'Uiteindelijk bleek dat...',
  'Met een luide knal...',
  'Terwijl iedereen sliep...',
  'Het plan was eigenlijk perfect, maar...',
  'Het lot had andere plannen:',
  'Een vreemd toeval leidde ertoe dat...',
  'Helemaal aan het einde...',
  'Zo kwam het dat...',
  'En de moraal van het verhaal:',
  'Wat niemand wist:',
  'Maar de echte held was:',
  'Precies op dat moment...',
  'Om de hoek...',
  'Iedereen riep tegelijk:',
  'Het raadsel was opgelost, maar...',
  'Het was niet de eerste keer dat...',
  'De geur deed denken aan...',
  'Net op tijd...',
  'Als je beter keek...',
  'Maar niemand had erop gerekend dat...',
  'Vanaf die dag...',
  'Er was maar een verklaring:',
  'De deur ging open en daarachter stond...',
  'De telefoon ging voor de derde keer:',
  'Met trillende handen...',
  'De vreemdeling glimlachte en zei:',
  'In werkelijkheid...',
  'Jaren later kwam men erachter dat...',
  'Het rook naar avontuur en...',
  'De klok tikte luid, toen...',
  'Een hard geklop onderbrak alles:',
  'Het antwoord lag de hele tijd voor onze neus:',
  'Maar dat was nog maar het begin...',
  'In het maanlicht...',
  'Wie had gedacht dat...',
  'Het was de oudste truc ter wereld:',
  'Opeens werd alles duidelijk:',
  'En dat was het moment waarop alles veranderde.',
];
