export const STORY_STARTERS_IT: string[] = [
  'C\'era una volta, in un lunedi del tutto normale, quando...',
  'Nessuno avrebbe mai pensato che proprio oggi...',
  'Quando l\'orologio segno la mezzanotte, accadde qualcosa di inaspettato:',
  'In una piccola citta ai confini del mondo viveva...',
  'La lettera arrivo senza mittente e conteneva una sola frase:',
  'Tutto comincio con uno strano rumore nel frigorifero.',
  'Piovevano caramelle gommose, e nessuno sapeva il perche.',
  'Il nuovo vicino aveva un segreto che avrebbe cambiato tutto.',
  'Il mio cane mi guardo e all\'improvviso disse:',
  'In soffitta trovai una cassa con la scritta "NON APRIRE".',
  'L\'invito arrivo tramite piccione viaggiatore e profumava di cannella.',
  'Quando mi svegliai, c\'era un pinguino accanto al mio letto.',
  'Il supermercato era chiuso, quindi dovemmo...',
  'Tre sconosciuti si incontrarono per caso in ascensore e...',
  'Il telefono squillo. Sul display apparve: "Hai 24 ore."',
  'Il caffe aveva un sapore diverso oggi, e all\'improvviso potevo...',
  'Quando l\'ultimo ospite lascio la festa, ci accorgemmo che...',
  'Il navigatore disse "Siete arrivati a destinazione", ma tutto cio che vedevo era...',
  'Nella sala d\'attesa del dentista trovai un messaggio misterioso:',
  'Il corriere consegno qualcosa che nessuno aveva ordinato:',
  'Nel bel mezzo della riunione, la maschera del mio capo cadde — letteralmente.',
  'Il gatto porto a casa qualcosa che decisamente non era normale.',
  'Quando aprii il mio vecchio quaderno di scuola, cadde un biglietto con...',
  'L\'ascensore si blocco tra due piani, e il mio compagno di viaggio disse:',
  'A mezzanotte in punto il mio telefono si illumino — un messaggio da me stesso.',
  'I bambini trovarono in giardino un forziere che...',
  'Quando cadde il Wi-Fi, accadde qualcosa di incredibile:',
  'Il tassista si giro e disse: "Non la porto li."',
  'Al mercato delle pulci trovai una lampada — e si, dentro c\'era un genio.',
  'Manco la corrente, e nel buio sentimmo...',
  'Il mio riflesso nello specchio all\'improvviso si mosse diversamente da me.',
  'L\'ultima pagina del libro mancava, cosi scrissi io:',
  'Il mio cane abbaio al muro — e il muro abbaio a lui.',
  'All\'ufficio oggetti smarriti c\'era un oggetto che non sarebbe dovuto esistere.',
];

export const STORY_PROMPTS_IT: string[] = [
  'All\'improvviso...',
  'Ma poi...',
  'Nessuno sapeva che...',
  'Quello che nessuno immaginava:',
  'Il giorno dopo...',
  'Allo stesso tempo...',
  'Il problema era solo:',
  'Per fortuna...',
  'Purtroppo...',
  'Senza preavviso...',
  'All\'ultimo momento...',
  'Come per miracolo...',
  'E poi arrivo il colpo di scena:',
  'Quello che accadde dopo fu incredibile:',
  'La soluzione era piu semplice del previsto:',
  'Nessuno si sarebbe aspettato che...',
  'Nel cuore della notte...',
  'Dal nulla...',
  'La verita era:',
  'Tutti erano d\'accordo:',
  'In quel momento...',
  'Per giunta...',
  'L\'unica cosa che mancava era...',
  'Alla fine si scopri che...',
  'Con un forte boato...',
  'Mentre tutti dormivano...',
  'Il piano era perfetto, ma...',
  'Il destino aveva altri piani:',
  'Una strana coincidenza fece si che...',
  'Proprio alla fine...',
  'E cosi accadde che...',
  'E la morale della storia:',
  'Cio che nessuno sapeva:',
  'Ma il vero eroe era:',
  'Esattamente in quel momento...',
  'Dietro l\'angolo...',
  'Tutti gridarono all\'unisono:',
  'L\'enigma era risolto, ma...',
  'Non era la prima volta che...',
  'L\'odore ricordava...',
  'Appena in tempo...',
  'Se si guardava piu attentamente...',
  'Ma nessuno aveva previsto che...',
  'Da quel giorno in poi...',
  'C\'era una sola spiegazione:',
  'La porta si apri e dietro c\'era...',
  'Il telefono squillo per la terza volta:',
  'Con le mani tremanti...',
  'Lo sconosciuto sorrise e disse:',
  'In realta...',
  'Anni dopo si scopri che...',
  'Profumava di avventura e...',
  'L\'orologio ticchettava forte, quando...',
  'Un forte bussare interruppe tutto:',
  'La risposta era sempre stata davanti ai nostri occhi:',
  'Ma quello era solo l\'inizio...',
  'Alla luce della luna...',
  'Chi l\'avrebbe mai detto che...',
  'Era il trucco piu vecchio del mondo:',
  'Di colpo tutto divenne chiaro:',
  'E quello fu il momento in cui tutto cambio.',
];
