export const STORY_STARTERS_PT: string[] = [
  'Era uma vez em uma segunda-feira totalmente normal, quando...',
  'Ninguem imaginava que justamente hoje...',
  'Quando o relogio bateu meia-noite, algo inesperado aconteceu:',
  'Em uma pequena cidade no fim do mundo vivia...',
  'A carta veio sem remetente e continha apenas uma frase:',
  'Tudo comecou com um barulho estranho na geladeira.',
  'Estava chovendo jujubas, e ninguem sabia por que.',
  'O novo vizinho tinha um segredo que mudaria tudo.',
  'Meu cachorro me olhou e de repente disse:',
  'No sotao encontrei uma caixa com a inscricao "NAO ABRA".',
  'O convite chegou por pombo-correio e cheirava a canela.',
  'Quando acordei, havia um pinguim ao lado da minha cama.',
  'O supermercado estava fechado, entao tivemos que...',
  'Tres desconhecidos se encontraram por acaso no elevador e...',
  'O celular tocou. Na tela dizia: "Voce tem 24 horas."',
  'O cafe tinha um gosto diferente hoje, e de repente eu podia...',
  'Quando o ultimo convidado saiu da festa, percebemos...',
  'O GPS disse "Voce chegou ao seu destino", mas tudo que eu via era...',
  'Na sala de espera do dentista encontrei uma mensagem misteriosa:',
  'O entregador trouxe algo que ninguem tinha pedido:',
  'No meio da reuniao, a mascara do meu chefe caiu — literalmente.',
  'O gato trouxe algo para casa que definitivamente nao era normal.',
  'Quando abri meu caderno antigo da escola, caiu um bilhete com...',
  'O elevador parou entre dois andares, e meu companheiro disse:',
  'A meia-noite exata, meu celular acendeu — uma mensagem de mim mesmo.',
  'As criancas encontraram no jardim um bau do tesouro que...',
  'Quando o Wi-Fi caiu, algo inacreditavel aconteceu:',
  'O motorista do taxi se virou e disse: "Nao vou te levar la."',
  'No brechó encontrei uma lampada — e sim, tinha um genio dentro.',
  'A luz acabou, e no escuro ouvimos...',
  'Meu reflexo no espelho de repente se moveu diferente de mim.',
  'A ultima pagina do livro estava faltando, entao eu mesmo escrevi:',
  'Meu cachorro latiu para a parede — e a parede latiu de volta.',
  'No achados e perdidos havia um objeto que nao deveria existir.',
];

export const STORY_PROMPTS_PT: string[] = [
  'De repente...',
  'Mas entao...',
  'Ninguem sabia que...',
  'O que ninguem imaginava:',
  'No dia seguinte...',
  'Ao mesmo tempo...',
  'O problema era:',
  'Por sorte...',
  'Infelizmente...',
  'Sem aviso...',
  'No ultimo momento...',
  'Como por milagre...',
  'E entao veio a reviravolta:',
  'O que aconteceu depois foi inacreditavel:',
  'A solucao era mais simples do que se pensava:',
  'Ninguem esperava que...',
  'No meio da noite...',
  'Do nada...',
  'A verdade era:',
  'Todos concordaram:',
  'Nesse momento...',
  'Para piorar...',
  'A unica coisa que faltava era...',
  'No final descobriu-se que...',
  'Com um estrondo...',
  'Enquanto todos dormiam...',
  'O plano era perfeito, mas...',
  'O destino tinha outros planos:',
  'Uma coincidencia estranha fez com que...',
  'No finalzinho...',
  'Foi assim que...',
  'E a moral da historia:',
  'O que ninguem sabia:',
  'Mas o verdadeiro heroi era:',
  'Exatamente naquele momento...',
  'Atras da proxima esquina...',
  'Todos gritaram ao mesmo tempo:',
  'O enigma foi resolvido, mas...',
  'Nao era a primeira vez que...',
  'O cheiro lembrava...',
  'Bem a tempo...',
  'Se voce olhasse mais de perto...',
  'Mas ninguem contava com isso:',
  'Daquele dia em diante...',
  'So havia uma explicacao:',
  'A porta se abriu e atras dela estava...',
  'O telefone tocou pela terceira vez:',
  'Com as maos tremendo...',
  'O estranho sorriu e disse:',
  'Na verdade...',
  'Anos depois descobriu-se que...',
  'Cheirava a aventura e...',
  'O relogio tiquetaqueava alto, quando...',
  'Uma batida forte interrompeu tudo:',
  'A resposta estava o tempo todo diante do nosso nariz:',
  'Mas isso era so o comeco...',
  'A luz da lua...',
  'Quem diria que...',
  'Era o truque mais antigo do mundo:',
  'De repente tudo ficou claro:',
  'E esse foi o momento em que tudo mudou.',
];
