export const STORY_STARTERS: string[] = [
  'It was a perfectly normal Monday when...',
  'Nobody would have thought that today of all days...',
  'When the clock struck midnight, something unexpected happened:',
  'In a small town at the edge of the world lived...',
  'The letter arrived without a return address and contained only one sentence:',
  'It all started with a strange noise in the refrigerator.',
  'It was raining gummy bears, and nobody knew why.',
  'The new neighbor had a secret that would change everything.',
  'My dog looked at me and suddenly said:',
  'In the attic, I found a box labeled "DO NOT OPEN".',
  'The invitation arrived by carrier pigeon and smelled of cinnamon.',
  'When I woke up, a penguin was standing next to my bed.',
  'The supermarket was closed, so we had to...',
  'Three strangers met by chance in an elevator and...',
  'The phone rang. The display read: "You have 24 hours."',
  'The coffee tasted different today, and suddenly I could...',
  'When the last guest left the party, we noticed...',
  'The GPS said "You have reached your destination," but all I could see was...',
  'In the dentist\'s waiting room, I found a mysterious message:',
  'The delivery driver brought something nobody had ordered:',
  'In the middle of the meeting, my boss\'s mask fell off — literally.',
  'The cat brought something home that was definitely not normal.',
  'When I opened my old school notebook, a note fell out with...',
  'The elevator got stuck between two floors, and my fellow passenger said:',
  'At exactly midnight, my phone lit up — a message from myself.',
  'The kids found a treasure chest in the garden that...',
  'When the WiFi went out, something incredible happened:',
  'The taxi driver turned around and said: "I\'m not taking you there."',
  'At the flea market, I found a lamp — and yes, there was a genie inside.',
  'The power went out, and in the darkness we heard...',
  'My reflection in the mirror suddenly moved differently than I did.',
  'The last page of the book was missing, so I wrote my own:',
  'My dog barked at the wall — and the wall barked back.',
  'At the lost and found office, there was an object that shouldn\'t exist.',
];

export const STORY_PROMPTS: string[] = [
  'Suddenly...',
  'But then...',
  'Nobody knew that...',
  'What no one suspected:',
  'The next day...',
  'At the same time...',
  'The only problem was:',
  'Luckily...',
  'Unfortunately...',
  'Without warning...',
  'At the last moment...',
  'As if by miracle...',
  'And then came the plot twist:',
  'What happened next was unbelievable:',
  'The solution was simpler than expected:',
  'Nobody would have expected that...',
  'In the middle of the night...',
  'Out of nowhere...',
  'The truth was:',
  'Everyone agreed:',
  'In that moment...',
  'To make matters worse...',
  'The only thing missing was...',
  'In the end, it turned out that...',
  'With a loud bang...',
  'While everyone was sleeping...',
  'The plan was actually perfect, but...',
  'Fate had other plans:',
  'A strange coincidence led to...',
  'At the very end...',
  'And so it happened that...',
  'And the moral of the story:',
  'What nobody knew:',
  'But the true hero was:',
  'At that exact moment...',
  'Around the next corner...',
  'Everyone screamed at once:',
  'The mystery was solved, but...',
  'It wasn\'t the first time that...',
  'The smell reminded me of...',
  'Just in time...',
  'If you looked more closely...',
  'But nobody had expected that...',
  'From that day on...',
  'There was only one explanation:',
  'The door opened and behind it stood...',
  'The phone rang for the third time:',
  'With trembling hands...',
  'The stranger smiled and said:',
  'In reality...',
  'Years later, it was discovered that...',
  'It smelled of adventure and...',
  'The clock ticked loudly as...',
  'A loud knock interrupted everything:',
  'The answer was right in front of us the whole time:',
  'But that was just the beginning...',
  'In the light of the moon...',
  'Who would have thought that...',
  'It was the oldest trick in the book:',
  'Suddenly everything became clear:',
  'And that was the moment everything changed.',
];
