export const STORY_STARTERS: string[] = [
  'Es war einmal an einem voellig normalen Montag, als...',
  'Niemand haette gedacht, dass ausgerechnet heute...',
  'Als die Uhr Mitternacht schlug, passierte etwas Unerwartetes:',
  'In einer kleinen Stadt am Rande der Welt lebte...',
  'Der Brief kam ohne Absender und enthielt nur einen Satz:',
  'Alles begann mit einem merkwuerdigen Geraeusch im Kuehlschrank.',
  'Es regnete Gummibaerchen, und niemand wusste warum.',
  'Der neue Nachbar hatte ein Geheimnis, das alle aendern wuerde.',
  'Mein Hund sah mich an und sagte ploetzlich:',
  'Auf dem Dachboden fand ich eine Kiste mit der Aufschrift "NICHT OEFFNEN".',
  'Die Einladung kam per Brieftaube und roch nach Zimt.',
  'Als ich aufwachte, stand ein Pinguin neben meinem Bett.',
  'Der Supermarkt hatte geschlossen, also mussten wir...',
  'Drei Fremde trafen sich zufaellig im Aufzug und...',
  'Das Handy klingelte. Auf dem Display stand: "Du hast 24 Stunden."',
];

export const STORY_PROMPTS: string[] = [
  'Ploetzlich...',
  'Aber dann...',
  'Niemand wusste, dass...',
  'Was niemand ahnte:',
  'Am naechsten Tag...',
  'Gleichzeitig...',
  'Das Problem war nur:',
  'Zum Glueck...',
  'Leider...',
  'Ohne Vorwarnung...',
  'Im letzten Moment...',
  'Wie durch ein Wunder...',
  'Und dann kam der Plot-Twist:',
  'Was danach passierte, war unfassbar:',
  'Die Loesung war einfacher als gedacht:',
  'Keiner haette erwartet, dass...',
  'Mitten in der Nacht...',
  'Aus dem Nichts...',
  'Die Wahrheit war:',
  'Alle waren sich einig:',
  'In diesem Moment...',
  'Zu allem Ueberfluss...',
  'Das Einzige, was noch fehlte, war...',
  'Am Ende stellte sich heraus, dass...',
  'Mit einem lauten Knall...',
  'Waehrend alle schliefen...',
  'Der Plan war eigentlich perfekt, aber...',
  'Das Schicksal hatte andere Plaene:',
  'Ein merkwuerdiger Zufall fuehrte dazu, dass...',
  'Ganz zum Schluss...',
  'So kam es, dass...',
  'Und die Moral von der Geschichte:',
];
