export type BottleCategory = 'spass' | 'party' | 'jga' | 'erwachsene' | 'eisbrecher';
export type CardType = 'frage' | 'aufgabe';
export interface BottleCard { text: string; type: CardType; category: BottleCategory; }
export const CATEGORY_META: Record<BottleCategory, { name: string; emoji: string; color: string }> = {
  spass: { name: 'Diversion', emoji: '😂', color: '#f59e0b' },
  party: { name: 'Fiesta', emoji: '🎉', color: '#ef4444' },
  jga: { name: 'Despedida', emoji: '💍', color: '#ec4899' },
  erwachsene: { name: 'Adultos 18+', emoji: '🔥', color: '#f97316' },
  eisbrecher: { name: 'Rompehielos', emoji: '🧊', color: '#06b6d4' },
};
export const BOTTLE_CARDS: BottleCard[] = [
  { text: 'Cuenta tu momento mas vergonzoso.', type: 'frage', category: 'spass' },
  { text: 'Haz tu mejor imitacion de animal.', type: 'aufgabe', category: 'spass' },
  { text: 'Ensena la foto mas antigua de tu movil.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual fue tu peor cita?', type: 'frage', category: 'spass' },
  { text: 'Imita a una persona famosa — los demas deben adivinar.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es la cosa mas tonta que has comprado?', type: 'frage', category: 'spass' },
  { text: 'Canta el estribillo de tu cancion favorita.', type: 'aufgabe', category: 'spass' },
  { text: 'Ensena tu chat mas gracioso.', type: 'aufgabe', category: 'spass' },
  { text: 'Que apodo tenias de nino?', type: 'frage', category: 'spass' },
  { text: 'Baila 15 segundos sin musica.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es el mensaje mas vergonzoso que enviaste a la persona equivocada?', type: 'frage', category: 'spass' },
  { text: 'Hazte un selfie con la cara mas graciosa y compartelo.', type: 'aufgabe', category: 'spass' },
  { text: 'Cuenta una mentira y los demas deben adivinar si es verdad.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es la cancion mas vergonzosa de tu playlist?', type: 'frage', category: 'spass' },
  { text: 'Habla con un acento inventado durante 1 minuto.', type: 'aufgabe', category: 'spass' },
  { text: 'Que video de YouTube has visto mas veces?', type: 'frage', category: 'spass' },
  { text: 'Intenta no reir durante 30 segundos — los demas pueden intentar todo.', type: 'aufgabe', category: 'spass' },
  { text: 'Que harias si fueras invisible por un dia?', type: 'frage', category: 'spass' },
  { text: 'Intercambia tu foto de perfil con la persona de al lado.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual fue tu mayor fracaso cocinando?', type: 'frage', category: 'spass' },
  { text: 'Haz un moonwalk por la habitacion.', type: 'aufgabe', category: 'spass' },
  { text: 'Que serie has visto en secreto de un tiron?', type: 'frage', category: 'spass' },
  { text: 'Deja que la persona de al lado publique una story en tu Instagram.', type: 'aufgabe', category: 'spass' },
  { text: 'Que es lo mas raro que hay en tu nevera?', type: 'frage', category: 'spass' },
  { text: 'Da un discurso de 30 segundos sobre el papel higienico.', type: 'aufgabe', category: 'spass' },
  { text: 'Que tres cosas te llevarias a una isla desierta?', type: 'frage', category: 'spass' },
  { text: 'Imita el canto de un gallo — lo mas fuerte que puedas.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es tu talento secreto que nadie conoce?', type: 'frage', category: 'spass' },
  { text: 'Camina hacia atras por la habitacion.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual fue el sueno mas extrano que has tenido?', type: 'frage', category: 'spass' },
  { text: 'Bebe un trago con los ojos cerrados.', type: 'aufgabe', category: 'party' },
  { text: 'Intercambia una prenda con tu vecino.', type: 'aufgabe', category: 'party' },
  { text: 'Cual fue la fiesta mas loca a la que fuiste?', type: 'frage', category: 'party' },
  { text: 'Mezcla un nuevo trago con lo que haya — y pruebalo!', type: 'aufgabe', category: 'party' },
  { text: 'Que cancion te hace bailar siempre?', type: 'frage', category: 'party' },
  { text: 'Reta a alguien a un pulso.', type: 'aufgabe', category: 'party' },
  { text: 'Cual fue el momento mas borracho de tu vida?', type: 'frage', category: 'party' },
  { text: 'Bebe cada vez que alguien diga tu nombre — las proximas 3 rondas.', type: 'aufgabe', category: 'party' },
  { text: 'Con quien de la ronda te gustaria pasar la noche?', type: 'frage', category: 'party' },
  { text: 'Haz un baile de TikTok.', type: 'aufgabe', category: 'party' },
  { text: 'Que es lo mas valiente que hiciste en una fiesta?', type: 'frage', category: 'party' },
  { text: 'Las proximas 2 rondas solo puedes susurrar.', type: 'aufgabe', category: 'party' },
  { text: 'Quien de la ronda aguanta menos bebiendo?', type: 'frage', category: 'party' },
  { text: 'Llama a alguien y dile: "Estoy en la mejor fiesta del mundo!"', type: 'aufgabe', category: 'party' },
  { text: 'Cual es tu ritual antes de salir de fiesta?', type: 'frage', category: 'party' },
  { text: 'Reparte 3 tragos a quien quieras.', type: 'aufgabe', category: 'party' },
  { text: 'Cuenta tu experiencia mas vergonzosa en una fiesta.', type: 'frage', category: 'party' },
  { text: 'Haz una conga — todos deben unirse.', type: 'aufgabe', category: 'party' },
  { text: 'Que DJ o artista esta en tu bucket list?', type: 'frage', category: 'party' },
  { text: 'Grabate haciendo beatbox 5 segundos.', type: 'aufgabe', category: 'party' },
  { text: 'Cuenta la historia mas divertida de la novia/novio.', type: 'frage', category: 'jga' },
  { text: 'Llama a una persona al azar y felicitala por la boda.', type: 'aufgabe', category: 'jga' },
  { text: 'Que crees que hara la pareja en 10 anos?', type: 'frage', category: 'jga' },
  { text: 'Envia a la novia/novio un mensaje vergonzoso.', type: 'aufgabe', category: 'jga' },
  { text: 'Cual fue tu primera impresion de la pareja?', type: 'frage', category: 'jga' },
  { text: 'Aprende un paso de baile de boda y ejecutalo.', type: 'aufgabe', category: 'jga' },
  { text: 'Quien lloro mas cuando se anuncio la boda?', type: 'frage', category: 'jga' },
  { text: 'Haz una foto que parezca una sesion de boda.', type: 'aufgabe', category: 'jga' },
  { text: 'Cual es el mejor consejo matrimonial que darias?', type: 'frage', category: 'jga' },
  { text: 'Da un mini discurso de boda.', type: 'aufgabe', category: 'jga' },
  { text: 'Cuenta el recuerdo mas vergonzoso con la novia/novio.', type: 'frage', category: 'jga' },
  { text: 'Invita a un desconocido a la boda.', type: 'aufgabe', category: 'jga' },
  { text: 'Que le regralarias a la pareja como regalo de boda?', type: 'frage', category: 'jga' },
  { text: 'Graba un video de 15 segundos de felicitacion.', type: 'aufgabe', category: 'jga' },
  { text: 'Que cancion describe mejor la relacion de la pareja?', type: 'frage', category: 'jga' },
  { text: 'Encuentra a un desconocido que diga "Si, acepto!" y grabalo.', type: 'aufgabe', category: 'jga' },
  { text: 'Que es lo mas molesto que hace la novia/novio?', type: 'frage', category: 'jga' },
  { text: 'Organiza una foto grupal espontanea.', type: 'aufgabe', category: 'jga' },
  { text: 'Como conto la novia/novio la historia de la propuesta?', type: 'frage', category: 'jga' },
  { text: 'Escribe una profecia matrimonial en una servilleta.', type: 'aufgabe', category: 'jga' },
  { text: 'Describe tu peor beso.', type: 'frage', category: 'erwachsene' },
  { text: 'A quien de la ronda le mandarias un mensaje a las 2 de la manana?', type: 'frage', category: 'erwachsene' },
  { text: 'Cual es la cosa mas atrevida que has hecho?', type: 'frage', category: 'erwachsene' },
  { text: 'Ensena el ultimo chat de flirteo en tu movil.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual es tu mayor turn-off?', type: 'frage', category: 'erwachsene' },
  { text: 'Hazle un cumplido a la persona de al lado que le haga sonrojar.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Que es lo mas seductor que alguien te ha dicho?', type: 'frage', category: 'erwachsene' },
  { text: 'Pon tu mejor cara de flirteo y mantela 10 segundos.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual fue tu cita mas vergonzosa?', type: 'frage', category: 'erwachsene' },
  { text: 'Susurrale algo atrevido a la persona de tu derecha.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Has encontrado atractivo a alguien de esta ronda?', type: 'frage', category: 'erwachsene' },
  { text: 'Envia un mensaje atrevido a alguien — ensenaselo a la ronda.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual es tu crush mas inusual?', type: 'frage', category: 'erwachsene' },
  { text: 'Deja que la persona de enfrente lea un mensaje de tu movil.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Que es lo mas loco que viviste en una fiesta?', type: 'frage', category: 'erwachsene' },
  { text: 'Cuenta la historia de tu primer beso.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Si pudieras salir con un famoso — quien?', type: 'frage', category: 'erwachsene' },
  { text: 'Pon una mirada seductora a la camara y enviala al grupo.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual fue el lugar mas extrano donde besaste a alguien?', type: 'frage', category: 'erwachsene' },
  { text: 'Comparte un secreto que nadie aqui sabe.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual es tu guilty pleasure?', type: 'frage', category: 'eisbrecher' },
  { text: 'Si tuvieras un superpoder, cual seria?', type: 'frage', category: 'eisbrecher' },
  { text: 'Que querias ser de nino?', type: 'frage', category: 'eisbrecher' },
  { text: 'Nombra una cosa de tu bucket list.', type: 'frage', category: 'eisbrecher' },
  { text: 'Que es lo mejor que te ha pasado este ano?', type: 'frage', category: 'eisbrecher' },
  { text: 'Comparte algo que nadie aqui deberia saber.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual es tu plato favorito y por que?', type: 'frage', category: 'eisbrecher' },
  { text: 'Hazle una pregunta personal a la persona de al lado.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Si pudieras vivir en cualquier lugar del mundo, donde seria?', type: 'frage', category: 'eisbrecher' },
  { text: 'Describete en tres palabras.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual fue el ultimo libro o podcast que te inspiro?', type: 'frage', category: 'eisbrecher' },
  { text: 'Dile algo bonito a cada persona del grupo.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual es tu opinion mas impopular?', type: 'frage', category: 'eisbrecher' },
  { text: 'Comparte un recuerdo divertido de la infancia.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Si fueras un animal, cual serias y por que?', type: 'frage', category: 'eisbrecher' },
  { text: 'Ensena al grupo el ultimo meme que enviaste.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual es tu cita o lema favorito?', type: 'frage', category: 'eisbrecher' },
  { text: 'Hazle un cumplido a la persona que menos conozcas.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual fue el mejor viaje que has hecho?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cuenta un momento que cambio tu vida.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Que habilidad te gustaria aprender?', type: 'frage', category: 'eisbrecher' },
  { text: 'Ponle un apodo a la persona de enfrente para toda la noche.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual es tu cancion favorita ahora y por que?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cuenta que fue lo primero que hiciste al despertar hoy.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual fue el mejor consejo que te dieron?', type: 'frage', category: 'eisbrecher' },
  { text: 'Presentate como si fueras un personaje de pelicula.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Que te hace realmente feliz?', type: 'frage', category: 'eisbrecher' },
  { text: 'Nombra tres cosas que tu y la persona de al lado tengan en comun.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Si tuvieras una maquina del tiempo, a donde irias?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cuenta tu mejor experiencia con un desconocido.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Que electrodomestico de tu casa serias y por que?', type: 'frage', category: 'spass' },
  { text: 'Imita como bailan tus padres en una boda.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es la palabra que mas mal pronuncias siempre?', type: 'frage', category: 'spass' },
  { text: 'Habla los proximos 30 segundos como un presentador de telediario.', type: 'aufgabe', category: 'spass' },
  { text: 'Que es lo mas absurdo que has buscado en Google?', type: 'frage', category: 'spass' },
  { text: 'Imita a un gato pidiendo comida durante 15 segundos.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es tu mania mas rara que nadie entiende?', type: 'frage', category: 'spass' },
  { text: 'Inventa un anuncio de teletienda para el objeto mas cercano.', type: 'aufgabe', category: 'spass' },
  { text: 'Que personaje de dibujos animados te describe mejor?', type: 'frage', category: 'spass' },
  { text: 'Recita el alfabeto al reves lo mas rapido que puedas.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es la excusa mas mala que has puesto para faltar al trabajo?', type: 'frage', category: 'spass' },
  { text: 'Pon voz de bebe durante las proximas dos rondas.', type: 'aufgabe', category: 'spass' },
  { text: 'Que comida no soportas aunque a todo el mundo le encante?', type: 'frage', category: 'spass' },
  { text: 'Haz como si estuvieras atrapado en una caja invisible.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es el sonido mas raro que sabes hacer con la boca?', type: 'frage', category: 'spass' },
  { text: 'Describe tu dia de hoy usando solo gestos, sin hablar.', type: 'aufgabe', category: 'spass' },
  { text: 'Que cosa de pequeno te daba un miedo absurdo?', type: 'frage', category: 'spass' },
  { text: 'Canta una cancion infantil con voz de opera.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es el peor corte de pelo que has llevado?', type: 'frage', category: 'spass' },
  { text: 'Haz una pose de yoga imposible y aguantala 10 segundos.', type: 'aufgabe', category: 'spass' },
  { text: 'Que app de tu movil te avergonzaria que vieran?', type: 'frage', category: 'spass' },
  { text: 'Imita a tu profesor mas odiado del colegio.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es el meme que mejor define tu vida?', type: 'frage', category: 'spass' },
  { text: 'Pon cara de poker mientras los demas te cuentan chistes malos.', type: 'aufgabe', category: 'spass' },
  { text: 'Que objeto inutil tienes guardado y no tiras nunca?', type: 'frage', category: 'spass' },
  { text: 'Anda como si fueras un robot sin pilas por la habitacion.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es la serie que finges haber visto pero no?', type: 'frage', category: 'spass' },
  { text: 'Haz tu mejor risa malvada de villano de pelicula.', type: 'aufgabe', category: 'spass' },
  { text: 'Que famoso crees que serias en otra vida?', type: 'frage', category: 'spass' },
  { text: 'Narra como un comentarista de futbol lo que pasa en la sala.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es tu placer culpable de comida basura?', type: 'frage', category: 'spass' },
  { text: 'Imita a una estatua viviente y no te muevas 20 segundos.', type: 'aufgabe', category: 'spass' },
  { text: 'Que cancion no puedes evitar cantar aunque la odies?', type: 'frage', category: 'spass' },
  { text: 'Haz un rap improvisado sobre la persona de tu izquierda.', type: 'aufgabe', category: 'spass' },
  { text: 'Cual es la mentira mas pequena que dices casi a diario?', type: 'frage', category: 'spass' },
  { text: 'Imita cinco emojis distintos con la cara, que los adivinen.', type: 'aufgabe', category: 'spass' },
  { text: 'Que harias con un dia entero sin internet?', type: 'frage', category: 'spass' },
  { text: 'Hazte el dormido y ronca de forma exagerada 10 segundos.', type: 'aufgabe', category: 'spass' },
  { text: 'A quien de la sala invitarias a un afterparty ahora mismo?', type: 'frage', category: 'party' },
  { text: 'Brinda con un discurso epico de 20 segundos antes de beber.', type: 'aufgabe', category: 'party' },
  { text: 'Cual ha sido tu peor resaca y por que?', type: 'frage', category: 'party' },
  { text: 'Elige a alguien para que beba contigo a la de tres.', type: 'aufgabe', category: 'party' },
  { text: 'Que copa o cubata pides siempre en una discoteca?', type: 'frage', category: 'party' },
  { text: 'Inventa un baile de fiesta y que todos lo copien.', type: 'aufgabe', category: 'party' },
  { text: 'Cual es la hora mas tarde que has llegado a casa de fiesta?', type: 'frage', category: 'party' },
  { text: 'Haz un brindis dedicado a la persona mas fiestera de la sala.', type: 'aufgabe', category: 'party' },
  { text: 'Que cancion no puede faltar en tu playlist de previa?', type: 'frage', category: 'party' },
  { text: 'Bebe un trago cada vez que alguien se ria en la proxima ronda.', type: 'aufgabe', category: 'party' },
  { text: 'Cual ha sido tu mayor metedura de pata estando borracho?', type: 'frage', category: 'party' },
  { text: 'Imita como bailas tu despues de tres copas.', type: 'aufgabe', category: 'party' },
  { text: 'Que ciudad tiene la mejor vida nocturna que has vivido?', type: 'frage', category: 'party' },
  { text: 'Reparte dos tragos y elige tu quien los bebe.', type: 'aufgabe', category: 'party' },
  { text: 'Cual es tu chupito favorito y cual no puedes ni oler?', type: 'frage', category: 'party' },
  { text: 'Grita tu frase de fiesta favorita lo mas fuerte que puedas.', type: 'aufgabe', category: 'party' },
  { text: 'Con quien de la sala harias equipo en un beer pong?', type: 'frage', category: 'party' },
  { text: 'Haz un brindis pero solo puedes usar palabras que empiecen por la misma letra.', type: 'aufgabe', category: 'party' },
  { text: 'Cual ha sido la fiesta mas cara a la que has ido?', type: 'frage', category: 'party' },
  { text: 'Elige a alguien y bailad juntos una cancion lenta de forma dramatica.', type: 'aufgabe', category: 'party' },
  { text: 'Que es lo que nunca falta en tu kit de supervivencia de fiesta?', type: 'frage', category: 'party' },
  { text: 'Las proximas dos rondas solo puedes hablar cantando.', type: 'aufgabe', category: 'party' },
  { text: 'Cual ha sido tu mejor noche de fiesta que recuerdes?', type: 'frage', category: 'party' },
  { text: 'Haz una foto de grupo posando como en la portada de un disco.', type: 'aufgabe', category: 'party' },
  { text: 'Que harias si manana ganaras la loteria de golpe?', type: 'frage', category: 'party' },
  { text: 'Inventa un cantico de fiesta y que toda la sala lo repita.', type: 'aufgabe', category: 'party' },
  { text: 'Cual es el sitio mas raro donde te has quedado dormido de fiesta?', type: 'frage', category: 'party' },
  { text: 'Imita a un DJ pinchando durante 15 segundos con efectos de sonido.', type: 'aufgabe', category: 'party' },
  { text: 'Que tres canciones pondrias para animar una fiesta muerta?', type: 'frage', category: 'party' },
  { text: 'Bebe sin usar las manos durante esta ronda.', type: 'aufgabe', category: 'party' },
  { text: 'Cual es tu mayor reto que has cumplido estando de fiesta?', type: 'frage', category: 'party' },
  { text: 'Haz el baile de la persona mas vergonzosa que conozcas.', type: 'aufgabe', category: 'party' },
  { text: 'Que bebida te recuerda a tu primera borrachera?', type: 'frage', category: 'party' },
  { text: 'Elige a dos personas para que se reten en un duelo de miradas.', type: 'aufgabe', category: 'party' },
  { text: 'Cual es tu plan ideal para terminar una noche de fiesta?', type: 'frage', category: 'party' },
  { text: 'Haz como si fueras el camarero y toma nota de la sala con voz pija.', type: 'aufgabe', category: 'party' },
  { text: 'Que es lo mas loco que hiciste para entrar a un sitio?', type: 'frage', category: 'party' },
  { text: 'Que consejo le darias a la novia o novio para la noche de bodas?', type: 'frage', category: 'jga' },
  { text: 'Llama a un familiar de la novia o novio y cuentale un secreto inventado.', type: 'aufgabe', category: 'jga' },
  { text: 'Cual fue el momento mas loco que viviste con la novia o novio?', type: 'frage', category: 'jga' },
  { text: 'Inventa el voto matrimonial mas ridiculo y declamalo.', type: 'aufgabe', category: 'jga' },
  { text: 'Que apuesta harias sobre cuanto durara el banquete de boda?', type: 'frage', category: 'jga' },
  { text: 'Pide a un desconocido que te de un consejo de pareja para la novia o novio.', type: 'aufgabe', category: 'jga' },
  { text: 'Cual crees que sera la primera pelea de casados de la pareja?', type: 'frage', category: 'jga' },
  { text: 'Haz una coreografia sorpresa para el dia de la boda y ensenala.', type: 'aufgabe', category: 'jga' },
  { text: 'Que cancion deberia sonar en el primer baile de la pareja?', type: 'frage', category: 'jga' },
  { text: 'Graba un mensaje de audio gracioso para escuchar en la boda.', type: 'aufgabe', category: 'jga' },
  { text: 'Cual fue tu reaccion cuando supiste que se casaban?', type: 'frage', category: 'jga' },
  { text: 'Brinda por la novia o novio con la anecdota mas embarazosa que sepas.', type: 'aufgabe', category: 'jga' },
  { text: 'Que crees que echara mas de menos la novia o novio de la soltera?', type: 'frage', category: 'jga' },
  { text: 'Convence a un desconocido de que vista a la novia o novio para la boda.', type: 'aufgabe', category: 'jga' },
  { text: 'Cual es el mayor defecto adorable de la novia o novio?', type: 'frage', category: 'jga' },
  { text: 'Escribe en una servilleta tu prediccion de cuantos hijos tendran.', type: 'aufgabe', category: 'jga' },
  { text: 'Que regalo de boda jamas le harias a la pareja?', type: 'frage', category: 'jga' },
  { text: 'Haz un brindis llorando de la emocion de forma teatral.', type: 'aufgabe', category: 'jga' },
  { text: 'Como describirias a la pareja con una sola pelicula?', type: 'frage', category: 'jga' },
  { text: 'Recoge tres numeros de telefono de desconocidos para la novia o novio.', type: 'aufgabe', category: 'jga' },
  { text: 'Cual fue la tonteria mas grande que hicisteis juntos de jovenes?', type: 'frage', category: 'jga' },
  { text: 'Pide a un desconocido que cante el cumpleanos feliz a la novia o novio.', type: 'aufgabe', category: 'jga' },
  { text: 'Que crees que dira la suegra en el discurso de la boda?', type: 'frage', category: 'jga' },
  { text: 'Haz una sesion de fotos improvisada con la novia o novio como modelo.', type: 'aufgabe', category: 'jga' },
  { text: 'Cual es tu mejor recuerdo de viaje con la novia o novio?', type: 'frage', category: 'jga' },
  { text: 'Declara un brindis usando solo refranes sobre el amor.', type: 'aufgabe', category: 'jga' },
  { text: 'Que pondrias en el ramo si pudieras elegir tu?', type: 'frage', category: 'jga' },
  { text: 'Consigue que un desconocido grite Vivan los novios.', type: 'aufgabe', category: 'jga' },
  { text: 'Cual es la cualidad por la que crees que se enamoraron?', type: 'frage', category: 'jga' },
  { text: 'Inventa un baile nupcial absurdo y baila con la novia o novio.', type: 'aufgabe', category: 'jga' },
  { text: 'Que esperas que NO pase en la boda?', type: 'frage', category: 'jga' },
  { text: 'Escribe una carta de tres frases para que la lean el dia de la boda.', type: 'aufgabe', category: 'jga' },
  { text: 'Cual es el mote que le pondrias a la futura suegra?', type: 'frage', category: 'jga' },
  { text: 'Haz un brindis dando las gracias a un objeto al azar de la sala.', type: 'aufgabe', category: 'jga' },
  { text: 'Que hobby de la pareja crees que no sobrevivira al matrimonio?', type: 'frage', category: 'jga' },
  { text: 'Pide a un desconocido que de un consejo de amor en menos de 10 segundos.', type: 'aufgabe', category: 'jga' },
  { text: 'Como imaginas a la pareja celebrando sus bodas de oro?', type: 'frage', category: 'jga' },
  { text: 'Cual es tu mayor fantasia que nunca has confesado?', type: 'frage', category: 'erwachsene' },
  { text: 'Describe al oido de tu derecha tu tipo ideal con todo detalle.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual ha sido el lugar mas atrevido donde lo has hecho?', type: 'frage', category: 'erwachsene' },
  { text: 'Manda un mensaje subido de tono a tu ultimo contacto y ensenalo.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Que es lo que mas te atrae fisicamente de alguien?', type: 'frage', category: 'erwachsene' },
  { text: 'Haz tu mejor baile sensual durante 15 segundos.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual ha sido tu encuentro de una noche mas memorable?', type: 'frage', category: 'erwachsene' },
  { text: 'Susurrale un piropo atrevido a la persona mas atractiva de la sala.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Que prenda de ropa te parece mas sexy en otra persona?', type: 'frage', category: 'erwachsene' },
  { text: 'Imita un gemido convincente sin que de risa.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual es tu mayor curiosidad que te gustaria probar en la cama?', type: 'frage', category: 'erwachsene' },
  { text: 'Pon tu cara mas seductora y mantenla mientras te miran fijamente.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Has tenido alguna vez una aventura prohibida?', type: 'frage', category: 'erwachsene' },
  { text: 'Quitate una prenda de ropa o bebe un chupito, tu eliges.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual es la peor frase para ligar que te han dicho jamas?', type: 'frage', category: 'erwachsene' },
  { text: 'Haz un striptease imaginario quitandote una prenda invisible.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Que parte de tu cuerpo es tu favorita y por que?', type: 'frage', category: 'erwachsene' },
  { text: 'Demuestra como besas usando tu propia mano.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual es el mayor numero de citas que has tenido en una semana?', type: 'frage', category: 'erwachsene' },
  { text: 'Dale un masaje de hombros de 20 segundos a tu vecino de la derecha.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Que es lo mas raro que te ha puesto a tono?', type: 'frage', category: 'erwachsene' },
  { text: 'Describe tu noche perfecta de romance con todo lujo de detalles.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual es el mensaje mas picante que has recibido?', type: 'frage', category: 'erwachsene' },
  { text: 'Elige a alguien de la sala y dale un cumplido fisico atrevido.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Has fingido alguna vez en la cama?', type: 'frage', category: 'erwachsene' },
  { text: 'Imita la cara que pones cuando algo te gusta mucho.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual es tu cita mas desastrosa que acabo fatal?', type: 'frage', category: 'erwachsene' },
  { text: 'Cuenta una fantasia inventada y que adivinen si es real.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Que es lo primero en lo que te fijas de alguien que te gusta?', type: 'frage', category: 'erwachsene' },
  { text: 'Haz un guino sexy a cada persona de la sala, una por una.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual es tu mayor reto pendiente en el terreno romantico?', type: 'frage', category: 'erwachsene' },
  { text: 'Manda un emoji atrevido a alguien de tus contactos y ensena la respuesta.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Con quien de la sala compartirias un viaje romantico?', type: 'frage', category: 'erwachsene' },
  { text: 'Recita un piropo de los antiguos con toda tu pasion.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Cual es la edad a la que tuviste tu primera vez sin decir el numero?', type: 'frage', category: 'erwachsene' },
  { text: 'Elige a alguien para hacer un baile pegado de 10 segundos.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Que es lo mas atrevido que has hecho por amor?', type: 'frage', category: 'erwachsene' },
  { text: 'Cual es tu mayor sueno que aun no le has contado a nadie?', type: 'frage', category: 'eisbrecher' },
  { text: 'Di el nombre de la persona de la sala que mejor te cae a primera vista.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Que harias si tuvieras un ano libre y dinero de sobra?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cuenta como llegaste a conocer al anfitrion de esta reunion.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual es el mejor regalo que te han hecho nunca?', type: 'frage', category: 'eisbrecher' },
  { text: 'Comparte una palabra que defina tu estado de animo de hoy.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Que es lo que mas valoras en una amistad?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cuenta un momento en el que te sentiste muy orgulloso de ti mismo.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Si pudieras cenar con cualquier persona viva, quien seria?', type: 'frage', category: 'eisbrecher' },
  { text: 'Haz un cumplido sincero a la persona que tengas enfrente.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual es tu rincon favorito de tu ciudad?', type: 'frage', category: 'eisbrecher' },
  { text: 'Comparte algo nuevo que hayas aprendido esta semana.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Que cosa pequena te alegra el dia siempre?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cuenta cual es tu tradicion familiar favorita.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Si pudieras cambiar de profesion manana, cual elegirias?', type: 'frage', category: 'eisbrecher' },
  { text: 'Describe a la persona de tu izquierda con tres adjetivos positivos.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual es la decision mas valiente que has tomado en tu vida?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cuenta cual es tu pelicula que puedes ver mil veces sin cansarte.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Que estacion del ano te define mejor y por que?', type: 'frage', category: 'eisbrecher' },
  { text: 'Comparte un objetivo que te gustaria cumplir este ano.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual es tu primer recuerdo de la infancia?', type: 'frage', category: 'eisbrecher' },
  { text: 'Di que tienes en comun con la persona que menos conoces de la sala.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Que persona ha tenido la mayor influencia en tu vida?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cuenta la ultima vez que te reiste a carcajadas.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual seria tu dia perfecto de principio a fin?', type: 'frage', category: 'eisbrecher' },
  { text: 'Comparte una cancion que te transporte a un recuerdo bonito.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Que cosa de tu trabajo o estudios te apasiona de verdad?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cuenta un acto de bondad que hayas recibido de un desconocido.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Si tuvieras que mudarte a otro pais, cual elegirias?', type: 'frage', category: 'eisbrecher' },
  { text: 'Describe en una frase como te gustaria que te recordaran.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual es el mejor consejo que has dado tu a alguien?', type: 'frage', category: 'eisbrecher' },
  { text: 'Comparte cual es tu comida favorita para cuando estas triste.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Que es lo que mas te ilusiona del futuro proximo?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cuenta una afición que tienes y que poca gente conoce.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cual es el lugar mas bonito que has visitado en tu vida?', type: 'frage', category: 'eisbrecher' },
  { text: 'Di a la persona de tu derecha algo que admires de ella.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Que harias diferente si pudieras volver a tus 18 anos?', type: 'frage', category: 'eisbrecher' },
];
