// ---------------------------------------------------------------------------
// Flaschendrehen – Arabic content (150+ cards across 5 categories)
// ---------------------------------------------------------------------------

export type BottleCategory = 'spass' | 'party' | 'jga' | 'erwachsene' | 'eisbrecher';
export type CardType = 'frage' | 'aufgabe';

export interface BottleCard {
  text: string;
  type: CardType;
  category: BottleCategory;
}

export const CATEGORY_META: Record<BottleCategory, { name: string; emoji: string; color: string }> = {
  spass: { name: 'مرح', emoji: '😂', color: '#f59e0b' },
  party: { name: 'حفلة', emoji: '🎉', color: '#ef4444' },
  jga: { name: 'وداع العزوبية', emoji: '💍', color: '#ec4899' },
  erwachsene: { name: 'للبالغين 18+', emoji: '🔥', color: '#f97316' },
  eisbrecher: { name: 'كسر الجليد', emoji: '🧊', color: '#06b6d4' },
};

export const BOTTLE_CARDS: BottleCard[] = [
  // -------------------------------------------------------------------------
  // SPASS (30+)
  // -------------------------------------------------------------------------
  { text: 'احكِ عن أكثر لحظة محرجة في حياتك.', type: 'frage', category: 'spass' },
  { text: 'قلّد أفضل صوت حيوان لديك.', type: 'aufgabe', category: 'spass' },
  { text: 'أرِنا أقدم صورة على هاتفك.', type: 'aufgabe', category: 'spass' },
  { text: 'ما أسوأ موعد غرامي خرجت فيه؟', type: 'frage', category: 'spass' },
  { text: 'قلّد شخصية مشهورة — على الآخرين أن يخمنوا.', type: 'aufgabe', category: 'spass' },
  { text: 'ما أغبى شيء اشتريته على الإطلاق؟', type: 'frage', category: 'spass' },
  { text: 'غنِّ لازمة أغنيتك المفضلة.', type: 'aufgabe', category: 'spass' },
  { text: 'أرِنا أطرف محادثة على هاتفك.', type: 'aufgabe', category: 'spass' },
  { text: 'ما اللقب الذي كان لديك في طفولتك؟', type: 'frage', category: 'spass' },
  { text: 'ارقص لمدة 15 ثانية بدون موسيقى.', type: 'aufgabe', category: 'spass' },
  { text: 'ما أكثر رسالة محرجة أرسلتها للشخص الخطأ؟', type: 'frage', category: 'spass' },
  { text: 'التقط سيلفي بأطرف تعبير وأرسله للمجموعة.', type: 'aufgabe', category: 'spass' },
  { text: 'قل كذبة ودع الآخرين يخمنون إن كانت صحيحة.', type: 'aufgabe', category: 'spass' },
  { text: 'ما أكثر أغنية محرجة في قائمة تشغيلك؟', type: 'frage', category: 'spass' },
  { text: 'تحدث لمدة دقيقة بلهجة مختلقة.', type: 'aufgabe', category: 'spass' },
  { text: 'ما الفيديو الذي شاهدته أكثر على يوتيوب؟', type: 'frage', category: 'spass' },
  { text: 'حاول ألا تضحك لمدة 30 ثانية — الآخرون يمكنهم فعل أي شيء.', type: 'aufgabe', category: 'spass' },
  { text: 'ماذا ستفعل لو كنت غير مرئي ليوم واحد؟', type: 'frage', category: 'spass' },
  { text: 'بدّل صورة ملفك الشخصي مع الشخص الذي على يمينك.', type: 'aufgabe', category: 'spass' },
  { text: 'ما أكبر فشل لك في الطبخ؟', type: 'frage', category: 'spass' },
  { text: 'امشِ مشية القمر عبر الغرفة.', type: 'aufgabe', category: 'spass' },
  { text: 'ما المسلسل الذي شاهدته سراً بالكامل؟', type: 'frage', category: 'spass' },
  { text: 'دع الشخص على يسارك ينشر ستوري على إنستغرامك.', type: 'aufgabe', category: 'spass' },
  { text: 'ما أغرب شيء في ثلاجتك؟', type: 'frage', category: 'spass' },
  { text: 'ألقِ خطاباً لمدة 30 ثانية عن ورق التواليت.', type: 'aufgabe', category: 'spass' },
  { text: 'ما الأشياء الثلاثة التي ستأخذها معك لجزيرة نائية؟', type: 'frage', category: 'spass' },
  { text: 'قلّد صياح الديك — بأعلى صوت ممكن.', type: 'aufgabe', category: 'spass' },
  { text: 'ما موهبتك السرية التي لا يعرفها أحد؟', type: 'frage', category: 'spass' },
  { text: 'امشِ للخلف عبر الغرفة.', type: 'aufgabe', category: 'spass' },
  { text: 'ما أغرب حلم حلمت به على الإطلاق؟', type: 'frage', category: 'spass' },
  { text: 'قم بعمل 10 تمارين قرفصاء واحكِ نكتة في الوقت نفسه.', type: 'aufgabe', category: 'spass' },

  // -------------------------------------------------------------------------
  // PARTY (30+)
  // -------------------------------------------------------------------------
  { text: 'اشرب كأساً وعيناك مغمضتان.', type: 'aufgabe', category: 'party' },
  { text: 'بدّل قطعة ملابس مع جارك.', type: 'aufgabe', category: 'party' },
  { text: 'ما أجنّ حفلة حضرتها على الإطلاق؟', type: 'frage', category: 'party' },
  { text: 'اخلط مشروباً جديداً مما هو متاح — وجرّبه!', type: 'aufgabe', category: 'party' },
  { text: 'ما الأغنية التي تجعلك ترقص دائماً؟', type: 'frage', category: 'party' },
  { text: 'تحدَّ شخصاً في مصارعة الذراع.', type: 'aufgabe', category: 'party' },
  { text: 'ما أكثر لحظة سكراً في حياتك؟', type: 'frage', category: 'party' },
  { text: 'اشرب كلما ذكر أحد اسمك — خلال الجولات الثلاث القادمة.', type: 'aufgabe', category: 'party' },
  { text: 'مع مَن في المجموعة تودّ قضاء المساء أكثر؟', type: 'frage', category: 'party' },
  { text: 'أدِّ رقصة تيك توك.', type: 'aufgabe', category: 'party' },
  { text: 'ما أجرأ شيء فعلته في حفلة على الإطلاق؟', type: 'frage', category: 'party' },
  { text: 'خلال الجولتين القادمتين يمكنك الهمس فقط.', type: 'aufgabe', category: 'party' },
  { text: 'مَن في المجموعة أقل تحملاً للشرب؟', type: 'frage', category: 'party' },
  { text: 'اتصل بشخص وقل: "أنا في أفضل حفلة في العالم!"', type: 'aufgabe', category: 'party' },
  { text: 'ما طقسك قبل الخروج للحفلة؟', type: 'frage', category: 'party' },
  { text: 'وزّع 3 رشفات على أشخاص من اختيارك.', type: 'aufgabe', category: 'party' },
  { text: 'احكِ عن أكثر تجربة محرجة لك في حفلة.', type: 'frage', category: 'party' },
  { text: 'قُد بولونيز عبر الغرفة — الكل يجب أن يشارك.', type: 'aufgabe', category: 'party' },
  { text: 'أي دي جي أو فنان على قائمة أمنياتك؟', type: 'frage', category: 'party' },
  { text: 'صوّر فيديو وأنت تعمل بيت بوكس لمدة 5 ثوانٍ.', type: 'aufgabe', category: 'party' },
  { text: 'ما أفضل وجبة خفيفة للحفلات؟', type: 'frage', category: 'party' },
  { text: 'اشرب من كأس جارك.', type: 'aufgabe', category: 'party' },
  { text: 'مَن ستحجزه دي جي لحفلة أحلامك؟', type: 'frage', category: 'party' },
  { text: 'دع المجموعة تختار أغنية عليك غناؤها.', type: 'aufgabe', category: 'party' },
  { text: 'ما أفضل لحظة في حفلة هذا العام؟', type: 'frage', category: 'party' },
  { text: 'ابنِ هرماً من الأكواب — في 15 ثانية!', type: 'aufgabe', category: 'party' },
  { text: 'مَن في المجموعة سيكون أفضل مقتحم حفلات؟', type: 'frage', category: 'party' },
  { text: 'قف على يديك (أو على الأقل حاول).', type: 'aufgabe', category: 'party' },
  { text: 'ما أفضل مكان لحفلة في مدينتكم؟', type: 'frage', category: 'party' },
  { text: 'ألقِ نخباً للمجموعة كلها — قف أثناء ذلك!', type: 'aufgabe', category: 'party' },
  { text: 'مَن هنا لديه أفضل حركات على حلبة الرقص؟', type: 'frage', category: 'party' },

  // -------------------------------------------------------------------------
  // JGA (30+)
  // -------------------------------------------------------------------------
  { text: 'احكِ أطرف قصة عن العروس/العريس.', type: 'frage', category: 'jga' },
  { text: 'اتصل بشخص عشوائي وهنّئه بالزفاف.', type: 'aufgabe', category: 'jga' },
  { text: 'ماذا تعتقد أن العروسين سيفعلان بعد 10 سنوات؟', type: 'frage', category: 'jga' },
  { text: 'أرسل للعروس/العريس رسالة محرجة.', type: 'aufgabe', category: 'jga' },
  { text: 'ما كان انطباعك الأول عن شريك/ة العروس/العريس؟', type: 'frage', category: 'jga' },
  { text: 'تعلّم حركة رقص زفاف وأدّها.', type: 'aufgabe', category: 'jga' },
  { text: 'مَن بكى أكثر عند إعلان الزواج؟', type: 'frage', category: 'jga' },
  { text: 'التقط صورة تبدو كجلسة تصوير زفاف.', type: 'aufgabe', category: 'jga' },
  { text: 'ما أفضل نصيحة زواج يمكنك تقديمها؟', type: 'frage', category: 'jga' },
  { text: 'ألقِ خطاب زفاف مصغّراً للعروسين.', type: 'aufgabe', category: 'jga' },
  { text: 'احكِ أكثر ذكرى محرجة مشتركة مع العروس/العريس.', type: 'frage', category: 'jga' },
  { text: 'اذهب لشخص غريب وادعُه للزفاف.', type: 'aufgabe', category: 'jga' },
  { text: 'ما الهدية التي ستصنعها للعروسين؟', type: 'frage', category: 'jga' },
  { text: 'صوّر فيديو تهنئة لمدة 15 ثانية.', type: 'aufgabe', category: 'jga' },
  { text: 'أي أغنية تصف علاقة العروسين أفضل وصف؟', type: 'frage', category: 'jga' },
  { text: 'ابحث عن شخص غريب يقول "نعم، أقبل!" وصوّره.', type: 'aufgabe', category: 'jga' },
  { text: 'ما أكثر شيء مزعج يفعله العروس/العريس؟', type: 'frage', category: 'jga' },
  { text: 'نظّم صورة جماعية عفوية مع الجميع.', type: 'aufgabe', category: 'jga' },
  { text: 'كيف روى/ت العروس/العريس قصة الخطوبة؟', type: 'frage', category: 'jga' },
  { text: 'اكتب للعروسين نبوءة زواج على منديل.', type: 'aufgabe', category: 'jga' },
  { text: 'ماذا تتمنى لزواج العروسين؟', type: 'frage', category: 'jga' },
  { text: 'اجمع 5 توقيعات من غرباء على منديل خلال دقيقتين.', type: 'aufgabe', category: 'jga' },
  { text: 'ما أطرف إخفاق للعروس/العريس؟', type: 'frage', category: 'jga' },
  { text: 'غنِّ "Going to the Chapel" أو أغنية زفاف بصوت عالٍ.', type: 'aufgabe', category: 'jga' },
  { text: 'ماذا قال/ت العروس/العريس عندما علمتَ بالخطوبة لأول مرة؟', type: 'frage', category: 'jga' },
  { text: 'التقط صورة مع شخص غريب واكتب عليها "ضيف زفاف".', type: 'aufgabe', category: 'jga' },
  { text: 'مَن يجب ألا يلقي خطاباً في الزفاف بأي حال؟ ولماذا؟', type: 'frage', category: 'jga' },
  { text: 'اطلب من ثلاثة أشخاص نصيحة زواج واكتبها.', type: 'aufgabe', category: 'jga' },
  { text: 'كيف كان/ت العروس/العريس في سنّ المراهقة؟', type: 'frage', category: 'jga' },
  { text: 'تقدّم بطلب زواج — على ركبتيك — أمام المجموعة كلها.', type: 'aufgabe', category: 'jga' },
  { text: 'مَن تعتقد سيبكي أكثر في الزفاف؟', type: 'frage', category: 'jga' },

  // -------------------------------------------------------------------------
  // ERWACHSENE 18+ (30+)
  // -------------------------------------------------------------------------
  { text: 'صِف أسوأ قبلة لك.', type: 'frage', category: 'erwachsene' },
  { text: 'لمَن في المجموعة سترسل رسالة الساعة 2 صباحاً؟', type: 'frage', category: 'erwachsene' },
  { text: 'ما أجرأ شيء فعلته على الإطلاق؟', type: 'frage', category: 'erwachsene' },
  { text: 'أرِ آخر محادثة مغازلة على هاتفك.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أكبر شيء ينفّرك؟', type: 'frage', category: 'erwachsene' },
  { text: 'قل للشخص على يسارك مجاملة تجعله يحمرّ خجلاً.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أكثر شيء مُغوٍ قاله لك أحد؟', type: 'frage', category: 'erwachsene' },
  { text: 'اصنع أفضل "وجه مغازلة" واحتفظ به 10 ثوانٍ.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أكثر تجربة محرجة لك في موعد؟', type: 'frage', category: 'erwachsene' },
  { text: 'اهمس بشيء جريء لأذن الشخص على يمينك.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'هل سبق أن وجدت أحداً في هذه المجموعة جذاباً؟', type: 'frage', category: 'erwachsene' },
  { text: 'أرسل رسالة جريئة لشخص من اختيارك — أرِها للمجموعة.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'مَن أغرب شخص أعجبتَ به؟', type: 'frage', category: 'erwachsene' },
  { text: 'دع الشخص المقابل يقرأ رسالة من هاتفك.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أجنّ شيء حصل لك في حفلة؟', type: 'frage', category: 'erwachsene' },
  { text: 'احكِ قصة قبلتك الأولى.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'لو استطعت الخروج مع شخص مشهور — مَن سيكون؟', type: 'frage', category: 'erwachsene' },
  { text: 'انظر نظرة مُغوية للكاميرا وأرسل الصورة للمجموعة.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أغرب مكان تقابلتَ فيه مع أحد؟', type: 'frage', category: 'erwachsene' },
  { text: 'احكِ سراً لا يعرفه أحد هنا.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما فيلمك المفضل الذي لن تعترف به علناً أبداً؟', type: 'frage', category: 'erwachsene' },
  { text: 'عضّ شفتك وانظر 5 ثوانٍ في عيني الشخص المقابل.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'هل سبق وتجاهلت أحداً فجأة؟ لماذا؟', type: 'frage', category: 'erwachsene' },
  { text: 'أرِ آخر صورة حفظتها في المعرض.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أكثر شيء رومانسي فعله أحد من أجلك؟', type: 'frage', category: 'erwachsene' },
  { text: 'اكتب رسالة جريئة بلا نظر وأرسلها لآخر جهة اتصال.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'مَن هنا هو الأكثر من نوع كاسر القلوب؟', type: 'frage', category: 'erwachsene' },
  { text: 'قم بـ 5 ضغطات وتأوّه بشكل درامي.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ماذا ستفعل لو دخل حبيبك/تك السابق/ة الآن؟', type: 'frage', category: 'erwachsene' },
  { text: 'اجلس في الجولة القادمة على حضن الشخص على يسارك.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أوقح رسالة تلقيتها على الإطلاق؟', type: 'frage', category: 'erwachsene' },

  // -------------------------------------------------------------------------
  // EISBRECHER (30+)
  // -------------------------------------------------------------------------
  { text: 'ما مُتعتك المذنبة؟', type: 'frage', category: 'eisbrecher' },
  { text: 'لو كانت لديك قوة خارقة، ماذا ستكون؟', type: 'frage', category: 'eisbrecher' },
  { text: 'ماذا كنت تريد أن تصبح عندما كنت طفلاً؟', type: 'frage', category: 'eisbrecher' },
  { text: 'اذكر شيئاً واحداً من قائمة أمنياتك.', type: 'frage', category: 'eisbrecher' },
  { text: 'ما أفضل شيء حدث لك هذا العام؟', type: 'frage', category: 'eisbrecher' },
  { text: 'احكِ شيئاً لا يجب أن يعرفه أحد هنا عنك.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما طبقك المفضل ولماذا؟', type: 'frage', category: 'eisbrecher' },
  { text: 'اسأل الشخص على يمينك سؤالاً شخصياً.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'لو استطعت العيش في أي مكان بالعالم، أين سيكون؟', type: 'frage', category: 'eisbrecher' },
  { text: 'صِف نفسك بثلاث كلمات.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما آخر كتاب أو بودكاست أثار حماسك؟', type: 'frage', category: 'eisbrecher' },
  { text: 'قل شيئاً لطيفاً لكل شخص في المجموعة.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما رأيك الأكثر إثارة للجدل؟', type: 'frage', category: 'eisbrecher' },
  { text: 'شارك ذكرى طريفة من طفولتك.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'لو كنت حيواناً، أي حيوان ستكون ولماذا؟', type: 'frage', category: 'eisbrecher' },
  { text: 'أرِ المجموعة آخر ميم أرسلته.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما اقتباسك أو شعارك المفضل؟', type: 'frage', category: 'eisbrecher' },
  { text: 'قل مجاملة للشخص الذي تعرفه أقل.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما أفضل رحلة قمت بها على الإطلاق؟', type: 'frage', category: 'eisbrecher' },
  { text: 'احكِ عن لحظة غيّرت حياتك.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'أي مهارة تودّ تعلّمها؟', type: 'frage', category: 'eisbrecher' },
  { text: 'أعطِ الشخص المقابل لقباً جديداً لهذا المساء.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما أغنيتك المفضلة حالياً ولماذا؟', type: 'frage', category: 'eisbrecher' },
  { text: 'احكِ عن أول شيء فعلته اليوم بعد الاستيقاظ.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما أفضل نصيحة تلقيتها على الإطلاق؟', type: 'frage', category: 'eisbrecher' },
  { text: 'قدّم نفسك كأنك شخصية من فيلم.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما الذي يجعلك سعيداً حقاً؟', type: 'frage', category: 'eisbrecher' },
  { text: 'اذكر ثلاثة أشياء مشتركة بينك وبين الشخص بجانبك.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'لو كانت لديك آلة زمن، إلى أين ستسافر؟', type: 'frage', category: 'eisbrecher' },
  { text: 'احكِ عن أجمل تجربة عشتها مع شخص غريب.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ماذا ستفعل لو ربحت مليون يورو؟', type: 'frage', category: 'eisbrecher' },

  // === بطاقات جديدة: مرح (30) ===
  { text: 'قلّد ميم مشهور — الآخرون يخمنون!', type: 'aufgabe', category: 'spass' },
  { text: 'احكِ أغرب حلم حلمته الأسبوع الماضي.', type: 'frage', category: 'spass' },
  { text: 'اصنع أفضل وجه أوبرا لمدة 10 ثوانٍ.', type: 'aufgabe', category: 'spass' },
  { text: 'ما أكثر شيء محرج قلته في طفولتك؟', type: 'frage', category: 'spass' },
  { text: 'تمشَّ مع كلب غير مرئي — عبر الغرفة كلها.', type: 'aufgabe', category: 'spass' },
  { text: 'أي صوت يجنّنك؟', type: 'frage', category: 'spass' },
  { text: 'حاول التحدث كروبوت لمدة 30 ثانية.', type: 'aufgabe', category: 'spass' },
  { text: 'ما أغرب لقاء حصل لك مع شخص غريب؟', type: 'frage', category: 'spass' },
  { text: 'العب غيتار هوائي على أغنية يدندنها الآخرون!', type: 'aufgabe', category: 'spass' },
  { text: 'أي طعام يبدو فظيعاً لكن طعمه رائع؟', type: 'frage', category: 'spass' },
  { text: 'قف وقدّم نشرة أحوال جوية درامية!', type: 'aufgabe', category: 'spass' },
  { text: 'ماذا ستفعل لو كنت الشخص الوحيد في العالم؟', type: 'frage', category: 'spass' },
  { text: 'حاول ألا ترمش لمدة 20 ثانية!', type: 'aufgabe', category: 'spass' },
  { text: 'لو كانت حياتك فيلماً، ما نوعه؟', type: 'frage', category: 'spass' },
  { text: 'اصنع إعلاناً لأكثر منتج مملّ في العالم!', type: 'aufgabe', category: 'spass' },
  { text: 'ما أسوأ شيء أكلته على الإطلاق؟', type: 'frage', category: 'spass' },
  { text: 'احكِ نكتة — إذا لم يضحك أحد، قم بـ 5 تمارين قرفصاء!', type: 'aufgabe', category: 'spass' },
  { text: 'ما أكثر لحظة محرجة بسبب التصحيح التلقائي على هاتفك؟', type: 'frage', category: 'spass' },
  { text: 'أدِّ خدعة سحرية — حتى لو لم تعرف واحدة!', type: 'aufgabe', category: 'spass' },
  { text: 'ما أطرف شيء حصل لك في العمل؟', type: 'frage', category: 'spass' },
  { text: 'اذهب للنافذة ولوّح بحماس للمارة!', type: 'aufgabe', category: 'spass' },
  { text: 'لو كنت إيموجي — أيّها ستكون؟', type: 'frage', category: 'spass' },
  { text: 'قلّد طعامك المفضل!', type: 'aufgabe', category: 'spass' },
  { text: 'ماذا ستضع في كبسولة زمنية؟', type: 'frage', category: 'spass' },
  { text: 'كن أفضل معلّق رياضي لمدة 30 ثانية!', type: 'aufgabe', category: 'spass' },
  { text: 'ما أجنّ شيء نشرته على وسائل التواصل الاجتماعي؟', type: 'frage', category: 'spass' },
  { text: 'امشِ عبر الغرفة بحركة بطيئة!', type: 'aufgabe', category: 'spass' },
  { text: 'ما أكثر سؤال مزعج يُطرح عليك دائماً؟', type: 'frage', category: 'spass' },
  { text: 'خرخر كالقطة لمدة 15 ثانية!', type: 'aufgabe', category: 'spass' },
  { text: 'لو كنت حيواناً ليوم واحد — ماذا ستفعل؟', type: 'frage', category: 'spass' },

  // === بطاقات جديدة: حفلة (30) ===
  { text: 'خذ رشفة وعيناك مغمضتان — خمّن ما هو!', type: 'aufgabe', category: 'party' },
  { text: 'مَن هنا سينجو أولاً في نهاية عالم الزومبي؟', type: 'frage', category: 'party' },
  { text: 'اخترع كوكتيلاً جديداً مما هو متاح — وسمّه!', type: 'aufgabe', category: 'party' },
  { text: 'ما أفضل أغنية في آخر حفلة حضرتها؟', type: 'frage', category: 'party' },
  { text: 'اعمل بولونيز — الكل يجب أن يشارك!', type: 'aufgabe', category: 'party' },
  { text: 'مَن في المجموعة أفضل راقص/ة؟', type: 'frage', category: 'party' },
  { text: 'ألقِ خطاباً عن حفلة اليوم!', type: 'aufgabe', category: 'party' },
  { text: 'ما أجرأ شيء فعلته في حفلة؟', type: 'frage', category: 'party' },
  { text: 'ارقص 30 ثانية على أغنية يختارها الفريق!', type: 'aufgabe', category: 'party' },
  { text: 'ما حيلتك السرية في الحفلات؟', type: 'frage', category: 'party' },
  { text: 'التقط صورة جماعية — أنت تحدد الوضعية!', type: 'aufgabe', category: 'party' },
  { text: 'مَن في المجموعة لديه أفضل حركات رقص؟', type: 'frage', category: 'party' },
  { text: 'ابدأ موجة — الكل يجب أن يشارك!', type: 'aufgabe', category: 'party' },
  { text: 'ما أجنّ شيء فعلته وأنت ثمل؟', type: 'frage', category: 'party' },
  { text: 'اعمل بيت بوكس لمدة 20 ثانية!', type: 'aufgabe', category: 'party' },
  { text: 'أي أغنية يجب أن تُشغَّل الآن فوراً؟', type: 'frage', category: 'party' },
  { text: 'بدّل إكسسواراً مع الشخص المقابل!', type: 'aufgabe', category: 'party' },
  { text: 'ما أفضل طعام حفلة أكلته على الإطلاق؟', type: 'frage', category: 'party' },
  { text: 'اهمس بسرّ لأذن الشخص على يمينك!', type: 'aufgabe', category: 'party' },
  { text: 'مَن هنا سيقيم أجنّ حفلة عفوية؟', type: 'frage', category: 'party' },
  { text: 'ارفع نخباً — للحياة!', type: 'aufgabe', category: 'party' },
  { text: 'ما أغنيتك المفضلة للكاريوكي؟', type: 'frage', category: 'party' },
  { text: 'تحدَّ شخصاً في مبارزة رقص!', type: 'aufgabe', category: 'party' },
  { text: 'ما أطرف حادثة حفلة عشتها؟', type: 'frage', category: 'party' },
  { text: 'انقر كأسك مع كل شخص — واحداً تلو الآخر!', type: 'aufgabe', category: 'party' },
  { text: 'مَن في المجموعة هو منظّم الحفلات؟', type: 'frage', category: 'party' },
  { text: 'قم بإعلان كالدي جي في النادي!', type: 'aufgabe', category: 'party' },
  { text: 'ما الشيء الذي لا يمكن أن يغيب عن أي حفلة؟', type: 'frage', category: 'party' },
  { text: 'صوّر بوميرانغ مع المجموعة!', type: 'aufgabe', category: 'party' },
  { text: 'ما قاعدة الحفلة التي تحب كسرها أكثر؟', type: 'frage', category: 'party' },

  // === بطاقات جديدة: وداع العزوبية (30) ===
  { text: 'اذكر ثلاثة أشياء لا يستطيع/تستطيع العروس/العريس فعلها!', type: 'frage', category: 'jga' },
  { text: 'التقطوا صورة يقف فيها الجميع كأنهم عروسان!', type: 'aufgabe', category: 'jga' },
  { text: 'ماذا ستقول في خطاب الزفاف عن العروسين؟', type: 'frage', category: 'jga' },
  { text: 'أقنع شخصاً غريباً بالتقاط صورة مع المجموعة!', type: 'aufgabe', category: 'jga' },
  { text: 'ما أطرف صفة في العروس/العريس؟', type: 'frage', category: 'jga' },
  { text: 'غنِّ أغنية حب للعروسين!', type: 'aufgabe', category: 'jga' },
  { text: 'ما أول خلاف بين العروس والعريس؟', type: 'frage', category: 'jga' },
  { text: 'اكتب للعروسين اعتراف حب على منديل!', type: 'aufgabe', category: 'jga' },
  { text: 'مَن يعرف العروس/العريس لأطول فترة؟', type: 'frage', category: 'jga' },
  { text: 'صوّر فيديو تهنئة من شخص غريب!', type: 'aufgabe', category: 'jga' },
  { text: 'ما أكثر لحظة رومانسية للعروسين؟', type: 'frage', category: 'jga' },
  { text: 'اخترع رقصة زفاف — الكل يرقص!', type: 'aufgabe', category: 'jga' },
  { text: 'أي فيلم يصف علاقة العروسين؟', type: 'frage', category: 'jga' },
  { text: 'ابحث عن شيء أزرق وقديم وجديد ومستعار!', type: 'aufgabe', category: 'jga' },
  { text: 'ما الذي يجب ألا يحدث بأي شكل في الزفاف؟', type: 'frage', category: 'jga' },
  { text: 'اتصل بالعروس/العريس وقل: نشتاق لك!', type: 'aufgabe', category: 'jga' },
  { text: 'ما أول شيء سيفعله العروسان بعد الزفاف؟', type: 'frage', category: 'jga' },
  { text: 'اكتب عقد زواج — ببنود مضحكة!', type: 'aufgabe', category: 'jga' },
  { text: 'ما أكبر عيب في العروس/العريس؟', type: 'frage', category: 'jga' },
  { text: 'اصنع باقة زفاف مما تجده!', type: 'aufgabe', category: 'jga' },
  { text: 'ما الشيء الذي لن يفعله العروس/العريس أبداً؟', type: 'frage', category: 'jga' },
  { text: 'صوّر فيديو يقول فيه الجميع "نعم، أقبل!"', type: 'aufgabe', category: 'jga' },
  { text: 'ما أفضل هدية حصل/ت عليها العروس/العريس على الإطلاق؟', type: 'frage', category: 'jga' },
  { text: 'ارتجل خطاب زفاف — دقيقة واحدة كحد أقصى!', type: 'aufgabe', category: 'jga' },
  { text: 'أي حيوان سيكون العروس/العريس ولماذا؟', type: 'frage', category: 'jga' },
  { text: 'التقط صورة تبدو كملصق فيلم!', type: 'aufgabe', category: 'jga' },
  { text: 'أي أغنية يجب أن يشغّلها العروسان حتماً في الزفاف؟', type: 'frage', category: 'jga' },
  { text: 'اجمع 3 نصائح زواج من المارة!', type: 'aufgabe', category: 'jga' },
  { text: 'ما أكثر لحظة محرجة للعروس/العريس؟', type: 'frage', category: 'jga' },
  { text: 'التقطوا صورة جماعية على شكل قلب!', type: 'aufgabe', category: 'jga' },

  // === بطاقات جديدة: للبالغين (30) ===
  { text: 'ما أسوأ عبارة تودّد سمعتها على الإطلاق؟', type: 'frage', category: 'erwachsene' },
  { text: 'قل للشخص المقابل أفضل مجاملة لديك!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أكبر فشل لك في المواعيد؟', type: 'frage', category: 'erwachsene' },
  { text: 'غازل الشخص على يسارك — 15 ثانية!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما عبارة المغازلة المفضلة لديك؟', type: 'frage', category: 'erwachsene' },
  { text: 'اصنع أفضل وجه عارض/ة أزياء لصورة!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أكثر مكان رومانسي كنت فيه؟', type: 'frage', category: 'erwachsene' },
  { text: 'أرسل مجاملة للشخص الخامس في جهات اتصالك!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أجرأ شيء فعلته في موعد؟', type: 'frage', category: 'erwachsene' },
  { text: 'التقط سيلفي مجنون مع الشخص المقابل!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'مَن هنا لديه أكثر صوت إغراءً؟', type: 'frage', category: 'erwachsene' },
  { text: 'اهمس بشيء جريء لأذن الشخص على يمينك!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ماذا ستفعل في الموعد المثالي؟', type: 'frage', category: 'erwachsene' },
  { text: 'انظر في عيني الشخص المقابل بعمق لمدة 10 ثوانٍ!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أغرب تجربة لك في تطبيق مواعدة؟', type: 'frage', category: 'erwachsene' },
  { text: 'أعطِ كل شخص في المجموعة لقب مغازلة!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أكثر شيء يجذبك؟', type: 'frage', category: 'erwachsene' },
  { text: 'قل أفضل عبارة تودّد لديك — واستخدمها!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أكثر شيء رومانسي حدث لك على الإطلاق؟', type: 'frage', category: 'erwachsene' },
  { text: 'أدِّ مشهد حب درامي — بمفردك!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'مَن هنا سيكون أفضل مُقبّل في الأفلام؟', type: 'frage', category: 'erwachsene' },
  { text: 'أرسل إيموجي قلب لآخر شخص!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أكثر لحظة محرجة لك في المغازلة؟', type: 'frage', category: 'erwachsene' },
  { text: 'اصنع أفضل وجه مغازلة — احتفظ به 10 ثوانٍ!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'أي مشهور سيكون موعدك المثالي؟', type: 'frage', category: 'erwachsene' },
  { text: 'غنِّ أغنية حب للشخص على يسارك!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'ما أفضل قبلة في حياتك؟', type: 'frage', category: 'erwachsene' },
  { text: 'اعترف بحبك لطعامك المفضل!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'عن ماذا ستتنازل من أجل الحب الكبير؟', type: 'frage', category: 'erwachsene' },
  { text: 'دع المجموعة تخطط لك موعداً غرامياً!', type: 'aufgabe', category: 'erwachsene' },

  // === بطاقات جديدة: كسر الجليد (30) ===
  { text: 'ما أفضل قرار اتخذته على الإطلاق؟', type: 'frage', category: 'eisbrecher' },
  { text: 'احكِ عن شيء تشعر بالامتنان تجاهه.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ماذا ستغيّر في اسمك؟', type: 'frage', category: 'eisbrecher' },
  { text: 'قل للشخص المقابل ما يعجبك فيه.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما الذي على رأس قائمة أمنياتك؟', type: 'frage', category: 'eisbrecher' },
  { text: 'احكِ عن لحظة جعلتك تفكر.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما الذي يجعلك فريداً؟', type: 'frage', category: 'eisbrecher' },
  { text: 'أرِ المجموعة صورتك المفضلة على الهاتف.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'لو كنت شخصاً آخر ليوم واحد — مَن ستكون؟', type: 'frage', category: 'eisbrecher' },
  { text: 'قل مجاملة صادقة للشخص على يسارك.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما أهم شيء في الصداقة؟', type: 'frage', category: 'eisbrecher' },
  { text: 'شارك حكمة حياتية تعلمتها.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'أي بلد تودّ زيارته ولماذا؟', type: 'frage', category: 'eisbrecher' },
  { text: 'اسأل أحداً في المجموعة شيئاً طالما أردت معرفته.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ماذا يعني النجاح بالنسبة لك؟', type: 'frage', category: 'eisbrecher' },
  { text: 'احكِ عن أجمل لحظة في طفولتك.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما الذي فاجأك حقاً مؤخراً؟', type: 'frage', category: 'eisbrecher' },
  { text: 'قل ثلاثة أشياء تحبها في نفسك.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'أي كتاب غيّر حياتك؟', type: 'frage', category: 'eisbrecher' },
  { text: 'أعطِ الشخص الذي تعرفه أقل لقباً.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما وصفتك السرية للمزاج الجيد؟', type: 'frage', category: 'eisbrecher' },
  { text: 'احكِ عن اللحظة التي كنت فيها أكثر فخراً.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما النصيحة التي ستعطيها لنفسك الأصغر؟', type: 'frage', category: 'eisbrecher' },
  { text: 'أرِ المجموعة ميمك المفضل.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما الذي تفعله أفضل من معظم الناس؟', type: 'frage', category: 'eisbrecher' },
  { text: 'اذكر ثلاثة أشياء تجمعك بجارك.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ماذا ستفعل لو عرفت أنك لن تفشل؟', type: 'frage', category: 'eisbrecher' },
  { text: 'احكِ قصة في 3 جمل بالضبط.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'ما أجمل شيء قاله لك أحد على الإطلاق؟', type: 'frage', category: 'eisbrecher' },
  { text: 'قم بتأمل قصير — الكل يغمض عينيه 15 ثانية.', type: 'aufgabe', category: 'eisbrecher' },
];
