export type BottleCategory = 'spass' | 'party' | 'jga' | 'erwachsene' | 'eisbrecher';
export type CardType = 'frage' | 'aufgabe';
export interface BottleCard { text: string; type: CardType; category: BottleCategory; }
export const CATEGORY_META: Record<BottleCategory, { name: string; emoji: string; color: string }> = {
  spass: { name: 'Fun', emoji: '😂', color: '#f59e0b' },
  party: { name: 'Fete', emoji: '🎉', color: '#ef4444' },
  jga: { name: 'EVJF/EVG', emoji: '💍', color: '#ec4899' },
  erwachsene: { name: 'Adultes 18+', emoji: '🔥', color: '#f97316' },
  eisbrecher: { name: 'Brise-glace', emoji: '🧊', color: '#06b6d4' },
};
export const BOTTLE_CARDS: BottleCard[] = [
  { text: 'Raconte ton moment le plus embarrassant.', type: 'frage', category: 'spass' },
  { text: 'Fais ton meilleur cri d\'animal.', type: 'aufgabe', category: 'spass' },
  { text: 'Montre la photo la plus ancienne de ton telephone.', type: 'aufgabe', category: 'spass' },
  { text: 'Quel a ete ton pire rendez-vous?', type: 'frage', category: 'spass' },
  { text: 'Imite une personne celebre — les autres doivent deviner.', type: 'aufgabe', category: 'spass' },
  { text: 'Quelle est la chose la plus bete que tu aies achetee?', type: 'frage', category: 'spass' },
  { text: 'Chante le refrain de ta chanson preferee.', type: 'aufgabe', category: 'spass' },
  { text: 'Montre ta conversation la plus drole.', type: 'aufgabe', category: 'spass' },
  { text: 'Quel surnom avais-tu enfant?', type: 'frage', category: 'spass' },
  { text: 'Danse 15 secondes sans musique.', type: 'aufgabe', category: 'spass' },
  { text: 'Quel est le message le plus genant envoye a la mauvaise personne?', type: 'frage', category: 'spass' },
  { text: 'Prends un selfie avec la grimace la plus drole et partage-le.', type: 'aufgabe', category: 'spass' },
  { text: 'Raconte un mensonge et les autres doivent deviner si c\'est vrai.', type: 'aufgabe', category: 'spass' },
  { text: 'Quelle est la chanson la plus genante de ta playlist?', type: 'frage', category: 'spass' },
  { text: 'Parle avec un accent invente pendant 1 minute.', type: 'aufgabe', category: 'spass' },
  { text: 'Quelle video YouTube as-tu regardee le plus souvent?', type: 'frage', category: 'spass' },
  { text: 'Essaie de ne pas rire 30 secondes — les autres peuvent tout tenter.', type: 'aufgabe', category: 'spass' },
  { text: 'Que ferais-tu si tu etais invisible un jour?', type: 'frage', category: 'spass' },
  { text: 'Echange ta photo de profil avec la personne a cote.', type: 'aufgabe', category: 'spass' },
  { text: 'Quel a ete ton plus gros fail en cuisine?', type: 'frage', category: 'spass' },
  { text: 'Fais un moonwalk a travers la piece.', type: 'aufgabe', category: 'spass' },
  { text: 'Quelle serie as-tu regardee en cachette?', type: 'frage', category: 'spass' },
  { text: 'Laisse la personne a cote poster une story sur ton Instagram.', type: 'aufgabe', category: 'spass' },
  { text: 'Qu\'y a-t-il de plus bizarre dans ton frigo?', type: 'frage', category: 'spass' },
  { text: 'Fais un discours de 30 secondes sur le papier toilette.', type: 'aufgabe', category: 'spass' },
  { text: 'Quelles 3 choses emporterais-tu sur une ile deserte?', type: 'frage', category: 'spass' },
  { text: 'Fais un chant de coq — le plus fort possible.', type: 'aufgabe', category: 'spass' },
  { text: 'Quel est ton talent secret que personne ne connait?', type: 'frage', category: 'spass' },
  { text: 'Marche a reculons dans la piece.', type: 'aufgabe', category: 'spass' },
  { text: 'Quel est le reve le plus etrange que tu as fait?', type: 'frage', category: 'spass' },
  { text: 'Bois une gorgee les yeux fermes.', type: 'aufgabe', category: 'party' },
  { text: 'Echange un vetement avec ton voisin.', type: 'aufgabe', category: 'party' },
  { text: 'Quelle a ete la fete la plus folle?', type: 'frage', category: 'party' },
  { text: 'Melange un nouveau cocktail et goute-le!', type: 'aufgabe', category: 'party' },
  { text: 'Quelle chanson te fait toujours danser?', type: 'frage', category: 'party' },
  { text: 'Defie quelqu\'un au bras de fer.', type: 'aufgabe', category: 'party' },
  { text: 'Quel a ete ton moment le plus ivre?', type: 'frage', category: 'party' },
  { text: 'Bois a chaque fois qu\'on dit ton prenom — 3 prochains tours.', type: 'aufgabe', category: 'party' },
  { text: 'Avec qui du groupe aimerais-tu passer la soiree?', type: 'frage', category: 'party' },
  { text: 'Fais une danse TikTok.', type: 'aufgabe', category: 'party' },
  { text: 'Quelle est la chose la plus courageuse que tu as faite en soiree?', type: 'frage', category: 'party' },
  { text: 'Chuchote tout les 2 prochains tours.', type: 'aufgabe', category: 'party' },
  { text: 'Qui du groupe tient le moins l\'alcool?', type: 'frage', category: 'party' },
  { text: 'Appelle quelqu\'un et dis: "Je suis a la meilleure fete du monde!"', type: 'aufgabe', category: 'party' },
  { text: 'Quel est ton rituel avant de sortir?', type: 'frage', category: 'party' },
  { text: 'Distribue 3 gorgees a qui tu veux.', type: 'aufgabe', category: 'party' },
  { text: 'Raconte ton experience la plus genante en soiree.', type: 'frage', category: 'party' },
  { text: 'Lance une farandole — tout le monde doit suivre.', type: 'aufgabe', category: 'party' },
  { text: 'Quel DJ ou artiste est sur ta bucket list?', type: 'frage', category: 'party' },
  { text: 'Enregistre-toi en train de beatboxer 5 secondes.', type: 'aufgabe', category: 'party' },
  { text: 'Raconte l\'histoire la plus drole sur la mariee/le marie.', type: 'frage', category: 'jga' },
  { text: 'Appelle une personne au hasard et felicite-la pour le mariage.', type: 'aufgabe', category: 'jga' },
  { text: 'Que penses-tu que le couple fera dans 10 ans?', type: 'frage', category: 'jga' },
  { text: 'Envoie un message genant a la mariee/au marie.', type: 'aufgabe', category: 'jga' },
  { text: 'Quelle a ete ta premiere impression du/de la partenaire?', type: 'frage', category: 'jga' },
  { text: 'Apprends un pas de danse de mariage et execute-le.', type: 'aufgabe', category: 'jga' },
  { text: 'Qui a le plus pleure a l\'annonce du mariage?', type: 'frage', category: 'jga' },
  { text: 'Prends une photo qui ressemble a un shooting de mariage.', type: 'aufgabe', category: 'jga' },
  { text: 'Quel est le meilleur conseil de mariage que tu puisses donner?', type: 'frage', category: 'jga' },
  { text: 'Fais un mini discours de mariage.', type: 'aufgabe', category: 'jga' },
  { text: 'Raconte le souvenir le plus genant avec la mariee/le marie.', type: 'frage', category: 'jga' },
  { text: 'Invite un inconnu au mariage.', type: 'aufgabe', category: 'jga' },
  { text: 'Qu\'offrirais-tu comme cadeau de mariage?', type: 'frage', category: 'jga' },
  { text: 'Enregistre une video de felicitations de 15 secondes.', type: 'aufgabe', category: 'jga' },
  { text: 'Quelle chanson decrit le mieux la relation du couple?', type: 'frage', category: 'jga' },
  { text: 'Trouve un inconnu qui dise "Oui, je le veux!" et filme-le.', type: 'aufgabe', category: 'jga' },
  { text: 'Qu\'est-ce qui est le plus agacant chez la mariee/le marie?', type: 'frage', category: 'jga' },
  { text: 'Organise une photo de groupe spontanee.', type: 'aufgabe', category: 'jga' },
  { text: 'Comment la mariee/le marie a-t-elle/il raconte la demande?', type: 'frage', category: 'jga' },
  { text: 'Ecris une prophetie de mariage sur une serviette.', type: 'aufgabe', category: 'jga' },
  { text: 'Decris ton pire baiser.', type: 'frage', category: 'erwachsene' },
  { text: 'A qui du groupe enverrais-tu un message a 2h du matin?', type: 'frage', category: 'erwachsene' },
  { text: 'Quelle est la chose la plus audacieuse que tu aies faite?', type: 'frage', category: 'erwachsene' },
  { text: 'Montre le dernier chat de drague sur ton telephone.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Quel est ton plus grand turn-off?', type: 'frage', category: 'erwachsene' },
  { text: 'Fais un compliment qui fait rougir a la personne a cote.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Quelle est la chose la plus seduisante qu\'on t\'ait dite?', type: 'frage', category: 'erwachsene' },
  { text: 'Fais ton meilleur visage de drague pendant 10 secondes.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Quel a ete ton rendez-vous le plus genant?', type: 'frage', category: 'erwachsene' },
  { text: 'Chuchote quelque chose de coquin a la personne a droite.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'As-tu deja trouve quelqu\'un de ce groupe attirant?', type: 'frage', category: 'erwachsene' },
  { text: 'Envoie un message coquin a quelqu\'un — montre-le au groupe.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Quel est ton crush le plus insolite?', type: 'frage', category: 'erwachsene' },
  { text: 'Laisse la personne en face lire un message de ton telephone.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Quelle est la chose la plus folle que tu as vecue en soiree?', type: 'frage', category: 'erwachsene' },
  { text: 'Raconte l\'histoire de ton premier baiser.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Si tu pouvais sortir avec une celebrite — qui?', type: 'frage', category: 'erwachsene' },
  { text: 'Fais un regard seducteur et envoie la photo au groupe.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Quel etait l\'endroit le plus etrange ou tu as embrasse quelqu\'un?', type: 'frage', category: 'erwachsene' },
  { text: 'Partage un secret que personne ici ne connait.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Quel est ton guilty pleasure?', type: 'frage', category: 'eisbrecher' },
  { text: 'Si tu avais un superpouvoir, lequel serait-ce?', type: 'frage', category: 'eisbrecher' },
  { text: 'Que voulais-tu etre enfant?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cite une chose sur ta bucket list.', type: 'frage', category: 'eisbrecher' },
  { text: 'Quelle est la meilleure chose qui t\'est arrivee cette annee?', type: 'frage', category: 'eisbrecher' },
  { text: 'Partage quelque chose que personne ici ne devrait savoir.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Quel est ton plat prefere et pourquoi?', type: 'frage', category: 'eisbrecher' },
  { text: 'Pose une question personnelle a la personne a cote.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Si tu pouvais vivre n\'importe ou, ou irais-tu?', type: 'frage', category: 'eisbrecher' },
  { text: 'Decris-toi en trois mots.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Quel livre ou podcast t\'a inspire recemment?', type: 'frage', category: 'eisbrecher' },
  { text: 'Dis quelque chose de gentil a chacun du groupe.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Quelle est ton opinion la plus impopulaire?', type: 'frage', category: 'eisbrecher' },
  { text: 'Partage un souvenir drole d\'enfance.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Si tu etais un animal, lequel et pourquoi?', type: 'frage', category: 'eisbrecher' },
  { text: 'Montre au groupe le dernier meme que tu as envoye.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Quelle est ta citation ou devise preferee?', type: 'frage', category: 'eisbrecher' },
  { text: 'Fais un compliment a la personne que tu connais le moins.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Quel est le meilleur voyage que tu as fait?', type: 'frage', category: 'eisbrecher' },
  { text: 'Raconte un moment qui a change ta vie.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Quelle competence aimerais-tu apprendre?', type: 'frage', category: 'eisbrecher' },
  { text: 'Donne un surnom a la personne en face pour la soiree.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Quelle est ta chanson preferee du moment et pourquoi?', type: 'frage', category: 'eisbrecher' },
  { text: 'Raconte ce que tu as fait en premier en te reveillant.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Quel est le meilleur conseil qu\'on t\'ait donne?', type: 'frage', category: 'eisbrecher' },
  { text: 'Presente-toi comme un personnage de film.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qu\'est-ce qui te rend vraiment heureux?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cite 3 choses en commun avec la personne a cote.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Si tu avais une machine a remonter le temps, ou irais-tu?', type: 'frage', category: 'eisbrecher' },
  { text: 'Raconte ta meilleure experience avec un inconnu.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Quel emoji utilises-tu le plus souvent?', type: 'frage', category: 'eisbrecher' },
  { text: 'Es-tu plutot du matin ou du soir?', type: 'frage', category: 'eisbrecher' },
  { text: 'Quel est ton plat reconfort quand tu es triste?', type: 'frage', category: 'eisbrecher' },
  { text: 'Decris ta journee parfaite du dimanche.', type: 'frage', category: 'eisbrecher' },
  { text: 'Quelle saison preferes-tu et pourquoi?', type: 'frage', category: 'eisbrecher' },
  { text: 'Quel est le dernier truc que tu as cherche sur Google?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cafe ou the? Justifie ton choix.', type: 'frage', category: 'eisbrecher' },
  { text: 'Quelle application ouvres-tu en premier le matin?', type: 'frage', category: 'eisbrecher' },
  { text: 'Quel est ton endroit prefere dans ta ville?', type: 'frage', category: 'eisbrecher' },
  { text: 'Si tu avais une journee de conge surprise, que ferais-tu?', type: 'frage', category: 'eisbrecher' },
  { text: 'Quel film peux-tu regarder en boucle sans t\'ennuyer?', type: 'frage', category: 'eisbrecher' },
  { text: 'Quelle est ta collation preferee devant une serie?', type: 'frage', category: 'eisbrecher' },
  { text: 'Quel objet du quotidien ne pourrais-tu pas remplacer?', type: 'frage', category: 'eisbrecher' },
  { text: 'Quel est ton souvenir prefere des vacances d\'ete?', type: 'frage', category: 'eisbrecher' },
  { text: 'Plutot montagne ou plage?', type: 'frage', category: 'eisbrecher' },
  { text: 'Quelle odeur te rappelle ton enfance?', type: 'frage', category: 'eisbrecher' },
  { text: 'Quel est ton petit plaisir du matin?', type: 'frage', category: 'eisbrecher' },
  { text: 'Quelle langue aimerais-tu parler couramment?', type: 'frage', category: 'eisbrecher' },
  { text: 'Dis a la personne a ta gauche ce que tu admires chez elle.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Devine l\'age de chaque personne du groupe a haute voix.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Montre la derniere photo prise avec ton telephone.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Apprends au groupe un mot dans une autre langue.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Decris ton humeur du jour avec une seule couleur.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Trouve un point commun avec chaque personne du cercle.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Mime ton metier sans parler, les autres devinent.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Raconte comment tu connais la personne qui t\'a invite.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Classe le groupe du plus matinal au plus couche-tard.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Donne un conseil de vie en une seule phrase.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Decris ta semaine en trois emojis a voix haute.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Fais deviner ton film prefere en trois indices.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Partage la meilleure nouvelle de ta semaine.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cite trois choses pour lesquelles tu es reconnaissant aujourd\'hui.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Presente ton voisin au groupe comme si c\'etait une star.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Decris ta playlist ideale pour un road trip.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Raconte ton plus beau souvenir de cette annee.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Si ta vie etait un film, quel en serait le titre?', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Quel emoji utiliserais-tu pour decrire chaque personne du groupe?', type: 'frage', category: 'eisbrecher' },
  { text: 'Quel est le mot que tu prononces toujours mal?', type: 'frage', category: 'spass' },
  { text: 'Quelle est la pire coiffure que tu as eue?', type: 'frage', category: 'spass' },
  { text: 'Quel personnage de dessin anime te ressemble le plus?', type: 'frage', category: 'spass' },
  { text: 'Quelle est la chose la plus inutile que tu sais faire?', type: 'frage', category: 'spass' },
  { text: 'Quel est ton aliment le plus controverse aime?', type: 'frage', category: 'spass' },
  { text: 'Quelle excuse bidon as-tu deja utilisee pour annuler un plan?', type: 'frage', category: 'spass' },
  { text: 'Quel est le surnom le plus ridicule donne a ton animal?', type: 'frage', category: 'spass' },
  { text: 'Quelle est la theorie du complot la plus drole a laquelle tu as cru?', type: 'frage', category: 'spass' },
  { text: 'Quel est ton pire gout musical assume?', type: 'frage', category: 'spass' },
  { text: 'Quelle est la chose la plus bizarre que tu manges en cachette?', type: 'frage', category: 'spass' },
  { text: 'Quel objet as-tu garde alors qu\'il est completement casse?', type: 'frage', category: 'spass' },
  { text: 'Quelle est la pub que tu connais par coeur?', type: 'frage', category: 'spass' },
  { text: 'Quel est le truc le plus enfantin que tu fais encore?', type: 'frage', category: 'spass' },
  { text: 'Quelle phrase de film cites-tu tout le temps?', type: 'frage', category: 'spass' },
  { text: 'Quel est ton talent completement inutile en soiree?', type: 'frage', category: 'spass' },
  { text: 'Quelle est la chose la plus chere que tu as cassee par maladresse?', type: 'frage', category: 'spass' },
  { text: 'Quel jeu video t\'a rendu fou de rage?', type: 'frage', category: 'spass' },
  { text: 'Quelle est ta plus grosse peur irrationnelle?', type: 'frage', category: 'spass' },
  { text: 'Imite la demarche de quelqu\'un dans la piece sans dire qui.', type: 'aufgabe', category: 'spass' },
  { text: 'Invente une pub de 20 secondes pour une chaussette.', type: 'aufgabe', category: 'spass' },
  { text: 'Parle uniquement en chantant pendant les deux prochains tours.', type: 'aufgabe', category: 'spass' },
  { text: 'Fais semblant d\'etre un commentateur sportif de la scene actuelle.', type: 'aufgabe', category: 'spass' },
  { text: 'Raconte une blague tellement nulle qu\'elle en devient drole.', type: 'aufgabe', category: 'spass' },
  { text: 'Imite un bebe qui apprend a marcher.', type: 'aufgabe', category: 'spass' },
  { text: 'Fais le bruitage d\'un film d\'horreur pendant 10 secondes.', type: 'aufgabe', category: 'spass' },
  { text: 'Recite l\'alphabet en eructant ou en imitant un robot.', type: 'aufgabe', category: 'spass' },
  { text: 'Dessine un portrait de ton voisin en 15 secondes et montre-le.', type: 'aufgabe', category: 'spass' },
  { text: 'Marche comme un mannequin sur un podium imaginaire.', type: 'aufgabe', category: 'spass' },
  { text: 'Invente une langue imaginaire et tiens une conversation de 20 secondes.', type: 'aufgabe', category: 'spass' },
  { text: 'Fais semblant de pleurer de joie comme aux Oscars.', type: 'aufgabe', category: 'spass' },
  { text: 'Imite ta grand-mere au telephone.', type: 'aufgabe', category: 'spass' },
  { text: 'Fais une pose de yoga improbable et tiens-la 10 secondes.', type: 'aufgabe', category: 'spass' },
  { text: 'Decris la personne en face comme un narrateur de documentaire animalier.', type: 'aufgabe', category: 'spass' },
  { text: 'Chante "Joyeux anniversaire" version opera.', type: 'aufgabe', category: 'spass' },
  { text: 'Fais semblant d\'etre un mannequin de vitrine pendant 30 secondes.', type: 'aufgabe', category: 'spass' },
  { text: 'Imite trois animaux differents et fais-les deviner.', type: 'aufgabe', category: 'spass' },
  { text: 'Raconte ta matinee comme si c\'etait une bande-annonce de blockbuster.', type: 'aufgabe', category: 'spass' },
  { text: 'Qui du groupe ferait le meilleur president?', type: 'frage', category: 'party' },
  { text: 'Quel est le pire lendemain de soiree que tu as vecu?', type: 'frage', category: 'party' },
  { text: 'Quelle est la chose la plus folle faite pour entrer dans une boite?', type: 'frage', category: 'party' },
  { text: 'Qui dans le groupe est le roi ou la reine de la piste?', type: 'frage', category: 'party' },
  { text: 'Quel est ton shot prefere et celui que tu detestes?', type: 'frage', category: 'party' },
  { text: 'Quelle est la pire decision prise apres minuit?', type: 'frage', category: 'party' },
  { text: 'Qui du groupe envoie les pires messages bourre?', type: 'frage', category: 'party' },
  { text: 'Quel est ton karaoke garanti banger?', type: 'frage', category: 'party' },
  { text: 'Quelle est la fete que tu n\'oublieras jamais?', type: 'frage', category: 'party' },
  { text: 'Qui finit toujours par perdre ses affaires en soiree?', type: 'frage', category: 'party' },
  { text: 'Quelle boisson ne reprendras-tu jamais apres un mauvais souvenir?', type: 'frage', category: 'party' },
  { text: 'Qui du groupe danse le mieux quand personne ne regarde?', type: 'frage', category: 'party' },
  { text: 'Quel est l\'after le plus improbable ou tu as fini?', type: 'frage', category: 'party' },
  { text: 'Bois une gorgee si tu as deja danse sur une table.', type: 'aufgabe', category: 'party' },
  { text: 'Choisis quelqu\'un: vous trinquez et buvez ensemble.', type: 'aufgabe', category: 'party' },
  { text: 'Lance un "cul sec" collectif avec ta boisson.', type: 'aufgabe', category: 'party' },
  { text: 'Invente un toast et fais lever tous les verres.', type: 'aufgabe', category: 'party' },
  { text: 'Mime ton etat apres trois verres de trop.', type: 'aufgabe', category: 'party' },
  { text: 'Distribue 5 gorgees a repartir comme tu veux dans le groupe.', type: 'aufgabe', category: 'party' },
  { text: 'Imite ta facon de danser quand le DJ met ta chanson preferee.', type: 'aufgabe', category: 'party' },
  { text: 'Fais un battle de danse de 15 secondes avec la personne en face.', type: 'aufgabe', category: 'party' },
  { text: 'Lance le karaoke: chante 20 secondes d\'un tube de fete.', type: 'aufgabe', category: 'party' },
  { text: 'Bois chaque fois que quelqu\'un rit pendant ce tour.', type: 'aufgabe', category: 'party' },
  { text: 'Echange de place avec quelqu\'un et trinquez.', type: 'aufgabe', category: 'party' },
  { text: 'Fais le DJ: choisis la prochaine chanson de la soiree.', type: 'aufgabe', category: 'party' },
  { text: 'Tout le monde qui a deja danse sous la pluie boit une gorgee.', type: 'aufgabe', category: 'party' },
  { text: 'Imite la personne qui s\'endort toujours en premier en soiree.', type: 'aufgabe', category: 'party' },
  { text: 'Crie "Sante" le plus fort possible et tout le monde trinque.', type: 'aufgabe', category: 'party' },
  { text: 'Choisis un partenaire de boisson pour les 3 prochains tours.', type: 'aufgabe', category: 'party' },
  { text: 'Fais un mini concours de grimaces, le perdant boit.', type: 'aufgabe', category: 'party' },
  { text: 'Bois si tu as deja envoye un texto a ton ex en soiree.', type: 'aufgabe', category: 'party' },
  { text: 'Designe la personne qui doit faire le prochain toast.', type: 'aufgabe', category: 'party' },
  { text: 'Quel est ton apero prefere pour lancer une soiree?', type: 'frage', category: 'party' },
  { text: 'Qui du groupe rentre toujours le dernier?', type: 'frage', category: 'party' },
  { text: 'Quelle est ta strategie pour tenir toute la nuit en fete?', type: 'frage', category: 'party' },
  { text: 'Quelle chanson lance officiellement la soiree pour toi?', type: 'frage', category: 'party' },
  { text: 'Tout le monde qui n\'a jamais danse en boite boit une gorgee.', type: 'aufgabe', category: 'party' },
  { text: 'Quel a ete le moment le plus emouvant avec la mariee ou le marie?', type: 'frage', category: 'jga' },
  { text: 'Quel surnom le groupe devrait-il donner a la future marie pour ce soir?', type: 'frage', category: 'jga' },
  { text: 'Quelle betise as-tu deja couverte pour la mariee ou le marie?', type: 'frage', category: 'jga' },
  { text: 'Quel est le pire plan drague dont tu as ete temoin avec l\'organisateur du jour?', type: 'frage', category: 'jga' },
  { text: 'Que penses-tu que sera la lune de miel du couple?', type: 'frage', category: 'jga' },
  { text: 'Quelle habitude de la mariee ou du marie surprendra son partenaire?', type: 'frage', category: 'jga' },
  { text: 'Quel est le secret le plus drole que tu connais sur l\'organisateur de ce JGA?', type: 'frage', category: 'jga' },
  { text: 'Quelle chanson devrait passer pour l\'ouverture du bal?', type: 'frage', category: 'jga' },
  { text: 'Quel etait le style vestimentaire le plus douteux de la mariee ou du marie?', type: 'frage', category: 'jga' },
  { text: 'Quelle est la phrase culte de la mariee ou du marie?', type: 'frage', category: 'jga' },
  { text: 'Quel a ete le voyage le plus fou fait avec la future marie?', type: 'frage', category: 'jga' },
  { text: 'Quel talent cache la mariee ou le marie devrait montrer au mariage?', type: 'frage', category: 'jga' },
  { text: 'Quel surnom secret le partenaire utilise-t-il pour la mariee ou le marie?', type: 'frage', category: 'jga' },
  { text: 'Quel sera selon toi le plus grand defi de leur vie a deux?', type: 'frage', category: 'jga' },
  { text: 'Compose un poeme de quatre vers pour la future marie.', type: 'aufgabe', category: 'jga' },
  { text: 'Fais une declaration d\'amitie a la mariee ou au marie devant le groupe.', type: 'aufgabe', category: 'jga' },
  { text: 'Demande a un inconnu trois conseils pour un mariage reussi.', type: 'aufgabe', category: 'jga' },
  { text: 'Mime le jour de la demande en mariage du couple.', type: 'aufgabe', category: 'jga' },
  { text: 'Invente un slogan de campagne pour le mariage et scande-le.', type: 'aufgabe', category: 'jga' },
  { text: 'Apprends une choregraphie de groupe a presenter au mariage.', type: 'aufgabe', category: 'jga' },
  { text: 'Filme un message de 20 secondes pour les noces d\'or du couple.', type: 'aufgabe', category: 'jga' },
  { text: 'Demande a un inconnu de chanter une chanson d\'amour pour le couple.', type: 'aufgabe', category: 'jga' },
  { text: 'Fais une imitation de la mariee ou du marie a faire deviner.', type: 'aufgabe', category: 'jga' },
  { text: 'Ecris un voeu de mariage humoristique sur ton telephone et lis-le.', type: 'aufgabe', category: 'jga' },
  { text: 'Organise un toast collectif en l\'honneur de la future marie.', type: 'aufgabe', category: 'jga' },
  { text: 'Invente un jeu de mariage et explique les regles au groupe.', type: 'aufgabe', category: 'jga' },
  { text: 'Trouve un inconnu pour faire un selfie avec la mariee ou le marie.', type: 'aufgabe', category: 'jga' },
  { text: 'Fais predire l\'avenir du couple par un inconnu et filme-le.', type: 'aufgabe', category: 'jga' },
  { text: 'Cree un hashtag de mariage parfait et fais-le valider par le groupe.', type: 'aufgabe', category: 'jga' },
  { text: 'Recite trois qualites de la mariee ou du marie en rimes.', type: 'aufgabe', category: 'jga' },
  { text: 'Demande a trois inconnus de crier "Vive les maries".', type: 'aufgabe', category: 'jga' },
  { text: 'Quel moment du JGA finira certainement dans le discours de mariage?', type: 'frage', category: 'jga' },
  { text: 'Quelle promesse drole la mariee ou le marie devrait ajouter a ses voeux?', type: 'frage', category: 'jga' },
  { text: 'Mime le premier rendez-vous du couple tel que tu l\'imagines.', type: 'aufgabe', category: 'jga' },
  { text: 'Fais un mini sketch de la vie quotidienne du futur couple marie.', type: 'aufgabe', category: 'jga' },
  { text: 'Quelle est la plus belle qualite de la mariee ou du marie selon toi?', type: 'frage', category: 'jga' },
  { text: 'Donne un conseil osé pour la nuit de noces, version humour.', type: 'aufgabe', category: 'jga' },
  { text: 'Quel est ton plus grand fantasme avoue?', type: 'frage', category: 'erwachsene' },
  { text: 'Quel est l\'endroit le plus risque ou tu l\'as fait?', type: 'frage', category: 'erwachsene' },
  { text: 'Quelle est ta limite que tu ne franchiras jamais au lit?', type: 'frage', category: 'erwachsene' },
  { text: 'Quel est ton plus grand regret romantique?', type: 'frage', category: 'erwachsene' },
  { text: 'As-tu deja eu un coup de foudre purement physique?', type: 'frage', category: 'erwachsene' },
  { text: 'Quelle est la chose la plus osee que tu as faite en public?', type: 'frage', category: 'erwachsene' },
  { text: 'Qui dans cette piece embrasserais-tu si tu devais choisir?', type: 'frage', category: 'erwachsene' },
  { text: 'Quel est ton type physique ideal en une phrase?', type: 'frage', category: 'erwachsene' },
  { text: 'Quelle est la pire excuse que tu as donnee apres une nuit?', type: 'frage', category: 'erwachsene' },
  { text: 'Quel a ete ton flirt le plus inattendu?', type: 'frage', category: 'erwachsene' },
  { text: 'Quelle partie du corps remarques-tu en premier chez quelqu\'un?', type: 'frage', category: 'erwachsene' },
  { text: 'As-tu deja menti sur le nombre de tes ex?', type: 'frage', category: 'erwachsene' },
  { text: 'Quelle est la chose la plus coquine sur ta bucket list?', type: 'frage', category: 'erwachsene' },
  { text: 'Quel est ton souvenir le plus chaud d\'un ete?', type: 'frage', category: 'erwachsene' },
  { text: 'Quel est le pire moment ou tu t\'es fait surprendre?', type: 'frage', category: 'erwachsene' },
  { text: 'As-tu deja eu un crush sur un ami du groupe?', type: 'frage', category: 'erwachsene' },
  { text: 'Quelle phrase de drague marche toujours sur toi?', type: 'frage', category: 'erwachsene' },
  { text: 'Quel est ton plus grand secret de chambre a coucher?', type: 'frage', category: 'erwachsene' },
  { text: 'Murmure ton fantasme a l\'oreille de la personne a gauche.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Fais une danse sensuelle de 10 secondes pour le groupe.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Donne ta meilleure phrase de drague a la personne en face.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Decris ton crush ideal sans dire de nom et fais deviner.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Fais un compliment osé a la personne a ta droite.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Imite ta tete au reveil apres une nuit torride.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Envoie un emoji coquin a quelqu\'un de tes contacts et montre la reponse.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Fais un regard de seduction a chaque personne du groupe.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Mime une scene de film romantique avec un coussin.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Classe les personnes du groupe par ordre de charme, discretement.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Donne ta note sur 10 de flirt a la personne en face, justifie.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Murmure le compliment le plus audacieux a la personne a droite.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Recite une replique de film coquin de la facon la plus sensuelle.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Fais une demonstration de ton meilleur slow collé.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Decris ta scene de seduction ideale en trois phrases.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Quel est le rendez-vous le plus romantique que tu as organise?', type: 'frage', category: 'erwachsene' },
  { text: 'Quelle est la chose la plus folle faite par amour?', type: 'frage', category: 'erwachsene' },
  { text: 'Quel surnom intime trouves-tu insupportable?', type: 'frage', category: 'erwachsene' },
  { text: 'Fais ta meilleure imitation d\'un regard de braise au ralenti.', type: 'aufgabe', category: 'erwachsene' },
];
