export type BottleCategory = 'spass' | 'party' | 'jga' | 'erwachsene' | 'eisbrecher';
export type CardType = 'frage' | 'aufgabe';
export interface BottleCard { text: string; type: CardType; category: BottleCategory; }

export const CATEGORY_META: Record<BottleCategory, { name: string; emoji: string; color: string }> = {
  spass: { name: 'Fun', emoji: '😂', color: '#f59e0b' },
  party: { name: 'Party', emoji: '🎉', color: '#ef4444' },
  jga: { name: 'Bachelor/ette', emoji: '💍', color: '#ec4899' },
  erwachsene: { name: 'Adults 18+', emoji: '🔥', color: '#f97316' },
  eisbrecher: { name: 'Icebreaker', emoji: '🧊', color: '#06b6d4' },
};

export const BOTTLE_CARDS: BottleCard[] = [
  // FUN (60)
  { text: 'Tell your most embarrassing moment.', type: 'frage', category: 'spass' },
  { text: 'Do your best animal impression.', type: 'aufgabe', category: 'spass' },
  { text: 'Show the oldest photo on your phone.', type: 'aufgabe', category: 'spass' },
  { text: 'What was your worst date?', type: 'frage', category: 'spass' },
  { text: 'Imitate a famous person — others must guess.', type: 'aufgabe', category: 'spass' },
  { text: 'What is the dumbest thing you have ever bought?', type: 'frage', category: 'spass' },
  { text: 'Sing the chorus of your favorite song.', type: 'aufgabe', category: 'spass' },
  { text: 'Show your funniest chat history.', type: 'aufgabe', category: 'spass' },
  { text: 'What nickname did you have as a child?', type: 'frage', category: 'spass' },
  { text: 'Dance for 15 seconds without music.', type: 'aufgabe', category: 'spass' },
  { text: 'What is the most embarrassing message you sent to the wrong person?', type: 'frage', category: 'spass' },
  { text: 'Take a selfie with the funniest face and share it.', type: 'aufgabe', category: 'spass' },
  { text: 'Tell a lie and the others must guess if it is true.', type: 'aufgabe', category: 'spass' },
  { text: 'What is the most embarrassing song on your playlist?', type: 'frage', category: 'spass' },
  { text: 'Speak in a made-up accent for 1 minute.', type: 'aufgabe', category: 'spass' },
  { text: 'Which YouTube video have you watched the most?', type: 'frage', category: 'spass' },
  { text: 'Try not to laugh for 30 seconds — the others can try everything.', type: 'aufgabe', category: 'spass' },
  { text: 'What would you do if you were invisible for a day?', type: 'frage', category: 'spass' },
  { text: 'Swap your profile picture with the person next to you.', type: 'aufgabe', category: 'spass' },
  { text: 'What was your biggest cooking fail?', type: 'frage', category: 'spass' },
  { text: 'Do a moonwalk across the room.', type: 'aufgabe', category: 'spass' },
  { text: 'Which show did you secretly binge-watch?', type: 'frage', category: 'spass' },
  { text: 'Let the person next to you post a story on your Instagram.', type: 'aufgabe', category: 'spass' },
  { text: 'What is the weirdest thing in your fridge?', type: 'frage', category: 'spass' },
  { text: 'Give a 30-second speech about toilet paper.', type: 'aufgabe', category: 'spass' },
  { text: 'Which three things would you take to a deserted island?', type: 'frage', category: 'spass' },
  { text: 'Do a rooster call — as loud as you can.', type: 'aufgabe', category: 'spass' },
  { text: 'What is your secret talent nobody knows about?', type: 'frage', category: 'spass' },
  { text: 'Walk backwards across the room.', type: 'aufgabe', category: 'spass' },
  { text: 'What was the strangest dream you ever had?', type: 'frage', category: 'spass' },
  { text: 'Do 10 squats while telling a joke.', type: 'aufgabe', category: 'spass' },
  { text: 'Imitate a famous meme — the others must guess!', type: 'aufgabe', category: 'spass' },
  { text: 'Tell the strangest dream from last week.', type: 'frage', category: 'spass' },
  { text: 'Make your best opera face for 10 seconds.', type: 'aufgabe', category: 'spass' },
  { text: 'What is the most embarrassing thing you said as a kid?', type: 'frage', category: 'spass' },
  { text: 'Walk an invisible dog through the room.', type: 'aufgabe', category: 'spass' },
  { text: 'Which sound drives you crazy?', type: 'frage', category: 'spass' },
  { text: 'Talk like a robot for 30 seconds.', type: 'aufgabe', category: 'spass' },
  { text: 'What was the strangest encounter with a stranger?', type: 'frage', category: 'spass' },
  { text: 'Play air guitar to a song the others hum!', type: 'aufgabe', category: 'spass' },
  { text: 'Which food looks terrible but tastes amazing?', type: 'frage', category: 'spass' },
  { text: 'Stand up and give a dramatic weather forecast!', type: 'aufgabe', category: 'spass' },
  { text: 'What would you do if you were the only person on Earth?', type: 'frage', category: 'spass' },
  { text: 'Try not to blink for 20 seconds!', type: 'aufgabe', category: 'spass' },
  { text: 'If your life was a movie, what genre would it be?', type: 'frage', category: 'spass' },
  { text: 'Advertise the most boring product in the world!', type: 'aufgabe', category: 'spass' },
  { text: 'What was the worst thing you ever ate?', type: 'frage', category: 'spass' },
  { text: 'Tell a joke — if nobody laughs, do 5 squats!', type: 'aufgabe', category: 'spass' },
  { text: 'What was the most embarrassing autocorrect on your phone?', type: 'frage', category: 'spass' },
  { text: 'Perform a magic trick — even if you don\'t know one!', type: 'aufgabe', category: 'spass' },
  { text: 'What is the funniest thing that happened at work?', type: 'frage', category: 'spass' },
  { text: 'Go to the window and wave enthusiastically at people!', type: 'aufgabe', category: 'spass' },
  { text: 'If you were an emoji — which one?', type: 'frage', category: 'spass' },
  { text: 'Imitate your favorite food!', type: 'aufgabe', category: 'spass' },
  { text: 'What would you put in a time capsule?', type: 'frage', category: 'spass' },
  { text: 'Be a sports commentator for 30 seconds!', type: 'aufgabe', category: 'spass' },
  { text: 'What is the craziest thing you posted on social media?', type: 'frage', category: 'spass' },
  { text: 'Walk through the room in slow motion!', type: 'aufgabe', category: 'spass' },
  { text: 'What is the most annoying question you always get?', type: 'frage', category: 'spass' },
  { text: 'Purr like a cat for 15 seconds!', type: 'aufgabe', category: 'spass' },

  // PARTY (60)
  { text: 'Take a sip with your eyes closed.', type: 'aufgabe', category: 'party' },
  { text: 'Swap a piece of clothing with your neighbor.', type: 'aufgabe', category: 'party' },
  { text: 'What was the wildest party you ever went to?', type: 'frage', category: 'party' },
  { text: 'Mix a new drink from what is available — and try it!', type: 'aufgabe', category: 'party' },
  { text: 'Which song always makes you dance?', type: 'frage', category: 'party' },
  { text: 'Challenge someone to arm wrestling.', type: 'aufgabe', category: 'party' },
  { text: 'What was the drunkest moment of your life?', type: 'frage', category: 'party' },
  { text: 'Drink every time someone says your name — next 3 rounds.', type: 'aufgabe', category: 'party' },
  { text: 'Who in the group would you most like to spend the evening with?', type: 'frage', category: 'party' },
  { text: 'Do a TikTok dance.', type: 'aufgabe', category: 'party' },
  { text: 'What is the bravest thing you did at a party?', type: 'frage', category: 'party' },
  { text: 'Whisper only for the next 2 rounds.', type: 'aufgabe', category: 'party' },
  { text: 'Who in the group can drink the least?', type: 'frage', category: 'party' },
  { text: 'Call someone and say: "I am at the best party ever!"', type: 'aufgabe', category: 'party' },
  { text: 'What is your pre-party ritual?', type: 'frage', category: 'party' },
  { text: 'Give out 3 sips to people of your choice.', type: 'aufgabe', category: 'party' },
  { text: 'Tell your most embarrassing party story.', type: 'frage', category: 'party' },
  { text: 'Start a conga line — everyone must join.', type: 'aufgabe', category: 'party' },
  { text: 'Which DJ or artist is on your bucket list?', type: 'frage', category: 'party' },
  { text: 'Record yourself beatboxing for 5 seconds.', type: 'aufgabe', category: 'party' },
  { text: 'What is the best party snack?', type: 'frage', category: 'party' },
  { text: 'Drink from your neighbor\'s cup.', type: 'aufgabe', category: 'party' },
  { text: 'Who would you book as DJ for your dream party?', type: 'frage', category: 'party' },
  { text: 'Let the group pick a song you have to sing.', type: 'aufgabe', category: 'party' },
  { text: 'What was your best party moment this year?', type: 'frage', category: 'party' },
  { text: 'Build a cup pyramid in 15 seconds!', type: 'aufgabe', category: 'party' },
  { text: 'Who in the group would be the best party crasher?', type: 'frage', category: 'party' },
  { text: 'Do a handstand (or try).', type: 'aufgabe', category: 'party' },
  { text: 'What is the best party spot in your city?', type: 'frage', category: 'party' },
  { text: 'Stand up and give a toast to everyone!', type: 'aufgabe', category: 'party' },
  { text: 'Who here has the wildest moves on the dance floor?', type: 'frage', category: 'party' },
  { text: 'Take a blind sip — guess what it is!', type: 'aufgabe', category: 'party' },
  { text: 'Who would survive first in a zombie apocalypse?', type: 'frage', category: 'party' },
  { text: 'Invent a new cocktail and name it!', type: 'aufgabe', category: 'party' },
  { text: 'What was the best song at the last party?', type: 'frage', category: 'party' },
  { text: 'Start a conga line — everyone joins!', type: 'aufgabe', category: 'party' },
  { text: 'Who in the group dances best?', type: 'frage', category: 'party' },
  { text: 'Give a speech to tonight\'s party!', type: 'aufgabe', category: 'party' },
  { text: 'What is the bravest thing you did at a party?', type: 'frage', category: 'party' },
  { text: 'Dance 30 seconds to a song the group picks!', type: 'aufgabe', category: 'party' },
  { text: 'What is your secret party trick?', type: 'frage', category: 'party' },
  { text: 'Take a group photo — you decide the pose!', type: 'aufgabe', category: 'party' },
  { text: 'Who has the best dance moves?', type: 'frage', category: 'party' },
  { text: 'Start a wave — everyone joins!', type: 'aufgabe', category: 'party' },
  { text: 'What is the craziest thing you did drunk?', type: 'frage', category: 'party' },
  { text: 'Beatbox for 20 seconds!', type: 'aufgabe', category: 'party' },
  { text: 'Which song should be played right now?', type: 'frage', category: 'party' },
  { text: 'Swap an accessory with the person across from you!', type: 'aufgabe', category: 'party' },
  { text: 'What was the best party food you ever had?', type: 'frage', category: 'party' },
  { text: 'Whisper a secret to the person on the right!', type: 'aufgabe', category: 'party' },
  { text: 'Who would throw the best spontaneous party?', type: 'frage', category: 'party' },
  { text: 'Give a toast — to life!', type: 'aufgabe', category: 'party' },
  { text: 'What is your favorite karaoke song?', type: 'frage', category: 'party' },
  { text: 'Challenge someone to a dance battle!', type: 'aufgabe', category: 'party' },
  { text: 'What was the funniest party fail?', type: 'frage', category: 'party' },
  { text: 'Cheers with everyone — one by one!', type: 'aufgabe', category: 'party' },
  { text: 'Who is the party planner in the group?', type: 'frage', category: 'party' },
  { text: 'Announce like a DJ in the club!', type: 'aufgabe', category: 'party' },
  { text: 'What must never be missing at a party?', type: 'frage', category: 'party' },
  { text: 'Which party rule do you like breaking best?', type: 'frage', category: 'party' },

  // BACHELOR/ETTE (60)
  { text: 'Tell the funniest story about the bride/groom.', type: 'frage', category: 'jga' },
  { text: 'Call a random person and congratulate them on the wedding.', type: 'aufgabe', category: 'jga' },
  { text: 'What do you think the couple will be doing in 10 years?', type: 'frage', category: 'jga' },
  { text: 'Send the bride/groom an embarrassing message.', type: 'aufgabe', category: 'jga' },
  { text: 'What was your first impression of the partner?', type: 'frage', category: 'jga' },
  { text: 'Learn a wedding dance move and perform it.', type: 'aufgabe', category: 'jga' },
  { text: 'Who cried the most when the wedding was announced?', type: 'frage', category: 'jga' },
  { text: 'Take a photo that looks like a wedding shoot.', type: 'aufgabe', category: 'jga' },
  { text: 'What is the best marriage advice you could give?', type: 'frage', category: 'jga' },
  { text: 'Give a mini wedding speech.', type: 'aufgabe', category: 'jga' },
  { text: 'Tell the most embarrassing shared memory.', type: 'frage', category: 'jga' },
  { text: 'Invite a stranger to the wedding.', type: 'aufgabe', category: 'jga' },
  { text: 'What would you give the couple as a wedding gift?', type: 'frage', category: 'jga' },
  { text: 'Record a 15-second congratulations video.', type: 'aufgabe', category: 'jga' },
  { text: 'Which song best describes the couple\'s relationship?', type: 'frage', category: 'jga' },
  { text: 'Find a stranger who says "I do!" and record it.', type: 'aufgabe', category: 'jga' },
  { text: 'What is the most annoying thing the bride/groom does?', type: 'frage', category: 'jga' },
  { text: 'Organize a spontaneous group photo.', type: 'aufgabe', category: 'jga' },
  { text: 'How did the bride/groom tell the proposal story?', type: 'frage', category: 'jga' },
  { text: 'Write a marriage prophecy on a napkin.', type: 'aufgabe', category: 'jga' },
  { text: 'What do you wish for the couple\'s marriage?', type: 'frage', category: 'jga' },
  { text: 'Collect 5 signatures from strangers in 2 minutes.', type: 'aufgabe', category: 'jga' },
  { text: 'What was the funniest fail of the bride/groom?', type: 'frage', category: 'jga' },
  { text: 'Sing "Going to the Chapel" loudly.', type: 'aufgabe', category: 'jga' },
  { text: 'What did the bride/groom say when you heard about the engagement?', type: 'frage', category: 'jga' },
  { text: 'Take a photo with a stranger labeled "Wedding Guest".', type: 'aufgabe', category: 'jga' },
  { text: 'Who should definitely NOT give a speech at the wedding? Why?', type: 'frage', category: 'jga' },
  { text: 'Ask three people for marriage tips and write them down.', type: 'aufgabe', category: 'jga' },
  { text: 'What kind of teenager was the bride/groom?', type: 'frage', category: 'jga' },
  { text: 'Propose — on your knees — in front of the group.', type: 'aufgabe', category: 'jga' },
  { text: 'Name 3 things the bride/groom cannot do!', type: 'frage', category: 'jga' },
  { text: 'Take a pic where everyone poses like a married couple!', type: 'aufgabe', category: 'jga' },
  { text: 'What would you say in your wedding speech?', type: 'frage', category: 'jga' },
  { text: 'Convince a stranger to take a photo with the group!', type: 'aufgabe', category: 'jga' },
  { text: 'What is the funniest trait of the bride/groom?', type: 'frage', category: 'jga' },
  { text: 'Sing a love song for the couple!', type: 'aufgabe', category: 'jga' },
  { text: 'What was the first fight between bride and groom?', type: 'frage', category: 'jga' },
  { text: 'Write a love letter to the couple on a napkin!', type: 'aufgabe', category: 'jga' },
  { text: 'Who has known the bride/groom the longest?', type: 'frage', category: 'jga' },
  { text: 'Get a congratulations video from a stranger!', type: 'aufgabe', category: 'jga' },
  { text: 'What is the most romantic moment of the couple?', type: 'frage', category: 'jga' },
  { text: 'Invent a wedding dance — everyone dances along!', type: 'aufgabe', category: 'jga' },
  { text: 'Which movie describes the couple\'s relationship?', type: 'frage', category: 'jga' },
  { text: 'Find something old, new, borrowed, and blue!', type: 'aufgabe', category: 'jga' },
  { text: 'What must absolutely NOT happen at the wedding?', type: 'frage', category: 'jga' },
  { text: 'Call the bride/groom and say: We miss you!', type: 'aufgabe', category: 'jga' },
  { text: 'What will the couple do first after the wedding?', type: 'frage', category: 'jga' },
  { text: 'Write a marriage contract — with funny clauses!', type: 'aufgabe', category: 'jga' },
  { text: 'What is the biggest quirk of the bride/groom?', type: 'frage', category: 'jga' },
  { text: 'Build a wedding bouquet from whatever you find!', type: 'aufgabe', category: 'jga' },
  { text: 'What would the bride/groom NEVER do?', type: 'frage', category: 'jga' },
  { text: 'Record everyone saying "I do!"', type: 'aufgabe', category: 'jga' },
  { text: 'What was the best gift the bride/groom got?', type: 'frage', category: 'jga' },
  { text: 'Improvise a wedding speech — max 1 minute!', type: 'aufgabe', category: 'jga' },
  { text: 'Which animal would the bride/groom be and why?', type: 'frage', category: 'jga' },
  { text: 'Take a photo that looks like a movie poster!', type: 'aufgabe', category: 'jga' },
  { text: 'What song should definitely play at the wedding?', type: 'frage', category: 'jga' },
  { text: 'Collect 3 marriage tips from passersby!', type: 'aufgabe', category: 'jga' },
  { text: 'What was the most embarrassing moment of the bride/groom?', type: 'frage', category: 'jga' },
  { text: 'Take a group heart photo!', type: 'aufgabe', category: 'jga' },

  // ADULTS 18+ (60)
  { text: 'Describe your worst kiss.', type: 'frage', category: 'erwachsene' },
  { text: 'Who in the group would you text at 2 AM?', type: 'frage', category: 'erwachsene' },
  { text: 'What is the boldest thing you have ever done?', type: 'frage', category: 'erwachsene' },
  { text: 'Show the last flirty chat on your phone.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What is your biggest turn-off?', type: 'frage', category: 'erwachsene' },
  { text: 'Give the person next to you a compliment that makes them blush.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What is the most seductive thing someone ever said to you?', type: 'frage', category: 'erwachsene' },
  { text: 'Make your best "flirt face" and hold it for 10 seconds.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What was your most embarrassing date?', type: 'frage', category: 'erwachsene' },
  { text: 'Whisper something cheeky to the person on your right.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Have you ever found someone in this group attractive?', type: 'frage', category: 'erwachsene' },
  { text: 'Send a cheeky message to someone — show it to the group.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What is your most unusual crush?', type: 'frage', category: 'erwachsene' },
  { text: 'Let the person across from you read a message on your phone.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What is the wildest thing you experienced at a party?', type: 'frage', category: 'erwachsene' },
  { text: 'Tell the story of your first kiss.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'If you could go on a date with any celebrity — who?', type: 'frage', category: 'erwachsene' },
  { text: 'Make a seductive look at the camera and send it to the group.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What was the strangest place you ever kissed someone?', type: 'frage', category: 'erwachsene' },
  { text: 'Share a secret nobody here knows.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What is your favorite movie you would never publicly admit?', type: 'frage', category: 'erwachsene' },
  { text: 'Bite your lip and look into the eyes of the person across from you for 5 seconds.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Have you ever ghosted someone? Why?', type: 'frage', category: 'erwachsene' },
  { text: 'Show the last photo saved in your gallery.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What is the most romantic thing someone did for you?', type: 'frage', category: 'erwachsene' },
  { text: 'Write a blind cheeky message and send it to your last contact.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Who here is most likely the heartbreaker type?', type: 'frage', category: 'erwachsene' },
  { text: 'Do 5 push-ups and groan dramatically.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What would you do if your ex walked in right now?', type: 'frage', category: 'erwachsene' },
  { text: 'Sit on the lap of the person to your left for the next round.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What was the worst pickup line you ever heard?', type: 'frage', category: 'erwachsene' },
  { text: 'Give the person across from you your best compliment!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What was your biggest dating fail?', type: 'frage', category: 'erwachsene' },
  { text: 'Flirt with the person to your left — 15 seconds!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What is your favorite pickup line?', type: 'frage', category: 'erwachsene' },
  { text: 'Make your best model face for a photo!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What was the most romantic place you have been?', type: 'frage', category: 'erwachsene' },
  { text: 'Send a compliment to the 5th person in your contacts!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What is the boldest thing you did on a date?', type: 'frage', category: 'erwachsene' },
  { text: 'Take a crazy selfie with the person across from you!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Who here has the most seductive voice?', type: 'frage', category: 'erwachsene' },
  { text: 'Whisper something cheeky in the ear of the person on your right!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What would you do on a perfect date?', type: 'frage', category: 'erwachsene' },
  { text: 'Stare deeply into the eyes of the person across for 10 seconds!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What is the weirdest dating app experience?', type: 'frage', category: 'erwachsene' },
  { text: 'Give everyone a flirty nickname!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What is your biggest turn-on?', type: 'frage', category: 'erwachsene' },
  { text: 'Tell your best pickup line — and use it!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What is the most romantic thing that happened to you?', type: 'frage', category: 'erwachsene' },
  { text: 'Act out a dramatic love scene — alone!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Who here would be the best movie kisser?', type: 'frage', category: 'erwachsene' },
  { text: 'Send the last person a heart emoji!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What was your most embarrassing flirting moment?', type: 'frage', category: 'erwachsene' },
  { text: 'Make your best flirt face — hold it 10 seconds!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Which celebrity would be your perfect date?', type: 'frage', category: 'erwachsene' },
  { text: 'Sing the person to your left a love song!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What was the best kiss of your life?', type: 'frage', category: 'erwachsene' },
  { text: 'Make a love declaration to your favorite food!', type: 'aufgabe', category: 'erwachsene' },
  { text: 'What would you give up for true love?', type: 'frage', category: 'erwachsene' },
  { text: 'Let the group plan a date for you!', type: 'aufgabe', category: 'erwachsene' },

  // ICEBREAKER (60)
  { text: 'What is your guilty pleasure?', type: 'frage', category: 'eisbrecher' },
  { text: 'If you had a superpower, what would it be?', type: 'frage', category: 'eisbrecher' },
  { text: 'What did you want to be as a child?', type: 'frage', category: 'eisbrecher' },
  { text: 'Name one thing on your bucket list.', type: 'frage', category: 'eisbrecher' },
  { text: 'What is the best thing that happened to you this year?', type: 'frage', category: 'eisbrecher' },
  { text: 'Share something nobody here should know about you.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What is your favorite dish and why?', type: 'frage', category: 'eisbrecher' },
  { text: 'Ask the person next to you a personal question.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'If you could live anywhere in the world, where?', type: 'frage', category: 'eisbrecher' },
  { text: 'Describe yourself in three words.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What was the last book or podcast that inspired you?', type: 'frage', category: 'eisbrecher' },
  { text: 'Say something nice to everyone in the group.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What is your most unpopular opinion?', type: 'frage', category: 'eisbrecher' },
  { text: 'Share a funny childhood memory.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'If you were an animal, which one and why?', type: 'frage', category: 'eisbrecher' },
  { text: 'Show the group the last meme you sent.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What is your favorite quote or motto?', type: 'frage', category: 'eisbrecher' },
  { text: 'Give a compliment to the person you know least.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What is the best trip you ever took?', type: 'frage', category: 'eisbrecher' },
  { text: 'Tell about a moment that changed your life.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What skill would you love to learn?', type: 'frage', category: 'eisbrecher' },
  { text: 'Give the person across from you a nickname for the evening.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What is your favorite song right now and why?', type: 'frage', category: 'eisbrecher' },
  { text: 'Tell what you did first thing after waking up today.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What was the best advice you ever received?', type: 'frage', category: 'eisbrecher' },
  { text: 'Introduce yourself as if you were a movie character.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What truly makes you happy?', type: 'frage', category: 'eisbrecher' },
  { text: 'Name three things you and the person next to you have in common.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'If you had a time machine, where would you travel?', type: 'frage', category: 'eisbrecher' },
  { text: 'Tell about your best experience with a stranger.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What is the best decision you ever made?', type: 'frage', category: 'eisbrecher' },
  { text: 'Share something you are grateful for.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What would you change about your name?', type: 'frage', category: 'eisbrecher' },
  { text: 'Tell the person across from you what impresses you about them.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What is at the top of your wish list?', type: 'frage', category: 'eisbrecher' },
  { text: 'Tell about a moment that made you think.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What makes you unique?', type: 'frage', category: 'eisbrecher' },
  { text: 'Show the group your favorite photo on your phone.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'If you could be someone else for a day — who?', type: 'frage', category: 'eisbrecher' },
  { text: 'Give the person to the left an honest compliment.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What is the most important thing in a friendship?', type: 'frage', category: 'eisbrecher' },
  { text: 'Share a life lesson you learned.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Which country would you love to visit and why?', type: 'frage', category: 'eisbrecher' },
  { text: 'Ask someone something you always wanted to know.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What does success mean to you?', type: 'frage', category: 'eisbrecher' },
  { text: 'Tell your most beautiful childhood moment.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What has surprised you recently?', type: 'frage', category: 'eisbrecher' },
  { text: 'Name three things you like about yourself.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Which book changed your life?', type: 'frage', category: 'eisbrecher' },
  { text: 'Give the person you know least a nickname.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What is your secret recipe for a good mood?', type: 'frage', category: 'eisbrecher' },
  { text: 'Tell about the moment you were most proud.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What advice would you give your younger self?', type: 'frage', category: 'eisbrecher' },
  { text: 'Show the group your favorite meme.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What can you do better than most people?', type: 'frage', category: 'eisbrecher' },
  { text: 'Name three things that connect you and your neighbor.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What would you do if you knew you couldn\'t fail?', type: 'frage', category: 'eisbrecher' },
  { text: 'Tell a story in exactly 3 sentences.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'What is the nicest thing someone ever said to you?', type: 'frage', category: 'eisbrecher' },
  { text: 'Do a mini meditation — everyone closes their eyes for 15 seconds.', type: 'aufgabe', category: 'eisbrecher' },
];
