export type BottleCategory = 'spass' | 'party' | 'jga' | 'erwachsene' | 'eisbrecher';
export type CardType = 'frage' | 'aufgabe';
export interface BottleCard { text: string; type: CardType; category: BottleCategory; }
export const CATEGORY_META: Record<BottleCategory, { name: string; emoji: string; color: string }> = {
  spass: { name: 'Divertimento', emoji: '😂', color: '#f59e0b' },
  party: { name: 'Festa', emoji: '🎉', color: '#ef4444' },
  jga: { name: 'Addio al celibato', emoji: '💍', color: '#ec4899' },
  erwachsene: { name: 'Adulti 18+', emoji: '🔥', color: '#f97316' },
  eisbrecher: { name: 'Rompighiaccio', emoji: '🧊', color: '#06b6d4' },
};
export const BOTTLE_CARDS: BottleCard[] = [
  { text: 'Racconta il tuo momento piu imbarazzante.', type: 'frage', category: 'spass' },
  { text: 'Fai il tuo miglior verso animale.', type: 'aufgabe', category: 'spass' },
  { text: 'Mostra la foto piu vecchia del tuo telefono.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e stato il tuo peggior appuntamento?', type: 'frage', category: 'spass' },
  { text: 'Imita un personaggio famoso — gli altri devono indovinare.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e la cosa piu stupida che hai comprato?', type: 'frage', category: 'spass' },
  { text: 'Canta il ritornello della tua canzone preferita.', type: 'aufgabe', category: 'spass' },
  { text: 'Mostra la tua chat piu divertente.', type: 'aufgabe', category: 'spass' },
  { text: 'Che soprannome avevi da bambino?', type: 'frage', category: 'spass' },
  { text: 'Balla 15 secondi senza musica.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e il messaggio piu imbarazzante inviato alla persona sbagliata?', type: 'frage', category: 'spass' },
  { text: 'Fai un selfie con la faccia piu buffa e condividilo.', type: 'aufgabe', category: 'spass' },
  { text: 'Racconta una bugia — gli altri devono indovinare se e vera.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e la canzone piu imbarazzante nella tua playlist?', type: 'frage', category: 'spass' },
  { text: 'Parla con un accento inventato per 1 minuto.', type: 'aufgabe', category: 'spass' },
  { text: 'Quale video YouTube hai guardato piu spesso?', type: 'frage', category: 'spass' },
  { text: 'Prova a non ridere per 30 secondi — gli altri possono fare di tutto.', type: 'aufgabe', category: 'spass' },
  { text: 'Cosa faresti se fossi invisibile per un giorno?', type: 'frage', category: 'spass' },
  { text: 'Scambia la tua foto profilo con la persona accanto.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e stato il tuo piu grande fail in cucina?', type: 'frage', category: 'spass' },
  { text: 'Fai un moonwalk per la stanza.', type: 'aufgabe', category: 'spass' },
  { text: 'Quale serie hai guardato di nascosto?', type: 'frage', category: 'spass' },
  { text: 'Lascia che la persona accanto posti una storia sul tuo Instagram.', type: 'aufgabe', category: 'spass' },
  { text: 'Cosa c\'e di piu strano nel tuo frigo?', type: 'frage', category: 'spass' },
  { text: 'Tieni un discorso di 30 secondi sulla carta igienica.', type: 'aufgabe', category: 'spass' },
  { text: 'Quali 3 cose porteresti su un\'isola deserta?', type: 'frage', category: 'spass' },
  { text: 'Fai il verso del gallo — piu forte che puoi.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e il tuo talento segreto?', type: 'frage', category: 'spass' },
  { text: 'Cammina all\'indietro per la stanza.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e il sogno piu strano che hai fatto?', type: 'frage', category: 'spass' },
  { text: 'Bevi un sorso ad occhi chiusi.', type: 'aufgabe', category: 'party' },
  { text: 'Scambia un capo d\'abbigliamento con il vicino.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e stata la festa piu pazza?', type: 'frage', category: 'party' },
  { text: 'Mescola un nuovo drink e assaggialo!', type: 'aufgabe', category: 'party' },
  { text: 'Quale canzone ti fa sempre ballare?', type: 'frage', category: 'party' },
  { text: 'Sfida qualcuno a braccio di ferro.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e stato il momento piu ubriaco della tua vita?', type: 'frage', category: 'party' },
  { text: 'Bevi ogni volta che qualcuno dice il tuo nome — prossimi 3 turni.', type: 'aufgabe', category: 'party' },
  { text: 'Con chi del gruppo vorresti passare la serata?', type: 'frage', category: 'party' },
  { text: 'Fai un ballo di TikTok.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e la cosa piu coraggiosa che hai fatto a una festa?', type: 'frage', category: 'party' },
  { text: 'Sussurra tutto per i prossimi 2 turni.', type: 'aufgabe', category: 'party' },
  { text: 'Chi del gruppo regge meno l\'alcol?', type: 'frage', category: 'party' },
  { text: 'Chiama qualcuno e dì: "Sono alla migliore festa del mondo!"', type: 'aufgabe', category: 'party' },
  { text: 'Qual e il tuo rituale prima di uscire?', type: 'frage', category: 'party' },
  { text: 'Distribuisci 3 sorsi a chi vuoi.', type: 'aufgabe', category: 'party' },
  { text: 'Racconta la tua esperienza piu imbarazzante a una festa.', type: 'frage', category: 'party' },
  { text: 'Fai un trenino — tutti devono unirsi.', type: 'aufgabe', category: 'party' },
  { text: 'Quale DJ o artista e sulla tua bucket list?', type: 'frage', category: 'party' },
  { text: 'Registrati mentre fai beatbox per 5 secondi.', type: 'aufgabe', category: 'party' },
  { text: 'Racconta la storia piu divertente sulla sposa/sullo sposo.', type: 'frage', category: 'jga' },
  { text: 'Chiama una persona a caso e falle le congratulazioni per il matrimonio.', type: 'aufgabe', category: 'jga' },
  { text: 'Cosa pensi che fara la coppia tra 10 anni?', type: 'frage', category: 'jga' },
  { text: 'Manda alla sposa/allo sposo un messaggio imbarazzante.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e stata la tua prima impressione del partner?', type: 'frage', category: 'jga' },
  { text: 'Impara un passo del ballo nuziale e fallo.', type: 'aufgabe', category: 'jga' },
  { text: 'Chi ha pianto di piu quando e stato annunciato il matrimonio?', type: 'frage', category: 'jga' },
  { text: 'Scatta una foto che sembra un servizio di nozze.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e il miglior consiglio matrimoniale che puoi dare?', type: 'frage', category: 'jga' },
  { text: 'Fai un mini discorso di nozze.', type: 'aufgabe', category: 'jga' },
  { text: 'Racconta il ricordo piu imbarazzante con la sposa/lo sposo.', type: 'frage', category: 'jga' },
  { text: 'Invita uno sconosciuto al matrimonio.', type: 'aufgabe', category: 'jga' },
  { text: 'Cosa regaleresti alla coppia come regalo di nozze?', type: 'frage', category: 'jga' },
  { text: 'Registra un video di auguri di 15 secondi.', type: 'aufgabe', category: 'jga' },
  { text: 'Quale canzone descrive meglio la relazione della coppia?', type: 'frage', category: 'jga' },
  { text: 'Trova uno sconosciuto che dica "Si, lo voglio!" e filmalo.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e la cosa piu fastidiosa della sposa/dello sposo?', type: 'frage', category: 'jga' },
  { text: 'Organizza una foto di gruppo spontanea.', type: 'aufgabe', category: 'jga' },
  { text: 'Come ha raccontato la sposa/lo sposo la proposta?', type: 'frage', category: 'jga' },
  { text: 'Scrivi una profezia matrimoniale su un tovagliolo.', type: 'aufgabe', category: 'jga' },
  { text: 'Descrivi il tuo peggior bacio.', type: 'frage', category: 'erwachsene' },
  { text: 'A chi del gruppo manderesti un messaggio alle 2 di notte?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e la cosa piu audace che hai mai fatto?', type: 'frage', category: 'erwachsene' },
  { text: 'Mostra l\'ultima chat di flirt sul tuo telefono.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e il tuo piu grande turn-off?', type: 'frage', category: 'erwachsene' },
  { text: 'Fai un complimento alla persona accanto che la faccia arrossire.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e la cosa piu seducente che qualcuno ti abbia detto?', type: 'frage', category: 'erwachsene' },
  { text: 'Fai la tua migliore faccia da flirt per 10 secondi.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e stato il tuo appuntamento piu imbarazzante?', type: 'frage', category: 'erwachsene' },
  { text: 'Sussurra qualcosa di audace alla persona alla tua destra.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Hai mai trovato attraente qualcuno di questo gruppo?', type: 'frage', category: 'erwachsene' },
  { text: 'Manda un messaggio audace a qualcuno — mostralo al gruppo.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e la tua cotta piu insolita?', type: 'frage', category: 'erwachsene' },
  { text: 'Lascia che la persona di fronte legga un messaggio del tuo telefono.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e la cosa piu pazza che hai vissuto a una festa?', type: 'frage', category: 'erwachsene' },
  { text: 'Racconta la storia del tuo primo bacio.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Se potessi uscire con una celebrita — chi sarebbe?', type: 'frage', category: 'erwachsene' },
  { text: 'Fai uno sguardo seducente e manda la foto al gruppo.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e stato il posto piu strano in cui hai baciato qualcuno?', type: 'frage', category: 'erwachsene' },
  { text: 'Condividi un segreto che nessuno qui conosce.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e il tuo guilty pleasure?', type: 'frage', category: 'eisbrecher' },
  { text: 'Se avessi un superpotere, quale sarebbe?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cosa volevi fare da grande?', type: 'frage', category: 'eisbrecher' },
  { text: 'Nomina una cosa della tua bucket list.', type: 'frage', category: 'eisbrecher' },
  { text: 'Qual e la cosa migliore che ti e successa quest\'anno?', type: 'frage', category: 'eisbrecher' },
  { text: 'Condividi qualcosa che nessuno qui dovrebbe sapere.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e il tuo piatto preferito e perche?', type: 'frage', category: 'eisbrecher' },
  { text: 'Fai una domanda personale alla persona accanto.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Se potessi vivere ovunque, dove andresti?', type: 'frage', category: 'eisbrecher' },
  { text: 'Descriviti in tre parole.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e l\'ultimo libro o podcast che ti ha ispirato?', type: 'frage', category: 'eisbrecher' },
  { text: 'Di qualcosa di carino a ciascuno del gruppo.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e la tua opinione piu impopolare?', type: 'frage', category: 'eisbrecher' },
  { text: 'Condividi un ricordo divertente dell\'infanzia.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Se fossi un animale, quale saresti e perche?', type: 'frage', category: 'eisbrecher' },
  { text: 'Mostra al gruppo l\'ultimo meme che hai inviato.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e la tua citazione o motto preferito?', type: 'frage', category: 'eisbrecher' },
  { text: 'Fai un complimento alla persona che conosci meno.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e il viaggio migliore che hai fatto?', type: 'frage', category: 'eisbrecher' },
  { text: 'Racconta un momento che ha cambiato la tua vita.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Quale abilita vorresti imparare?', type: 'frage', category: 'eisbrecher' },
  { text: 'Dai un soprannome alla persona di fronte per la serata.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e la tua canzone preferita del momento e perche?', type: 'frage', category: 'eisbrecher' },
  { text: 'Racconta cosa hai fatto appena sveglio stamattina.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e il miglior consiglio che hai ricevuto?', type: 'frage', category: 'eisbrecher' },
  { text: 'Presentati come un personaggio di un film.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cosa ti rende veramente felice?', type: 'frage', category: 'eisbrecher' },
  { text: 'Nomina 3 cose che tu e la persona accanto avete in comune.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Se avessi una macchina del tempo, dove andresti?', type: 'frage', category: 'eisbrecher' },
  { text: 'Racconta la tua migliore esperienza con uno sconosciuto.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e l\'app che apri appena ti svegli?', type: 'frage', category: 'eisbrecher' },
  { text: 'Dolce o salato a colazione?', type: 'frage', category: 'eisbrecher' },
  { text: 'Sei piu tipo da mare o da montagna?', type: 'frage', category: 'eisbrecher' },
  { text: 'Qual e il film che hai visto piu volte?', type: 'frage', category: 'eisbrecher' },
  { text: 'Caffe o cappuccino dopo pranzo? Difendi la tua scelta.', type: 'frage', category: 'eisbrecher' },
  { text: 'Qual e la tua stagione preferita e perche?', type: 'frage', category: 'eisbrecher' },
  { text: 'Sei una persona mattiniera o nottambula?', type: 'frage', category: 'eisbrecher' },
  { text: 'Qual e l\'ultimo posto nuovo che hai visitato?', type: 'frage', category: 'eisbrecher' },
  { text: 'Pizza con o senza ananas? Spiega.', type: 'frage', category: 'eisbrecher' },
  { text: 'Qual e la cosa che ti rilassa di piu dopo una giornata pesante?', type: 'frage', category: 'eisbrecher' },
  { text: 'Se potessi cenare con una persona del passato, chi sceglieresti?', type: 'frage', category: 'eisbrecher' },
  { text: 'Qual e il tuo piatto della nonna preferito?', type: 'frage', category: 'eisbrecher' },
  { text: 'Mare d\'estate o neve d\'inverno?', type: 'frage', category: 'eisbrecher' },
  { text: 'Qual e la prima cosa che noti in una persona?', type: 'frage', category: 'eisbrecher' },
  { text: 'Qual e il tuo posto preferito in casa?', type: 'frage', category: 'eisbrecher' },
  { text: 'Citta o campagna per vivere? Perche?', type: 'frage', category: 'eisbrecher' },
  { text: 'Qual e una piccola cosa che ti rende felice ogni giorno?', type: 'frage', category: 'eisbrecher' },
  { text: 'Qual e stato il tuo primo lavoro?', type: 'frage', category: 'eisbrecher' },
  { text: 'Presenta la persona alla tua sinistra come se fosse il tuo migliore amico da vent\'anni.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Racconta un fatto curioso su di te che ti distingue dagli altri.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Descrivi la tua giornata di ieri in una sola frase.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Trova una cosa in comune con ogni persona del gruppo.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Mostra l\'ultima foto che hai scattato e raccontane la storia.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Fai un complimento sincero alla persona di fronte.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Racconta come hai conosciuto la persona che ti ha invitato qui.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Disegna nell\'aria il tuo animale preferito e fai indovinare gli altri.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Di\' una parola che descrive l\'atmosfera di questa serata.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Racconta qual e il tuo posto preferito della tua citta.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Condividi un obiettivo che vuoi raggiungere quest\'anno.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Spiega cosa fai nella vita come se lo raccontassi a un bambino di 5 anni.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Racconta la tua materia preferita a scuola e quella che odiavi.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Di\' qual e la cosa piu bella che hai fatto nell\'ultimo mese.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Fai indovinare al gruppo il tuo hobby usando solo gesti.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Racconta un piccolo gesto gentile che qualcuno ha fatto per te di recente.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Descrivi la persona alla tua destra con tre aggettivi positivi.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Spiega perche secondo te sei stato invitato a questa festa.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Racconta la tua tradizione di famiglia preferita.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e la cosa piu inutile che sai fare benissimo?', type: 'frage', category: 'spass' },
  { text: 'Se la tua vita avesse una colonna sonora, quale sarebbe la sigla?', type: 'frage', category: 'spass' },
  { text: 'Qual e l\'emoji che usi di piu?', type: 'frage', category: 'spass' },
  { text: 'Qual e la scusa piu ridicola che hai usato per saltare qualcosa?', type: 'frage', category: 'spass' },
  { text: 'Se fossi un gusto di gelato, quale saresti?', type: 'frage', category: 'spass' },
  { text: 'Qual e la cosa piu strana che hai mangiato?', type: 'frage', category: 'spass' },
  { text: 'Quale supereroe saresti il peggiore a interpretare?', type: 'frage', category: 'spass' },
  { text: 'Qual e il fail tecnologico piu imbarazzante che ti e capitato?', type: 'frage', category: 'spass' },
  { text: 'Se potessi parlare con gli animali, con quale specie litigheresti subito?', type: 'frage', category: 'spass' },
  { text: 'Qual e la pubblicita che ti resta in testa per giorni?', type: 'frage', category: 'spass' },
  { text: 'Qual e la cosa piu da nonno/nonna che fai gia adesso?', type: 'frage', category: 'spass' },
  { text: 'Se la tua casa prendesse fuoco e fossero salvi tutti, quale oggetto inutile salveresti?', type: 'frage', category: 'spass' },
  { text: 'Qual e l\'autocorrettore piu imbarazzante che ti ha tradito?', type: 'frage', category: 'spass' },
  { text: 'Qual e la teoria del complotto piu assurda in cui hai quasi creduto?', type: 'frage', category: 'spass' },
  { text: 'Se potessi cancellare una moda dalla storia, quale sceglieresti?', type: 'frage', category: 'spass' },
  { text: 'Qual e la cosa piu costosa che hai rotto per sbaglio?', type: 'frage', category: 'spass' },
  { text: 'Imita come cammini quando pensi che nessuno ti guardi.', type: 'aufgabe', category: 'spass' },
  { text: 'Recita uno scioglilingua tre volte di fila senza sbagliare.', type: 'aufgabe', category: 'spass' },
  { text: 'Fai finta di essere un telecronista e commenta cosa sta facendo il gruppo.', type: 'aufgabe', category: 'spass' },
  { text: 'Parla per i prossimi due turni come se fossi un robot.', type: 'aufgabe', category: 'spass' },
  { text: 'Imita il rumore di tre elettrodomestici e fai indovinare gli altri.', type: 'aufgabe', category: 'spass' },
  { text: 'Fai la tua imitazione migliore di un politico qualsiasi.', type: 'aufgabe', category: 'spass' },
  { text: 'Inventa un nome buffo per ogni persona del gruppo.', type: 'aufgabe', category: 'spass' },
  { text: 'Canta una canzone famosa ma sostituendo tutte le parole con \'miao\'.', type: 'aufgabe', category: 'spass' },
  { text: 'Cammina come se il pavimento fosse fatto di lava.', type: 'aufgabe', category: 'spass' },
  { text: 'Fai una posa da statua e mantienila per un turno intero.', type: 'aufgabe', category: 'spass' },
  { text: 'Racconta una barzelletta: se nessuno ride, bevi un sorso.', type: 'aufgabe', category: 'spass' },
  { text: 'Imita un personaggio di un cartone animato fino a quando non lo indovinano.', type: 'aufgabe', category: 'spass' },
  { text: 'Fai una smorfia per ogni emozione che gli altri ti gridano.', type: 'aufgabe', category: 'spass' },
  { text: 'Mangia o bevi qualcosa facendo le facce di un food blogger esagerato.', type: 'aufgabe', category: 'spass' },
  { text: 'Parla solo facendo rime per il prossimo turno.', type: 'aufgabe', category: 'spass' },
  { text: 'Improvvisa una sigla di tre secondi per il gruppo e cantala.', type: 'aufgabe', category: 'spass' },
  { text: 'Fai vedere come balli quando sei da solo in cucina.', type: 'aufgabe', category: 'spass' },
  { text: 'Recita una frase drammatica come se fossi in una telenovela.', type: 'aufgabe', category: 'spass' },
  { text: 'Inventa una danza della pioggia e convinci almeno una persona a unirsi.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e la cosa piu folle che faresti per 100 euro?', type: 'frage', category: 'party' },
  { text: 'Chi del gruppo sopravvivrebbe piu a lungo a una festa di tre giorni?', type: 'frage', category: 'party' },
  { text: 'Qual e il tuo cocktail preferito da ordinare al bar?', type: 'frage', category: 'party' },
  { text: 'Chi del gruppo e il re o la regina della pista da ballo?', type: 'frage', category: 'party' },
  { text: 'Qual e stata la nottata in cui sei tornato a casa piu tardi?', type: 'frage', category: 'party' },
  { text: 'Chi del gruppo organizzerebbe la festa piu epica?', type: 'frage', category: 'party' },
  { text: 'Qual e la canzone che fa scatenare tutta la pista?', type: 'frage', category: 'party' },
  { text: 'Chi del gruppo e quello che chiude sempre per ultimo il locale?', type: 'frage', category: 'party' },
  { text: 'Qual e stata la festa piu costosa a cui sei andato?', type: 'frage', category: 'party' },
  { text: 'Chi del gruppo perde sempre il telefono quando esce?', type: 'frage', category: 'party' },
  { text: 'Qual e la peggior sbornia che ricordi?', type: 'frage', category: 'party' },
  { text: 'Chi del gruppo conosce sempre il buttafuori?', type: 'frage', category: 'party' },
  { text: 'Manda un messaggio vocale di 10 secondi cantando alla persona di fronte.', type: 'aufgabe', category: 'party' },
  { text: 'Distribuisci due sorsi e fai un brindisi a tema scelto dal gruppo.', type: 'aufgabe', category: 'party' },
  { text: 'Fai un balletto di 20 secondi insieme alla persona alla tua destra.', type: 'aufgabe', category: 'party' },
  { text: 'Inventa una regola assurda che tutti devono seguire per i prossimi 3 turni.', type: 'aufgabe', category: 'party' },
  { text: 'Imita il modo di ballare di una persona del gruppo e fai indovinare chi.', type: 'aufgabe', category: 'party' },
  { text: 'Lancia un trend: fai un gesto che tutti devono ripetere a ogni turno.', type: 'aufgabe', category: 'party' },
  { text: 'Brinda con un discorso epico di 15 secondi a chi sta organizzando la serata.', type: 'aufgabe', category: 'party' },
  { text: 'Scegli una persona: per il prossimo turno siete gemelli e dovete copiarvi i movimenti.', type: 'aufgabe', category: 'party' },
  { text: 'Fai partire un coro che tutto il gruppo deve cantare.', type: 'aufgabe', category: 'party' },
  { text: 'Scambia il posto con qualcuno e imita il suo modo di sedersi.', type: 'aufgabe', category: 'party' },
  { text: 'Crea un cocktail analcolico al volo e fallo assaggiare a qualcuno.', type: 'aufgabe', category: 'party' },
  { text: 'Fai una gara di sguardi seri con la persona di fronte: chi ride prima beve.', type: 'aufgabe', category: 'party' },
  { text: 'Indovina cosa sta bevendo la persona accanto solo annusando.', type: 'aufgabe', category: 'party' },
  { text: 'Fai una foto di gruppo con tutti che fanno la stessa posa ridicola.', type: 'aufgabe', category: 'party' },
  { text: 'Scegli una persona che dovra ripetere l\'ultima parola di ogni sua frase fino al prossimo turno.', type: 'aufgabe', category: 'party' },
  { text: 'Fai un balletto di benvenuto ogni volta che qualcuno torna dal bagno per i prossimi turni.', type: 'aufgabe', category: 'party' },
  { text: 'Distribuisci un sorso a tutti quelli che oggi hanno guardato il telefono piu di te.', type: 'aufgabe', category: 'party' },
  { text: 'Diventa il DJ del gruppo: scegli e fai partire la prossima canzone.', type: 'aufgabe', category: 'party' },
  { text: 'Proponi un brindisi a sorpresa e tutti devono inventare un motivo per cui festeggiare.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e il talento piu inutile della sposa o dello sposo?', type: 'frage', category: 'jga' },
  { text: 'Chi tra gli invitati piangera di piu durante la cerimonia?', type: 'frage', category: 'jga' },
  { text: 'Qual e l\'abitudine della sposa o dello sposo che il partner dovra sopportare per sempre?', type: 'frage', category: 'jga' },
  { text: 'Qual e stata la cotta adolescenziale piu imbarazzante della sposa o dello sposo?', type: 'frage', category: 'jga' },
  { text: 'Chi del gruppo conosce la sposa o lo sposo da piu tempo?', type: 'frage', category: 'jga' },
  { text: 'Qual e la festa piu folle che avete fatto insieme alla sposa o allo sposo?', type: 'frage', category: 'jga' },
  { text: 'Quale soprannome dell\'infanzia della sposa o dello sposo dovremmo conoscere tutti?', type: 'frage', category: 'jga' },
  { text: 'Chi e stato il peggior ex della sposa o dello sposo?', type: 'frage', category: 'jga' },
  { text: 'Qual e la bugia piu grande che la sposa o lo sposo ha raccontato ai genitori?', type: 'frage', category: 'jga' },
  { text: 'Chi del gruppo sara il primo a ubriacarsi al matrimonio?', type: 'frage', category: 'jga' },
  { text: 'Qual e la mania piu strana della sposa o dello sposo che pochi conoscono?', type: 'frage', category: 'jga' },
  { text: 'Chi tra gli amici fara il discorso piu commovente al matrimonio?', type: 'frage', category: 'jga' },
  { text: 'Qual e stata la peggiore decisione di moda della sposa o dello sposo?', type: 'frage', category: 'jga' },
  { text: 'Quale promessa avete giurato di mantenere segreta sulla sposa o sullo sposo?', type: 'frage', category: 'jga' },
  { text: 'Componi un brindisi imbarazzante per la sposa o lo sposo e recitalo in piedi.', type: 'aufgabe', category: 'jga' },
  { text: 'Chiama un parente della sposa o dello sposo e racconta un aneddoto divertente.', type: 'aufgabe', category: 'jga' },
  { text: 'Inventa e canta una canzone d\'amore dedicata alla coppia.', type: 'aufgabe', category: 'jga' },
  { text: 'Disegna come immagini la coppia tra 30 anni e mostra il risultato.', type: 'aufgabe', category: 'jga' },
  { text: 'Fai una previsione su quanti figli avra la coppia e perche.', type: 'aufgabe', category: 'jga' },
  { text: 'Recita la dichiarazione d\'amore che la sposa o lo sposo dovrebbe fare al matrimonio.', type: 'aufgabe', category: 'jga' },
  { text: 'Imita la sposa o lo sposo in una situazione tipica e fai indovinare la scena.', type: 'aufgabe', category: 'jga' },
  { text: 'Crea un decalogo di sopravvivenza per il futuro coniuge della sposa o dello sposo.', type: 'aufgabe', category: 'jga' },
  { text: 'Scrivi un messaggio d\'auguri di gruppo e fallo firmare da tutti.', type: 'aufgabe', category: 'jga' },
  { text: 'Trova uno sconosciuto che faccia gli auguri di matrimonio in video.', type: 'aufgabe', category: 'jga' },
  { text: 'Improvvisa il discorso del testimone come se fossi gia brillo.', type: 'aufgabe', category: 'jga' },
  { text: 'Crea una coreografia di 10 secondi per l\'ingresso degli sposi e insegnala al gruppo.', type: 'aufgabe', category: 'jga' },
  { text: 'Racconta la prima volta che hai pensato che questi due sarebbero finiti insieme.', type: 'aufgabe', category: 'jga' },
  { text: 'Inventa il titolo del film che racconterebbe la storia della coppia.', type: 'aufgabe', category: 'jga' },
  { text: 'Fai un selfie di gruppo a tema addio al celibato o nubilato e postalo.', type: 'aufgabe', category: 'jga' },
  { text: 'Proponi un brindisi e fai dire a ognuno una qualita della sposa o dello sposo.', type: 'aufgabe', category: 'jga' },
  { text: 'Racconta il regalo piu strano che faresti alla coppia per il matrimonio.', type: 'aufgabe', category: 'jga' },
  { text: 'Mima la prima notte di nozze come la immagini, in versione comica.', type: 'aufgabe', category: 'jga' },
  { text: 'Fai un sondaggio nel gruppo: chi indossera i pantaloni in questo matrimonio?', type: 'aufgabe', category: 'jga' },
  { text: 'Crea un hashtag perfetto per il matrimonio della coppia.', type: 'aufgabe', category: 'jga' },
  { text: 'Recita la scena del \'lo voglio\' con la persona accanto come se foste gli sposi.', type: 'aufgabe', category: 'jga' },
  { text: 'Racconta cosa pensi che la sposa o lo sposo combinera alla festa.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e la fantasia piu audace che ti sei mai concesso?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e il posto piu rischioso in cui hai pomiciato?', type: 'frage', category: 'erwachsene' },
  { text: 'Chi del gruppo bacerebbe meglio, secondo te?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e stata la tua bugia piu grossa per portarti a letto qualcuno?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e il complimento piu spinto che hai ricevuto?', type: 'frage', category: 'erwachsene' },
  { text: 'Boxer o slip? E perche e importante per te?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e stata l\'avventura di una notte piu memorabile?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e il tuo punto debole quando qualcuno ti corteggia?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e la cosa piu sfacciata che hai scritto in chat a qualcuno?', type: 'frage', category: 'erwachsene' },
  { text: 'Chi del gruppo ti incuriosisce di piu in questo momento?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e il momento piu hot che hai vissuto in vacanza?', type: 'frage', category: 'erwachsene' },
  { text: 'Quale parte del corpo noti per prima in una persona che ti attrae?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e la cosa piu folle che hai fatto per amore o per passione?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e il segreto piccante che non hai mai raccontato a nessuno qui?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e stato il flirt piu pericoloso a cui hai ceduto?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e la frase che ti fa cadere ai piedi di qualcuno?', type: 'frage', category: 'erwachsene' },
  { text: 'Hai mai mandato una foto piccante? Racconta come e andata.', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e la cosa piu osata che hai fatto in pubblico?', type: 'frage', category: 'erwachsene' },
  { text: 'Sussurra all\'orecchio della persona a sinistra il complimento piu spinto che ti viene.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Fai il tuo sguardo piu seducente alla persona di fronte per 15 secondi senza ridere.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Recita la tua frase di rimorchio migliore alla persona alla tua destra.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Manda un messaggio audace all\'ultima persona con cui hai chattato e leggi la risposta al gruppo.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Descrivi il tuo appuntamento ideale piccante nei minimi dettagli.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Mima la tua mossa di seduzione segreta e fai indovinare cosa significa.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Fai un complimento sensuale a ogni persona del gruppo, una per una.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Imita come ci provi con qualcuno che ti piace davvero.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Sussurra il tuo desiderio piu segreto alla persona accanto.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Scegli una persona del gruppo e racconta perche sarebbe un buon partito.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Recita una scena romantica da film con la persona di fronte.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Fai una classifica top 3 delle qualita che cerchi in un amante.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Dai un voto da 1 a 10 al tuo livello di sfacciataggine e racconta un episodio che lo dimostra.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Manda un messaggio sfacciato a qualcuno fuori dal gruppo e condividi cosa succede.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Descrivi al gruppo la situazione piu romantica che vorresti vivere.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Fai il tuo ballo piu seducente per 10 secondi davanti al gruppo.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Confessa al gruppo quale sguardo o gesto ti fa perdere completamente la testa.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Scegli la persona del gruppo con cui andresti a un appuntamento e spiega perche.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Racconta la cosa piu imbarazzante che ti e successa sotto le lenzuola, se hai coraggio.', type: 'aufgabe', category: 'erwachsene' },
];
