export type BottleCategory = 'spass' | 'party' | 'jga' | 'erwachsene' | 'eisbrecher';
export type CardType = 'frage' | 'aufgabe';
export interface BottleCard { text: string; type: CardType; category: BottleCategory; }
export const CATEGORY_META: Record<BottleCategory, { name: string; emoji: string; color: string }> = {
  spass: { name: 'Divertimento', emoji: '😂', color: '#f59e0b' },
  party: { name: 'Festa', emoji: '🎉', color: '#ef4444' },
  jga: { name: 'Addio al celibato', emoji: '💍', color: '#ec4899' },
  erwachsene: { name: 'Adulti 18+', emoji: '🔥', color: '#f97316' },
  eisbrecher: { name: 'Rompighiaccio', emoji: '🧊', color: '#06b6d4' },
};
export const BOTTLE_CARDS: BottleCard[] = [
  { text: 'Racconta il tuo momento piu imbarazzante.', type: 'frage', category: 'spass' },
  { text: 'Fai il tuo miglior verso animale.', type: 'aufgabe', category: 'spass' },
  { text: 'Mostra la foto piu vecchia del tuo telefono.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e stato il tuo peggior appuntamento?', type: 'frage', category: 'spass' },
  { text: 'Imita un personaggio famoso — gli altri devono indovinare.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e la cosa piu stupida che hai comprato?', type: 'frage', category: 'spass' },
  { text: 'Canta il ritornello della tua canzone preferita.', type: 'aufgabe', category: 'spass' },
  { text: 'Mostra la tua chat piu divertente.', type: 'aufgabe', category: 'spass' },
  { text: 'Che soprannome avevi da bambino?', type: 'frage', category: 'spass' },
  { text: 'Balla 15 secondi senza musica.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e il messaggio piu imbarazzante inviato alla persona sbagliata?', type: 'frage', category: 'spass' },
  { text: 'Fai un selfie con la faccia piu buffa e condividilo.', type: 'aufgabe', category: 'spass' },
  { text: 'Racconta una bugia — gli altri devono indovinare se e vera.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e la canzone piu imbarazzante nella tua playlist?', type: 'frage', category: 'spass' },
  { text: 'Parla con un accento inventato per 1 minuto.', type: 'aufgabe', category: 'spass' },
  { text: 'Quale video YouTube hai guardato piu spesso?', type: 'frage', category: 'spass' },
  { text: 'Prova a non ridere per 30 secondi — gli altri possono fare di tutto.', type: 'aufgabe', category: 'spass' },
  { text: 'Cosa faresti se fossi invisibile per un giorno?', type: 'frage', category: 'spass' },
  { text: 'Scambia la tua foto profilo con la persona accanto.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e stato il tuo piu grande fail in cucina?', type: 'frage', category: 'spass' },
  { text: 'Fai un moonwalk per la stanza.', type: 'aufgabe', category: 'spass' },
  { text: 'Quale serie hai guardato di nascosto?', type: 'frage', category: 'spass' },
  { text: 'Lascia che la persona accanto posti una storia sul tuo Instagram.', type: 'aufgabe', category: 'spass' },
  { text: 'Cosa c\'e di piu strano nel tuo frigo?', type: 'frage', category: 'spass' },
  { text: 'Tieni un discorso di 30 secondi sulla carta igienica.', type: 'aufgabe', category: 'spass' },
  { text: 'Quali 3 cose porteresti su un\'isola deserta?', type: 'frage', category: 'spass' },
  { text: 'Fai il verso del gallo — piu forte che puoi.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e il tuo talento segreto?', type: 'frage', category: 'spass' },
  { text: 'Cammina all\'indietro per la stanza.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e il sogno piu strano che hai fatto?', type: 'frage', category: 'spass' },
  { text: 'Bevi un sorso ad occhi chiusi.', type: 'aufgabe', category: 'party' },
  { text: 'Scambia un capo d\'abbigliamento con il vicino.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e stata la festa piu pazza?', type: 'frage', category: 'party' },
  { text: 'Mescola un nuovo drink e assaggialo!', type: 'aufgabe', category: 'party' },
  { text: 'Quale canzone ti fa sempre ballare?', type: 'frage', category: 'party' },
  { text: 'Sfida qualcuno a braccio di ferro.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e stato il momento piu ubriaco della tua vita?', type: 'frage', category: 'party' },
  { text: 'Bevi ogni volta che qualcuno dice il tuo nome — prossimi 3 turni.', type: 'aufgabe', category: 'party' },
  { text: 'Con chi del gruppo vorresti passare la serata?', type: 'frage', category: 'party' },
  { text: 'Fai un ballo di TikTok.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e la cosa piu coraggiosa che hai fatto a una festa?', type: 'frage', category: 'party' },
  { text: 'Sussurra tutto per i prossimi 2 turni.', type: 'aufgabe', category: 'party' },
  { text: 'Chi del gruppo regge meno l\'alcol?', type: 'frage', category: 'party' },
  { text: 'Chiama qualcuno e dì: "Sono alla migliore festa del mondo!"', type: 'aufgabe', category: 'party' },
  { text: 'Qual e il tuo rituale prima di uscire?', type: 'frage', category: 'party' },
  { text: 'Distribuisci 3 sorsi a chi vuoi.', type: 'aufgabe', category: 'party' },
  { text: 'Racconta la tua esperienza piu imbarazzante a una festa.', type: 'frage', category: 'party' },
  { text: 'Fai un trenino — tutti devono unirsi.', type: 'aufgabe', category: 'party' },
  { text: 'Quale DJ o artista e sulla tua bucket list?', type: 'frage', category: 'party' },
  { text: 'Registrati mentre fai beatbox per 5 secondi.', type: 'aufgabe', category: 'party' },
  { text: 'Racconta la storia piu divertente sulla sposa/sullo sposo.', type: 'frage', category: 'jga' },
  { text: 'Chiama una persona a caso e falle le congratulazioni per il matrimonio.', type: 'aufgabe', category: 'jga' },
  { text: 'Cosa pensi che fara la coppia tra 10 anni?', type: 'frage', category: 'jga' },
  { text: 'Manda alla sposa/allo sposo un messaggio imbarazzante.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e stata la tua prima impressione del partner?', type: 'frage', category: 'jga' },
  { text: 'Impara un passo del ballo nuziale e fallo.', type: 'aufgabe', category: 'jga' },
  { text: 'Chi ha pianto di piu quando e stato annunciato il matrimonio?', type: 'frage', category: 'jga' },
  { text: 'Scatta una foto che sembra un servizio di nozze.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e il miglior consiglio matrimoniale che puoi dare?', type: 'frage', category: 'jga' },
  { text: 'Fai un mini discorso di nozze.', type: 'aufgabe', category: 'jga' },
  { text: 'Racconta il ricordo piu imbarazzante con la sposa/lo sposo.', type: 'frage', category: 'jga' },
  { text: 'Invita uno sconosciuto al matrimonio.', type: 'aufgabe', category: 'jga' },
  { text: 'Cosa regaleresti alla coppia come regalo di nozze?', type: 'frage', category: 'jga' },
  { text: 'Registra un video di auguri di 15 secondi.', type: 'aufgabe', category: 'jga' },
  { text: 'Quale canzone descrive meglio la relazione della coppia?', type: 'frage', category: 'jga' },
  { text: 'Trova uno sconosciuto che dica "Si, lo voglio!" e filmalo.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e la cosa piu fastidiosa della sposa/dello sposo?', type: 'frage', category: 'jga' },
  { text: 'Organizza una foto di gruppo spontanea.', type: 'aufgabe', category: 'jga' },
  { text: 'Come ha raccontato la sposa/lo sposo la proposta?', type: 'frage', category: 'jga' },
  { text: 'Scrivi una profezia matrimoniale su un tovagliolo.', type: 'aufgabe', category: 'jga' },
  { text: 'Descrivi il tuo peggior bacio.', type: 'frage', category: 'erwachsene' },
  { text: 'A chi del gruppo manderesti un messaggio alle 2 di notte?', type: 'frage', category: 'erwachsene' },
  { text: 'Qual e la cosa piu audace che hai mai fatto?', type: 'frage', category: 'erwachsene' },
  { text: 'Mostra l\'ultima chat di flirt sul tuo telefono.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e il tuo piu grande turn-off?', type: 'frage', category: 'erwachsene' },
  { text: 'Fai un complimento alla persona accanto che la faccia arrossire.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e la cosa piu seducente che qualcuno ti abbia detto?', type: 'frage', category: 'erwachsene' },
  { text: 'Fai la tua migliore faccia da flirt per 10 secondi.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e stato il tuo appuntamento piu imbarazzante?', type: 'frage', category: 'erwachsene' },
  { text: 'Sussurra qualcosa di audace alla persona alla tua destra.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Hai mai trovato attraente qualcuno di questo gruppo?', type: 'frage', category: 'erwachsene' },
  { text: 'Manda un messaggio audace a qualcuno — mostralo al gruppo.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e la tua cotta piu insolita?', type: 'frage', category: 'erwachsene' },
  { text: 'Lascia che la persona di fronte legga un messaggio del tuo telefono.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e la cosa piu pazza che hai vissuto a una festa?', type: 'frage', category: 'erwachsene' },
  { text: 'Racconta la storia del tuo primo bacio.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Se potessi uscire con una celebrita — chi sarebbe?', type: 'frage', category: 'erwachsene' },
  { text: 'Fai uno sguardo seducente e manda la foto al gruppo.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e stato il posto piu strano in cui hai baciato qualcuno?', type: 'frage', category: 'erwachsene' },
  { text: 'Condividi un segreto che nessuno qui conosce.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e il tuo guilty pleasure?', type: 'frage', category: 'eisbrecher' },
  { text: 'Se avessi un superpotere, quale sarebbe?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cosa volevi fare da grande?', type: 'frage', category: 'eisbrecher' },
  { text: 'Nomina una cosa della tua bucket list.', type: 'frage', category: 'eisbrecher' },
  { text: 'Qual e la cosa migliore che ti e successa quest\'anno?', type: 'frage', category: 'eisbrecher' },
  { text: 'Condividi qualcosa che nessuno qui dovrebbe sapere.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e il tuo piatto preferito e perche?', type: 'frage', category: 'eisbrecher' },
  { text: 'Fai una domanda personale alla persona accanto.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Se potessi vivere ovunque, dove andresti?', type: 'frage', category: 'eisbrecher' },
  { text: 'Descriviti in tre parole.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e l\'ultimo libro o podcast che ti ha ispirato?', type: 'frage', category: 'eisbrecher' },
  { text: 'Di qualcosa di carino a ciascuno del gruppo.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e la tua opinione piu impopolare?', type: 'frage', category: 'eisbrecher' },
  { text: 'Condividi un ricordo divertente dell\'infanzia.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Se fossi un animale, quale saresti e perche?', type: 'frage', category: 'eisbrecher' },
  { text: 'Mostra al gruppo l\'ultimo meme che hai inviato.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e la tua citazione o motto preferito?', type: 'frage', category: 'eisbrecher' },
  { text: 'Fai un complimento alla persona che conosci meno.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e il viaggio migliore che hai fatto?', type: 'frage', category: 'eisbrecher' },
  { text: 'Racconta un momento che ha cambiato la tua vita.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Quale abilita vorresti imparare?', type: 'frage', category: 'eisbrecher' },
  { text: 'Dai un soprannome alla persona di fronte per la serata.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e la tua canzone preferita del momento e perche?', type: 'frage', category: 'eisbrecher' },
  { text: 'Racconta cosa hai fatto appena sveglio stamattina.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e il miglior consiglio che hai ricevuto?', type: 'frage', category: 'eisbrecher' },
  { text: 'Presentati come un personaggio di un film.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cosa ti rende veramente felice?', type: 'frage', category: 'eisbrecher' },
  { text: 'Nomina 3 cose che tu e la persona accanto avete in comune.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Se avessi una macchina del tempo, dove andresti?', type: 'frage', category: 'eisbrecher' },
  { text: 'Racconta la tua migliore esperienza con uno sconosciuto.', type: 'aufgabe', category: 'eisbrecher' },
];
