export type BottleCategory = 'spass' | 'party' | 'jga' | 'erwachsene' | 'eisbrecher';
export type CardType = 'frage' | 'aufgabe';
export interface BottleCard { text: string; type: CardType; category: BottleCategory; }
export const CATEGORY_META: Record<BottleCategory, { name: string; emoji: string; color: string }> = {
  spass: { name: 'Diversao', emoji: '😂', color: '#f59e0b' },
  party: { name: 'Festa', emoji: '🎉', color: '#ef4444' },
  jga: { name: 'Despedida', emoji: '💍', color: '#ec4899' },
  erwachsene: { name: 'Adultos 18+', emoji: '🔥', color: '#f97316' },
  eisbrecher: { name: 'Quebra-gelo', emoji: '🧊', color: '#06b6d4' },
};
export const BOTTLE_CARDS: BottleCard[] = [
  { text: 'Conta o teu momento mais embaracoso.', type: 'frage', category: 'spass' },{ text: 'Faz a tua melhor imitacao de animal.', type: 'aufgabe', category: 'spass' },{ text: 'Mostra a foto mais antiga do teu telemovel.', type: 'aufgabe', category: 'spass' },{ text: 'Qual foi o teu pior encontro?', type: 'frage', category: 'spass' },{ text: 'Imita uma pessoa famosa — os outros devem adivinhar.', type: 'aufgabe', category: 'spass' },{ text: 'Qual e a coisa mais estupida que compraste?', type: 'frage', category: 'spass' },{ text: 'Canta o refrao da tua musica favorita.', type: 'aufgabe', category: 'spass' },{ text: 'Mostra o teu chat mais engracado.', type: 'aufgabe', category: 'spass' },{ text: 'Que alcunha tinhas em crianca?', type: 'frage', category: 'spass' },{ text: 'Danca 15 segundos sem musica.', type: 'aufgabe', category: 'spass' },{ text: 'Qual e a mensagem mais embaracosa que enviaste a pessoa errada?', type: 'frage', category: 'spass' },{ text: 'Tira uma selfie com a cara mais engracada e partilha.', type: 'aufgabe', category: 'spass' },{ text: 'Conta uma mentira — os outros devem adivinhar se e verdade.', type: 'aufgabe', category: 'spass' },{ text: 'Qual e a musica mais embaracosa na tua playlist?', type: 'frage', category: 'spass' },{ text: 'Fala com um sotaque inventado durante 1 minuto.', type: 'aufgabe', category: 'spass' },{ text: 'Que video do YouTube viste mais vezes?', type: 'frage', category: 'spass' },{ text: 'Tenta nao rir durante 30 segundos — os outros podem tentar tudo.', type: 'aufgabe', category: 'spass' },{ text: 'O que farias se fosses invisivel por um dia?', type: 'frage', category: 'spass' },{ text: 'Troca a tua foto de perfil com a pessoa ao lado.', type: 'aufgabe', category: 'spass' },{ text: 'Qual foi o teu maior fail na cozinha?', type: 'frage', category: 'spass' },{ text: 'Faz um moonwalk pela sala.', type: 'aufgabe', category: 'spass' },{ text: 'Que serie viste em segredo de uma vez?', type: 'frage', category: 'spass' },{ text: 'Deixa a pessoa ao lado postar uma story no teu Instagram.', type: 'aufgabe', category: 'spass' },{ text: 'O que ha de mais estranho no teu frigorifico?', type: 'frage', category: 'spass' },{ text: 'Faz um discurso de 30 segundos sobre papel higienico.', type: 'aufgabe', category: 'spass' },{ text: 'Que 3 coisas levarias para uma ilha deserta?', type: 'frage', category: 'spass' },{ text: 'Imita o canto de um galo — o mais alto que conseguires.', type: 'aufgabe', category: 'spass' },{ text: 'Qual e o teu talento secreto que ninguem conhece?', type: 'frage', category: 'spass' },{ text: 'Anda para tras pela sala.', type: 'aufgabe', category: 'spass' },{ text: 'Qual foi o sonho mais estranho que tiveste?', type: 'frage', category: 'spass' },
  { text: 'Bebe um gole de olhos fechados.', type: 'aufgabe', category: 'party' },{ text: 'Troca uma peca de roupa com o vizinho.', type: 'aufgabe', category: 'party' },{ text: 'Qual foi a festa mais louca?', type: 'frage', category: 'party' },{ text: 'Mistura um novo drink e prova-o!', type: 'aufgabe', category: 'party' },{ text: 'Que musica te faz sempre dancar?', type: 'frage', category: 'party' },{ text: 'Desafia alguem para queda de braco.', type: 'aufgabe', category: 'party' },{ text: 'Qual foi o momento mais bebado da tua vida?', type: 'frage', category: 'party' },{ text: 'Bebe cada vez que alguem disser o teu nome — proximas 3 rondas.', type: 'aufgabe', category: 'party' },{ text: 'Com quem do grupo gostarias de passar a noite?', type: 'frage', category: 'party' },{ text: 'Faz uma danca de TikTok.', type: 'aufgabe', category: 'party' },{ text: 'Qual e a coisa mais corajosa que fizeste numa festa?', type: 'frage', category: 'party' },{ text: 'Nas proximas 2 rondas so podes sussurrar.', type: 'aufgabe', category: 'party' },{ text: 'Quem do grupo aguenta menos a bebida?', type: 'frage', category: 'party' },{ text: 'Liga a alguem e diz: "Estou na melhor festa do mundo!"', type: 'aufgabe', category: 'party' },{ text: 'Qual e o teu ritual antes de sair?', type: 'frage', category: 'party' },{ text: 'Distribui 3 goles a quem quiseres.', type: 'aufgabe', category: 'party' },{ text: 'Conta a tua experiencia mais embaracosa numa festa.', type: 'frage', category: 'party' },{ text: 'Comeca uma conga — todos devem participar.', type: 'aufgabe', category: 'party' },{ text: 'Que DJ ou artista esta na tua bucket list?', type: 'frage', category: 'party' },{ text: 'Grava-te a fazer beatbox durante 5 segundos.', type: 'aufgabe', category: 'party' },
  { text: 'Conta a historia mais engracada sobre a noiva/noivo.', type: 'frage', category: 'jga' },{ text: 'Liga a uma pessoa aleatoria e da-lhe os parabens pelo casamento.', type: 'aufgabe', category: 'jga' },{ text: 'O que achas que o casal estara a fazer daqui a 10 anos?', type: 'frage', category: 'jga' },{ text: 'Envia a noiva/noivo uma mensagem embaracosa.', type: 'aufgabe', category: 'jga' },{ text: 'Qual foi a tua primeira impressao do parceiro?', type: 'frage', category: 'jga' },{ text: 'Aprende um passo de danca de casamento e executa-o.', type: 'aufgabe', category: 'jga' },{ text: 'Quem chorou mais quando o casamento foi anunciado?', type: 'frage', category: 'jga' },{ text: 'Tira uma foto que pareca uma sessao de casamento.', type: 'aufgabe', category: 'jga' },{ text: 'Qual e o melhor conselho de casamento que podes dar?', type: 'frage', category: 'jga' },{ text: 'Faz um mini discurso de casamento.', type: 'aufgabe', category: 'jga' },{ text: 'Conta a memoria mais embaracosa com a noiva/noivo.', type: 'frage', category: 'jga' },{ text: 'Convida um desconhecido para o casamento.', type: 'aufgabe', category: 'jga' },{ text: 'O que darias ao casal como presente de casamento?', type: 'frage', category: 'jga' },{ text: 'Grava um video de felicitacoes de 15 segundos.', type: 'aufgabe', category: 'jga' },{ text: 'Que musica descreve melhor a relacao do casal?', type: 'frage', category: 'jga' },{ text: 'Encontra um desconhecido que diga "Sim, aceito!" e filma.', type: 'aufgabe', category: 'jga' },{ text: 'O que e mais irritante na noiva/noivo?', type: 'frage', category: 'jga' },{ text: 'Organiza uma foto de grupo espontanea.', type: 'aufgabe', category: 'jga' },{ text: 'Como e que a noiva/noivo contou a proposta?', type: 'frage', category: 'jga' },{ text: 'Escreve uma profecia de casamento num guardanapo.', type: 'aufgabe', category: 'jga' },
  { text: 'Descreve o teu pior beijo.', type: 'frage', category: 'erwachsene' },{ text: 'A quem do grupo mandarias mensagem as 2 da manha?', type: 'frage', category: 'erwachsene' },{ text: 'Qual e a coisa mais ousada que fizeste?', type: 'frage', category: 'erwachsene' },{ text: 'Mostra o ultimo chat de flirt no teu telemovel.', type: 'aufgabe', category: 'erwachsene' },{ text: 'Qual e o teu maior turn-off?', type: 'frage', category: 'erwachsene' },{ text: 'Faz um elogio a pessoa ao lado que a faca corar.', type: 'aufgabe', category: 'erwachsene' },{ text: 'Qual e a coisa mais sedutora que alguem te disse?', type: 'frage', category: 'erwachsene' },{ text: 'Faz a tua melhor cara de flirt e mantem durante 10 segundos.', type: 'aufgabe', category: 'erwachsene' },{ text: 'Qual foi o teu encontro mais embaracoso?', type: 'frage', category: 'erwachsene' },{ text: 'Sussurra algo atrevido a pessoa a tua direita.', type: 'aufgabe', category: 'erwachsene' },{ text: 'Ja achaste alguem deste grupo atraente?', type: 'frage', category: 'erwachsene' },{ text: 'Envia uma mensagem atrevida a alguem — mostra ao grupo.', type: 'aufgabe', category: 'erwachsene' },{ text: 'Qual e o teu crush mais incomum?', type: 'frage', category: 'erwachsene' },{ text: 'Deixa a pessoa a frente ler uma mensagem do teu telemovel.', type: 'aufgabe', category: 'erwachsene' },{ text: 'Qual e a coisa mais louca que viveste numa festa?', type: 'frage', category: 'erwachsene' },{ text: 'Conta a historia do teu primeiro beijo.', type: 'aufgabe', category: 'erwachsene' },{ text: 'Se pudesses sair com um famoso — quem?', type: 'frage', category: 'erwachsene' },{ text: 'Faz um olhar sedutor e envia a foto ao grupo.', type: 'aufgabe', category: 'erwachsene' },{ text: 'Qual foi o lugar mais estranho onde beijaste alguem?', type: 'frage', category: 'erwachsene' },{ text: 'Partilha um segredo que ninguem aqui sabe.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e o teu guilty pleasure?', type: 'frage', category: 'eisbrecher' },{ text: 'Se tivesses um superpoder, qual seria?', type: 'frage', category: 'eisbrecher' },{ text: 'O que querias ser em crianca?', type: 'frage', category: 'eisbrecher' },{ text: 'Diz uma coisa da tua bucket list.', type: 'frage', category: 'eisbrecher' },{ text: 'Qual e a melhor coisa que te aconteceu este ano?', type: 'frage', category: 'eisbrecher' },{ text: 'Partilha algo que ninguem aqui deveria saber.', type: 'aufgabe', category: 'eisbrecher' },{ text: 'Qual e o teu prato favorito e porque?', type: 'frage', category: 'eisbrecher' },{ text: 'Faz uma pergunta pessoal a pessoa ao lado.', type: 'aufgabe', category: 'eisbrecher' },{ text: 'Se pudesses viver em qualquer lugar do mundo, onde?', type: 'frage', category: 'eisbrecher' },{ text: 'Descreve-te em tres palavras.', type: 'aufgabe', category: 'eisbrecher' },{ text: 'Qual foi o ultimo livro ou podcast que te inspirou?', type: 'frage', category: 'eisbrecher' },{ text: 'Diz algo simpatico a cada pessoa do grupo.', type: 'aufgabe', category: 'eisbrecher' },{ text: 'Qual e a tua opiniao mais impopular?', type: 'frage', category: 'eisbrecher' },{ text: 'Partilha uma memoria engracada de infancia.', type: 'aufgabe', category: 'eisbrecher' },{ text: 'Se fosses um animal, qual serias e porque?', type: 'frage', category: 'eisbrecher' },{ text: 'Mostra ao grupo o ultimo meme que enviaste.', type: 'aufgabe', category: 'eisbrecher' },{ text: 'Qual e a tua citacao ou lema favorito?', type: 'frage', category: 'eisbrecher' },{ text: 'Faz um elogio a pessoa que menos conheces.', type: 'aufgabe', category: 'eisbrecher' },{ text: 'Qual foi a melhor viagem que fizeste?', type: 'frage', category: 'eisbrecher' },{ text: 'Conta um momento que mudou a tua vida.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e a app que mais usas e que terias vergonha de admitir?', type: 'frage', category: 'spass' },
  { text: 'Faz de conta que es um apresentador de televendas e vende o objeto mais proximo de ti.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual foi a desculpa mais ridicula que ja deste para faltar a algo?', type: 'frage', category: 'spass' },
  { text: 'Imita a forma como o teu chefe ou professor fala.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e o emoji que usas a mais?', type: 'frage', category: 'spass' },
  { text: 'Diz o alfabeto ao contrario o mais rapido que conseguires.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual foi a tua maior obsessao quando eras adolescente?', type: 'frage', category: 'spass' },
  { text: 'Faz uma cara de assustado e mantem-na ate ser a tua vez outra vez.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e a coisa mais inutil que sabes fazer?', type: 'frage', category: 'spass' },
  { text: 'Fala como uma personagem de desenho animado durante a proxima ronda.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual foi a moda dos anos passados de que mais te arrependes?', type: 'frage', category: 'spass' },
  { text: 'Mostra o ultimo video que gravaste no telemovel.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e o pior corte de cabelo que ja tiveste?', type: 'frage', category: 'spass' },
  { text: 'Inventa um anuncio de radio para o teu prato favorito.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual foi a mentira mais inocente que contaste aos teus pais?', type: 'frage', category: 'spass' },
  { text: 'Faz a tua melhor imitacao de uma pessoa a dormir e a ressonar.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e o filme que finges ter visto mas nunca viste?', type: 'frage', category: 'spass' },
  { text: 'Anda pela sala como se fosses um modelo numa passerelle.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e o som que mais te irrita no mundo?', type: 'frage', category: 'spass' },
  { text: 'Conta uma piada e se ninguem rir, bebe um gole.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual foi a coisa mais estranha que comeste por curiosidade?', type: 'frage', category: 'spass' },
  { text: 'Faz a tua melhor pose de super-heroi durante 10 segundos.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e a tua manha mais embaracosa de quando estas sozinho?', type: 'frage', category: 'spass' },
  { text: 'Le a tua ultima mensagem enviada com voz de noticiario.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual foi a maior aldrabice que pregaste a alguem no 1 de abril?', type: 'frage', category: 'spass' },
  { text: 'Imita o teu animal de estimacao ou um que gostarias de ter.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e o objeto mais inutil que tens em casa mas nao deitas fora?', type: 'frage', category: 'spass' },
  { text: 'Inventa uma palavra nova e usa-a numa frase com toda a seriedade.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e a serie infantil que ainda verias hoje sem vergonha?', type: 'frage', category: 'spass' },
  { text: 'Faz beatbox enquanto outra pessoa canta o refrao de uma musica.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual foi o presente mais estranho que ja recebeste?', type: 'frage', category: 'spass' },
  { text: 'Descreve o teu dia de hoje so com mimica.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e a teoria da conspiracao mais maluca em que quase acreditaste?', type: 'frage', category: 'spass' },
  { text: 'Faz a tua melhor imitacao de um comentador de futebol a narrar a sala.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual foi a coisa mais cara que partiste sem querer?', type: 'frage', category: 'spass' },
  { text: 'Canta tudo o que disseres durante a proxima ronda como se fosse uma opera.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e o teu tique nervoso quando estas stressado?', type: 'frage', category: 'spass' },
  { text: 'Faz uma cara feliz e uma cara triste a alternar cinco vezes muito rapido.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual foi a tua maior gafe a falar uma lingua estrangeira?', type: 'frage', category: 'spass' },
  { text: 'Inventa uma danca para o nome da pessoa a tua esquerda.', type: 'aufgabe', category: 'spass' },
  { text: 'Qual e a coisa mais infantil que ainda fazes?', type: 'frage', category: 'party' },
  { text: 'Bebe um gole sempre que alguem cruzar os bracos na proxima ronda.', type: 'aufgabe', category: 'party' },
  { text: 'Qual foi a melhor noite de sempre que nunca conseguiste repetir?', type: 'frage', category: 'party' },
  { text: 'Escolhe uma pessoa para ser o teu gemeo e copiem-se um ao outro ate a tua proxima vez.', type: 'aufgabe', category: 'party' },
  { text: 'Quem do grupo seria o primeiro a desaparecer numa festa?', type: 'frage', category: 'party' },
  { text: 'Faz um brinde dramatico ao grupo e todos tem de beber.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e a tua bebida de assinatura numa festa?', type: 'frage', category: 'party' },
  { text: 'Da o teu telemovel a uma pessoa para escolher a proxima musica.', type: 'aufgabe', category: 'party' },
  { text: 'Qual foi a ressaca mais epica que ja tiveste?', type: 'frage', category: 'party' },
  { text: 'Inventa um grito de guerra para o grupo e fa-lo gritar contigo.', type: 'aufgabe', category: 'party' },
  { text: 'Quem do grupo e mais provavel acordar num sitio desconhecido?', type: 'frage', category: 'party' },
  { text: 'Imita como cada pessoa do grupo danca.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e a desculpa que mais usas para ir embora cedo de uma festa?', type: 'frage', category: 'party' },
  { text: 'Bebe sem usar as maos durante esta ronda.', type: 'aufgabe', category: 'party' },
  { text: 'Qual foi a coisa mais cara que pagaste numa noite de copos?', type: 'frage', category: 'party' },
  { text: 'Faz uma pose de estatua e ninguem te pode mexer durante 20 segundos.', type: 'aufgabe', category: 'party' },
  { text: 'Quem do grupo conta sempre as melhores histórias?', type: 'frage', category: 'party' },
  { text: 'Da dois goles a quem te fez rir mais esta noite.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e a tua musica garantida para encher a pista de danca?', type: 'frage', category: 'party' },
  { text: 'Os proximos dois jogadores tem de falar so a cantar ate a tua proxima vez.', type: 'aufgabe', category: 'party' },
  { text: 'Qual foi a maior aposta louca que aceitaste numa festa?', type: 'frage', category: 'party' },
  { text: 'Escolhe uma palavra proibida e quem a disser bebe ate ao fim da ronda.', type: 'aufgabe', category: 'party' },
  { text: 'Quem do grupo e o melhor a fingir que esta sobrio?', type: 'frage', category: 'party' },
  { text: 'Troca de lugar com alguem e imita-o ate a tua proxima vez.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e a coisa mais espontanea que ja fizeste a meio de uma festa?', type: 'frage', category: 'party' },
  { text: 'Tira uma foto de grupo com a pose mais ridicula possivel.', type: 'aufgabe', category: 'party' },
  { text: 'Qual foi a festa de aniversario mais memoravel da tua vida?', type: 'frage', category: 'party' },
  { text: 'Faz de DJ e anuncia a proxima musica como num festival.', type: 'aufgabe', category: 'party' },
  { text: 'Quem do grupo seria expulso primeiro de uma discoteca?', type: 'frage', category: 'party' },
  { text: 'Bebe sempre que rires nos proximos cinco minutos.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e o teu petisco favorito para acompanhar as bebidas?', type: 'frage', category: 'party' },
  { text: 'Da um abraco a cada pessoa do grupo enquanto dizes algo simpatico.', type: 'aufgabe', category: 'party' },
  { text: 'Qual foi a coisa mais embaracosa que perdeste numa festa?', type: 'frage', category: 'party' },
  { text: 'Escolhe dois jogadores para fazerem um duelo de mimica agora.', type: 'aufgabe', category: 'party' },
  { text: 'Quem do grupo da sempre as melhores festas?', type: 'frage', category: 'party' },
  { text: 'Conta ate dez numa lingua inventada com cara seria.', type: 'aufgabe', category: 'party' },
  { text: 'Qual foi a vez que mais te divertiste sem gastar nada?', type: 'frage', category: 'party' },
  { text: 'Faz uma maquina de fazer cafe com sons da boca.', type: 'aufgabe', category: 'party' },
  { text: 'Qual e a tua regra de ouro numa noite de copos?', type: 'frage', category: 'party' },
  { text: 'Escolhe um capitao da bebida que decide quem bebe na proxima ronda.', type: 'aufgabe', category: 'party' },
  { text: 'Como vai ser a despedida de solteiro ou solteira dos teus sonhos?', type: 'frage', category: 'jga' },
  { text: 'Faz um juramento solene de lealdade a noiva ou ao noivo de joelhos.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e a maior asneira que a noiva ou o noivo ja fez convosco?', type: 'frage', category: 'jga' },
  { text: 'Liga a um familiar do casal e pede uma historia embaracosa sobre eles.', type: 'aufgabe', category: 'jga' },
  { text: 'Que conselho darias para sobreviver ao primeiro ano de casamento?', type: 'frage', category: 'jga' },
  { text: 'Faz um brinde improvisado a noiva ou ao noivo com lagrimas de fingir.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual foi a primeira coisa que pensaste quando conheceste o par?', type: 'frage', category: 'jga' },
  { text: 'Reencena o pedido de casamento com um voluntario do grupo.', type: 'aufgabe', category: 'jga' },
  { text: 'Que cancao deve tocar na entrada da noiva ou do noivo?', type: 'frage', category: 'jga' },
  { text: 'Escreve um voto de casamento ridiculo e le-o em voz alta.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e a mania da noiva ou do noivo que o par vai ter de aturar para sempre?', type: 'frage', category: 'jga' },
  { text: 'Inventa uma danca de casal e ensina-a a outra pessoa.', type: 'aufgabe', category: 'jga' },
  { text: 'Quem do grupo vai chorar mais no dia do casamento?', type: 'frage', category: 'jga' },
  { text: 'Pede a um desconhecido para dar um conselho de casamento e filma.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual foi a fase mais maluca que viveste com a noiva ou o noivo?', type: 'frage', category: 'jga' },
  { text: 'Faz o discurso do padrinho ou da madrinha em 30 segundos.', type: 'aufgabe', category: 'jga' },
  { text: 'Que apelido carinhoso achas que o casal usa em privado?', type: 'frage', category: 'jga' },
  { text: 'Desenha o vestido ou o fato de casamento perfeito num guardanapo.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e a coisa que mais admiras na noiva ou no noivo?', type: 'frage', category: 'jga' },
  { text: 'Canta uma serenata romantica a noiva ou ao noivo agora mesmo.', type: 'aufgabe', category: 'jga' },
  { text: 'Como imaginas a lua de mel do casal?', type: 'frage', category: 'jga' },
  { text: 'Faz uma previsao sobre o futuro do casamento e escreve-a num papel.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual foi o momento em que percebeste que aquele era o par perfeito?', type: 'frage', category: 'jga' },
  { text: 'Convence um desconhecido a fazer um brinde a noiva ou ao noivo.', type: 'aufgabe', category: 'jga' },
  { text: 'Que nome dariam ao primeiro filho do casal se vos deixassem escolher?', type: 'frage', category: 'jga' },
  { text: 'Faz uma imitacao de como a noiva ou o noivo vai estar no altar.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual foi a maior surpresa que a noiva ou o noivo te fez?', type: 'frage', category: 'jga' },
  { text: 'Cria um slogan publicitario para o casamento e grita-o.', type: 'aufgabe', category: 'jga' },
  { text: 'Que tradicao de casamento achas mais ridicula?', type: 'frage', category: 'jga' },
  { text: 'Pede a tres pessoas para assinarem como testemunhas num guardanapo de casamento falso.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e a historia mais antiga que tens com a noiva ou o noivo?', type: 'frage', category: 'jga' },
  { text: 'Faz uma garrida coreografia de boas-vindas para o casal.', type: 'aufgabe', category: 'jga' },
  { text: 'Que prenda de casamento o casal vai detestar mas fingir gostar?', type: 'frage', category: 'jga' },
  { text: 'Grava uma mensagem de video para o casal ver no 10 aniversario de casamento.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e o maior segredo de amizade que partilhas com a noiva ou o noivo?', type: 'frage', category: 'jga' },
  { text: 'Inventa um voto comico em nome do par sem que ele saiba.', type: 'aufgabe', category: 'jga' },
  { text: 'Que musica nunca pode faltar na festa de casamento?', type: 'frage', category: 'jga' },
  { text: 'Faz uma fila de conga so com o grupo em honra da noiva ou do noivo.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual foi a viagem mais inesquecivel que fizeste com a noiva ou o noivo?', type: 'frage', category: 'jga' },
  { text: 'Escolhe a pessoa que faria o melhor par alternativo e justifica a brincar.', type: 'aufgabe', category: 'jga' },
  { text: 'Qual e a tua maior fantasia que nunca contaste a ninguem?', type: 'frage', category: 'erwachsene' },
  { text: 'Sussurra ao ouvido da pessoa a tua esquerda o teu pensamento mais atrevido de hoje.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual foi o sitio mais inesperado onde tiveste um momento intimo?', type: 'frage', category: 'erwachsene' },
  { text: 'Da um beijo na mao a pessoa que achas mais atraente do grupo.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e a tua maior tentacao que tentas sempre resistir?', type: 'frage', category: 'erwachsene' },
  { text: 'Faz a tua melhor cara de desejo a pessoa a tua frente durante 10 segundos.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual foi a coisa mais ousada que fizeste para impressionar alguem?', type: 'frage', category: 'erwachsene' },
  { text: 'Diz um elogio picante a pessoa a tua direita.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e o teu maior arrependimento amoroso?', type: 'frage', category: 'erwachsene' },
  { text: 'Demonstra como danças quando queres seduzir alguem.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual foi a paixoneta mais inconveniente que ja tiveste?', type: 'frage', category: 'erwachsene' },
  { text: 'Manda um piropo ousado a pessoa que escolheres do grupo.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e a coisa que te faz perder completamente a cabeca por alguem?', type: 'frage', category: 'erwachsene' },
  { text: 'Descreve o teu encontro ideal com todos os pormenores.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual foi a mensagem mais ousada que ja recebeste?', type: 'frage', category: 'erwachsene' },
  { text: 'Imita a tua melhor cantada como se estivesses num bar.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e o traco fisico que mais te atrai numa pessoa?', type: 'frage', category: 'erwachsene' },
  { text: 'Faz uma declaracao apaixonada a primeira pessoa a tua esquerda.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Ja te apaixonaste por alguem que nao devias?', type: 'frage', category: 'erwachsene' },
  { text: 'Mostra como morderias o labio de forma sedutora.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual foi o flirt mais arriscado que ja fizeste em publico?', type: 'frage', category: 'erwachsene' },
  { text: 'Da uma massagem de 20 segundos nos ombros da pessoa a tua direita.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e o teu maior segredo romantico que ninguem aqui sabe?', type: 'frage', category: 'erwachsene' },
  { text: 'Escolhe uma pessoa e diz-lhe ao ouvido o que mais te chama a atencao nela.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual foi a vez em que mais te sentiste desejado?', type: 'frage', category: 'erwachsene' },
  { text: 'Faz a tua melhor pose de capa de revista.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e a coisa mais romantica que farias por alguem de quem gostas?', type: 'frage', category: 'erwachsene' },
  { text: 'Conta a tua experiencia mais embaracosa numa primeira noite com alguem.', type: 'frage', category: 'erwachsene' },
  { text: 'Sopra um beijo a pessoa do grupo que escolheres.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e o teu maior tabu que nunca discutirias com a familia?', type: 'frage', category: 'erwachsene' },
  { text: 'Diz tres coisas que te deixam completamente irresistivel.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual foi o encontro mais quente da tua vida?', type: 'frage', category: 'erwachsene' },
  { text: 'Faz olhinhos sedutores para cada pessoa do grupo, um de cada vez.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e a tua opiniao sobre encontros de uma noite so?', type: 'frage', category: 'erwachsene' },
  { text: 'Recria a tua melhor cara de cinema antes de um beijo.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual foi a coisa mais corajosa que disseste a alguem de quem gostavas?', type: 'frage', category: 'erwachsene' },
  { text: 'Manda uma mensagem provocadora ao teu contacto preferido e mostra a resposta.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual e o teu maior fetiche secreto que ja confessaste a alguem?', type: 'frage', category: 'erwachsene' },
  { text: 'Faz a tua imitacao de alguem completamente apaixonado.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Qual foi o momento mais constrangedor que viveste num relacionamento?', type: 'frage', category: 'erwachsene' },
  { text: 'Como te chamas e qual e a tua historia favorita sobre o teu nome?', type: 'frage', category: 'eisbrecher' },
  { text: 'Diz a primeira palavra que te vem a cabeca quando olhas para a pessoa a tua esquerda.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e a tua bebida favorita para um dia em casa?', type: 'frage', category: 'eisbrecher' },
  { text: 'Cumprimenta cada pessoa do grupo de uma forma diferente.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual foi a melhor decisao que tomaste nos ultimos cinco anos?', type: 'frage', category: 'eisbrecher' },
  { text: 'Partilha uma coisa que tens em comum com a pessoa a tua direita.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Es mais de manha ou mais de noite, e porque?', type: 'frage', category: 'eisbrecher' },
  { text: 'Conta ao grupo qual foi a primeira coisa que reparaste em cada um.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e o teu lugar favorito no mundo que ja visitaste?', type: 'frage', category: 'eisbrecher' },
  { text: 'Faz uma pergunta que sempre quiseste fazer a alguem deste grupo.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e o teu pequeno-almoco perfeito?', type: 'frage', category: 'eisbrecher' },
  { text: 'Diz um objetivo que queres alcancar ate ao fim do ano.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e a tua estacao do ano favorita e porque?', type: 'frage', category: 'eisbrecher' },
  { text: 'Apresenta a pessoa a tua esquerda como se fosse uma celebridade.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual foi a melhor refeicao que comeste recentemente?', type: 'frage', category: 'eisbrecher' },
  { text: 'Partilha um habito saudavel de que te orgulhas.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Cidade ou campo, e o que mais gostas em cada um?', type: 'frage', category: 'eisbrecher' },
  { text: 'Diz uma coisa que aprendeste recentemente que te surpreendeu.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e a tua forma favorita de relaxar ao fim de um dia longo?', type: 'frage', category: 'eisbrecher' },
  { text: 'Descreve o teu fim de semana ideal em tres frases.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual foi o melhor conselho que alguem ja te deu?', type: 'frage', category: 'eisbrecher' },
  { text: 'Diz uma coisa que admiras em cada pessoa do grupo.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e a tua serie ou filme favorito de todos os tempos?', type: 'frage', category: 'eisbrecher' },
  { text: 'Partilha qual seria a tua profissao dos sonhos sem limites.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Es uma pessoa de planos ou de improviso?', type: 'frage', category: 'eisbrecher' },
  { text: 'Conta uma tradicao da tua familia que adoras.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e a coisa mais simples que te faz feliz?', type: 'frage', category: 'eisbrecher' },
  { text: 'Diz qual super-poder escolherias e o que farias com ele.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e o teu hobby ou paixao fora do trabalho?', type: 'frage', category: 'eisbrecher' },
  { text: 'Partilha uma meta na tua lista de coisas a fazer antes de morrer.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual foi a viagem que mais gostavas de repetir?', type: 'frage', category: 'eisbrecher' },
  { text: 'Diz tres palavras que descrevem o ambiente deste grupo.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e o teu prato de conforto que comes quando estas em baixo?', type: 'frage', category: 'eisbrecher' },
  { text: 'Conta uma pequena vitoria que tiveste esta semana.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e a habilidade que mais gostarias de aprender?', type: 'frage', category: 'eisbrecher' },
  { text: 'Faz um elogio sincero a alguem que acabaste de conhecer hoje.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual e a tua cor favorita e que sentimento te transmite?', type: 'frage', category: 'eisbrecher' },
  { text: 'Partilha o que mais te deixa entusiasmado ultimamente.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Qual foi a melhor compra que fizeste este ano?', type: 'frage', category: 'eisbrecher' },
  { text: 'Diz uma coisa pela qual estas grato hoje.', type: 'aufgabe', category: 'eisbrecher' },
];
