// ---------------------------------------------------------------------------
// Flaschendrehen – German content (150+ cards across 5 categories)
// ---------------------------------------------------------------------------

export type BottleCategory = 'spass' | 'party' | 'jga' | 'erwachsene' | 'eisbrecher';
export type CardType = 'frage' | 'aufgabe';

export interface BottleCard {
  text: string;
  type: CardType;
  category: BottleCategory;
}

export const CATEGORY_META: Record<BottleCategory, { name: string; emoji: string; color: string }> = {
  spass: { name: 'Spass', emoji: '😂', color: '#f59e0b' },
  party: { name: 'Party', emoji: '🎉', color: '#ef4444' },
  jga: { name: 'JGA', emoji: '💍', color: '#ec4899' },
  erwachsene: { name: 'Erwachsene 18+', emoji: '🔥', color: '#f97316' },
  eisbrecher: { name: 'Eisbrecher', emoji: '🧊', color: '#06b6d4' },
};

export const BOTTLE_CARDS: BottleCard[] = [
  // -------------------------------------------------------------------------
  // SPASS (30+)
  // -------------------------------------------------------------------------
  { text: 'Erzaehle deinen peinlichsten Moment.', type: 'frage', category: 'spass' },
  { text: 'Mach dein bestes Tiergeraeusch.', type: 'aufgabe', category: 'spass' },
  { text: 'Zeig dein aeltestes Foto auf deinem Handy.', type: 'aufgabe', category: 'spass' },
  { text: 'Was war dein schlimmstes Date?', type: 'frage', category: 'spass' },
  { text: 'Imitiere eine beruehmte Person – die anderen muessen raten.', type: 'aufgabe', category: 'spass' },
  { text: 'Was ist die duemmste Sache, die du jemals gekauft hast?', type: 'frage', category: 'spass' },
  { text: 'Singe den Refrain deines Lieblingssongs vor.', type: 'aufgabe', category: 'spass' },
  { text: 'Zeige deinen lustigsten Chat-Verlauf.', type: 'aufgabe', category: 'spass' },
  { text: 'Welchen Spitznamen hattest du als Kind?', type: 'frage', category: 'spass' },
  { text: 'Tanze 15 Sekunden lang ohne Musik.', type: 'aufgabe', category: 'spass' },
  { text: 'Was ist die peinlichste Nachricht, die du an die falsche Person geschickt hast?', type: 'frage', category: 'spass' },
  { text: 'Mach ein Selfie mit dem lustigsten Gesichtsausdruck und poste es in eure Gruppe.', type: 'aufgabe', category: 'spass' },
  { text: 'Erzaehle eine Luege und die anderen muessen raten, ob es stimmt.', type: 'aufgabe', category: 'spass' },
  { text: 'Was ist der peinlichste Song in deiner Playlist?', type: 'frage', category: 'spass' },
  { text: 'Sprich 1 Minute lang in einem erfundenen Akzent.', type: 'aufgabe', category: 'spass' },
  { text: 'Welches YouTube-Video hast du dir am oeftesten angeschaut?', type: 'frage', category: 'spass' },
  { text: 'Versuche 30 Sekunden lang nicht zu lachen – die anderen duerfen alles versuchen.', type: 'aufgabe', category: 'spass' },
  { text: 'Was wuerdest du tun, wenn du einen Tag lang unsichtbar waerst?', type: 'frage', category: 'spass' },
  { text: 'Tausche dein Profilbild mit dem der Person rechts neben dir.', type: 'aufgabe', category: 'spass' },
  { text: 'Was war dein groesster Fail beim Kochen?', type: 'frage', category: 'spass' },
  { text: 'Mache einen Moonwalk durch den Raum.', type: 'aufgabe', category: 'spass' },
  { text: 'Welche Serie hast du heimlich durchgebinged?', type: 'frage', category: 'spass' },
  { text: 'Lass die Person links neben dir eine Story auf deinem Instagram posten.', type: 'aufgabe', category: 'spass' },
  { text: 'Was ist die seltsamste Sache in deinem Kuehlschrank?', type: 'frage', category: 'spass' },
  { text: 'Halte eine 30-Sekunden-Rede ueber Toilettenpapier.', type: 'aufgabe', category: 'spass' },
  { text: 'Welche drei Dinge wuerdest du auf eine einsame Insel mitnehmen?', type: 'frage', category: 'spass' },
  { text: 'Mach den Ruf eines Hahns – so laut du kannst.', type: 'aufgabe', category: 'spass' },
  { text: 'Was ist dein heimliches Talent, von dem niemand weiss?', type: 'frage', category: 'spass' },
  { text: 'Lauf eine Runde rueckwaerts durch den Raum.', type: 'aufgabe', category: 'spass' },
  { text: 'Was war der seltsamste Traum, den du je hattest?', type: 'frage', category: 'spass' },
  { text: 'Mach 10 Kniebeugen und erzaehle dabei einen Witz.', type: 'aufgabe', category: 'spass' },

  // -------------------------------------------------------------------------
  // PARTY (30+)
  // -------------------------------------------------------------------------
  { text: 'Trinke einen Shot mit geschlossenen Augen.', type: 'aufgabe', category: 'party' },
  { text: 'Tausche ein Kleidungsstueck mit deinem Nachbarn.', type: 'aufgabe', category: 'party' },
  { text: 'Was war die wildeste Party, auf der du je warst?', type: 'frage', category: 'party' },
  { text: 'Mische einen neuen Drink aus dem, was da ist – und probiere ihn!', type: 'aufgabe', category: 'party' },
  { text: 'Welches Lied bringt dich IMMER zum Tanzen?', type: 'frage', category: 'party' },
  { text: 'Fordere jemanden zu einem Arm-Druecken heraus.', type: 'aufgabe', category: 'party' },
  { text: 'Was war der betrunkenste Moment deines Lebens?', type: 'frage', category: 'party' },
  { text: 'Trinke jedes Mal, wenn jemand deinen Namen sagt – die naechsten 3 Runden.', type: 'aufgabe', category: 'party' },
  { text: 'Mit wem in der Runde wuerdest du am liebsten den Abend verbringen?', type: 'frage', category: 'party' },
  { text: 'Fuehre einen TikTok-Tanz auf.', type: 'aufgabe', category: 'party' },
  { text: 'Was ist die mutigste Sache, die du auf einer Party je gemacht hast?', type: 'frage', category: 'party' },
  { text: 'Die naechsten 2 Runden darfst du nur fluestern.', type: 'aufgabe', category: 'party' },
  { text: 'Wer in der Runde kann am wenigsten trinken?', type: 'frage', category: 'party' },
  { text: 'Ruf jemanden an und sag: "Ich bin auf der besten Party der Welt!"', type: 'aufgabe', category: 'party' },
  { text: 'Was ist dein Party-Ritual, bevor du ausgehst?', type: 'frage', category: 'party' },
  { text: 'Verteile 3 Schlucke an Personen deiner Wahl.', type: 'aufgabe', category: 'party' },
  { text: 'Erzaehle von deinem peinlichsten Partyerlebnis.', type: 'frage', category: 'party' },
  { text: 'Mach eine Polonaise durch den Raum – alle muessen mitmachen.', type: 'aufgabe', category: 'party' },
  { text: 'Welcher DJ oder Kuenstler steht auf deiner Bucket List?', type: 'frage', category: 'party' },
  { text: 'Nimm ein Video von dir auf, wie du 5 Sekunden lang beatboxst.', type: 'aufgabe', category: 'party' },
  { text: 'Was ist der beste Party-Snack?', type: 'frage', category: 'party' },
  { text: 'Trinke aus dem Becher deines Nachbarn.', type: 'aufgabe', category: 'party' },
  { text: 'Wen wuerdest du als DJ fuer deine Traumparty buchen?', type: 'frage', category: 'party' },
  { text: 'Lass die Gruppe ein Lied waehlen, das du vorsingen musst.', type: 'aufgabe', category: 'party' },
  { text: 'Was war dein bester Party-Moment dieses Jahr?', type: 'frage', category: 'party' },
  { text: 'Stelle eine Pyramide aus Bechern – in 15 Sekunden!', type: 'aufgabe', category: 'party' },
  { text: 'Wer aus der Runde waere der beste Partycrasher?', type: 'frage', category: 'party' },
  { text: 'Mach einen Handstand (oder versuche es zumindest).', type: 'aufgabe', category: 'party' },
  { text: 'Was ist der beste Ort fuer eine Party in eurer Stadt?', type: 'frage', category: 'party' },
  { text: 'Erzaehle einen Toast auf die ganze Runde – steh dabei auf!', type: 'aufgabe', category: 'party' },
  { text: 'Wer hier hat die wildesten Moves auf der Tanzflaeche?', type: 'frage', category: 'party' },

  // -------------------------------------------------------------------------
  // JGA (30+)
  // -------------------------------------------------------------------------
  { text: 'Erzaehle die lustigste Geschichte ueber die Braut/den Braeutigam.', type: 'frage', category: 'jga' },
  { text: 'Rufe eine zufaellige Person an und gratuliere zur Hochzeit.', type: 'aufgabe', category: 'jga' },
  { text: 'Was glaubst du, wird das Brautpaar in 10 Jahren machen?', type: 'frage', category: 'jga' },
  { text: 'Schreibe der Braut/dem Braeutigam eine peinliche Nachricht.', type: 'aufgabe', category: 'jga' },
  { text: 'Was war der erste Eindruck, den du vom Partner der Braut/des Braeutigams hattest?', type: 'frage', category: 'jga' },
  { text: 'Lerne einen Hochzeitstanz-Move und fuehre ihn vor.', type: 'aufgabe', category: 'jga' },
  { text: 'Wer hat bei der Hochzeitsankuendigung am meisten geweint?', type: 'frage', category: 'jga' },
  { text: 'Mach ein Foto, das aussieht wie ein Hochzeits-Shooting.', type: 'aufgabe', category: 'jga' },
  { text: 'Was ist der beste Eheratschlag, den du geben koenntest?', type: 'frage', category: 'jga' },
  { text: 'Halte eine Mini-Hochzeitsrede fuer das Brautpaar.', type: 'aufgabe', category: 'jga' },
  { text: 'Erzaehle die peinlichste gemeinsame Erinnerung mit der Braut/dem Braeutigam.', type: 'frage', category: 'jga' },
  { text: 'Geh zu einem Fremden und lade ihn zur Hochzeit ein.', type: 'aufgabe', category: 'jga' },
  { text: 'Was wuerdest du dem Brautpaar als Hochzeitsgeschenk machen?', type: 'frage', category: 'jga' },
  { text: 'Mach ein Buergeldvideo mit Glueckwuenschen – 15 Sekunden.', type: 'aufgabe', category: 'jga' },
  { text: 'Welches Lied beschreibt die Beziehung des Brautpaars am besten?', type: 'frage', category: 'jga' },
  { text: 'Finde einen Fremden, der "Ja, ich will!" sagt, und nimm es auf.', type: 'aufgabe', category: 'jga' },
  { text: 'Was ist das Nervigste, das die Braut/der Braeutigam macht?', type: 'frage', category: 'jga' },
  { text: 'Organisiere ein spontanes Gruppenfoto mit allen.', type: 'aufgabe', category: 'jga' },
  { text: 'Wie hat die Braut/der Braeutigam vom Antrag erzaehlt?', type: 'frage', category: 'jga' },
  { text: 'Schreibe dem Brautpaar auf eine Serviette eine Prophezeiung fuer die Ehe.', type: 'aufgabe', category: 'jga' },
  { text: 'Was wuensche du dir fuer die Ehe des Brautpaars?', type: 'frage', category: 'jga' },
  { text: 'Sammle innerhalb von 2 Minuten 5 Unterschriften von Fremden auf einer Serviette.', type: 'aufgabe', category: 'jga' },
  { text: 'Was war der lustigste Fail der Braut/des Braeutigams?', type: 'frage', category: 'jga' },
  { text: 'Sing "Going to the Chapel" oder ein Hochzeitslied laut vor.', type: 'aufgabe', category: 'jga' },
  { text: 'Was hat die Braut/der Braeutigam gesagt, als du zum ersten Mal von der Verlobung erfuhrst?', type: 'frage', category: 'jga' },
  { text: 'Mach ein Foto mit einem Fremden und beschrifte es mit "Hochzeitsgast".', type: 'aufgabe', category: 'jga' },
  { text: 'Wer sollte auf der Hochzeit auf keinen Fall die Rede halten? Und warum?', type: 'frage', category: 'jga' },
  { text: 'Bitte drei Leute um einen Ehetipp und schreibe sie auf.', type: 'aufgabe', category: 'jga' },
  { text: 'Was war die Braut/der Braeutigam als Teenager fuer ein Typ?', type: 'frage', category: 'jga' },
  { text: 'Mach einen Antrag – auf den Knien – vor der ganzen Gruppe.', type: 'aufgabe', category: 'jga' },
  { text: 'Was glaubst du, wer auf der Hochzeit am meisten weinen wird?', type: 'frage', category: 'jga' },

  // -------------------------------------------------------------------------
  // ERWACHSENE 18+ (30+)
  // -------------------------------------------------------------------------
  { text: 'Beschreibe deinen schlechtesten Kuss.', type: 'frage', category: 'erwachsene' },
  { text: 'Wem aus der Runde wuerdest du eine Nachricht um 2 Uhr nachts schicken?', type: 'frage', category: 'erwachsene' },
  { text: 'Was ist die gewagteste Sache, die du je gemacht hast?', type: 'frage', category: 'erwachsene' },
  { text: 'Zeige den letzten Flirt-Chat auf deinem Handy.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Was ist dein groesster Turn-off?', type: 'frage', category: 'erwachsene' },
  { text: 'Gib der Person links neben dir ein Kompliment, das sie errroeten laesst.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Was ist das Verfuehrerischste, das jemand jemals zu dir gesagt hat?', type: 'frage', category: 'erwachsene' },
  { text: 'Mach dein bestes "Flirt-Gesicht" und halte es 10 Sekunden.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Was war dein peinlichstes Date-Erlebnis?', type: 'frage', category: 'erwachsene' },
  { text: 'Fluester der Person rechts neben dir etwas Freches ins Ohr.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Hast du schon mal jemanden aus dieser Runde attraktiv gefunden?', type: 'frage', category: 'erwachsene' },
  { text: 'Schicke einer Person deiner Wahl eine freche Nachricht – zeige sie der Runde.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Was ist dein ungewoehnlichster Crush?', type: 'frage', category: 'erwachsene' },
  { text: 'Lass die Person gegenueber dir eine Nachricht von deinem Handy lesen.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Was ist das Wildeste, das du auf einer Party erlebt hast?', type: 'frage', category: 'erwachsene' },
  { text: 'Erzaehle die Geschichte deines ersten Kusses.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Wenn du mit einer beruemten Person ausgehen koenntest – wer waere es?', type: 'frage', category: 'erwachsene' },
  { text: 'Mach einen verfuehrerischen Blick in die Kamera und schick das Bild an die Gruppe.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Was war der seltsamste Ort, an dem du jemals gekuesst hast?', type: 'frage', category: 'erwachsene' },
  { text: 'Erzaehle ein Geheimnis, das hier niemand kennt.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Was ist dein Lieblingsfilm, den du nie oeffentlich zugeben wuerdest?', type: 'frage', category: 'erwachsene' },
  { text: 'Beiß dir auf die Lippe und schau 5 Sekunden der Person gegenueber in die Augen.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Hast du schon mal jemanden geghosted? Warum?', type: 'frage', category: 'erwachsene' },
  { text: 'Zeige das letzte Bild, das du in deiner Galerie gespeichert hast.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Was ist das Romantischste, das je jemand fuer dich getan hat?', type: 'frage', category: 'erwachsene' },
  { text: 'Schreibe blind eine freche Nachricht und schicke sie an den letzten Kontakt.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Wer hier ist am ehesten der Heartbreaker-Typ?', type: 'frage', category: 'erwachsene' },
  { text: 'Mach 5 Liegestuetze und stoehn dabei dramatisch.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Was wuerdest du tun, wenn dein Ex gerade reinkaeme?', type: 'frage', category: 'erwachsene' },
  { text: 'Setze dich fuer die naechste Runde auf den Schoss der Person links neben dir.', type: 'aufgabe', category: 'erwachsene' },
  { text: 'Was ist die frecchste Nachricht, die du je erhalten hast?', type: 'frage', category: 'erwachsene' },

  // -------------------------------------------------------------------------
  // EISBRECHER (30+)
  // -------------------------------------------------------------------------
  { text: 'Was ist dein guilty pleasure?', type: 'frage', category: 'eisbrecher' },
  { text: 'Wenn du eine Superkraft haettest, welche waere es?', type: 'frage', category: 'eisbrecher' },
  { text: 'Was wolltest du als Kind werden?', type: 'frage', category: 'eisbrecher' },
  { text: 'Nenne eine Sache auf deiner Bucket List.', type: 'frage', category: 'eisbrecher' },
  { text: 'Was ist das Beste, das dir dieses Jahr passiert ist?', type: 'frage', category: 'eisbrecher' },
  { text: 'Erzaehle etwas, das niemand hier ueber dich wissen duerfte.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Was ist dein Lieblingsgericht und warum?', type: 'frage', category: 'eisbrecher' },
  { text: 'Stelle der Person rechts neben dir eine persoenliche Frage.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Wenn du irgendwo auf der Welt leben koenntest, wo waere das?', type: 'frage', category: 'eisbrecher' },
  { text: 'Beschreibe dich selbst in drei Worten.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Was war das letzte Buch oder der letzte Podcast, der dich begeistert hat?', type: 'frage', category: 'eisbrecher' },
  { text: 'Sage jedem in der Runde etwas Nettes.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Was ist deine unpopulärste Meinung?', type: 'frage', category: 'eisbrecher' },
  { text: 'Teile eine lustige Kindheitserinnerung.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Wenn du ein Tier waerst, welches waerst du und warum?', type: 'frage', category: 'eisbrecher' },
  { text: 'Zeige der Gruppe das letzte Meme, das du verschickt hast.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Was ist dein Lieblingszitat oder Motto?', type: 'frage', category: 'eisbrecher' },
  { text: 'Mach ein Kompliment fuer die Person, die du am wenigsten kennst.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Was ist die beste Reise, die du je gemacht hast?', type: 'frage', category: 'eisbrecher' },
  { text: 'Erzaehle von einem Moment, der dein Leben veraendert hat.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Welche Faehigkeit wuerdest du gerne lernen?', type: 'frage', category: 'eisbrecher' },
  { text: 'Gib der Person gegenueber einen neuen Spitznamen fuer den Abend.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Was ist dein Lieblingslied gerade und warum?', type: 'frage', category: 'eisbrecher' },
  { text: 'Erzaehle, was du heute als Erstes nach dem Aufwachen gemacht hast.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Was war der beste Ratschlag, den du je bekommen hast?', type: 'frage', category: 'eisbrecher' },
  { text: 'Stelle dich vor, als waerst du ein Charakter aus einem Film.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Was macht dich wirklich gluecklich?', type: 'frage', category: 'eisbrecher' },
  { text: 'Nenne drei Dinge, die du und die Person neben dir gemeinsam habt.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Wenn du eine Zeitmaschine haettest, wohin wuerdest du reisen?', type: 'frage', category: 'eisbrecher' },
  { text: 'Erzaehle von deinem schoensten Erlebnis mit einem Fremden.', type: 'aufgabe', category: 'eisbrecher' },
  { text: 'Was wuerdest du tun, wenn du eine Million Euro gewinnen wuerdest?', type: 'frage', category: 'eisbrecher' },
];
