/** Indywidualne tłumaczenia kart, w kolejności oryginału. */
export const QUESTIONS = {
  eisbrecher: [
    'Jaki mały luksus poprawia ci zwykły dzień?', 'Co goście prawdopodobnie zauważają najpierw w twoim mieszkaniu?',
    'Przy jakim temacie tracisz poczucie czasu, gdy o nim opowiadasz?', 'Jaką umiejętnością od razu zaoferujesz pomoc nowemu współlokatorowi?',
    'Jak wygląda twój idealny wolny poranek?', 'Jakie jedzenie zamawiasz, kiedy trudno ci się zdecydować?',
    'Po czym poznać, że dobrze czujesz się w grupie?', 'Jakie zajęcie zaskakująco skutecznie cię uspokaja?',
    'Co zwykle masz pod ręką przy łóżku?', 'Jaka niepozorna rzecz wychodzi ci zaskakująco dobrze?',
    'Jaki zapach od razu przypomina ci miłe miejsce?', 'Jak opiszesz swój humor komuś, kto cię nie zna?',
    'Którą część codzienności najchętniej powierzysz robotowi?', 'Gdzie najbardziej lubisz obserwować ludzi?',
    'Jaką aplikację zainstalujesz jako pierwszą na nowym telefonie?', 'Od jakiego napoju zaczyna się dla ciebie przyjemny wieczór?',
    'Która pora roku najlepiej pasuje do twojego temperamentu?', 'Co zbierasz, choć nie było to twoim świadomym zamiarem?',
    'Jaki komplement szczególnie lubisz słyszeć?', 'Ile planowania wymaga u ciebie udana niedziela?',
    'Jaki niewinny drobiazg cieszy cię nieproporcjonalnie mocno?', 'Przy jakiej planszówce lub grze karcianej odzywa się twoja ambicja?',
    'Co najpierw pokażesz gościowi w swojej okolicy?', 'Jakie pytanie słyszysz zdecydowanie za rzadko?',
    'Jak wybierasz kolejną rzecz do czytania lub oglądania?', 'Co twoja obecna torba zdradza o twojej codzienności?',
    'Jaką pogodę lubisz bardziej niż większość ludzi?', 'Jakie zwierzę oddaje twoją energię w poniedziałkowy poranek?',
    'Co wolisz kupować używane niż nowe?', 'Co według ciebie wyróżnia dobrą kawiarnię?',
    'Który obowiązek domowy naprawdę lubisz wykonywać?', 'Jak decydujesz, czy przyjąć zaproszenie?',
    'Jaka mała niespodzianka byłaby dla ciebie trafiona?', 'Z którą częścią garderoby trudno byłoby ci się rozstać?',
    'Po jakim dźwięku poznajesz, że jesteś w domu?', 'Co chcesz najpierw zrozumieć w nowo poznanej osobie?',
    'Jakie danie wychodzi ci nawet bez przepisu?', 'O jakiej porze dnia masz najbardziej jasny umysł?',
    'Czego nie może zabraknąć na twoim pikniku?', 'Który przedmiot w pobliżu ma swoją historię?',
    'Jak spędzasz dziesięć niespodziewanych wolnych minut?', 'Jaki był twój ostatni naprawdę dobry spontaniczny pomysł?',
    'Jaki sklep trudno ci minąć bez zajrzenia do środka?', 'Co sprawia, że chcesz kontynuować rozmowę?',
    'Jaki nawyk przyszedł do ciebie od kogoś innego?', 'Czym zajmiesz się podczas wspólnego wieczoru z gotowaniem?',
    'Jakiego słowa używasz prawdopodobnie częściej niż inni?', 'Co jest dla ciebie oznaką dobrej gościnności?',
    'Jakie pytanie chcesz zadać tej grupie?', 'Co trzeba o tobie wiedzieć, żeby zaplanować z tobą wycieczkę?',
  ],
  spass: [
    'Jakiej zupełnie nieważnej rzeczy bronisz z zadziwiającą pasją?', 'Jakie było twoje najzabawniejsze przejęzyczenie, które pamiętasz?',
    'Jaką nieszkodliwą zasadę wymyślasz wyłącznie dla siebie?', 'Jakie zajęcie czasem komentujesz jak reporter sportowy?',
    'Która postać filmowa byłaby dla ciebie koszmarnym współlokatorem?', 'W czym regularnie przeceniasz swój talent?',
    'Jaki dźwięk potrafisz zaskakująco przekonująco naśladować?', 'Jaki niedorzeczny lęk pamiętasz z dzieciństwa?',
    'Jakie hasło reklamowe najmniej pasowałoby do twojej codzienności?', 'Jaki drobiazg ciągle odkładasz w to samo absurdalne miejsce?',
    'Jakie twoje danie wygląda gorzej, niż smakuje?', 'Kiedy ostatnio rozśmieszył cię twój własny błąd?',
    'Jakie powiedzenie długo miało dla ciebie błędne znaczenie?', 'Co napiszesz na pucharze za swoją najgorszą cechę?',
    'Jakie dziwne połączenie smaków naprawdę ci smakuje?', 'Jaki przedmiot codziennego użytku byłby najtrudniejszy w roli domowego zwierzaka?',
    'Jaka sytuacja rozśmiesza cię nawet wtedy, gdy chcesz zachować powagę?', 'Jakie proste zadanie zdarzyło ci się rozwiązać niepotrzebnie skomplikowaną metodą?',
    'Jakie zmyślone prawo zakazywałoby twojego najbardziej irytującego nawyku?', 'Jaka maleńka niedogodność wywołuje w twojej głowie wielki dramat?',
    'Jaki tytuł miałby sitcom o twoim ostatnim miesiącu?', 'Który rzekomo fajny etap w swoim życiu uważasz dziś za szczególnie zabawny?',
    'Jaka była najdziwniejsza wymówka, w którą udało ci się uwierzyć we własnej głowie?', 'Przy jakiej awarii technicznej twoja reakcja najbardziej cię zaskoczyła?',
    'Jaki zupełnie bezużyteczny talent wpiszesz do CV?', 'Który mebel podejrzewasz o zły humor?',
    'Wokół jakiej drobnej czynności robisz zbyt wielką ceremonię?', 'Jaki niezwykły pseudonim wybierzesz do występu iluzjonistycznego?',
    'Jakie niewinne kłamstwo o codzienności łatwo byłoby przejrzeć?', 'Jaka była twoja najzabawniejsza pomyłka podczas zakupów?',
    'Jakie jedzenie powinno według ciebie mieć instrukcję obsługi?', 'Jaka rola przypadłaby ci w chaotycznej załodze statku kosmicznego?',
    'Jak brzmi twój wewnętrzny głos, gdy trzeba coś zmontować?', 'Co cię bawi, choć trudno ci wyjaśnić, na czym polega żart?',
    'Jaki byłby najbardziej niedorzeczny powód zawziętego sporu sąsiedzkiego?', 'Jaki codzienny ruch wychodzi ci mimowolnie elegancko?',
    'Jakie słowo brzmi dla ciebie zupełnie niezgodnie ze swoim znaczeniem?', 'Co wygadałaby o tobie twoja lodówka?',
    'Który sport byłby najzabawniejszy z użyciem wyposażenia biurowego?', 'Jaka była twoja najzabawniejsza przygoda z autokorektą?',
    'Który twój przedmiot zasługuje na imię?', 'Jak opowiesz o nudnych zakupach niczym o filmie akcji?',
    'Jaka absurdalna debata mogłaby cię mimo wszystko wciągnąć na dwadzieścia minut?', 'Jaki zaskakująco szczery tytuł miałaby twoja książka kucharska?',
    'Który z twoich zwyczajów kosmita mógłby źle zrozumieć?', 'Jakie zwierzę najbardziej rozpraszałoby jako prezenter wiadomości?',
    'Jaki nietrafiony zakup przynajmniej dał ci dobrą historię?', 'Po jakim nawyku natychmiast rozpoznasz swojego sobowtóra?',
    'Jakie zwyczajne zdanie można wypowiedzieć jak dramatyczne ostrzeżenie filmowe?', 'Jakie było najzabawniejsze błędne wyobrażenie kogoś na twój temat?',
  ],
  party: [
    'Jaka piosenka porywa cię do ruchu nawet po długim dniu?', 'Co odróżnia udaną imprezę od imprezy, która jest tylko głośna?',
    'Jaki koncert chcesz jeszcze raz przeżyć po raz pierwszy?', 'Jaką rolę automatycznie przejmujesz na imprezach?',
    'Jaki motyw naprawdę zachęciłby cię do imprezy przebieranej?', 'Jaką piosenkę łączysz z konkretną przyjaźnią?',
    'Jak wygląda twoje idealne zakończenie długiego wieczoru?', 'Jaki drobiazg sprawia, że gospodarza lub gospodyni nie sposób zapomnieć?',
    'Znasz tylko refren, a mimo to śpiewasz — jaka to piosenka?', 'Jaka była najlepsza rozmowa poza parkietem?',
    'Na jakim instrumencie chcesz grać w zespole?', 'Jaka impreza miło cię zaskoczyła, choć początkowo nie było ochoty iść?',
    'Co musi znaleźć się na bufecie, żeby cię zadowolić?', 'Jaki gatunek muzyczny udało ci się docenić dopiero późno?',
    'Jak pomożesz nowym osobom na imprezie nawiązać rozmowę?', 'Kogo wybierzesz na kameralny koncert w salonie?',
    'Jakie jest twoje najprzyjemniejsze wspomnienie z festiwalu?', 'Jaka piosenka powinna zagrać przy twoich osobistych napisach końcowych?',
    'Jaką imprezową tradycję można twoim zdaniem spokojnie zlikwidować?', 'Co ważniejsze na imprezie: znajome twarze czy nowe znajomości?',
    'Jaka muzyczna rekomendacja od znajomych naprawdę trafiła w twój gust?', 'Jak sprawisz, że urodziny przy bardzo małym budżecie będą wyjątkowe?',
    'Jaki ruch taneczny zawsze wydaje ci się odpowiedni?', 'O czym byłaby twoja własna audycja radiowa?',
    'Jakie przyjęcie wolisz urządzić na zewnątrz niż w środku?', 'Jaka piosenka przypomina ci długą podróż?',
    'Jakie było najbardziej pomysłowe zaproszenie, które do ciebie trafiło?', 'Jakich trzech rzeczy potrzebują goście, żeby szybko poczuć się swobodnie?',
    'Jaką piosenkę pokażesz komuś, kto ma zrozumieć twój nastrój?', 'Co sprawia, że wspólny wieczór z grami jest dla ciebie udany?',
    'Jakiej twojej opinii muzycznej niemal nikt nie podziela?', 'Jakie nietypowe jedzenie pasowałoby na przerwę o północy?',
    'Po czym poznajesz, że pora wracać do domu?', 'Co na imprezie wolisz zrobić samodzielnie, zamiast zlecać organizację?',
    'Jaki tekst piosenki szczególnie utkwił ci w pamięci?', 'Jaka niespodzianka urodzinowa mogłaby cię przytłoczyć?',
    'Jaki dźwięk z nagrania koncertowego uwielbiasz?', 'Jakie świętowanie nie potrzebuje według ciebie żadnej okazji?',
    'Jaka byłaby idealna długość wspólnej playlisty?', 'Jaka muzyka towarzyszy ci podczas sprzątania po gościach?',
    'Jaki piękny moment z wesela pamiętasz poza samą ceremonią?', 'Jakie miejsce byłoby nietypowe, ale przytulne na małe przyjęcie?',
    'Jak urozmaicisz imprezę bez głośników?', 'Jakiego albumu wolisz słuchać w całości niż wybierać pojedyncze utwory?',
    'Jak najlepiej zacząć rozmowę przy stole pełnym nieznajomych?', 'Jakim muzycznym odkryciem chcesz podzielić się z grupą?',
    'Jak wyglądałaby impreza idealnie dopasowana do twojego poziomu energii?', 'Jakie wspomnienie łączy się dla ciebie z konkretnym tańcem?',
    'Co na swojej następnej imprezie chcesz świadomie zrobić inaczej?', 'Jaki tytuł miałaby playlista dzisiejszego wieczoru?',
  ],
  freundschaft: [
    'Po czym poznajesz, że znajomość przerodziła się w przyjaźń?', 'Jaki drobny gest przyjaciół szczególnie wiele dla ciebie znaczy?',
    'Co możesz robić z przyjaciółmi bez potrzeby długich rozmów?', 'Jak utrzymujesz kontakt z osobami mieszkającymi daleko?',
    'Jaka cecha twoich przyjaciół zmieniła również ciebie?', 'Jak najlepiej odezwać się po długim milczeniu?',
    'Jaka wspólna wpadka jeszcze bardziej was zbliżyła?', 'Jak pokazujesz przyjacielowi, że naprawdę słuchasz?',
    'Czego spróbujesz z przyjacielem, ale nie w pojedynkę?', 'Jaka tradycja w przyjaźni nigdy nie powinna stać się obowiązkiem?',
    'Kiedy ktoś z twojego grona przyjaciół wzbudził w tobie szczególną dumę?', 'Na ile spontaniczności pozwalasz w planowaniu spotkań z przyjaciółmi?',
    'Co cenisz w przyjaciołach zupełnie innych niż ty?', 'Jaki rodzaj wsparcia łatwo ci zaoferować?',
    'Jak można szczerze się z tobą nie zgodzić, żeby nie zamknąć rozmowy?', 'Jaka wspólna wycieczka szczególnie żywo utkwiła ci w pamięci?',
    'Co według ciebie składa się na dobre przeprosiny między przyjaciółmi?', 'Jaka wiadomość ucieszy cię w zwykły dzień?',
    'W jakiej sprawie poprosisz o radę przyjaciela zamiast szukać w internecie?', 'Jaka granica w przyjaźni stała się dla ciebie ważna?',
    'Jakie wspólne zajęcie dobrze łączy różnych ludzi?', 'Po czym poznajesz, że ktoś potrzebuje teraz towarzystwa, a nie rad?',
    'Jaki prezent od przyjaciół pokazał największą uważność?', 'Która przyjaźń zaczęła się w nieoczekiwanym miejscu?',
    'Jak zmienia się twój sposób mówienia przy najbliższych przyjaciołach?', 'Czego nie warto brać do siebie, przyjaźniąc się z tobą?',
    'Jaka cecha czyni kogoś dobrym towarzyszem podróży?', 'Co zaproponujesz na wspólną wolną godzinę?',
    'Jakie wspomnienie chcesz porównać ze wspomnieniem dawnego przyjaciela?', 'Jak świętujesz małe sukcesy przyjaciół?',
    'Co pomaga ci odzyskać bliskość po różnicy zdań?', 'Jaki wspólny projekt mógłby wzbogacić waszą przyjaźń?',
    'Czego przyjaciele nauczyli cię o tobie?', 'Jaki rodzaj pomocy trudno ci przyjąć?',
    'Jak ważna jest dla ciebie punktualność w przyjaźni?', 'Jaki niewinny żart zrozumiały tylko dla was możesz wyjaśnić grupie?',
    'Co u przyjaciela rozpoznasz od razu nawet po latach?', 'Kiedy wspólne milczenie jest dla ciebie przyjemne?',
    'Co sprawia, że nowa osoba czuje się mile widziana w istniejącej grupie?', 'Którą przyjaźń chcesz częściej pielęgnować na co dzień?',
    'Czym różni się dla ciebie lojalność od bezmyślnego przytakiwania?', 'Jakie wypady lepiej wychodzą z przyjaciółmi niż z rodziną?',
    'Jak podniesiesz przyjaciela na duchu po rozczarowującym dniu?', 'Za jakim wspólnym zwyczajem czasem tęsknisz?',
    'Po czym widać, że potrzebujesz czasu dla siebie?', 'Jakie zaskakujące podobieństwo zbliżyło cię do kogoś?',
    'Co jest dobrym powodem, żeby po prostu podziękować przyjacielowi?', 'Jak radzisz sobie z tym, że różne przyjaźnie mają różny stopień bliskości?',
    'Jaką umiejętność przyjaciela podziwiasz skrycie lub otwarcie?', 'Co chcesz w przyszłości robić bardziej świadomie jako przyjaciel?',
  ],
  liebe: [
    'Jaka forma uwagi sprawia, że czujesz, że ktoś naprawdę cię dostrzega?', 'Co sprawia, że pierwsze spotkanie jest dla ciebie swobodne?',
    'Jaka mała codzienna scena wydaje ci się romantyczna?', 'Po czym poznajesz, że możesz komuś zaufać?',
    'O czym przy poznawaniu kogoś wolisz opowiedzieć osobiście niż na czacie?', 'Jaka cecha z czasem staje się dla ciebie bardziej atrakcyjna?',
    'Co oznacza dla ciebie bliskość poza dotykiem?', 'Jak ktoś powinien zareagować, gdy wyznaczasz granicę?',
    'Jaki wspólny zwyczaj mógłby wzbogacić związek?', 'Jaka byłaby miła randka, która prawie nic nie kosztuje?',
    'Jak okazujesz uczucie, kiedy brakuje ci właściwych słów?', 'Jaka wizja romantyzmu zupełnie do ciebie nie pasuje?',
    'Co o codzienności partnera chcesz wiedzieć już na początku?', 'Jaki rodzaj humoru pomaga ci we flirtowaniu?',
    'Kiedy podczas rozmowy czujesz szczególną więź?', 'Czego potrzebujesz, żeby zachować niezależność w związku?',
    'Jakie pytanie mówi przy poznawaniu więcej niż pytanie o zawód?', 'Jak sobie radzisz, gdy druga osoba potrzebuje znacznie więcej spokoju?',
    'Jaki komplement na randce szczerze by cię ucieszył?', 'Co jest dla ciebie dobrym znakiem po różnicy zdań?',
    'Jakie wspólne doświadczenie wiele mówi o waszej relacji?', 'Jak ważne są podobne zainteresowania w związku?',
    'Co sprawiłoby, że list miłosny byłby dla ciebie osobisty?', 'Jakie niespodzianki lubisz w związku?',
    'Co w związku powinno być regularnie wypowiadane na głos?', 'Po czym odróżniasz pełne szacunku zainteresowanie od natarczywości?',
    'Jak zaplanujesz wspólny wolny dzień bez ekranów?', 'Jaki drobiazg może pomóc ci opanować zdenerwowanie na spotkaniu?',
    'Czym różni się dla ciebie zakochanie od poczucia bliskości i znajomości?', 'Jaki filmowy związek wydaje ci się wiarygodny?',
    'Ile wspólnego planowania ci odpowiada?', 'Jaki gest byłby wyrazem troski w związku na odległość?',
    'Jakie rozmowy wolisz prowadzić podczas spaceru?', 'Jak ktoś ma się do ciebie odezwać, gdy widać, że coś cię trapi?',
    'Co nowego wiesz dziś o swoich potrzebach?', 'Jaka cecha sprawia, że ktoś dobrze słucha podczas randki?',
    'Jak można okazywać uczucie bez wydawania pieniędzy?', 'Jak zdrowo podchodzić do różnych zainteresowań?',
    'Jakiej wspólnej decyzji nikt nie powinien podejmować samodzielnie?', 'Co konkretnie oznacza dla ciebie niezawodność?',
    'Jak sprawiedliwie uwzględniać różnice w poziomie energii?', 'Jakiej rozmowy nigdy nie chcesz prowadzić w pośpiechu między innymi sprawami?',
    'Czego para może nauczyć się od dobrych przyjaźni?', 'Jakiej małej tradycji chcesz spróbować we dwoje?',
    'Jak ważne jest dla ciebie, żeby bliscy dobrze znali twoją drugą połówkę?', 'Jak uroczo okazać zainteresowanie, nie wywierając presji?',
    'Gdzie stawiasz granicę publicznym wyznaniom miłości?', 'Po czym poznasz, że związek dobrze na ciebie wpływa?',
    'Co chcesz zrobić najpierw przy spotkaniu po długiej rozłące?', 'Jak zmieniło się twoje wyobrażenie o dobrym związku?',
  ],
  erinnerungen: [
    'Jaki drobny szczegół z dzieciństwa potrafisz nadal dokładnie opisać?', 'Która droga do szkoły szczególnie utkwiła ci w pamięci?',
    'Jaki pierwszy samodzielnie kupiony przedmiot był twoją dumą?', 'Jaka kuchnia kojarzy ci się z poczuciem bezpieczeństwa?',
    'Przy jakiej grze można cię było dawniej zastać przez wiele godzin?', 'Jaki deszczowy dzień okazał się niespodziewanie piękny?',
    'Która dorosła osoba traktowała cię poważnie w dzieciństwie?', 'Jaki wakacyjny rytuał chcesz przywrócić?',
    'Jaki był twój pierwszy świadomie przeżyty sukces poza szkołą?', 'Które miejsce znasz dziś już tylko ze wspomnień?',
    'Jaką historię często opowiadano w twojej rodzinie?', 'Jaka była twoja najzabawniejsza próba udawania dorosłej osoby?',
    'Jaka dawna pasja mogłaby dziś znów cię porwać?', 'Jaka scena z dawnego sąsiedztwa została ci w pamięci?',
    'Co w dzieciństwie wychodziło ci lepiej niż dziś?', 'Jaki prezent zupełnie cię wtedy zaskoczył?',
    'Jak wyglądało dawniej twoje ulubione miejsce odosobnienia?', 'Jakie pierwsze spotkanie pamiętasz niezwykle dokładnie?',
    'Jaki drobny odważny moment pamiętasz z młodości?', 'Która wycieczka poszła inaczej niż planowano, a mimo to była udana?',
    'Kto nauczył cię praktycznej umiejętności?', 'Jakie jedzenie dawniej było wyjątkowe, a dziś jest codziennością?',
    'Jakie zdjęcie chcesz zrobić jeszcze raz?', 'Jaki dawny zwyczaj swojej rodziny lepiej dziś rozumiesz?',
    'Które trudności pierwszego samodzielnego mieszkania przerosły twoje oczekiwania?', 'Za jakim dźwiękiem z wcześniejszego etapu życia tęsknisz?',
    'Jakie pożegnanie okazało się później dobrym początkiem?', 'Która lekcja szkolna została ci w pamięci z zaskakującego powodu?',
    'Który przedmiot przetrwał z tobą kilka przeprowadzek?', 'Na co poszły twoje pierwsze samodzielnie zarobione pieniądze?',
    'Kogo z dawnych lat chcesz zapytać, jak zapamiętał wspólne wydarzenie?', 'Jakie było twoje pierwsze wielkie błędne wyobrażenie o świecie dorosłych?',
    'Które przyjęcie urodzinowe z dzieciństwa pamiętasz do dziś?', 'Co było dawniej twoją kolekcją i dlaczego?',
    'Jaki film był dla ciebie wtedy prawdziwym wydarzeniem?', 'Kiedy po raz pierwszy udało ci się samodzielnie odnaleźć w nowym mieście?',
    'Jaka mała tradycja z czasów szkolnych sprawiała ci przyjemność?', 'Jaką niespodziewaną pochwałę nadal pamiętasz?',
    'Jakie przygotowanie do podróży było dawniej dla ciebie nieodłączną częścią wakacji?', 'Co powiesz swojemu młodszemu ja o przyjaźni?',
    'Jaki zapach przenosi cię myślami do konkretnej pory roku?', 'Znaczenie jakiej codziennej chwili dotarło do ciebie dopiero później?',
    'Które dawne ulubione ubranie chcesz znów nosić?', 'Jaka zmiana w twojej rodzinnej miejscowości cię zaskakuje?',
    'Jakie wspomnienie chcesz utrwalić jako krótką scenę filmową?', 'Jaki wspólny napad śmiechu pamiętasz do dziś?',
    'Co zaskoczyło cię podczas pierwszej samotnej podróży?', 'Jaka wczesna decyzja nieoczekiwanie zmieniła bardzo wiele?',
    'Jaki stary list lub karteczkę zachowujesz z ważnego powodu?', 'Co prawdopodobnie najbardziej zapamiętasz z obecnego etapu życia?',
  ],
  reisen: [
    'Co oglądasz jako pierwsze w nowym miejscu?', 'Która podróż była piękniejsza dzięki temu, że nie wszystko zaplanowano?',
    'Co jest twoim osobistym sygnałem, że wakacje się zaczęły?', 'Którego miejsca w swojej okolicy nadal nie znasz tak naprawdę?',
    'Jaki krajobraz od razu cię uspokaja?', 'Co zabierasz do bagażu, choć inni uważają to za zbędne?',
    'Jaka rozmowa w podróży szczególnie utkwiła ci w pamięci?', 'Jak decydujesz, czy dany cel podróży do ciebie pasuje?',
    'Co zrobisz podczas dnia w pojedynkę w obcym mieście?', 'Jakie danie z podróży chcesz odtworzyć w domu?',
    'Co składa się dla ciebie na dobre miejsce przy oknie w pociągu?', 'Jaki codzienny zwyczaj w innym miejscu zrobił na tobie wrażenie?',
    'Dokąd pojedziesz, jeśli sama droga ma być częścią przygody?', 'Który nocleg pamiętasz ze względu na poznanych ludzi?',
    'Jak najbardziej lubisz orientować się w mieście?', 'Jakiej pamiątki z podróży rzeczywiście używasz na co dzień?',
    'Ile czasu potrzebujesz, żeby poczuć się swojsko w nowym miejscu?', 'Jaką podróż chcesz odbyć w bardzo wolnym tempie?',
    'Czego podróże nauczyły cię o twoich wymaganiach?', 'Które miejsce wygląda w twoich wspomnieniach zupełnie inaczej niż na zdjęciach?',
    'Jaką drobną wpadkę w podróży potrafisz już przyjąć spokojnie?', 'Co pokażesz komuś, kto po raz pierwszy odwiedza twój kraj?',
    'Jaki język chcesz znać, żeby rozmawiać z ludźmi na miejscu?', 'Jak ważna jest dla ciebie możliwość zmiany planów w podróży?',
    'Co jest dla ciebie najpiękniejsze w powrocie do domu?', 'Jaki targ lub sklep w podróży szczególnie wzbudził twoją ciekawość?',
    'Jaką trasę wolisz przeżyć pieszo niż samochodem?', 'Co powinien o tobie wiedzieć dobry towarzysz podróży?',
    'Jakim widokiem chcesz nacieszyć się bez aparatu?', 'Jak spędzisz wolne popołudnie przy złej pogodzie podczas wyjazdu?',
    'Jaki pomysł na podróż odkładasz wyłącznie z powodu planowania?', 'Czego dowiadujesz się o miejscu, odwiedzając supermarket?',
    'Który środek transportu najbardziej kojarzy ci się z przygodą?', 'Jakie obce miasto wyobrażasz sobie jako tymczasowy dom?',
    'Jakie jest twoje najlepsze wspomnienie z wycieczki bez noclegu?', 'Jaki rodzaj muzeum mógłby przyciągnąć cię nawet spontanicznie?',
    'Jak znajdujesz w podróży miejsca poza oczywistymi atrakcjami?', 'Czego świadomie nie sprawdzisz przed wyjazdem?',
    'Jaka chwila z naturą zaskoczyła cię podczas podróży?', 'Która podróż obaliła twoje oczekiwania?',
    'Jaki byłby twój idealny przystanek podczas długiej drogi?', 'Czym twoje wakacyjne tempo różni się od codziennego?',
    'Jakie miejsce chcesz ponownie zobaczyć o innej porze roku?', 'Co dla ciebie oznacza okazywanie szacunku odwiedzanemu miejscu?',
    'Jakie krótkie spotkanie w podróży chcesz kontynuować?', 'Jaka trasa pasowałaby na wycieczkę z tą grupą?',
    'Jaka umiejętność niespodziewanie przydała ci się w drodze?', 'Jakie przeżycie brzmi zwyczajnie, ale w podróży było wyjątkowe?',
    'Jak wygląda twój dzień podróży bez biletów wstępu?', 'Jakie pytanie zadasz osobie, która mieszka w tym miejscu od zawsze?',
  ],
  traeume: [
    'Jaki mały pomysł na przyszłość już teraz cię cieszy?', 'Czego chcesz się nauczyć, nawet jeśli nigdy nie osiągniesz w tym wysokiego poziomu?',
    'Jak chcesz się czuć w zwykły dzień za pięć lat?', 'Jaki projekt interesowałby cię nawet bez uznania innych?',
    'Jaki dom chcesz sobie z czasem stworzyć?', 'Co zrobisz z jednym wolnym popołudniem w tygodniu?',
    'Jaki nawyk chcesz podarować swojemu przyszłemu ja?', 'Które marzenie staje się dla ciebie ważniejsze z wiekiem?',
    'Czego chcesz doświadczyć po raz pierwszy?', 'Jaka umiejętność mogłaby wyraźnie ułatwić ci codzienność?',
    'Co chcesz kiedyś zrobić własnoręcznie zamiast kupować?', 'Jakich ludzi chcesz częściej mieć wokół siebie w przyszłości?',
    'Jakie przedsięwzięcie wymaga raczej odwagi niż pieniędzy?', 'Jak zaplanujesz rok, w którym nikt nie ocenia twojego życiorysu?',
    'Czego chcesz kiedyś nauczyć młodszą osobę?', 'Co w twoim życiu może spokojnie pozostać takie, jakie jest?',
    'Jakie wspólne przedsięwzięcie chcesz zaplanować z przyjaciółmi?', 'Czego spróbujesz, jeśli porażka nie będzie mieć konsekwencji?',
    'Jaki rodzaj pracy mógłby ci sprawiać radość także później?', 'Co chcesz kiedyś móc o sobie powiedzieć?',
    'Jaki dawny pomysł zasługuje u ciebie na drugą próbę?', 'Jak wyglądałoby idealne miejsce na twórczą przerwę?',
    'Którego marzenia prawie nigdy nie wypowiadasz na głos?', 'Jaki byłby realistyczny pierwszy krok do wielkiego celu?',
    'Jaką nową tradycję chcesz zapoczątkować w swoim otoczeniu?', 'Czego chcesz mieć mniej, żeby zyskać więcej wolności?',
    'Jakie doświadczenie byłoby dla ciebie cenniejsze niż drogi przedmiot?', 'Jak chcesz świętować wielki osobisty sukces?',
    'Jaki rodzaj przygody pasuje do ciebie dzisiaj?', 'W tworzeniu czego w swojej okolicy chcesz uczestniczyć?',
    'Które dziecięce marzenie nadal sprawiłoby ci radość?', 'Po czym poznasz, że osiągnięć jest już wystarczająco dużo?',
    'Co przyszłej zimy chcesz zrobić inaczej niż dotąd?', 'Jakie nowe połączenie między swoimi zainteresowaniami chcesz odkryć?',
    'Na co chcesz kiedyś spojrzeć z dumą, choć nikt inny tego nie widzi?', 'Jakiego wolnego miejsca w kalendarzu chcesz bronić?',
    'Co chcesz kiedyś pokazać małej publiczności?', 'Jaką społeczność chcesz stworzyć lub znaleźć?',
    'Jakie motto pasowałoby do kolejnego roku twojego życia?', 'Jaki cel obierzesz bez porównywania się z innymi?',
    'Co przy następnej przeprowadzce chcesz świadomie zabrać albo zostawić?', 'Jaką powolną zmianę chcesz rozpocząć?',
    'Komu chcesz kiedyś się odwdzięczyć?', 'Jaki powód byłby wart ponownego zostania początkującą osobą?',
    'Jakie wspomnienie chcesz jeszcze stworzyć z rodziną?', 'Co zrobisz z małym pustym pomieszczeniem?',
    'Jaką cechę chcesz zachować na starość?', 'Co chcesz częściej świętować w przyszłym roku?',
    'Jakie marzenie możesz wkrótce zrealizować w mniejszej wersji?', 'Jakie otwarte pytanie o przyszłość teraz cię fascynuje?',
  ],
  entscheidungen: [
    'Przy jakiej decyzji naprawdę pomaga ci przespanie się z nią?', 'Co stało się dla ciebie ważniejsze od dobrego pierwszego wrażenia?',
    'Kiedy zrezygnujesz z wygody na rzecz sprawiedliwości?', 'Jaką decyzję wolisz podejmować intuicyjnie niż według listy?',
    'Co oznacza dla ciebie sukces poza pieniędzmi i pracą?', 'Jakie granice dotyczące swojego czasu chcesz lepiej chronić?',
    'W jakiej sprawie dobry argument zmienił twoje zdanie?', 'Co sprawia, że obietnica jest dla ciebie wiążąca?',
    'Po czym poznajesz, że kompromis idzie dla ciebie za daleko?', 'Jaka mała decyzja wpływa na twój nastrój mocniej, niż można się spodziewać?',
    'Kiedy szczerość bez dodatkowych wyjaśnień jest szczególnie ważna?', 'Co wolisz naprawić, nawet jeśli łatwiej byłoby kupić nowe?',
    'Jaki rodzaj ryzyka chętnie podejmujesz?', 'Jak wybierasz między dwiema równie dobrymi możliwościami?',
    'Co sprawia, że ktoś jest w twoich oczach wiarygodny?', 'Wobec czego chcesz okazywać więcej cierpliwości na co dzień?',
    'Kiedy odmowa może być życzliwą decyzją?', 'Jakie przekonanie chcesz jeszcze dokładniej samodzielnie sprawdzić?',
    'Co jest dla ciebie ważniejsze w przeprosinach: słowa czy zachowanie?', 'Ile niepewności potrzebujesz, żeby życie pozostało ciekawe?',
    'Jaki wygodny nawyk nie do końca pasuje do twoich wartości?', 'Kiedy zdarzyło ci się zrezygnować z pieniędzy na rzecz czasu?',
    'Czym warto się dzielić, nawet jeśli należy tylko do nas?', 'Jakiej decyzji nie podejmiesz przez głosowanie w grupie?',
    'Po czym poznajesz radę, która naprawdę do ciebie pasuje?', 'Co odróżnia dla ciebie hojność od chęci przypodobania się?',
    'Jaki drobiazg zasługuje na większe uznanie, niż dostaje?', 'Kiedy rozsądniej jest odpuścić rozpoczęte przedsięwzięcie?',
    'O czym w swoich zakupach chcesz decydować bardziej świadomie?', 'Jaka cecha znaczy dla ciebie więcej niż imponujące umiejętności?',
    'Jak radzisz sobie z decyzją, która dopiero później okazuje się błędna?', 'Co ochronisz w pierwszej kolejności przy ograniczonym budżecie?',
    'Kiedy zasada powinna dopuszczać uzasadniony wyjątek?', 'Co oznacza odpowiedzialność we wspólnym mieszkaniu?',
    'Jakiej opinii bronisz nawet bez poparcia przyjaciół?', 'Co pomaga ci nie odkładać decyzji w nieskończoność?',
    'Kiedy trudna rozmowa jest więcej warta niż zgoda za wszelką cenę?', 'Jaka decyzja dała ci wolność?',
    'Co należy wiedzieć, zanim oceni się sukces innych?', 'Ile planowania daje ci bezpieczeństwo, a od kiedy staje się kontrolą?',
    'Co składa się na sprawiedliwy podział obowiązków?', 'Jaki rodzaj rywalizacji uważasz za wzbogacający?',
    'Przy czym nawet w męczący dzień nie pójdziesz na skróty?', 'Kiedy warto publicznie skorygować własną opinię?',
    'Z jakiej okazji wolisz zrezygnować, żeby pozostać w zgodzie ze sobą?', 'Jak odróżniasz prawdziwą potrzebę od chwilowego pragnienia?',
    'Co w twoim stylu życia może zaskakiwać innych?', 'Jaką decyzję podejmiesz dziś spokojniej niż dawniej?',
    'Po czym poznajesz, że potrzebujesz przerwy, a nie nowego rozwiązania?', 'Jakie codzienne działanie najlepiej wyraża twoje wartości?',
  ],
  kreativ: [
    'Jaki sekretny pokój dodasz do biblioteki?', 'Jak wyglądałoby święto, które możesz samodzielnie wymyślić?',
    'Jakie dwa zwykłe zawody stworzyłyby razem fantastyczny nowy?', 'Co muzeum pokazałoby na wystawie o twojej dzisiejszej codzienności?',
    'Jaka supermoc byłaby przydatna wyłącznie w domu?', 'Jak wyglądałoby miasto zbudowane dla nocnych marków?',
    'Jakiemu przedmiotowi dasz głos na jeden dzień?', 'Jaka scena dobrze otwierałaby film o tej grupie?',
    'Jaki nowy sport można wymyślić bez sprzętu?', 'Jak wyglądałaby restauracja z menu uporządkowanym według nastrojów?',
    'Co zostawisz w kapsule czasu ludziom za sto lat?', 'Jaki kolor miałby dźwięk, który lubisz?',
    'Jak zmienisz nudną poczekalnię w ulubione miejsce?', 'Jaka zwierzęca umiejętność byłaby zaskakująco praktyczna w biurze?',
    'Co byłoby głównym problemem świata, w którym wszystkie myśli pojawiają się jako napisy?', 'Jakie codzienne wydarzenie zasługuje na własną ścieżkę dźwiękową?',
    'Jak wyglądałaby przyjazna wersja klasycznego filmowego potwora?', 'Jaki wynalazek od razu pokochałaby osoba ze średniowiecza?',
    'Co chmura mogłaby opisywać w swoim pamiętniku?', 'Jak zaprojektujesz park rozrywki bez karuzel i kolejek?',
    'Jakie fantastyczne zwierzę byłoby dobrym towarzyszem podróży pociągiem?', 'Jaki szósty zmysł przydałby się na co dzień?',
    'Jak wyglądałby kryminał, w którym nikt nie umie kłamać?', 'Jaka nietypowa waluta sprawdziłaby się na wyspie kucharzy?',
    'Co umieścisz na zupełnie pustym placu miejskim?', 'Jak wyglądałby wymarzony dom, gdyby każdy pokój był porą roku?',
    'Jaka nieszkodliwa rzecz byłaby wielkim skarbem w twoim wymyślonym świecie?', 'Jaka nazwa pasowałaby do statku kosmicznego tej grupy?',
    'Jak wyjaśnisz robotowi, co to znaczy przytulność?', 'Która postać z bajki pilnie potrzebowałaby dziś zmiany zawodu?',
    'Co mogłaby robić winda, gdyby miała własny wolny dzień?', 'Jak wyglądałaby szkoła, w której ciekawość jest jedynym przedmiotem?',
    'Jakie trzy zasady miałaby gra rozgrywana wyłącznie w głowie?', 'Jaka byłaby najbardziej niezwykła, ale sensowna wróżba w ciasteczku?',
    'Jak zmieniłoby się miasto, gdyby dachy zamieniono w ogrody?', 'Jakiego nowego słowa brakuje na uczucie, które znasz?',
    'Co detektyw wywnioskowałby o tobie z twojego śniadania?', 'Jak wyglądałaby wystawa złożona wyłącznie z zapachów?',
    'Jakie zadanie przejąłby u ciebie maleńki przyjazny smok domowy?', 'Jak brzmiałaby zabawna instrukcja obsługi niedzieli?',
    'Jak zaplanujesz podróż, w której moneta decyduje o każdym kierunku?', 'Jaki cud byłby spektakularny, ale zupełnie niepraktyczny na co dzień?',
    'Co mogłaby opowiadać książka, która sama wybiera czytelnika?', 'Jak działałby sklep sprzedający wspomnienia zamiast przedmiotów?',
    'Jaka nowa dyscyplina pasowałaby do igrzysk olimpijskich cierpliwości?', 'Jak brzmiałby pierwszy komunikat w podwodnym mieście?',
    'Jak nazwiesz planszówkę o swoim zawodzie lub codzienności?', 'Jaką wiadomość napisałoby ci twoje przyszłe zwierzątko?',
    'Jakie miłe zadanie można powierzyć bardzo małemu czarowi?', 'Jak mogłyby wyglądać napisy końcowe dzisiejszego wieczoru?',
  ],
} as const;
export const TASKS = {
  eisbrecher: [
    'Przedstaw się w trzech zdaniach, nie podając imienia, zawodu ani miejsca zamieszkania.', 'Opisz swoje idealne śniadanie jak krótką rekomendację restauracji.',
    'Wyjaśnij grupie drobną umiejętność, z której często korzystasz na co dzień.', 'Wymień trzy rzeczy, które dziś wypadły lepiej od twoich oczekiwań.',
    'Zadaj grupie nietypowe pytanie na poznanie się i najpierw odpowiedz na nie samodzielnie.', 'Opisz ulubione miejsce tak, by można je było sobie wyobrazić bez podawania nazwy.',
    'Wymyśl przyjazne powitanie pasujące do dzisiejszego wieczoru.', 'Krótko oprowadź grupę po przedmiocie, który leży teraz w pobliżu.',
    'Podsumuj swój dotychczasowy dzień w dokładnie sześciu słowach.', 'Poleć tej grupie wspólne zajęcie na wolne popołudnie.',
  ],
  spass: [
    'Wygłoś krótką, poważną mowę dziękczynną dla zgubionej skarpetki.', 'Sprzedaj niewidzialną łyżkę za pomocą zupełnie przesadzonego hasła reklamowego.',
    'Przez dziesięć sekund komentuj siedzenie jak pasjonujący finał sportowy.', 'Powiedz „Zupa gotowa” jak dramatyczną zapowiedź filmu.',
    'Poważnym głosem wyjaśnij, dlaczego poduszki zasługują na urlop.', 'Odegraj krótki dialog budzika ze zmęczonym człowiekiem.',
    'Pokaż trzy różne miny na widok niespodziewanie pustej lodówki.', 'Wymyśl absurdalnie zawiłą nazwę zastępującą słowo „krzesło”.',
    'Przedstaw prognozę pogody dla swojego obecnego nastroju z zabawnym zwrotem akcji.', 'Uzasadnij w dwóch zdaniach, dlaczego banan powinien zostać burmistrzem.',
  ],
  party: [
    'Zanuć krótko własną melodię przewodnią dzisiejszego wieczoru.', 'Zapowiedz następną rundę jak krótką audycję radiową.',
    'Wymyśl bezalkoholowy drink, jego nazwę i trzy składniki.', 'Siedząc, pokaż prosty ruch taneczny tylko ramionami i dłońmi.',
    'Ułóż miniplaylistę: po jednej piosence na przybycie, kulminację i powrót do domu.', 'Wystukaj krótki rytm na własnych udach i go powtórz.',
    'Wymyśl zaproszenie na imprezę o nietypowym, ale przytulnym motywie.', 'Serdecznie powitaj gościa, który nikogo tu nie zna.',
    'Opisz wymyślony festiwal z jedną sceną i wyjątkowym dodatkiem.', 'Wygłoś krótki toast za coś codziennego, bez zachęcania do picia.',
  ],
  freundschaft: [
    'Sformułuj szczery komplement dotyczący cechy, którą cenisz w tej grupie.', 'Wyjaśnij w dwóch zdaniach, jak podniesiesz przyjaciela na duchu po nieudanym dniu.',
    'Zaplanuj wspólną wycieczkę, która nic nie kosztuje i nikogo nie wyklucza.', 'Wymyśl mały rytuał pomagający przyjaciołom utrzymywać kontakt mimo odległości.',
    'Wymień trzy sposoby oferowania pomocy bez narzucania się.', 'Ułóż przyjazną wiadomość na odnowienie kontaktu po długiej ciszy; niczego nie wysyłaj.',
    'Odegraj krótkie, szczere przeprosiny za nieobecność na umówionym spotkaniu.', 'Znajdź obraz lub porównanie oddające istotę dobrej przyjaźni.',
    'Wymień praktyczną umiejętność, której możesz dobrowolnie nauczyć grupę.', 'Opisz małą wspólną tradycję pasującą do tej grupy.',
  ],
  liebe: [
    'Zaplanuj swobodną pierwszą randkę z budżetem zero euro.', 'Ułóż komplement dotyczący uważności zamiast wyglądu.',
    'Odegraj uprzejmą i jednoznaczną odmowę przyjęcia zaproszenia.', 'Wymyśl list miłosny filiżanki herbaty do jej spodka.',
    'Wymień trzy małe gesty okazujące uczucie bez kontaktu fizycznego.', 'Opisz w dwóch zdaniach pełen szacunku sposób zapytania o kolejne spotkanie.',
    'Wymyśl tytuł romantycznego filmu o dwojgu ludziach w kolejce.', 'Ułóż zdanie, którym jasno i życzliwie wyznaczysz osobistą granicę.',
    'Zaproponuj wspólną niedzielę, podczas której obie osoby mają też czas dla siebie.', 'Ułóż w głowie krótkie wyznanie miłości do ulubionego jedzenia i je wygłoś.',
  ],
  erinnerungen: [
    'Opisz swój dawny pokój dziecięcy za pomocą trzech konkretnych szczegółów.', 'Wyjaśnij zasady gry lubianej przez ciebie w dzieciństwie.',
    'Opowiedz miłe drobne wspomnienie jako wiadomość radiową w trzech zdaniach.', 'Wymień trzy rzeczy z czasów szkolnych, które dziś prawie zniknęły.',
    'Opisz swoje dawne ulubione danie bez zdradzania nazwy; grupa może zgadywać.', 'Daj swojemu młodszemu ja życzliwą radę w jednym zdaniu.',
    'Wymyśl tytuł albumu ze zdjęciami z pięknego etapu życia.', 'Pokaż dłońmi rozmiar przedmiotu, który w dzieciństwie wydawał ci się ogromny.',
    'Opowiedz o dawnej małej próbie odwagi, którą dziś ciepło wspominasz.', 'Opisz wspomnienie wyłącznie wrażeniami zmysłowymi: dźwiękiem, zapachem i kolorem.',
  ],
  reisen: [
    'Krótko oprowadź grupę po swojej miejscowości, nie wymieniając atrakcji turystycznych.', 'Spakuj w myślach pięć przedmiotów na spontaniczną jednodniową wycieczkę i uzasadnij wybór jednego z nich.',
    'Opisz krajobraz jak pocztówkę w dokładnie trzech zdaniach.', 'Zaplanuj deszczowy dzień w obcym miejscu bez wydawania pieniędzy na wstęp.',
    'Wymyśl przyjazną wskazówkę dla podróżnych w wyimaginowanej wiosce.', 'Przedstaw wymarzoną trasę kolejową z trzema zupełnie różnymi przystankami.',
    'Bez słów pokaż, jak zapytasz o drogę do kawiarni.', 'Poleć grupie małą przygodę, do której można dotrzeć w ciągu godziny.',
    'Opisz nietypowy nocleg, w którym chcesz spędzić jedną noc.', 'Wymyśl turystyczne hasło reklamowe dla niepozornego miejsca, takiego jak parking lub klatka schodowa.',
  ],
  traeume: [
    'Opisz marzenie i pierwszy krok, który zajmie mniej niż dziesięć minut.', 'Wygłoś krótkie podziękowanie swojemu przyszłemu ja za dobry nowy nawyk.',
    'Wymyśl tytuł kursu, na który pójdziesz z czystej ciekawości.', 'Namaluj słowami zwykły poranek w swojej wymarzonej codzienności.',
    'Wymień trzy rzeczy, których chcesz kiedyś się uczyć bez konieczności mistrzowskiego opanowania.', 'Ułóż życzliwe motto na swój następny miesiąc.',
    'Przedstaw wspólny projekt na przyszłość, który ta grupa mogłaby rozpocząć w weekend.', 'Opowiedz o dziecięcym marzeniu tak, jakby to był zupełnie nowy pomysł.',
    'Wymyśl małe świętowanie sukcesu, którego nikt inny by nie zauważył.', 'Opisz kapsułę czasu z trzema rzeczami dobrze reprezentującymi twoje dzisiejsze ja.',
  ],
  entscheidungen: [
    'W dwóch zdaniach obroń przerwę jako mądrą decyzję.', 'Zaproponuj sprawiedliwy podział trzech nieprzyjemnych obowiązków domowych między trzy osoby.',
    'Podaj dobry powód do planowania i równie dobry do spontaniczności.', 'Przećwicz uprzejmą odmowę zaproszenia bez wymyślania wymówki.',
    'Wyjaśnij wymyślonemu dziecku na codziennym przykładzie, czym jest sprawiedliwość.', 'Podaj drobną decyzję zakupową i możliwą bardziej ekologiczną alternatywę.',
    'Ułóż zdanie, którym możesz zmienić swoje stanowisko po usłyszeniu dobrego argumentu.', 'Przedstaw dwa sprawiedliwe rozwiązania, gdy grupa nie może wybrać restauracji.',
    'Opisz osobistą zasadę ułatwiającą ci życie i jeden dozwolony wyjątek.', 'Wymyśl krótką reklamę cierpliwości zamiast produktu.',
  ],
  kreativ: [
    'Wymyśl w trzech zdaniach historię z kluczem, chmurą i piekarnią.', 'Nadaj przedmiotowi w pokoju supermoc i zabawną słabość.',
    'Wymyśl nowe słowo na radość z odwołania męczących planów.', 'Opisz przyjaznego potwora i jego ulubione zajęcie.',
    'Wymyśl dwie linijki reklamy niewidzialnego parasola.', 'Dwoma różnymi głosami odegraj rozmowę Słońca z Księżycem.',
    'Zaprojektuj w myślach nowe święto z nazwą i prostą tradycją.', 'Wymyśl tytuł książki i pierwsze zdanie historii o tej butelce.',
    'Opisz pokój, w którym grawitacja nie działa wyłącznie na meble.', 'Wymyśl maleńkie zaklęcie rozwiązujące dokładnie jeden nieszkodliwy codzienny problem.',
  ],
} as const;
