/** Complete English edition, in the same order as editorial-de.ts. */
export const QUESTIONS = {
  eisbrecher: [
    "What little luxury makes an ordinary day better for you?", "What do guests probably notice first in your home?",
    "What topic makes you lose track of time when you talk about it?", "What skill would you immediately offer a new housemate?",
    "What does your ideal free morning look like?", "What food do you order when you can't decide?",
    "How can people tell you're comfortable in a group?", "What activity calms you down surprisingly reliably?",
    "What do you usually keep within reach beside your bed?", "What unassuming little thing are you surprisingly good at?",
    "What smell instantly reminds you of a lovely place?", "How would you describe your sense of humour to someone who doesn't know you?",
    "What part of your daily routine would you love to hand over to a robot?", "Where is your favourite spot for people-watching?",
    "Which app would you install first on a new phone?", "What drink marks the start of a cosy evening for you?",
    "Which season best matches your temperament?", "What do you collect without ever having decided to?",
    "What compliment do you especially enjoy hearing?", "How much planning does a good Sunday need for you?",
    "What harmless little thing gets you disproportionately excited?", "Which board or card game brings out your competitive side?",
    "What would you show a visitor to your area first?", "What question do people ask you far too rarely?",
    "How do you choose what to read or watch next?", "What does the bag you're using reveal about your everyday life?",
    "What kind of weather do you enjoy more than most people?", "What animal captures your energy on a Monday morning?",
    "What would you rather buy second-hand than new?", "What makes a good café for you?",
    "Which household chore do you actually enjoy?", "How do you decide whether to accept an invitation?",
    "What would be a small surprise that really suits you?", "What item of clothing would you hate to part with?",
    "What sound tells you you're home?", "What do you want to understand first about someone new?",
    "What meal can you make successfully without a recipe?", "What time of day do you feel most alert?",
    "What is an absolute picnic essential for you?", "What object near you has a story behind it?",
    "How would you spend ten unexpected free minutes?", "What was your last really good spur-of-the-moment idea?",
    "What kind of shop can you hardly walk past without looking inside?", "What makes you want to keep a conversation going?",
    "What habit have you picked up from someone else?", "What would you take charge of at a group cooking evening?",
    "What word do you probably use more than other people?", "What is a sign of good hospitality to you?",
    "What question would you like to ask this group?", "What should someone know about you before planning an outing with you?",
  ],
  spass: [
    "What completely trivial thing do you defend with surprising passion?", "What's the funniest slip of the tongue you can remember making?",
    "What harmless rule have you invented just for yourself?", "What activity do you sometimes commentate on like a sports reporter?",
    "Which film character would be a disastrous housemate for you?", "What talent do you regularly overestimate?",
    "What sound can you imitate surprisingly convincingly?", "What silly fear did you have as a child?",
    "What would be the least fitting advertising slogan for your daily life?", "What little thing do you keep misplacing in the same absurd spot?",
    "What dish looks worse than it tastes when you make it?", "When did you last laugh at your own mistake?",
    "What expression did you misunderstand for a long time?", "What would you write on a trophy for your worst trait?",
    "What strange combination do you genuinely enjoy eating?", "What everyday object would be the hardest to have as a pet?",
    "What situation makes you laugh even when you're trying to stay serious?", "What was your unnecessarily complicated solution to a simple problem?",
    "What imaginary law would ban your most annoying habit?", "What tiny inconvenience makes you inwardly dramatic?",
    "What would a sitcom about your last month be called?", "What supposedly cool phase of yours seems especially funny in hindsight?",
    "What's the strangest excuse you've managed to believe yourself?", "What tech mishap made you surprise yourself the most?",
    "What completely useless talent would you put on a job application?", "Which piece of furniture seems capable of being in a bad mood?",
    "What little thing do you turn into a ridiculously big ceremony?", "What unusual stage name would you use in a magic show?",
    "What harmless lie about everyday life would be easy to see through?", "What was your funniest shopping misunderstanding?",
    "What food do you think should come with instructions?", "What role would you get in a chaotic spaceship crew?",
    "What does your inner voice sound like when you have to assemble something?", "What do you find funny even though you can barely explain the joke?",
    "What would be the most ridiculous cause of a bitter feud between neighbours?", "What everyday movement looks unintentionally elegant when you do it?",
    "What word sounds nothing like its meaning to you?", "What would your fridge reveal about you?",
    "Which sport would be funniest if played with office equipment?", "What was your funniest autocorrect moment?",
    "What object of yours deserves a name?", "How would you tell the story of a boring shopping trip as an action film?",
    "What ridiculous debate could still keep you occupied for twenty minutes?", "What would be a surprisingly honest title for your cookbook?",
    "Which of your habits might an alien misunderstand?", "Which animal would be the most distracting newsreader?",
    "What bad purchase at least gave you a good story?", "What habit would you immediately recognise in your double?",
    "What ordinary sentence could be delivered as a dramatic warning in a film?", "What was the funniest wrong assumption someone made about you?",
  ],
  party: [
    "What song gets you moving even after a long day?", "What separates a good party from a merely loud one?",
    "What concert would you love to experience for the first time again?", "What role do you automatically take on at parties?",
    "What theme would genuinely tempt you to a fancy-dress party?", "What song do you associate with a particular friendship?",
    "What's your perfect way to finish a long evening?", "What little thing makes a host unforgettable?",
    "What song do you sing along to even though you only know the chorus?", "What was your best conversation away from a dance floor?",
    "What instrument would you want to play in a band?", "What party pleasantly surprised you after you hadn't felt like going?",
    "What does a buffet need for you to be happy?", "What musical genre did you only learn to appreciate later?",
    "How would you get strangers talking to each other at a party?", "Which artist would you choose for a tiny living-room concert?",
    "What's your fondest festival memory?", "What song should play over your personal closing credits?",
    "What party tradition could you happily get rid of?", "What's more important to you at a party: familiar faces or new encounters?",
    "What music recommendation from someone you know really hit the mark?", "How would you make a birthday special with very little money?",
    "What dance move always feels right to you?", "What would your own radio show be about?",
    "What celebration would you rather hold outdoors than indoors?", "What song reminds you of a long journey?",
    "What was the most creative invitation you've received?", "What three things help guests feel comfortable quickly?",
    "What song would you play someone to help them understand your mood?", "What makes a games night with others a success for you?",
    "What musical opinion do you share with almost nobody?", "What unusual food would make a good midnight snack?",
    "How do you know it's time to go home?", "What would you rather do yourself at a party than have someone organise for you?",
    "What song lyrics have particularly stayed with you?", "What kind of birthday surprise would overwhelm you?",
    "What sound in a live recording do you love?", "What kind of celebration needs no special occasion for you?",
    "What's your ideal length for a shared playlist?", "What music do you play while tidying up after guests?",
    "What was a lovely wedding moment outside the ceremony?", "What place would be unusual but cosy for a small party?",
    "How would you make a party interesting without speakers?", "What album do you prefer listening to as a whole rather than as individual songs?",
    "What's the best conversation starter at a table of strangers?", "What musical discovery would you like to share with the group?",
    "What would a party that exactly matches your energy level look like?", "What memory do you associate with a particular dance?",
    "What would you deliberately do differently at your next party?", "What would tonight's playlist be called?",
  ],
  freundschaft: [
    "How did you realise an acquaintance had become a friend?", "What small gesture from friends means a lot to you?",
    "What can you do with friends without needing to talk much?", "How do you stay in touch with people who live far away?",
    "What quality in your friends has changed you?", "What's a good way to get back in touch after a long silence?",
    "What shared mishap brought you closer together?", "How do you show a friend you're really listening?",
    "What would you try with a friend but not alone?", "What tradition should never become an obligation in a friendship?",
    "When have you been especially proud of someone in your circle of friends?", "How much spontaneity fits into your plans with friends?",
    "What do you appreciate about friends who are very different from you?", "What kind of support is easy for you to offer?",
    "How can someone honestly disagree with you without making you shut down?", "What outing with friends do you remember especially vividly?",
    "What makes a good apology between friends?", "What kind of message brightens an ordinary day for you?",
    "What would you ask a friend about rather than the internet?", "What boundary has become important to you in friendships?",
    "What shared activity brings different kinds of people together?", "How do you recognise when someone needs company rather than advice?",
    "What was the most thoughtful gift you've received from a friend?", "What friendship began in an unexpected place?",
    "How does the way you talk change around your closest friends?", "What shouldn't someone take personally if they're friends with you?",
    "What quality makes someone a good travel companion?", "What would you suggest doing if you had a free hour together?",
    "What memory would you like to compare notes on with an old friend?", "How do you celebrate your friends' small successes?",
    "What helps you reconnect after a disagreement?", "What shared project could enrich your friendship?",
    "What have your friends taught you about yourself?", "What kind of help do you find hard to accept?",
    "How important is punctuality to you in a friendship?", "What harmless inside joke could you explain to the group?",
    "What would you instantly recognise about a friend even after years apart?", "When is shared silence comfortable for you?",
    "What makes a new person feel welcome in an established group?", "What friendship would you like to nurture more often in everyday life?",
    "What's the difference between loyalty and blindly agreeing?", "What activity works better with friends than with family?",
    "How would you cheer up a friend after a disappointing day?", "What shared habit do you sometimes miss?",
    "How can people tell you need time to yourself?", "What surprising thing in common brought you closer to someone?",
    "What's a good reason to simply thank a friend?", "How do you handle friendships with different levels of closeness?",
    "What skill of a friend's do you admire, secretly or openly?", "What would you like to be more mindful of as a friend?",
  ],
  liebe: [
    "What kind of attention makes you feel seen?", "What makes a first date feel relaxed for you?",
    "What small everyday scene do you find romantic?", "How do you know you can trust someone?",
    "When getting to know someone, what would you rather share in person than by text?", "What quality becomes more attractive to you over time?",
    "What does closeness mean to you beyond physical touch?", "How should someone respond when you express a boundary?",
    "What shared habit could enrich a relationship?", "What would be a lovely date that costs almost nothing?",
    "How do you show affection when you can't find the right words?", "What idea of romance doesn't suit you at all?",
    "What would you like to know early on about a partner's daily life?", "What kind of humour helps you flirt?",
    "When do you feel particularly connected during a conversation?", "What do you need to stay independent in a relationship?",
    "When getting to know someone, what question reveals more than their job?", "How do you handle someone needing much more quiet time than you?",
    "What compliment would genuinely make you happy on a date?", "What's a good sign after a disagreement?",
    "What shared experience reveals a lot about how people get along?", "How important are similar hobbies in a relationship?",
    "What would make a love letter feel personal to you?", "What kind of surprise do you enjoy in relationships?",
    "What should be said regularly in a relationship?", "How do you distinguish respectful interest from pushy behaviour?",
    "How would you spend a day off together without screens?", "What little thing can ease your nerves when meeting someone?",
    "What's the difference between being infatuated and feeling deeply familiar with someone?", "What relationship in a film feels believable to you?",
    "How much joint planning feels good to you?", "What would be a thoughtful gesture in a long-distance relationship?",
    "What kind of conversation would you rather have while walking?", "How would you like someone to approach you when something is visibly bothering you?",
    "What have you learned about your own needs?", "What quality makes someone a good listener on a date?",
    "How can you show affection without spending money?", "What's a healthy way to have different interests?",
    "What shared decision should nobody make alone?", "What does reliability mean to you in practical terms?",
    "What's a fair way to handle different energy levels?", "What kind of conversation would you never want to squeeze into a spare moment?",
    "What can a couple learn from good friendships?", "What little tradition would you like to try as a couple?",
    "How important is it to you that the people around you know your partner well?", "What's a charming way to show interest without putting someone under pressure?",
    "What boundary do you have around public displays of affection?", "How would you know a relationship is good for you?",
    "What would you want to do first when reunited after a long time apart?", "What idea of a good relationship has changed for you?",
  ],
  erinnerungen: [
    "What little detail from your childhood can you still describe precisely?", "What route to school has particularly stayed in your memory?",
    "What was the first thing you bought yourself that made you proud?", "What kitchen do you associate with feeling safe and at home?",
    "What game could you play for hours when you were younger?", "What was an unexpectedly lovely rainy day?",
    "What adult took you seriously when you were a child?", "What holiday ritual would you like to bring back?",
    "What was the first achievement outside school that you really recognised as your own?", "What place do you now know only through memories?",
    "What story was often told in your family?", "What was your funniest attempt to seem grown-up?",
    "What former passion could easily draw you in again today?", "What scene from your old neighbourhood has stayed with you?",
    "What were you better at as a child than you are now?", "What gift completely surprised you back then?",
    "What did your favourite childhood hideaway look like?", "What first meeting do you remember in unusual detail?",
    "What was a small brave moment in your youth?", "What outing went differently from the plan but was lovely anyway?",
    "Who taught you a practical skill?", "What used to be a special meal but is ordinary now?",
    "What photo would you like to take again?", "What old family habit do you understand better today?",
    "What did you underestimate when you first lived on your own?", "What sound do you miss from an earlier stage of life?",
    "What goodbye later turned into a good beginning?", "What school lesson stayed with you for a surprising reason?",
    "What object has survived several moves with you?", "What did you do with the first money you earned yourself?",
    "Who from your past would you like to ask for their perspective on a memory?", "What was your first big misconception about the adult world?",
    "What childhood birthday party has stayed with you?", "What did you collect when you were younger, and why?",
    "What film felt like a really big event to you at the time?", "When did you first manage to find your way around a new city?",
    "What little tradition from your school days did you enjoy?", "What unexpected praise do you still remember?",
    "What travel preparation used to feel like part of the holiday itself?", "What would you tell your younger self about friendship?",
    "What scent takes you back to a particular season?", "What everyday moment only revealed its importance to you later?",
    "What former favourite outfit would you wear again today?", "What change in your hometown surprises you?",
    "What memory would you like to capture as a short film scene?", "What shared fit of laughter has stayed with you to this day?",
    "What surprised you the first time you travelled alone?", "What early decision had an unexpectedly big impact?",
    "What old letter or note have you kept for a good reason?", "What do you think will particularly stay with you from this stage of your life?",
  ],
  reisen: [
    "What do you look at first in a new place?", "What trip was better because something was left unplanned?",
    "What's your personal sign that a holiday has begun?", "What place near you have you never properly explored?",
    "What kind of landscape instantly makes you feel calm?", "What goes in your luggage even though others think it's unnecessary?",
    "What conversation during your travels particularly stayed with you?", "How do you decide whether a destination suits you?",
    "What would you do with a day alone in an unfamiliar city?", "What meal from your travels would you like to recreate?",
    "What makes a good train window seat for you?", "What everyday habit in another place impressed you?",
    "Where would you go if the journey itself were part of the adventure?", "What accommodation do you remember because of the people?",
    "What's your favourite way to get your bearings in a city?", "What travel souvenir do you actually use in daily life?",
    "How long does it take you to feel at home somewhere new?", "What journey would you like to make at a very leisurely pace?",
    "What have you learned about your own expectations while travelling?", "What place looks completely different in your memory than in photos?",
    "What small travel mishap can you now take in your stride?", "What would you show someone visiting your country for the first time?",
    "What language would you like to speak for conversations with locals?", "How important is being able to change plans when you travel?",
    "What's the best thing about coming home for you?", "What market or shop on your travels made you especially curious?",
    "What route would you rather experience on foot than by car?", "What should a good travel companion know about you?",
    "What view would you like to enjoy without a camera?", "How would you spend a free afternoon in bad weather while travelling?",
    "What travel idea have you put off simply because of the planning?", "What do you learn about a place by visiting a supermarket?",
    "What means of transport feels most adventurous to you?", "What unfamiliar city could you imagine making your temporary home?",
    "What's your best memory of a day trip?", "What kind of museum might tempt you inside on the spur of the moment?",
    "How do you find places beyond the obvious sights when travelling?", "What would you deliberately not research before a trip?",
    "What moment in nature surprised you during your travels?", "What trip disproved an expectation you had?",
    "What would be your ideal stop on a long journey?", "How does your holiday pace differ from your everyday pace?",
    "What place would you like to revisit in another season?", "What does treating an unfamiliar place respectfully mean to you?",
    "What brief travel encounter would you like to pick up again?", "What would make a nice route for an outing with this group?",
    "What skill unexpectedly helped you while travelling?", "What travel experience sounds unremarkable but was special to you?",
    "What would a day of travelling without entry tickets look like for you?", "What would you ask someone who has always lived there?",
  ],
  traeume: [
    "What small idea about the future are you looking forward to right now?", "What would you like to learn even if you never get especially good at it?",
    "How would you like an ordinary day to feel in five years?", "What project would interest you even without recognition?",
    "What kind of home would you like to create for yourself in the long term?", "What would you do with one free afternoon a week?",
    "What habit would you like to give your future self as a gift?", "What wish has become more important to you as you've grown older?",
    "What would you like to experience for the first time?", "What skill could make your daily life noticeably easier?",
    "What would you like to make yourself one day instead of buying it?", "What kinds of people would you like to have around you more in future?",
    "What plan requires courage more than money?", "How would you spend a year if nobody were judging your CV?",
    "What would you like to teach a younger person one day?", "What part of your life would you be happy to keep just as it is?",
    "What shared plan would you like to make with friends?", "What would you try if failure had no consequences?",
    "What kind of work could still bring you joy later in life?", "What would you like to be able to say about yourself one day?",
    "What old idea deserves a second attempt?", "What would your ideal place for a creative break look like?",
    "What wish have you barely ever said out loud?", "What would be a realistic first step towards a big goal?",
    "What tradition would you like to start among the people around you?", "What would you like to own less of so you could feel freer?",
    "What experience would be worth more to you than an expensive object?", "How would you like to celebrate a big personal achievement?",
    "What kind of adventure suits who you are today?", "What would you like to help shape in your local area?",
    "What childhood wish would still bring you joy today?", "How would you know you'd achieved enough?",
    "What would you like to do differently next winter?", "What new connection between your interests would you like to discover?",
    "What would you like to look back on proudly, even if nobody else sees it?", "What space in your calendar would you like to protect?",
    "What would you like to present to a small audience one day?", "What kind of community would you like to create or find?",
    "What could be a good motto for your next year of life?", "What goal would you pursue without comparing yourself to others?",
    "What would you deliberately take with you or leave behind on your next move?", "What gradual change would you like to begin?",
    "Who would you like to give something back to one day?", "What would make it worthwhile for you to become a beginner again?",
    "What memory would you still like to create with your family?", "What would you do with a small empty room?",
    "What quality would you like to keep as you grow old?", "What would you like to celebrate more often next year?",
    "What dream could you put into practice soon on a smaller scale?", "What unanswered question about your future feels exciting right now?",
  ],
  entscheidungen: [
    "What kind of decision genuinely benefits from sleeping on it?", "What has become more important to you than making a good first impression?",
    "When would you give up convenience for fairness?", "What decision would you rather make by instinct than with a list?",
    "What does success mean to you beyond money and work?", "What boundary around your time would you like to protect better?",
    "When did a good argument change your mind?", "What makes a promise binding for you?",
    "How do you know a compromise goes too far for you?", "What small decision affects your mood more than you'd expect?",
    "When is honesty without further explanation especially important?", "What would you rather repair even if buying a replacement were easier?",
    "What kind of risk do you enjoy taking?", "How do you choose between two equally good options?",
    "What makes someone credible in your eyes?", "What would you like to be more patient about in everyday life?",
    "When can saying no be a kind decision?", "What belief of yours would you like to examine more closely?",
    "What matters more to you in an apology: words or behaviour?", "How much uncertainty do you need to keep life interesting?",
    "What convenient habit doesn't quite fit your values?", "When have you given up money in exchange for time?",
    "What should people share even if it belongs to them alone?", "What decision would you not put to a group vote?",
    "How do you recognise advice that genuinely suits you?", "What's the difference between generosity and trying to please people?",
    "What little thing deserves more appreciation than it gets?", "When is it wiser to let go of a project you've started?",
    "What would you like to be more mindful about as a consumer?", "What quality matters more to you than impressive ability?",
    "How do you deal with a decision that only later turns out to be wrong?", "What would you protect first on a limited budget?",
    "When should a rule allow a justified exception?", "What does responsibility mean in a shared home?",
    "What opinion do you hold even without your friends' agreement?", "What helps you stop putting a decision off endlessly?",
    "When is a difficult conversation worth more than harmony?", "What decision gave you freedom?",
    "What should someone know before judging other people's success?", "How much planning gives you security, and when does it become control?",
    "What makes a division of tasks fair?", "What kind of competition do you find enriching?",
    "What wouldn't you take a shortcut on, even on a tiring day?", "When is it helpful to correct your own opinion publicly?",
    "What opportunity would you rather turn down to stay true to yourself?", "How do you distinguish a real need from a passing wish?",
    "What about your lifestyle might surprise other people?", "What decision would you make more calmly today than in the past?",
    "How do you know you need a break rather than a new solution?", "What everyday action best expresses your values?",
  ],
  kreativ: [
    "What secret room would you build into a library?", "What would a holiday you invented yourself look like?",
    "What two ordinary jobs would combine into one fantastic new one?", "What would a museum about your daily life today display?",
    "What superpower would only be useful around the house?", "What would a city built for night owls look like?",
    "What object would you give a voice to for a day?", "What would be a good opening scene for a film about this group?",
    "What new sport could you invent without equipment?", "What would a restaurant with a menu organised by moods look like?",
    "What would you leave in a time capsule for people a hundred years from now?", "What colour would a sound you like be?",
    "How would you turn a boring waiting area into a favourite place?", "What animal ability would be surprisingly useful in an office?",
    "What would be the main problem in a world where everyone's thoughts appeared as subtitles?", "What everyday event deserves its own soundtrack?",
    "What would a friendly version of a classic movie monster look like?", "What invention would someone from the Middle Ages instantly love?",
    "What might a cloud write in its diary?", "How would you design an amusement park without rides?",
    "What imaginary animal would make a good companion on a train journey?", "What would be a useful sixth sense for everyday life?",
    "What would a detective story look like if nobody could lie?", "What unusual currency would work on an island of cooks?",
    "What would you put in a completely empty town square?", "What would a dream home look like if each room were a season?",
    "What harmless thing would be a great treasure in your imaginary world?", "What would be a good name for this group's spaceship?",
    "How would you explain cosiness to a robot?", "What fairy-tale character would urgently need a career change today?",
    "What might a lift do if it had a day off of its own?", "What would a school look like if curiosity were its only subject?",
    "What three rules would a game played only in your head have?", "What would be the most unusual but meaningful fortune-cookie message?",
    "How would a city change if its rooftops became gardens?", "What new word is missing for a feeling you know?",
    "What would a detective deduce about you from your breakfast?", "What would an exhibition made entirely of smells look like?",
    "What job would a tiny friendly house dragon take on in your home?", "What would be a funny set of instructions for a Sunday?",
    "How would you plan a journey where a coin decides every direction?", "What miracle would be spectacular but completely impractical in daily life?",
    "What story might a book that chooses its own reader tell?", "How would a shop selling memories rather than objects work?",
    "What new event would fit the Olympics of patience?", "What would be the first announcement in an underwater city?",
    "What would you call a board game about your job or daily life?", "What message would your future pet write to you?",
    "What would be a lovely task for a very small spell?", "What could the closing credits for tonight look like?",
  ],
} as const;

export const TASKS = {
  eisbrecher: [
    "Introduce yourself in three sentences without mentioning your name, job or where you live.", "Describe your perfect breakfast as a short restaurant recommendation.",
    "Explain a small skill you often use in daily life to the group.", "Name three things that were better today than expected.",
    "Ask the group an unusual getting-to-know-you question and answer it yourself first.", "Describe a favourite place so people can picture it without hearing its name.",
    "Invent a friendly greeting that suits tonight.", "Give a short guided tour of an object near you.",
    "Sum up your day so far in exactly six words.", "Suggest an activity you'd recommend to this group for a free afternoon together.",
  ],
  spass: [
    "Give a short, serious acceptance speech for a lost sock.", "Sell an invisible spoon with a wildly exaggerated advertising slogan.",
    "Commentate on sitting down for ten seconds as if it were an exciting sporting final.", "Say 'The soup is ready' like a dramatic film trailer announcement.",
    "Explain in a serious voice why cushions deserve a holiday.", "Act out a short dialogue between an alarm clock and a tired person.",
    "Make three different facial expressions in response to a surprisingly empty fridge.", "Invent an absurdly long-winded name for a chair.",
    "Give a weather forecast for your current mood with a silly twist.", "Explain in two sentences why a banana should become mayor.",
  ],
  party: [
    "Briefly hum a theme tune you've invented for tonight.", "Introduce the next round as if you were hosting a little radio show.",
    "Invent an alcohol-free drink with a name and three ingredients.", "While seated, show a simple dance move using only your shoulders and hands.",
    "Put together a mini playlist: one song each for arrival, the highlight and the journey home.", "Tap a short rhythm on your own thighs and repeat it.",
    "Invent an invitation to a party with an unusual but cosy theme.", "Give a warm welcome to a guest who doesn't know anyone here.",
    "Describe an imaginary festival with just one stage and one special extra.", "Give a short toast to something ordinary, without asking anyone to drink.",
  ],
  freundschaft: [
    "Give an honest compliment about a quality you appreciate in this group.", "Explain in two sentences how you'd cheer up a friend after a day that went wrong.",
    "Plan a free outing together that doesn't exclude anyone.", "Invent a little ritual that helps friends stay in touch despite the distance.",
    "Name three ways to offer help without imposing.", "Compose a friendly message to reconnect after a long silence; don't send anything.",
    "Act out a short, sincere apology for missing a get-together.", "Find an image or comparison that captures what makes a good friendship.",
    "Name a practical skill you could volunteer to teach the group.", "Describe a small shared tradition that would suit this group.",
  ],
  liebe: [
    "Plan a relaxed first date with a budget of zero.", "Give a compliment about someone's thoughtfulness rather than their appearance.",
    "Act out how you would politely and clearly decline an invitation.", "Invent a love letter from a teacup to its coaster.",
    "Name three little gestures that show affection without physical contact.", "Describe a respectful way to ask for another date in two sentences.",
    "Invent a romantic film title about two people in a queue.", "Formulate a sentence that expresses a personal boundary clearly and kindly.",
    "Suggest a Sunday plan for a couple that also gives both people time to themselves.", "Think up a short declaration of love to your favourite food and deliver it.",
  ],
  erinnerungen: [
    "Describe your childhood bedroom using three specific details.", "Explain the rules of a game you enjoyed playing as a child.",
    "Tell a lovely little memory as a three-sentence radio news item.", "Name three things from your school days that have almost disappeared today.",
    "Describe a former favourite food without naming it; the group can guess.", "Give your younger self one sentence of friendly advice.",
    "Invent a fitting title for a photo album of a happy period of your life.", "Use your hands to show the size of an object that seemed enormous as a child.",
    "Tell the group about a small childhood dare you now look back on fondly.", "Describe a memory using only sensory details: a sound, a smell and a colour.",
  ],
  reisen: [
    "Give a short guided tour of where you live without mentioning any sights.", "Mentally pack five things for a spontaneous day trip and explain one of your choices.",
    "Describe a landscape as a postcard in exactly three sentences.", "Plan a rainy day in an unfamiliar place without paying any entry fees.",
    "Invent a friendly tip for travellers in an imaginary village.", "Present your dream train route with three very different stops.",
    "Show how you'd ask for directions to a café without words.", "Recommend a little adventure to the group that might be reachable within an hour.",
    "Describe an unusual place to stay where you'd spend one night.", "Invent a travel slogan for an unremarkable place such as a car park or hallway.",
  ],
  traeume: [
    "Describe a wish and a first step towards it that takes less than ten minutes.", "Give a short speech thanking your future self for a good new habit.",
    "Invent the title of a course you'd take purely out of curiosity.", "Paint a picture in words of an ordinary morning in your ideal everyday life.",
    "Name three things you'd like to learn without having to master them.", "Create a kind motto for your next month.",
    "Present a future project this group could start together over a weekend.", "Explain a childhood wish as if you were discovering it anew today.",
    "Invent a little celebration for an achievement nobody else would notice.", "Describe a time capsule containing three things that represent who you are today.",
  ],
  entscheidungen: [
    "Defend taking a break as a wise decision in two sentences.", "Propose a fair way to divide three unpleasant chores between three people.",
    "Give one good reason for planning and an equally good one for spontaneity.", "Practise politely declining an invitation without inventing an excuse.",
    "Explain fairness to an imaginary child using an everyday example.", "Name a small purchasing decision and a possible more sustainable alternative.",
    "Formulate a sentence you could use to change your mind after hearing a good argument.", "Suggest two fair solutions when a group can't agree on a restaurant.",
    "Describe a personal rule that makes your daily life easier and one allowed exception.", "Invent a short advertising message for patience rather than a product.",
  ],
  kreativ: [
    "Invent a three-sentence story featuring a key, a cloud and a bakery.", "Give an object in the room a superpower and a silly weakness.",
    "Invent a new word for the joy of having tiring plans cancelled.", "Describe a friendly monster and its favourite pastime.",
    "Invent two lines of an advert for an invisible umbrella.", "Act out a conversation between the sun and moon using two different voices.",
    "Dream up a new holiday with a name and a simple tradition.", "Invent a book title and opening sentence for a story about this bottle.",
    "Describe a room where gravity doesn't apply to furniture, but does to everything else.", "Invent a tiny spell that solves exactly one harmless everyday problem.",
  ],
} as const;
