// Individually translated canonical cards.
const eisbrecherQuestions = [
  "Que pequeno luxo melhora um dia normal para ti?", "Qual é a primeira coisa em que as visitas reparam em tua casa?",
  "Sobre que assunto perdes a noção do tempo quando falas?", "Que habilidade oferecerias logo a alguém que viesse partilhar casa contigo?",
  "Como seria a tua manhã livre ideal?", "Que comida pedes quando não consegues decidir?",
  "Como se percebe que te sentes à vontade num grupo?", "Que atividade te acalma quase sempre, para tua surpresa?",
  "O que costumas ter à mão ao lado da cama?", "Que coisa discreta sabes fazer surpreendentemente bem?",
  "Que cheiro te lembra imediatamente um lugar bonito?", "Como descreverias o teu sentido de humor a quem não te conhece?",
  "Que parte da tua rotina entregarias de bom grado a um robô?", "Qual é o teu lugar preferido para observar as pessoas?",
  "Que aplicação instalarias primeiro num telemóvel novo?", "Com que bebida começa uma noite tranquila para ti?",
  "Que estação do ano combina melhor com o teu temperamento?", "O que colecionas sem nunca o teres decidido conscientemente?",
  "Que elogio gostas especialmente de ouvir?", "De quanto planeamento precisas para ter um bom domingo?",
  "Que pequena coisa inofensiva te entusiasma de forma desproporcionada?", "Que jogo de tabuleiro ou de cartas desperta a tua competitividade?",
  "O que mostrarias primeiro a alguém que visitasse a tua zona?", "Que pergunta te fazem muito menos vezes do que gostarias?",
  "Como escolhes o que vais ler ou ver a seguir?", "O que revela sobre o teu dia a dia a mala ou mochila que usas agora?",
  "De que tipo de tempo gostas mais do que a maioria das pessoas?", "Que animal representa a tua energia numa segunda-feira de manhã?",
  "O que preferes comprar em segunda mão em vez de novo?", "O que faz de um café um bom sítio para ti?",
  "Que tarefa doméstica fazes mesmo com gosto?", "Como decides se aceitas um convite?",
  "Que pequena surpresa seria mesmo a tua cara?", "De que peça de roupa te custaria abdicar?",
  "Que som te faz perceber que estás em casa?", "O que queres perceber primeiro numa pessoa que acabaste de conhecer?",
  "Que prato te sai bem mesmo sem receita?", "Em que altura do dia sentes a mente mais desperta?",
  "O que não pode faltar num piquenique para ti?", "Que objeto perto de ti tem uma história?",
  "Como passas dez minutos livres inesperados?", "Qual foi a tua última ideia espontânea mesmo boa?",
  "Por que tipo de loja te custa passar sem espreitar?", "O que te dá vontade de continuar uma conversa?",
  "Que hábito adotaste de outra pessoa?", "De que te encarregarias numa noite em que todos cozinham juntos?",
  "Que palavra achas que usas mais do que as outras pessoas?", "O que é, para ti, um sinal de boa hospitalidade?",
  "Que pergunta gostarias de fazer a este grupo?", "O que é preciso saber sobre ti para planear um passeio contigo?",
];
const eisbrecherTasks = [
  "Apresenta-te em três frases sem dizeres o teu nome, a tua profissão ou onde vives.", "Descreve o teu pequeno-almoço perfeito como uma breve recomendação de restaurante.",
  "Explica ao grupo uma pequena habilidade que usas muitas vezes no dia a dia.", "Diz três coisas que hoje correram melhor do que esperavas.",
  "Faz ao grupo uma pergunta invulgar para se conhecerem e responde primeiro.", "Descreve um lugar de que gostas para que se consiga imaginá-lo sem dizeres o nome.",
  "Inventa uma saudação simpática que combine com esta noite.", "Faz uma breve visita guiada a um objeto que tenhas por perto.",
  "Resume o teu dia até agora em exatamente seis palavras.", "Sugere uma atividade em conjunto que recomendarias a este grupo para uma tarde livre.",
];
const spassQuestions = [
  "Que coisa completamente irrelevante defendes com uma paixão surpreendente?", "Qual foi o teu lapso de linguagem mais engraçado de que te lembras?",
  "Que regra inofensiva inventaste só para ti?", "Que atividade comentas às vezes como se fosses um comentador desportivo?",
  "Que personagem de um filme seria um péssimo colega de casa para ti?", "Em que é que costumas sobrestimar o teu talento?",
  "Que som sabes imitar de forma surpreendentemente convincente?", "Que medo disparatado tinhas em criança?",
  "Qual seria o slogan publicitário menos adequado ao teu dia a dia?", "Que pequeno objeto perdes sempre no mesmo sítio absurdo?",
  "Que prato teu tem pior aspeto do que sabor?", "Quando te riste pela última vez de um erro teu?",
  "Que expressão interpretaste mal durante muito tempo?", "O que escreverias num troféu dedicado ao teu pior defeito?",
  "De que combinação estranha de comida gostas mesmo?", "Que objeto do dia a dia seria mais difícil ter como animal de estimação?",
  "Que situação te faz rir mesmo quando queres manter a seriedade?", "Que solução desnecessariamente complicada arranjaste para um problema simples?",
  "Que lei imaginária proibiria o teu hábito mais irritante?", "Que minúsculo incómodo te faz entrar num drama por dentro?",
  "Qual seria o título de uma série de comédia sobre o teu último mês?", "Que fase em que te achavas muito fixe te parece especialmente cómica agora?",
  "Qual é a desculpa mais estranha em que tu próprio acreditaste?", "Em que avaria tecnológica mais te surpreendeste a ti próprio?",
  "Que talento completamente inútil colocarias numa candidatura a um emprego?", "Que móvel imaginas capaz de estar de mau humor?",
  "Que pequena coisa fazes com uma cerimónia exagerada?", "Qual seria o teu nome artístico invulgar num espetáculo de magia?",
  "Que mentira inofensiva sobre o dia a dia seria fácil de desmascarar?", "Qual foi o teu engano mais cómico ao fazer compras?",
  "Que comida deveria ter um manual de instruções, na tua opinião?", "Que papel te dariam na tripulação caótica de uma nave espacial?",
  "Como soa a tua voz interior quando tens de montar alguma coisa?", "O que achas engraçado mesmo sem conseguires explicar bem a piada?",
  "Qual seria o motivo mais ridículo para uma discussão feroz entre vizinhos?", "Que movimento do dia a dia te sai involuntariamente elegante?",
  "Que palavra não te soa nada àquilo que significa?", "O que revelaria o teu frigorífico sobre ti?",
  "Que desporto seria mais cómico com material de escritório?", "Qual foi o teu momento mais engraçado com o corretor automático?",
  "Que objeto teu merece ter um nome?", "Como contarias uma ida aborrecida às compras como se fosse um filme de ação?",
  "Que debate ridículo conseguiria ocupar-te durante vinte minutos?", "Qual seria um título surpreendentemente honesto para o teu livro de receitas?",
  "Que hábito teu poderia ser mal interpretado por um extraterrestre?", "Que animal seria mais distrativo como apresentador de notícias?",
  "Que compra falhada te deixou pelo menos uma boa história para contar?", "Que hábito reconhecerias logo num sósia teu?",
  "Que frase normal poderia ser dita como um aviso dramático de um filme?", "Qual foi a suposição errada mais engraçada que alguém fez sobre ti?",
];
const spassTasks = [
  "Faz um discurso breve e sério de agradecimento por uma meia perdida.", "Vende uma colher invisível com um slogan publicitário completamente exagerado.",
  "Durante dez segundos, comenta o ato de estar sentado como uma final desportiva emocionante.", "Diz «A sopa está pronta» como um anúncio dramático de um filme.",
  "Explica com voz séria por que razão as almofadas merecem férias.", "Representa um diálogo breve entre um despertador e uma pessoa cansada.",
  "Faz três expressões diferentes perante um frigorífico inesperadamente vazio.", "Inventa um nome absurdamente complicado para a palavra «cadeira».",
  "Faz uma previsão do tempo para o teu estado de espírito atual com uma reviravolta disparatada.", "Explica em duas frases por que razão uma banana deveria ser presidente da câmara.",
];
const partyQuestions = [
  "Que música te põe a mexer mesmo depois de um dia longo?", "O que distingue uma boa festa de uma festa apenas barulhenta?",
  "Que concerto gostarias de voltar a viver como se fosse a primeira vez?", "Que papel assumes automaticamente nas festas?",
  "Que tema te convenceria mesmo a ir a uma festa de máscaras?", "Que música associas a uma amizade em particular?",
  "Como terminaria uma noite longa de forma perfeita para ti?", "Que pequeno gesto torna inesquecível quem recebe uma festa?",
  "De que música só sabes o refrão e mesmo assim cantas?", "Qual foi a melhor conversa longe da pista de dança?",
  "Que instrumento gostarias de tocar numa banda?", "Que festa te surpreendeu pela positiva apesar de não te apetecer ir?",
  "O que tem de haver num bufete para ficares satisfeito?", "Que género musical só aprendeste a apreciar mais tarde?",
  "Como porias a conversar pessoas que não se conhecem numa festa?", "Que artista escolherias para um concerto pequenino na sala?",
  "Qual é a tua recordação mais agradável de um festival?", "Que música deveria acompanhar os teus créditos finais pessoais?",
  "Que tradição das festas poderias abolir sem problema?", "Numa festa, o que valorizas mais: caras conhecidas ou conhecer pessoas novas?",
  "Que recomendação musical de alguém próximo acertou mesmo nos teus gostos?", "Como tornarias um aniversário especial com muito pouco dinheiro?",
  "Que movimento de dança te parece sempre certo?", "Qual seria o tema do teu próprio programa de rádio?",
  "Que festa preferirias organizar ao ar livre em vez de num espaço fechado?", "Que música te lembra uma viagem longa?",
  "Qual foi o convite mais criativo que recebeste?", "De que três coisas precisam as visitas para se sentirem logo à vontade?",
  "Que música mostrarias a alguém para perceber o teu estado de espírito?", "O que faz resultar uma noite de jogos em grupo para ti?",
  "Que opinião sobre música partilhas com quase ninguém?", "Que comida invulgar combinaria com uma pausa à meia-noite?",
  "Como percebes que chegou a hora de ir para casa?", "O que preferirias fazer pessoalmente numa festa em vez de deixar a organização a outros?",
  "Que letra de uma música te ficou especialmente na memória?", "Que surpresa de aniversário poderia ser demais para ti?",
  "Que som de uma gravação ao vivo adoras?", "Que festa não precisa de motivo nenhum para ti?",
  "Qual seria a duração ideal de uma lista de músicas partilhada?", "Que música te acompanha quando arrumas a casa depois das visitas?",
  "Que momento bonito recordas de um casamento, fora da cerimónia?", "Que lugar seria invulgar mas acolhedor para uma pequena festa?",
  "Como tornarias interessante uma festa sem colunas de som?", "Que álbum preferes ouvir de seguida em vez de músicas soltas?",
  "Qual é a melhor forma de iniciar uma conversa numa mesa de desconhecidos?", "Que descoberta musical gostarias de partilhar com o grupo?",
  "Como seria uma festa à medida do teu nível de energia?", "Que recordação associas a uma dança em particular?",
  "O que queres fazer de propósito de maneira diferente na tua próxima festa?", "Que título teria a lista de músicas desta noite?",
];
const partyTasks = [
  "Trauteia uma pequena melodia inventada por ti para esta noite.", "Apresenta a próxima ronda como se fosse um pequeno programa de rádio.",
  "Inventa uma bebida sem álcool com nome e três ingredientes.", "Sentado, mostra um movimento de dança simples usando apenas os ombros e as mãos.",
  "Cria uma pequena lista: uma música para a chegada, outra para o auge e outra para o regresso a casa.", "Bate um ritmo breve nas tuas próprias coxas e repete-o.",
  "Inventa um convite para uma festa com um tema invulgar mas acolhedor.", "Dá as boas-vindas de forma calorosa a alguém que não conhece ninguém aqui.",
  "Descreve um festival inventado com um só palco e um extra especial.", "Faz um brinde breve a algo do dia a dia, sem convidar ninguém a beber.",
];
const freundschaftQuestions = [
  "Como percebeste que uma pessoa conhecida se tinha tornado amiga?", "Que pequeno gesto dos teus amigos significa muito para ti?",
  "O que podes fazer com amigos sem ser preciso falar muito?", "Como manténs o contacto com quem vive longe?",
  "Que qualidade dos teus amigos também te mudou?", "Qual é uma boa forma de retomar o contacto depois de muito tempo sem notícias?",
  "Que percalço partilhado vos aproximou mais?", "Como mostras a um amigo que estás mesmo a ouvir?",
  "O que experimentarias com um amigo mas não a sós?", "Que tradição nunca deveria tornar-se uma obrigação numa amizade?",
  "Quando sentiste um orgulho especial por alguém do teu grupo de amigos?", "Quanto espaço para a espontaneidade têm os teus planos com amigos?",
  "O que valorizas nos amigos que são muito diferentes de ti?", "Que tipo de apoio te é fácil oferecer?",
  "Como te podem contrariar com sinceridade sem que te feches?", "Que passeio em conjunto recordas com especial nitidez?",
  "O que faz de um pedido de desculpa entre amigos um bom pedido de desculpa para ti?", "Que tipo de mensagem te alegra num dia normal?",
  "Sobre o que pedirias conselho a um amigo em vez de procurar na internet?", "Que limite numa amizade se tornou importante para ti?",
  "Que atividade em conjunto aproxima bem pessoas diferentes?", "Como percebes que alguém precisa de companhia em vez de conselhos?",
  "Qual foi o presente mais atencioso que recebeste de amigos?", "Que amizade nasceu num lugar inesperado?",
  "Como muda a tua forma de falar com os teus amigos mais próximos?", "O que não deve levar a peito quem é teu amigo?",
  "Que qualidade faz de alguém um bom companheiro de viagem?", "O que sugeririas para passarem uma hora livre juntos?",
  "Que recordação gostarias de comparar com a de um velho amigo?", "Como celebras os pequenos sucessos dos teus amigos?",
  "O que te ajuda a recuperar a proximidade depois de uma divergência?", "Que projeto em conjunto poderia enriquecer a vossa amizade?",
  "O que te ensinaram os teus amigos sobre ti próprio?", "Que tipo de ajuda te custa aceitar?",
  "Que importância tem para ti a pontualidade numa amizade?", "Que piada interna inofensiva podes explicar ao grupo?",
  "O que reconhecerias logo num amigo mesmo passados muitos anos?", "Quando te é agradável partilhar o silêncio?",
  "O que faz uma pessoa nova sentir-se bem-vinda num grupo já formado?", "Que amizade gostarias de cultivar mais no dia a dia?",
  "Qual é, para ti, a diferença entre lealdade e concordar cegamente?", "Que atividade resulta melhor com amigos do que com a família?",
  "Como animarias um amigo depois de um dia dececionante?", "De que hábito partilhado sentes por vezes falta?",
  "Como se percebe que precisas de tempo para ti?", "Que semelhança inesperada te aproximou de alguém?",
  "Qual é uma boa ocasião para dizer simplesmente obrigado a um amigo?", "Como lidas com o facto de algumas amizades serem mais próximas do que outras?",
  "Que habilidade de um amigo admiras em segredo ou abertamente?", "O que gostarias de fazer de forma mais consciente como amigo daqui para a frente?",
];
const freundschaftTasks = [
  "Faz um elogio sincero a uma qualidade que valorizas neste grupo.", "Explica em duas frases como animarias um amigo depois de um dia que correu mal.",
  "Planeia um passeio em conjunto que não custe nada e não exclua ninguém.", "Inventa um pequeno ritual para os amigos manterem o contacto apesar da distância.",
  "Diz três formas de oferecer ajuda sem te impores.", "Formula uma mensagem simpática para retomar o contacto após muito tempo sem notícias; não envies nada.",
  "Representa um pedido de desculpa breve e sincero por teres faltado a um encontro.", "Encontra uma imagem ou uma comparação que represente uma boa amizade.",
  "Diz uma habilidade prática que poderias ensinar ao grupo por vontade própria.", "Descreve uma pequena tradição em conjunto que combinaria com este grupo.",
];
const liebeQuestions = [
  "Que forma de atenção te faz sentir que realmente te veem?", "O que torna um primeiro encontro descontraído para ti?",
  "Que pequena cena do dia a dia achas romântica?", "Como percebes que podes confiar em alguém?",
  "Ao conhecer alguém, o que preferes contar pessoalmente em vez de por mensagem?", "Que qualidade se torna mais atraente para ti com o tempo?",
  "O que significa proximidade para ti para além do contacto físico?", "Como deve reagir alguém quando estabeleces um limite?",
  "Que hábito partilhado poderia enriquecer uma relação?", "Como seria um encontro bonito que custasse quase nada?",
  "Como mostras carinho quando te faltam as palavras certas?", "Que ideia de romantismo não combina nada contigo?",
  "O que gostarias de saber desde cedo sobre o dia a dia de um parceiro?", "Que tipo de humor te ajuda a seduzir?",
  "Quando sentes uma ligação especial numa conversa?", "De que precisas para manter a tua autonomia numa relação?",
  "Que pergunta revela mais do que a profissão quando conheces alguém?", "Como lidas com o facto de outra pessoa precisar de muito mais sossego?",
  "Que elogio te deixaria mesmo contente num encontro?", "O que consideras um bom sinal depois de uma divergência?",
  "Que experiência partilhada diz muito sobre a forma como se relacionam?", "Que importância têm passatempos semelhantes numa relação?",
  "O que tornaria uma carta de amor pessoal para ti?", "De que tipo de surpresa gostas numa relação?",
  "O que deve ser dito com regularidade numa relação?", "Como distingues um interesse respeitoso de um comportamento invasivo?",
  "Como organizarias um dia livre a dois sem ecrãs?", "Que pequeno gesto te pode acalmar os nervos num encontro?",
  "Qual é, para ti, a diferença entre estar apaixonado e sentir familiaridade?", "Que relação num filme te parece credível?",
  "Quanto planeamento em conjunto te faz sentir bem?", "O que seria um gesto atencioso numa relação à distância?",
  "Que tipo de conversa preferes ter enquanto passeias?", "Como gostarias que falassem contigo quando se nota que algo te preocupa?",
  "O que aprendeste de novo sobre as tuas próprias necessidades?", "Que qualidade faz de alguém um bom ouvinte num encontro?",
  "Como se pode mostrar carinho sem gastar dinheiro?", "Qual é uma forma saudável de ter interesses diferentes?",
  "Que decisão do casal não deve ser tomada por uma só pessoa?", "O que significa para ti ser de confiança, em concreto?",
  "Como se pode lidar de forma justa com diferentes níveis de energia?", "Que tipo de conversa nunca queres ter à pressa entre uma coisa e outra?",
  "O que pode um casal aprender com boas amizades?", "Que pequena tradição gostarias de experimentar a dois?",
  "Que importância tem para ti que as pessoas próximas conheçam bem o teu parceiro?", "Qual é uma forma cativante de mostrar interesse sem criar pressão ou expectativas?",
  "Que limite tens em relação a demonstrações de amor em público?", "Como perceberias que uma relação te faz bem?",
  "O que gostarias de fazer primeiro ao reencontrar alguém depois de uma longa separação?", "Que ideia tua sobre uma boa relação mudou?",
];
const liebeTasks = [
  "Planeia um primeiro encontro descontraído com um orçamento de zero euros.", "Formula um elogio sobre a atenção e não sobre a aparência.",
  "Representa como recusarias um convite de forma simpática e clara.", "Inventa uma carta de amor de uma chávena de chá para a sua base.",
  "Diz três pequenos gestos para mostrar carinho sem contacto físico.", "Descreve em duas frases uma forma respeitosa de propor outro encontro.",
  "Inventa o título de um filme romântico sobre duas pessoas numa fila.", "Formula uma frase para expressar um limite pessoal de forma clara e simpática.",
  "Apresenta uma ideia para um domingo a dois em que ambos tenham também tempo para si.", "Compõe mentalmente uma breve declaração de amor à tua comida preferida e recita-a.",
];
const erinnerungenQuestions = [
  "Que pequeno pormenor da tua infância ainda consegues descrever com precisão?", "Que caminho para a escola te ficou especialmente na memória?",
  "Qual foi o primeiro objeto que compraste e de que te orgulhaste?", "Que cozinha associas à sensação de aconchego e segurança?",
  "Que jogo conseguias jogar durante horas?", "Que dia de chuva foi inesperadamente bonito?",
  "Que pessoa adulta te levava a sério em criança?", "Que ritual de férias gostarias de recuperar?",
  "Qual foi o teu primeiro sucesso fora da escola de que tiveste consciência?", "Que lugar conheces hoje apenas através das recordações?",
  "Que história era contada muitas vezes na tua família?", "Qual foi a tua tentativa mais engraçada de parecer adulto?",
  "Que paixão de outros tempos poderia voltar a entusiasmar-te hoje?", "Que cena do teu bairro de outros tempos te ficou na memória?",
  "O que fazias melhor em criança do que agora?", "Que presente te apanhou completamente de surpresa naquela altura?",
  "Como era o teu refúgio preferido antigamente?", "Que primeiro encontro recordas com uma precisão invulgar?",
  "Qual foi um pequeno momento de coragem da tua juventude?", "Que passeio correu de forma diferente do planeado e mesmo assim foi bonito?",
  "Quem te ensinou uma habilidade prática?", "Que comida era especial antigamente e hoje é comum?",
  "Que fotografia gostarias de voltar a tirar?", "Que antigo hábito da tua família compreendes melhor hoje?",
  "O que subestimaste quando foste viver por tua conta?", "De que som de uma fase anterior da tua vida sentes falta?",
  "Que despedida acabou por se tornar um bom começo?", "Que aula recordas por um motivo surpreendente?",
  "Que objeto sobreviveu contigo a várias mudanças de casa?", "O que fizeste com o primeiro dinheiro que ganhaste?",
  "A que pessoa do teu passado gostarias de perguntar a sua versão de uma recordação?", "Qual foi a tua primeira grande ideia errada sobre o mundo dos adultos?",
  "De que festa de aniversário da tua infância ainda te lembras?", "O que colecionavas antigamente e porquê?",
  "Que filme foi, na altura, um verdadeiro acontecimento para ti?", "Quando conseguiste orientar-te pela primeira vez numa cidade nova?",
  "De que pequena tradição dos teus tempos de escola gostavas?", "De que elogio inesperado ainda te lembras?",
  "Que preparativo de viagem já fazia parte das férias para ti antigamente?", "O que contarias sobre amizade à tua versão mais nova?",
  "Que aroma te transporta mentalmente para uma estação específica?", "De que momento do dia a dia só mais tarde percebeste a importância?",
  "Que antiga peça de roupa preferida voltarias a usar hoje?", "Que mudança na tua terra natal te surpreende?",
  "Que recordação gostarias de guardar como uma pequena cena de um filme?", "De que ataque de riso em conjunto ainda te lembras hoje?",
  "O que te surpreendeu na primeira vez que viajaste a sós?", "Que decisão tomada cedo teve consequências inesperadamente grandes?",
  "Que carta ou bilhete antigo guardaste por um bom motivo?", "O que achas que te ficará especialmente na memória desta fase da tua vida?",
];
const erinnerungenTasks = [
  "Descreve o quarto da tua infância com três pormenores concretos.", "Explica as regras de um jogo de que gostavas em criança.",
  "Conta uma pequena recordação bonita como uma notícia de rádio em três frases.", "Diz três coisas dos teus tempos de escola que hoje quase desapareceram.",
  "Descreve uma comida de que gostavas sem dizer o nome; o grupo pode adivinhar.", "Dá um conselho simpático à tua versão mais nova numa única frase.",
  "Inventa um título adequado para o álbum de fotografias de uma fase bonita da tua vida.", "Mostra com as mãos o tamanho de um objeto que em criança te parecia enorme.",
  "Conta uma pequena prova de coragem do passado que hoje recordes com carinho.", "Descreve uma recordação apenas através dos sentidos: som, cheiro e cor.",
];
const reisenQuestions = [
  "O que vais ver primeiro num lugar novo?", "Que viagem foi mais bonita por ter ficado algo por planear?",
  "Qual é o teu sinal pessoal de que as férias começaram?", "Que lugar perto de ti nunca exploraste a sério?",
  "Que tipo de paisagem te acalma imediatamente?", "O que levas na bagagem mesmo que os outros achem desnecessário?",
  "Que conversa durante uma viagem te ficou especialmente na memória?", "Como decides se um destino combina contigo?",
  "O que farias num dia a sós numa cidade desconhecida?", "Que prato provado numa viagem gostarias de cozinhar em casa?",
  "O que faz de um lugar à janela no comboio um bom lugar para ti?", "Que hábito do dia a dia de outros lugares te impressionou?",
  "Para onde irias se o percurso tivesse de fazer parte da aventura?", "De que alojamento te lembras sobretudo pelas pessoas?",
  "Qual é a tua forma preferida de te orientares numa cidade?", "Que lembrança de viagem usas mesmo no dia a dia?",
  "Quanto tempo precisas para te sentires em casa num lugar novo?", "Que viagem gostarias de fazer a um ritmo muito lento?",
  "O que aprendeste ao viajar sobre as tuas próprias exigências?", "Que lugar parece muito diferente nas tuas recordações e nas fotografias?",
  "Que pequeno percalço de viagem já consegues encarar com calma?", "O que mostrarias a alguém que visitasse o teu país pela primeira vez?",
  "Que língua gostarias de saber para conversar com as pessoas locais?", "Que importância tem para ti poder mudar de planos numa viagem?",
  "O que é, para ti, o melhor de voltar a casa?", "Que mercado ou loja encontrado numa viagem te despertou mais curiosidade?",
  "Que percurso preferirias fazer a pé em vez de carro?", "O que deve saber sobre ti um bom companheiro de viagem?",
  "Que vista gostarias de apreciar sem máquina fotográfica?", "Como passarias uma tarde livre numa viagem com mau tempo?",
  "Que ideia de viagem tens adiado apenas por causa do planeamento?", "O que aprendes sobre um lugar ao visitar um supermercado?",
  "Que meio de transporte te dá mais a sensação de aventura?", "Que cidade estrangeira imaginarias como casa temporária?",
  "Qual é a tua melhor recordação de um passeio de um dia?", "Que tipo de museu te poderia levar a entrar de forma espontânea?",
  "Como encontras lugares para além das atrações óbvias quando viajas?", "Sobre o que escolherias não pesquisar antes de uma viagem?",
  "Que momento na natureza te surpreendeu durante uma viagem?", "Que viagem contrariou uma expectativa tua?",
  "Qual seria a tua paragem ideal num percurso longo?", "Em que difere o teu ritmo de férias do teu ritmo diário?",
  "Que lugar gostarias de voltar a ver noutra estação do ano?", "O que significa para ti tratar com respeito um lugar que não é o teu?",
  "Que encontro fugaz de uma viagem gostarias de prolongar?", "Que percurso seria bonito para um passeio com este grupo?",
  "Que habilidade te ajudou inesperadamente numa viagem?", "Que experiência parece pouco espetacular mas foi especial numa viagem?",
  "Como seria para ti um dia de viagem sem bilhetes de entrada?", "Que pergunta farias a alguém que vive lá desde sempre?",
];
const reisenTasks = [
  "Faz uma breve visita guiada à tua localidade sem mencionar atrações turísticas.", "Prepara mentalmente cinco objetos para um passeio espontâneo de um dia e justifica um deles.",
  "Descreve uma paisagem como num postal, em exatamente três frases.", "Planeia um dia de chuva num lugar desconhecido sem pagar entradas.",
  "Inventa um aviso simpático para viajantes numa aldeia imaginária.", "Apresenta uma linha de comboio dos teus sonhos com três paragens muito diferentes.",
  "Mostra sem palavras como perguntarias o caminho para um café.", "Recomenda ao grupo uma pequena aventura que possa estar a uma hora de distância.",
  "Descreve um alojamento invulgar onde passarias uma noite.", "Inventa um slogan turístico para um lugar discreto, como um parque de estacionamento ou um patamar.",
];
const traeumeQuestions = [
  "Que pequena ideia para o futuro te deixa com vontade de lá chegar?", "O que gostarias de aprender mesmo sem nunca te tornares especialmente bom nisso?",
  "Como gostarias de te sentir num dia normal daqui a cinco anos?", "Que projeto te interessaria mesmo sem reconhecimento?",
  "Que tipo de lar gostarias de criar a longo prazo?", "O que farias com uma tarde livre por semana?",
  "Que hábito gostarias de oferecer à tua versão futura?", "Que desejo se tornou mais importante para ti à medida que foste crescendo?",
  "O que gostarias de viver pela primeira vez?", "Que habilidade poderia facilitar bastante o teu dia a dia?",
  "O que gostarias de fazer pelas tuas mãos em vez de comprar?", "Que pessoas gostarias de ter mais vezes por perto no futuro?",
  "Que projeto precisa mais de coragem do que de dinheiro?", "Como organizarias um ano em que ninguém avaliasse o teu currículo?",
  "O que gostarias de ensinar um dia a alguém mais novo?", "O que pode continuar tranquilamente como está na tua vida?",
  "Que projeto em conjunto gostarias de planear com amigos?", "O que experimentarias se falhar não tivesse consequências?",
  "Que tipo de trabalho poderia continuar a dar-te alegria no futuro?", "O que gostarias de poder dizer sobre ti um dia?",
  "Que ideia antiga tua merece uma segunda tentativa?", "Como seria o teu lugar ideal para uma pausa criativa?",
  "Que desejo quase nunca disseste em voz alta até agora?", "Qual seria um primeiro passo realista em direção a um grande objetivo?",
  "Que tradição gostarias de iniciar entre as pessoas próximas de ti?", "O que gostarias de ter em menor quantidade para te sentires mais livre?",
  "Que experiência valeria para ti mais do que um objeto caro?", "Como gostarias de celebrar um grande sucesso pessoal?",
  "Que tipo de aventura combina com a pessoa que és hoje?", "O que gostarias de ajudar a criar ou melhorar na tua zona?",
  "Que desejo de infância ainda hoje te daria alegria?", "Como perceberias que já alcançaste o suficiente?",
  "O que gostarias de fazer de forma diferente no próximo inverno?", "Que nova ligação entre os teus interesses gostarias de descobrir?",
  "Do que gostarias de te orgulhar no futuro, mesmo que ninguém o veja?", "Que espaço livre gostarias de proteger na tua agenda?",
  "O que gostarias de mostrar um dia a um pequeno público?", "Que tipo de comunidade gostarias de criar ou encontrar?",
  "Qual poderia ser um bom lema para o teu próximo ano de vida?", "Que objetivo seguirias sem te comparares com os outros?",
  "O que escolherias levar ou deixar para trás na tua próxima mudança de casa?", "Que mudança gradual gostarias de iniciar?",
  "A quem gostarias de retribuir um dia algo que recebeste?", "Que motivo faria valer a pena voltares a ser principiante?",
  "Que recordação ainda gostarias de criar com a tua família?", "O que farias com uma pequena divisão vazia?",
  "Que qualidade gostarias de conservar ao envelhecer?", "O que gostarias de celebrar mais vezes no próximo ano?",
  "Que sonho poderias concretizar em breve numa versão mais pequena?", "Que pergunta em aberto sobre o teu futuro achas interessante neste momento?",
];
const traeumeTasks = [
  "Descreve um desejo e um primeiro passo que demore menos de dez minutos.", "Faz um breve discurso de agradecimento à tua versão futura por um bom hábito novo.",
  "Inventa o título de um curso que frequentarias por pura curiosidade.", "Pinta por palavras uma manhã normal do teu dia a dia ideal.",
  "Diz três coisas que gostarias de aprender sem teres de as dominar.", "Formula um lema simpático para o teu próximo mês.",
  "Apresenta um projeto futuro em conjunto que este grupo possa iniciar num fim de semana.", "Explica um desejo de infância como se o estivesses a descobrir hoje.",
  "Inventa uma pequena celebração para um sucesso de que mais ninguém daria conta.", "Descreve uma cápsula do tempo com três coisas que representem bem quem és hoje.",
];
const entscheidungenQuestions = [
  "Em que decisão te ajuda mesmo dormir sobre o assunto?", "O que se tornou mais importante para ti do que uma boa primeira impressão?",
  "Quando abdicarias da comodidade em nome da justiça?", "Que decisão preferes tomar por intuição em vez de seguir uma lista?",
  "O que significa sucesso para ti para além do dinheiro e do trabalho?", "Que limite ao teu tempo gostarias de proteger melhor?",
  "Sobre o que mudaste de opinião depois de ouvires um bom argumento?", "O que torna uma promessa um compromisso para ti?",
  "Como percebes que um compromisso vai longe demais para ti?", "Que pequena decisão influencia o teu estado de espírito mais do que esperavas?",
  "Quando é especialmente importante ser sincero sem acrescentar explicações?", "O que preferirias reparar mesmo que comprar novo fosse mais fácil?",
  "Que tipo de risco corres com gosto?", "Como escolhes entre duas opções igualmente boas?",
  "O que torna alguém credível aos teus olhos?", "Para que gostarias de ter mais paciência no dia a dia?",
  "Quando é que dizer não pode ser uma decisão simpática?", "Que convicção tua gostarias de analisar melhor?",
  "O que valorizas mais num pedido de desculpa: as palavras ou o comportamento?", "De quanta incerteza precisas para que a vida continue interessante?",
  "Que hábito cómodo não combina totalmente com os teus valores?", "Quando renunciaste a dinheiro para ganhar tempo?",
  "O que se deve partilhar mesmo que pertença só a nós?", "Que decisão não tomarias através de uma votação em grupo?",
  "Como reconheces um conselho que realmente se adequa a ti?", "O que distingue, para ti, a generosidade da vontade de agradar?",
  "Que pequena coisa merece mais valorização do que recebe?", "Quando é mais sensato largar um projeto já iniciado?",
  "O que gostarias de decidir de forma mais consciente no teu consumo?", "Que qualidade valorizas mais do que capacidades impressionantes?",
  "Como lidas com uma decisão que só mais tarde se revela errada?", "O que protegerias primeiro com um orçamento limitado?",
  "Quando deve uma regra permitir uma exceção justificada?", "O que significa responsabilidade numa casa partilhada?",
  "Que opinião defendes mesmo sem a concordância dos teus amigos?", "O que te ajuda a não adiar uma decisão indefinidamente?",
  "Quando vale mais uma conversa difícil do que manter a harmonia?", "Que decisão te deu liberdade?",
  "O que deve alguém saber antes de julgar o sucesso dos outros?", "Quanto planeamento te dá segurança e a partir de quando se torna controlo?",
  "O que torna uma divisão de tarefas justa?", "Que tipo de competição achas enriquecedora?",
  "Em que não tomarias atalhos mesmo num dia cansativo?", "Quando é útil corrigir publicamente a tua própria opinião?",
  "Que oportunidade preferirias recusar para te manteres fiel a ti próprio?", "Como distingues uma necessidade real de um desejo passageiro?",
  "O que pode surpreender os outros no teu estilo de vida?", "Que decisão tomarias hoje com mais calma do que antigamente?",
  "Como percebes que precisas de uma pausa em vez de uma nova solução?", "Que ação do dia a dia exprime melhor os teus valores?",
];
const entscheidungenTasks = [
  "Defende em duas frases uma pausa como uma decisão inteligente.", "Propõe uma divisão justa de três tarefas domésticas desagradáveis entre três pessoas.",
  "Diz uma boa razão para planear e outra igualmente boa para a espontaneidade.", "Pratica uma recusa educada a um convite sem inventar desculpas.",
  "Explica a uma criança imaginária o que significa ser justo com um exemplo do dia a dia.", "Diz uma pequena decisão de compra e uma possível alternativa mais sustentável.",
  "Formula uma frase com que poderias mudar de opinião após um bom argumento.", "Apresenta duas soluções justas quando um grupo não se consegue decidir por um restaurante.",
  "Descreve uma regra pessoal que te facilita o dia a dia e uma exceção permitida.", "Inventa uma pequena mensagem publicitária para a paciência em vez de para um produto.",
];
const kreativQuestions = [
  "Que sala secreta acrescentarias a uma biblioteca?", "Como seria um feriado que pudesses inventar?",
  "Que duas profissões normais dariam uma nova profissão fantástica se fossem combinadas?", "O que exporia um museu sobre o teu dia a dia atual?",
  "Que superpoder só seria útil nas tarefas domésticas?", "Como seria uma cidade construída para pessoas noturnas?",
  "A que objeto darias voz durante um dia?", "Qual seria uma boa cena de abertura para um filme sobre este grupo?",
  "Que novo desporto se poderia inventar sem equipamento?", "Como seria um restaurante com a ementa organizada por estados de espírito?",
  "O que deixarias numa cápsula do tempo para as pessoas de daqui a cem anos?", "Que cor teria um som de que gostas?",
  "Como transformarias uma sala de espera aborrecida num lugar preferido?", "Que capacidade animal seria surpreendentemente prática num escritório?",
  "Qual seria o principal problema de um mundo onde todos os pensamentos aparecem como legendas?", "Que acontecimento do dia a dia merece a sua própria banda sonora?",
  "Como seria uma versão simpática de um monstro clássico do cinema?", "Que invenção adoraria imediatamente uma pessoa da Idade Média?",
  "O que poderia contar uma nuvem no seu diário?", "Como criarias um parque de diversões sem atrações mecânicas?",
  "Que animal imaginário seria um bom companheiro de viagem de comboio?", "Qual seria um sexto sentido útil no dia a dia?",
  "Como seria uma história policial em que ninguém consegue mentir?", "Que moeda invulgar funcionaria numa ilha de cozinheiros?",
  "O que colocarias numa praça completamente vazia?", "Como seria uma casa de sonho se cada divisão fosse uma estação do ano?",
  "Que coisa inofensiva seria um grande tesouro no teu mundo inventado?", "Qual seria um bom nome para a nave espacial deste grupo?",
  "Como explicarias a um robô o que significa aconchego?", "Que personagem de conto de fadas precisaria hoje de mudar urgentemente de profissão?",
  "O que faria um elevador se tivesse um dia livre só para si?", "Como seria uma escola onde a curiosidade fosse a única disciplina?",
  "Que três regras teria um jogo que só se joga na cabeça?", "Qual seria a mensagem mais invulgar mas sensata numa bolacha da sorte?",
  "Como mudaria uma cidade se os telhados se tornassem jardins?", "Que palavra nova falta para um sentimento que conheces?",
  "O que deduziria um detetive sobre ti a partir do teu pequeno-almoço?", "Como seria uma exposição feita apenas de cheiros?",
  "De que tarefa se encarregaria em tua casa um dragão minúsculo e simpático?", "Como seria um manual de instruções engraçado para um domingo?",
  "Como planearias uma viagem em que uma moeda decide todas as direções?", "Que milagre seria espetacular mas totalmente imprático no dia a dia?",
  "O que poderia contar um livro que escolhe o seu próprio leitor?", "Como funcionaria uma loja que vende recordações em vez de objetos?",
  "Que nova modalidade combinaria com uns Jogos Olímpicos da paciência?", "Qual seria o primeiro anúncio numa cidade debaixo de água?",
  "Como chamarias a um jogo de tabuleiro sobre a tua profissão ou o teu dia a dia?", "Que mensagem te escreveria o teu futuro animal de estimação?",
  "Qual seria uma bonita missão para uma magia muito pequena?", "Como poderiam ser os créditos finais desta noite?",
];
const kreativTasks = [
  "Inventa em três frases uma história em que apareçam uma chave, uma nuvem e uma padaria.", "Dá a um objeto da sala um superpoder e uma fraqueza disparatada.",
  "Inventa uma palavra nova para a alegria de ver cancelados planos cansativos.", "Descreve um monstro simpático e a sua atividade preferida.",
  "Inventa duas frases de um anúncio para um guarda-chuva invisível.", "Representa uma conversa entre o sol e a lua com duas vozes diferentes.",
  "Imagina um novo feriado com nome e uma tradição simples.", "Inventa um título de livro e a primeira frase de uma história sobre esta garrafa.",
  "Descreve uma sala onde a gravidade só não se aplica aos móveis.", "Inventa um pequeno feitiço que resolva exatamente um problema inofensivo do dia a dia.",
];
export const QUESTIONS = {
  eisbrecher: eisbrecherQuestions,
  spass: spassQuestions,
  party: partyQuestions,
  freundschaft: freundschaftQuestions,
  liebe: liebeQuestions,
  erinnerungen: erinnerungenQuestions,
  reisen: reisenQuestions,
  traeume: traeumeQuestions,
  entscheidungen: entscheidungenQuestions,
  kreativ: kreativQuestions,
};
export const TASKS = {
  eisbrecher: eisbrecherTasks,
  spass: spassTasks,
  party: partyTasks,
  freundschaft: freundschaftTasks,
  liebe: liebeTasks,
  erinnerungen: erinnerungenTasks,
  reisen: reisenTasks,
  traeume: traeumeTasks,
  entscheidungen: entscheidungenTasks,
  kreativ: kreativTasks,
};
