// Individually translated canonical cards.
const eisbrecherQuestions = [
  "¿Qué pequeño lujo te mejora un día cualquiera?", "¿Qué crees que notan primero las visitas en tu casa?",
  "¿Sobre qué tema se te pasa el tiempo volando cuando hablas?", "¿Qué habilidad ofrecerías enseguida a alguien que acaba de compartir piso contigo?",
  "¿Cómo sería tu mañana libre ideal?", "¿Qué pides para comer cuando no consigues decidirte?",
  "¿Cómo se nota que te sientes a gusto en un grupo?", "¿Qué actividad consigue tranquilizarte con una eficacia sorprendente?",
  "¿Qué sueles tener a mano junto a la cama?", "¿Qué cosa poco llamativa se te da sorprendentemente bien?",
  "¿Qué olor te recuerda al instante un lugar bonito?", "¿Cómo describirías tu humor a alguien que no te conoce?",
  "¿Qué parte de tu rutina dejarías encantado en manos de un robot?", "¿Cuál es tu lugar favorito para observar a la gente?",
  "¿Qué aplicación instalarías primero en un móvil nuevo?", "¿Con qué bebida empieza para ti una noche tranquila?",
  "¿Qué estación del año encaja mejor con tu temperamento?", "¿Qué coleccionas sin haberlo decidido nunca de forma consciente?",
  "¿Qué cumplido te gusta especialmente recibir?", "¿Cuánta planificación necesitas para pasar un buen domingo?",
  "¿Qué tontería inofensiva te entusiasma de forma desproporcionada?", "¿Qué juego de mesa o de cartas despierta tu competitividad?",
  "¿Qué le enseñarías primero a alguien que visita tu zona?", "¿Qué pregunta te hacen demasiado pocas veces?",
  "¿Cómo eliges lo próximo que vas a leer o ver?", "¿Qué revela sobre tu día a día el bolso o la mochila que llevas ahora?",
  "¿Qué tipo de tiempo te gusta más que a la mayoría de la gente?", "¿Qué animal representa tu energía un lunes por la mañana?",
  "¿Qué prefieres comprar de segunda mano en vez de nuevo?", "¿Qué tiene que tener una buena cafetería para ti?",
  "¿Qué tarea de casa haces realmente con gusto?", "¿Cómo decides si aceptas una invitación?",
  "¿Qué pequeña sorpresa sería perfecta para ti?", "¿De qué prenda te costaría desprenderte?",
  "¿Qué sonido te hace sentir que estás en casa?", "¿Qué quieres entender primero de alguien a quien acabas de conocer?",
  "¿Qué plato te sale bien incluso sin receta?", "¿En qué momento del día te notas más despierto?",
  "¿Qué no puede faltar en un pícnic para ti?", "¿Qué objeto que tienes cerca guarda una historia?",
  "¿Cómo aprovechas diez minutos libres inesperados?", "¿Cuál fue tu última ocurrencia espontánea realmente buena?",
  "¿Qué tipo de tienda te cuesta pasar de largo sin mirar?", "¿Qué hace que te apetezca seguir una conversación?",
  "¿Qué costumbre has adoptado de otra persona?", "¿De qué te encargarías en una noche de cocinar en grupo?",
  "¿Qué palabra crees que usas más que los demás?", "¿Qué es para ti una muestra de buena hospitalidad?",
  "¿Qué pregunta te gustaría hacerle a este grupo?", "¿Qué hay que saber de ti para organizar una excursión contigo?",
];
const eisbrecherTasks = [
  "Preséntate en tres frases sin decir tu nombre, tu profesión ni dónde vives.", "Describe tu desayuno perfecto como si recomendaras brevemente un restaurante.",
  "Explícale al grupo una pequeña habilidad que usas a menudo en tu día a día.", "Di tres cosas que hoy hayan ido mejor de lo esperado.",
  "Hazle al grupo una pregunta poco habitual para conoceros y responde tú primero.", "Describe un lugar que te encante para que los demás puedan imaginarlo sin decir su nombre.",
  "Inventa un saludo amable que pegue con esta noche.", "Haz una breve visita guiada por un objeto que tengas cerca.",
  "Resume lo que llevas de día en exactamente seis palabras.", "Propón una actividad en común que recomendarías a este grupo para una tarde libre.",
];
const spassQuestions = [
  "¿Qué cosa totalmente irrelevante defiendes con una pasión sorprendente?", "¿Cuál es el lapsus más gracioso que recuerdas haber tenido?",
  "¿Qué regla inofensiva has inventado solo para ti?", "¿Qué actividad comentas a veces como si fueras comentarista deportivo?",
  "¿Qué personaje de película sería un compañero de piso desastroso para ti?", "¿En qué sueles sobrevalorar tu talento?",
  "¿Qué sonido sabes imitar de forma sorprendentemente convincente?", "¿Qué miedo absurdo tenías de pequeño?",
  "¿Cuál sería el eslogan publicitario menos apropiado para tu día a día?", "¿Qué cosa pequeña extravías siempre en el mismo sitio absurdo?",
  "¿Qué plato te sale más rico de lo que parece?", "¿Cuándo te reíste por última vez de un error tuyo?",
  "¿Qué expresión estuviste mucho tiempo entendiendo mal?", "¿Qué escribirías en un trofeo por tu peor defecto?",
  "¿Qué combinación rara de comida te gusta de verdad?", "¿Qué objeto cotidiano sería el más difícil de tener como mascota?",
  "¿Qué situación te hace reír incluso cuando quieres mantener la seriedad?", "¿Qué solución innecesariamente complicada diste a un problema sencillo?",
  "¿Qué ley imaginaria prohibiría tu costumbre más molesta?", "¿Qué inconveniente diminuto te hace ponerte dramático por dentro?",
  "¿Cómo se titularía una comedia de situación sobre tu último mes?", "¿Qué época en la que te creías muy guay te resulta especialmente cómica ahora?",
  "¿Cuál es la excusa más extraña que te has creído tú mismo?", "¿En qué percance tecnológico te sorprendiste más a ti mismo?",
  "¿Qué talento completamente inútil pondrías en una solicitud de empleo?", "¿A qué mueble te imaginas de mal humor?",
  "¿Qué cosa pequeña haces con una ceremonia exageradísima?", "¿Cuál sería tu nombre artístico inusual en un espectáculo de magia?",
  "¿Qué mentira inofensiva sobre el día a día sería fácil de descubrir?", "¿Cuál fue tu confusión más cómica al hacer la compra?",
  "¿Qué comida debería llevar un manual de instrucciones, en tu opinión?", "¿Qué papel te tocaría en la tripulación caótica de una nave espacial?",
  "¿Cómo suena tu voz interior cuando tienes que montar algo?", "¿Qué te hace gracia aunque apenas sepas explicar el chiste?",
  "¿Cuál sería el motivo más ridículo para una disputa feroz entre vecinos?", "¿Qué movimiento cotidiano te sale elegante sin querer?",
  "¿Qué palabra no te suena en absoluto a lo que significa?", "¿Qué contaría tu nevera sobre ti?",
  "¿Qué deporte sería más cómico con material de oficina?", "¿Cuál fue tu momento más gracioso con el autocorrector?",
  "¿Qué objeto tuyo merece tener nombre propio?", "¿Cómo contarías una compra aburrida como si fuera una película de acción?",
  "¿Qué debate ridículo podría entretenerte aun así durante veinte minutos?", "¿Cuál sería un título sorprendentemente sincero para tu libro de cocina?",
  "¿Qué costumbre tuya podría malinterpretar un extraterrestre?", "¿Qué animal distraería más como presentador de informativos?",
  "¿Qué mala compra te dejó al menos una buena historia que contar?", "¿Qué costumbre reconocerías al instante en un doble tuyo?",
  "¿Qué frase normal podría decirse como una advertencia dramática de película?", "¿Cuál fue la suposición equivocada más divertida que alguien hizo sobre ti?",
];
const spassTasks = [
  "Da un breve y solemne discurso de agradecimiento por un calcetín perdido.", "Vende una cuchara invisible con un eslogan publicitario totalmente exagerado.",
  "Comenta durante diez segundos el hecho de estar sentado como si fuera una final deportiva emocionante.", "Di «La sopa está lista» como un anuncio cinematográfico dramático.",
  "Explica con voz seria por qué los cojines merecen vacaciones.", "Representa un diálogo breve entre un despertador y una persona cansada.",
  "Haz tres expresiones diferentes al encontrarte la nevera vacía por sorpresa.", "Inventa un nombre absurdamente complicado para la palabra «silla».",
  "Da una previsión del tiempo para tu estado de ánimo actual con un giro absurdo.", "Explica en dos frases por qué un plátano debería ser alcalde.",
];
const partyQuestions = [
  "¿Qué canción te hace moverte incluso después de un día largo?", "¿Qué distingue una buena fiesta de una fiesta que solo hace ruido?",
  "¿Qué concierto te gustaría volver a vivir como si fuera la primera vez?", "¿Qué papel asumes automáticamente en las fiestas?",
  "¿Qué temática te animaría de verdad a ir a una fiesta de disfraces?", "¿Qué canción relacionas con una amistad concreta?",
  "¿Cómo terminaría para ti una noche larga de forma perfecta?", "¿Qué pequeño detalle hace inolvidable a quien organiza una fiesta?",
  "¿De qué canción solo sabes el estribillo y aun así la cantas?", "¿Cuál fue la mejor conversación lejos de la pista de baile?",
  "¿Qué instrumento te gustaría tocar en una banda?", "¿Qué fiesta te sorprendió para bien aunque no te apetecía ir?",
  "¿Qué tiene que haber en un bufé para que te quedes a gusto?", "¿Qué género musical aprendiste a apreciar bastante tarde?",
  "¿Cómo harías que la gente nueva empezara a hablar entre sí en una fiesta?", "¿Qué artista elegirías para un concierto diminuto en el salón?",
  "¿Cuál es tu recuerdo más agradable de un festival?", "¿Qué canción debería sonar en tus créditos finales personales?",
  "¿Qué tradición de las fiestas eliminarías sin problema?", "¿Qué valoras más en una fiesta: las caras conocidas o conocer gente nueva?",
  "¿Qué recomendación musical de tu entorno acertó de lleno contigo?", "¿Cómo harías especial un cumpleaños con muy poco dinero?",
  "¿Qué movimiento de baile siempre te parece el adecuado?", "¿De qué trataría tu propio programa de radio?",
  "¿Qué celebración preferirías organizar al aire libre en vez de dentro?", "¿Qué canción te recuerda a un viaje largo?",
  "¿Cuál fue la invitación más creativa que recibiste?", "¿Qué tres cosas necesitan los invitados para sentirse a gusto enseguida?",
  "¿Qué canción le pondrías a alguien para que entienda tu estado de ánimo?", "¿Qué hace que una noche de juegos en grupo salga bien para ti?",
  "¿Qué opinión musical compartes con casi nadie?", "¿Qué comida poco habitual encajaría en una pausa a medianoche?",
  "¿Cómo te das cuenta de que es hora de irte a casa?", "¿Qué preferirías hacer tú en una fiesta en vez de dejar que lo organicen otros?",
  "¿Qué letra de canción se te ha quedado especialmente grabada?", "¿Qué sorpresa de cumpleaños podría agobiarte?",
  "¿Qué sonido de una grabación en directo te encanta?", "¿Qué fiesta no necesita ningún motivo para ti?",
  "¿Cuánto debería durar tu lista de reproducción compartida ideal?", "¿Qué música te acompaña al recoger después de recibir visitas?",
  "¿Qué momento bonito recuerdas de una boda, aparte de la ceremonia?", "¿Qué lugar sería poco habitual pero acogedor para una fiesta pequeña?",
  "¿Cómo harías interesante una fiesta sin altavoces?", "¿Qué álbum prefieres escuchar entero en vez de canciones sueltas?",
  "¿Cuál es la mejor forma de iniciar una conversación en una mesa de desconocidos?", "¿Qué descubrimiento musical te gustaría compartir con el grupo?",
  "¿Cómo sería una fiesta que encajara exactamente con tu nivel de energía?", "¿Qué recuerdo relacionas con un baile concreto?",
  "¿Qué quieres hacer de forma distinta a propósito en tu próxima fiesta?", "¿Qué título tendría la lista de reproducción de esta noche?",
];
const partyTasks = [
  "Tararea una breve sintonía inventada por ti para esta noche.", "Presenta la siguiente ronda como si fuera un pequeño programa de radio.",
  "Inventa una bebida sin alcohol con nombre y tres ingredientes.", "Sentado, muestra un movimiento de baile sencillo usando solo hombros y manos.",
  "Prepara una minilista: una canción para la llegada, otra para el momento álgido y otra para la vuelta a casa.", "Marca un ritmo breve sobre tus propios muslos y repítelo.",
  "Inventa una invitación a una fiesta con una temática inusual pero acogedora.", "Da una bienvenida cariñosa a alguien que no conoce a nadie aquí.",
  "Describe un festival inventado con un solo escenario y un extra especial.", "Dedica un brindis breve a algo cotidiano, sin invitar a nadie a beber.",
];
const freundschaftQuestions = [
  "¿Cómo te diste cuenta de que un conocido se había convertido en amigo?", "¿Qué pequeño gesto de tus amigos significa mucho para ti?",
  "¿Qué puedes hacer con amigos sin necesidad de hablar mucho?", "¿Cómo mantienes el contacto con quienes viven lejos?",
  "¿Qué cualidad de tus amigos te ha cambiado a ti?", "¿Cuál es una buena forma de retomar el contacto después de mucho tiempo?",
  "¿Qué contratiempo compartido os unió más?", "¿Cómo demuestras que escuchas de verdad a un amigo?",
  "¿Qué probarías con un amigo pero no a solas?", "¿Qué tradición nunca debería convertirse en una obligación entre amigos?",
  "¿Cuándo sentiste especial orgullo por alguien de tu grupo de amigos?", "¿Cuánta espontaneidad admiten tus planes con amigos?",
  "¿Qué aprecias de los amigos que son muy distintos a ti?", "¿Qué tipo de apoyo te resulta fácil ofrecer?",
  "¿Cómo pueden llevarte la contraria con sinceridad sin que te cierres?", "¿Qué excursión compartida recuerdas con especial viveza?",
  "¿Qué hace que una disculpa entre amigos sea buena para ti?", "¿Qué tipo de mensaje te alegra un día normal?",
  "¿Para qué pedirías consejo a un amigo en lugar de buscar en internet?", "¿Qué límite en una amistad se ha vuelto importante para ti?",
  "¿Qué actividad compartida consigue unir a personas distintas?", "¿Cómo notas que alguien necesita compañía en vez de consejos?",
  "¿Cuál fue el regalo más considerado que recibiste de tus amigos?", "¿Qué amistad nació en un lugar inesperado?",
  "¿Cómo cambia tu forma de hablar con tus amigos más cercanos?", "¿Qué no debería tomarse como algo personal quien sea amigo tuyo?",
  "¿Qué cualidad hace que alguien sea un buen compañero de viaje?", "¿Qué propondrías para pasar juntos una hora libre?",
  "¿Qué recuerdo te gustaría contrastar con un viejo amigo?", "¿Cómo celebras los pequeños éxitos de tus amigos?",
  "¿Qué te ayuda a recuperar la cercanía después de un desacuerdo?", "¿Qué proyecto en común podría enriquecer vuestra amistad?",
  "¿Qué te han enseñado tus amigos sobre ti?", "¿Qué tipo de ayuda te cuesta aceptar?",
  "¿Qué importancia tiene para ti la puntualidad en una amistad?", "¿Qué broma interna inofensiva puedes explicarle al grupo?",
  "¿Qué reconocerías enseguida en un amigo incluso después de muchos años?", "¿Cuándo te resulta agradable compartir el silencio?",
  "¿Qué hace que una persona nueva se sienta bienvenida en un grupo ya formado?", "¿Qué amistad te gustaría cuidar más en el día a día?",
  "¿Qué diferencia hay para ti entre la lealtad y dar la razón a ciegas?", "¿Qué plan funciona mejor con amigos que con la familia?",
  "¿Cómo animarías a un amigo después de un día decepcionante?", "¿Qué costumbre compartida echas de menos a veces?",
  "¿Cómo se nota que necesitas tiempo para ti?", "¿Qué coincidencia inesperada te acercó a alguien?",
  "¿Qué es una buena ocasión para darle las gracias sin más a un amigo?", "¿Cómo llevas que unas amistades sean más cercanas que otras?",
  "¿Qué habilidad de un amigo admiras en secreto o abiertamente?", "¿Qué te gustaría hacer de forma más consciente como amigo a partir de ahora?",
];
const freundschaftTasks = [
  "Haz un cumplido sincero sobre una cualidad que aprecias en este grupo.", "Explica en dos frases cómo animarías a un amigo después de un día desastroso.",
  "Planea una excursión en grupo que no cueste nada y no excluya a nadie.", "Inventa un pequeño ritual para que los amigos mantengan el contacto a pesar de la distancia.",
  "Di tres formas de ofrecer ayuda sin imponerte.", "Formula un mensaje amable para retomar el contacto después de mucho tiempo; no envíes nada.",
  "Representa una disculpa breve y sincera por haber faltado a una cita.", "Busca una imagen o una comparación que represente una buena amistad.",
  "Di una habilidad práctica que podrías enseñar al grupo voluntariamente.", "Describe una pequeña tradición compartida que encajaría con este grupo.",
];
const liebeQuestions = [
  "¿Qué forma de atención te hace sentir que de verdad te ven?", "¿Qué hace que una primera cita sea relajada para ti?",
  "¿Qué pequeña escena cotidiana te parece romántica?", "¿Cómo sabes que puedes confiar en alguien?",
  "¿Qué preferirías contar en persona y no por chat al conocer a alguien?", "¿Qué cualidad te resulta más atractiva con el tiempo?",
  "¿Qué significa para ti la cercanía más allá del contacto físico?", "¿Cómo debería reaccionar alguien cuando expresas un límite?",
  "¿Qué costumbre compartida podría enriquecer una relación?", "¿Qué cita bonita se podría hacer sin gastar casi nada?",
  "¿Cómo muestras cariño cuando te faltan las palabras adecuadas?", "¿Qué idea del romanticismo no encaja nada contigo?",
  "¿Qué te gustaría saber pronto sobre el día a día de tu pareja?", "¿Qué tipo de humor te ayuda a coquetear?",
  "¿Cuándo sientes una conexión especial en una conversación?", "¿Qué necesitas para mantener tu independencia en una relación?",
  "¿Qué pregunta revela más que la profesión al conocer a alguien?", "¿Cómo llevas que otra persona necesite mucha más tranquilidad?",
  "¿Qué cumplido te alegraría de verdad en una cita?", "¿Qué consideras una buena señal después de un desacuerdo?",
  "¿Qué experiencia compartida dice mucho sobre cómo os relacionáis?", "¿Qué importancia tienen las aficiones parecidas en una relación?",
  "¿Qué haría que una carta de amor fuera personal para ti?", "¿Qué tipo de sorpresa te gusta en una relación?",
  "¿Qué debería decirse con frecuencia en una relación?", "¿Cómo distingues el interés respetuoso de un comportamiento agobiante?",
  "¿Cómo organizarías un día libre juntos sin pantallas?", "¿Qué pequeño detalle puede quitarte los nervios en una cita?",
  "¿Qué diferencia hay para ti entre enamoramiento y confianza cotidiana?", "¿Qué relación de una película te resulta creíble?",
  "¿Cuánta planificación conjunta te hace sentir a gusto?", "¿Qué sería un gesto atento en una relación a distancia?",
  "¿Qué tipo de conversación prefieres tener mientras paseas?", "¿Cómo te gustaría que se dirigieran a ti cuando se nota que algo te preocupa?",
  "¿Qué has aprendido sobre tus propias necesidades?", "¿Qué cualidad hace que alguien escuche bien en una cita?",
  "¿Cómo se puede mostrar cariño sin gastar dinero?", "¿Cómo se pueden tener intereses distintos de forma sana?",
  "¿Qué decisión de pareja no debería tomar nadie por su cuenta?", "¿Qué significa para ti ser fiable, en concreto?",
  "¿Cómo se pueden respetar de forma justa distintos niveles de energía?", "¿Qué conversación no querrías tener nunca deprisa y de pasada?",
  "¿Qué puede aprender una pareja de las buenas amistades?", "¿Qué pequeña tradición te gustaría probar en pareja?",
  "¿Qué importancia tiene para ti que tu entorno conozca bien a tu pareja?", "¿Cuál es una forma bonita de mostrar interés sin presionar ni crear expectativas?",
  "¿Qué límite tienes con las muestras de amor en público?", "¿Cómo notarías que una relación te hace bien?",
  "¿Qué te gustaría hacer primero al reencontrarte con alguien después de una larga separación?", "¿Qué idea tuya sobre una buena relación ha cambiado?",
];
const liebeTasks = [
  "Planea una primera cita relajada con un presupuesto de cero euros.", "Formula un cumplido sobre la atención y no sobre el aspecto físico.",
  "Representa cómo rechazarías una invitación de forma amable y clara.", "Inventa una carta de amor de una taza de té a su posavasos.",
  "Di tres pequeños gestos para mostrar cariño sin contacto físico.", "Describe en dos frases una forma respetuosa de proponer otro encuentro.",
  "Inventa el título de una película romántica sobre dos personas en una cola.", "Formula una frase para expresar un límite personal de forma clara y amable.",
  "Propón un plan de domingo juntos en el que ambos tengáis también tiempo propio.", "Compón mentalmente una breve declaración de amor a tu comida favorita y recítala.",
];
const erinnerungenQuestions = [
  "¿Qué pequeño detalle de tu infancia todavía puedes describir con precisión?", "¿Qué camino al colegio recuerdas especialmente?",
  "¿Cuál fue el primer objeto que compraste tú y del que te sentiste orgulloso?", "¿Qué cocina relacionas con la sensación de sentirte arropado?",
  "¿A qué juego podías pasarte horas jugando antes?", "¿Qué día de lluvia resultó inesperadamente bonito?",
  "¿Qué persona adulta te tomaba en serio de pequeño?", "¿Qué ritual de vacaciones te gustaría recuperar?",
  "¿Cuál fue tu primer éxito fuera del colegio del que fuiste consciente?", "¿Qué lugar conoces hoy solo a través de tus recuerdos?",
  "¿Qué historia se contaba a menudo en tu familia?", "¿Cuál fue tu intento más gracioso de parecer mayor?",
  "¿Qué entusiasmo de antes podría volver a atraparte hoy?", "¿Qué escena de tu vecindario de hace años se te quedó grabada?",
  "¿Qué se te daba mejor de pequeño que ahora?", "¿Qué regalo te sorprendió totalmente en aquella época?",
  "¿Cómo era antes tu refugio favorito?", "¿Qué primer encuentro recuerdas con una precisión poco habitual?",
  "¿Cuál fue un pequeño momento de valentía de tu juventud?", "¿Qué excursión salió distinta a lo planeado y aun así fue bonita?",
  "¿Qué persona te enseñó una habilidad práctica?", "¿Qué comida era especial antes y hoy es algo cotidiano?",
  "¿Qué foto te gustaría volver a hacer?", "¿Qué antigua costumbre de tu familia entiendes mejor ahora?",
  "¿Qué subestimaste al empezar a vivir por tu cuenta?", "¿Qué sonido echas de menos de una etapa anterior de tu vida?",
  "¿Qué despedida acabó convirtiéndose en un buen comienzo?", "¿Qué clase del colegio recuerdas por un motivo sorprendente?",
  "¿Qué objeto ha sobrevivido contigo a varias mudanzas?", "¿Qué hiciste con el primer dinero que ganaste por tu cuenta?",
  "¿A qué persona de tu pasado te gustaría preguntarle su versión de un recuerdo?", "¿Cuál fue tu primera gran idea equivocada sobre el mundo adulto?",
  "¿Qué fiesta de cumpleaños de tu infancia recuerdas todavía?", "¿Qué coleccionabas antes y por qué?",
  "¿Qué película fue todo un acontecimiento para ti en su momento?", "¿Cuándo conseguiste orientarte por primera vez en una ciudad nueva?",
  "¿Qué pequeña tradición de tu época escolar te gustaba?", "¿Qué elogio inesperado recuerdas todavía?",
  "¿Qué preparativo de viaje formaba ya parte de tus vacaciones antes?", "¿Qué le contarías sobre la amistad a tu yo más joven?",
  "¿Qué aroma te devuelve mentalmente a una estación concreta?", "¿Qué momento cotidiano solo entendiste que era importante más adelante?",
  "¿Qué antigua prenda favorita volverías a ponerte hoy?", "¿Qué cambio en tu lugar de origen te sorprende?",
  "¿Qué recuerdo te gustaría guardar como una pequeña escena de película?", "¿Qué ataque de risa compartido recuerdas hasta hoy?",
  "¿Qué te sorprendió la primera vez que viajaste a solas?", "¿Qué decisión temprana tuvo efectos inesperadamente importantes?",
  "¿Qué carta o nota antigua conservaste por un buen motivo?", "¿Qué crees que recordarás especialmente de esta etapa de tu vida?",
];
const erinnerungenTasks = [
  "Describe la habitación de tu infancia con tres detalles concretos.", "Explica las reglas de un juego al que te gustaba jugar de pequeño.",
  "Cuenta un pequeño recuerdo bonito como una noticia de radio en tres frases.", "Di tres cosas de tu época escolar que hoy casi han desaparecido.",
  "Describe una comida que te encantaba sin decir su nombre; el grupo puede adivinarla.", "Dale un consejo amable a tu yo más joven en una sola frase.",
  "Inventa un título adecuado para el álbum de fotos de una etapa bonita de tu vida.", "Muestra con las manos el tamaño de un objeto que de pequeño te parecía enorme.",
  "Cuenta una pequeña prueba de valor del pasado que hoy recuerdes con cariño.", "Describe un recuerdo solo con sensaciones: sonido, olor y color.",
];
const reisenQuestions = [
  "¿Qué miras primero cuando llegas a un lugar nuevo?", "¿Qué viaje fue más bonito porque dejaste algo sin planear?",
  "¿Cuál es tu señal personal de que han empezado las vacaciones?", "¿Qué lugar cercano nunca has explorado de verdad?",
  "¿Qué tipo de paisaje te tranquiliza al instante?", "¿Qué llevas en el equipaje aunque los demás lo vean innecesario?",
  "¿Qué conversación de un viaje se te quedó especialmente grabada?", "¿Cómo decides si un destino encaja contigo?",
  "¿Qué harías un día a solas en una ciudad desconocida?", "¿Qué plato que probaste viajando te gustaría cocinar en casa?",
  "¿Qué hace que un asiento de ventanilla en el tren sea bueno para ti?", "¿Qué costumbre cotidiana de otros lugares te impresionó?",
  "¿Adónde irías si el trayecto tuviera que formar parte de la aventura?", "¿Qué alojamiento recuerdas por las personas?",
  "¿Cuál es tu forma favorita de orientarte en una ciudad?", "¿Qué recuerdo de viaje usas de verdad en tu día a día?",
  "¿Cuánto tardas en sentirte como en casa en un lugar nuevo?", "¿Qué viaje te gustaría hacer a un ritmo muy lento?",
  "¿Qué has aprendido viajando sobre tus propias exigencias?", "¿Qué lugar recuerdas muy distinto de cómo aparece en las fotos?",
  "¿Qué pequeño contratiempo de viaje ya te tomas con calma?", "¿Qué le enseñarías a alguien que visita tu país por primera vez?",
  "¿Qué idioma te gustaría saber para conversar con la gente del lugar?", "¿Qué importancia tiene para ti poder cambiar de planes al viajar?",
  "¿Qué es para ti lo mejor de volver a casa?", "¿Qué mercado o tienda de un viaje despertó especialmente tu curiosidad?",
  "¿Qué recorrido preferirías hacer a pie en lugar de en coche?", "¿Qué debería saber de ti un buen compañero de viaje?",
  "¿Qué vista te gustaría disfrutar sin cámara?", "¿Cómo pasarías una tarde libre de viaje con mal tiempo?",
  "¿Qué idea de viaje has aplazado hasta ahora solo por la planificación?", "¿Qué aprendes de un lugar al visitar un supermercado?",
  "¿Qué medio de transporte te hace sentir más de aventura?", "¿Qué ciudad extranjera podrías imaginar como hogar temporal?",
  "¿Cuál es tu mejor recuerdo de una excursión de un solo día?", "¿Qué tipo de museo podría hacerte entrar por impulso?",
  "¿Cómo encuentras lugares más allá de las atracciones evidentes cuando viajas?", "¿Sobre qué elegirías no informarte antes de un viaje?",
  "¿Qué momento en la naturaleza te sorprendió durante un viaje?", "¿Qué viaje desmintió una expectativa tuya?",
  "¿Cuál sería tu parada ideal en un trayecto largo?", "¿En qué se diferencia tu ritmo de vacaciones del cotidiano?",
  "¿Qué lugar te gustaría volver a ver en otra estación del año?", "¿Qué significa para ti tratar con respeto un lugar ajeno?",
  "¿Qué encuentro fugaz de un viaje te gustaría prolongar?", "¿Qué ruta sería bonita para una excursión con este grupo?",
  "¿Qué habilidad te ayudó de forma inesperada durante un viaje?", "¿Qué experiencia suena poco espectacular pero fue especial durante un viaje?",
  "¿Cómo sería para ti un día de viaje sin entradas a ningún sitio?", "¿Qué le preguntarías a alguien que lleva toda la vida viviendo allí?",
];
const reisenTasks = [
  "Haz una breve visita guiada por donde vives sin nombrar monumentos ni atracciones.", "Prepara mentalmente cinco objetos para una excursión improvisada de un día y explica uno de ellos.",
  "Describe un paisaje como en una postal, en exactamente tres frases.", "Planea un día de lluvia en un lugar desconocido sin pagar entradas.",
  "Inventa un aviso amable para viajeros en un pueblo imaginario.", "Presenta una ruta de tren de tus sueños con tres paradas muy distintas.",
  "Muestra sin palabras cómo preguntarías el camino a una cafetería.", "Recomienda al grupo una pequeña aventura a la que se pueda llegar en una hora.",
  "Describe un alojamiento poco habitual en el que pasarías una noche.", "Inventa un eslogan turístico para un lugar poco llamativo, como un aparcamiento o un rellano.",
];
const traeumeQuestions = [
  "¿Qué pequeña idea de futuro te hace ilusión ahora mismo?", "¿Qué te gustaría aprender aunque nunca se te diera especialmente bien?",
  "¿Cómo te gustaría sentirte en un día normal dentro de cinco años?", "¿Qué proyecto te interesaría aunque nadie te reconociera el mérito?",
  "¿Qué tipo de hogar te gustaría crear a largo plazo?", "¿Qué harías con una tarde libre a la semana?",
  "¿Qué costumbre te gustaría regalarle a tu yo del futuro?", "¿Qué deseo se ha vuelto más importante para ti al hacerte mayor?",
  "¿Qué te gustaría vivir por primera vez?", "¿Qué habilidad podría facilitarte mucho el día a día?",
  "¿Qué te gustaría fabricar tú alguna vez en vez de comprarlo?", "¿Qué personas te gustaría tener más a menudo cerca en el futuro?",
  "¿Qué proyecto necesita más valor que dinero?", "¿Cómo organizarías un año en el que nadie juzgara tu currículum?",
  "¿Qué te gustaría enseñarle alguna vez a alguien más joven?", "¿Qué parte de tu vida puede quedarse tranquilamente como está?",
  "¿Qué proyecto compartido te gustaría planear con amigos?", "¿Qué probarías si fracasar no tuviera consecuencias?",
  "¿Qué tipo de trabajo podría seguir dándote alegría más adelante?", "¿Qué te gustaría poder decir de ti algún día?",
  "¿Qué vieja idea tuya merece un segundo intento?", "¿Cómo sería tu lugar ideal para una pausa creativa?",
  "¿Qué deseo apenas has dicho en voz alta hasta ahora?", "¿Cuál sería un primer paso realista hacia una gran meta?",
  "¿Qué tradición te gustaría iniciar en tu entorno?", "¿De qué te gustaría tener menos para sentirte más libre?",
  "¿Qué experiencia valdría para ti más que un objeto caro?", "¿Cómo te gustaría celebrar un gran éxito personal?",
  "¿Qué tipo de aventura encaja con quien eres hoy?", "¿Qué te gustaría ayudar a crear o mejorar en tu zona?",
  "¿Qué deseo de la infancia te haría ilusión todavía hoy?", "¿Cómo sabrías que ya has logrado suficiente?",
  "¿Qué te gustaría hacer distinto el próximo invierno?", "¿Qué nueva conexión entre tus intereses te gustaría descubrir?",
  "¿De qué te gustaría sentirte orgulloso al mirar atrás, aunque nadie lo vea?", "¿Qué espacio libre de tu agenda te gustaría proteger?",
  "¿Qué te gustaría mostrar alguna vez ante un público pequeño?", "¿Qué tipo de comunidad te gustaría crear o encontrar?",
  "¿Cuál podría ser un buen lema para tu próximo año de vida?", "¿Qué objetivo perseguirías sin compararte con los demás?",
  "¿Qué elegirías llevarte o dejar atrás conscientemente en tu próxima mudanza?", "¿Qué cambio lento te gustaría empezar?",
  "¿A quién te gustaría devolverle algún día algo de lo que has recibido?", "¿Qué motivo haría que te mereciera la pena volver a ser principiante?",
  "¿Qué recuerdo te gustaría crear todavía con tu familia?", "¿Qué harías con una habitación pequeña vacía?",
  "¿Qué cualidad te gustaría conservar al hacerte mayor?", "¿Qué te gustaría celebrar más a menudo el año que viene?",
  "¿Qué sueño podrías hacer realidad pronto en una versión más pequeña?", "¿Qué pregunta abierta sobre tu futuro te resulta interesante ahora mismo?",
];
const traeumeTasks = [
  "Describe un deseo y un primer paso que lleve menos de diez minutos.", "Da un breve discurso de agradecimiento a tu yo futuro por una buena costumbre nueva.",
  "Inventa el título de un curso al que irías por pura curiosidad.", "Pinta con palabras una mañana normal de tu vida cotidiana ideal.",
  "Di tres cosas que te gustaría aprender sin tener que dominarlas.", "Formula un lema amable para tu próximo mes.",
  "Presenta un proyecto de futuro compartido que este grupo pueda empezar un fin de semana.", "Explica un deseo de la infancia como si lo descubrieras hoy por primera vez.",
  "Inventa una pequeña celebración para un logro que nadie más notaría.", "Describe una cápsula del tiempo con tres cosas que representen bien a tu yo actual.",
];
const entscheidungenQuestions = [
  "¿Para qué decisión te ayuda de verdad consultarlo con la almohada?", "¿Qué se ha vuelto más importante para ti que una buena primera impresión?",
  "¿Cuándo renunciarías a la comodidad por actuar con justicia?", "¿Qué decisión prefieres tomar por intuición y no con una lista?",
  "¿Qué significa el éxito para ti más allá del dinero y el trabajo?", "¿Qué límite de tu tiempo te gustaría proteger mejor?",
  "¿Sobre qué cambiaste de opinión tras escuchar un buen argumento?", "¿Qué hace que una promesa sea un compromiso para ti?",
  "¿Cómo sabes que un compromiso va demasiado lejos para ti?", "¿Qué pequeña decisión influye en tu ánimo más de lo esperado?",
  "¿Cuándo es especialmente importante ser sincero sin añadir explicaciones?", "¿Qué preferirías reparar aunque comprarlo nuevo fuera más fácil?",
  "¿Qué tipo de riesgo te gusta asumir?", "¿Cómo eliges entre dos opciones igual de buenas?",
  "¿Qué hace que alguien sea creíble a tus ojos?", "¿Para qué te gustaría tener más paciencia en el día a día?",
  "¿Cuándo puede ser amable decidir que no?", "¿Qué convicción tuya te gustaría examinar más a fondo?",
  "¿Qué valoras más en una disculpa: las palabras o el comportamiento?", "¿Cuánta incertidumbre necesitas para que la vida siga siendo emocionante?",
  "¿Qué costumbre cómoda no encaja del todo con tus valores?", "¿Cuándo renunciaste a dinero para ganar tiempo?",
  "¿Qué habría que compartir aunque solo te pertenezca a ti?", "¿Qué decisión no tomarías mediante una votación en grupo?",
  "¿Cómo reconoces un consejo que realmente encaja contigo?", "¿Qué distingue para ti la generosidad del deseo de agradar?",
  "¿Qué pequeña cosa merece más reconocimiento del que recibe?", "¿Cuándo es más sensato dejar un proyecto que ya has empezado?",
  "¿Qué te gustaría decidir de forma más consciente al consumir?", "¿Qué cualidad valoras más que unas habilidades impresionantes?",
  "¿Cómo afrontas una decisión que solo más tarde resulta equivocada?", "¿Qué protegerías primero con un presupuesto limitado?",
  "¿Cuándo debería una regla permitir una excepción justificada?", "¿Qué significa la responsabilidad en una vivienda compartida?",
  "¿Qué opinión mantienes aunque tus amigos no estén de acuerdo?", "¿Qué te ayuda a no aplazar una decisión eternamente?",
  "¿Cuándo merece más la pena una conversación difícil que mantener la armonía?", "¿Qué decisión te dio libertad?",
  "¿Qué debería saber alguien antes de juzgar el éxito de los demás?", "¿Cuánta planificación te da seguridad y a partir de cuándo se convierte en control?",
  "¿Qué hace que un reparto de tareas sea justo?", "¿Qué tipo de competición te resulta enriquecedora?",
  "¿En qué no tomarías atajos ni siquiera en un día agotador?", "¿Cuándo es útil corregir públicamente tu propia opinión?",
  "¿Qué oportunidad preferirías rechazar para mantenerte fiel a ti?", "¿Cómo distingues una necesidad real de un deseo pasajero?",
  "¿Qué puede sorprender a los demás de tu estilo de vida?", "¿Qué decisión tomarías hoy con más calma que antes?",
  "¿Cómo notas que necesitas una pausa en vez de una solución nueva?", "¿Qué acción cotidiana expresa mejor tus valores?",
];
const entscheidungenTasks = [
  "Defiende en dos frases que hacer una pausa es una decisión inteligente.", "Propón un reparto justo de tres tareas domésticas desagradables entre tres personas.",
  "Da una buena razón para planear y otra igual de buena para ser espontáneo.", "Practica un no educado a una invitación sin inventar una excusa.",
  "Explícale a un niño imaginario qué significa la justicia con un ejemplo cotidiano.", "Di una pequeña decisión de compra y una posible alternativa más sostenible.",
  "Formula una frase con la que podrías cambiar de opinión tras un buen argumento.", "Propón dos soluciones justas si un grupo no consigue ponerse de acuerdo sobre un restaurante.",
  "Describe una regla personal que te facilite el día a día y una excepción permitida.", "Inventa un mensaje publicitario breve para la paciencia en vez de para un producto.",
];
const kreativQuestions = [
  "¿Qué habitación secreta añadirías a una biblioteca?", "¿Cómo sería una festividad que pudieras inventar tú?",
  "¿Qué dos profesiones normales crearían una nueva y fantástica al juntarlas?", "¿Qué expondría un museo sobre tu vida cotidiana actual?",
  "¿Qué superpoder solo serviría para las tareas de casa?", "¿Cómo sería una ciudad construida para personas nocturnas?",
  "¿A qué objeto le darías voz durante un día?", "¿Cuál sería una buena escena inicial para una película sobre este grupo?",
  "¿Qué deporte nuevo se podría inventar sin material?", "¿Cómo sería un restaurante con la carta organizada por estados de ánimo?",
  "¿Qué dejarías en una cápsula del tiempo para la gente de dentro de cien años?", "¿De qué color sería un sonido que te gusta?",
  "¿Cómo convertirías una sala de espera aburrida en un lugar favorito?", "¿Qué habilidad animal sería sorprendentemente práctica en una oficina?",
  "¿Cuál sería el mayor problema de un mundo donde todos los pensamientos aparecen como subtítulos?", "¿Qué acontecimiento cotidiano merece su propia banda sonora?",
  "¿Cómo sería una versión amistosa de un monstruo clásico del cine?", "¿Qué invento le encantaría al instante a alguien de la Edad Media?",
  "¿Qué podría contar una nube en su diario?", "¿Cómo diseñarías un parque de ocio sin atracciones mecánicas?",
  "¿Qué animal imaginario sería un buen compañero de viaje en tren?", "¿Cuál sería un sexto sentido útil para el día a día?",
  "¿Cómo sería una historia policiaca en la que nadie puede mentir?", "¿Qué moneda poco habitual funcionaría en una isla de cocineros?",
  "¿Qué pondrías en una plaza de ciudad completamente vacía?", "¿Cómo sería una casa de ensueño si cada habitación fuera una estación del año?",
  "¿Qué cosa inofensiva sería un gran tesoro en tu mundo inventado?", "¿Cuál sería un buen nombre para la nave espacial de este grupo?",
  "¿Cómo le explicarías a un robot lo que significa sentirse a gusto?", "¿Qué personaje de cuento necesitaría cambiar urgentemente de profesión hoy?",
  "¿Qué haría un ascensor si tuviera su propio día libre?", "¿Cómo sería una escuela donde la curiosidad fuera la única asignatura?",
  "¿Qué tres reglas tendría un juego que solo se juega en la cabeza?", "¿Cuál sería el mensaje más inusual pero sensato en una galleta de la suerte?",
  "¿Cómo cambiaría una ciudad si los tejados se convirtieran en jardines?", "¿Qué palabra nueva falta para un sentimiento que conoces?",
  "¿Qué deduciría un detective sobre ti a partir de tu desayuno?", "¿Cómo sería una exposición formada solo por olores?",
  "¿De qué tarea se encargaría en tu casa un pequeño dragón simpático?", "¿Cómo sería un manual de instrucciones gracioso para un domingo?",
  "¿Cómo planearías un viaje en el que una moneda decide todas las direcciones?", "¿Qué milagro sería espectacular pero completamente inútil en el día a día?",
  "¿Qué podría contar un libro que elige a su propio lector?", "¿Cómo funcionaría una tienda que vende recuerdos en vez de objetos?",
  "¿Qué nueva disciplina encajaría en unas Olimpiadas de la paciencia?", "¿Cuál sería el primer anuncio en una ciudad bajo el agua?",
  "¿Cómo llamarías a un juego de mesa sobre tu profesión o tu día a día?", "¿Qué mensaje te escribiría tu futura mascota?",
  "¿Cuál sería una bonita misión para un hechizo muy pequeño?", "¿Cómo podrían ser los créditos finales de esta noche?",
];
const kreativTasks = [
  "Inventa en tres frases una historia en la que aparezcan una llave, una nube y una panadería.", "Dale a un objeto de la habitación un superpoder y una debilidad absurda.",
  "Inventa una palabra nueva para la alegría de que se cancelen planes agotadores.", "Describe un monstruo simpático y su pasatiempo favorito.",
  "Inventa dos frases de un anuncio para un paraguas invisible.", "Representa una conversación entre el sol y la luna con dos voces distintas.",
  "Diseña mentalmente una nueva festividad con nombre y una tradición sencilla.", "Inventa el título de un libro y la primera frase de una historia sobre esta botella.",
  "Describe una habitación donde solo los muebles se libran de la gravedad.", "Inventa un pequeño hechizo que resuelva exactamente un problema cotidiano inofensivo.",
];
export const QUESTIONS = {
  eisbrecher: eisbrecherQuestions,
  spass: spassQuestions,
  party: partyQuestions,
  freundschaft: freundschaftQuestions,
  liebe: liebeQuestions,
  erinnerungen: erinnerungenQuestions,
  reisen: reisenQuestions,
  traeume: traeumeQuestions,
  entscheidungen: entscheidungenQuestions,
  kreativ: kreativQuestions,
};
export const TASKS = {
  eisbrecher: eisbrecherTasks,
  spass: spassTasks,
  party: partyTasks,
  freundschaft: freundschaftTasks,
  liebe: liebeTasks,
  erinnerungen: erinnerungenTasks,
  reisen: reisenTasks,
  traeume: traeumeTasks,
  entscheidungen: entscheidungenTasks,
  kreativ: kreativTasks,
};
