/** Édition française complète, dans le même ordre que editorial-de.ts. */
export const QUESTIONS = {
  eisbrecher: [
    "Quel petit luxe améliore une journée ordinaire pour toi ?", "Qu'est-ce que les invités remarquent probablement en premier chez toi ?",
    "De quel sujet peux-tu parler au point d'en oublier l'heure ?", "Quelle compétence proposerais-tu tout de suite à une nouvelle personne en colocation ?",
    "À quoi ressemble ta matinée libre idéale ?", "Quel plat commandes-tu quand tu n'arrives pas à choisir ?",
    "À quoi voit-on que tu te sens à l'aise dans un groupe ?", "Quelle activité te calme avec une efficacité surprenante ?",
    "Que gardes-tu généralement à portée de main près de ton lit ?", "Quelle petite chose discrète sais-tu étonnamment bien faire ?",
    "Quelle odeur te rappelle immédiatement un bel endroit ?", "Comment décrirais-tu ton humour à quelqu'un qui ne te connaît pas ?",
    "Quelle partie de ton quotidien aimerais-tu confier à un robot ?", "Quel est ton endroit préféré pour observer les gens ?",
    "Quelle application installerais-tu en premier sur un nouveau téléphone ?", "Quelle boisson marque pour toi le début d'une soirée tranquille ?",
    "Quelle saison correspond le mieux à ton tempérament ?", "Que collectionnes-tu sans l'avoir vraiment décidé ?",
    "Quel compliment aimes-tu particulièrement entendre ?", "De combien d'organisation as-tu besoin pour passer un bon dimanche ?",
    "Quelle petite chose anodine t'enthousiasme démesurément ?", "Quel jeu de société ou de cartes réveille ton esprit de compétition ?",
    "Que montrerais-tu en premier à quelqu'un qui visite ta région ?", "Quelle question te pose-t-on bien trop rarement ?",
    "Comment choisis-tu ta prochaine lecture ou ce que tu vas regarder ?", "Que révèle ton sac actuel sur ton quotidien ?",
    "Quel temps apprécies-tu davantage que la plupart des gens ?", "Quel animal représente ton énergie un lundi matin ?",
    "Qu'est-ce que tu préfères acheter d'occasion plutôt que neuf ?", "Qu'est-ce qui fait un bon café pour toi ?",
    "Quelle tâche ménagère aimes-tu vraiment faire ?", "Comment décides-tu d'accepter ou non une invitation ?",
    "Quelle petite surprise te ferait vraiment plaisir ?", "De quel vêtement aurais-tu du mal à te séparer ?",
    "Quel bruit te fait sentir que tu es chez toi ?", "Que veux-tu comprendre en premier chez une personne que tu viens de rencontrer ?",
    "Quel repas réussis-tu même sans recette ?", "À quel moment de la journée as-tu l'esprit le plus vif ?",
    "Qu'est-ce qui ne doit jamais manquer dans ton pique-nique ?", "Quel objet près de toi a une histoire ?",
    "Comment occupes-tu dix minutes libres inattendues ?", "Quelle a été ta dernière excellente idée improvisée ?",
    "Devant quel type de boutique as-tu du mal à passer sans jeter un œil ?", "Qu'est-ce qui te donne envie de poursuivre une conversation ?",
    "Quelle habitude as-tu adoptée en imitant quelqu'un d'autre ?", "De quoi t'occuperais-tu lors d'une soirée cuisine à plusieurs ?",
    "Quel mot utilises-tu probablement plus souvent que les autres ?", "Qu'est-ce qui témoigne pour toi d'un accueil chaleureux ?",
    "Quelle question aimerais-tu poser à ce groupe ?", "Que faut-il savoir sur toi pour organiser une sortie avec toi ?",
  ],
  spass: [
    "Quelle chose totalement insignifiante défends-tu avec une passion surprenante ?", "Quel est le lapsus le plus drôle que tu te rappelles avoir fait ?",
    "Quelle règle anodine as-tu inventée uniquement pour toi ?", "Quelle activité commentes-tu parfois comme un journaliste sportif ?",
    "Quel personnage de film serait une catastrophe en colocation avec toi ?", "Dans quel domaine surestimes-tu régulièrement ton talent ?",
    "Quel bruit sais-tu imiter de façon étonnamment convaincante ?", "Quelle peur ridicule avais-tu dans ton enfance ?",
    "Quel slogan publicitaire serait le moins adapté à ton quotidien ?", "Quel petit objet égares-tu toujours au même endroit absurde ?",
    "Quel plat est moins beau que bon quand tu le prépares ?", "Quand as-tu ri de ta propre erreur pour la dernière fois ?",
    "Quelle expression as-tu longtemps mal comprise ?", "Qu'écrirais-tu sur un trophée récompensant ton pire défaut ?",
    "Quelle combinaison étrange aimes-tu vraiment manger ?", "Quel objet du quotidien serait le plus compliqué à avoir comme animal de compagnie ?",
    "Quelle situation te fait rire même quand tu veux garder ton sérieux ?", "Quelle solution inutilement compliquée as-tu trouvée à un problème simple ?",
    "Quelle loi imaginaire interdirait ton habitude la plus agaçante ?", "Quel minuscule désagrément te fait intérieurement tout dramatiser ?",
    "Quel serait le titre d'une sitcom sur ton mois écoulé ?", "Quelle période où tu te croyais cool te paraît particulièrement drôle aujourd'hui ?",
    "Quelle est l'excuse la plus étrange que tu as réussi à te faire croire ?", "Lors de quelle panne technologique t'es-tu le plus surpris toi-même ?",
    "Quel talent parfaitement inutile mettrais-tu dans une candidature ?", "Quel meuble te semble capable d'être de mauvaise humeur ?",
    "Quelle petite chose accomplis-tu avec beaucoup trop de cérémonie ?", "Quel serait ton nom de scène insolite dans un spectacle de magie ?",
    "Quel petit mensonge sur le quotidien serait facile à démasquer ?", "Quelle a été ta confusion la plus drôle en faisant les courses ?",
    "Quel aliment devrait, selon toi, être livré avec un mode d'emploi ?", "Quel rôle aurais-tu dans l'équipage chaotique d'un vaisseau spatial ?",
    "Comment parle ta voix intérieure quand tu dois assembler quelque chose ?", "Qu'est-ce qui te fait rire alors que tu as du mal à expliquer pourquoi ?",
    "Quel serait le motif le plus ridicule d'une querelle acharnée entre voisins ?", "Quel mouvement quotidien paraît involontairement élégant quand tu le fais ?",
    "Quel mot ne ressemble pas du tout à son sens, à tes oreilles ?", "Qu'est-ce que ton réfrigérateur raconterait sur toi ?",
    "Quel sport serait le plus drôle avec du matériel de bureau ?", "Quel est ton souvenir le plus drôle lié au correcteur automatique ?",
    "Quel objet chez toi mérite un prénom ?", "Comment raconterais-tu une corvée de courses comme un film d'action ?",
    "Quel débat ridicule pourrait quand même t'occuper vingt minutes ?", "Quel serait un titre étonnamment honnête pour ton livre de cuisine ?",
    "Laquelle de tes habitudes un extraterrestre pourrait-il mal interpréter ?", "Quel animal détournerait le plus l'attention en présentant le journal télévisé ?",
    "Quel mauvais achat t'a au moins donné une bonne histoire à raconter ?", "Quelle habitude reconnaîtrais-tu immédiatement chez ton sosie ?",
    "Quelle phrase ordinaire pourrait devenir un avertissement dramatique au cinéma ?", "Quelle est la supposition erronée la plus drôle qu'on ait faite sur toi ?",
  ],
  party: [
    "Quelle chanson te donne envie de bouger même après une longue journée ?", "Qu'est-ce qui distingue une bonne fête d'une fête simplement bruyante ?",
    "Quel concert aimerais-tu pouvoir redécouvrir pour la première fois ?", "Quel rôle prends-tu automatiquement pendant les fêtes ?",
    "Quel thème te donnerait vraiment envie d'aller à une soirée déguisée ?", "Quelle chanson associes-tu à une amitié particulière ?",
    "Quelle serait la conclusion parfaite d'une longue soirée pour toi ?", "Quel petit détail rend une personne qui reçoit inoubliable ?",
    "Quelle chanson chantes-tu même si tu n'en connais que le refrain ?", "Quelle a été ta meilleure conversation à l'écart d'une piste de danse ?",
    "De quel instrument aimerais-tu jouer dans un groupe ?", "Quelle fête t'a agréablement surpris alors que tu n'avais pas envie d'y aller ?",
    "Que doit proposer un buffet pour te satisfaire ?", "Quel style musical as-tu appris à apprécier sur le tard ?",
    "Comment ferais-tu pour que des inconnus discutent lors d'une fête ?", "Quel artiste choisirais-tu pour un minuscule concert dans un salon ?",
    "Quel est ton meilleur souvenir de festival ?", "Quelle chanson devrait accompagner ton générique de fin personnel ?",
    "Quelle tradition de fête supprimerais-tu sans regret ?", "En soirée, qu'est-ce qui compte le plus pour toi : les visages familiers ou les nouvelles rencontres ?",
    "Quelle recommandation musicale de ton entourage t'a vraiment plu ?", "Comment rendrais-tu un anniversaire spécial avec très peu d'argent ?",
    "Quel pas de danse te semble toujours approprié ?", "De quoi parlerait ta propre émission de radio ?",
    "Quelle fête préférerais-tu organiser dehors plutôt qu'à l'intérieur ?", "Quelle chanson te rappelle un long trajet ?",
    "Quelle est l'invitation la plus créative que tu aies reçue ?", "De quelles trois choses les invités ont-ils besoin pour se sentir vite à l'aise ?",
    "Quelle chanson ferais-tu écouter à quelqu'un pour lui faire comprendre ton humeur ?", "Qu'est-ce qui fait pour toi une soirée jeux réussie ?",
    "Quelle opinion musicale ne partages-tu avec presque personne ?", "Quel aliment inhabituel conviendrait à une pause de minuit ?",
    "Comment sais-tu qu'il est temps de rentrer ?", "Que préférerais-tu faire toi-même à une fête plutôt que de laisser quelqu'un l'organiser ?",
    "Quelles paroles de chanson t'ont particulièrement marqué ?", "Quelle surprise d'anniversaire risquerait de te mettre mal à l'aise ?",
    "Quel bruit aimes-tu dans un enregistrement de concert ?", "Pour quelle fête n'as-tu besoin d'aucune occasion particulière ?",
    "Quelle serait la durée idéale d'une playlist commune ?", "Quelle musique accompagne le rangement après le départ des invités chez toi ?",
    "Quel beau moment as-tu vécu à un mariage en dehors de la cérémonie ?", "Quel endroit serait insolite mais chaleureux pour une petite fête ?",
    "Comment rendrais-tu une soirée intéressante sans enceintes ?", "Quel album préfères-tu écouter en entier plutôt que chanson par chanson ?",
    "Quelle est la meilleure façon d'engager la conversation à une table d'inconnus ?", "Quelle découverte musicale aimerais-tu partager avec le groupe ?",
    "À quoi ressemblerait une fête parfaitement adaptée à ton niveau d'énergie ?", "Quel souvenir associes-tu à une danse particulière ?",
    "Que veux-tu volontairement changer lors de ta prochaine fête ?", "Quel titre donnerais-tu à la playlist de cette soirée ?",
  ],
  freundschaft: [
    "Comment as-tu compris qu'une connaissance était devenue une véritable amitié ?", "Quel petit geste de tes amis compte particulièrement pour toi ?",
    "Que peux-tu faire avec des amis sans avoir besoin de beaucoup parler ?", "Comment gardes-tu le contact avec les personnes qui habitent loin ?",
    "Quelle qualité de tes amis t'a toi-même fait évoluer ?", "Quelle est une bonne manière de reprendre contact après un long silence ?",
    "Quelle mésaventure vécue ensemble a renforcé vos liens ?", "Comment montres-tu à un ami que tu l'écoutes vraiment ?",
    "Qu'essaierais-tu avec un ami, mais pas en solo ?", "Quelle tradition ne devrait jamais devenir une obligation dans une amitié ?",
    "Quand as-tu ressenti une grande fierté pour quelqu'un de ton cercle d'amis ?", "Quelle place laisses-tu à la spontanéité dans tes projets entre amis ?",
    "Qu'apprécies-tu chez les amis très différents de toi ?", "Quel type de soutien proposes-tu facilement ?",
    "Comment peut-on te contredire franchement sans que tu te refermes ?", "Quelle sortie entre amis reste particulièrement vivante dans ta mémoire ?",
    "Qu'est-ce qui fait de bonnes excuses entre amis pour toi ?", "Quel type de message te fait plaisir lors d'une journée ordinaire ?",
    "Sur quel sujet demanderais-tu conseil à un ami plutôt qu'à Internet ?", "Quelle limite est devenue importante pour toi en amitié ?",
    "Quelle activité commune rapproche des personnes très différentes ?", "Comment repères-tu qu'une personne a besoin de compagnie plutôt que de conseils ?",
    "Quel est le cadeau le plus attentionné que tu aies reçu d'un ami ?", "Quelle amitié est née dans un lieu inattendu ?",
    "Comment ta façon de parler change-t-elle avec tes amis les plus proches ?", "Que ne faut-il pas prendre personnellement quand on est ton ami ?",
    "Quelle qualité fait de quelqu'un un bon compagnon de voyage ?", "Que proposerais-tu pour une heure libre à passer ensemble ?",
    "Quel souvenir aimerais-tu comparer avec celui d'un vieil ami ?", "Comment célèbres-tu les petites réussites de tes amis ?",
    "Qu'est-ce qui t'aide à retrouver de la proximité après un désaccord ?", "Quel projet commun pourrait enrichir votre amitié ?",
    "Qu'est-ce que tes amis t'ont appris sur toi-même ?", "Quel type d'aide as-tu du mal à accepter ?",
    "Quelle importance accordes-tu à la ponctualité en amitié ?", "Quelle petite blague entre amis peux-tu expliquer au groupe ?",
    "Que reconnaîtrais-tu immédiatement chez un ami, même après des années ?", "Quand un silence partagé te paraît-il agréable ?",
    "Qu'est-ce qui permet à une nouvelle personne de se sentir bienvenue dans un groupe déjà formé ?", "Quelle amitié aimerais-tu entretenir plus souvent au quotidien ?",
    "Quelle différence fais-tu entre la loyauté et le fait de toujours approuver ?", "Quelle activité fonctionne mieux avec des amis qu'en famille ?",
    "Comment remonterais-tu le moral d'un ami après une journée décevante ?", "Quelle habitude partagée te manque parfois ?",
    "À quoi voit-on que tu as besoin de temps pour toi ?", "Quel point commun inattendu t'a rapproché de quelqu'un ?",
    "Quelle est une bonne occasion de simplement remercier un ami ?", "Comment vis-tu les différents degrés de proximité dans tes amitiés ?",
    "Quelle compétence d'un ami admires-tu, discrètement ou ouvertement ?", "À quoi aimerais-tu faire davantage attention dans ta façon d'être un ami ?",
  ],
  liebe: [
    "Quelle forme d'attention te donne le sentiment de vraiment compter ?", "Qu'est-ce qui rend un premier rendez-vous détendu pour toi ?",
    "Quelle petite scène du quotidien trouves-tu romantique ?", "Comment sais-tu que tu peux faire confiance à quelqu'un ?",
    "En faisant connaissance, que préférerais-tu raconter en personne plutôt que par message ?", "Quelle qualité devient plus attirante à tes yeux avec le temps ?",
    "Que signifie la proximité pour toi en dehors du contact physique ?", "Comment une personne devrait-elle réagir quand tu exprimes une limite ?",
    "Quelle habitude commune pourrait enrichir une relation ?", "Quel serait un beau rendez-vous qui ne coûte presque rien ?",
    "Comment montres-tu ton affection quand les mots te manquent ?", "Quelle idée du romantisme ne te correspond pas du tout ?",
    "Qu'aimerais-tu connaître assez tôt du quotidien de la personne avec qui tu es ?", "Quel genre d'humour t'aide à flirter ?",
    "Quand ressens-tu une connexion particulièrement forte dans une conversation ?", "De quoi as-tu besoin pour préserver ton autonomie dans une relation ?",
    "Quelle question révèle plus de choses qu'un métier quand on fait connaissance ?", "Comment fais-tu quand l'autre personne a besoin de beaucoup plus de calme ?",
    "Quel compliment te ferait sincèrement plaisir lors d'un rendez-vous ?", "Qu'est-ce qui est pour toi un bon signe après un désaccord ?",
    "Quelle expérience partagée en dit long sur la façon de vivre ensemble ?", "Quelle importance ont les loisirs communs dans une relation ?",
    "Qu'est-ce qui rendrait une lettre d'amour personnelle à tes yeux ?", "Quel type de surprise aimes-tu dans une relation ?",
    "Que devrait-on se dire régulièrement dans une relation ?", "Comment reconnais-tu un intérêt respectueux plutôt qu'un comportement insistant ?",
    "Comment organiserais-tu une journée libre à deux sans écrans ?", "Quel petit détail peut apaiser ta nervosité lors d'un rendez-vous ?",
    "Quelle différence fais-tu entre les premiers élans amoureux et la complicité installée ?", "Quelle relation dans un film te paraît crédible ?",
    "Quelle place aimes-tu donner aux projets planifiés à deux ?", "Quel serait un geste attentionné dans une relation à distance ?",
    "Quel genre de conversation préfères-tu avoir en te promenant ?", "Comment aimerais-tu qu'on t'aborde quand quelque chose te préoccupe visiblement ?",
    "Qu'as-tu appris sur tes propres besoins ?", "Quelle qualité fait de quelqu'un une personne à l'écoute lors d'un rendez-vous ?",
    "Comment peut-on montrer son affection sans dépenser d'argent ?", "Comment vivre sainement le fait d'avoir des centres d'intérêt différents ?",
    "Quelle décision commune ne devrait jamais être prise en solo ?", "Que signifie pour toi être fiable, très concrètement ?",
    "Comment gérer équitablement des niveaux d'énergie différents ?", "Quel genre de conversation ne voudrais-tu jamais avoir à la va-vite ?",
    "Que peut apprendre un couple des bonnes amitiés ?", "Quelle petite tradition aimerais-tu essayer à deux ?",
    "Est-ce important pour toi que ton entourage connaisse bien la personne avec qui tu es ?", "Quelle est une façon charmante de montrer son intérêt sans mettre la pression ?",
    "Quelle limite as-tu concernant les démonstrations d'affection en public ?", "À quoi verrais-tu qu'une relation te fait du bien ?",
    "Que voudrais-tu faire en premier lors de retrouvailles après une longue séparation ?", "Quelle idée d'une bonne relation a changé pour toi ?",
  ],
  erinnerungen: [
    "Quel petit détail de ton enfance peux-tu encore décrire précisément ?", "Quel trajet vers l'école t'a particulièrement marqué ?",
    "Quel a été ton premier achat personnel qui t'a donné de la fierté ?", "Quelle cuisine associes-tu à un sentiment de réconfort ?",
    "À quel jeu pouvais-tu jouer pendant des heures autrefois ?", "Quelle journée pluvieuse a été étonnamment belle ?",
    "Quelle personne adulte t'a pris au sérieux pendant ton enfance ?", "Quel rituel de vacances aimerais-tu faire revivre ?",
    "Quelle a été ta première réussite dont tu as pris conscience en dehors de l'école ?", "Quel endroit ne connais-tu plus aujourd'hui que par tes souvenirs ?",
    "Quelle histoire racontait-on souvent dans ta famille ?", "Quelle a été ta tentative la plus drôle pour avoir l'air adulte ?",
    "Quelle ancienne passion pourrait te reprendre aujourd'hui ?", "Quelle scène de ton ancien quartier t'est restée en mémoire ?",
    "Que savais-tu mieux faire dans ton enfance qu'aujourd'hui ?", "Quel cadeau t'avait complètement surpris à l'époque ?",
    "À quoi ressemblait ton refuge préféré autrefois ?", "Quelle première rencontre te rappelles-tu avec une précision inhabituelle ?",
    "Quel petit moment de courage as-tu vécu dans ta jeunesse ?", "Quelle sortie s'est déroulée autrement que prévu tout en restant belle ?",
    "Qui t'a appris une compétence pratique ?", "Quel repas autrefois exceptionnel est devenu ordinaire aujourd'hui ?",
    "Quelle photo aimerais-tu pouvoir reprendre ?", "Quelle ancienne habitude familiale comprends-tu mieux aujourd'hui ?",
    "Qu'as-tu sous-estimé en ayant ton premier logement ?", "Quel bruit te manque d'une période passée de ta vie ?",
    "Quel départ a ensuite ouvert la voie à un beau début ?", "Quel cours t'a marqué pour une raison surprenante ?",
    "Quel objet t'a suivi au fil de plusieurs déménagements ?", "Qu'as-tu fait du premier argent que tu as gagné ?",
    "À quelle personne de ton passé aimerais-tu demander sa version d'un souvenir ?", "Quelle a été ta première grande idée fausse sur le monde adulte ?",
    "Quelle fête d'anniversaire de ton enfance t'est restée en mémoire ?", "Que collectionnais-tu autrefois, et pourquoi ?",
    "Quel film représentait un véritable événement pour toi à l'époque ?", "Quand as-tu réussi pour la première fois à te repérer dans une nouvelle ville ?",
    "Quelle petite tradition scolaire te plaisait ?", "Quel compliment inattendu te rappelles-tu encore ?",
    "Quelle préparation au voyage faisait déjà partie des vacances pour toi ?", "Que dirais-tu à ton toi plus jeune sur l'amitié ?",
    "Quel parfum te ramène mentalement à une saison particulière ?", "De quel moment ordinaire n'as-tu compris l'importance que plus tard ?",
    "Quel ancien vêtement préféré porterais-tu de nouveau aujourd'hui ?", "Quel changement dans ta ville d'origine te surprend ?",
    "Quel souvenir aimerais-tu conserver sous forme de petite scène de film ?", "Quel fou rire partagé te reste encore aujourd'hui ?",
    "Qu'est-ce qui t'a surpris lors de ton premier voyage en solo ?", "Quelle décision prise tôt a eu des effets étonnamment importants ?",
    "Quelle ancienne lettre ou quel petit mot as-tu conservé pour une bonne raison ?", "Que retiendras-tu probablement le plus de ta période de vie actuelle ?",
  ],
  reisen: [
    "Que regardes-tu en premier dans un nouvel endroit ?", "Quel voyage a été plus beau parce que tout n'était pas prévu ?",
    "Quel est ton signe personnel que les vacances ont commencé ?", "Quel lieu près de chez toi n'as-tu jamais vraiment exploré ?",
    "Quel type de paysage te calme immédiatement ?", "Qu'emportes-tu dans tes bagages alors que les autres trouvent cela inutile ?",
    "Quelle conversation en voyage t'a particulièrement marqué ?", "Comment décides-tu qu'une destination te correspond ?",
    "Que ferais-tu pendant une journée en solo dans une ville inconnue ?", "Quel plat découvert en voyage aimerais-tu refaire ?",
    "Qu'est-ce qui fait une bonne place près de la fenêtre dans un train pour toi ?", "Quelle habitude quotidienne observée ailleurs t'a impressionné ?",
    "Où irais-tu si le trajet devait faire partie de l'aventure ?", "De quel hébergement te souviens-tu grâce aux personnes rencontrées ?",
    "Quelle est ta façon préférée de te repérer dans une ville ?", "Quel souvenir de voyage utilises-tu vraiment au quotidien ?",
    "Combien de temps te faut-il pour te sentir chez toi dans un nouvel endroit ?", "Quel voyage aimerais-tu faire en prenant vraiment ton temps ?",
    "Qu'as-tu appris en voyage sur tes propres exigences ?", "Quel endroit est très différent dans ton souvenir et sur les photos ?",
    "Quelle petite mésaventure de voyage arrives-tu désormais à prendre avec calme ?", "Que montrerais-tu à quelqu'un qui visite ton pays pour la première fois ?",
    "Quelle langue aimerais-tu parler pour échanger sur place ?", "Est-ce important pour toi de pouvoir changer tes plans en voyage ?",
    "Qu'est-ce que tu préfères dans le retour à la maison ?", "Quel marché ou magasin découvert en voyage a particulièrement éveillé ta curiosité ?",
    "Quel trajet préférerais-tu découvrir à pied plutôt qu'en voiture ?", "Que devrait savoir sur toi une bonne personne pour voyager à tes côtés ?",
    "Quelle vue aimerais-tu savourer sans appareil photo ?", "Comment passerais-tu un après-midi libre par mauvais temps en voyage ?",
    "Quelle idée de voyage as-tu repoussée uniquement à cause de l'organisation ?", "Qu'apprends-tu sur un lieu en allant dans un supermarché ?",
    "Quel moyen de transport te donne le plus le sentiment de partir à l'aventure ?", "Dans quelle ville étrangère pourrais-tu imaginer vivre quelque temps ?",
    "Quel est ton meilleur souvenir d'une excursion sans nuit sur place ?", "Quel type de musée pourrait te donner envie d'entrer spontanément ?",
    "Comment trouves-tu en voyage des endroits au-delà des sites touristiques évidents ?", "Sur quoi choisirais-tu de ne pas te renseigner avant un voyage ?",
    "Quel moment dans la nature t'a surpris pendant un voyage ?", "Quel voyage a démenti une de tes attentes ?",
    "Quelle serait ton escale idéale sur un long trajet ?", "En quoi ton rythme en vacances diffère-t-il de ton rythme quotidien ?",
    "Quel endroit aimerais-tu revoir à une autre saison ?", "Que signifie pour toi respecter un lieu que tu découvres ?",
    "Quelle brève rencontre de voyage aimerais-tu prolonger ?", "Quel serait un bel itinéraire pour une sortie avec ce groupe ?",
    "Quelle compétence t'a servi de façon inattendue en voyage ?", "Quelle expérience de voyage semble banale mais a été spéciale pour toi ?",
    "À quoi ressemblerait pour toi une journée de voyage sans billets d'entrée ?", "Quelle question poserais-tu à une personne qui a toujours vécu sur place ?",
  ],
  traeume: [
    "Quelle petite idée pour l'avenir te réjouit en ce moment ?", "Qu'aimerais-tu apprendre même sans jamais y exceller ?",
    "Comment aimerais-tu te sentir lors d'une journée ordinaire dans cinq ans ?", "Quel projet t'intéresserait même sans reconnaissance ?",
    "Quel genre de chez-toi aimerais-tu te créer à long terme ?", "Que ferais-tu d'un après-midi libre par semaine ?",
    "Quelle habitude aimerais-tu offrir à ton futur toi ?", "Quel souhait est devenu plus important en prenant de l'âge ?",
    "Quelle expérience aimerais-tu vivre pour la première fois ?", "Quelle compétence pourrait nettement faciliter ton quotidien ?",
    "Qu'aimerais-tu un jour fabriquer plutôt qu'acheter ?", "De quelles personnes aimerais-tu t'entourer davantage à l'avenir ?",
    "Quel projet demande surtout du courage plutôt que de l'argent ?", "Comment organiserais-tu une année durant laquelle personne ne juge ton CV ?",
    "Qu'aimerais-tu un jour apprendre à une personne plus jeune ?", "Qu'est-ce qui peut très bien rester comme c'est dans ta vie ?",
    "Quel projet commun aimerais-tu organiser avec des amis ?", "Qu'essaierais-tu si un échec n'avait aucune conséquence ?",
    "Quel type de travail pourrait encore te plaire plus tard dans la vie ?", "Que voudrais-tu pouvoir dire de toi un jour ?",
    "Quelle ancienne idée mérite une deuxième tentative ?", "À quoi ressemblerait ton lieu idéal pour une pause créative ?",
    "Quel souhait as-tu jusqu'ici très peu exprimé à voix haute ?", "Quel serait un premier pas réaliste vers un grand objectif ?",
    "Quelle tradition aimerais-tu lancer dans ton entourage ?", "De quoi aimerais-tu posséder moins pour gagner en liberté ?",
    "Quelle expérience aurait plus de valeur pour toi qu'un objet coûteux ?", "Comment aimerais-tu célébrer une grande réussite personnelle ?",
    "Quel genre d'aventure convient à la personne que tu es aujourd'hui ?", "À quoi aimerais-tu contribuer dans ton quartier ou ta région ?",
    "Quel rêve d'enfant te ferait encore plaisir aujourd'hui ?", "Comment saurais-tu que tu as suffisamment accompli ?",
    "Que voudrais-tu faire autrement l'hiver prochain ?", "Quel nouveau lien entre tes centres d'intérêt aimerais-tu découvrir ?",
    "De quoi aimerais-tu être fier plus tard, même si personne ne le voit ?", "Quel créneau libre aimerais-tu protéger dans ton agenda ?",
    "Qu'aimerais-tu un jour présenter devant un petit public ?", "Quel type de communauté aimerais-tu créer ou rejoindre ?",
    "Quelle pourrait être une bonne devise pour ta prochaine année de vie ?", "Quel objectif poursuivrais-tu sans te comparer aux autres ?",
    "Que voudrais-tu consciemment emporter ou laisser derrière toi lors de ton prochain déménagement ?", "Quel changement progressif aimerais-tu amorcer ?",
    "À qui aimerais-tu un jour rendre quelque chose ?", "Qu'est-ce qui vaudrait pour toi la peine de repartir de zéro ?",
    "Quel souvenir aimerais-tu encore créer avec ta famille ?", "Que ferais-tu d'une petite pièce vide ?",
    "Quelle qualité aimerais-tu conserver en vieillissant ?", "Que voudrais-tu célébrer plus souvent l'année prochaine ?",
    "Quel rêve pourrais-tu bientôt réaliser à plus petite échelle ?", "Quelle question encore ouverte sur ton avenir t'intéresse en ce moment ?",
  ],
  entscheidungen: [
    "Pour quelle décision une nuit de sommeil t'aide-t-elle vraiment ?", "Qu'est-ce qui est devenu plus important pour toi que de faire bonne impression ?",
    "Quand renoncerais-tu à la facilité au nom de l'équité ?", "Quelle décision préfères-tu prendre à l'intuition plutôt qu'avec une liste ?",
    "Que signifie réussir pour toi, en dehors de l'argent et du travail ?", "Quelle limite autour de ton temps aimerais-tu mieux protéger ?",
    "Sur quel sujet as-tu changé d'avis après un bon argument ?", "Qu'est-ce qui rend une promesse engageante pour toi ?",
    "Comment reconnais-tu qu'un compromis va trop loin pour toi ?", "Quelle petite décision influence ton humeur plus que prévu ?",
    "Quand l'honnêteté sans explication supplémentaire est-elle particulièrement importante ?", "Que préférerais-tu réparer même s'il était plus simple d'en racheter ?",
    "Quel genre de risque prends-tu volontiers ?", "Comment choisis-tu entre deux possibilités aussi bonnes l'une que l'autre ?",
    "Qu'est-ce qui rend une personne crédible à tes yeux ?", "Pour quoi aimerais-tu faire preuve de plus de patience au quotidien ?",
    "Quand un non peut-il être une décision bienveillante ?", "Quelle conviction aimerais-tu examiner toi-même de plus près ?",
    "Dans des excuses, qu'est-ce qui compte le plus pour toi : les mots ou les actes ?", "De combien d'incertitude as-tu besoin pour que la vie reste intéressante ?",
    "Quelle habitude confortable ne correspond pas tout à fait à tes valeurs ?", "Quand as-tu renoncé à de l'argent pour gagner du temps ?",
    "Que devrait-on partager même si cela nous appartient à nous seuls ?", "Quelle décision ne soumettrais-tu pas à un vote collectif ?",
    "Comment reconnais-tu un conseil qui te correspond vraiment ?", "Quelle différence fais-tu entre la générosité et le besoin de plaire ?",
    "Quelle petite chose mérite plus de reconnaissance qu'elle n'en reçoit ?", "Quand est-il plus raisonnable d'abandonner un projet commencé ?",
    "Sur quoi aimerais-tu décider plus consciemment dans ta consommation ?", "Quelle qualité compte plus à tes yeux qu'un talent impressionnant ?",
    "Comment gères-tu une décision dont l'erreur n'apparaît que plus tard ?", "Que préserverais-tu en premier avec un budget limité ?",
    "Quand une règle devrait-elle autoriser une exception justifiée ?", "Que signifie la responsabilité dans un logement partagé ?",
    "Quelle opinion défends-tu même sans l'accord de tes amis ?", "Qu'est-ce qui t'aide à ne pas repousser indéfiniment une décision ?",
    "Quand une conversation difficile vaut-elle plus que l'harmonie ?", "Quelle décision t'a donné de la liberté ?",
    "Que devrait-on savoir avant de juger la réussite des autres ?", "Jusqu'où l'organisation te rassure-t-elle, et quand devient-elle du contrôle ?",
    "Qu'est-ce qui rend une répartition des tâches équitable ?", "Quel type de compétition trouves-tu enrichissant ?",
    "Sur quoi ne prendrais-tu pas de raccourci, même lors d'une journée fatigante ?", "Quand est-il utile de rectifier publiquement son opinion ?",
    "Quelle occasion préférerais-tu refuser pour rester fidèle à toi-même ?", "Comment distingues-tu un vrai besoin d'une envie passagère ?",
    "Qu'est-ce qui peut surprendre les autres dans ton mode de vie ?", "Quelle décision prendrais-tu plus sereinement aujourd'hui qu'autrefois ?",
    "Comment sais-tu que tu as besoin d'une pause plutôt que d'une nouvelle solution ?", "Quel geste quotidien exprime le mieux tes valeurs ?",
  ],
  kreativ: [
    "Quelle pièce secrète installerais-tu dans une bibliothèque ?", "À quoi ressemblerait une fête du calendrier que tu pourrais inventer ?",
    "Quels deux métiers ordinaires formeraient un nouveau métier fantastique ?", "Qu'exposerait un musée consacré à ton quotidien actuel ?",
    "Quel superpouvoir ne serait utile que dans la maison ?", "À quoi ressemblerait une ville construite pour les oiseaux de nuit ?",
    "À quel objet donnerais-tu la parole pendant une journée ?", "Quelle serait une bonne scène d'ouverture pour un film sur ce groupe ?",
    "Quel nouveau sport pourrait-on inventer sans matériel ?", "À quoi ressemblerait un restaurant dont le menu serait classé par humeur ?",
    "Que laisserais-tu dans une capsule temporelle pour les gens dans cent ans ?", "Quelle couleur aurait un son que tu aimes ?",
    "Comment transformerais-tu une salle d'attente ennuyeuse en un lieu préféré ?", "Quelle capacité animale serait étonnamment pratique dans un bureau ?",
    "Quel serait le problème principal d'un monde où les pensées apparaissent en sous-titres ?", "Quel événement quotidien mérite sa propre bande-son ?",
    "À quoi ressemblerait la version amicale d'un monstre classique du cinéma ?", "Quelle invention une personne du Moyen Âge adorerait-elle immédiatement ?",
    "Que pourrait raconter un nuage dans son journal intime ?", "Comment aménagerais-tu un parc d'attractions sans manèges ?",
    "Quel animal imaginaire serait un bon compagnon de voyage en train ?", "Quel sixième sens serait utile au quotidien ?",
    "À quoi ressemblerait une enquête policière dans laquelle personne ne peut mentir ?", "Quelle monnaie inhabituelle fonctionnerait sur une île de cuisiniers ?",
    "Que placerais-tu sur une place de ville entièrement vide ?", "À quoi ressemblerait une maison de rêve si chaque pièce était une saison ?",
    "Quelle chose anodine serait un grand trésor dans ton monde imaginaire ?", "Quel serait un bon nom pour le vaisseau spatial de ce groupe ?",
    "Comment expliquerais-tu à un robot ce que signifie une ambiance douillette ?", "Quel personnage de conte aurait aujourd'hui besoin de changer de métier ?",
    "Que pourrait faire un ascenseur s'il avait sa propre journée de repos ?", "À quoi ressemblerait une école où la curiosité serait la seule matière ?",
    "Quelles seraient les trois règles d'un jeu qui se joue uniquement dans la tête ?", "Quel message serait le plus inhabituel, mais pertinent, dans un biscuit porte-bonheur ?",
    "Comment une ville changerait-elle si ses toits devenaient des jardins ?", "Quel mot manque pour désigner un sentiment que tu connais ?",
    "Que déduirait un détective de ton petit-déjeuner ?", "À quoi ressemblerait une exposition uniquement composée d'odeurs ?",
    "Quelle tâche un minuscule dragon domestique sympathique accomplirait-il chez toi ?", "Quel serait un mode d'emploi amusant pour un dimanche ?",
    "Comment organiserais-tu un voyage où une pièce décide de toutes les directions ?", "Quel miracle serait spectaculaire mais totalement peu pratique au quotidien ?",
    "Que pourrait raconter un livre qui choisit lui-même qui le lit ?", "Comment fonctionnerait une boutique qui vend des souvenirs vécus plutôt que des objets ?",
    "Quelle nouvelle épreuve conviendrait aux Jeux olympiques de la patience ?", "Quelle serait la première annonce dans une ville sous l'eau ?",
    "Comment appellerais-tu un jeu de société sur ton métier ou ton quotidien ?", "Quel message ton futur animal de compagnie t'écrirait-il ?",
    "Quelle serait une jolie mission pour un tout petit sortilège ?", "À quoi pourrait ressembler le générique de fin de cette soirée ?",
  ],
} as const;

export const TASKS = {
  eisbrecher: [
    "Présente-toi en trois phrases sans donner ton nom, ton métier ni ton lieu de résidence.", "Décris ton petit-déjeuner idéal comme une brève recommandation de restaurant.",
    "Explique au groupe une petite compétence que tu utilises souvent au quotidien.", "Cite trois choses qui ont été mieux que prévu aujourd'hui.",
    "Pose au groupe une question originale pour faire connaissance et réponds-y en premier.", "Décris un endroit préféré pour qu'on puisse l'imaginer sans en connaître le nom.",
    "Invente une formule de bienvenue chaleureuse qui convient à cette soirée.", "Fais une courte visite guidée d'un objet qui se trouve près de toi.",
    "Résume ta journée jusqu'ici en exactement six mots.", "Propose une activité commune que tu recommanderais à ce groupe pour un après-midi libre.",
  ],
  spass: [
    "Fais un court discours de remerciement très sérieux pour une chaussette perdue.", "Vends une cuillère invisible avec un slogan publicitaire complètement exagéré.",
    "Commente pendant dix secondes le fait de s'asseoir comme une finale sportive palpitante.", "Dis « La soupe est prête » comme une annonce dramatique de bande-annonce.",
    "Explique d'une voix sérieuse pourquoi les coussins méritent des vacances.", "Joue un bref dialogue entre un réveil et une personne fatiguée.",
    "Fais trois expressions différentes en découvrant un réfrigérateur étonnamment vide.", "Invente une appellation absurdement compliquée pour une chaise.",
    "Présente la météo de ton humeur actuelle avec un rebondissement ridicule.", "Explique en deux phrases pourquoi une banane devrait devenir maire.",
  ],
  party: [
    "Fredonne brièvement un indicatif que tu inventes pour cette soirée.", "Annonce la prochaine manche comme dans une petite émission de radio.",
    "Invente une boisson sans alcool avec un nom et trois ingrédients.", "En restant assis, montre un mouvement de danse simple avec seulement les épaules et les mains.",
    "Compose une mini-playlist : une chanson pour l'arrivée, une pour le moment fort et une pour le retour.", "Tape un petit rythme sur tes propres cuisses et répète-le.",
    "Invente une invitation à une fête au thème insolite mais chaleureux.", "Souhaite chaleureusement la bienvenue à une personne qui ne connaît personne ici.",
    "Décris un festival imaginaire avec une seule scène et un petit plus particulier.", "Porte un bref toast à quelque chose d'ordinaire, sans inviter quiconque à boire.",
  ],
  freundschaft: [
    "Fais un compliment sincère sur une qualité que tu apprécies dans ce groupe.", "Explique en deux phrases comment tu remonterais le moral d'un ami après une journée ratée.",
    "Prévois une sortie commune gratuite qui n'exclut personne.", "Invente un petit rituel pour garder le contact entre amis malgré la distance.",
    "Cite trois façons de proposer de l'aide sans s'imposer.", "Compose un message amical pour reprendre contact après un long silence ; n'envoie rien.",
    "Joue de courtes excuses sincères pour avoir manqué un rendez-vous entre amis.", "Trouve une image ou une comparaison qui représente une belle amitié.",
    "Cite une compétence pratique que tu pourrais proposer d'apprendre au groupe.", "Décris une petite tradition commune qui conviendrait à ce groupe.",
  ],
  liebe: [
    "Organise un premier rendez-vous détendu avec un budget de zéro euro.", "Formule un compliment sur l'attention portée aux autres plutôt que sur l'apparence.",
    "Joue la façon dont tu refuserais une invitation avec gentillesse et clarté.", "Invente une lettre d'amour d'une tasse de thé à son dessous de tasse.",
    "Cite trois petits gestes qui montrent de l'affection sans contact physique.", "Décris en deux phrases une façon respectueuse de proposer de se revoir.",
    "Invente un titre de film romantique sur deux personnes dans une file d'attente.", "Formule une phrase qui exprime une limite personnelle clairement et avec bienveillance.",
    "Présente une idée de dimanche à deux où chacun dispose aussi de temps pour soi.", "Imagine une courte déclaration d'amour à ton plat préféré et récite-la.",
  ],
  erinnerungen: [
    "Décris ta chambre d'enfant avec trois détails précis.", "Explique les règles d'un jeu que tu aimais dans ton enfance.",
    "Raconte un joli petit souvenir sous la forme d'une information radio en trois phrases.", "Cite trois choses de tes années d'école qui ont presque disparu aujourd'hui.",
    "Décris un ancien plat préféré sans le nommer ; le groupe peut deviner.", "Donne un conseil bienveillant à ton toi plus jeune en une seule phrase.",
    "Invente un titre adapté à l'album photo d'une belle période de ta vie.", "Montre avec tes mains la taille d'un objet qui te paraissait immense dans ton enfance.",
    "Raconte un petit défi de jeunesse auquel tu repenses aujourd'hui avec tendresse.", "Décris un souvenir uniquement avec des sensations : un bruit, une odeur et une couleur.",
  ],
  reisen: [
    "Fais une courte visite guidée de ton lieu de vie sans citer de sites touristiques.", "Prépare mentalement cinq objets pour une sortie improvisée et explique l'un de tes choix.",
    "Décris un paysage comme sur une carte postale en exactement trois phrases.", "Prévois une journée pluvieuse dans un lieu inconnu sans payer de billets d'entrée.",
    "Invente un conseil amical pour les voyageurs dans un village imaginaire.", "Présente un trajet en train de tes rêves avec trois arrêts très différents.",
    "Montre sans parler comment tu demanderais le chemin vers un café.", "Recommande au groupe une petite aventure qui pourrait se trouver à moins d'une heure.",
    "Décris un hébergement insolite où tu passerais une nuit.", "Invente un slogan touristique pour un endroit banal comme un parking ou un couloir.",
  ],
  traeume: [
    "Décris un souhait et un premier pas qui demande moins de dix minutes.", "Fais un court discours pour remercier ton futur toi d'une bonne nouvelle habitude.",
    "Invente le titre d'un cours que tu suivrais par pure curiosité.", "Décris avec des mots un matin ordinaire dans ton quotidien rêvé.",
    "Cite trois choses que tu aimerais apprendre sans devoir les maîtriser.", "Trouve une devise bienveillante pour ton mois à venir.",
    "Présente un projet commun que ce groupe pourrait commencer pendant un week-end.", "Explique un rêve d'enfant comme si tu le redécouvrais aujourd'hui.",
    "Invente une petite fête pour une réussite que personne d'autre ne remarquerait.", "Décris une capsule temporelle avec trois objets qui représentent bien ton toi actuel.",
  ],
  entscheidungen: [
    "Défends en deux phrases l'idée qu'une pause est une décision judicieuse.", "Propose une répartition équitable de trois corvées désagréables entre trois personnes.",
    "Donne une bonne raison de planifier et une raison tout aussi bonne d'improviser.", "Entraîne-toi à refuser poliment une invitation sans inventer d'excuse.",
    "Explique l'équité à un enfant imaginaire avec un exemple du quotidien.", "Cite un petit choix d'achat et une alternative potentiellement plus durable.",
    "Formule une phrase qui te permettrait de changer d'avis après un bon argument.", "Propose deux solutions équitables quand un groupe n'arrive pas à choisir un restaurant.",
    "Décris une règle personnelle qui facilite ton quotidien et une exception autorisée.", "Invente un bref message publicitaire pour la patience plutôt que pour un produit.",
  ],
  kreativ: [
    "Invente en trois phrases une histoire avec une clé, un nuage et une boulangerie.", "Donne à un objet de la pièce un superpouvoir et une faiblesse ridicule.",
    "Invente un mot pour la joie ressentie quand des projets fatigants sont annulés.", "Décris un monstre sympathique et son passe-temps préféré.",
    "Invente deux phrases de publicité pour un parapluie invisible.", "Joue une conversation entre le soleil et la lune avec deux voix différentes.",
    "Imagine une nouvelle fête du calendrier avec un nom et une tradition simple.", "Invente un titre de livre et une première phrase pour une histoire sur cette bouteille.",
    "Décris une pièce où seuls les meubles échappent à la gravité.", "Invente un minuscule sortilège qui résout exactement un petit problème inoffensif du quotidien.",
  ],
} as const;
