/** Volledige Nederlandse editie, in dezelfde volgorde als editorial-de.ts. */
export const QUESTIONS = {
  eisbrecher: [
    "Welke kleine luxe maakt een gewone dag voor jou beter?", "Wat valt gasten in jouw huis waarschijnlijk als eerste op?",
    "Bij welk onderwerp vergeet je tijdens het vertellen de tijd?", "Welke vaardigheid zou je meteen aan een nieuwe huisgenoot aanbieden?",
    "Hoe ziet jouw ideale vrije ochtend eruit?", "Welk eten bestel je als je niet kunt kiezen?",
    "Waaraan merken mensen dat je je prettig voelt in een groep?", "Welke activiteit brengt je verrassend betrouwbaar tot rust?",
    "Wat ligt er bij jou meestal binnen handbereik naast je bed?", "In welk onopvallend dingetje ben je verrassend goed?",
    "Welke geur doet je meteen aan een fijne plek denken?", "Hoe zou je jouw humor beschrijven aan iemand die je niet kent?",
    "Welk deel van je dagelijkse routine zou je graag aan een robot overlaten?", "Waar kijk je het liefst naar voorbijgangers?",
    "Welke app zou je als eerste op een nieuwe telefoon installeren?", "Met welk drankje begint voor jou een gezellige avond?",
    "Welk seizoen past het beste bij jouw temperament?", "Wat verzamel je zonder daar ooit bewust voor gekozen te hebben?",
    "Welk compliment hoor je bijzonder graag?", "Hoeveel planning heb jij nodig voor een fijne zondag?",
    "Van welk onschuldig kleinigheidje word je overdreven enthousiast?", "Bij welk bord- of kaartspel word je fanatiek?",
    "Wat zou je een bezoeker in jouw omgeving als eerste laten zien?", "Welke vraag wordt jou veel te weinig gesteld?",
    "Hoe kies je wat je hierna gaat lezen of kijken?", "Wat verraadt de tas die je nu gebruikt over je dagelijks leven?",
    "Van welk weer houd jij meer dan de meeste mensen?", "Welk dier past bij jouw energie op maandagochtend?",
    "Wat koop je liever tweedehands dan nieuw?", "Wat maakt een café voor jou goed?",
    "Welk huishoudelijk klusje doe je echt graag?", "Hoe beslis je of je op een uitnodiging ingaat?",
    "Wat zou een kleine verrassing zijn die echt bij je past?", "Van welk kledingstuk zou je moeilijk afscheid kunnen nemen?",
    "Aan welk geluid merk je dat je thuis bent?", "Wat wil je als eerste begrijpen van iemand die je net ontmoet?",
    "Welke maaltijd lukt jou ook zonder recept?", "Op welk moment van de dag ben je het meest alert?",
    "Wat mag voor jou absoluut niet ontbreken bij een picknick?", "Welk voorwerp bij jou in de buurt heeft een verhaal?",
    "Hoe besteed je tien onverwachte vrije minuten?", "Wat was je laatste echt goede spontane ingeving?",
    "Aan welk soort winkel kun je bijna niet voorbijlopen zonder even te kijken?", "Waardoor wil je een gesprek voortzetten?",
    "Welke gewoonte heb je van iemand anders overgenomen?", "Wat zou jij op je nemen tijdens een gezamenlijke kookavond?",
    "Welk woord gebruik je waarschijnlijk vaker dan anderen?", "Wat is voor jou een teken van goede gastvrijheid?",
    "Welke vraag zou je aan deze groep willen stellen?", "Wat moet iemand over je weten om een uitstapje met je te plannen?",
  ],
  spass: [
    "Welk volkomen onbelangrijk ding verdedig je met verrassend veel passie?", "Wat is de grappigste verspreking die je je van jezelf herinnert?",
    "Welke onschuldige regel heb je alleen voor jezelf bedacht?", "Bij welke activiteit geef je soms commentaar als een sportverslaggever?",
    "Welk filmpersonage zou voor jou een rampzalige huisgenoot zijn?", "Waarbij overschat je regelmatig je talent?",
    "Welk geluid kun je verrassend overtuigend nadoen?", "Welke gekke angst had je als kind?",
    "Wat zou de slechtst passende reclameslogan voor jouw dagelijks leven zijn?", "Welk klein ding raak je telkens op dezelfde absurde plek kwijt?",
    "Welk gerecht ziet er bij jou slechter uit dan het smaakt?", "Wanneer heb je voor het laatst om je eigen fout gelachen?",
    "Welke uitdrukking heb je lange tijd verkeerd begrepen?", "Wat zou je op een trofee voor je slechtste eigenschap zetten?",
    "Welke vreemde combinatie vind je echt lekker?", "Welk alledaags voorwerp zou het lastigst zijn als huisdier?",
    "Welke situatie laat je lachen, ook als je serieus wilt blijven?", "Wat was jouw onnodig ingewikkelde oplossing voor een simpel probleem?",
    "Welke fantasiewet zou jouw irritantste gewoonte verbieden?", "Van welk piepklein ongemak maak je in je hoofd een drama?",
    "Hoe zou een sitcom over jouw afgelopen maand heten?", "Welke zogenaamd coole fase van jezelf vind je achteraf bijzonder grappig?",
    "Wat is het vreemdste excuus dat je zelf bent gaan geloven?", "Bij welk technisch probleem verbaasde je jezelf het meest?",
    "Welk totaal nutteloos talent zou je in een sollicitatie vermelden?", "Welk meubelstuk zie jij wel een slecht humeur hebben?",
    "Van welk kleinigheidje maak jij een veel te grote ceremonie?", "Wat zou jouw ongewone artiestennaam in een goochelshow zijn?",
    "Welk onschuldig leugentje over het dagelijks leven zou makkelijk te doorzien zijn?", "Wat was jouw grappigste misverstand tijdens het winkelen?",
    "Bij welk eten zou volgens jou een handleiding moeten zitten?", "Welke rol zou je krijgen in een chaotische ruimteschipbemanning?",
    "Hoe klinkt je innerlijke stem als je iets in elkaar moet zetten?", "Wat vind je grappig terwijl je nauwelijks kunt uitleggen waarom?",
    "Wat zou de meest belachelijke aanleiding voor een felle burenruzie zijn?", "Welke alledaagse beweging ziet er bij jou onbedoeld elegant uit?",
    "Welk woord klinkt voor jou helemaal niet naar wat het betekent?", "Wat zou je koelkast over jou verklappen?",
    "Welke sport zou met kantoorartikelen het grappigst zijn?", "Wat was je grappigste moment met autocorrectie?",
    "Welk voorwerp van jou verdient een naam?", "Hoe zou je een saaie boodschap als een actiefilm navertellen?",
    "Welk belachelijk debat zou je toch twintig minuten kunnen bezighouden?", "Wat zou een verrassend eerlijke titel voor jouw kookboek zijn?",
    "Welke gewoonte van jou zou een buitenaards wezen verkeerd kunnen begrijpen?", "Welk dier zou als nieuwslezer het meest afleiden?",
    "Welke miskoop leverde tenminste nog een goed verhaal op?", "Welke gewoonte zou je bij een dubbelganger meteen herkennen?",
    "Welke gewone zin zou je als een dramatische filmwaarschuwing kunnen uitspreken?", "Wat was de grappigste verkeerde veronderstelling die iemand over jou had?",
  ],
  party: [
    "Welk nummer krijgt je ook na een lange dag in beweging?", "Wat onderscheidt een goed feest van een feest dat alleen maar luid is?",
    "Welk concert zou je graag nog eens voor het eerst beleven?", "Welke rol neem je op feestjes vanzelf op je?",
    "Welk thema zou jou echt naar een verkleedfeest lokken?", "Welk liedje verbind je met een bepaalde vriendschap?",
    "Hoe ziet jouw perfecte afsluiting van een lange avond eruit?", "Welk klein gebaar maakt een gastheer of gastvrouw onvergetelijk?",
    "Bij welk lied ken je alleen het refrein en zing je toch mee?", "Wat was je beste gesprek buiten de dansvloer?",
    "Welk instrument zou je in een band willen spelen?", "Welk feest verraste je positief terwijl je er eigenlijk geen zin in had?",
    "Wat moet er op een buffet staan om jou tevreden te maken?", "Welk muziekgenre ben je pas laat gaan waarderen?",
    "Hoe zou je nieuwe mensen op een feest met elkaar in gesprek brengen?", "Welke artiest zou je kiezen voor een piepklein huiskamerconcert?",
    "Wat is je fijnste herinnering aan een festival?", "Welk nummer zou tijdens jouw persoonlijke aftiteling moeten klinken?",
    "Welke feesttraditie zou je zonder moeite afschaffen?", "Wat vind je op een feest belangrijker: bekende gezichten of nieuwe ontmoetingen?",
    "Welke muziektip uit je omgeving sloeg bij jou echt aan?", "Hoe zou je met heel weinig geld een verjaardag bijzonder maken?",
    "Welke dansbeweging voelt voor jou altijd goed?", "Wat zou het onderwerp van jouw eigen radioprogramma zijn?",
    "Welk feest zou je liever buiten dan binnen organiseren?", "Welk liedje doet je aan een lange rit denken?",
    "Wat was de creatiefste uitnodiging die je hebt gekregen?", "Welke drie dingen hebben gasten nodig om zich snel prettig te voelen?",
    "Welk nummer zou je iemand laten horen om jouw stemming uit te leggen?", "Wat maakt een gezamenlijke spelletjesavond voor jou geslaagd?",
    "Welke mening over muziek deel je met bijna niemand?", "Welk ongewoon hapje zou bij een pauze rond middernacht passen?",
    "Hoe merk je dat het tijd is om naar huis te gaan?", "Wat zou je op een feest liever zelf doen dan laten regelen?",
    "Welke songtekst is je bijzonder bijgebleven?", "Welke verjaardagsverrassing zou je eerder overweldigen?",
    "Welk geluid in een liveopname vind je heerlijk?", "Voor welk feest heb jij helemaal geen aanleiding nodig?",
    "Wat zou voor jou de ideale lengte van een gezamenlijke playlist zijn?", "Welke muziek zet je op bij het opruimen na bezoek?",
    "Wat was een mooi moment op een bruiloft buiten de ceremonie om?", "Welke plek zou ongewoon maar gezellig zijn voor een klein feest?",
    "Hoe zou je een feest zonder luidsprekers interessant maken?", "Welk album beluister je liever helemaal dan nummer voor nummer?",
    "Wat is de beste gespreksopening aan een tafel met onbekenden?", "Welke muzikale ontdekking zou je graag met de groep delen?",
    "Hoe zou een feest eruitzien dat precies bij jouw energieniveau past?", "Welke herinnering verbind je aan een bepaalde dans?",
    "Wat wil je bij je volgende feest bewust anders doen?", "Welke titel zou de playlist van deze avond krijgen?",
  ],
  freundschaft: [
    "Waaraan merkte je dat een kennis een vriend was geworden?", "Welk klein gebaar van vrienden betekent bijzonder veel voor je?",
    "Wat kun je met vrienden doen zonder veel te hoeven praten?", "Hoe houd je contact met mensen die ver weg wonen?",
    "Welke eigenschap van je vrienden heeft jou zelf veranderd?", "Wat is een goede manier om na lang stilzwijgen weer contact te zoeken?",
    "Welke gezamenlijke pech heeft jullie dichter bij elkaar gebracht?", "Hoe laat je een vriend merken dat je echt luistert?",
    "Wat zou je met een vriend proberen, maar niet alleen?", "Welke traditie mag in een vriendschap nooit een verplichting worden?",
    "Wanneer was je bijzonder trots op iemand uit je vriendenkring?", "Hoeveel spontaniteit past er in jouw plannen met vrienden?",
    "Wat waardeer je aan vrienden die heel anders zijn dan jij?", "Welke ondersteuning bied je makkelijk aan?",
    "Hoe kan iemand je eerlijk tegenspreken zonder dat je dichtklapt?", "Welk gezamenlijk uitstapje herinner je je bijzonder levendig?",
    "Wat maakt excuses tussen vrienden voor jou goed?", "Van wat voor bericht word je op een gewone dag blij?",
    "Waarover zou je een vriend om raad vragen in plaats van het internet?", "Welke grens in vriendschappen is belangrijk voor je geworden?",
    "Welke gezamenlijke activiteit brengt verschillende mensen goed bij elkaar?", "Hoe merk je dat iemand juist gezelschap nodig heeft in plaats van advies?",
    "Wat was het meest attente cadeau uit je vriendenkring?", "Welke vriendschap ontstond op een onverwachte plek?",
    "Hoe verandert je manier van praten bij je beste vrienden?", "Wat moet iemand niet persoonlijk nemen als die met jou bevriend is?",
    "Welke eigenschap maakt iemand een fijne reisgenoot?", "Wat zou je voorstellen als jullie samen een uurtje vrij hadden?",
    "Welke herinnering zou je graag met een oude vriend vergelijken?", "Hoe vier je kleine successen van je vrienden?",
    "Wat helpt je om na een meningsverschil weer toenadering te vinden?", "Welk gezamenlijk project zou jullie vriendschap kunnen verrijken?",
    "Wat hebben vrienden je over jezelf geleerd?", "Welke hulp vind je moeilijk om aan te nemen?",
    "Hoe belangrijk vind je op tijd komen in een vriendschap?", "Welk onschuldig onderonsje kun je aan de groep uitleggen?",
    "Wat zou je aan een vriend ook na jaren meteen herkennen?", "Wanneer vind je samen stil zijn prettig?",
    "Waardoor voelt een nieuw persoon zich welkom in een bestaande groep?", "Welke vriendschap zou je vaker aandacht willen geven in je dagelijks leven?",
    "Wat is voor jou het verschil tussen loyaliteit en blind instemmen?", "Welke activiteit werkt beter met vrienden dan met familie?",
    "Hoe zou je een vriend na een teleurstellende dag opvrolijken?", "Welke gezamenlijke gewoonte mis je soms?",
    "Waaraan merken mensen dat je tijd voor jezelf nodig hebt?", "Welke verrassende overeenkomst bracht je dichter bij iemand?",
    "Wat is een goede aanleiding om een vriend gewoon eens te bedanken?", "Hoe ga je ermee om dat je met de ene vriend hechter bent dan met de andere?",
    "Welke vaardigheid van een vriend bewonder je stiekem of openlijk?", "Wat zou je als vriend voortaan bewuster willen doen?",
  ],
  liebe: [
    "Door welke vorm van aandacht voel je je gezien?", "Wat maakt een eerste afspraakje voor jou ontspannen?",
    "Welk klein alledaags tafereel vind je romantisch?", "Hoe merk je dat je iemand kunt vertrouwen?",
    "Wat zou je bij het kennismaken liever persoonlijk dan via de chat vertellen?", "Welke eigenschap wordt voor jou met de tijd aantrekkelijker?",
    "Wat betekent verbondenheid voor jou buiten aanrakingen om?", "Hoe zou iemand moeten reageren als jij een grens aangeeft?",
    "Welke gezamenlijke gewoonte zou een relatie kunnen verrijken?", "Wat zou een leuke date zijn die bijna niets kost?",
    "Hoe toon je genegenheid als je de juiste woorden niet kunt vinden?", "Welk beeld van romantiek past helemaal niet bij je?",
    "Wat zou je graag vroeg over het dagelijks leven van een partner weten?", "Wat voor humor helpt jou bij het flirten?",
    "Wanneer voel je je tijdens een gesprek bijzonder verbonden?", "Wat heb je nodig om zelfstandig te blijven in een relatie?",
    "Welke vraag zegt bij het kennismaken meer dan iemands beroep?", "Hoe ga je ermee om als iemand anders veel meer rust nodig heeft?",
    "Welk compliment zou je op een date oprecht blij maken?", "Wat is voor jou een goed teken na een meningsverschil?",
    "Welke gezamenlijke ervaring zegt veel over hoe je met elkaar omgaat?", "Hoe belangrijk zijn vergelijkbare hobby's voor een relatie?",
    "Wat zou een liefdesbrief voor jou persoonlijk maken?", "Van welke verrassingen houd je in relaties?",
    "Wat moet in een relatie regelmatig hardop gezegd worden?", "Hoe herken je respectvolle belangstelling in plaats van opdringerig gedrag?",
    "Hoe zou je een gezamenlijke vrije dag zonder schermen invullen?", "Welk kleinigheidje kan je zenuwen bij een afspraakje wegnemen?",
    "Wat is voor jou het verschil tussen verliefdheid en vertrouwdheid?", "Welke relatie in een film vind je geloofwaardig?",
    "Hoeveel gezamenlijke planning voelt voor jou prettig?", "Wat zou een attent gebaar in een langeafstandsrelatie zijn?",
    "Wat voor gesprek voer je liever tijdens het wandelen?", "Hoe wil je aangesproken worden als iets je zichtbaar bezighoudt?",
    "Wat heb je over je eigen behoeften bijgeleerd?", "Welke eigenschap maakt iemand een goede luisteraar op een date?",
    "Hoe kun je genegenheid tonen zonder geld uit te geven?", "Wat is een gezonde manier om verschillende interesses te hebben?",
    "Welke gezamenlijke beslissing mag niemand in zijn eentje nemen?", "Wat betekent betrouwbaarheid voor jou heel concreet?",
    "Hoe ga je op een eerlijke manier om met verschillende energieniveaus?", "Wat voor gesprek wil je nooit even tussendoor voeren?",
    "Wat kan een stel van goede vriendschappen leren?", "Welke kleine traditie zou je graag met z'n tweeën proberen?",
    "Hoe belangrijk vind je het dat je omgeving je partner goed kent?", "Wat is een charmante manier om belangstelling te tonen zonder druk te leggen?",
    "Welke grens heb je bij openbare liefdesuitingen?", "Waaraan zou je merken dat een relatie je goeddoet?",
    "Wat wil je als eerste doen als je elkaar na lange tijd weer ziet?", "Welk beeld van een goede relatie is bij jou veranderd?",
  ],
  erinnerungen: [
    "Welk klein detail uit je jeugd kun je nog precies beschrijven?", "Welke route naar school is je bijzonder bijgebleven?",
    "Wat was het eerste zelfgekochte voorwerp waar je trots op was?", "Welke keuken verbind je met een gevoel van geborgenheid?",
    "Welk spel kon je vroeger urenlang spelen?", "Wat was een onverwacht fijne regendag?",
    "Welke volwassene nam jou als kind serieus?", "Welk vakantieritueel zou je graag nieuw leven inblazen?",
    "Wat was je eerste bewuste succes buiten school?", "Welke plek ken je nu alleen nog uit je herinneringen?",
    "Welk verhaal werd bij jou in de familie vaak verteld?", "Wat was je grappigste poging om volwassen over te komen?",
    "Welke vroegere passie zou je nu weer kunnen grijpen?", "Welk tafereel uit je vroegere buurt is je bijgebleven?",
    "Wat kon je als kind beter dan nu?", "Welk cadeau verraste je destijds helemaal?",
    "Hoe zag je favoriete terugtrekplek er vroeger uit?", "Welke eerste ontmoeting herinner je je ongewoon precies?",
    "Wat was een klein dapper moment in je jeugd?", "Welk uitstapje liep anders dan gepland en werd toch fijn?",
    "Wie heeft je een praktische vaardigheid geleerd?", "Welk eten was vroeger bijzonder en is nu heel gewoon?",
    "Welke foto zou je graag nog eens willen maken?", "Welke oude gewoonte van je familie begrijp je nu beter?",
    "Wat onderschatte je toen je voor het eerst op jezelf woonde?", "Welk geluid mis je uit een eerdere levensfase?",
    "Welk afscheid bleek later een mooi begin te zijn?", "Welke schoolles is je om een verrassende reden bijgebleven?",
    "Welk voorwerp heeft meerdere verhuizingen met je meegemaakt?", "Wat heb je met je eerste zelfverdiende geld gedaan?",
    "Welke persoon van vroeger zou je willen vragen hoe die een herinnering heeft beleefd?", "Wat was je eerste grote misvatting over de wereld van volwassenen?",
    "Welk verjaardagsfeest uit je jeugd is je bijgebleven?", "Wat verzamelde je vroeger en waarom?",
    "Welke film was voor jou destijds een echte gebeurtenis?", "Wanneer vond je voor het eerst zelfstandig je weg in een nieuwe stad?",
    "Welke kleine traditie uit je schooltijd vond je leuk?", "Welk onverwacht compliment herinner je je nog?",
    "Welke voorbereiding op een reis hoorde vroeger voor jou al bij de vakantie?", "Wat zou je jouw jongere ik over vriendschap vertellen?",
    "Welke geur brengt je in gedachten terug naar een bepaald seizoen?", "Van welk alledaags moment besefte je pas later de betekenis?",
    "Welk vroeger lievelingskledingstuk zou je nu weer dragen?", "Welke verandering in je geboorteplaats verrast je?",
    "Welke herinnering zou je graag als een kleine filmscène vastleggen?", "Welke gezamenlijke lachbui is je tot vandaag bijgebleven?",
    "Wat verraste je toen je voor het eerst alleen reisde?", "Welke vroege beslissing heeft onverwacht veel veranderd?",
    "Welke oude brief of welk briefje heb je met een goede reden bewaard?", "Wat zal je waarschijnlijk vooral bijblijven van je huidige levensfase?",
  ],
  reisen: [
    "Wat bekijk je als eerste op een nieuwe plek?", "Welke reis werd mooier doordat er iets ongepland bleef?",
    "Wat is voor jou persoonlijk het teken dat de vakantie is begonnen?", "Welke plek in je omgeving heb je nog nooit goed verkend?",
    "Van welk soort landschap word je meteen rustig?", "Wat hoort in jouw bagage terwijl anderen het overbodig vinden?",
    "Welk gesprek onderweg is je bijzonder bijgebleven?", "Hoe bepaal je of een reisbestemming bij je past?",
    "Wat zou je doen met een dag alleen in een onbekende stad?", "Welke maaltijd van een reis zou je graag zelf namaken?",
    "Wat maakt voor jou een goede raamplaats in de trein?", "Welke dagelijkse gewoonte op een andere plek heeft indruk op je gemaakt?",
    "Waar zou je naartoe gaan als de heenreis onderdeel van het avontuur moest zijn?", "Welk verblijf is je door de mensen bijgebleven?",
    "Hoe oriënteer je je het liefst in een stad?", "Welk souvenir gebruik je echt in je dagelijks leven?",
    "Hoe lang duurt het voordat je je ergens nieuw thuis voelt?", "Welke reis zou je graag in een heel rustig tempo maken?",
    "Wat heb je onderweg over je eigen verwachtingen geleerd?", "Welke plek ziet er in je herinnering heel anders uit dan op foto's?",
    "Met welke kleine tegenslag op reis kun je inmiddels rustig omgaan?", "Wat zou je iemand laten zien die jouw land voor het eerst bezoekt?",
    "Welke taal zou je graag spreken om ter plekke gesprekken te voeren?", "Hoe belangrijk vind je het dat je reisplannen kunt veranderen?",
    "Wat vind je het fijnste aan thuiskomen?", "Welke markt of winkel maakte je onderweg bijzonder nieuwsgierig?",
    "Welke route zou je liever te voet dan met de auto beleven?", "Wat moet een fijne reisgenoot over jou weten?",
    "Van welk uitzicht zou je graag zonder camera genieten?", "Hoe zou je op reis een vrije middag bij slecht weer doorbrengen?",
    "Welk reisidee heb je tot nu toe alleen vanwege de planning uitgesteld?", "Wat leer je over een plek door een supermarkt te bezoeken?",
    "Welk vervoermiddel voelt voor jou het meest avontuurlijk?", "Welke buitenlandse stad zou je je als tijdelijk thuis kunnen voorstellen?",
    "Wat is je mooiste herinnering aan een uitstapje zonder overnachting?", "Welk soort museum zou je ook spontaan naar binnen trekken?",
    "Hoe vind je op reis plekken buiten de voor de hand liggende bezienswaardigheden?", "Wat zou je voor een reis bewust niet vooraf uitzoeken?",
    "Welk moment in de natuur heeft je onderweg verrast?", "Welke reis heeft een verwachting van jou ontkracht?",
    "Wat zou je ideale tussenstop tijdens een lange rit zijn?", "Hoe verschilt je vakantietempo van je dagelijkse tempo?",
    "Welke plek zou je graag in een ander seizoen terugzien?", "Wat betekent het voor jou om respectvol met een onbekende plek om te gaan?",
    "Welke vluchtige ontmoeting op reis zou je graag voortzetten?", "Wat zou een mooie route zijn voor een uitstapje met deze groep?",
    "Welke vaardigheid heeft je onderweg onverwacht geholpen?", "Welke ervaring klinkt onopvallend maar was op reis bijzonder?",
    "Hoe ziet een reisdag zonder toegangskaartjes er voor jou uit?", "Welke vraag zou je stellen aan iemand die daar altijd heeft gewoond?",
  ],
  traeume: [
    "Op welk klein toekomstidee verheug je je op dit moment?", "Wat zou je graag leren, ook als je er nooit bijzonder goed in wordt?",
    "Hoe moet een gewone dag over vijf jaar voor jou voelen?", "Welk project zou je ook zonder erkenning interesseren?",
    "Wat voor thuis wil je op lange termijn voor jezelf creëren?", "Wat zou je doen met één vrije middag per week?",
    "Welke gewoonte wil je aan je toekomstige ik cadeau doen?", "Welke wens is belangrijker voor je geworden naarmate je ouder werd?",
    "Wat zou je graag voor het eerst meemaken?", "Welke vaardigheid zou je dagelijks leven merkbaar makkelijker maken?",
    "Wat wil je ooit zelf maken in plaats van kopen?", "Welke mensen wil je in de toekomst vaker om je heen hebben?",
    "Welk plan vraagt eerder om moed dan om geld?", "Hoe zou je een jaar invullen waarin niemand je cv beoordeelt?",
    "Wat zou je ooit aan een jonger iemand willen leren?", "Wat mag in je leven gerust blijven zoals het is?",
    "Welk gezamenlijk plan zou je graag met vrienden maken?", "Wat zou je proberen als mislukken geen gevolgen had?",
    "Wat voor werk zou je ook later nog plezier kunnen geven?", "Wat wil je ooit over jezelf kunnen zeggen?",
    "Welk oud idee verdient bij jou een tweede poging?", "Hoe zou jouw ideale plek voor een creatieve pauze eruitzien?",
    "Welke wens heb je tot nu toe nauwelijks hardop uitgesproken?", "Wat zou een realistische eerste stap naar een groot doel zijn?",
    "Welke traditie wil je in je omgeving beginnen?", "Waarvan zou je minder willen bezitten om vrijer te zijn?",
    "Welke ervaring zou je meer waard zijn dan een duur voorwerp?", "Hoe wil je een groot persoonlijk succes vieren?",
    "Welk soort avontuur past bij wie je nu bent?", "Waaraan zou je in jouw omgeving graag willen meewerken?",
    "Welke wens uit je kindertijd zou je vandaag nog blij maken?", "Hoe zou je herkennen dat je genoeg hebt bereikt?",
    "Wat wil je volgende winter anders doen dan tot nu toe?", "Welke nieuwe verbinding tussen je interesses zou je graag ontdekken?",
    "Waar wil je later trots op terugkijken, ook al ziet niemand het?", "Welke vrije ruimte in je agenda zou je graag beschermen?",
    "Wat zou je ooit voor een klein publiek willen laten zien?", "Wat voor gemeenschap zou je graag oprichten of vinden?",
    "Wat zou een goed motto voor je volgende levensjaar zijn?", "Welk doel zou je nastreven zonder jezelf met anderen te vergelijken?",
    "Wat wil je bij je volgende verhuizing bewust meenemen of achterlaten?", "Welke geleidelijke verandering zou je graag in gang zetten?",
    "Aan wie zou je ooit iets willen teruggeven?", "Wat zou voor jou een goede reden zijn om opnieuw beginner te worden?",
    "Welke herinnering wil je nog met je familie maken?", "Wat zou je met een leegstaand klein kamertje doen?",
    "Welke eigenschap wil je behouden als je ouder wordt?", "Wat wil je volgend jaar vaker vieren?",
    "Welke droom zou je binnenkort in een kleinere versie kunnen waarmaken?", "Welke open vraag over je toekomst vind je nu spannend?",
  ],
  entscheidungen: [
    "Bij welke beslissing helpt een nachtje slapen je echt?", "Wat is voor jou belangrijker geworden dan een goede eerste indruk?",
    "Wanneer zou je gemak opgeven om eerlijk te zijn?", "Welke beslissing neem je liever op gevoel dan met een lijstje?",
    "Wat betekent succes voor jou buiten geld en werk?", "Welke grens rond je tijd zou je beter willen beschermen?",
    "Waarover heb je na een goed argument je mening veranderd?", "Wat maakt een belofte voor jou bindend?",
    "Hoe merk je dat een compromis voor jou te ver gaat?", "Welke kleine beslissing heeft meer invloed op je stemming dan verwacht?",
    "Wanneer is eerlijkheid zonder verdere uitleg bijzonder belangrijk?", "Wat zou je liever repareren, ook als nieuw kopen makkelijker is?",
    "Wat voor risico neem je graag?", "Hoe kies je tussen twee even goede mogelijkheden?",
    "Wat maakt iemand geloofwaardig in jouw ogen?", "Waarvoor zou je in het dagelijks leven meer geduld willen opbrengen?",
    "Wanneer kan nee zeggen een vriendelijke beslissing zijn?", "Welke overtuiging van jezelf zou je nog beter willen onderzoeken?",
    "Wat vind je bij excuses belangrijker: woorden of gedrag?", "Hoeveel onzekerheid heb je nodig om het leven spannend te houden?",
    "Welke gemakkelijke gewoonte past niet helemaal bij je waarden?", "Wanneer heb je geld opgegeven om tijd te winnen?",
    "Wat zou je moeten delen, ook als het alleen van jou is?", "Welke beslissing zou je niet met een groepsstemming nemen?",
    "Hoe herken je advies dat echt bij je past?", "Wat is voor jou het verschil tussen vrijgevigheid en graag aardig gevonden willen worden?",
    "Welk kleinigheidje verdient meer waardering dan het krijgt?", "Wanneer is het verstandiger om een begonnen plan los te laten?",
    "Waarover wil je als consument bewuster beslissen?", "Welke eigenschap weegt voor jou zwaarder dan indrukwekkend talent?",
    "Hoe ga je om met een beslissing die pas later verkeerd blijkt?", "Wat zou je bij een beperkt budget als eerste beschermen?",
    "Wanneer moet een regel ruimte laten voor een goede uitzondering?", "Wat betekent verantwoordelijkheid in een gedeeld huis?",
    "Welke mening houd je ook zonder instemming van je vrienden?", "Wat helpt je om een beslissing niet eindeloos uit te stellen?",
    "Wanneer is een moeilijk gesprek meer waard dan harmonie?", "Welke beslissing heeft je vrijheid gegeven?",
    "Wat moet iemand weten voordat die over het succes van anderen oordeelt?", "Hoeveel planning geeft jou zekerheid en wanneer wordt het controle?",
    "Wat maakt een taakverdeling eerlijk?", "Wat voor competitie vind je verrijkend?",
    "Waarop zou je ook op een vermoeiende dag niet beknibbelen?", "Wanneer is het nuttig om je eigen mening openbaar te corrigeren?",
    "Welke kans zou je liever laten liggen om trouw aan jezelf te blijven?", "Hoe onderscheid je een echte behoefte van een tijdelijke wens?",
    "Wat mag andere mensen aan jouw levensstijl verrassen?", "Welke beslissing zou je nu rustiger nemen dan vroeger?",
    "Waaraan merk je dat je een pauze nodig hebt in plaats van een nieuwe oplossing?", "Welke dagelijkse handeling drukt jouw waarden het beste uit?",
  ],
  kreativ: [
    "Welke geheime kamer zou je in een bibliotheek bouwen?", "Hoe zou een feestdag eruitzien die je zelf mag bedenken?",
    "Welke twee gewone beroepen zouden samen één fantastisch nieuw beroep vormen?", "Wat zou een museum over jouw dagelijks leven van nu tentoonstellen?",
    "Welke superkracht zou alleen in het huishouden nuttig zijn?", "Hoe zou een stad eruitzien die voor nachtmensen is gebouwd?",
    "Welk voorwerp zou je één dag een stem geven?", "Wat zou een goede openingsscène voor een film over deze groep zijn?",
    "Welke nieuwe sport kun je zonder spullen bedenken?", "Hoe zou een restaurant eruitzien waar de menukaart op stemming is ingedeeld?",
    "Wat zou je in een tijdcapsule achterlaten voor mensen over honderd jaar?", "Welke kleur zou een geluid hebben dat je fijn vindt?",
    "Hoe zou je een saaie wachtruimte veranderen in een favoriete plek?", "Welke dierlijke vaardigheid zou op kantoor verrassend handig zijn?",
    "Wat zou het grootste probleem zijn in een wereld waar alle gedachten als ondertitels verschijnen?", "Welke alledaagse gebeurtenis verdient een eigen soundtrack?",
    "Hoe zou een vriendelijke versie van een klassiek filmmonster eruitzien?", "Welke uitvinding zou iemand uit de middeleeuwen meteen geweldig vinden?",
    "Wat zou een wolk in zijn dagboek kunnen schrijven?", "Hoe zou je een pretpark zonder bewegende attracties inrichten?",
    "Welk fantasiedier zou een fijne metgezel zijn op een treinreis?", "Wat zou een nuttig zesde zintuig voor het dagelijks leven zijn?",
    "Hoe zou een detectiveverhaal eruitzien waarin niemand kan liegen?", "Welke ongewone munt zou werken op een eiland vol koks?",
    "Wat zou je op een volledig leeg stadsplein zetten?", "Hoe zou een droomhuis eruitzien als elke kamer een seizoen was?",
    "Welk onschuldig ding zou in jouw verzonnen wereld een grote schat zijn?", "Wat zou een goede naam voor het ruimteschip van deze groep zijn?",
    "Hoe zou je een robot uitleggen wat gezelligheid betekent?", "Welk sprookjesfiguur zou vandaag dringend van beroep moeten veranderen?",
    "Wat zou een lift doen als die een eigen vrije dag had?", "Hoe zou een school eruitzien waar nieuwsgierigheid het enige vak is?",
    "Welke drie regels zou een spel hebben dat je alleen in je hoofd speelt?", "Wat zou de ongewoonste maar zinvolle boodschap in een gelukskoekje zijn?",
    "Hoe zou een stad veranderen als daken tuinen werden?", "Welk nieuw woord ontbreekt voor een gevoel dat jij kent?",
    "Wat zou een detective uit jouw ontbijt over je afleiden?", "Hoe zou een tentoonstelling eruitzien die alleen uit geuren bestaat?",
    "Welke taak zou een piepkleine vriendelijke huisdraak bij jou op zich nemen?", "Wat zou een grappige gebruiksaanwijzing voor een zondag zijn?",
    "Hoe zou je een reis plannen waarbij een munt alle richtingen bepaalt?", "Welk wonder zou spectaculair zijn maar in het dagelijks leven totaal onhandig?",
    "Wat zou een boek kunnen vertellen dat zelf zijn lezer uitkiest?", "Hoe zou een winkel werken die herinneringen verkoopt in plaats van spullen?",
    "Welke nieuwe discipline zou bij de Olympische Spelen van het geduld passen?", "Wat zou de eerste omroepboodschap in een onderwaterstad zijn?",
    "Hoe zou je een bordspel over jouw beroep of dagelijks leven noemen?", "Welk bericht zou je toekomstige huisdier je schrijven?",
    "Wat zou een mooie opdracht voor een heel kleine toverspreuk zijn?", "Hoe zou de aftiteling van deze avond eruit kunnen zien?",
  ],
} as const;

export const TASKS = {
  eisbrecher: [
    "Stel jezelf in drie zinnen voor zonder je naam, beroep of woonplaats te noemen.", "Beschrijf jouw perfecte ontbijt als een korte restaurantaanbeveling.",
    "Leg de groep een kleine vaardigheid uit die je vaak in het dagelijks leven gebruikt.", "Noem drie dingen die vandaag beter waren dan verwacht.",
    "Stel de groep een ongewone kennismakingsvraag en beantwoord die eerst zelf.", "Beschrijf een favoriete plek zo dat je die voor je ziet zonder de plaatsnaam te kennen.",
    "Bedenk een vriendelijke begroeting die bij deze avond past.", "Geef een korte rondleiding door een voorwerp dat bij je in de buurt ligt.",
    "Vat je dag tot nu toe samen in precies zes woorden.", "Noem een gezamenlijke activiteit die je deze groep voor een vrije middag zou aanraden.",
  ],
  spass: [
    "Houd een korte, serieuze dankrede voor een verloren sok.", "Verkoop een onzichtbare lepel met een totaal overdreven reclameslogan.",
    "Geef tien seconden commentaar op zitten alsof het een spannende sportfinale is.", "Zeg 'De soep is klaar' als een dramatische filmaankondiging.",
    "Leg met een serieuze stem uit waarom kussens vakantie verdienen.", "Voer een kort gesprek op tussen een wekker en een moe persoon.",
    "Trek drie verschillende gezichten bij een verrassend lege koelkast.", "Bedenk een absurd omslachtige naam voor een stoel.",
    "Geef een weersverwachting voor je huidige stemming met een gekke wending.", "Leg in twee zinnen uit waarom een banaan burgemeester zou moeten worden.",
  ],
  party: [
    "Neurie kort een zelfbedachte herkenningsmelodie voor deze avond.", "Kondig de volgende ronde aan alsof je een klein radioprogramma presenteert.",
    "Bedenk een alcoholvrij drankje met een naam en drie ingrediënten.", "Laat zittend een eenvoudige dansbeweging zien met alleen je schouders en handen.",
    "Stel een mini-playlist samen: één lied voor de aankomst, één voor het hoogtepunt en één voor de terugweg.", "Tik een kort ritme op je eigen bovenbenen en herhaal het.",
    "Bedenk een uitnodiging voor een feest met een ongewoon maar gezellig thema.", "Heet een gast die hier niemand kent hartelijk welkom.",
    "Beschrijf een verzonnen festival met maar één podium en één bijzonder extraatje.", "Breng een korte toost uit op iets alledaags, zonder iemand te vragen te drinken.",
  ],
  freundschaft: [
    "Geef een eerlijk compliment over een eigenschap die je aan deze groep waardeert.", "Leg in twee zinnen uit hoe je een vriend na een mislukte dag zou opvrolijken.",
    "Plan een gezamenlijk uitstapje dat niets kost en niemand buitensluit.", "Bedenk een klein ritueel waarmee vrienden ondanks afstand contact kunnen houden.",
    "Noem drie manieren om hulp aan te bieden zonder je op te dringen.", "Formuleer een vriendelijk bericht om na lange stilte weer contact te zoeken; verstuur niets.",
    "Speel een korte, oprechte verontschuldiging voor een gemiste afspraak voor.", "Bedenk een beeld of vergelijking voor wat goede vriendschap inhoudt.",
    "Noem een praktische vaardigheid die je de groep vrijwillig zou kunnen leren.", "Beschrijf een kleine gezamenlijke traditie die bij deze groep past.",
  ],
  liebe: [
    "Plan een ontspannen eerste date met een budget van nul euro.", "Geef een compliment over aandacht voor anderen in plaats van uiterlijk.",
    "Speel voor hoe je een uitnodiging vriendelijk en duidelijk zou afslaan.", "Bedenk een liefdesbrief van een theekopje aan zijn onderzetter.",
    "Noem drie kleine gebaren waarmee je zonder lichamelijk contact genegenheid kunt tonen.", "Beschrijf in twee zinnen een respectvolle manier om een nieuwe afspraak voor te stellen.",
    "Bedenk een romantische filmtitel over twee mensen in een wachtrij.", "Formuleer een zin waarmee je een persoonlijke grens duidelijk en vriendelijk aangeeft.",
    "Stel een gezamenlijke zondag voor waarbij allebei ook tijd voor zichzelf krijgen.", "Bedenk een korte liefdesverklaring aan je favoriete eten en draag die voor.",
  ],
  erinnerungen: [
    "Beschrijf je vroegere kinderkamer met drie concrete details.", "Leg de regels uit van een spel dat je als kind graag speelde.",
    "Vertel een fijne kleine herinnering als een radiobericht in drie zinnen.", "Noem drie dingen uit je schooltijd die tegenwoordig bijna verdwenen zijn.",
    "Beschrijf vroeger lievelingseten zonder de naam te noemen; de groep mag raden.", "Geef je jongere ik in één zin een vriendelijk advies.",
    "Bedenk een passende titel voor het fotoalbum van een mooie levensperiode.", "Laat met je handen zien hoe groot een voorwerp was dat je als kind enorm vond.",
    "Vertel over een vroegere kleine uitdaging waarvoor moed nodig was en waar je nu vriendelijk op terugkijkt.", "Beschrijf een herinnering alleen met zintuiglijke indrukken: geluid, geur en kleur.",
  ],
  reisen: [
    "Geef een korte rondleiding door je woonplaats zonder bezienswaardigheden te noemen.", "Pak in gedachten vijf dingen in voor een spontaan dagje uit en leg één keuze uit.",
    "Beschrijf een landschap als een ansichtkaart in precies drie zinnen.", "Plan een regendag op een onbekende plek zonder entreegeld uit te geven.",
    "Bedenk een vriendelijke tip voor reizigers in een denkbeeldig dorp.", "Presenteer je droomtreinroute met drie heel verschillende haltes.",
    "Laat zonder woorden zien hoe je de weg naar een café zou vragen.", "Raad de groep een klein avontuur aan dat binnen een uur bereikbaar zou kunnen zijn.",
    "Beschrijf een ongewone accommodatie waar je één nacht zou willen slapen.", "Bedenk een reisslogan voor een onopvallende plek zoals een parkeerplaats of gang.",
  ],
  traeume: [
    "Beschrijf een wens en een eerste stap die minder dan tien minuten kost.", "Houd een korte dankrede aan je toekomstige ik voor een goede nieuwe gewoonte.",
    "Bedenk de titel van een cursus die je uit pure nieuwsgierigheid zou volgen.", "Schilder met woorden een gewone ochtend in jouw ideale dagelijks leven.",
    "Noem drie dingen die je ooit wilt leren zonder ze te hoeven beheersen.", "Formuleer een vriendelijk motto voor je komende maand.",
    "Presenteer een gezamenlijk toekomstproject dat deze groep in een weekend zou kunnen beginnen.", "Leg een wens uit je kindertijd uit alsof je die vandaag opnieuw ontdekt.",
    "Bedenk een klein feestje voor een succes dat verder niemand zou opmerken.", "Beschrijf een tijdcapsule met drie dingen die je huidige ik goed vertegenwoordigen.",
  ],
  entscheidungen: [
    "Verdedig in twee zinnen een pauze als een verstandige beslissing.", "Bedenk een eerlijke verdeling van drie vervelende huishoudelijke taken over drie personen.",
    "Noem een goede reden voor planning en een even goede reden voor spontaniteit.", "Oefen vriendelijk nee zeggen tegen een uitnodiging zonder een excuus te verzinnen.",
    "Leg een denkbeeldig kind met een alledaags voorbeeld uit wat rechtvaardigheid betekent.", "Noem een kleine aankoopkeuze en een mogelijk duurzamer alternatief.",
    "Formuleer een zin waarmee je na een goed argument van mening zou kunnen veranderen.", "Stel twee eerlijke oplossingen voor als een groep het niet eens wordt over een restaurant.",
    "Beschrijf een persoonlijke regel die je dagelijks leven makkelijker maakt en één toegestane uitzondering.", "Bedenk een korte reclameboodschap voor geduld in plaats van voor een product.",
  ],
  kreativ: [
    "Bedenk in drie zinnen een verhaal met een sleutel, een wolk en een bakkerij.", "Geef een voorwerp in de kamer een superkracht en een gekke zwakte.",
    "Bedenk een nieuw woord voor de blijdschap als vermoeiende plannen worden afgezegd.", "Beschrijf een vriendelijk monster en zijn favoriete bezigheid.",
    "Bedenk twee regels voor een reclamespot over een onzichtbare paraplu.", "Speel met twee verschillende stemmen een gesprek tussen de zon en de maan.",
    "Bedenk een nieuwe feestdag met een naam en een eenvoudige traditie.", "Bedenk een boektitel en de eerste zin van een verhaal over deze fles.",
    "Beschrijf een kamer waar de zwaartekracht alleen voor meubels niet geldt.", "Bedenk een piepkleine toverspreuk die precies één onschuldig alledaags probleem oplost.",
  ],
} as const;
