// Original German special cards from Git HEAD; order preserved, obvious spelling errors corrected.
import type { BottleCard, CategoryMeta } from "./bottlespin-content-de";

export const CATEGORY_META: Record<string, CategoryMeta> = {
  "jga": {
    "name": "JGA",
    "emoji": "💍",
    "color": "#ec4899"
  },
  "erwachsene": {
    "name": "Erwachsene 18+",
    "emoji": "🔥",
    "color": "#f97316"
  }
};

export const BOTTLE_CARDS: BottleCard[] = [
  {"text":"Erzähle die lustigste Geschichte über die Braut/den Bräutigam.","type":"frage","category":"jga"},
  {"text":"Rufe eine zufällige Person an und gratuliere zur Hochzeit.","type":"aufgabe","category":"jga"},
  {"text":"Was glaubst du, wird das Brautpaar in 10 Jahren machen?","type":"frage","category":"jga"},
  {"text":"Schreibe der Braut/dem Bräutigam eine peinliche Nachricht.","type":"aufgabe","category":"jga"},
  {"text":"Was war der erste Eindruck, den du vom Partner der Braut/des Bräutigams hattest?","type":"frage","category":"jga"},
  {"text":"Lerne einen Hochzeitstanz-Move und führe ihn vor.","type":"aufgabe","category":"jga"},
  {"text":"Wer hat bei der Hochzeitsankündigung am meisten geweint?","type":"frage","category":"jga"},
  {"text":"Mach ein Foto, das aussieht wie ein Hochzeits-Shooting.","type":"aufgabe","category":"jga"},
  {"text":"Was ist der beste Eheratschlag, den du geben könntest?","type":"frage","category":"jga"},
  {"text":"Halte eine Mini-Hochzeitsrede für das Brautpaar.","type":"aufgabe","category":"jga"},
  {"text":"Erzähle die peinlichste gemeinsame Erinnerung mit der Braut/dem Bräutigam.","type":"frage","category":"jga"},
  {"text":"Geh zu einem Fremden und lade ihn zur Hochzeit ein.","type":"aufgabe","category":"jga"},
  {"text":"Was würdest du dem Brautpaar als Hochzeitsgeschenk machen?","type":"frage","category":"jga"},
  {"text":"Mach ein Glückwunschvideo – 15 Sekunden.","type":"aufgabe","category":"jga"},
  {"text":"Welches Lied beschreibt die Beziehung des Brautpaars am besten?","type":"frage","category":"jga"},
  {"text":"Finde einen Fremden, der \"Ja, ich will!\" sagt, und nimm es auf.","type":"aufgabe","category":"jga"},
  {"text":"Was ist das Nervigste, das die Braut/der Bräutigam macht?","type":"frage","category":"jga"},
  {"text":"Organisiere ein spontanes Gruppenfoto mit allen.","type":"aufgabe","category":"jga"},
  {"text":"Wie hat die Braut/der Bräutigam vom Antrag erzählt?","type":"frage","category":"jga"},
  {"text":"Schreibe dem Brautpaar auf eine Serviette eine Prophezeiung für die Ehe.","type":"aufgabe","category":"jga"},
  {"text":"Was wünschst du dir für die Ehe des Brautpaars?","type":"frage","category":"jga"},
  {"text":"Sammle innerhalb von 2 Minuten 5 Unterschriften von Fremden auf einer Serviette.","type":"aufgabe","category":"jga"},
  {"text":"Was war der lustigste Fail der Braut/des Bräutigams?","type":"frage","category":"jga"},
  {"text":"Sing \"Going to the Chapel\" oder ein Hochzeitslied laut vor.","type":"aufgabe","category":"jga"},
  {"text":"Was hat die Braut/der Bräutigam gesagt, als du zum ersten Mal von der Verlobung erfuhrst?","type":"frage","category":"jga"},
  {"text":"Mach ein Foto mit einem Fremden und beschrifte es mit \"Hochzeitsgast\".","type":"aufgabe","category":"jga"},
  {"text":"Wer sollte auf der Hochzeit auf keinen Fall die Rede halten? Und warum?","type":"frage","category":"jga"},
  {"text":"Bitte drei Leute um einen Ehetipp und schreibe sie auf.","type":"aufgabe","category":"jga"},
  {"text":"Was war die Braut/der Bräutigam als Teenager für ein Typ?","type":"frage","category":"jga"},
  {"text":"Mach einen Antrag – auf den Knien – vor der ganzen Gruppe.","type":"aufgabe","category":"jga"},
  {"text":"Was glaubst du, wer auf der Hochzeit am meisten weinen wird?","type":"frage","category":"jga"},
  {"text":"Beschreibe deinen schlechtesten Kuss.","type":"frage","category":"erwachsene"},
  {"text":"Wem aus der Runde würdest du eine Nachricht um 2 Uhr nachts schicken?","type":"frage","category":"erwachsene"},
  {"text":"Was ist die gewagteste Sache, die du je gemacht hast?","type":"frage","category":"erwachsene"},
  {"text":"Zeige den letzten Flirt-Chat auf deinem Handy.","type":"aufgabe","category":"erwachsene"},
  {"text":"Was ist dein größter Turn-off?","type":"frage","category":"erwachsene"},
  {"text":"Gib der Person links neben dir ein Kompliment, das sie erröten lässt.","type":"aufgabe","category":"erwachsene"},
  {"text":"Was ist das Verführerischste, das jemand jemals zu dir gesagt hat?","type":"frage","category":"erwachsene"},
  {"text":"Mach dein bestes \"Flirt-Gesicht\" und halte es 10 Sekunden.","type":"aufgabe","category":"erwachsene"},
  {"text":"Was war dein peinlichstes Date-Erlebnis?","type":"frage","category":"erwachsene"},
  {"text":"Flüster der Person rechts neben dir etwas Freches ins Ohr.","type":"aufgabe","category":"erwachsene"},
  {"text":"Hast du schon mal jemanden aus dieser Runde attraktiv gefunden?","type":"frage","category":"erwachsene"},
  {"text":"Schicke einer Person deiner Wahl eine freche Nachricht – zeige sie der Runde.","type":"aufgabe","category":"erwachsene"},
  {"text":"Was ist dein ungewöhnlichster Crush?","type":"frage","category":"erwachsene"},
  {"text":"Lass die Person gegenüber dir eine Nachricht von deinem Handy lesen.","type":"aufgabe","category":"erwachsene"},
  {"text":"Was ist das Wildeste, das du auf einer Party erlebt hast?","type":"frage","category":"erwachsene"},
  {"text":"Erzähle die Geschichte deines ersten Kusses.","type":"aufgabe","category":"erwachsene"},
  {"text":"Wenn du mit einer berühmten Person ausgehen könntest – wer wäre es?","type":"frage","category":"erwachsene"},
  {"text":"Mach einen verführerischen Blick in die Kamera und schick das Bild an die Gruppe.","type":"aufgabe","category":"erwachsene"},
  {"text":"Was war der seltsamste Ort, an dem du jemals geküsst hast?","type":"frage","category":"erwachsene"},
  {"text":"Erzähle ein Geheimnis, das hier niemand kennt.","type":"aufgabe","category":"erwachsene"},
  {"text":"Was ist dein Lieblingsfilm, den du nie öffentlich zugeben würdest?","type":"frage","category":"erwachsene"},
  {"text":"Beiß dir auf die Lippe und schau 5 Sekunden der Person gegenüber in die Augen.","type":"aufgabe","category":"erwachsene"},
  {"text":"Hast du schon mal jemanden geghosted? Warum?","type":"frage","category":"erwachsene"},
  {"text":"Zeige das letzte Bild, das du in deiner Galerie gespeichert hast.","type":"aufgabe","category":"erwachsene"},
  {"text":"Was ist das Romantischste, das je jemand für dich getan hat?","type":"frage","category":"erwachsene"},
  {"text":"Schreibe blind eine freche Nachricht und schicke sie an den letzten Kontakt.","type":"aufgabe","category":"erwachsene"},
  {"text":"Wer hier ist am ehesten der Heartbreaker-Typ?","type":"frage","category":"erwachsene"},
  {"text":"Mach 5 Liegestütze und stöhn dabei dramatisch.","type":"aufgabe","category":"erwachsene"},
  {"text":"Was würdest du tun, wenn dein Ex gerade reinkäme?","type":"frage","category":"erwachsene"},
  {"text":"Setze dich für die nächste Runde auf den Schoß der Person links neben dir.","type":"aufgabe","category":"erwachsene"},
  {"text":"Was ist die frechste Nachricht, die du je erhalten hast?","type":"frage","category":"erwachsene"},
  {"text":"Nenne drei Dinge, die die Braut/der Bräutigam NICHT kann!","type":"frage","category":"jga"},
  {"text":"Mach ein Bild, auf dem alle wie ein Brautpaar posieren!","type":"aufgabe","category":"jga"},
  {"text":"Was würdest du in deiner Hochzeitsrede über das Brautpaar sagen?","type":"frage","category":"jga"},
  {"text":"Überrede einen Fremden, ein Foto mit der Gruppe zu machen!","type":"aufgabe","category":"jga"},
  {"text":"Was ist die lustigste Eigenschaft der Braut/des Bräutigams?","type":"frage","category":"jga"},
  {"text":"Sing ein Liebeslied für das Brautpaar!","type":"aufgabe","category":"jga"},
  {"text":"Was war der erste Streit zwischen Braut und Bräutigam?","type":"frage","category":"jga"},
  {"text":"Schreibe dem Brautpaar eine Liebeserklärung auf eine Serviette!","type":"aufgabe","category":"jga"},
  {"text":"Wer kennt die Braut/den Bräutigam am längsten?","type":"frage","category":"jga"},
  {"text":"Mache ein Video mit Glückwünschen von einem Fremden!","type":"aufgabe","category":"jga"},
  {"text":"Was ist der romantischste Moment des Brautpaars?","type":"frage","category":"jga"},
  {"text":"Erfinde einen Hochzeitstanz — alle tanzen mit!","type":"aufgabe","category":"jga"},
  {"text":"Welcher Film beschreibt die Beziehung des Brautpaars?","type":"frage","category":"jga"},
  {"text":"Finde etwas Blaues, Altes, Neues und Geliehenes!","type":"aufgabe","category":"jga"},
  {"text":"Was darf auf der Hochzeit auf KEINEN Fall passieren?","type":"frage","category":"jga"},
  {"text":"Rufe die Braut/den Bräutigam an und sag: Wir vermissen dich!","type":"aufgabe","category":"jga"},
  {"text":"Was wird das Brautpaar als Erstes nach der Hochzeit machen?","type":"frage","category":"jga"},
  {"text":"Schreibe einen Ehevertrag — mit lustigen Klauseln!","type":"aufgabe","category":"jga"},
  {"text":"Was ist die größte Macke der Braut/des Bräutigams?","type":"frage","category":"jga"},
  {"text":"Baue ein Hochzeitsbouquet aus dem, was du findest!","type":"aufgabe","category":"jga"},
  {"text":"Was würde die Braut/der Bräutigam NIEMALS tun?","type":"frage","category":"jga"},
  {"text":"Nimm ein Video auf, in dem alle \"Ja, ich will!\" rufen!","type":"aufgabe","category":"jga"},
  {"text":"Was war das beste Geschenk, das die Braut/der Bräutigam je bekommen hat?","type":"frage","category":"jga"},
  {"text":"Improvisiere eine Hochzeitsrede — max. 1 Minute!","type":"aufgabe","category":"jga"},
  {"text":"Welches Tier wäre die Braut/der Bräutigam und warum?","type":"frage","category":"jga"},
  {"text":"Mache ein Foto, das wie ein Filmposter aussieht!","type":"aufgabe","category":"jga"},
  {"text":"Was sollte das Brautpaar UNBEDINGT auf der Hochzeit spielen?","type":"frage","category":"jga"},
  {"text":"Sammle 3 Ehetipps von Passanten!","type":"aufgabe","category":"jga"},
  {"text":"Was war der peinlichste Moment der Braut/des Bräutigams?","type":"frage","category":"jga"},
  {"text":"Mach ein Gruppenherz-Foto!","type":"aufgabe","category":"jga"},
  {"text":"Was war der schlechteste Anmachspruch, den du je gehört hast?","type":"frage","category":"erwachsene"},
  {"text":"Gib der Person gegenüber dein bestes Kompliment!","type":"aufgabe","category":"erwachsene"},
  {"text":"Was war dein größter Dating-Fail?","type":"frage","category":"erwachsene"},
  {"text":"Flirte mit der Person links von dir — 15 Sekunden!","type":"aufgabe","category":"erwachsene"},
  {"text":"Was ist dein Lieblings-Flirtspruch?","type":"frage","category":"erwachsene"},
  {"text":"Mach dein bestes Modelgesicht für ein Foto!","type":"aufgabe","category":"erwachsene"},
  {"text":"Was war der romantischste Ort, an dem du je warst?","type":"frage","category":"erwachsene"},
  {"text":"Schreibe der 5. Person in deinen Kontakten ein Kompliment!","type":"aufgabe","category":"erwachsene"},
  {"text":"Was ist das Gewagteste, das du je auf einem Date gemacht hast?","type":"frage","category":"erwachsene"},
  {"text":"Mach ein verrücktes Selfie mit der Person gegenüber!","type":"aufgabe","category":"erwachsene"},
  {"text":"Wer hier hat die verführerischste Stimme?","type":"frage","category":"erwachsene"},
  {"text":"Flüster der Person rechts etwas Freches ins Ohr!","type":"aufgabe","category":"erwachsene"},
  {"text":"Was würdest du bei einem perfekten Date machen?","type":"frage","category":"erwachsene"},
  {"text":"Schau 10 Sekunden der Person gegenüber tief in die Augen!","type":"aufgabe","category":"erwachsene"},
  {"text":"Was ist die seltsamste Dating-App-Erfahrung?","type":"frage","category":"erwachsene"},
  {"text":"Gib jedem in der Runde einen Flirt-Spitznamen!","type":"aufgabe","category":"erwachsene"},
  {"text":"Was ist dein größter Turn-on?","type":"frage","category":"erwachsene"},
  {"text":"Erzähle deinen besten Anmachspruch — und benutze ihn!","type":"aufgabe","category":"erwachsene"},
  {"text":"Was ist das Romantischste, das dir je passiert ist?","type":"frage","category":"erwachsene"},
  {"text":"Mach eine dramatische Liebesszene — alleine!","type":"aufgabe","category":"erwachsene"},
  {"text":"Wer hier wäre der beste Filmküsser?","type":"frage","category":"erwachsene"},
  {"text":"Schicke der letzten Person ein Herz-Emoji!","type":"aufgabe","category":"erwachsene"},
  {"text":"Was war dein peinlichster Flirt-Moment?","type":"frage","category":"erwachsene"},
  {"text":"Mach dein bestes Flirt-Gesicht — halte es 10 Sekunden!","type":"aufgabe","category":"erwachsene"},
  {"text":"Welcher Promi wäre dein perfektes Date?","type":"frage","category":"erwachsene"},
  {"text":"Sing der Person links ein Liebeslied!","type":"aufgabe","category":"erwachsene"},
  {"text":"Was war der beste Kuss deines Lebens?","type":"frage","category":"erwachsene"},
  {"text":"Mach eine Liebeserklärung an dein Lieblingsessen!","type":"aufgabe","category":"erwachsene"},
  {"text":"Was würdest du für die große Liebe aufgeben?","type":"frage","category":"erwachsene"},
  {"text":"Lass die Gruppe ein Date für dich planen!","type":"aufgabe","category":"erwachsene"},
];
