export const TEXTS = [
  "Conta a história mais engraçada sobre a noiva ou o noivo.",
  "Liga a uma pessoa ao acaso e dá-lhe os parabéns pelo casamento.",
  "O que achas que os noivos estarão a fazer daqui a dez anos?",
  "Escreve uma mensagem embaraçosa à noiva ou ao noivo.",
  "Qual foi a tua primeira impressão do parceiro da noiva ou do noivo?",
  "Aprende um passo de dança de casamento e mostra-o.",
  "Quem chorou mais quando foi anunciado o casamento?",
  "Tira uma fotografia que pareça uma sessão fotográfica de casamento.",
  "Qual é o melhor conselho sobre casamento que poderias dar?",
  "Faz um pequeno discurso de casamento para os noivos.",
  "Conta a recordação partilhada mais embaraçosa com a noiva ou o noivo.",
  "Aproxima-te de um desconhecido e convida-o para o casamento.",
  "O que darias aos noivos como presente de casamento?",
  "Grava um vídeo de felicitações de quinze segundos.",
  "Que música descreve melhor a relação dos noivos?",
  "Encontra um desconhecido que diga «Sim, aceito!» e grava-o.",
  "Qual é a coisa mais irritante que a noiva ou o noivo faz?",
  "Organiza uma fotografia de grupo espontânea com toda a gente.",
  "Como contou a noiva ou o noivo o pedido de casamento?",
  "Escreve num guardanapo uma profecia para o casamento dos noivos.",
  "O que desejas para o casamento dos noivos?",
  "Recolhe cinco assinaturas de desconhecidos num guardanapo em dois minutos.",
  "Qual foi a asneira mais engraçada da noiva ou do noivo?",
  "Canta em voz alta «Going to the Chapel» ou uma música de casamento.",
  "O que disse a noiva ou o noivo quando soubeste do noivado pela primeira vez?",
  "Tira uma fotografia com um desconhecido e escreve «Convidado do casamento».",
  "Quem não deveria fazer o discurso no casamento de maneira nenhuma? E porquê?",
  "Pede a três pessoas um conselho sobre casamento e anota-os.",
  "Como era a noiva ou o noivo na adolescência?",
  "Faz um pedido de casamento de joelhos à frente de todo o grupo.",
  "Quem achas que vai chorar mais no casamento?",
  "Descreve o teu pior beijo.",
  "A quem deste grupo enviarias uma mensagem às duas da manhã?",
  "Qual foi a coisa mais ousada que alguma vez fizeste?",
  "Mostra a última conversa de flirt no teu telemóvel.",
  "O que mais te faz perder a atração por alguém?",
  "Faz um elogio à pessoa à tua esquerda que a faça corar.",
  "Qual foi a coisa mais sedutora que alguém te disse?",
  "Faz a tua melhor expressão de flirt e mantém-na durante dez segundos.",
  "Qual foi a tua experiência mais embaraçosa num encontro?",
  "Sussurra algo atrevido ao ouvido da pessoa à tua direita.",
  "Alguma vez achaste alguém deste grupo atraente?",
  "Envia uma mensagem atrevida a uma pessoa à tua escolha e mostra-a ao grupo.",
  "Qual foi a tua paixoneta mais invulgar?",
  "Deixa a pessoa à tua frente ler uma mensagem do teu telemóvel.",
  "Qual foi a coisa mais louca que viveste numa festa?",
  "Conta a história do teu primeiro beijo.",
  "Se pudesses sair com uma pessoa famosa, quem seria?",
  "Faz um olhar sedutor para a câmara e envia a fotografia ao grupo.",
  "Qual foi o sítio mais estranho onde beijaste alguém?",
  "Conta um segredo que ninguém aqui saiba.",
  "Qual é o teu filme preferido que nunca admitirias em público?",
  "Morde o lábio e olha nos olhos da pessoa à tua frente durante cinco segundos.",
  "Alguma vez deixaste de responder a alguém sem dar explicações? Porquê?",
  "Mostra a última imagem que guardaste na tua galeria.",
  "Qual foi o gesto mais romântico que alguém fez por ti?",
  "Escreve sem olhar uma mensagem atrevida e envia-a ao último contacto.",
  "Quem aqui tem mais ar de partir corações?",
  "Faz cinco flexões e geme de forma dramática enquanto as fazes.",
  "O que farias se o teu ex entrasse agora?",
  "Senta-te ao colo da pessoa à tua esquerda durante a próxima ronda.",
  "Qual foi a mensagem mais atrevida que alguma vez recebeste?",
  "Diz três coisas que a noiva ou o noivo NÃO sabe fazer!",
  "Tira uma fotografia em que todos posem como um casal de noivos!",
  "O que dirias sobre os noivos no teu discurso de casamento?",
  "Convence um desconhecido a tirar uma fotografia com o grupo!",
  "Qual é a característica mais engraçada da noiva ou do noivo?",
  "Canta uma canção de amor para os noivos!",
  "Qual foi a primeira discussão entre a noiva e o noivo?",
  "Escreve uma declaração de amor aos noivos num guardanapo!",
  "Quem conhece a noiva ou o noivo há mais tempo?",
  "Grava um vídeo com os votos de felicidades de um desconhecido!",
  "Qual é o momento mais romântico dos noivos?",
  "Inventa uma dança de casamento e todos dançam contigo!",
  "Que filme descreve a relação dos noivos?",
  "Encontra algo azul, algo velho, algo novo e algo emprestado!",
  "O que NÃO pode acontecer de maneira nenhuma no casamento?",
  "Liga à noiva ou ao noivo e diz: «Temos saudades tuas!»",
  "O que farão os noivos logo depois do casamento?",
  "Escreve um contrato de casamento com cláusulas engraçadas!",
  "Qual é a maior mania da noiva ou do noivo?",
  "Faz um ramo de noiva com o que encontrares!",
  "O que a noiva ou o noivo NUNCA faria?",
  "Grava um vídeo em que todos gritam «Sim, aceito!»",
  "Qual foi o melhor presente que a noiva ou o noivo recebeu?",
  "Improvisa um discurso de casamento de um minuto, no máximo!",
  "Que animal seria a noiva ou o noivo e porquê?",
  "Tira uma fotografia que pareça o cartaz de um filme!",
  "O que deveriam os noivos pôr a tocar SEM FALTA no casamento?",
  "Recolhe três conselhos sobre casamento de pessoas que passam!",
  "Qual foi o momento mais embaraçoso da noiva ou do noivo?",
  "Tirem uma fotografia a formar um coração em grupo!",
  "Qual foi a pior frase de engate que alguma vez ouviste?",
  "Faz o teu melhor elogio à pessoa à tua frente!",
  "Qual foi o teu maior desastre num encontro?",
  "Flirta com a pessoa à tua esquerda durante quinze segundos!",
  "Qual é a tua frase preferida para seduzir?",
  "Faz a tua melhor expressão de modelo para uma fotografia!",
  "Qual foi o lugar mais romântico onde estiveste?",
  "Escreve um elogio à quinta pessoa dos teus contactos!",
  "Qual foi a coisa mais ousada que fizeste num encontro?",
  "Tira uma selfie disparatada com a pessoa à tua frente!",
  "Quem aqui tem a voz mais sedutora?",
  "Diz algo atrevido baixinho ao ouvido da pessoa da direita!",
  "O que farias num encontro perfeito?",
  "Olha profundamente nos olhos da pessoa à tua frente durante dez segundos!",
  "Qual foi a tua experiência mais estranha numa aplicação de encontros?",
  "Dá a cada pessoa do grupo uma alcunha de flirt!",
  "O que mais te desperta o desejo?",
  "Diz a tua melhor frase de engate e usa-a!",
  "Qual foi a coisa mais romântica que te aconteceu?",
  "Representa uma cena de amor dramática, a sós!",
  "Quem aqui daria os melhores beijos de cinema?",
  "Envia um emoji de coração à última pessoa!",
  "Qual foi o teu momento de flirt mais embaraçoso?",
  "Mostra a tua melhor cara de flirt e aguenta dez segundos!",
  "Que celebridade seria o teu par perfeito para um encontro?",
  "Canta uma canção de amor à pessoa à tua esquerda!",
  "Qual foi o melhor beijo da tua vida?",
  "Faz uma declaração de amor à tua comida preferida!",
  "De que abdicarias pelo grande amor da tua vida?",
  "Deixa o grupo planear um encontro para ti!",
];
