export const TEXTS = [
  "Racconta la storia più divertente sulla sposa o sullo sposo.",
  "Chiama una persona a caso e falle gli auguri per il matrimonio.",
  "Cosa pensi che faranno gli sposi tra dieci anni?",
  "Scrivi un messaggio imbarazzante alla sposa o allo sposo.",
  "Qual è stata la tua prima impressione del partner della sposa o dello sposo?",
  "Impara un passo di ballo da matrimonio e mostralo.",
  "Chi ha pianto di più all'annuncio del matrimonio?",
  "Scatta una foto che sembri un servizio fotografico di nozze.",
  "Qual è il miglior consiglio sul matrimonio che potresti dare?",
  "Fai un breve discorso di nozze per gli sposi.",
  "Racconta il ricordo più imbarazzante che condividi con la sposa o lo sposo.",
  "Avvicinati a uno sconosciuto e invitalo al matrimonio.",
  "Cosa regaleresti agli sposi per il matrimonio?",
  "Gira un video di auguri di quindici secondi.",
  "Quale canzone descrive meglio la relazione degli sposi?",
  "Trova uno sconosciuto che dica «Sì, lo voglio!» e registralo.",
  "Qual è la cosa più fastidiosa che fa la sposa o lo sposo?",
  "Organizza una foto di gruppo improvvisata con tutti.",
  "Come ha raccontato la proposta di matrimonio la sposa o lo sposo?",
  "Scrivi su un tovagliolo una profezia sul matrimonio degli sposi.",
  "Cosa auguri agli sposi per la loro vita matrimoniale?",
  "Raccogli cinque firme di sconosciuti su un tovagliolo in due minuti.",
  "Qual è stata la figuraccia più divertente della sposa o dello sposo?",
  "Canta ad alta voce «Going to the Chapel» o una canzone da matrimonio.",
  "Cosa ha detto la sposa o lo sposo quando hai saputo per la prima volta del fidanzamento ufficiale?",
  "Scatta una foto con uno sconosciuto e aggiungi la scritta «Invitato al matrimonio».",
  "Chi non dovrebbe assolutamente tenere il discorso al matrimonio? E perché?",
  "Chiedi a tre persone un consiglio sul matrimonio e annotali.",
  "Che tipo era la sposa o lo sposo da adolescente?",
  "Fai una proposta di matrimonio in ginocchio davanti a tutto il gruppo.",
  "Chi pensi che piangerà di più al matrimonio?",
  "Descrivi il tuo bacio peggiore.",
  "A chi di questo gruppo manderesti un messaggio alle due di notte?",
  "Qual è la cosa più audace che hai mai fatto?",
  "Mostra l'ultima conversazione di flirt sul tuo telefono.",
  "Cosa ti fa passare di più l'attrazione per qualcuno?",
  "Fai alla persona alla tua sinistra un complimento che la faccia arrossire.",
  "Qual è la cosa più seducente che qualcuno ti abbia mai detto?",
  "Fai la tua migliore espressione da flirt e mantienila per dieci secondi.",
  "Qual è stata la tua esperienza più imbarazzante a un appuntamento?",
  "Sussurra qualcosa di provocante all'orecchio della persona alla tua destra.",
  "Hai mai trovato attraente qualcuno di questo gruppo?",
  "Manda un messaggio provocante a una persona a tua scelta e mostralo al gruppo.",
  "Qual è la tua cotta più insolita?",
  "Lascia che la persona di fronte a te legga un messaggio dal tuo telefono.",
  "Qual è la cosa più folle che hai vissuto a una festa?",
  "Racconta la storia del tuo primo bacio.",
  "Se potessi uscire con una persona famosa, chi sceglieresti?",
  "Guarda la fotocamera in modo seducente e manda la foto al gruppo.",
  "Qual è il posto più strano in cui hai mai baciato qualcuno?",
  "Racconta un segreto che qui non conosce nessuno.",
  "Qual è il tuo film preferito che non ammetteresti mai in pubblico?",
  "Morditi il labbro e guarda negli occhi la persona di fronte a te per cinque secondi.",
  "Hai mai smesso di rispondere a qualcuno senza spiegazioni? Perché?",
  "Mostra l'ultima immagine salvata nella tua galleria.",
  "Qual è il gesto più romantico che qualcuno abbia mai fatto per te?",
  "Scrivi senza guardare un messaggio provocante e invialo all'ultimo contatto.",
  "Chi qui ha più l'aria di uno spezzacuori?",
  "Fai cinque piegamenti e gemi in modo teatrale mentre li fai.",
  "Cosa faresti se adesso entrasse il tuo ex?",
  "Per il prossimo turno siediti in braccio alla persona alla tua sinistra.",
  "Qual è il messaggio più sfacciato che hai mai ricevuto?",
  "Nomina tre cose che la sposa o lo sposo NON sa fare!",
  "Scatta una foto in cui tutti posano come una coppia di sposi!",
  "Cosa diresti degli sposi nel tuo discorso di nozze?",
  "Convinci uno sconosciuto a fare una foto con il gruppo!",
  "Qual è la caratteristica più divertente della sposa o dello sposo?",
  "Canta una canzone d'amore per gli sposi!",
  "Qual è stato il primo litigio tra la sposa e lo sposo?",
  "Scrivi una dichiarazione d'amore agli sposi su un tovagliolo!",
  "Chi conosce la sposa o lo sposo da più tempo?",
  "Gira un video con gli auguri di uno sconosciuto!",
  "Qual è il momento più romantico degli sposi?",
  "Inventa un ballo di nozze: tutti devono ballare insieme!",
  "Quale film descrive la relazione degli sposi?",
  "Trova qualcosa di blu, qualcosa di vecchio, qualcosa di nuovo e qualcosa di prestato!",
  "Cosa non deve succedere ASSOLUTAMENTE al matrimonio?",
  "Chiama la sposa o lo sposo e di': «Ci manchi!»",
  "Cosa faranno gli sposi subito dopo il matrimonio?",
  "Scrivi un contratto matrimoniale con clausole divertenti!",
  "Qual è la fissazione più grande della sposa o dello sposo?",
  "Crea un bouquet da sposa con quello che trovi!",
  "Cosa non farebbe MAI la sposa o lo sposo?",
  "Registra un video in cui tutti gridano «Sì, lo voglio!»",
  "Qual è il regalo più bello che la sposa o lo sposo abbia mai ricevuto?",
  "Improvvisa un discorso di nozze di un minuto al massimo!",
  "Quale animale sarebbe la sposa o lo sposo, e perché?",
  "Scatta una foto che sembri la locandina di un film!",
  "Cosa dovrebbero assolutamente far suonare gli sposi al matrimonio?",
  "Raccogli tre consigli sul matrimonio dai passanti!",
  "Qual è stato il momento più imbarazzante della sposa o dello sposo?",
  "Scattate una foto formando un cuore di gruppo!",
  "Qual è la peggiore frase da rimorchio che tu abbia mai sentito?",
  "Fai il tuo miglior complimento alla persona di fronte a te!",
  "Qual è stata la tua peggior figuraccia durante un appuntamento?",
  "Flirta con la persona alla tua sinistra per quindici secondi!",
  "Qual è la tua frase da flirt preferita?",
  "Fai la tua migliore espressione da modello per una foto!",
  "Qual è il posto più romantico in cui sei mai stato?",
  "Scrivi un complimento alla quinta persona della tua rubrica!",
  "Qual è la cosa più audace che hai mai fatto durante un appuntamento?",
  "Fai un selfie buffissimo con la persona di fronte a te!",
  "Chi qui ha la voce più seducente?",
  "Di' qualcosa di sfacciato sottovoce all'orecchio della persona a destra!",
  "Cosa faresti in un appuntamento perfetto?",
  "Guarda intensamente negli occhi la persona di fronte a te per dieci secondi!",
  "Qual è la tua esperienza più strana con un'app di incontri?",
  "Dai a ciascuno del gruppo un soprannome da flirt!",
  "Cosa ti accende di più il desiderio?",
  "Di' la tua migliore frase da rimorchio e usala!",
  "Qual è la cosa più romantica che ti sia mai successa?",
  "Recita una scena d'amore drammatica, da solo!",
  "Chi qui darebbe i migliori baci da film?",
  "Manda un emoji a forma di cuore all'ultima persona!",
  "Qual è stato il tuo momento di flirt più imbarazzante?",
  "Sfoggia la tua espressione più seducente e tienila per dieci secondi!",
  "Quale celebrità sarebbe il tuo appuntamento perfetto?",
  "Canta una canzone d'amore alla persona alla tua sinistra!",
  "Qual è stato il bacio più bello della tua vita?",
  "Fai una dichiarazione d'amore al tuo cibo preferito!",
  "A cosa rinunceresti per il grande amore?",
  "Lascia che il gruppo organizzi un appuntamento per te!",
];
