/** Canonieke volgorde uit legacy-special-de.ts. */
export const TEXTS = [
  "Vertel het grappigste verhaal over de bruid of bruidegom.",
  "Bel een willekeurig persoon en feliciteer die met het huwelijk.",
  "Wat denk je dat het bruidspaar over tien jaar doet?",
  "Stuur de bruid of bruidegom een gênant bericht.",
  "Wat was je eerste indruk van de partner van de bruid of bruidegom?",
  "Leer een beweging voor een bruiloftsdans en doe die voor.",
  "Wie huilde het meest toen het huwelijk werd aangekondigd?",
  "Maak een foto die op een trouwfotoshoot lijkt.",
  "Wat is het beste huwelijksadvies dat je zou kunnen geven?",
  "Houd een korte huwelijkstoespraak voor het bruidspaar.",
  "Vertel je gênantste gezamenlijke herinnering met de bruid of bruidegom.",
  "Stap op een onbekende af en nodig die uit voor de bruiloft.",
  "Wat zou je het bruidspaar als huwelijkscadeau geven?",
  "Neem een felicitatievideo van vijftien seconden op.",
  "Welk lied beschrijft de relatie van het bruidspaar het beste?",
  "Zoek een onbekende die 'Ja, ik wil!' zegt en neem het op.",
  "Wat is het irritantste dat de bruid of bruidegom doet?",
  "Organiseer een spontane groepsfoto met iedereen.",
  "Hoe vertelde de bruid of bruidegom over het aanzoek?",
  "Schrijf op een servet een voorspelling voor het huwelijk van het bruidspaar.",
  "Wat wens je het bruidspaar toe voor hun huwelijk?",
  "Verzamel binnen twee minuten vijf handtekeningen van onbekenden op een servet.",
  "Wat was de grappigste misser van de bruid of bruidegom?",
  "Zing 'Going to the Chapel' of een bruiloftslied hardop.",
  "Wat zei de bruid of bruidegom toen je voor het eerst over de verloving hoorde?",
  "Maak een foto met een onbekende en zet er 'Bruiloftsgast' bij.",
  "Wie moet absoluut geen toespraak op de bruiloft houden, en waarom?",
  "Vraag drie mensen om een huwelijkstip en schrijf hun tips op.",
  "Wat voor type was de bruid of bruidegom als tiener?",
  "Doe op je knieën een aanzoek voor de hele groep.",
  "Wie denk je dat op de bruiloft het meest zal huilen?",
  "Beschrijf je slechtste kus.",
  "Wie uit de groep zou je om twee uur 's nachts een bericht sturen?",
  "Wat is het gewaagdste dat je ooit hebt gedaan?",
  "Laat het laatste flirtgesprek op je telefoon zien.",
  "Wat is jouw grootste afknapper?",
  "Geef de persoon links naast je een compliment waarvan die gaat blozen.",
  "Wat is het verleidelijkste dat iemand ooit tegen je heeft gezegd?",
  "Zet je beste flirtgezicht op en houd het tien seconden vast.",
  "Wat was je gênantste ervaring tijdens een date?",
  "Fluister iets ondeugends in het oor van de persoon rechts naast je.",
  "Heb je ooit iemand uit deze groep aantrekkelijk gevonden?",
  "Stuur iemand naar keuze een ondeugend bericht en laat het aan de groep zien.",
  "Wie was jouw meest ongewone crush?",
  "Laat de persoon tegenover je een bericht op je telefoon lezen.",
  "Wat is het wildste dat je op een feest hebt meegemaakt?",
  "Vertel het verhaal van je eerste kus.",
  "Als je met een beroemdheid zou kunnen daten, wie zou dat zijn?",
  "Kijk verleidelijk in de camera en stuur de foto naar de groep.",
  "Wat is de vreemdste plek waar je ooit iemand hebt gekust?",
  "Vertel een geheim dat niemand hier kent.",
  "Van welke favoriete film zou je nooit openlijk toegeven dat je ervan houdt?",
  "Bijt op je lip en kijk de persoon tegenover je vijf seconden in de ogen.",
  "Heb je ooit iemand geghost? Waarom?",
  "Laat de laatste afbeelding zien die je in je galerij hebt opgeslagen.",
  "Wat is het romantischste dat iemand ooit voor je heeft gedaan?",
  "Typ zonder te kijken een ondeugend bericht en stuur het naar je laatste contact.",
  "Wie hier is het meest een hartenbreker?",
  "Doe vijf push-ups en kreun daarbij dramatisch.",
  "Wat zou je doen als je ex nu binnenkwam?",
  "Ga de volgende ronde op schoot zitten bij de persoon links naast je.",
  "Wat is het brutaalste bericht dat je ooit hebt gekregen?",
  "Noem drie dingen die de bruid of bruidegom NIET kan!",
  "Maak een foto waarop iedereen als bruidspaar poseert!",
  "Wat zou je in je huwelijkstoespraak over het bruidspaar zeggen?",
  "Haal een onbekende over om met de groep op de foto te gaan!",
  "Wat is de grappigste eigenschap van de bruid of bruidegom?",
  "Zing een liefdeslied voor het bruidspaar!",
  "Waarover ging de eerste ruzie tussen de bruid en bruidegom?",
  "Schrijf een liefdesverklaring aan het bruidspaar op een servet!",
  "Wie kent de bruid of bruidegom het langst?",
  "Maak een video met felicitaties van een onbekende!",
  "Wat is het romantischste moment van het bruidspaar?",
  "Bedenk een bruiloftsdans waarbij iedereen meedanst!",
  "Welke film beschrijft de relatie van het bruidspaar?",
  "Zoek iets blauws, iets ouds, iets nieuws en iets geleends!",
  "Wat mag er ABSOLUUT NIET op de bruiloft gebeuren?",
  "Bel de bruid of bruidegom en zeg: 'We missen je!'",
  "Wat zal het bruidspaar als eerste na de bruiloft doen?",
  "Schrijf een huwelijkscontract met grappige bepalingen!",
  "Wat is de grootste eigenaardigheid van de bruid of bruidegom?",
  "Maak een bruidsboeket van wat je kunt vinden!",
  "Wat zou de bruid of bruidegom NOOIT doen?",
  "Neem een video op waarin iedereen 'Ja, ik wil!' roept!",
  "Wat was het beste cadeau dat de bruid of bruidegom ooit kreeg?",
  "Improviseer een huwelijkstoespraak van maximaal één minuut!",
  "Welk dier zou de bruid of bruidegom zijn, en waarom?",
  "Maak een foto die op een filmposter lijkt!",
  "Wat moet het bruidspaar ZEKER op de bruiloft laten spelen?",
  "Verzamel drie huwelijkstips van voorbijgangers!",
  "Wat was het gênantste moment van de bruid of bruidegom?",
  "Maak een groepsfoto waarop jullie een hart vormen!",
  "Wat was de slechtste openingszin die je ooit hoorde?",
  "Geef de persoon tegenover je jouw beste compliment!",
  "Wat was je grootste datingblunder?",
  "Flirt vijftien seconden met de persoon links van je!",
  "Wat is je favoriete flirtzin?",
  "Zet je beste modelgezicht op voor een foto!",
  "Wat was de romantischste plek waar je ooit bent geweest?",
  "Stuur de vijfde persoon in je contacten een compliment!",
  "Wat is het gewaagdste dat je ooit op een date hebt gedaan?",
  "Maak een gekke selfie met de persoon tegenover je!",
  "Wie hier heeft de verleidelijkste stem?",
  "Fluister iets ondeugends bij de persoon rechts in het oor!",
  "Wat zou je doen tijdens een perfecte date?",
  "Kijk de persoon tegenover je tien seconden diep in de ogen!",
  "Wat is je vreemdste ervaring met een datingapp?",
  "Geef iedereen in de groep een flirtbijnaam!",
  "Waar word je het meest opgewonden van?",
  "Vertel je beste openingszin en gebruik hem!",
  "Wat is het romantischste dat je ooit is overkomen?",
  "Speel helemaal alleen een dramatische liefdesscène!",
  "Wie hier zou het beste kunnen kussen in een film?",
  "Stuur de laatste persoon een hart-emoji!",
  "Wat was je gênantste flirtmoment?",
  "Laat je verleidelijkste gezichtsuitdrukking zien en houd die tien seconden vast!",
  "Welke beroemdheid zou jouw perfecte date zijn?",
  "Zing een liefdeslied voor de persoon links van je!",
  "Wat was de beste kus van je leven?",
  "Verklaar je liefde aan je favoriete eten!",
  "Wat zou je voor de grote liefde opgeven?",
  "Laat de groep een date voor jou plannen!",
] as const;
