export const TEXTS = [
  "Cuenta la historia más divertida sobre la novia o el novio.",
  "Llama a una persona al azar y felicítala por su boda.",
  "¿Qué crees que estarán haciendo los novios dentro de diez años?",
  "Escríbele un mensaje vergonzoso a la novia o al novio.",
  "¿Cuál fue tu primera impresión de la pareja de la novia o del novio?",
  "Aprende un paso de baile de boda y muéstralo.",
  "¿Quién lloró más cuando se anunció la boda?",
  "Haz una foto que parezca una sesión fotográfica de boda.",
  "¿Cuál es el mejor consejo matrimonial que podrías dar?",
  "Da un pequeño discurso de boda para los novios.",
  "Cuenta el recuerdo compartido más vergonzoso con la novia o el novio.",
  "Acércate a un desconocido e invítalo a la boda.",
  "¿Qué les regalarías a los novios por su boda?",
  "Graba un vídeo de felicitación de quince segundos.",
  "¿Qué canción describe mejor la relación de los novios?",
  "Encuentra a un desconocido que diga «¡Sí, quiero!» y grábalo.",
  "¿Qué es lo más molesto que hace la novia o el novio?",
  "Organiza una foto de grupo espontánea con todos.",
  "¿Cómo contó la propuesta de matrimonio la novia o el novio?",
  "Escribe en una servilleta una profecía sobre el matrimonio de los novios.",
  "¿Qué deseas para el matrimonio de los novios?",
  "Consigue cinco firmas de desconocidos en una servilleta en dos minutos.",
  "¿Cuál fue la metedura de pata más divertida de la novia o del novio?",
  "Canta en voz alta «Going to the Chapel» o una canción de boda.",
  "¿Qué dijo la novia o el novio cuando te enteraste del compromiso por primera vez?",
  "Hazte una foto con un desconocido y ponle el texto «Invitado a la boda».",
  "¿Quién no debería dar el discurso de la boda bajo ningún concepto? ¿Y por qué?",
  "Pídeles a tres personas un consejo matrimonial y apúntalos.",
  "¿Cómo era la novia o el novio de adolescente?",
  "Haz una proposición de matrimonio de rodillas delante de todo el grupo.",
  "¿Quién crees que llorará más en la boda?",
  "Describe tu peor beso.",
  "¿A quién de este grupo le mandarías un mensaje a las dos de la madrugada?",
  "¿Qué es lo más atrevido que has hecho nunca?",
  "Enseña la última conversación de coqueteo de tu móvil.",
  "¿Qué es lo que más te corta la atracción por alguien?",
  "Hazle a la persona de tu izquierda un cumplido que la haga sonrojar.",
  "¿Qué es lo más seductor que alguien te ha dicho nunca?",
  "Pon tu mejor cara de coqueteo y mantenla diez segundos.",
  "¿Cuál fue tu experiencia más vergonzosa en una cita?",
  "Susurra algo picante al oído de la persona de tu derecha.",
  "¿Alguna vez te ha parecido atractivo alguien de este grupo?",
  "Manda un mensaje atrevido a alguien de tu elección y enséñaselo al grupo.",
  "¿Cuál es tu flechazo más inusual?",
  "Deja que la persona de enfrente lea un mensaje de tu móvil.",
  "¿Qué es lo más salvaje que has vivido en una fiesta?",
  "Cuenta la historia de tu primer beso.",
  "Si pudieras salir con una persona famosa, ¿quién sería?",
  "Mira a la cámara de forma seductora y envía la foto al grupo.",
  "¿Cuál es el lugar más raro donde has besado a alguien?",
  "Cuenta un secreto que aquí no conozca nadie.",
  "¿Qué película te encanta pero nunca lo admitirías en público?",
  "Muérdete el labio y mira a los ojos a la persona de enfrente durante cinco segundos.",
  "¿Alguna vez dejaste de responder a alguien sin dar explicaciones? ¿Por qué?",
  "Enseña la última imagen que guardaste en tu galería.",
  "¿Qué es lo más romántico que alguien ha hecho por ti?",
  "Escribe sin mirar un mensaje atrevido y envíaselo al último contacto.",
  "¿Quién de aquí tiene más pinta de rompecorazones?",
  "Haz cinco flexiones y gime de forma dramática mientras las haces.",
  "¿Qué harías si entrara tu ex ahora mismo?",
  "Siéntate en el regazo de la persona de tu izquierda durante la próxima ronda.",
  "¿Cuál es el mensaje más descarado que has recibido nunca?",
  "¡Di tres cosas que la novia o el novio NO sabe hacer!",
  "¡Haz una foto en la que todos posen como una pareja de novios!",
  "¿Qué dirías de los novios en tu discurso de boda?",
  "¡Convence a un desconocido para que se haga una foto con el grupo!",
  "¿Cuál es el rasgo más divertido de la novia o del novio?",
  "¡Canta una canción de amor para los novios!",
  "¿Cuál fue la primera discusión entre la novia y el novio?",
  "¡Escribe una declaración de amor para los novios en una servilleta!",
  "¿Quién conoce a la novia o al novio desde hace más tiempo?",
  "¡Graba un vídeo con las felicitaciones de un desconocido!",
  "¿Cuál es el momento más romántico de los novios?",
  "¡Inventa un baile de boda y que todos lo bailen!",
  "¿Qué película describe la relación de los novios?",
  "¡Encuentra algo azul, algo viejo, algo nuevo y algo prestado!",
  "¿Qué NO debe pasar bajo ningún concepto en la boda?",
  "¡Llama a la novia o al novio y dile: «Te echamos de menos»!",
  "¿Qué harán los novios justo después de la boda?",
  "¡Escribe un contrato matrimonial con cláusulas divertidas!",
  "¿Cuál es la mayor manía de la novia o del novio?",
  "¡Haz un ramo de novia con lo que encuentres!",
  "¿Qué no haría NUNCA la novia o el novio?",
  "¡Graba un vídeo en el que todos griten «Sí, quiero»!",
  "¿Cuál es el mejor regalo que ha recibido la novia o el novio?",
  "¡Improvisa un discurso de boda de un minuto como máximo!",
  "¿Qué animal sería la novia o el novio y por qué?",
  "¡Haz una foto que parezca el cartel de una película!",
  "¿Qué deberían poner los novios sí o sí en la boda?",
  "¡Recoge tres consejos matrimoniales de los transeúntes!",
  "¿Cuál fue el momento más vergonzoso de la novia o del novio?",
  "¡Haced una foto formando un corazón en grupo!",
  "¿Cuál es la peor frase para ligar que has oído nunca?",
  "¡Hazle tu mejor cumplido a la persona de enfrente!",
  "¿Cuál fue tu mayor metedura de pata en una cita?",
  "¡Coquetea con la persona de tu izquierda durante quince segundos!",
  "¿Cuál es tu frase favorita para coquetear?",
  "¡Pon tu mejor cara de modelo para una foto!",
  "¿Cuál es el lugar más romántico en el que has estado?",
  "¡Escríbele un cumplido a la quinta persona de tus contactos!",
  "¿Qué es lo más atrevido que has hecho en una cita?",
  "¡Hazte un selfi disparatado con la persona de enfrente!",
  "¿Quién de aquí tiene la voz más seductora?",
  "¡Dile algo descarado en un susurro al oído a la persona de la derecha!",
  "¿Qué harías en una cita perfecta?",
  "¡Mira fijamente a los ojos a la persona de enfrente durante diez segundos!",
  "¿Cuál es tu experiencia más extraña en una aplicación de citas?",
  "¡Ponle a cada persona del grupo un apodo de coqueteo!",
  "¿Qué es lo que más te excita?",
  "¡Di tu mejor frase para ligar y úsala!",
  "¿Qué es lo más romántico que te ha pasado?",
  "¡Representa una escena de amor dramática a solas!",
  "¿Quién de aquí daría los mejores besos de película?",
  "¡Envíale un emoji de corazón a la última persona!",
  "¿Cuál fue tu momento más vergonzoso al coquetear?",
  "¡Saca tu mejor expresión de coqueteo y aguántala diez segundos!",
  "¿Qué famoso sería tu cita perfecta?",
  "¡Cántale una canción de amor a la persona de tu izquierda!",
  "¿Cuál fue el mejor beso de tu vida?",
  "¡Hazle una declaración de amor a tu comida favorita!",
  "¿A qué renunciarías por el gran amor de tu vida?",
  "¡Deja que el grupo organice una cita para ti!",
];
