/** Canonical order from legacy-special-de.ts: 31 JGA, 31 adult, 30 JGA, 30 adult cards. */
export const TEXTS = [
  "Tell the funniest story about the bride or groom.",
  "Call a random person and congratulate them on their wedding.",
  "What do you think the couple will be doing in ten years?",
  "Send the bride or groom an embarrassing message.",
  "What was your first impression of the bride's or groom's partner?",
  "Learn a wedding dance move and perform it.",
  "Who cried the most when the wedding was announced?",
  "Take a photo that looks like a wedding photo shoot.",
  "What's the best marriage advice you could give?",
  "Give a mini wedding speech for the couple.",
  "Share your most embarrassing memory with the bride or groom.",
  "Go up to a stranger and invite them to the wedding.",
  "What would you give the couple as a wedding present?",
  "Record a fifteen-second video of congratulations.",
  "What song best describes the couple's relationship?",
  "Find a stranger who says 'I do!' and record it.",
  "What's the most annoying thing the bride or groom does?",
  "Organise a spontaneous group photo with everyone.",
  "How did the bride or groom tell the story of the proposal?",
  "Write a prediction for the couple's marriage on a napkin.",
  "What do you wish for the couple's marriage?",
  "Collect five strangers' signatures on a napkin within two minutes.",
  "What was the bride's or groom's funniest mishap?",
  "Sing 'Going to the Chapel' or a wedding song out loud.",
  "What did the bride or groom say when you first heard about the engagement?",
  "Take a photo with a stranger and caption it 'Wedding guest'.",
  "Who absolutely shouldn't give a speech at the wedding, and why?",
  "Ask three people for a piece of marriage advice and write their tips down.",
  "What was the bride or groom like as a teenager?",
  "Propose on your knees in front of the whole group.",
  "Who do you think will cry the most at the wedding?",
  "Describe your worst kiss.",
  "Who in this group would you text at two in the morning?",
  "What's the most daring thing you've ever done?",
  "Show the latest flirty conversation on your phone.",
  "What's your biggest turn-off?",
  "Give the person on your left a compliment that makes them blush.",
  "What's the most seductive thing anyone has ever said to you?",
  "Make your best flirty face and hold it for ten seconds.",
  "What was your most embarrassing date experience?",
  "Whisper something cheeky into the ear of the person on your right.",
  "Have you ever found someone in this group attractive?",
  "Send someone of your choice a cheeky message and show it to the group.",
  "What's your most unusual crush?",
  "Let the person opposite you read a message on your phone.",
  "What's the wildest thing you've experienced at a party?",
  "Tell the story of your first kiss.",
  "If you could date a famous person, who would it be?",
  "Give the camera a seductive look and send the photo to the group.",
  "What's the strangest place you've ever kissed someone?",
  "Tell a secret that nobody here knows.",
  "What favourite film would you never publicly admit to loving?",
  "Bite your lip and look into the eyes of the person opposite you for five seconds.",
  "Have you ever ghosted someone? Why?",
  "Show the last picture you saved to your gallery.",
  "What's the most romantic thing anyone has ever done for you?",
  "Type a cheeky message without looking and send it to your last contact.",
  "Who here is most likely to be a heartbreaker?",
  "Do five push-ups while groaning dramatically.",
  "What would you do if your ex walked in right now?",
  "Sit on the lap of the person on your left for the next round.",
  "What's the cheekiest message you've ever received?",
  "Name three things the bride or groom CANNOT do!",
  "Take a picture where everyone poses like a wedding couple!",
  "What would you say about the couple in your wedding speech?",
  "Persuade a stranger to take a photo with the group!",
  "What's the bride's or groom's funniest trait?",
  "Sing a love song for the couple!",
  "What was the bride and groom's first argument about?",
  "Write the couple a declaration of love on a napkin!",
  "Who has known the bride or groom the longest?",
  "Make a video of a stranger offering their congratulations!",
  "What's the couple's most romantic moment?",
  "Invent a wedding dance for everyone to join in!",
  "What film describes the couple's relationship?",
  "Find something blue, something old, something new and something borrowed!",
  "What must ABSOLUTELY NOT happen at the wedding?",
  "Call the bride or groom and say, 'We miss you!'",
  "What will the couple do first after the wedding?",
  "Write a marriage contract with funny clauses!",
  "What's the bride's or groom's biggest quirk?",
  "Build a wedding bouquet out of whatever you find!",
  "What would the bride or groom NEVER do?",
  "Record a video of everyone shouting 'I do!'",
  "What's the best gift the bride or groom has ever received?",
  "Improvise a wedding speech lasting no more than one minute!",
  "What animal would the bride or groom be, and why?",
  "Take a photo that looks like a film poster!",
  "What should the couple DEFINITELY play at their wedding?",
  "Collect three marriage tips from passers-by!",
  "What was the bride's or groom's most embarrassing moment?",
  "Take a group photo forming a heart!",
  "What's the worst chat-up line you've ever heard?",
  "Give the person opposite you your best compliment!",
  "What was your biggest dating disaster?",
  "Flirt with the person on your left for fifteen seconds!",
  "What's your favourite flirting line?",
  "Put on your best model face for a photo!",
  "What's the most romantic place you've ever been to?",
  "Text a compliment to the fifth person in your contacts!",
  "What's the boldest thing you've ever done on a date?",
  "Take a crazy selfie with the person opposite you!",
  "Who here has the most seductive voice?",
  "Whisper something naughty to the person on your right!",
  "What would you do on a perfect date?",
  "Gaze deeply into the eyes of the person opposite you for ten seconds!",
  "What's your strangest dating-app experience?",
  "Give everyone in the group a flirty nickname!",
  "What's your biggest turn-on?",
  "Share your best chat-up line and use it!",
  "What's the most romantic thing that has ever happened to you?",
  "Act out a dramatic love scene all by yourself!",
  "Who here would be the best on-screen kisser?",
  "Send the last person a heart emoji!",
  "What was your most embarrassing flirting moment?",
  "Show off your best flirting expression and keep it for ten seconds!",
  "Which celebrity would be your perfect date?",
  "Sing a love song to the person on your left!",
  "What was the best kiss of your life?",
  "Declare your love for your favourite food!",
  "What would you give up for true love?",
  "Let the group plan a date for you!",
] as const;
