export interface DrawWord {
  word: string;
  category: string;
  difficulty: 1 | 2 | 3;
}

export const DRAW_WORDS: DrawWord[] = [
  // Tiere (30)
  { word: 'Hund', category: 'Tiere', difficulty: 1 },
  { word: 'Katze', category: 'Tiere', difficulty: 1 },
  { word: 'Elefant', category: 'Tiere', difficulty: 1 },
  { word: 'Fisch', category: 'Tiere', difficulty: 1 },
  { word: 'Vogel', category: 'Tiere', difficulty: 1 },
  { word: 'Schmetterling', category: 'Tiere', difficulty: 2 },
  { word: 'Schildkröte', category: 'Tiere', difficulty: 2 },
  { word: 'Krokodil', category: 'Tiere', difficulty: 2 },
  { word: 'Pinguin', category: 'Tiere', difficulty: 1 },
  { word: 'Löwe', category: 'Tiere', difficulty: 1 },
  { word: 'Giraffe', category: 'Tiere', difficulty: 2 },
  { word: 'Schlange', category: 'Tiere', difficulty: 1 },
  { word: 'Spinne', category: 'Tiere', difficulty: 2 },
  { word: 'Delfin', category: 'Tiere', difficulty: 2 },
  { word: 'Pferd', category: 'Tiere', difficulty: 1 },
  { word: 'Affe', category: 'Tiere', difficulty: 1 },
  { word: 'Frosch', category: 'Tiere', difficulty: 1 },
  { word: 'Eule', category: 'Tiere', difficulty: 2 },
  { word: 'Biene', category: 'Tiere', difficulty: 2 },
  { word: 'Hai', category: 'Tiere', difficulty: 1 },
  { word: 'Wal', category: 'Tiere', difficulty: 2 },
  { word: 'Papagei', category: 'Tiere', difficulty: 2 },
  { word: 'Schnecke', category: 'Tiere', difficulty: 1 },
  { word: 'Flamingo', category: 'Tiere', difficulty: 2 },
  { word: 'Chamäleon', category: 'Tiere', difficulty: 3 },
  { word: 'Seepferdchen', category: 'Tiere', difficulty: 3 },
  { word: 'Känguru', category: 'Tiere', difficulty: 2 },
  { word: 'Igel', category: 'Tiere', difficulty: 2 },
  { word: 'Marienkäfer', category: 'Tiere', difficulty: 2 },
  { word: 'Qualle', category: 'Tiere', difficulty: 2 },

  // Essen (30)
  { word: 'Pizza', category: 'Essen', difficulty: 1 },
  { word: 'Hamburger', category: 'Essen', difficulty: 1 },
  { word: 'Eis', category: 'Essen', difficulty: 1 },
  { word: 'Kuchen', category: 'Essen', difficulty: 1 },
  { word: 'Banane', category: 'Essen', difficulty: 1 },
  { word: 'Apfel', category: 'Essen', difficulty: 1 },
  { word: 'Spaghetti', category: 'Essen', difficulty: 2 },
  { word: 'Popcorn', category: 'Essen', difficulty: 2 },
  { word: 'Brezel', category: 'Essen', difficulty: 2 },
  { word: 'Sushi', category: 'Essen', difficulty: 2 },
  { word: 'Pommes', category: 'Essen', difficulty: 1 },
  { word: 'Donut', category: 'Essen', difficulty: 1 },
  { word: 'Wassermelone', category: 'Essen', difficulty: 2 },
  { word: 'Croissant', category: 'Essen', difficulty: 2 },
  { word: 'Taco', category: 'Essen', difficulty: 2 },
  { word: 'Bratwurst', category: 'Essen', difficulty: 1 },
  { word: 'Pfannkuchen', category: 'Essen', difficulty: 2 },
  { word: 'Käse', category: 'Essen', difficulty: 1 },
  { word: 'Brötchen', category: 'Essen', difficulty: 1 },
  { word: 'Schokolade', category: 'Essen', difficulty: 2 },
  { word: 'Erdbeere', category: 'Essen', difficulty: 1 },
  { word: 'Spiegelei', category: 'Essen', difficulty: 1 },
  { word: 'Salat', category: 'Essen', difficulty: 2 },
  { word: 'Sandwich', category: 'Essen', difficulty: 1 },
  { word: 'Lollipop', category: 'Essen', difficulty: 1 },
  { word: 'Torte', category: 'Essen', difficulty: 2 },
  { word: 'Suppe', category: 'Essen', difficulty: 2 },
  { word: 'Muffin', category: 'Essen', difficulty: 1 },
  { word: 'Kebab', category: 'Essen', difficulty: 2 },
  { word: 'Bonbon', category: 'Essen', difficulty: 1 },

  // Berufe (30)
  { word: 'Arzt', category: 'Berufe', difficulty: 1 },
  { word: 'Feuerwehrmann', category: 'Berufe', difficulty: 2 },
  { word: 'Polizist', category: 'Berufe', difficulty: 2 },
  { word: 'Lehrer', category: 'Berufe', difficulty: 2 },
  { word: 'Koch', category: 'Berufe', difficulty: 1 },
  { word: 'Pilot', category: 'Berufe', difficulty: 2 },
  { word: 'Astronaut', category: 'Berufe', difficulty: 2 },
  { word: 'Maler', category: 'Berufe', difficulty: 1 },
  { word: 'Fotograf', category: 'Berufe', difficulty: 2 },
  { word: 'Zahnarzt', category: 'Berufe', difficulty: 2 },
  { word: 'Bäcker', category: 'Berufe', difficulty: 1 },
  { word: 'Friseur', category: 'Berufe', difficulty: 2 },
  { word: 'Richter', category: 'Berufe', difficulty: 2 },
  { word: 'Clown', category: 'Berufe', difficulty: 1 },
  { word: 'Taucher', category: 'Berufe', difficulty: 2 },
  { word: 'DJ', category: 'Berufe', difficulty: 2 },
  { word: 'Mechaniker', category: 'Berufe', difficulty: 2 },
  { word: 'Zauberer', category: 'Berufe', difficulty: 2 },
  { word: 'Detektiv', category: 'Berufe', difficulty: 3 },
  { word: 'Gärtner', category: 'Berufe', difficulty: 2 },
  { word: 'Tierarzt', category: 'Berufe', difficulty: 2 },
  { word: 'Pirat', category: 'Berufe', difficulty: 1 },
  { word: 'Kellner', category: 'Berufe', difficulty: 2 },
  { word: 'Ninja', category: 'Berufe', difficulty: 2 },
  { word: 'Cowboy', category: 'Berufe', difficulty: 2 },
  { word: 'Briefträger', category: 'Berufe', difficulty: 2 },
  { word: 'Dirigent', category: 'Berufe', difficulty: 3 },
  { word: 'Imker', category: 'Berufe', difficulty: 3 },
  { word: 'Fischer', category: 'Berufe', difficulty: 1 },
  { word: 'Ritter', category: 'Berufe', difficulty: 2 },

  // Objekte (30)
  { word: 'Haus', category: 'Objekte', difficulty: 1 },
  { word: 'Auto', category: 'Objekte', difficulty: 1 },
  { word: 'Fahrrad', category: 'Objekte', difficulty: 1 },
  { word: 'Flugzeug', category: 'Objekte', difficulty: 2 },
  { word: 'Regenschirm', category: 'Objekte', difficulty: 1 },
  { word: 'Schere', category: 'Objekte', difficulty: 1 },
  { word: 'Brille', category: 'Objekte', difficulty: 1 },
  { word: 'Schlüssel', category: 'Objekte', difficulty: 2 },
  { word: 'Gitarre', category: 'Objekte', difficulty: 2 },
  { word: 'Kamera', category: 'Objekte', difficulty: 2 },
  { word: 'Telefon', category: 'Objekte', difficulty: 1 },
  { word: 'Rakete', category: 'Objekte', difficulty: 2 },
  { word: 'Schiff', category: 'Objekte', difficulty: 2 },
  { word: 'Kerze', category: 'Objekte', difficulty: 1 },
  { word: 'Uhr', category: 'Objekte', difficulty: 1 },
  { word: 'Fernseher', category: 'Objekte', difficulty: 1 },
  { word: 'Globus', category: 'Objekte', difficulty: 2 },
  { word: 'Diamant', category: 'Objekte', difficulty: 2 },
  { word: 'Krone', category: 'Objekte', difficulty: 2 },
  { word: 'Ballon', category: 'Objekte', difficulty: 1 },
  { word: 'Zelt', category: 'Objekte', difficulty: 1 },
  { word: 'Leuchtturm', category: 'Objekte', difficulty: 2 },
  { word: 'Roboter', category: 'Objekte', difficulty: 2 },
  { word: 'Skateboard', category: 'Objekte', difficulty: 2 },
  { word: 'Kompass', category: 'Objekte', difficulty: 3 },
  { word: 'Schneemann', category: 'Objekte', difficulty: 1 },
  { word: 'Drachen', category: 'Objekte', difficulty: 2 },
  { word: 'Schaukel', category: 'Objekte', difficulty: 2 },
  { word: 'Hubschrauber', category: 'Objekte', difficulty: 3 },
  { word: 'Sandburg', category: 'Objekte', difficulty: 2 },

  // Aktionen (30)
  { word: 'Schwimmen', category: 'Aktionen', difficulty: 2 },
  { word: 'Tanzen', category: 'Aktionen', difficulty: 2 },
  { word: 'Kochen', category: 'Aktionen', difficulty: 2 },
  { word: 'Schlafen', category: 'Aktionen', difficulty: 1 },
  { word: 'Surfen', category: 'Aktionen', difficulty: 2 },
  { word: 'Skifahren', category: 'Aktionen', difficulty: 2 },
  { word: 'Angeln', category: 'Aktionen', difficulty: 1 },
  { word: 'Klettern', category: 'Aktionen', difficulty: 2 },
  { word: 'Singen', category: 'Aktionen', difficulty: 2 },
  { word: 'Jonglieren', category: 'Aktionen', difficulty: 3 },
  { word: 'Boxen', category: 'Aktionen', difficulty: 2 },
  { word: 'Reiten', category: 'Aktionen', difficulty: 2 },
  { word: 'Fotografieren', category: 'Aktionen', difficulty: 3 },
  { word: 'Meditieren', category: 'Aktionen', difficulty: 3 },
  { word: 'Fallschirmspringen', category: 'Aktionen', difficulty: 3 },
  { word: 'Duschen', category: 'Aktionen', difficulty: 2 },
  { word: 'Lesen', category: 'Aktionen', difficulty: 2 },
  { word: 'Malen', category: 'Aktionen', difficulty: 1 },
  { word: 'Telefonieren', category: 'Aktionen', difficulty: 2 },
  { word: 'Backen', category: 'Aktionen', difficulty: 2 },
  { word: 'Staubsaugen', category: 'Aktionen', difficulty: 2 },
  { word: 'Zelten', category: 'Aktionen', difficulty: 2 },
  { word: 'Joggen', category: 'Aktionen', difficulty: 2 },
  { word: 'Trampolinspringen', category: 'Aktionen', difficulty: 3 },
  { word: 'Tauchen', category: 'Aktionen', difficulty: 2 },
  { word: 'Fußball spielen', category: 'Aktionen', difficulty: 1 },
  { word: 'Yoga', category: 'Aktionen', difficulty: 2 },
  { word: 'Bügeln', category: 'Aktionen', difficulty: 2 },
  { word: 'Segeln', category: 'Aktionen', difficulty: 2 },
  { word: 'Schnorcheln', category: 'Aktionen', difficulty: 3 },

  // Neue Tiere (20)
  { word: 'Krokodil', category: 'Tiere', difficulty: 2 },
  { word: 'Schildkröte', category: 'Tiere', difficulty: 2 },
  { word: 'Gorilla', category: 'Tiere', difficulty: 2 },
  { word: 'Pelikan', category: 'Tiere', difficulty: 3 },
  { word: 'Koala', category: 'Tiere', difficulty: 2 },
  { word: 'Fledermaus', category: 'Tiere', difficulty: 2 },
  { word: 'Ameise', category: 'Tiere', difficulty: 2 },
  { word: 'Krabbe', category: 'Tiere', difficulty: 2 },
  { word: 'Nashorn', category: 'Tiere', difficulty: 2 },
  { word: 'Zebra', category: 'Tiere', difficulty: 1 },
  { word: 'Robbe', category: 'Tiere', difficulty: 2 },
  { word: 'Storch', category: 'Tiere', difficulty: 2 },
  { word: 'Faultier', category: 'Tiere', difficulty: 2 },
  { word: 'Tintenfisch', category: 'Tiere', difficulty: 3 },
  { word: 'Libelle', category: 'Tiere', difficulty: 3 },
  { word: 'Muecke', category: 'Tiere', difficulty: 3 },
  { word: 'Lama', category: 'Tiere', difficulty: 2 },
  { word: 'Waschbaer', category: 'Tiere', difficulty: 2 },
  { word: 'Biber', category: 'Tiere', difficulty: 2 },
  { word: 'Chamäleon', category: 'Tiere', difficulty: 3 },

  // Neue Objekte (20)
  { word: 'Anker', category: 'Objekte', difficulty: 2 },
  { word: 'Windmuehle', category: 'Objekte', difficulty: 2 },
  { word: 'Regenbogen', category: 'Objekte', difficulty: 1 },
  { word: 'Vulkan', category: 'Objekte', difficulty: 2 },
  { word: 'Kaktus', category: 'Objekte', difficulty: 1 },
  { word: 'Iglu', category: 'Objekte', difficulty: 2 },
  { word: 'Stethoskop', category: 'Objekte', difficulty: 3 },
  { word: 'Fernglas', category: 'Objekte', difficulty: 2 },
  { word: 'Taschenlampe', category: 'Objekte', difficulty: 2 },
  { word: 'Feuerwerk', category: 'Objekte', difficulty: 2 },
  { word: 'Pfeil und Bogen', category: 'Objekte', difficulty: 2 },
  { word: 'Laterne', category: 'Objekte', difficulty: 1 },
  { word: 'Trompete', category: 'Objekte', difficulty: 2 },
  { word: 'Schwert', category: 'Objekte', difficulty: 1 },
  { word: 'Krone', category: 'Objekte', difficulty: 1 },
  { word: 'Piratenschiff', category: 'Objekte', difficulty: 3 },
  { word: 'Riesenrad', category: 'Objekte', difficulty: 2 },
  { word: 'Heissluftballon', category: 'Objekte', difficulty: 2 },
  { word: 'Tempel', category: 'Objekte', difficulty: 3 },
  { word: 'Pyramide', category: 'Objekte', difficulty: 2 },

  // Neue Essen (20)
  { word: 'Ramen', category: 'Essen', difficulty: 2 },
  { word: 'Bretzel', category: 'Essen', difficulty: 1 },
  { word: 'Waffel', category: 'Essen', difficulty: 1 },
  { word: 'Lebkuchen', category: 'Essen', difficulty: 2 },
  { word: 'Avocado', category: 'Essen', difficulty: 2 },
  { word: 'Kiwi', category: 'Essen', difficulty: 1 },
  { word: 'Ananas', category: 'Essen', difficulty: 1 },
  { word: 'Kokosnuss', category: 'Essen', difficulty: 2 },
  { word: 'Pilz', category: 'Essen', difficulty: 1 },
  { word: 'Karotte', category: 'Essen', difficulty: 1 },
  { word: 'Aubergine', category: 'Essen', difficulty: 2 },
  { word: 'Mais', category: 'Essen', difficulty: 1 },
  { word: 'Gummibaerchen', category: 'Essen', difficulty: 2 },
  { word: 'Zuckerwatte', category: 'Essen', difficulty: 2 },
  { word: 'Praline', category: 'Essen', difficulty: 3 },
  { word: 'Milchshake', category: 'Essen', difficulty: 2 },
  { word: 'Croissant', category: 'Essen', difficulty: 2 },
  { word: 'Hotdog', category: 'Essen', difficulty: 1 },
  { word: 'Currywurst', category: 'Essen', difficulty: 2 },
  { word: 'Smoothie Bowl', category: 'Essen', difficulty: 3 },

  // Neue Aktionen (20)
  { word: 'Haare foehnen', category: 'Aktionen', difficulty: 2 },
  { word: 'Schneemann bauen', category: 'Aktionen', difficulty: 2 },
  { word: 'Seifenblasen pusten', category: 'Aktionen', difficulty: 2 },
  { word: 'Drachen steigen lassen', category: 'Aktionen', difficulty: 2 },
  { word: 'Schlittschuh laufen', category: 'Aktionen', difficulty: 2 },
  { word: 'Karate machen', category: 'Aktionen', difficulty: 2 },
  { word: 'Geschenke auspacken', category: 'Aktionen', difficulty: 2 },
  { word: 'Seilspringen', category: 'Aktionen', difficulty: 2 },
  { word: 'Huepfburg springen', category: 'Aktionen', difficulty: 2 },
  { word: 'Bowling spielen', category: 'Aktionen', difficulty: 2 },
  { word: 'Waesche aufhaengen', category: 'Aktionen', difficulty: 2 },
  { word: 'Fenster putzen', category: 'Aktionen', difficulty: 2 },
  { word: 'Hunde baden', category: 'Aktionen', difficulty: 3 },
  { word: 'Kuerbis schnitzen', category: 'Aktionen', difficulty: 3 },
  { word: 'Darts werfen', category: 'Aktionen', difficulty: 2 },
  { word: 'Fahrrad reparieren', category: 'Aktionen', difficulty: 3 },
  { word: 'Wasser trinken', category: 'Aktionen', difficulty: 1 },
  { word: 'Selfie machen', category: 'Aktionen', difficulty: 2 },
  { word: 'Skateboard fahren', category: 'Aktionen', difficulty: 2 },
  { word: 'Trampolin springen', category: 'Aktionen', difficulty: 2 },
];
