/**
 * Hochstapler / Impostor — Word Sets in 10 languages.
 * Each word set has a category + word. The impostor gets a different word
 * from the same category, so they have to bluff.
 */

export interface WordSet {
  category: string;
  word: string;
}

// ─── German ──────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_DE: WordSet[] = [
  // Tiere (12)
  { category: 'Tiere', word: 'Elefant' }, { category: 'Tiere', word: 'Pinguin' },
  { category: 'Tiere', word: 'Delfin' }, { category: 'Tiere', word: 'Flamingo' },
  { category: 'Tiere', word: 'Känguru' }, { category: 'Tiere', word: 'Chamäleon' },
  { category: 'Tiere', word: 'Giraffe' }, { category: 'Tiere', word: 'Papagei' },
  { category: 'Tiere', word: 'Schildkröte' }, { category: 'Tiere', word: 'Koala' },
  { category: 'Tiere', word: 'Eisbär' }, { category: 'Tiere', word: 'Waschbär' },
  // Essen (12)
  { category: 'Essen', word: 'Pizza' }, { category: 'Essen', word: 'Sushi' },
  { category: 'Essen', word: 'Schnitzel' }, { category: 'Essen', word: 'Döner' },
  { category: 'Essen', word: 'Tiramisu' }, { category: 'Essen', word: 'Currywurst' },
  { category: 'Essen', word: 'Tacos' }, { category: 'Essen', word: 'Crêpe' },
  { category: 'Essen', word: 'Käsespätzle' }, { category: 'Essen', word: 'Ramen' },
  { category: 'Essen', word: 'Pancakes' }, { category: 'Essen', word: 'Lasagne' },
  // Länder (10)
  { category: 'Länder', word: 'Japan' }, { category: 'Länder', word: 'Brasilien' },
  { category: 'Länder', word: 'Ägypten' }, { category: 'Länder', word: 'Neuseeland' },
  { category: 'Länder', word: 'Island' }, { category: 'Länder', word: 'Kanada' },
  { category: 'Länder', word: 'Thailand' }, { category: 'Länder', word: 'Mexiko' },
  { category: 'Länder', word: 'Südafrika' }, { category: 'Länder', word: 'Norwegen' },
  // Berufe (10)
  { category: 'Berufe', word: 'Feuerwehrmann' }, { category: 'Berufe', word: 'Astronaut' },
  { category: 'Berufe', word: 'Detektiv' }, { category: 'Berufe', word: 'Pilot' },
  { category: 'Berufe', word: 'Tierärztin' }, { category: 'Berufe', word: 'Koch' },
  { category: 'Berufe', word: 'Architekt' }, { category: 'Berufe', word: 'DJ' },
  { category: 'Berufe', word: 'Taucher' }, { category: 'Berufe', word: 'Zauberer' },
  // Filme (10)
  { category: 'Filme', word: 'Titanic' }, { category: 'Filme', word: 'Matrix' },
  { category: 'Filme', word: 'König der Löwen' }, { category: 'Filme', word: 'Star Wars' },
  { category: 'Filme', word: 'Harry Potter' }, { category: 'Filme', word: 'Shrek' },
  { category: 'Filme', word: 'Avengers' }, { category: 'Filme', word: 'Joker' },
  { category: 'Filme', word: 'Forrest Gump' }, { category: 'Filme', word: 'Frozen' },
  // Sport (10)
  { category: 'Sport', word: 'Fußball' }, { category: 'Sport', word: 'Surfen' },
  { category: 'Sport', word: 'Klettern' }, { category: 'Sport', word: 'Eishockey' },
  { category: 'Sport', word: 'Tennis' }, { category: 'Sport', word: 'Skateboarden' },
  { category: 'Sport', word: 'Tauchen' }, { category: 'Sport', word: 'Bogenschießen' },
  { category: 'Sport', word: 'Snowboarden' }, { category: 'Sport', word: 'Yoga' },
  // Orte (8)
  { category: 'Orte', word: 'Strand' }, { category: 'Orte', word: 'Bibliothek' },
  { category: 'Orte', word: 'Freizeitpark' }, { category: 'Orte', word: 'Berggipfel' },
  { category: 'Orte', word: 'Flughafen' }, { category: 'Orte', word: 'Unterwasserwelt' },
  { category: 'Orte', word: 'Dschungel' }, { category: 'Orte', word: 'Raumstation' },
  // Musik (8)
  { category: 'Musik', word: 'Klavier' }, { category: 'Musik', word: 'Schlagzeug' },
  { category: 'Musik', word: 'Gitarre' }, { category: 'Musik', word: 'Saxophon' },
  { category: 'Musik', word: 'Geige' }, { category: 'Musik', word: 'Trompete' },
  { category: 'Musik', word: 'Harfe' }, { category: 'Musik', word: 'Mundharmonika' },
  // Fahrzeuge (8)
  { category: 'Fahrzeuge', word: 'U-Boot' }, { category: 'Fahrzeuge', word: 'Heißluftballon' },
  { category: 'Fahrzeuge', word: 'Skateboard' }, { category: 'Fahrzeuge', word: 'Segelboot' },
  { category: 'Fahrzeuge', word: 'Motorrad' }, { category: 'Fahrzeuge', word: 'Rikscha' },
  { category: 'Fahrzeuge', word: 'Gondel' }, { category: 'Fahrzeuge', word: 'Pferdekutsche' },
  // Natur (8)
  { category: 'Natur', word: 'Vulkan' }, { category: 'Natur', word: 'Regenbogen' },
  { category: 'Natur', word: 'Gletscher' }, { category: 'Natur', word: 'Korallenriff' },
  { category: 'Natur', word: 'Nordlicht' }, { category: 'Natur', word: 'Wasserfall' },
  { category: 'Natur', word: 'Wüste' }, { category: 'Natur', word: 'Tornado' },
  // Superhelden (6)
  { category: 'Superhelden', word: 'Batman' }, { category: 'Superhelden', word: 'Spider-Man' },
  { category: 'Superhelden', word: 'Superman' }, { category: 'Superhelden', word: 'Iron Man' },
  { category: 'Superhelden', word: 'Wonder Woman' }, { category: 'Superhelden', word: 'Hulk' },
  // Märchen (6)
  { category: 'Märchen', word: 'Rotkäppchen' }, { category: 'Märchen', word: 'Aschenputtel' },
  { category: 'Märchen', word: 'Rapunzel' }, { category: 'Märchen', word: 'Schneewittchen' },
  { category: 'Märchen', word: 'Hänsel und Gretel' }, { category: 'Märchen', word: 'Dornröschen' },
];

// ─── English ─────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_EN: WordSet[] = [
  { category: 'Animals', word: 'Elephant' }, { category: 'Animals', word: 'Penguin' },
  { category: 'Animals', word: 'Dolphin' }, { category: 'Animals', word: 'Flamingo' },
  { category: 'Animals', word: 'Kangaroo' }, { category: 'Animals', word: 'Chameleon' },
  { category: 'Animals', word: 'Giraffe' }, { category: 'Animals', word: 'Parrot' },
  { category: 'Animals', word: 'Turtle' }, { category: 'Animals', word: 'Koala' },
  { category: 'Animals', word: 'Polar Bear' }, { category: 'Animals', word: 'Raccoon' },
  { category: 'Food', word: 'Pizza' }, { category: 'Food', word: 'Sushi' },
  { category: 'Food', word: 'Schnitzel' }, { category: 'Food', word: 'Kebab' },
  { category: 'Food', word: 'Tiramisu' }, { category: 'Food', word: 'Curry' },
  { category: 'Food', word: 'Tacos' }, { category: 'Food', word: 'Crêpe' },
  { category: 'Food', word: 'Mac & Cheese' }, { category: 'Food', word: 'Ramen' },
  { category: 'Food', word: 'Pancakes' }, { category: 'Food', word: 'Lasagna' },
  { category: 'Countries', word: 'Japan' }, { category: 'Countries', word: 'Brazil' },
  { category: 'Countries', word: 'Egypt' }, { category: 'Countries', word: 'New Zealand' },
  { category: 'Countries', word: 'Iceland' }, { category: 'Countries', word: 'Canada' },
  { category: 'Countries', word: 'Thailand' }, { category: 'Countries', word: 'Mexico' },
  { category: 'Countries', word: 'South Africa' }, { category: 'Countries', word: 'Norway' },
  { category: 'Jobs', word: 'Firefighter' }, { category: 'Jobs', word: 'Astronaut' },
  { category: 'Jobs', word: 'Detective' }, { category: 'Jobs', word: 'Pilot' },
  { category: 'Jobs', word: 'Veterinarian' }, { category: 'Jobs', word: 'Chef' },
  { category: 'Jobs', word: 'Architect' }, { category: 'Jobs', word: 'DJ' },
  { category: 'Jobs', word: 'Diver' }, { category: 'Jobs', word: 'Magician' },
  { category: 'Movies', word: 'Titanic' }, { category: 'Movies', word: 'The Matrix' },
  { category: 'Movies', word: 'The Lion King' }, { category: 'Movies', word: 'Star Wars' },
  { category: 'Movies', word: 'Harry Potter' }, { category: 'Movies', word: 'Shrek' },
  { category: 'Movies', word: 'Avengers' }, { category: 'Movies', word: 'Joker' },
  { category: 'Movies', word: 'Forrest Gump' }, { category: 'Movies', word: 'Frozen' },
  { category: 'Sports', word: 'Soccer' }, { category: 'Sports', word: 'Surfing' },
  { category: 'Sports', word: 'Climbing' }, { category: 'Sports', word: 'Ice Hockey' },
  { category: 'Sports', word: 'Tennis' }, { category: 'Sports', word: 'Skateboarding' },
  { category: 'Sports', word: 'Diving' }, { category: 'Sports', word: 'Archery' },
  { category: 'Sports', word: 'Snowboarding' }, { category: 'Sports', word: 'Yoga' },
  { category: 'Places', word: 'Beach' }, { category: 'Places', word: 'Library' },
  { category: 'Places', word: 'Theme Park' }, { category: 'Places', word: 'Mountain Peak' },
  { category: 'Places', word: 'Airport' }, { category: 'Places', word: 'Underwater World' },
  { category: 'Places', word: 'Jungle' }, { category: 'Places', word: 'Space Station' },
  { category: 'Music', word: 'Piano' }, { category: 'Music', word: 'Drums' },
  { category: 'Music', word: 'Guitar' }, { category: 'Music', word: 'Saxophone' },
  { category: 'Music', word: 'Violin' }, { category: 'Music', word: 'Trumpet' },
  { category: 'Music', word: 'Harp' }, { category: 'Music', word: 'Harmonica' },
  { category: 'Vehicles', word: 'Submarine' }, { category: 'Vehicles', word: 'Hot Air Balloon' },
  { category: 'Vehicles', word: 'Skateboard' }, { category: 'Vehicles', word: 'Sailboat' },
  { category: 'Vehicles', word: 'Motorcycle' }, { category: 'Vehicles', word: 'Rickshaw' },
  { category: 'Vehicles', word: 'Gondola' }, { category: 'Vehicles', word: 'Horse Carriage' },
  { category: 'Nature', word: 'Volcano' }, { category: 'Nature', word: 'Rainbow' },
  { category: 'Nature', word: 'Glacier' }, { category: 'Nature', word: 'Coral Reef' },
  { category: 'Nature', word: 'Northern Lights' }, { category: 'Nature', word: 'Waterfall' },
  { category: 'Nature', word: 'Desert' }, { category: 'Nature', word: 'Tornado' },
  { category: 'Superheroes', word: 'Batman' }, { category: 'Superheroes', word: 'Spider-Man' },
  { category: 'Superheroes', word: 'Superman' }, { category: 'Superheroes', word: 'Iron Man' },
  { category: 'Superheroes', word: 'Wonder Woman' }, { category: 'Superheroes', word: 'Hulk' },
  { category: 'Fairy Tales', word: 'Little Red Riding Hood' }, { category: 'Fairy Tales', word: 'Cinderella' },
  { category: 'Fairy Tales', word: 'Rapunzel' }, { category: 'Fairy Tales', word: 'Snow White' },
  { category: 'Fairy Tales', word: 'Hansel and Gretel' }, { category: 'Fairy Tales', word: 'Sleeping Beauty' },
];

// ─── Spanish ─────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_ES: WordSet[] = [
  { category: 'Animales', word: 'Elefante' }, { category: 'Animales', word: 'Pingüino' },
  { category: 'Animales', word: 'Delfín' }, { category: 'Animales', word: 'Flamenco' },
  { category: 'Animales', word: 'Canguro' }, { category: 'Animales', word: 'Camaleón' },
  { category: 'Animales', word: 'Jirafa' }, { category: 'Animales', word: 'Loro' },
  { category: 'Animales', word: 'Tortuga' }, { category: 'Animales', word: 'Koala' },
  { category: 'Animales', word: 'Oso polar' }, { category: 'Animales', word: 'Mapache' },
  { category: 'Comida', word: 'Pizza' }, { category: 'Comida', word: 'Sushi' },
  { category: 'Comida', word: 'Milanesa' }, { category: 'Comida', word: 'Kebab' },
  { category: 'Comida', word: 'Tiramisú' }, { category: 'Comida', word: 'Curry' },
  { category: 'Comida', word: 'Tacos' }, { category: 'Comida', word: 'Crêpe' },
  { category: 'Comida', word: 'Paella' }, { category: 'Comida', word: 'Ramen' },
  { category: 'Comida', word: 'Pancakes' }, { category: 'Comida', word: 'Lasaña' },
  { category: 'Países', word: 'Japón' }, { category: 'Países', word: 'Brasil' },
  { category: 'Países', word: 'Egipto' }, { category: 'Países', word: 'Nueva Zelanda' },
  { category: 'Países', word: 'Islandia' }, { category: 'Países', word: 'Canadá' },
  { category: 'Países', word: 'Tailandia' }, { category: 'Países', word: 'México' },
  { category: 'Países', word: 'Sudáfrica' }, { category: 'Países', word: 'Noruega' },
  { category: 'Profesiones', word: 'Bombero' }, { category: 'Profesiones', word: 'Astronauta' },
  { category: 'Profesiones', word: 'Detective' }, { category: 'Profesiones', word: 'Piloto' },
  { category: 'Profesiones', word: 'Veterinaria' }, { category: 'Profesiones', word: 'Chef' },
  { category: 'Profesiones', word: 'Arquitecto' }, { category: 'Profesiones', word: 'DJ' },
  { category: 'Profesiones', word: 'Buceador' }, { category: 'Profesiones', word: 'Mago' },
  { category: 'Películas', word: 'Titanic' }, { category: 'Películas', word: 'Matrix' },
  { category: 'Películas', word: 'El Rey León' }, { category: 'Películas', word: 'Star Wars' },
  { category: 'Películas', word: 'Harry Potter' }, { category: 'Películas', word: 'Shrek' },
  { category: 'Películas', word: 'Avengers' }, { category: 'Películas', word: 'Joker' },
  { category: 'Películas', word: 'Forrest Gump' }, { category: 'Películas', word: 'Frozen' },
  { category: 'Deportes', word: 'Fútbol' }, { category: 'Deportes', word: 'Surf' },
  { category: 'Deportes', word: 'Escalada' }, { category: 'Deportes', word: 'Hockey' },
  { category: 'Deportes', word: 'Tenis' }, { category: 'Deportes', word: 'Skate' },
  { category: 'Deportes', word: 'Buceo' }, { category: 'Deportes', word: 'Tiro con arco' },
  { category: 'Deportes', word: 'Snowboard' }, { category: 'Deportes', word: 'Yoga' },
  { category: 'Lugares', word: 'Playa' }, { category: 'Lugares', word: 'Biblioteca' },
  { category: 'Lugares', word: 'Parque temático' }, { category: 'Lugares', word: 'Cumbre' },
  { category: 'Lugares', word: 'Aeropuerto' }, { category: 'Lugares', word: 'Mundo submarino' },
  { category: 'Lugares', word: 'Selva' }, { category: 'Lugares', word: 'Estación espacial' },
  { category: 'Música', word: 'Piano' }, { category: 'Música', word: 'Batería' },
  { category: 'Música', word: 'Guitarra' }, { category: 'Música', word: 'Saxofón' },
  { category: 'Música', word: 'Violín' }, { category: 'Música', word: 'Trompeta' },
  { category: 'Música', word: 'Arpa' }, { category: 'Música', word: 'Armónica' },
  { category: 'Vehículos', word: 'Submarino' }, { category: 'Vehículos', word: 'Globo aerostático' },
  { category: 'Vehículos', word: 'Monopatín' }, { category: 'Vehículos', word: 'Velero' },
  { category: 'Vehículos', word: 'Motocicleta' }, { category: 'Vehículos', word: 'Rickshaw' },
  { category: 'Vehículos', word: 'Góndola' }, { category: 'Vehículos', word: 'Carruaje' },
  { category: 'Naturaleza', word: 'Volcán' }, { category: 'Naturaleza', word: 'Arcoíris' },
  { category: 'Naturaleza', word: 'Glaciar' }, { category: 'Naturaleza', word: 'Arrecife' },
  { category: 'Naturaleza', word: 'Aurora boreal' }, { category: 'Naturaleza', word: 'Cascada' },
  { category: 'Naturaleza', word: 'Desierto' }, { category: 'Naturaleza', word: 'Tornado' },
  { category: 'Superhéroes', word: 'Batman' }, { category: 'Superhéroes', word: 'Spider-Man' },
  { category: 'Superhéroes', word: 'Superman' }, { category: 'Superhéroes', word: 'Iron Man' },
  { category: 'Superhéroes', word: 'Wonder Woman' }, { category: 'Superhéroes', word: 'Hulk' },
  { category: 'Cuentos', word: 'Caperucita Roja' }, { category: 'Cuentos', word: 'Cenicienta' },
  { category: 'Cuentos', word: 'Rapunzel' }, { category: 'Cuentos', word: 'Blancanieves' },
  { category: 'Cuentos', word: 'Hansel y Gretel' }, { category: 'Cuentos', word: 'La Bella Durmiente' },
];

// ─── French ──────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_FR: WordSet[] = [
  { category: 'Animaux', word: 'Éléphant' }, { category: 'Animaux', word: 'Pingouin' },
  { category: 'Animaux', word: 'Dauphin' }, { category: 'Animaux', word: 'Flamant rose' },
  { category: 'Animaux', word: 'Kangourou' }, { category: 'Animaux', word: 'Caméléon' },
  { category: 'Animaux', word: 'Girafe' }, { category: 'Animaux', word: 'Perroquet' },
  { category: 'Animaux', word: 'Tortue' }, { category: 'Animaux', word: 'Koala' },
  { category: 'Animaux', word: 'Ours polaire' }, { category: 'Animaux', word: 'Raton laveur' },
  { category: 'Nourriture', word: 'Pizza' }, { category: 'Nourriture', word: 'Sushi' },
  { category: 'Nourriture', word: 'Escalope' }, { category: 'Nourriture', word: 'Kebab' },
  { category: 'Nourriture', word: 'Tiramisu' }, { category: 'Nourriture', word: 'Curry' },
  { category: 'Nourriture', word: 'Tacos' }, { category: 'Nourriture', word: 'Crêpe' },
  { category: 'Nourriture', word: 'Gratin' }, { category: 'Nourriture', word: 'Ramen' },
  { category: 'Nourriture', word: 'Pancakes' }, { category: 'Nourriture', word: 'Lasagne' },
  { category: 'Pays', word: 'Japon' }, { category: 'Pays', word: 'Brésil' },
  { category: 'Pays', word: 'Égypte' }, { category: 'Pays', word: 'Nouvelle-Zélande' },
  { category: 'Pays', word: 'Islande' }, { category: 'Pays', word: 'Canada' },
  { category: 'Pays', word: 'Thaïlande' }, { category: 'Pays', word: 'Mexique' },
  { category: 'Pays', word: 'Afrique du Sud' }, { category: 'Pays', word: 'Norvège' },
  { category: 'Métiers', word: 'Pompier' }, { category: 'Métiers', word: 'Astronaute' },
  { category: 'Métiers', word: 'Détective' }, { category: 'Métiers', word: 'Pilote' },
  { category: 'Métiers', word: 'Vétérinaire' }, { category: 'Métiers', word: 'Chef' },
  { category: 'Métiers', word: 'Architecte' }, { category: 'Métiers', word: 'DJ' },
  { category: 'Métiers', word: 'Plongeur' }, { category: 'Métiers', word: 'Magicien' },
  { category: 'Films', word: 'Titanic' }, { category: 'Films', word: 'Matrix' },
  { category: 'Films', word: 'Le Roi Lion' }, { category: 'Films', word: 'Star Wars' },
  { category: 'Films', word: 'Harry Potter' }, { category: 'Films', word: 'Shrek' },
  { category: 'Films', word: 'Avengers' }, { category: 'Films', word: 'Joker' },
  { category: 'Films', word: 'Forrest Gump' }, { category: 'Films', word: 'La Reine des Neiges' },
  { category: 'Sports', word: 'Football' }, { category: 'Sports', word: 'Surf' },
  { category: 'Sports', word: 'Escalade' }, { category: 'Sports', word: 'Hockey' },
  { category: 'Sports', word: 'Tennis' }, { category: 'Sports', word: 'Skateboard' },
  { category: 'Sports', word: 'Plongée' }, { category: 'Sports', word: 'Tir à l\'arc' },
  { category: 'Sports', word: 'Snowboard' }, { category: 'Sports', word: 'Yoga' },
  { category: 'Lieux', word: 'Plage' }, { category: 'Lieux', word: 'Bibliothèque' },
  { category: 'Lieux', word: 'Parc d\'attractions' }, { category: 'Lieux', word: 'Sommet' },
  { category: 'Lieux', word: 'Aéroport' }, { category: 'Lieux', word: 'Monde sous-marin' },
  { category: 'Lieux', word: 'Jungle' }, { category: 'Lieux', word: 'Station spatiale' },
  { category: 'Musique', word: 'Piano' }, { category: 'Musique', word: 'Batterie' },
  { category: 'Musique', word: 'Guitare' }, { category: 'Musique', word: 'Saxophone' },
  { category: 'Musique', word: 'Violon' }, { category: 'Musique', word: 'Trompette' },
  { category: 'Musique', word: 'Harpe' }, { category: 'Musique', word: 'Harmonica' },
  { category: 'Véhicules', word: 'Sous-marin' }, { category: 'Véhicules', word: 'Montgolfière' },
  { category: 'Véhicules', word: 'Planche à roulettes' }, { category: 'Véhicules', word: 'Voilier' },
  { category: 'Véhicules', word: 'Moto' }, { category: 'Véhicules', word: 'Pousse-pousse' },
  { category: 'Véhicules', word: 'Gondole' }, { category: 'Véhicules', word: 'Calèche' },
  { category: 'Nature', word: 'Volcan' }, { category: 'Nature', word: 'Arc-en-ciel' },
  { category: 'Nature', word: 'Glacier' }, { category: 'Nature', word: 'Récif corallien' },
  { category: 'Nature', word: 'Aurore boréale' }, { category: 'Nature', word: 'Cascade' },
  { category: 'Nature', word: 'Désert' }, { category: 'Nature', word: 'Tornade' },
  { category: 'Super-héros', word: 'Batman' }, { category: 'Super-héros', word: 'Spider-Man' },
  { category: 'Super-héros', word: 'Superman' }, { category: 'Super-héros', word: 'Iron Man' },
  { category: 'Super-héros', word: 'Wonder Woman' }, { category: 'Super-héros', word: 'Hulk' },
  { category: 'Contes', word: 'Le Petit Chaperon Rouge' }, { category: 'Contes', word: 'Cendrillon' },
  { category: 'Contes', word: 'Raiponce' }, { category: 'Contes', word: 'Blanche-Neige' },
  { category: 'Contes', word: 'Hansel et Gretel' }, { category: 'Contes', word: 'La Belle au bois dormant' },
];

// ─── Italian ─────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_IT: WordSet[] = [
  { category: 'Animali', word: 'Elefante' }, { category: 'Animali', word: 'Pinguino' },
  { category: 'Animali', word: 'Delfino' }, { category: 'Animali', word: 'Fenicottero' },
  { category: 'Animali', word: 'Canguro' }, { category: 'Animali', word: 'Camaleonte' },
  { category: 'Animali', word: 'Giraffa' }, { category: 'Animali', word: 'Pappagallo' },
  { category: 'Animali', word: 'Tartaruga' }, { category: 'Animali', word: 'Koala' },
  { category: 'Animali', word: 'Orso polare' }, { category: 'Animali', word: 'Procione' },
  { category: 'Cibo', word: 'Pizza' }, { category: 'Cibo', word: 'Sushi' },
  { category: 'Cibo', word: 'Cotoletta' }, { category: 'Cibo', word: 'Kebab' },
  { category: 'Cibo', word: 'Tiramisù' }, { category: 'Cibo', word: 'Curry' },
  { category: 'Cibo', word: 'Tacos' }, { category: 'Cibo', word: 'Crêpe' },
  { category: 'Cibo', word: 'Risotto' }, { category: 'Cibo', word: 'Ramen' },
  { category: 'Cibo', word: 'Pancake' }, { category: 'Cibo', word: 'Lasagna' },
  { category: 'Paesi', word: 'Giappone' }, { category: 'Paesi', word: 'Brasile' },
  { category: 'Paesi', word: 'Egitto' }, { category: 'Paesi', word: 'Nuova Zelanda' },
  { category: 'Paesi', word: 'Islanda' }, { category: 'Paesi', word: 'Canada' },
  { category: 'Paesi', word: 'Thailandia' }, { category: 'Paesi', word: 'Messico' },
  { category: 'Paesi', word: 'Sudafrica' }, { category: 'Paesi', word: 'Norvegia' },
  { category: 'Mestieri', word: 'Pompiere' }, { category: 'Mestieri', word: 'Astronauta' },
  { category: 'Mestieri', word: 'Detective' }, { category: 'Mestieri', word: 'Pilota' },
  { category: 'Mestieri', word: 'Veterinaria' }, { category: 'Mestieri', word: 'Chef' },
  { category: 'Mestieri', word: 'Architetto' }, { category: 'Mestieri', word: 'DJ' },
  { category: 'Mestieri', word: 'Subacqueo' }, { category: 'Mestieri', word: 'Mago' },
  { category: 'Film', word: 'Titanic' }, { category: 'Film', word: 'Matrix' },
  { category: 'Film', word: 'Il Re Leone' }, { category: 'Film', word: 'Star Wars' },
  { category: 'Film', word: 'Harry Potter' }, { category: 'Film', word: 'Shrek' },
  { category: 'Film', word: 'Avengers' }, { category: 'Film', word: 'Joker' },
  { category: 'Film', word: 'Forrest Gump' }, { category: 'Film', word: 'Frozen' },
  { category: 'Sport', word: 'Calcio' }, { category: 'Sport', word: 'Surf' },
  { category: 'Sport', word: 'Arrampicata' }, { category: 'Sport', word: 'Hockey' },
  { category: 'Sport', word: 'Tennis' }, { category: 'Sport', word: 'Skateboard' },
  { category: 'Sport', word: 'Immersione' }, { category: 'Sport', word: 'Tiro con l\'arco' },
  { category: 'Sport', word: 'Snowboard' }, { category: 'Sport', word: 'Yoga' },
  { category: 'Luoghi', word: 'Spiaggia' }, { category: 'Luoghi', word: 'Biblioteca' },
  { category: 'Luoghi', word: 'Parco divertimenti' }, { category: 'Luoghi', word: 'Vetta' },
  { category: 'Luoghi', word: 'Aeroporto' }, { category: 'Luoghi', word: 'Mondo sottomarino' },
  { category: 'Luoghi', word: 'Giungla' }, { category: 'Luoghi', word: 'Stazione spaziale' },
  { category: 'Musica', word: 'Pianoforte' }, { category: 'Musica', word: 'Batteria' },
  { category: 'Musica', word: 'Chitarra' }, { category: 'Musica', word: 'Sassofono' },
  { category: 'Musica', word: 'Violino' }, { category: 'Musica', word: 'Tromba' },
  { category: 'Musica', word: 'Arpa' }, { category: 'Musica', word: 'Armonica' },
  { category: 'Veicoli', word: 'Sottomarino' }, { category: 'Veicoli', word: 'Mongolfiera' },
  { category: 'Veicoli', word: 'Skateboard' }, { category: 'Veicoli', word: 'Barca a vela' },
  { category: 'Veicoli', word: 'Motocicletta' }, { category: 'Veicoli', word: 'Risciò' },
  { category: 'Veicoli', word: 'Gondola' }, { category: 'Veicoli', word: 'Carrozza' },
  { category: 'Natura', word: 'Vulcano' }, { category: 'Natura', word: 'Arcobaleno' },
  { category: 'Natura', word: 'Ghiacciaio' }, { category: 'Natura', word: 'Barriera corallina' },
  { category: 'Natura', word: 'Aurora boreale' }, { category: 'Natura', word: 'Cascata' },
  { category: 'Natura', word: 'Deserto' }, { category: 'Natura', word: 'Tornado' },
  { category: 'Supereroi', word: 'Batman' }, { category: 'Supereroi', word: 'Spider-Man' },
  { category: 'Supereroi', word: 'Superman' }, { category: 'Supereroi', word: 'Iron Man' },
  { category: 'Supereroi', word: 'Wonder Woman' }, { category: 'Supereroi', word: 'Hulk' },
  { category: 'Fiabe', word: 'Cappuccetto Rosso' }, { category: 'Fiabe', word: 'Cenerentola' },
  { category: 'Fiabe', word: 'Raperonzolo' }, { category: 'Fiabe', word: 'Biancaneve' },
  { category: 'Fiabe', word: 'Hansel e Gretel' }, { category: 'Fiabe', word: 'La Bella Addormentata' },
];

// ─── Dutch ───────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_NL: WordSet[] = [
  { category: 'Dieren', word: 'Olifant' }, { category: 'Dieren', word: 'Pinguïn' },
  { category: 'Dieren', word: 'Dolfijn' }, { category: 'Dieren', word: 'Flamingo' },
  { category: 'Dieren', word: 'Kangoeroe' }, { category: 'Dieren', word: 'Kameleon' },
  { category: 'Dieren', word: 'Giraf' }, { category: 'Dieren', word: 'Papegaai' },
  { category: 'Dieren', word: 'Schildpad' }, { category: 'Dieren', word: 'Koala' },
  { category: 'Dieren', word: 'IJsbeer' }, { category: 'Dieren', word: 'Wasbeer' },
  { category: 'Eten', word: 'Pizza' }, { category: 'Eten', word: 'Sushi' },
  { category: 'Eten', word: 'Schnitzel' }, { category: 'Eten', word: 'Kebab' },
  { category: 'Eten', word: 'Tiramisu' }, { category: 'Eten', word: 'Curry' },
  { category: 'Eten', word: 'Taco\'s' }, { category: 'Eten', word: 'Crêpe' },
  { category: 'Eten', word: 'Stamppot' }, { category: 'Eten', word: 'Ramen' },
  { category: 'Eten', word: 'Pannenkoeken' }, { category: 'Eten', word: 'Lasagne' },
  { category: 'Landen', word: 'Japan' }, { category: 'Landen', word: 'Brazilië' },
  { category: 'Landen', word: 'Egypte' }, { category: 'Landen', word: 'Nieuw-Zeeland' },
  { category: 'Landen', word: 'IJsland' }, { category: 'Landen', word: 'Canada' },
  { category: 'Landen', word: 'Thailand' }, { category: 'Landen', word: 'Mexico' },
  { category: 'Landen', word: 'Zuid-Afrika' }, { category: 'Landen', word: 'Noorwegen' },
  { category: 'Beroepen', word: 'Brandweerman' }, { category: 'Beroepen', word: 'Astronaut' },
  { category: 'Beroepen', word: 'Detective' }, { category: 'Beroepen', word: 'Piloot' },
  { category: 'Beroepen', word: 'Dierenarts' }, { category: 'Beroepen', word: 'Kok' },
  { category: 'Beroepen', word: 'Architect' }, { category: 'Beroepen', word: 'DJ' },
  { category: 'Beroepen', word: 'Duiker' }, { category: 'Beroepen', word: 'Goochelaar' },
  { category: 'Films', word: 'Titanic' }, { category: 'Films', word: 'Matrix' },
  { category: 'Films', word: 'De Leeuwenkoning' }, { category: 'Films', word: 'Star Wars' },
  { category: 'Films', word: 'Harry Potter' }, { category: 'Films', word: 'Shrek' },
  { category: 'Films', word: 'Avengers' }, { category: 'Films', word: 'Joker' },
  { category: 'Films', word: 'Forrest Gump' }, { category: 'Films', word: 'Frozen' },
  { category: 'Sport', word: 'Voetbal' }, { category: 'Sport', word: 'Surfen' },
  { category: 'Sport', word: 'Klimmen' }, { category: 'Sport', word: 'IJshockey' },
  { category: 'Sport', word: 'Tennis' }, { category: 'Sport', word: 'Skateboarden' },
  { category: 'Sport', word: 'Duiken' }, { category: 'Sport', word: 'Boogschieten' },
  { category: 'Sport', word: 'Snowboarden' }, { category: 'Sport', word: 'Yoga' },
  { category: 'Plaatsen', word: 'Strand' }, { category: 'Plaatsen', word: 'Bibliotheek' },
  { category: 'Plaatsen', word: 'Pretpark' }, { category: 'Plaatsen', word: 'Bergtop' },
  { category: 'Plaatsen', word: 'Vliegveld' }, { category: 'Plaatsen', word: 'Onderwaterwereld' },
  { category: 'Plaatsen', word: 'Jungle' }, { category: 'Plaatsen', word: 'Ruimtestation' },
  { category: 'Muziek', word: 'Piano' }, { category: 'Muziek', word: 'Drums' },
  { category: 'Muziek', word: 'Gitaar' }, { category: 'Muziek', word: 'Saxofoon' },
  { category: 'Muziek', word: 'Viool' }, { category: 'Muziek', word: 'Trompet' },
  { category: 'Muziek', word: 'Harp' }, { category: 'Muziek', word: 'Mondharmonica' },
  { category: 'Voertuigen', word: 'Onderzeeër' }, { category: 'Voertuigen', word: 'Luchtballon' },
  { category: 'Voertuigen', word: 'Skateboard' }, { category: 'Voertuigen', word: 'Zeilboot' },
  { category: 'Voertuigen', word: 'Motor' }, { category: 'Voertuigen', word: 'Riksja' },
  { category: 'Voertuigen', word: 'Gondel' }, { category: 'Voertuigen', word: 'Paardenkoets' },
  { category: 'Natuur', word: 'Vulkaan' }, { category: 'Natuur', word: 'Regenboog' },
  { category: 'Natuur', word: 'Gletsjer' }, { category: 'Natuur', word: 'Koraalrif' },
  { category: 'Natuur', word: 'Noorderlicht' }, { category: 'Natuur', word: 'Waterval' },
  { category: 'Natuur', word: 'Woestijn' }, { category: 'Natuur', word: 'Tornado' },
  { category: 'Superhelden', word: 'Batman' }, { category: 'Superhelden', word: 'Spider-Man' },
  { category: 'Superhelden', word: 'Superman' }, { category: 'Superhelden', word: 'Iron Man' },
  { category: 'Superhelden', word: 'Wonder Woman' }, { category: 'Superhelden', word: 'Hulk' },
  { category: 'Sprookjes', word: 'Roodkapje' }, { category: 'Sprookjes', word: 'Assepoester' },
  { category: 'Sprookjes', word: 'Rapunzel' }, { category: 'Sprookjes', word: 'Sneeuwwitje' },
  { category: 'Sprookjes', word: 'Hans en Grietje' }, { category: 'Sprookjes', word: 'Doornroosje' },
];

// ─── Polish ──────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_PL: WordSet[] = [
  { category: 'Zwierzęta', word: 'Słoń' }, { category: 'Zwierzęta', word: 'Pingwin' },
  { category: 'Zwierzęta', word: 'Delfin' }, { category: 'Zwierzęta', word: 'Flaming' },
  { category: 'Zwierzęta', word: 'Kangur' }, { category: 'Zwierzęta', word: 'Kameleon' },
  { category: 'Zwierzęta', word: 'Żyrafa' }, { category: 'Zwierzęta', word: 'Papuga' },
  { category: 'Zwierzęta', word: 'Żółw' }, { category: 'Zwierzęta', word: 'Koala' },
  { category: 'Zwierzęta', word: 'Niedźwiedź polarny' }, { category: 'Zwierzęta', word: 'Szop' },
  { category: 'Jedzenie', word: 'Pizza' }, { category: 'Jedzenie', word: 'Sushi' },
  { category: 'Jedzenie', word: 'Sznycel' }, { category: 'Jedzenie', word: 'Kebab' },
  { category: 'Jedzenie', word: 'Tiramisu' }, { category: 'Jedzenie', word: 'Curry' },
  { category: 'Jedzenie', word: 'Tacos' }, { category: 'Jedzenie', word: 'Naleśnik' },
  { category: 'Jedzenie', word: 'Pierogi' }, { category: 'Jedzenie', word: 'Ramen' },
  { category: 'Jedzenie', word: 'Placki' }, { category: 'Jedzenie', word: 'Lazania' },
  { category: 'Kraje', word: 'Japonia' }, { category: 'Kraje', word: 'Brazylia' },
  { category: 'Kraje', word: 'Egipt' }, { category: 'Kraje', word: 'Nowa Zelandia' },
  { category: 'Kraje', word: 'Islandia' }, { category: 'Kraje', word: 'Kanada' },
  { category: 'Kraje', word: 'Tajlandia' }, { category: 'Kraje', word: 'Meksyk' },
  { category: 'Kraje', word: 'RPA' }, { category: 'Kraje', word: 'Norwegia' },
  { category: 'Zawody', word: 'Strażak' }, { category: 'Zawody', word: 'Astronauta' },
  { category: 'Zawody', word: 'Detektyw' }, { category: 'Zawody', word: 'Pilot' },
  { category: 'Zawody', word: 'Weterynarz' }, { category: 'Zawody', word: 'Kucharz' },
  { category: 'Zawody', word: 'Architekt' }, { category: 'Zawody', word: 'DJ' },
  { category: 'Zawody', word: 'Nurek' }, { category: 'Zawody', word: 'Magik' },
  { category: 'Filmy', word: 'Titanic' }, { category: 'Filmy', word: 'Matrix' },
  { category: 'Filmy', word: 'Król Lew' }, { category: 'Filmy', word: 'Gwiezdne Wojny' },
  { category: 'Filmy', word: 'Harry Potter' }, { category: 'Filmy', word: 'Shrek' },
  { category: 'Filmy', word: 'Avengers' }, { category: 'Filmy', word: 'Joker' },
  { category: 'Filmy', word: 'Forrest Gump' }, { category: 'Filmy', word: 'Kraina Lodu' },
  { category: 'Sport', word: 'Piłka nożna' }, { category: 'Sport', word: 'Surfing' },
  { category: 'Sport', word: 'Wspinaczka' }, { category: 'Sport', word: 'Hokej' },
  { category: 'Sport', word: 'Tenis' }, { category: 'Sport', word: 'Deskorolka' },
  { category: 'Sport', word: 'Nurkowanie' }, { category: 'Sport', word: 'Łucznictwo' },
  { category: 'Sport', word: 'Snowboard' }, { category: 'Sport', word: 'Joga' },
  { category: 'Miejsca', word: 'Plaża' }, { category: 'Miejsca', word: 'Biblioteka' },
  { category: 'Miejsca', word: 'Park rozrywki' }, { category: 'Miejsca', word: 'Szczyt' },
  { category: 'Miejsca', word: 'Lotnisko' }, { category: 'Miejsca', word: 'Podwodny świat' },
  { category: 'Miejsca', word: 'Dżungla' }, { category: 'Miejsca', word: 'Stacja kosmiczna' },
  { category: 'Muzyka', word: 'Pianino' }, { category: 'Muzyka', word: 'Perkusja' },
  { category: 'Muzyka', word: 'Gitara' }, { category: 'Muzyka', word: 'Saksofon' },
  { category: 'Muzyka', word: 'Skrzypce' }, { category: 'Muzyka', word: 'Trąbka' },
  { category: 'Muzyka', word: 'Harfa' }, { category: 'Muzyka', word: 'Harmonijka' },
  { category: 'Pojazdy', word: 'Łódź podwodna' }, { category: 'Pojazdy', word: 'Balon' },
  { category: 'Pojazdy', word: 'Deskorolka' }, { category: 'Pojazdy', word: 'Żaglówka' },
  { category: 'Pojazdy', word: 'Motocykl' }, { category: 'Pojazdy', word: 'Riksza' },
  { category: 'Pojazdy', word: 'Gondola' }, { category: 'Pojazdy', word: 'Kareta' },
  { category: 'Natura', word: 'Wulkan' }, { category: 'Natura', word: 'Tęcza' },
  { category: 'Natura', word: 'Lodowiec' }, { category: 'Natura', word: 'Rafa koralowa' },
  { category: 'Natura', word: 'Zorza polarna' }, { category: 'Natura', word: 'Wodospad' },
  { category: 'Natura', word: 'Pustynia' }, { category: 'Natura', word: 'Tornado' },
  { category: 'Superbohaterowie', word: 'Batman' }, { category: 'Superbohaterowie', word: 'Spider-Man' },
  { category: 'Superbohaterowie', word: 'Superman' }, { category: 'Superbohaterowie', word: 'Iron Man' },
  { category: 'Superbohaterowie', word: 'Wonder Woman' }, { category: 'Superbohaterowie', word: 'Hulk' },
  { category: 'Baśnie', word: 'Czerwony Kapturek' }, { category: 'Baśnie', word: 'Kopciuszek' },
  { category: 'Baśnie', word: 'Roszpunka' }, { category: 'Baśnie', word: 'Królewna Śnieżka' },
  { category: 'Baśnie', word: 'Jaś i Małgosia' }, { category: 'Baśnie', word: 'Śpiąca Królewna' },
];

// ─── Portuguese ──────────────────────────────────────────────────
export const IMPOSTOR_WORDS_PT: WordSet[] = [
  { category: 'Animais', word: 'Elefante' }, { category: 'Animais', word: 'Pinguim' },
  { category: 'Animais', word: 'Golfinho' }, { category: 'Animais', word: 'Flamingo' },
  { category: 'Animais', word: 'Canguru' }, { category: 'Animais', word: 'Camaleão' },
  { category: 'Animais', word: 'Girafa' }, { category: 'Animais', word: 'Papagaio' },
  { category: 'Animais', word: 'Tartaruga' }, { category: 'Animais', word: 'Coala' },
  { category: 'Animais', word: 'Urso polar' }, { category: 'Animais', word: 'Guaxinim' },
  { category: 'Comida', word: 'Pizza' }, { category: 'Comida', word: 'Sushi' },
  { category: 'Comida', word: 'Schnitzel' }, { category: 'Comida', word: 'Kebab' },
  { category: 'Comida', word: 'Tiramisu' }, { category: 'Comida', word: 'Curry' },
  { category: 'Comida', word: 'Tacos' }, { category: 'Comida', word: 'Crêpe' },
  { category: 'Comida', word: 'Feijoada' }, { category: 'Comida', word: 'Ramen' },
  { category: 'Comida', word: 'Panquecas' }, { category: 'Comida', word: 'Lasanha' },
  { category: 'Países', word: 'Japão' }, { category: 'Países', word: 'Brasil' },
  { category: 'Países', word: 'Egito' }, { category: 'Países', word: 'Nova Zelândia' },
  { category: 'Países', word: 'Islândia' }, { category: 'Países', word: 'Canadá' },
  { category: 'Países', word: 'Tailândia' }, { category: 'Países', word: 'México' },
  { category: 'Países', word: 'África do Sul' }, { category: 'Países', word: 'Noruega' },
  { category: 'Profissões', word: 'Bombeiro' }, { category: 'Profissões', word: 'Astronauta' },
  { category: 'Profissões', word: 'Detetive' }, { category: 'Profissões', word: 'Piloto' },
  { category: 'Profissões', word: 'Veterinária' }, { category: 'Profissões', word: 'Chef' },
  { category: 'Profissões', word: 'Arquiteto' }, { category: 'Profissões', word: 'DJ' },
  { category: 'Profissões', word: 'Mergulhador' }, { category: 'Profissões', word: 'Mágico' },
  { category: 'Filmes', word: 'Titanic' }, { category: 'Filmes', word: 'Matrix' },
  { category: 'Filmes', word: 'O Rei Leão' }, { category: 'Filmes', word: 'Star Wars' },
  { category: 'Filmes', word: 'Harry Potter' }, { category: 'Filmes', word: 'Shrek' },
  { category: 'Filmes', word: 'Vingadores' }, { category: 'Filmes', word: 'Coringa' },
  { category: 'Filmes', word: 'Forrest Gump' }, { category: 'Filmes', word: 'Frozen' },
  { category: 'Esportes', word: 'Futebol' }, { category: 'Esportes', word: 'Surf' },
  { category: 'Esportes', word: 'Escalada' }, { category: 'Esportes', word: 'Hóquei' },
  { category: 'Esportes', word: 'Tênis' }, { category: 'Esportes', word: 'Skate' },
  { category: 'Esportes', word: 'Mergulho' }, { category: 'Esportes', word: 'Arco e flecha' },
  { category: 'Esportes', word: 'Snowboard' }, { category: 'Esportes', word: 'Ioga' },
  { category: 'Lugares', word: 'Praia' }, { category: 'Lugares', word: 'Biblioteca' },
  { category: 'Lugares', word: 'Parque temático' }, { category: 'Lugares', word: 'Cume' },
  { category: 'Lugares', word: 'Aeroporto' }, { category: 'Lugares', word: 'Mundo submarino' },
  { category: 'Lugares', word: 'Selva' }, { category: 'Lugares', word: 'Estação espacial' },
  { category: 'Música', word: 'Piano' }, { category: 'Música', word: 'Bateria' },
  { category: 'Música', word: 'Guitarra' }, { category: 'Música', word: 'Saxofone' },
  { category: 'Música', word: 'Violino' }, { category: 'Música', word: 'Trompete' },
  { category: 'Música', word: 'Harpa' }, { category: 'Música', word: 'Gaita' },
  { category: 'Veículos', word: 'Submarino' }, { category: 'Veículos', word: 'Balão' },
  { category: 'Veículos', word: 'Skate' }, { category: 'Veículos', word: 'Veleiro' },
  { category: 'Veículos', word: 'Motocicleta' }, { category: 'Veículos', word: 'Riquixá' },
  { category: 'Veículos', word: 'Gôndola' }, { category: 'Veículos', word: 'Carruagem' },
  { category: 'Natureza', word: 'Vulcão' }, { category: 'Natureza', word: 'Arco-íris' },
  { category: 'Natureza', word: 'Glaciar' }, { category: 'Natureza', word: 'Recife de coral' },
  { category: 'Natureza', word: 'Aurora boreal' }, { category: 'Natureza', word: 'Cascata' },
  { category: 'Natureza', word: 'Deserto' }, { category: 'Natureza', word: 'Tornado' },
  { category: 'Super-heróis', word: 'Batman' }, { category: 'Super-heróis', word: 'Homem-Aranha' },
  { category: 'Super-heróis', word: 'Superman' }, { category: 'Super-heróis', word: 'Homem de Ferro' },
  { category: 'Super-heróis', word: 'Mulher-Maravilha' }, { category: 'Super-heróis', word: 'Hulk' },
  { category: 'Contos', word: 'Chapeuzinho Vermelho' }, { category: 'Contos', word: 'Cinderela' },
  { category: 'Contos', word: 'Rapunzel' }, { category: 'Contos', word: 'Branca de Neve' },
  { category: 'Contos', word: 'João e Maria' }, { category: 'Contos', word: 'A Bela Adormecida' },
];

// ─── Turkish ─────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_TR: WordSet[] = [
  { category: 'Hayvanlar', word: 'Fil' }, { category: 'Hayvanlar', word: 'Penguen' },
  { category: 'Hayvanlar', word: 'Yunus' }, { category: 'Hayvanlar', word: 'Flamingo' },
  { category: 'Hayvanlar', word: 'Kanguru' }, { category: 'Hayvanlar', word: 'Bukalemun' },
  { category: 'Hayvanlar', word: 'Zürafa' }, { category: 'Hayvanlar', word: 'Papağan' },
  { category: 'Hayvanlar', word: 'Kaplumbağa' }, { category: 'Hayvanlar', word: 'Koala' },
  { category: 'Hayvanlar', word: 'Kutup ayısı' }, { category: 'Hayvanlar', word: 'Rakun' },
  { category: 'Yemek', word: 'Pizza' }, { category: 'Yemek', word: 'Suşi' },
  { category: 'Yemek', word: 'Şnitzel' }, { category: 'Yemek', word: 'Kebap' },
  { category: 'Yemek', word: 'Tiramisu' }, { category: 'Yemek', word: 'Köri' },
  { category: 'Yemek', word: 'Taco' }, { category: 'Yemek', word: 'Krep' },
  { category: 'Yemek', word: 'Mantı' }, { category: 'Yemek', word: 'Ramen' },
  { category: 'Yemek', word: 'Gözleme' }, { category: 'Yemek', word: 'Lazanya' },
  { category: 'Ülkeler', word: 'Japonya' }, { category: 'Ülkeler', word: 'Brezilya' },
  { category: 'Ülkeler', word: 'Mısır' }, { category: 'Ülkeler', word: 'Yeni Zelanda' },
  { category: 'Ülkeler', word: 'İzlanda' }, { category: 'Ülkeler', word: 'Kanada' },
  { category: 'Ülkeler', word: 'Tayland' }, { category: 'Ülkeler', word: 'Meksika' },
  { category: 'Ülkeler', word: 'Güney Afrika' }, { category: 'Ülkeler', word: 'Norveç' },
  { category: 'Meslekler', word: 'İtfaiyeci' }, { category: 'Meslekler', word: 'Astronot' },
  { category: 'Meslekler', word: 'Dedektif' }, { category: 'Meslekler', word: 'Pilot' },
  { category: 'Meslekler', word: 'Veteriner' }, { category: 'Meslekler', word: 'Şef' },
  { category: 'Meslekler', word: 'Mimar' }, { category: 'Meslekler', word: 'DJ' },
  { category: 'Meslekler', word: 'Dalgıç' }, { category: 'Meslekler', word: 'Sihirbaz' },
  { category: 'Filmler', word: 'Titanic' }, { category: 'Filmler', word: 'Matrix' },
  { category: 'Filmler', word: 'Aslan Kral' }, { category: 'Filmler', word: 'Yıldız Savaşları' },
  { category: 'Filmler', word: 'Harry Potter' }, { category: 'Filmler', word: 'Shrek' },
  { category: 'Filmler', word: 'Yenilmezler' }, { category: 'Filmler', word: 'Joker' },
  { category: 'Filmler', word: 'Forrest Gump' }, { category: 'Filmler', word: 'Karlar Ülkesi' },
  { category: 'Spor', word: 'Futbol' }, { category: 'Spor', word: 'Sörf' },
  { category: 'Spor', word: 'Tırmanış' }, { category: 'Spor', word: 'Buz hokeyi' },
  { category: 'Spor', word: 'Tenis' }, { category: 'Spor', word: 'Kaykay' },
  { category: 'Spor', word: 'Dalış' }, { category: 'Spor', word: 'Okçuluk' },
  { category: 'Spor', word: 'Snowboard' }, { category: 'Spor', word: 'Yoga' },
  { category: 'Yerler', word: 'Plaj' }, { category: 'Yerler', word: 'Kütüphane' },
  { category: 'Yerler', word: 'Lunapark' }, { category: 'Yerler', word: 'Zirve' },
  { category: 'Yerler', word: 'Havalimanı' }, { category: 'Yerler', word: 'Sualtı dünyası' },
  { category: 'Yerler', word: 'Orman' }, { category: 'Yerler', word: 'Uzay istasyonu' },
  { category: 'Müzik', word: 'Piyano' }, { category: 'Müzik', word: 'Davul' },
  { category: 'Müzik', word: 'Gitar' }, { category: 'Müzik', word: 'Saksafon' },
  { category: 'Müzik', word: 'Keman' }, { category: 'Müzik', word: 'Trompet' },
  { category: 'Müzik', word: 'Arp' }, { category: 'Müzik', word: 'Mızıka' },
  { category: 'Araçlar', word: 'Denizaltı' }, { category: 'Araçlar', word: 'Balon' },
  { category: 'Araçlar', word: 'Kaykay' }, { category: 'Araçlar', word: 'Yelkenli' },
  { category: 'Araçlar', word: 'Motosiklet' }, { category: 'Araçlar', word: 'Çekçek' },
  { category: 'Araçlar', word: 'Gondol' }, { category: 'Araçlar', word: 'At arabası' },
  { category: 'Doğa', word: 'Yanardağ' }, { category: 'Doğa', word: 'Gökkuşağı' },
  { category: 'Doğa', word: 'Buzul' }, { category: 'Doğa', word: 'Mercan resifi' },
  { category: 'Doğa', word: 'Kuzey ışıkları' }, { category: 'Doğa', word: 'Şelale' },
  { category: 'Doğa', word: 'Çöl' }, { category: 'Doğa', word: 'Kasırga' },
  { category: 'Süper kahramanlar', word: 'Batman' }, { category: 'Süper kahramanlar', word: 'Örümcek Adam' },
  { category: 'Süper kahramanlar', word: 'Süpermen' }, { category: 'Süper kahramanlar', word: 'Demir Adam' },
  { category: 'Süper kahramanlar', word: 'Wonder Woman' }, { category: 'Süper kahramanlar', word: 'Hulk' },
  { category: 'Masallar', word: 'Kırmızı Başlıklı Kız' }, { category: 'Masallar', word: 'Külkedisi' },
  { category: 'Masallar', word: 'Rapunzel' }, { category: 'Masallar', word: 'Pamuk Prenses' },
  { category: 'Masallar', word: 'Hansel ve Gretel' }, { category: 'Masallar', word: 'Uyuyan Güzel' },
];

// ─── Arabic ──────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_AR: WordSet[] = [
  { category: 'حيوانات', word: 'فيل' }, { category: 'حيوانات', word: 'بطريق' },
  { category: 'حيوانات', word: 'دلفين' }, { category: 'حيوانات', word: 'فلامنغو' },
  { category: 'حيوانات', word: 'كنغر' }, { category: 'حيوانات', word: 'حرباء' },
  { category: 'حيوانات', word: 'زرافة' }, { category: 'حيوانات', word: 'ببغاء' },
  { category: 'حيوانات', word: 'سلحفاة' }, { category: 'حيوانات', word: 'كوالا' },
  { category: 'حيوانات', word: 'دب قطبي' }, { category: 'حيوانات', word: 'راكون' },
  { category: 'طعام', word: 'بيتزا' }, { category: 'طعام', word: 'سوشي' },
  { category: 'طعام', word: 'شنيتزل' }, { category: 'طعام', word: 'كباب' },
  { category: 'طعام', word: 'تيراميسو' }, { category: 'طعام', word: 'كاري' },
  { category: 'طعام', word: 'تاكو' }, { category: 'طعام', word: 'كريب' },
  { category: 'طعام', word: 'كشري' }, { category: 'طعام', word: 'رامن' },
  { category: 'طعام', word: 'فطائر' }, { category: 'طعام', word: 'لازانيا' },
  { category: 'دول', word: 'اليابان' }, { category: 'دول', word: 'البرازيل' },
  { category: 'دول', word: 'مصر' }, { category: 'دول', word: 'نيوزيلندا' },
  { category: 'دول', word: 'آيسلندا' }, { category: 'دول', word: 'كندا' },
  { category: 'دول', word: 'تايلاند' }, { category: 'دول', word: 'المكسيك' },
  { category: 'دول', word: 'جنوب أفريقيا' }, { category: 'دول', word: 'النرويج' },
  { category: 'مهن', word: 'رجل إطفاء' }, { category: 'مهن', word: 'رائد فضاء' },
  { category: 'مهن', word: 'محقق' }, { category: 'مهن', word: 'طيار' },
  { category: 'مهن', word: 'طبيب بيطري' }, { category: 'مهن', word: 'طاهٍ' },
  { category: 'مهن', word: 'مهندس معماري' }, { category: 'مهن', word: 'دي جي' },
  { category: 'مهن', word: 'غواص' }, { category: 'مهن', word: 'ساحر' },
  { category: 'أفلام', word: 'تايتانيك' }, { category: 'أفلام', word: 'ماتريكس' },
  { category: 'أفلام', word: 'الأسد الملك' }, { category: 'أفلام', word: 'حرب النجوم' },
  { category: 'أفلام', word: 'هاري بوتر' }, { category: 'أفلام', word: 'شريك' },
  { category: 'أفلام', word: 'المنتقمون' }, { category: 'أفلام', word: 'الجوكر' },
  { category: 'أفلام', word: 'فورست غامب' }, { category: 'أفلام', word: 'فروزن' },
  { category: 'رياضة', word: 'كرة القدم' }, { category: 'رياضة', word: 'ركوب الأمواج' },
  { category: 'رياضة', word: 'تسلق' }, { category: 'رياضة', word: 'هوكي الجليد' },
  { category: 'رياضة', word: 'تنس' }, { category: 'رياضة', word: 'تزلج' },
  { category: 'رياضة', word: 'غوص' }, { category: 'رياضة', word: 'رماية بالقوس' },
  { category: 'رياضة', word: 'تزلج على الثلج' }, { category: 'رياضة', word: 'يوغا' },
  { category: 'أماكن', word: 'شاطئ' }, { category: 'أماكن', word: 'مكتبة' },
  { category: 'أماكن', word: 'مدينة ملاهي' }, { category: 'أماكن', word: 'قمة جبل' },
  { category: 'أماكن', word: 'مطار' }, { category: 'أماكن', word: 'عالم تحت الماء' },
  { category: 'أماكن', word: 'غابة' }, { category: 'أماكن', word: 'محطة فضائية' },
  { category: 'موسيقى', word: 'بيانو' }, { category: 'موسيقى', word: 'طبول' },
  { category: 'موسيقى', word: 'جيتار' }, { category: 'موسيقى', word: 'ساكسفون' },
  { category: 'موسيقى', word: 'كمان' }, { category: 'موسيقى', word: 'بوق' },
  { category: 'موسيقى', word: 'قيثارة' }, { category: 'موسيقى', word: 'هارمونيكا' },
  { category: 'مركبات', word: 'غواصة' }, { category: 'مركبات', word: 'منطاد' },
  { category: 'مركبات', word: 'لوح تزلج' }, { category: 'مركبات', word: 'قارب شراعي' },
  { category: 'مركبات', word: 'دراجة نارية' }, { category: 'مركبات', word: 'عربة يد' },
  { category: 'مركبات', word: 'جندول' }, { category: 'مركبات', word: 'عربة حصان' },
  { category: 'طبيعة', word: 'بركان' }, { category: 'طبيعة', word: 'قوس قزح' },
  { category: 'طبيعة', word: 'نهر جليدي' }, { category: 'طبيعة', word: 'شعاب مرجانية' },
  { category: 'طبيعة', word: 'شفق قطبي' }, { category: 'طبيعة', word: 'شلال' },
  { category: 'طبيعة', word: 'صحراء' }, { category: 'طبيعة', word: 'إعصار' },
  { category: 'أبطال خارقون', word: 'باتمان' }, { category: 'أبطال خارقون', word: 'سبايدرمان' },
  { category: 'أبطال خارقون', word: 'سوبرمان' }, { category: 'أبطال خارقون', word: 'آيرون مان' },
  { category: 'أبطال خارقون', word: 'وندر وومن' }, { category: 'أبطال خارقون', word: 'هالك' },
  { category: 'قصص', word: 'ليلى والذئب' }, { category: 'قصص', word: 'سندريلا' },
  { category: 'قصص', word: 'رابونزل' }, { category: 'قصص', word: 'بياض الثلج' },
  { category: 'قصص', word: 'هانسل وغريتل' }, { category: 'قصص', word: 'الجميلة النائمة' },
];
