/**
 * Hochstapler / Impostor — Word Sets in 10 languages.
 * Each word set has a category + word. The impostor gets a different word
 * from the same category, so they have to bluff.
 */

export interface WordSet {
  category: string;
  word: string;
}

// ─── German ──────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_DE: WordSet[] = [
  // Tiere (12)
  { category: 'Tiere', word: 'Elefant' }, { category: 'Tiere', word: 'Pinguin' },
  { category: 'Tiere', word: 'Delfin' }, { category: 'Tiere', word: 'Flamingo' },
  { category: 'Tiere', word: 'Känguru' }, { category: 'Tiere', word: 'Chamäleon' },
  { category: 'Tiere', word: 'Giraffe' }, { category: 'Tiere', word: 'Papagei' },
  { category: 'Tiere', word: 'Schildkröte' }, { category: 'Tiere', word: 'Koala' },
  { category: 'Tiere', word: 'Eisbär' }, { category: 'Tiere', word: 'Waschbär' },
  // Essen (12)
  { category: 'Essen', word: 'Pizza' }, { category: 'Essen', word: 'Sushi' },
  { category: 'Essen', word: 'Schnitzel' }, { category: 'Essen', word: 'Döner' },
  { category: 'Essen', word: 'Tiramisu' }, { category: 'Essen', word: 'Currywurst' },
  { category: 'Essen', word: 'Tacos' }, { category: 'Essen', word: 'Crêpe' },
  { category: 'Essen', word: 'Käsespätzle' }, { category: 'Essen', word: 'Ramen' },
  { category: 'Essen', word: 'Pancakes' }, { category: 'Essen', word: 'Lasagne' },
  // Länder (10)
  { category: 'Länder', word: 'Japan' }, { category: 'Länder', word: 'Brasilien' },
  { category: 'Länder', word: 'Ägypten' }, { category: 'Länder', word: 'Neuseeland' },
  { category: 'Länder', word: 'Island' }, { category: 'Länder', word: 'Kanada' },
  { category: 'Länder', word: 'Thailand' }, { category: 'Länder', word: 'Mexiko' },
  { category: 'Länder', word: 'Südafrika' }, { category: 'Länder', word: 'Norwegen' },
  // Berufe (10)
  { category: 'Berufe', word: 'Feuerwehrmann' }, { category: 'Berufe', word: 'Astronaut' },
  { category: 'Berufe', word: 'Detektiv' }, { category: 'Berufe', word: 'Pilot' },
  { category: 'Berufe', word: 'Tierärztin' }, { category: 'Berufe', word: 'Koch' },
  { category: 'Berufe', word: 'Architekt' }, { category: 'Berufe', word: 'DJ' },
  { category: 'Berufe', word: 'Taucher' }, { category: 'Berufe', word: 'Zauberer' },
  // Filme (10)
  { category: 'Filme', word: 'Titanic' }, { category: 'Filme', word: 'Matrix' },
  { category: 'Filme', word: 'König der Löwen' }, { category: 'Filme', word: 'Star Wars' },
  { category: 'Filme', word: 'Harry Potter' }, { category: 'Filme', word: 'Shrek' },
  { category: 'Filme', word: 'Avengers' }, { category: 'Filme', word: 'Joker' },
  { category: 'Filme', word: 'Forrest Gump' }, { category: 'Filme', word: 'Frozen' },
  // Sport (10)
  { category: 'Sport', word: 'Fußball' }, { category: 'Sport', word: 'Surfen' },
  { category: 'Sport', word: 'Klettern' }, { category: 'Sport', word: 'Eishockey' },
  { category: 'Sport', word: 'Tennis' }, { category: 'Sport', word: 'Skateboarden' },
  { category: 'Sport', word: 'Tauchen' }, { category: 'Sport', word: 'Bogenschießen' },
  { category: 'Sport', word: 'Snowboarden' }, { category: 'Sport', word: 'Yoga' },
  // Orte (8)
  { category: 'Orte', word: 'Strand' }, { category: 'Orte', word: 'Bibliothek' },
  { category: 'Orte', word: 'Freizeitpark' }, { category: 'Orte', word: 'Berggipfel' },
  { category: 'Orte', word: 'Flughafen' }, { category: 'Orte', word: 'Unterwasserwelt' },
  { category: 'Orte', word: 'Dschungel' }, { category: 'Orte', word: 'Raumstation' },
  // Musik (8)
  { category: 'Musik', word: 'Klavier' }, { category: 'Musik', word: 'Schlagzeug' },
  { category: 'Musik', word: 'Gitarre' }, { category: 'Musik', word: 'Saxophon' },
  { category: 'Musik', word: 'Geige' }, { category: 'Musik', word: 'Trompete' },
  { category: 'Musik', word: 'Harfe' }, { category: 'Musik', word: 'Mundharmonika' },
  // Fahrzeuge (8)
  { category: 'Fahrzeuge', word: 'U-Boot' }, { category: 'Fahrzeuge', word: 'Heißluftballon' },
  { category: 'Fahrzeuge', word: 'Skateboard' }, { category: 'Fahrzeuge', word: 'Segelboot' },
  { category: 'Fahrzeuge', word: 'Motorrad' }, { category: 'Fahrzeuge', word: 'Rikscha' },
  { category: 'Fahrzeuge', word: 'Gondel' }, { category: 'Fahrzeuge', word: 'Pferdekutsche' },
  // Natur (8)
  { category: 'Natur', word: 'Vulkan' }, { category: 'Natur', word: 'Regenbogen' },
  { category: 'Natur', word: 'Gletscher' }, { category: 'Natur', word: 'Korallenriff' },
  { category: 'Natur', word: 'Nordlicht' }, { category: 'Natur', word: 'Wasserfall' },
  { category: 'Natur', word: 'Wüste' }, { category: 'Natur', word: 'Tornado' },
  // Superhelden (6)
  { category: 'Superhelden', word: 'Batman' }, { category: 'Superhelden', word: 'Spider-Man' },
  { category: 'Superhelden', word: 'Superman' }, { category: 'Superhelden', word: 'Iron Man' },
  { category: 'Superhelden', word: 'Wonder Woman' }, { category: 'Superhelden', word: 'Hulk' },
  // Märchen (6)
  { category: 'Märchen', word: 'Rotkäppchen' }, { category: 'Märchen', word: 'Aschenputtel' },
  { category: 'Märchen', word: 'Rapunzel' }, { category: 'Märchen', word: 'Schneewittchen' },
  { category: 'Märchen', word: 'Hänsel und Gretel' }, { category: 'Märchen', word: 'Dornröschen' },
];

// ─── English ─────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_EN: WordSet[] = [
  { category: 'Animals', word: 'Elephant' }, { category: 'Animals', word: 'Penguin' },
  { category: 'Animals', word: 'Dolphin' }, { category: 'Animals', word: 'Flamingo' },
  { category: 'Animals', word: 'Kangaroo' }, { category: 'Animals', word: 'Chameleon' },
  { category: 'Animals', word: 'Giraffe' }, { category: 'Animals', word: 'Parrot' },
  { category: 'Animals', word: 'Turtle' }, { category: 'Animals', word: 'Koala' },
  { category: 'Animals', word: 'Polar Bear' }, { category: 'Animals', word: 'Raccoon' },
  { category: 'Food', word: 'Pizza' }, { category: 'Food', word: 'Sushi' },
  { category: 'Food', word: 'Schnitzel' }, { category: 'Food', word: 'Kebab' },
  { category: 'Food', word: 'Tiramisu' }, { category: 'Food', word: 'Curry' },
  { category: 'Food', word: 'Tacos' }, { category: 'Food', word: 'Crêpe' },
  { category: 'Food', word: 'Mac & Cheese' }, { category: 'Food', word: 'Ramen' },
  { category: 'Food', word: 'Pancakes' }, { category: 'Food', word: 'Lasagna' },
  { category: 'Countries', word: 'Japan' }, { category: 'Countries', word: 'Brazil' },
  { category: 'Countries', word: 'Egypt' }, { category: 'Countries', word: 'New Zealand' },
  { category: 'Countries', word: 'Iceland' }, { category: 'Countries', word: 'Canada' },
  { category: 'Countries', word: 'Thailand' }, { category: 'Countries', word: 'Mexico' },
  { category: 'Countries', word: 'South Africa' }, { category: 'Countries', word: 'Norway' },
  { category: 'Jobs', word: 'Firefighter' }, { category: 'Jobs', word: 'Astronaut' },
  { category: 'Jobs', word: 'Detective' }, { category: 'Jobs', word: 'Pilot' },
  { category: 'Jobs', word: 'Veterinarian' }, { category: 'Jobs', word: 'Chef' },
  { category: 'Jobs', word: 'Architect' }, { category: 'Jobs', word: 'DJ' },
  { category: 'Jobs', word: 'Diver' }, { category: 'Jobs', word: 'Magician' },
  { category: 'Movies', word: 'Titanic' }, { category: 'Movies', word: 'The Matrix' },
  { category: 'Movies', word: 'The Lion King' }, { category: 'Movies', word: 'Star Wars' },
  { category: 'Movies', word: 'Harry Potter' }, { category: 'Movies', word: 'Shrek' },
  { category: 'Movies', word: 'Avengers' }, { category: 'Movies', word: 'Joker' },
  { category: 'Movies', word: 'Forrest Gump' }, { category: 'Movies', word: 'Frozen' },
  { category: 'Sports', word: 'Soccer' }, { category: 'Sports', word: 'Surfing' },
  { category: 'Sports', word: 'Climbing' }, { category: 'Sports', word: 'Ice Hockey' },
  { category: 'Sports', word: 'Tennis' }, { category: 'Sports', word: 'Skateboarding' },
  { category: 'Sports', word: 'Diving' }, { category: 'Sports', word: 'Archery' },
  { category: 'Sports', word: 'Snowboarding' }, { category: 'Sports', word: 'Yoga' },
  { category: 'Places', word: 'Beach' }, { category: 'Places', word: 'Library' },
  { category: 'Places', word: 'Theme Park' }, { category: 'Places', word: 'Mountain Peak' },
  { category: 'Places', word: 'Airport' }, { category: 'Places', word: 'Underwater World' },
  { category: 'Places', word: 'Jungle' }, { category: 'Places', word: 'Space Station' },
  { category: 'Music', word: 'Piano' }, { category: 'Music', word: 'Drums' },
  { category: 'Music', word: 'Guitar' }, { category: 'Music', word: 'Saxophone' },
  { category: 'Music', word: 'Violin' }, { category: 'Music', word: 'Trumpet' },
  { category: 'Music', word: 'Harp' }, { category: 'Music', word: 'Harmonica' },
  { category: 'Vehicles', word: 'Submarine' }, { category: 'Vehicles', word: 'Hot Air Balloon' },
  { category: 'Vehicles', word: 'Skateboard' }, { category: 'Vehicles', word: 'Sailboat' },
  { category: 'Vehicles', word: 'Motorcycle' }, { category: 'Vehicles', word: 'Rickshaw' },
  { category: 'Vehicles', word: 'Gondola' }, { category: 'Vehicles', word: 'Horse Carriage' },
  { category: 'Nature', word: 'Volcano' }, { category: 'Nature', word: 'Rainbow' },
  { category: 'Nature', word: 'Glacier' }, { category: 'Nature', word: 'Coral Reef' },
  { category: 'Nature', word: 'Northern Lights' }, { category: 'Nature', word: 'Waterfall' },
  { category: 'Nature', word: 'Desert' }, { category: 'Nature', word: 'Tornado' },
  { category: 'Superheroes', word: 'Batman' }, { category: 'Superheroes', word: 'Spider-Man' },
  { category: 'Superheroes', word: 'Superman' }, { category: 'Superheroes', word: 'Iron Man' },
  { category: 'Superheroes', word: 'Wonder Woman' }, { category: 'Superheroes', word: 'Hulk' },
  { category: 'Fairy Tales', word: 'Little Red Riding Hood' }, { category: 'Fairy Tales', word: 'Cinderella' },
  { category: 'Fairy Tales', word: 'Rapunzel' }, { category: 'Fairy Tales', word: 'Snow White' },
  { category: 'Fairy Tales', word: 'Hansel and Gretel' }, { category: 'Fairy Tales', word: 'Sleeping Beauty' },
];

// ─── Spanish ─────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_ES: WordSet[] = [
  { category: 'Animales', word: 'Elefante' }, { category: 'Animales', word: 'Pingüino' },
  { category: 'Animales', word: 'Delfín' }, { category: 'Animales', word: 'Flamenco' },
  { category: 'Animales', word: 'Canguro' }, { category: 'Animales', word: 'Camaleón' },
  { category: 'Animales', word: 'Jirafa' }, { category: 'Animales', word: 'Loro' },
  { category: 'Animales', word: 'Tortuga' }, { category: 'Animales', word: 'Koala' },
  { category: 'Animales', word: 'Oso polar' }, { category: 'Animales', word: 'Mapache' },
  { category: 'Comida', word: 'Pizza' }, { category: 'Comida', word: 'Sushi' },
  { category: 'Comida', word: 'Milanesa' }, { category: 'Comida', word: 'Kebab' },
  { category: 'Comida', word: 'Tiramisú' }, { category: 'Comida', word: 'Curry' },
  { category: 'Comida', word: 'Tacos' }, { category: 'Comida', word: 'Crêpe' },
  { category: 'Comida', word: 'Paella' }, { category: 'Comida', word: 'Ramen' },
  { category: 'Comida', word: 'Pancakes' }, { category: 'Comida', word: 'Lasaña' },
  { category: 'Países', word: 'Japón' }, { category: 'Países', word: 'Brasil' },
  { category: 'Países', word: 'Egipto' }, { category: 'Países', word: 'Nueva Zelanda' },
  { category: 'Países', word: 'Islandia' }, { category: 'Países', word: 'Canadá' },
  { category: 'Países', word: 'Tailandia' }, { category: 'Países', word: 'México' },
  { category: 'Países', word: 'Sudáfrica' }, { category: 'Países', word: 'Noruega' },
  { category: 'Profesiones', word: 'Bombero' }, { category: 'Profesiones', word: 'Astronauta' },
  { category: 'Profesiones', word: 'Detective' }, { category: 'Profesiones', word: 'Piloto' },
  { category: 'Profesiones', word: 'Veterinaria' }, { category: 'Profesiones', word: 'Chef' },
  { category: 'Profesiones', word: 'Arquitecto' }, { category: 'Profesiones', word: 'DJ' },
  { category: 'Profesiones', word: 'Buceador' }, { category: 'Profesiones', word: 'Mago' },
  { category: 'Películas', word: 'Titanic' }, { category: 'Películas', word: 'Matrix' },
  { category: 'Películas', word: 'El Rey León' }, { category: 'Películas', word: 'Star Wars' },
  { category: 'Películas', word: 'Harry Potter' }, { category: 'Películas', word: 'Shrek' },
  { category: 'Películas', word: 'Avengers' }, { category: 'Películas', word: 'Joker' },
  { category: 'Películas', word: 'Forrest Gump' }, { category: 'Películas', word: 'Frozen' },
  { category: 'Deportes', word: 'Fútbol' }, { category: 'Deportes', word: 'Surf' },
  { category: 'Deportes', word: 'Escalada' }, { category: 'Deportes', word: 'Hockey' },
  { category: 'Deportes', word: 'Tenis' }, { category: 'Deportes', word: 'Skate' },
  { category: 'Deportes', word: 'Buceo' }, { category: 'Deportes', word: 'Tiro con arco' },
  { category: 'Deportes', word: 'Snowboard' }, { category: 'Deportes', word: 'Yoga' },
  { category: 'Lugares', word: 'Playa' }, { category: 'Lugares', word: 'Biblioteca' },
  { category: 'Lugares', word: 'Parque temático' }, { category: 'Lugares', word: 'Cumbre' },
  { category: 'Lugares', word: 'Aeropuerto' }, { category: 'Lugares', word: 'Mundo submarino' },
  { category: 'Lugares', word: 'Selva' }, { category: 'Lugares', word: 'Estación espacial' },
  { category: 'Música', word: 'Piano' }, { category: 'Música', word: 'Batería' },
  { category: 'Música', word: 'Guitarra' }, { category: 'Música', word: 'Saxofón' },
  { category: 'Música', word: 'Violín' }, { category: 'Música', word: 'Trompeta' },
  { category: 'Música', word: 'Arpa' }, { category: 'Música', word: 'Armónica' },
  { category: 'Vehículos', word: 'Submarino' }, { category: 'Vehículos', word: 'Globo aerostático' },
  { category: 'Vehículos', word: 'Monopatín' }, { category: 'Vehículos', word: 'Velero' },
  { category: 'Vehículos', word: 'Motocicleta' }, { category: 'Vehículos', word: 'Rickshaw' },
  { category: 'Vehículos', word: 'Góndola' }, { category: 'Vehículos', word: 'Carruaje' },
  { category: 'Naturaleza', word: 'Volcán' }, { category: 'Naturaleza', word: 'Arcoíris' },
  { category: 'Naturaleza', word: 'Glaciar' }, { category: 'Naturaleza', word: 'Arrecife' },
  { category: 'Naturaleza', word: 'Aurora boreal' }, { category: 'Naturaleza', word: 'Cascada' },
  { category: 'Naturaleza', word: 'Desierto' }, { category: 'Naturaleza', word: 'Tornado' },
  { category: 'Superhéroes', word: 'Batman' }, { category: 'Superhéroes', word: 'Spider-Man' },
  { category: 'Superhéroes', word: 'Superman' }, { category: 'Superhéroes', word: 'Iron Man' },
  { category: 'Superhéroes', word: 'Wonder Woman' }, { category: 'Superhéroes', word: 'Hulk' },
  { category: 'Cuentos', word: 'Caperucita Roja' }, { category: 'Cuentos', word: 'Cenicienta' },
  { category: 'Cuentos', word: 'Rapunzel' }, { category: 'Cuentos', word: 'Blancanieves' },
  { category: 'Cuentos', word: 'Hansel y Gretel' }, { category: 'Cuentos', word: 'La Bella Durmiente' },
];

// ─── French ──────────────────────────────────────────────────────
export const IMPOSTOR_WORDS_FR: WordSet[] = [
  { category: 'Animaux', word: 'Éléphant' }, { category: 'Animaux', word: 'Pingouin' },
  { category: 'Animaux', word: 'Dauphin' }, { category: 'Animaux', word: 'Flamant rose' },
  { category: 'Animaux', word: 'Kangourou' }, { category: 'Animaux', word: 'Caméléon' },
  { category: 'Animaux', word: 'Girafe' }, { category: 'Animaux', word: 'Perroquet' },
  { category: 'Animaux', word: 'Tortue' }, { category: 'Animaux', word: 'Koala' },
  { category: 'Animaux', word: 'Ours polaire' }, { category: 'Animaux', word: 'Raton laveur' },
  { category: 'Nourriture', word: 'Pizza' }, { category: 'Nourriture', word: 'Sushi' },
  { category: 'Nourriture', word: 'Escalope' }, { category: 'Nourriture', word: 'Kebab' },
  { category: 'Nourriture', word: 'Tiramisu' }, { category: 'Nourriture', word: 'Curry' },
  { category: 'Nourriture', word: 'Tacos' }, { category: 'Nourriture', word: 'Crêpe' },
  { category: 'Nourriture', word: 'Gratin' }, { category: 'Nourriture', word: 'Ramen' },
  { category: 'Nourriture', word: 'Pancakes' }, { category: 'Nourriture', word: 'Lasagne' },
  { category: 'Pays', word: 'Japon' }, { category: 'Pays', word: 'Brésil' },
  { category: 'Pays', word: 'Égypte' }, { category: 'Pays', word: 'Nouvelle-Zélande' },
  { category: 'Pays', word: 'Islande' }, { category: 'Pays', word: 'Canada' },
  { category: 'Pays', word: 'Thaïlande' }, { category: 'Pays', word: 'Mexique' },
  { category: 'Pays', word: 'Afrique du Sud' }, { category: 'Pays', word: 'Norvège' },
  { category: 'Métiers', word: 'Pompier' }, { category: 'Métiers', word: 'Astronaute' },
  { category: 'Métiers', word: 'Détective' }, { category: 'Métiers', word: 'Pilote' },
  { category: 'Métiers', word: 'Vétérinaire' }, { category: 'Métiers', word: 'Chef' },
  { category: 'Métiers', word: 'Architecte' }, { category: 'Métiers', word: 'DJ' },
  { category: 'Métiers', word: 'Plongeur' }, { category: 'Métiers', word: 'Magicien' },
  { category: 'Films', word: 'Titanic' }, { category: 'Films', word: 'Matrix' },
  { category: 'Films', word: 'Le Roi Lion' }, { category: 'Films', word: 'Star Wars' },
  { category: 'Films', word: 'Harry Potter' }, { category: 'Films', word: 'Shrek' },
  { category: 'Films', word: 'Avengers' }, { category: 'Films', word: 'Joker' },
  { category: 'Films', word: 'Forrest Gump' }, { category: 'Films', word: 'La Reine des Neiges' },
  { category: 'Sports', word: 'Football' }, { category: 'Sports', word: 'Surf' },
  { category: 'Sports', word: 'Escalade' }, { category: 'Sports', word: 'Hockey' },
  { category: 'Sports', word: 'Tennis' }, { category: 'Sports', word: 'Skateboard' },
  { category: 'Sports', word: 'Plongée' }, { category: 'Sports', word: 'Tir à l\'arc' },
  { category: 'Sports', word: 'Snowboard' }, { category: 'Sports', word: 'Yoga' },
  { category: 'Lieux', word: 'Plage' }, { category: 'Lieux', word: 'Bibliothèque' },
  { category: 'Lieux', word: 'Parc d\'attractions' }, { category: 'Lieux', word: 'Sommet' },
  { category: 'Lieux', word: 'Aéroport' }, { category: 'Lieux', word: 'Monde sous-marin' },
  { category: 'Lieux', word: 'Jungle' }, { category: 'Lieux', word: 'Station spatiale' },
  { category: 'Musique', word: 'Piano' }, { category: 'Musique', word: 'Batterie' },
  { category: 'Musique', word: 'Guitare' }, { category: 'Musique', word: 'Saxophone' },
  { category: 'Musique', word: 'Violon' }, { category: 'Musique', word: 'Trompette' },
  { category: 'Musique', word: 'Harpe' }, { category: 'Musique', word: 'Harmonica' },
  { category: 'Véhicules', word: 'Sous-marin' }, { category: 'Véhicules', word: 'Montgolfière' },
  { category: 'Véhicules', word: 'Planche à roulettes' }, { category: 'Véhicules', word: 'Voilier' },
  { category: 'Véhicules', word: 'Moto' }, { category: 'Véhicules', word: 'Pousse-pousse' },
  { category: 'Véhicules', word: 'Gondole' }, { category: 'Véhicules', word: 'Calèche' },
  { category: 'Nature', word: 'Volcan' }, { category: 'Nature', word: 'Arc-en-ciel' },
  { category: 'Nature', word: 'Glacier' }, { category: 'Nature', word: 'Récif corallien' },
  { category: 'Nature', word: 'Aurore boréale' }, { category: 'Nature', word: 'Cascade' },
  { category: 'Nature', word: 'Désert' }, { category: 'Nature', word: 'Tornade' },
  { category: 'Super-héros', word: 'Batman' }, { category: 'Super-héros', word: 'Spider-Man' },
  { category: 'Super-héros', word: 'Superman' }, { category: 'Super-héros', word: 'Iron Man' },
  { category: 'Super-héros', word: 'Wonder Woman' }, { category: 'Super-héros', word: 'Hulk' },
  { category: 'Contes', word: 'Le Petit Chaperon Rouge' }, { category: 'Contes', word: 'Cendrillon' },
  { category: 'Contes', word: 'Raiponce' }, { category: 'Contes', word: 'Blanche-Neige' },
  { category: 'Contes', word: 'Hansel et Gretel' }, { category: 'Contes', word: 'La Belle au bois dormant' },
];
