export interface HeadUpCategory {
  id: string;
  name: string;
  emoji: string;
  gradient: string;
  words: string[];
}

export const HEADUP_CATEGORIES_ES: HeadUpCategory[] = [
  {
    id: 'celebrities',
    name: 'Famosos',
    emoji: '🌟',
    gradient: 'from-amber-500 to-orange-600',
    words: [
      'Lionel Messi', 'Shakira', 'Rafael Nadal', 'Bad Bunny',
      'Penelope Cruz', 'Antonio Banderas', 'Rosalia', 'Pablo Picasso',
      'Cristiano Ronaldo', 'Elon Musk', 'Leonardo DiCaprio', 'Beyonce',
      'Taylor Swift', 'Rihanna', 'Adele', 'Ed Sheeran',
      'Barack Obama', 'Frida Kahlo', 'Gabriel Garcia Marquez', 'Salvador Dali',
      'Daddy Yankee', 'J Balvin', 'Alejandro Sanz', 'Enrique Iglesias',
      'Javier Bardem', 'Pedro Almodovar', 'Fernando Alonso', 'Sergio Ramos',
      'Iker Casillas', 'Andres Iniesta', 'Diego Maradona', 'Eva Longoria',
      'Sofia Vergara', 'Lin-Manuel Miranda', 'Selena Gomez', 'Ozuna',
      'Nicky Jam', 'Marc Anthony', 'Maluma', 'Karol G',
      'Brad Pitt', 'Johnny Depp', 'Lady Gaga', 'Billie Eilish',
      'Greta Thunberg', 'Morgan Freeman', 'Dwayne Johnson', 'Oprah Winfrey',
      'Drake', 'Ariana Grande',
    ],
  },
  {
    id: 'animals',
    name: 'Animales',
    emoji: '🐾',
    gradient: 'from-green-500 to-emerald-600',
    words: [
      'Elefante', 'Pinguino', 'Jirafa', 'Cocodrilo', 'Delfin',
      'Mariposa', 'Camaleon', 'Colibri', 'Tortuga', 'Flamenco',
      'Gorila', 'Pavo real', 'Canguro', 'Caballito de mar', 'Loro',
      'Escorpion', 'Rinoceronte', 'Mapache', 'Perezoso', 'Guepardo',
      'Suricata', 'Koala', 'Pulpo', 'Oso polar', 'Mofeta',
      'Castor', 'Hormiga', 'Panda', 'Tejon', 'Lince',
      'Perro', 'Gato', 'Leon', 'Tigre', 'Aguila',
      'Serpiente', 'Tiburon', 'Lobo', 'Zorro', 'Conejo',
      'Ardilla', 'Medusa', 'Buho', 'Ballena', 'Abeja',
      'Rana', 'Erizo', 'Murcielago', 'Iguana', 'Cebra',
    ],
  },
  {
    id: 'movies',
    name: 'Peliculas y Series',
    emoji: '🎬',
    gradient: 'from-purple-500 to-violet-600',
    words: [
      'Titanic', 'El Rey Leon', 'Harry Potter', 'Star Wars',
      'Buscando a Nemo', 'Parque Jurasico', 'Forrest Gump', 'Matrix',
      'Piratas del Caribe', 'Shrek', 'Frozen', 'Batman',
      'El Senor de los Anillos', 'Origen', 'Avatar', 'Spider-Man',
      'Toy Story', 'Enredados', 'Aladdin', 'Interestelar',
      'E.T.', 'Regreso al Futuro', 'Cazafantasmas', 'Top Gun',
      'Rocky', 'Indiana Jones', 'Terminator', 'El Club de la Lucha',
      'Pulp Fiction', 'Gladiador', 'El Padrino', 'Joker',
      'Breaking Bad', 'Juego de Tronos', 'Friends', 'Stranger Things',
      'La Casa de Papel', 'Squid Game', 'Elite', 'Vis a Vis',
      'Wednesday', 'Los Simpson', 'Avengers', 'The Mandalorian',
      'Vikingos', 'Peaky Blinders', 'Narcos', 'Black Mirror',
      'Las Chicas del Cable', 'Quien es el Asesino',
    ],
  },
  {
    id: 'food',
    name: 'Comida y Bebida',
    emoji: '🍕',
    gradient: 'from-red-500 to-rose-600',
    words: [
      'Paella', 'Tortilla espanola', 'Gazpacho', 'Sushi',
      'Hamburguesa', 'Pizza Margarita', 'Churros', 'Tiramisu',
      'Crepes', 'Jamon iberico', 'Croquetas', 'Empanadas',
      'Patatas bravas', 'Fabada', 'Pulpo a la gallega', 'Fondue',
      'Turron', 'Sangria', 'Tacos', 'Nachos',
      'Croissant', 'Fish and Chips', 'Ramen',
      'Pad Thai', 'Patatas fritas', 'Raclette',
      'Filete', 'Lasana', 'Risotto', 'Guacamole',
      'Gofres', 'Donut', 'Gominolas', 'Chocolate',
      'Helado', 'Palomitas', 'Cafe', 'Capuchino',
      'Batido', 'Tinto de verano', 'Limonada', 'Coctel',
      'Pinchos', 'Ceviche', 'Arepas', 'Pupusas',
    ],
  },
  {
    id: 'sports',
    name: 'Deportes',
    emoji: '⚽',
    gradient: 'from-blue-500 to-cyan-600',
    words: [
      'Futbol', 'Tenis', 'Natacion', 'Esqui', 'Baloncesto',
      'Voleibol', 'Hockey sobre hielo', 'Surf', 'Boxeo', 'Golf',
      'Yoga', 'Maraton', 'Snowboard', 'Escalada', 'Equitacion',
      'Esgrima', 'Tiro con arco', 'Buceo', 'Vela', 'Remo',
      'Karate', 'Patinaje', 'Cama elastica', 'Curling',
      'Dardos', 'Tenis de mesa', 'Badminton', 'Balonmano', 'Waterpolo',
      'Biatlon', 'Triatlon', 'Judo', 'Gimnasia', 'Beisbol',
      'Rugby', 'Bolos', 'Lucha libre', 'Patinaje artistico', 'Bobsled',
      'Atletismo', 'Automovilismo', 'Lacrosse', 'Polo',
      'Sumo', 'Parkour', 'Wakeboard',
    ],
  },
  {
    id: 'professions',
    name: 'Profesiones',
    emoji: '👷',
    gradient: 'from-indigo-500 to-blue-600',
    words: [
      'Bombero', 'Astronauta', 'Dentista', 'Piloto', 'Detective',
      'Panadero', 'Veterinario', 'Director de orquesta', 'Buzo', 'Arbitro',
      'Mago', 'Arqueologo', 'Guardaespaldas', 'Taxista', 'Apicultor',
      'Deshollinador', 'Especialista de cine', 'Cirujano', 'Farero',
      'Pastor', 'Herrero', 'Maquillador', 'Doblador de voz',
      'Maestro cervecero', 'Socorrista', 'Jardinero', 'Relojero',
      'Cartografo', 'Carnicero', 'Sumiller', 'Medico', 'Profesor',
      'Policia', 'Cocinero', 'Abogado', 'Arquitecto', 'Fotografo',
      'Periodista', 'Juez', 'Farmaceutico', 'Cartero',
      'Conductor de autobus', 'Capitan', 'Actor', 'DJ', 'Peluquero',
      'Sastre', 'Controlador aereo', 'Catedratico', 'Orfebre', 'Carpintero',
    ],
  },
  {
    id: 'actions',
    name: 'Actividades',
    emoji: '🏃',
    gradient: 'from-teal-500 to-green-600',
    words: [
      'Secarse el pelo', 'Lavarse los dientes', 'Hacer la maleta', 'Bailar',
      'Patinar sobre hielo', 'Hacerse un selfie', 'Toser', 'Estornudar',
      'Roncar', 'Planchar', 'Pasar la aspiradora', 'Bostezar',
      'Hacer malabares', 'Saltar a la comba', 'Tocar la guitarra', 'Cocinar',
      'Lavar el coche', 'Aparcar', 'Vaciar el lavavajillas',
      'Pasear al perro', 'Pintarse las unas',
      'Tocar la guitarra de aire', 'Correr', 'Hacer flexiones',
      'Hacer un muneco de nieve', 'Pescar', 'Poner la mesa',
      'Atarse los zapatos', 'Silbar', 'Montar en bicicleta',
      'Envolver regalos', 'Hornear un pastel', 'Hacer pompas de jabon',
      'Jugar a las cartas', 'Volar una cometa', 'Trotar',
      'Preparar el desayuno', 'Sacar la basura', 'Comer chocolate',
      'Hacer fotos',
    ],
  },
  {
    id: 'places',
    name: 'Lugares y Paises',
    emoji: '🌍',
    gradient: 'from-sky-500 to-indigo-600',
    words: [
      'Paris', 'Nueva York', 'Tokio', 'Egipto', 'Australia',
      'Venecia', 'Hollywood', 'Antartida', 'Hawai', 'Londres',
      'Sahara', 'Amazonas', 'Triangulo de las Bermudas', 'Monte Everest',
      'Gran Canon', 'Cataratas del Niagara', 'Coliseo', 'Estatua de la Libertad',
      'Torre Eiffel', 'Sagrada Familia', 'Alhambra',
      'Taj Mahal', 'Gran Muralla China', 'Machu Picchu',
      'Stonehenge', 'Vaticano', 'Dubai', 'Las Vegas',
      'Cancun', 'Ibiza',
      'Espana', 'Francia', 'Italia', 'Mexico', 'Japon',
      'Brasil', 'Canada', 'Argentina', 'Colombia', 'Peru',
      'Cuba', 'Grecia', 'Tailandia', 'Islandia',
      'Nueva Zelanda', 'Croacia', 'Marruecos', 'Chile', 'Costa Rica',
    ],
  },
  {
    id: 'fairytale',
    name: 'Personajes de cuentos',
    emoji: '🏰',
    words: [
      'Blancanieves', 'Caperucita Roja', 'Cenicienta', 'Rapunzel', 'Bella Durmiente',
      'El Gato con Botas', 'Pulgarcito', 'Los Tres Cerditos', 'El Principe Rana',
      'Hansel y Gretel', 'Ricitos de Oro', 'El Lobo Feroz', 'La Bruja Malvada',
      'Pinocho', 'Peter Pan', 'Robin Hood', 'Aladino',
      'La Sirenita', 'Ali Baba', 'Simbad', 'La Reina de las Nieves',
      'El Mago de Oz', 'La Bella y la Bestia', 'El Principito',
      'Alicia en el Pais de las Maravillas', 'Los Siete Enanitos', 'Hada', 'Dragon',
      'Unicornio', 'Gigante', 'Enano', 'Troll', 'Elfo',
      'Genio', 'Campanilla', 'Don Quijote', 'Sancho Panza',
      'El Zorro', 'Blancaflor',
    ],
    gradient: 'from-pink-500 to-purple-600',
  },
  {
    id: 'superheroes',
    name: 'Superheroes',
    emoji: '🦸',
    gradient: 'from-red-600 to-blue-600',
    words: [
      'Superman', 'Batman', 'Spider-Man', 'Iron Man', 'Thor',
      'Hulk', 'Capitan America', 'Wonder Woman', 'Aquaman', 'Flash',
      'Wolverine', 'Black Panther', 'Deadpool', 'Doctor Strange', 'Ant-Man',
      'Linterna Verde', 'Ojo de Halcon', 'Viuda Negra', 'Bruja Escarlata', 'Vision',
      'Catwoman', 'Robin', 'Joker', 'Thanos', 'Loki',
      'Harley Quinn', 'Magneto', 'Profesor X', 'Tormenta',
      'Groot', 'Rocket', 'Gamora', 'Star-Lord', 'Shazam',
      'Flecha Verde', 'Daredevil', 'Punisher', 'Elektra', 'Nightwing',
    ],
  },
  {
    id: 'music',
    name: 'Musica y Cantantes',
    emoji: '🎤',
    gradient: 'from-fuchsia-500 to-pink-600',
    words: [
      'Bad Bunny', 'Rosalia', 'Shakira', 'Alejandro Sanz', 'Enrique Iglesias',
      'Daddy Yankee', 'J Balvin', 'Maluma', 'Karol G', 'Ozuna',
      'Luis Fonsi', 'Juanes', 'Marc Anthony', 'Celia Cruz', 'Ricky Martin',
      'The Beatles', 'Queen', 'ABBA', 'Rolling Stones', 'Pink Floyd',
      'Nirvana', 'AC/DC', 'U2', 'Coldplay', 'Linkin Park',
      'Eminem', 'Michael Jackson', 'Madonna', 'Elvis Presley', 'David Bowie',
      'Bob Marley', 'Adele', 'Ed Sheeran', 'Beyonce', 'Taylor Swift',
      'Lady Gaga', 'Billie Eilish', 'Bruno Mars', 'The Weeknd', 'Dua Lipa',
      'Sia', 'Imagine Dragons', 'Maroon 5', 'Reggaeton', 'Flamenco',
    ],
  },
  {
    id: 'emojis',
    name: 'Describir emojis',
    emoji: '😀',
    gradient: 'from-yellow-400 to-orange-500',
    words: [
      'Cara riendo', 'Llorar de risa', 'Ojos de corazon', 'Guino', 'Mandando beso',
      'Pensativo', 'Cara triste', 'Enfadado', 'Sorprendido', 'Dormido',
      'Cara de fiesta', 'Gafas de sol', 'Cara loca', 'Fantasma', 'Payaso',
      'Robot', 'Mono tapandose ojos', 'Pulgar arriba', 'Aplaudir', 'Musculos',
      'Signo de paz', 'Corazon', 'Corazon roto', 'Fuego', 'Arcoiris',
      'Sol', 'Nube', 'Rayo', 'Copo de nieve', 'Cohete',
      'Corona', 'Diamante', 'Unicornio', 'Mariposa', 'Arbol de Navidad',
      'Regalo', 'Pastel de cumpleanos', 'Confeti', 'Trebol', 'Estrella',
      'Trozo de pizza', 'Taza de cafe', 'Bebida tropical', 'Balon de futbol', 'Trofeo',
    ],
  },
];
