export interface HeadUpCategory {
  id: string;
  name: string;
  emoji: string;
  gradient: string;
  words: string[];
}

export const HEADUP_CATEGORIES_EN: HeadUpCategory[] = [
  {
    id: 'celebrities',
    name: 'Celebrities',
    emoji: '🌟',
    gradient: 'from-amber-500 to-orange-600',
    words: [
      'Taylor Swift', 'Beyonce', 'Elon Musk', 'Oprah Winfrey',
      'Tom Hanks', 'Dwayne Johnson', 'Leonardo DiCaprio', 'Michael Jordan',
      'LeBron James', 'Kim Kardashian', 'Ed Sheeran', 'Ariana Grande',
      'Barack Obama', 'Jennifer Lawrence', 'Tom Brady', 'Rihanna',
      'Drake', 'Billie Eilish', 'Lady Gaga', 'Cristiano Ronaldo',
      'Lionel Messi', 'Adele', 'Morgan Freeman', 'Brad Pitt',
      'Shakira', 'Will Smith', 'Keanu Reeves', 'Greta Thunberg',
      'Jeff Bezos', 'Mark Zuckerberg', 'Serena Williams', 'Stephen Hawking',
      'Ellen DeGeneres', 'Selena Gomez', 'Post Malone', 'Cardi B',
      'Johnny Depp', 'Arnold Schwarzenegger', 'David Beckham', 'Justin Bieber',
      'Snoop Dogg', 'Eminem', 'Kanye West', 'Gordon Ramsay',
      'Martha Stewart', 'Dolly Parton', 'Sandra Bullock', 'Robert Downey Jr.',
      'Chris Hemsworth', 'Zendaya',
    ],
  },
  {
    id: 'animals',
    name: 'Animals',
    emoji: '🐾',
    gradient: 'from-green-500 to-emerald-600',
    words: [
      'Elephant', 'Penguin', 'Giraffe', 'Crocodile', 'Dolphin',
      'Butterfly', 'Chameleon', 'Hummingbird', 'Turtle', 'Flamingo',
      'Gorilla', 'Peacock', 'Kangaroo', 'Seahorse', 'Parrot',
      'Scorpion', 'Rhinoceros', 'Raccoon', 'Sloth', 'Cheetah',
      'Meerkat', 'Koala', 'Octopus', 'Polar Bear', 'Skunk',
      'Beaver', 'Ant', 'Panda', 'Badger', 'Lynx',
      'Dog', 'Cat', 'Lion', 'Tiger', 'Eagle',
      'Snake', 'Shark', 'Wolf', 'Fox', 'Rabbit',
      'Squirrel', 'Jellyfish', 'Owl', 'Whale', 'Bee',
      'Frog', 'Hedgehog', 'Bat', 'Iguana', 'Zebra',
    ],
  },
  {
    id: 'movies',
    name: 'Movies & TV Shows',
    emoji: '🎬',
    gradient: 'from-purple-500 to-violet-600',
    words: [
      'Titanic', 'The Lion King', 'Harry Potter', 'Star Wars',
      'Finding Nemo', 'Jurassic Park', 'Forrest Gump', 'The Matrix',
      'Pirates of the Caribbean', 'Shrek', 'Frozen', 'Batman',
      'The Lord of the Rings', 'Inception', 'Avatar', 'Spider-Man',
      'Toy Story', 'Tangled', 'Aladdin', 'Interstellar',
      'E.T.', 'Back to the Future', 'Ghostbusters', 'Top Gun',
      'Rocky', 'Indiana Jones', 'Terminator', 'Fight Club',
      'Pulp Fiction', 'Gladiator', 'The Godfather', 'Joker',
      'Breaking Bad', 'Game of Thrones', 'Friends', 'Stranger Things',
      'The Office', 'Squid Game', 'Money Heist', 'Wednesday',
      'Seinfeld', 'The Simpsons', 'Avengers', 'The Mandalorian',
      'Vikings', 'Peaky Blinders', 'Narcos', 'Black Mirror',
      'Grey\'s Anatomy', 'The Walking Dead',
    ],
  },
  {
    id: 'food',
    name: 'Food & Drinks',
    emoji: '🍕',
    gradient: 'from-red-500 to-rose-600',
    words: [
      'Spaghetti Bolognese', 'Fish and Chips', 'BBQ Ribs', 'Sushi',
      'Hamburger', 'Pizza Margherita', 'Hot Dog', 'Tiramisu',
      'Pancakes', 'Pretzel', 'Apple Pie', 'Grilled Cheese',
      'Mac and Cheese', 'Pumpkin Pie', 'Thanksgiving Turkey', 'Fondue',
      'Gingerbread', 'Clam Chowder', 'Lobster', 'Cheesesteak',
      'Buffalo Wings', 'Nachos', 'Burrito', 'Guacamole',
      'Croissant', 'Paella', 'Tacos', 'Ramen',
      'Pad Thai', 'French Fries', 'Raclette', 'Steak',
      'Lasagna', 'Risotto', 'Nachos', 'Waffles',
      'Donut', 'Gummy Bears', 'Chocolate', 'Ice Cream',
      'Popcorn', 'Coffee', 'Cappuccino', 'Smoothie',
      'Lemonade', 'Milkshake', 'Root Beer Float', 'Cocktail',
    ],
  },
  {
    id: 'sports',
    name: 'Sports',
    emoji: '⚽',
    gradient: 'from-blue-500 to-cyan-600',
    words: [
      'Soccer', 'Tennis', 'Swimming', 'Skiing', 'Basketball',
      'Volleyball', 'Ice Hockey', 'Surfing', 'Boxing', 'Golf',
      'Yoga', 'Marathon', 'Snowboarding', 'Rock Climbing', 'Horse Riding',
      'Fencing', 'Archery', 'Scuba Diving', 'Sailing', 'Rowing',
      'Karate', 'Skateboarding', 'Trampoline', 'Curling',
      'Darts', 'Table Tennis', 'Badminton', 'Handball', 'Water Polo',
      'Biathlon', 'Triathlon', 'Judo', 'Gymnastics', 'Baseball',
      'Rugby', 'Bowling', 'Wrestling', 'Figure Skating', 'Bobsled',
      'Track and Field', 'Motorsport', 'Lacrosse', 'Polo',
      'Sumo Wrestling', 'Parkour', 'Wakeboarding',
    ],
  },
  {
    id: 'professions',
    name: 'Professions',
    emoji: '👷',
    gradient: 'from-indigo-500 to-blue-600',
    words: [
      'Firefighter', 'Astronaut', 'Dentist', 'Pilot', 'Detective',
      'Baker', 'Veterinarian', 'Conductor', 'Diver', 'Referee',
      'Magician', 'Archaeologist', 'Bodyguard', 'Taxi Driver', 'Beekeeper',
      'Chimney Sweep', 'Stuntman', 'Surgeon', 'Lighthouse Keeper',
      'Shepherd', 'Blacksmith', 'Makeup Artist', 'Voice Actor',
      'Brewmaster', 'Lifeguard', 'Gardener', 'Watchmaker',
      'Cartographer', 'Butcher', 'Sommelier', 'Doctor', 'Teacher',
      'Police Officer', 'Chef', 'Lawyer', 'Architect', 'Photographer',
      'Journalist', 'Judge', 'Pharmacist', 'Mail Carrier',
      'Bus Driver', 'Ship Captain', 'Actor', 'DJ', 'Hairdresser',
      'Tailor', 'Air Traffic Controller', 'Professor', 'Goldsmith', 'Carpenter',
    ],
  },
  {
    id: 'actions',
    name: 'Activities',
    emoji: '🏃',
    gradient: 'from-teal-500 to-green-600',
    words: [
      'Blow drying hair', 'Brushing teeth', 'Packing a suitcase', 'Dancing',
      'Ice skating', 'Taking a selfie', 'Coughing', 'Sneezing',
      'Snoring', 'Ironing', 'Vacuuming', 'Yawning',
      'Juggling', 'Jump roping', 'Playing guitar', 'Cooking',
      'Washing a car', 'Parallel parking', 'Unloading the dishwasher',
      'Walking the dog', 'Painting nails',
      'Playing air guitar', 'Jogging', 'Doing push-ups',
      'Building a snowman', 'Fishing', 'Setting the table',
      'Tying shoes', 'Whistling', 'Riding a bicycle',
      'Wrapping presents', 'Baking a cake', 'Blowing bubbles',
      'Playing cards', 'Flying a kite', 'Running',
      'Making breakfast', 'Taking out the trash', 'Eating chocolate',
      'Taking photos',
    ],
  },
  {
    id: 'places',
    name: 'Places & Countries',
    emoji: '🌍',
    gradient: 'from-sky-500 to-indigo-600',
    words: [
      'Paris', 'New York', 'Tokyo', 'Egypt', 'Australia',
      'Venice', 'Hollywood', 'Antarctica', 'Hawaii', 'London',
      'Sahara', 'Amazon', 'Bermuda Triangle', 'Mount Everest',
      'Grand Canyon', 'Niagara Falls', 'Colosseum', 'Statue of Liberty',
      'Eiffel Tower', 'Times Square', 'Golden Gate Bridge',
      'Taj Mahal', 'Great Wall of China', 'Machu Picchu',
      'Stonehenge', 'Vatican', 'Dubai', 'Las Vegas',
      'Disney World', 'Yellowstone',
      'United States', 'France', 'Italy', 'Spain', 'Japan',
      'Brazil', 'Canada', 'Mexico', 'India', 'Switzerland',
      'Austria', 'Greece', 'Thailand', 'Iceland',
      'New Zealand', 'Croatia', 'Morocco', 'Peru', 'Cuba',
    ],
  },
  {
    id: 'fairytale',
    name: 'Fairy Tale Characters',
    emoji: '🏰',
    words: [
      'Snow White', 'Little Red Riding Hood', 'Cinderella', 'Rapunzel', 'Sleeping Beauty',
      'Rumpelstiltskin', 'Mother Goose', 'Puss in Boots', 'Jack and the Beanstalk', 'Frog Prince',
      'Hansel and Gretel', 'Three Little Pigs', 'Goldilocks', 'Big Bad Wolf', 'Wicked Witch',
      'Pinocchio', 'Peter Pan', 'Robin Hood', 'Aladdin',
      'The Little Mermaid', 'Ali Baba', 'Tom Thumb', 'Sinbad', 'Snow Queen',
      'Wizard of Oz', 'Beauty and the Beast', 'Pied Piper', 'The Little Prince',
      'Alice in Wonderland', 'Seven Dwarfs', 'Fairy', 'Dragon',
      'Unicorn', 'Giant', 'Dwarf', 'Troll', 'Elf',
      'Genie', 'Tinker Bell',
    ],
    gradient: 'from-pink-500 to-purple-600',
  },
  {
    id: 'superheroes',
    name: 'Superheroes',
    emoji: '🦸',
    gradient: 'from-red-600 to-blue-600',
    words: [
      'Superman', 'Batman', 'Spider-Man', 'Iron Man', 'Thor',
      'Hulk', 'Captain America', 'Wonder Woman', 'Aquaman', 'Flash',
      'Wolverine', 'Black Panther', 'Deadpool', 'Doctor Strange', 'Ant-Man',
      'Green Lantern', 'Hawkeye', 'Black Widow', 'Scarlet Witch', 'Vision',
      'Catwoman', 'Robin', 'Joker', 'Thanos', 'Loki',
      'Harley Quinn', 'Poison Ivy', 'Magneto', 'Professor X', 'Storm',
      'Groot', 'Rocket Raccoon', 'Gamora', 'Star-Lord', 'Shazam',
      'Green Arrow', 'Nightwing', 'Elektra', 'Daredevil', 'Punisher',
    ],
  },
  {
    id: 'music',
    name: 'Music Bands & Singers',
    emoji: '🎤',
    gradient: 'from-fuchsia-500 to-pink-600',
    words: [
      'Taylor Swift', 'Beyonce', 'Ed Sheeran', 'Adele', 'Drake',
      'Billie Eilish', 'Lady Gaga', 'Bruno Mars', 'The Weeknd', 'Dua Lipa',
      'The Beatles', 'Queen', 'ABBA', 'Rolling Stones', 'Pink Floyd',
      'Nirvana', 'AC/DC', 'U2', 'Coldplay', 'Linkin Park',
      'Eminem', 'Michael Jackson', 'Madonna', 'Elvis Presley', 'David Bowie',
      'Bob Marley', 'Elton John', 'Whitney Houston', 'Prince', 'Stevie Wonder',
      'Sia', 'Shakira', 'Imagine Dragons', 'Maroon 5', 'Arctic Monkeys',
      'Post Malone', 'Ariana Grande', 'Rihanna', 'Kanye West', 'Kendrick Lamar',
      'Foo Fighters', 'Red Hot Chili Peppers', 'Metallica', 'Guns N\' Roses', 'Aerosmith',
    ],
  },
  {
    id: 'emojis',
    name: 'Describe Emojis',
    emoji: '😀',
    gradient: 'from-yellow-400 to-orange-500',
    words: [
      'Laughing Face', 'Crying Laughing', 'Heart Eyes', 'Winking', 'Blowing a Kiss',
      'Thinking', 'Sad Face', 'Angry', 'Surprised', 'Sleeping',
      'Party Face', 'Sunglasses', 'Crazy Face', 'Ghost', 'Clown',
      'Robot', 'See No Evil Monkey', 'Thumbs Up', 'Clapping', 'Flexing',
      'Peace Sign', 'Heart', 'Broken Heart', 'Fire', 'Rainbow',
      'Sun', 'Cloud', 'Lightning', 'Snowflake', 'Rocket',
      'Crown', 'Diamond', 'Unicorn', 'Butterfly', 'Christmas Tree',
      'Present', 'Birthday Cake', 'Confetti', 'Four Leaf Clover', 'Star',
      'Pizza Slice', 'Coffee Cup', 'Tropical Drink', 'Soccer Ball', 'Trophy',
    ],
  },
];
