export interface HeadUpCategory {
  id: string;
  name: string;
  emoji: string;
  gradient: string;
  words: string[];
}

export const HEADUP_CATEGORIES_DE: HeadUpCategory[] = [
  {
    id: 'celebrities',
    name: 'Prominente',
    emoji: '🌟',
    gradient: 'from-amber-500 to-orange-600',
    words: [
      'Angela Merkel', 'Albert Einstein', 'Beethoven', 'Heidi Klum',
      'Thomas Mueller', 'Till Schweiger', 'Helene Fischer', 'Michael Schumacher',
      'Boris Becker', 'Bastian Schweinsteiger', 'Dirk Nowitzki',
      'Karl Lagerfeld', 'Marlene Dietrich', 'Johann Wolfgang von Goethe',
      'Wolfgang Amadeus Mozart', 'Rihanna', 'Taylor Swift', 'Cristiano Ronaldo',
      'Elon Musk', 'Leonardo DiCaprio', 'Beyonce', 'Lionel Messi',
      'Adele', 'Ed Sheeran', 'Dwayne Johnson', 'Ariana Grande',
      'Barack Obama', 'Oprah Winfrey', 'David Beckham', 'Shakira',
      'Juergen Klopp', 'Herbert Groenemeyer', 'Steffi Graf', 'Manuel Neuer',
      'Jan Boehmermann', 'Joko Winterscheidt', 'Stefan Raab', 'Lena Meyer-Landrut',
      'Brad Pitt', 'Johnny Depp', 'Morgan Freeman', 'Lady Gaga',
      'Billie Eilish', 'Drake', 'Arnold Schwarzenegger', 'Greta Thunberg',
      'Udo Lindenberg', 'Dieter Bohlen', 'Oliver Kahn', 'Tom Hanks',
      'Keanu Reeves', 'Will Smith', 'Scarlett Johansson', 'Margot Robbie',
      'Robert Downey Jr.', 'Chris Hemsworth', 'Zendaya', 'Selena Gomez',
      'Post Malone', 'Cardi B', 'Travis Scott', 'Doja Cat',
      'Sandra Bullock', 'Meryl Streep', 'Denzel Washington', 'Samuel L. Jackson',
      'Jennifer Lawrence', 'Emma Watson', 'Tom Holland', 'Timothee Chalamet',
      'Bad Bunny', 'The Weeknd', 'Dua Lipa', 'Harry Styles',
      'Zlatan Ibrahimovic', 'Lewis Hamilton', 'Serena Williams', 'Usain Bolt',
      'Roger Federer', 'Rafael Nadal', 'Novak Djokovic', 'Kylian Mbappe',
    ],
  },
  {
    id: 'animals',
    name: 'Tiere',
    emoji: '🐾',
    gradient: 'from-green-500 to-emerald-600',
    words: [
      'Elefant', 'Pinguin', 'Giraffe', 'Krokodil', 'Delfin',
      'Schmetterling', 'Chamaeleon', 'Kolibri', 'Schildkroete', 'Flamingo',
      'Gorilla', 'Pfau', 'Kaenguru', 'Seepferdchen', 'Papagei',
      'Skorpion', 'Nashorn', 'Waschbaer', 'Faultier', 'Gepard',
      'Erdmaennchen', 'Koala', 'Tintenfisch', 'Eisbaer', 'Stinktier',
      'Biber', 'Ameise', 'Panda', 'Dachs', 'Luchs',
      'Hund', 'Katze', 'Loewe', 'Tiger', 'Adler',
      'Schlange', 'Hai', 'Wolf', 'Fuchs', 'Hase',
      'Eichhoernchen', 'Qualle', 'Eule', 'Wal', 'Biene',
      'Frosch', 'Igel', 'Fledermaus', 'Leguan', 'Zebra',
      'Maulwurf', 'Nilpferd', 'Stinktier', 'Tapir', 'Wombat',
      'Albatros', 'Kuckuck', 'Robbe', 'Seekuh', 'Lama',
      'Alpaka', 'Otter', 'Hermelin', 'Murmeltier', 'Lemur',
      'Axolotl', 'Narwal', 'Okapi', 'Ameisenfresser', 'Schnabeltier',
    ],
  },
  {
    id: 'movies',
    name: 'Filme & Serien',
    emoji: '🎬',
    gradient: 'from-purple-500 to-violet-600',
    words: [
      'Titanic', 'Der Koenig der Loewen', 'Harry Potter', 'Star Wars',
      'Findet Nemo', 'Jurassic Park', 'Forrest Gump', 'Matrix',
      'Fluch der Karibik', 'Shrek', 'Die Eiskoenigin', 'Batman',
      'Der Herr der Ringe', 'Inception', 'Avatar', 'Spider-Man',
      'Toy Story', 'Rapunzel', 'Aladin', 'Interstellar',
      'E.T.', 'Zurueck in die Zukunft', 'Ghostbusters', 'Top Gun',
      'Rocky', 'Indiana Jones', 'Terminator', 'Fight Club',
      'Pulp Fiction', 'Gladiator', 'Der Pate', 'Joker',
      'Breaking Bad', 'Game of Thrones', 'Friends', 'Stranger Things',
      'Dark', 'Squid Game', 'Haus des Geldes', 'The Office',
      'Wednesday', 'Tatort', 'Das Boot', 'Die unendliche Geschichte',
      'Avengers', 'The Mandalorian', 'Vikings', 'Peaky Blinders',
      'Narcos', 'Black Mirror',
      'Oppenheimer', 'Barbie', 'Dune', 'John Wick', 'The Batman',
      'Parasite', 'Coco', 'Inside Out', 'Soul', 'Ratatouille',
      'The Witcher', 'Bridgerton', 'Lupin', 'The Crown', 'Yellowstone',
      'Succession', 'Ted Lasso', 'Cobra Kai', 'Emily in Paris', 'Loki',
      'Schindlers Liste', 'Forest Gump', 'Der weisse Hai', 'Alien', 'Blade Runner',
      'Madagascar', 'Kung Fu Panda', 'Ice Age', 'Shutter Island', 'Django Unchained',
    ],
  },
  {
    id: 'food',
    name: 'Essen & Trinken',
    emoji: '🍕',
    gradient: 'from-red-500 to-rose-600',
    words: [
      'Spaghetti Bolognese', 'Schnitzel', 'Currywurst', 'Sushi',
      'Hamburger', 'Pizza Margherita', 'Doener Kebab', 'Tiramisu',
      'Crepes', 'Brezel', 'Apfelstrudel', 'Bratwurst',
      'Kartoffelpuffer', 'Sachertorte', 'Kaiserschmarrn', 'Fondue',
      'Lebkuchen', 'Maultaschen', 'Kaesespaetzle', 'Schweinebraten',
      'Flammkuchen', 'Sauerbraten', 'Rouladen', 'Gulasch',
      'Croissant', 'Paella', 'Fish and Chips', 'Tacos',
      'Ramen', 'Pad Thai', 'Pommes', 'Raclette',
      'Steak', 'Lasagne', 'Risotto', 'Nachos',
      'Waffeln', 'Donut', 'Gummibaerchen', 'Schokolade',
      'Eis', 'Popcorn', 'Kaffee', 'Cappuccino',
      'Smoothie', 'Gluehwein', 'Limonade', 'Cocktail',
    ],
  },
  {
    id: 'sports',
    name: 'Sportarten',
    emoji: '⚽',
    gradient: 'from-blue-500 to-cyan-600',
    words: [
      'Fussball', 'Tennis', 'Schwimmen', 'Ski fahren', 'Basketball',
      'Volleyball', 'Eishockey', 'Surfen', 'Boxen', 'Golf',
      'Yoga', 'Marathon', 'Snowboarden', 'Klettern', 'Reiten',
      'Fechten', 'Bogenschiessen', 'Tauchen', 'Segeln', 'Rudern',
      'Karate', 'Skateboardfahren', 'Trampolinspringen', 'Curling',
      'Darts', 'Tischtennis', 'Badminton', 'Handball', 'Wasserball',
      'Biathlon', 'Triathlon', 'Judo', 'Turnen', 'Baseball',
      'Rugby', 'Bowling', 'Ringen', 'Eiskunstlauf', 'Bobfahren',
      'Leichtathletik', 'Motorsport', 'Lacrosse', 'Polo',
      'Sumoringen', 'Parkour', 'Wakeboarden',
    ],
  },
  {
    id: 'professions',
    name: 'Berufe',
    emoji: '👷',
    gradient: 'from-indigo-500 to-blue-600',
    words: [
      'Feuerwehrmann', 'Astronaut', 'Zahnarzt', 'Pilot', 'Detektiv',
      'Baecker', 'Tierarzt', 'Dirigent', 'Taucher', 'Schiedsrichter',
      'Zauberer', 'Archaeologe', 'Bodyguard', 'Taxifahrer', 'Imker',
      'Schornsteinfeger', 'Stuntman', 'Chirurg', 'Leuchtturmwaerter',
      'Schafhirte', 'Schmied', 'Maskenbildner', 'Synchronsprecher',
      'Braumeister', 'Rettungsschwimmer', 'Gaertner', 'Uhrmacher',
      'Kartograf', 'Metzger', 'Sommelier', 'Arzt', 'Lehrer',
      'Polizist', 'Koch', 'Anwalt', 'Architekt', 'Fotograf',
      'Journalist', 'Richter', 'Apotheker', 'Brieftraeger',
      'Busfahrer', 'Kapitaen', 'Schauspieler', 'DJ', 'Friseur',
      'Schneider', 'Fluglotse', 'Professor', 'Goldschmied', 'Tischler',
    ],
  },
  {
    id: 'actions',
    name: 'Taetigkeiten',
    emoji: '🏃',
    gradient: 'from-teal-500 to-green-600',
    words: [
      'Haare foehnen', 'Zaehne putzen', 'Koffer packen', 'Tanzen',
      'Schlittschuh laufen', 'Selfie machen', 'Husten', 'Niesen',
      'Schnarchen', 'Buegeln', 'Staubsaugen', 'Gaehnen',
      'Jonglieren', 'Seilspringen', 'Gitarre spielen', 'Kochen',
      'Auto waschen', 'Einparken', 'Spuelmaschine ausraeumen',
      'Hund Gassi gehen', 'Naegel lackieren',
      'Luftgitarre spielen', 'Dauerlauf', 'Liegestuetze machen',
      'Schneemann bauen', 'Angeln', 'Tischdecken',
      'Schuhe binden', 'Pfeifen', 'Fahrrad fahren',
      'Geschenke einpacken', 'Kuchen backen', 'Seifenblasen pusten',
      'Kartenspielen', 'Drachen steigen lassen', 'Joggen',
      'Fruehstueck machen', 'Muell rausbringen', 'Schokolade essen',
      'Fotos machen',
    ],
  },
  {
    id: 'places',
    name: 'Orte & Laender',
    emoji: '🌍',
    gradient: 'from-sky-500 to-indigo-600',
    words: [
      'Paris', 'New York', 'Tokio', 'Aegypten', 'Australien',
      'Venedig', 'Hollywood', 'Antarktis', 'Hawaii', 'London',
      'Sahara', 'Amazonas', 'Bermuda-Dreieck', 'Mount Everest',
      'Grand Canyon', 'Niagarafaelle', 'Kolosseum', 'Freiheitsstatue',
      'Eiffelturm', 'Brandenburger Tor', 'Neuschwanstein',
      'Taj Mahal', 'Chinesische Mauer', 'Machu Picchu',
      'Stonehenge', 'Vatikan', 'Dubai', 'Las Vegas',
      'Oktoberfest Muenchen', 'Schwarzwald',
      'Deutschland', 'Frankreich', 'Italien', 'Spanien', 'Japan',
      'Brasilien', 'Kanada', 'Mexiko', 'Indien', 'Schweiz',
      'Oesterreich', 'Griechenland', 'Thailand', 'Island',
      'Neuseeland', 'Kroatien', 'Marokko', 'Peru', 'Kuba',
    ],
  },
  {
    id: 'fairytale',
    name: 'Maerchenfiguren',
    emoji: '🏰',
    words: [
      'Schneewittchen', 'Rotkappchen', 'Aschenputtel', 'Rapunzel', 'Dornroeschen',
      'Rumpelstilzchen', 'Frau Holle', 'Der gestiefelte Kater', 'Hans im Glueck', 'Froschkoenig',
      'Haensel und Gretel', 'Bremer Stadtmusikanten', 'Sterntaler', 'Der Wolf', 'Die boese Hexe',
      'Goldloeckchen', 'Pinocchio', 'Peter Pan', 'Robin Hood', 'Aladin',
      'Die kleine Meerjungfrau', 'Ali Baba', 'Daeumling', 'Sindbad', 'Schneekoenigin',
      'Zauberer von Oz', 'Rosenrot', 'Schneeweisschen', 'Der Rattenfaenger', 'Der kleine Prinz',
      'Struwwelpeter', 'Max und Moritz', 'Die sieben Zwerge', 'Fee', 'Drache',
      'Einhorn', 'Riese', 'Zwerg', 'Troll', 'Elfe',
    ],
    gradient: 'from-pink-500 to-purple-600',
  },
  {
    id: 'superheroes',
    name: 'Superhelden',
    emoji: '🦸',
    gradient: 'from-red-600 to-blue-600',
    words: [
      'Superman', 'Batman', 'Spider-Man', 'Iron Man', 'Thor',
      'Hulk', 'Captain America', 'Wonder Woman', 'Aquaman', 'Flash',
      'Wolverine', 'Black Panther', 'Deadpool', 'Doctor Strange', 'Ant-Man',
      'Green Lantern', 'Hawkeye', 'Black Widow', 'Scarlet Witch', 'Vision',
      'Catwoman', 'Robin', 'Joker', 'Thanos', 'Loki',
      'Harley Quinn', 'Poison Ivy', 'Magneto', 'Professor X', 'Storm',
      'Groot', 'Rocket Raccoon', 'Gamora', 'Star-Lord', 'Shazam',
      'Green Arrow', 'Nightwing', 'Elektra', 'Daredevil', 'Punisher',
    ],
  },
  {
    id: 'music',
    name: 'Musikbands & Saenger',
    emoji: '🎤',
    gradient: 'from-fuchsia-500 to-pink-600',
    words: [
      'Rammstein', 'Die Toten Hosen', 'Die Aerzte', 'Helene Fischer', 'Herbert Groenemeyer',
      'Nena', 'Udo Lindenberg', 'Falco', 'Scorpions', 'Kraftwerk',
      'Peter Maffay', 'Cro', 'Capital Bra', 'Apache 207', 'Mark Forster',
      'The Beatles', 'Queen', 'ABBA', 'Rolling Stones', 'Pink Floyd',
      'Nirvana', 'AC/DC', 'U2', 'Coldplay', 'Linkin Park',
      'Eminem', 'Michael Jackson', 'Madonna', 'Elvis Presley', 'David Bowie',
      'Bob Marley', 'Adele', 'Ed Sheeran', 'Beyonce', 'Taylor Swift',
      'Lady Gaga', 'Billie Eilish', 'Bruno Mars', 'The Weeknd', 'Dua Lipa',
      'Sia', 'Shakira', 'Imagine Dragons', 'Maroon 5', 'Arctic Monkeys',
    ],
  },
  {
    id: 'emojis',
    name: 'Emojis beschreiben',
    emoji: '😀',
    gradient: 'from-yellow-400 to-orange-500',
    words: [
      'Lachendes Gesicht', 'Traenen lachen', 'Herz Augen', 'Zwinkern', 'Kuss senden',
      'Nachdenklich', 'Trauriges Gesicht', 'Wütend', 'Überrascht', 'Schlafend',
      'Party Gesicht', 'Sonnenbrille', 'Verruecktes Gesicht', 'Geist', 'Clown',
      'Roboter', 'Affe Augen zu', 'Daumen hoch', 'Klatschen', 'Muskeln',
      'Friedenszeichen', 'Herz', 'Gebrochenes Herz', 'Feuer', 'Regenbogen',
      'Sonne', 'Wolke', 'Blitz', 'Schneeflocke', 'Rakete',
      'Krone', 'Diamant', 'Einhorn', 'Schmetterling', 'Weihnachtsbaum',
      'Geschenk', 'Geburtstagskuchen', 'Konfetti', 'Kleeblatt', 'Stern',
      'Pizza Stueck', 'Kaffeetasse', 'Tropisches Getraenk', 'Fussball', 'Pokal',
    ],
  },
  {
    id: 'science',
    name: 'Wissenschaft & Natur',
    emoji: '🔬',
    gradient: 'from-emerald-500 to-teal-600',
    words: [
      'Schwerkraft', 'Schwarzes Loch', 'Photosynthese', 'Evolution', 'Atom',
      'DNA', 'Elektrizitaet', 'Magnet', 'Teleskop', 'Mikroskop',
      'Vulkan', 'Erdbeben', 'Tsunami', 'Tornado', 'Nordlicht',
      'Regenbogen', 'Sternschnuppe', 'Mondfinsternis', 'Sonnenfinsternis', 'Komet',
      'Dinosaurier', 'Fossil', 'Gletscher', 'Geysir', 'Korallenriff',
      'Regenwald', 'Wueste', 'Tundra', 'Ozonschicht', 'Treibhauseffekt',
      'Roboter', 'Kuenstliche Intelligenz', 'Rakete', 'Satellit', 'Raumstation',
      'Batterie', 'Solar', 'Windenergie', 'Recycling', 'Klimawandel',
    ],
  },
  {
    id: 'history',
    name: 'Geschichte & Kultur',
    emoji: '🏛️',
    gradient: 'from-amber-600 to-yellow-500',
    words: [
      'Pyramide', 'Kolosseum', 'Ritter', 'Samurai', 'Wikinger',
      'Gladiator', 'Pharao', 'Caesar', 'Kleopatra', 'Napoleon',
      'Mittelalter', 'Renaissance', 'Industrielle Revolution', 'Mondlandung', 'Berliner Mauer',
      'Olympische Spiele', 'Demokratie', 'Buchdruck', 'Kompass', 'Dampfmaschine',
      'Titanic', 'Kolumbus', 'Marco Polo', 'Magellan', 'Gutenberg',
      'Hieroglyphen', 'Stonehenge', 'Machu Picchu', 'Terrakotta-Armee', 'Trojanisches Pferd',
      'Kreuzzug', 'Seidenstrasse', 'Roemer', 'Griechen', 'Azteken',
      'Mumie', 'Schatzkarte', 'Pirat', 'Entdecker', 'Zeitreise',
    ],
  },
];
