export interface QuizQuestion { id: string; question: string; answers: string[]; correctIndex: number; category: string; difficulty: 'easy' | 'medium' | 'hard'; }

export const QUIZ_QUESTIONS_ES: QuizQuestion[] = [
  // === Geografia (20) ===
  { id: 'geo-1', question: 'Cual es la capital de Australia?', answers: ['Sidney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-2', question: 'Cual es el rio mas largo del mundo?', answers: ['Amazonas', 'Nilo', 'Yangtsé', 'Misisipi'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-3', question: 'En que pais esta Machu Picchu?', answers: ['Bolivia', 'Ecuador', 'Peru', 'Colombia'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-4', question: 'Cuantas comunidades autonomas tiene Espana?', answers: ['15', '16', '17', '18'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-5', question: 'Cual es el pais mas pequeno del mundo?', answers: ['Monaco', 'Ciudad del Vaticano', 'San Marino', 'Liechtenstein'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-6', question: 'Que mar bana las costas de Croacia?', answers: ['Mar Negro', 'Mediterraneo', 'Mar Adriatico', 'Mar Egeo'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-7', question: 'Que pais tiene mas habitantes?', answers: ['India', 'China', 'EEUU', 'Indonesia'], correctIndex: 0, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-8', question: 'Cual es el desierto mas grande de la Tierra?', answers: ['Sahara', 'Gobi', 'Antartida', 'Kalahari'], correctIndex: 2, category: 'Geografia', difficulty: 'hard' },
  { id: 'geo-9', question: 'En que continente esta Egipto?', answers: ['Asia', 'Africa', 'Europa', 'Sudamerica'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-10', question: 'Que ciudad se conoce como la "Gran Manzana"?', answers: ['Los Angeles', 'Chicago', 'Nueva York', 'Boston'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-11', question: 'Que pais tiene forma de bota?', answers: ['Espana', 'Grecia', 'Italia', 'Portugal'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-12', question: 'Cual es la capital de Canada?', answers: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'], correctIndex: 3, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-13', question: 'Cual es la montana mas alta del mundo?', answers: ['K2', 'Kangchenjunga', 'Monte Everest', 'Lhotse'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-14', question: 'Que pais tiene mas islas?', answers: ['Indonesia', 'Filipinas', 'Suecia', 'Noruega'], correctIndex: 2, category: 'Geografia', difficulty: 'hard' },
  { id: 'geo-15', question: 'Por que rio pasa Paris?', answers: ['Ródano', 'Loira', 'Sena', 'Garona'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-16', question: 'Cual es el pais mas grande del mundo por superficie?', answers: ['Canada', 'China', 'EEUU', 'Rusia'], correctIndex: 3, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-17', question: 'En que pais esta la Estatua de la Libertad?', answers: ['Francia', 'EEUU', 'Inglaterra', 'Canada'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-18', question: 'Que ciudad esta en el Bosforo?', answers: ['Atenas', 'Estambul', 'Ankara', 'Bucarest'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-19', question: 'Cual es el lago mas grande de Sudamerica?', answers: ['Titicaca', 'Maracaibo', 'Buenos Aires', 'Poopo'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-20', question: 'Que pais no limita con Espana?', answers: ['Portugal', 'Italia', 'Francia', 'Andorra'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  // === Historia (20) ===
  { id: 'his-1', question: 'En que ano cayo el Muro de Berlin?', answers: ['1987', '1988', '1989', '1990'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'his-2', question: 'Quien fue el primer hombre en la Luna?', answers: ['Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'John Glenn'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-3', question: 'Que pueblo construyo las Piramides de Guiza?', answers: ['Romanos', 'Griegos', 'Egipcios', 'Persas'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'his-4', question: 'Cuando empezo la Primera Guerra Mundial?', answers: ['1912', '1914', '1916', '1918'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-5', question: 'Quien invento la imprenta?', answers: ['Martin Lutero', 'Johannes Gutenberg', 'Nicolas Copernico', 'Leonardo da Vinci'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-6', question: 'Que oceano nombro Magallanes como "Pacifico"?', answers: ['Atlantico', 'Indico', 'Pacifico', 'Artico'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  { id: 'his-7', question: 'Cuando se hundio el Titanic?', answers: ['1910', '1912', '1914', '1916'], correctIndex: 1, category: 'Historia', difficulty: 'medium' },
  { id: 'his-8', question: 'Que emperador romano mando construir el Coliseo?', answers: ['Neron', 'Augusto', 'Vespasiano', 'Trajano'], correctIndex: 2, category: 'Historia', difficulty: 'hard' },
  { id: 'his-9', question: 'En que ano Colon llego a America?', answers: ['1482', '1492', '1502', '1512'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-10', question: 'Que pais regalo la Estatua de la Libertad a EEUU?', answers: ['Inglaterra', 'Alemania', 'Francia', 'Espana'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  { id: 'his-11', question: 'Quien pinto la Mona Lisa?', answers: ['Miguel Angel', 'Rafael', 'Leonardo da Vinci', 'Rembrandt'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'his-12', question: 'Que animal era el emblema del Imperio Romano?', answers: ['Leon', 'Aguila', 'Oso', 'Lobo'], correctIndex: 1, category: 'Historia', difficulty: 'medium' },
  { id: 'his-13', question: 'Cuando termino la Segunda Guerra Mundial en Europa?', answers: ['1944', '1945', '1946', '1947'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-14', question: 'Quien escribio "El Quijote"?', answers: ['Lope de Vega', 'Miguel de Cervantes', 'Calderon de la Barca', 'Garcilaso'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-15', question: 'Que ciudad fue destruida por una erupcion volcanica en el 79 d.C.?', answers: ['Roma', 'Atenas', 'Pompeya', 'Cartago'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  { id: 'his-16', question: 'Quien fue Simon Bolivar?', answers: ['Rey espanol', 'Libertador de America del Sur', 'Papa', 'Explorador'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-17', question: 'Que imperio gobernaba gran parte de Sudamerica antes de la colonizacion?', answers: ['Azteca', 'Maya', 'Inca', 'Olmeca'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  { id: 'his-18', question: 'Que maravilla antigua estaba en Babilonia?', answers: ['Coloso de Rodas', 'Jardines Colgantes', 'Faro de Alejandria', 'Estatua de Zeus'], correctIndex: 1, category: 'Historia', difficulty: 'hard' },
  { id: 'his-19', question: 'Quien lidero la Reforma Protestante?', answers: ['Juan Calvino', 'Martin Lutero', 'Ulrico Zuinglio', 'Jan Hus'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-20', question: 'En que ano se firmo la Constitucion espanola actual?', answers: ['1975', '1977', '1978', '1980'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  // === Deporte (20) ===
  { id: 'spo-1', question: 'Cuantos jugadores tiene un equipo de futbol en el campo?', answers: ['9', '10', '11', '12'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-2', question: 'Que pais gano el Mundial de Futbol 2010?', answers: ['Brasil', 'Alemania', 'Espana', 'Holanda'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-3', question: 'Cuanto dura un partido de hockey sobre hielo?', answers: ['60 minutos', '80 minutos', '90 minutos', '120 minutos'], correctIndex: 0, category: 'Deporte', difficulty: 'medium' },
  { id: 'spo-4', question: 'Que boxeador era conocido como "The Greatest"?', answers: ['Mike Tyson', 'Muhammad Ali', 'Floyd Mayweather', 'Lennox Lewis'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-5', question: 'Cuantos anillos tiene el simbolo olimpico?', answers: ['3', '4', '5', '6'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-6', question: 'En que deporte hay un "Slam Dunk"?', answers: ['Voleibol', 'Tenis', 'Baloncesto', 'Balonmano'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-7', question: 'Quien tiene el record de los 100m lisos?', answers: ['Carl Lewis', 'Usain Bolt', 'Tyson Gay', 'Yohan Blake'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-8', question: 'Que Grand Slam se juega sobre hierba?', answers: ['Roland Garros', 'US Open', 'Open de Australia', 'Wimbledon'], correctIndex: 3, category: 'Deporte', difficulty: 'medium' },
  { id: 'spo-9', question: 'Cuantos puntos se necesitan para ganar un set de voleibol?', answers: ['15', '21', '25', '30'], correctIndex: 2, category: 'Deporte', difficulty: 'medium' },
  { id: 'spo-10', question: 'Que pais tiene mas medallas olimpicas de oro en total?', answers: ['China', 'Rusia', 'EEUU', 'Gran Bretana'], correctIndex: 2, category: 'Deporte', difficulty: 'medium' },
  { id: 'spo-11', question: 'En que ciudad se celebraron los JJOO de 1992?', answers: ['Atlanta', 'Barcelona', 'Sidney', 'Atenas'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-12', question: 'Cuantos sets hay que ganar en un Grand Slam masculino de tenis?', answers: ['2', '3', '4', '5'], correctIndex: 1, category: 'Deporte', difficulty: 'medium' },
  { id: 'spo-13', question: 'De que color es la bola numero 8 en billar?', answers: ['Roja', 'Azul', 'Negra', 'Verde'], correctIndex: 2, category: 'Deporte', difficulty: 'medium' },
  { id: 'spo-14', question: 'Cuantos kilometros tiene un maraton (redondeado)?', answers: ['40 km', '42 km', '44 km', '46 km'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-15', question: 'Que club tiene mas titulos de Champions League?', answers: ['FC Barcelona', 'AC Milan', 'Real Madrid', 'Bayern Munich'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-16', question: 'En que deporte se consigue un "Birdie"?', answers: ['Badminton', 'Golf', 'Cricket', 'Tenis'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-17', question: 'Cuantos jugadores hay en la cancha en un equipo de baloncesto?', answers: ['4', '5', '6', '7'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-18', question: 'Que pais es famoso por el sumo?', answers: ['China', 'Corea', 'Japon', 'Tailandia'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-19', question: 'Como se llama la primera division del futbol espanol?', answers: ['Serie A', 'LaLiga', 'Premier League', 'Bundesliga'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-20', question: 'Que deporte combina natacion, ciclismo y carrera?', answers: ['Biatlon', 'Triatlon', 'Pentatlon', 'Decatlon'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  // === Ciencia (20) ===
  { id: 'wis-1', question: 'Cual es la formula quimica del agua?', answers: ['H2O', 'CO2', 'O2', 'NaCl'], correctIndex: 0, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-2', question: 'Cuantos planetas tiene nuestro sistema solar?', answers: ['7', '8', '9', '10'], correctIndex: 1, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-3', question: 'Que gas absorben las plantas?', answers: ['Oxigeno', 'Nitrogeno', 'Dioxido de carbono', 'Helio'], correctIndex: 2, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-4', question: 'Que organo bombea la sangre por el cuerpo?', answers: ['Pulmones', 'Higado', 'Corazon', 'Rinon'], correctIndex: 2, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-5', question: 'Cual es la velocidad de la luz?', answers: ['150.000 km/s', '200.000 km/s', '300.000 km/s', '400.000 km/s'], correctIndex: 2, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-6', question: 'Que elemento tiene numero atomico 1?', answers: ['Helio', 'Hidrogeno', 'Litio', 'Oxigeno'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-7', question: 'Cual es la unidad de voltaje electrico?', answers: ['Amperio', 'Vatio', 'Voltio', 'Ohmio'], correctIndex: 2, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-8', question: 'Que planeta esta mas cerca del Sol?', answers: ['Venus', 'Mercurio', 'Marte', 'Tierra'], correctIndex: 1, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-9', question: 'Cual es la sustancia natural mas dura?', answers: ['Acero', 'Diamante', 'Cuarzo', 'Zafiro'], correctIndex: 1, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-10', question: 'Cuantos huesos tiene un adulto aproximadamente?', answers: ['106', '156', '206', '256'], correctIndex: 2, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-11', question: 'Que vitamina produce el cuerpo con la luz solar?', answers: ['Vitamina A', 'Vitamina B', 'Vitamina C', 'Vitamina D'], correctIndex: 3, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-12', question: 'Cual es la formula de la sal de mesa?', answers: ['KCl', 'NaCl', 'CaCl2', 'MgCl2'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-13', question: 'Que planeta tiene mas lunas?', answers: ['Jupiter', 'Saturno', 'Urano', 'Neptuno'], correctIndex: 1, category: 'Ciencia', difficulty: 'hard' },
  { id: 'wis-14', question: 'Que mide un barometro?', answers: ['Temperatura', 'Humedad', 'Presion atmosferica', 'Velocidad del viento'], correctIndex: 2, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-15', question: 'Que vaso sanguineo transporta sangre desde el corazon?', answers: ['Vena', 'Arteria', 'Capilar', 'Vaso linfatico'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-16', question: 'Quien desarrollo la teoria de la relatividad?', answers: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Max Planck'], correctIndex: 2, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-17', question: 'Cual es el organo mas grande del cuerpo humano?', answers: ['Higado', 'Piel', 'Pulmon', 'Intestino'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-18', question: 'Que animal tiene sangre azul?', answers: ['Pulpo', 'Tiburon', 'Medusa', 'Anguila'], correctIndex: 0, category: 'Ciencia', difficulty: 'hard' },
  { id: 'wis-19', question: 'Cual es el pH del agua pura?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-20', question: 'Que gas compone la mayor parte de la atmosfera?', answers: ['Oxigeno', 'Nitrogeno', 'Dioxido de carbono', 'Argon'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  // === Cine y TV (20) ===
  { id: 'fil-1', question: 'Quien interpreta a Jack Sparrow en "Piratas del Caribe"?', answers: ['Orlando Bloom', 'Johnny Depp', 'Brad Pitt', 'Leonardo DiCaprio'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-2', question: 'En que pelicula se dice "Yo soy tu padre"?', answers: ['Star Trek', 'Star Wars', 'Harry Potter', 'El Senor de los Anillos'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-3', question: 'Como se llama el protagonista de "Breaking Bad"?', answers: ['Jesse Pinkman', 'Saul Goodman', 'Walter White', 'Hank Schrader'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-4', question: 'Que pelicula gano el primer Oscar a la Mejor Pelicula?', answers: ['Wings', 'Sunrise', 'The Jazz Singer', 'Metropolis'], correctIndex: 0, category: 'Cine y TV', difficulty: 'hard' },
  { id: 'fil-5', question: 'Como se llama el pez payaso en "Buscando a Nemo"?', answers: ['Dory', 'Marlin', 'Nemo', 'Gil'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-6', question: 'Que director hizo "Titanic" y "Avatar"?', answers: ['Steven Spielberg', 'James Cameron', 'Christopher Nolan', 'Ridley Scott'], correctIndex: 1, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'fil-7', question: 'Cuantas peliculas de Harry Potter hay?', answers: ['6', '7', '8', '9'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-8', question: 'Que serie se ambienta en Invernalia?', answers: ['The Witcher', 'Juego de Tronos', 'Vikingos', 'The Last Kingdom'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-9', question: 'Quien interpreta al Joker en "El Caballero Oscuro"?', answers: ['Jack Nicholson', 'Joaquin Phoenix', 'Heath Ledger', 'Jared Leto'], correctIndex: 2, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'fil-10', question: 'En que ciudad se ambienta "Friends"?', answers: ['Los Angeles', 'Chicago', 'Nueva York', 'Boston'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-11', question: 'Que superheroe viene de Krypton?', answers: ['Batman', 'Spider-Man', 'Superman', 'Wonder Woman'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-12', question: 'Como se llama la nave espacial de "Star Trek"?', answers: ['Halcon Milenario', 'Enterprise', 'Serenity', 'Discovery'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-13', question: 'Que pelicula de Disney se ambienta en el "Dia de los Muertos" mexicano?', answers: ['Moana', 'Encanto', 'Coco', 'Luca'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-14', question: 'Quien creo "Los Simpson"?', answers: ['Seth MacFarlane', 'Matt Groening', 'Trey Parker', 'Mike Judge'], correctIndex: 1, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'fil-15', question: 'En que pelicula Neo lucha contra la Matrix?', answers: ['Origen', 'Blade Runner', 'Matrix', 'Tron'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-16', question: 'Como se llama la Reina de las Nieves en la pelicula de Disney?', answers: ['Anna', 'Elsa', 'Rapunzel', 'Merida'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-17', question: 'De que color es la piel de Shrek?', answers: ['Azul', 'Verde', 'Amarillo', 'Marron'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-18', question: 'En que serie aparecen los "Caminantes Blancos"?', answers: ['The Walking Dead', 'Juego de Tronos', 'Stranger Things', 'The 100'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-19', question: 'Quien interpreta a Iron Man en el MCU?', answers: ['Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr.', 'Mark Ruffalo'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-20', question: 'Que serie trata sobre un atraco en Espana?', answers: ['Narcos', 'La Casa de Papel', 'Elite', 'Vis a Vis'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  // === Musica (20) ===
  { id: 'mus-1', question: 'Que banda canto "Bohemian Rhapsody"?', answers: ['The Beatles', 'Led Zeppelin', 'Queen', 'Pink Floyd'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-2', question: 'De que pais es ABBA?', answers: ['Noruega', 'Dinamarca', 'Finlandia', 'Suecia'], correctIndex: 3, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-3', question: 'Quien es el "Rey del Pop"?', answers: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Freddie Mercury'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-4', question: 'Que instrumento tiene 88 teclas?', answers: ['Organo', 'Acordeon', 'Piano', 'Teclado'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-5', question: 'Quien compuso la "Sonata Claro de Luna"?', answers: ['Mozart', 'Beethoven', 'Bach', 'Chopin'], correctIndex: 1, category: 'Musica', difficulty: 'medium' },
  { id: 'mus-6', question: 'Cuantas cuerdas tiene una guitarra estandar?', answers: ['4', '5', '6', '7'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-7', question: 'Que cantante colombiana es famosa mundialmente?', answers: ['Jennifer Lopez', 'Shakira', 'Thalia', 'Gloria Estefan'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-8', question: 'Que cantante es conocida como "Queen Bey"?', answers: ['Rihanna', 'Beyonce', 'Adele', 'Taylor Swift'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-9', question: 'De que ciudad son los Beatles?', answers: ['Londres', 'Manchester', 'Liverpool', 'Birmingham'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-10', question: 'Que instrumento se toca con arco?', answers: ['Flauta', 'Violin', 'Trompeta', 'Guitarra'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-11', question: 'Cual es el festival de musica en el desierto de Nevada?', answers: ['Coachella', 'Burning Man', 'Tomorrowland', 'Glastonbury'], correctIndex: 1, category: 'Musica', difficulty: 'medium' },
  { id: 'mus-12', question: 'Que compositor se quedo sordo y siguio componiendo?', answers: ['Mozart', 'Beethoven', 'Haydn', 'Schubert'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-13', question: 'Que genero musical nacio en Puerto Rico y Panama?', answers: ['Salsa', 'Reggaeton', 'Bachata', 'Merengue'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-14', question: 'Que pais gana frecuentemente Eurovision?', answers: ['Suecia', 'Irlanda', 'Francia', 'Espana'], correctIndex: 0, category: 'Musica', difficulty: 'medium' },
  { id: 'mus-15', question: 'Que rapero es conocido por "Lose Yourself"?', answers: ['Jay-Z', '50 Cent', 'Eminem', 'Kanye West'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-16', question: 'Cuantas sinfonias escribio Beethoven?', answers: ['5', '7', '9', '12'], correctIndex: 2, category: 'Musica', difficulty: 'hard' },
  { id: 'mus-17', question: 'Que genero musical se origino en Jamaica?', answers: ['Blues', 'Reggae', 'Salsa', 'Samba'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-18', question: 'Quien canto "Rolling in the Deep"?', answers: ['Amy Winehouse', 'Adele', 'Lana Del Rey', 'Florence Welch'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-19', question: 'Que instrumento de viento es el mas grande de la orquesta?', answers: ['Trombon', 'Tuba', 'Trompa', 'Fagot'], correctIndex: 1, category: 'Musica', difficulty: 'medium' },
  { id: 'mus-20', question: 'Que cancion famosa canto Luis Fonsi?', answers: ['Bailando', 'Despacito', 'Vivir mi vida', 'La Bicicleta'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  // === Cultura general (20) + Naturaleza (20) + Tecnologia (20) + Comida (20) ===
  { id: 'all-1', question: 'Cuantos dias tiene un ano bisiesto?', answers: ['364', '365', '366', '367'], correctIndex: 2, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-2', question: 'Que color obtienes al mezclar azul y amarillo?', answers: ['Rojo', 'Verde', 'Naranja', 'Morado'], correctIndex: 1, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-3', question: 'Cuantas caras tiene un cubo?', answers: ['4', '6', '8', '12'], correctIndex: 1, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-4', question: 'Que significa "UE"?', answers: ['Union Europea', 'Unidad Economica', 'Union Euroasiatica', 'Unidad Energetica'], correctIndex: 0, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-5', question: 'Que animal es el simbolo de Espana en la tauromaquia?', answers: ['Aguila', 'Leon', 'Toro', 'Lobo'], correctIndex: 2, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-6', question: 'Cual es la raiz cuadrada de 144?', answers: ['10', '11', '12', '13'], correctIndex: 2, category: 'Cultura general', difficulty: 'medium' },
  { id: 'all-7', question: 'Cual es la moneda de Japon?', answers: ['Won', 'Yuan', 'Yen', 'Rupia'], correctIndex: 2, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-8', question: 'Que dia es el "Dia de la Hispanidad" en Espana?', answers: ['12 de octubre', '6 de diciembre', '1 de mayo', '15 de agosto'], correctIndex: 0, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-9', question: 'Cuantas provincias tiene Argentina?', answers: ['21', '22', '23', '24'], correctIndex: 2, category: 'Cultura general', difficulty: 'medium' },
  { id: 'all-10', question: 'Cual es la diferencia entre un camello y un dromedario?', answers: ['Color', 'Numero de jorobas', 'Tamano', 'Origen'], correctIndex: 1, category: 'Cultura general', difficulty: 'easy' },
  { id: 'nat-1', question: 'Cual es el animal mas grande del mundo?', answers: ['Elefante', 'Jirafa', 'Ballena azul', 'Tiburon blanco'], correctIndex: 2, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'nat-2', question: 'Cuantas patas tiene una arana?', answers: ['6', '8', '10', '12'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'nat-3', question: 'Que pajaro no puede volar?', answers: ['Aguila', 'Avestruz', 'Loro', 'Colibri'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'nat-4', question: 'Que animal hiberna?', answers: ['Zorro', 'Ciervo', 'Erizo', 'Ardilla'], correctIndex: 2, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'nat-5', question: 'De que esta compuesto quimicamente un diamante?', answers: ['Silicio', 'Carbono', 'Hierro', 'Calcio'], correctIndex: 1, category: 'Naturaleza', difficulty: 'medium' },
  { id: 'tec-1', question: 'Que significa "USB"?', answers: ['Universal System Bus', 'Universal Serial Bus', 'Unified Serial Bus', 'Ultra Speed Bus'], correctIndex: 1, category: 'Tecnologia', difficulty: 'medium' },
  { id: 'tec-2', question: 'Quien fundo Apple?', answers: ['Bill Gates', 'Steve Jobs', 'Elon Musk', 'Jeff Bezos'], correctIndex: 1, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'tec-3', question: 'Que significa "HTML"?', answers: ['Hyper Text Markup Language', 'High Tech Modern Language', 'Hyper Transfer Markup Language', 'Home Tool Markup Language'], correctIndex: 0, category: 'Tecnologia', difficulty: 'medium' },
  { id: 'tec-4', question: 'Que empresa desarrollo Android?', answers: ['Apple', 'Microsoft', 'Google', 'Samsung'], correctIndex: 2, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'tec-5', question: 'En que ano se presento el primer iPhone?', answers: ['2005', '2006', '2007', '2008'], correctIndex: 2, category: 'Tecnologia', difficulty: 'medium' },
  { id: 'ess-1', question: 'De que pais es originaria la pizza?', answers: ['Espana', 'Francia', 'Italia', 'Grecia'], correctIndex: 2, category: 'Comida', difficulty: 'easy' },
  { id: 'ess-2', question: 'Que es el wasabi?', answers: ['Una fruta', 'Un pescado', 'Una pasta picante', 'Una bebida'], correctIndex: 2, category: 'Comida', difficulty: 'easy' },
  { id: 'ess-3', question: 'Que bebida se hace con uvas?', answers: ['Cerveza', 'Whisky', 'Vino', 'Vodka'], correctIndex: 2, category: 'Comida', difficulty: 'easy' },
  { id: 'ess-4', question: 'Que es el tofu?', answers: ['Un sustituto de carne de soja', 'Un pescado', 'Una verdura', 'Un tipo de fideo'], correctIndex: 0, category: 'Comida', difficulty: 'easy' },
  { id: 'ess-5', question: 'De que pais viene el sushi?', answers: ['China', 'Corea', 'Japon', 'Tailandia'], correctIndex: 2, category: 'Comida', difficulty: 'easy' },
];

let _usedIndices: Set<number> = new Set();
export function getRandomQuestion(): QuizQuestion { if (_usedIndices.size >= QUIZ_QUESTIONS_ES.length) { _usedIndices.clear(); } let idx: number; do { idx = Math.floor(Math.random() * QUIZ_QUESTIONS_ES.length); } while (_usedIndices.has(idx)); _usedIndices.add(idx); return QUIZ_QUESTIONS_ES[idx]; }
export function resetQuestions(): void { _usedIndices.clear(); }
