export interface QuizQuestion { id: string; question: string; answers: string[]; correctIndex: number; category: string; difficulty: 'easy' | 'medium' | 'hard'; }

export const QUIZ_QUESTIONS_ES: QuizQuestion[] = [
  // === Geografia (20) ===
  { id: 'geo-1', question: 'Cual es la capital de Australia?', answers: ['Sidney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-2', question: 'Cual es el rio mas largo del mundo?', answers: ['Amazonas', 'Nilo', 'Yangtsé', 'Misisipi'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-3', question: 'En que pais esta Machu Picchu?', answers: ['Bolivia', 'Ecuador', 'Peru', 'Colombia'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-4', question: 'Cuantas comunidades autonomas tiene Espana?', answers: ['15', '16', '17', '18'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-5', question: 'Cual es el pais mas pequeno del mundo?', answers: ['Monaco', 'Ciudad del Vaticano', 'San Marino', 'Liechtenstein'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-6', question: 'Que mar bana las costas de Croacia?', answers: ['Mar Negro', 'Mediterraneo', 'Mar Adriatico', 'Mar Egeo'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-7', question: 'Que pais tiene mas habitantes?', answers: ['India', 'China', 'EEUU', 'Indonesia'], correctIndex: 0, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-8', question: 'Cual es el desierto mas grande de la Tierra?', answers: ['Sahara', 'Gobi', 'Antartida', 'Kalahari'], correctIndex: 2, category: 'Geografia', difficulty: 'hard' },
  { id: 'geo-9', question: 'En que continente esta Egipto?', answers: ['Asia', 'Africa', 'Europa', 'Sudamerica'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-10', question: 'Que ciudad se conoce como la "Gran Manzana"?', answers: ['Los Angeles', 'Chicago', 'Nueva York', 'Boston'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-11', question: 'Que pais tiene forma de bota?', answers: ['Espana', 'Grecia', 'Italia', 'Portugal'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-12', question: 'Cual es la capital de Canada?', answers: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'], correctIndex: 3, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-13', question: 'Cual es la montana mas alta del mundo?', answers: ['K2', 'Kangchenjunga', 'Monte Everest', 'Lhotse'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-14', question: 'Que pais tiene mas islas?', answers: ['Indonesia', 'Filipinas', 'Suecia', 'Noruega'], correctIndex: 2, category: 'Geografia', difficulty: 'hard' },
  { id: 'geo-15', question: 'Por que rio pasa Paris?', answers: ['Ródano', 'Loira', 'Sena', 'Garona'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-16', question: 'Cual es el pais mas grande del mundo por superficie?', answers: ['Canada', 'China', 'EEUU', 'Rusia'], correctIndex: 3, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-17', question: 'En que pais esta la Estatua de la Libertad?', answers: ['Francia', 'EEUU', 'Inglaterra', 'Canada'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-18', question: 'Que ciudad esta en el Bosforo?', answers: ['Atenas', 'Estambul', 'Ankara', 'Bucarest'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-19', question: 'Cual es el lago mas grande de Sudamerica?', answers: ['Titicaca', 'Maracaibo', 'Buenos Aires', 'Poopo'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-20', question: 'Que pais no limita con Espana?', answers: ['Portugal', 'Italia', 'Francia', 'Andorra'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  // === Historia (20) ===
  { id: 'his-1', question: 'En que ano cayo el Muro de Berlin?', answers: ['1987', '1988', '1989', '1990'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'his-2', question: 'Quien fue el primer hombre en la Luna?', answers: ['Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'John Glenn'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-3', question: 'Que pueblo construyo las Piramides de Guiza?', answers: ['Romanos', 'Griegos', 'Egipcios', 'Persas'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'his-4', question: 'Cuando empezo la Primera Guerra Mundial?', answers: ['1912', '1914', '1916', '1918'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-5', question: 'Quien invento la imprenta?', answers: ['Martin Lutero', 'Johannes Gutenberg', 'Nicolas Copernico', 'Leonardo da Vinci'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-6', question: 'Que oceano nombro Magallanes como "Pacifico"?', answers: ['Atlantico', 'Indico', 'Pacifico', 'Artico'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  { id: 'his-7', question: 'Cuando se hundio el Titanic?', answers: ['1910', '1912', '1914', '1916'], correctIndex: 1, category: 'Historia', difficulty: 'medium' },
  { id: 'his-8', question: 'Que emperador romano mando construir el Coliseo?', answers: ['Neron', 'Augusto', 'Vespasiano', 'Trajano'], correctIndex: 2, category: 'Historia', difficulty: 'hard' },
  { id: 'his-9', question: 'En que ano Colon llego a America?', answers: ['1482', '1492', '1502', '1512'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-10', question: 'Que pais regalo la Estatua de la Libertad a EEUU?', answers: ['Inglaterra', 'Alemania', 'Francia', 'Espana'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  { id: 'his-11', question: 'Quien pinto la Mona Lisa?', answers: ['Miguel Angel', 'Rafael', 'Leonardo da Vinci', 'Rembrandt'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'his-12', question: 'Que animal era el emblema del Imperio Romano?', answers: ['Leon', 'Aguila', 'Oso', 'Lobo'], correctIndex: 1, category: 'Historia', difficulty: 'medium' },
  { id: 'his-13', question: 'Cuando termino la Segunda Guerra Mundial en Europa?', answers: ['1944', '1945', '1946', '1947'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-14', question: 'Quien escribio "El Quijote"?', answers: ['Lope de Vega', 'Miguel de Cervantes', 'Calderon de la Barca', 'Garcilaso'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-15', question: 'Que ciudad fue destruida por una erupcion volcanica en el 79 d.C.?', answers: ['Roma', 'Atenas', 'Pompeya', 'Cartago'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  { id: 'his-16', question: 'Quien fue Simon Bolivar?', answers: ['Rey espanol', 'Libertador de America del Sur', 'Papa', 'Explorador'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-17', question: 'Que imperio gobernaba gran parte de Sudamerica antes de la colonizacion?', answers: ['Azteca', 'Maya', 'Inca', 'Olmeca'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  { id: 'his-18', question: 'Que maravilla antigua estaba en Babilonia?', answers: ['Coloso de Rodas', 'Jardines Colgantes', 'Faro de Alejandria', 'Estatua de Zeus'], correctIndex: 1, category: 'Historia', difficulty: 'hard' },
  { id: 'his-19', question: 'Quien lidero la Reforma Protestante?', answers: ['Juan Calvino', 'Martin Lutero', 'Ulrico Zuinglio', 'Jan Hus'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-20', question: 'En que ano se firmo la Constitucion espanola actual?', answers: ['1975', '1977', '1978', '1980'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  // === Deporte (20) ===
  { id: 'spo-1', question: 'Cuantos jugadores tiene un equipo de futbol en el campo?', answers: ['9', '10', '11', '12'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-2', question: 'Que pais gano el Mundial de Futbol 2010?', answers: ['Brasil', 'Alemania', 'Espana', 'Holanda'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-3', question: 'Cuanto dura un partido de hockey sobre hielo?', answers: ['60 minutos', '80 minutos', '90 minutos', '120 minutos'], correctIndex: 0, category: 'Deporte', difficulty: 'medium' },
  { id: 'spo-4', question: 'Que boxeador era conocido como "The Greatest"?', answers: ['Mike Tyson', 'Muhammad Ali', 'Floyd Mayweather', 'Lennox Lewis'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-5', question: 'Cuantos anillos tiene el simbolo olimpico?', answers: ['3', '4', '5', '6'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-6', question: 'En que deporte hay un "Slam Dunk"?', answers: ['Voleibol', 'Tenis', 'Baloncesto', 'Balonmano'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-7', question: 'Quien tiene el record de los 100m lisos?', answers: ['Carl Lewis', 'Usain Bolt', 'Tyson Gay', 'Yohan Blake'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-8', question: 'Que Grand Slam se juega sobre hierba?', answers: ['Roland Garros', 'US Open', 'Open de Australia', 'Wimbledon'], correctIndex: 3, category: 'Deporte', difficulty: 'medium' },
  { id: 'spo-9', question: 'Cuantos puntos se necesitan para ganar un set de voleibol?', answers: ['15', '21', '25', '30'], correctIndex: 2, category: 'Deporte', difficulty: 'medium' },
  { id: 'spo-10', question: 'Que pais tiene mas medallas olimpicas de oro en total?', answers: ['China', 'Rusia', 'EEUU', 'Gran Bretana'], correctIndex: 2, category: 'Deporte', difficulty: 'medium' },
  { id: 'spo-11', question: 'En que ciudad se celebraron los JJOO de 1992?', answers: ['Atlanta', 'Barcelona', 'Sidney', 'Atenas'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-12', question: 'Cuantos sets hay que ganar en un Grand Slam masculino de tenis?', answers: ['2', '3', '4', '5'], correctIndex: 1, category: 'Deporte', difficulty: 'medium' },
  { id: 'spo-13', question: 'De que color es la bola numero 8 en billar?', answers: ['Roja', 'Azul', 'Negra', 'Verde'], correctIndex: 2, category: 'Deporte', difficulty: 'medium' },
  { id: 'spo-14', question: 'Cuantos kilometros tiene un maraton (redondeado)?', answers: ['40 km', '42 km', '44 km', '46 km'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-15', question: 'Que club tiene mas titulos de Champions League?', answers: ['FC Barcelona', 'AC Milan', 'Real Madrid', 'Bayern Munich'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-16', question: 'En que deporte se consigue un "Birdie"?', answers: ['Badminton', 'Golf', 'Cricket', 'Tenis'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-17', question: 'Cuantos jugadores hay en la cancha en un equipo de baloncesto?', answers: ['4', '5', '6', '7'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-18', question: 'Que pais es famoso por el sumo?', answers: ['China', 'Corea', 'Japon', 'Tailandia'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-19', question: 'Como se llama la primera division del futbol espanol?', answers: ['Serie A', 'LaLiga', 'Premier League', 'Bundesliga'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'spo-20', question: 'Que deporte combina natacion, ciclismo y carrera?', answers: ['Biatlon', 'Triatlon', 'Pentatlon', 'Decatlon'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  // === Ciencia (20) ===
  { id: 'wis-1', question: 'Cual es la formula quimica del agua?', answers: ['H2O', 'CO2', 'O2', 'NaCl'], correctIndex: 0, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-2', question: 'Cuantos planetas tiene nuestro sistema solar?', answers: ['7', '8', '9', '10'], correctIndex: 1, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-3', question: 'Que gas absorben las plantas?', answers: ['Oxigeno', 'Nitrogeno', 'Dioxido de carbono', 'Helio'], correctIndex: 2, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-4', question: 'Que organo bombea la sangre por el cuerpo?', answers: ['Pulmones', 'Higado', 'Corazon', 'Rinon'], correctIndex: 2, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-5', question: 'Cual es la velocidad de la luz?', answers: ['150.000 km/s', '200.000 km/s', '300.000 km/s', '400.000 km/s'], correctIndex: 2, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-6', question: 'Que elemento tiene numero atomico 1?', answers: ['Helio', 'Hidrogeno', 'Litio', 'Oxigeno'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-7', question: 'Cual es la unidad de voltaje electrico?', answers: ['Amperio', 'Vatio', 'Voltio', 'Ohmio'], correctIndex: 2, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-8', question: 'Que planeta esta mas cerca del Sol?', answers: ['Venus', 'Mercurio', 'Marte', 'Tierra'], correctIndex: 1, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-9', question: 'Cual es la sustancia natural mas dura?', answers: ['Acero', 'Diamante', 'Cuarzo', 'Zafiro'], correctIndex: 1, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-10', question: 'Cuantos huesos tiene un adulto aproximadamente?', answers: ['106', '156', '206', '256'], correctIndex: 2, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-11', question: 'Que vitamina produce el cuerpo con la luz solar?', answers: ['Vitamina A', 'Vitamina B', 'Vitamina C', 'Vitamina D'], correctIndex: 3, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-12', question: 'Cual es la formula de la sal de mesa?', answers: ['KCl', 'NaCl', 'CaCl2', 'MgCl2'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-13', question: 'Que planeta tiene mas lunas?', answers: ['Jupiter', 'Saturno', 'Urano', 'Neptuno'], correctIndex: 1, category: 'Ciencia', difficulty: 'hard' },
  { id: 'wis-14', question: 'Que mide un barometro?', answers: ['Temperatura', 'Humedad', 'Presion atmosferica', 'Velocidad del viento'], correctIndex: 2, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-15', question: 'Que vaso sanguineo transporta sangre desde el corazon?', answers: ['Vena', 'Arteria', 'Capilar', 'Vaso linfatico'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-16', question: 'Quien desarrollo la teoria de la relatividad?', answers: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Max Planck'], correctIndex: 2, category: 'Ciencia', difficulty: 'easy' },
  { id: 'wis-17', question: 'Cual es el organo mas grande del cuerpo humano?', answers: ['Higado', 'Piel', 'Pulmon', 'Intestino'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-18', question: 'Que animal tiene sangre azul?', answers: ['Pulpo', 'Tiburon', 'Medusa', 'Anguila'], correctIndex: 0, category: 'Ciencia', difficulty: 'hard' },
  { id: 'wis-19', question: 'Cual es el pH del agua pura?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Ciencia', difficulty: 'medium' },
  { id: 'wis-20', question: 'Que gas compone la mayor parte de la atmosfera?', answers: ['Oxigeno', 'Nitrogeno', 'Dioxido de carbono', 'Argon'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  // === Cine y TV (20) ===
  { id: 'fil-1', question: 'Quien interpreta a Jack Sparrow en "Piratas del Caribe"?', answers: ['Orlando Bloom', 'Johnny Depp', 'Brad Pitt', 'Leonardo DiCaprio'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-2', question: 'En que pelicula se dice "Yo soy tu padre"?', answers: ['Star Trek', 'Star Wars', 'Harry Potter', 'El Senor de los Anillos'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-3', question: 'Como se llama el protagonista de "Breaking Bad"?', answers: ['Jesse Pinkman', 'Saul Goodman', 'Walter White', 'Hank Schrader'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-4', question: 'Que pelicula gano el primer Oscar a la Mejor Pelicula?', answers: ['Wings', 'Sunrise', 'The Jazz Singer', 'Metropolis'], correctIndex: 0, category: 'Cine y TV', difficulty: 'hard' },
  { id: 'fil-5', question: 'Como se llama el pez payaso en "Buscando a Nemo"?', answers: ['Dory', 'Marlin', 'Nemo', 'Gil'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-6', question: 'Que director hizo "Titanic" y "Avatar"?', answers: ['Steven Spielberg', 'James Cameron', 'Christopher Nolan', 'Ridley Scott'], correctIndex: 1, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'fil-7', question: 'Cuantas peliculas de Harry Potter hay?', answers: ['6', '7', '8', '9'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-8', question: 'Que serie se ambienta en Invernalia?', answers: ['The Witcher', 'Juego de Tronos', 'Vikingos', 'The Last Kingdom'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-9', question: 'Quien interpreta al Joker en "El Caballero Oscuro"?', answers: ['Jack Nicholson', 'Joaquin Phoenix', 'Heath Ledger', 'Jared Leto'], correctIndex: 2, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'fil-10', question: 'En que ciudad se ambienta "Friends"?', answers: ['Los Angeles', 'Chicago', 'Nueva York', 'Boston'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-11', question: 'Que superheroe viene de Krypton?', answers: ['Batman', 'Spider-Man', 'Superman', 'Wonder Woman'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-12', question: 'Como se llama la nave espacial de "Star Trek"?', answers: ['Halcon Milenario', 'Enterprise', 'Serenity', 'Discovery'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-13', question: 'Que pelicula de Disney se ambienta en el "Dia de los Muertos" mexicano?', answers: ['Moana', 'Encanto', 'Coco', 'Luca'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-14', question: 'Quien creo "Los Simpson"?', answers: ['Seth MacFarlane', 'Matt Groening', 'Trey Parker', 'Mike Judge'], correctIndex: 1, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'fil-15', question: 'En que pelicula Neo lucha contra la Matrix?', answers: ['Origen', 'Blade Runner', 'Matrix', 'Tron'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-16', question: 'Como se llama la Reina de las Nieves en la pelicula de Disney?', answers: ['Anna', 'Elsa', 'Rapunzel', 'Merida'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-17', question: 'De que color es la piel de Shrek?', answers: ['Azul', 'Verde', 'Amarillo', 'Marron'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-18', question: 'En que serie aparecen los "Caminantes Blancos"?', answers: ['The Walking Dead', 'Juego de Tronos', 'Stranger Things', 'The 100'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-19', question: 'Quien interpreta a Iron Man en el MCU?', answers: ['Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr.', 'Mark Ruffalo'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'fil-20', question: 'Que serie trata sobre un atraco en Espana?', answers: ['Narcos', 'La Casa de Papel', 'Elite', 'Vis a Vis'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  // === Musica (20) ===
  { id: 'mus-1', question: 'Que banda canto "Bohemian Rhapsody"?', answers: ['The Beatles', 'Led Zeppelin', 'Queen', 'Pink Floyd'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-2', question: 'De que pais es ABBA?', answers: ['Noruega', 'Dinamarca', 'Finlandia', 'Suecia'], correctIndex: 3, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-3', question: 'Quien es el "Rey del Pop"?', answers: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Freddie Mercury'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-4', question: 'Que instrumento tiene 88 teclas?', answers: ['Organo', 'Acordeon', 'Piano', 'Teclado'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-5', question: 'Quien compuso la "Sonata Claro de Luna"?', answers: ['Mozart', 'Beethoven', 'Bach', 'Chopin'], correctIndex: 1, category: 'Musica', difficulty: 'medium' },
  { id: 'mus-6', question: 'Cuantas cuerdas tiene una guitarra estandar?', answers: ['4', '5', '6', '7'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-7', question: 'Que cantante colombiana es famosa mundialmente?', answers: ['Jennifer Lopez', 'Shakira', 'Thalia', 'Gloria Estefan'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-8', question: 'Que cantante es conocida como "Queen Bey"?', answers: ['Rihanna', 'Beyonce', 'Adele', 'Taylor Swift'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-9', question: 'De que ciudad son los Beatles?', answers: ['Londres', 'Manchester', 'Liverpool', 'Birmingham'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-10', question: 'Que instrumento se toca con arco?', answers: ['Flauta', 'Violin', 'Trompeta', 'Guitarra'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-11', question: 'Cual es el festival de musica en el desierto de Nevada?', answers: ['Coachella', 'Burning Man', 'Tomorrowland', 'Glastonbury'], correctIndex: 1, category: 'Musica', difficulty: 'medium' },
  { id: 'mus-12', question: 'Que compositor se quedo sordo y siguio componiendo?', answers: ['Mozart', 'Beethoven', 'Haydn', 'Schubert'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-13', question: 'Que genero musical nacio en Puerto Rico y Panama?', answers: ['Salsa', 'Reggaeton', 'Bachata', 'Merengue'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-14', question: 'Que pais gana frecuentemente Eurovision?', answers: ['Suecia', 'Irlanda', 'Francia', 'Espana'], correctIndex: 0, category: 'Musica', difficulty: 'medium' },
  { id: 'mus-15', question: 'Que rapero es conocido por "Lose Yourself"?', answers: ['Jay-Z', '50 Cent', 'Eminem', 'Kanye West'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-16', question: 'Cuantas sinfonias escribio Beethoven?', answers: ['5', '7', '9', '12'], correctIndex: 2, category: 'Musica', difficulty: 'hard' },
  { id: 'mus-17', question: 'Que genero musical se origino en Jamaica?', answers: ['Blues', 'Reggae', 'Salsa', 'Samba'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-18', question: 'Quien canto "Rolling in the Deep"?', answers: ['Amy Winehouse', 'Adele', 'Lana Del Rey', 'Florence Welch'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-19', question: 'Que instrumento de viento es el mas grande de la orquesta?', answers: ['Trombon', 'Tuba', 'Trompa', 'Fagot'], correctIndex: 1, category: 'Musica', difficulty: 'medium' },
  { id: 'mus-20', question: 'Que cancion famosa canto Luis Fonsi?', answers: ['Bailando', 'Despacito', 'Vivir mi vida', 'La Bicicleta'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  // === Cultura general (20) + Naturaleza (20) + Tecnologia (20) + Comida (20) ===
  { id: 'all-1', question: 'Cuantos dias tiene un ano bisiesto?', answers: ['364', '365', '366', '367'], correctIndex: 2, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-2', question: 'Que color obtienes al mezclar azul y amarillo?', answers: ['Rojo', 'Verde', 'Naranja', 'Morado'], correctIndex: 1, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-3', question: 'Cuantas caras tiene un cubo?', answers: ['4', '6', '8', '12'], correctIndex: 1, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-4', question: 'Que significa "UE"?', answers: ['Union Europea', 'Unidad Economica', 'Union Euroasiatica', 'Unidad Energetica'], correctIndex: 0, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-5', question: 'Que animal es el simbolo de Espana en la tauromaquia?', answers: ['Aguila', 'Leon', 'Toro', 'Lobo'], correctIndex: 2, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-6', question: 'Cual es la raiz cuadrada de 144?', answers: ['10', '11', '12', '13'], correctIndex: 2, category: 'Cultura general', difficulty: 'medium' },
  { id: 'all-7', question: 'Cual es la moneda de Japon?', answers: ['Won', 'Yuan', 'Yen', 'Rupia'], correctIndex: 2, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-8', question: 'Que dia es el "Dia de la Hispanidad" en Espana?', answers: ['12 de octubre', '6 de diciembre', '1 de mayo', '15 de agosto'], correctIndex: 0, category: 'Cultura general', difficulty: 'easy' },
  { id: 'all-9', question: 'Cuantas provincias tiene Argentina?', answers: ['21', '22', '23', '24'], correctIndex: 2, category: 'Cultura general', difficulty: 'medium' },
  { id: 'all-10', question: 'Cual es la diferencia entre un camello y un dromedario?', answers: ['Color', 'Numero de jorobas', 'Tamano', 'Origen'], correctIndex: 1, category: 'Cultura general', difficulty: 'easy' },
  { id: 'nat-1', question: 'Cual es el animal mas grande del mundo?', answers: ['Elefante', 'Jirafa', 'Ballena azul', 'Tiburon blanco'], correctIndex: 2, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'nat-2', question: 'Cuantas patas tiene una arana?', answers: ['6', '8', '10', '12'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'nat-3', question: 'Que pajaro no puede volar?', answers: ['Aguila', 'Avestruz', 'Loro', 'Colibri'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'nat-4', question: 'Que animal hiberna?', answers: ['Zorro', 'Ciervo', 'Erizo', 'Ardilla'], correctIndex: 2, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'nat-5', question: 'De que esta compuesto quimicamente un diamante?', answers: ['Silicio', 'Carbono', 'Hierro', 'Calcio'], correctIndex: 1, category: 'Naturaleza', difficulty: 'medium' },
  { id: 'tec-1', question: 'Que significa "USB"?', answers: ['Universal System Bus', 'Universal Serial Bus', 'Unified Serial Bus', 'Ultra Speed Bus'], correctIndex: 1, category: 'Tecnologia', difficulty: 'medium' },
  { id: 'tec-2', question: 'Quien fundo Apple?', answers: ['Bill Gates', 'Steve Jobs', 'Elon Musk', 'Jeff Bezos'], correctIndex: 1, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'tec-3', question: 'Que significa "HTML"?', answers: ['Hyper Text Markup Language', 'High Tech Modern Language', 'Hyper Transfer Markup Language', 'Home Tool Markup Language'], correctIndex: 0, category: 'Tecnologia', difficulty: 'medium' },
  { id: 'tec-4', question: 'Que empresa desarrollo Android?', answers: ['Apple', 'Microsoft', 'Google', 'Samsung'], correctIndex: 2, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'tec-5', question: 'En que ano se presento el primer iPhone?', answers: ['2005', '2006', '2007', '2008'], correctIndex: 2, category: 'Tecnologia', difficulty: 'medium' },
  { id: 'ess-1', question: 'De que pais es originaria la pizza?', answers: ['Espana', 'Francia', 'Italia', 'Grecia'], correctIndex: 2, category: 'Comida', difficulty: 'easy' },
  { id: 'ess-2', question: 'Que es el wasabi?', answers: ['Una fruta', 'Un pescado', 'Una pasta picante', 'Una bebida'], correctIndex: 2, category: 'Comida', difficulty: 'easy' },
  { id: 'ess-3', question: 'Que bebida se hace con uvas?', answers: ['Cerveza', 'Whisky', 'Vino', 'Vodka'], correctIndex: 2, category: 'Comida', difficulty: 'easy' },
  { id: 'ess-4', question: 'Que es el tofu?', answers: ['Un sustituto de carne de soja', 'Un pescado', 'Una verdura', 'Un tipo de fideo'], correctIndex: 0, category: 'Comida', difficulty: 'easy' },
  { id: 'ess-5', question: 'De que pais viene el sushi?', answers: ['China', 'Corea', 'Japon', 'Tailandia'], correctIndex: 2, category: 'Comida', difficulty: 'easy' },
  { id: 'xq-1', question: '¿Cuál es el río más largo de la Península Ibérica?', answers: ['El Ebro', 'El Tajo', 'El Guadalquivir', 'El Duero'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-2', question: '¿Cuál es la capital de Australia?', answers: ['Sídney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, category: 'Geografia', difficulty: 'medium' },
  { id: 'xq-3', question: '¿En qué comunidad autónoma se encuentra la ciudad de Santiago de Compostela?', answers: ['Asturias', 'Galicia', 'Cantabria', 'Castilla y León'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-4', question: '¿Cuál es el país más extenso del mundo por superficie?', answers: ['China', 'Canadá', 'Estados Unidos', 'Rusia'], correctIndex: 3, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-5', question: '¿Qué estrecho separa España del continente africano?', answers: ['El estrecho de Gibraltar', 'El estrecho de Mesina', 'El estrecho de Ormuz', 'El estrecho del Bósforo'], correctIndex: 0, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-6', question: '¿Cuál es el archipiélago español situado en el océano Atlántico?', answers: ['Las Islas Baleares', 'Las Islas Cíes', 'Las Islas Canarias', 'Las Islas Columbretes'], correctIndex: 2, category: 'Geografia', difficulty: 'medium' },
  { id: 'xq-7', question: '¿En qué año descubrió Cristóbal Colón América?', answers: ['1485', '1492', '1500', '1510'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'xq-8', question: '¿Qué muro cayó en 1989 marcando el fin de la división de Alemania?', answers: ['El Muro de Berlín', 'La Línea Maginot', 'El Muro de Adriano', 'La Gran Muralla'], correctIndex: 0, category: 'Historia', difficulty: 'easy' },
  { id: 'xq-9', question: '¿Quién fue el primer rey de la España moderna tras la unión de Castilla y Aragón?', answers: ['Felipe II', 'Carlos I', 'Fernando el Católico', 'Alfonso XIII'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  { id: 'xq-10', question: '¿En qué año comenzó la Guerra Civil Española?', answers: ['1931', '1936', '1939', '1945'], correctIndex: 1, category: 'Historia', difficulty: 'medium' },
  { id: 'xq-11', question: '¿Qué civilización construyó las pirámides de Giza?', answers: ['Los romanos', 'Los griegos', 'Los egipcios', 'Los persas'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'xq-12', question: '¿Quién pronunció el famoso discurso \'I Have a Dream\' en 1963?', answers: ['Malcolm X', 'Martin Luther King', 'Nelson Mandela', 'Barack Obama'], correctIndex: 1, category: 'Historia', difficulty: 'medium' },
  { id: 'xq-13', question: '¿Cada cuántos años se celebran los Juegos Olímpicos de verano?', answers: ['Cada 2 años', 'Cada 3 años', 'Cada 4 años', 'Cada 5 años'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'xq-14', question: '¿En qué deporte destacó el tenista español Rafael Nadal especialmente sobre tierra batida?', answers: ['Pádel', 'Tenis', 'Bádminton', 'Squash'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'xq-15', question: '¿Cuántos jugadores tiene un equipo de fútbol en el campo durante un partido?', answers: ['9', '10', '11', '12'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'xq-16', question: '¿Qué selección ganó el Mundial de Fútbol de 2010 celebrado en Sudáfrica?', answers: ['Países Bajos', 'Alemania', 'España', 'Brasil'], correctIndex: 2, category: 'Deporte', difficulty: 'medium' },
  { id: 'xq-17', question: '¿En qué ciudad se celebra el famoso torneo de tenis de Wimbledon?', answers: ['París', 'Nueva York', 'Londres', 'Melbourne'], correctIndex: 2, category: 'Deporte', difficulty: 'medium' },
  { id: 'xq-18', question: '¿Cuántos anillos tiene el símbolo olímpico?', answers: ['Cuatro', 'Cinco', 'Seis', 'Siete'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'xq-19', question: '¿Cuál es el planeta más grande del Sistema Solar?', answers: ['Saturno', 'Júpiter', 'Neptuno', 'Urano'], correctIndex: 1, category: 'Ciencia', difficulty: 'easy' },
  { id: 'xq-20', question: '¿Cuál es el símbolo químico del oro?', answers: ['Or', 'Au', 'Ag', 'Go'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'xq-21', question: '¿Cuántos huesos tiene aproximadamente el cuerpo humano adulto?', answers: ['106', '206', '306', '406'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'xq-22', question: '¿Qué gas absorben las plantas durante la fotosíntesis?', answers: ['Oxígeno', 'Nitrógeno', 'Dióxido de carbono', 'Hidrógeno'], correctIndex: 2, category: 'Ciencia', difficulty: 'easy' },
  { id: 'xq-23', question: '¿Quién formuló la teoría de la relatividad?', answers: ['Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Stephen Hawking'], correctIndex: 1, category: 'Ciencia', difficulty: 'easy' },
  { id: 'xq-24', question: '¿Cuál es el metal líquido a temperatura ambiente?', answers: ['Plomo', 'Mercurio', 'Estaño', 'Aluminio'], correctIndex: 1, category: 'Ciencia', difficulty: 'hard' },
  { id: 'xq-25', question: '¿Qué director español dirigió la película \'Todo sobre mi madre\'?', answers: ['Alejandro Amenábar', 'Pedro Almodóvar', 'Luis Buñuel', 'Carlos Saura'], correctIndex: 1, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'xq-26', question: '¿En qué película aparece el personaje de Darth Vader?', answers: ['Star Trek', 'La guerra de las galaxias', 'Blade Runner', 'Matrix'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'xq-27', question: '¿Cuál es el nombre de la serie española de atracos protagonizada por \'El Profesor\'?', answers: ['Vis a vis', 'La casa de papel', 'Élite', 'Las chicas del cable'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'xq-28', question: '¿Qué actriz interpreta a Hermione Granger en las películas de Harry Potter?', answers: ['Emma Stone', 'Emma Watson', 'Keira Knightley', 'Natalie Portman'], correctIndex: 1, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'xq-29', question: '¿Quién dirigió la película \'Titanic\' de 1997?', answers: ['Steven Spielberg', 'James Cameron', 'Ridley Scott', 'Martin Scorsese'], correctIndex: 1, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'xq-30', question: '¿En qué ciudad ficticia transcurre la serie \'Los Simpson\'?', answers: ['Quahog', 'Springfield', 'Gotham', 'South Park'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'xq-31', question: '¿Qué grupo británico compuso la canción \'Hey Jude\'?', answers: ['The Rolling Stones', 'The Beatles', 'Queen', 'Pink Floyd'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'xq-32', question: '¿Cuántas cuerdas tiene una guitarra española tradicional?', answers: ['Cuatro', 'Cinco', 'Seis', 'Siete'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'xq-33', question: '¿Qué cantante es conocida como la \'Reina del Pop\'?', answers: ['Whitney Houston', 'Madonna', 'Celine Dion', 'Tina Turner'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'xq-34', question: '¿De qué país es originario el estilo musical y de baile llamado flamenco?', answers: ['Portugal', 'Italia', 'España', 'Argentina'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'xq-35', question: '¿Qué compositor alemán, ya sordo, escribió la famosa \'Novena Sinfonía\'?', answers: ['Mozart', 'Bach', 'Beethoven', 'Wagner'], correctIndex: 2, category: 'Musica', difficulty: 'medium' },
  { id: 'xq-36', question: '¿Qué grupo sueco interpretó el éxito \'Dancing Queen\'?', answers: ['ABBA', 'Roxette', 'Ace of Base', 'Europe'], correctIndex: 0, category: 'Musica', difficulty: 'medium' },
  { id: 'xq-37', question: '¿Cuántos colores tiene el arcoíris según la representación clásica?', answers: ['Cinco', 'Seis', 'Siete', 'Ocho'], correctIndex: 2, category: 'Cultura general', difficulty: 'easy' },
  { id: 'xq-38', question: '¿Quién escribió \'Don Quijote de la Mancha\'?', answers: ['Lope de Vega', 'Miguel de Cervantes', 'Francisco de Quevedo', 'Garcilaso de la Vega'], correctIndex: 1, category: 'Cultura general', difficulty: 'easy' },
  { id: 'xq-39', question: '¿Cuál es el idioma más hablado del mundo como lengua materna?', answers: ['Inglés', 'Español', 'Chino mandarín', 'Hindi'], correctIndex: 2, category: 'Cultura general', difficulty: 'medium' },
  { id: 'xq-40', question: '¿En qué ciudad se encuentra la Torre Eiffel?', answers: ['Roma', 'Londres', 'París', 'Bruselas'], correctIndex: 2, category: 'Cultura general', difficulty: 'easy' },
  { id: 'xq-41', question: '¿Cuántos días tiene un año bisiesto?', answers: ['364', '365', '366', '367'], correctIndex: 2, category: 'Cultura general', difficulty: 'easy' },
  { id: 'xq-42', question: '¿Qué moneda se utiliza en Japón?', answers: ['El won', 'El yen', 'El yuan', 'El baht'], correctIndex: 1, category: 'Cultura general', difficulty: 'medium' },
  { id: 'xq-43', question: '¿Cuál es el animal terrestre más grande del mundo?', answers: ['El rinoceronte', 'El elefante africano', 'El hipopótamo', 'La jirafa'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'xq-44', question: '¿Cuál es el mamífero más grande del planeta?', answers: ['El elefante', 'El tiburón ballena', 'La ballena azul', 'El cachalote'], correctIndex: 2, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'xq-45', question: '¿Qué insecto produce la miel?', answers: ['La avispa', 'La abeja', 'El abejorro', 'La hormiga'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'xq-46', question: '¿Cuál es el ave más rápida del mundo en picado?', answers: ['El águila real', 'El halcón peregrino', 'El avestruz', 'El cóndor'], correctIndex: 1, category: 'Naturaleza', difficulty: 'hard' },
  { id: 'xq-47', question: '¿Cuántas patas tiene una araña?', answers: ['Seis', 'Ocho', 'Diez', 'Doce'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'xq-48', question: '¿Qué árbol produce las bellotas?', answers: ['El pino', 'El roble', 'El abedul', 'El olmo'], correctIndex: 1, category: 'Naturaleza', difficulty: 'medium' },
  { id: 'xq-49', question: '¿Qué empresa creó el sistema operativo Windows?', answers: ['Apple', 'Microsoft', 'Google', 'IBM'], correctIndex: 1, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'xq-50', question: '¿Quién cofundó Apple junto a Steve Wozniak?', answers: ['Bill Gates', 'Steve Jobs', 'Mark Zuckerberg', 'Jeff Bezos'], correctIndex: 1, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'xq-51', question: '¿Qué significan las siglas \'www\' en una dirección de Internet?', answers: ['World Web Wide', 'World Wide Web', 'Wide World Web', 'Web World Wide'], correctIndex: 1, category: 'Tecnologia', difficulty: 'medium' },
  { id: 'xq-52', question: '¿Cuál es el ingrediente principal del guacamole?', answers: ['El tomate', 'El aguacate', 'El pepino', 'El calabacín'], correctIndex: 1, category: 'Comida', difficulty: 'easy' },
  { id: 'xq-53', question: '¿De qué región española es típica la paella?', answers: ['Andalucía', 'Cataluña', 'Comunidad Valenciana', 'País Vasco'], correctIndex: 2, category: 'Comida', difficulty: 'medium' },
  { id: 'xq-54', question: '¿Cuál es el ingrediente base del tradicional gazpacho andaluz?', answers: ['La patata', 'El tomate', 'El garbanzo', 'La zanahoria'], correctIndex: 1, category: 'Comida', difficulty: 'easy' },
  { id: 'yq-1', question: '¿Cuál es la capital de Portugal?', answers: ['Oporto', 'Lisboa', 'Coímbra', 'Braga'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'yq-2', question: '¿En qué continente se encuentra el desierto del Kalahari?', answers: ['Asia', 'Sudamérica', 'África', 'Oceanía'], correctIndex: 2, category: 'Geografia', difficulty: 'medium' },
  { id: 'yq-3', question: '¿Cuál es la capital de Marruecos?', answers: ['Casablanca', 'Rabat', 'Marrakech', 'Fez'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'yq-4', question: '¿Qué cordillera separa Europa de Asia?', answers: ['Los Alpes', 'Los Cárpatos', 'Los Urales', 'El Cáucaso'], correctIndex: 2, category: 'Geografia', difficulty: 'medium' },
  { id: 'yq-5', question: '¿Cuál es el país más septentrional del mundo continental?', answers: ['Islandia', 'Noruega', 'Canadá', 'Rusia'], correctIndex: 1, category: 'Geografia', difficulty: 'hard' },
  { id: 'yq-6', question: '¿En qué país se encuentra la ciudad de Marrakech?', answers: ['Túnez', 'Egipto', 'Marruecos', 'Argelia'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'yq-7', question: '¿Cuál es el océano más grande del mundo?', answers: ['Atlántico', 'Índico', 'Ártico', 'Pacífico'], correctIndex: 3, category: 'Geografia', difficulty: 'easy' },
  { id: 'yq-8', question: '¿Qué país tiene como capital a Canberra?', answers: ['Nueva Zelanda', 'Australia', 'Sudáfrica', 'Canadá'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'yq-9', question: '¿Cuál es el lago de agua dulce más grande del mundo por superficie?', answers: ['Lago Victoria', 'Lago Superior', 'Lago Baikal', 'Mar Caspio'], correctIndex: 1, category: 'Geografia', difficulty: 'hard' },
  { id: 'yq-10', question: '¿En qué país europeo se encuentra la región de la Toscana?', answers: ['Francia', 'España', 'Italia', 'Grecia'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'yq-11', question: '¿Cuál es la capital de Egipto?', answers: ['Alejandría', 'El Cairo', 'Luxor', 'Asuán'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'yq-12', question: '¿Quién fue el primer presidente de los Estados Unidos?', answers: ['Thomas Jefferson', 'Abraham Lincoln', 'George Washington', 'John Adams'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'yq-13', question: '¿En qué año llegó el ser humano a la Luna por primera vez?', answers: ['1965', '1969', '1972', '1958'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'yq-14', question: '¿Qué reina egipcia tuvo relación con Julio César y Marco Antonio?', answers: ['Nefertiti', 'Hatshepsut', 'Cleopatra', 'Nefertari'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'yq-15', question: '¿Qué revolución comenzó en Francia en 1789?', answers: ['La Revolución Industrial', 'La Revolución Francesa', 'La Revolución Rusa', 'La Comuna de París'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'yq-16', question: '¿Qué general cartaginés cruzó los Alpes con elefantes?', answers: ['Aníbal', 'Escipión', 'Asdrúbal', 'Amílcar'], correctIndex: 0, category: 'Historia', difficulty: 'medium' },
  { id: 'yq-17', question: '¿En qué año cayó el Imperio Romano de Occidente?', answers: ['476 d.C.', '1453 d.C.', '27 a.C.', '800 d.C.'], correctIndex: 0, category: 'Historia', difficulty: 'hard' },
  { id: 'yq-18', question: '¿Qué documento firmaron los barones ingleses con el rey Juan en 1215?', answers: ['La Declaración de Derechos', 'La Carta Magna', 'El Acta de Unión', 'La Constitución'], correctIndex: 1, category: 'Historia', difficulty: 'medium' },
  { id: 'yq-19', question: '¿Qué imperio fue gobernado por Solimán el Magnífico?', answers: ['El Imperio Persa', 'El Imperio Mogol', 'El Imperio Otomano', 'El Imperio Bizantino'], correctIndex: 2, category: 'Historia', difficulty: 'hard' },
  { id: 'yq-20', question: '¿Quién lideró el ejército francés durante las guerras napoleónicas y fue derrotado en Waterloo?', answers: ['Luis XVI', 'Napoleón Bonaparte', 'Robespierre', 'Carlomagno'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'yq-21', question: '¿En qué ciudad se firmó el tratado que puso fin a la Primera Guerra Mundial en 1919?', answers: ['Berlín', 'Viena', 'Versalles', 'Londres'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  { id: 'yq-22', question: '¿Qué civilización antigua inventó el concepto del cero como número?', answers: ['Los egipcios', 'Los griegos', 'Los mayas', 'Los romanos'], correctIndex: 2, category: 'Historia', difficulty: 'hard' },
  { id: 'yq-23', question: '¿Cada cuántos años se celebra normalmente el Mundial de Fútbol?', answers: ['Cada 2 años', 'Cada 3 años', 'Cada 4 años', 'Cada 5 años'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'yq-24', question: '¿Con qué deporte se asocia el Tour de Francia?', answers: ['Atletismo', 'Ciclismo', 'Automovilismo', 'Natación'], correctIndex: 1, category: 'Deporte', difficulty: 'easy' },
  { id: 'yq-25', question: '¿En qué deporte destacó el jugador Michael Jordan?', answers: ['Béisbol', 'Fútbol americano', 'Baloncesto', 'Tenis'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'yq-26', question: '¿Cuántos jugadores hay en un equipo de waterpolo dentro del agua?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Deporte', difficulty: 'hard' },
  { id: 'yq-27', question: '¿En qué país se originó el deporte del judo?', answers: ['China', 'Corea', 'Japón', 'Tailandia'], correctIndex: 2, category: 'Deporte', difficulty: 'medium' },
  { id: 'yq-28', question: '¿Qué piloto tiene siete títulos mundiales de Fórmula 1 y compitió con Ferrari y Mercedes?', answers: ['Ayrton Senna', 'Michael Schumacher', 'Fernando Alonso', 'Sebastian Vettel'], correctIndex: 1, category: 'Deporte', difficulty: 'medium' },
  { id: 'yq-29', question: '¿En qué deporte se utiliza un implemento llamado \'stick\'?', answers: ['Voleibol', 'Hockey', 'Rugby', 'Balonmano'], correctIndex: 1, category: 'Deporte', difficulty: 'medium' },
  { id: 'yq-30', question: '¿Cuántos hoyos tiene un campo de golf reglamentario?', answers: ['9', '12', '18', '24'], correctIndex: 2, category: 'Deporte', difficulty: 'easy' },
  { id: 'yq-31', question: '¿Qué selección nacional ha ganado más Mundiales de Fútbol masculino?', answers: ['Alemania', 'Italia', 'Argentina', 'Brasil'], correctIndex: 3, category: 'Deporte', difficulty: 'medium' },
  { id: 'yq-32', question: '¿En qué ciudad nacieron los Juegos Olímpicos de la Antigüedad?', answers: ['Atenas', 'Esparta', 'Olimpia', 'Corinto'], correctIndex: 2, category: 'Deporte', difficulty: 'hard' },
  { id: 'yq-33', question: '¿Qué prueba de atletismo combina diez disciplinas para los hombres?', answers: ['Pentatlón', 'Heptatlón', 'Decatlón', 'Triatlón'], correctIndex: 2, category: 'Deporte', difficulty: 'medium' },
  { id: 'yq-34', question: '¿Cuál es el planeta conocido como el \'planeta rojo\'?', answers: ['Júpiter', 'Venus', 'Marte', 'Saturno'], correctIndex: 2, category: 'Ciencia', difficulty: 'easy' },
  { id: 'yq-35', question: '¿Qué gas necesitan los seres humanos para respirar?', answers: ['Nitrógeno', 'Oxígeno', 'Hidrógeno', 'Helio'], correctIndex: 1, category: 'Ciencia', difficulty: 'easy' },
  { id: 'yq-36', question: '¿Cuántos cromosomas tiene normalmente una célula humana?', answers: ['23', '46', '48', '21'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'yq-37', question: '¿Qué científica recibió dos premios Nobel, en Física y en Química?', answers: ['Rosalind Franklin', 'Marie Curie', 'Ada Lovelace', 'Lise Meitner'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'yq-38', question: '¿Cuál es el símbolo químico del hierro?', answers: ['Hi', 'Fe', 'Ir', 'Hr'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'yq-39', question: '¿Qué fuerza nos mantiene pegados a la superficie de la Tierra?', answers: ['La fricción', 'El magnetismo', 'La gravedad', 'La electricidad'], correctIndex: 2, category: 'Ciencia', difficulty: 'easy' },
  { id: 'yq-40', question: '¿A qué temperatura hierve el agua a nivel del mar en grados Celsius?', answers: ['90', '100', '120', '80'], correctIndex: 1, category: 'Ciencia', difficulty: 'easy' },
  { id: 'yq-41', question: '¿Qué tipo de roca se forma a partir de la lava enfriada?', answers: ['Sedimentaria', 'Metamórfica', 'Ígnea', 'Caliza'], correctIndex: 2, category: 'Ciencia', difficulty: 'hard' },
  { id: 'yq-42', question: '¿Cuál es la partícula subatómica con carga negativa?', answers: ['Protón', 'Neutrón', 'Electrón', 'Fotón'], correctIndex: 2, category: 'Ciencia', difficulty: 'medium' },
  { id: 'yq-43', question: '¿Qué científico propuso las leyes del movimiento y la gravitación universal?', answers: ['Galileo Galilei', 'Isaac Newton', 'Nikola Tesla', 'Charles Darwin'], correctIndex: 1, category: 'Ciencia', difficulty: 'easy' },
  { id: 'yq-44', question: '¿Qué parte de la célula contiene el material genético?', answers: ['La mitocondria', 'El núcleo', 'El ribosoma', 'La membrana'], correctIndex: 1, category: 'Ciencia', difficulty: 'medium' },
  { id: 'yq-45', question: '¿Qué actor protagoniza la saga de \'Indiana Jones\'?', answers: ['Tom Hanks', 'Harrison Ford', 'Mel Gibson', 'Kevin Costner'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'yq-46', question: '¿En qué película animada de Disney aparece el león Simba?', answers: ['Madagascar', 'El rey león', 'Bambi', 'Tarzán'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'yq-47', question: '¿Quién dirigió la película \'Pulp Fiction\'?', answers: ['Martin Scorsese', 'Quentin Tarantino', 'Steven Spielberg', 'Christopher Nolan'], correctIndex: 1, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'yq-48', question: '¿Cómo se llama el mayordomo de Batman?', answers: ['Jarvis', 'Alfred', 'Lucius', 'Robin'], correctIndex: 1, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'yq-49', question: '¿En qué saga de películas aparecen los hobbits?', answers: ['Las crónicas de Narnia', 'Harry Potter', 'El señor de los anillos', 'Juego de tronos'], correctIndex: 2, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'yq-50', question: '¿Qué actriz interpreta a Katniss Everdeen en \'Los juegos del hambre\'?', answers: ['Emma Stone', 'Jennifer Lawrence', 'Scarlett Johansson', 'Anne Hathaway'], correctIndex: 1, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'yq-51', question: '¿Qué película de 1994 narra la vida de un hombre interpretado por Tom Hanks que dice \'la vida es como una caja de bombones\'?', answers: ['Náufrago', 'Forrest Gump', 'El indomable Will Hunting', 'Philadelphia'], correctIndex: 1, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'yq-52', question: '¿En qué serie de televisión aparece el químico Walter White?', answers: ['The Wire', 'Breaking Bad', 'Mad Men', 'Dexter'], correctIndex: 1, category: 'Cine y TV', difficulty: 'easy' },
  { id: 'yq-53', question: '¿Quién dirigió la trilogía original de \'La guerra de las galaxias\' en su primera entrega?', answers: ['George Lucas', 'Ridley Scott', 'James Cameron', 'Robert Zemeckis'], correctIndex: 0, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'yq-54', question: '¿Qué actor interpreta al Capitán Jack Sparrow además de aparecer en \'Eduardo Manostijeras\'?', answers: ['Brad Pitt', 'Johnny Depp', 'Leonardo DiCaprio', 'Christian Bale'], correctIndex: 1, category: 'Cine y TV', difficulty: 'medium' },
  { id: 'yq-55', question: '¿En qué película de Stanley Kubrick aparece la computadora HAL 9000?', answers: ['La naranja mecánica', '2001: Una odisea del espacio', 'El resplandor', 'Blade Runner'], correctIndex: 1, category: 'Cine y TV', difficulty: 'hard' },
  { id: 'yq-56', question: '¿Cuántas teclas blancas y negras juntas tiene un piano estándar de cola?', answers: ['76', '88', '61', '100'], correctIndex: 1, category: 'Musica', difficulty: 'medium' },
  { id: 'yq-57', question: '¿Qué cantante británico fue apodado el \'Duque Blanco\' y creó el personaje Ziggy Stardust?', answers: ['Elton John', 'David Bowie', 'Freddie Mercury', 'Mick Jagger'], correctIndex: 1, category: 'Musica', difficulty: 'hard' },
  { id: 'yq-58', question: '¿Qué instrumento toca principalmente un violonchelista?', answers: ['La flauta', 'El violonchelo', 'La trompeta', 'El arpa'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'yq-59', question: '¿Cuántas notas musicales básicas hay en la escala (do, re, mi...)?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'yq-60', question: '¿Qué compositor austriaco, niño prodigio, compuso \'La flauta mágica\'?', answers: ['Johann Sebastian Bach', 'Wolfgang Amadeus Mozart', 'Franz Schubert', 'Antonio Vivaldi'], correctIndex: 1, category: 'Musica', difficulty: 'medium' },
  { id: 'yq-61', question: '¿De qué país es originario el tango?', answers: ['México', 'Brasil', 'Argentina', 'Cuba'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'yq-62', question: '¿Qué banda estadounidense de rock grabó el álbum \'Nevermind\' con la canción \'Smells Like Teen Spirit\'?', answers: ['Pearl Jam', 'Nirvana', 'Soundgarden', 'Green Day'], correctIndex: 1, category: 'Musica', difficulty: 'medium' },
  { id: 'yq-63', question: '¿Qué instrumento de percusión consiste en dos platos metálicos que se golpean entre sí?', answers: ['El timbal', 'Los platillos', 'El bombo', 'El xilófono'], correctIndex: 1, category: 'Musica', difficulty: 'medium' },
  { id: 'yq-64', question: '¿Qué compositor italiano del Barroco escribió \'Las cuatro estaciones\'?', answers: ['Antonio Vivaldi', 'Giuseppe Verdi', 'Giacomo Puccini', 'Domenico Scarlatti'], correctIndex: 0, category: 'Musica', difficulty: 'medium' },
  { id: 'yq-65', question: '¿Cómo se llama el cantante principal de la banda U2?', answers: ['Sting', 'Bono', 'Chris Martin', 'Liam Gallagher'], correctIndex: 1, category: 'Musica', difficulty: 'medium' },
  { id: 'yq-66', question: '¿Qué baile y música tradicional está muy ligado a Andalucía y usa palmas y taconeo?', answers: ['La jota', 'El flamenco', 'La sardana', 'La muñeira'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'yq-67', question: '¿Cuántos lados tiene un hexágono?', answers: ['5', '6', '7', '8'], correctIndex: 1, category: 'Cultura general', difficulty: 'easy' },
  { id: 'yq-68', question: '¿Cuál es la moneda oficial del Reino Unido?', answers: ['El euro', 'La libra esterlina', 'El dólar', 'El franco'], correctIndex: 1, category: 'Cultura general', difficulty: 'easy' },
  { id: 'yq-69', question: '¿Cuántos colores tiene la bandera de España?', answers: ['Dos', 'Tres', 'Cuatro', 'Cinco'], correctIndex: 0, category: 'Cultura general', difficulty: 'medium' },
  { id: 'yq-70', question: '¿Cuál es el número romano que representa el 50?', answers: ['X', 'L', 'C', 'D'], correctIndex: 1, category: 'Cultura general', difficulty: 'medium' },
  { id: 'yq-71', question: '¿En qué idioma están escritas las obras originales de Shakespeare?', answers: ['Latín', 'Francés', 'Inglés', 'Alemán'], correctIndex: 2, category: 'Cultura general', difficulty: 'easy' },
  { id: 'yq-72', question: '¿Cuál es el resultado de multiplicar 12 por 12?', answers: ['124', '144', '132', '154'], correctIndex: 1, category: 'Cultura general', difficulty: 'easy' },
  { id: 'yq-73', question: '¿Qué planeta da nombre al día de la semana \'martes\' en su origen?', answers: ['Marte', 'Mercurio', 'Venus', 'Júpiter'], correctIndex: 0, category: 'Cultura general', difficulty: 'medium' },
  { id: 'yq-74', question: '¿Cuántos minutos tiene una hora y media?', answers: ['75', '80', '90', '100'], correctIndex: 2, category: 'Cultura general', difficulty: 'easy' },
  { id: 'yq-75', question: '¿Qué organización tiene su sede principal en Nueva York y agrupa a casi todos los países del mundo?', answers: ['La OTAN', 'La ONU', 'La UNESCO', 'La OMS'], correctIndex: 1, category: 'Cultura general', difficulty: 'medium' },
  { id: 'yq-76', question: '¿Cuál es la lengua oficial de Brasil?', answers: ['Español', 'Portugués', 'Francés', 'Inglés'], correctIndex: 1, category: 'Cultura general', difficulty: 'easy' },
  { id: 'yq-77', question: '¿Quién escribió la obra de teatro \'Romeo y Julieta\'?', answers: ['Molière', 'William Shakespeare', 'Lope de Vega', 'Oscar Wilde'], correctIndex: 1, category: 'Cultura general', difficulty: 'medium' },
  { id: 'yq-78', question: '¿Qué animal es el rey de la selva según el dicho popular?', answers: ['El tigre', 'El león', 'El elefante', 'El leopardo'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'yq-79', question: '¿Cuál es el felino terrestre más rápido del mundo?', answers: ['El leopardo', 'El guepardo', 'El tigre', 'El puma'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'yq-80', question: '¿Cómo se llama el proceso por el que una oruga se transforma en mariposa?', answers: ['Mutación', 'Metamorfosis', 'Hibernación', 'Regeneración'], correctIndex: 1, category: 'Naturaleza', difficulty: 'medium' },
  { id: 'yq-81', question: '¿Qué animal es el mamífero terrestre más alto del mundo?', answers: ['El elefante', 'La jirafa', 'El rinoceronte', 'El camello'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'yq-82', question: '¿De qué se alimentan principalmente los osos panda?', answers: ['Peces', 'Bambú', 'Insectos', 'Carne'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'yq-83', question: '¿Cuál es el grupo de animales al que pertenecen las ranas y los sapos?', answers: ['Reptiles', 'Anfibios', 'Peces', 'Mamíferos'], correctIndex: 1, category: 'Naturaleza', difficulty: 'medium' },
  { id: 'yq-84', question: '¿Qué órgano usan los peces para respirar bajo el agua?', answers: ['Los pulmones', 'Las branquias', 'La piel', 'Las aletas'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'yq-85', question: '¿Cuál es el ave más grande del mundo, que no puede volar?', answers: ['El cóndor', 'El avestruz', 'El emú', 'El pingüino emperador'], correctIndex: 1, category: 'Naturaleza', difficulty: 'medium' },
  { id: 'yq-86', question: '¿Cuántos corazones tiene un pulpo?', answers: ['Uno', 'Dos', 'Tres', 'Cuatro'], correctIndex: 2, category: 'Naturaleza', difficulty: 'hard' },
  { id: 'yq-87', question: '¿Qué tipo de animal es el delfín?', answers: ['Un pez', 'Un mamífero', 'Un anfibio', 'Un reptil'], correctIndex: 1, category: 'Naturaleza', difficulty: 'easy' },
  { id: 'yq-88', question: '¿Qué planta carnívora atrapa insectos cerrando sus hojas como una trampa?', answers: ['El cactus', 'La venus atrapamoscas', 'El nenúfar', 'El girasol'], correctIndex: 1, category: 'Naturaleza', difficulty: 'hard' },
  { id: 'yq-89', question: '¿Qué significa la sigla \'PC\' en informática?', answers: ['Programa Central', 'Ordenador Personal', 'Periférico de Conexión', 'Procesador Compacto'], correctIndex: 1, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'yq-90', question: '¿Qué empresa creó el motor de búsqueda más usado del mundo?', answers: ['Microsoft', 'Apple', 'Google', 'Yahoo'], correctIndex: 2, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'yq-91', question: '¿Qué red social fue fundada por Mark Zuckerberg?', answers: ['Twitter', 'Facebook', 'Instagram', 'LinkedIn'], correctIndex: 1, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'yq-92', question: '¿Qué significa la sigla \'CPU\' en un ordenador?', answers: ['Unidad Central de Procesamiento', 'Control Principal Universal', 'Conexión Para USB', 'Computadora Personal Única'], correctIndex: 0, category: 'Tecnologia', difficulty: 'medium' },
  { id: 'yq-93', question: '¿Qué tecla se suele pulsar junto con otra para copiar texto en Windows?', answers: ['Alt', 'Tab', 'Ctrl', 'Shift'], correctIndex: 2, category: 'Tecnologia', difficulty: 'medium' },
  { id: 'yq-94', question: '¿Quién es considerado cofundador de Microsoft junto con Paul Allen?', answers: ['Steve Jobs', 'Bill Gates', 'Larry Page', 'Elon Musk'], correctIndex: 1, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'yq-95', question: '¿Qué unidad mide la cantidad de información digital y equivale a 8 bits?', answers: ['El hercio', 'El byte', 'El píxel', 'El vatio'], correctIndex: 1, category: 'Tecnologia', difficulty: 'medium' },
  { id: 'yq-96', question: '¿Qué lenguaje de programación tiene un nombre relacionado con una serpiente?', answers: ['Java', 'Python', 'Ruby', 'Cobra'], correctIndex: 1, category: 'Tecnologia', difficulty: 'medium' },
  { id: 'yq-97', question: '¿Qué dispositivo permite conectar varios ordenadores a una red wifi en casa?', answers: ['El monitor', 'El router', 'La impresora', 'El escáner'], correctIndex: 1, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'yq-98', question: '¿Qué empresa desarrolla el sistema operativo macOS?', answers: ['Microsoft', 'Apple', 'Google', 'IBM'], correctIndex: 1, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'yq-99', question: '¿De qué planta se obtiene el chocolate?', answers: ['Del café', 'Del cacao', 'De la caña de azúcar', 'De la vainilla'], correctIndex: 1, category: 'Comida', difficulty: 'easy' },
  { id: 'yq-100', question: '¿Cuál es el ingrediente principal del hummus?', answers: ['Lentejas', 'Garbanzos', 'Judías', 'Soja'], correctIndex: 1, category: 'Comida', difficulty: 'medium' },
  { id: 'yq-101', question: '¿De qué país es originario el plato llamado \'sushi\'?', answers: ['China', 'Tailandia', 'Japón', 'Corea'], correctIndex: 2, category: 'Comida', difficulty: 'easy' },
];

let _usedIndices: Set<number> = new Set();
export function getRandomQuestion(): QuizQuestion { if (_usedIndices.size >= QUIZ_QUESTIONS_ES.length) { _usedIndices.clear(); } let idx: number; do { idx = Math.floor(Math.random() * QUIZ_QUESTIONS_ES.length); } while (_usedIndices.has(idx)); _usedIndices.add(idx); return QUIZ_QUESTIONS_ES[idx]; }
export function resetQuestions(): void { _usedIndices.clear(); }
