export interface QuizQuestion { id: string; question: string; answers: string[]; correctIndex: number; category: string; difficulty: 'easy' | 'medium' | 'hard'; }
export const QUIZ_QUESTIONS_TR: QuizQuestion[] = [
  { id: 'geo-1', question: 'Avustralya\'nin baskenti neresidir?', answers: ['Sidney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, category: 'Cografya', difficulty: 'medium' },
  { id: 'geo-2', question: 'Dunyanin en uzun nehri hangisidir?', answers: ['Amazon', 'Nil', 'Yangtze', 'Mississippi'], correctIndex: 1, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-3', question: 'Machu Picchu hangi ulkededir?', answers: ['Bolivya', 'Ekvador', 'Peru', 'Kolombiya'], correctIndex: 2, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-4', question: 'Turkiye kac ilden olusur?', answers: ['79', '80', '81', '82'], correctIndex: 2, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-5', question: 'Dunyanin en kucuk ulkesi hangisidir?', answers: ['Monako', 'Vatikan', 'San Marino', 'Lihtenstayn'], correctIndex: 1, category: 'Cografya', difficulty: 'medium' },
  { id: 'geo-6', question: 'Hangi ulke cizme seklindedir?', answers: ['Ispanya', 'Yunanistan', 'Italya', 'Portekiz'], correctIndex: 2, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-7', question: 'Dunyanin en yuksek dagi hangisidir?', answers: ['K2', 'Kangchenjunga', 'Everest', 'Lhotse'], correctIndex: 2, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-8', question: 'Dunyanin en buyuk ulkesi hangisidir?', answers: ['Kanada', 'Cin', 'ABD', 'Rusya'], correctIndex: 3, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-9', question: 'Istanbul hangi bogazda yer alir?', answers: ['Canakkale', 'Istanbul Bogazi', 'Cebelitarik', 'Sueys'], correctIndex: 1, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-10', question: 'Turkiye\'nin en uzun nehri hangisidir?', answers: ['Firat', 'Kizilirmak', 'Dicle', 'Sakarya'], correctIndex: 1, category: 'Cografya', difficulty: 'medium' },
  { id: 'his-1', question: 'Berlin Duvari hangi yil yikildi?', answers: ['1987', '1988', '1989', '1990'], correctIndex: 2, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-2', question: 'Ay\'a ilk ayak basan kisidir?', answers: ['Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'John Glenn'], correctIndex: 1, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-3', question: 'Giza piramitlerini hangi medeniyet yapti?', answers: ['Romalilar', 'Yunanlılar', 'Misirlilar', 'Persler'], correctIndex: 2, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-4', question: 'Turkiye Cumhuriyeti hangi yil kuruldu?', answers: ['1920', '1921', '1922', '1923'], correctIndex: 3, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-5', question: 'Istanbul\'un fethi hangi yildadir?', answers: ['1451', '1453', '1455', '1461'], correctIndex: 1, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-6', question: 'Mona Lisa\'yi kim cizdi?', answers: ['Michelangelo', 'Rafael', 'Leonardo da Vinci', 'Rembrandt'], correctIndex: 2, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-7', question: 'Kolomb Amerika\'yi hangi yil kesfetti?', answers: ['1482', '1492', '1502', '1512'], correctIndex: 1, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-8', question: 'Titanic hangi yil batti?', answers: ['1910', '1912', '1914', '1916'], correctIndex: 1, category: 'Tarih', difficulty: 'medium' },
  { id: 'spo-1', question: 'Bir futbol takiminda sahada kac oyuncu vardir?', answers: ['9', '10', '11', '12'], correctIndex: 2, category: 'Spor', difficulty: 'easy' },
  { id: 'spo-2', question: 'Olimpiyat sembolunde kac halka vardir?', answers: ['3', '4', '5', '6'], correctIndex: 2, category: 'Spor', difficulty: 'easy' },
  { id: 'spo-3', question: '100 metre rekor kime aittir?', answers: ['Carl Lewis', 'Usain Bolt', 'Tyson Gay', 'Yohan Blake'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'spo-4', question: 'Maraton kac kilometredir (yuvarlanmis)?', answers: ['40 km', '42 km', '44 km', '46 km'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'spo-5', question: 'En cok Sampiyonlar Ligi kupasi olan kulup hangisidir?', answers: ['FC Barcelona', 'AC Milan', 'Real Madrid', 'Bayern Munih'], correctIndex: 2, category: 'Spor', difficulty: 'medium' },
  { id: 'spo-6', question: 'Sumo gulesi hangi ulkeye aittir?', answers: ['Cin', 'Kore', 'Japonya', 'Tayland'], correctIndex: 2, category: 'Spor', difficulty: 'easy' },
  { id: 'spo-7', question: 'Yagli gures hangi ulkenin geleneksel sporudur?', answers: ['Iran', 'Turkiye', 'Mogolistan', 'Hindistan'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'spo-8', question: 'Hangi spor yuzme, bisiklet ve kosuyu birlestirir?', answers: ['Biatlon', 'Triatlon', 'Pentatlon', 'Dekatlon'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'wis-1', question: 'Suyun kimyasal formulu nedir?', answers: ['H2O', 'CO2', 'O2', 'NaCl'], correctIndex: 0, category: 'Bilim', difficulty: 'easy' },
  { id: 'wis-2', question: 'Gunes sistemimizde kac gezegen var?', answers: ['7', '8', '9', '10'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'wis-3', question: 'Hangi organ kani vucuda pompalar?', answers: ['Akciger', 'Karaciger', 'Kalp', 'Bobrek'], correctIndex: 2, category: 'Bilim', difficulty: 'easy' },
  { id: 'wis-4', question: 'En sert dogal madde nedir?', answers: ['Celik', 'Elmas', 'Kuvars', 'Safir'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'wis-5', question: 'Gorelilik teorisini kim gelistirdi?', answers: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Max Planck'], correctIndex: 2, category: 'Bilim', difficulty: 'easy' },
  { id: 'wis-6', question: 'Saf suyun pH degeri kactir?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Bilim', difficulty: 'medium' },
  { id: 'wis-7', question: 'Bir yetiskin insanda yaklasik kac kemik vardir?', answers: ['106', '156', '206', '256'], correctIndex: 2, category: 'Bilim', difficulty: 'medium' },
  { id: 'wis-8', question: 'Aziz Sancar hangi alanda Nobel odulu aldi?', answers: ['Fizik', 'Kimya', 'Tip', 'Edebiyat'], correctIndex: 1, category: 'Bilim', difficulty: 'medium' },
  { id: 'fil-1', question: '"Karayip Korsanlari"nda Jack Sparrow\'u kim canlandirir?', answers: ['Orlando Bloom', 'Johnny Depp', 'Brad Pitt', 'Leonardo DiCaprio'], correctIndex: 1, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'fil-2', question: 'Kac Harry Potter filmi vardir?', answers: ['6', '7', '8', '9'], correctIndex: 2, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'fil-3', question: 'Disney filmindeki Buz Kralicesi\'nin adi nedir?', answers: ['Anna', 'Elsa', 'Rapunzel', 'Merida'], correctIndex: 1, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'fil-4', question: 'MCU\'da Iron Man\'i kim canlandirir?', answers: ['Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr.', 'Mark Ruffalo'], correctIndex: 2, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'fil-5', question: 'Hangi Turk dizisi dunyada buyuk ilgi gordu?', answers: ['Kurtlar Vadisi', 'Muhtesem Yuzyil', 'Cukur', 'Hepsi'], correctIndex: 1, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'mus-1', question: '"Bohemian Rhapsody"yi hangi grup soyledi?', answers: ['The Beatles', 'Led Zeppelin', 'Queen', 'Pink Floyd'], correctIndex: 2, category: 'Muzik', difficulty: 'easy' },
  { id: 'mus-2', question: '"Pop\'un Krali" kimdir?', answers: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Freddie Mercury'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'mus-3', question: 'Hangi calginin 88 tusu vardir?', answers: ['Org', 'Akordeon', 'Piyano', 'Klavye'], correctIndex: 2, category: 'Muzik', difficulty: 'easy' },
  { id: 'mus-4', question: '"Simarik" sarkisiyla tanidiginiz Turk pop stari kimdir?', answers: ['Sezen Aksu', 'Tarkan', 'Hadise', 'Ajda Pekkan'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'mus-5', question: 'Reggae muzik hangi ulkede dogdu?', answers: ['Blues', 'Jamaika', 'Kuba', 'Brezilya'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'all-1', question: 'Artik yilda kac gun vardir?', answers: ['364', '365', '366', '367'], correctIndex: 2, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'all-2', question: 'Mavi ve sariyi karistirinca hangi renk olur?', answers: ['Kirmizi', 'Yesil', 'Turuncu', 'Mor'], correctIndex: 1, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'all-3', question: 'Japonya\'nin para birimi nedir?', answers: ['Won', 'Yuan', 'Yen', 'Rupi'], correctIndex: 2, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'all-4', question: 'Cumhuriyet Bayrami hangi tarihte kutlanir?', answers: ['23 Nisan', '19 Mayis', '30 Agustos', '29 Ekim'], correctIndex: 3, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'all-5', question: 'Brezilya\'nin resmi dili nedir?', answers: ['Ispanyolca', 'Portekizce', 'Fransizca', 'Ingilizce'], correctIndex: 1, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'nat-1', question: 'Dunyadaki en buyuk hayvan hangisidir?', answers: ['Fil', 'Zurafa', 'Mavi balina', 'Beyaz kopekbaligi'], correctIndex: 2, category: 'Doga', difficulty: 'easy' },
  { id: 'nat-2', question: 'Bir orumcegin kac bacagi var?', answers: ['6', '8', '10', '12'], correctIndex: 1, category: 'Doga', difficulty: 'easy' },
  { id: 'nat-3', question: 'En hizli kara hayvani hangisidir?', answers: ['Aslan', 'Cita', 'Antilop', 'Tazı'], correctIndex: 1, category: 'Doga', difficulty: 'easy' },
  { id: 'nat-4', question: 'Bir ahtapotun kac kalbi var?', answers: ['1', '2', '3', '4'], correctIndex: 2, category: 'Doga', difficulty: 'hard' },
  { id: 'nat-5', question: 'Hollanda\'nin simgesi olan cicek hangisidir?', answers: ['Gul', 'Aycicegi', 'Lale', 'Zambak'], correctIndex: 2, category: 'Doga', difficulty: 'easy' },
  { id: 'tec-1', question: 'Apple\'i kim kurdu?', answers: ['Bill Gates', 'Steve Jobs', 'Elon Musk', 'Jeff Bezos'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'tec-2', question: 'Android\'i hangi sirket gelistirdi?', answers: ['Apple', 'Microsoft', 'Google', 'Samsung'], correctIndex: 2, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'tec-3', question: '"YZ" ne anlama gelir?', answers: ['Yakin Zamanda', 'Yapay Zeka', 'Yuksek Zeka', 'Yeni Zaman'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'tec-4', question: 'World Wide Web\'i kim icat etti?', answers: ['Steve Jobs', 'Bill Gates', 'Tim Berners-Lee', 'Mark Zuckerberg'], correctIndex: 2, category: 'Teknoloji', difficulty: 'medium' },
  { id: 'ess-1', question: 'Pizza hangi ulkeden gelir?', answers: ['Ispanya', 'Fransa', 'Italya', 'Yunanistan'], correctIndex: 2, category: 'Yemek', difficulty: 'easy' },
  { id: 'ess-2', question: 'Sushi hangi ulkeden gelir?', answers: ['Cin', 'Kore', 'Japonya', 'Tayland'], correctIndex: 2, category: 'Yemek', difficulty: 'easy' },
  { id: 'ess-3', question: 'Lahmacun hangi mutfaga aittir?', answers: ['Arap', 'Turk', 'Iran', 'Yunan'], correctIndex: 1, category: 'Yemek', difficulty: 'easy' },
  { id: 'ess-4', question: 'Hangi ulke en cok kahve uretir?', answers: ['Kolombiya', 'Etiyopya', 'Vietnam', 'Brezilya'], correctIndex: 3, category: 'Yemek', difficulty: 'medium' },
  { id: 'ess-5', question: 'Hangi sebze keserken gozleri yaktirir?', answers: ['Sarimsak', 'Sogan', 'Turp', 'Biber'], correctIndex: 1, category: 'Yemek', difficulty: 'easy' },
];
let _usedIndices: Set<number> = new Set();
export function getRandomQuestion(): QuizQuestion { if (_usedIndices.size >= QUIZ_QUESTIONS_TR.length) { _usedIndices.clear(); } let idx: number; do { idx = Math.floor(Math.random() * QUIZ_QUESTIONS_TR.length); } while (_usedIndices.has(idx)); _usedIndices.add(idx); return QUIZ_QUESTIONS_TR[idx]; }
export function resetQuestions(): void { _usedIndices.clear(); }
