export interface QuizQuestion { id: string; question: string; answers: string[]; correctIndex: number; category: string; difficulty: 'easy' | 'medium' | 'hard'; }
export const QUIZ_QUESTIONS_AR: QuizQuestion[] = [
  { id: 'geo-1', question: 'ما هي عاصمة أستراليا؟', answers: ['سيدني', 'ملبورن', 'كانبرا', 'بريزبن'], correctIndex: 2, category: 'جغرافيا', difficulty: 'medium' },
  { id: 'geo-2', question: 'ما هو أطول نهر في العالم؟', answers: ['الأمازون', 'النيل', 'يانغتسي', 'المسيسيبي'], correctIndex: 1, category: 'جغرافيا', difficulty: 'easy' },
  { id: 'geo-3', question: 'في أي بلد يقع ماتشو بيتشو؟', answers: ['بوليفيا', 'الإكوادور', 'بيرو', 'كولومبيا'], correctIndex: 2, category: 'جغرافيا', difficulty: 'easy' },
  { id: 'geo-4', question: 'كم عدد الدول العربية؟', answers: ['20', '21', '22', '23'], correctIndex: 2, category: 'جغرافيا', difficulty: 'easy' },
  { id: 'geo-5', question: 'ما هي أصغر دولة في العالم؟', answers: ['موناكو', 'الفاتيكان', 'سان مارينو', 'ليختنشتاين'], correctIndex: 1, category: 'جغرافيا', difficulty: 'medium' },
  { id: 'geo-6', question: 'أي بلد يشبه شكل الحذاء؟', answers: ['إسبانيا', 'اليونان', 'إيطاليا', 'البرتغال'], correctIndex: 2, category: 'جغرافيا', difficulty: 'easy' },
  { id: 'geo-7', question: 'ما هو أعلى جبل في العالم؟', answers: ['كي تو', 'كانغشنغونغا', 'جبل إيفرست', 'لوتسي'], correctIndex: 2, category: 'جغرافيا', difficulty: 'easy' },
  { id: 'geo-8', question: 'ما هي أكبر دولة في العالم مساحة؟', answers: ['كندا', 'الصين', 'أمريكا', 'روسيا'], correctIndex: 3, category: 'جغرافيا', difficulty: 'easy' },
  { id: 'geo-9', question: 'في أي قارة تقع مصر؟', answers: ['آسيا', 'أفريقيا', 'أوروبا', 'أمريكا الجنوبية'], correctIndex: 1, category: 'جغرافيا', difficulty: 'easy' },
  { id: 'geo-10', question: 'ما هو أطول نهر في مصر؟', answers: ['الأمازون', 'النيل', 'الدانوب', 'الفرات'], correctIndex: 1, category: 'جغرافيا', difficulty: 'easy' },
  { id: 'geo-11', question: 'ما هي عاصمة المغرب؟', answers: ['الدار البيضاء', 'مراكش', 'الرباط', 'فاس'], correctIndex: 2, category: 'جغرافيا', difficulty: 'medium' },
  { id: 'geo-12', question: 'أي مدينة تقع على مضيق البوسفور؟', answers: ['أثينا', 'إسطنبول', 'أنقرة', 'بوخارست'], correctIndex: 1, category: 'جغرافيا', difficulty: 'medium' },
  { id: 'his-1', question: 'في أي عام سقط جدار برلين؟', answers: ['١٩٨٧', '١٩٨٨', '١٩٨٩', '١٩٩٠'], correctIndex: 2, category: 'تاريخ', difficulty: 'easy' },
  { id: 'his-2', question: 'من كان أول إنسان على القمر؟', answers: ['باز ألدرين', 'نيل أرمسترونغ', 'يوري غاغارين', 'جون غلين'], correctIndex: 1, category: 'تاريخ', difficulty: 'easy' },
  { id: 'his-3', question: 'أي شعب بنى أهرامات الجيزة؟', answers: ['الرومان', 'الإغريق', 'المصريون', 'الفرس'], correctIndex: 2, category: 'تاريخ', difficulty: 'easy' },
  { id: 'his-4', question: 'من رسم الموناليزا؟', answers: ['مايكل أنجلو', 'رافائيل', 'ليوناردو دا فينشي', 'رمبرانت'], correctIndex: 2, category: 'تاريخ', difficulty: 'easy' },
  { id: 'his-5', question: 'في أي عام اكتشف كولومبوس أمريكا؟', answers: ['١٤٨٢', '١٤٩٢', '١٥٠٢', '١٥١٢'], correctIndex: 1, category: 'تاريخ', difficulty: 'easy' },
  { id: 'his-6', question: 'من فتح القسطنطينية عام ١٤٥٣؟', answers: ['صلاح الدين', 'محمد الفاتح', 'سليمان القانوني', 'هارون الرشيد'], correctIndex: 1, category: 'تاريخ', difficulty: 'easy' },
  { id: 'his-7', question: 'من كتب المقدمة في التاريخ؟', answers: ['ابن سينا', 'ابن خلدون', 'الخوارزمي', 'ابن رشد'], correctIndex: 1, category: 'تاريخ', difficulty: 'medium' },
  { id: 'his-8', question: 'متى غرقت سفينة تايتانيك؟', answers: ['١٩١٠', '١٩١٢', '١٩١٤', '١٩١٦'], correctIndex: 1, category: 'تاريخ', difficulty: 'medium' },
  { id: 'spo-1', question: 'كم عدد لاعبي فريق كرة القدم في الملعب؟', answers: ['٩', '١٠', '١١', '١٢'], correctIndex: 2, category: 'رياضة', difficulty: 'easy' },
  { id: 'spo-2', question: 'كم حلقة في الشعار الأولمبي؟', answers: ['٣', '٤', '٥', '٦'], correctIndex: 2, category: 'رياضة', difficulty: 'easy' },
  { id: 'spo-3', question: 'من يحمل الرقم القياسي في سباق ١٠٠ متر؟', answers: ['كارل لويس', 'أوسين بولت', 'تايسون غاي', 'يوهان بليك'], correctIndex: 1, category: 'رياضة', difficulty: 'easy' },
  { id: 'spo-4', question: 'كم كيلومتر في الماراثون (تقريبا)؟', answers: ['٤٠ كم', '٤٢ كم', '٤٤ كم', '٤٦ كم'], correctIndex: 1, category: 'رياضة', difficulty: 'easy' },
  { id: 'spo-5', question: 'أي نادي لديه أكثر ألقاب في دوري أبطال أوروبا؟', answers: ['برشلونة', 'ميلان', 'ريال مدريد', 'بايرن ميونخ'], correctIndex: 2, category: 'رياضة', difficulty: 'medium' },
  { id: 'spo-6', question: 'رياضة السومو من أي بلد؟', answers: ['الصين', 'كوريا', 'اليابان', 'تايلاند'], correctIndex: 2, category: 'رياضة', difficulty: 'easy' },
  { id: 'spo-7', question: 'أي رياضة تجمع السباحة وركوب الدراجة والجري؟', answers: ['البياتلون', 'الترياتلون', 'البنتاتلون', 'الديكاتلون'], correctIndex: 1, category: 'رياضة', difficulty: 'easy' },
  { id: 'spo-8', question: 'كم مرة فاز محمد صلاح بجائزة أفضل لاعب في إنجلترا؟', answers: ['مرة', 'مرتين', 'ثلاث مرات', 'أربع مرات'], correctIndex: 1, category: 'رياضة', difficulty: 'medium' },
  { id: 'wis-1', question: 'ما هي الصيغة الكيميائية للماء؟', answers: ['H2O', 'CO2', 'O2', 'NaCl'], correctIndex: 0, category: 'علوم', difficulty: 'easy' },
  { id: 'wis-2', question: 'كم كوكب في مجموعتنا الشمسية؟', answers: ['٧', '٨', '٩', '١٠'], correctIndex: 1, category: 'علوم', difficulty: 'easy' },
  { id: 'wis-3', question: 'أي عضو يضخ الدم في الجسم؟', answers: ['الرئتان', 'الكبد', 'القلب', 'الكلية'], correctIndex: 2, category: 'علوم', difficulty: 'easy' },
  { id: 'wis-4', question: 'ما هي أصلب مادة طبيعية؟', answers: ['الفولاذ', 'الألماس', 'الكوارتز', 'الياقوت'], correctIndex: 1, category: 'علوم', difficulty: 'easy' },
  { id: 'wis-5', question: 'من طور نظرية النسبية؟', answers: ['إسحاق نيوتن', 'نيلز بور', 'ألبرت أينشتاين', 'ماكس بلانك'], correctIndex: 2, category: 'علوم', difficulty: 'easy' },
  { id: 'wis-6', question: 'ما هو الرقم الهيدروجيني للماء النقي؟', answers: ['٥', '٦', '٧', '٨'], correctIndex: 2, category: 'علوم', difficulty: 'medium' },
  { id: 'wis-7', question: 'كم عظمة في جسم الإنسان البالغ تقريبا؟', answers: ['١٠٦', '١٥٦', '٢٠٦', '٢٥٦'], correctIndex: 2, category: 'علوم', difficulty: 'medium' },
  { id: 'wis-8', question: 'من اخترع الخوارزميات؟', answers: ['ابن سينا', 'الخوارزمي', 'ابن الهيثم', 'جابر بن حيان'], correctIndex: 1, category: 'علوم', difficulty: 'easy' },
  { id: 'fil-1', question: 'من يلعب دور جاك سبارو في "قراصنة الكاريبي"؟', answers: ['أورلاندو بلوم', 'جوني ديب', 'براد بيت', 'ليوناردو دي كابريو'], correctIndex: 1, category: 'سينما', difficulty: 'easy' },
  { id: 'fil-2', question: 'كم عدد أفلام هاري بوتر؟', answers: ['٦', '٧', '٨', '٩'], correctIndex: 2, category: 'سينما', difficulty: 'easy' },
  { id: 'fil-3', question: 'ما اسم ملكة الثلج في فيلم ديزني؟', answers: ['آنا', 'إلسا', 'رابونزل', 'ميريدا'], correctIndex: 1, category: 'سينما', difficulty: 'easy' },
  { id: 'fil-4', question: 'من يلعب دور آيرون مان في MCU؟', answers: ['كريس إيفانز', 'كريس هيمسوورث', 'روبرت داوني جونيور', 'مارك رافالو'], correctIndex: 2, category: 'سينما', difficulty: 'easy' },
  { id: 'fil-5', question: 'أي مسلسل عربي حقق شهرة واسعة؟', answers: ['نور', 'باب الحارة', 'عمر', 'كل هذه'], correctIndex: 3, category: 'سينما', difficulty: 'easy' },
  { id: 'mus-1', question: 'أي فرقة غنت "Bohemian Rhapsody"؟', answers: ['البيتلز', 'ليد زيبلين', 'كوين', 'بينك فلويد'], correctIndex: 2, category: 'موسيقى', difficulty: 'easy' },
  { id: 'mus-2', question: 'من هو "ملك البوب"؟', answers: ['إلفيس بريسلي', 'مايكل جاكسون', 'برنس', 'فريدي ميركوري'], correctIndex: 1, category: 'موسيقى', difficulty: 'easy' },
  { id: 'mus-3', question: 'أي آلة موسيقية لها ٨٨ مفتاح؟', answers: ['الأورغ', 'الأكورديون', 'البيانو', 'الكيبورد'], correctIndex: 2, category: 'موسيقى', difficulty: 'easy' },
  { id: 'mus-4', question: 'من هي "كوكب الشرق"؟', answers: ['فيروز', 'أم كلثوم', 'وردة', 'صباح'], correctIndex: 1, category: 'موسيقى', difficulty: 'easy' },
  { id: 'mus-5', question: 'من أي بلد نشأ الريغي؟', answers: ['البلوز', 'جامايكا', 'كوبا', 'البرازيل'], correctIndex: 1, category: 'موسيقى', difficulty: 'easy' },
  { id: 'all-1', question: 'كم يوم في السنة الكبيسة؟', answers: ['٣٦٤', '٣٦٥', '٣٦٦', '٣٦٧'], correctIndex: 2, category: 'معلومات عامة', difficulty: 'easy' },
  { id: 'all-2', question: 'ما اللون الناتج عن خلط الأزرق والأصفر؟', answers: ['أحمر', 'أخضر', 'برتقالي', 'بنفسجي'], correctIndex: 1, category: 'معلومات عامة', difficulty: 'easy' },
  { id: 'all-3', question: 'ما هي عملة اليابان؟', answers: ['وون', 'يوان', 'ين', 'روبية'], correctIndex: 2, category: 'معلومات عامة', difficulty: 'easy' },
  { id: 'all-4', question: 'ما هي اللغة الرسمية للبرازيل؟', answers: ['الإسبانية', 'البرتغالية', 'الفرنسية', 'الإنجليزية'], correctIndex: 1, category: 'معلومات عامة', difficulty: 'easy' },
  { id: 'all-5', question: 'كم عدد أركان الإسلام؟', answers: ['٣', '٤', '٥', '٦'], correctIndex: 2, category: 'معلومات عامة', difficulty: 'easy' },
  { id: 'nat-1', question: 'ما هو أكبر حيوان في العالم؟', answers: ['الفيل', 'الزرافة', 'الحوت الأزرق', 'القرش الأبيض'], correctIndex: 2, category: 'طبيعة', difficulty: 'easy' },
  { id: 'nat-2', question: 'كم أرجل للعنكبوت؟', answers: ['٦', '٨', '١٠', '١٢'], correctIndex: 1, category: 'طبيعة', difficulty: 'easy' },
  { id: 'nat-3', question: 'ما هو أسرع حيوان بري؟', answers: ['الأسد', 'الفهد', 'الظبي', 'السلوقي'], correctIndex: 1, category: 'طبيعة', difficulty: 'easy' },
  { id: 'nat-4', question: 'كم قلب للأخطبوط؟', answers: ['١', '٢', '٣', '٤'], correctIndex: 2, category: 'طبيعة', difficulty: 'hard' },
  { id: 'nat-5', question: 'أي زهرة هي رمز هولندا؟', answers: ['الوردة', 'دوار الشمس', 'التوليب', 'الزنبق'], correctIndex: 2, category: 'طبيعة', difficulty: 'easy' },
  { id: 'tec-1', question: 'من أسس شركة آبل؟', answers: ['بيل غيتس', 'ستيف جوبز', 'إيلون ماسك', 'جيف بيزوس'], correctIndex: 1, category: 'تكنولوجيا', difficulty: 'easy' },
  { id: 'tec-2', question: 'أي شركة طورت أندرويد؟', answers: ['آبل', 'مايكروسوفت', 'غوغل', 'سامسونغ'], correctIndex: 2, category: 'تكنولوجيا', difficulty: 'easy' },
  { id: 'tec-3', question: 'ماذا تعني "الذكاء الاصطناعي"؟', answers: ['الذكاء الآلي', 'الذكاء الاصطناعي', 'التكامل المتقدم', 'التكامل التلقائي'], correctIndex: 1, category: 'تكنولوجيا', difficulty: 'easy' },
  { id: 'tec-4', question: 'من اخترع شبكة الإنترنت العالمية؟', answers: ['ستيف جوبز', 'بيل غيتس', 'تيم بيرنرز لي', 'مارك زوكربيرغ'], correctIndex: 2, category: 'تكنولوجيا', difficulty: 'medium' },
  { id: 'ess-1', question: 'من أي بلد تأتي البيتزا؟', answers: ['إسبانيا', 'فرنسا', 'إيطاليا', 'اليونان'], correctIndex: 2, category: 'طعام', difficulty: 'easy' },
  { id: 'ess-2', question: 'من أي بلد يأتي السوشي؟', answers: ['الصين', 'كوريا', 'اليابان', 'تايلاند'], correctIndex: 2, category: 'طعام', difficulty: 'easy' },
  { id: 'ess-3', question: 'أي بلد ينتج أكثر قهوة؟', answers: ['كولومبيا', 'إثيوبيا', 'فيتنام', 'البرازيل'], correctIndex: 3, category: 'طعام', difficulty: 'medium' },
  { id: 'ess-4', question: 'ما هو الطبق الوطني المصري؟', answers: ['الفلافل', 'الكشري', 'الشاورما', 'الحمص'], correctIndex: 1, category: 'طعام', difficulty: 'easy' },
  { id: 'ess-5', question: 'أي خضار يسبب البكاء عند تقطيعه؟', answers: ['الثوم', 'البصل', 'الفجل', 'الفلفل'], correctIndex: 1, category: 'طعام', difficulty: 'easy' },
];
let _usedIndices: Set<number> = new Set();
export function getRandomQuestion(): QuizQuestion { if (_usedIndices.size >= QUIZ_QUESTIONS_AR.length) { _usedIndices.clear(); } let idx: number; do { idx = Math.floor(Math.random() * QUIZ_QUESTIONS_AR.length); } while (_usedIndices.has(idx)); _usedIndices.add(idx); return QUIZ_QUESTIONS_AR[idx]; }
export function resetQuestions(): void { _usedIndices.clear(); }
