export interface QuizQuestion { id: string; question: string; answers: string[]; correctIndex: number; category: string; difficulty: 'easy' | 'medium' | 'hard'; }
export const QUIZ_QUESTIONS_TR: QuizQuestion[] = [
  { id: 'geo-1', question: 'Avustralya\'nin baskenti neresidir?', answers: ['Sidney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, category: 'Cografya', difficulty: 'medium' },
  { id: 'geo-2', question: 'Dunyanin en uzun nehri hangisidir?', answers: ['Amazon', 'Nil', 'Yangtze', 'Mississippi'], correctIndex: 1, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-3', question: 'Machu Picchu hangi ulkededir?', answers: ['Bolivya', 'Ekvador', 'Peru', 'Kolombiya'], correctIndex: 2, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-4', question: 'Turkiye kac ilden olusur?', answers: ['79', '80', '81', '82'], correctIndex: 2, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-5', question: 'Dunyanin en kucuk ulkesi hangisidir?', answers: ['Monako', 'Vatikan', 'San Marino', 'Lihtenstayn'], correctIndex: 1, category: 'Cografya', difficulty: 'medium' },
  { id: 'geo-6', question: 'Hangi ulke cizme seklindedir?', answers: ['Ispanya', 'Yunanistan', 'Italya', 'Portekiz'], correctIndex: 2, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-7', question: 'Dunyanin en yuksek dagi hangisidir?', answers: ['K2', 'Kangchenjunga', 'Everest', 'Lhotse'], correctIndex: 2, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-8', question: 'Dunyanin en buyuk ulkesi hangisidir?', answers: ['Kanada', 'Cin', 'ABD', 'Rusya'], correctIndex: 3, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-9', question: 'Istanbul hangi bogazda yer alir?', answers: ['Canakkale', 'Istanbul Bogazi', 'Cebelitarik', 'Sueys'], correctIndex: 1, category: 'Cografya', difficulty: 'easy' },
  { id: 'geo-10', question: 'Turkiye\'nin en uzun nehri hangisidir?', answers: ['Firat', 'Kizilirmak', 'Dicle', 'Sakarya'], correctIndex: 1, category: 'Cografya', difficulty: 'medium' },
  { id: 'his-1', question: 'Berlin Duvari hangi yil yikildi?', answers: ['1987', '1988', '1989', '1990'], correctIndex: 2, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-2', question: 'Ay\'a ilk ayak basan kisidir?', answers: ['Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'John Glenn'], correctIndex: 1, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-3', question: 'Giza piramitlerini hangi medeniyet yapti?', answers: ['Romalilar', 'Yunanlılar', 'Misirlilar', 'Persler'], correctIndex: 2, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-4', question: 'Turkiye Cumhuriyeti hangi yil kuruldu?', answers: ['1920', '1921', '1922', '1923'], correctIndex: 3, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-5', question: 'Istanbul\'un fethi hangi yildadir?', answers: ['1451', '1453', '1455', '1461'], correctIndex: 1, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-6', question: 'Mona Lisa\'yi kim cizdi?', answers: ['Michelangelo', 'Rafael', 'Leonardo da Vinci', 'Rembrandt'], correctIndex: 2, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-7', question: 'Kolomb Amerika\'yi hangi yil kesfetti?', answers: ['1482', '1492', '1502', '1512'], correctIndex: 1, category: 'Tarih', difficulty: 'easy' },
  { id: 'his-8', question: 'Titanic hangi yil batti?', answers: ['1910', '1912', '1914', '1916'], correctIndex: 1, category: 'Tarih', difficulty: 'medium' },
  { id: 'spo-1', question: 'Bir futbol takiminda sahada kac oyuncu vardir?', answers: ['9', '10', '11', '12'], correctIndex: 2, category: 'Spor', difficulty: 'easy' },
  { id: 'spo-2', question: 'Olimpiyat sembolunde kac halka vardir?', answers: ['3', '4', '5', '6'], correctIndex: 2, category: 'Spor', difficulty: 'easy' },
  { id: 'spo-3', question: '100 metre rekor kime aittir?', answers: ['Carl Lewis', 'Usain Bolt', 'Tyson Gay', 'Yohan Blake'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'spo-4', question: 'Maraton kac kilometredir (yuvarlanmis)?', answers: ['40 km', '42 km', '44 km', '46 km'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'spo-5', question: 'En cok Sampiyonlar Ligi kupasi olan kulup hangisidir?', answers: ['FC Barcelona', 'AC Milan', 'Real Madrid', 'Bayern Munih'], correctIndex: 2, category: 'Spor', difficulty: 'medium' },
  { id: 'spo-6', question: 'Sumo gulesi hangi ulkeye aittir?', answers: ['Cin', 'Kore', 'Japonya', 'Tayland'], correctIndex: 2, category: 'Spor', difficulty: 'easy' },
  { id: 'spo-7', question: 'Yagli gures hangi ulkenin geleneksel sporudur?', answers: ['Iran', 'Turkiye', 'Mogolistan', 'Hindistan'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'spo-8', question: 'Hangi spor yuzme, bisiklet ve kosuyu birlestirir?', answers: ['Biatlon', 'Triatlon', 'Pentatlon', 'Dekatlon'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'wis-1', question: 'Suyun kimyasal formulu nedir?', answers: ['H2O', 'CO2', 'O2', 'NaCl'], correctIndex: 0, category: 'Bilim', difficulty: 'easy' },
  { id: 'wis-2', question: 'Gunes sistemimizde kac gezegen var?', answers: ['7', '8', '9', '10'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'wis-3', question: 'Hangi organ kani vucuda pompalar?', answers: ['Akciger', 'Karaciger', 'Kalp', 'Bobrek'], correctIndex: 2, category: 'Bilim', difficulty: 'easy' },
  { id: 'wis-4', question: 'En sert dogal madde nedir?', answers: ['Celik', 'Elmas', 'Kuvars', 'Safir'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'wis-5', question: 'Gorelilik teorisini kim gelistirdi?', answers: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Max Planck'], correctIndex: 2, category: 'Bilim', difficulty: 'easy' },
  { id: 'wis-6', question: 'Saf suyun pH degeri kactir?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Bilim', difficulty: 'medium' },
  { id: 'wis-7', question: 'Bir yetiskin insanda yaklasik kac kemik vardir?', answers: ['106', '156', '206', '256'], correctIndex: 2, category: 'Bilim', difficulty: 'medium' },
  { id: 'wis-8', question: 'Aziz Sancar hangi alanda Nobel odulu aldi?', answers: ['Fizik', 'Kimya', 'Tip', 'Edebiyat'], correctIndex: 1, category: 'Bilim', difficulty: 'medium' },
  { id: 'fil-1', question: '"Karayip Korsanlari"nda Jack Sparrow\'u kim canlandirir?', answers: ['Orlando Bloom', 'Johnny Depp', 'Brad Pitt', 'Leonardo DiCaprio'], correctIndex: 1, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'fil-2', question: 'Kac Harry Potter filmi vardir?', answers: ['6', '7', '8', '9'], correctIndex: 2, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'fil-3', question: 'Disney filmindeki Buz Kralicesi\'nin adi nedir?', answers: ['Anna', 'Elsa', 'Rapunzel', 'Merida'], correctIndex: 1, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'fil-4', question: 'MCU\'da Iron Man\'i kim canlandirir?', answers: ['Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr.', 'Mark Ruffalo'], correctIndex: 2, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'fil-5', question: 'Hangi Turk dizisi dunyada buyuk ilgi gordu?', answers: ['Kurtlar Vadisi', 'Muhtesem Yuzyil', 'Cukur', 'Hepsi'], correctIndex: 1, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'mus-1', question: '"Bohemian Rhapsody"yi hangi grup soyledi?', answers: ['The Beatles', 'Led Zeppelin', 'Queen', 'Pink Floyd'], correctIndex: 2, category: 'Muzik', difficulty: 'easy' },
  { id: 'mus-2', question: '"Pop\'un Krali" kimdir?', answers: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Freddie Mercury'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'mus-3', question: 'Hangi calginin 88 tusu vardir?', answers: ['Org', 'Akordeon', 'Piyano', 'Klavye'], correctIndex: 2, category: 'Muzik', difficulty: 'easy' },
  { id: 'mus-4', question: '"Simarik" sarkisiyla tanidiginiz Turk pop stari kimdir?', answers: ['Sezen Aksu', 'Tarkan', 'Hadise', 'Ajda Pekkan'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'mus-5', question: 'Reggae muzik hangi ulkede dogdu?', answers: ['Blues', 'Jamaika', 'Kuba', 'Brezilya'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'all-1', question: 'Artik yilda kac gun vardir?', answers: ['364', '365', '366', '367'], correctIndex: 2, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'all-2', question: 'Mavi ve sariyi karistirinca hangi renk olur?', answers: ['Kirmizi', 'Yesil', 'Turuncu', 'Mor'], correctIndex: 1, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'all-3', question: 'Japonya\'nin para birimi nedir?', answers: ['Won', 'Yuan', 'Yen', 'Rupi'], correctIndex: 2, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'all-4', question: 'Cumhuriyet Bayrami hangi tarihte kutlanir?', answers: ['23 Nisan', '19 Mayis', '30 Agustos', '29 Ekim'], correctIndex: 3, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'all-5', question: 'Brezilya\'nin resmi dili nedir?', answers: ['Ispanyolca', 'Portekizce', 'Fransizca', 'Ingilizce'], correctIndex: 1, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'nat-1', question: 'Dunyadaki en buyuk hayvan hangisidir?', answers: ['Fil', 'Zurafa', 'Mavi balina', 'Beyaz kopekbaligi'], correctIndex: 2, category: 'Doga', difficulty: 'easy' },
  { id: 'nat-2', question: 'Bir orumcegin kac bacagi var?', answers: ['6', '8', '10', '12'], correctIndex: 1, category: 'Doga', difficulty: 'easy' },
  { id: 'nat-3', question: 'En hizli kara hayvani hangisidir?', answers: ['Aslan', 'Cita', 'Antilop', 'Tazı'], correctIndex: 1, category: 'Doga', difficulty: 'easy' },
  { id: 'nat-4', question: 'Bir ahtapotun kac kalbi var?', answers: ['1', '2', '3', '4'], correctIndex: 2, category: 'Doga', difficulty: 'hard' },
  { id: 'nat-5', question: 'Hollanda\'nin simgesi olan cicek hangisidir?', answers: ['Gul', 'Aycicegi', 'Lale', 'Zambak'], correctIndex: 2, category: 'Doga', difficulty: 'easy' },
  { id: 'tec-1', question: 'Apple\'i kim kurdu?', answers: ['Bill Gates', 'Steve Jobs', 'Elon Musk', 'Jeff Bezos'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'tec-2', question: 'Android\'i hangi sirket gelistirdi?', answers: ['Apple', 'Microsoft', 'Google', 'Samsung'], correctIndex: 2, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'tec-3', question: '"YZ" ne anlama gelir?', answers: ['Yakin Zamanda', 'Yapay Zeka', 'Yuksek Zeka', 'Yeni Zaman'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'tec-4', question: 'World Wide Web\'i kim icat etti?', answers: ['Steve Jobs', 'Bill Gates', 'Tim Berners-Lee', 'Mark Zuckerberg'], correctIndex: 2, category: 'Teknoloji', difficulty: 'medium' },
  { id: 'ess-1', question: 'Pizza hangi ulkeden gelir?', answers: ['Ispanya', 'Fransa', 'Italya', 'Yunanistan'], correctIndex: 2, category: 'Yemek', difficulty: 'easy' },
  { id: 'ess-2', question: 'Sushi hangi ulkeden gelir?', answers: ['Cin', 'Kore', 'Japonya', 'Tayland'], correctIndex: 2, category: 'Yemek', difficulty: 'easy' },
  { id: 'ess-3', question: 'Lahmacun hangi mutfaga aittir?', answers: ['Arap', 'Turk', 'Iran', 'Yunan'], correctIndex: 1, category: 'Yemek', difficulty: 'easy' },
  { id: 'ess-4', question: 'Hangi ulke en cok kahve uretir?', answers: ['Kolombiya', 'Etiyopya', 'Vietnam', 'Brezilya'], correctIndex: 3, category: 'Yemek', difficulty: 'medium' },
  { id: 'ess-5', question: 'Hangi sebze keserken gozleri yaktirir?', answers: ['Sarimsak', 'Sogan', 'Turp', 'Biber'], correctIndex: 1, category: 'Yemek', difficulty: 'easy' },
  { id: 'xq-1', question: 'Turkiye\'nin baskenti hangi sehirdir?', answers: ['Istanbul', 'Ankara', 'Izmir', 'Bursa'], correctIndex: 1, category: 'Cografya', difficulty: 'easy' },
  { id: 'xq-2', question: 'Dunyanin en uzun nehri hangisidir?', answers: ['Amazon', 'Nil', 'Mississippi', 'Yangtze'], correctIndex: 1, category: 'Cografya', difficulty: 'medium' },
  { id: 'xq-3', question: 'Hangi sehir iki kitaya yayilmistir?', answers: ['Atina', 'Istanbul', 'Roma', 'Kahire'], correctIndex: 1, category: 'Cografya', difficulty: 'easy' },
  { id: 'xq-4', question: 'Avustralya\'nin baskenti hangi sehirdir?', answers: ['Sidney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, category: 'Cografya', difficulty: 'medium' },
  { id: 'xq-5', question: 'Dunyanin en yuksek dagi hangisidir?', answers: ['K2', 'Everest', 'Kilimanjaro', 'Aconcagua'], correctIndex: 1, category: 'Cografya', difficulty: 'easy' },
  { id: 'xq-6', question: 'Hangi ulke en fazla nufusa sahiptir?', answers: ['Cin', 'Hindistan', 'ABD', 'Endonezya'], correctIndex: 1, category: 'Cografya', difficulty: 'medium' },
  { id: 'xq-7', question: 'Turkiye\'nin en buyuk golu hangisidir?', answers: ['Tuz Golu', 'Van Golu', 'Beysehir Golu', 'Egirdir Golu'], correctIndex: 1, category: 'Cografya', difficulty: 'easy' },
  { id: 'xq-8', question: 'Sahra Colu hangi kitada yer alir?', answers: ['Asya', 'Afrika', 'Avustralya', 'Guney Amerika'], correctIndex: 1, category: 'Cografya', difficulty: 'easy' },
  { id: 'xq-9', question: 'Hangi okyanus dunyanin en buyuk okyanusudur?', answers: ['Atlas Okyanusu', 'Hint Okyanusu', 'Pasifik Okyanusu', 'Arktik Okyanusu'], correctIndex: 2, category: 'Cografya', difficulty: 'easy' },
  { id: 'xq-10', question: 'Eyfel Kulesi hangi sehirdedir?', answers: ['Londra', 'Paris', 'Berlin', 'Madrid'], correctIndex: 1, category: 'Cografya', difficulty: 'easy' },
  { id: 'xq-11', question: 'Turkiye\'nin en yuksek dagi hangisidir?', answers: ['Erciyes', 'Agri Dagi', 'Kackar', 'Suphan'], correctIndex: 1, category: 'Cografya', difficulty: 'medium' },
  { id: 'xq-12', question: 'Japonya\'nin baskenti hangi sehirdir?', answers: ['Osaka', 'Kyoto', 'Tokyo', 'Nagoya'], correctIndex: 2, category: 'Cografya', difficulty: 'easy' },
  { id: 'xq-13', question: 'Hangi ulke Iskandinavya\'da yer almaz?', answers: ['Norvec', 'Isvec', 'Danimarka', 'Hollanda'], correctIndex: 3, category: 'Cografya', difficulty: 'medium' },
  { id: 'xq-14', question: 'Boyutca dunyanin en buyuk ulkesi hangisidir?', answers: ['Kanada', 'Cin', 'Rusya', 'ABD'], correctIndex: 2, category: 'Cografya', difficulty: 'easy' },
  { id: 'xq-15', question: 'Turkiye Cumhuriyeti hangi yil kuruldu?', answers: ['1920', '1923', '1918', '1930'], correctIndex: 1, category: 'Tarih', difficulty: 'easy' },
  { id: 'xq-16', question: 'Istanbul\'u (Konstantinopolis) 1453\'te fetheden Osmanli padisahi kimdir?', answers: ['Yavuz Sultan Selim', 'Fatih Sultan Mehmet', 'Kanuni Sultan Suleyman', 'Orhan Gazi'], correctIndex: 1, category: 'Tarih', difficulty: 'easy' },
  { id: 'xq-17', question: 'Birinci Dunya Savasi hangi yil basladi?', answers: ['1912', '1914', '1916', '1918'], correctIndex: 1, category: 'Tarih', difficulty: 'medium' },
  { id: 'xq-18', question: 'Turkiye\'nin ilk cumhurbaskani kimdir?', answers: ['Ismet Inonu', 'Mustafa Kemal Ataturk', 'Celal Bayar', 'Mahmut Sevket Pasa'], correctIndex: 1, category: 'Tarih', difficulty: 'easy' },
  { id: 'xq-19', question: 'Antik Misir\'da firavunlar icin insa edilen anitsal mezarlara ne ad verilir?', answers: ['Ziggurat', 'Piramit', 'Tapinak', 'Mastaba'], correctIndex: 1, category: 'Tarih', difficulty: 'easy' },
  { id: 'xq-20', question: 'Ikinci Dunya Savasi hangi yil sona erdi?', answers: ['1943', '1944', '1945', '1946'], correctIndex: 2, category: 'Tarih', difficulty: 'easy' },
  { id: 'xq-21', question: 'Roma Imparatorlugu\'nun unlu komutani ve diktatoru kimdir?', answers: ['Julius Caesar', 'Hannibal', 'Iskender', 'Spartakus'], correctIndex: 0, category: 'Tarih', difficulty: 'medium' },
  { id: 'xq-22', question: 'Cumhuriyet doneminde Turkiye\'de Latin alfabesine gecis hangi yil yapildi?', answers: ['1925', '1928', '1932', '1934'], correctIndex: 1, category: 'Tarih', difficulty: 'medium' },
  { id: 'xq-23', question: 'Berlin Duvari hangi yil yikildi?', answers: ['1987', '1989', '1991', '1993'], correctIndex: 1, category: 'Tarih', difficulty: 'medium' },
  { id: 'xq-24', question: 'Osmanli Devleti\'nin kurucusu kimdir?', answers: ['Orhan Bey', 'Osman Bey', 'Murat Hudavendigar', 'Sultan Alparslan'], correctIndex: 1, category: 'Tarih', difficulty: 'medium' },
  { id: 'xq-25', question: 'Malazgirt Savasi hangi yil yapildi?', answers: ['1071', '1453', '1299', '1176'], correctIndex: 0, category: 'Tarih', difficulty: 'hard' },
  { id: 'xq-26', question: 'Amerika kitasina 1492\'de ulasan denizci kimdir?', answers: ['Macellan', 'Kristof Kolomb', 'Vasco da Gama', 'Marco Polo'], correctIndex: 1, category: 'Tarih', difficulty: 'easy' },
  { id: 'xq-27', question: 'Kanuni Sultan Suleyman hangi unvanla da bilinir?', answers: ['Yavuz', 'Fatih', 'Muhtesem', 'Gazi'], correctIndex: 2, category: 'Tarih', difficulty: 'medium' },
  { id: 'xq-28', question: 'Fransiz Devrimi hangi yil basladi?', answers: ['1776', '1789', '1804', '1815'], correctIndex: 1, category: 'Tarih', difficulty: 'hard' },
  { id: 'xq-29', question: 'Bir futbol takiminda sahada kac oyuncu bulunur?', answers: ['9', '10', '11', '12'], correctIndex: 2, category: 'Spor', difficulty: 'easy' },
  { id: 'xq-30', question: 'Olimpiyat Oyunlari kac yilda bir duzenlenir?', answers: ['2', '3', '4', '5'], correctIndex: 2, category: 'Spor', difficulty: 'easy' },
  { id: 'xq-31', question: '2002 Dunya Kupasi\'nda Turkiye milli futbol takimi kacinci oldu?', answers: ['Birinci', 'Ikinci', 'Ucuncu', 'Dorduncu'], correctIndex: 2, category: 'Spor', difficulty: 'medium' },
  { id: 'xq-32', question: 'Basketbolda bir sayinin uc sayilmasi icin top nereden atilmalidir?', answers: ['Pota altindan', 'Serbest atis cizgisinden', 'Uc sayi cizgisinin disindan', 'Orta sahadan'], correctIndex: 2, category: 'Spor', difficulty: 'easy' },
  { id: 'xq-33', question: 'Tenis turnuvasi Wimbledon hangi ulkede duzenlenir?', answers: ['ABD', 'Fransa', 'Ingiltere', 'Avustralya'], correctIndex: 2, category: 'Spor', difficulty: 'medium' },
  { id: 'xq-34', question: 'Formula 1\'de yarislar genellikle hangi pist uzerinde yapilir?', answers: ['Toprak pist', 'Asfalt pist', 'Buz pist', 'Kum pist'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'xq-35', question: 'Bir maraton kosusunun resmi mesafesi yaklasik kac kilometredir?', answers: ['21 km', '32 km', '42 km', '50 km'], correctIndex: 2, category: 'Spor', difficulty: 'medium' },
  { id: 'xq-36', question: 'Hangi spor dalinda \'smac\' terimi kullanilir?', answers: ['Futbol', 'Voleybol', 'Yuzme', 'Golf'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'xq-37', question: 'FIFA Dunya Kupasi\'ni en cok kazanan ulke hangisidir?', answers: ['Almanya', 'Brezilya', 'Italya', 'Arjantin'], correctIndex: 1, category: 'Spor', difficulty: 'medium' },
  { id: 'xq-38', question: 'Galatasaray hangi sehrin takimidir?', answers: ['Ankara', 'Izmir', 'Istanbul', 'Trabzon'], correctIndex: 2, category: 'Spor', difficulty: 'easy' },
  { id: 'xq-39', question: 'Bir golf sahasinda standart kac delik bulunur?', answers: ['9', '12', '18', '24'], correctIndex: 2, category: 'Spor', difficulty: 'medium' },
  { id: 'xq-40', question: 'Tour de France hangi spor dalinin yarisidir?', answers: ['Kosu', 'Bisiklet', 'At yarisi', 'Motosiklet'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'xq-41', question: 'Buz hokeyinde topun yerini hangi nesne alir?', answers: ['Disk (puck)', 'Top', 'Halka', 'Mekik'], correctIndex: 0, category: 'Spor', difficulty: 'medium' },
  { id: 'xq-42', question: 'Olimpiyat halkalarinin sayisi kactir?', answers: ['4', '5', '6', '7'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'xq-43', question: 'Suyun kimyasal formulu nedir?', answers: ['CO2', 'H2O', 'O2', 'NaCl'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'xq-44', question: 'Gunes Sistemi\'ndeki en buyuk gezegen hangisidir?', answers: ['Saturn', 'Jupiter', 'Neptun', 'Dunya'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'xq-45', question: 'Insan vucudundaki en buyuk organ hangisidir?', answers: ['Karaciger', 'Beyin', 'Deri', 'Akciger'], correctIndex: 2, category: 'Bilim', difficulty: 'medium' },
  { id: 'xq-46', question: 'Isigin hizina en yakin deger hangisidir?', answers: ['300.000 km/s', '30.000 km/s', '3.000 km/s', '3 milyon km/s'], correctIndex: 0, category: 'Bilim', difficulty: 'medium' },
  { id: 'xq-47', question: 'Periyodik tabloda \'O\' sembolu hangi elementi temsil eder?', answers: ['Altin', 'Oksijen', 'Osmiyum', 'Karbon'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'xq-48', question: 'Bir insanin normal vucut sicakligi yaklasik kac derecedir?', answers: ['35 C', '37 C', '39 C', '41 C'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'xq-49', question: 'Yer cekimi yasasini formule eden bilim insani kimdir?', answers: ['Einstein', 'Newton', 'Galileo', 'Darwin'], correctIndex: 1, category: 'Bilim', difficulty: 'medium' },
  { id: 'xq-50', question: 'DNA\'nin acilimindaki \'D\' harfi neyi ifade eder?', answers: ['Dioksit', 'Deoksiribo', 'Dinamik', 'Dipol'], correctIndex: 1, category: 'Bilim', difficulty: 'hard' },
  { id: 'xq-51', question: 'Hangi gezegen \'Kizil Gezegen\' olarak bilinir?', answers: ['Venus', 'Mars', 'Merkur', 'Saturn'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'xq-52', question: 'Sesin yayilamayacagi ortam hangisidir?', answers: ['Hava', 'Su', 'Boslukta (vakum)', 'Metal'], correctIndex: 2, category: 'Bilim', difficulty: 'medium' },
  { id: 'xq-53', question: 'Goreceligi (izafiyet teorisi) gelistiren bilim insani kimdir?', answers: ['Newton', 'Einstein', 'Tesla', 'Bohr'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'xq-54', question: 'Bitkilerin gunes isigiyla besin uretme surecine ne ad verilir?', answers: ['Solunum', 'Fotosentez', 'Terleme', 'Difuzyon'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'xq-55', question: 'Periyodik tablodaki en hafif element hangisidir?', answers: ['Helyum', 'Hidrojen', 'Oksijen', 'Lityum'], correctIndex: 1, category: 'Bilim', difficulty: 'medium' },
  { id: 'xq-56', question: 'Kani vucutta pompalayan organ hangisidir?', answers: ['Akciger', 'Kalp', 'Bobrek', 'Mide'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'xq-57', question: '\'Titanik\' filminin yonetmeni kimdir?', answers: ['Steven Spielberg', 'James Cameron', 'Christopher Nolan', 'Martin Scorsese'], correctIndex: 1, category: 'Film ve TV', difficulty: 'medium' },
  { id: 'xq-58', question: '\'Yuzuklerin Efendisi\' serisi hangi yazarin kitaplarina dayanir?', answers: ['J.K. Rowling', 'J.R.R. Tolkien', 'George R.R. Martin', 'C.S. Lewis'], correctIndex: 1, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'xq-58b', question: 'Harry Potter serisinde Harry\'nin en yakin iki arkadasi kimlerdir?', answers: ['Draco ve Neville', 'Ron ve Hermione', 'Fred ve George', 'Cedric ve Luna'], correctIndex: 1, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'xq-59', question: '\'Jurassic Park\' filmi hangi tur hayvanlarla unludur?', answers: ['Dinozorlar', 'Dev maymunlar', 'Kopekbalıklari', 'Uzaylilar'], correctIndex: 0, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'xq-60', question: '\'The Godfather\' (Baba) filminde basrol oynayan efsane oyuncu kimdir?', answers: ['Al Pacino', 'Marlon Brando', 'Robert De Niro', 'Jack Nicholson'], correctIndex: 1, category: 'Film ve TV', difficulty: 'medium' },
  { id: 'xq-61', question: 'Animasyon filmi \'Aslan Kral\'da basrol aslanin adi nedir?', answers: ['Simba', 'Mufasa', 'Scar', 'Nala'], correctIndex: 0, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'xq-62', question: '\'Matrix\' filminde basrol Neo\'yu kim canlandirir?', answers: ['Tom Cruise', 'Keanu Reeves', 'Brad Pitt', 'Will Smith'], correctIndex: 1, category: 'Film ve TV', difficulty: 'medium' },
  { id: 'xq-63', question: '\'Game of Thrones\' dizisi hangi roman serisine dayanir?', answers: ['Bujelerin Sarkisi', 'Buz ve Atesin Sarkisi', 'Ejderhanin Yolu', 'Demir Taht'], correctIndex: 1, category: 'Film ve TV', difficulty: 'hard' },
  { id: 'xq-64', question: '\'Pulp Fiction\' ve \'Kill Bill\' filmlerinin yonetmeni kimdir?', answers: ['Quentin Tarantino', 'Ridley Scott', 'David Fincher', 'Coen Kardesler'], correctIndex: 0, category: 'Film ve TV', difficulty: 'medium' },
  { id: 'xq-65', question: 'Disney/Pixar filmi \'Toy Story\'de kovboy oyuncagin adi nedir?', answers: ['Buzz', 'Woody', 'Rex', 'Hamm'], correctIndex: 1, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'xq-66', question: '\'Star Wars\' evreninde Luke Skywalker\'in babasi kimdir?', answers: ['Obi-Wan', 'Darth Vader', 'Yoda', 'Han Solo'], correctIndex: 1, category: 'Film ve TV', difficulty: 'medium' },
  { id: 'xq-67', question: '\'Friends\' dizisi hangi sehirde gecer?', answers: ['Los Angeles', 'New York', 'Chicago', 'Boston'], correctIndex: 1, category: 'Film ve TV', difficulty: 'medium' },
  { id: 'xq-68', question: '\'Forrest Gump\' filminde basrolu kim oynar?', answers: ['Tom Hanks', 'Kevin Costner', 'Mel Gibson', 'Harrison Ford'], correctIndex: 0, category: 'Film ve TV', difficulty: 'medium' },
  { id: 'xq-69', question: '\'Inception\' (Baslangic) filminin yonetmeni kimdir?', answers: ['Christopher Nolan', 'Denis Villeneuve', 'James Cameron', 'Ridley Scott'], correctIndex: 0, category: 'Film ve TV', difficulty: 'hard' },
  { id: 'xq-70', question: '\'Bohemian Rhapsody\' sarkisi hangi gruba aittir?', answers: ['The Beatles', 'Queen', 'Led Zeppelin', 'Pink Floyd'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'xq-71', question: 'Pop muziginin \'Kralı\' olarak anilan sanatci kimdir?', answers: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Freddie Mercury'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'xq-72', question: 'Standart bir gitarda kac tel bulunur?', answers: ['4', '5', '6', '7'], correctIndex: 2, category: 'Muzik', difficulty: 'easy' },
  { id: 'xq-73', question: 'The Beatles grubu hangi ulkeden cikmistir?', answers: ['ABD', 'Ingiltere', 'Avustralya', 'Kanada'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'xq-74', question: 'Bir orkestrayi yoneten kisiye ne ad verilir?', answers: ['Solist', 'Sef (orkestra sefi)', 'Besteci', 'Virtuoz'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'xq-75', question: '\'Like a Virgin\' ve \'Material Girl\' sarkilariyla unlu pop sanatcisi kimdir?', answers: ['Cher', 'Madonna', 'Whitney Houston', 'Tina Turner'], correctIndex: 1, category: 'Muzik', difficulty: 'medium' },
  { id: 'xq-76', question: 'Klasik muzigin unlu bestecisi Beethoven hangi ulkeden gelmektedir?', answers: ['Avusturya', 'Almanya', 'Italya', 'Fransa'], correctIndex: 1, category: 'Muzik', difficulty: 'medium' },
  { id: 'xq-77', question: 'Bir piyanonun klavyesinde toplam kac tus vardir (standart)?', answers: ['66', '76', '88', '102'], correctIndex: 2, category: 'Muzik', difficulty: 'hard' },
  { id: 'xq-78', question: 'Reggae muziginin en unlu temsilcisi kimdir?', answers: ['Bob Marley', 'Jimi Hendrix', 'James Brown', 'Stevie Wonder'], correctIndex: 0, category: 'Muzik', difficulty: 'medium' },
  { id: 'xq-79', question: '\'Smells Like Teen Spirit\' sarkisi hangi gruba aittir?', answers: ['Pearl Jam', 'Nirvana', 'Soundgarden', 'Metallica'], correctIndex: 1, category: 'Muzik', difficulty: 'medium' },
  { id: 'xq-80', question: 'Turk Sanat Muziginde kullanilan, armut bicimli yayli calgi hangisidir?', answers: ['Baglama', 'Kanun', 'Kemence', 'Ud'], correctIndex: 2, category: 'Muzik', difficulty: 'medium' },
  { id: 'xq-81', question: 'Asik Veysel hangi calgiyi calmasiyla unludur?', answers: ['Ud', 'Kanun', 'Baglama (saz)', 'Ney'], correctIndex: 2, category: 'Muzik', difficulty: 'medium' },
  { id: 'xq-82', question: '\'Thriller\' albumu hangi sanatciya aittir?', answers: ['Prince', 'Michael Jackson', 'Lionel Richie', 'Stevie Wonder'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'xq-83', question: 'Davul ve zil seti kullanan muzisyene ne denir?', answers: ['Basgitarist', 'Davulcu', 'Klavyeci', 'Vokalist'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'xq-84', question: 'Bir saatte kac dakika vardir?', answers: ['50', '60', '90', '100'], correctIndex: 1, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'xq-85', question: 'Gokkusaginda kac renk bulunur?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'xq-86', question: 'Bir haftada kac gun vardir?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'xq-87', question: 'Satrancta oyunu kazanmak icin hedef alinan tas hangisidir?', answers: ['Vezir', 'Kale', 'Sah', 'At'], correctIndex: 2, category: 'Genel kultur', difficulty: 'medium' },
  { id: 'xq-88', question: 'Mona Lisa tablosu hangi muzede sergilenmektedir?', answers: ['British Museum', 'Louvre', 'Prado', 'Uffizi'], correctIndex: 1, category: 'Genel kultur', difficulty: 'medium' },
  { id: 'xq-89', question: 'Turkiye\'nin para birimi nedir?', answers: ['Lira', 'Euro', 'Dolar', 'Dinar'], correctIndex: 0, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'xq-90', question: 'Bir dortgenin kac kenari vardir?', answers: ['3', '4', '5', '6'], correctIndex: 1, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'xq-91', question: 'Trafik isiginda \'dur\' anlamina gelen renk hangisidir?', answers: ['Yesil', 'Sari', 'Kirmizi', 'Mavi'], correctIndex: 2, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'xq-92', question: 'Romen rakamlarinda \'X\' hangi sayiyi temsil eder?', answers: ['5', '10', '50', '100'], correctIndex: 1, category: 'Genel kultur', difficulty: 'medium' },
  { id: 'xq-93', question: 'Bir yilda kac ay vardir?', answers: ['10', '11', '12', '13'], correctIndex: 2, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'xq-94', question: 'Pizza yemegi koken olarak hangi ulkeyle ozdeslesmistir?', answers: ['Yunanistan', 'Italya', 'Ispanya', 'Fransa'], correctIndex: 1, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'xq-95', question: 'Olimpiyat bayraginin zemini hangi renktir?', answers: ['Mavi', 'Beyaz', 'Kirmizi', 'Sari'], correctIndex: 1, category: 'Genel kultur', difficulty: 'medium' },
  { id: 'xq-96', question: 'Turk bayraginda hangi semboller bulunur?', answers: ['Ay ve yildiz', 'Kartal ve yildiz', 'Aslan ve gunes', 'Hilal ve mesale'], correctIndex: 0, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'xq-97', question: 'Bir dakika kac saniyedir?', answers: ['30', '45', '60', '100'], correctIndex: 2, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'xq-98', question: 'Karada yasayan en buyuk hayvan hangisidir?', answers: ['Gergedan', 'Afrika fili', 'Su aygiri', 'Zurafa'], correctIndex: 1, category: 'Doga', difficulty: 'easy' },
  { id: 'xq-99', question: 'Dunyanin en hizli kara hayvani hangisidir?', answers: ['Aslan', 'Cita', 'Ceylan', 'At'], correctIndex: 1, category: 'Doga', difficulty: 'easy' },
  { id: 'xq-100', question: 'Ari kovaninda yumurta birakan ariya ne ad verilir?', answers: ['Isci ari', 'Erkek ari', 'Kralice ari', 'Asker ari'], correctIndex: 2, category: 'Doga', difficulty: 'medium' },
  { id: 'xq-101', question: 'Pandalar agirlikli olarak neyle beslenir?', answers: ['Bambu', 'Balik', 'Et', 'Meyve'], correctIndex: 0, category: 'Doga', difficulty: 'easy' },
  { id: 'xq-102', question: 'Dunyanin en buyuk hayvani hangisidir?', answers: ['Afrika fili', 'Mavi balina', 'Beyaz kopekbaligi', 'Dev kalamar'], correctIndex: 1, category: 'Doga', difficulty: 'medium' },
  { id: 'xq-103', question: 'Kelebekler hangi yasam evresinden once kozadan cikar?', answers: ['Yumurta', 'Tirtil', 'Pupa (krizalit)', 'Larva'], correctIndex: 2, category: 'Doga', difficulty: 'hard' },
  { id: 'xq-104', question: 'Hangi kus ucamaz?', answers: ['Kartal', 'Penguen', 'Marti', 'Serce'], correctIndex: 1, category: 'Doga', difficulty: 'easy' },
  { id: 'xq-105', question: 'Bir agacin yasini belirlemek icin govdesindeki neye bakilir?', answers: ['Yapraklar', 'Halkalar', 'Kabuk rengi', 'Dallar'], correctIndex: 1, category: 'Doga', difficulty: 'medium' },
  { id: 'xq-106', question: 'Develer collerde uzun sure susuz dayanabilmek icin neyi depolar?', answers: ['Su', 'Yag (hörgüçte)', 'Hava', 'Tuz'], correctIndex: 1, category: 'Doga', difficulty: 'medium' },
  { id: 'xq-107', question: 'Ormanlarda en cok hangi gaz uretilir?', answers: ['Karbondioksit', 'Oksijen', 'Azot', 'Hidrojen'], correctIndex: 1, category: 'Doga', difficulty: 'medium' },
  { id: 'xq-108', question: 'Hangi hayvan \'denizin tehlikeli avcisi\' olarak bilinir ve uzun yuzgeci vardir?', answers: ['Yunus', 'Kopekbaligi', 'Foku', 'Mors'], correctIndex: 1, category: 'Doga', difficulty: 'easy' },
  { id: 'xq-109', question: 'Ahtapotun kac kolu vardir?', answers: ['6', '8', '10', '12'], correctIndex: 1, category: 'Doga', difficulty: 'easy' },
  { id: 'xq-110', question: 'Volkanlardan piskuren erimis kayaya ne ad verilir?', answers: ['Magma/Lav', 'Kum', 'Kristal', 'Granit'], correctIndex: 0, category: 'Doga', difficulty: 'medium' },
  { id: 'xq-111', question: 'Apple firmasinin akilli telefon serisinin adi nedir?', answers: ['Galaxy', 'iPhone', 'Pixel', 'Lumia'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'xq-112', question: '\'www\' kisaltmasi neyi ifade eder?', answers: ['World Web Window', 'World Wide Web', 'Wide World Web', 'Web World Wide'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'xq-113', question: 'Windows isletim sistemini gelistiren sirket hangisidir?', answers: ['Apple', 'Microsoft', 'Google', 'IBM'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'xq-114', question: 'Bir bilgisayarda \'beyin\' olarak adlandirilan ana islemci kisaltmasi nedir?', answers: ['GPU', 'CPU', 'RAM', 'SSD'], correctIndex: 1, category: 'Teknoloji', difficulty: 'medium' },
  { id: 'xq-115', question: 'YouTube\'u 2006 yilinda satin alan sirket hangisidir?', answers: ['Microsoft', 'Google', 'Facebook', 'Amazon'], correctIndex: 1, category: 'Teknoloji', difficulty: 'medium' },
  { id: 'xq-116', question: 'Android isletim sistemi hangi sirkete aittir?', answers: ['Apple', 'Google', 'Samsung', 'Nokia'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'xq-117', question: '\'@\' isareti en cok hangi alanda kullanilir?', answers: ['Telefon numarasi', 'E-posta adresleri', 'Sifre', 'Saat gosterimi'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'xq-118', question: 'Facebook\'un kurucusu kimdir?', answers: ['Bill Gates', 'Mark Zuckerberg', 'Steve Jobs', 'Elon Musk'], correctIndex: 1, category: 'Teknoloji', difficulty: 'medium' },
  { id: 'xq-119', question: 'Bilgisayar bilimine gore 1 byte kac bitten olusur?', answers: ['4', '8', '16', '32'], correctIndex: 1, category: 'Teknoloji', difficulty: 'hard' },
  { id: 'xq-120', question: 'Tesla ve SpaceX sirketlerinin liderligiyle taninan girisimci kimdir?', answers: ['Jeff Bezos', 'Elon Musk', 'Larry Page', 'Tim Cook'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'xq-121', question: 'Bir web sitesi adresinin basinda sik gorulen guvenli protokol kisaltmasi nedir?', answers: ['FTP', 'HTTPS', 'SMTP', 'TCP'], correctIndex: 1, category: 'Teknoloji', difficulty: 'medium' },
  { id: 'xq-122', question: 'Kablosuz internet baglantisi icin kullanilan teknolojinin yaygin adi nedir?', answers: ['Bluetooth', 'Wi-Fi', 'NFC', 'Infrared'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'xq-123', question: 'Google arama motoru hangi yil kuruldu?', answers: ['1995', '1998', '2001', '2004'], correctIndex: 1, category: 'Teknoloji', difficulty: 'hard' },
  { id: 'xq-124', question: 'Geleneksel Turk tatlisi baklavanin ana malzemelerinden biri nedir?', answers: ['Pirinc', 'Yufka', 'Patates', 'Misir'], correctIndex: 1, category: 'Yemek', difficulty: 'easy' },
  { id: 'xq-125', question: 'Sushi yemegi hangi ulkenin mutfagina aittir?', answers: ['Cin', 'Japonya', 'Kore', 'Tayland'], correctIndex: 1, category: 'Yemek', difficulty: 'easy' },
  { id: 'xq-126', question: 'Turk kahvesi nasil pisirilir?', answers: ['Filtreden gecirilerek', 'Cezvede', 'Espresso makinesinde', 'Caydanlikta'], correctIndex: 1, category: 'Yemek', difficulty: 'easy' },
  { id: 'xq-127', question: 'Mozzarella peyniri koken olarak hangi ulkeyle ozdeslesir?', answers: ['Fransa', 'Italya', 'Yunanistan', 'Ispanya'], correctIndex: 1, category: 'Yemek', difficulty: 'medium' },
  { id: 'xq-128', question: 'Adana kebap hangi malzemeden yapilir?', answers: ['Tavuk', 'Kiyma (kirmizi et)', 'Balik', 'Sebze'], correctIndex: 1, category: 'Yemek', difficulty: 'easy' },
  { id: 'xq-129', question: 'Cikolatanin ana hammaddesi nedir?', answers: ['Kakao', 'Kahve', 'Findik', 'Seker pancari'], correctIndex: 0, category: 'Yemek', difficulty: 'easy' },
  { id: 'xq-130', question: 'Geleneksel Italyan yemegi \'risotto\'nun ana malzemesi nedir?', answers: ['Makarna', 'Pirinc', 'Patates', 'Ekmek'], correctIndex: 1, category: 'Yemek', difficulty: 'medium' },
  { id: 'xq-131', question: 'Turk mutfaginda \'menemen\' hangi malzemeyle yapilir?', answers: ['Yumurta ve domates', 'Et ve pirinc', 'Balik ve limon', 'Tavuk ve mantar'], correctIndex: 0, category: 'Yemek', difficulty: 'easy' },
  { id: 'xq-132', question: 'Hangi baharat \'kirmizi altin\' olarak da bilinir ve dunyanin en pahali baharatidir?', answers: ['Karabiber', 'Safran', 'Tarcin', 'Kimyon'], correctIndex: 1, category: 'Yemek', difficulty: 'hard' },
  { id: 'xq-133', question: 'Guacamole sosunun ana malzemesi nedir?', answers: ['Domates', 'Avokado', 'Biber', 'Sogan'], correctIndex: 1, category: 'Yemek', difficulty: 'medium' },
  { id: 'xq-134', question: 'Turk mutfagina ozgu, ince yufkaya kiyma ya da peynir sarilan yemek hangisidir?', answers: ['Manti', 'Borek', 'Lahmacun', 'Pide'], correctIndex: 1, category: 'Yemek', difficulty: 'medium' },
  { id: 'xq-135', question: 'Hangi icecek kahve cekirdeginden uretilir?', answers: ['Espresso', 'Yesil cay', 'Limonata', 'Ayran'], correctIndex: 0, category: 'Yemek', difficulty: 'easy' },
  { id: 'xq-136', question: 'Geleneksel Turk icecegi \'ayran\' neyden yapilir?', answers: ['Yogurt, su ve tuz', 'Sut ve seker', 'Meyve suyu', 'Kahve ve sut'], correctIndex: 0, category: 'Yemek', difficulty: 'easy' },
  { id: 'yq-1', question: 'Kanada\'nin baskenti neresidir?', answers: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], correctIndex: 1, category: 'Cografia', difficulty: 'easy' },
  { id: 'yq-2', question: 'Hangi kita uzerinde hic ulke bulunmaz?', answers: ['Antarktika', 'Avustralya', 'Afrika', 'Asya'], correctIndex: 0, category: 'Cografia', difficulty: 'easy' },
  { id: 'yq-3', question: 'Nil Nehri hangi denize dokulur?', answers: ['Kizildeniz', 'Akdeniz', 'Hint Okyanusu', 'Karadeniz'], correctIndex: 1, category: 'Cografia', difficulty: 'medium' },
  { id: 'yq-4', question: 'Dunyanin en buyuk colu (sicak col) hangisidir?', answers: ['Gobi', 'Kalahari', 'Sahra', 'Atacama'], correctIndex: 2, category: 'Cografia', difficulty: 'easy' },
  { id: 'yq-5', question: 'Hangi ulke hem Avrupa hem Asya kitasinda topraga sahip degildir?', answers: ['Rusya', 'Kazakistan', 'Misir', 'Brezilya'], correctIndex: 3, category: 'Cografia', difficulty: 'medium' },
  { id: 'yq-6', question: 'Vezuv Yanardagi hangi ulkede bulunur?', answers: ['Yunanistan', 'Italya', 'Ispanya', 'Turkiye'], correctIndex: 1, category: 'Cografia', difficulty: 'medium' },
  { id: 'yq-7', question: 'Iguazu Selaleri hangi iki ulkenin sinirinda yer alir?', answers: ['Arjantin ve Brezilya', 'Sili ve Peru', 'Kolombiya ve Venezuela', 'Bolivya ve Paraguay'], correctIndex: 0, category: 'Cografia', difficulty: 'hard' },
  { id: 'yq-8', question: 'Turkiye\'nin en kalabalik ikinci sehri hangisidir?', answers: ['Izmir', 'Ankara', 'Bursa', 'Antalya'], correctIndex: 1, category: 'Cografia', difficulty: 'medium' },
  { id: 'yq-9', question: 'Hangi sehir \'Ebedi Sehir\' lakabiyla anilir?', answers: ['Atina', 'Roma', 'Kahire', 'Kudus'], correctIndex: 1, category: 'Cografia', difficulty: 'medium' },
  { id: 'yq-10', question: 'Dunyanin en derin golu hangisidir?', answers: ['Tanganika Golu', 'Baykal Golu', 'Superior Golu', 'Hazar Denizi'], correctIndex: 1, category: 'Cografia', difficulty: 'hard' },
  { id: 'yq-11', question: 'Antik Yunan\'da demokrasinin dogdugu sehir devleti hangisidir?', answers: ['Sparta', 'Atina', 'Korint', 'Teb'], correctIndex: 1, category: 'Tarih', difficulty: 'easy' },
  { id: 'yq-12', question: 'Buyuk Iskender hangi ulkenin krali idi?', answers: ['Pers', 'Makedonya', 'Misir', 'Roma'], correctIndex: 1, category: 'Tarih', difficulty: 'medium' },
  { id: 'yq-13', question: 'Amerikan Bagimsizlik Bildirgesi hangi yil ilan edildi?', answers: ['1776', '1789', '1804', '1812'], correctIndex: 0, category: 'Tarih', difficulty: 'medium' },
  { id: 'yq-14', question: 'Osmanli Devleti\'nde Tanzimat Fermani hangi yil ilan edildi?', answers: ['1808', '1839', '1856', '1876'], correctIndex: 1, category: 'Tarih', difficulty: 'hard' },
  { id: 'yq-15', question: 'Matbaayi Avrupa\'da gelistiren kisi kimdir?', answers: ['Johannes Gutenberg', 'Leonardo da Vinci', 'Galileo Galilei', 'Isaac Newton'], correctIndex: 0, category: 'Tarih', difficulty: 'medium' },
  { id: 'yq-16', question: 'Hangi medeniyet cived yazi sistemini gelistirmistir?', answers: ['Sumerler', 'Mayalar', 'Incalar', 'Aztekler'], correctIndex: 0, category: 'Tarih', difficulty: 'hard' },
  { id: 'yq-17', question: 'Kurtulus Savasi\'nda Buyuk Taarruz hangi yil yapildi?', answers: ['1920', '1921', '1922', '1923'], correctIndex: 2, category: 'Tarih', difficulty: 'medium' },
  { id: 'yq-18', question: 'Birinci Dunya Savasi hangi yil sona erdi?', answers: ['1916', '1917', '1918', '1919'], correctIndex: 2, category: 'Tarih', difficulty: 'easy' },
  { id: 'yq-19', question: 'Hangi imparator Roma\'yi Hristiyanligin serbest oldugu bir devlet haline getiren Milano Fermani\'ni ilan etti?', answers: ['Neron', 'Konstantin', 'Sezar', 'Augustus'], correctIndex: 1, category: 'Tarih', difficulty: 'hard' },
  { id: 'yq-20', question: 'Tarihteki ilk Olimpiyat Oyunlari hangi ulkede duzenlendi?', answers: ['Italya', 'Misir', 'Yunanistan', 'Cin'], correctIndex: 2, category: 'Tarih', difficulty: 'easy' },
  { id: 'yq-21', question: 'Bir basketbol macinda her takimda sahada kac oyuncu bulunur?', answers: ['5', '6', '7', '11'], correctIndex: 0, category: 'Spor', difficulty: 'easy' },
  { id: 'yq-22', question: 'Bir voleybol takiminda sahada kac oyuncu yer alir?', answers: ['5', '6', '7', '9'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'yq-23', question: 'Tenis\'te \'40-40\' skor durumuna ne ad verilir?', answers: ['Avantaj', 'Doys (Deuce)', 'Servis', 'Eslesme'], correctIndex: 1, category: 'Spor', difficulty: 'medium' },
  { id: 'yq-24', question: 'Olimpiyat Oyunlari\'nda en cok altin madalya kazanan sporcu kimdir?', answers: ['Usain Bolt', 'Michael Phelps', 'Carl Lewis', 'Mark Spitz'], correctIndex: 1, category: 'Spor', difficulty: 'medium' },
  { id: 'yq-25', question: 'Formula 1 tarihinin en cok dunya sampiyonluguna sahip iki pilotundan biri yedi unvanlidir; bu pilot Lewis Hamilton ve kimdir?', answers: ['Ayrton Senna', 'Michael Schumacher', 'Sebastian Vettel', 'Alain Prost'], correctIndex: 1, category: 'Spor', difficulty: 'hard' },
  { id: 'yq-26', question: 'Bir beyzbol takiminda sahada kac savunma oyuncusu bulunur?', answers: ['7', '9', '11', '5'], correctIndex: 1, category: 'Spor', difficulty: 'medium' },
  { id: 'yq-27', question: 'Ragbi sporu en cok hangi ulkelerle ozdeslesmistir?', answers: ['Yeni Zelanda ve Ingiltere', 'Brezilya ve Arjantin', 'Japonya ve Cin', 'Norvec ve Isvec'], correctIndex: 0, category: 'Spor', difficulty: 'medium' },
  { id: 'yq-28', question: 'Bir satranc tahtasinda toplam kac kare bulunur?', answers: ['49', '64', '81', '100'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'yq-29', question: 'Boks musabakalarinda bir ringin sekli nedir?', answers: ['Daire', 'Kare', 'Ucgen', 'Altigen'], correctIndex: 1, category: 'Spor', difficulty: 'easy' },
  { id: 'yq-30', question: 'Naim Suleymanoglu hangi spor dalinda Olimpiyat sampiyonu olmustur?', answers: ['Gures', 'Halter', 'Atletizm', 'Judo'], correctIndex: 1, category: 'Spor', difficulty: 'medium' },
  { id: 'yq-31', question: 'Insan vucudundaki en uzun kemik hangisidir?', answers: ['Kaval kemigi', 'Uyluk kemigi (femur)', 'Kol kemigi', 'Omurga'], correctIndex: 1, category: 'Bilim', difficulty: 'medium' },
  { id: 'yq-32', question: 'Bitkilerin yesil rengini veren pigment hangisidir?', answers: ['Klorofil', 'Hemoglobin', 'Melanin', 'Karoten'], correctIndex: 0, category: 'Bilim', difficulty: 'easy' },
  { id: 'yq-33', question: 'Periyodik tabloda \'Au\' sembolu hangi elementi temsil eder?', answers: ['Gumus', 'Altin', 'Bakir', 'Aluminyum'], correctIndex: 1, category: 'Bilim', difficulty: 'medium' },
  { id: 'yq-34', question: 'Sesin frekans birimi nedir?', answers: ['Watt', 'Hertz', 'Joule', 'Newton'], correctIndex: 1, category: 'Bilim', difficulty: 'medium' },
  { id: 'yq-35', question: 'Suyun kaynama noktasi deniz seviyesinde kac derecedir?', answers: ['90', '100', '110', '120'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'yq-36', question: 'Gunes sistemindeki Gunes\'e en yakin gezegen hangisidir?', answers: ['Venus', 'Merkur', 'Dunya', 'Mars'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'yq-37', question: 'Atomun cekirdeginde bulunmayan parcacik hangisidir?', answers: ['Proton', 'Notron', 'Elektron', 'Hicbiri'], correctIndex: 2, category: 'Bilim', difficulty: 'medium' },
  { id: 'yq-38', question: 'Evrim teorisini gelistiren bilim insani kimdir?', answers: ['Gregor Mendel', 'Charles Darwin', 'Louis Pasteur', 'Alexander Fleming'], correctIndex: 1, category: 'Bilim', difficulty: 'easy' },
  { id: 'yq-39', question: 'Penisilini kesfeden bilim insani kimdir?', answers: ['Alexander Fleming', 'Marie Curie', 'Louis Pasteur', 'Robert Koch'], correctIndex: 0, category: 'Bilim', difficulty: 'medium' },
  { id: 'yq-40', question: 'Bir maddenin kati halden dogrudan gaz haline gecmesine ne ad verilir?', answers: ['Buharlasma', 'Sublimlesme', 'Erime', 'Yogunlasma'], correctIndex: 1, category: 'Bilim', difficulty: 'hard' },
  { id: 'yq-41', question: '\'Titanic\' filminde basrol oyuncularindan biri Leonardo DiCaprio, digeri kimdir?', answers: ['Nicole Kidman', 'Kate Winslet', 'Julia Roberts', 'Cate Blanchett'], correctIndex: 1, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'yq-42', question: '\'Breaking Bad\' dizisinin ana karakteri Walter White\'in meslegi neydi?', answers: ['Doktor', 'Kimya ogretmeni', 'Avukat', 'Polis'], correctIndex: 1, category: 'Film ve TV', difficulty: 'medium' },
  { id: 'yq-43', question: '\'The Dark Knight\' filminde Joker\'i canlandiran ve olumunun ardindan Oscar kazanan oyuncu kimdir?', answers: ['Joaquin Phoenix', 'Heath Ledger', 'Jack Nicholson', 'Jared Leto'], correctIndex: 1, category: 'Film ve TV', difficulty: 'medium' },
  { id: 'yq-44', question: 'Pixar\'in \'Finding Nemo\' filminde Nemo hangi tur bir baliktir?', answers: ['Palyaco baligi', 'Kopek baligi', 'Japon baligi', 'Mavi balina'], correctIndex: 0, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'yq-45', question: '\'The Lord of the Rings\' uclemesinin yonetmeni kimdir?', answers: ['Steven Spielberg', 'Peter Jackson', 'James Cameron', 'Ridley Scott'], correctIndex: 1, category: 'Film ve TV', difficulty: 'medium' },
  { id: 'yq-46', question: '\'Stranger Things\' dizisi hangi platformda yayinlanmaktadir?', answers: ['Disney+', 'Netflix', 'HBO', 'Amazon Prime'], correctIndex: 1, category: 'Film ve TV', difficulty: 'easy' },
  { id: 'yq-47', question: '\'The Silence of the Lambs\' filminde Hannibal Lecter\'i canlandiran oyuncu kimdir?', answers: ['Anthony Hopkins', 'Al Pacino', 'Robert De Niro', 'Morgan Freeman'], correctIndex: 0, category: 'Film ve TV', difficulty: 'hard' },
  { id: 'yq-48', question: '\'Avatar\' (2009) filminin yonetmeni kimdir?', answers: ['George Lucas', 'James Cameron', 'Christopher Nolan', 'Steven Spielberg'], correctIndex: 1, category: 'Film ve TV', difficulty: 'medium' },
  { id: 'yq-49', question: '\'The Simpsons\' animasyon dizisinde ailenin yasadigi kasabanin adi nedir?', answers: ['Quahog', 'Springfield', 'South Park', 'Bedrock'], correctIndex: 1, category: 'Film ve TV', difficulty: 'medium' },
  { id: 'yq-50', question: '\'Parasite\' (Parazit) filmi En Iyi Film Oscar\'ini kazanan ilk hangi ulke yapimidir?', answers: ['Japonya', 'Guney Kore', 'Cin', 'Tayland'], correctIndex: 1, category: 'Film ve TV', difficulty: 'hard' },
  { id: 'yq-51', question: 'Wolfgang Amadeus Mozart hangi ulkede dogmustur?', answers: ['Almanya', 'Avusturya', 'Italya', 'Fransa'], correctIndex: 1, category: 'Muzik', difficulty: 'medium' },
  { id: 'yq-52', question: 'Bir senfoni orkestrasinda en buyuk yayli calgi hangisidir?', answers: ['Cello', 'Kontrbas', 'Viyola', 'Keman'], correctIndex: 1, category: 'Muzik', difficulty: 'medium' },
  { id: 'yq-53', question: '\'Imagine\' ve \'Hey Jude\' sarkilariyla taninan grubun adi nedir?', answers: ['The Rolling Stones', 'The Beatles', 'Pink Floyd', 'Led Zeppelin'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'yq-54', question: 'Caz muzigi koken olarak hangi ulkede dogmustur?', answers: ['Ingiltere', 'ABD', 'Fransa', 'Brezilya'], correctIndex: 1, category: 'Muzik', difficulty: 'medium' },
  { id: 'yq-55', question: 'Bir muzik eserinde sesin yuksekligini gosteren isaretlere ne denir?', answers: ['Nuans', 'Tempo', 'Akort', 'Ritim'], correctIndex: 0, category: 'Muzik', difficulty: 'hard' },
  { id: 'yq-56', question: '\'Rolling in the Deep\' ve \'Hello\' sarkilariyla unlu Ingiliz sanatci kimdir?', answers: ['Dua Lipa', 'Adele', 'Amy Winehouse', 'Ed Sheeran'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'yq-57', question: 'Bir gitarda parmaklarla bastirilan metal seritlere ne ad verilir?', answers: ['Perde', 'Tel', 'Kopru', 'Esik'], correctIndex: 0, category: 'Muzik', difficulty: 'medium' },
  { id: 'yq-58', question: 'Turk Halk Muziginde kullanilan, uzun saplı telli calginin adi nedir?', answers: ['Ud', 'Baglama', 'Kanun', 'Ney'], correctIndex: 1, category: 'Muzik', difficulty: 'easy' },
  { id: 'yq-59', question: 'Vivaldi\'nin unlu \'Dort Mevsim\' eseri hangi calgi icin bestelenmistir?', answers: ['Piyano', 'Keman', 'Flut', 'Org'], correctIndex: 1, category: 'Muzik', difficulty: 'hard' },
  { id: 'yq-60', question: '\'Purple Rain\' ve \'Kiss\' sarkilariyla taninan sanatci kimdir?', answers: ['Prince', 'David Bowie', 'George Michael', 'Elton John'], correctIndex: 0, category: 'Muzik', difficulty: 'medium' },
  { id: 'yq-61', question: 'Bir ucgenin ic acilari toplami kac derecedir?', answers: ['90', '180', '270', '360'], correctIndex: 1, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'yq-62', question: 'Romen rakamlarinda \'L\' hangi sayiyi temsil eder?', answers: ['5', '50', '100', '500'], correctIndex: 1, category: 'Genel kultur', difficulty: 'medium' },
  { id: 'yq-63', question: 'Bir dolar kac sente esittir?', answers: ['10', '50', '100', '1000'], correctIndex: 2, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'yq-64', question: 'Avrupa Birligi\'nin ortak para birimi nedir?', answers: ['Sterlin', 'Euro', 'Frank', 'Mark'], correctIndex: 1, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'yq-65', question: 'Kirmizi ve beyaz karistirildiginda hangi renk olusur?', answers: ['Pembe', 'Mor', 'Turuncu', 'Kahverengi'], correctIndex: 0, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'yq-66', question: 'Bir asir kac yildir?', answers: ['10', '50', '100', '1000'], correctIndex: 2, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'yq-67', question: 'Morse alfabesinde \'SOS\' sinyali hangi desenle gosterilir?', answers: ['... --- ...', '--- ... ---', '... ... ...', '--- --- ---'], correctIndex: 0, category: 'Genel kultur', difficulty: 'hard' },
  { id: 'yq-68', question: 'Bir dairenin cevresini hesaplarken kullanilan sabit sayinin adi nedir?', answers: ['Pi sayisi', 'E sayisi', 'Altin oran', 'Karekok'], correctIndex: 0, category: 'Genel kultur', difficulty: 'medium' },
  { id: 'yq-69', question: 'Birlesmis Milletler\'in merkezi hangi sehirdedir?', answers: ['Cenevre', 'New York', 'Brüksel', 'Paris'], correctIndex: 1, category: 'Genel kultur', difficulty: 'medium' },
  { id: 'yq-70', question: 'Bir duzine kac adettir?', answers: ['6', '10', '12', '20'], correctIndex: 2, category: 'Genel kultur', difficulty: 'easy' },
  { id: 'yq-71', question: 'Hangi hayvan grubu \'memeli\' degildir?', answers: ['Yunus', 'Yarasa', 'Timsah', 'Balina'], correctIndex: 2, category: 'Doga', difficulty: 'medium' },
  { id: 'yq-72', question: 'Aricilikta ariların urettigi tatli madde nedir?', answers: ['Bal', 'Vaks', 'Polen', 'Recine'], correctIndex: 0, category: 'Doga', difficulty: 'easy' },
  { id: 'yq-73', question: 'Dunyanin en yuksek agac turu hangisidir?', answers: ['Mese', 'Cam', 'Sekoya (Redwood)', 'Kavak'], correctIndex: 2, category: 'Doga', difficulty: 'hard' },
  { id: 'yq-74', question: 'Kurbagalar yasam dongusunde once hangi evreden gecer?', answers: ['Iribas', 'Koza', 'Larva kanadi', 'Yumurta zari yok'], correctIndex: 0, category: 'Doga', difficulty: 'medium' },
  { id: 'yq-75', question: 'Hangi hayvan dunyanin en hizli ucan kusu olarak bilinir?', answers: ['Kartal', 'Gokdogan (Sahin)', 'Albatros', 'Kirlangic'], correctIndex: 1, category: 'Doga', difficulty: 'hard' },
  { id: 'yq-76', question: 'Yarasalar gezinirken ve avlanirken hangi yontemi kullanir?', answers: ['Ekolokasyon', 'Koku alma', 'Termal goru', 'Manyetik alan'], correctIndex: 0, category: 'Doga', difficulty: 'medium' },
  { id: 'yq-77', question: 'Penguenler dogal olarak agirlikli olarak hangi yarim kurede yasar?', answers: ['Kuzey yarim kure', 'Guney yarim kure', 'Ekvator bolgesi', 'Kuzey Kutbu'], correctIndex: 1, category: 'Doga', difficulty: 'medium' },
  { id: 'yq-78', question: 'Bir karincanin vucudu kac ana bolumden olusur?', answers: ['2', '3', '4', '6'], correctIndex: 1, category: 'Doga', difficulty: 'medium' },
  { id: 'yq-79', question: 'Hangi hayvan derisini periyodik olarak komple degistirir (deri degistirir)?', answers: ['Yilan', 'Kopek', 'At', 'Kedi'], correctIndex: 0, category: 'Doga', difficulty: 'easy' },
  { id: 'yq-80', question: 'Mercanlar aslinda nedir?', answers: ['Bitki', 'Hayvan', 'Mantar', 'Kaya'], correctIndex: 1, category: 'Doga', difficulty: 'hard' },
  { id: 'yq-81', question: 'Bilgisayar belleginde 1 kilobayt yaklasik kac bayttir?', answers: ['100', '1000', '1024', '10000'], correctIndex: 2, category: 'Teknoloji', difficulty: 'medium' },
  { id: 'yq-82', question: '\'HTML\' kisaltmasi neyle ilgilidir?', answers: ['Web sayfasi olusturma', 'Veritabani yonetimi', 'Isletim sistemi', 'Ag guvenligi'], correctIndex: 0, category: 'Teknoloji', difficulty: 'medium' },
  { id: 'yq-83', question: 'Bir bilgisayarda gecici verileri tutan hizli bellek hangisidir?', answers: ['RAM', 'HDD', 'CPU', 'GPU'], correctIndex: 0, category: 'Teknoloji', difficulty: 'medium' },
  { id: 'yq-84', question: 'Microsoft sirketinin kurucularindan biri kimdir?', answers: ['Steve Jobs', 'Bill Gates', 'Larry Page', 'Jeff Bezos'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'yq-85', question: 'Amazon sirketinin kurucusu kimdir?', answers: ['Elon Musk', 'Jeff Bezos', 'Mark Zuckerberg', 'Bill Gates'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'yq-86', question: '\'USB\' kisaltmasinda \'U\' harfi neyi ifade eder?', answers: ['Universal', 'Ultra', 'Unit', 'Upload'], correctIndex: 0, category: 'Teknoloji', difficulty: 'hard' },
  { id: 'yq-87', question: 'Google\'in gelistirdigi web tarayicisinin adi nedir?', answers: ['Firefox', 'Chrome', 'Safari', 'Edge'], correctIndex: 1, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'yq-88', question: 'Bir QR kodu temel olarak ne ise yarar?', answers: ['Veri saklama ve okutma', 'Ses kaydetme', 'Resim duzenleme', 'Elektrik uretme'], correctIndex: 0, category: 'Teknoloji', difficulty: 'medium' },
  { id: 'yq-89', question: 'Programlama dunyasinda \'Python\' nedir?', answers: ['Bir programlama dili', 'Bir isletim sistemi', 'Bir oyun konsolu', 'Bir antivirus'], correctIndex: 0, category: 'Teknoloji', difficulty: 'easy' },
  { id: 'yq-90', question: 'Internette bir alan adinin sahibini ve adresini cozumleyen sisteme ne ad verilir?', answers: ['DNS', 'VPN', 'FTP', 'SQL'], correctIndex: 0, category: 'Teknoloji', difficulty: 'hard' },
  { id: 'yq-91', question: 'Geleneksel \'paella\' yemegi hangi ulkenin mutfagina aittir?', answers: ['Italya', 'Ispanya', 'Portekiz', 'Yunanistan'], correctIndex: 1, category: 'Yemek', difficulty: 'medium' },
  { id: 'yq-92', question: 'Cig balik ve pirincten yapilan Japon yemegi \'sashimi\' ile sushi arasindaki temel fark nedir?', answers: ['Sashimi pirincsiz servis edilir', 'Sashimi her zaman pisiriktir', 'Sashimi sadece sebzeden olusur', 'Aralarinda fark yoktur'], correctIndex: 0, category: 'Yemek', difficulty: 'hard' },
  { id: 'yq-93', question: '\'Hummus\' (humus) yemeginin ana malzemesi nedir?', answers: ['Mercimek', 'Nohut', 'Fasulye', 'Bezelye'], correctIndex: 1, category: 'Yemek', difficulty: 'medium' },
  { id: 'yq-94', question: 'Turk mutfaginda \'manti\' genellikle uzerine ne ile servis edilir?', answers: ['Yogurt ve sarimsak', 'Bal ve tarcin', 'Sirke ve seker', 'Recel'], correctIndex: 0, category: 'Yemek', difficulty: 'easy' },
  { id: 'yq-95', question: '\'Tiramisu\' tatlisi koken olarak hangi ulkeye aittir?', answers: ['Fransa', 'Italya', 'Avusturya', 'Belcika'], correctIndex: 1, category: 'Yemek', difficulty: 'medium' },
  { id: 'yq-96', question: 'Yeşil cay agirlikli olarak hangi ulkelerde tuketilir ve uretilir?', answers: ['Cin ve Japonya', 'Brezilya ve Kolombiya', 'Italya ve Ispanya', 'Almanya ve Fransa'], correctIndex: 0, category: 'Yemek', difficulty: 'medium' },
  { id: 'yq-97', question: '\'Cheddar\' bir tur nedir?', answers: ['Peynir', 'Ekmek', 'Sarap', 'Et'], correctIndex: 0, category: 'Yemek', difficulty: 'easy' },
  { id: 'yq-98', question: 'Turk kahvaltisinin vazgecilmezi olan \'simit\' uzerine genellikle ne serpilir?', answers: ['Susam', 'Hashas', 'Cevizi', 'Findik'], correctIndex: 0, category: 'Yemek', difficulty: 'easy' },
  { id: 'yq-99', question: '\'Croissant\' (kruvasan) hangi ulke ile ozdeslesmis bir hamur isidir?', answers: ['Italya', 'Fransa', 'Almanya', 'Ingiltere'], correctIndex: 1, category: 'Yemek', difficulty: 'easy' },
  { id: 'yq-100', question: 'Hangi meyve kurutuldugunda \'kuru uzum\' olur?', answers: ['Erik', 'Uzum', 'Incir', 'Kayisi'], correctIndex: 1, category: 'Yemek', difficulty: 'easy' },
];
let _usedIndices: Set<number> = new Set();
export function getRandomQuestion(): QuizQuestion { if (_usedIndices.size >= QUIZ_QUESTIONS_TR.length) { _usedIndices.clear(); } let idx: number; do { idx = Math.floor(Math.random() * QUIZ_QUESTIONS_TR.length); } while (_usedIndices.has(idx)); _usedIndices.add(idx); return QUIZ_QUESTIONS_TR[idx]; }
export function resetQuestions(): void { _usedIndices.clear(); }
