export interface QuizQuestion { id: string; question: string; answers: string[]; correctIndex: number; category: string; difficulty: 'easy' | 'medium' | 'hard'; }
export const QUIZ_QUESTIONS_NL: QuizQuestion[] = [
  { id: 'geo-1', question: 'Wat is de hoofdstad van Australie?', answers: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, category: 'Aardrijkskunde', difficulty: 'medium' },
  { id: 'geo-2', question: 'Welke rivier is de langste ter wereld?', answers: ['Amazone', 'Nijl', 'Yangtze', 'Mississippi'], correctIndex: 1, category: 'Aardrijkskunde', difficulty: 'easy' },
  { id: 'geo-3', question: 'In welk land ligt Machu Picchu?', answers: ['Bolivia', 'Ecuador', 'Peru', 'Colombia'], correctIndex: 2, category: 'Aardrijkskunde', difficulty: 'easy' },
  { id: 'geo-4', question: 'Hoeveel provincies heeft Nederland?', answers: ['10', '11', '12', '13'], correctIndex: 2, category: 'Aardrijkskunde', difficulty: 'easy' },
  { id: 'geo-5', question: 'Wat is het kleinste land ter wereld?', answers: ['Monaco', 'Vaticaanstad', 'San Marino', 'Liechtenstein'], correctIndex: 1, category: 'Aardrijkskunde', difficulty: 'medium' },
  { id: 'geo-6', question: 'Welk land heeft de vorm van een laars?', answers: ['Spanje', 'Griekenland', 'Italie', 'Portugal'], correctIndex: 2, category: 'Aardrijkskunde', difficulty: 'easy' },
  { id: 'geo-7', question: 'Welk land heeft de meeste inwoners?', answers: ['India', 'China', 'VS', 'Indonesie'], correctIndex: 0, category: 'Aardrijkskunde', difficulty: 'medium' },
  { id: 'geo-8', question: 'Wat is de grootste woestijn op aarde?', answers: ['Sahara', 'Gobi', 'Antarctica', 'Kalahari'], correctIndex: 2, category: 'Aardrijkskunde', difficulty: 'hard' },
  { id: 'geo-9', question: 'Op welk continent ligt Egypte?', answers: ['Azie', 'Afrika', 'Europa', 'Zuid-Amerika'], correctIndex: 1, category: 'Aardrijkskunde', difficulty: 'easy' },
  { id: 'geo-10', question: 'Welke stad wordt de "Big Apple" genoemd?', answers: ['Los Angeles', 'Chicago', 'New York', 'Boston'], correctIndex: 2, category: 'Aardrijkskunde', difficulty: 'easy' },
  { id: 'geo-11', question: 'Wat is de hoofdstad van Canada?', answers: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'], correctIndex: 3, category: 'Aardrijkskunde', difficulty: 'medium' },
  { id: 'geo-12', question: 'Welke berg is de hoogste ter wereld?', answers: ['K2', 'Kangchenjunga', 'Mount Everest', 'Lhotse'], correctIndex: 2, category: 'Aardrijkskunde', difficulty: 'easy' },
  { id: 'geo-13', question: 'Wat is het grootste land ter wereld qua oppervlakte?', answers: ['Canada', 'China', 'VS', 'Rusland'], correctIndex: 3, category: 'Aardrijkskunde', difficulty: 'easy' },
  { id: 'geo-14', question: 'Aan welke rivier ligt Parijs?', answers: ['Rhone', 'Loire', 'Seine', 'Garonne'], correctIndex: 2, category: 'Aardrijkskunde', difficulty: 'easy' },
  { id: 'geo-15', question: 'Welke stad ligt aan de Bosporus?', answers: ['Athene', 'Istanbul', 'Ankara', 'Boekarest'], correctIndex: 1, category: 'Aardrijkskunde', difficulty: 'medium' },
  { id: 'geo-16', question: 'Wat is de langste rivier van Nederland?', answers: ['Maas', 'Rijn', 'IJssel', 'Waal'], correctIndex: 1, category: 'Aardrijkskunde', difficulty: 'medium' },
  { id: 'geo-17', question: 'Welk land grenst niet aan Nederland?', answers: ['Belgie', 'Duitsland', 'Luxemburg', 'Frankrijk'], correctIndex: 3, category: 'Aardrijkskunde', difficulty: 'medium' },
  { id: 'geo-18', question: 'Wat is de hoofdstad van Belgie?', answers: ['Antwerpen', 'Brussel', 'Gent', 'Brugge'], correctIndex: 1, category: 'Aardrijkskunde', difficulty: 'easy' },
  { id: 'geo-19', question: 'Welk eiland behoort tot het Koninkrijk der Nederlanden?', answers: ['Ibiza', 'Curacao', 'Mallorca', 'Kreta'], correctIndex: 1, category: 'Aardrijkskunde', difficulty: 'easy' },
  { id: 'geo-20', question: 'Wat is het laagste punt van Nederland?', answers: ['Amsterdam', 'Zuidplaspolder', 'Flevopolder', 'Wieringermeer'], correctIndex: 1, category: 'Aardrijkskunde', difficulty: 'hard' },
  { id: 'his-1', question: 'In welk jaar viel de Berlijnse Muur?', answers: ['1987', '1988', '1989', '1990'], correctIndex: 2, category: 'Geschiedenis', difficulty: 'easy' },
  { id: 'his-2', question: 'Wie was de eerste mens op de maan?', answers: ['Buzz Aldrin', 'Neil Armstrong', 'Joeri Gagarin', 'John Glenn'], correctIndex: 1, category: 'Geschiedenis', difficulty: 'easy' },
  { id: 'his-3', question: 'Welk volk bouwde de piramides van Gizeh?', answers: ['Romeinen', 'Grieken', 'Egyptenaren', 'Perzen'], correctIndex: 2, category: 'Geschiedenis', difficulty: 'easy' },
  { id: 'his-4', question: 'Wanneer begon de Eerste Wereldoorlog?', answers: ['1912', '1914', '1916', '1918'], correctIndex: 1, category: 'Geschiedenis', difficulty: 'easy' },
  { id: 'his-5', question: 'Wie schilderde de Mona Lisa?', answers: ['Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Rembrandt'], correctIndex: 2, category: 'Geschiedenis', difficulty: 'easy' },
  { id: 'his-6', question: 'In welk jaar ontdekte Columbus Amerika?', answers: ['1482', '1492', '1502', '1512'], correctIndex: 1, category: 'Geschiedenis', difficulty: 'easy' },
  { id: 'his-7', question: 'Wanneer zonk de Titanic?', answers: ['1910', '1912', '1914', '1916'], correctIndex: 1, category: 'Geschiedenis', difficulty: 'medium' },
  { id: 'his-8', question: 'Wie was Anne Frank?', answers: ['Schrijfster', 'Joods meisje met dagboek', 'Koningin', 'Wetenschapper'], correctIndex: 1, category: 'Geschiedenis', difficulty: 'easy' },
  { id: 'his-9', question: 'Wie was Willem van Oranje?', answers: ['Koning', 'Vader des Vaderlands', 'Schilder', 'Ontdekker'], correctIndex: 1, category: 'Geschiedenis', difficulty: 'easy' },
  { id: 'his-10', question: 'Welk land schonk de Vrijheidsstatue aan de VS?', answers: ['Engeland', 'Duitsland', 'Frankrijk', 'Spanje'], correctIndex: 2, category: 'Geschiedenis', difficulty: 'medium' },
  { id: 'spo-1', question: 'Hoeveel spelers heeft een voetbalteam op het veld?', answers: ['9', '10', '11', '12'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-2', question: 'Welk land won het WK voetbal 2010?', answers: ['Brazilie', 'Nederland', 'Spanje', 'Duitsland'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-3', question: 'Hoeveel ringen heeft het olympisch symbool?', answers: ['3', '4', '5', '6'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-4', question: 'Wie houdt het record op de 100 meter?', answers: ['Carl Lewis', 'Usain Bolt', 'Tyson Gay', 'Dafne Schippers'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-5', question: 'Welke club heeft de meeste Champions League-titels?', answers: ['FC Barcelona', 'AC Milan', 'Real Madrid', 'Ajax'], correctIndex: 2, category: 'Sport', difficulty: 'medium' },
  { id: 'spo-6', question: 'Hoeveel kilometer is een marathon (afgerond)?', answers: ['40 km', '42 km', '44 km', '46 km'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-7', question: 'In welke Formule 1-klasse rijdt Max Verstappen?', answers: ['Ferrari', 'Mercedes', 'Red Bull', 'McLaren'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-8', question: 'Welke sport combineert zwemmen, fietsen en hardlopen?', answers: ['Biatlon', 'Triatlon', 'Pentatlon', 'Decatlon'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-9', question: 'Welke Nederlandse voetbalclub heet de "Godenzonen"?', answers: ['Feyenoord', 'PSV', 'Ajax', 'AZ'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-10', question: 'Welk land is beroemd om sumoworstelen?', answers: ['China', 'Korea', 'Japan', 'Thailand'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'wis-1', question: 'Wat is de chemische formule van water?', answers: ['H2O', 'CO2', 'O2', 'NaCl'], correctIndex: 0, category: 'Wetenschap', difficulty: 'easy' },
  { id: 'wis-2', question: 'Hoeveel planeten heeft ons zonnestelsel?', answers: ['7', '8', '9', '10'], correctIndex: 1, category: 'Wetenschap', difficulty: 'easy' },
  { id: 'wis-3', question: 'Welk orgaan pompt het bloed door het lichaam?', answers: ['Longen', 'Lever', 'Hart', 'Nier'], correctIndex: 2, category: 'Wetenschap', difficulty: 'easy' },
  { id: 'wis-4', question: 'Wat is de hardste natuurlijke stof?', answers: ['Staal', 'Diamant', 'Kwarts', 'Saffier'], correctIndex: 1, category: 'Wetenschap', difficulty: 'easy' },
  { id: 'wis-5', question: 'Wie ontwikkelde de relativiteitstheorie?', answers: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Max Planck'], correctIndex: 2, category: 'Wetenschap', difficulty: 'easy' },
  { id: 'wis-6', question: 'Welke planeet staat het dichtst bij de zon?', answers: ['Venus', 'Mercurius', 'Mars', 'Aarde'], correctIndex: 1, category: 'Wetenschap', difficulty: 'easy' },
  { id: 'wis-7', question: 'Hoeveel botten heeft een volwassen mens ongeveer?', answers: ['106', '156', '206', '256'], correctIndex: 2, category: 'Wetenschap', difficulty: 'medium' },
  { id: 'wis-8', question: 'Welk gas vormt het grootste deel van de atmosfeer?', answers: ['Zuurstof', 'Stikstof', 'CO2', 'Argon'], correctIndex: 1, category: 'Wetenschap', difficulty: 'medium' },
  { id: 'wis-9', question: 'Welk dier heeft blauw bloed?', answers: ['Octopus', 'Haai', 'Kwal', 'Paling'], correctIndex: 0, category: 'Wetenschap', difficulty: 'hard' },
  { id: 'wis-10', question: 'Wat is de pH-waarde van zuiver water?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Wetenschap', difficulty: 'medium' },
  { id: 'fil-1', question: 'Wie speelt Jack Sparrow in "Pirates of the Caribbean"?', answers: ['Orlando Bloom', 'Johnny Depp', 'Brad Pitt', 'Leonardo DiCaprio'], correctIndex: 1, category: 'Film & TV', difficulty: 'easy' },
  { id: 'fil-2', question: 'In welke film zegt men "Ik ben je vader"?', answers: ['Star Trek', 'Star Wars', 'Harry Potter', 'Lord of the Rings'], correctIndex: 1, category: 'Film & TV', difficulty: 'easy' },
  { id: 'fil-3', question: 'Hoeveel Harry Potter-films zijn er?', answers: ['6', '7', '8', '9'], correctIndex: 2, category: 'Film & TV', difficulty: 'easy' },
  { id: 'fil-4', question: 'Hoe heet de IJskoningin in de Disney-film?', answers: ['Anna', 'Elsa', 'Rapunzel', 'Merida'], correctIndex: 1, category: 'Film & TV', difficulty: 'easy' },
  { id: 'fil-5', question: 'Wie speelt Iron Man in het MCU?', answers: ['Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr.', 'Mark Ruffalo'], correctIndex: 2, category: 'Film & TV', difficulty: 'easy' },
  { id: 'mus-1', question: 'Welke band zong "Bohemian Rhapsody"?', answers: ['The Beatles', 'Led Zeppelin', 'Queen', 'Pink Floyd'], correctIndex: 2, category: 'Muziek', difficulty: 'easy' },
  { id: 'mus-2', question: 'Wie is de "King of Pop"?', answers: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Freddie Mercury'], correctIndex: 1, category: 'Muziek', difficulty: 'easy' },
  { id: 'mus-3', question: 'Welk instrument heeft 88 toetsen?', answers: ['Orgel', 'Accordeon', 'Piano', 'Keyboard'], correctIndex: 2, category: 'Muziek', difficulty: 'easy' },
  { id: 'mus-4', question: 'Welke Nederlandse DJ is wereldberoemd?', answers: ['Afrojack', 'Martin Garrix', 'Tiesto', 'Alle drie'], correctIndex: 3, category: 'Muziek', difficulty: 'easy' },
  { id: 'mus-5', question: 'Welk muziekgenre komt uit Jamaica?', answers: ['Blues', 'Reggae', 'Salsa', 'Samba'], correctIndex: 1, category: 'Muziek', difficulty: 'easy' },
  { id: 'all-1', question: 'Hoeveel dagen heeft een schrikkeljaar?', answers: ['364', '365', '366', '367'], correctIndex: 2, category: 'Algemene kennis', difficulty: 'easy' },
  { id: 'all-2', question: 'Welke kleur krijg je als je blauw en geel mengt?', answers: ['Rood', 'Groen', 'Oranje', 'Paars'], correctIndex: 1, category: 'Algemene kennis', difficulty: 'easy' },
  { id: 'all-3', question: 'Wat is de munt van Japan?', answers: ['Won', 'Yuan', 'Yen', 'Roepie'], correctIndex: 2, category: 'Algemene kennis', difficulty: 'easy' },
  { id: 'all-4', question: 'Op welke dag viert Nederland Koningsdag?', answers: ['30 april', '27 april', '5 mei', '4 mei'], correctIndex: 1, category: 'Algemene kennis', difficulty: 'easy' },
  { id: 'all-5', question: 'Wat is de officiele taal van Brazilie?', answers: ['Spaans', 'Portugees', 'Frans', 'Engels'], correctIndex: 1, category: 'Algemene kennis', difficulty: 'easy' },
  { id: 'nat-1', question: 'Welk dier is het grootst ter wereld?', answers: ['Olifant', 'Giraffe', 'Blauwe vinvis', 'Witte haai'], correctIndex: 2, category: 'Natuur', difficulty: 'easy' },
  { id: 'nat-2', question: 'Hoeveel poten heeft een spin?', answers: ['6', '8', '10', '12'], correctIndex: 1, category: 'Natuur', difficulty: 'easy' },
  { id: 'nat-3', question: 'Welke bloem is het symbool van Nederland?', answers: ['Roos', 'Zonnebloem', 'Tulp', 'Lelie'], correctIndex: 2, category: 'Natuur', difficulty: 'easy' },
  { id: 'nat-4', question: 'Wat is het snelste landdier?', answers: ['Leeuw', 'Jachtluipaard', 'Antilope', 'Windhond'], correctIndex: 1, category: 'Natuur', difficulty: 'easy' },
  { id: 'nat-5', question: 'Hoeveel harten heeft een octopus?', answers: ['1', '2', '3', '4'], correctIndex: 2, category: 'Natuur', difficulty: 'hard' },
  { id: 'tec-1', question: 'Wie heeft Apple opgericht?', answers: ['Bill Gates', 'Steve Jobs', 'Elon Musk', 'Jeff Bezos'], correctIndex: 1, category: 'Technologie', difficulty: 'easy' },
  { id: 'tec-2', question: 'Welk bedrijf ontwikkelde Android?', answers: ['Apple', 'Microsoft', 'Google', 'Samsung'], correctIndex: 2, category: 'Technologie', difficulty: 'easy' },
  { id: 'tec-3', question: 'Wat betekent "AI"?', answers: ['Automatische Intelligentie', 'Artificiele Intelligentie', 'Geavanceerde Integratie', 'Automatische Integratie'], correctIndex: 1, category: 'Technologie', difficulty: 'easy' },
  { id: 'tec-4', question: 'Welk sociaal netwerk is opgericht in 2004?', answers: ['Twitter', 'Instagram', 'Facebook', 'TikTok'], correctIndex: 2, category: 'Technologie', difficulty: 'easy' },
  { id: 'tec-5', question: 'Wie vond het World Wide Web uit?', answers: ['Steve Jobs', 'Bill Gates', 'Tim Berners-Lee', 'Mark Zuckerberg'], correctIndex: 2, category: 'Technologie', difficulty: 'medium' },
  { id: 'ess-1', question: 'Uit welk land komt pizza?', answers: ['Spanje', 'Frankrijk', 'Italie', 'Griekenland'], correctIndex: 2, category: 'Eten & Drinken', difficulty: 'easy' },
  { id: 'ess-2', question: 'Uit welk land komt sushi?', answers: ['China', 'Korea', 'Japan', 'Thailand'], correctIndex: 2, category: 'Eten & Drinken', difficulty: 'easy' },
  { id: 'ess-3', question: 'Welk land produceert de meeste koffie?', answers: ['Colombia', 'Ethiopie', 'Vietnam', 'Brazilie'], correctIndex: 3, category: 'Eten & Drinken', difficulty: 'medium' },
  { id: 'ess-4', question: 'Welke Nederlandse lekkernij wordt traditioneel bij Oud en Nieuw gegeten?', answers: ['Stroopwafels', 'Oliebollen', 'Poffertjes', 'Hagelslag'], correctIndex: 1, category: 'Eten & Drinken', difficulty: 'easy' },
  { id: 'ess-5', question: 'Welke groente laat je huilen bij het snijden?', answers: ['Knoflook', 'Ui', 'Radijs', 'Paprika'], correctIndex: 1, category: 'Eten & Drinken', difficulty: 'easy' },
];
let _usedIndices: Set<number> = new Set();
export function getRandomQuestion(): QuizQuestion { if (_usedIndices.size >= QUIZ_QUESTIONS_NL.length) { _usedIndices.clear(); } let idx: number; do { idx = Math.floor(Math.random() * QUIZ_QUESTIONS_NL.length); } while (_usedIndices.has(idx)); _usedIndices.add(idx); return QUIZ_QUESTIONS_NL[idx]; }
export function resetQuestions(): void { _usedIndices.clear(); }
