export interface QuizQuestion { id: string; question: string; answers: string[]; correctIndex: number; category: string; difficulty: 'easy' | 'medium' | 'hard'; }
export const QUIZ_QUESTIONS_PL: QuizQuestion[] = [
  { id: 'geo-1', question: 'Jaka jest stolica Australii?', answers: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-2', question: 'Ktora rzeka jest najdluzsza na swiecie?', answers: ['Amazonka', 'Nil', 'Jangcy', 'Missisipi'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-3', question: 'W jakim kraju znajduje sie Machu Picchu?', answers: ['Boliwia', 'Ekwador', 'Peru', 'Kolumbia'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-4', question: 'Ile wojewodztw ma Polska?', answers: ['14', '15', '16', '17'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-5', question: 'Jakie jest najmniejsze panstwo na swiecie?', answers: ['Monako', 'Watykan', 'San Marino', 'Liechtenstein'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-6', question: 'Ktory kraj ma ksztalt buta?', answers: ['Hiszpania', 'Grecja', 'Wlochy', 'Portugalia'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-7', question: 'Ktory kraj ma najwiecej mieszkancow?', answers: ['Indie', 'Chiny', 'USA', 'Indonezja'], correctIndex: 0, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-8', question: 'Jaka jest najwyzsza gora swiata?', answers: ['K2', 'Kangczendzonga', 'Mount Everest', 'Lhotse'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-9', question: 'Na jakim kontynencie lezy Egipt?', answers: ['Azja', 'Afryka', 'Europa', 'Ameryka Poludniowa'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-10', question: 'Jakie jest najwieksze panstwo swiata pod wzgledem powierzchni?', answers: ['Kanada', 'Chiny', 'USA', 'Rosja'], correctIndex: 3, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-11', question: 'Jaka jest najdluzsza rzeka w Polsce?', answers: ['Odra', 'Wisla', 'Bug', 'Warta'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-12', question: 'Jakie jest najglebsze jezioro w Polsce?', answers: ['Sniaridwy', 'Hancza', 'Mamry', 'Morskie Oko'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'his-1', question: 'W jakim roku upadl Mur Berlinski?', answers: ['1987', '1988', '1989', '1990'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'his-2', question: 'Kto byl pierwszym czlowiekiem na Ksiezycu?', answers: ['Buzz Aldrin', 'Neil Armstrong', 'Jurij Gagarin', 'John Glenn'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-3', question: 'Ktory lud zbudowal piramidy w Gizie?', answers: ['Rzymianie', 'Grecy', 'Egipcjanie', 'Persowie'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'his-4', question: 'Kiedy Kolumb dotarl do Ameryki?', answers: ['1482', '1492', '1502', '1512'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-5', question: 'Kto namalowal Mone Lise?', answers: ['Michal Aniol', 'Rafael', 'Leonardo da Vinci', 'Rembrandt'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'his-6', question: 'Kto wynalazl druk?', answers: ['Marcin Luter', 'Jan Gutenberg', 'Mikolaj Kopernik', 'Leonardo da Vinci'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'his-7', question: 'W jakim roku Polska odzyskala niepodleglosc?', answers: ['1916', '1917', '1918', '1919'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'his-8', question: 'Kto odkryl heliocentryzm?', answers: ['Galileusz', 'Mikolaj Kopernik', 'Johannes Kepler', 'Isaac Newton'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'spo-1', question: 'Ilu graczy liczy druzyna pilkarska na boisku?', answers: ['9', '10', '11', '12'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-2', question: 'Ile kolek ma symbol olimpijski?', answers: ['3', '4', '5', '6'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-3', question: 'Kto ma rekord na 100m?', answers: ['Carl Lewis', 'Usain Bolt', 'Tyson Gay', 'Yohan Blake'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-4', question: 'Ile kilometrow ma maraton (zaokraglony)?', answers: ['40 km', '42 km', '44 km', '46 km'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-5', question: 'Ktory klub ma najwiecej tytulow Ligi Mistrzow?', answers: ['FC Barcelona', 'AC Milan', 'Real Madryt', 'Bayern Monachium'], correctIndex: 2, category: 'Sport', difficulty: 'medium' },
  { id: 'spo-6', question: 'W jakim sporcie zdobywa sie "Birdie"?', answers: ['Badminton', 'Golf', 'Krykiet', 'Tenis'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-7', question: 'Jaki sport laczy plywanie, kolarstwo i bieganie?', answers: ['Biatlon', 'Triatlon', 'Pieciobo', 'Dziesieciobo'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-8', question: 'W jakiej dyscyplinie slynie Robert Lewandowski?', answers: ['Tenis', 'Pilka nozna', 'Siatkowka', 'Boks'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'wis-1', question: 'Jaki jest wzor chemiczny wody?', answers: ['H2O', 'CO2', 'O2', 'NaCl'], correctIndex: 0, category: 'Nauka', difficulty: 'easy' },
  { id: 'wis-2', question: 'Ile planet ma nasz uklad sloneczny?', answers: ['7', '8', '9', '10'], correctIndex: 1, category: 'Nauka', difficulty: 'easy' },
  { id: 'wis-3', question: 'Ktory organ pompuje krew w ciele?', answers: ['Pluca', 'Watroba', 'Serce', 'Nerka'], correctIndex: 2, category: 'Nauka', difficulty: 'easy' },
  { id: 'wis-4', question: 'Jaka jest najtwardsza substancja naturalna?', answers: ['Stal', 'Diament', 'Kwarc', 'Szafir'], correctIndex: 1, category: 'Nauka', difficulty: 'easy' },
  { id: 'wis-5', question: 'Kto opracowal teorie wzglednosci?', answers: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Max Planck'], correctIndex: 2, category: 'Nauka', difficulty: 'easy' },
  { id: 'wis-6', question: 'Jaka jest pH czystej wody?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Nauka', difficulty: 'medium' },
  { id: 'wis-7', question: 'Ile kosci ma dorosly czlowiek?', answers: ['106', '156', '206', '256'], correctIndex: 2, category: 'Nauka', difficulty: 'medium' },
  { id: 'wis-8', question: 'Kto odkryl radoaktywnosc?', answers: ['Albert Einstein', 'Maria Sklodowska-Curie', 'Niels Bohr', 'Ernest Rutherford'], correctIndex: 1, category: 'Nauka', difficulty: 'easy' },
  { id: 'fil-1', question: 'Kto gra Jacka Sparrowa w "Piratach z Karaibow"?', answers: ['Orlando Bloom', 'Johnny Depp', 'Brad Pitt', 'Leonardo DiCaprio'], correctIndex: 1, category: 'Film i TV', difficulty: 'easy' },
  { id: 'fil-2', question: 'Ile filmow o Harrym Potterze nakrecono?', answers: ['6', '7', '8', '9'], correctIndex: 2, category: 'Film i TV', difficulty: 'easy' },
  { id: 'fil-3', question: 'Jak nazywa sie Krolowa Sniegu w filmie Disneya?', answers: ['Anna', 'Elsa', 'Roszpunka', 'Merida'], correctIndex: 1, category: 'Film i TV', difficulty: 'easy' },
  { id: 'fil-4', question: 'Kto gra Iron Mana w MCU?', answers: ['Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr.', 'Mark Ruffalo'], correctIndex: 2, category: 'Film i TV', difficulty: 'easy' },
  { id: 'fil-5', question: 'Jaki polski serial jest oparty na grze "Wiedzmin"?', answers: ['Ranczo', 'Wiedzmin', 'Ojciec Mateusz', 'Klan'], correctIndex: 1, category: 'Film i TV', difficulty: 'easy' },
  { id: 'mus-1', question: 'Ktory zespol spiewal "Bohemian Rhapsody"?', answers: ['The Beatles', 'Led Zeppelin', 'Queen', 'Pink Floyd'], correctIndex: 2, category: 'Muzyka', difficulty: 'easy' },
  { id: 'mus-2', question: 'Kto jest "Krolem Popu"?', answers: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Freddie Mercury'], correctIndex: 1, category: 'Muzyka', difficulty: 'easy' },
  { id: 'mus-3', question: 'Ktory instrument ma 88 klawiszy?', answers: ['Organy', 'Akordeon', 'Fortepian', 'Keyboard'], correctIndex: 2, category: 'Muzyka', difficulty: 'easy' },
  { id: 'mus-4', question: 'Ktory polski kompozytor slynie z nokturno?', answers: ['Moniuszko', 'Chopin', 'Penderecki', 'Szymanowski'], correctIndex: 1, category: 'Muzyka', difficulty: 'easy' },
  { id: 'mus-5', question: 'Jaki gatunek muzyczny pochodzi z Jamajki?', answers: ['Blues', 'Reggae', 'Salsa', 'Samba'], correctIndex: 1, category: 'Muzyka', difficulty: 'easy' },
  { id: 'all-1', question: 'Ile dni ma rok przestepny?', answers: ['364', '365', '366', '367'], correctIndex: 2, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'all-2', question: 'Jaki kolor powstaje po zmieszaniu niebieskiego i zoltego?', answers: ['Czerwony', 'Zielony', 'Pomaranczowy', 'Fioletowy'], correctIndex: 1, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'all-3', question: 'Jaka jest waluta Japonii?', answers: ['Won', 'Juan', 'Jen', 'Rupia'], correctIndex: 2, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'all-4', question: 'Kiedy obchodzimy Swieto Niepodleglosci w Polsce?', answers: ['3 maja', '11 listopada', '1 maja', '15 sierpnia'], correctIndex: 1, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'all-5', question: 'Jaki jest oficjalny jezyk Brazylii?', answers: ['Hiszpanski', 'Portugalski', 'Francuski', 'Angielski'], correctIndex: 1, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'nat-1', question: 'Jakie jest najwieksze zwierze na swiecie?', answers: ['Slon', 'Zyrafa', 'Plettwal', 'Bialy rekin'], correctIndex: 2, category: 'Przyroda', difficulty: 'easy' },
  { id: 'nat-2', question: 'Ile nog ma pajak?', answers: ['6', '8', '10', '12'], correctIndex: 1, category: 'Przyroda', difficulty: 'easy' },
  { id: 'nat-3', question: 'Jakie jest najszybsze zwierze ladowe?', answers: ['Lew', 'Gepard', 'Antylopa', 'Chart'], correctIndex: 1, category: 'Przyroda', difficulty: 'easy' },
  { id: 'nat-4', question: 'Ile serc ma osmica?', answers: ['1', '2', '3', '4'], correctIndex: 2, category: 'Przyroda', difficulty: 'hard' },
  { id: 'nat-5', question: 'Jaki kwiat jest symbolem Holandii?', answers: ['Roza', 'Slonecznik', 'Tulipan', 'Lilia'], correctIndex: 2, category: 'Przyroda', difficulty: 'easy' },
  { id: 'tec-1', question: 'Kto zalozyl Apple?', answers: ['Bill Gates', 'Steve Jobs', 'Elon Musk', 'Jeff Bezos'], correctIndex: 1, category: 'Technologia', difficulty: 'easy' },
  { id: 'tec-2', question: 'Ktora firma opracowala Androida?', answers: ['Apple', 'Microsoft', 'Google', 'Samsung'], correctIndex: 2, category: 'Technologia', difficulty: 'easy' },
  { id: 'tec-3', question: 'Co oznacza "AI"?', answers: ['Automatyczna Inteligencja', 'Sztuczna Inteligencja', 'Zaawansowana Integracja', 'Automatyczna Integracja'], correctIndex: 1, category: 'Technologia', difficulty: 'easy' },
  { id: 'tec-4', question: 'Kto wynalazl World Wide Web?', answers: ['Steve Jobs', 'Bill Gates', 'Tim Berners-Lee', 'Mark Zuckerberg'], correctIndex: 2, category: 'Technologia', difficulty: 'medium' },
  { id: 'tec-5', question: 'Jaka polska gra zdobyla swiatowa slawe?', answers: ['Gothic', 'Wiedzmin 3', 'Doom', 'Halo'], correctIndex: 1, category: 'Technologia', difficulty: 'easy' },
  { id: 'ess-1', question: 'Z jakiego kraju pochodzi pizza?', answers: ['Hiszpania', 'Francja', 'Wlochy', 'Grecja'], correctIndex: 2, category: 'Jedzenie', difficulty: 'easy' },
  { id: 'ess-2', question: 'Z jakiego kraju pochodzi sushi?', answers: ['Chiny', 'Korea', 'Japonia', 'Tajlandia'], correctIndex: 2, category: 'Jedzenie', difficulty: 'easy' },
  { id: 'ess-3', question: 'Jakie polskie danie jest typowe na Wigilie?', answers: ['Bigos', 'Barszcz z uszkami', 'Zurek', 'Rosol'], correctIndex: 1, category: 'Jedzenie', difficulty: 'easy' },
  { id: 'ess-4', question: 'Ktory kraj produkuje najwiecej kawy?', answers: ['Kolumbia', 'Etiopia', 'Wietnam', 'Brazylia'], correctIndex: 3, category: 'Jedzenie', difficulty: 'medium' },
  { id: 'ess-5', question: 'Jaka warzywo powoduje lzawienie przy krojeniu?', answers: ['Czosnek', 'Cebula', 'Rzodkiewka', 'Papryka'], correctIndex: 1, category: 'Jedzenie', difficulty: 'easy' },
  { id: 'xq-1', question: 'Jaka jest stolica Polski?', answers: ['Krakow', 'Warszawa', 'Wroclaw', 'Gdansk'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-2', question: 'Nad jakim morzem lezy Polska?', answers: ['Morzem Czarnym', 'Morzem Srodziemnym', 'Morzem Baltyckim', 'Morzem Polnocnym'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-3', question: 'Ktora rzeka jest najdluzsza w Polsce?', answers: ['Odra', 'Warta', 'Wisla', 'Bug'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-4', question: 'Jaki jest najwyzszy szczyt Polski?', answers: ['Rysy', 'Sniezka', 'Babia Gora', 'Giewont'], correctIndex: 0, category: 'Geografia', difficulty: 'medium' },
  { id: 'xq-5', question: 'Stolica Francji to?', answers: ['Lyon', 'Marsylia', 'Paryz', 'Nicea'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-6', question: 'Ktore panstwo jest najwieksze pod wzgledem powierzchni?', answers: ['Kanada', 'Chiny', 'USA', 'Rosja'], correctIndex: 3, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-7', question: 'Na ktorym kontynencie lezy Egipt?', answers: ['Azja', 'Afryka', 'Europa', 'Ameryka Poludniowa'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-8', question: 'Jakie jest najwieksze jezioro w Polsce?', answers: ['Mamry', 'Sniardwy', 'Niegocin', 'Wigry'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'xq-9', question: 'Stolica Hiszpanii to?', answers: ['Barcelona', 'Sewilla', 'Madryt', 'Walencja'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-10', question: 'Ktore z tych miast lezy nad Wisla?', answers: ['Wroclaw', 'Poznan', 'Krakow', 'Szczecin'], correctIndex: 2, category: 'Geografia', difficulty: 'medium' },
  { id: 'xq-11', question: 'Jaka pustynia jest najwieksza na swiecie (goraca)?', answers: ['Gobi', 'Sahara', 'Kalahari', 'Atakama'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'xq-12', question: 'Z iloma panstwami graniczy Polska?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Geografia', difficulty: 'medium' },
  { id: 'xq-13', question: 'Stolica Japonii to?', answers: ['Osaka', 'Kioto', 'Tokio', 'Nagoja'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-14', question: 'Najwyzsza gora swiata to?', answers: ['K2', 'Mount Everest', 'Kangczendzonga', 'Lhotse'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-15', question: 'W ktorym kraju znajduja sie piramidy w Gizie?', answers: ['Meksyk', 'Egipt', 'Sudan', 'Peru'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-16', question: 'Ktore morze jest najbardziej zasolone?', answers: ['Morze Martwe', 'Morze Czerwone', 'Morze Czarne', 'Morze Karaibskie'], correctIndex: 0, category: 'Geografia', difficulty: 'hard' },
  { id: 'xq-17', question: 'Stolica Niemiec to?', answers: ['Monachium', 'Hamburg', 'Berlin', 'Frankfurt'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-18', question: 'Ktora rzeka przeplywa przez Krakow?', answers: ['Odra', 'Warta', 'Wisla', 'San'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'xq-19', question: 'Jakie jest najludniejsze miasto na swiecie?', answers: ['Delhi', 'Szanghaj', 'Tokio', 'Sao Paulo'], correctIndex: 2, category: 'Geografia', difficulty: 'hard' },
  { id: 'xq-20', question: 'W ktorym roku Polska odzyskala niepodleglosc?', answers: ['1918', '1920', '1945', '1989'], correctIndex: 0, category: 'Historia', difficulty: 'easy' },
  { id: 'xq-21', question: 'Kto byl pierwszym krolem Polski?', answers: ['Mieszko I', 'Boleslaw Chrobry', 'Kazimierz Wielki', 'Wladyslaw Lokietek'], correctIndex: 1, category: 'Historia', difficulty: 'medium' },
  { id: 'xq-22', question: 'W ktorym roku rozpoczela sie II wojna swiatowa?', answers: ['1938', '1939', '1940', '1941'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'xq-23', question: 'Kto byl pierwszym czlowiekiem na Ksiezycu?', answers: ['Buzz Aldrin', 'Jurij Gagarin', 'Neil Armstrong', 'Michael Collins'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'xq-24', question: 'W ktorym roku upadl mur berlinski?', answers: ['1987', '1989', '1991', '1985'], correctIndex: 1, category: 'Historia', difficulty: 'medium' },
  { id: 'xq-25', question: 'Ktory polski papiez nosil imie Jan Pawel II?', answers: ['Stefan Wyszynski', 'Karol Wojtyla', 'Jozef Glemp', 'Adam Sapieha'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'xq-26', question: 'W ktorym roku doszlo do chrztu Polski?', answers: ['966', '1000', '1025', '1138'], correctIndex: 0, category: 'Historia', difficulty: 'medium' },
  { id: 'xq-27', question: 'Kto dowodzil polskim wojskiem w bitwie pod Grunwaldem?', answers: ['Wladyslaw Jagiello', 'Kazimierz Jagiellonczyk', 'Boleslaw Krzywousty', 'Jan III Sobieski'], correctIndex: 0, category: 'Historia', difficulty: 'medium' },
  { id: 'xq-28', question: 'W ktorym roku odbyla sie bitwa pod Grunwaldem?', answers: ['1385', '1410', '1444', '1466'], correctIndex: 1, category: 'Historia', difficulty: 'medium' },
  { id: 'xq-29', question: 'Kto byl przywodca zwiazku Solidarnosc?', answers: ['Wojciech Jaruzelski', 'Lech Walesa', 'Tadeusz Mazowiecki', 'Bronislaw Geremek'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'xq-30', question: 'Ktora cywilizacja zbudowala Machu Picchu?', answers: ['Majowie', 'Aztekowie', 'Inkowie', 'Olmekowie'], correctIndex: 2, category: 'Historia', difficulty: 'medium' },
  { id: 'xq-31', question: 'Kto namalowal Mona Lise?', answers: ['Michal Aniol', 'Rafael', 'Leonardo da Vinci', 'Botticelli'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'xq-32', question: 'W ktorym roku zatonal Titanic?', answers: ['1905', '1912', '1918', '1921'], correctIndex: 1, category: 'Historia', difficulty: 'easy' },
  { id: 'xq-33', question: 'Kto byl pierwszym cesarzem Rzymu?', answers: ['Juliusz Cezar', 'Oktawian August', 'Neron', 'Kaligula'], correctIndex: 1, category: 'Historia', difficulty: 'hard' },
  { id: 'xq-34', question: 'Konstytucja 3 Maja zostala uchwalona w roku?', answers: ['1772', '1791', '1795', '1807'], correctIndex: 1, category: 'Historia', difficulty: 'medium' },
  { id: 'xq-35', question: 'Jan III Sobieski odznaczyl sie zwyciestwem w bitwie pod?', answers: ['Wieden', 'Cecora', 'Chocim', 'Kluszyn'], correctIndex: 0, category: 'Historia', difficulty: 'medium' },
  { id: 'xq-36', question: 'Ktory wladca przeniosl stolice Polski z Krakowa do Warszawy?', answers: ['Zygmunt III Waza', 'Stefan Batory', 'Zygmunt August', 'Wladyslaw IV'], correctIndex: 0, category: 'Historia', difficulty: 'hard' },
  { id: 'xq-37', question: 'W ktorym roku Polska wstapila do Unii Europejskiej?', answers: ['2000', '2002', '2004', '2007'], correctIndex: 2, category: 'Historia', difficulty: 'easy' },
  { id: 'xq-38', question: 'Ile graczy jednej druzyny jest na boisku w pilce noznej?', answers: ['9', '10', '11', '12'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'xq-39', question: 'Co ile lat odbywaja sie letnie igrzyska olimpijskie?', answers: ['2 lata', '3 lata', '4 lata', '5 lat'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'xq-40', question: 'Ktory polski skoczek narciarski zdobyl 4 zlote medale olimpijskie?', answers: ['Kamil Stoch', 'Adam Malysz', 'Piotr Zyla', 'Dawid Kubacki'], correctIndex: 0, category: 'Sport', difficulty: 'medium' },
  { id: 'xq-41', question: 'W jakim sporcie znana jest Iga Swiatek?', answers: ['Siatkowka', 'Tenis', 'Lekkoatletyka', 'Plywanie'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'xq-42', question: 'Ile punktow warte jest trafienie zza linii w koszykowce (rzut za trzy)?', answers: ['1', '2', '3', '4'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'xq-43', question: 'W ktorym kraju odbyly sie igrzyska olimpijskie w 2021 (Tokio)?', answers: ['Chiny', 'Korea', 'Japonia', 'Brazylia'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'xq-44', question: 'Robert Lewandowski gral w klubie Bayern Monachium na pozycji?', answers: ['Bramkarz', 'Obronca', 'Pomocnik', 'Napastnik'], correctIndex: 3, category: 'Sport', difficulty: 'easy' },
  { id: 'xq-45', question: 'Ile minut trwa standardowy mecz pilki noznej (bez doliczonego czasu)?', answers: ['60', '80', '90', '100'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'xq-46', question: 'Ktora reprezentacja zdobyla mistrzostwo swiata w pilce noznej w 2018 roku?', answers: ['Niemcy', 'Francja', 'Chorwacja', 'Brazylia'], correctIndex: 1, category: 'Sport', difficulty: 'medium' },
  { id: 'xq-47', question: 'W jakim sporcie uzywa sie kija i krazka na lodzie?', answers: ['Curling', 'Hokej na lodzie', 'Lyzwiarstwo', 'Bobsleje'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'xq-48', question: 'Ile zawodnikow ma druzyna siatkowki na boisku?', answers: ['5', '6', '7', '8'], correctIndex: 1, category: 'Sport', difficulty: 'medium' },
  { id: 'xq-49', question: 'Kto jest uznawany za najlepszego kierowce F1 z 7 tytulami (wraz z Schumacherem)?', answers: ['Sebastian Vettel', 'Ayrton Senna', 'Lewis Hamilton', 'Fernando Alonso'], correctIndex: 2, category: 'Sport', difficulty: 'medium' },
  { id: 'xq-50', question: 'Ktory tenisowy turniej Wielkiego Szlema odbywa sie na trawie?', answers: ['Roland Garros', 'US Open', 'Wimbledon', 'Australian Open'], correctIndex: 2, category: 'Sport', difficulty: 'medium' },
  { id: 'xq-51', question: 'Maraton ma dlugosc okolo?', answers: ['21 km', '42 km', '50 km', '100 km'], correctIndex: 1, category: 'Sport', difficulty: 'medium' },
  { id: 'xq-52', question: 'Justyna Kowalczyk byla mistrzynia w jakiej dyscyplinie?', answers: ['Biathlon', 'Biegi narciarskie', 'Lyzwiarstwo', 'Snowboard'], correctIndex: 1, category: 'Sport', difficulty: 'medium' },
  { id: 'xq-53', question: 'Ktory kraj wygral najwiecej mistrzostw swiata w pilce noznej?', answers: ['Niemcy', 'Wlochy', 'Brazylia', 'Argentyna'], correctIndex: 2, category: 'Sport', difficulty: 'medium' },
  { id: 'xq-54', question: 'W boksie waga ciezka oznacza zawodnikow?', answers: ['Najlzejszych', 'Najciezszych', 'Sredniej wagi', 'Juniorow'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'xq-55', question: 'Jaki gaz jest najwazniejszy dla oddychania czlowieka?', answers: ['Azot', 'Tlen', 'Dwutlenek wegla', 'Wodor'], correctIndex: 1, category: 'Nauka', difficulty: 'easy' },
  { id: 'xq-56', question: 'Ile planet jest w Ukladzie Slonecznym?', answers: ['7', '8', '9', '10'], correctIndex: 1, category: 'Nauka', difficulty: 'easy' },
  { id: 'xq-57', question: 'Jaki jest symbol chemiczny zlota?', answers: ['Zo', 'Au', 'Ag', 'Gd'], correctIndex: 1, category: 'Nauka', difficulty: 'medium' },
  { id: 'xq-58', question: 'Ktora planeta jest najblizej Slonca?', answers: ['Wenus', 'Mars', 'Merkury', 'Ziemia'], correctIndex: 2, category: 'Nauka', difficulty: 'easy' },
  { id: 'xq-59', question: 'Ile kosci ma doroslo czlowiek?', answers: ['106', '186', '206', '256'], correctIndex: 2, category: 'Nauka', difficulty: 'medium' },
  { id: 'xq-60', question: 'Co mierzy termometr?', answers: ['Cisnienie', 'Temperature', 'Wilgotnosc', 'Wage'], correctIndex: 1, category: 'Nauka', difficulty: 'easy' },
  { id: 'xq-61', question: 'Jaki jest wzor chemiczny wody?', answers: ['CO2', 'H2O', 'O2', 'NaCl'], correctIndex: 1, category: 'Nauka', difficulty: 'easy' },
  { id: 'xq-62', question: 'Kto sformulowal teorie wzglednosci?', answers: ['Isaac Newton', 'Albert Einstein', 'Niels Bohr', 'Galileo Galilei'], correctIndex: 1, category: 'Nauka', difficulty: 'easy' },
  { id: 'xq-63', question: 'Jaka jest predkosc swiatla w prozni (w przyblizeniu)?', answers: ['300 km/s', '3 000 km/s', '30 000 km/s', '300 000 km/s'], correctIndex: 3, category: 'Nauka', difficulty: 'hard' },
  { id: 'xq-64', question: 'Ktory organ pompuje krew w organizmie?', answers: ['Watroba', 'Pluca', 'Serce', 'Nerki'], correctIndex: 2, category: 'Nauka', difficulty: 'easy' },
  { id: 'xq-65', question: 'Jaki pierwiastek ma symbol O?', answers: ['Zloto', 'Tlen', 'Osm', 'Olow'], correctIndex: 1, category: 'Nauka', difficulty: 'easy' },
  { id: 'xq-66', question: 'Ktora polska noblistka odkryla polon i rad?', answers: ['Maria Sklodowska-Curie', 'Wislawa Szymborska', 'Olga Tokarczuk', 'Irena Sendlerowa'], correctIndex: 0, category: 'Nauka', difficulty: 'easy' },
  { id: 'xq-67', question: 'Jaka jest jednostka sily w ukladzie SI?', answers: ['Dzul', 'Niuton', 'Wat', 'Paskal'], correctIndex: 1, category: 'Nauka', difficulty: 'medium' },
  { id: 'xq-68', question: 'Ile chromosomow ma czlowiek?', answers: ['23', '44', '46', '48'], correctIndex: 2, category: 'Nauka', difficulty: 'hard' },
  { id: 'xq-69', question: 'W jakiej temperaturze woda wrze (na poziomie morza)?', answers: ['90 stopni C', '100 stopni C', '110 stopni C', '120 stopni C'], correctIndex: 1, category: 'Nauka', difficulty: 'easy' },
  { id: 'xq-70', question: 'Ktory naukowiec sformulowal prawo powszechnego ciazenia?', answers: ['Einstein', 'Newton', 'Kopernik', 'Kepler'], correctIndex: 1, category: 'Nauka', difficulty: 'medium' },
  { id: 'xq-71', question: 'Mikolaj Kopernik twierdzil, ze w centrum znajduje sie?', answers: ['Ziemia', 'Slonce', 'Ksiezyc', 'Mars'], correctIndex: 1, category: 'Nauka', difficulty: 'easy' },
  { id: 'xq-72', question: 'Jaki proces zachodzi w roslinach przy udziale swiatla?', answers: ['Oddychanie', 'Fotosynteza', 'Fermentacja', 'Transpiracja'], correctIndex: 1, category: 'Nauka', difficulty: 'medium' },
  { id: 'xq-73', question: 'Kto wyrezyserowal film Titanic z 1997 roku?', answers: ['Steven Spielberg', 'James Cameron', 'Ridley Scott', 'Christopher Nolan'], correctIndex: 1, category: 'Film i TV', difficulty: 'medium' },
  { id: 'xq-74', question: 'W ktorym filmie pada slawne zdanie \'May the Force be with you\'?', answers: ['Star Trek', 'Gwiezdne wojny', 'Matrix', 'Avatar'], correctIndex: 1, category: 'Film i TV', difficulty: 'easy' },
  { id: 'xq-75', question: 'Kto gra glowna role w serii filmow o Jamesie Bondzie jako agent 007 (oryginalny numer)?', answers: ['Bohater o numerze 007', 'Bohater o numerze 006', 'Bohater o numerze 008', 'Bohater o numerze 009'], correctIndex: 0, category: 'Film i TV', difficulty: 'easy' },
  { id: 'xq-76', question: 'Jak nazywa sie czarodziej z serii ksiazek i filmow J.K. Rowling?', answers: ['Frodo', 'Harry Potter', 'Gandalf', 'Percy Jackson'], correctIndex: 1, category: 'Film i TV', difficulty: 'easy' },
  { id: 'xq-77', question: 'Ktory polski rezyser zdobyl Oscara za film Pianista?', answers: ['Andrzej Wajda', 'Roman Polanski', 'Krzysztof Kieslowski', 'Jerzy Hoffman'], correctIndex: 1, category: 'Film i TV', difficulty: 'medium' },
  { id: 'xq-78', question: 'W ktorym serialu pojawia sie postac Waltera White\'a?', answers: ['Breaking Bad', 'The Wire', 'Dexter', 'Narcos'], correctIndex: 0, category: 'Film i TV', difficulty: 'medium' },
  { id: 'xq-79', question: 'Jak nazywa sie lew w filmie Krol Lew?', answers: ['Mufasa', 'Simba', 'Scar', 'Nala'], correctIndex: 1, category: 'Film i TV', difficulty: 'easy' },
  { id: 'xq-80', question: 'Ktory film animowany opowiada o zabawkach, ktore ozywaja?', answers: ['Shrek', 'Toy Story', 'Madagaskar', 'Auta'], correctIndex: 1, category: 'Film i TV', difficulty: 'easy' },
  { id: 'xq-81', question: 'W jakim serialu HBO wystepuja rody walczace o Zelazny Tron?', answers: ['Wikingowie', 'Gra o tron', 'Rzym', 'Korona'], correctIndex: 1, category: 'Film i TV', difficulty: 'easy' },
  { id: 'xq-82', question: 'Kto rezyserowal film Incepcja?', answers: ['Christopher Nolan', 'Denis Villeneuve', 'David Fincher', 'Martin Scorsese'], correctIndex: 0, category: 'Film i TV', difficulty: 'medium' },
  { id: 'xq-83', question: 'Ktora polska seria filmowa opowiada o przygodach Sary?', answers: ['Kiler', 'Sara', 'Psy', 'Vabank'], correctIndex: 1, category: 'Film i TV', difficulty: 'hard' },
  { id: 'xq-84', question: 'Jak nazywa sie zielony ogr z filmu wytworni DreamWorks?', answers: ['Shrek', 'Hulk', 'Yoda', 'Grinch'], correctIndex: 0, category: 'Film i TV', difficulty: 'easy' },
  { id: 'xq-85', question: 'Ktory aktor zagral Jacka Dawsona w filmie Titanic?', answers: ['Brad Pitt', 'Leonardo DiCaprio', 'Johnny Depp', 'Tom Cruise'], correctIndex: 1, category: 'Film i TV', difficulty: 'medium' },
  { id: 'xq-86', question: 'Polski serial Czterej pancerni i pies opowiada o czasach?', answers: ['I wojny swiatowej', 'II wojny swiatowej', 'Sredniowiecza', 'Wspolczesnosci'], correctIndex: 1, category: 'Film i TV', difficulty: 'medium' },
  { id: 'xq-87', question: 'W jakim filmie wystepuje postac o imieniu Forrest?', answers: ['Rain Man', 'Forrest Gump', 'Zielona mila', 'Skazani na Shawshank'], correctIndex: 1, category: 'Film i TV', difficulty: 'medium' },
  { id: 'xq-88', question: 'Ile strun ma standardowa gitara?', answers: ['4', '5', '6', '7'], correctIndex: 2, category: 'Muzyka', difficulty: 'easy' },
  { id: 'xq-89', question: 'Ktory polski kompozytor napisal slynne mazurki i polonezy?', answers: ['Stanislaw Moniuszko', 'Fryderyk Chopin', 'Karol Szymanowski', 'Witold Lutoslawski'], correctIndex: 1, category: 'Muzyka', difficulty: 'easy' },
  { id: 'xq-90', question: 'Jak nazywal sie zespol, ktorego czlonkiem byl John Lennon?', answers: ['The Rolling Stones', 'The Beatles', 'Queen', 'Pink Floyd'], correctIndex: 1, category: 'Muzyka', difficulty: 'easy' },
  { id: 'xq-91', question: 'Kto byl wokalista zespolu Queen?', answers: ['Freddie Mercury', 'Mick Jagger', 'David Bowie', 'Elton John'], correctIndex: 0, category: 'Muzyka', difficulty: 'easy' },
  { id: 'xq-92', question: 'Ile klawiszy ma standardowy fortepian?', answers: ['66', '76', '88', '98'], correctIndex: 2, category: 'Muzyka', difficulty: 'hard' },
  { id: 'xq-93', question: 'Ktory instrument nalezy do detych?', answers: ['Skrzypce', 'Pianino', 'Trabka', 'Bebny'], correctIndex: 2, category: 'Muzyka', difficulty: 'easy' },
  { id: 'xq-94', question: 'Kto spiewal piosenke Thriller?', answers: ['Prince', 'Michael Jackson', 'Stevie Wonder', 'Lionel Richie'], correctIndex: 1, category: 'Muzyka', difficulty: 'easy' },
  { id: 'xq-95', question: 'Czerwone Gitary to slynny polski zespol z jakiej dekady (poczatki)?', answers: ['Lata 40.', 'Lata 50.', 'Lata 60.', 'Lata 80.'], correctIndex: 2, category: 'Muzyka', difficulty: 'hard' },
  { id: 'xq-96', question: 'Jak nazywa sie najwyzszy glos kobiecy?', answers: ['Alt', 'Sopran', 'Mezzosopran', 'Tenor'], correctIndex: 1, category: 'Muzyka', difficulty: 'medium' },
  { id: 'xq-97', question: 'Ktory instrument ma czarne i biale klawisze?', answers: ['Gitara', 'Skrzypce', 'Pianino', 'Flet'], correctIndex: 2, category: 'Muzyka', difficulty: 'easy' },
  { id: 'xq-98', question: 'Kto skomponowal IX Symfonie z \'Oda do radosci\'?', answers: ['Mozart', 'Beethoven', 'Bach', 'Vivaldi'], correctIndex: 1, category: 'Muzyka', difficulty: 'medium' },
  { id: 'xq-99', question: 'Z jakiego kraju pochodzi zespol ABBA?', answers: ['Norwegia', 'Szwecja', 'Dania', 'Finlandia'], correctIndex: 1, category: 'Muzyka', difficulty: 'medium' },
  { id: 'xq-100', question: 'Jaki gatunek muzyki reprezentuje Bob Marley?', answers: ['Jazz', 'Reggae', 'Blues', 'Country'], correctIndex: 1, category: 'Muzyka', difficulty: 'medium' },
  { id: 'xq-101', question: 'Konkurs Chopinowski odbywa sie w jakim miescie?', answers: ['Krakow', 'Warszawa', 'Gdansk', 'Wroclaw'], correctIndex: 1, category: 'Muzyka', difficulty: 'medium' },
  { id: 'xq-102', question: 'Ile dni ma rok przestepny?', answers: ['364', '365', '366', '367'], correctIndex: 2, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'xq-103', question: 'Jakiego koloru nie ma na fladze Polski?', answers: ['Bialy', 'Czerwony', 'Niebieski', 'Wszystkie sa'], correctIndex: 2, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'xq-104', question: 'Ile minut ma godzina?', answers: ['30', '60', '90', '120'], correctIndex: 1, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'xq-105', question: 'Jaka jest waluta Polski?', answers: ['Euro', 'Korona', 'Zloty', 'Forint'], correctIndex: 2, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'xq-106', question: 'Ile kontynentow jest na Ziemi?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'xq-107', question: 'Ktory dzien tygodnia nastepuje po srodzie?', answers: ['Wtorek', 'Czwartek', 'Piatek', 'Poniedzialek'], correctIndex: 1, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'xq-108', question: 'Ile sekund ma minuta?', answers: ['30', '60', '100', '120'], correctIndex: 1, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'xq-109', question: 'Jaki kolor powstaje z polaczenia niebieskiego i zoltego?', answers: ['Pomaranczowy', 'Zielony', 'Fioletowy', 'Brazowy'], correctIndex: 1, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'xq-110', question: 'Ile zer ma milion?', answers: ['5', '6', '7', '9'], correctIndex: 1, category: 'Wiedza ogolna', difficulty: 'medium' },
  { id: 'xq-111', question: 'Jak nazywa sie hejnal grany z wiezy w Krakowie?', answers: ['Hejnal mariacki', 'Hejnal wawelski', 'Hejnal sukienniczy', 'Hejnal kazimierski'], correctIndex: 0, category: 'Wiedza ogolna', difficulty: 'medium' },
  { id: 'xq-112', question: 'Ile boku ma trojkat?', answers: ['2', '3', '4', '5'], correctIndex: 1, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'xq-113', question: 'Jaki jest symbol narodowy Polski (zwierze w godle)?', answers: ['Lew', 'Orzel', 'Niedzwiedz', 'Zubr'], correctIndex: 1, category: 'Wiedza ogolna', difficulty: 'easy' },
  { id: 'xq-114', question: 'Ile miesiecy w roku ma 31 dni?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Wiedza ogolna', difficulty: 'hard' },
  { id: 'xq-115', question: 'Jaki ksztalt ma znak STOP?', answers: ['Kolo', 'Trojkat', 'Osmiokat', 'Kwadrat'], correctIndex: 2, category: 'Wiedza ogolna', difficulty: 'medium' },
  { id: 'xq-116', question: 'Jakie jest najwieksze zwierze na Ziemi?', answers: ['Slon afrykanski', 'Pletwal blekitny', 'Zyrafa', 'Rekin wielorybi'], correctIndex: 1, category: 'Przyroda', difficulty: 'easy' },
  { id: 'xq-117', question: 'Ile nog ma pajak?', answers: ['6', '8', '10', '12'], correctIndex: 1, category: 'Przyroda', difficulty: 'easy' },
  { id: 'xq-118', question: 'Ktore zwierze jest najszybsze na ladzie?', answers: ['Lew', 'Gepard', 'Antylopa', 'Kon'], correctIndex: 1, category: 'Przyroda', difficulty: 'easy' },
  { id: 'xq-119', question: 'Jak nazywa sie najwiekszy ptak nielotny?', answers: ['Pingwin', 'Strus', 'Emu', 'Kazuar'], correctIndex: 1, category: 'Przyroda', difficulty: 'medium' },
  { id: 'xq-120', question: 'Ktore zwierze jest symbolem Puszczy Bialowieskiej?', answers: ['Los', 'Zubr', 'Jelen', 'Dzik'], correctIndex: 1, category: 'Przyroda', difficulty: 'medium' },
  { id: 'xq-121', question: 'Jaki owad produkuje miod?', answers: ['Osa', 'Pszczola', 'Trzmiel', 'Szerszen'], correctIndex: 1, category: 'Przyroda', difficulty: 'easy' },
  { id: 'xq-122', question: 'Ktore drzewo gubi liscie na zime?', answers: ['Sosna', 'Swierk', 'Dab', 'Jodla'], correctIndex: 2, category: 'Przyroda', difficulty: 'easy' },
  { id: 'xq-123', question: 'Ile serc ma osmiornica?', answers: ['1', '2', '3', '4'], correctIndex: 2, category: 'Przyroda', difficulty: 'hard' },
  { id: 'xq-124', question: 'Jaki jest najwiekszy gatunek rekina?', answers: ['Rekin bialy', 'Rekin tygrysi', 'Rekin wielorybi', 'Mlot'], correctIndex: 2, category: 'Przyroda', difficulty: 'medium' },
  { id: 'xq-125', question: 'Ktory ptak potrafi naśladowac ludzka mowe?', answers: ['Wrobel', 'Papuga', 'Golab', 'Sikorka'], correctIndex: 1, category: 'Przyroda', difficulty: 'easy' },
  { id: 'xq-126', question: 'Jaka roslina jest miesozerna?', answers: ['Roza', 'Muchołowka', 'Tulipan', 'Slonecznik'], correctIndex: 1, category: 'Przyroda', difficulty: 'medium' },
  { id: 'xq-127', question: 'Ile lat moze dozyc zolw olbrzymi?', answers: ['Okolo 20', 'Okolo 50', 'Ponad 100', 'Okolo 10'], correctIndex: 2, category: 'Przyroda', difficulty: 'medium' },
  { id: 'xq-128', question: 'Co oznacza skrot \'www\'?', answers: ['World Wide Web', 'Web World Wide', 'Wide Web World', 'World Web Wide'], correctIndex: 0, category: 'Technologia', difficulty: 'easy' },
  { id: 'xq-129', question: 'Kto jest wspolzalozycielem firmy Microsoft?', answers: ['Steve Jobs', 'Bill Gates', 'Mark Zuckerberg', 'Elon Musk'], correctIndex: 1, category: 'Technologia', difficulty: 'easy' },
  { id: 'xq-130', question: 'Jaka firma produkuje iPhone\'a?', answers: ['Samsung', 'Apple', 'Huawei', 'Nokia'], correctIndex: 1, category: 'Technologia', difficulty: 'easy' },
  { id: 'xq-131', question: 'Co oznacza skrot \'CPU\' w komputerze?', answers: ['Procesor', 'Karta graficzna', 'Pamiec', 'Dysk twardy'], correctIndex: 0, category: 'Technologia', difficulty: 'medium' },
  { id: 'xq-132', question: 'Ktora platforma jest serwisem do udostepniania filmow online?', answers: ['Spotify', 'YouTube', 'Twitter', 'WhatsApp'], correctIndex: 1, category: 'Technologia', difficulty: 'easy' },
  { id: 'xq-133', question: 'W ktorym roku Apple zaprezentowal pierwszego iPhone\'a?', answers: ['2005', '2007', '2009', '2011'], correctIndex: 1, category: 'Technologia', difficulty: 'hard' },
];
let _usedIndices: Set<number> = new Set();
export function getRandomQuestion(): QuizQuestion { if (_usedIndices.size >= QUIZ_QUESTIONS_PL.length) { _usedIndices.clear(); } let idx: number; do { idx = Math.floor(Math.random() * QUIZ_QUESTIONS_PL.length); } while (_usedIndices.has(idx)); _usedIndices.add(idx); return QUIZ_QUESTIONS_PL[idx]; }
export function resetQuestions(): void { _usedIndices.clear(); }
