export interface QuizQuestion { id: string; question: string; answers: string[]; correctIndex: number; category: string; difficulty: 'easy' | 'medium' | 'hard'; }

export const QUIZ_QUESTIONS_FR: QuizQuestion[] = [
  // === Geographie (20) ===
  { id: 'geo-1', question: 'Quelle est la capitale de l\'Australie?', answers: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, category: 'Geographie', difficulty: 'medium' },
  { id: 'geo-2', question: 'Quel est le fleuve le plus long du monde?', answers: ['Amazone', 'Nil', 'Yangtse', 'Mississippi'], correctIndex: 1, category: 'Geographie', difficulty: 'easy' },
  { id: 'geo-3', question: 'Dans quel pays se trouve le Machu Picchu?', answers: ['Bolivie', 'Equateur', 'Perou', 'Colombie'], correctIndex: 2, category: 'Geographie', difficulty: 'easy' },
  { id: 'geo-4', question: 'Combien de regions a la France metropolitaine?', answers: ['11', '12', '13', '14'], correctIndex: 2, category: 'Geographie', difficulty: 'easy' },
  { id: 'geo-5', question: 'Quel est le plus petit pays du monde?', answers: ['Monaco', 'Vatican', 'Saint-Marin', 'Liechtenstein'], correctIndex: 1, category: 'Geographie', difficulty: 'medium' },
  { id: 'geo-6', question: 'Quel pays a la forme d\'une botte?', answers: ['Espagne', 'Grece', 'Italie', 'Portugal'], correctIndex: 2, category: 'Geographie', difficulty: 'easy' },
  { id: 'geo-7', question: 'Quel pays a le plus d\'habitants?', answers: ['Inde', 'Chine', 'USA', 'Indonesie'], correctIndex: 0, category: 'Geographie', difficulty: 'medium' },
  { id: 'geo-8', question: 'Quel est le plus grand desert de la Terre?', answers: ['Sahara', 'Gobi', 'Antarctique', 'Kalahari'], correctIndex: 2, category: 'Geographie', difficulty: 'hard' },
  { id: 'geo-9', question: 'Sur quel continent se trouve l\'Egypte?', answers: ['Asie', 'Afrique', 'Europe', 'Amerique du Sud'], correctIndex: 1, category: 'Geographie', difficulty: 'easy' },
  { id: 'geo-10', question: 'Quelle ville est surnommee la "Grosse Pomme"?', answers: ['Los Angeles', 'Chicago', 'New York', 'Boston'], correctIndex: 2, category: 'Geographie', difficulty: 'easy' },
  { id: 'geo-11', question: 'Quelle est la capitale du Canada?', answers: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'], correctIndex: 3, category: 'Geographie', difficulty: 'medium' },
  { id: 'geo-12', question: 'Quelle est la montagne la plus haute du monde?', answers: ['K2', 'Kangchenjunga', 'Mont Everest', 'Lhotse'], correctIndex: 2, category: 'Geographie', difficulty: 'easy' },
  { id: 'geo-13', question: 'Sur quel fleuve se trouve Paris?', answers: ['Rhone', 'Loire', 'Seine', 'Garonne'], correctIndex: 2, category: 'Geographie', difficulty: 'easy' },
  { id: 'geo-14', question: 'Quel est le plus grand pays du monde par superficie?', answers: ['Canada', 'Chine', 'USA', 'Russie'], correctIndex: 3, category: 'Geographie', difficulty: 'easy' },
  { id: 'geo-15', question: 'Dans quel pays se trouve la Statue de la Liberte?', answers: ['France', 'USA', 'Angleterre', 'Canada'], correctIndex: 1, category: 'Geographie', difficulty: 'easy' },
  { id: 'geo-16', question: 'Quelle ville se trouve sur le Bosphore?', answers: ['Athenes', 'Istanbul', 'Ankara', 'Bucarest'], correctIndex: 1, category: 'Geographie', difficulty: 'medium' },
  { id: 'geo-17', question: 'Quel est le plus haut sommet de France?', answers: ['Mont Ventoux', 'Pic du Midi', 'Mont Blanc', 'Puy de Dome'], correctIndex: 2, category: 'Geographie', difficulty: 'easy' },
  { id: 'geo-18', question: 'Combien de pays bordent la France metropolitaine?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Geographie', difficulty: 'medium' },
  { id: 'geo-19', question: 'Quel DOM-TOM est en Amerique du Sud?', answers: ['Martinique', 'Guyane', 'Reunion', 'Mayotte'], correctIndex: 1, category: 'Geographie', difficulty: 'medium' },
  { id: 'geo-20', question: 'Quelle est la capitale de la Suisse?', answers: ['Zurich', 'Geneve', 'Berne', 'Lausanne'], correctIndex: 2, category: 'Geographie', difficulty: 'medium' },
  // === Histoire (20) ===
  { id: 'his-1', question: 'En quelle annee le mur de Berlin est-il tombe?', answers: ['1987', '1988', '1989', '1990'], correctIndex: 2, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-2', question: 'Qui fut le premier homme sur la Lune?', answers: ['Buzz Aldrin', 'Neil Armstrong', 'Youri Gagarine', 'John Glenn'], correctIndex: 1, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-3', question: 'Quel peuple a construit les pyramides de Gizeh?', answers: ['Romains', 'Grecs', 'Egyptiens', 'Perses'], correctIndex: 2, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-4', question: 'Quand a commence la Premiere Guerre mondiale?', answers: ['1912', '1914', '1916', '1918'], correctIndex: 1, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-5', question: 'Qui a invente l\'imprimerie?', answers: ['Martin Luther', 'Johannes Gutenberg', 'Nicolas Copernic', 'Leonard de Vinci'], correctIndex: 1, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-6', question: 'En quelle annee la Revolution francaise a-t-elle commence?', answers: ['1776', '1789', '1799', '1804'], correctIndex: 1, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-7', question: 'Quand le Titanic a-t-il coule?', answers: ['1910', '1912', '1914', '1916'], correctIndex: 1, category: 'Histoire', difficulty: 'medium' },
  { id: 'his-8', question: 'Quel empereur romain a fait construire le Colisee?', answers: ['Neron', 'Auguste', 'Vespasien', 'Trajan'], correctIndex: 2, category: 'Histoire', difficulty: 'hard' },
  { id: 'his-9', question: 'Qui a peint la Joconde?', answers: ['Michel-Ange', 'Raphael', 'Leonard de Vinci', 'Rembrandt'], correctIndex: 2, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-10', question: 'Quel pays a offert la Statue de la Liberte aux USA?', answers: ['Angleterre', 'Allemagne', 'France', 'Espagne'], correctIndex: 2, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-11', question: 'En quelle annee Christophe Colomb a-t-il decouvert l\'Amerique?', answers: ['1482', '1492', '1502', '1512'], correctIndex: 1, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-12', question: 'Quand la Seconde Guerre mondiale s\'est-elle terminee en Europe?', answers: ['1944', '1945', '1946', '1947'], correctIndex: 1, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-13', question: 'Qui a ecrit "Les Miserables"?', answers: ['Emile Zola', 'Victor Hugo', 'Alexandre Dumas', 'Gustave Flaubert'], correctIndex: 1, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-14', question: 'Quel roi de France etait surnomme le "Roi Soleil"?', answers: ['Louis XIII', 'Louis XIV', 'Louis XV', 'Louis XVI'], correctIndex: 1, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-15', question: 'Quelle ville a ete detruite par une eruption volcanique en 79 ap. J.-C.?', answers: ['Rome', 'Athenes', 'Pompei', 'Carthage'], correctIndex: 2, category: 'Histoire', difficulty: 'medium' },
  { id: 'his-16', question: 'Qui a ete le premier president de la Ve Republique?', answers: ['Vincent Auriol', 'Charles de Gaulle', 'Rene Coty', 'Georges Pompidou'], correctIndex: 1, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-17', question: 'Quel empire a gouverne une grande partie de l\'Amerique du Sud?', answers: ['Azteque', 'Maya', 'Inca', 'Olmeque'], correctIndex: 2, category: 'Histoire', difficulty: 'medium' },
  { id: 'his-18', question: 'Quelle merveille antique se trouvait a Babylone?', answers: ['Colosse de Rhodes', 'Jardins suspendus', 'Phare d\'Alexandrie', 'Statue de Zeus'], correctIndex: 1, category: 'Histoire', difficulty: 'hard' },
  { id: 'his-19', question: 'Qui a mene la Reforme protestante?', answers: ['Jean Calvin', 'Martin Luther', 'Ulrich Zwingli', 'Jan Hus'], correctIndex: 1, category: 'Histoire', difficulty: 'easy' },
  { id: 'his-20', question: 'En quelle annee Napoleon a-t-il ete couronne empereur?', answers: ['1800', '1802', '1804', '1806'], correctIndex: 2, category: 'Histoire', difficulty: 'medium' },
  // === Sport (20) ===
  { id: 'spo-1', question: 'Combien de joueurs une equipe de football a-t-elle sur le terrain?', answers: ['9', '10', '11', '12'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-2', question: 'Quel pays a gagne la Coupe du Monde 2018?', answers: ['Bresil', 'Croatie', 'France', 'Belgique'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-3', question: 'Combien dure un match de hockey sur glace?', answers: ['60 minutes', '80 minutes', '90 minutes', '120 minutes'], correctIndex: 0, category: 'Sport', difficulty: 'medium' },
  { id: 'spo-4', question: 'Quel boxeur etait connu comme "The Greatest"?', answers: ['Mike Tyson', 'Muhammad Ali', 'Floyd Mayweather', 'Lennox Lewis'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-5', question: 'Combien d\'anneaux a le symbole olympique?', answers: ['3', '4', '5', '6'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-6', question: 'Quel Grand Chelem se joue sur terre battue?', answers: ['Roland-Garros', 'US Open', 'Open d\'Australie', 'Wimbledon'], correctIndex: 0, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-7', question: 'Qui detient le record du 100m?', answers: ['Carl Lewis', 'Usain Bolt', 'Tyson Gay', 'Yohan Blake'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-8', question: 'Quel Grand Chelem se joue sur gazon?', answers: ['Roland-Garros', 'US Open', 'Open d\'Australie', 'Wimbledon'], correctIndex: 3, category: 'Sport', difficulty: 'medium' },
  { id: 'spo-9', question: 'Combien de kilometres fait un marathon (arrondi)?', answers: ['40 km', '42 km', '44 km', '46 km'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-10', question: 'Quel club a le plus de titres en Ligue des Champions?', answers: ['FC Barcelone', 'AC Milan', 'Real Madrid', 'Bayern Munich'], correctIndex: 2, category: 'Sport', difficulty: 'medium' },
  { id: 'spo-11', question: 'En quelle annee les JO ont-ils eu lieu a Paris pour la 3e fois?', answers: ['2020', '2024', '2028', '2032'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-12', question: 'Combien de sets faut-il gagner dans un match de tennis masculin en Grand Chelem?', answers: ['2', '3', '4', '5'], correctIndex: 1, category: 'Sport', difficulty: 'medium' },
  { id: 'spo-13', question: 'De quelle couleur est la boule numero 8 au billard?', answers: ['Rouge', 'Bleue', 'Noire', 'Verte'], correctIndex: 2, category: 'Sport', difficulty: 'medium' },
  { id: 'spo-14', question: 'Dans quel sport y a-t-il un "Birdie"?', answers: ['Badminton', 'Golf', 'Cricket', 'Tennis'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-15', question: 'Combien de joueurs y a-t-il dans une equipe de basket sur le terrain?', answers: ['4', '5', '6', '7'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-16', question: 'Quel pays est celebre pour le sumo?', answers: ['Chine', 'Coree', 'Japon', 'Thailande'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-17', question: 'Quel sport combine natation, cyclisme et course?', answers: ['Biathlon', 'Triathlon', 'Pentathlon', 'Decathlon'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-18', question: 'Qui est le meilleur buteur de l\'equipe de France?', answers: ['Zinedine Zidane', 'Thierry Henry', 'Olivier Giroud', 'Michel Platini'], correctIndex: 2, category: 'Sport', difficulty: 'medium' },
  { id: 'spo-19', question: 'Quelle course cycliste a lieu chaque annee en juillet en France?', answers: ['Giro d\'Italia', 'Vuelta', 'Tour de France', 'Paris-Roubaix'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-20', question: 'Combien de points faut-il pour gagner un set de volley?', answers: ['15', '21', '25', '30'], correctIndex: 2, category: 'Sport', difficulty: 'medium' },
  // === Science (20) ===
  { id: 'wis-1', question: 'Quelle est la formule chimique de l\'eau?', answers: ['H2O', 'CO2', 'O2', 'NaCl'], correctIndex: 0, category: 'Science', difficulty: 'easy' },
  { id: 'wis-2', question: 'Combien de planetes a notre systeme solaire?', answers: ['7', '8', '9', '10'], correctIndex: 1, category: 'Science', difficulty: 'easy' },
  { id: 'wis-3', question: 'Quel gaz les plantes absorbent-elles?', answers: ['Oxygene', 'Azote', 'Dioxyde de carbone', 'Helium'], correctIndex: 2, category: 'Science', difficulty: 'easy' },
  { id: 'wis-4', question: 'Quel organe pompe le sang dans le corps?', answers: ['Poumons', 'Foie', 'Coeur', 'Rein'], correctIndex: 2, category: 'Science', difficulty: 'easy' },
  { id: 'wis-5', question: 'Quelle est la vitesse de la lumiere?', answers: ['150 000 km/s', '200 000 km/s', '300 000 km/s', '400 000 km/s'], correctIndex: 2, category: 'Science', difficulty: 'medium' },
  { id: 'wis-6', question: 'Quel element a le numero atomique 1?', answers: ['Helium', 'Hydrogene', 'Lithium', 'Oxygene'], correctIndex: 1, category: 'Science', difficulty: 'medium' },
  { id: 'wis-7', question: 'Quelle est l\'unite de tension electrique?', answers: ['Ampere', 'Watt', 'Volt', 'Ohm'], correctIndex: 2, category: 'Science', difficulty: 'easy' },
  { id: 'wis-8', question: 'Quelle planete est la plus proche du Soleil?', answers: ['Venus', 'Mercure', 'Mars', 'Terre'], correctIndex: 1, category: 'Science', difficulty: 'easy' },
  { id: 'wis-9', question: 'Quelle est la substance naturelle la plus dure?', answers: ['Acier', 'Diamant', 'Quartz', 'Saphir'], correctIndex: 1, category: 'Science', difficulty: 'easy' },
  { id: 'wis-10', question: 'Combien d\'os un adulte a-t-il environ?', answers: ['106', '156', '206', '256'], correctIndex: 2, category: 'Science', difficulty: 'medium' },
  { id: 'wis-11', question: 'Quelle vitamine le corps produit-il grace au soleil?', answers: ['Vitamine A', 'Vitamine B', 'Vitamine C', 'Vitamine D'], correctIndex: 3, category: 'Science', difficulty: 'medium' },
  { id: 'wis-12', question: 'Qui a developpe la theorie de la relativite?', answers: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Max Planck'], correctIndex: 2, category: 'Science', difficulty: 'easy' },
  { id: 'wis-13', question: 'Quel est le plus grand organe du corps humain?', answers: ['Foie', 'Peau', 'Poumon', 'Intestin'], correctIndex: 1, category: 'Science', difficulty: 'medium' },
  { id: 'wis-14', question: 'Que mesure un barometre?', answers: ['Temperature', 'Humidite', 'Pression atmospherique', 'Vitesse du vent'], correctIndex: 2, category: 'Science', difficulty: 'medium' },
  { id: 'wis-15', question: 'Quel gaz compose la majorite de l\'atmosphere terrestre?', answers: ['Oxygene', 'Azote', 'CO2', 'Argon'], correctIndex: 1, category: 'Science', difficulty: 'medium' },
  { id: 'wis-16', question: 'Quel animal a le sang bleu?', answers: ['Poulpe', 'Requin', 'Meduse', 'Anguille'], correctIndex: 0, category: 'Science', difficulty: 'hard' },
  { id: 'wis-17', question: 'Quel est le pH de l\'eau pure?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Science', difficulty: 'medium' },
  { id: 'wis-18', question: 'Combien de coeurs a un poulpe?', answers: ['1', '2', '3', '4'], correctIndex: 2, category: 'Science', difficulty: 'hard' },
  { id: 'wis-19', question: 'Quel vaisseau sanguin transporte le sang depuis le coeur?', answers: ['Veine', 'Artere', 'Capillaire', 'Lymphatique'], correctIndex: 1, category: 'Science', difficulty: 'medium' },
  { id: 'wis-20', question: 'Quelle planete a le plus de lunes?', answers: ['Jupiter', 'Saturne', 'Uranus', 'Neptune'], correctIndex: 1, category: 'Science', difficulty: 'hard' },
  // === Cinema (20) + Musique (20) + Culture Generale + Nature + Tech + Cuisine (condensed 40) ===
  { id: 'fil-1', question: 'Qui joue Jack Sparrow dans "Pirates des Caraibes"?', answers: ['Orlando Bloom', 'Johnny Depp', 'Brad Pitt', 'Leonardo DiCaprio'], correctIndex: 1, category: 'Cinema', difficulty: 'easy' },
  { id: 'fil-2', question: 'Dans quel film dit-on "Je suis ton pere"?', answers: ['Star Trek', 'Star Wars', 'Harry Potter', 'Le Seigneur des Anneaux'], correctIndex: 1, category: 'Cinema', difficulty: 'easy' },
  { id: 'fil-3', question: 'Comment s\'appelle le personnage principal de "Breaking Bad"?', answers: ['Jesse Pinkman', 'Saul Goodman', 'Walter White', 'Hank Schrader'], correctIndex: 2, category: 'Cinema', difficulty: 'easy' },
  { id: 'fil-4', question: 'Combien de films Harry Potter y a-t-il?', answers: ['6', '7', '8', '9'], correctIndex: 2, category: 'Cinema', difficulty: 'easy' },
  { id: 'fil-5', question: 'Quel realisateur a fait "Titanic" et "Avatar"?', answers: ['Steven Spielberg', 'James Cameron', 'Christopher Nolan', 'Ridley Scott'], correctIndex: 1, category: 'Cinema', difficulty: 'medium' },
  { id: 'fil-6', question: 'Comment s\'appelle la Reine des Neiges chez Disney?', answers: ['Anna', 'Elsa', 'Raiponce', 'Merida'], correctIndex: 1, category: 'Cinema', difficulty: 'easy' },
  { id: 'fil-7', question: 'De quelle couleur est la peau de Shrek?', answers: ['Bleue', 'Verte', 'Jaune', 'Marron'], correctIndex: 1, category: 'Cinema', difficulty: 'easy' },
  { id: 'fil-8', question: 'Qui joue Iron Man dans le MCU?', answers: ['Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr.', 'Mark Ruffalo'], correctIndex: 2, category: 'Cinema', difficulty: 'easy' },
  { id: 'fil-9', question: 'Quel film francais avec Omar Sy a ete un succes mondial?', answers: ['Le Fabuleux Destin d\'Amelie', 'Intouchables', 'La Haine', 'Le Diner de Cons'], correctIndex: 1, category: 'Cinema', difficulty: 'easy' },
  { id: 'fil-10', question: 'Dans quelle ville se deroule "Friends"?', answers: ['Los Angeles', 'Chicago', 'New York', 'Boston'], correctIndex: 2, category: 'Cinema', difficulty: 'easy' },
  { id: 'mus-1', question: 'Quel groupe a chante "Bohemian Rhapsody"?', answers: ['The Beatles', 'Led Zeppelin', 'Queen', 'Pink Floyd'], correctIndex: 2, category: 'Musique', difficulty: 'easy' },
  { id: 'mus-2', question: 'De quel pays vient ABBA?', answers: ['Norvege', 'Danemark', 'Finlande', 'Suede'], correctIndex: 3, category: 'Musique', difficulty: 'easy' },
  { id: 'mus-3', question: 'Qui est le "Roi de la Pop"?', answers: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Freddie Mercury'], correctIndex: 1, category: 'Musique', difficulty: 'easy' },
  { id: 'mus-4', question: 'Quel instrument a 88 touches?', answers: ['Orgue', 'Accordeon', 'Piano', 'Clavier'], correctIndex: 2, category: 'Musique', difficulty: 'easy' },
  { id: 'mus-5', question: 'De quelle ville viennent les Beatles?', answers: ['Londres', 'Manchester', 'Liverpool', 'Birmingham'], correctIndex: 2, category: 'Musique', difficulty: 'easy' },
  { id: 'mus-6', question: 'Quelle chanteuse francaise est connue pour "La Vie en rose"?', answers: ['Mireille Mathieu', 'Edith Piaf', 'Dalida', 'France Gall'], correctIndex: 1, category: 'Musique', difficulty: 'easy' },
  { id: 'mus-7', question: 'Quel genre musical est ne en Jamaique?', answers: ['Blues', 'Reggae', 'Salsa', 'Samba'], correctIndex: 1, category: 'Musique', difficulty: 'easy' },
  { id: 'mus-8', question: 'Qui a chante "Rolling in the Deep"?', answers: ['Amy Winehouse', 'Adele', 'Lana Del Rey', 'Florence Welch'], correctIndex: 1, category: 'Musique', difficulty: 'easy' },
  { id: 'mus-9', question: 'Combien de symphonies Beethoven a-t-il ecrites?', answers: ['5', '7', '9', '12'], correctIndex: 2, category: 'Musique', difficulty: 'hard' },
  { id: 'mus-10', question: 'Quel duo electronique francais est connu pour "Get Lucky"?', answers: ['Air', 'Daft Punk', 'Justice', 'David Guetta'], correctIndex: 1, category: 'Musique', difficulty: 'easy' },
  { id: 'all-1', question: 'Combien de jours a une annee bissextile?', answers: ['364', '365', '366', '367'], correctIndex: 2, category: 'Culture generale', difficulty: 'easy' },
  { id: 'all-2', question: 'Quelle couleur obtient-on en melangeant bleu et jaune?', answers: ['Rouge', 'Vert', 'Orange', 'Violet'], correctIndex: 1, category: 'Culture generale', difficulty: 'easy' },
  { id: 'all-3', question: 'Quelle est la monnaie du Japon?', answers: ['Won', 'Yuan', 'Yen', 'Roupie'], correctIndex: 2, category: 'Culture generale', difficulty: 'easy' },
  { id: 'all-4', question: 'Quel jour celebre-t-on la Fete nationale francaise?', answers: ['14 juillet', '1er mai', '11 novembre', '8 mai'], correctIndex: 0, category: 'Culture generale', difficulty: 'easy' },
  { id: 'all-5', question: 'Quelle est la langue officielle du Bresil?', answers: ['Espagnol', 'Portugais', 'Francais', 'Anglais'], correctIndex: 1, category: 'Culture generale', difficulty: 'easy' },
  { id: 'nat-1', question: 'Quel est le plus grand animal du monde?', answers: ['Elephant', 'Girafe', 'Baleine bleue', 'Grand requin blanc'], correctIndex: 2, category: 'Nature', difficulty: 'easy' },
  { id: 'nat-2', question: 'Combien de pattes a une araignee?', answers: ['6', '8', '10', '12'], correctIndex: 1, category: 'Nature', difficulty: 'easy' },
  { id: 'nat-3', question: 'Quel oiseau ne peut pas voler?', answers: ['Aigle', 'Autruche', 'Perroquet', 'Colibri'], correctIndex: 1, category: 'Nature', difficulty: 'easy' },
  { id: 'nat-4', question: 'Quel est le plus rapide animal terrestre?', answers: ['Lion', 'Guepard', 'Antilope', 'Levrier'], correctIndex: 1, category: 'Nature', difficulty: 'easy' },
  { id: 'nat-5', question: 'Quelle fleur est le symbole des Pays-Bas?', answers: ['Rose', 'Tournesol', 'Tulipe', 'Lys'], correctIndex: 2, category: 'Nature', difficulty: 'easy' },
  { id: 'tec-1', question: 'Qui a fonde Apple?', answers: ['Bill Gates', 'Steve Jobs', 'Elon Musk', 'Jeff Bezos'], correctIndex: 1, category: 'Technologie', difficulty: 'easy' },
  { id: 'tec-2', question: 'Quelle entreprise a developpe Android?', answers: ['Apple', 'Microsoft', 'Google', 'Samsung'], correctIndex: 2, category: 'Technologie', difficulty: 'easy' },
  { id: 'tec-3', question: 'Que signifie "IA"?', answers: ['Intelligence Automatisee', 'Intelligence Artificielle', 'Integration Avancee', 'Integration Automatisee'], correctIndex: 1, category: 'Technologie', difficulty: 'easy' },
  { id: 'tec-4', question: 'Quel reseau social a ete fonde en 2004?', answers: ['Twitter', 'Instagram', 'Facebook', 'TikTok'], correctIndex: 2, category: 'Technologie', difficulty: 'easy' },
  { id: 'tec-5', question: 'Qui a invente le World Wide Web?', answers: ['Steve Jobs', 'Bill Gates', 'Tim Berners-Lee', 'Mark Zuckerberg'], correctIndex: 2, category: 'Technologie', difficulty: 'medium' },
  { id: 'ess-1', question: 'De quel pays vient la pizza?', answers: ['Espagne', 'France', 'Italie', 'Grece'], correctIndex: 2, category: 'Cuisine', difficulty: 'easy' },
  { id: 'ess-2', question: 'Quel est l\'ingredient principal du guacamole?', answers: ['Tomate', 'Avocat', 'Poivron', 'Concombre'], correctIndex: 1, category: 'Cuisine', difficulty: 'easy' },
  { id: 'ess-3', question: 'De quel pays vient le sushi?', answers: ['Chine', 'Coree', 'Japon', 'Thailande'], correctIndex: 2, category: 'Cuisine', difficulty: 'easy' },
  { id: 'ess-4', question: 'Quel pays produit le plus de cafe?', answers: ['Colombie', 'Ethiopie', 'Vietnam', 'Bresil'], correctIndex: 3, category: 'Cuisine', difficulty: 'medium' },
  { id: 'ess-5', question: 'Quel pays est connu pour la paella?', answers: ['Italie', 'Portugal', 'Espagne', 'France'], correctIndex: 2, category: 'Cuisine', difficulty: 'easy' },
];

let _usedIndices: Set<number> = new Set();
export function getRandomQuestion(): QuizQuestion { if (_usedIndices.size >= QUIZ_QUESTIONS_FR.length) { _usedIndices.clear(); } let idx: number; do { idx = Math.floor(Math.random() * QUIZ_QUESTIONS_FR.length); } while (_usedIndices.has(idx)); _usedIndices.add(idx); return QUIZ_QUESTIONS_FR[idx]; }
export function resetQuestions(): void { _usedIndices.clear(); }
