export interface QuizQuestion { id: string; question: string; answers: string[]; correctIndex: number; category: string; difficulty: 'easy' | 'medium' | 'hard'; }

export const QUIZ_QUESTIONS_IT: QuizQuestion[] = [
  { id: 'geo-1', question: 'Qual e la capitale dell\'Australia?', answers: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-2', question: 'Qual e il fiume piu lungo del mondo?', answers: ['Amazzoni', 'Nilo', 'Yangtze', 'Mississippi'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-3', question: 'In quale paese si trova il Machu Picchu?', answers: ['Bolivia', 'Ecuador', 'Peru', 'Colombia'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-4', question: 'Quante regioni ha l\'Italia?', answers: ['18', '19', '20', '21'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-5', question: 'Qual e il paese piu piccolo del mondo?', answers: ['Monaco', 'Citta del Vaticano', 'San Marino', 'Liechtenstein'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-6', question: 'Quale paese ha la forma di uno stivale?', answers: ['Spagna', 'Grecia', 'Italia', 'Portogallo'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-7', question: 'Quale paese ha piu abitanti?', answers: ['India', 'Cina', 'USA', 'Indonesia'], correctIndex: 0, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-8', question: 'Qual e il deserto piu grande della Terra?', answers: ['Sahara', 'Gobi', 'Antartide', 'Kalahari'], correctIndex: 2, category: 'Geografia', difficulty: 'hard' },
  { id: 'geo-9', question: 'In quale continente si trova l\'Egitto?', answers: ['Asia', 'Africa', 'Europa', 'Sud America'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-10', question: 'Quale citta e soprannominata la "Grande Mela"?', answers: ['Los Angeles', 'Chicago', 'New York', 'Boston'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-11', question: 'Qual e la capitale del Canada?', answers: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'], correctIndex: 3, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-12', question: 'Qual e la montagna piu alta del mondo?', answers: ['K2', 'Kangchenjunga', 'Monte Everest', 'Lhotse'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-13', question: 'Su quale fiume si trova Roma?', answers: ['Po', 'Arno', 'Tevere', 'Adige'], correctIndex: 2, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-14', question: 'Qual e il paese piu grande del mondo per superficie?', answers: ['Canada', 'Cina', 'USA', 'Russia'], correctIndex: 3, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-15', question: 'In quale paese si trova la Statua della Liberta?', answers: ['Francia', 'USA', 'Inghilterra', 'Canada'], correctIndex: 1, category: 'Geografia', difficulty: 'easy' },
  { id: 'geo-16', question: 'Qual e il vulcano piu alto d\'Europa?', answers: ['Vesuvio', 'Etna', 'Stromboli', 'Teide'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-17', question: 'Quale citta si trova sul Bosforo?', answers: ['Atene', 'Istanbul', 'Ankara', 'Bucarest'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-18', question: 'Qual e il lago piu grande d\'Italia?', answers: ['Lago di Como', 'Lago Maggiore', 'Lago di Garda', 'Lago Trasimeno'], correctIndex: 2, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-19', question: 'Quante nazioni confinano con l\'Italia?', answers: ['3', '4', '5', '6'], correctIndex: 1, category: 'Geografia', difficulty: 'medium' },
  { id: 'geo-20', question: 'Qual e la capitale della Svizzera?', answers: ['Zurigo', 'Ginevra', 'Berna', 'Losanna'], correctIndex: 2, category: 'Geografia', difficulty: 'medium' },
  { id: 'his-1', question: 'In che anno e caduto il Muro di Berlino?', answers: ['1987', '1988', '1989', '1990'], correctIndex: 2, category: 'Storia', difficulty: 'easy' },
  { id: 'his-2', question: 'Chi fu il primo uomo sulla Luna?', answers: ['Buzz Aldrin', 'Neil Armstrong', 'Yuri Gagarin', 'John Glenn'], correctIndex: 1, category: 'Storia', difficulty: 'easy' },
  { id: 'his-3', question: 'Quale popolo costrui le Piramidi di Giza?', answers: ['Romani', 'Greci', 'Egizi', 'Persiani'], correctIndex: 2, category: 'Storia', difficulty: 'easy' },
  { id: 'his-4', question: 'Quando inizio la Prima Guerra Mondiale?', answers: ['1912', '1914', '1916', '1918'], correctIndex: 1, category: 'Storia', difficulty: 'easy' },
  { id: 'his-5', question: 'Chi invento la stampa?', answers: ['Martin Lutero', 'Johannes Gutenberg', 'Niccolo Copernico', 'Leonardo da Vinci'], correctIndex: 1, category: 'Storia', difficulty: 'easy' },
  { id: 'his-6', question: 'Chi dipinse la Gioconda?', answers: ['Michelangelo', 'Raffaello', 'Leonardo da Vinci', 'Rembrandt'], correctIndex: 2, category: 'Storia', difficulty: 'easy' },
  { id: 'his-7', question: 'Quando affondo il Titanic?', answers: ['1910', '1912', '1914', '1916'], correctIndex: 1, category: 'Storia', difficulty: 'medium' },
  { id: 'his-8', question: 'Quale imperatore romano fece costruire il Colosseo?', answers: ['Nerone', 'Augusto', 'Vespasiano', 'Traiano'], correctIndex: 2, category: 'Storia', difficulty: 'easy' },
  { id: 'his-9', question: 'In che anno Colombo arrivo in America?', answers: ['1482', '1492', '1502', '1512'], correctIndex: 1, category: 'Storia', difficulty: 'easy' },
  { id: 'his-10', question: 'Quale paese regalo la Statua della Liberta agli USA?', answers: ['Inghilterra', 'Germania', 'Francia', 'Spagna'], correctIndex: 2, category: 'Storia', difficulty: 'medium' },
  { id: 'spo-1', question: 'Quanti giocatori ha una squadra di calcio in campo?', answers: ['9', '10', '11', '12'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-2', question: 'Quale paese ha vinto i Mondiali di calcio 2006?', answers: ['Brasile', 'Francia', 'Italia', 'Germania'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-3', question: 'Quanti anelli ha il simbolo olimpico?', answers: ['3', '4', '5', '6'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-4', question: 'Chi detiene il record dei 100 metri piani?', answers: ['Carl Lewis', 'Usain Bolt', 'Tyson Gay', 'Yohan Blake'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-5', question: 'Quale club ha piu titoli di Champions League?', answers: ['FC Barcelona', 'AC Milan', 'Real Madrid', 'Bayern Monaco'], correctIndex: 2, category: 'Sport', difficulty: 'medium' },
  { id: 'spo-6', question: 'Quanti chilometri ha una maratona (arrotondati)?', answers: ['40 km', '42 km', '44 km', '46 km'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-7', question: 'Quale sport combina nuoto, ciclismo e corsa?', answers: ['Biathlon', 'Triathlon', 'Pentathlon', 'Decathlon'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-8', question: 'In quale sport si segna un "Birdie"?', answers: ['Badminton', 'Golf', 'Cricket', 'Tennis'], correctIndex: 1, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-9', question: 'Quale paese e famoso per il sumo?', answers: ['Cina', 'Corea', 'Giappone', 'Tailandia'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'spo-10', question: 'Come si chiama la corsa ciclistica piu famosa d\'Italia?', answers: ['Tour de France', 'Vuelta', 'Giro d\'Italia', 'Parigi-Roubaix'], correctIndex: 2, category: 'Sport', difficulty: 'easy' },
  { id: 'wis-1', question: 'Qual e la formula chimica dell\'acqua?', answers: ['H2O', 'CO2', 'O2', 'NaCl'], correctIndex: 0, category: 'Scienza', difficulty: 'easy' },
  { id: 'wis-2', question: 'Quanti pianeti ha il nostro sistema solare?', answers: ['7', '8', '9', '10'], correctIndex: 1, category: 'Scienza', difficulty: 'easy' },
  { id: 'wis-3', question: 'Quale gas assorbono le piante?', answers: ['Ossigeno', 'Azoto', 'Anidride carbonica', 'Elio'], correctIndex: 2, category: 'Scienza', difficulty: 'easy' },
  { id: 'wis-4', question: 'Quale organo pompa il sangue nel corpo?', answers: ['Polmoni', 'Fegato', 'Cuore', 'Rene'], correctIndex: 2, category: 'Scienza', difficulty: 'easy' },
  { id: 'wis-5', question: 'Qual e la sostanza naturale piu dura?', answers: ['Acciaio', 'Diamante', 'Quarzo', 'Zaffiro'], correctIndex: 1, category: 'Scienza', difficulty: 'easy' },
  { id: 'wis-6', question: 'Chi ha sviluppato la teoria della relativita?', answers: ['Isaac Newton', 'Niels Bohr', 'Albert Einstein', 'Max Planck'], correctIndex: 2, category: 'Scienza', difficulty: 'easy' },
  { id: 'wis-7', question: 'Quale pianeta e il piu vicino al Sole?', answers: ['Venere', 'Mercurio', 'Marte', 'Terra'], correctIndex: 1, category: 'Scienza', difficulty: 'easy' },
  { id: 'wis-8', question: 'Quante ossa ha un adulto circa?', answers: ['106', '156', '206', '256'], correctIndex: 2, category: 'Scienza', difficulty: 'medium' },
  { id: 'wis-9', question: 'Qual e il gas piu presente nell\'atmosfera terrestre?', answers: ['Ossigeno', 'Azoto', 'CO2', 'Argon'], correctIndex: 1, category: 'Scienza', difficulty: 'medium' },
  { id: 'wis-10', question: 'Qual e il pH dell\'acqua pura?', answers: ['5', '6', '7', '8'], correctIndex: 2, category: 'Scienza', difficulty: 'medium' },
  { id: 'fil-1', question: 'Chi interpreta Jack Sparrow in "Pirati dei Caraibi"?', answers: ['Orlando Bloom', 'Johnny Depp', 'Brad Pitt', 'Leonardo DiCaprio'], correctIndex: 1, category: 'Cinema', difficulty: 'easy' },
  { id: 'fil-2', question: 'In quale film si dice "Io sono tuo padre"?', answers: ['Star Trek', 'Guerre Stellari', 'Harry Potter', 'Il Signore degli Anelli'], correctIndex: 1, category: 'Cinema', difficulty: 'easy' },
  { id: 'fil-3', question: 'Quanti film di Harry Potter ci sono?', answers: ['6', '7', '8', '9'], correctIndex: 2, category: 'Cinema', difficulty: 'easy' },
  { id: 'fil-4', question: 'Come si chiama la Regina dei Ghiacci nel film Disney?', answers: ['Anna', 'Elsa', 'Rapunzel', 'Merida'], correctIndex: 1, category: 'Cinema', difficulty: 'easy' },
  { id: 'fil-5', question: 'Chi interpreta Iron Man nel MCU?', answers: ['Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr.', 'Mark Ruffalo'], correctIndex: 2, category: 'Cinema', difficulty: 'easy' },
  { id: 'mus-1', question: 'Quale band ha cantato "Bohemian Rhapsody"?', answers: ['The Beatles', 'Led Zeppelin', 'Queen', 'Pink Floyd'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-2', question: 'Chi e il "Re del Pop"?', answers: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Freddie Mercury'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-3', question: 'Quale strumento ha 88 tasti?', answers: ['Organo', 'Fisarmonica', 'Pianoforte', 'Tastiera'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-4', question: 'Di quale citta sono i Beatles?', answers: ['Londra', 'Manchester', 'Liverpool', 'Birmingham'], correctIndex: 2, category: 'Musica', difficulty: 'easy' },
  { id: 'mus-5', question: 'Quale band italiana ha vinto l\'Eurovision 2021?', answers: ['Il Volo', 'Maneskin', 'Lacuna Coil', 'Negramaro'], correctIndex: 1, category: 'Musica', difficulty: 'easy' },
  { id: 'all-1', question: 'Quanti giorni ha un anno bisestile?', answers: ['364', '365', '366', '367'], correctIndex: 2, category: 'Cultura generale', difficulty: 'easy' },
  { id: 'all-2', question: 'Quale colore si ottiene mescolando blu e giallo?', answers: ['Rosso', 'Verde', 'Arancione', 'Viola'], correctIndex: 1, category: 'Cultura generale', difficulty: 'easy' },
  { id: 'all-3', question: 'Qual e la moneta del Giappone?', answers: ['Won', 'Yuan', 'Yen', 'Rupia'], correctIndex: 2, category: 'Cultura generale', difficulty: 'easy' },
  { id: 'all-4', question: 'Qual e la lingua ufficiale del Brasile?', answers: ['Spagnolo', 'Portoghese', 'Francese', 'Inglese'], correctIndex: 1, category: 'Cultura generale', difficulty: 'easy' },
  { id: 'all-5', question: 'Quando si celebra la Festa della Repubblica in Italia?', answers: ['25 aprile', '1 maggio', '2 giugno', '15 agosto'], correctIndex: 2, category: 'Cultura generale', difficulty: 'easy' },
  { id: 'nat-1', question: 'Qual e l\'animale piu grande del mondo?', answers: ['Elefante', 'Giraffa', 'Balenottera azzurra', 'Squalo bianco'], correctIndex: 2, category: 'Natura', difficulty: 'easy' },
  { id: 'nat-2', question: 'Quante zampe ha un ragno?', answers: ['6', '8', '10', '12'], correctIndex: 1, category: 'Natura', difficulty: 'easy' },
  { id: 'nat-3', question: 'Qual e l\'animale terrestre piu veloce?', answers: ['Leone', 'Ghepardo', 'Antilope', 'Levriero'], correctIndex: 1, category: 'Natura', difficulty: 'easy' },
  { id: 'nat-4', question: 'Quale fiore e il simbolo dei Paesi Bassi?', answers: ['Rosa', 'Girasole', 'Tulipano', 'Giglio'], correctIndex: 2, category: 'Natura', difficulty: 'easy' },
  { id: 'nat-5', question: 'Quanti cuori ha un polpo?', answers: ['1', '2', '3', '4'], correctIndex: 2, category: 'Natura', difficulty: 'hard' },
  { id: 'tec-1', question: 'Chi ha fondato Apple?', answers: ['Bill Gates', 'Steve Jobs', 'Elon Musk', 'Jeff Bezos'], correctIndex: 1, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'tec-2', question: 'Quale azienda ha sviluppato Android?', answers: ['Apple', 'Microsoft', 'Google', 'Samsung'], correctIndex: 2, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'tec-3', question: 'Che cosa significa "IA"?', answers: ['Intelligenza Automatizzata', 'Intelligenza Artificiale', 'Integrazione Avanzata', 'Integrazione Automatica'], correctIndex: 1, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'tec-4', question: 'Quale social network e stato fondato nel 2004?', answers: ['Twitter', 'Instagram', 'Facebook', 'TikTok'], correctIndex: 2, category: 'Tecnologia', difficulty: 'easy' },
  { id: 'tec-5', question: 'Chi ha inventato il World Wide Web?', answers: ['Steve Jobs', 'Bill Gates', 'Tim Berners-Lee', 'Mark Zuckerberg'], correctIndex: 2, category: 'Tecnologia', difficulty: 'medium' },
  { id: 'ess-1', question: 'Da quale paese viene la pizza?', answers: ['Spagna', 'Francia', 'Italia', 'Grecia'], correctIndex: 2, category: 'Cucina', difficulty: 'easy' },
  { id: 'ess-2', question: 'Da quale paese viene il sushi?', answers: ['Cina', 'Corea', 'Giappone', 'Tailandia'], correctIndex: 2, category: 'Cucina', difficulty: 'easy' },
  { id: 'ess-3', question: 'Qual e l\'ingrediente principale del guacamole?', answers: ['Pomodoro', 'Avocado', 'Peperone', 'Cetriolo'], correctIndex: 1, category: 'Cucina', difficulty: 'easy' },
  { id: 'ess-4', question: 'Quale paese produce piu caffe?', answers: ['Colombia', 'Etiopia', 'Vietnam', 'Brasile'], correctIndex: 3, category: 'Cucina', difficulty: 'medium' },
  { id: 'ess-5', question: 'Cosa significa "al dente" per la pasta?', answers: ['Morbida', 'Croccante', 'Cruda', 'Stracotta'], correctIndex: 1, category: 'Cucina', difficulty: 'easy' },
];

let _usedIndices: Set<number> = new Set();
export function getRandomQuestion(): QuizQuestion { if (_usedIndices.size >= QUIZ_QUESTIONS_IT.length) { _usedIndices.clear(); } let idx: number; do { idx = Math.floor(Math.random() * QUIZ_QUESTIONS_IT.length); } while (_usedIndices.has(idx)); _usedIndices.add(idx); return QUIZ_QUESTIONS_IT[idx]; }
export function resetQuestions(): void { _usedIndices.clear(); }
