export interface TabooCard {
  term: string;
  forbidden: string[];
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const TABOO_CARDS_IT: TabooCard[] = [
  // === Sport (21) ===
  { term: 'Calcio', forbidden: ['Pallone', 'Gol', 'Giocatore', 'Squadra', 'Stadio'], category: 'Sport', difficulty: 'easy' },
  { term: 'Tennis', forbidden: ['Racchetta', 'Palla', 'Rete', 'Servizio', 'Wimbledon'], category: 'Sport', difficulty: 'easy' },
  { term: 'Pallacanestro', forbidden: ['Canestro', 'Palla', 'Lanciare', 'NBA', 'Schiacciata'], category: 'Sport', difficulty: 'easy' },
  { term: 'Nuoto', forbidden: ['Acqua', 'Piscina', 'Corsia', 'Bracciata', 'Costume'], category: 'Sport', difficulty: 'easy' },
  { term: 'Pugilato', forbidden: ['Combattimento', 'Ring', 'Guantoni', 'Pugno', 'Round'], category: 'Sport', difficulty: 'easy' },
  { term: 'Sci', forbidden: ['Neve', 'Montagna', 'Pista', 'Inverno', 'Seggiovia'], category: 'Sport', difficulty: 'easy' },
  { term: 'Maratona', forbidden: ['Correre', 'Chilometri', 'Distanza', 'Resistenza', 'Traguardo'], category: 'Sport', difficulty: 'medium' },
  { term: 'Golf', forbidden: ['Palla', 'Mazza', 'Buca', 'Prato', 'Handicap'], category: 'Sport', difficulty: 'easy' },
  { term: 'Olimpiadi', forbidden: ['Giochi', 'Anelli', 'Medaglia', 'Atleti', 'Competizione'], category: 'Sport', difficulty: 'easy' },
  { term: 'Surf', forbidden: ['Onda', 'Tavola', 'Mare', 'Spiaggia', 'Acqua'], category: 'Sport', difficulty: 'easy' },
  { term: 'Hockey su ghiaccio', forbidden: ['Disco', 'Ghiaccio', 'Mazza', 'Porta', 'Pattini'], category: 'Sport', difficulty: 'easy' },
  { term: 'Yoga', forbidden: ['Stretching', 'Meditazione', 'Corpo', 'Posizione', 'Rilassamento'], category: 'Sport', difficulty: 'medium' },
  { term: 'Formula 1', forbidden: ['Gara', 'Auto', 'Veloce', 'Pilota', 'Circuito'], category: 'Sport', difficulty: 'easy' },
  { term: 'Arrampicata', forbidden: ['Parete', 'Roccia', 'Corda', 'Altezza', 'Prese'], category: 'Sport', difficulty: 'easy' },
  { term: 'Pallamano', forbidden: ['Palla', 'Porta', 'Lanciare', 'Squadra', 'Campo'], category: 'Sport', difficulty: 'easy' },
  { term: 'Biathlon', forbidden: ['Sci', 'Tiro', 'Inverno', 'Fucile', 'Fondo'], category: 'Sport', difficulty: 'hard' },
  { term: 'Freccette', forbidden: ['Freccia', 'Bersaglio', 'Lanciare', 'Punti', 'Centro'], category: 'Sport', difficulty: 'medium' },
  { term: 'Pallavolo', forbidden: ['Rete', 'Palla', 'Spiaggia', 'Squadra', 'Schiacciata'], category: 'Sport', difficulty: 'easy' },
  { term: 'Scherma', forbidden: ['Spada', 'Maschera', 'Stoccata', 'Fioretto', 'Combattimento'], category: 'Sport', difficulty: 'medium' },
  { term: 'Ping pong', forbidden: ['Palla', 'Racchetta', 'Tavolo', 'Ping', 'Pong'], category: 'Sport', difficulty: 'easy' },
  { term: 'Paracadute', forbidden: ['Saltare', 'Volare', 'Aereo', 'Aprire', 'Aria'], category: 'Sport', difficulty: 'easy' },

  // === Cibo (27) ===
  { term: 'Pizza', forbidden: ['Italia', 'Impasto', 'Condimento', 'Formaggio', 'Forno'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Spaghetti', forbidden: ['Pasta', 'Italia', 'Sugo', 'Cucinare', 'Lunghi'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Cioccolato', forbidden: ['Dolce', 'Cacao', 'Marrone', 'Tavoletta', 'Latte'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Hamburger', forbidden: ['Carne', 'Panino', 'Fast food', 'McDonalds', 'Polpetta'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Gelato', forbidden: ['Freddo', 'Estate', 'Pallina', 'Cono', 'Dolce'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Sushi', forbidden: ['Giappone', 'Riso', 'Pesce', 'Alga', 'Crudo'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Focaccia', forbidden: ['Pane', 'Olio', 'Liguria', 'Sale', 'Forno'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Kebab', forbidden: ['Carne', 'Pane', 'Insalata', 'Turchia', 'Salsa'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Torta', forbidden: ['Cuocere', 'Dolce', 'Compleanno', 'Panna', 'Forno'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Patatine fritte', forbidden: ['Patata', 'Friggere', 'Ketchup', 'Salate', 'Fast food'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Insalata', forbidden: ['Verde', 'Sano', 'Verdura', 'Condimento', 'Fresca'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Croissant', forbidden: ['Francia', 'Colazione', 'Burro', 'Impasto', 'Panetteria'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Carbonara', forbidden: ['Pasta', 'Uovo', 'Guanciale', 'Roma', 'Pecorino'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Risotto', forbidden: ['Riso', 'Brodo', 'Milanese', 'Zafferano', 'Mantecato'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Lasagne', forbidden: ['Pasta', 'Strati', 'Ragu', 'Forno', 'Besciamella'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Fondue', forbidden: ['Formaggio', 'Fondere', 'Pentola', 'Svizzera', 'Intingere'], category: 'Cibo', difficulty: 'medium' },
  { term: 'Ossobuco', forbidden: ['Carne', 'Milano', 'Vitello', 'Stinco', 'Midollo'], category: 'Cibo', difficulty: 'medium' },
  { term: 'Tiramisu', forbidden: ['Italia', 'Caffe', 'Mascarpone', 'Dolce', 'Cacao'], category: 'Cibo', difficulty: 'medium' },
  { term: 'Minestrone', forbidden: ['Verdure', 'Zuppa', 'Brodo', 'Cucinare', 'Caldo'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Muesli', forbidden: ['Colazione', 'Avena', 'Latte', 'Frutta', 'Sano'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Bruschetta', forbidden: ['Pane', 'Pomodoro', 'Olio', 'Aglio', 'Antipasto'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Tacos', forbidden: ['Messico', 'Mais', 'Carne', 'Salsa', 'Ripieno'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Raclette', forbidden: ['Formaggio', 'Fondere', 'Padellino', 'Patata', 'Svizzera'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Panettone', forbidden: ['Natale', 'Milano', 'Uvetta', 'Dolce', 'Lievitato'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Cannoli', forbidden: ['Sicilia', 'Ricotta', 'Croccante', 'Dolce', 'Ripieno'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Popcorn', forbidden: ['Mais', 'Cinema', 'Salato', 'Dolce', 'Film'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Vin brule', forbidden: ['Natale', 'Caldo', 'Vino', 'Spezie', 'Mercatino'], category: 'Cibo', difficulty: 'easy' },

  // === Animali (25) ===
  { term: 'Elefante', forbidden: ['Grande', 'Proboscide', 'Africa', 'Grigio', 'Zanna'], category: 'Animali', difficulty: 'easy' },
  { term: 'Pinguino', forbidden: ['Ghiaccio', 'Bianco e nero', 'Antartide', 'Uccello', 'Volare'], category: 'Animali', difficulty: 'easy' },
  { term: 'Giraffa', forbidden: ['Collo', 'Lungo', 'Africa', 'Macchie', 'Alto'], category: 'Animali', difficulty: 'easy' },
  { term: 'Delfino', forbidden: ['Mare', 'Nuotare', 'Intelligente', 'Saltare', 'Flipper'], category: 'Animali', difficulty: 'easy' },
  { term: 'Camaleonte', forbidden: ['Colore', 'Cambiare', 'Lucertola', 'Lingua', 'Mimetismo'], category: 'Animali', difficulty: 'easy' },
  { term: 'Coccodrillo', forbidden: ['Denti', 'Acqua', 'Pericoloso', 'Rettile', 'Fiume'], category: 'Animali', difficulty: 'easy' },
  { term: 'Farfalla', forbidden: ['Ali', 'Colorata', 'Bruco', 'Volare', 'Fiore'], category: 'Animali', difficulty: 'easy' },
  { term: 'Bradipo', forbidden: ['Lento', 'Albero', 'Appendere', 'Dormire', 'Pigro'], category: 'Animali', difficulty: 'easy' },
  { term: 'Squalo', forbidden: ['Mare', 'Denti', 'Pericoloso', 'Pesce', 'Pinna'], category: 'Animali', difficulty: 'easy' },
  { term: 'Colibri', forbidden: ['Piccolo', 'Uccello', 'Volare', 'Fiore', 'Veloce'], category: 'Animali', difficulty: 'medium' },
  { term: 'Pappagallo', forbidden: ['Uccello', 'Parlare', 'Colorato', 'Piume', 'Pirata'], category: 'Animali', difficulty: 'easy' },
  { term: 'Orso polare', forbidden: ['Bianco', 'Artico', 'Freddo', 'Ghiaccio', 'Orso'], category: 'Animali', difficulty: 'easy' },
  { term: 'Fenicottero', forbidden: ['Rosa', 'Uccello', 'Zampa', 'Stare', 'Lago'], category: 'Animali', difficulty: 'easy' },
  { term: 'Canguro', forbidden: ['Australia', 'Saltare', 'Marsupio', 'Cucciolo', 'Balzare'], category: 'Animali', difficulty: 'easy' },
  { term: 'Pavone', forbidden: ['Piume', 'Ruota', 'Colorato', 'Uccello', 'Maschio'], category: 'Animali', difficulty: 'easy' },
  { term: 'Formica', forbidden: ['Piccola', 'Insetto', 'Formicaio', 'Forte', 'Colonia'], category: 'Animali', difficulty: 'easy' },
  { term: 'Ippopotamo', forbidden: ['Acqua', 'Africa', 'Grande', 'Bocca', 'Fiume'], category: 'Animali', difficulty: 'easy' },
  { term: 'Gufo', forbidden: ['Notte', 'Uccello', 'Occhi', 'Verso', 'Saggio'], category: 'Animali', difficulty: 'easy' },
  { term: 'Panda', forbidden: ['Cina', 'Bambu', 'Bianco e nero', 'Orso', 'Carino'], category: 'Animali', difficulty: 'easy' },
  { term: 'Tartaruga', forbidden: ['Guscio', 'Lenta', 'Vecchia', 'Corazza', 'Rettile'], category: 'Animali', difficulty: 'easy' },
  { term: 'Lupo', forbidden: ['Ululare', 'Branco', 'Bosco', 'Cane', 'Favola'], category: 'Animali', difficulty: 'easy' },
  { term: 'Polpo', forbidden: ['Braccia', 'Otto', 'Mare', 'Inchiostro', 'Tentacolo'], category: 'Animali', difficulty: 'medium' },
  { term: 'Cavalluccio marino', forbidden: ['Mare', 'Piccolo', 'Cavallo', 'Nuotare', 'Acqua'], category: 'Animali', difficulty: 'easy' },
  { term: 'Gorilla', forbidden: ['Scimmia', 'Grande', 'Forte', 'Giungla', 'Dorso argentato'], category: 'Animali', difficulty: 'easy' },
  { term: 'Ape', forbidden: ['Miele', 'Pungere', 'Fiore', 'Volare', 'Regina'], category: 'Animali', difficulty: 'easy' },

  // === Tecnologia (20) ===
  { term: 'Smartphone', forbidden: ['Cellulare', 'Telefono', 'Apple', 'App', 'Schermo'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Internet', forbidden: ['Online', 'Rete', 'Navigare', 'Sito web', 'Connessione'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Computer', forbidden: ['Macchina', 'Schermo', 'Tastiera', 'Mouse', 'PC'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Robot', forbidden: ['Macchina', 'Artificiale', 'Metallo', 'Automatico', 'Tecnologia'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Intelligenza artificiale', forbidden: ['Computer', 'Robot', 'Imparare', 'Macchina', 'Algoritmo'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Drone', forbidden: ['Volare', 'Telecamera', 'Telecomando', 'Elica', 'Aria'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'WiFi', forbidden: ['Internet', 'Senza fili', 'Connessione', 'Router', 'Rete'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Selfie', forbidden: ['Foto', 'Fotocamera', 'Telefono', 'Se stesso', 'Immagine'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Stampante 3D', forbidden: ['Stampare', 'Tridimensionale', 'Plastica', 'Strato', 'Modello'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Realta virtuale', forbidden: ['Visore', 'Virtuale', 'Mondo', 'Computer', 'Simulazione'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Bluetooth', forbidden: ['Senza fili', 'Connessione', 'Telefono', 'Cuffie', 'Radio'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Streaming', forbidden: ['Film', 'Musica', 'Netflix', 'Internet', 'Video'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'GPS', forbidden: ['Navigazione', 'Posizione', 'Satellite', 'Mappa', 'Localizzazione'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Auto elettrica', forbidden: ['Elettricita', 'Tesla', 'Batteria', 'Guidare', 'Caricare'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Social media', forbidden: ['Facebook', 'Instagram', 'Rete', 'Condividere', 'Follower'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Podcast', forbidden: ['Audio', 'Ascoltare', 'Trasmissione', 'Spotify', 'Episodio'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Alexa', forbidden: ['Amazon', 'Assistente vocale', 'Parlare', 'Intelligente', 'Altoparlante'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Tablet', forbidden: ['iPad', 'Schermo', 'Touch', 'Computer', 'Portatile'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Algoritmo', forbidden: ['Calcolo', 'Computer', 'Passo', 'Programma', 'Logica'], category: 'Tecnologia', difficulty: 'hard' },
  { term: 'Blockchain', forbidden: ['Bitcoin', 'Cripto', 'Decentralizzato', 'Catena', 'Dati'], category: 'Tecnologia', difficulty: 'hard' },

  // === Celebrita (15) ===
  { term: 'Albert Einstein', forbidden: ['Relativita', 'Fisica', 'Genio', 'E=mc2', 'Capelli'], category: 'Celebrita', difficulty: 'easy' },
  { term: 'Mozart', forbidden: ['Musica', 'Compositore', 'Salisburgo', 'Piano', 'Classica'], category: 'Celebrita', difficulty: 'easy' },
  { term: 'Leonardo da Vinci', forbidden: ['Gioconda', 'Pittore', 'Inventore', 'Rinascimento', 'Italia'], category: 'Celebrita', difficulty: 'easy' },
  { term: 'Beethoven', forbidden: ['Musica', 'Compositore', 'Sordo', 'Sinfonia', 'Piano'], category: 'Celebrita', difficulty: 'easy' },
  { term: 'Galileo Galilei', forbidden: ['Telescopio', 'Scienza', 'Astronomia', 'Terra', 'Pisa'], category: 'Celebrita', difficulty: 'easy' },
  { term: 'Cristiano Ronaldo', forbidden: ['Calcio', 'Portogallo', 'Gol', 'Juventus', 'Attaccante'], category: 'Celebrita', difficulty: 'easy' },
  { term: 'Sophia Loren', forbidden: ['Attrice', 'Cinema', 'Italia', 'Bellezza', 'Oscar'], category: 'Celebrita', difficulty: 'easy' },
  { term: 'Elon Musk', forbidden: ['Tesla', 'SpaceX', 'Miliardario', 'Twitter', 'Imprenditore'], category: 'Celebrita', difficulty: 'easy' },
  { term: 'Dante Alighieri', forbidden: ['Divina Commedia', 'Poeta', 'Inferno', 'Firenze', 'Letteratura'], category: 'Celebrita', difficulty: 'medium' },
  { term: 'Cleopatra', forbidden: ['Egitto', 'Regina', 'Faraone', 'Nilo', 'Cesare'], category: 'Celebrita', difficulty: 'medium' },
  { term: 'Napoleone', forbidden: ['Francia', 'Imperatore', 'Guerra', 'Basso', 'Waterloo'], category: 'Celebrita', difficulty: 'easy' },
  { term: 'Marie Curie', forbidden: ['Radioattivita', 'Fisica', 'Nobel', 'Scienza', 'Ricerca'], category: 'Celebrita', difficulty: 'medium' },
  { term: 'Michael Jackson', forbidden: ['Cantante', 'Thriller', 'Ballo', 'Pop', 'Re'], category: 'Celebrita', difficulty: 'easy' },
  { term: 'Lionel Messi', forbidden: ['Calcio', 'Argentina', 'Barcellona', 'Gol', 'Mondiale'], category: 'Celebrita', difficulty: 'easy' },
  { term: 'Giuseppe Verdi', forbidden: ['Opera', 'Musica', 'Aida', 'Compositore', 'La Traviata'], category: 'Celebrita', difficulty: 'medium' },

  // === Vita quotidiana (32) ===
  { term: 'Sveglia', forbidden: ['Mattina', 'Alzarsi', 'Orologio', 'Suonare', 'Allarme'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Spazzolino', forbidden: ['Denti', 'Spazzolare', 'Bocca', 'Dentifricio', 'Bagno'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Chiave', forbidden: ['Porta', 'Aprire', 'Serratura', 'Casa', 'Chiudere'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Ombrello', forbidden: ['Pioggia', 'Bagnato', 'Meteo', 'Riparo', 'Asciutto'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Occhiali', forbidden: ['Occhi', 'Vedere', 'Lente', 'Ottico', 'Naso'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Frigorifero', forbidden: ['Freddo', 'Cibo', 'Cucina', 'Conservare', 'Porta'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Aspirapolvere', forbidden: ['Aspirare', 'Sporco', 'Tappeto', 'Pulire', 'Pavimento'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Lavatrice', forbidden: ['Vestiti', 'Lavare', 'Acqua', 'Centrifuga', 'Bucato'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Semaforo', forbidden: ['Rosso', 'Verde', 'Giallo', 'Strada', 'Traffico'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Ascensore', forbidden: ['Salire', 'Scendere', 'Piano', 'Pulsanti', 'Palazzo'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Coperta', forbidden: ['Letto', 'Dormire', 'Caldo', 'Cuscino', 'Coprire'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Telecomando', forbidden: ['Televisione', 'Pulsanti', 'Cambiare', 'Canale', 'Divano'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Portafoglio', forbidden: ['Soldi', 'Monete', 'Carte', 'Tasca', 'Pagare'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Parcheggio', forbidden: ['Auto', 'Parcheggiare', 'Posto', 'Fermare', 'Cercare'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Bottiglia d\'acqua', forbidden: ['Acqua', 'Bere', 'Bottiglia', 'Tappo', 'Portare'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Compleanno', forbidden: ['Festeggiare', 'Torta', 'Regali', 'Candeline', 'Festa'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Supermercato', forbidden: ['Fare la spesa', 'Cassa', 'Scaffali', 'Negozio', 'Alimentari'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Parrucchiere', forbidden: ['Capelli', 'Tagliare', 'Forbici', 'Salone', 'Acconciatura'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Biblioteca', forbidden: ['Libri', 'Leggere', 'Prestare', 'Silenzio', 'Scaffali'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Ingorgo', forbidden: ['Auto', 'Strada', 'Aspettare', 'Traffico', 'Autostrada'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Palestra', forbidden: ['Sport', 'Allenarsi', 'Muscoli', 'Attrezzi', 'Pesi'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Crema solare', forbidden: ['Sole', 'Pelle', 'Protezione', 'Spiaggia', 'Spalmare'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Montagne russe', forbidden: ['Parco', 'Veloce', 'Binari', 'Curve', 'Adrenalina'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Ruota panoramica', forbidden: ['Luna park', 'Girare', 'Alto', 'Cabina', 'Vista'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Pupazzo di neve', forbidden: ['Neve', 'Inverno', 'Carota', 'Naso', 'Freddo'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Falo', forbidden: ['Fuoco', 'Legna', 'Notte', 'Caldo', 'Marshmallow'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Bolla di sapone', forbidden: ['Sapone', 'Bolla', 'Soffiare', 'Rotonda', 'Scoppiare'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Torcia', forbidden: ['Luce', 'Batteria', 'Buio', 'Illuminare', 'Lampada'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Palloncino', forbidden: ['Aria', 'Gonfiare', 'Festa', 'Colorato', 'Scoppiare'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Castello di sabbia', forbidden: ['Sabbia', 'Spiaggia', 'Costruire', 'Mare', 'Secchiello'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Puzzle', forbidden: ['Pezzi', 'Assemblare', 'Immagine', 'Rompicapo', 'Pazienza'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Casa sull\'albero', forbidden: ['Albero', 'Bambini', 'Legno', 'Alto', 'Casa'], category: 'Vita quotidiana', difficulty: 'easy' },

  // === Viaggi (18) ===
  { term: 'Valigia', forbidden: ['Viaggio', 'Preparare', 'Vestiti', 'Aeroporto', 'Vacanza'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Passaporto', forbidden: ['Confine', 'Documento', 'Foto', 'Aeroporto', 'Visto'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Albergo', forbidden: ['Camera', 'Dormire', 'Letto', 'Reception', 'Vacanza'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Aeroporto', forbidden: ['Aereo', 'Volare', 'Gate', 'Imbarco', 'Terminal'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Crociera', forbidden: ['Nave', 'Mare', 'Viaggio', 'Cabina', 'Vacanza'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Souvenir', forbidden: ['Ricordo', 'Memoria', 'Comprare', 'Vacanza', 'Regalo'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Escursione', forbidden: ['Montagna', 'Natura', 'Sentiero', 'Camminare', 'Zaino'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Campeggio', forbidden: ['Tenda', 'Natura', 'Aperto', 'Campeggio', 'Dormire'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Vacanza al mare', forbidden: ['Mare', 'Sole', 'Sabbia', 'Spiaggia', 'Nuotare'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Tour della citta', forbidden: ['Citta', 'Guida', 'Monumenti', 'Gruppo', 'Giro'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Carta d\'imbarco', forbidden: ['Aereo', 'Posto', 'Gate', 'Imbarco', 'Volare'], category: 'Viaggi', difficulty: 'medium' },
  { term: 'Jet lag', forbidden: ['Fuso orario', 'Stanco', 'Volo', 'Viaggio', 'Sonno'], category: 'Viaggi', difficulty: 'medium' },
  { term: 'Zaino in spalla', forbidden: ['Zaino', 'Viaggiare', 'Economico', 'Ostello', 'Mondo'], category: 'Viaggi', difficulty: 'medium' },
  { term: 'Viaggio in auto', forbidden: ['Auto', 'Guidare', 'Strada', 'Viaggio', 'Percorso'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Snorkeling', forbidden: ['Acqua', 'Maschera', 'Mare', 'Pesci', 'Immersione'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Mongolfiera', forbidden: ['Volare', 'Aria', 'Cesto', 'Caldo', 'Fiamma'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Escursione notturna', forbidden: ['Notte', 'Buio', 'Bosco', 'Torcia', 'Camminare'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Sacco a pelo', forbidden: ['Dormire', 'Campeggio', 'Caldo', 'Tenda', 'Notte'], category: 'Viaggi', difficulty: 'easy' },

  // === Cultura (20) ===
  { term: 'Opera', forbidden: ['Cantare', 'Palco', 'Musica', 'Teatro', 'Orchestra'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Museo', forbidden: ['Arte', 'Mostra', 'Quadri', 'Visitatori', 'Galleria'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Carnevale', forbidden: ['Costume', 'Sfilata', 'Festeggiare', 'Maschera', 'Carro'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Ferragosto', forbidden: ['Agosto', 'Vacanza', 'Estate', 'Festa', 'Spiaggia'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Mercatino di Natale', forbidden: ['Natale', 'Vin brule', 'Bancarelle', 'Regali', 'Inverno'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Balletto', forbidden: ['Danza', 'Palco', 'Punte', 'Musica', 'Lago dei cigni'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Graffiti', forbidden: ['Muro', 'Spray', 'Vernice', 'Arte', 'Strada'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Tatuaggio', forbidden: ['Pelle', 'Ago', 'Disegno', 'Corpo', 'Inchiostro'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Circo', forbidden: ['Pagliaccio', 'Acrobata', 'Tendone', 'Animali', 'Spettacolo'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Capodanno', forbidden: ['Anno nuovo', 'Fuochi', 'Mezzanotte', 'Razzi', 'Festeggiare'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Matrimonio', forbidden: ['Sposa', 'Sposo', 'Anelli', 'Chiesa', 'Sposare'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Cinema', forbidden: ['Film', 'Popcorn', 'Schermo', 'Sala', 'Biglietti'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Karaoke', forbidden: ['Cantare', 'Microfono', 'Testo', 'Canzone', 'Palco'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Festival', forbidden: ['Musica', 'All\'aperto', 'Palco', 'Band', 'Estate'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Escape Room', forbidden: ['Enigma', 'Chiuso', 'Squadra', 'Tempo', 'Indizio'], category: 'Cultura', difficulty: 'medium' },
  { term: 'Babbo Natale', forbidden: ['Natale', 'Camino', 'Regali', 'Dicembre', 'Rosso'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Coniglio di Pasqua', forbidden: ['Pasqua', 'Uova', 'Nascondere', 'Coniglio', 'Primavera'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Messaggio in bottiglia', forbidden: ['Bottiglia', 'Mare', 'Messaggio', 'Acqua', 'Isola'], category: 'Cultura', difficulty: 'medium' },
  { term: 'Torre Eiffel', forbidden: ['Parigi', 'Francia', 'Torre', 'Metallo', 'Monumento'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Colosseo', forbidden: ['Roma', 'Gladiatore', 'Anfiteatro', 'Antico', 'Italia'], category: 'Cultura', difficulty: 'easy' },

  // === Scienza (16) ===
  { term: 'Gravita', forbidden: ['Terra', 'Cadere', 'Newton', 'Fisica', 'Attirare'], category: 'Scienza', difficulty: 'medium' },
  { term: 'Fotosintesi', forbidden: ['Pianta', 'Sole', 'Luce', 'Verde', 'Ossigeno'], category: 'Scienza', difficulty: 'hard' },
  { term: 'Telescopio', forbidden: ['Stelle', 'Vedere', 'Cielo', 'Lente', 'Astronomia'], category: 'Scienza', difficulty: 'easy' },
  { term: 'DNA', forbidden: ['Geni', 'Ereditarieta', 'Cellula', 'Elica', 'Corpo'], category: 'Scienza', difficulty: 'medium' },
  { term: 'Vulcano', forbidden: ['Lava', 'Eruzione', 'Montagna', 'Caldo', 'Fuoco'], category: 'Scienza', difficulty: 'easy' },
  { term: 'Arcobaleno', forbidden: ['Colori', 'Pioggia', 'Sole', 'Arco', 'Cielo'], category: 'Scienza', difficulty: 'easy' },
  { term: 'Fossile', forbidden: ['Dinosauro', 'Antico', 'Pietra', 'Ossa', 'Scavo'], category: 'Scienza', difficulty: 'medium' },
  { term: 'Campo magnetico', forbidden: ['Bussola', 'Terra', 'Nord', 'Sud', 'Attirare'], category: 'Scienza', difficulty: 'hard' },
  { term: 'Atomo', forbidden: ['Piccolo', 'Nucleo', 'Particella', 'Fisica', 'Elettrone'], category: 'Scienza', difficulty: 'medium' },
  { term: 'Buco nero', forbidden: ['Spazio', 'Gravita', 'Luce', 'Stella', 'Inghiottire'], category: 'Scienza', difficulty: 'medium' },
  { term: 'Microscopio', forbidden: ['Piccolo', 'Ingrandire', 'Lente', 'Laboratorio', 'Vedere'], category: 'Scienza', difficulty: 'easy' },
  { term: 'Batteria', forbidden: ['Corrente', 'Energia', 'Caricare', 'Positivo', 'Negativo'], category: 'Scienza', difficulty: 'easy' },
  { term: 'Dinosauro', forbidden: ['Estinto', 'Grande', 'Rettile', 'Fossile', 'T-Rex'], category: 'Scienza', difficulty: 'easy' },
  { term: 'Sistema solare', forbidden: ['Pianeti', 'Sole', 'Terra', 'Orbita', 'Spazio'], category: 'Scienza', difficulty: 'easy' },
  { term: 'Vaccino', forbidden: ['Siringa', 'Dottore', 'Malattia', 'Protezione', 'Immunitario'], category: 'Scienza', difficulty: 'easy' },
  { term: 'Viaggio nel tempo', forbidden: ['Tempo', 'Passato', 'Futuro', 'Macchina', 'Viaggiare'], category: 'Scienza', difficulty: 'medium' },

  // === Extra misto (20) ===
  { term: 'Astronauta', forbidden: ['Spazio', 'Razzo', 'Luna', 'NASA', 'Galleggiare'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Polizia', forbidden: ['Uniforme', 'Criminale', 'Sirena', 'Legge', 'Pattuglia'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Ristorante', forbidden: ['Cibo', 'Cameriere', 'Menu', 'Chef', 'Tavolo'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Asilo', forbidden: ['Bambini', 'Giocare', 'Maestra', 'Imparare', 'Piccoli'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Occhiali da sole', forbidden: ['Sole', 'Occhi', 'Scuri', 'Estate', 'Indossare'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Giungla', forbidden: ['Foresta', 'Animali', 'Tropicale', 'Scimmie', 'Piante'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Autostrada', forbidden: ['Auto', 'Veloce', 'Strada', 'Guidare', 'Velocita'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Televisione', forbidden: ['Schermo', 'Guardare', 'Programma', 'Canale', 'Film'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Ospedale', forbidden: ['Dottore', 'Paziente', 'Malato', 'Operazione', 'Letto'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Castello', forbidden: ['Re', 'Fortezza', 'Porta', 'Chiave', 'Fiaba'], category: 'Cultura', difficulty: 'medium' },
  { term: 'Ferrovia', forbidden: ['Treno', 'Binari', 'Stazione', 'Viaggiare', 'Rotaie'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Vigili del fuoco', forbidden: ['Fuoco', 'Spegnere', 'Idrante', 'Rosso', 'Sirena'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Chitarra', forbidden: ['Corde', 'Musica', 'Suonare', 'Strumento', 'Concerto'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Pagliaccio', forbidden: ['Circo', 'Divertente', 'Naso', 'Ridere', 'Costume'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Diamante', forbidden: ['Pietra preziosa', 'Anello', 'Costoso', 'Brillare', 'Duro'], category: 'Scienza', difficulty: 'easy' },
  { term: 'Miele', forbidden: ['Ape', 'Dolce', 'Vasetto', 'Pane', 'Dorato'], category: 'Cibo', difficulty: 'easy' },
  { term: 'Faro', forbidden: ['Luce', 'Mare', 'Costa', 'Nave', 'Torre'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Aereo', forbidden: ['Volare', 'Pilota', 'Cielo', 'Aeroporto', 'Nuvole'], category: 'Viaggi', difficulty: 'easy' },
  { term: 'Dentista', forbidden: ['Denti', 'Trapano', 'Dolore', 'Studio', 'Dottore'], category: 'Vita quotidiana', difficulty: 'easy' },
  { term: 'Panettiere', forbidden: ['Pane', 'Cornetti', 'Cuocere', 'Forno', 'Farina'], category: 'Vita quotidiana', difficulty: 'easy' },
];
