export interface TabooCard {
  term: string;
  forbidden: string[];
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const TABOO_CARDS_EN: TabooCard[] = [
  // === Sports (21) ===
  { term: 'Soccer', forbidden: ['Ball', 'Goal', 'Player', 'Team', 'Stadium'], category: 'Sports', difficulty: 'easy' },
  { term: 'Tennis', forbidden: ['Racket', 'Ball', 'Net', 'Serve', 'Wimbledon'], category: 'Sports', difficulty: 'easy' },
  { term: 'Basketball', forbidden: ['Hoop', 'Ball', 'Throw', 'NBA', 'Dunk'], category: 'Sports', difficulty: 'easy' },
  { term: 'Swimming', forbidden: ['Water', 'Pool', 'Lane', 'Stroke', 'Swimsuit'], category: 'Sports', difficulty: 'easy' },
  { term: 'Boxing', forbidden: ['Fight', 'Ring', 'Gloves', 'Punch', 'Round'], category: 'Sports', difficulty: 'easy' },
  { term: 'Skiing', forbidden: ['Snow', 'Mountain', 'Slope', 'Winter', 'Lift'], category: 'Sports', difficulty: 'easy' },
  { term: 'Marathon', forbidden: ['Run', 'Kilometers', 'Distance', 'Endurance', 'Finish'], category: 'Sports', difficulty: 'medium' },
  { term: 'Golf', forbidden: ['Ball', 'Club', 'Hole', 'Green', 'Handicap'], category: 'Sports', difficulty: 'easy' },
  { term: 'Olympics', forbidden: ['Games', 'Rings', 'Medal', 'Athletes', 'Competition'], category: 'Sports', difficulty: 'easy' },
  { term: 'Surfing', forbidden: ['Wave', 'Board', 'Ocean', 'Beach', 'Water'], category: 'Sports', difficulty: 'easy' },
  { term: 'Ice Hockey', forbidden: ['Puck', 'Ice', 'Stick', 'Goal', 'Skate'], category: 'Sports', difficulty: 'easy' },
  { term: 'Yoga', forbidden: ['Stretch', 'Meditation', 'Body', 'Pose', 'Relaxation'], category: 'Sports', difficulty: 'medium' },
  { term: 'Formula 1', forbidden: ['Race', 'Car', 'Fast', 'Driver', 'Track'], category: 'Sports', difficulty: 'easy' },
  { term: 'Rock Climbing', forbidden: ['Wall', 'Rock', 'Rope', 'Height', 'Holds'], category: 'Sports', difficulty: 'easy' },
  { term: 'Handball', forbidden: ['Ball', 'Goal', 'Throw', 'Team', 'Court'], category: 'Sports', difficulty: 'easy' },
  { term: 'Biathlon', forbidden: ['Ski', 'Shooting', 'Winter', 'Rifle', 'Cross-country'], category: 'Sports', difficulty: 'hard' },
  { term: 'Darts', forbidden: ['Arrow', 'Board', 'Throw', 'Points', 'Bull'], category: 'Sports', difficulty: 'medium' },
  { term: 'Volleyball', forbidden: ['Net', 'Ball', 'Beach', 'Team', 'Spike'], category: 'Sports', difficulty: 'easy' },
  { term: 'Fencing', forbidden: ['Sword', 'Mask', 'Touch', 'Foil', 'Fight'], category: 'Sports', difficulty: 'medium' },
  { term: 'Table Tennis', forbidden: ['Ball', 'Paddle', 'Table', 'Ping', 'Pong'], category: 'Sports', difficulty: 'easy' },
  { term: 'Parachute', forbidden: ['Jump', 'Fly', 'Airplane', 'Open', 'Air'], category: 'Sports', difficulty: 'easy' },

  // === Food (27) ===
  { term: 'Pizza', forbidden: ['Italy', 'Dough', 'Topping', 'Cheese', 'Oven'], category: 'Food', difficulty: 'easy' },
  { term: 'Spaghetti', forbidden: ['Noodle', 'Italy', 'Sauce', 'Cook', 'Long'], category: 'Food', difficulty: 'easy' },
  { term: 'Chocolate', forbidden: ['Sweet', 'Cocoa', 'Brown', 'Bar', 'Milk'], category: 'Food', difficulty: 'easy' },
  { term: 'Hamburger', forbidden: ['Meat', 'Bun', 'Fast food', 'McDonalds', 'Patty'], category: 'Food', difficulty: 'easy' },
  { term: 'Ice Cream', forbidden: ['Cold', 'Summer', 'Scoop', 'Cone', 'Sweet'], category: 'Food', difficulty: 'easy' },
  { term: 'Sushi', forbidden: ['Japan', 'Rice', 'Fish', 'Seaweed', 'Raw'], category: 'Food', difficulty: 'easy' },
  { term: 'Pretzel', forbidden: ['Bakery', 'Salt', 'Dough', 'Twisted', 'German'], category: 'Food', difficulty: 'easy' },
  { term: 'Kebab', forbidden: ['Meat', 'Bread', 'Salad', 'Turkey', 'Sauce'], category: 'Food', difficulty: 'easy' },
  { term: 'Cake', forbidden: ['Bake', 'Sweet', 'Birthday', 'Cream', 'Oven'], category: 'Food', difficulty: 'easy' },
  { term: 'French Fries', forbidden: ['Potato', 'Deep-fry', 'Ketchup', 'Salty', 'Fast food'], category: 'Food', difficulty: 'easy' },
  { term: 'Salad', forbidden: ['Green', 'Healthy', 'Vegetables', 'Dressing', 'Fresh'], category: 'Food', difficulty: 'easy' },
  { term: 'Croissant', forbidden: ['France', 'Breakfast', 'Butter', 'Dough', 'Bakery'], category: 'Food', difficulty: 'easy' },
  { term: 'Hot Dog', forbidden: ['Sausage', 'Mustard', 'American', 'Bun', 'Ketchup'], category: 'Food', difficulty: 'easy' },
  { term: 'Pancake', forbidden: ['Pan', 'Dough', 'Flour', 'Egg', 'Sweet'], category: 'Food', difficulty: 'easy' },
  { term: 'Fish and Chips', forbidden: ['British', 'Fried', 'Potato', 'England', 'Newspaper'], category: 'Food', difficulty: 'easy' },
  { term: 'Fondue', forbidden: ['Cheese', 'Melt', 'Pot', 'Switzerland', 'Dip'], category: 'Food', difficulty: 'medium' },
  { term: 'Barbecue', forbidden: ['Grill', 'Meat', 'Charcoal', 'Outdoor', 'Smoke'], category: 'Food', difficulty: 'easy' },
  { term: 'Tiramisu', forbidden: ['Italy', 'Coffee', 'Mascarpone', 'Dessert', 'Cocoa'], category: 'Food', difficulty: 'medium' },
  { term: 'Goulash', forbidden: ['Meat', 'Paprika', 'Hungary', 'Stew', 'Cook'], category: 'Food', difficulty: 'medium' },
  { term: 'Cereal', forbidden: ['Breakfast', 'Oats', 'Milk', 'Fruit', 'Healthy'], category: 'Food', difficulty: 'easy' },
  { term: 'Mac and Cheese', forbidden: ['Pasta', 'Cheese', 'American', 'Comfort', 'Bake'], category: 'Food', difficulty: 'easy' },
  { term: 'Tacos', forbidden: ['Mexico', 'Corn', 'Meat', 'Salsa', 'Filling'], category: 'Food', difficulty: 'easy' },
  { term: 'Raclette', forbidden: ['Cheese', 'Melt', 'Pan', 'Potato', 'Switzerland'], category: 'Food', difficulty: 'easy' },
  { term: 'Baguette', forbidden: ['France', 'Bread', 'Long', 'Crust', 'Bakery'], category: 'Food', difficulty: 'easy' },
  { term: 'Gingerbread', forbidden: ['Christmas', 'Ginger', 'Spice', 'Sweet', 'Bake'], category: 'Food', difficulty: 'easy' },
  { term: 'Popcorn', forbidden: ['Corn', 'Cinema', 'Salty', 'Sweet', 'Movie'], category: 'Food', difficulty: 'easy' },
  { term: 'Mulled Wine', forbidden: ['Christmas', 'Warm', 'Wine', 'Spices', 'Market'], category: 'Food', difficulty: 'easy' },

  // === Animals (25) ===
  { term: 'Elephant', forbidden: ['Big', 'Trunk', 'Africa', 'Gray', 'Tusk'], category: 'Animals', difficulty: 'easy' },
  { term: 'Penguin', forbidden: ['Ice', 'Black-white', 'Antarctica', 'Bird', 'Fly'], category: 'Animals', difficulty: 'easy' },
  { term: 'Giraffe', forbidden: ['Neck', 'Long', 'Africa', 'Spots', 'Tall'], category: 'Animals', difficulty: 'easy' },
  { term: 'Dolphin', forbidden: ['Ocean', 'Swim', 'Intelligent', 'Jump', 'Flipper'], category: 'Animals', difficulty: 'easy' },
  { term: 'Chameleon', forbidden: ['Color', 'Change', 'Lizard', 'Tongue', 'Camouflage'], category: 'Animals', difficulty: 'easy' },
  { term: 'Crocodile', forbidden: ['Teeth', 'Water', 'Dangerous', 'Reptile', 'River'], category: 'Animals', difficulty: 'easy' },
  { term: 'Butterfly', forbidden: ['Wings', 'Colorful', 'Caterpillar', 'Fly', 'Flower'], category: 'Animals', difficulty: 'easy' },
  { term: 'Sloth', forbidden: ['Slow', 'Tree', 'Hang', 'Sleep', 'Lazy'], category: 'Animals', difficulty: 'easy' },
  { term: 'Shark', forbidden: ['Ocean', 'Teeth', 'Dangerous', 'Fish', 'Fin'], category: 'Animals', difficulty: 'easy' },
  { term: 'Hummingbird', forbidden: ['Small', 'Bird', 'Fly', 'Flower', 'Fast'], category: 'Animals', difficulty: 'medium' },
  { term: 'Parrot', forbidden: ['Bird', 'Talk', 'Colorful', 'Feathers', 'Pirate'], category: 'Animals', difficulty: 'easy' },
  { term: 'Polar Bear', forbidden: ['White', 'Arctic', 'Cold', 'Ice', 'Bear'], category: 'Animals', difficulty: 'easy' },
  { term: 'Flamingo', forbidden: ['Pink', 'Bird', 'Leg', 'Stand', 'Lake'], category: 'Animals', difficulty: 'easy' },
  { term: 'Kangaroo', forbidden: ['Australia', 'Hop', 'Pouch', 'Baby', 'Jump'], category: 'Animals', difficulty: 'easy' },
  { term: 'Peacock', forbidden: ['Feathers', 'Fan', 'Colorful', 'Bird', 'Male'], category: 'Animals', difficulty: 'easy' },
  { term: 'Ant', forbidden: ['Small', 'Insect', 'Hill', 'Strong', 'Colony'], category: 'Animals', difficulty: 'easy' },
  { term: 'Hippopotamus', forbidden: ['Water', 'Africa', 'Big', 'Mouth', 'River'], category: 'Animals', difficulty: 'easy' },
  { term: 'Owl', forbidden: ['Night', 'Bird', 'Eyes', 'Hoot', 'Wise'], category: 'Animals', difficulty: 'easy' },
  { term: 'Panda', forbidden: ['China', 'Bamboo', 'Black-white', 'Bear', 'Cute'], category: 'Animals', difficulty: 'easy' },
  { term: 'Turtle', forbidden: ['Shell', 'Slow', 'Old', 'Armor', 'Reptile'], category: 'Animals', difficulty: 'easy' },
  { term: 'Wolf', forbidden: ['Howl', 'Pack', 'Forest', 'Dog', 'Fairy tale'], category: 'Animals', difficulty: 'easy' },
  { term: 'Octopus', forbidden: ['Arms', 'Eight', 'Ocean', 'Ink', 'Tentacle'], category: 'Animals', difficulty: 'medium' },
  { term: 'Seahorse', forbidden: ['Ocean', 'Small', 'Horse', 'Swim', 'Water'], category: 'Animals', difficulty: 'easy' },
  { term: 'Gorilla', forbidden: ['Ape', 'Big', 'Strong', 'Jungle', 'Silverback'], category: 'Animals', difficulty: 'easy' },
  { term: 'Bee', forbidden: ['Honey', 'Sting', 'Flower', 'Fly', 'Queen'], category: 'Animals', difficulty: 'easy' },

  // === Technology (20) ===
  { term: 'Smartphone', forbidden: ['Phone', 'Mobile', 'Apple', 'Apps', 'Screen'], category: 'Technology', difficulty: 'easy' },
  { term: 'Internet', forbidden: ['Online', 'Web', 'Browse', 'Website', 'Connection'], category: 'Technology', difficulty: 'easy' },
  { term: 'Computer', forbidden: ['Machine', 'Screen', 'Keyboard', 'Mouse', 'PC'], category: 'Technology', difficulty: 'easy' },
  { term: 'Robot', forbidden: ['Machine', 'Artificial', 'Metal', 'Automatic', 'Technology'], category: 'Technology', difficulty: 'easy' },
  { term: 'Artificial Intelligence', forbidden: ['Computer', 'Robot', 'Learn', 'Machine', 'Algorithm'], category: 'Technology', difficulty: 'medium' },
  { term: 'Drone', forbidden: ['Fly', 'Camera', 'Remote', 'Propeller', 'Air'], category: 'Technology', difficulty: 'easy' },
  { term: 'WiFi', forbidden: ['Internet', 'Wireless', 'Connection', 'Router', 'Network'], category: 'Technology', difficulty: 'easy' },
  { term: 'Selfie', forbidden: ['Photo', 'Camera', 'Phone', 'Self', 'Picture'], category: 'Technology', difficulty: 'easy' },
  { term: '3D Printer', forbidden: ['Print', 'Three-dimensional', 'Plastic', 'Layer', 'Model'], category: 'Technology', difficulty: 'medium' },
  { term: 'Virtual Reality', forbidden: ['Headset', 'Virtual', 'World', 'Computer', 'Simulation'], category: 'Technology', difficulty: 'medium' },
  { term: 'Bluetooth', forbidden: ['Wireless', 'Connection', 'Phone', 'Headphones', 'Radio'], category: 'Technology', difficulty: 'easy' },
  { term: 'Streaming', forbidden: ['Movie', 'Music', 'Netflix', 'Internet', 'Video'], category: 'Technology', difficulty: 'easy' },
  { term: 'GPS', forbidden: ['Navigation', 'Location', 'Satellite', 'Map', 'Position'], category: 'Technology', difficulty: 'easy' },
  { term: 'Electric Car', forbidden: ['Power', 'Tesla', 'Battery', 'Drive', 'Charge'], category: 'Technology', difficulty: 'easy' },
  { term: 'Social Media', forbidden: ['Facebook', 'Instagram', 'Network', 'Share', 'Follower'], category: 'Technology', difficulty: 'easy' },
  { term: 'Podcast', forbidden: ['Audio', 'Listen', 'Show', 'Spotify', 'Episode'], category: 'Technology', difficulty: 'easy' },
  { term: 'Alexa', forbidden: ['Amazon', 'Voice assistant', 'Speak', 'Smart', 'Speaker'], category: 'Technology', difficulty: 'easy' },
  { term: 'Tablet', forbidden: ['iPad', 'Screen', 'Touch', 'Computer', 'Portable'], category: 'Technology', difficulty: 'easy' },
  { term: 'Algorithm', forbidden: ['Calculation', 'Computer', 'Step', 'Program', 'Logic'], category: 'Technology', difficulty: 'hard' },
  { term: 'Blockchain', forbidden: ['Bitcoin', 'Crypto', 'Decentralized', 'Chain', 'Data'], category: 'Technology', difficulty: 'hard' },

  // === Celebrities (15) ===
  { term: 'Albert Einstein', forbidden: ['Relativity', 'Physics', 'Genius', 'E=mc2', 'Hair'], category: 'Celebrities', difficulty: 'easy' },
  { term: 'Mozart', forbidden: ['Music', 'Composer', 'Salzburg', 'Piano', 'Classical'], category: 'Celebrities', difficulty: 'easy' },
  { term: 'Queen Elizabeth', forbidden: ['England', 'Queen', 'Crown', 'Monarchy', 'Buckingham'], category: 'Celebrities', difficulty: 'easy' },
  { term: 'Beethoven', forbidden: ['Music', 'Composer', 'Deaf', 'Symphony', 'Piano'], category: 'Celebrities', difficulty: 'easy' },
  { term: 'Leonardo da Vinci', forbidden: ['Mona Lisa', 'Painter', 'Inventor', 'Renaissance', 'Italy'], category: 'Celebrities', difficulty: 'easy' },
  { term: 'Cristiano Ronaldo', forbidden: ['Soccer', 'Portugal', 'Goal', 'Real Madrid', 'Striker'], category: 'Celebrities', difficulty: 'easy' },
  { term: 'Taylor Swift', forbidden: ['Singer', 'Pop', 'Music', 'America', 'Concert'], category: 'Celebrities', difficulty: 'easy' },
  { term: 'Elon Musk', forbidden: ['Tesla', 'SpaceX', 'Billionaire', 'Twitter', 'Entrepreneur'], category: 'Celebrities', difficulty: 'easy' },
  { term: 'Shakespeare', forbidden: ['Writer', 'Hamlet', 'England', 'Playwright', 'Theater'], category: 'Celebrities', difficulty: 'medium' },
  { term: 'Cleopatra', forbidden: ['Egypt', 'Queen', 'Pharaoh', 'Nile', 'Caesar'], category: 'Celebrities', difficulty: 'medium' },
  { term: 'Napoleon', forbidden: ['France', 'Emperor', 'War', 'Short', 'Waterloo'], category: 'Celebrities', difficulty: 'easy' },
  { term: 'Marie Curie', forbidden: ['Radioactivity', 'Physics', 'Nobel Prize', 'Science', 'Research'], category: 'Celebrities', difficulty: 'medium' },
  { term: 'Michael Jackson', forbidden: ['Singer', 'Thriller', 'Dance', 'Pop', 'King'], category: 'Celebrities', difficulty: 'easy' },
  { term: 'Lionel Messi', forbidden: ['Soccer', 'Argentina', 'Barcelona', 'Goal', 'World Cup'], category: 'Celebrities', difficulty: 'easy' },
  { term: 'Oprah Winfrey', forbidden: ['TV', 'Talk show', 'America', 'Billionaire', 'Media'], category: 'Celebrities', difficulty: 'easy' },

  // === Daily Life (32) ===
  { term: 'Alarm Clock', forbidden: ['Morning', 'Wake up', 'Clock', 'Ring', 'Alarm'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Toothbrush', forbidden: ['Teeth', 'Brush', 'Mouth', 'Toothpaste', 'Bathroom'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Key', forbidden: ['Door', 'Open', 'Lock', 'House', 'Close'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Umbrella', forbidden: ['Rain', 'Wet', 'Weather', 'Cover', 'Dry'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Glasses', forbidden: ['Eyes', 'See', 'Lens', 'Optician', 'Nose'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Refrigerator', forbidden: ['Cold', 'Food', 'Kitchen', 'Store', 'Door'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Vacuum Cleaner', forbidden: ['Suck', 'Dirt', 'Carpet', 'Clean', 'Floor'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Washing Machine', forbidden: ['Clothes', 'Wash', 'Water', 'Spin', 'Laundry'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Traffic Light', forbidden: ['Red', 'Green', 'Yellow', 'Street', 'Traffic'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Elevator', forbidden: ['Lift', 'Up', 'Down', 'Floor', 'Buttons'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Blanket', forbidden: ['Bed', 'Sleep', 'Warm', 'Pillow', 'Cover'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Remote Control', forbidden: ['TV', 'Buttons', 'Switch', 'Channel', 'Couch'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Wallet', forbidden: ['Money', 'Coins', 'Cards', 'Pocket', 'Pay'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Parking Lot', forbidden: ['Car', 'Park', 'Stand', 'Space', 'Search'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Water Bottle', forbidden: ['Water', 'Drink', 'Bottle', 'Lid', 'Carry'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Birthday', forbidden: ['Celebrate', 'Cake', 'Gifts', 'Candles', 'Party'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Supermarket', forbidden: ['Shopping', 'Checkout', 'Shelves', 'Store', 'Groceries'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Hairdresser', forbidden: ['Hair', 'Cut', 'Scissors', 'Salon', 'Style'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Library', forbidden: ['Books', 'Read', 'Borrow', 'Quiet', 'Shelves'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Traffic Jam', forbidden: ['Car', 'Road', 'Wait', 'Traffic', 'Highway'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Gym', forbidden: ['Sport', 'Train', 'Muscles', 'Equipment', 'Weights'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Sunscreen', forbidden: ['Sun', 'Skin', 'Protection', 'Beach', 'Apply'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Roller Coaster', forbidden: ['Theme park', 'Fast', 'Rails', 'Curves', 'Adrenaline'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Ferris Wheel', forbidden: ['Fair', 'Spin', 'High', 'Cabin', 'View'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Snowman', forbidden: ['Snow', 'Winter', 'Carrot', 'Nose', 'Cold'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Campfire', forbidden: ['Fire', 'Wood', 'Night', 'Warm', 'Marshmallow'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Soap Bubble', forbidden: ['Soap', 'Bubble', 'Blow', 'Round', 'Pop'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Flashlight', forbidden: ['Light', 'Battery', 'Dark', 'Shine', 'Lamp'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Balloon', forbidden: ['Air', 'Blow', 'Party', 'Colorful', 'Pop'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Sandcastle', forbidden: ['Sand', 'Beach', 'Build', 'Ocean', 'Bucket'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Puzzle', forbidden: ['Pieces', 'Assemble', 'Picture', 'Riddle', 'Patience'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Treehouse', forbidden: ['Tree', 'Children', 'Wood', 'Up', 'House'], category: 'Daily Life', difficulty: 'easy' },

  // === Travel (18) ===
  { term: 'Suitcase', forbidden: ['Travel', 'Pack', 'Clothes', 'Airport', 'Vacation'], category: 'Travel', difficulty: 'easy' },
  { term: 'Passport', forbidden: ['Border', 'Document', 'Photo', 'Airport', 'Visa'], category: 'Travel', difficulty: 'easy' },
  { term: 'Hotel', forbidden: ['Room', 'Stay', 'Bed', 'Reception', 'Vacation'], category: 'Travel', difficulty: 'easy' },
  { term: 'Airport', forbidden: ['Airplane', 'Fly', 'Gate', 'Boarding', 'Terminal'], category: 'Travel', difficulty: 'easy' },
  { term: 'Cruise', forbidden: ['Ship', 'Ocean', 'Travel', 'Cabin', 'Vacation'], category: 'Travel', difficulty: 'easy' },
  { term: 'Souvenir', forbidden: ['Keepsake', 'Memory', 'Buy', 'Vacation', 'Gift'], category: 'Travel', difficulty: 'easy' },
  { term: 'Hiking', forbidden: ['Mountains', 'Nature', 'Trail', 'Walk', 'Backpack'], category: 'Travel', difficulty: 'easy' },
  { term: 'Camping', forbidden: ['Tent', 'Nature', 'Outdoors', 'Campsite', 'Sleep'], category: 'Travel', difficulty: 'easy' },
  { term: 'Beach Vacation', forbidden: ['Ocean', 'Sun', 'Sand', 'Beach', 'Swim'], category: 'Travel', difficulty: 'easy' },
  { term: 'City Tour', forbidden: ['City', 'Guide', 'Sights', 'Group', 'Tour'], category: 'Travel', difficulty: 'easy' },
  { term: 'Boarding Pass', forbidden: ['Airplane', 'Seat', 'Gate', 'Boarding', 'Fly'], category: 'Travel', difficulty: 'medium' },
  { term: 'Jet Lag', forbidden: ['Time zone', 'Tired', 'Flight', 'Travel', 'Sleep'], category: 'Travel', difficulty: 'medium' },
  { term: 'Backpacking', forbidden: ['Backpack', 'Travel', 'Budget', 'Hostel', 'World'], category: 'Travel', difficulty: 'medium' },
  { term: 'Road Trip', forbidden: ['Car', 'Drive', 'Road', 'Travel', 'Route'], category: 'Travel', difficulty: 'easy' },
  { term: 'Snorkeling', forbidden: ['Water', 'Mask', 'Ocean', 'Fish', 'Dive'], category: 'Travel', difficulty: 'easy' },
  { term: 'Hot Air Balloon', forbidden: ['Fly', 'Air', 'Basket', 'Hot', 'Flame'], category: 'Travel', difficulty: 'easy' },
  { term: 'Night Hike', forbidden: ['Night', 'Dark', 'Forest', 'Flashlight', 'Walk'], category: 'Travel', difficulty: 'easy' },
  { term: 'Sleeping Bag', forbidden: ['Sleep', 'Camping', 'Warm', 'Tent', 'Night'], category: 'Travel', difficulty: 'easy' },

  // === Culture (20) ===
  { term: 'Opera', forbidden: ['Sing', 'Stage', 'Music', 'Theater', 'Orchestra'], category: 'Culture', difficulty: 'easy' },
  { term: 'Museum', forbidden: ['Art', 'Exhibition', 'Paintings', 'Visitors', 'Gallery'], category: 'Culture', difficulty: 'easy' },
  { term: 'Carnival', forbidden: ['Costume', 'Parade', 'Celebrate', 'Mask', 'Float'], category: 'Culture', difficulty: 'easy' },
  { term: 'Oktoberfest', forbidden: ['Munich', 'Beer', 'Bavaria', 'Tent', 'Lederhosen'], category: 'Culture', difficulty: 'easy' },
  { term: 'Christmas Market', forbidden: ['Christmas', 'Mulled wine', 'Stalls', 'Gifts', 'Winter'], category: 'Culture', difficulty: 'easy' },
  { term: 'Ballet', forbidden: ['Dance', 'Stage', 'Pointe shoes', 'Music', 'Swan Lake'], category: 'Culture', difficulty: 'easy' },
  { term: 'Graffiti', forbidden: ['Wall', 'Spray', 'Paint', 'Art', 'Street'], category: 'Culture', difficulty: 'easy' },
  { term: 'Tattoo', forbidden: ['Skin', 'Needle', 'Image', 'Body', 'Ink'], category: 'Culture', difficulty: 'easy' },
  { term: 'Circus', forbidden: ['Clown', 'Acrobat', 'Tent', 'Animals', 'Show'], category: 'Culture', difficulty: 'easy' },
  { term: 'New Year\'s Eve', forbidden: ['New Year', 'Fireworks', 'Midnight', 'Rockets', 'Celebrate'], category: 'Culture', difficulty: 'easy' },
  { term: 'Wedding', forbidden: ['Bride', 'Groom', 'Rings', 'Church', 'Marry'], category: 'Culture', difficulty: 'easy' },
  { term: 'Cinema', forbidden: ['Movie', 'Popcorn', 'Screen', 'Hall', 'Tickets'], category: 'Culture', difficulty: 'easy' },
  { term: 'Karaoke', forbidden: ['Sing', 'Microphone', 'Lyrics', 'Song', 'Stage'], category: 'Culture', difficulty: 'easy' },
  { term: 'Festival', forbidden: ['Music', 'Outdoor', 'Stage', 'Band', 'Summer'], category: 'Culture', difficulty: 'easy' },
  { term: 'Escape Room', forbidden: ['Puzzle', 'Locked', 'Team', 'Time', 'Clue'], category: 'Culture', difficulty: 'medium' },
  { term: 'Santa Claus', forbidden: ['Christmas', 'Stocking', 'Gifts', 'December', 'Red'], category: 'Culture', difficulty: 'easy' },
  { term: 'Easter Bunny', forbidden: ['Easter', 'Eggs', 'Hide', 'Rabbit', 'Spring'], category: 'Culture', difficulty: 'easy' },
  { term: 'Message in a Bottle', forbidden: ['Bottle', 'Ocean', 'Message', 'Water', 'Island'], category: 'Culture', difficulty: 'medium' },
  { term: 'Eiffel Tower', forbidden: ['Paris', 'France', 'Tower', 'Metal', 'Landmark'], category: 'Culture', difficulty: 'easy' },
  { term: 'Statue of Liberty', forbidden: ['New York', 'America', 'Statue', 'Torch', 'Landmark'], category: 'Culture', difficulty: 'easy' },

  // === Science (16) ===
  { term: 'Gravity', forbidden: ['Earth', 'Fall', 'Newton', 'Physics', 'Attract'], category: 'Science', difficulty: 'medium' },
  { term: 'Photosynthesis', forbidden: ['Plant', 'Sun', 'Light', 'Green', 'Oxygen'], category: 'Science', difficulty: 'hard' },
  { term: 'Telescope', forbidden: ['Stars', 'See', 'Sky', 'Lens', 'Astronomy'], category: 'Science', difficulty: 'easy' },
  { term: 'DNA', forbidden: ['Genes', 'Heredity', 'Cell', 'Helix', 'Body'], category: 'Science', difficulty: 'medium' },
  { term: 'Volcano', forbidden: ['Lava', 'Eruption', 'Mountain', 'Hot', 'Fire'], category: 'Science', difficulty: 'easy' },
  { term: 'Rainbow', forbidden: ['Colors', 'Rain', 'Sun', 'Arc', 'Sky'], category: 'Science', difficulty: 'easy' },
  { term: 'Fossil', forbidden: ['Dinosaur', 'Old', 'Stone', 'Bones', 'Dig'], category: 'Science', difficulty: 'medium' },
  { term: 'Magnetic Field', forbidden: ['Compass', 'Earth', 'North', 'South', 'Attract'], category: 'Science', difficulty: 'hard' },
  { term: 'Atom', forbidden: ['Small', 'Nucleus', 'Particle', 'Physics', 'Electron'], category: 'Science', difficulty: 'medium' },
  { term: 'Black Hole', forbidden: ['Space', 'Gravity', 'Light', 'Star', 'Swallow'], category: 'Science', difficulty: 'medium' },
  { term: 'Microscope', forbidden: ['Small', 'Magnify', 'Lens', 'Lab', 'See'], category: 'Science', difficulty: 'easy' },
  { term: 'Battery', forbidden: ['Power', 'Energy', 'Charge', 'Plus', 'Minus'], category: 'Science', difficulty: 'easy' },
  { term: 'Dinosaur', forbidden: ['Extinct', 'Big', 'Reptile', 'Fossil', 'T-Rex'], category: 'Science', difficulty: 'easy' },
  { term: 'Solar System', forbidden: ['Planets', 'Sun', 'Earth', 'Orbit', 'Space'], category: 'Science', difficulty: 'easy' },
  { term: 'Vaccination', forbidden: ['Needle', 'Doctor', 'Disease', 'Protection', 'Immune'], category: 'Science', difficulty: 'easy' },
  { term: 'Time Travel', forbidden: ['Time', 'Past', 'Future', 'Machine', 'Travel'], category: 'Science', difficulty: 'medium' },

  // === Extra mixed (20) ===
  { term: 'Astronaut', forbidden: ['Space', 'Rocket', 'Moon', 'NASA', 'Float'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Police', forbidden: ['Uniform', 'Criminal', 'Siren', 'Law', 'Patrol'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Restaurant', forbidden: ['Food', 'Waiter', 'Menu', 'Chef', 'Table'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Kindergarten', forbidden: ['Children', 'Play', 'Teacher', 'Learn', 'Small'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Sunglasses', forbidden: ['Sun', 'Eyes', 'Dark', 'Summer', 'Wear'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Jungle', forbidden: ['Forest', 'Animals', 'Tropical', 'Monkeys', 'Plants'], category: 'Travel', difficulty: 'easy' },
  { term: 'Highway', forbidden: ['Car', 'Fast', 'Road', 'Drive', 'Speed'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Television', forbidden: ['Screen', 'Watch', 'Program', 'Channel', 'Movie'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Hospital', forbidden: ['Doctor', 'Patient', 'Sick', 'Surgery', 'Bed'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Castle', forbidden: ['King', 'Fortress', 'Door', 'Key', 'Fairy tale'], category: 'Culture', difficulty: 'medium' },
  { term: 'Railroad', forbidden: ['Train', 'Rails', 'Station', 'Drive', 'Tracks'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Fire Department', forbidden: ['Fire', 'Extinguish', 'Hose', 'Red', 'Siren'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Guitar', forbidden: ['Strings', 'Music', 'Play', 'Instrument', 'Concert'], category: 'Culture', difficulty: 'easy' },
  { term: 'Clown', forbidden: ['Circus', 'Funny', 'Nose', 'Laugh', 'Costume'], category: 'Culture', difficulty: 'easy' },
  { term: 'Diamond', forbidden: ['Gemstone', 'Ring', 'Expensive', 'Sparkle', 'Hard'], category: 'Science', difficulty: 'easy' },
  { term: 'Honey', forbidden: ['Bee', 'Sweet', 'Jar', 'Bread', 'Golden'], category: 'Food', difficulty: 'easy' },
  { term: 'Lighthouse', forbidden: ['Light', 'Ocean', 'Coast', 'Ship', 'Tower'], category: 'Travel', difficulty: 'easy' },
  { term: 'Airplane', forbidden: ['Fly', 'Pilot', 'Sky', 'Airport', 'Clouds'], category: 'Travel', difficulty: 'easy' },
  { term: 'Dentist', forbidden: ['Teeth', 'Drill', 'Pain', 'Office', 'Doctor'], category: 'Daily Life', difficulty: 'easy' },
  { term: 'Baker', forbidden: ['Bread', 'Rolls', 'Bake', 'Oven', 'Flour'], category: 'Daily Life', difficulty: 'easy' },
];
