export interface TabooCard {
  term: string;
  forbidden: [string, string, string, string, string];
}

export const TABOO_CARDS_DE: TabooCard[] = [
  { term: 'Hochzeit', forbidden: ['Braut', 'Trauung', 'Ring', 'Kirche', 'heiraten'] },
  { term: 'Geburtstag', forbidden: ['Kerzen', 'Kuchen', 'Geschenk', 'Feier', 'Party'] },
  { term: 'Strand', forbidden: ['Sand', 'Meer', 'Wasser', 'Sonne', 'Urlaub'] },
  { term: 'Weihnachten', forbidden: ['Geschenke', 'Baum', 'Dezember', 'Schnee', 'Nikolaus'] },
  { term: 'Fussball', forbidden: ['Ball', 'Tor', 'Spieler', 'Stadion', 'Mannschaft'] },
  { term: 'Schokolade', forbidden: ['Kakao', 'braun', 'Tafel', 'Milch', 'Zucker'] },
  { term: 'Flugzeug', forbidden: ['fliegen', 'Pilot', 'Himmel', 'Flughafen', 'Wolken'] },
  { term: 'Smartphone', forbidden: ['Handy', 'Telefon', 'App', 'Bildschirm', 'Apple'] },
  { term: 'Polizei', forbidden: ['Uniform', 'Verbrecher', 'Sirene', 'Gesetz', 'Streife'] },
  { term: 'Restaurant', forbidden: ['Essen', 'Kellner', 'Speisekarte', 'Koch', 'Tisch'] },
  { term: 'Elefant', forbidden: ['Tier', 'Russel', 'Afrika', 'gross', 'grau'] },
  { term: 'Zahnarzt', forbidden: ['Zahne', 'Bohren', 'Schmerz', 'Praxis', 'Arzt'] },
  { term: 'Karneval', forbidden: ['Kostum', 'Fasching', 'Koln', 'Maske', 'Umzug'] },
  { term: 'Pizza', forbidden: ['Italien', 'Kase', 'Teig', 'Ofen', 'Salami'] },
  { term: 'Kindergarten', forbidden: ['Kinder', 'spielen', 'Erzieherin', 'lernen', 'klein'] },
  { term: 'Silvester', forbidden: ['Rakete', 'Feuerwerk', 'Mitternacht', 'Neujahr', 'Sekt'] },
  { term: 'Bibliothek', forbidden: ['Bucher', 'lesen', 'leise', 'ausleihen', 'Regal'] },
  { term: 'Camping', forbidden: ['Zelt', 'Natur', 'schlafen', 'Lagerfeuer', 'draussen'] },
  { term: 'Sonnenbrille', forbidden: ['Sonne', 'Augen', 'dunkel', 'Sommer', 'tragen'] },
  { term: 'Oktoberfest', forbidden: ['Bier', 'Munchen', 'Tracht', 'Zelt', 'Bayern'] },
  { term: 'Regenschirm', forbidden: ['Regen', 'nass', 'Wetter', 'Schutz', 'Schirm'] },
  { term: 'Astronaut', forbidden: ['Weltraum', 'Rakete', 'Mond', 'NASA', 'schweben'] },
  { term: 'Backer', forbidden: ['Brot', 'Brotchen', 'backen', 'Ofen', 'Mehl'] },
  { term: 'Dschungel', forbidden: ['Wald', 'Tiere', 'tropisch', 'Affen', 'Pflanzen'] },
  { term: 'Autobahn', forbidden: ['Auto', 'schnell', 'Strasse', 'fahren', 'Geschwindigkeit'] },
  { term: 'Fernseher', forbidden: ['Bildschirm', 'schauen', 'Programm', 'Sender', 'Film'] },
  { term: 'Krankenhaus', forbidden: ['Arzt', 'Patient', 'krank', 'Operation', 'Bett'] },
  { term: 'Schloss', forbidden: ['Konig', 'Burg', 'Tur', 'Schlussel', 'Marchen'] },
  { term: 'Supermarkt', forbidden: ['einkaufen', 'Kasse', 'Regal', 'Lebensmittel', 'Wagen'] },
  { term: 'Vulkan', forbidden: ['Lava', 'Ausbruch', 'Berg', 'heiss', 'Feuer'] },
  { term: 'Eisenbahn', forbidden: ['Zug', 'Schienen', 'Bahnhof', 'fahren', 'Gleise'] },
  { term: 'Pinguin', forbidden: ['Vogel', 'Eis', 'schwarz', 'weiss', 'Antarktis'] },
  { term: 'Feuerwehr', forbidden: ['Brand', 'loschen', 'Schlauch', 'rot', 'Sirene'] },
  { term: 'Gitarre', forbidden: ['Saiten', 'Musik', 'spielen', 'Instrument', 'Konzert'] },
  { term: 'Waschmaschine', forbidden: ['Wasche', 'waschen', 'Trommel', 'Wasser', 'Schleudern'] },
  { term: 'Clown', forbidden: ['Zirkus', 'lustig', 'Nase', 'lachen', 'Kostum'] },
  { term: 'Diamant', forbidden: ['Edelstein', 'Ring', 'teuer', 'glitzern', 'hart'] },
  { term: 'Fallschirm', forbidden: ['springen', 'Flugzeug', 'fliegen', 'Luft', 'Hohe'] },
  { term: 'Honig', forbidden: ['Biene', 'suss', 'Glas', 'Brot', 'gold'] },
  { term: 'Leuchtturm', forbidden: ['Licht', 'Meer', 'Kuste', 'Schiff', 'Turm'] },
];
