export interface TabooCard {
  term: string;
  forbidden: string[];
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const TABOO_CARDS_AR: TabooCard[] = [
  // === رياضة (21) ===
  { term: 'كرة القدم', forbidden: ['كرة', 'هدف', 'لاعب', 'فريق', 'ملعب'], category: 'رياضة', difficulty: 'easy' },
  { term: 'التنس', forbidden: ['مضرب', 'كرة', 'شبكة', 'إرسال', 'ويمبلدون'], category: 'رياضة', difficulty: 'easy' },
  { term: 'كرة السلة', forbidden: ['سلة', 'كرة', 'رمي', 'إن بي إيه', 'تسديدة'], category: 'رياضة', difficulty: 'easy' },
  { term: 'السباحة', forbidden: ['ماء', 'مسبح', 'حارة', 'سباحة', 'مايوه'], category: 'رياضة', difficulty: 'easy' },
  { term: 'الملاكمة', forbidden: ['قتال', 'حلبة', 'قفازات', 'لكمة', 'جولة'], category: 'رياضة', difficulty: 'easy' },
  { term: 'التزلج', forbidden: ['ثلج', 'جبل', 'منحدر', 'شتاء', 'تلفريك'], category: 'رياضة', difficulty: 'easy' },
  { term: 'الماراثون', forbidden: ['جري', 'كيلومتر', 'مسافة', 'تحمل', 'نهاية'], category: 'رياضة', difficulty: 'medium' },
  { term: 'الغولف', forbidden: ['كرة', 'عصا', 'حفرة', 'عشب', 'هانديكاب'], category: 'رياضة', difficulty: 'easy' },
  { term: 'الأولمبياد', forbidden: ['ألعاب', 'حلقات', 'ميدالية', 'رياضيون', 'منافسة'], category: 'رياضة', difficulty: 'easy' },
  { term: 'ركوب الأمواج', forbidden: ['موجة', 'لوح', 'بحر', 'شاطئ', 'ماء'], category: 'رياضة', difficulty: 'easy' },
  { term: 'هوكي الجليد', forbidden: ['قرص', 'جليد', 'عصا', 'مرمى', 'تزلج'], category: 'رياضة', difficulty: 'easy' },
  { term: 'اليوغا', forbidden: ['تمدد', 'تأمل', 'جسم', 'وضعية', 'استرخاء'], category: 'رياضة', difficulty: 'medium' },
  { term: 'فورمولا 1', forbidden: ['سباق', 'سيارة', 'سريع', 'سائق', 'حلبة'], category: 'رياضة', difficulty: 'easy' },
  { term: 'تسلق الصخور', forbidden: ['جدار', 'صخرة', 'حبل', 'ارتفاع', 'مقابض'], category: 'رياضة', difficulty: 'easy' },
  { term: 'كرة اليد', forbidden: ['كرة', 'مرمى', 'رمي', 'فريق', 'صالة'], category: 'رياضة', difficulty: 'easy' },
  { term: 'البياتلون', forbidden: ['تزلج', 'رماية', 'شتاء', 'بندقية', 'ريفي'], category: 'رياضة', difficulty: 'hard' },
  { term: 'رمي السهام', forbidden: ['سهم', 'هدف', 'رمي', 'نقاط', 'مركز'], category: 'رياضة', difficulty: 'medium' },
  { term: 'الكرة الطائرة', forbidden: ['شبكة', 'كرة', 'شاطئ', 'فريق', 'ضربة'], category: 'رياضة', difficulty: 'easy' },
  { term: 'المبارزة', forbidden: ['سيف', 'قناع', 'لمسة', 'شيش', 'قتال'], category: 'رياضة', difficulty: 'medium' },
  { term: 'تنس الطاولة', forbidden: ['كرة', 'مضرب', 'طاولة', 'بينغ', 'بونغ'], category: 'رياضة', difficulty: 'easy' },
  { term: 'المظلة', forbidden: ['قفز', 'طيران', 'طائرة', 'فتح', 'هواء'], category: 'رياضة', difficulty: 'easy' },

  // === طعام (27) ===
  { term: 'بيتزا', forbidden: ['إيطاليا', 'عجين', 'إضافات', 'جبن', 'فرن'], category: 'طعام', difficulty: 'easy' },
  { term: 'سباغيتي', forbidden: ['معكرونة', 'إيطاليا', 'صلصة', 'طبخ', 'طويل'], category: 'طعام', difficulty: 'easy' },
  { term: 'شوكولاتة', forbidden: ['حلو', 'كاكاو', 'بني', 'لوح', 'حليب'], category: 'طعام', difficulty: 'easy' },
  { term: 'هامبرغر', forbidden: ['لحم', 'خبز', 'وجبة سريعة', 'ماكدونالدز', 'لحم مفروم'], category: 'طعام', difficulty: 'easy' },
  { term: 'آيس كريم', forbidden: ['بارد', 'صيف', 'كرة', 'قمع', 'حلو'], category: 'طعام', difficulty: 'easy' },
  { term: 'سوشي', forbidden: ['اليابان', 'أرز', 'سمك', 'أعشاب بحرية', 'نيء'], category: 'طعام', difficulty: 'easy' },
  { term: 'فلافل', forbidden: ['حمص', 'مقلي', 'خبز', 'طحينة', 'كرات'], category: 'طعام', difficulty: 'easy' },
  { term: 'شاورما', forbidden: ['لحم', 'خبز', 'سلطة', 'دوران', 'صلصة'], category: 'طعام', difficulty: 'easy' },
  { term: 'كعكة', forbidden: ['خبز', 'حلو', 'عيد ميلاد', 'كريمة', 'فرن'], category: 'طعام', difficulty: 'easy' },
  { term: 'بطاطس مقلية', forbidden: ['بطاطس', 'قلي', 'كاتشب', 'مالح', 'وجبة سريعة'], category: 'طعام', difficulty: 'easy' },
  { term: 'سلطة', forbidden: ['أخضر', 'صحي', 'خضروات', 'صلصة', 'طازج'], category: 'طعام', difficulty: 'easy' },
  { term: 'كرواسون', forbidden: ['فرنسا', 'إفطار', 'زبدة', 'عجين', 'مخبز'], category: 'طعام', difficulty: 'easy' },
  { term: 'كشري', forbidden: ['مصر', 'عدس', 'أرز', 'معكرونة', 'صلصة'], category: 'طعام', difficulty: 'easy' },
  { term: 'حمص', forbidden: ['حمص', 'طحينة', 'زيت زيتون', 'خبز', 'ليمون'], category: 'طعام', difficulty: 'easy' },
  { term: 'منسف', forbidden: ['أردن', 'لحم', 'أرز', 'لبن', 'ضيافة'], category: 'طعام', difficulty: 'easy' },
  { term: 'فوندو', forbidden: ['جبن', 'ذوبان', 'قدر', 'سويسرا', 'غمس'], category: 'طعام', difficulty: 'medium' },
  { term: 'ملوخية', forbidden: ['خضراء', 'مصر', 'أرز', 'دجاج', 'طبخ'], category: 'طعام', difficulty: 'easy' },
  { term: 'تيراميسو', forbidden: ['إيطاليا', 'قهوة', 'ماسكاربوني', 'حلوى', 'كاكاو'], category: 'طعام', difficulty: 'medium' },
  { term: 'كباب', forbidden: ['لحم', 'سيخ', 'شواء', 'فحم', 'خبز'], category: 'طعام', difficulty: 'easy' },
  { term: 'جرانولا', forbidden: ['إفطار', 'شوفان', 'حليب', 'فواكه', 'صحي'], category: 'طعام', difficulty: 'easy' },
  { term: 'ورق عنب', forbidden: ['ورق', 'أرز', 'لحم', 'لف', 'ليمون'], category: 'طعام', difficulty: 'easy' },
  { term: 'تاكو', forbidden: ['المكسيك', 'ذرة', 'لحم', 'صلصة', 'حشوة'], category: 'طعام', difficulty: 'easy' },
  { term: 'راكليت', forbidden: ['جبن', 'ذوبان', 'صينية', 'بطاطس', 'سويسرا'], category: 'طعام', difficulty: 'easy' },
  { term: 'خبز فرنسي', forbidden: ['فرنسا', 'خبز', 'طويل', 'قشرة', 'مخبز'], category: 'طعام', difficulty: 'easy' },
  { term: 'بقلاوة', forbidden: ['حلوى', 'عجين', 'فستق', 'شيرة', 'طبقات'], category: 'طعام', difficulty: 'easy' },
  { term: 'فشار', forbidden: ['ذرة', 'سينما', 'مالح', 'حلو', 'فيلم'], category: 'طعام', difficulty: 'easy' },
  { term: 'سحلب', forbidden: ['شتاء', 'ساخن', 'حليب', 'قرفة', 'مشروب'], category: 'طعام', difficulty: 'easy' },

  // === حيوانات (25) ===
  { term: 'فيل', forbidden: ['كبير', 'خرطوم', 'أفريقيا', 'رمادي', 'ناب'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'بطريق', forbidden: ['جليد', 'أسود وأبيض', 'القطب', 'طائر', 'طيران'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'زرافة', forbidden: ['رقبة', 'طويل', 'أفريقيا', 'بقع', 'طويل القامة'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'دلفين', forbidden: ['بحر', 'سباحة', 'ذكي', 'قفز', 'فليبر'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'حرباء', forbidden: ['لون', 'تغيير', 'سحلية', 'لسان', 'تمويه'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'تمساح', forbidden: ['أسنان', 'ماء', 'خطير', 'زاحف', 'نهر'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'فراشة', forbidden: ['أجنحة', 'ملونة', 'يرقة', 'طيران', 'زهرة'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'كسلان', forbidden: ['بطيء', 'شجرة', 'تعلق', 'نوم', 'كسول'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'قرش', forbidden: ['بحر', 'أسنان', 'خطير', 'سمكة', 'زعنفة'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'طائر الطنان', forbidden: ['صغير', 'طائر', 'طيران', 'زهرة', 'سريع'], category: 'حيوانات', difficulty: 'medium' },
  { term: 'ببغاء', forbidden: ['طائر', 'كلام', 'ملون', 'ريش', 'قرصان'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'الدب القطبي', forbidden: ['أبيض', 'القطب', 'بارد', 'جليد', 'دب'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'فلامنغو', forbidden: ['وردي', 'طائر', 'ساق', 'وقوف', 'بحيرة'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'كنغر', forbidden: ['أستراليا', 'قفز', 'جراب', 'صغير', 'نط'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'طاووس', forbidden: ['ريش', 'مروحة', 'ملون', 'طائر', 'ذكر'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'نملة', forbidden: ['صغيرة', 'حشرة', 'مستعمرة', 'قوية', 'عش'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'فرس النهر', forbidden: ['ماء', 'أفريقيا', 'كبير', 'فم', 'نهر'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'بومة', forbidden: ['ليل', 'طائر', 'عيون', 'صوت', 'حكيمة'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'باندا', forbidden: ['الصين', 'خيزران', 'أسود وأبيض', 'دب', 'لطيف'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'سلحفاة', forbidden: ['صدفة', 'بطيء', 'عمر', 'درع', 'زاحف'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'ذئب', forbidden: ['عواء', 'قطيع', 'غابة', 'كلب', 'قصة'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'أخطبوط', forbidden: ['أذرع', 'ثمانية', 'بحر', 'حبر', 'مخالب'], category: 'حيوانات', difficulty: 'medium' },
  { term: 'حصان البحر', forbidden: ['بحر', 'صغير', 'حصان', 'سباحة', 'ماء'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'غوريلا', forbidden: ['قرد', 'كبير', 'قوي', 'غابة', 'ظهر فضي'], category: 'حيوانات', difficulty: 'easy' },
  { term: 'نحلة', forbidden: ['عسل', 'لسع', 'زهرة', 'طيران', 'ملكة'], category: 'حيوانات', difficulty: 'easy' },

  // === تكنولوجيا (20) ===
  { term: 'هاتف ذكي', forbidden: ['هاتف', 'جوال', 'آبل', 'تطبيقات', 'شاشة'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'إنترنت', forbidden: ['أونلاين', 'شبكة', 'تصفح', 'موقع', 'اتصال'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'كمبيوتر', forbidden: ['آلة', 'شاشة', 'لوحة مفاتيح', 'فأرة', 'حاسوب'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'روبوت', forbidden: ['آلة', 'صناعي', 'معدن', 'تلقائي', 'تكنولوجيا'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'ذكاء اصطناعي', forbidden: ['كمبيوتر', 'روبوت', 'تعلم', 'آلة', 'خوارزمية'], category: 'تكنولوجيا', difficulty: 'medium' },
  { term: 'طائرة بدون طيار', forbidden: ['طيران', 'كاميرا', 'تحكم عن بعد', 'مروحة', 'هواء'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'واي فاي', forbidden: ['إنترنت', 'لاسلكي', 'اتصال', 'راوتر', 'شبكة'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'سيلفي', forbidden: ['صورة', 'كاميرا', 'هاتف', 'نفس', 'ذاتية'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'طابعة ثلاثية الأبعاد', forbidden: ['طباعة', 'ثلاثي', 'بلاستيك', 'طبقة', 'نموذج'], category: 'تكنولوجيا', difficulty: 'medium' },
  { term: 'واقع افتراضي', forbidden: ['نظارة', 'افتراضي', 'عالم', 'كمبيوتر', 'محاكاة'], category: 'تكنولوجيا', difficulty: 'medium' },
  { term: 'بلوتوث', forbidden: ['لاسلكي', 'اتصال', 'هاتف', 'سماعة', 'راديو'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'بث مباشر', forbidden: ['فيلم', 'موسيقى', 'نتفليكس', 'إنترنت', 'فيديو'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'نظام تحديد المواقع', forbidden: ['ملاحة', 'موقع', 'قمر صناعي', 'خريطة', 'موضع'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'سيارة كهربائية', forbidden: ['كهرباء', 'تسلا', 'بطارية', 'قيادة', 'شحن'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'وسائل التواصل', forbidden: ['فيسبوك', 'إنستغرام', 'شبكة', 'مشاركة', 'متابعين'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'بودكاست', forbidden: ['صوت', 'استماع', 'برنامج', 'سبوتيفاي', 'حلقة'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'أليكسا', forbidden: ['أمازون', 'مساعد صوتي', 'تحدث', 'ذكي', 'مكبر صوت'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'جهاز لوحي', forbidden: ['آيباد', 'شاشة', 'لمس', 'كمبيوتر', 'محمول'], category: 'تكنولوجيا', difficulty: 'easy' },
  { term: 'خوارزمية', forbidden: ['حساب', 'كمبيوتر', 'خطوة', 'برنامج', 'منطق'], category: 'تكنولوجيا', difficulty: 'hard' },
  { term: 'بلوكتشين', forbidden: ['بيتكوين', 'عملة رقمية', 'لامركزي', 'سلسلة', 'بيانات'], category: 'تكنولوجيا', difficulty: 'hard' },

  // === مشاهير (15) ===
  { term: 'ألبرت أينشتاين', forbidden: ['نسبية', 'فيزياء', 'عبقري', 'معادلة', 'شعر'], category: 'مشاهير', difficulty: 'easy' },
  { term: 'موتسارت', forbidden: ['موسيقى', 'ملحن', 'سالزبورغ', 'بيانو', 'كلاسيكي'], category: 'مشاهير', difficulty: 'easy' },
  { term: 'أم كلثوم', forbidden: ['غناء', 'مصر', 'كوكب الشرق', 'صوت', 'طرب'], category: 'مشاهير', difficulty: 'easy' },
  { term: 'بيتهوفن', forbidden: ['موسيقى', 'ملحن', 'أصم', 'سيمفونية', 'بيانو'], category: 'مشاهير', difficulty: 'easy' },
  { term: 'ليوناردو دا فينشي', forbidden: ['موناليزا', 'رسام', 'مخترع', 'عصر النهضة', 'إيطاليا'], category: 'مشاهير', difficulty: 'easy' },
  { term: 'كريستيانو رونالدو', forbidden: ['كرة قدم', 'البرتغال', 'هدف', 'ريال مدريد', 'مهاجم'], category: 'مشاهير', difficulty: 'easy' },
  { term: 'محمد صلاح', forbidden: ['كرة قدم', 'مصر', 'ليفربول', 'هدف', 'جناح'], category: 'مشاهير', difficulty: 'easy' },
  { term: 'إيلون ماسك', forbidden: ['تسلا', 'سبيس إكس', 'ملياردير', 'تويتر', 'رائد أعمال'], category: 'مشاهير', difficulty: 'easy' },
  { term: 'نجيب محفوظ', forbidden: ['كاتب', 'نوبل', 'مصر', 'رواية', 'أدب'], category: 'مشاهير', difficulty: 'medium' },
  { term: 'كليوباترا', forbidden: ['مصر', 'ملكة', 'فرعون', 'نيل', 'قيصر'], category: 'مشاهير', difficulty: 'medium' },
  { term: 'نابليون', forbidden: ['فرنسا', 'إمبراطور', 'حرب', 'قصير', 'واترلو'], category: 'مشاهير', difficulty: 'easy' },
  { term: 'ماري كوري', forbidden: ['إشعاع', 'فيزياء', 'نوبل', 'علم', 'بحث'], category: 'مشاهير', difficulty: 'medium' },
  { term: 'مايكل جاكسون', forbidden: ['مغني', 'ثريلر', 'رقص', 'بوب', 'ملك'], category: 'مشاهير', difficulty: 'easy' },
  { term: 'ليونيل ميسي', forbidden: ['كرة قدم', 'الأرجنتين', 'برشلونة', 'هدف', 'كأس العالم'], category: 'مشاهير', difficulty: 'easy' },
  { term: 'صلاح الدين الأيوبي', forbidden: ['قائد', 'القدس', 'حروب', 'إسلام', 'بطل'], category: 'مشاهير', difficulty: 'easy' },

  // === حياة يومية (32) ===
  { term: 'منبه', forbidden: ['صباح', 'استيقاظ', 'ساعة', 'رنين', 'إنذار'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'فرشاة أسنان', forbidden: ['أسنان', 'تنظيف', 'فم', 'معجون', 'حمام'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'مفتاح', forbidden: ['باب', 'فتح', 'قفل', 'بيت', 'إغلاق'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'مظلة', forbidden: ['مطر', 'مبلل', 'طقس', 'حماية', 'جاف'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'نظارات', forbidden: ['عيون', 'رؤية', 'عدسة', 'بصريات', 'أنف'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'ثلاجة', forbidden: ['بارد', 'طعام', 'مطبخ', 'تخزين', 'باب'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'مكنسة كهربائية', forbidden: ['شفط', 'أوساخ', 'سجادة', 'تنظيف', 'أرضية'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'غسالة', forbidden: ['ملابس', 'غسل', 'ماء', 'عصر', 'غسيل'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'إشارة مرور', forbidden: ['أحمر', 'أخضر', 'أصفر', 'شارع', 'مرور'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'مصعد', forbidden: ['أعلى', 'أسفل', 'طابق', 'أزرار', 'مبنى'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'غطاء', forbidden: ['سرير', 'نوم', 'دافئ', 'وسادة', 'تغطية'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'جهاز تحكم', forbidden: ['تلفزيون', 'أزرار', 'تغيير', 'قناة', 'أريكة'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'محفظة', forbidden: ['نقود', 'عملات', 'بطاقات', 'جيب', 'دفع'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'موقف سيارات', forbidden: ['سيارة', 'ركن', 'وقوف', 'مكان', 'بحث'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'قارورة ماء', forbidden: ['ماء', 'شرب', 'زجاجة', 'غطاء', 'حمل'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'عيد ميلاد', forbidden: ['احتفال', 'كعكة', 'هدايا', 'شموع', 'حفلة'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'سوبر ماركت', forbidden: ['تسوق', 'كاشير', 'رفوف', 'محل', 'طعام'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'حلاق', forbidden: ['شعر', 'قص', 'مقص', 'صالون', 'تسريحة'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'مكتبة', forbidden: ['كتب', 'قراءة', 'استعارة', 'هدوء', 'رفوف'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'ازدحام', forbidden: ['سيارة', 'طريق', 'انتظار', 'مرور', 'طريق سريع'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'صالة رياضية', forbidden: ['رياضة', 'تدريب', 'عضلات', 'أجهزة', 'أوزان'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'واقي شمس', forbidden: ['شمس', 'بشرة', 'حماية', 'شاطئ', 'وضع'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'أفعوانية', forbidden: ['متنزه', 'سريع', 'قضبان', 'منحنيات', 'أدرينالين'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'عجلة دوارة', forbidden: ['ملاهي', 'دوران', 'عالي', 'كابينة', 'منظر'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'رجل ثلج', forbidden: ['ثلج', 'شتاء', 'جزر', 'أنف', 'بارد'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'نار مخيم', forbidden: ['نار', 'حطب', 'ليل', 'دافئ', 'مارشملو'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'فقاعة صابون', forbidden: ['صابون', 'فقاعة', 'نفخ', 'دائرية', 'انفجار'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'كشاف', forbidden: ['ضوء', 'بطارية', 'ظلام', 'إنارة', 'مصباح'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'بالون', forbidden: ['هواء', 'نفخ', 'حفلة', 'ملون', 'انفجار'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'قلعة رمل', forbidden: ['رمل', 'شاطئ', 'بناء', 'بحر', 'دلو'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'أحجية', forbidden: ['قطع', 'تجميع', 'صورة', 'لغز', 'صبر'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'بيت شجرة', forbidden: ['شجرة', 'أطفال', 'خشب', 'أعلى', 'بيت'], category: 'حياة يومية', difficulty: 'easy' },

  // === سفر + ثقافة + علوم + إضافي ===
  { term: 'حقيبة سفر', forbidden: ['سفر', 'حزم', 'ملابس', 'مطار', 'إجازة'], category: 'سفر', difficulty: 'easy' },
  { term: 'جواز سفر', forbidden: ['حدود', 'وثيقة', 'صورة', 'مطار', 'تأشيرة'], category: 'سفر', difficulty: 'easy' },
  { term: 'فندق', forbidden: ['غرفة', 'مبيت', 'سرير', 'استقبال', 'إجازة'], category: 'سفر', difficulty: 'easy' },
  { term: 'مطار', forbidden: ['طائرة', 'طيران', 'بوابة', 'صعود', 'محطة'], category: 'سفر', difficulty: 'easy' },
  { term: 'رحلة بحرية', forbidden: ['سفينة', 'بحر', 'سفر', 'كابينة', 'إجازة'], category: 'سفر', difficulty: 'easy' },
  { term: 'أوبرا', forbidden: ['غناء', 'مسرح', 'موسيقى', 'خشبة', 'أوركسترا'], category: 'ثقافة', difficulty: 'easy' },
  { term: 'متحف', forbidden: ['فن', 'معرض', 'لوحات', 'زوار', 'صالة'], category: 'ثقافة', difficulty: 'easy' },
  { term: 'زفاف', forbidden: ['عروس', 'عريس', 'خواتم', 'مسجد', 'زواج'], category: 'ثقافة', difficulty: 'easy' },
  { term: 'سينما', forbidden: ['فيلم', 'فشار', 'شاشة', 'صالة', 'تذاكر'], category: 'ثقافة', difficulty: 'easy' },
  { term: 'أهرامات الجيزة', forbidden: ['مصر', 'فراعنة', 'صحراء', 'قديم', 'عجائب'], category: 'ثقافة', difficulty: 'easy' },
  { term: 'الجاذبية', forbidden: ['أرض', 'سقوط', 'نيوتن', 'فيزياء', 'جذب'], category: 'علوم', difficulty: 'medium' },
  { term: 'بركان', forbidden: ['حمم', 'ثوران', 'جبل', 'حار', 'نار'], category: 'علوم', difficulty: 'easy' },
  { term: 'قوس قزح', forbidden: ['ألوان', 'مطر', 'شمس', 'قوس', 'سماء'], category: 'علوم', difficulty: 'easy' },
  { term: 'ديناصور', forbidden: ['منقرض', 'كبير', 'زاحف', 'أحفورة', 'تي ركس'], category: 'علوم', difficulty: 'easy' },
  { term: 'رائد فضاء', forbidden: ['فضاء', 'صاروخ', 'قمر', 'ناسا', 'طفو'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'مطعم', forbidden: ['طعام', 'نادل', 'قائمة', 'طاهي', 'طاولة'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'مستشفى', forbidden: ['طبيب', 'مريض', 'مرض', 'عملية', 'سرير'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'تلفزيون', forbidden: ['شاشة', 'مشاهدة', 'برنامج', 'قناة', 'فيلم'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'طبيب أسنان', forbidden: ['أسنان', 'حفر', 'ألم', 'عيادة', 'دكتور'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'خباز', forbidden: ['خبز', 'معجنات', 'خبز', 'فرن', 'طحين'], category: 'حياة يومية', difficulty: 'easy' },
  { term: 'طائرة', forbidden: ['طيران', 'طيار', 'سماء', 'مطار', 'غيوم'], category: 'سفر', difficulty: 'easy' },
  { term: 'منارة', forbidden: ['ضوء', 'بحر', 'ساحل', 'سفينة', 'برج'], category: 'سفر', difficulty: 'easy' },
  { term: 'غيتار', forbidden: ['أوتار', 'موسيقى', 'عزف', 'آلة', 'حفلة'], category: 'ثقافة', difficulty: 'easy' },
];
