export interface TabooCard {
  term: string;
  forbidden: string[];
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const TABOO_CARDS_NL: TabooCard[] = [
  // === Sport (21) ===
  { term: 'Voetbal', forbidden: ['Bal', 'Doel', 'Speler', 'Team', 'Stadion'], category: 'Sport', difficulty: 'easy' },
  { term: 'Tennis', forbidden: ['Racket', 'Bal', 'Net', 'Opslag', 'Wimbledon'], category: 'Sport', difficulty: 'easy' },
  { term: 'Basketbal', forbidden: ['Basket', 'Bal', 'Gooien', 'NBA', 'Dunk'], category: 'Sport', difficulty: 'easy' },
  { term: 'Zwemmen', forbidden: ['Water', 'Zwembad', 'Baan', 'Slag', 'Badpak'], category: 'Sport', difficulty: 'easy' },
  { term: 'Boksen', forbidden: ['Gevecht', 'Ring', 'Handschoenen', 'Klap', 'Ronde'], category: 'Sport', difficulty: 'easy' },
  { term: 'Skieen', forbidden: ['Sneeuw', 'Berg', 'Piste', 'Winter', 'Lift'], category: 'Sport', difficulty: 'easy' },
  { term: 'Marathon', forbidden: ['Rennen', 'Kilometer', 'Afstand', 'Uithoudingsvermogen', 'Finish'], category: 'Sport', difficulty: 'medium' },
  { term: 'Golf', forbidden: ['Bal', 'Club', 'Hole', 'Gras', 'Handicap'], category: 'Sport', difficulty: 'easy' },
  { term: 'Olympische Spelen', forbidden: ['Spelen', 'Ringen', 'Medaille', 'Atleten', 'Wedstrijd'], category: 'Sport', difficulty: 'easy' },
  { term: 'Surfen', forbidden: ['Golf', 'Plank', 'Zee', 'Strand', 'Water'], category: 'Sport', difficulty: 'easy' },
  { term: 'IJshockey', forbidden: ['Puck', 'IJs', 'Stick', 'Doel', 'Schaats'], category: 'Sport', difficulty: 'easy' },
  { term: 'Yoga', forbidden: ['Rekken', 'Meditatie', 'Lichaam', 'Houding', 'Ontspanning'], category: 'Sport', difficulty: 'medium' },
  { term: 'Formule 1', forbidden: ['Race', 'Auto', 'Snel', 'Coureur', 'Circuit'], category: 'Sport', difficulty: 'easy' },
  { term: 'Klimmen', forbidden: ['Muur', 'Rots', 'Touw', 'Hoogte', 'Grepen'], category: 'Sport', difficulty: 'easy' },
  { term: 'Handbal', forbidden: ['Bal', 'Doel', 'Gooien', 'Team', 'Zaal'], category: 'Sport', difficulty: 'easy' },
  { term: 'Biatlon', forbidden: ['Ski', 'Schieten', 'Winter', 'Geweer', 'Langlaufen'], category: 'Sport', difficulty: 'hard' },
  { term: 'Darten', forbidden: ['Pijl', 'Bord', 'Gooien', 'Punten', 'Bull'], category: 'Sport', difficulty: 'medium' },
  { term: 'Volleybal', forbidden: ['Net', 'Bal', 'Strand', 'Team', 'Smash'], category: 'Sport', difficulty: 'easy' },
  { term: 'Schermen', forbidden: ['Zwaard', 'Masker', 'Raak', 'Degen', 'Gevecht'], category: 'Sport', difficulty: 'medium' },
  { term: 'Tafeltennis', forbidden: ['Bal', 'Batje', 'Tafel', 'Ping', 'Pong'], category: 'Sport', difficulty: 'easy' },
  { term: 'Parachute', forbidden: ['Springen', 'Vliegen', 'Vliegtuig', 'Openen', 'Lucht'], category: 'Sport', difficulty: 'easy' },

  // === Eten (27) ===
  { term: 'Pizza', forbidden: ['Italie', 'Deeg', 'Beleg', 'Kaas', 'Oven'], category: 'Eten', difficulty: 'easy' },
  { term: 'Spaghetti', forbidden: ['Pasta', 'Italie', 'Saus', 'Koken', 'Lang'], category: 'Eten', difficulty: 'easy' },
  { term: 'Chocolade', forbidden: ['Zoet', 'Cacao', 'Bruin', 'Reep', 'Melk'], category: 'Eten', difficulty: 'easy' },
  { term: 'Hamburger', forbidden: ['Vlees', 'Broodje', 'Fastfood', 'McDonalds', 'Gehakt'], category: 'Eten', difficulty: 'easy' },
  { term: 'IJs', forbidden: ['Koud', 'Zomer', 'Bolletje', 'Hoorntje', 'Zoet'], category: 'Eten', difficulty: 'easy' },
  { term: 'Sushi', forbidden: ['Japan', 'Rijst', 'Vis', 'Zeewier', 'Rauw'], category: 'Eten', difficulty: 'easy' },
  { term: 'Stroopwafel', forbidden: ['Stroop', 'Wafel', 'Nederland', 'Zoet', 'Karamel'], category: 'Eten', difficulty: 'easy' },
  { term: 'Doner', forbidden: ['Vlees', 'Brood', 'Salade', 'Turkije', 'Saus'], category: 'Eten', difficulty: 'easy' },
  { term: 'Taart', forbidden: ['Bakken', 'Zoet', 'Verjaardag', 'Slagroom', 'Oven'], category: 'Eten', difficulty: 'easy' },
  { term: 'Patat', forbidden: ['Aardappel', 'Frituren', 'Ketchup', 'Zout', 'Fastfood'], category: 'Eten', difficulty: 'easy' },
  { term: 'Salade', forbidden: ['Groen', 'Gezond', 'Groenten', 'Dressing', 'Vers'], category: 'Eten', difficulty: 'easy' },
  { term: 'Croissant', forbidden: ['Frankrijk', 'Ontbijt', 'Boter', 'Deeg', 'Bakkerij'], category: 'Eten', difficulty: 'easy' },
  { term: 'Bitterballen', forbidden: ['Hapje', 'Frituur', 'Mosterd', 'Borrel', 'Rond'], category: 'Eten', difficulty: 'easy' },
  { term: 'Pannenkoek', forbidden: ['Pan', 'Deeg', 'Meel', 'Ei', 'Zoet'], category: 'Eten', difficulty: 'easy' },
  { term: 'Stamppot', forbidden: ['Aardappel', 'Groenten', 'Stampen', 'Winter', 'Rookworst'], category: 'Eten', difficulty: 'easy' },
  { term: 'Fondue', forbidden: ['Kaas', 'Smelten', 'Pan', 'Zwitserland', 'Dopen'], category: 'Eten', difficulty: 'medium' },
  { term: 'Erwtensoep', forbidden: ['Erwten', 'Soep', 'Winter', 'Rookworst', 'Dik'], category: 'Eten', difficulty: 'easy' },
  { term: 'Tiramisu', forbidden: ['Italie', 'Koffie', 'Mascarpone', 'Dessert', 'Cacao'], category: 'Eten', difficulty: 'medium' },
  { term: 'Stoofvlees', forbidden: ['Vlees', 'Sudderen', 'Bier', 'Aardappel', 'Koken'], category: 'Eten', difficulty: 'medium' },
  { term: 'Muesli', forbidden: ['Ontbijt', 'Havermout', 'Melk', 'Fruit', 'Gezond'], category: 'Eten', difficulty: 'easy' },
  { term: 'Kaassoufle', forbidden: ['Kaas', 'Frituur', 'Snack', 'Krokant', 'Warm'], category: 'Eten', difficulty: 'easy' },
  { term: 'Tacos', forbidden: ['Mexico', 'Mais', 'Vlees', 'Salsa', 'Vulling'], category: 'Eten', difficulty: 'easy' },
  { term: 'Raclette', forbidden: ['Kaas', 'Smelten', 'Pannetje', 'Aardappel', 'Zwitserland'], category: 'Eten', difficulty: 'easy' },
  { term: 'Baguette', forbidden: ['Frankrijk', 'Brood', 'Lang', 'Korst', 'Bakkerij'], category: 'Eten', difficulty: 'easy' },
  { term: 'Oliebollen', forbidden: ['Oud en Nieuw', 'Frituur', 'Poedersuiker', 'Deeg', 'Rond'], category: 'Eten', difficulty: 'easy' },
  { term: 'Popcorn', forbidden: ['Mais', 'Bioscoop', 'Zout', 'Zoet', 'Film'], category: 'Eten', difficulty: 'easy' },
  { term: 'Gluhwein', forbidden: ['Kerstmis', 'Warm', 'Wijn', 'Kruiden', 'Markt'], category: 'Eten', difficulty: 'easy' },

  // === Dieren (25) ===
  { term: 'Olifant', forbidden: ['Groot', 'Slurf', 'Afrika', 'Grijs', 'Slagtand'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Pinguïn', forbidden: ['IJs', 'Zwart-wit', 'Antarctica', 'Vogel', 'Vliegen'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Giraffe', forbidden: ['Nek', 'Lang', 'Afrika', 'Vlekken', 'Groot'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Dolfijn', forbidden: ['Zee', 'Zwemmen', 'Intelligent', 'Springen', 'Flipper'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Kameleon', forbidden: ['Kleur', 'Veranderen', 'Hagedis', 'Tong', 'Camouflage'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Krokodil', forbidden: ['Tanden', 'Water', 'Gevaarlijk', 'Reptiel', 'Rivier'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Vlinder', forbidden: ['Vleugels', 'Kleurrijk', 'Rups', 'Vliegen', 'Bloem'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Luiaard', forbidden: ['Langzaam', 'Boom', 'Hangen', 'Slapen', 'Lui'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Haai', forbidden: ['Zee', 'Tanden', 'Gevaarlijk', 'Vis', 'Vin'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Kolibrie', forbidden: ['Klein', 'Vogel', 'Vliegen', 'Bloem', 'Snel'], category: 'Dieren', difficulty: 'medium' },
  { term: 'Papegaai', forbidden: ['Vogel', 'Praten', 'Kleurrijk', 'Veren', 'Piraat'], category: 'Dieren', difficulty: 'easy' },
  { term: 'IJsbeer', forbidden: ['Wit', 'Arctisch', 'Koud', 'IJs', 'Beer'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Flamingo', forbidden: ['Roze', 'Vogel', 'Poot', 'Staan', 'Meer'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Kangoeroe', forbidden: ['Australie', 'Springen', 'Buidel', 'Baby', 'Hoppen'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Pauw', forbidden: ['Veren', 'Waaier', 'Kleurrijk', 'Vogel', 'Mannelijk'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Mier', forbidden: ['Klein', 'Insect', 'Heuvel', 'Sterk', 'Kolonie'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Nijlpaard', forbidden: ['Water', 'Afrika', 'Groot', 'Bek', 'Rivier'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Uil', forbidden: ['Nacht', 'Vogel', 'Ogen', 'Roepen', 'Wijs'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Panda', forbidden: ['China', 'Bamboe', 'Zwart-wit', 'Beer', 'Schattig'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Schildpad', forbidden: ['Schild', 'Langzaam', 'Oud', 'Pantser', 'Reptiel'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Wolf', forbidden: ['Huilen', 'Roedel', 'Bos', 'Hond', 'Sprookje'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Octopus', forbidden: ['Armen', 'Acht', 'Zee', 'Inkt', 'Tentakel'], category: 'Dieren', difficulty: 'medium' },
  { term: 'Zeepaardje', forbidden: ['Zee', 'Klein', 'Paard', 'Zwemmen', 'Water'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Gorilla', forbidden: ['Aap', 'Groot', 'Sterk', 'Jungle', 'Zilverrug'], category: 'Dieren', difficulty: 'easy' },
  { term: 'Bij', forbidden: ['Honing', 'Steken', 'Bloem', 'Vliegen', 'Koningin'], category: 'Dieren', difficulty: 'easy' },

  // === Technologie (20) ===
  { term: 'Smartphone', forbidden: ['Telefoon', 'Mobiel', 'Apple', 'Apps', 'Scherm'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Internet', forbidden: ['Online', 'Web', 'Surfen', 'Website', 'Verbinding'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Computer', forbidden: ['Machine', 'Scherm', 'Toetsenbord', 'Muis', 'PC'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Robot', forbidden: ['Machine', 'Kunstmatig', 'Metaal', 'Automatisch', 'Technologie'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Kunstmatige intelligentie', forbidden: ['Computer', 'Robot', 'Leren', 'Machine', 'Algoritme'], category: 'Technologie', difficulty: 'medium' },
  { term: 'Drone', forbidden: ['Vliegen', 'Camera', 'Afstandsbediening', 'Propeller', 'Lucht'], category: 'Technologie', difficulty: 'easy' },
  { term: 'WiFi', forbidden: ['Internet', 'Draadloos', 'Verbinding', 'Router', 'Netwerk'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Selfie', forbidden: ['Foto', 'Camera', 'Telefoon', 'Zelf', 'Beeld'], category: 'Technologie', difficulty: 'easy' },
  { term: '3D-printer', forbidden: ['Printen', 'Driedimensionaal', 'Plastic', 'Laag', 'Model'], category: 'Technologie', difficulty: 'medium' },
  { term: 'Virtual reality', forbidden: ['Bril', 'Virtueel', 'Wereld', 'Computer', 'Simulatie'], category: 'Technologie', difficulty: 'medium' },
  { term: 'Bluetooth', forbidden: ['Draadloos', 'Verbinding', 'Telefoon', 'Koptelefoon', 'Radio'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Streaming', forbidden: ['Film', 'Muziek', 'Netflix', 'Internet', 'Video'], category: 'Technologie', difficulty: 'easy' },
  { term: 'GPS', forbidden: ['Navigatie', 'Locatie', 'Satelliet', 'Kaart', 'Positie'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Elektrische auto', forbidden: ['Stroom', 'Tesla', 'Batterij', 'Rijden', 'Opladen'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Social media', forbidden: ['Facebook', 'Instagram', 'Netwerk', 'Delen', 'Volger'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Podcast', forbidden: ['Audio', 'Luisteren', 'Uitzending', 'Spotify', 'Aflevering'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Alexa', forbidden: ['Amazon', 'Spraakassistent', 'Praten', 'Slim', 'Speaker'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Tablet', forbidden: ['iPad', 'Scherm', 'Aanraken', 'Computer', 'Draagbaar'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Algoritme', forbidden: ['Berekening', 'Computer', 'Stap', 'Programma', 'Logica'], category: 'Technologie', difficulty: 'hard' },
  { term: 'Blockchain', forbidden: ['Bitcoin', 'Crypto', 'Decentraal', 'Keten', 'Data'], category: 'Technologie', difficulty: 'hard' },

  // === Beroemdheden (15) ===
  { term: 'Albert Einstein', forbidden: ['Relativiteit', 'Fysica', 'Genie', 'E=mc2', 'Haar'], category: 'Beroemdheden', difficulty: 'easy' },
  { term: 'Mozart', forbidden: ['Muziek', 'Componist', 'Salzburg', 'Piano', 'Klassiek'], category: 'Beroemdheden', difficulty: 'easy' },
  { term: 'Vincent van Gogh', forbidden: ['Schilder', 'Oor', 'Zonnebloemen', 'Sterrennacht', 'Nederland'], category: 'Beroemdheden', difficulty: 'easy' },
  { term: 'Beethoven', forbidden: ['Muziek', 'Componist', 'Doof', 'Symfonie', 'Piano'], category: 'Beroemdheden', difficulty: 'easy' },
  { term: 'Leonardo da Vinci', forbidden: ['Mona Lisa', 'Schilder', 'Uitvinder', 'Renaissance', 'Italie'], category: 'Beroemdheden', difficulty: 'easy' },
  { term: 'Cristiano Ronaldo', forbidden: ['Voetbal', 'Portugal', 'Doelpunt', 'Real Madrid', 'Spits'], category: 'Beroemdheden', difficulty: 'easy' },
  { term: 'Anne Frank', forbidden: ['Dagboek', 'Tweede Wereldoorlog', 'Amsterdam', 'Joods', 'Onderduik'], category: 'Beroemdheden', difficulty: 'easy' },
  { term: 'Elon Musk', forbidden: ['Tesla', 'SpaceX', 'Miljardair', 'Twitter', 'Ondernemer'], category: 'Beroemdheden', difficulty: 'easy' },
  { term: 'Rembrandt', forbidden: ['Schilder', 'Nachtwacht', 'Amsterdam', 'Gouden Eeuw', 'Kunst'], category: 'Beroemdheden', difficulty: 'medium' },
  { term: 'Cleopatra', forbidden: ['Egypte', 'Koningin', 'Farao', 'Nijl', 'Caesar'], category: 'Beroemdheden', difficulty: 'medium' },
  { term: 'Napoleon', forbidden: ['Frankrijk', 'Keizer', 'Oorlog', 'Klein', 'Waterloo'], category: 'Beroemdheden', difficulty: 'easy' },
  { term: 'Marie Curie', forbidden: ['Radioactiviteit', 'Fysica', 'Nobelprijs', 'Wetenschap', 'Onderzoek'], category: 'Beroemdheden', difficulty: 'medium' },
  { term: 'Michael Jackson', forbidden: ['Zanger', 'Thriller', 'Dans', 'Pop', 'Koning'], category: 'Beroemdheden', difficulty: 'easy' },
  { term: 'Lionel Messi', forbidden: ['Voetbal', 'Argentinie', 'Barcelona', 'Doelpunt', 'Wereldkampioen'], category: 'Beroemdheden', difficulty: 'easy' },
  { term: 'Max Verstappen', forbidden: ['Formule 1', 'Red Bull', 'Coureur', 'Kampioen', 'Racen'], category: 'Beroemdheden', difficulty: 'easy' },

  // === Dagelijks leven (32) ===
  { term: 'Wekker', forbidden: ['Ochtend', 'Opstaan', 'Klok', 'Rinkelen', 'Alarm'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Tandenborstel', forbidden: ['Tanden', 'Poetsen', 'Mond', 'Tandpasta', 'Badkamer'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Sleutel', forbidden: ['Deur', 'Openen', 'Slot', 'Huis', 'Afsluiten'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Paraplu', forbidden: ['Regen', 'Nat', 'Weer', 'Beschermen', 'Droog'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Bril', forbidden: ['Ogen', 'Zien', 'Glas', 'Opticien', 'Neus'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Koelkast', forbidden: ['Koud', 'Eten', 'Keuken', 'Bewaren', 'Deur'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Stofzuiger', forbidden: ['Zuigen', 'Vuil', 'Tapijt', 'Schoonmaken', 'Vloer'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Wasmachine', forbidden: ['Kleding', 'Wassen', 'Water', 'Draaien', 'Was'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Stoplicht', forbidden: ['Rood', 'Groen', 'Oranje', 'Straat', 'Verkeer'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Lift', forbidden: ['Omhoog', 'Omlaag', 'Verdieping', 'Knoppen', 'Gebouw'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Dekbed', forbidden: ['Bed', 'Slapen', 'Warm', 'Kussen', 'Toedekken'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Afstandsbediening', forbidden: ['Televisie', 'Knoppen', 'Zappen', 'Zender', 'Bank'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Portemonnee', forbidden: ['Geld', 'Munten', 'Kaarten', 'Zak', 'Betalen'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Parkeerplaats', forbidden: ['Auto', 'Parkeren', 'Staan', 'Plek', 'Zoeken'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Waterfles', forbidden: ['Water', 'Drinken', 'Fles', 'Dop', 'Meenemen'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Verjaardag', forbidden: ['Vieren', 'Taart', 'Cadeaus', 'Kaarsjes', 'Feest'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Supermarkt', forbidden: ['Boodschappen', 'Kassa', 'Schap', 'Winkel', 'Levensmiddelen'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Kapper', forbidden: ['Haar', 'Knippen', 'Schaar', 'Salon', 'Kapsel'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Bibliotheek', forbidden: ['Boeken', 'Lezen', 'Lenen', 'Stil', 'Kasten'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'File', forbidden: ['Auto', 'Weg', 'Wachten', 'Verkeer', 'Snelweg'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Sportschool', forbidden: ['Sport', 'Trainen', 'Spieren', 'Apparaten', 'Gewichten'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Zonnebrand', forbidden: ['Zon', 'Huid', 'Bescherming', 'Strand', 'Smeren'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Achtbaan', forbidden: ['Pretpark', 'Snel', 'Rails', 'Bochten', 'Adrenaline'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Reuzenrad', forbidden: ['Kermis', 'Draaien', 'Hoog', 'Gondel', 'Uitzicht'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Sneeuwpop', forbidden: ['Sneeuw', 'Winter', 'Wortel', 'Neus', 'Koud'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Kampvuur', forbidden: ['Vuur', 'Hout', 'Nacht', 'Warm', 'Marshmallow'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Zeepbel', forbidden: ['Zeep', 'Bel', 'Blazen', 'Rond', 'Knappen'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Zaklamp', forbidden: ['Licht', 'Batterij', 'Donker', 'Schijnen', 'Lamp'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Ballon', forbidden: ['Lucht', 'Opblazen', 'Feest', 'Kleurrijk', 'Knallen'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Zandkasteel', forbidden: ['Zand', 'Strand', 'Bouwen', 'Zee', 'Emmer'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Puzzel', forbidden: ['Stukjes', 'Leggen', 'Plaatje', 'Raadsel', 'Geduld'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Boomhut', forbidden: ['Boom', 'Kinderen', 'Hout', 'Boven', 'Huis'], category: 'Dagelijks leven', difficulty: 'easy' },

  // === Reizen (18) ===
  { term: 'Koffer', forbidden: ['Reis', 'Inpakken', 'Kleding', 'Vliegveld', 'Vakantie'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Paspoort', forbidden: ['Grens', 'Document', 'Foto', 'Vliegveld', 'Visum'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Hotel', forbidden: ['Kamer', 'Overnachten', 'Bed', 'Receptie', 'Vakantie'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Vliegveld', forbidden: ['Vliegtuig', 'Vliegen', 'Gate', 'Boarden', 'Terminal'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Cruise', forbidden: ['Schip', 'Zee', 'Reis', 'Hut', 'Vakantie'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Souvenir', forbidden: ['Aandenken', 'Herinnering', 'Kopen', 'Vakantie', 'Cadeau'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Wandelen', forbidden: ['Bergen', 'Natuur', 'Pad', 'Lopen', 'Rugzak'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Kamperen', forbidden: ['Tent', 'Natuur', 'Buiten', 'Camping', 'Slapen'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Strandvakantie', forbidden: ['Zee', 'Zon', 'Zand', 'Strand', 'Zwemmen'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Stadswandeling', forbidden: ['Stad', 'Gids', 'Bezienswaardigheden', 'Groep', 'Rondleiding'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Boardingpass', forbidden: ['Vliegtuig', 'Stoel', 'Gate', 'Boarden', 'Vliegen'], category: 'Reizen', difficulty: 'medium' },
  { term: 'Jetlag', forbidden: ['Tijdzone', 'Moe', 'Vlucht', 'Reizen', 'Slaap'], category: 'Reizen', difficulty: 'medium' },
  { term: 'Backpacken', forbidden: ['Rugzak', 'Reizen', 'Goedkoop', 'Hostel', 'Wereld'], category: 'Reizen', difficulty: 'medium' },
  { term: 'Roadtrip', forbidden: ['Auto', 'Rijden', 'Weg', 'Reis', 'Route'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Snorkelen', forbidden: ['Water', 'Masker', 'Zee', 'Vissen', 'Duiken'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Luchtballon', forbidden: ['Vliegen', 'Lucht', 'Mand', 'Heet', 'Vlam'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Nachtwandeling', forbidden: ['Nacht', 'Donker', 'Bos', 'Zaklamp', 'Lopen'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Slaapzak', forbidden: ['Slapen', 'Kamperen', 'Warm', 'Tent', 'Nacht'], category: 'Reizen', difficulty: 'easy' },

  // === Cultuur (20) ===
  { term: 'Opera', forbidden: ['Zingen', 'Podium', 'Muziek', 'Theater', 'Orkest'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Museum', forbidden: ['Kunst', 'Tentoonstelling', 'Schilderijen', 'Bezoekers', 'Galerie'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Carnaval', forbidden: ['Kostuum', 'Optocht', 'Vieren', 'Masker', 'Praalwagen'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Koningsdag', forbidden: ['Oranje', 'Koning', 'April', 'Vrijmarkt', 'Nederland'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Kerstmarkt', forbidden: ['Kerstmis', 'Gluhwein', 'Kraampjes', 'Cadeaus', 'Winter'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Ballet', forbidden: ['Dans', 'Podium', 'Spitzen', 'Muziek', 'Zwanenmeer'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Graffiti', forbidden: ['Muur', 'Spray', 'Verf', 'Kunst', 'Straat'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Tatoeage', forbidden: ['Huid', 'Naald', 'Afbeelding', 'Lichaam', 'Inkt'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Circus', forbidden: ['Clown', 'Acrobaat', 'Tent', 'Dieren', 'Show'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Oud en Nieuw', forbidden: ['Nieuwjaar', 'Vuurwerk', 'Middernacht', 'Champagne', 'Vieren'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Bruiloft', forbidden: ['Bruid', 'Bruidegom', 'Ringen', 'Kerk', 'Trouwen'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Bioscoop', forbidden: ['Film', 'Popcorn', 'Scherm', 'Zaal', 'Kaartjes'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Karaoke', forbidden: ['Zingen', 'Microfoon', 'Tekst', 'Lied', 'Podium'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Festival', forbidden: ['Muziek', 'Openlucht', 'Podium', 'Band', 'Zomer'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Escape Room', forbidden: ['Puzzel', 'Opgesloten', 'Team', 'Tijd', 'Aanwijzing'], category: 'Cultuur', difficulty: 'medium' },
  { term: 'Sinterklaas', forbidden: ['December', 'Cadeau', 'Schoen', 'Piet', 'Stoomboot'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Paashaas', forbidden: ['Pasen', 'Eieren', 'Verstoppen', 'Konijn', 'Lente'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Flessenpost', forbidden: ['Fles', 'Zee', 'Bericht', 'Water', 'Eiland'], category: 'Cultuur', difficulty: 'medium' },
  { term: 'Eiffeltoren', forbidden: ['Parijs', 'Frankrijk', 'Toren', 'Metaal', 'Bezienswaardigheid'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Molen', forbidden: ['Wind', 'Nederland', 'Wieken', 'Graan', 'Polder'], category: 'Cultuur', difficulty: 'easy' },

  // === Wetenschap (16) ===
  { term: 'Zwaartekracht', forbidden: ['Aarde', 'Vallen', 'Newton', 'Fysica', 'Aantrekken'], category: 'Wetenschap', difficulty: 'medium' },
  { term: 'Fotosynthese', forbidden: ['Plant', 'Zon', 'Licht', 'Groen', 'Zuurstof'], category: 'Wetenschap', difficulty: 'hard' },
  { term: 'Telescoop', forbidden: ['Sterren', 'Kijken', 'Hemel', 'Lens', 'Astronomie'], category: 'Wetenschap', difficulty: 'easy' },
  { term: 'DNA', forbidden: ['Genen', 'Erfelijkheid', 'Cel', 'Helix', 'Lichaam'], category: 'Wetenschap', difficulty: 'medium' },
  { term: 'Vulkaan', forbidden: ['Lava', 'Uitbarsting', 'Berg', 'Heet', 'Vuur'], category: 'Wetenschap', difficulty: 'easy' },
  { term: 'Regenboog', forbidden: ['Kleuren', 'Regen', 'Zon', 'Boog', 'Hemel'], category: 'Wetenschap', difficulty: 'easy' },
  { term: 'Fossiel', forbidden: ['Dinosaurus', 'Oud', 'Steen', 'Botten', 'Opgraving'], category: 'Wetenschap', difficulty: 'medium' },
  { term: 'Magneetveld', forbidden: ['Kompas', 'Aarde', 'Noord', 'Zuid', 'Aantrekken'], category: 'Wetenschap', difficulty: 'hard' },
  { term: 'Atoom', forbidden: ['Klein', 'Kern', 'Deeltje', 'Fysica', 'Elektron'], category: 'Wetenschap', difficulty: 'medium' },
  { term: 'Zwart gat', forbidden: ['Ruimte', 'Zwaartekracht', 'Licht', 'Ster', 'Opslokken'], category: 'Wetenschap', difficulty: 'medium' },
  { term: 'Microscoop', forbidden: ['Klein', 'Vergroten', 'Lens', 'Laboratorium', 'Kijken'], category: 'Wetenschap', difficulty: 'easy' },
  { term: 'Batterij', forbidden: ['Stroom', 'Energie', 'Opladen', 'Plus', 'Min'], category: 'Wetenschap', difficulty: 'easy' },
  { term: 'Dinosaurus', forbidden: ['Uitgestorven', 'Groot', 'Reptiel', 'Fossiel', 'T-Rex'], category: 'Wetenschap', difficulty: 'easy' },
  { term: 'Zonnestelsel', forbidden: ['Planeten', 'Zon', 'Aarde', 'Baan', 'Ruimte'], category: 'Wetenschap', difficulty: 'easy' },
  { term: 'Vaccinatie', forbidden: ['Naald', 'Dokter', 'Ziekte', 'Bescherming', 'Immuun'], category: 'Wetenschap', difficulty: 'easy' },
  { term: 'Tijdreizen', forbidden: ['Tijd', 'Verleden', 'Toekomst', 'Machine', 'Reizen'], category: 'Wetenschap', difficulty: 'medium' },

  // === Extra gemengd (20) ===
  { term: 'Astronaut', forbidden: ['Ruimte', 'Raket', 'Maan', 'NASA', 'Zweven'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Politie', forbidden: ['Uniform', 'Crimineel', 'Sirene', 'Wet', 'Patrouille'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Restaurant', forbidden: ['Eten', 'Ober', 'Menukaart', 'Kok', 'Tafel'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Kleuterschool', forbidden: ['Kinderen', 'Spelen', 'Juf', 'Leren', 'Klein'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Zonnebril', forbidden: ['Zon', 'Ogen', 'Donker', 'Zomer', 'Dragen'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Jungle', forbidden: ['Bos', 'Dieren', 'Tropisch', 'Apen', 'Planten'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Snelweg', forbidden: ['Auto', 'Snel', 'Weg', 'Rijden', 'Snelheid'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Televisie', forbidden: ['Scherm', 'Kijken', 'Programma', 'Zender', 'Film'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Ziekenhuis', forbidden: ['Dokter', 'Patient', 'Ziek', 'Operatie', 'Bed'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Kasteel', forbidden: ['Koning', 'Burcht', 'Deur', 'Sleutel', 'Sprookje'], category: 'Cultuur', difficulty: 'medium' },
  { term: 'Spoorweg', forbidden: ['Trein', 'Rails', 'Station', 'Rijden', 'Spoor'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Brandweer', forbidden: ['Brand', 'Blussen', 'Slang', 'Rood', 'Sirene'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Gitaar', forbidden: ['Snaren', 'Muziek', 'Spelen', 'Instrument', 'Concert'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Clown', forbidden: ['Circus', 'Grappig', 'Neus', 'Lachen', 'Kostuum'], category: 'Cultuur', difficulty: 'easy' },
  { term: 'Diamant', forbidden: ['Edelsteen', 'Ring', 'Duur', 'Schitteren', 'Hard'], category: 'Wetenschap', difficulty: 'easy' },
  { term: 'Honing', forbidden: ['Bij', 'Zoet', 'Pot', 'Brood', 'Goud'], category: 'Eten', difficulty: 'easy' },
  { term: 'Vuurtoren', forbidden: ['Licht', 'Zee', 'Kust', 'Schip', 'Toren'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Vliegtuig', forbidden: ['Vliegen', 'Piloot', 'Lucht', 'Vliegveld', 'Wolken'], category: 'Reizen', difficulty: 'easy' },
  { term: 'Tandarts', forbidden: ['Tanden', 'Boren', 'Pijn', 'Praktijk', 'Dokter'], category: 'Dagelijks leven', difficulty: 'easy' },
  { term: 'Bakker', forbidden: ['Brood', 'Broodjes', 'Bakken', 'Oven', 'Meel'], category: 'Dagelijks leven', difficulty: 'easy' },
];
