export interface TabooCard {
  term: string;
  forbidden: string[];
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const TABOO_CARDS_ES: TabooCard[] = [
  // === Deportes (21) ===
  { term: 'Futbol', forbidden: ['Balon', 'Gol', 'Jugador', 'Equipo', 'Estadio'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Tenis', forbidden: ['Raqueta', 'Pelota', 'Red', 'Saque', 'Wimbledon'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Baloncesto', forbidden: ['Canasta', 'Balon', 'Lanzar', 'NBA', 'Mate'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Natacion', forbidden: ['Agua', 'Piscina', 'Calle', 'Brazada', 'Banador'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Boxeo', forbidden: ['Pelea', 'Ring', 'Guantes', 'Golpe', 'Asalto'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Esqui', forbidden: ['Nieve', 'Montana', 'Pista', 'Invierno', 'Telesilla'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Maraton', forbidden: ['Correr', 'Kilometros', 'Distancia', 'Resistencia', 'Meta'], category: 'Deportes', difficulty: 'medium' },
  { term: 'Golf', forbidden: ['Pelota', 'Palo', 'Hoyo', 'Cesped', 'Handicap'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Olimpiadas', forbidden: ['Juegos', 'Anillos', 'Medalla', 'Atletas', 'Competicion'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Surf', forbidden: ['Ola', 'Tabla', 'Mar', 'Playa', 'Agua'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Hockey sobre hielo', forbidden: ['Disco', 'Hielo', 'Palo', 'Porteria', 'Patines'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Yoga', forbidden: ['Estiramiento', 'Meditacion', 'Cuerpo', 'Postura', 'Relajacion'], category: 'Deportes', difficulty: 'medium' },
  { term: 'Formula 1', forbidden: ['Carrera', 'Coche', 'Rapido', 'Piloto', 'Circuito'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Escalada', forbidden: ['Pared', 'Roca', 'Cuerda', 'Altura', 'Agarres'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Balonmano', forbidden: ['Balon', 'Porteria', 'Lanzar', 'Equipo', 'Cancha'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Biatlon', forbidden: ['Esqui', 'Disparo', 'Invierno', 'Rifle', 'Campo a traves'], category: 'Deportes', difficulty: 'hard' },
  { term: 'Dardos', forbidden: ['Flecha', 'Diana', 'Lanzar', 'Puntos', 'Centro'], category: 'Deportes', difficulty: 'medium' },
  { term: 'Voleibol', forbidden: ['Red', 'Balon', 'Playa', 'Equipo', 'Remate'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Esgrima', forbidden: ['Espada', 'Mascara', 'Tocado', 'Florete', 'Combate'], category: 'Deportes', difficulty: 'medium' },
  { term: 'Tenis de mesa', forbidden: ['Pelota', 'Pala', 'Mesa', 'Ping', 'Pong'], category: 'Deportes', difficulty: 'easy' },
  { term: 'Paracaidas', forbidden: ['Saltar', 'Volar', 'Avion', 'Abrir', 'Aire'], category: 'Deportes', difficulty: 'easy' },

  // === Comida (27) ===
  { term: 'Pizza', forbidden: ['Italia', 'Masa', 'Ingredientes', 'Queso', 'Horno'], category: 'Comida', difficulty: 'easy' },
  { term: 'Espaguetis', forbidden: ['Pasta', 'Italia', 'Salsa', 'Cocinar', 'Largos'], category: 'Comida', difficulty: 'easy' },
  { term: 'Chocolate', forbidden: ['Dulce', 'Cacao', 'Marron', 'Tableta', 'Leche'], category: 'Comida', difficulty: 'easy' },
  { term: 'Hamburguesa', forbidden: ['Carne', 'Pan', 'Comida rapida', 'McDonalds', 'Filete'], category: 'Comida', difficulty: 'easy' },
  { term: 'Helado', forbidden: ['Frio', 'Verano', 'Bola', 'Cucurucho', 'Dulce'], category: 'Comida', difficulty: 'easy' },
  { term: 'Sushi', forbidden: ['Japon', 'Arroz', 'Pescado', 'Alga', 'Crudo'], category: 'Comida', difficulty: 'easy' },
  { term: 'Churros', forbidden: ['Aceite', 'Azucar', 'Chocolate', 'Masa', 'Frito'], category: 'Comida', difficulty: 'easy' },
  { term: 'Kebab', forbidden: ['Carne', 'Pan', 'Ensalada', 'Turquia', 'Salsa'], category: 'Comida', difficulty: 'easy' },
  { term: 'Tarta', forbidden: ['Hornear', 'Dulce', 'Cumpleanos', 'Nata', 'Horno'], category: 'Comida', difficulty: 'easy' },
  { term: 'Patatas fritas', forbidden: ['Patata', 'Freir', 'Ketchup', 'Saladas', 'Comida rapida'], category: 'Comida', difficulty: 'easy' },
  { term: 'Ensalada', forbidden: ['Verde', 'Saludable', 'Verdura', 'Aliño', 'Fresca'], category: 'Comida', difficulty: 'easy' },
  { term: 'Croissant', forbidden: ['Francia', 'Desayuno', 'Mantequilla', 'Masa', 'Panaderia'], category: 'Comida', difficulty: 'easy' },
  { term: 'Tortilla espanola', forbidden: ['Huevo', 'Patata', 'Espana', 'Sarten', 'Cebolla'], category: 'Comida', difficulty: 'easy' },
  { term: 'Crepe', forbidden: ['Sarten', 'Masa', 'Harina', 'Relleno', 'Fino'], category: 'Comida', difficulty: 'easy' },
  { term: 'Paella', forbidden: ['Arroz', 'Espana', 'Marisco', 'Valencia', 'Sarten'], category: 'Comida', difficulty: 'easy' },
  { term: 'Fondue', forbidden: ['Queso', 'Derretir', 'Olla', 'Suiza', 'Mojar'], category: 'Comida', difficulty: 'medium' },
  { term: 'Gazpacho', forbidden: ['Frio', 'Tomate', 'Sopa', 'Verano', 'Andalucia'], category: 'Comida', difficulty: 'easy' },
  { term: 'Tiramisu', forbidden: ['Italia', 'Cafe', 'Mascarpone', 'Postre', 'Cacao'], category: 'Comida', difficulty: 'medium' },
  { term: 'Guiso', forbidden: ['Carne', 'Verdura', 'Olla', 'Cocinar', 'Caldo'], category: 'Comida', difficulty: 'medium' },
  { term: 'Muesli', forbidden: ['Desayuno', 'Avena', 'Leche', 'Frutas', 'Saludable'], category: 'Comida', difficulty: 'easy' },
  { term: 'Empanada', forbidden: ['Masa', 'Relleno', 'Argentina', 'Horno', 'Carne'], category: 'Comida', difficulty: 'easy' },
  { term: 'Tacos', forbidden: ['Mexico', 'Maiz', 'Carne', 'Salsa', 'Relleno'], category: 'Comida', difficulty: 'easy' },
  { term: 'Raclette', forbidden: ['Queso', 'Derretir', 'Bandeja', 'Patata', 'Suiza'], category: 'Comida', difficulty: 'easy' },
  { term: 'Baguette', forbidden: ['Francia', 'Pan', 'Largo', 'Corteza', 'Panaderia'], category: 'Comida', difficulty: 'easy' },
  { term: 'Turron', forbidden: ['Navidad', 'Almendra', 'Dulce', 'Espana', 'Miel'], category: 'Comida', difficulty: 'easy' },
  { term: 'Palomitas', forbidden: ['Maiz', 'Cine', 'Saladas', 'Dulces', 'Pelicula'], category: 'Comida', difficulty: 'easy' },
  { term: 'Sangria', forbidden: ['Vino', 'Fruta', 'Espana', 'Verano', 'Jarra'], category: 'Comida', difficulty: 'easy' },

  // === Animales (25) ===
  { term: 'Elefante', forbidden: ['Grande', 'Trompa', 'Africa', 'Gris', 'Colmillo'], category: 'Animales', difficulty: 'easy' },
  { term: 'Pinguino', forbidden: ['Hielo', 'Blanco y negro', 'Antartida', 'Ave', 'Volar'], category: 'Animales', difficulty: 'easy' },
  { term: 'Jirafa', forbidden: ['Cuello', 'Largo', 'Africa', 'Manchas', 'Alto'], category: 'Animales', difficulty: 'easy' },
  { term: 'Delfin', forbidden: ['Mar', 'Nadar', 'Inteligente', 'Saltar', 'Flipper'], category: 'Animales', difficulty: 'easy' },
  { term: 'Camaleon', forbidden: ['Color', 'Cambiar', 'Lagarto', 'Lengua', 'Camuflaje'], category: 'Animales', difficulty: 'easy' },
  { term: 'Cocodrilo', forbidden: ['Dientes', 'Agua', 'Peligroso', 'Reptil', 'Rio'], category: 'Animales', difficulty: 'easy' },
  { term: 'Mariposa', forbidden: ['Alas', 'Colorida', 'Oruga', 'Volar', 'Flor'], category: 'Animales', difficulty: 'easy' },
  { term: 'Perezoso', forbidden: ['Lento', 'Arbol', 'Colgar', 'Dormir', 'Pereza'], category: 'Animales', difficulty: 'easy' },
  { term: 'Tiburon', forbidden: ['Mar', 'Dientes', 'Peligroso', 'Pez', 'Aleta'], category: 'Animales', difficulty: 'easy' },
  { term: 'Colibri', forbidden: ['Pequeno', 'Ave', 'Volar', 'Flor', 'Rapido'], category: 'Animales', difficulty: 'medium' },
  { term: 'Loro', forbidden: ['Ave', 'Hablar', 'Colorido', 'Plumas', 'Pirata'], category: 'Animales', difficulty: 'easy' },
  { term: 'Oso polar', forbidden: ['Blanco', 'Artico', 'Frio', 'Hielo', 'Oso'], category: 'Animales', difficulty: 'easy' },
  { term: 'Flamenco', forbidden: ['Rosa', 'Ave', 'Pata', 'Pararse', 'Lago'], category: 'Animales', difficulty: 'easy' },
  { term: 'Canguro', forbidden: ['Australia', 'Saltar', 'Bolsa', 'Cria', 'Brincar'], category: 'Animales', difficulty: 'easy' },
  { term: 'Pavo real', forbidden: ['Plumas', 'Abanico', 'Colorido', 'Ave', 'Macho'], category: 'Animales', difficulty: 'easy' },
  { term: 'Hormiga', forbidden: ['Pequena', 'Insecto', 'Hormiguero', 'Fuerte', 'Colonia'], category: 'Animales', difficulty: 'easy' },
  { term: 'Hipopotamo', forbidden: ['Agua', 'Africa', 'Grande', 'Boca', 'Rio'], category: 'Animales', difficulty: 'easy' },
  { term: 'Buho', forbidden: ['Noche', 'Ave', 'Ojos', 'Ulular', 'Sabio'], category: 'Animales', difficulty: 'easy' },
  { term: 'Panda', forbidden: ['China', 'Bambu', 'Blanco y negro', 'Oso', 'Tierno'], category: 'Animales', difficulty: 'easy' },
  { term: 'Tortuga', forbidden: ['Caparazon', 'Lenta', 'Vieja', 'Coraza', 'Reptil'], category: 'Animales', difficulty: 'easy' },
  { term: 'Lobo', forbidden: ['Aullar', 'Manada', 'Bosque', 'Perro', 'Cuento'], category: 'Animales', difficulty: 'easy' },
  { term: 'Pulpo', forbidden: ['Brazos', 'Ocho', 'Mar', 'Tinta', 'Tentaculo'], category: 'Animales', difficulty: 'medium' },
  { term: 'Caballito de mar', forbidden: ['Mar', 'Pequeno', 'Caballo', 'Nadar', 'Agua'], category: 'Animales', difficulty: 'easy' },
  { term: 'Gorila', forbidden: ['Mono', 'Grande', 'Fuerte', 'Selva', 'Espalda plateada'], category: 'Animales', difficulty: 'easy' },
  { term: 'Abeja', forbidden: ['Miel', 'Picar', 'Flor', 'Volar', 'Reina'], category: 'Animales', difficulty: 'easy' },

  // === Tecnologia (20) ===
  { term: 'Telefono movil', forbidden: ['Movil', 'Telefono', 'Apple', 'Aplicaciones', 'Pantalla'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Internet', forbidden: ['En linea', 'Red', 'Navegar', 'Pagina web', 'Conexion'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Ordenador', forbidden: ['Maquina', 'Pantalla', 'Teclado', 'Raton', 'PC'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Robot', forbidden: ['Maquina', 'Artificial', 'Metal', 'Automatico', 'Tecnologia'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Inteligencia artificial', forbidden: ['Ordenador', 'Robot', 'Aprender', 'Maquina', 'Algoritmo'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Dron', forbidden: ['Volar', 'Camara', 'Control remoto', 'Helice', 'Aire'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'WiFi', forbidden: ['Internet', 'Inalambrico', 'Conexion', 'Router', 'Red'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Selfie', forbidden: ['Foto', 'Camara', 'Movil', 'Uno mismo', 'Imagen'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Impresora 3D', forbidden: ['Imprimir', 'Tridimensional', 'Plastico', 'Capa', 'Modelo'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Realidad virtual', forbidden: ['Gafas', 'Virtual', 'Mundo', 'Ordenador', 'Simulacion'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Bluetooth', forbidden: ['Inalambrico', 'Conexion', 'Movil', 'Auriculares', 'Radio'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Streaming', forbidden: ['Pelicula', 'Musica', 'Netflix', 'Internet', 'Video'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'GPS', forbidden: ['Navegacion', 'Ubicacion', 'Satelite', 'Mapa', 'Posicion'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Coche electrico', forbidden: ['Electricidad', 'Tesla', 'Bateria', 'Conducir', 'Cargar'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Redes sociales', forbidden: ['Facebook', 'Instagram', 'Red', 'Compartir', 'Seguidores'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Podcast', forbidden: ['Audio', 'Escuchar', 'Programa', 'Spotify', 'Episodio'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Alexa', forbidden: ['Amazon', 'Asistente de voz', 'Hablar', 'Inteligente', 'Altavoz'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Tableta', forbidden: ['iPad', 'Pantalla', 'Tactil', 'Ordenador', 'Portatil'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Algoritmo', forbidden: ['Calculo', 'Ordenador', 'Paso', 'Programa', 'Logica'], category: 'Tecnologia', difficulty: 'hard' },
  { term: 'Blockchain', forbidden: ['Bitcoin', 'Cripto', 'Descentralizado', 'Cadena', 'Datos'], category: 'Tecnologia', difficulty: 'hard' },

  // === Famosos (15) ===
  { term: 'Albert Einstein', forbidden: ['Relatividad', 'Fisica', 'Genio', 'E=mc2', 'Pelo'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Mozart', forbidden: ['Musica', 'Compositor', 'Salzburgo', 'Piano', 'Clasica'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Cervantes', forbidden: ['Quijote', 'Escritor', 'Espana', 'Novela', 'Molinos'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Beethoven', forbidden: ['Musica', 'Compositor', 'Sordo', 'Sinfonia', 'Piano'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Leonardo da Vinci', forbidden: ['Mona Lisa', 'Pintor', 'Inventor', 'Renacimiento', 'Italia'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Cristiano Ronaldo', forbidden: ['Futbol', 'Portugal', 'Gol', 'Real Madrid', 'Delantero'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Shakira', forbidden: ['Cantante', 'Colombia', 'Caderas', 'Musica', 'Waka Waka'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Elon Musk', forbidden: ['Tesla', 'SpaceX', 'Millonario', 'Twitter', 'Empresario'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Picasso', forbidden: ['Pintor', 'Guernica', 'Espana', 'Cubismo', 'Arte'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Cleopatra', forbidden: ['Egipto', 'Reina', 'Faraon', 'Nilo', 'Cesar'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Napoleon', forbidden: ['Francia', 'Emperador', 'Guerra', 'Bajo', 'Waterloo'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Marie Curie', forbidden: ['Radiactividad', 'Fisica', 'Nobel', 'Ciencia', 'Investigacion'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Michael Jackson', forbidden: ['Cantante', 'Thriller', 'Baile', 'Pop', 'Rey'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Lionel Messi', forbidden: ['Futbol', 'Argentina', 'Barcelona', 'Gol', 'Mundial'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Frida Kahlo', forbidden: ['Pintura', 'Mexico', 'Cejas', 'Autorretrato', 'Arte'], category: 'Famosos', difficulty: 'easy' },

  // === Vida diaria (32) ===
  { term: 'Despertador', forbidden: ['Manana', 'Despertar', 'Reloj', 'Sonar', 'Alarma'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Cepillo de dientes', forbidden: ['Dientes', 'Cepillar', 'Boca', 'Pasta', 'Bano'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Llave', forbidden: ['Puerta', 'Abrir', 'Cerradura', 'Casa', 'Cerrar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Paraguas', forbidden: ['Lluvia', 'Mojado', 'Tiempo', 'Proteger', 'Seco'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Gafas', forbidden: ['Ojos', 'Ver', 'Cristal', 'Optica', 'Nariz'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Nevera', forbidden: ['Frio', 'Comida', 'Cocina', 'Guardar', 'Puerta'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Aspiradora', forbidden: ['Aspirar', 'Suciedad', 'Alfombra', 'Limpiar', 'Suelo'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Lavadora', forbidden: ['Ropa', 'Lavar', 'Agua', 'Centrifugar', 'Colada'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Semaforo', forbidden: ['Rojo', 'Verde', 'Amarillo', 'Calle', 'Trafico'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Ascensor', forbidden: ['Subir', 'Bajar', 'Piso', 'Botones', 'Edificio'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Manta', forbidden: ['Cama', 'Dormir', 'Caliente', 'Almohada', 'Tapar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Mando a distancia', forbidden: ['Television', 'Botones', 'Cambiar', 'Canal', 'Sofa'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Cartera', forbidden: ['Dinero', 'Monedas', 'Tarjetas', 'Bolsillo', 'Pagar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Aparcamiento', forbidden: ['Coche', 'Aparcar', 'Parar', 'Plaza', 'Buscar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Botella de agua', forbidden: ['Agua', 'Beber', 'Botella', 'Tapon', 'Llevar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Cumpleanos', forbidden: ['Celebrar', 'Tarta', 'Regalos', 'Velas', 'Fiesta'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Supermercado', forbidden: ['Comprar', 'Caja', 'Estantes', 'Tienda', 'Alimentos'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Peluquero', forbidden: ['Pelo', 'Cortar', 'Tijeras', 'Salon', 'Peinado'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Biblioteca', forbidden: ['Libros', 'Leer', 'Prestar', 'Silencio', 'Estantes'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Atasco', forbidden: ['Coche', 'Calle', 'Esperar', 'Trafico', 'Autopista'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Gimnasio', forbidden: ['Deporte', 'Entrenar', 'Musculos', 'Maquinas', 'Pesas'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Protector solar', forbidden: ['Sol', 'Piel', 'Proteccion', 'Playa', 'Crema'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Montana rusa', forbidden: ['Parque', 'Rapido', 'Railes', 'Curvas', 'Adrenalina'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Noria', forbidden: ['Feria', 'Girar', 'Alto', 'Cabina', 'Vista'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Muneco de nieve', forbidden: ['Nieve', 'Invierno', 'Zanahoria', 'Nariz', 'Frio'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Hoguera', forbidden: ['Fuego', 'Lena', 'Noche', 'Calor', 'Malvavisco'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Pompa de jabon', forbidden: ['Jabon', 'Burbuja', 'Soplar', 'Redonda', 'Explotar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Linterna', forbidden: ['Luz', 'Pila', 'Oscuridad', 'Iluminar', 'Lampara'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Globo', forbidden: ['Aire', 'Inflar', 'Fiesta', 'Colores', 'Explotar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Castillo de arena', forbidden: ['Arena', 'Playa', 'Construir', 'Mar', 'Cubo'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Puzzle', forbidden: ['Piezas', 'Armar', 'Imagen', 'Rompecabezas', 'Paciencia'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Casa del arbol', forbidden: ['Arbol', 'Ninos', 'Madera', 'Arriba', 'Casa'], category: 'Vida diaria', difficulty: 'easy' },

  // === Viajes (18) ===
  { term: 'Maleta', forbidden: ['Viaje', 'Hacer', 'Ropa', 'Aeropuerto', 'Vacaciones'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Pasaporte', forbidden: ['Frontera', 'Documento', 'Foto', 'Aeropuerto', 'Visado'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Hotel', forbidden: ['Habitacion', 'Dormir', 'Cama', 'Recepcion', 'Vacaciones'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Aeropuerto', forbidden: ['Avion', 'Volar', 'Puerta', 'Embarque', 'Terminal'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Crucero', forbidden: ['Barco', 'Mar', 'Viaje', 'Camarote', 'Vacaciones'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Souvenir', forbidden: ['Recuerdo', 'Memoria', 'Comprar', 'Vacaciones', 'Regalo'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Senderismo', forbidden: ['Montana', 'Naturaleza', 'Camino', 'Andar', 'Mochila'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Camping', forbidden: ['Tienda', 'Naturaleza', 'Aire libre', 'Camping', 'Dormir'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Vacaciones en la playa', forbidden: ['Mar', 'Sol', 'Arena', 'Playa', 'Nadar'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Tour por la ciudad', forbidden: ['Ciudad', 'Guia', 'Monumentos', 'Grupo', 'Excursion'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Tarjeta de embarque', forbidden: ['Avion', 'Asiento', 'Puerta', 'Embarque', 'Volar'], category: 'Viajes', difficulty: 'medium' },
  { term: 'Jet lag', forbidden: ['Zona horaria', 'Cansado', 'Vuelo', 'Viaje', 'Sueno'], category: 'Viajes', difficulty: 'medium' },
  { term: 'Mochilero', forbidden: ['Mochila', 'Viajar', 'Barato', 'Hostal', 'Mundo'], category: 'Viajes', difficulty: 'medium' },
  { term: 'Viaje por carretera', forbidden: ['Coche', 'Conducir', 'Carretera', 'Viaje', 'Ruta'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Esnorquel', forbidden: ['Agua', 'Mascara', 'Mar', 'Peces', 'Bucear'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Globo aerostatico', forbidden: ['Volar', 'Aire', 'Cesta', 'Caliente', 'Llama'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Excursion nocturna', forbidden: ['Noche', 'Oscuridad', 'Bosque', 'Linterna', 'Caminar'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Saco de dormir', forbidden: ['Dormir', 'Camping', 'Caliente', 'Tienda', 'Noche'], category: 'Viajes', difficulty: 'easy' },

  // === Cultura (20) ===
  { term: 'Opera', forbidden: ['Cantar', 'Escenario', 'Musica', 'Teatro', 'Orquesta'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Museo', forbidden: ['Arte', 'Exposicion', 'Cuadros', 'Visitantes', 'Galeria'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Carnaval', forbidden: ['Disfraz', 'Desfile', 'Celebrar', 'Mascara', 'Carroza'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Feria de abril', forbidden: ['Sevilla', 'Casetas', 'Flamenco', 'Caballos', 'Vestido'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Mercado navideño', forbidden: ['Navidad', 'Regalos', 'Puestos', 'Invierno', 'Luces'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Ballet', forbidden: ['Danza', 'Escenario', 'Zapatillas', 'Musica', 'Lago de los cisnes'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Grafiti', forbidden: ['Pared', 'Spray', 'Pintura', 'Arte', 'Calle'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Tatuaje', forbidden: ['Piel', 'Aguja', 'Dibujo', 'Cuerpo', 'Tinta'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Circo', forbidden: ['Payaso', 'Acrobata', 'Carpa', 'Animales', 'Espectaculo'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Nochevieja', forbidden: ['Ano nuevo', 'Fuegos artificiales', 'Medianoche', 'Cohetes', 'Celebrar'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Boda', forbidden: ['Novia', 'Novio', 'Anillos', 'Iglesia', 'Casarse'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Cine', forbidden: ['Pelicula', 'Palomitas', 'Pantalla', 'Sala', 'Entradas'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Karaoke', forbidden: ['Cantar', 'Microfono', 'Letra', 'Cancion', 'Escenario'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Festival', forbidden: ['Musica', 'Aire libre', 'Escenario', 'Grupo', 'Verano'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Escape Room', forbidden: ['Enigma', 'Encerrado', 'Equipo', 'Tiempo', 'Pista'], category: 'Cultura', difficulty: 'medium' },
  { term: 'Papa Noel', forbidden: ['Navidad', 'Regalos', 'Diciembre', 'Rojo', 'Trineo'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Conejo de Pascua', forbidden: ['Pascua', 'Huevos', 'Esconder', 'Conejo', 'Primavera'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Mensaje en botella', forbidden: ['Botella', 'Mar', 'Mensaje', 'Agua', 'Isla'], category: 'Cultura', difficulty: 'medium' },
  { term: 'Torre Eiffel', forbidden: ['Paris', 'Francia', 'Torre', 'Metal', 'Monumento'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Sagrada Familia', forbidden: ['Barcelona', 'Gaudi', 'Basilica', 'Espana', 'Monumento'], category: 'Cultura', difficulty: 'easy' },

  // === Ciencia (16) ===
  { term: 'Gravedad', forbidden: ['Tierra', 'Caer', 'Newton', 'Fisica', 'Atraer'], category: 'Ciencia', difficulty: 'medium' },
  { term: 'Fotosintesis', forbidden: ['Planta', 'Sol', 'Luz', 'Verde', 'Oxigeno'], category: 'Ciencia', difficulty: 'hard' },
  { term: 'Telescopio', forbidden: ['Estrellas', 'Ver', 'Cielo', 'Lente', 'Astronomia'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'ADN', forbidden: ['Genes', 'Herencia', 'Celula', 'Helice', 'Cuerpo'], category: 'Ciencia', difficulty: 'medium' },
  { term: 'Volcan', forbidden: ['Lava', 'Erupcion', 'Montana', 'Caliente', 'Fuego'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Arcoiris', forbidden: ['Colores', 'Lluvia', 'Sol', 'Arco', 'Cielo'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Fosil', forbidden: ['Dinosaurio', 'Antiguo', 'Piedra', 'Huesos', 'Excavacion'], category: 'Ciencia', difficulty: 'medium' },
  { term: 'Campo magnetico', forbidden: ['Brujula', 'Tierra', 'Norte', 'Sur', 'Atraer'], category: 'Ciencia', difficulty: 'hard' },
  { term: 'Atomo', forbidden: ['Pequeno', 'Nucleo', 'Particula', 'Fisica', 'Electron'], category: 'Ciencia', difficulty: 'medium' },
  { term: 'Agujero negro', forbidden: ['Espacio', 'Gravedad', 'Luz', 'Estrella', 'Absorber'], category: 'Ciencia', difficulty: 'medium' },
  { term: 'Microscopio', forbidden: ['Pequeno', 'Ampliar', 'Lente', 'Laboratorio', 'Ver'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Bateria', forbidden: ['Electricidad', 'Energia', 'Cargar', 'Positivo', 'Negativo'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Dinosaurio', forbidden: ['Extinto', 'Grande', 'Reptil', 'Fosil', 'T-Rex'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Sistema solar', forbidden: ['Planetas', 'Sol', 'Tierra', 'Orbita', 'Espacio'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Vacuna', forbidden: ['Jeringa', 'Medico', 'Enfermedad', 'Proteccion', 'Inmune'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Viaje en el tiempo', forbidden: ['Tiempo', 'Pasado', 'Futuro', 'Maquina', 'Viajar'], category: 'Ciencia', difficulty: 'medium' },

  // === Extra mixto (20) ===
  { term: 'Astronauta', forbidden: ['Espacio', 'Cohete', 'Luna', 'NASA', 'Flotar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Policia', forbidden: ['Uniforme', 'Criminal', 'Sirena', 'Ley', 'Patrulla'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Restaurante', forbidden: ['Comida', 'Camarero', 'Menu', 'Chef', 'Mesa'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Guarderia', forbidden: ['Ninos', 'Jugar', 'Educador', 'Aprender', 'Pequenos'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Gafas de sol', forbidden: ['Sol', 'Ojos', 'Oscuras', 'Verano', 'Llevar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Selva', forbidden: ['Bosque', 'Animales', 'Tropical', 'Monos', 'Plantas'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Autopista', forbidden: ['Coche', 'Rapido', 'Carretera', 'Conducir', 'Velocidad'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Television', forbidden: ['Pantalla', 'Ver', 'Programa', 'Canal', 'Pelicula'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Hospital', forbidden: ['Medico', 'Paciente', 'Enfermo', 'Operacion', 'Cama'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Castillo', forbidden: ['Rey', 'Fortaleza', 'Puerta', 'Llave', 'Cuento'], category: 'Cultura', difficulty: 'medium' },
  { term: 'Ferrocarril', forbidden: ['Tren', 'Railes', 'Estacion', 'Conducir', 'Vias'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Bomberos', forbidden: ['Fuego', 'Apagar', 'Manguera', 'Rojo', 'Sirena'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Guitarra', forbidden: ['Cuerdas', 'Musica', 'Tocar', 'Instrumento', 'Concierto'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Payaso', forbidden: ['Circo', 'Gracioso', 'Nariz', 'Reir', 'Disfraz'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Diamante', forbidden: ['Piedra preciosa', 'Anillo', 'Caro', 'Brillar', 'Duro'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Miel', forbidden: ['Abeja', 'Dulce', 'Tarro', 'Pan', 'Dorada'], category: 'Comida', difficulty: 'easy' },
  { term: 'Faro', forbidden: ['Luz', 'Mar', 'Costa', 'Barco', 'Torre'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Avion', forbidden: ['Volar', 'Piloto', 'Cielo', 'Aeropuerto', 'Nubes'], category: 'Viajes', difficulty: 'easy' },
  { term: 'Dentista', forbidden: ['Dientes', 'Taladro', 'Dolor', 'Consulta', 'Doctor'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Panadero', forbidden: ['Pan', 'Bolleria', 'Hornear', 'Horno', 'Harina'], category: 'Vida diaria', difficulty: 'easy' },
];
