export interface TabooCard {
  term: string;
  forbidden: string[];
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const TABOO_CARDS_PT: TabooCard[] = [
  // === Esporte (21) ===
  { term: 'Futebol', forbidden: ['Bola', 'Gol', 'Jogador', 'Time', 'Estadio'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Tenis', forbidden: ['Raquete', 'Bola', 'Rede', 'Saque', 'Wimbledon'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Basquete', forbidden: ['Cesta', 'Bola', 'Arremessar', 'NBA', 'Enterrada'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Natacao', forbidden: ['Agua', 'Piscina', 'Raia', 'Nado', 'Maio'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Boxe', forbidden: ['Luta', 'Ringue', 'Luvas', 'Soco', 'Round'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Esqui', forbidden: ['Neve', 'Montanha', 'Pista', 'Inverno', 'Teleférico'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Maratona', forbidden: ['Correr', 'Quilometros', 'Distancia', 'Resistencia', 'Chegada'], category: 'Esporte', difficulty: 'medium' },
  { term: 'Golfe', forbidden: ['Bola', 'Taco', 'Buraco', 'Grama', 'Handicap'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Olimpiadas', forbidden: ['Jogos', 'Aneis', 'Medalha', 'Atletas', 'Competicao'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Surfe', forbidden: ['Onda', 'Prancha', 'Mar', 'Praia', 'Agua'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Hoquei no gelo', forbidden: ['Disco', 'Gelo', 'Taco', 'Gol', 'Patins'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Yoga', forbidden: ['Alongamento', 'Meditacao', 'Corpo', 'Postura', 'Relaxamento'], category: 'Esporte', difficulty: 'medium' },
  { term: 'Formula 1', forbidden: ['Corrida', 'Carro', 'Rapido', 'Piloto', 'Circuito'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Escalada', forbidden: ['Parede', 'Rocha', 'Corda', 'Altura', 'Agarras'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Handebol', forbidden: ['Bola', 'Gol', 'Arremessar', 'Equipe', 'Quadra'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Biatlo', forbidden: ['Esqui', 'Tiro', 'Inverno', 'Rifle', 'Fundo'], category: 'Esporte', difficulty: 'hard' },
  { term: 'Dardos', forbidden: ['Flecha', 'Alvo', 'Lancar', 'Pontos', 'Centro'], category: 'Esporte', difficulty: 'medium' },
  { term: 'Volei', forbidden: ['Rede', 'Bola', 'Praia', 'Equipe', 'Cortada'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Esgrima', forbidden: ['Espada', 'Mascara', 'Toque', 'Florete', 'Combate'], category: 'Esporte', difficulty: 'medium' },
  { term: 'Tenis de mesa', forbidden: ['Bola', 'Raquete', 'Mesa', 'Ping', 'Pong'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Paraquedas', forbidden: ['Pular', 'Voar', 'Aviao', 'Abrir', 'Ar'], category: 'Esporte', difficulty: 'easy' },

  // === Comida (27) ===
  { term: 'Pizza', forbidden: ['Italia', 'Massa', 'Cobertura', 'Queijo', 'Forno'], category: 'Comida', difficulty: 'easy' },
  { term: 'Espaguete', forbidden: ['Massa', 'Italia', 'Molho', 'Cozinhar', 'Longo'], category: 'Comida', difficulty: 'easy' },
  { term: 'Chocolate', forbidden: ['Doce', 'Cacau', 'Marrom', 'Barra', 'Leite'], category: 'Comida', difficulty: 'easy' },
  { term: 'Hamburguer', forbidden: ['Carne', 'Pao', 'Fast food', 'McDonalds', 'Hamburger'], category: 'Comida', difficulty: 'easy' },
  { term: 'Sorvete', forbidden: ['Frio', 'Verao', 'Bola', 'Casquinha', 'Doce'], category: 'Comida', difficulty: 'easy' },
  { term: 'Sushi', forbidden: ['Japao', 'Arroz', 'Peixe', 'Alga', 'Cru'], category: 'Comida', difficulty: 'easy' },
  { term: 'Pao de queijo', forbidden: ['Queijo', 'Minas', 'Polvilho', 'Redondo', 'Cafe'], category: 'Comida', difficulty: 'easy' },
  { term: 'Churrasco', forbidden: ['Carne', 'Grelha', 'Carvao', 'Brasil', 'Espeto'], category: 'Comida', difficulty: 'easy' },
  { term: 'Bolo', forbidden: ['Assar', 'Doce', 'Aniversario', 'Creme', 'Forno'], category: 'Comida', difficulty: 'easy' },
  { term: 'Batata frita', forbidden: ['Batata', 'Fritar', 'Ketchup', 'Salgada', 'Fast food'], category: 'Comida', difficulty: 'easy' },
  { term: 'Salada', forbidden: ['Verde', 'Saudavel', 'Legumes', 'Molho', 'Fresca'], category: 'Comida', difficulty: 'easy' },
  { term: 'Croissant', forbidden: ['Franca', 'Cafe da manha', 'Manteiga', 'Massa', 'Padaria'], category: 'Comida', difficulty: 'easy' },
  { term: 'Feijoada', forbidden: ['Feijao', 'Carne', 'Brasil', 'Arroz', 'Sabado'], category: 'Comida', difficulty: 'easy' },
  { term: 'Coxinha', forbidden: ['Frango', 'Frito', 'Massa', 'Salgado', 'Gota'], category: 'Comida', difficulty: 'easy' },
  { term: 'Acai', forbidden: ['Fruta', 'Roxo', 'Amazonia', 'Tigela', 'Granola'], category: 'Comida', difficulty: 'easy' },
  { term: 'Fondue', forbidden: ['Queijo', 'Derreter', 'Panela', 'Suica', 'Mergulhar'], category: 'Comida', difficulty: 'medium' },
  { term: 'Moqueca', forbidden: ['Peixe', 'Bahia', 'Coco', 'Dende', 'Panela'], category: 'Comida', difficulty: 'medium' },
  { term: 'Tiramisu', forbidden: ['Italia', 'Cafe', 'Mascarpone', 'Sobremesa', 'Cacau'], category: 'Comida', difficulty: 'medium' },
  { term: 'Brigadeiro', forbidden: ['Chocolate', 'Leite condensado', 'Festa', 'Granulado', 'Doce'], category: 'Comida', difficulty: 'easy' },
  { term: 'Granola', forbidden: ['Cafe da manha', 'Aveia', 'Iogurte', 'Frutas', 'Saudavel'], category: 'Comida', difficulty: 'easy' },
  { term: 'Empada', forbidden: ['Massa', 'Recheio', 'Frango', 'Camarao', 'Assada'], category: 'Comida', difficulty: 'easy' },
  { term: 'Tacos', forbidden: ['Mexico', 'Milho', 'Carne', 'Salsa', 'Recheio'], category: 'Comida', difficulty: 'easy' },
  { term: 'Raclette', forbidden: ['Queijo', 'Derreter', 'Panelinha', 'Batata', 'Suica'], category: 'Comida', difficulty: 'easy' },
  { term: 'Baguete', forbidden: ['Franca', 'Pao', 'Longo', 'Crosta', 'Padaria'], category: 'Comida', difficulty: 'easy' },
  { term: 'Panetone', forbidden: ['Natal', 'Frutas', 'Massa', 'Doce', 'Italia'], category: 'Comida', difficulty: 'easy' },
  { term: 'Pipoca', forbidden: ['Milho', 'Cinema', 'Salgada', 'Doce', 'Filme'], category: 'Comida', difficulty: 'easy' },
  { term: 'Quentao', forbidden: ['Festa junina', 'Quente', 'Vinho', 'Gengibre', 'Canela'], category: 'Comida', difficulty: 'easy' },

  // === Animais (25) ===
  { term: 'Elefante', forbidden: ['Grande', 'Tromba', 'Africa', 'Cinza', 'Presa'], category: 'Animais', difficulty: 'easy' },
  { term: 'Pinguim', forbidden: ['Gelo', 'Preto e branco', 'Antartica', 'Ave', 'Voar'], category: 'Animais', difficulty: 'easy' },
  { term: 'Girafa', forbidden: ['Pescoco', 'Longo', 'Africa', 'Manchas', 'Alto'], category: 'Animais', difficulty: 'easy' },
  { term: 'Golfinho', forbidden: ['Mar', 'Nadar', 'Inteligente', 'Pular', 'Flipper'], category: 'Animais', difficulty: 'easy' },
  { term: 'Camaleao', forbidden: ['Cor', 'Mudar', 'Lagarto', 'Lingua', 'Camuflagem'], category: 'Animais', difficulty: 'easy' },
  { term: 'Crocodilo', forbidden: ['Dentes', 'Agua', 'Perigoso', 'Reptil', 'Rio'], category: 'Animais', difficulty: 'easy' },
  { term: 'Borboleta', forbidden: ['Asas', 'Colorida', 'Lagarta', 'Voar', 'Flor'], category: 'Animais', difficulty: 'easy' },
  { term: 'Bicho-preguica', forbidden: ['Lento', 'Arvore', 'Pendurar', 'Dormir', 'Preguicoso'], category: 'Animais', difficulty: 'easy' },
  { term: 'Tubarao', forbidden: ['Mar', 'Dentes', 'Perigoso', 'Peixe', 'Barbatana'], category: 'Animais', difficulty: 'easy' },
  { term: 'Beija-flor', forbidden: ['Pequeno', 'Passaro', 'Voar', 'Flor', 'Rapido'], category: 'Animais', difficulty: 'medium' },
  { term: 'Papagaio', forbidden: ['Passaro', 'Falar', 'Colorido', 'Penas', 'Pirata'], category: 'Animais', difficulty: 'easy' },
  { term: 'Urso polar', forbidden: ['Branco', 'Artico', 'Frio', 'Gelo', 'Urso'], category: 'Animais', difficulty: 'easy' },
  { term: 'Flamingo', forbidden: ['Rosa', 'Ave', 'Perna', 'Ficar em pe', 'Lago'], category: 'Animais', difficulty: 'easy' },
  { term: 'Canguru', forbidden: ['Australia', 'Pular', 'Bolsa', 'Filhote', 'Saltar'], category: 'Animais', difficulty: 'easy' },
  { term: 'Pavao', forbidden: ['Penas', 'Leque', 'Colorido', 'Ave', 'Macho'], category: 'Animais', difficulty: 'easy' },
  { term: 'Formiga', forbidden: ['Pequena', 'Inseto', 'Formigueiro', 'Forte', 'Colonia'], category: 'Animais', difficulty: 'easy' },
  { term: 'Hipopotamo', forbidden: ['Agua', 'Africa', 'Grande', 'Boca', 'Rio'], category: 'Animais', difficulty: 'easy' },
  { term: 'Coruja', forbidden: ['Noite', 'Ave', 'Olhos', 'Piar', 'Sabia'], category: 'Animais', difficulty: 'easy' },
  { term: 'Panda', forbidden: ['China', 'Bambu', 'Preto e branco', 'Urso', 'Fofo'], category: 'Animais', difficulty: 'easy' },
  { term: 'Tartaruga', forbidden: ['Casco', 'Lenta', 'Velha', 'Carapaca', 'Reptil'], category: 'Animais', difficulty: 'easy' },
  { term: 'Lobo', forbidden: ['Uivar', 'Matilha', 'Floresta', 'Cao', 'Conto'], category: 'Animais', difficulty: 'easy' },
  { term: 'Polvo', forbidden: ['Bracos', 'Oito', 'Mar', 'Tinta', 'Tentaculo'], category: 'Animais', difficulty: 'medium' },
  { term: 'Cavalo-marinho', forbidden: ['Mar', 'Pequeno', 'Cavalo', 'Nadar', 'Agua'], category: 'Animais', difficulty: 'easy' },
  { term: 'Gorila', forbidden: ['Macaco', 'Grande', 'Forte', 'Selva', 'Dorso prateado'], category: 'Animais', difficulty: 'easy' },
  { term: 'Abelha', forbidden: ['Mel', 'Ferroar', 'Flor', 'Voar', 'Rainha'], category: 'Animais', difficulty: 'easy' },

  // === Tecnologia (20) ===
  { term: 'Smartphone', forbidden: ['Celular', 'Telefone', 'Apple', 'Apps', 'Tela'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Internet', forbidden: ['Online', 'Rede', 'Navegar', 'Site', 'Conexao'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Computador', forbidden: ['Maquina', 'Tela', 'Teclado', 'Mouse', 'PC'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Robo', forbidden: ['Maquina', 'Artificial', 'Metal', 'Automatico', 'Tecnologia'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Inteligencia artificial', forbidden: ['Computador', 'Robo', 'Aprender', 'Maquina', 'Algoritmo'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Drone', forbidden: ['Voar', 'Camera', 'Controle remoto', 'Helice', 'Ar'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'WiFi', forbidden: ['Internet', 'Sem fio', 'Conexao', 'Roteador', 'Rede'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Selfie', forbidden: ['Foto', 'Camera', 'Celular', 'Proprio', 'Imagem'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Impressora 3D', forbidden: ['Imprimir', 'Tridimensional', 'Plastico', 'Camada', 'Modelo'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Realidade virtual', forbidden: ['Oculos', 'Virtual', 'Mundo', 'Computador', 'Simulacao'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Bluetooth', forbidden: ['Sem fio', 'Conexao', 'Celular', 'Fone', 'Radio'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Streaming', forbidden: ['Filme', 'Musica', 'Netflix', 'Internet', 'Video'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'GPS', forbidden: ['Navegacao', 'Localizacao', 'Satelite', 'Mapa', 'Posicao'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Carro eletrico', forbidden: ['Energia', 'Tesla', 'Bateria', 'Dirigir', 'Carregar'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Redes sociais', forbidden: ['Facebook', 'Instagram', 'Rede', 'Compartilhar', 'Seguidor'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Podcast', forbidden: ['Audio', 'Ouvir', 'Programa', 'Spotify', 'Episodio'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Alexa', forbidden: ['Amazon', 'Assistente de voz', 'Falar', 'Inteligente', 'Alto-falante'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Tablet', forbidden: ['iPad', 'Tela', 'Toque', 'Computador', 'Portatil'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Algoritmo', forbidden: ['Calculo', 'Computador', 'Passo', 'Programa', 'Logica'], category: 'Tecnologia', difficulty: 'hard' },
  { term: 'Blockchain', forbidden: ['Bitcoin', 'Cripto', 'Descentralizado', 'Cadeia', 'Dados'], category: 'Tecnologia', difficulty: 'hard' },

  // === Famosos (15) ===
  { term: 'Albert Einstein', forbidden: ['Relatividade', 'Fisica', 'Genio', 'E=mc2', 'Cabelo'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Mozart', forbidden: ['Musica', 'Compositor', 'Salzburgo', 'Piano', 'Classico'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Pele', forbidden: ['Futebol', 'Brasil', 'Gol', 'Rei', 'Santos'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Beethoven', forbidden: ['Musica', 'Compositor', 'Surdo', 'Sinfonia', 'Piano'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Leonardo da Vinci', forbidden: ['Mona Lisa', 'Pintor', 'Inventor', 'Renascimento', 'Italia'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Cristiano Ronaldo', forbidden: ['Futebol', 'Portugal', 'Gol', 'Real Madrid', 'Atacante'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Carmen Miranda', forbidden: ['Cantora', 'Frutas', 'Hollywood', 'Brasil', 'Danca'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Elon Musk', forbidden: ['Tesla', 'SpaceX', 'Bilionario', 'Twitter', 'Empreendedor'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Machado de Assis', forbidden: ['Escritor', 'Brasil', 'Romance', 'Literatura', 'Dom Casmurro'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Cleopatra', forbidden: ['Egito', 'Rainha', 'Farao', 'Nilo', 'Cesar'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Napoleao', forbidden: ['Franca', 'Imperador', 'Guerra', 'Baixo', 'Waterloo'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Marie Curie', forbidden: ['Radioatividade', 'Fisica', 'Nobel', 'Ciencia', 'Pesquisa'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Michael Jackson', forbidden: ['Cantor', 'Thriller', 'Danca', 'Pop', 'Rei'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Lionel Messi', forbidden: ['Futebol', 'Argentina', 'Barcelona', 'Gol', 'Copa do Mundo'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Ayrton Senna', forbidden: ['Formula 1', 'Brasil', 'Piloto', 'Velocidade', 'Campeonato'], category: 'Famosos', difficulty: 'easy' },

  // === Vida diaria (32) + Viagens (18) + Cultura (20) + Ciencia (16) + Extra (20) — abbreviated for file size
  // Categories follow same pattern as German original with Brazilian Portuguese cultural adaptation
  { term: 'Despertador', forbidden: ['Manha', 'Acordar', 'Relogio', 'Tocar', 'Alarme'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Escova de dentes', forbidden: ['Dentes', 'Escovar', 'Boca', 'Pasta', 'Banheiro'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Chave', forbidden: ['Porta', 'Abrir', 'Fechadura', 'Casa', 'Fechar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Guarda-chuva', forbidden: ['Chuva', 'Molhado', 'Tempo', 'Proteger', 'Seco'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Oculos', forbidden: ['Olhos', 'Ver', 'Lente', 'Otica', 'Nariz'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Geladeira', forbidden: ['Fria', 'Comida', 'Cozinha', 'Guardar', 'Porta'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Aspirador', forbidden: ['Aspirar', 'Sujeira', 'Tapete', 'Limpar', 'Chao'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Maquina de lavar', forbidden: ['Roupas', 'Lavar', 'Agua', 'Centrifugar', 'Roupa'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Semaforo', forbidden: ['Vermelho', 'Verde', 'Amarelo', 'Rua', 'Transito'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Elevador', forbidden: ['Subir', 'Descer', 'Andar', 'Botoes', 'Predio'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Cobertor', forbidden: ['Cama', 'Dormir', 'Quente', 'Travesseiro', 'Cobrir'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Controle remoto', forbidden: ['Televisao', 'Botoes', 'Trocar', 'Canal', 'Sofa'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Carteira', forbidden: ['Dinheiro', 'Moedas', 'Cartoes', 'Bolso', 'Pagar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Estacionamento', forbidden: ['Carro', 'Estacionar', 'Parar', 'Vaga', 'Procurar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Garrafa de agua', forbidden: ['Agua', 'Beber', 'Garrafa', 'Tampa', 'Levar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Aniversario', forbidden: ['Comemorar', 'Bolo', 'Presentes', 'Velas', 'Festa'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Supermercado', forbidden: ['Compras', 'Caixa', 'Prateleiras', 'Loja', 'Alimentos'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Cabeleireiro', forbidden: ['Cabelo', 'Cortar', 'Tesoura', 'Salao', 'Penteado'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Biblioteca', forbidden: ['Livros', 'Ler', 'Emprestar', 'Silencio', 'Estantes'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Engarrafamento', forbidden: ['Carro', 'Rua', 'Esperar', 'Transito', 'Rodovia'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Academia', forbidden: ['Esporte', 'Treinar', 'Musculos', 'Aparelhos', 'Pesos'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Protetor solar', forbidden: ['Sol', 'Pele', 'Protecao', 'Praia', 'Passar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Montanha-russa', forbidden: ['Parque', 'Rapido', 'Trilhos', 'Curvas', 'Adrenalina'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Roda-gigante', forbidden: ['Parque', 'Girar', 'Alto', 'Cabine', 'Vista'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Boneco de neve', forbidden: ['Neve', 'Inverno', 'Cenoura', 'Nariz', 'Frio'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Fogueira', forbidden: ['Fogo', 'Lenha', 'Noite', 'Quente', 'Marshmallow'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Bolha de sabao', forbidden: ['Sabao', 'Bolha', 'Soprar', 'Redonda', 'Estourar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Lanterna', forbidden: ['Luz', 'Pilha', 'Escuro', 'Iluminar', 'Lampada'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Balao', forbidden: ['Ar', 'Encher', 'Festa', 'Colorido', 'Estourar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Castelo de areia', forbidden: ['Areia', 'Praia', 'Construir', 'Mar', 'Balde'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Quebra-cabeca', forbidden: ['Pecas', 'Montar', 'Imagem', 'Enigma', 'Paciencia'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Casa na arvore', forbidden: ['Arvore', 'Criancas', 'Madeira', 'Cima', 'Casa'], category: 'Vida diaria', difficulty: 'easy' },
  // === Viagens ===
  { term: 'Mala', forbidden: ['Viagem', 'Arrumar', 'Roupas', 'Aeroporto', 'Ferias'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Passaporte', forbidden: ['Fronteira', 'Documento', 'Foto', 'Aeroporto', 'Visto'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Hotel', forbidden: ['Quarto', 'Dormir', 'Cama', 'Recepcao', 'Ferias'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Aeroporto', forbidden: ['Aviao', 'Voar', 'Portao', 'Embarque', 'Terminal'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Cruzeiro', forbidden: ['Navio', 'Mar', 'Viagem', 'Cabine', 'Ferias'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Souvenir', forbidden: ['Lembranca', 'Memoria', 'Comprar', 'Ferias', 'Presente'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Trilha', forbidden: ['Montanha', 'Natureza', 'Caminho', 'Andar', 'Mochila'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Acampamento', forbidden: ['Barraca', 'Natureza', 'Ar livre', 'Camping', 'Dormir'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Ferias na praia', forbidden: ['Mar', 'Sol', 'Areia', 'Praia', 'Nadar'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Passeio pela cidade', forbidden: ['Cidade', 'Guia', 'Pontos turisticos', 'Grupo', 'Tour'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Cartao de embarque', forbidden: ['Aviao', 'Assento', 'Portao', 'Embarque', 'Voar'], category: 'Viagens', difficulty: 'medium' },
  { term: 'Jet lag', forbidden: ['Fuso horario', 'Cansado', 'Voo', 'Viagem', 'Sono'], category: 'Viagens', difficulty: 'medium' },
  { term: 'Mochilao', forbidden: ['Mochila', 'Viajar', 'Barato', 'Hostel', 'Mundo'], category: 'Viagens', difficulty: 'medium' },
  { term: 'Viagem de carro', forbidden: ['Carro', 'Dirigir', 'Estrada', 'Viagem', 'Rota'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Mergulho', forbidden: ['Agua', 'Mascara', 'Mar', 'Peixes', 'Submergir'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Balao de ar quente', forbidden: ['Voar', 'Ar', 'Cesto', 'Quente', 'Chama'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Caminhada noturna', forbidden: ['Noite', 'Escuro', 'Floresta', 'Lanterna', 'Andar'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Saco de dormir', forbidden: ['Dormir', 'Acampamento', 'Quente', 'Barraca', 'Noite'], category: 'Viagens', difficulty: 'easy' },
  // === Cultura + Ciencia + Extra ===
  { term: 'Opera', forbidden: ['Cantar', 'Palco', 'Musica', 'Teatro', 'Orquestra'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Museu', forbidden: ['Arte', 'Exposicao', 'Quadros', 'Visitantes', 'Galeria'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Carnaval', forbidden: ['Fantasia', 'Desfile', 'Comemorar', 'Mascara', 'Samba'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Festa Junina', forbidden: ['Junho', 'Fogueira', 'Quadrilha', 'Milho', 'Bandeirinha'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Casamento', forbidden: ['Noiva', 'Noivo', 'Aliancas', 'Igreja', 'Casar'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Cinema', forbidden: ['Filme', 'Pipoca', 'Tela', 'Sala', 'Ingressos'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Cristo Redentor', forbidden: ['Rio', 'Estatua', 'Corcovado', 'Brasil', 'Bracos'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Gravidade', forbidden: ['Terra', 'Cair', 'Newton', 'Fisica', 'Atrair'], category: 'Ciencia', difficulty: 'medium' },
  { term: 'Vulcao', forbidden: ['Lava', 'Erupcao', 'Montanha', 'Quente', 'Fogo'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Arco-iris', forbidden: ['Cores', 'Chuva', 'Sol', 'Arco', 'Ceu'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Dinossauro', forbidden: ['Extinto', 'Grande', 'Reptil', 'Fossil', 'T-Rex'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Astronauta', forbidden: ['Espaco', 'Foguete', 'Lua', 'NASA', 'Flutuar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Restaurante', forbidden: ['Comida', 'Garcom', 'Cardapio', 'Chef', 'Mesa'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Hospital', forbidden: ['Medico', 'Paciente', 'Doente', 'Cirurgia', 'Cama'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Televisao', forbidden: ['Tela', 'Assistir', 'Programa', 'Canal', 'Filme'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Dentista', forbidden: ['Dentes', 'Broca', 'Dor', 'Consultorio', 'Doutor'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Padeiro', forbidden: ['Pao', 'Paes', 'Assar', 'Forno', 'Farinha'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Aviao', forbidden: ['Voar', 'Piloto', 'Ceu', 'Aeroporto', 'Nuvens'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Farol', forbidden: ['Luz', 'Mar', 'Costa', 'Navio', 'Torre'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Guitarra', forbidden: ['Cordas', 'Musica', 'Tocar', 'Instrumento', 'Show'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Ciclismo', forbidden: ['bicicleta', 'pedalar', 'roda', 'corrida', 'capacete'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Andebol', forbidden: ['bola', 'baliza', 'mao', 'equipa', 'pavilhao'], category: 'Esporte', difficulty: 'medium' },
  { term: 'Remo', forbidden: ['barco', 'agua', 'remos', 'equipa', 'rio'], category: 'Esporte', difficulty: 'medium' },
  { term: 'Patinagem', forbidden: ['gelo', 'patins', 'deslizar', 'pista', 'rodas'], category: 'Esporte', difficulty: 'medium' },
  { term: 'Ginastica', forbidden: ['barra', 'salto', 'flexibilidade', 'colchao', 'corpo'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Badminton', forbidden: ['raquete', 'volante', 'rede', 'penas', 'bater'], category: 'Esporte', difficulty: 'hard' },
  { term: 'Halterofilismo', forbidden: ['pesos', 'levantar', 'barra', 'forca', 'musculos'], category: 'Esporte', difficulty: 'hard' },
  { term: 'Treinador', forbidden: ['equipa', 'jogadores', 'tatica', 'apito', 'banco'], category: 'Esporte', difficulty: 'medium' },
  { term: 'Estadio', forbidden: ['futebol', 'bancadas', 'adeptos', 'relva', 'jogo'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Penalti', forbidden: ['futebol', 'golo', 'guarda-redes', 'marca', 'castigo'], category: 'Esporte', difficulty: 'medium' },
  { term: 'Medalha', forbidden: ['ouro', 'vencedor', 'pescoco', 'podio', 'premio'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Arbitro', forbidden: ['apito', 'cartao', 'jogo', 'falta', 'decisao'], category: 'Esporte', difficulty: 'easy' },
  { term: 'Cronometro', forbidden: ['tempo', 'segundos', 'medir', 'corrida', 'botao'], category: 'Esporte', difficulty: 'hard' },
  { term: 'Bacalhau', forbidden: ['peixe', 'sal', 'seco', 'Portugal', 'Natal'], category: 'Comida', difficulty: 'easy' },
  { term: 'Pastel de nata', forbidden: ['creme', 'massa', 'Belem', 'forno', 'doce'], category: 'Comida', difficulty: 'easy' },
  { term: 'Caldo verde', forbidden: ['couve', 'sopa', 'batata', 'chourico', 'verde'], category: 'Comida', difficulty: 'medium' },
  { term: 'Francesinha', forbidden: ['Porto', 'sanduiche', 'molho', 'queijo', 'carne'], category: 'Comida', difficulty: 'medium' },
  { term: 'Queijo', forbidden: ['leite', 'amarelo', 'ratos', 'fatia', 'sabor'], category: 'Comida', difficulty: 'easy' },
  { term: 'Omelete', forbidden: ['ovos', 'frigideira', 'bater', 'dobrar', 'fritar'], category: 'Comida', difficulty: 'easy' },
  { term: 'Panqueca', forbidden: ['massa', 'frigideira', 'fina', 'xarope', 'redonda'], category: 'Comida', difficulty: 'easy' },
  { term: 'Cogumelo', forbidden: ['fungo', 'floresta', 'chapeu', 'comestivel', 'veneno'], category: 'Comida', difficulty: 'medium' },
  { term: 'Mel', forbidden: ['abelha', 'doce', 'dourado', 'colmeia', 'viscoso'], category: 'Comida', difficulty: 'easy' },
  { term: 'Caril', forbidden: ['picante', 'India', 'molho', 'amarelo', 'especiarias'], category: 'Comida', difficulty: 'medium' },
  { term: 'Risotto', forbidden: ['arroz', 'cremoso', 'Italia', 'queijo', 'mexer'], category: 'Comida', difficulty: 'hard' },
  { term: 'Lasanha', forbidden: ['camadas', 'massa', 'forno', 'molho', 'queijo'], category: 'Comida', difficulty: 'medium' },
  { term: 'Marmelada', forbidden: ['marmelo', 'doce', 'fruta', 'barra', 'compota'], category: 'Comida', difficulty: 'hard' },
  { term: 'Leao', forbidden: ['juba', 'rei', 'selva', 'rugido', 'felino'], category: 'Animais', difficulty: 'easy' },
  { term: 'Cao', forbidden: ['ladrar', 'fiel', 'osso', 'trela', 'amigo'], category: 'Animais', difficulty: 'easy' },
  { term: 'Gato', forbidden: ['miar', 'ratos', 'bigodes', 'arranhar', 'felino'], category: 'Animais', difficulty: 'easy' },
  { term: 'Cobra', forbidden: ['rastejar', 'veneno', 'lingua', 'sibilar', 'escamas'], category: 'Animais', difficulty: 'easy' },
  { term: 'Aguia', forbidden: ['voar', 'bico', 'garras', 'ave', 'caca'], category: 'Animais', difficulty: 'medium' },
  { term: 'Raposa', forbidden: ['esperta', 'cauda', 'laranja', 'floresta', 'astuta'], category: 'Animais', difficulty: 'medium' },
  { term: 'Coelho', forbidden: ['orelhas', 'cenoura', 'saltar', 'tocas', 'peludo'], category: 'Animais', difficulty: 'easy' },
  { term: 'Macaco', forbidden: ['banana', 'arvore', 'trepar', 'cauda', 'selva'], category: 'Animais', difficulty: 'easy' },
  { term: 'Zebra', forbidden: ['riscas', 'preto', 'branco', 'Africa', 'cavalo'], category: 'Animais', difficulty: 'medium' },
  { term: 'Morcego', forbidden: ['noite', 'voar', 'caverna', 'sangue', 'asas'], category: 'Animais', difficulty: 'medium' },
  { term: 'Ourico-cacheiro', forbidden: ['espinhos', 'picar', 'bola', 'pequeno', 'jardim'], category: 'Animais', difficulty: 'hard' },
  { term: 'Toupeira', forbidden: ['terra', 'cego', 'tunel', 'escavar', 'subterraneo'], category: 'Animais', difficulty: 'hard' },
  { term: 'Lagosta', forbidden: ['mar', 'pincas', 'vermelha', 'marisco', 'cozer'], category: 'Animais', difficulty: 'medium' },
  { term: 'Auscultadores', forbidden: ['ouvidos', 'musica', 'som', 'ouvir', 'cabos'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Teclado', forbidden: ['teclas', 'escrever', 'computador', 'letras', 'digitar'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Rato', forbidden: ['computador', 'clicar', 'cursor', 'ecra', 'mover'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Ecra', forbidden: ['televisao', 'imagem', 'brilho', 'pixeis', 'mostrar'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Camara', forbidden: ['fotografia', 'lente', 'tirar', 'foto', 'clique'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Carregador', forbidden: ['bateria', 'ficha', 'telemovel', 'energia', 'cabo'], category: 'Tecnologia', difficulty: 'easy' },
  { term: 'Aplicacao', forbidden: ['telemovel', 'instalar', 'ecra', 'programa', 'descarregar'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Palavra-passe', forbidden: ['secreta', 'entrar', 'conta', 'letras', 'seguranca'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Satelite', forbidden: ['espaco', 'orbita', 'sinal', 'antena', 'Terra'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Consola', forbidden: ['jogos', 'comando', 'videojogos', 'televisao', 'jogar'], category: 'Tecnologia', difficulty: 'medium' },
  { term: 'Realidade aumentada', forbidden: ['virtual', 'camara', 'ecra', 'sobrepor', 'filtros'], category: 'Tecnologia', difficulty: 'hard' },
  { term: 'Servidor', forbidden: ['dados', 'internet', 'armazenar', 'rede', 'computador'], category: 'Tecnologia', difficulty: 'hard' },
  { term: 'Codigo QR', forbidden: ['quadrado', 'digitalizar', 'camara', 'preto', 'ligacao'], category: 'Tecnologia', difficulty: 'hard' },
  { term: 'Amalia Rodrigues', forbidden: ['fado', 'cantora', 'Portugal', 'voz', 'saudade'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Luis de Camoes', forbidden: ['poeta', 'Lusiadas', 'Portugal', 'olho', 'escritor'], category: 'Famosos', difficulty: 'medium' },
  { term: 'William Shakespeare', forbidden: ['escritor', 'Hamlet', 'teatro', 'Ingles', 'Romeu'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Pablo Picasso', forbidden: ['pintor', 'arte', 'cubismo', 'Espanha', 'quadro'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Charlie Chaplin', forbidden: ['cinema', 'mudo', 'bigode', 'comico', 'bengala'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Madonna', forbidden: ['cantora', 'pop', 'palco', 'musica', 'rainha'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Walt Disney', forbidden: ['desenhos', 'Mickey', 'parque', 'animacao', 'filmes'], category: 'Famosos', difficulty: 'easy' },
  { term: 'Usain Bolt', forbidden: ['corredor', 'velocidade', 'Jamaica', 'recorde', 'sprint'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Steve Jobs', forbidden: ['Apple', 'iPhone', 'computador', 'tecnologia', 'fundador'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Frida Kahlo', forbidden: ['pintora', 'Mexico', 'sobrancelhas', 'autorretrato', 'arte'], category: 'Famosos', difficulty: 'hard' },
  { term: 'Nelson Mandela', forbidden: ['Africa', 'prisao', 'presidente', 'apartheid', 'liberdade'], category: 'Famosos', difficulty: 'medium' },
  { term: 'Vincent van Gogh', forbidden: ['pintor', 'orelha', 'girassois', 'quadro', 'Holanda'], category: 'Famosos', difficulty: 'hard' },
  { term: 'Fernando Pessoa', forbidden: ['poeta', 'Lisboa', 'heteronimos', 'escritor', 'cafe'], category: 'Famosos', difficulty: 'hard' },
  { term: 'Pequeno-almoco', forbidden: ['manha', 'cafe', 'comer', 'torradas', 'primeira'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Dormir', forbidden: ['cama', 'noite', 'sono', 'olhos', 'descansar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Tomar banho', forbidden: ['agua', 'chuveiro', 'sabonete', 'limpar', 'corpo'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Cozinhar', forbidden: ['comida', 'fogao', 'panela', 'receita', 'preparar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Limpar', forbidden: ['po', 'casa', 'esfregar', 'sujidade', 'arrumar'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Roupa', forbidden: ['vestir', 'corpo', 'armario', 'tecido', 'cores'], category: 'Vida diaria', difficulty: 'easy' },
  { term: 'Talheres', forbidden: ['garfo', 'faca', 'colher', 'comer', 'mesa'], category: 'Vida diaria', difficulty: 'medium' },
  { term: 'Vassoura', forbidden: ['varrer', 'chao', 'po', 'pelos', 'limpar'], category: 'Vida diaria', difficulty: 'medium' },
  { term: 'Correio', forbidden: ['cartas', 'carteiro', 'selo', 'caixa', 'enviar'], category: 'Vida diaria', difficulty: 'medium' },
  { term: 'Vizinho', forbidden: ['casa', 'lado', 'porta', 'predio', 'conhecido'], category: 'Vida diaria', difficulty: 'medium' },
  { term: 'Recibo', forbidden: ['compra', 'papel', 'loja', 'pagamento', 'comprovativo'], category: 'Vida diaria', difficulty: 'hard' },
  { term: 'Estendal', forbidden: ['roupa', 'secar', 'molas', 'fios', 'varanda'], category: 'Vida diaria', difficulty: 'hard' },
  { term: 'Tomada', forbidden: ['parede', 'eletricidade', 'ficha', 'ligar', 'corrente'], category: 'Vida diaria', difficulty: 'medium' },
  { term: 'Comboio', forbidden: ['estacao', 'carris', 'carruagem', 'viagem', 'bilhete'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Bussola', forbidden: ['norte', 'agulha', 'direcao', 'orientar', 'mapa'], category: 'Viagens', difficulty: 'medium' },
  { term: 'Mapa', forbidden: ['estradas', 'localizacao', 'papel', 'direcao', 'caminho'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Praia', forbidden: ['areia', 'mar', 'sol', 'ondas', 'toalha'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Montanha', forbidden: ['alta', 'neve', 'subir', 'cume', 'rocha'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Autocarro', forbidden: ['paragem', 'passageiros', 'bilhete', 'rodas', 'cidade'], category: 'Viagens', difficulty: 'easy' },
  { term: 'Tenda', forbidden: ['acampar', 'dormir', 'estacas', 'exterior', 'tecido'], category: 'Viagens', difficulty: 'medium' },
  { term: 'Guia turistico', forbidden: ['turistas', 'explicar', 'cidade', 'grupo', 'monumentos'], category: 'Viagens', difficulty: 'medium' },
  { term: 'Ilha', forbidden: ['mar', 'rodeada', 'terra', 'praia', 'barco'], category: 'Viagens', difficulty: 'medium' },
  { term: 'Deserto', forbidden: ['areia', 'calor', 'camelo', 'seco', 'dunas'], category: 'Viagens', difficulty: 'medium' },
  { term: 'Funicular', forbidden: ['Lisboa', 'subir', 'ladeira', 'carris', 'colina'], category: 'Viagens', difficulty: 'hard' },
  { term: 'Albergue', forbidden: ['dormir', 'barato', 'mochileiros', 'camas', 'quartos'], category: 'Viagens', difficulty: 'hard' },
  { term: 'Cataratas', forbidden: ['agua', 'queda', 'rio', 'altura', 'ruido'], category: 'Viagens', difficulty: 'hard' },
  { term: 'Teatro', forbidden: ['palco', 'atores', 'peca', 'publico', 'cortina'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Fado', forbidden: ['Portugal', 'guitarra', 'cantar', 'saudade', 'Lisboa'], category: 'Cultura', difficulty: 'medium' },
  { term: 'Pintura', forbidden: ['quadro', 'tinta', 'pincel', 'artista', 'tela'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Concerto', forbidden: ['musica', 'palco', 'banda', 'publico', 'tocar'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Estatua', forbidden: ['pedra', 'praca', 'escultura', 'figura', 'monumento'], category: 'Cultura', difficulty: 'medium' },
  { term: 'Igreja', forbidden: ['padre', 'reza', 'altar', 'sino', 'cruz'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Festival', forbidden: ['musica', 'palcos', 'verao', 'multidao', 'bandas'], category: 'Cultura', difficulty: 'medium' },
  { term: 'Danca', forbidden: ['musica', 'corpo', 'movimento', 'passos', 'ritmo'], category: 'Cultura', difficulty: 'easy' },
  { term: 'Ballet', forbidden: ['danca', 'bailarina', 'pontas', 'palco', 'tutu'], category: 'Cultura', difficulty: 'medium' },
  { term: 'Azulejo', forbidden: ['parede', 'ceramica', 'azul', 'Portugal', 'quadrado'], category: 'Cultura', difficulty: 'hard' },
  { term: 'Orquestra', forbidden: ['musicos', 'maestro', 'instrumentos', 'tocar', 'violino'], category: 'Cultura', difficulty: 'hard' },
  { term: 'Mosteiro', forbidden: ['monges', 'reza', 'pedra', 'claustro', 'antigo'], category: 'Cultura', difficulty: 'hard' },
  { term: 'Atomo', forbidden: ['pequeno', 'particula', 'nucleo', 'eletroes', 'materia'], category: 'Ciencia', difficulty: 'medium' },
  { term: 'Eletricidade', forbidden: ['corrente', 'energia', 'tomada', 'fios', 'luz'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Esqueleto', forbidden: ['ossos', 'corpo', 'cranio', 'humano', 'estrutura'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Planeta', forbidden: ['espaco', 'orbita', 'Terra', 'Sol', 'redondo'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Microscopio', forbidden: ['ampliar', 'lente', 'celulas', 'pequeno', 'laboratorio'], category: 'Ciencia', difficulty: 'medium' },
  { term: 'Iman', forbidden: ['atrair', 'metal', 'polos', 'frigorifico', 'campo'], category: 'Ciencia', difficulty: 'medium' },
  { term: 'Coracao', forbidden: ['bater', 'sangue', 'peito', 'orgao', 'pulsar'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Telescopio', forbidden: ['estrelas', 'ver', 'longe', 'lente', 'ceu'], category: 'Ciencia', difficulty: 'medium' },
  { term: 'Cerebro', forbidden: ['cabeca', 'pensar', 'orgao', 'neuronios', 'memoria'], category: 'Ciencia', difficulty: 'easy' },
  { term: 'Fotossintese', forbidden: ['plantas', 'luz', 'folhas', 'oxigenio', 'clorofila'], category: 'Ciencia', difficulty: 'hard' },
  { term: 'Eclipse', forbidden: ['Sol', 'Lua', 'sombra', 'escuro', 'alinhar'], category: 'Ciencia', difficulty: 'medium' },
  { term: 'Bacteria', forbidden: ['microbio', 'doenca', 'pequena', 'microscopio', 'germe'], category: 'Ciencia', difficulty: 'hard' },
  { term: 'Evolucao', forbidden: ['Darwin', 'especies', 'mudanca', 'adaptar', 'tempo'], category: 'Ciencia', difficulty: 'hard' },
];
