export interface TabooCard {
  term: string;
  forbidden: string[];
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const TABOO_CARDS_TR: TabooCard[] = [
  // === Spor (21) ===
  { term: 'Futbol', forbidden: ['Top', 'Gol', 'Oyuncu', 'Takim', 'Stadyum'], category: 'Spor', difficulty: 'easy' },
  { term: 'Tenis', forbidden: ['Raket', 'Top', 'File', 'Servis', 'Wimbledon'], category: 'Spor', difficulty: 'easy' },
  { term: 'Basketbol', forbidden: ['Pota', 'Top', 'Atmak', 'NBA', 'Smaç'], category: 'Spor', difficulty: 'easy' },
  { term: 'Yuzme', forbidden: ['Su', 'Havuz', 'Kulvar', 'Stil', 'Mayo'], category: 'Spor', difficulty: 'easy' },
  { term: 'Boks', forbidden: ['Dovus', 'Ring', 'Eldiven', 'Yumruk', 'Raund'], category: 'Spor', difficulty: 'easy' },
  { term: 'Kayak', forbidden: ['Kar', 'Dag', 'Pist', 'Kis', 'Teleferik'], category: 'Spor', difficulty: 'easy' },
  { term: 'Maraton', forbidden: ['Kosmak', 'Kilometre', 'Mesafe', 'Dayaniklilik', 'Bitis'], category: 'Spor', difficulty: 'medium' },
  { term: 'Golf', forbidden: ['Top', 'Sopa', 'Delik', 'Cim', 'Handikap'], category: 'Spor', difficulty: 'easy' },
  { term: 'Olimpiyat', forbidden: ['Oyunlar', 'Halkalar', 'Madalya', 'Sporcular', 'Yarisma'], category: 'Spor', difficulty: 'easy' },
  { term: 'Sorf', forbidden: ['Dalga', 'Tahta', 'Deniz', 'Plaj', 'Su'], category: 'Spor', difficulty: 'easy' },
  { term: 'Buz hokeyi', forbidden: ['Disk', 'Buz', 'Sopa', 'Kale', 'Paten'], category: 'Spor', difficulty: 'easy' },
  { term: 'Yoga', forbidden: ['Esneme', 'Meditasyon', 'Vucut', 'Poz', 'Rahatlama'], category: 'Spor', difficulty: 'medium' },
  { term: 'Formula 1', forbidden: ['Yaris', 'Araba', 'Hizli', 'Pilot', 'Pist'], category: 'Spor', difficulty: 'easy' },
  { term: 'Tirmanma', forbidden: ['Duvar', 'Kaya', 'Ip', 'Yukseklik', 'Tutamak'], category: 'Spor', difficulty: 'easy' },
  { term: 'Hentbol', forbidden: ['Top', 'Kale', 'Atmak', 'Takim', 'Salon'], category: 'Spor', difficulty: 'easy' },
  { term: 'Biatlon', forbidden: ['Kayak', 'Atis', 'Kis', 'Tufek', 'Kayakli kos'], category: 'Spor', difficulty: 'hard' },
  { term: 'Dart', forbidden: ['Ok', 'Hedef', 'Atmak', 'Puan', 'Merkez'], category: 'Spor', difficulty: 'medium' },
  { term: 'Voleybol', forbidden: ['File', 'Top', 'Plaj', 'Takim', 'Smaç'], category: 'Spor', difficulty: 'easy' },
  { term: 'Eskrim', forbidden: ['Kilic', 'Maske', 'Temas', 'Flore', 'Dovus'], category: 'Spor', difficulty: 'medium' },
  { term: 'Masa tenisi', forbidden: ['Top', 'Raket', 'Masa', 'Ping', 'Pong'], category: 'Spor', difficulty: 'easy' },
  { term: 'Parasut', forbidden: ['Atlamak', 'Ucmak', 'Ucak', 'Acmak', 'Hava'], category: 'Spor', difficulty: 'easy' },

  // === Yemek (27) ===
  { term: 'Pizza', forbidden: ['Italya', 'Hamur', 'Malzeme', 'Peynir', 'Firin'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Spagetti', forbidden: ['Makarna', 'Italya', 'Sos', 'Pişirmek', 'Uzun'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Cikolata', forbidden: ['Tatli', 'Kakao', 'Kahverengi', 'Tablet', 'Sut'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Hamburger', forbidden: ['Et', 'Ekmek', 'Fast food', 'McDonalds', 'Kofte'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Dondurma', forbidden: ['Soguk', 'Yaz', 'Top', 'Kulah', 'Tatli'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Sushi', forbidden: ['Japonya', 'Pirinc', 'Balik', 'Yosun', 'Cig'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Lahmacun', forbidden: ['Hamur', 'Kiyma', 'Firin', 'Limon', 'Ince'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Doner', forbidden: ['Et', 'Ekmek', 'Cevirmek', 'Sis', 'Sos'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Pasta', forbidden: ['Pişirmek', 'Tatli', 'Dogum gunu', 'Krema', 'Firin'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Patates kizartmasi', forbidden: ['Patates', 'Kizartmak', 'Ketcap', 'Tuzlu', 'Fast food'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Salata', forbidden: ['Yesil', 'Saglikli', 'Sebze', 'Sos', 'Taze'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Simit', forbidden: ['Susam', 'Halka', 'Istanbul', 'Cay', 'Firinci'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Manti', forbidden: ['Hamur', 'Kiyma', 'Yogurt', 'Kayseri', 'Kucuk'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Borek', forbidden: ['Hamur', 'Peynir', 'Firin', 'Yufka', 'Ispanak'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Iskender', forbidden: ['Et', 'Doner', 'Yogurt', 'Bursa', 'Sos'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Fondu', forbidden: ['Peynir', 'Eritmek', 'Tencere', 'Isvicre', 'Batirmak'], category: 'Yemek', difficulty: 'medium' },
  { term: 'Pide', forbidden: ['Hamur', 'Firin', 'Peynir', 'Karadeniz', 'Tekne'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Tiramisu', forbidden: ['Italya', 'Kahve', 'Mascarpone', 'Tatli', 'Kakao'], category: 'Yemek', difficulty: 'medium' },
  { term: 'Kebap', forbidden: ['Et', 'Sis', 'Mangal', 'Adana', 'Ates'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Musli', forbidden: ['Kahvalti', 'Yulaf', 'Sut', 'Meyve', 'Saglikli'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Kofte', forbidden: ['Et', 'Kiyma', 'Izgara', 'Ekmek', 'Yuvarlak'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Taco', forbidden: ['Meksika', 'Misir', 'Et', 'Salsa', 'Dolgu'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Raclette', forbidden: ['Peynir', 'Eritmek', 'Tava', 'Patates', 'Isvicre'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Baget', forbidden: ['Fransa', 'Ekmek', 'Uzun', 'Kabuk', 'Firinci'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Baklava', forbidden: ['Tatli', 'Yufka', 'Fistik', 'Serbet', 'Antep'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Patlamis misir', forbidden: ['Misir', 'Sinema', 'Tuzlu', 'Tatli', 'Film'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Salep', forbidden: ['Kis', 'Sicak', 'Sut', 'Tarcin', 'Icicek'], category: 'Yemek', difficulty: 'easy' },

  // === Hayvanlar (25) ===
  { term: 'Fil', forbidden: ['Buyuk', 'Hortum', 'Afrika', 'Gri', 'Dis'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Penguen', forbidden: ['Buz', 'Siyah beyaz', 'Antarktika', 'Kus', 'Ucmak'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Zurafa', forbidden: ['Boyun', 'Uzun', 'Afrika', 'Benekler', 'Yuksek'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Yunus', forbidden: ['Deniz', 'Yuzmek', 'Akilli', 'Ziplamak', 'Flipper'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Bukalemun', forbidden: ['Renk', 'Degistirmek', 'Kertenkele', 'Dil', 'Kamufraj'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Timsah', forbidden: ['Dis', 'Su', 'Tehlikeli', 'Surunegen', 'Nehir'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Kelebek', forbidden: ['Kanat', 'Renkli', 'Tirtil', 'Ucmak', 'Cicek'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Tembel hayvan', forbidden: ['Yavas', 'Agac', 'Asilmak', 'Uyumak', 'Tembel'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Kopekbaligi', forbidden: ['Deniz', 'Dis', 'Tehlikeli', 'Balik', 'Yuzgec'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Sinek kus', forbidden: ['Kucuk', 'Kus', 'Ucmak', 'Cicek', 'Hizli'], category: 'Hayvanlar', difficulty: 'medium' },
  { term: 'Papagan', forbidden: ['Kus', 'Konusmak', 'Renkli', 'Tuy', 'Korsan'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Kutup ayisi', forbidden: ['Beyaz', 'Kutup', 'Soguk', 'Buz', 'Ayi'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Flamingo', forbidden: ['Pembe', 'Kus', 'Bacak', 'Durmak', 'Gol'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Kanguru', forbidden: ['Avustralya', 'Ziplamak', 'Kese', 'Yavru', 'Sicramak'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Tavuskusu', forbidden: ['Tuyler', 'Yelpaze', 'Renkli', 'Kus', 'Erkek'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Karinca', forbidden: ['Kucuk', 'Bocek', 'Yuva', 'Guclu', 'Koloni'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Suaygiri', forbidden: ['Su', 'Afrika', 'Buyuk', 'Agiz', 'Nehir'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Baykus', forbidden: ['Gece', 'Kus', 'Gozler', 'Otmek', 'Bilge'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Panda', forbidden: ['Cin', 'Bambu', 'Siyah beyaz', 'Ayi', 'Sevimli'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Kaplumbaga', forbidden: ['Kabuk', 'Yavas', 'Yasli', 'Zirh', 'Surunegen'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Kurt', forbidden: ['Ulumak', 'Suru', 'Orman', 'Kopek', 'Masal'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Ahtapot', forbidden: ['Kollar', 'Sekiz', 'Deniz', 'Murekkep', 'Dokunaç'], category: 'Hayvanlar', difficulty: 'medium' },
  { term: 'Denizati', forbidden: ['Deniz', 'Kucuk', 'At', 'Yuzmek', 'Su'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Goril', forbidden: ['Maymun', 'Buyuk', 'Guclu', 'Orman', 'Gumus sirt'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Ari', forbidden: ['Bal', 'Sokmak', 'Cicek', 'Ucmak', 'Kralice'], category: 'Hayvanlar', difficulty: 'easy' },

  // === Teknoloji (20) ===
  { term: 'Akilli telefon', forbidden: ['Telefon', 'Cep', 'Apple', 'Uygulama', 'Ekran'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Internet', forbidden: ['Çevrimiçi', 'Ag', 'Girmek', 'Site', 'Baglanti'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Bilgisayar', forbidden: ['Makine', 'Ekran', 'Klavye', 'Fare', 'PC'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Robot', forbidden: ['Makine', 'Yapay', 'Metal', 'Otomatik', 'Teknoloji'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Yapay zeka', forbidden: ['Bilgisayar', 'Robot', 'Ogrenmek', 'Makine', 'Algoritma'], category: 'Teknoloji', difficulty: 'medium' },
  { term: 'Drone', forbidden: ['Ucmak', 'Kamera', 'Uzaktan kumanda', 'Pervane', 'Hava'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'WiFi', forbidden: ['Internet', 'Kablosuz', 'Baglanti', 'Modem', 'Ag'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Selfie', forbidden: ['Fotograf', 'Kamera', 'Telefon', 'Kendin', 'Resim'], category: 'Teknoloji', difficulty: 'easy' },
  { term: '3D Yazici', forbidden: ['Yazdirmak', 'Uc boyutlu', 'Plastik', 'Katman', 'Model'], category: 'Teknoloji', difficulty: 'medium' },
  { term: 'Sanal gerceklik', forbidden: ['Gozluk', 'Sanal', 'Dunya', 'Bilgisayar', 'Simulasyon'], category: 'Teknoloji', difficulty: 'medium' },
  { term: 'Bluetooth', forbidden: ['Kablosuz', 'Baglanti', 'Telefon', 'Kulaklik', 'Radyo'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Streaming', forbidden: ['Film', 'Muzik', 'Netflix', 'Internet', 'Video'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'GPS', forbidden: ['Navigasyon', 'Konum', 'Uydu', 'Harita', 'Pozisyon'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Elektrikli araba', forbidden: ['Elektrik', 'Tesla', 'Batarya', 'Surmek', 'Sarj'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Sosyal medya', forbidden: ['Facebook', 'Instagram', 'Ag', 'Paylasmak', 'Takipci'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Podcast', forbidden: ['Ses', 'Dinlemek', 'Program', 'Spotify', 'Bolum'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Alexa', forbidden: ['Amazon', 'Ses asistani', 'Konusmak', 'Akilli', 'Hoparlor'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Tablet', forbidden: ['iPad', 'Ekran', 'Dokunmatik', 'Bilgisayar', 'Tasinabilir'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Algoritma', forbidden: ['Hesaplama', 'Bilgisayar', 'Adim', 'Program', 'Mantik'], category: 'Teknoloji', difficulty: 'hard' },
  { term: 'Blockchain', forbidden: ['Bitcoin', 'Kripto', 'Merkezi olmayan', 'Zincir', 'Veri'], category: 'Teknoloji', difficulty: 'hard' },

  // === Unluler (15) ===
  { term: 'Albert Einstein', forbidden: ['Gorelilik', 'Fizik', 'Dahi', 'E=mc2', 'Sac'], category: 'Unluler', difficulty: 'easy' },
  { term: 'Mozart', forbidden: ['Muzik', 'Besteci', 'Salzburg', 'Piyano', 'Klasik'], category: 'Unluler', difficulty: 'easy' },
  { term: 'Ataturk', forbidden: ['Turkiye', 'Cumhuriyet', 'Lider', 'Kurtuluş', 'Ankara'], category: 'Unluler', difficulty: 'easy' },
  { term: 'Beethoven', forbidden: ['Muzik', 'Besteci', 'Sagir', 'Senfoni', 'Piyano'], category: 'Unluler', difficulty: 'easy' },
  { term: 'Leonardo da Vinci', forbidden: ['Mona Lisa', 'Ressam', 'Mucit', 'Ronesans', 'Italya'], category: 'Unluler', difficulty: 'easy' },
  { term: 'Cristiano Ronaldo', forbidden: ['Futbol', 'Portekiz', 'Gol', 'Real Madrid', 'Forvet'], category: 'Unluler', difficulty: 'easy' },
  { term: 'Tarkan', forbidden: ['Sarki', 'Pop', 'Megastar', 'Turkiye', 'Simarik'], category: 'Unluler', difficulty: 'easy' },
  { term: 'Elon Musk', forbidden: ['Tesla', 'SpaceX', 'Milyarder', 'Twitter', 'Girisimci'], category: 'Unluler', difficulty: 'easy' },
  { term: 'Orhan Pamuk', forbidden: ['Yazar', 'Nobel', 'Istanbul', 'Roman', 'Edebiyat'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Kleopatra', forbidden: ['Misir', 'Kralice', 'Firavun', 'Nil', 'Sezar'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Napolyon', forbidden: ['Fransa', 'Imparator', 'Savas', 'Kisa', 'Waterloo'], category: 'Unluler', difficulty: 'easy' },
  { term: 'Marie Curie', forbidden: ['Radyoaktivite', 'Fizik', 'Nobel', 'Bilim', 'Arastirma'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Michael Jackson', forbidden: ['Sarkici', 'Thriller', 'Dans', 'Pop', 'Kral'], category: 'Unluler', difficulty: 'easy' },
  { term: 'Lionel Messi', forbidden: ['Futbol', 'Arjantin', 'Barcelona', 'Gol', 'Dunya Kupasi'], category: 'Unluler', difficulty: 'easy' },
  { term: 'Mevlana', forbidden: ['Sema', 'Konya', 'Sufi', 'Sair', 'Donmek'], category: 'Unluler', difficulty: 'easy' },

  // === Gunluk yasam + Seyahat + Kultur + Bilim + Ekstra (condensed) ===
  { term: 'Calar saat', forbidden: ['Sabah', 'Kalkmak', 'Saat', 'Calmak', 'Alarm'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Dis fircasi', forbidden: ['Disler', 'Fircalamak', 'Agiz', 'Macun', 'Banyo'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Anahtar', forbidden: ['Kapi', 'Acmak', 'Kilit', 'Ev', 'Kilitlemek'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Semsiye', forbidden: ['Yagmur', 'Islak', 'Hava', 'Korumak', 'Kuru'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Gozluk', forbidden: ['Gozler', 'Gormek', 'Cam', 'Optik', 'Burun'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Buzdolabi', forbidden: ['Soguk', 'Yiyecek', 'Mutfak', 'Saklamak', 'Kapi'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Elektrik supurgesi', forbidden: ['Emmek', 'Kir', 'Hali', 'Temizlemek', 'Zemin'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Camasir makinesi', forbidden: ['Giysi', 'Yikamak', 'Su', 'Sikma', 'Camasir'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Trafik lambasi', forbidden: ['Kirmizi', 'Yesil', 'Sari', 'Yol', 'Trafik'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Asansor', forbidden: ['Yukarı', 'Asagi', 'Kat', 'Dugme', 'Bina'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Yorgan', forbidden: ['Yatak', 'Uyumak', 'Sicak', 'Yastik', 'Ortunmek'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Kumanda', forbidden: ['Televizyon', 'Dugme', 'Degistirmek', 'Kanal', 'Koltuk'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Cuzdan', forbidden: ['Para', 'Bozuk', 'Kart', 'Cep', 'Odemek'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Otopark', forbidden: ['Araba', 'Park', 'Durmak', 'Yer', 'Aramak'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Su sisesi', forbidden: ['Su', 'Icmek', 'Sise', 'Kapak', 'Tasimak'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Dogum gunu', forbidden: ['Kutlamak', 'Pasta', 'Hediye', 'Mum', 'Parti'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Market', forbidden: ['Alisveris', 'Kasa', 'Raf', 'Magaza', 'Gida'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Kuafor', forbidden: ['Sac', 'Kesmek', 'Makas', 'Salon', 'Model'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Kutuphane', forbidden: ['Kitap', 'Okumak', 'Odunc', 'Sessiz', 'Raf'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Trafik', forbidden: ['Araba', 'Yol', 'Beklemek', 'Sikisiklik', 'Otoyol'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Spor salonu', forbidden: ['Spor', 'Antreman', 'Kas', 'Alet', 'Agirlik'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Gunes kremi', forbidden: ['Gunes', 'Cilt', 'Koruma', 'Plaj', 'Surmek'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Lunapark treni', forbidden: ['Park', 'Hizli', 'Ray', 'Viraj', 'Adrenalin'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Donme dolap', forbidden: ['Lunapark', 'Donmek', 'Yuksek', 'Kabin', 'Manzara'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Kardan adam', forbidden: ['Kar', 'Kis', 'Havuc', 'Burun', 'Soguk'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Kamp atesi', forbidden: ['Ates', 'Odun', 'Gece', 'Sicak', 'Marshmallow'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Sabun kopugu', forbidden: ['Sabun', 'Kopuk', 'Uflemek', 'Yuvarlak', 'Patlamak'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'El feneri', forbidden: ['Isik', 'Pil', 'Karanlik', 'Aydinlatmak', 'Lamba'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Balon', forbidden: ['Hava', 'Sişirmek', 'Parti', 'Renkli', 'Patlamak'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Kum kalesi', forbidden: ['Kum', 'Plaj', 'Yapmak', 'Deniz', 'Kova'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Puzzle', forbidden: ['Parca', 'Birleştirmek', 'Resim', 'Bulmaca', 'Sabir'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Agac ev', forbidden: ['Agac', 'Cocuklar', 'Tahta', 'Yukari', 'Ev'], category: 'Gunluk yasam', difficulty: 'easy' },
  // Seyahat + Kultur + Bilim + Ekstra
  { term: 'Bavul', forbidden: ['Seyahat', 'Hazirlamak', 'Giysi', 'Havalimani', 'Tatil'], category: 'Seyahat', difficulty: 'easy' },
  { term: 'Pasaport', forbidden: ['Sinir', 'Belge', 'Fotograf', 'Havalimani', 'Vize'], category: 'Seyahat', difficulty: 'easy' },
  { term: 'Otel', forbidden: ['Oda', 'Gecelemek', 'Yatak', 'Resepsiyon', 'Tatil'], category: 'Seyahat', difficulty: 'easy' },
  { term: 'Havalimani', forbidden: ['Ucak', 'Ucmak', 'Kapi', 'Binis', 'Terminal'], category: 'Seyahat', difficulty: 'easy' },
  { term: 'Kruvaziyer', forbidden: ['Gemi', 'Deniz', 'Yolculuk', 'Kabin', 'Tatil'], category: 'Seyahat', difficulty: 'easy' },
  { term: 'Opera', forbidden: ['Sarkı', 'Sahne', 'Muzik', 'Tiyatro', 'Orkestra'], category: 'Kultur', difficulty: 'easy' },
  { term: 'Muze', forbidden: ['Sanat', 'Sergi', 'Tablo', 'Ziyaretci', 'Galeri'], category: 'Kultur', difficulty: 'easy' },
  { term: 'Dugun', forbidden: ['Gelin', 'Damat', 'Yuzuk', 'Cami', 'Evlenmek'], category: 'Kultur', difficulty: 'easy' },
  { term: 'Sinema', forbidden: ['Film', 'Patlamis misir', 'Perde', 'Salon', 'Bilet'], category: 'Kultur', difficulty: 'easy' },
  { term: 'Ayasofya', forbidden: ['Istanbul', 'Cami', 'Bizans', 'Muze', 'Kubbe'], category: 'Kultur', difficulty: 'easy' },
  { term: 'Yercekim', forbidden: ['Dunya', 'Dusmek', 'Newton', 'Fizik', 'Cekmek'], category: 'Bilim', difficulty: 'medium' },
  { term: 'Yanardağ', forbidden: ['Lav', 'Patlama', 'Dag', 'Sicak', 'Ates'], category: 'Bilim', difficulty: 'easy' },
  { term: 'Gokkusagi', forbidden: ['Renkler', 'Yagmur', 'Gunes', 'Yay', 'Gokyuzu'], category: 'Bilim', difficulty: 'easy' },
  { term: 'Dinozor', forbidden: ['Nesli tukenmiş', 'Buyuk', 'Surunegen', 'Fosil', 'T-Rex'], category: 'Bilim', difficulty: 'easy' },
  { term: 'Astronot', forbidden: ['Uzay', 'Roket', 'Ay', 'NASA', 'Suzmek'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Restoran', forbidden: ['Yemek', 'Garson', 'Menu', 'Asci', 'Masa'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Hastane', forbidden: ['Doktor', 'Hasta', 'Ameliyat', 'Yatak', 'Hastanesi'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Televizyon', forbidden: ['Ekran', 'Izlemek', 'Program', 'Kanal', 'Film'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Disci', forbidden: ['Dis', 'Matkap', 'Agri', 'Muayenehane', 'Doktor'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Firinci', forbidden: ['Ekmek', 'Simit', 'Pismek', 'Firin', 'Un'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Beyzbol', forbidden: ['sopa', 'top', 'Amerika', 'eldiven', 'koşmak'], category: 'Spor', difficulty: 'medium' },
  { term: 'Bisiklet', forbidden: ['pedal', 'tekerlek', 'sürmek', 'zincir', 'sele'], category: 'Spor', difficulty: 'easy' },
  { term: 'Güreş', forbidden: ['minder', 'yağ', 'Kırkpınar', 'pehlivan', 'tutmak'], category: 'Spor', difficulty: 'medium' },
  { term: 'Halter', forbidden: ['ağırlık', 'kaldırmak', 'kas', 'demir', 'sporcu'], category: 'Spor', difficulty: 'medium' },
  { term: 'Okçuluk', forbidden: ['ok', 'yay', 'hedef', 'nişan', 'atmak'], category: 'Spor', difficulty: 'medium' },
  { term: 'Kano', forbidden: ['kürek', 'nehir', 'su', 'tekne', 'çekmek'], category: 'Spor', difficulty: 'hard' },
  { term: 'Badminton', forbidden: ['raket', 'file', 'tüy', 'top', 'vurmak'], category: 'Spor', difficulty: 'medium' },
  { term: 'Cimnastik', forbidden: ['esneklik', 'takla', 'minder', 'denge', 'jimnastikçi'], category: 'Spor', difficulty: 'medium' },
  { term: 'Bilardo', forbidden: ['masa', 'ıstaka', 'top', 'delik', 'yeşil'], category: 'Spor', difficulty: 'easy' },
  { term: 'Paten', forbidden: ['buz', 'kaymak', 'ayakkabı', 'tekerlek', 'düşmek'], category: 'Spor', difficulty: 'easy' },
  { term: 'Bowling', forbidden: ['lobut', 'top', 'devirmek', 'pist', 'strike'], category: 'Spor', difficulty: 'easy' },
  { term: 'Kürek', forbidden: ['tekne', 'su', 'çekmek', 'sporcu', 'nehir'], category: 'Spor', difficulty: 'hard' },
  { term: 'Triatlon', forbidden: ['yüzme', 'koşu', 'bisiklet', 'üç', 'yarış'], category: 'Spor', difficulty: 'hard' },
  { term: 'Hakem', forbidden: ['düdük', 'kart', 'karar', 'maç', 'faul'], category: 'Spor', difficulty: 'easy' },
  { term: 'Antrenör', forbidden: ['takım', 'çalıştırmak', 'sporcu', 'taktik', 'saha'], category: 'Spor', difficulty: 'easy' },
  { term: 'Çorba', forbidden: ['kaşık', 'sıcak', 'mercimek', 'içmek', 'kase'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Dolma', forbidden: ['biber', 'pirinç', 'yaprak', 'sarmak', 'içi'], category: 'Yemek', difficulty: 'medium' },
  { term: 'Köfte', forbidden: ['kıyma', 'et', 'yuvarlak', 'ızgara', 'pişirmek'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Menemen', forbidden: ['yumurta', 'domates', 'biber', 'kahvaltı', 'tava'], category: 'Yemek', difficulty: 'medium' },
  { term: 'Künefe', forbidden: ['peynir', 'kadayıf', 'şerbet', 'tatlı', 'sıcak'], category: 'Yemek', difficulty: 'medium' },
  { term: 'Lokum', forbidden: ['şeker', 'pudra', 'Türk', 'tatlı', 'yumuşak'], category: 'Yemek', difficulty: 'medium' },
  { term: 'Ayran', forbidden: ['yoğurt', 'su', 'tuz', 'içmek', 'beyaz'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Çay', forbidden: ['bardak', 'sıcak', 'demlemek', 'içmek', 'kırmızı'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Kahve', forbidden: ['fincan', 'Türk', 'içmek', 'fal', 'kafein'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Peynir', forbidden: ['beyaz', 'süt', 'kahvaltı', 'ekmek', 'tuzlu'], category: 'Yemek', difficulty: 'easy' },
  { term: 'Zeytin', forbidden: ['ağaç', 'yağ', 'siyah', 'kahvaltı', 'çekirdek'], category: 'Yemek', difficulty: 'medium' },
  { term: 'Gözleme', forbidden: ['hamur', 'açmak', 'sac', 'peynir', 'ince'], category: 'Yemek', difficulty: 'medium' },
  { term: 'Sucuk', forbidden: ['et', 'baharat', 'kahvaltı', 'yumurta', 'kırmızı'], category: 'Yemek', difficulty: 'medium' },
  { term: 'Turşu', forbidden: ['sirke', 'salatalık', 'ekşi', 'kavanoz', 'tuz'], category: 'Yemek', difficulty: 'hard' },
  { term: 'Helva', forbidden: ['tahin', 'irmik', 'tatlı', 'şeker', 'kavurmak'], category: 'Yemek', difficulty: 'hard' },
  { term: 'Aslan', forbidden: ['yele', 'kral', 'kükremek', 'Afrika', 'vahşi'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Kaplan', forbidden: ['çizgi', 'turuncu', 'vahşi', 'kedi', 'Asya'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Maymun', forbidden: ['muz', 'ağaç', 'taklit', 'kuyruk', 'tırmanmak'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Tavşan', forbidden: ['havuç', 'kulak', 'zıplamak', 'yumuşak', 'tüy'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'At', forbidden: ['binmek', 'koşmak', 'nal', 'yele', 'ahır'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'İnek', forbidden: ['süt', 'çiftlik', 'boynuz', 'mö', 'ot'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Yılan', forbidden: ['sürünmek', 'zehir', 'uzun', 'dil', 'sokmak'], category: 'Hayvanlar', difficulty: 'easy' },
  { term: 'Kartal', forbidden: ['kuş', 'gaga', 'pençe', 'uçmak', 'avlamak'], category: 'Hayvanlar', difficulty: 'medium' },
  { term: 'Balina', forbidden: ['okyanus', 'dev', 'memeli', 'su', 'fışkırtmak'], category: 'Hayvanlar', difficulty: 'medium' },
  { term: 'Zebra', forbidden: ['çizgi', 'siyah', 'beyaz', 'Afrika', 'at'], category: 'Hayvanlar', difficulty: 'medium' },
  { term: 'Köstebek', forbidden: ['toprak', 'kazmak', 'yeraltı', 'kör', 'tünel'], category: 'Hayvanlar', difficulty: 'hard' },
  { term: 'Yarasa', forbidden: ['gece', 'uçmak', 'mağara', 'kanat', 'ters'], category: 'Hayvanlar', difficulty: 'medium' },
  { term: 'Geyik', forbidden: ['boynuz', 'orman', 'koşmak', 'ot', 'ürkek'], category: 'Hayvanlar', difficulty: 'medium' },
  { term: 'Sincap', forbidden: ['fındık', 'kuyruk', 'ağaç', 'toplamak', 'kabarık'], category: 'Hayvanlar', difficulty: 'medium' },
  { term: 'Su samuru', forbidden: ['nehir', 'yüzmek', 'balık', 'tüy', 'kürk'], category: 'Hayvanlar', difficulty: 'hard' },
  { term: 'Klavye', forbidden: ['tuş', 'yazmak', 'bilgisayar', 'harf', 'parmak'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Fare', forbidden: ['tıklamak', 'imleç', 'bilgisayar', 'kaydırmak', 'el'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Ekran', forbidden: ['görüntü', 'monitör', 'piksel', 'parlak', 'göstermek'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Kulaklık', forbidden: ['müzik', 'kulak', 'ses', 'dinlemek', 'kablo'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Kamera', forbidden: ['fotoğraf', 'çekmek', 'lens', 'görüntü', 'objektif'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Şarj aleti', forbidden: ['pil', 'kablo', 'priz', 'telefon', 'doldurmak'], category: 'Teknoloji', difficulty: 'easy' },
  { term: 'Uygulama', forbidden: ['telefon', 'indirmek', 'ekran', 'açmak', 'program'], category: 'Teknoloji', difficulty: 'medium' },
  { term: 'E-posta', forbidden: ['mektup', 'göndermek', 'adres', 'gelen', 'kutu'], category: 'Teknoloji', difficulty: 'medium' },
  { term: 'Şifre', forbidden: ['giriş', 'gizli', 'hesap', 'güvenlik', 'unutmak'], category: 'Teknoloji', difficulty: 'medium' },
  { term: 'Yazılım', forbidden: ['program', 'kod', 'bilgisayar', 'geliştirmek', 'sistem'], category: 'Teknoloji', difficulty: 'medium' },
  { term: 'Bulut', forbidden: ['depolama', 'internet', 'veri', 'yedek', 'sunucu'], category: 'Teknoloji', difficulty: 'hard' },
  { term: 'QR kod', forbidden: ['kare', 'taramak', 'telefon', 'siyah', 'menü'], category: 'Teknoloji', difficulty: 'medium' },
  { term: 'Hoparlör', forbidden: ['ses', 'müzik', 'yüksek', 'çalmak', 'kutu'], category: 'Teknoloji', difficulty: 'medium' },
  { term: 'Sunucu', forbidden: ['veri', 'internet', 'barındırmak', 'sistem', 'bilgisayar'], category: 'Teknoloji', difficulty: 'hard' },
  { term: 'Sensör', forbidden: ['algılamak', 'hareket', 'ölçmek', 'cihaz', 'ışık'], category: 'Teknoloji', difficulty: 'hard' },
  { term: 'William Shakespeare', forbidden: ['oyun', 'tiyatro', 'İngiliz', 'yazar', 'Hamlet'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Pablo Picasso', forbidden: ['ressam', 'resim', 'İspanya', 'kübizm', 'tablo'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Charlie Chaplin', forbidden: ['sessiz', 'film', 'bıyık', 'komedi', 'şapka'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Steve Jobs', forbidden: ['Apple', 'iPhone', 'kurucu', 'teknoloji', 'siyah'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Galileo', forbidden: ['teleskop', 'gezegen', 'gökyüzü', 'bilim', 'İtalyan'], category: 'Unluler', difficulty: 'hard' },
  { term: 'Walt Disney', forbidden: ['çizgi film', 'Mickey', 'stüdyo', 'fare', 'park'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Nikola Tesla', forbidden: ['elektrik', 'mucit', 'akım', 'bilim', 'icat'], category: 'Unluler', difficulty: 'hard' },
  { term: 'Barış Manço', forbidden: ['müzik', 'sanatçı', 'bıyık', 'şarkı', 'Türk'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Fatih Sultan Mehmet', forbidden: ['İstanbul', 'fetih', 'padişah', 'Osmanlı', 'Bizans'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Mimar Sinan', forbidden: ['cami', 'mimar', 'Süleymaniye', 'Osmanlı', 'yapı'], category: 'Unluler', difficulty: 'hard' },
  { term: 'Nasreddin Hoca', forbidden: ['fıkra', 'eşek', 'göl', 'mizah', 'Akşehir'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Yunus Emre', forbidden: ['şiir', 'tasavvuf', 'sevgi', 'ozan', 'gönül'], category: 'Unluler', difficulty: 'hard' },
  { term: 'Sezen Aksu', forbidden: ['şarkı', 'müzik', 'Minik Serçe', 'beste', 'Türk'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Usain Bolt', forbidden: ['koşu', 'hız', 'Jamaika', 'altın', 'sprinter'], category: 'Unluler', difficulty: 'medium' },
  { term: 'Frida Kahlo', forbidden: ['ressam', 'Meksika', 'kaş', 'otoportre', 'tablo'], category: 'Unluler', difficulty: 'hard' },
  { term: 'Yastık', forbidden: ['uyumak', 'yatak', 'baş', 'yumuşak', 'tüy'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Havlu', forbidden: ['kurulamak', 'banyo', 'ıslak', 'el', 'kumaş'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Tarak', forbidden: ['saç', 'taramak', 'diş', 'düzeltmek', 'el'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Ayna', forbidden: ['yansıma', 'bakmak', 'yüz', 'cam', 'görmek'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Çatal', forbidden: ['yemek', 'metal', 'sivri', 'tabak', 'batırmak'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Sandalye', forbidden: ['oturmak', 'masa', 'bacak', 'ahşap', 'arkalık'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Çorap', forbidden: ['ayak', 'giymek', 'ayakkabı', 'yün', 'çift'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Saç kurutma makinesi', forbidden: ['saç', 'sıcak', 'hava', 'üflemek', 'banyo'], category: 'Gunluk yasam', difficulty: 'medium' },
  { term: 'Ütü', forbidden: ['kıyafet', 'sıcak', 'kırışık', 'düzeltmek', 'buhar'], category: 'Gunluk yasam', difficulty: 'medium' },
  { term: 'Kapı', forbidden: ['açmak', 'kapatmak', 'kol', 'ev', 'girmek'], category: 'Gunluk yasam', difficulty: 'easy' },
  { term: 'Perde', forbidden: ['pencere', 'ışık', 'asmak', 'kumaş', 'kapatmak'], category: 'Gunluk yasam', difficulty: 'medium' },
  { term: 'Makas', forbidden: ['kesmek', 'kağıt', 'keskin', 'el', 'iki'], category: 'Gunluk yasam', difficulty: 'medium' },
  { term: 'Fatura', forbidden: ['ödemek', 'para', 'elektrik', 'ay', 'borç'], category: 'Gunluk yasam', difficulty: 'medium' },
  { term: 'Bulaşık makinesi', forbidden: ['tabak', 'yıkamak', 'mutfak', 'su', 'temiz'], category: 'Gunluk yasam', difficulty: 'medium' },
  { term: 'Priz', forbidden: ['elektrik', 'fiş', 'duvar', 'takmak', 'akım'], category: 'Gunluk yasam', difficulty: 'hard' },
  { term: 'Tren', forbidden: ['ray', 'istasyon', 'vagon', 'gar', 'yolculuk'], category: 'Seyahat', difficulty: 'easy' },
  { term: 'Uçak', forbidden: ['uçmak', 'kanat', 'pilot', 'gökyüzü', 'havalimanı'], category: 'Seyahat', difficulty: 'easy' },
  { term: 'Otobüs', forbidden: ['durak', 'şoför', 'yolcu', 'bilet', 'koltuk'], category: 'Seyahat', difficulty: 'easy' },
  { term: 'Harita', forbidden: ['yol', 'yön', 'bulmak', 'şehir', 'çizgi'], category: 'Seyahat', difficulty: 'easy' },
  { term: 'Çadır', forbidden: ['kamp', 'kurmak', 'uyumak', 'doğa', 'direk'], category: 'Seyahat', difficulty: 'easy' },
  { term: 'Plaj', forbidden: ['kum', 'deniz', 'güneş', 'şezlong', 'tatil'], category: 'Seyahat', difficulty: 'easy' },
  { term: 'Dağ', forbidden: ['yüksek', 'tırmanmak', 'zirve', 'kar', 'doğa'], category: 'Seyahat', difficulty: 'easy' },
  { term: 'Feribot', forbidden: ['deniz', 'araba', 'geçmek', 'iskele', 'gemi'], category: 'Seyahat', difficulty: 'medium' },
  { term: 'Vize', forbidden: ['pasaport', 'ülke', 'başvuru', 'damga', 'izin'], category: 'Seyahat', difficulty: 'medium' },
  { term: 'Rehber', forbidden: ['tur', 'anlatmak', 'gezi', 'turist', 'yol'], category: 'Seyahat', difficulty: 'medium' },
  { term: 'Pusula', forbidden: ['yön', 'kuzey', 'iğne', 'bulmak', 'dönmek'], category: 'Seyahat', difficulty: 'hard' },
  { term: 'Sırt çantası', forbidden: ['taşımak', 'omuz', 'gezi', 'eşya', 'sırt'], category: 'Seyahat', difficulty: 'medium' },
  { term: 'Tatil köyü', forbidden: ['deniz', 'havuz', 'her şey dahil', 'konaklama', 'eğlence'], category: 'Seyahat', difficulty: 'medium' },
  { term: 'Sınır', forbidden: ['ülke', 'geçmek', 'pasaport', 'kapı', 'ayırmak'], category: 'Seyahat', difficulty: 'hard' },
  { term: 'Yat', forbidden: ['deniz', 'lüks', 'tekne', 'yelken', 'zengin'], category: 'Seyahat', difficulty: 'hard' },
  { term: 'Tiyatro', forbidden: ['sahne', 'oyuncu', 'perde', 'oyun', 'seyirci'], category: 'Kultur', difficulty: 'easy' },
  { term: 'Kitap', forbidden: ['okumak', 'sayfa', 'yazar', 'kapak', 'roman'], category: 'Kultur', difficulty: 'easy' },
  { term: 'Resim', forbidden: ['ressam', 'tablo', 'fırça', 'boya', 'çizmek'], category: 'Kultur', difficulty: 'easy' },
  { term: 'Dans', forbidden: ['müzik', 'hareket', 'ritim', 'oynamak', 'ayak'], category: 'Kultur', difficulty: 'easy' },
  { term: 'Konser', forbidden: ['müzik', 'sahne', 'sanatçı', 'dinlemek', 'kalabalık'], category: 'Kultur', difficulty: 'easy' },
  { term: 'Bale', forbidden: ['dans', 'parmak', 'ucu', 'zarif', 'sahne'], category: 'Kultur', difficulty: 'medium' },
  { term: 'Heykel', forbidden: ['taş', 'yontmak', 'sanat', 'figür', 'mermer'], category: 'Kultur', difficulty: 'medium' },
  { term: 'Gitar', forbidden: ['tel', 'çalmak', 'akor', 'müzik', 'pena'], category: 'Kultur', difficulty: 'easy' },
  { term: 'Piyano', forbidden: ['tuş', 'çalmak', 'siyah', 'beyaz', 'müzik'], category: 'Kultur', difficulty: 'easy' },
  { term: 'Şiir', forbidden: ['kafiye', 'dize', 'şair', 'yazmak', 'duygu'], category: 'Kultur', difficulty: 'medium' },
  { term: 'Karagöz', forbidden: ['gölge', 'perde', 'oyun', 'kukla', 'Hacivat'], category: 'Kultur', difficulty: 'hard' },
  { term: 'Halk oyunu', forbidden: ['folklor', 'yöre', 'dans', 'kostüm', 'ekip'], category: 'Kultur', difficulty: 'hard' },
  { term: 'Festival', forbidden: ['eğlence', 'kalabalık', 'kutlama', 'etkinlik', 'müzik'], category: 'Kultur', difficulty: 'medium' },
  { term: 'Çini', forbidden: ['mavi', 'desen', 'seramik', 'İznik', 'el'], category: 'Kultur', difficulty: 'hard' },
  { term: 'Ney', forbidden: ['üflemek', 'nefes', 'kamış', 'sema', 'ses'], category: 'Kultur', difficulty: 'hard' },
  { term: 'Mıknatıs', forbidden: ['çekmek', 'metal', 'kutup', 'demir', 'yapışmak'], category: 'Bilim', difficulty: 'easy' },
  { term: 'Atom', forbidden: ['küçük', 'çekirdek', 'parçacık', 'element', 'madde'], category: 'Bilim', difficulty: 'medium' },
  { term: 'Gezegen', forbidden: ['güneş', 'dönmek', 'uzay', 'yörünge', 'Dünya'], category: 'Bilim', difficulty: 'easy' },
  { term: 'Mikroskop', forbidden: ['büyütmek', 'küçük', 'görmek', 'lens', 'hücre'], category: 'Bilim', difficulty: 'medium' },
  { term: 'Teleskop', forbidden: ['yıldız', 'uzay', 'bakmak', 'gökyüzü', 'uzak'], category: 'Bilim', difficulty: 'medium' },
  { term: 'Elektrik', forbidden: ['akım', 'priz', 'enerji', 'kablo', 'ampul'], category: 'Bilim', difficulty: 'easy' },
  { term: 'Işık', forbidden: ['güneş', 'parlak', 'aydınlık', 'ampul', 'göz'], category: 'Bilim', difficulty: 'easy' },
  { term: 'Ses', forbidden: ['duymak', 'kulak', 'dalga', 'gürültü', 'titreşim'], category: 'Bilim', difficulty: 'easy' },
  { term: 'Hücre', forbidden: ['canlı', 'küçük', 'vücut', 'bölünmek', 'biyoloji'], category: 'Bilim', difficulty: 'medium' },
  { term: 'DNA', forbidden: ['gen', 'kalıtım', 'sarmal', 'kod', 'hücre'], category: 'Bilim', difficulty: 'hard' },
  { term: 'Termometre', forbidden: ['sıcaklık', 'ölçmek', 'ateş', 'derece', 'cıva'], category: 'Bilim', difficulty: 'medium' },
  { term: 'Buharlaşma', forbidden: ['su', 'gaz', 'ısı', 'kaynamak', 'sıvı'], category: 'Bilim', difficulty: 'hard' },
  { term: 'Yörünge', forbidden: ['dönmek', 'gezegen', 'uydu', 'güneş', 'dolanmak'], category: 'Bilim', difficulty: 'hard' },
  { term: 'Manyetik alan', forbidden: ['mıknatıs', 'kuvvet', 'kutup', 'pusula', 'çekim'], category: 'Bilim', difficulty: 'hard' },
  { term: 'Fosil', forbidden: ['taş', 'eski', 'kemik', 'dinozor', 'kalıntı'], category: 'Bilim', difficulty: 'medium' },
];
