export interface TabooCard {
  term: string;
  forbidden: string[];
  category: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const TABOO_CARDS_FR: TabooCard[] = [
  // === Sport (21) ===
  { term: 'Football', forbidden: ['Ballon', 'But', 'Joueur', 'Equipe', 'Stade'], category: 'Sport', difficulty: 'easy' },
  { term: 'Tennis', forbidden: ['Raquette', 'Balle', 'Filet', 'Service', 'Wimbledon'], category: 'Sport', difficulty: 'easy' },
  { term: 'Basketball', forbidden: ['Panier', 'Ballon', 'Lancer', 'NBA', 'Dunk'], category: 'Sport', difficulty: 'easy' },
  { term: 'Natation', forbidden: ['Eau', 'Piscine', 'Couloir', 'Nage', 'Maillot'], category: 'Sport', difficulty: 'easy' },
  { term: 'Boxe', forbidden: ['Combat', 'Ring', 'Gants', 'Coup', 'Round'], category: 'Sport', difficulty: 'easy' },
  { term: 'Ski', forbidden: ['Neige', 'Montagne', 'Piste', 'Hiver', 'Remontee'], category: 'Sport', difficulty: 'easy' },
  { term: 'Marathon', forbidden: ['Courir', 'Kilometres', 'Distance', 'Endurance', 'Arrivee'], category: 'Sport', difficulty: 'medium' },
  { term: 'Golf', forbidden: ['Balle', 'Club', 'Trou', 'Gazon', 'Handicap'], category: 'Sport', difficulty: 'easy' },
  { term: 'Jeux Olympiques', forbidden: ['Jeux', 'Anneaux', 'Medaille', 'Athletes', 'Competition'], category: 'Sport', difficulty: 'easy' },
  { term: 'Surf', forbidden: ['Vague', 'Planche', 'Mer', 'Plage', 'Eau'], category: 'Sport', difficulty: 'easy' },
  { term: 'Hockey sur glace', forbidden: ['Palet', 'Glace', 'Crosse', 'But', 'Patin'], category: 'Sport', difficulty: 'easy' },
  { term: 'Yoga', forbidden: ['Etirement', 'Meditation', 'Corps', 'Posture', 'Detente'], category: 'Sport', difficulty: 'medium' },
  { term: 'Formule 1', forbidden: ['Course', 'Voiture', 'Rapide', 'Pilote', 'Circuit'], category: 'Sport', difficulty: 'easy' },
  { term: 'Escalade', forbidden: ['Mur', 'Roche', 'Corde', 'Hauteur', 'Prises'], category: 'Sport', difficulty: 'easy' },
  { term: 'Handball', forbidden: ['Ballon', 'But', 'Lancer', 'Equipe', 'Terrain'], category: 'Sport', difficulty: 'easy' },
  { term: 'Biathlon', forbidden: ['Ski', 'Tir', 'Hiver', 'Fusil', 'Fond'], category: 'Sport', difficulty: 'hard' },
  { term: 'Flechettes', forbidden: ['Fleche', 'Cible', 'Lancer', 'Points', 'Centre'], category: 'Sport', difficulty: 'medium' },
  { term: 'Volleyball', forbidden: ['Filet', 'Ballon', 'Plage', 'Equipe', 'Smash'], category: 'Sport', difficulty: 'easy' },
  { term: 'Escrime', forbidden: ['Epee', 'Masque', 'Touche', 'Fleuret', 'Combat'], category: 'Sport', difficulty: 'medium' },
  { term: 'Tennis de table', forbidden: ['Balle', 'Raquette', 'Table', 'Ping', 'Pong'], category: 'Sport', difficulty: 'easy' },
  { term: 'Parachute', forbidden: ['Sauter', 'Voler', 'Avion', 'Ouvrir', 'Air'], category: 'Sport', difficulty: 'easy' },

  // === Cuisine (27) ===
  { term: 'Pizza', forbidden: ['Italie', 'Pate', 'Garniture', 'Fromage', 'Four'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Spaghetti', forbidden: ['Pates', 'Italie', 'Sauce', 'Cuire', 'Long'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Chocolat', forbidden: ['Sucre', 'Cacao', 'Marron', 'Tablette', 'Lait'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Hamburger', forbidden: ['Viande', 'Pain', 'Fast-food', 'McDonalds', 'Steak'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Glace', forbidden: ['Froid', 'Ete', 'Boule', 'Cornet', 'Sucre'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Sushi', forbidden: ['Japon', 'Riz', 'Poisson', 'Algue', 'Cru'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Baguette', forbidden: ['Boulangerie', 'Pain', 'France', 'Long', 'Croute'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Kebab', forbidden: ['Viande', 'Pain', 'Salade', 'Turquie', 'Sauce'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Gateau', forbidden: ['Patisserie', 'Sucre', 'Anniversaire', 'Creme', 'Four'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Frites', forbidden: ['Pomme de terre', 'Frire', 'Ketchup', 'Sale', 'Fast-food'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Salade', forbidden: ['Vert', 'Sain', 'Legumes', 'Vinaigrette', 'Frais'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Croissant', forbidden: ['France', 'Petit-dejeuner', 'Beurre', 'Pate', 'Boulangerie'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Croque-monsieur', forbidden: ['Pain', 'Fromage', 'Jambon', 'Grille', 'Chaud'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Crepe', forbidden: ['Poele', 'Pate', 'Farine', 'Garniture', 'Fine'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Ratatouille', forbidden: ['Legumes', 'Provence', 'Courgette', 'Film', 'Cuire'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Fondue', forbidden: ['Fromage', 'Fondre', 'Caquelon', 'Suisse', 'Tremper'], category: 'Cuisine', difficulty: 'medium' },
  { term: 'Bouillabaisse', forbidden: ['Poisson', 'Marseille', 'Soupe', 'Mer', 'Provence'], category: 'Cuisine', difficulty: 'medium' },
  { term: 'Tiramisu', forbidden: ['Italie', 'Cafe', 'Mascarpone', 'Dessert', 'Cacao'], category: 'Cuisine', difficulty: 'medium' },
  { term: 'Pot-au-feu', forbidden: ['Viande', 'Legumes', 'Bouillon', 'Cuire', 'Cocotte'], category: 'Cuisine', difficulty: 'medium' },
  { term: 'Muesli', forbidden: ['Petit-dejeuner', 'Avoine', 'Lait', 'Fruits', 'Sain'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Quiche Lorraine', forbidden: ['Oeufs', 'Lardons', 'Pate', 'Four', 'Lorraine'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Tacos', forbidden: ['Mexique', 'Mais', 'Viande', 'Salsa', 'Garniture'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Raclette', forbidden: ['Fromage', 'Fondre', 'Coupelle', 'Pomme de terre', 'Suisse'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Eclair', forbidden: ['Patisserie', 'Chocolat', 'Creme', 'Long', 'Paris'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Buche de Noel', forbidden: ['Noel', 'Gateau', 'Chocolat', 'Dessert', 'Fete'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Popcorn', forbidden: ['Mais', 'Cinema', 'Sale', 'Sucre', 'Film'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Vin chaud', forbidden: ['Noel', 'Chaud', 'Vin', 'Epices', 'Marche'], category: 'Cuisine', difficulty: 'easy' },

  // === Animaux (25) ===
  { term: 'Elephant', forbidden: ['Gros', 'Trompe', 'Afrique', 'Gris', 'Defense'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Pingouin', forbidden: ['Glace', 'Noir et blanc', 'Antarctique', 'Oiseau', 'Voler'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Girafe', forbidden: ['Cou', 'Long', 'Afrique', 'Taches', 'Grand'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Dauphin', forbidden: ['Mer', 'Nager', 'Intelligent', 'Sauter', 'Flipper'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Cameleon', forbidden: ['Couleur', 'Changer', 'Lezard', 'Langue', 'Camouflage'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Crocodile', forbidden: ['Dents', 'Eau', 'Dangereux', 'Reptile', 'Riviere'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Papillon', forbidden: ['Ailes', 'Colore', 'Chenille', 'Voler', 'Fleur'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Paresseux', forbidden: ['Lent', 'Arbre', 'Pendre', 'Dormir', 'Paresse'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Requin', forbidden: ['Mer', 'Dents', 'Dangereux', 'Poisson', 'Aileron'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Colibri', forbidden: ['Petit', 'Oiseau', 'Voler', 'Fleur', 'Rapide'], category: 'Animaux', difficulty: 'medium' },
  { term: 'Perroquet', forbidden: ['Oiseau', 'Parler', 'Colore', 'Plumes', 'Pirate'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Ours polaire', forbidden: ['Blanc', 'Arctique', 'Froid', 'Glace', 'Ours'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Flamant rose', forbidden: ['Rose', 'Oiseau', 'Patte', 'Debout', 'Lac'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Kangourou', forbidden: ['Australie', 'Sauter', 'Poche', 'Bebe', 'Bondir'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Paon', forbidden: ['Plumes', 'Roue', 'Colore', 'Oiseau', 'Male'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Fourmi', forbidden: ['Petite', 'Insecte', 'Fourmiliere', 'Forte', 'Colonie'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Hippopotame', forbidden: ['Eau', 'Afrique', 'Gros', 'Bouche', 'Riviere'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Hibou', forbidden: ['Nuit', 'Oiseau', 'Yeux', 'Hululer', 'Sage'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Panda', forbidden: ['Chine', 'Bambou', 'Noir et blanc', 'Ours', 'Mignon'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Tortue', forbidden: ['Carapace', 'Lent', 'Vieux', 'Coquille', 'Reptile'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Loup', forbidden: ['Hurler', 'Meute', 'Foret', 'Chien', 'Conte'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Poulpe', forbidden: ['Bras', 'Huit', 'Mer', 'Encre', 'Tentacule'], category: 'Animaux', difficulty: 'medium' },
  { term: 'Hippocampe', forbidden: ['Mer', 'Petit', 'Cheval', 'Nager', 'Eau'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Gorille', forbidden: ['Singe', 'Gros', 'Fort', 'Jungle', 'Dos argente'], category: 'Animaux', difficulty: 'easy' },
  { term: 'Abeille', forbidden: ['Miel', 'Piquer', 'Fleur', 'Voler', 'Reine'], category: 'Animaux', difficulty: 'easy' },

  // === Technologie (20) ===
  { term: 'Smartphone', forbidden: ['Telephone', 'Mobile', 'Apple', 'Applications', 'Ecran'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Internet', forbidden: ['En ligne', 'Toile', 'Naviguer', 'Site web', 'Connexion'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Ordinateur', forbidden: ['Machine', 'Ecran', 'Clavier', 'Souris', 'PC'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Robot', forbidden: ['Machine', 'Artificiel', 'Metal', 'Automatique', 'Technologie'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Intelligence artificielle', forbidden: ['Ordinateur', 'Robot', 'Apprendre', 'Machine', 'Algorithme'], category: 'Technologie', difficulty: 'medium' },
  { term: 'Drone', forbidden: ['Voler', 'Camera', 'Telecommande', 'Helice', 'Air'], category: 'Technologie', difficulty: 'easy' },
  { term: 'WiFi', forbidden: ['Internet', 'Sans fil', 'Connexion', 'Routeur', 'Reseau'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Selfie', forbidden: ['Photo', 'Camera', 'Telephone', 'Soi-meme', 'Image'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Imprimante 3D', forbidden: ['Imprimer', 'Tridimensionnel', 'Plastique', 'Couche', 'Modele'], category: 'Technologie', difficulty: 'medium' },
  { term: 'Realite virtuelle', forbidden: ['Casque', 'Virtuel', 'Monde', 'Ordinateur', 'Simulation'], category: 'Technologie', difficulty: 'medium' },
  { term: 'Bluetooth', forbidden: ['Sans fil', 'Connexion', 'Telephone', 'Ecouteurs', 'Radio'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Streaming', forbidden: ['Film', 'Musique', 'Netflix', 'Internet', 'Video'], category: 'Technologie', difficulty: 'easy' },
  { term: 'GPS', forbidden: ['Navigation', 'Position', 'Satellite', 'Carte', 'Localisation'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Voiture electrique', forbidden: ['Electricite', 'Tesla', 'Batterie', 'Conduire', 'Charger'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Reseaux sociaux', forbidden: ['Facebook', 'Instagram', 'Reseau', 'Partager', 'Abonne'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Podcast', forbidden: ['Audio', 'Ecouter', 'Emission', 'Spotify', 'Episode'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Alexa', forbidden: ['Amazon', 'Assistant vocal', 'Parler', 'Intelligent', 'Enceinte'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Tablette', forbidden: ['iPad', 'Ecran', 'Tactile', 'Ordinateur', 'Portable'], category: 'Technologie', difficulty: 'easy' },
  { term: 'Algorithme', forbidden: ['Calcul', 'Ordinateur', 'Etape', 'Programme', 'Logique'], category: 'Technologie', difficulty: 'hard' },
  { term: 'Blockchain', forbidden: ['Bitcoin', 'Crypto', 'Decentralise', 'Chaine', 'Donnees'], category: 'Technologie', difficulty: 'hard' },

  // === Celebrites (15) ===
  { term: 'Albert Einstein', forbidden: ['Relativite', 'Physique', 'Genie', 'E=mc2', 'Cheveux'], category: 'Celebrites', difficulty: 'easy' },
  { term: 'Mozart', forbidden: ['Musique', 'Compositeur', 'Salzbourg', 'Piano', 'Classique'], category: 'Celebrites', difficulty: 'easy' },
  { term: 'Napoleon', forbidden: ['France', 'Empereur', 'Guerre', 'Petit', 'Waterloo'], category: 'Celebrites', difficulty: 'easy' },
  { term: 'Beethoven', forbidden: ['Musique', 'Compositeur', 'Sourd', 'Symphonie', 'Piano'], category: 'Celebrites', difficulty: 'easy' },
  { term: 'Leonard de Vinci', forbidden: ['Joconde', 'Peintre', 'Inventeur', 'Renaissance', 'Italie'], category: 'Celebrites', difficulty: 'easy' },
  { term: 'Cristiano Ronaldo', forbidden: ['Football', 'Portugal', 'But', 'Real Madrid', 'Attaquant'], category: 'Celebrites', difficulty: 'easy' },
  { term: 'Edith Piaf', forbidden: ['Chanteuse', 'France', 'Vie en rose', 'Paris', 'Voix'], category: 'Celebrites', difficulty: 'easy' },
  { term: 'Elon Musk', forbidden: ['Tesla', 'SpaceX', 'Milliardaire', 'Twitter', 'Entrepreneur'], category: 'Celebrites', difficulty: 'easy' },
  { term: 'Victor Hugo', forbidden: ['Ecrivain', 'Miserables', 'France', 'Romancier', 'Notre-Dame'], category: 'Celebrites', difficulty: 'medium' },
  { term: 'Cleopatre', forbidden: ['Egypte', 'Reine', 'Pharaon', 'Nil', 'Cesar'], category: 'Celebrites', difficulty: 'medium' },
  { term: 'Marie Curie', forbidden: ['Radioactivite', 'Physique', 'Nobel', 'Science', 'Recherche'], category: 'Celebrites', difficulty: 'medium' },
  { term: 'Michael Jackson', forbidden: ['Chanteur', 'Thriller', 'Danse', 'Pop', 'Roi'], category: 'Celebrites', difficulty: 'easy' },
  { term: 'Lionel Messi', forbidden: ['Football', 'Argentine', 'Barcelone', 'But', 'Mondial'], category: 'Celebrites', difficulty: 'easy' },
  { term: 'Coco Chanel', forbidden: ['Mode', 'Parfum', 'Paris', 'Couturiere', 'N°5'], category: 'Celebrites', difficulty: 'easy' },
  { term: 'Louis XIV', forbidden: ['Roi', 'Soleil', 'Versailles', 'France', 'Monarchie'], category: 'Celebrites', difficulty: 'medium' },

  // === Vie quotidienne (32) ===
  { term: 'Reveil', forbidden: ['Matin', 'Se lever', 'Horloge', 'Sonner', 'Alarme'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Brosse a dents', forbidden: ['Dents', 'Brosser', 'Bouche', 'Dentifrice', 'Salle de bain'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Cle', forbidden: ['Porte', 'Ouvrir', 'Serrure', 'Maison', 'Fermer'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Parapluie', forbidden: ['Pluie', 'Mouille', 'Meteo', 'Proteger', 'Sec'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Lunettes', forbidden: ['Yeux', 'Voir', 'Verre', 'Opticien', 'Nez'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Refrigerateur', forbidden: ['Froid', 'Nourriture', 'Cuisine', 'Conserver', 'Porte'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Aspirateur', forbidden: ['Aspirer', 'Poussiere', 'Tapis', 'Nettoyer', 'Sol'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Machine a laver', forbidden: ['Vetements', 'Laver', 'Eau', 'Essorer', 'Linge'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Feu de circulation', forbidden: ['Rouge', 'Vert', 'Orange', 'Rue', 'Circulation'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Ascenseur', forbidden: ['Monter', 'Descendre', 'Etage', 'Boutons', 'Immeuble'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Couverture', forbidden: ['Lit', 'Dormir', 'Chaud', 'Oreiller', 'Couvrir'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Telecommande', forbidden: ['Television', 'Boutons', 'Changer', 'Chaine', 'Canape'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Portefeuille', forbidden: ['Argent', 'Pieces', 'Cartes', 'Poche', 'Payer'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Parking', forbidden: ['Voiture', 'Garer', 'Place', 'Stationner', 'Chercher'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Bouteille d\'eau', forbidden: ['Eau', 'Boire', 'Bouteille', 'Bouchon', 'Emporter'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Anniversaire', forbidden: ['Feter', 'Gateau', 'Cadeaux', 'Bougies', 'Fete'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Supermarche', forbidden: ['Courses', 'Caisse', 'Rayons', 'Magasin', 'Alimentaire'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Coiffeur', forbidden: ['Cheveux', 'Couper', 'Ciseaux', 'Salon', 'Coiffure'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Bibliotheque', forbidden: ['Livres', 'Lire', 'Emprunter', 'Silence', 'Etageres'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Embouteillage', forbidden: ['Voiture', 'Route', 'Attendre', 'Circulation', 'Autoroute'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Salle de sport', forbidden: ['Sport', 'Entrainer', 'Muscles', 'Appareils', 'Poids'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Creme solaire', forbidden: ['Soleil', 'Peau', 'Protection', 'Plage', 'Appliquer'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Montagnes russes', forbidden: ['Parc', 'Rapide', 'Rails', 'Virages', 'Adrenaline'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Grande roue', forbidden: ['Foire', 'Tourner', 'Haut', 'Nacelle', 'Vue'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Bonhomme de neige', forbidden: ['Neige', 'Hiver', 'Carotte', 'Nez', 'Froid'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Feu de camp', forbidden: ['Feu', 'Bois', 'Nuit', 'Chaud', 'Guimauve'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Bulle de savon', forbidden: ['Savon', 'Bulle', 'Souffler', 'Ronde', 'Eclater'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Lampe de poche', forbidden: ['Lumiere', 'Pile', 'Noir', 'Eclairer', 'Lampe'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Ballon', forbidden: ['Air', 'Gonfler', 'Fete', 'Colore', 'Eclater'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Chateau de sable', forbidden: ['Sable', 'Plage', 'Construire', 'Mer', 'Seau'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Puzzle', forbidden: ['Pieces', 'Assembler', 'Image', 'Casse-tete', 'Patience'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Cabane dans les arbres', forbidden: ['Arbre', 'Enfants', 'Bois', 'Haut', 'Maison'], category: 'Vie quotidienne', difficulty: 'easy' },

  // === Voyages (18) ===
  { term: 'Valise', forbidden: ['Voyage', 'Faire', 'Vetements', 'Aeroport', 'Vacances'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Passeport', forbidden: ['Frontiere', 'Document', 'Photo', 'Aeroport', 'Visa'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Hotel', forbidden: ['Chambre', 'Dormir', 'Lit', 'Reception', 'Vacances'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Aeroport', forbidden: ['Avion', 'Voler', 'Porte', 'Embarquement', 'Terminal'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Croisiere', forbidden: ['Bateau', 'Mer', 'Voyage', 'Cabine', 'Vacances'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Souvenir', forbidden: ['Memoire', 'Souvenir', 'Acheter', 'Vacances', 'Cadeau'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Randonnee', forbidden: ['Montagne', 'Nature', 'Chemin', 'Marcher', 'Sac a dos'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Camping', forbidden: ['Tente', 'Nature', 'Plein air', 'Camping', 'Dormir'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Vacances a la plage', forbidden: ['Mer', 'Soleil', 'Sable', 'Plage', 'Nager'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Visite guidee', forbidden: ['Ville', 'Guide', 'Monuments', 'Groupe', 'Tour'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Carte d\'embarquement', forbidden: ['Avion', 'Siege', 'Porte', 'Embarquement', 'Voler'], category: 'Voyages', difficulty: 'medium' },
  { term: 'Decalage horaire', forbidden: ['Fuseau', 'Fatigue', 'Vol', 'Voyage', 'Sommeil'], category: 'Voyages', difficulty: 'medium' },
  { term: 'Routard', forbidden: ['Sac a dos', 'Voyager', 'Budget', 'Auberge', 'Monde'], category: 'Voyages', difficulty: 'medium' },
  { term: 'Road trip', forbidden: ['Voiture', 'Conduire', 'Route', 'Voyage', 'Itineraire'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Plongee masque', forbidden: ['Eau', 'Masque', 'Mer', 'Poissons', 'Plonger'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Montgolfiere', forbidden: ['Voler', 'Air', 'Nacelle', 'Chaud', 'Flamme'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Randonnee nocturne', forbidden: ['Nuit', 'Sombre', 'Foret', 'Lampe', 'Marcher'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Sac de couchage', forbidden: ['Dormir', 'Camping', 'Chaud', 'Tente', 'Nuit'], category: 'Voyages', difficulty: 'easy' },

  // === Culture (20) ===
  { term: 'Opera', forbidden: ['Chanter', 'Scene', 'Musique', 'Theatre', 'Orchestre'], category: 'Culture', difficulty: 'easy' },
  { term: 'Musee', forbidden: ['Art', 'Exposition', 'Tableaux', 'Visiteurs', 'Galerie'], category: 'Culture', difficulty: 'easy' },
  { term: 'Carnaval', forbidden: ['Costume', 'Defile', 'Feter', 'Masque', 'Char'], category: 'Culture', difficulty: 'easy' },
  { term: 'Fete de la Musique', forbidden: ['Musique', 'Juin', 'Concert', 'Rue', 'Fete'], category: 'Culture', difficulty: 'easy' },
  { term: 'Marche de Noel', forbidden: ['Noel', 'Vin chaud', 'Stands', 'Cadeaux', 'Hiver'], category: 'Culture', difficulty: 'easy' },
  { term: 'Ballet', forbidden: ['Danse', 'Scene', 'Pointes', 'Musique', 'Lac des cygnes'], category: 'Culture', difficulty: 'easy' },
  { term: 'Graffiti', forbidden: ['Mur', 'Bombe', 'Peinture', 'Art', 'Rue'], category: 'Culture', difficulty: 'easy' },
  { term: 'Tatouage', forbidden: ['Peau', 'Aiguille', 'Dessin', 'Corps', 'Encre'], category: 'Culture', difficulty: 'easy' },
  { term: 'Cirque', forbidden: ['Clown', 'Acrobate', 'Chapiteau', 'Animaux', 'Spectacle'], category: 'Culture', difficulty: 'easy' },
  { term: 'Reveillon', forbidden: ['Nouvel An', 'Feu d\'artifice', 'Minuit', 'Champagne', 'Feter'], category: 'Culture', difficulty: 'easy' },
  { term: 'Mariage', forbidden: ['Mariee', 'Marie', 'Alliances', 'Eglise', 'Epouser'], category: 'Culture', difficulty: 'easy' },
  { term: 'Cinema', forbidden: ['Film', 'Popcorn', 'Ecran', 'Salle', 'Billets'], category: 'Culture', difficulty: 'easy' },
  { term: 'Karaoke', forbidden: ['Chanter', 'Micro', 'Paroles', 'Chanson', 'Scene'], category: 'Culture', difficulty: 'easy' },
  { term: 'Festival', forbidden: ['Musique', 'Plein air', 'Scene', 'Groupe', 'Ete'], category: 'Culture', difficulty: 'easy' },
  { term: 'Escape Game', forbidden: ['Enigme', 'Enferme', 'Equipe', 'Temps', 'Indice'], category: 'Culture', difficulty: 'medium' },
  { term: 'Pere Noel', forbidden: ['Noel', 'Cheminee', 'Cadeaux', 'Decembre', 'Rouge'], category: 'Culture', difficulty: 'easy' },
  { term: 'Lapin de Paques', forbidden: ['Paques', 'Oeufs', 'Cacher', 'Lapin', 'Printemps'], category: 'Culture', difficulty: 'easy' },
  { term: 'Bouteille a la mer', forbidden: ['Bouteille', 'Mer', 'Message', 'Eau', 'Ile'], category: 'Culture', difficulty: 'medium' },
  { term: 'Tour Eiffel', forbidden: ['Paris', 'France', 'Tour', 'Metal', 'Monument'], category: 'Culture', difficulty: 'easy' },
  { term: 'Arc de Triomphe', forbidden: ['Paris', 'Champs-Elysees', 'Monument', 'Napoleon', 'France'], category: 'Culture', difficulty: 'easy' },

  // === Science (16) ===
  { term: 'Gravite', forbidden: ['Terre', 'Tomber', 'Newton', 'Physique', 'Attirer'], category: 'Science', difficulty: 'medium' },
  { term: 'Photosynthese', forbidden: ['Plante', 'Soleil', 'Lumiere', 'Vert', 'Oxygene'], category: 'Science', difficulty: 'hard' },
  { term: 'Telescope', forbidden: ['Etoiles', 'Voir', 'Ciel', 'Lentille', 'Astronomie'], category: 'Science', difficulty: 'easy' },
  { term: 'ADN', forbidden: ['Genes', 'Heredite', 'Cellule', 'Helice', 'Corps'], category: 'Science', difficulty: 'medium' },
  { term: 'Volcan', forbidden: ['Lave', 'Eruption', 'Montagne', 'Chaud', 'Feu'], category: 'Science', difficulty: 'easy' },
  { term: 'Arc-en-ciel', forbidden: ['Couleurs', 'Pluie', 'Soleil', 'Arc', 'Ciel'], category: 'Science', difficulty: 'easy' },
  { term: 'Fossile', forbidden: ['Dinosaure', 'Ancien', 'Pierre', 'Os', 'Fouille'], category: 'Science', difficulty: 'medium' },
  { term: 'Champ magnetique', forbidden: ['Boussole', 'Terre', 'Nord', 'Sud', 'Attirer'], category: 'Science', difficulty: 'hard' },
  { term: 'Atome', forbidden: ['Petit', 'Noyau', 'Particule', 'Physique', 'Electron'], category: 'Science', difficulty: 'medium' },
  { term: 'Trou noir', forbidden: ['Espace', 'Gravite', 'Lumiere', 'Etoile', 'Engloutir'], category: 'Science', difficulty: 'medium' },
  { term: 'Microscope', forbidden: ['Petit', 'Grossir', 'Lentille', 'Laboratoire', 'Voir'], category: 'Science', difficulty: 'easy' },
  { term: 'Pile', forbidden: ['Courant', 'Energie', 'Charger', 'Plus', 'Moins'], category: 'Science', difficulty: 'easy' },
  { term: 'Dinosaure', forbidden: ['Disparu', 'Grand', 'Reptile', 'Fossile', 'T-Rex'], category: 'Science', difficulty: 'easy' },
  { term: 'Systeme solaire', forbidden: ['Planetes', 'Soleil', 'Terre', 'Orbite', 'Espace'], category: 'Science', difficulty: 'easy' },
  { term: 'Vaccin', forbidden: ['Piqure', 'Medecin', 'Maladie', 'Protection', 'Immunitaire'], category: 'Science', difficulty: 'easy' },
  { term: 'Voyage dans le temps', forbidden: ['Temps', 'Passe', 'Futur', 'Machine', 'Voyager'], category: 'Science', difficulty: 'medium' },

  // === Extra mixte (20) ===
  { term: 'Astronaute', forbidden: ['Espace', 'Fusee', 'Lune', 'NASA', 'Flotter'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Police', forbidden: ['Uniforme', 'Criminel', 'Sirene', 'Loi', 'Patrouille'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Restaurant', forbidden: ['Nourriture', 'Serveur', 'Menu', 'Chef', 'Table'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Maternelle', forbidden: ['Enfants', 'Jouer', 'Maitresse', 'Apprendre', 'Petit'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Lunettes de soleil', forbidden: ['Soleil', 'Yeux', 'Fonce', 'Ete', 'Porter'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Jungle', forbidden: ['Foret', 'Animaux', 'Tropical', 'Singes', 'Plantes'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Autoroute', forbidden: ['Voiture', 'Rapide', 'Route', 'Conduire', 'Vitesse'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Television', forbidden: ['Ecran', 'Regarder', 'Programme', 'Chaine', 'Film'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Hopital', forbidden: ['Medecin', 'Patient', 'Malade', 'Operation', 'Lit'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Chateau', forbidden: ['Roi', 'Forteresse', 'Porte', 'Cle', 'Conte'], category: 'Culture', difficulty: 'medium' },
  { term: 'Chemin de fer', forbidden: ['Train', 'Rails', 'Gare', 'Conduire', 'Voies'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Pompiers', forbidden: ['Feu', 'Eteindre', 'Lance', 'Rouge', 'Sirene'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Guitare', forbidden: ['Cordes', 'Musique', 'Jouer', 'Instrument', 'Concert'], category: 'Culture', difficulty: 'easy' },
  { term: 'Clown', forbidden: ['Cirque', 'Drole', 'Nez', 'Rire', 'Costume'], category: 'Culture', difficulty: 'easy' },
  { term: 'Diamant', forbidden: ['Pierre precieuse', 'Bague', 'Cher', 'Briller', 'Dur'], category: 'Science', difficulty: 'easy' },
  { term: 'Miel', forbidden: ['Abeille', 'Sucre', 'Pot', 'Pain', 'Dore'], category: 'Cuisine', difficulty: 'easy' },
  { term: 'Phare', forbidden: ['Lumiere', 'Mer', 'Cote', 'Bateau', 'Tour'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Avion', forbidden: ['Voler', 'Pilote', 'Ciel', 'Aeroport', 'Nuages'], category: 'Voyages', difficulty: 'easy' },
  { term: 'Dentiste', forbidden: ['Dents', 'Fraise', 'Douleur', 'Cabinet', 'Docteur'], category: 'Vie quotidienne', difficulty: 'easy' },
  { term: 'Boulanger', forbidden: ['Pain', 'Viennoiserie', 'Cuire', 'Four', 'Farine'], category: 'Vie quotidienne', difficulty: 'easy' },
];
