/** Deliberately selected visual clues. Unclear legacy associations are not dealt. */
export const CURATED_CLUES: Record<string, { emojis?: string; aliases?: string[] }> = {
  '🦁👑': { aliases: ['Der König der Löwen', 'Lion King'] },
  '🧊🚢💔': {},
  '🕷️🧑': {},
  '⭐🔫🌌': {},
  '🧙‍♂️💍🌋': { aliases: ['Der Herr der Ringe', 'The Lord of the Rings'] },
  '🦇🌃🦹': {},
  '🐟🔍': {},
  '👻👻👻🔫': {},
  '🧊❄️👸🎵': { aliases: ['Die Eiskönigin', 'Die Eiskönigin völlig unverfroren'] },
  '🏴‍☠️⚓🗺️': { aliases: ['Pirates of the Caribbean'] },
  '🐀👨‍🍳🇫🇷': {},
  '🦖🏝️🔬': { aliases: ['Jurassic World'] },
  '👽☎️🚲🌕': { aliases: ['ET der Außerirdische', 'ET the Extra Terrestrial'] },
  '💀🎃🎄': { aliases: ['The Nightmare Before Christmas'] },
  '🐼🥋🏯': {},
  '🧓⬆️🎈🏠': {},
  '🔵👤👤🌿': {},
  '👁️🐅': {},
  '🔔🎄🎅': {},
  '🎸🤘😈🛣️': {},
  '👑🍔🍟': {},
  '🟥🐂🐂': { emojis: '🔴🐂' },
  '🍎📱💻': {},
  '🧱🔴🟡🟢': {},
  '🧪👨‍🔬💊💰': {},
  '👑⚔️🐉': {},
  '🧟‍♂️🔫🌍': { aliases: ['Walking Dead'] },
  '🔦👦🚲🧇': {},
  '🏢📎😐': {},
  '🦑🎮💀': {},
  '🤖👍🔥': { emojis: '🤖🕶️🔫⏳' },
  '🧪👨‍🔬💚': { emojis: '🧪😡💚💪' },
  '🏎️💨🔧': { emojis: '🏎️👀🏁', aliases: ['Cars Autos wie wir'] },
  '🎤💃🕺🇸🇪': { emojis: '💃👑' },
  '🌧️☔😢': { emojis: '🎤🌧️☂️', aliases: ["Singing in the Rain", "Singin in the Rain"] },
  '🔥🎤👧': { emojis: '👧🔥' },
  '🌈🎵☁️': { emojis: '⬆️🌈', aliases: ['Over the Rainbow'] },
  '🦊❓': { emojis: '🦊🗣️❓', aliases: ['The Fox'] },
  '⏰🕐⏰': { emojis: '⏰➡️⏰' },
  '🎹🎤🔥👨': { emojis: '🎹👨' },
  '🌊🏄🎵': { emojis: '🏄🇺🇸', aliases: ["Surfin USA", "Surfing USA"] },
  '👩‍🚀🚀🌟': { emojis: '🚀👨' },
  '💛🌻🎵': { emojis: '☀️🌻' },
  '🍎🌳🔽': { emojis: '🌳🍎⬇️📍' },
  '⏰💰': {},
  '🗣️🥈🤫🥇': {},
  '👁️👁️🍽️': {},
  '🐱🏠🐭💃': { emojis: '🐈🚪➡️🐭💃', aliases: ['Ist die Katze aus dem Haus tanzen die Mäuse auf dem Tisch', 'Wenn die Katze aus dem Haus ist tanzen die Mäuse auf dem Tisch'] },
  '🌹🔧⚙️': { emojis: '🌹🌵', aliases: ['Keine Rosen ohne Dornen'] },
  '🌧️☀️🌈': {},
  '🐔🥚❓': {},
  '🪨💧🕰️': { emojis: '💧💧💧🪨' },
  '🙈🙉🙊': {},
  '🐴🎁🦷': {},
  '✔️👟💨': {},
  '🟡🟡🟡🟡🚗': { emojis: '⭕⭕⭕⭕🚗' },
  '⭐🏨☕': { emojis: '☕🧜‍♀️🟢' },
  '🐦📱💬': {},
  '🐻🧊🍬': { emojis: '🧸🟡🔴🍬' },
  '🟫🍫🐄': { emojis: '🟣🐄🍫' },
  '🏠💵📌': { emojis: '🏦💰🎭🔴', aliases: ['La Casa de Papel', 'Money Heist'] },
  '🧑‍🔬🤓🎯🏠': { emojis: '💥🌌⚛️🤓', aliases: ['Big Bang Theory'] },
  '☕👫👫👫': {},
  '🍳👨‍🍳🔪⭐': {},
  '🧛‍♂️🩸📖': { aliases: ['The Vampire Diaries'] },
  '🏝️✈️🔢': { emojis: '✈️💥🏝️🔢' },
  '♟️👸🇬🇧': { emojis: '♟️👑👩', aliases: ["The Queen's Gambit", 'Queens Gambit'] },
  '🍄🟢🏰👸': { emojis: '👨‍🔧🔴🍄👸', aliases: ['Super Mario Bros', 'Mario'] },
  '⛏️🟫🌍🧱': {},
  '🏎️🍌🏁🌈': {},
  '⚡🟡⚡🐭': {},
  '🗡️🛡️🧝‍♂️🏰': { aliases: ['The Legend of Zelda', 'Legend of Zelda'] },
  '🔵🦔💨💎': { aliases: ['Sonic the Hedgehog'] },
  '🧱🧱🧱📐': { emojis: '🟦🟦🟨🟨⬇️' },
  '🚀🌌👨‍🚀🔧': { emojis: '🚀👨‍🚀🔪🤫' },
  '🧸🎈🍯': { aliases: ['Winnie the Pooh', 'Winnie Puh'] },
  '🦈🏊‍♂️😱': { aliases: ['Der weiße Hai', 'Jaws'] },
  '🧪⏰🚗💨': {},
  '🎭🌹👻🎵': { aliases: ['Phantom der Oper', 'The Phantom of the Opera'] },
  '🧊🦣🐿️': {},
  '🏜️🪱🌍': { aliases: ['Der Wüstenplanet'] },
  '💜🌧️🎵': {},
  '🏠🛣️🎵': { emojis: '🛣️🏡⛰️', aliases: ['Country Roads', 'Take Me Home Country Roads'] },
  '🌊🏖️👩‍🦰🎵': { emojis: '🌊👀' },
  '🧡📞🎵': { emojis: '📞🙋❓' },
  '🐦🌅🪱': { aliases: ['Der frühe Vogel fängt den Wurm', 'Früher Vogel fängt den Wurm'] },
  '🏠🔑❤️': { emojis: '🏠🟰❤️' },
  '🪵👀🌲': { emojis: '🌲🌲🙈🌲🌲' },
  '👀🍲👩‍🍳': { emojis: '👨‍🍳👩‍🍳👨‍🍳🥣🤢' },
  '🪑🔧🇸🇪': {},
  '🏎️🐎🇮🇹': {},
};

export function curateEmojiPuzzles<T extends { emojis: string; answer: string; category: string; difficulty: 1|2|3 }>(localized: T[], languages: T[][]): (T & { aliases: string[] })[] {
  const seen = new Set<string>();
  return localized.filter(p => p.emojis in CURATED_CLUES && !seen.has(p.answer) && !!seen.add(p.answer)).map(p => {
    const rule = CURATED_CLUES[p.emojis];
    const aliases = [...new Set([...(rule.aliases ?? []), ...languages.flatMap(deck => deck.filter(item => item.emojis === p.emojis).map(item => item.answer))])].filter(answer => answer !== p.answer);
    return { ...p, emojis: rule.emojis ?? p.emojis, aliases };
  });
}
