export interface EmojiPuzzle {
  emojis: string;
  answer: string;
  category: string;
  difficulty: 1 | 2 | 3;
}

export const EMOJI_PUZZLES: EmojiPuzzle[] = [
  // Films (20)
  { emojis: '🦁👑', answer: 'Le Roi Lion', category: 'Films', difficulty: 1 },
  { emojis: '🧊🚢💔', answer: 'Titanic', category: 'Films', difficulty: 1 },
  { emojis: '🕷️🧑', answer: 'Spider-Man', category: 'Films', difficulty: 1 },
  { emojis: '⭐🔫🌌', answer: 'Star Wars', category: 'Films', difficulty: 1 },
  { emojis: '🧙‍♂️💍🌋', answer: 'Le Seigneur des Anneaux', category: 'Films', difficulty: 2 },
  { emojis: '🦇🌃🦹', answer: 'Batman', category: 'Films', difficulty: 1 },
  { emojis: '🐟🔍', answer: 'Le Monde de Nemo', category: 'Films', difficulty: 1 },
  { emojis: '👻👻👻🔫', answer: 'Ghostbusters', category: 'Films', difficulty: 2 },
  { emojis: '🧊❄️👸🎵', answer: 'La Reine des Neiges', category: 'Films', difficulty: 1 },
  { emojis: '🏴‍☠️⚓🗺️', answer: 'Pirates des Caraibes', category: 'Films', difficulty: 2 },
  { emojis: '🤖👍🔥', answer: 'Terminator', category: 'Films', difficulty: 2 },
  { emojis: '🧪👨‍🔬💚', answer: 'Hulk', category: 'Films', difficulty: 2 },
  { emojis: '🏎️💨🔧', answer: 'Cars', category: 'Films', difficulty: 1 },
  { emojis: '🐀👨‍🍳🇫🇷', answer: 'Ratatouille', category: 'Films', difficulty: 2 },
  { emojis: '🦖🏝️🔬', answer: 'Jurassic Park', category: 'Films', difficulty: 1 },
  { emojis: '👽☎️🚲🌕', answer: 'E.T.', category: 'Films', difficulty: 2 },
  { emojis: '💀🎃🎄', answer: 'L\'Etrange Noel de Mr Jack', category: 'Films', difficulty: 3 },
  { emojis: '🐼🥋🏯', answer: 'Kung Fu Panda', category: 'Films', difficulty: 1 },
  { emojis: '🧓⬆️🎈🏠', answer: 'La-Haut', category: 'Films', difficulty: 2 },
  { emojis: '🔵👤👤🌿', answer: 'Avatar', category: 'Films', difficulty: 2 },

  // Chansons (18)
  { emojis: '🎤💃🕺🇸🇪', answer: 'Dancing Queen', category: 'Chansons', difficulty: 2 },
  { emojis: '🌧️☔😢', answer: 'Singin in the Rain', category: 'Chansons', difficulty: 2 },
  { emojis: '🎸🤘😈🛣️', answer: 'Highway to Hell', category: 'Chansons', difficulty: 2 },
  { emojis: '💎🌌🎵', answer: 'Diamonds', category: 'Chansons', difficulty: 2 },
  { emojis: '🔥🎤👧', answer: 'Girl on Fire', category: 'Chansons', difficulty: 2 },
  { emojis: '☀️😊', answer: 'Happy', category: 'Chansons', difficulty: 1 },
  { emojis: '🌈🎵☁️', answer: 'Somewhere Over the Rainbow', category: 'Chansons', difficulty: 2 },
  { emojis: '👁️🐅', answer: 'Eye of the Tiger', category: 'Chansons', difficulty: 1 },
  { emojis: '🦊❓', answer: 'What Does the Fox Say', category: 'Chansons', difficulty: 1 },
  { emojis: '💃🍑', answer: 'Shake It Off', category: 'Chansons', difficulty: 3 },
  { emojis: '🧱🏗️🎵', answer: 'Another Brick in the Wall', category: 'Chansons', difficulty: 3 },
  { emojis: '🔔🎄🎅', answer: 'Jingle Bells', category: 'Chansons', difficulty: 1 },
  { emojis: '🌃🎷🗽', answer: 'New York New York', category: 'Chansons', difficulty: 2 },
  { emojis: '⏰🕐⏰', answer: 'Time After Time', category: 'Chansons', difficulty: 3 },
  { emojis: '🎹🎤🔥👨', answer: 'Piano Man', category: 'Chansons', difficulty: 2 },
  { emojis: '🌊🏄🎵', answer: 'Surfin USA', category: 'Chansons', difficulty: 2 },
  { emojis: '👩‍🚀🚀🌟', answer: 'Rocket Man', category: 'Chansons', difficulty: 2 },
  { emojis: '💛🌻🎵', answer: 'Sunflower', category: 'Chansons', difficulty: 2 },

  // Proverbes (18)
  { emojis: '🍎🌳🔽', answer: 'La pomme ne tombe pas loin de l\'arbre', category: 'Proverbes', difficulty: 1 },
  { emojis: '🐦🖐️🕊️🏠', answer: 'Un tiens vaut mieux que deux tu l\'auras', category: 'Proverbes', difficulty: 2 },
  { emojis: '⏰💰', answer: 'Le temps c\'est de l\'argent', category: 'Proverbes', difficulty: 1 },
  { emojis: '🗣️🥈🤫🥇', answer: 'La parole est d\'argent le silence est d\'or', category: 'Proverbes', difficulty: 2 },
  { emojis: '👁️👁️🍽️', answer: 'On mange avec les yeux', category: 'Proverbes', difficulty: 1 },
  { emojis: '🔚👍🔚', answer: 'Tout est bien qui finit bien', category: 'Proverbes', difficulty: 1 },
  { emojis: '❤️💧👁️', answer: 'Loin des yeux loin du coeur', category: 'Proverbes', difficulty: 2 },
  { emojis: '🐱🏠🐭💃', answer: 'Quand le chat n\'est pas la les souris dansent', category: 'Proverbes', difficulty: 3 },
  { emojis: '🌹🔧⚙️', answer: 'Pas de rose sans epines', category: 'Proverbes', difficulty: 2 },
  { emojis: '🌧️☀️🌈', answer: 'Apres la pluie le beau temps', category: 'Proverbes', difficulty: 1 },
  { emojis: '🐕🐕🐕🦴', answer: 'Trop de cuisiniers gatent la sauce', category: 'Proverbes', difficulty: 3 },
  { emojis: '🔑🗝️🔓', answer: 'C\'est en forgeant qu\'on devient forgeron', category: 'Proverbes', difficulty: 3 },
  { emojis: '🐔🥚❓', answer: 'Qui est venu en premier la poule ou l\'oeuf', category: 'Proverbes', difficulty: 2 },
  { emojis: '🪨💧🕰️', answer: 'Petit a petit l\'oiseau fait son nid', category: 'Proverbes', difficulty: 2 },
  { emojis: '🙈🙉🙊', answer: 'Ne rien voir ne rien entendre ne rien dire', category: 'Proverbes', difficulty: 1 },
  { emojis: '🐴🎁🦷', answer: 'A cheval donne on ne regarde pas les dents', category: 'Proverbes', difficulty: 3 },
  { emojis: '🧹✨🆕', answer: 'Balai neuf balaye bien', category: 'Proverbes', difficulty: 2 },
  { emojis: '💪🧠📚', answer: 'Le savoir c\'est le pouvoir', category: 'Proverbes', difficulty: 1 },

  // Marques (16)
  { emojis: '🍎📱💻', answer: 'Apple', category: 'Marques', difficulty: 1 },
  { emojis: '✔️👟💨', answer: 'Nike', category: 'Marques', difficulty: 1 },
  { emojis: '🟡🟡🟡🟡🚗', answer: 'Audi', category: 'Marques', difficulty: 2 },
  { emojis: '👑🍔🍟', answer: 'Burger King', category: 'Marques', difficulty: 1 },
  { emojis: '🟥🐂🐂', answer: 'Red Bull', category: 'Marques', difficulty: 1 },
  { emojis: '🎮🕹️🍄', answer: 'Nintendo', category: 'Marques', difficulty: 2 },
  { emojis: '📦🏠🔜', answer: 'Amazon', category: 'Marques', difficulty: 1 },
  { emojis: '🔎🌐📊', answer: 'Google', category: 'Marques', difficulty: 1 },
  { emojis: '🧱🔴🟡🟢', answer: 'Lego', category: 'Marques', difficulty: 1 },
  { emojis: '⭐🏨☕', answer: 'Starbucks', category: 'Marques', difficulty: 2 },
  { emojis: '🚗⚡🔋', answer: 'Tesla', category: 'Marques', difficulty: 1 },
  { emojis: '🐦📱💬', answer: 'Twitter', category: 'Marques', difficulty: 1 },
  { emojis: '📸🟪🌅', answer: 'Instagram', category: 'Marques', difficulty: 1 },
  { emojis: '🎵🎧🟢', answer: 'Spotify', category: 'Marques', difficulty: 1 },
  { emojis: '🐻🧊🍬', answer: 'Haribo', category: 'Marques', difficulty: 2 },
  { emojis: '🟫🍫🐄', answer: 'Milka', category: 'Marques', difficulty: 2 },

  // Series (16)
  { emojis: '🧪👨‍🔬💊💰', answer: 'Breaking Bad', category: 'Series', difficulty: 1 },
  { emojis: '👑⚔️🐉', answer: 'Game of Thrones', category: 'Series', difficulty: 1 },
  { emojis: '🧟‍♂️🔫🌍', answer: 'The Walking Dead', category: 'Series', difficulty: 1 },
  { emojis: '🔦👦🚲🧇', answer: 'Stranger Things', category: 'Series', difficulty: 1 },
  { emojis: '🏠💵📌', answer: 'La Casa de Papel', category: 'Series', difficulty: 2 },
  { emojis: '👩‍⚕️🏥💉', answer: 'Grey\'s Anatomy', category: 'Series', difficulty: 2 },
  { emojis: '🧑‍🔬🤓🎯🏠', answer: 'The Big Bang Theory', category: 'Series', difficulty: 1 },
  { emojis: '☕👫👫👫', answer: 'Friends', category: 'Series', difficulty: 1 },
  { emojis: '🏢📎😐', answer: 'The Office', category: 'Series', difficulty: 2 },
  { emojis: '🍳👨‍🍳🔪⭐', answer: 'MasterChef', category: 'Series', difficulty: 2 },
  { emojis: '🦑🎮💀', answer: 'Squid Game', category: 'Series', difficulty: 1 },
  { emojis: '🧛‍♂️🩸📖', answer: 'Vampire Diaries', category: 'Series', difficulty: 2 },
  { emojis: '🏝️✈️🔢', answer: 'Lost', category: 'Series', difficulty: 2 },
  { emojis: '♟️👸🇬🇧', answer: 'Le Jeu de la Dame', category: 'Series', difficulty: 3 },
  { emojis: '🧑‍🏫🔴🔵', answer: 'La Casa de Papel', category: 'Series', difficulty: 3 },
  { emojis: '🐺🌕🏰', answer: 'Teen Wolf', category: 'Series', difficulty: 2 },

  // Jeux video (14)
  { emojis: '🍄🟢🏰👸', answer: 'Super Mario', category: 'Jeux video', difficulty: 1 },
  { emojis: '⛏️🟫🌍🧱', answer: 'Minecraft', category: 'Jeux video', difficulty: 1 },
  { emojis: '⚽🏟️⚡', answer: 'FIFA', category: 'Jeux video', difficulty: 1 },
  { emojis: '🔫🎯🏃‍♂️💣', answer: 'Call of Duty', category: 'Jeux video', difficulty: 2 },
  { emojis: '🏎️🍌🏁🌈', answer: 'Mario Kart', category: 'Jeux video', difficulty: 1 },
  { emojis: '⚡🟡⚡🐭', answer: 'Pokemon', category: 'Jeux video', difficulty: 1 },
  { emojis: '🗡️🛡️🧝‍♂️🏰', answer: 'Zelda', category: 'Jeux video', difficulty: 2 },
  { emojis: '🔵🦔💨💎', answer: 'Sonic', category: 'Jeux video', difficulty: 1 },
  { emojis: '🏗️🏙️🚗🎮', answer: 'GTA', category: 'Jeux video', difficulty: 2 },
  { emojis: '🧱🧱🧱📐', answer: 'Tetris', category: 'Jeux video', difficulty: 1 },
  { emojis: '🐔🔫🪖🏝️', answer: 'Fortnite', category: 'Jeux video', difficulty: 1 },
  { emojis: '🧙‍♂️📖⚔️🐴', answer: 'The Witcher', category: 'Jeux video', difficulty: 2 },
  { emojis: '🚀🌌👨‍🚀🔧', answer: 'Among Us', category: 'Jeux video', difficulty: 2 },
  { emojis: '🐉⚔️🗻🏹', answer: 'Skyrim', category: 'Jeux video', difficulty: 3 },

  // Nouveaux Films (10)
  { emojis: '🧸🎈🍯', answer: 'Winnie l\'Ourson', category: 'Films', difficulty: 1 },
  { emojis: '🦈🏊‍♂️😱', answer: 'Les Dents de la Mer', category: 'Films', difficulty: 2 },
  { emojis: '🐒🍌👑', answer: 'Tarzan', category: 'Films', difficulty: 2 },
  { emojis: '🧪⏰🚗💨', answer: 'Retour vers le Futur', category: 'Films', difficulty: 2 },
  { emojis: '🎭🌹👻🎵', answer: 'Le Fantome de l\'Opera', category: 'Films', difficulty: 3 },
  { emojis: '🧊🦣🐿️', answer: 'L\'Age de Glace', category: 'Films', difficulty: 1 },
  { emojis: '🏜️🪱🌍', answer: 'Dune', category: 'Films', difficulty: 3 },
  { emojis: '🔫🤠🐴🌵', answer: 'Django Unchained', category: 'Films', difficulty: 3 },
  { emojis: '👩‍🍳🐀🇫🇷⭐', answer: 'Ratatouille', category: 'Films', difficulty: 1 },
  { emojis: '🦸‍♀️🏝️⚔️🛡️', answer: 'Wonder Woman', category: 'Films', difficulty: 2 },

  // Nouvelles Chansons (10)
  { emojis: '🎤🎵🌍🙏', answer: 'Imagine', category: 'Chansons', difficulty: 2 },
  { emojis: '💜🌧️🎵', answer: 'Purple Rain', category: 'Chansons', difficulty: 2 },
  { emojis: '🏠🛣️🎵', answer: 'Take Me Home Country Roads', category: 'Chansons', difficulty: 3 },
  { emojis: '👻🎵💀👻', answer: 'Thriller', category: 'Chansons', difficulty: 1 },
  { emojis: '🌊🏖️👩‍🦰🎵', answer: 'Ocean Eyes', category: 'Chansons', difficulty: 3 },
  { emojis: '💃🎶🇨🇺', answer: 'Havana', category: 'Chansons', difficulty: 2 },
  { emojis: '🔔🎅🎄⛄', answer: 'Last Christmas', category: 'Chansons', difficulty: 1 },
  { emojis: '🌙✨💤🎵', answer: 'Sonate au Clair de Lune', category: 'Chansons', difficulty: 3 },
  { emojis: '🚗💨🎵🛣️', answer: 'Drive', category: 'Chansons', difficulty: 3 },
  { emojis: '🧡📞🎵', answer: 'Call Me Maybe', category: 'Chansons', difficulty: 2 },

  // Nouveaux Proverbes (10)
  { emojis: '🐦🌅🪱', answer: 'L\'avenir appartient a ceux qui se levent tot', category: 'Proverbes', difficulty: 1 },
  { emojis: '🏠🔑❤️', answer: 'La maison c\'est la ou est le coeur', category: 'Proverbes', difficulty: 2 },
  { emojis: '🍒🍒👫', answer: 'Qui se ressemble s\'assemble', category: 'Proverbes', difficulty: 3 },
  { emojis: '🐕🌳🔔', answer: 'Il y a anguille sous roche', category: 'Proverbes', difficulty: 2 },
  { emojis: '🧹🏠✨', answer: 'L\'ordre c\'est la moitie de la vie', category: 'Proverbes', difficulty: 2 },
  { emojis: '💰🗣️❌', answer: 'L\'argent n\'a pas d\'odeur', category: 'Proverbes', difficulty: 2 },
  { emojis: '🪵👀🌲', answer: 'L\'arbre qui cache la foret', category: 'Proverbes', difficulty: 3 },
  { emojis: '🎯🔨💪', answer: 'C\'est en forgeant qu\'on devient forgeron', category: 'Proverbes', difficulty: 1 },
  { emojis: '🍏🌳⬇️', answer: 'La pomme ne tombe pas loin de l\'arbre', category: 'Proverbes', difficulty: 1 },
  { emojis: '👀🍲👩‍🍳', answer: 'Trop de cuisiniers gatent la sauce', category: 'Proverbes', difficulty: 2 },

  // Nouvelles Marques (10)
  { emojis: '🎬🍿❤️', answer: 'Netflix', category: 'Marques', difficulty: 1 },
  { emojis: '🪑🔧🇸🇪', answer: 'IKEA', category: 'Marques', difficulty: 1 },
  { emojis: '🏎️🐎🇮🇹', answer: 'Ferrari', category: 'Marques', difficulty: 1 },
  { emojis: '🎮🍄🔴', answer: 'Nintendo', category: 'Marques', difficulty: 1 },
  { emojis: '📱💬🟢', answer: 'WhatsApp', category: 'Marques', difficulty: 1 },
  { emojis: '☕🧜‍♀️🟢', answer: 'Starbucks', category: 'Marques', difficulty: 1 },
  { emojis: '🏠🔑✈️', answer: 'Airbnb', category: 'Marques', difficulty: 2 },
  { emojis: '📦📱🛒', answer: 'Amazon', category: 'Marques', difficulty: 1 },
  { emojis: '🎵🎧📱', answer: 'Spotify', category: 'Marques', difficulty: 1 },
  { emojis: '🔍📧📺', answer: 'Google', category: 'Marques', difficulty: 1 },
];
