export interface EmojiPuzzle {
  emojis: string;
  answer: string;
  category: string;
  difficulty: 1 | 2 | 3;
}

export const EMOJI_PUZZLES_IT: EmojiPuzzle[] = [
  // Film (30)
  { emojis: '🦁👑', answer: 'Il Re Leone', category: 'Film', difficulty: 1 },
  { emojis: '🧊🚢💔', answer: 'Titanic', category: 'Film', difficulty: 1 },
  { emojis: '🕷️🧑', answer: 'Spider-Man', category: 'Film', difficulty: 1 },
  { emojis: '⭐🔫🌌', answer: 'Guerre Stellari', category: 'Film', difficulty: 1 },
  { emojis: '🧙‍♂️💍🌋', answer: 'Il Signore degli Anelli', category: 'Film', difficulty: 2 },
  { emojis: '🦇🌃🦹', answer: 'Batman', category: 'Film', difficulty: 1 },
  { emojis: '🐟🔍', answer: 'Alla ricerca di Nemo', category: 'Film', difficulty: 1 },
  { emojis: '👻👻👻🔫', answer: 'Ghostbusters', category: 'Film', difficulty: 2 },
  { emojis: '🧊❄️👸🎵', answer: 'Frozen', category: 'Film', difficulty: 1 },
  { emojis: '🏴‍☠️⚓🗺️', answer: 'Pirati dei Caraibi', category: 'Film', difficulty: 2 },
  { emojis: '🤖👍🔥', answer: 'Terminator', category: 'Film', difficulty: 2 },
  { emojis: '🧪👨‍🔬💚', answer: 'Hulk', category: 'Film', difficulty: 2 },
  { emojis: '🏎️💨🔧', answer: 'Cars', category: 'Film', difficulty: 1 },
  { emojis: '🐀👨‍🍳🇫🇷', answer: 'Ratatouille', category: 'Film', difficulty: 2 },
  { emojis: '🦖🏝️🔬', answer: 'Jurassic Park', category: 'Film', difficulty: 1 },
  { emojis: '👽☎️🚲🌕', answer: 'E.T.', category: 'Film', difficulty: 2 },
  { emojis: '💀🎃🎄', answer: 'Nightmare Before Christmas', category: 'Film', difficulty: 3 },
  { emojis: '🐼🥋🏯', answer: 'Kung Fu Panda', category: 'Film', difficulty: 1 },
  { emojis: '🧓⬆️🎈🏠', answer: 'Up', category: 'Film', difficulty: 2 },
  { emojis: '🔵👤👤🌿', answer: 'Avatar', category: 'Film', difficulty: 2 },
  { emojis: '🧸🎈🍯', answer: 'Winnie the Pooh', category: 'Film', difficulty: 1 },
  { emojis: '🦈🏊‍♂️😱', answer: 'Lo squalo', category: 'Film', difficulty: 2 },
  { emojis: '🐒🍌👑', answer: 'Tarzan', category: 'Film', difficulty: 2 },
  { emojis: '🧪⏰🚗💨', answer: 'Ritorno al Futuro', category: 'Film', difficulty: 2 },
  { emojis: '🎭🌹👻🎵', answer: 'Il Fantasma dell\'Opera', category: 'Film', difficulty: 3 },
  { emojis: '🧊🦣🐿️', answer: 'L\'era glaciale', category: 'Film', difficulty: 1 },
  { emojis: '🏜️🪱🌍', answer: 'Dune', category: 'Film', difficulty: 3 },
  { emojis: '🔫🤠🐴🌵', answer: 'Django Unchained', category: 'Film', difficulty: 3 },
  { emojis: '👩‍🍳🐀🇫🇷⭐', answer: 'Ratatouille', category: 'Film', difficulty: 1 },
  { emojis: '🦸‍♀️🏝️⚔️🛡️', answer: 'Wonder Woman', category: 'Film', difficulty: 2 },

  // Canzoni (28)
  { emojis: '🎤💃🕺🇸🇪', answer: 'Dancing Queen', category: 'Canzoni', difficulty: 2 },
  { emojis: '🌧️☔😢', answer: 'Singin\' in the Rain', category: 'Canzoni', difficulty: 2 },
  { emojis: '🎸🤘😈🛣️', answer: 'Highway to Hell', category: 'Canzoni', difficulty: 2 },
  { emojis: '💎🌌🎵', answer: 'Diamonds', category: 'Canzoni', difficulty: 2 },
  { emojis: '🔥🎤👧', answer: 'Girl on Fire', category: 'Canzoni', difficulty: 2 },
  { emojis: '☀️😊', answer: 'Happy', category: 'Canzoni', difficulty: 1 },
  { emojis: '🌈🎵☁️', answer: 'Somewhere Over the Rainbow', category: 'Canzoni', difficulty: 2 },
  { emojis: '👁️🐅', answer: 'Eye of the Tiger', category: 'Canzoni', difficulty: 1 },
  { emojis: '🦊❓', answer: 'What Does the Fox Say', category: 'Canzoni', difficulty: 1 },
  { emojis: '💃🍑', answer: 'Shake It Off', category: 'Canzoni', difficulty: 3 },
  { emojis: '🧱🏗️🎵', answer: 'Another Brick in the Wall', category: 'Canzoni', difficulty: 3 },
  { emojis: '🔔🎄🎅', answer: 'Jingle Bells', category: 'Canzoni', difficulty: 1 },
  { emojis: '🌃🎷🗽', answer: 'New York New York', category: 'Canzoni', difficulty: 2 },
  { emojis: '⏰🕐⏰', answer: 'Time After Time', category: 'Canzoni', difficulty: 3 },
  { emojis: '🎹🎤🔥👨', answer: 'Piano Man', category: 'Canzoni', difficulty: 2 },
  { emojis: '🌊🏄🎵', answer: 'Surfin\' USA', category: 'Canzoni', difficulty: 2 },
  { emojis: '👩‍🚀🚀🌟', answer: 'Rocket Man', category: 'Canzoni', difficulty: 2 },
  { emojis: '💛🌻🎵', answer: 'Sunflower', category: 'Canzoni', difficulty: 2 },
  { emojis: '🎤🎵🌍🙏', answer: 'Imagine', category: 'Canzoni', difficulty: 2 },
  { emojis: '💜🌧️🎵', answer: 'Purple Rain', category: 'Canzoni', difficulty: 2 },
  { emojis: '🏠🛣️🎵', answer: 'Take Me Home Country Roads', category: 'Canzoni', difficulty: 3 },
  { emojis: '👻🎵💀👻', answer: 'Thriller', category: 'Canzoni', difficulty: 1 },
  { emojis: '🌊🏖️👩‍🦰🎵', answer: 'Ocean Eyes', category: 'Canzoni', difficulty: 3 },
  { emojis: '💃🎶🇨🇺', answer: 'Havana', category: 'Canzoni', difficulty: 2 },
  { emojis: '🔔🎅🎄⛄', answer: 'Last Christmas', category: 'Canzoni', difficulty: 1 },
  { emojis: '🌙✨💤🎵', answer: 'Sonata al chiaro di luna', category: 'Canzoni', difficulty: 3 },
  { emojis: '🚗💨🎵🛣️', answer: 'Drive', category: 'Canzoni', difficulty: 3 },
  { emojis: '🧡📞🎵', answer: 'Call Me Maybe', category: 'Canzoni', difficulty: 2 },

  // Proverbi (28)
  { emojis: '🍎🌳🔽', answer: 'La mela non cade lontano dall\'albero', category: 'Proverbi', difficulty: 1 },
  { emojis: '🐦🖐️🕊️🏠', answer: 'Meglio un uovo oggi che una gallina domani', category: 'Proverbi', difficulty: 2 },
  { emojis: '⏰💰', answer: 'Il tempo e denaro', category: 'Proverbi', difficulty: 1 },
  { emojis: '🗣️🥈🤫🥇', answer: 'La parola e d\'argento il silenzio e d\'oro', category: 'Proverbi', difficulty: 2 },
  { emojis: '👁️👁️🍽️', answer: 'Anche l\'occhio vuole la sua parte', category: 'Proverbi', difficulty: 1 },
  { emojis: '🔚👍🔚', answer: 'Tutto e bene quel che finisce bene', category: 'Proverbi', difficulty: 1 },
  { emojis: '❤️💧👁️', answer: 'Lontano dagli occhi lontano dal cuore', category: 'Proverbi', difficulty: 2 },
  { emojis: '🐱🏠🐭💃', answer: 'Quando il gatto non c\'e i topi ballano', category: 'Proverbi', difficulty: 3 },
  { emojis: '🌹🔧⚙️', answer: 'Non c\'e rosa senza spine', category: 'Proverbi', difficulty: 2 },
  { emojis: '🌧️☀️🌈', answer: 'Dopo la pioggia viene il sereno', category: 'Proverbi', difficulty: 1 },
  { emojis: '🐕🐕🐕🦴', answer: 'Troppi galli a cantar non si fa mai giorno', category: 'Proverbi', difficulty: 3 },
  { emojis: '🔑🗝️🔓', answer: 'Provare per credere', category: 'Proverbi', difficulty: 3 },
  { emojis: '🐔🥚❓', answer: 'E nato prima l\'uovo o la gallina', category: 'Proverbi', difficulty: 2 },
  { emojis: '🪨💧🕰️', answer: 'La goccia scava la pietra', category: 'Proverbi', difficulty: 2 },
  { emojis: '🙈🙉🙊', answer: 'Non vedo non sento non parlo', category: 'Proverbi', difficulty: 1 },
  { emojis: '🐴🎁🦷', answer: 'A caval donato non si guarda in bocca', category: 'Proverbi', difficulty: 3 },
  { emojis: '🧹✨🆕', answer: 'Scopa nuova spazza bene', category: 'Proverbi', difficulty: 2 },
  { emojis: '💪🧠📚', answer: 'Sapere e potere', category: 'Proverbi', difficulty: 1 },
  { emojis: '🐦🌅🪱', answer: 'Il mattino ha l\'oro in bocca', category: 'Proverbi', difficulty: 1 },
  { emojis: '🏠🔑❤️', answer: 'Casa dolce casa', category: 'Proverbi', difficulty: 2 },
  { emojis: '🍒🍒👫', answer: 'Chi si somiglia si piglia', category: 'Proverbi', difficulty: 3 },
  { emojis: '🧹🏠✨', answer: 'L\'ordine e meta della vita', category: 'Proverbi', difficulty: 2 },
  { emojis: '💰🗣️❌', answer: 'I soldi non si discutono', category: 'Proverbi', difficulty: 2 },
  { emojis: '🎯🔨💪', answer: 'La pratica rende perfetti', category: 'Proverbi', difficulty: 1 },
  { emojis: '👀🍲👩‍🍳', answer: 'Troppi cuochi guastano la cucina', category: 'Proverbi', difficulty: 2 },
  { emojis: '🐕🌳🔔', answer: 'Qui giace il nocciolo della questione', category: 'Proverbi', difficulty: 2 },
  { emojis: '🪵👀🌲', answer: 'Non vedere il bosco per gli alberi', category: 'Proverbi', difficulty: 3 },
  { emojis: '🍏🌳⬇️', answer: 'Tale padre tale figlio', category: 'Proverbi', difficulty: 1 },

  // Marchi (26)
  { emojis: '🍎📱💻', answer: 'Apple', category: 'Marchi', difficulty: 1 },
  { emojis: '✔️👟💨', answer: 'Nike', category: 'Marchi', difficulty: 1 },
  { emojis: '🟡🟡🟡🟡🚗', answer: 'Audi', category: 'Marchi', difficulty: 2 },
  { emojis: '👑🍔🍟', answer: 'Burger King', category: 'Marchi', difficulty: 1 },
  { emojis: '🟥🐂🐂', answer: 'Red Bull', category: 'Marchi', difficulty: 1 },
  { emojis: '🎮🕹️🍄', answer: 'Nintendo', category: 'Marchi', difficulty: 2 },
  { emojis: '📦🏠🔜', answer: 'Amazon', category: 'Marchi', difficulty: 1 },
  { emojis: '🔎🌐📊', answer: 'Google', category: 'Marchi', difficulty: 1 },
  { emojis: '🧱🔴🟡🟢', answer: 'Lego', category: 'Marchi', difficulty: 1 },
  { emojis: '⭐🏨☕', answer: 'Starbucks', category: 'Marchi', difficulty: 2 },
  { emojis: '🚗⚡🔋', answer: 'Tesla', category: 'Marchi', difficulty: 1 },
  { emojis: '🐦📱💬', answer: 'Twitter', category: 'Marchi', difficulty: 1 },
  { emojis: '📸🟪🌅', answer: 'Instagram', category: 'Marchi', difficulty: 1 },
  { emojis: '🎵🎧🟢', answer: 'Spotify', category: 'Marchi', difficulty: 1 },
  { emojis: '🐻🧊🍬', answer: 'Haribo', category: 'Marchi', difficulty: 2 },
  { emojis: '🟫🍫🐄', answer: 'Milka', category: 'Marchi', difficulty: 2 },
  { emojis: '🎬🍿❤️', answer: 'Netflix', category: 'Marchi', difficulty: 1 },
  { emojis: '🪑🔧🇸🇪', answer: 'IKEA', category: 'Marchi', difficulty: 1 },
  { emojis: '🏎️🐎🇮🇹', answer: 'Ferrari', category: 'Marchi', difficulty: 1 },
  { emojis: '🎮🍄🔴', answer: 'Nintendo', category: 'Marchi', difficulty: 1 },
  { emojis: '📱💬🟢', answer: 'WhatsApp', category: 'Marchi', difficulty: 1 },
  { emojis: '☕🧜‍♀️🟢', answer: 'Starbucks', category: 'Marchi', difficulty: 1 },
  { emojis: '🏠🔑✈️', answer: 'Airbnb', category: 'Marchi', difficulty: 2 },
  { emojis: '📦📱🛒', answer: 'Amazon', category: 'Marchi', difficulty: 1 },
  { emojis: '🎵🎧📱', answer: 'Spotify', category: 'Marchi', difficulty: 1 },
  { emojis: '🔍📧📺', answer: 'Google', category: 'Marchi', difficulty: 1 },

  // Serie TV (16)
  { emojis: '🧪👨‍🔬💊💰', answer: 'Breaking Bad', category: 'Serie TV', difficulty: 1 },
  { emojis: '👑⚔️🐉', answer: 'Il Trono di Spade', category: 'Serie TV', difficulty: 1 },
  { emojis: '🧟‍♂️🔫🌍', answer: 'The Walking Dead', category: 'Serie TV', difficulty: 1 },
  { emojis: '🔦👦🚲🧇', answer: 'Stranger Things', category: 'Serie TV', difficulty: 1 },
  { emojis: '🏠💵📌', answer: 'La Casa di Carta', category: 'Serie TV', difficulty: 2 },
  { emojis: '👩‍⚕️🏥💉', answer: 'Grey\'s Anatomy', category: 'Serie TV', difficulty: 2 },
  { emojis: '🧑‍🔬🤓🎯🏠', answer: 'The Big Bang Theory', category: 'Serie TV', difficulty: 1 },
  { emojis: '☕👫👫👫', answer: 'Friends', category: 'Serie TV', difficulty: 1 },
  { emojis: '🏢📎😐', answer: 'The Office', category: 'Serie TV', difficulty: 2 },
  { emojis: '🍳👨‍🍳🔪⭐', answer: 'MasterChef', category: 'Serie TV', difficulty: 2 },
  { emojis: '🦑🎮💀', answer: 'Squid Game', category: 'Serie TV', difficulty: 1 },
  { emojis: '🧛‍♂️🩸📖', answer: 'The Vampire Diaries', category: 'Serie TV', difficulty: 2 },
  { emojis: '🏝️✈️🔢', answer: 'Lost', category: 'Serie TV', difficulty: 2 },
  { emojis: '♟️👸🇬🇧', answer: 'La regina degli scacchi', category: 'Serie TV', difficulty: 3 },
  { emojis: '🧑‍🏫🔴🔵', answer: 'La Casa di Carta', category: 'Serie TV', difficulty: 3 },
  { emojis: '🐺🌕🏰', answer: 'Teen Wolf', category: 'Serie TV', difficulty: 2 },

  // Videogiochi (14)
  { emojis: '🍄🟢🏰👸', answer: 'Super Mario', category: 'Videogiochi', difficulty: 1 },
  { emojis: '⛏️🟫🌍🧱', answer: 'Minecraft', category: 'Videogiochi', difficulty: 1 },
  { emojis: '⚽🏟️⚡', answer: 'FIFA', category: 'Videogiochi', difficulty: 1 },
  { emojis: '🔫🎯🏃‍♂️💣', answer: 'Call of Duty', category: 'Videogiochi', difficulty: 2 },
  { emojis: '🏎️🍌🏁🌈', answer: 'Mario Kart', category: 'Videogiochi', difficulty: 1 },
  { emojis: '⚡🟡⚡🐭', answer: 'Pokemon', category: 'Videogiochi', difficulty: 1 },
  { emojis: '🗡️🛡️🧝‍♂️🏰', answer: 'Zelda', category: 'Videogiochi', difficulty: 2 },
  { emojis: '🔵🦔💨💎', answer: 'Sonic', category: 'Videogiochi', difficulty: 1 },
  { emojis: '🏗️🏙️🚗🎮', answer: 'GTA', category: 'Videogiochi', difficulty: 2 },
  { emojis: '🧱🧱🧱📐', answer: 'Tetris', category: 'Videogiochi', difficulty: 1 },
  { emojis: '🐔🔫🪖🏝️', answer: 'Fortnite', category: 'Videogiochi', difficulty: 1 },
  { emojis: '🧙‍♂️📖⚔️🐴', answer: 'The Witcher', category: 'Videogiochi', difficulty: 2 },
  { emojis: '🚀🌌👨‍🚀🔧', answer: 'Among Us', category: 'Videogiochi', difficulty: 2 },
  { emojis: '🐉⚔️🗻🏹', answer: 'Skyrim', category: 'Videogiochi', difficulty: 3 },
];
