import { EmojiPuzzle } from './emoji-content-de';

export const EMOJI_PUZZLES_TR: EmojiPuzzle[] = [
  // Filmler (30)
  { emojis: '🦁👑', answer: 'Aslan Kral', category: 'Filmler', difficulty: 1 },
  { emojis: '🧊🚢💔', answer: 'Titanic', category: 'Filmler', difficulty: 1 },
  { emojis: '🕷️🧑', answer: 'Orumcek Adam', category: 'Filmler', difficulty: 1 },
  { emojis: '⭐🔫🌌', answer: 'Yildiz Savaslari', category: 'Filmler', difficulty: 1 },
  { emojis: '🧙‍♂️💍🌋', answer: 'Yuzuklerin Efendisi', category: 'Filmler', difficulty: 2 },
  { emojis: '🦇🌃🦹', answer: 'Batman', category: 'Filmler', difficulty: 1 },
  { emojis: '🐟🔍', answer: 'Kayip Balik Nemo', category: 'Filmler', difficulty: 1 },
  { emojis: '👻👻👻🔫', answer: 'Hayalet Avcilari', category: 'Filmler', difficulty: 2 },
  { emojis: '🧊❄️👸🎵', answer: 'Karlar Ulkesi', category: 'Filmler', difficulty: 1 },
  { emojis: '🏴‍☠️⚓🗺️', answer: 'Karayip Korsanlari', category: 'Filmler', difficulty: 2 },
  { emojis: '🤖👍🔥', answer: 'Terminatör', category: 'Filmler', difficulty: 2 },
  { emojis: '🧪👨‍🔬💚', answer: 'Hulk', category: 'Filmler', difficulty: 2 },
  { emojis: '🏎️💨🔧', answer: 'Arabalar', category: 'Filmler', difficulty: 1 },
  { emojis: '🐀👨‍🍳🇫🇷', answer: 'Ratatouille', category: 'Filmler', difficulty: 2 },
  { emojis: '🦖🏝️🔬', answer: 'Jurassic Park', category: 'Filmler', difficulty: 1 },
  { emojis: '👽☎️🚲🌕', answer: 'E.T.', category: 'Filmler', difficulty: 2 },
  { emojis: '💀🎃🎄', answer: 'Noel Gecesi Kabusu', category: 'Filmler', difficulty: 3 },
  { emojis: '🐼🥋🏯', answer: 'Kung Fu Panda', category: 'Filmler', difficulty: 1 },
  { emojis: '🧓⬆️🎈🏠', answer: 'Yukari Bak', category: 'Filmler', difficulty: 2 },
  { emojis: '🔵👤👤🌿', answer: 'Avatar', category: 'Filmler', difficulty: 2 },
  { emojis: '🧸🎈🍯', answer: 'Winnie the Pooh', category: 'Filmler', difficulty: 1 },
  { emojis: '🦈🏊‍♂️😱', answer: 'Denizin Disleri', category: 'Filmler', difficulty: 2 },
  { emojis: '🐒🍌👑', answer: 'Tarzan', category: 'Filmler', difficulty: 2 },
  { emojis: '🧪⏰🚗💨', answer: 'Gelecege Donus', category: 'Filmler', difficulty: 2 },
  { emojis: '🎭🌹👻🎵', answer: 'Operadaki Hayalet', category: 'Filmler', difficulty: 3 },
  { emojis: '🧊🦣🐿️', answer: 'Buz Devri', category: 'Filmler', difficulty: 1 },
  { emojis: '🏜️🪱🌍', answer: 'Dune', category: 'Filmler', difficulty: 3 },
  { emojis: '🔫🤠🐴🌵', answer: 'Zincirsiz', category: 'Filmler', difficulty: 3 },
  { emojis: '👩‍🍳🐀🇫🇷⭐', answer: 'Ratatouille', category: 'Filmler', difficulty: 1 },
  { emojis: '🦸‍♀️🏝️⚔️🛡️', answer: 'Wonder Woman', category: 'Filmler', difficulty: 2 },

  // Sarkilar (28)
  { emojis: '🎤💃🕺🇸🇪', answer: 'Dancing Queen', category: 'Sarkilar', difficulty: 2 },
  { emojis: '🌧️☔😢', answer: 'Yagmurda Sarki Soylemek', category: 'Sarkilar', difficulty: 2 },
  { emojis: '🎸🤘😈🛣️', answer: 'Highway to Hell', category: 'Sarkilar', difficulty: 2 },
  { emojis: '💎🌌🎵', answer: 'Diamonds', category: 'Sarkilar', difficulty: 2 },
  { emojis: '🔥🎤👧', answer: 'Girl on Fire', category: 'Sarkilar', difficulty: 2 },
  { emojis: '☀️😊', answer: 'Happy', category: 'Sarkilar', difficulty: 1 },
  { emojis: '🌈🎵☁️', answer: 'Somewhere Over the Rainbow', category: 'Sarkilar', difficulty: 2 },
  { emojis: '👁️🐅', answer: 'Eye of the Tiger', category: 'Sarkilar', difficulty: 1 },
  { emojis: '🦊❓', answer: 'What Does the Fox Say', category: 'Sarkilar', difficulty: 1 },
  { emojis: '💃🍑', answer: 'Shake It Off', category: 'Sarkilar', difficulty: 3 },
  { emojis: '🧱🏗️🎵', answer: 'Another Brick in the Wall', category: 'Sarkilar', difficulty: 3 },
  { emojis: '🔔🎄🎅', answer: 'Jingle Bells', category: 'Sarkilar', difficulty: 1 },
  { emojis: '🌃🎷🗽', answer: 'New York New York', category: 'Sarkilar', difficulty: 2 },
  { emojis: '⏰🕐⏰', answer: 'Time After Time', category: 'Sarkilar', difficulty: 3 },
  { emojis: '🎹🎤🔥👨', answer: 'Piano Man', category: 'Sarkilar', difficulty: 2 },
  { emojis: '🌊🏄🎵', answer: 'Surfin USA', category: 'Sarkilar', difficulty: 2 },
  { emojis: '👩‍🚀🚀🌟', answer: 'Rocket Man', category: 'Sarkilar', difficulty: 2 },
  { emojis: '💛🌻🎵', answer: 'Sunflower', category: 'Sarkilar', difficulty: 2 },
  { emojis: '🎤🎵🌍🙏', answer: 'Imagine', category: 'Sarkilar', difficulty: 2 },
  { emojis: '💜🌧️🎵', answer: 'Purple Rain', category: 'Sarkilar', difficulty: 2 },
  { emojis: '🏠🛣️🎵', answer: 'Take Me Home Country Roads', category: 'Sarkilar', difficulty: 3 },
  { emojis: '👻🎵💀👻', answer: 'Thriller', category: 'Sarkilar', difficulty: 1 },
  { emojis: '🌊🏖️👩‍🦰🎵', answer: 'Ocean Eyes', category: 'Sarkilar', difficulty: 3 },
  { emojis: '💃🎶🇨🇺', answer: 'Havana', category: 'Sarkilar', difficulty: 2 },
  { emojis: '🔔🎅🎄⛄', answer: 'Last Christmas', category: 'Sarkilar', difficulty: 1 },
  { emojis: '🌙✨💤🎵', answer: 'Ay Isigi Sonati', category: 'Sarkilar', difficulty: 3 },
  { emojis: '🚗💨🎵🛣️', answer: 'Drive', category: 'Sarkilar', difficulty: 3 },
  { emojis: '🧡📞🎵', answer: 'Call Me Maybe', category: 'Sarkilar', difficulty: 2 },

  // Atasozleri (18)
  { emojis: '🍎🌳🔽', answer: 'Armut dibine duser', category: 'Atasozleri', difficulty: 1 },
  { emojis: '🐦🖐️🕊️🏠', answer: 'Eldeki bir kus daldaki ikiden iyidir', category: 'Atasozleri', difficulty: 2 },
  { emojis: '⏰💰', answer: 'Vakit nakittir', category: 'Atasozleri', difficulty: 1 },
  { emojis: '🗣️🥈🤫🥇', answer: 'Soz gumus sukut altindir', category: 'Atasozleri', difficulty: 2 },
  { emojis: '🔚👍🔚', answer: 'Sonu iyi biten her sey iyidir', category: 'Atasozleri', difficulty: 1 },
  { emojis: '🐱🏠🐭💃', answer: 'Kedi evden cikinca fareler cirit atar', category: 'Atasozleri', difficulty: 3 },
  { emojis: '🌹🔧⚙️', answer: 'Dikensiz gul olmaz', category: 'Atasozleri', difficulty: 2 },
  { emojis: '🌧️☀️🌈', answer: 'Yagmurdan sonra gunes acar', category: 'Atasozleri', difficulty: 1 },
  { emojis: '🙈🙉🙊', answer: 'Uc maymun', category: 'Atasozleri', difficulty: 1 },
  { emojis: '🪨💧🕰️', answer: 'Damla damla gol olur', category: 'Atasozleri', difficulty: 2 },
  { emojis: '💪🧠📚', answer: 'Bilgi guctur', category: 'Atasozleri', difficulty: 1 },
  { emojis: '🐦🌅🪱', answer: 'Erken kalkan yol alir', category: 'Atasozleri', difficulty: 1 },
  { emojis: '🎯🔨💪', answer: 'Tekrar basarinin anasidir', category: 'Atasozleri', difficulty: 1 },
  { emojis: '👀🍲👩‍🍳', answer: 'Asci cogun corusu karisi olur', category: 'Atasozleri', difficulty: 2 },
  { emojis: '🐔🥚❓', answer: 'Yumurta mi tavuk mu', category: 'Atasozleri', difficulty: 2 },
  { emojis: '🏠🔑❤️', answer: 'Ev is kalp rahatlatir', category: 'Atasozleri', difficulty: 2 },
  { emojis: '❤️💧👁️', answer: 'Gozden irak gonulden irak', category: 'Atasozleri', difficulty: 2 },
  { emojis: '👁️👁️🍽️', answer: 'Goz de yer', category: 'Atasozleri', difficulty: 1 },

  // Markalar (26)
  { emojis: '🍎📱💻', answer: 'Apple', category: 'Markalar', difficulty: 1 },
  { emojis: '✔️👟💨', answer: 'Nike', category: 'Markalar', difficulty: 1 },
  { emojis: '🟡🟡🟡🟡🚗', answer: 'Audi', category: 'Markalar', difficulty: 2 },
  { emojis: '👑🍔🍟', answer: 'Burger King', category: 'Markalar', difficulty: 1 },
  { emojis: '🟥🐂🐂', answer: 'Red Bull', category: 'Markalar', difficulty: 1 },
  { emojis: '🎮🕹️🍄', answer: 'Nintendo', category: 'Markalar', difficulty: 2 },
  { emojis: '📦🏠🔜', answer: 'Amazon', category: 'Markalar', difficulty: 1 },
  { emojis: '🔎🌐📊', answer: 'Google', category: 'Markalar', difficulty: 1 },
  { emojis: '🧱🔴🟡🟢', answer: 'Lego', category: 'Markalar', difficulty: 1 },
  { emojis: '⭐🏨☕', answer: 'Starbucks', category: 'Markalar', difficulty: 2 },
  { emojis: '🚗⚡🔋', answer: 'Tesla', category: 'Markalar', difficulty: 1 },
  { emojis: '🐦📱💬', answer: 'Twitter', category: 'Markalar', difficulty: 1 },
  { emojis: '📸🟪🌅', answer: 'Instagram', category: 'Markalar', difficulty: 1 },
  { emojis: '🎵🎧🟢', answer: 'Spotify', category: 'Markalar', difficulty: 1 },
  { emojis: '🐻🧊🍬', answer: 'Haribo', category: 'Markalar', difficulty: 2 },
  { emojis: '🟫🍫🐄', answer: 'Milka', category: 'Markalar', difficulty: 2 },
  { emojis: '🎬🍿❤️', answer: 'Netflix', category: 'Markalar', difficulty: 1 },
  { emojis: '🪑🔧🇸🇪', answer: 'IKEA', category: 'Markalar', difficulty: 1 },
  { emojis: '🏎️🐎🇮🇹', answer: 'Ferrari', category: 'Markalar', difficulty: 1 },
  { emojis: '📱💬🟢', answer: 'WhatsApp', category: 'Markalar', difficulty: 1 },
  { emojis: '☕🧜‍♀️🟢', answer: 'Starbucks', category: 'Markalar', difficulty: 1 },
  { emojis: '🏠🔑✈️', answer: 'Airbnb', category: 'Markalar', difficulty: 2 },
  { emojis: '📦📱🛒', answer: 'Amazon', category: 'Markalar', difficulty: 1 },
  { emojis: '🎵🎧📱', answer: 'Spotify', category: 'Markalar', difficulty: 1 },
  { emojis: '🔍📧📺', answer: 'Google', category: 'Markalar', difficulty: 1 },
  { emojis: '🎮🍄🔴', answer: 'Nintendo', category: 'Markalar', difficulty: 1 },

  // Diziler (16)
  { emojis: '🧪👨‍🔬💊💰', answer: 'Breaking Bad', category: 'Diziler', difficulty: 1 },
  { emojis: '👑⚔️🐉', answer: 'Taht Oyunlari', category: 'Diziler', difficulty: 1 },
  { emojis: '🧟‍♂️🔫🌍', answer: 'The Walking Dead', category: 'Diziler', difficulty: 1 },
  { emojis: '🔦👦🚲🧇', answer: 'Stranger Things', category: 'Diziler', difficulty: 1 },
  { emojis: '🏠💵📌', answer: 'La Casa de Papel', category: 'Diziler', difficulty: 2 },
  { emojis: '👩‍⚕️🏥💉', answer: 'Greys Anatomy', category: 'Diziler', difficulty: 2 },
  { emojis: '🧑‍🔬🤓🎯🏠', answer: 'The Big Bang Theory', category: 'Diziler', difficulty: 1 },
  { emojis: '☕👫👫👫', answer: 'Friends', category: 'Diziler', difficulty: 1 },
  { emojis: '🏢📎😐', answer: 'The Office', category: 'Diziler', difficulty: 2 },
  { emojis: '🍳👨‍🍳🔪⭐', answer: 'MasterChef', category: 'Diziler', difficulty: 2 },
  { emojis: '🦑🎮💀', answer: 'Squid Game', category: 'Diziler', difficulty: 1 },
  { emojis: '🧛‍♂️🩸📖', answer: 'Vampir Gunlukleri', category: 'Diziler', difficulty: 2 },
  { emojis: '🏝️✈️🔢', answer: 'Lost', category: 'Diziler', difficulty: 2 },
  { emojis: '♟️👸🇬🇧', answer: 'Vezir Gambiti', category: 'Diziler', difficulty: 3 },
  { emojis: '🧑‍🏫🔴🔵', answer: 'La Casa de Papel', category: 'Diziler', difficulty: 3 },
  { emojis: '🐺🌕🏰', answer: 'Teen Wolf', category: 'Diziler', difficulty: 2 },

  // Video Oyunlari (14)
  { emojis: '🍄🟢🏰👸', answer: 'Super Mario', category: 'Video Oyunlari', difficulty: 1 },
  { emojis: '⛏️🟫🌍🧱', answer: 'Minecraft', category: 'Video Oyunlari', difficulty: 1 },
  { emojis: '⚽🏟️⚡', answer: 'FIFA', category: 'Video Oyunlari', difficulty: 1 },
  { emojis: '🔫🎯🏃‍♂️💣', answer: 'Call of Duty', category: 'Video Oyunlari', difficulty: 2 },
  { emojis: '🏎️🍌🏁🌈', answer: 'Mario Kart', category: 'Video Oyunlari', difficulty: 1 },
  { emojis: '⚡🟡⚡🐭', answer: 'Pokemon', category: 'Video Oyunlari', difficulty: 1 },
  { emojis: '🗡️🛡️🧝‍♂️🏰', answer: 'Zelda', category: 'Video Oyunlari', difficulty: 2 },
  { emojis: '🔵🦔💨💎', answer: 'Sonic', category: 'Video Oyunlari', difficulty: 1 },
  { emojis: '🏗️🏙️🚗🎮', answer: 'GTA', category: 'Video Oyunlari', difficulty: 2 },
  { emojis: '🧱🧱🧱📐', answer: 'Tetris', category: 'Video Oyunlari', difficulty: 1 },
  { emojis: '🐔🔫🪖🏝️', answer: 'Fortnite', category: 'Video Oyunlari', difficulty: 1 },
  { emojis: '🧙‍♂️📖⚔️🐴', answer: 'The Witcher', category: 'Video Oyunlari', difficulty: 2 },
  { emojis: '🚀🌌👨‍🚀🔧', answer: 'Among Us', category: 'Video Oyunlari', difficulty: 2 },
  { emojis: '🐉⚔️🗻🏹', answer: 'Skyrim', category: 'Video Oyunlari', difficulty: 3 },
];
