export interface EmojiPuzzle {
  emojis: string;
  answer: string;
  category: string;
  difficulty: 1 | 2 | 3;
}

export const EMOJI_PUZZLES: EmojiPuzzle[] = [
  // Movies (20)
  { emojis: '🦁👑', answer: 'The Lion King', category: 'Movies', difficulty: 1 },
  { emojis: '🧊🚢💔', answer: 'Titanic', category: 'Movies', difficulty: 1 },
  { emojis: '🕷️🧑', answer: 'Spider-Man', category: 'Movies', difficulty: 1 },
  { emojis: '⭐🔫🌌', answer: 'Star Wars', category: 'Movies', difficulty: 1 },
  { emojis: '🧙‍♂️💍🌋', answer: 'Lord of the Rings', category: 'Movies', difficulty: 2 },
  { emojis: '🦇🌃🦹', answer: 'Batman', category: 'Movies', difficulty: 1 },
  { emojis: '🐟🔍', answer: 'Finding Nemo', category: 'Movies', difficulty: 1 },
  { emojis: '👻👻👻🔫', answer: 'Ghostbusters', category: 'Movies', difficulty: 2 },
  { emojis: '🧊❄️👸🎵', answer: 'Frozen', category: 'Movies', difficulty: 1 },
  { emojis: '🏴‍☠️⚓🗺️', answer: 'Pirates of the Caribbean', category: 'Movies', difficulty: 2 },
  { emojis: '🤖👍🔥', answer: 'Terminator', category: 'Movies', difficulty: 2 },
  { emojis: '🧪👨‍🔬💚', answer: 'Hulk', category: 'Movies', difficulty: 2 },
  { emojis: '🏎️💨🔧', answer: 'Cars', category: 'Movies', difficulty: 1 },
  { emojis: '🐀👨‍🍳🇫🇷', answer: 'Ratatouille', category: 'Movies', difficulty: 2 },
  { emojis: '🦖🏝️🔬', answer: 'Jurassic Park', category: 'Movies', difficulty: 1 },
  { emojis: '👽☎️🚲🌕', answer: 'E.T.', category: 'Movies', difficulty: 2 },
  { emojis: '💀🎃🎄', answer: 'Nightmare Before Christmas', category: 'Movies', difficulty: 3 },
  { emojis: '🐼🥋🏯', answer: 'Kung Fu Panda', category: 'Movies', difficulty: 1 },
  { emojis: '🧓⬆️🎈🏠', answer: 'Up', category: 'Movies', difficulty: 2 },
  { emojis: '🔵👤👤🌿', answer: 'Avatar', category: 'Movies', difficulty: 2 },

  // Songs (18)
  { emojis: '🎤💃🕺🇸🇪', answer: 'Dancing Queen', category: 'Songs', difficulty: 2 },
  { emojis: '🌧️☔😢', answer: 'Singin in the Rain', category: 'Songs', difficulty: 2 },
  { emojis: '🎸🤘😈🛣️', answer: 'Highway to Hell', category: 'Songs', difficulty: 2 },
  { emojis: '💎🌌🎵', answer: 'Diamonds', category: 'Songs', difficulty: 2 },
  { emojis: '🔥🎤👧', answer: 'Girl on Fire', category: 'Songs', difficulty: 2 },
  { emojis: '☀️😊', answer: 'Happy', category: 'Songs', difficulty: 1 },
  { emojis: '🌈🎵☁️', answer: 'Somewhere Over the Rainbow', category: 'Songs', difficulty: 2 },
  { emojis: '👁️🐅', answer: 'Eye of the Tiger', category: 'Songs', difficulty: 1 },
  { emojis: '🦊❓', answer: 'What Does the Fox Say', category: 'Songs', difficulty: 1 },
  { emojis: '💃🍑', answer: 'Shake It Off', category: 'Songs', difficulty: 3 },
  { emojis: '🧱🏗️🎵', answer: 'Another Brick in the Wall', category: 'Songs', difficulty: 3 },
  { emojis: '🔔🎄🎅', answer: 'Jingle Bells', category: 'Songs', difficulty: 1 },
  { emojis: '🌃🎷🗽', answer: 'New York New York', category: 'Songs', difficulty: 2 },
  { emojis: '⏰🕐⏰', answer: 'Time After Time', category: 'Songs', difficulty: 3 },
  { emojis: '🎹🎤🔥👨', answer: 'Piano Man', category: 'Songs', difficulty: 2 },
  { emojis: '🌊🏄🎵', answer: 'Surfin USA', category: 'Songs', difficulty: 2 },
  { emojis: '👩‍🚀🚀🌟', answer: 'Rocket Man', category: 'Songs', difficulty: 2 },
  { emojis: '💛🌻🎵', answer: 'Sunflower', category: 'Songs', difficulty: 2 },

  // Sayings (18)
  { emojis: '🍎🌳🔽', answer: 'The apple doesn\'t fall far from the tree', category: 'Sayings', difficulty: 1 },
  { emojis: '🐦🖐️🕊️🏠', answer: 'A bird in the hand is worth two in the bush', category: 'Sayings', difficulty: 2 },
  { emojis: '⏰💰', answer: 'Time is money', category: 'Sayings', difficulty: 1 },
  { emojis: '🗣️🥈🤫🥇', answer: 'Speech is silver silence is golden', category: 'Sayings', difficulty: 2 },
  { emojis: '👁️👁️🍽️', answer: 'You eat with your eyes first', category: 'Sayings', difficulty: 1 },
  { emojis: '🔚👍🔚', answer: 'All is well that ends well', category: 'Sayings', difficulty: 1 },
  { emojis: '❤️💧👁️', answer: 'Out of sight out of mind', category: 'Sayings', difficulty: 2 },
  { emojis: '🐱🏠🐭💃', answer: 'When the cat is away the mice will play', category: 'Sayings', difficulty: 3 },
  { emojis: '🌹🔧⚙️', answer: 'Every rose has its thorn', category: 'Sayings', difficulty: 2 },
  { emojis: '🌧️☀️🌈', answer: 'After the storm comes the sunshine', category: 'Sayings', difficulty: 1 },
  { emojis: '🐕🐕🐕🦴', answer: 'Too many cooks spoil the broth', category: 'Sayings', difficulty: 3 },
  { emojis: '🔑🗝️🔓', answer: 'Practice makes perfect', category: 'Sayings', difficulty: 3 },
  { emojis: '🐔🥚❓', answer: 'Which came first the chicken or the egg', category: 'Sayings', difficulty: 2 },
  { emojis: '🪨💧🕰️', answer: 'Slow and steady wins the race', category: 'Sayings', difficulty: 2 },
  { emojis: '🙈🙉🙊', answer: 'See no evil hear no evil speak no evil', category: 'Sayings', difficulty: 1 },
  { emojis: '🐴🎁🦷', answer: 'Don\'t look a gift horse in the mouth', category: 'Sayings', difficulty: 3 },
  { emojis: '🧹✨🆕', answer: 'A new broom sweeps clean', category: 'Sayings', difficulty: 2 },
  { emojis: '💪🧠📚', answer: 'Knowledge is power', category: 'Sayings', difficulty: 1 },

  // Brands (16)
  { emojis: '🍎📱💻', answer: 'Apple', category: 'Brands', difficulty: 1 },
  { emojis: '✔️👟💨', answer: 'Nike', category: 'Brands', difficulty: 1 },
  { emojis: '🟡🟡🟡🟡🚗', answer: 'Audi', category: 'Brands', difficulty: 2 },
  { emojis: '👑🍔🍟', answer: 'Burger King', category: 'Brands', difficulty: 1 },
  { emojis: '🟥🐂🐂', answer: 'Red Bull', category: 'Brands', difficulty: 1 },
  { emojis: '🎮🕹️🍄', answer: 'Nintendo', category: 'Brands', difficulty: 2 },
  { emojis: '📦🏠🔜', answer: 'Amazon', category: 'Brands', difficulty: 1 },
  { emojis: '🔎🌐📊', answer: 'Google', category: 'Brands', difficulty: 1 },
  { emojis: '🧱🔴🟡🟢', answer: 'Lego', category: 'Brands', difficulty: 1 },
  { emojis: '⭐🏨☕', answer: 'Starbucks', category: 'Brands', difficulty: 2 },
  { emojis: '🚗⚡🔋', answer: 'Tesla', category: 'Brands', difficulty: 1 },
  { emojis: '🐦📱💬', answer: 'Twitter', category: 'Brands', difficulty: 1 },
  { emojis: '📸🟪🌅', answer: 'Instagram', category: 'Brands', difficulty: 1 },
  { emojis: '🎵🎧🟢', answer: 'Spotify', category: 'Brands', difficulty: 1 },
  { emojis: '🐻🧊🍬', answer: 'Haribo', category: 'Brands', difficulty: 2 },
  { emojis: '🟫🍫🐄', answer: 'Milka', category: 'Brands', difficulty: 2 },

  // TV Shows (16)
  { emojis: '🧪👨‍🔬💊💰', answer: 'Breaking Bad', category: 'TV Shows', difficulty: 1 },
  { emojis: '👑⚔️🐉', answer: 'Game of Thrones', category: 'TV Shows', difficulty: 1 },
  { emojis: '🧟‍♂️🔫🌍', answer: 'The Walking Dead', category: 'TV Shows', difficulty: 1 },
  { emojis: '🔦👦🚲🧇', answer: 'Stranger Things', category: 'TV Shows', difficulty: 1 },
  { emojis: '🏠💵📌', answer: 'Money Heist', category: 'TV Shows', difficulty: 2 },
  { emojis: '👩‍⚕️🏥💉', answer: 'Grey\'s Anatomy', category: 'TV Shows', difficulty: 2 },
  { emojis: '🧑‍🔬🤓🎯🏠', answer: 'The Big Bang Theory', category: 'TV Shows', difficulty: 1 },
  { emojis: '☕👫👫👫', answer: 'Friends', category: 'TV Shows', difficulty: 1 },
  { emojis: '🏢📎😐', answer: 'The Office', category: 'TV Shows', difficulty: 2 },
  { emojis: '🍳👨‍🍳🔪⭐', answer: 'MasterChef', category: 'TV Shows', difficulty: 2 },
  { emojis: '🦑🎮💀', answer: 'Squid Game', category: 'TV Shows', difficulty: 1 },
  { emojis: '🧛‍♂️🩸📖', answer: 'Vampire Diaries', category: 'TV Shows', difficulty: 2 },
  { emojis: '🏝️✈️🔢', answer: 'Lost', category: 'TV Shows', difficulty: 2 },
  { emojis: '♟️👸🇬🇧', answer: 'The Queen\'s Gambit', category: 'TV Shows', difficulty: 3 },
  { emojis: '🧑‍🏫🔴🔵', answer: 'Money Heist', category: 'TV Shows', difficulty: 3 },
  { emojis: '🐺🌕🏰', answer: 'Teen Wolf', category: 'TV Shows', difficulty: 2 },

  // Video Games (14)
  { emojis: '🍄🟢🏰👸', answer: 'Super Mario', category: 'Video Games', difficulty: 1 },
  { emojis: '⛏️🟫🌍🧱', answer: 'Minecraft', category: 'Video Games', difficulty: 1 },
  { emojis: '⚽🏟️⚡', answer: 'FIFA', category: 'Video Games', difficulty: 1 },
  { emojis: '🔫🎯🏃‍♂️💣', answer: 'Call of Duty', category: 'Video Games', difficulty: 2 },
  { emojis: '🏎️🍌🏁🌈', answer: 'Mario Kart', category: 'Video Games', difficulty: 1 },
  { emojis: '⚡🟡⚡🐭', answer: 'Pokemon', category: 'Video Games', difficulty: 1 },
  { emojis: '🗡️🛡️🧝‍♂️🏰', answer: 'Zelda', category: 'Video Games', difficulty: 2 },
  { emojis: '🔵🦔💨💎', answer: 'Sonic', category: 'Video Games', difficulty: 1 },
  { emojis: '🏗️🏙️🚗🎮', answer: 'GTA', category: 'Video Games', difficulty: 2 },
  { emojis: '🧱🧱🧱📐', answer: 'Tetris', category: 'Video Games', difficulty: 1 },
  { emojis: '🐔🔫🪖🏝️', answer: 'Fortnite', category: 'Video Games', difficulty: 1 },
  { emojis: '🧙‍♂️📖⚔️🐴', answer: 'The Witcher', category: 'Video Games', difficulty: 2 },
  { emojis: '🚀🌌👨‍🚀🔧', answer: 'Among Us', category: 'Video Games', difficulty: 2 },
  { emojis: '🐉⚔️🗻🏹', answer: 'Skyrim', category: 'Video Games', difficulty: 3 },

  // New Movies (10)
  { emojis: '🧸🎈🍯', answer: 'Winnie the Pooh', category: 'Movies', difficulty: 1 },
  { emojis: '🦈🏊‍♂️😱', answer: 'Jaws', category: 'Movies', difficulty: 2 },
  { emojis: '🐒🍌👑', answer: 'Tarzan', category: 'Movies', difficulty: 2 },
  { emojis: '🧪⏰🚗💨', answer: 'Back to the Future', category: 'Movies', difficulty: 2 },
  { emojis: '🎭🌹👻🎵', answer: 'Phantom of the Opera', category: 'Movies', difficulty: 3 },
  { emojis: '🧊🦣🐿️', answer: 'Ice Age', category: 'Movies', difficulty: 1 },
  { emojis: '🏜️🪱🌍', answer: 'Dune', category: 'Movies', difficulty: 3 },
  { emojis: '🔫🤠🐴🌵', answer: 'Django Unchained', category: 'Movies', difficulty: 3 },
  { emojis: '👩‍🍳🐀🇫🇷⭐', answer: 'Ratatouille', category: 'Movies', difficulty: 1 },
  { emojis: '🦸‍♀️🏝️⚔️🛡️', answer: 'Wonder Woman', category: 'Movies', difficulty: 2 },

  // New Songs (10)
  { emojis: '🎤🎵🌍🙏', answer: 'Imagine', category: 'Songs', difficulty: 2 },
  { emojis: '💜🌧️🎵', answer: 'Purple Rain', category: 'Songs', difficulty: 2 },
  { emojis: '🏠🛣️🎵', answer: 'Take Me Home Country Roads', category: 'Songs', difficulty: 3 },
  { emojis: '👻🎵💀👻', answer: 'Thriller', category: 'Songs', difficulty: 1 },
  { emojis: '🌊🏖️👩‍🦰🎵', answer: 'Ocean Eyes', category: 'Songs', difficulty: 3 },
  { emojis: '💃🎶🇨🇺', answer: 'Havana', category: 'Songs', difficulty: 2 },
  { emojis: '🔔🎅🎄⛄', answer: 'Last Christmas', category: 'Songs', difficulty: 1 },
  { emojis: '🌙✨💤🎵', answer: 'Moonlight Sonata', category: 'Songs', difficulty: 3 },
  { emojis: '🚗💨🎵🛣️', answer: 'Drive', category: 'Songs', difficulty: 3 },
  { emojis: '🧡📞🎵', answer: 'Call Me Maybe', category: 'Songs', difficulty: 2 },

  // New Sayings (10)
  { emojis: '🐦🌅🪱', answer: 'The early bird catches the worm', category: 'Sayings', difficulty: 1 },
  { emojis: '🏠🔑❤️', answer: 'Home is where the heart is', category: 'Sayings', difficulty: 2 },
  { emojis: '🍒🍒👫', answer: 'Birds of a feather flock together', category: 'Sayings', difficulty: 3 },
  { emojis: '🐕🌳🔔', answer: 'Let sleeping dogs lie', category: 'Sayings', difficulty: 2 },
  { emojis: '🧹🏠✨', answer: 'Cleanliness is next to godliness', category: 'Sayings', difficulty: 2 },
  { emojis: '💰🗣️❌', answer: 'Money talks', category: 'Sayings', difficulty: 2 },
  { emojis: '🪵👀🌲', answer: 'Can\'t see the forest for the trees', category: 'Sayings', difficulty: 3 },
  { emojis: '🎯🔨💪', answer: 'Practice makes perfect', category: 'Sayings', difficulty: 1 },
  { emojis: '🍏🌳⬇️', answer: 'The apple doesn\'t fall far from the tree', category: 'Sayings', difficulty: 1 },
  { emojis: '👀🍲👩‍🍳', answer: 'Too many cooks spoil the broth', category: 'Sayings', difficulty: 2 },

  // New Brands (10)
  { emojis: '🎬🍿❤️', answer: 'Netflix', category: 'Brands', difficulty: 1 },
  { emojis: '🪑🔧🇸🇪', answer: 'IKEA', category: 'Brands', difficulty: 1 },
  { emojis: '🏎️🐎🇮🇹', answer: 'Ferrari', category: 'Brands', difficulty: 1 },
  { emojis: '🎮🍄🔴', answer: 'Nintendo', category: 'Brands', difficulty: 1 },
  { emojis: '📱💬🟢', answer: 'WhatsApp', category: 'Brands', difficulty: 1 },
  { emojis: '☕🧜‍♀️🟢', answer: 'Starbucks', category: 'Brands', difficulty: 1 },
  { emojis: '🏠🔑✈️', answer: 'Airbnb', category: 'Brands', difficulty: 2 },
  { emojis: '📦📱🛒', answer: 'Amazon', category: 'Brands', difficulty: 1 },
  { emojis: '🎵🎧📱', answer: 'Spotify', category: 'Brands', difficulty: 1 },
  { emojis: '🔍📧📺', answer: 'Google', category: 'Brands', difficulty: 1 },
];
