import { EmojiPuzzle } from './emoji-content-de';

export const EMOJI_PUZZLES_PT: EmojiPuzzle[] = [
  // Filmes (30)
  { emojis: '🦁👑', answer: 'O Rei Leao', category: 'Filmes', difficulty: 1 },
  { emojis: '🧊🚢💔', answer: 'Titanic', category: 'Filmes', difficulty: 1 },
  { emojis: '🕷️🧑', answer: 'Homem-Aranha', category: 'Filmes', difficulty: 1 },
  { emojis: '⭐🔫🌌', answer: 'Guerra nas Estrelas', category: 'Filmes', difficulty: 1 },
  { emojis: '🧙‍♂️💍🌋', answer: 'Senhor dos Aneis', category: 'Filmes', difficulty: 2 },
  { emojis: '🦇🌃🦹', answer: 'Batman', category: 'Filmes', difficulty: 1 },
  { emojis: '🐟🔍', answer: 'Procurando Nemo', category: 'Filmes', difficulty: 1 },
  { emojis: '👻👻👻🔫', answer: 'Cacafantasmas', category: 'Filmes', difficulty: 2 },
  { emojis: '🧊❄️👸🎵', answer: 'Frozen', category: 'Filmes', difficulty: 1 },
  { emojis: '🏴‍☠️⚓🗺️', answer: 'Piratas do Caribe', category: 'Filmes', difficulty: 2 },
  { emojis: '🤖👍🔥', answer: 'O Exterminador', category: 'Filmes', difficulty: 2 },
  { emojis: '🧪👨‍🔬💚', answer: 'Hulk', category: 'Filmes', difficulty: 2 },
  { emojis: '🏎️💨🔧', answer: 'Carros', category: 'Filmes', difficulty: 1 },
  { emojis: '🐀👨‍🍳🇫🇷', answer: 'Ratatouille', category: 'Filmes', difficulty: 2 },
  { emojis: '🦖🏝️🔬', answer: 'Parque dos Dinossauros', category: 'Filmes', difficulty: 1 },
  { emojis: '👽☎️🚲🌕', answer: 'E.T.', category: 'Filmes', difficulty: 2 },
  { emojis: '💀🎃🎄', answer: 'O Estranho Mundo de Jack', category: 'Filmes', difficulty: 3 },
  { emojis: '🐼🥋🏯', answer: 'Kung Fu Panda', category: 'Filmes', difficulty: 1 },
  { emojis: '🧓⬆️🎈🏠', answer: 'Up Altas Aventuras', category: 'Filmes', difficulty: 2 },
  { emojis: '🔵👤👤🌿', answer: 'Avatar', category: 'Filmes', difficulty: 2 },
  { emojis: '🧸🎈🍯', answer: 'Ursinho Pooh', category: 'Filmes', difficulty: 1 },
  { emojis: '🦈🏊‍♂️😱', answer: 'Tubarao', category: 'Filmes', difficulty: 2 },
  { emojis: '🐒🍌👑', answer: 'Tarzan', category: 'Filmes', difficulty: 2 },
  { emojis: '🧪⏰🚗💨', answer: 'De Volta para o Futuro', category: 'Filmes', difficulty: 2 },
  { emojis: '🎭🌹👻🎵', answer: 'O Fantasma da Opera', category: 'Filmes', difficulty: 3 },
  { emojis: '🧊🦣🐿️', answer: 'A Era do Gelo', category: 'Filmes', difficulty: 1 },
  { emojis: '🏜️🪱🌍', answer: 'Duna', category: 'Filmes', difficulty: 3 },
  { emojis: '🔫🤠🐴🌵', answer: 'Django Livre', category: 'Filmes', difficulty: 3 },
  { emojis: '👩‍🍳🐀🇫🇷⭐', answer: 'Ratatouille', category: 'Filmes', difficulty: 1 },
  { emojis: '🦸‍♀️🏝️⚔️🛡️', answer: 'Mulher-Maravilha', category: 'Filmes', difficulty: 2 },

  // Musicas (28)
  { emojis: '🎤💃🕺🇸🇪', answer: 'Dancing Queen', category: 'Musicas', difficulty: 2 },
  { emojis: '🌧️☔😢', answer: 'Cantando na Chuva', category: 'Musicas', difficulty: 2 },
  { emojis: '🎸🤘😈🛣️', answer: 'Highway to Hell', category: 'Musicas', difficulty: 2 },
  { emojis: '💎🌌🎵', answer: 'Diamonds', category: 'Musicas', difficulty: 2 },
  { emojis: '🔥🎤👧', answer: 'Girl on Fire', category: 'Musicas', difficulty: 2 },
  { emojis: '☀️😊', answer: 'Happy', category: 'Musicas', difficulty: 1 },
  { emojis: '🌈🎵☁️', answer: 'Somewhere Over the Rainbow', category: 'Musicas', difficulty: 2 },
  { emojis: '👁️🐅', answer: 'Eye of the Tiger', category: 'Musicas', difficulty: 1 },
  { emojis: '🦊❓', answer: 'What Does the Fox Say', category: 'Musicas', difficulty: 1 },
  { emojis: '💃🍑', answer: 'Shake It Off', category: 'Musicas', difficulty: 3 },
  { emojis: '🧱🏗️🎵', answer: 'Another Brick in the Wall', category: 'Musicas', difficulty: 3 },
  { emojis: '🔔🎄🎅', answer: 'Jingle Bells', category: 'Musicas', difficulty: 1 },
  { emojis: '🌃🎷🗽', answer: 'New York New York', category: 'Musicas', difficulty: 2 },
  { emojis: '⏰🕐⏰', answer: 'Time After Time', category: 'Musicas', difficulty: 3 },
  { emojis: '🎹🎤🔥👨', answer: 'Piano Man', category: 'Musicas', difficulty: 2 },
  { emojis: '🌊🏄🎵', answer: 'Surfin USA', category: 'Musicas', difficulty: 2 },
  { emojis: '👩‍🚀🚀🌟', answer: 'Rocket Man', category: 'Musicas', difficulty: 2 },
  { emojis: '💛🌻🎵', answer: 'Sunflower', category: 'Musicas', difficulty: 2 },
  { emojis: '🎤🎵🌍🙏', answer: 'Imagine', category: 'Musicas', difficulty: 2 },
  { emojis: '💜🌧️🎵', answer: 'Purple Rain', category: 'Musicas', difficulty: 2 },
  { emojis: '🏠🛣️🎵', answer: 'Take Me Home Country Roads', category: 'Musicas', difficulty: 3 },
  { emojis: '👻🎵💀👻', answer: 'Thriller', category: 'Musicas', difficulty: 1 },
  { emojis: '🌊🏖️👩‍🦰🎵', answer: 'Ocean Eyes', category: 'Musicas', difficulty: 3 },
  { emojis: '💃🎶🇨🇺', answer: 'Havana', category: 'Musicas', difficulty: 2 },
  { emojis: '🔔🎅🎄⛄', answer: 'Last Christmas', category: 'Musicas', difficulty: 1 },
  { emojis: '🌙✨💤🎵', answer: 'Sonata ao Luar', category: 'Musicas', difficulty: 3 },
  { emojis: '🚗💨🎵🛣️', answer: 'Drive', category: 'Musicas', difficulty: 3 },
  { emojis: '🧡📞🎵', answer: 'Call Me Maybe', category: 'Musicas', difficulty: 2 },

  // Proverbios (28)
  { emojis: '🍎🌳🔽', answer: 'Tal pai tal filho', category: 'Proverbios', difficulty: 1 },
  { emojis: '🐦🖐️🕊️🏠', answer: 'Mais vale um passaro na mao', category: 'Proverbios', difficulty: 2 },
  { emojis: '⏰💰', answer: 'Tempo e dinheiro', category: 'Proverbios', difficulty: 1 },
  { emojis: '🗣️🥈🤫🥇', answer: 'Quem cala consente', category: 'Proverbios', difficulty: 2 },
  { emojis: '👁️👁️🍽️', answer: 'Comer com os olhos', category: 'Proverbios', difficulty: 1 },
  { emojis: '🔚👍🔚', answer: 'Tudo esta bem quando acaba bem', category: 'Proverbios', difficulty: 1 },
  { emojis: '❤️💧👁️', answer: 'Longe dos olhos longe do coracao', category: 'Proverbios', difficulty: 2 },
  { emojis: '🐱🏠🐭💃', answer: 'Quando o gato sai os ratos fazem festa', category: 'Proverbios', difficulty: 3 },
  { emojis: '🌹🔧⚙️', answer: 'Nao ha rosa sem espinhos', category: 'Proverbios', difficulty: 2 },
  { emojis: '🌧️☀️🌈', answer: 'Depois da tempestade vem a bonanca', category: 'Proverbios', difficulty: 1 },
  { emojis: '🙈🙉🙊', answer: 'Nao ver nao ouvir nao falar', category: 'Proverbios', difficulty: 1 },
  { emojis: '🪨💧🕰️', answer: 'Agua mole em pedra dura tanto bate ate que fura', category: 'Proverbios', difficulty: 2 },
  { emojis: '🐔🥚❓', answer: 'Quem veio primeiro a galinha ou o ovo', category: 'Proverbios', difficulty: 2 },
  { emojis: '💪🧠📚', answer: 'Conhecimento e poder', category: 'Proverbios', difficulty: 1 },
  { emojis: '🐦🌅🪱', answer: 'Deus ajuda quem cedo madruga', category: 'Proverbios', difficulty: 1 },
  { emojis: '🏠🔑❤️', answer: 'Lar e onde esta o coracao', category: 'Proverbios', difficulty: 2 },
  { emojis: '🎯🔨💪', answer: 'A pratica leva a perfeicao', category: 'Proverbios', difficulty: 1 },
  { emojis: '👀🍲👩‍🍳', answer: 'Muitos cozinheiros estragam o caldo', category: 'Proverbios', difficulty: 2 },

  // Marcas (26)
  { emojis: '🍎📱💻', answer: 'Apple', category: 'Marcas', difficulty: 1 },
  { emojis: '✔️👟💨', answer: 'Nike', category: 'Marcas', difficulty: 1 },
  { emojis: '🟡🟡🟡🟡🚗', answer: 'Audi', category: 'Marcas', difficulty: 2 },
  { emojis: '👑🍔🍟', answer: 'Burger King', category: 'Marcas', difficulty: 1 },
  { emojis: '🟥🐂🐂', answer: 'Red Bull', category: 'Marcas', difficulty: 1 },
  { emojis: '🎮🕹️🍄', answer: 'Nintendo', category: 'Marcas', difficulty: 2 },
  { emojis: '📦🏠🔜', answer: 'Amazon', category: 'Marcas', difficulty: 1 },
  { emojis: '🔎🌐📊', answer: 'Google', category: 'Marcas', difficulty: 1 },
  { emojis: '🧱🔴🟡🟢', answer: 'Lego', category: 'Marcas', difficulty: 1 },
  { emojis: '⭐🏨☕', answer: 'Starbucks', category: 'Marcas', difficulty: 2 },
  { emojis: '🚗⚡🔋', answer: 'Tesla', category: 'Marcas', difficulty: 1 },
  { emojis: '🐦📱💬', answer: 'Twitter', category: 'Marcas', difficulty: 1 },
  { emojis: '📸🟪🌅', answer: 'Instagram', category: 'Marcas', difficulty: 1 },
  { emojis: '🎵🎧🟢', answer: 'Spotify', category: 'Marcas', difficulty: 1 },
  { emojis: '🐻🧊🍬', answer: 'Haribo', category: 'Marcas', difficulty: 2 },
  { emojis: '🟫🍫🐄', answer: 'Milka', category: 'Marcas', difficulty: 2 },
  { emojis: '🎬🍿❤️', answer: 'Netflix', category: 'Marcas', difficulty: 1 },
  { emojis: '🪑🔧🇸🇪', answer: 'IKEA', category: 'Marcas', difficulty: 1 },
  { emojis: '🏎️🐎🇮🇹', answer: 'Ferrari', category: 'Marcas', difficulty: 1 },
  { emojis: '📱💬🟢', answer: 'WhatsApp', category: 'Marcas', difficulty: 1 },
  { emojis: '☕🧜‍♀️🟢', answer: 'Starbucks', category: 'Marcas', difficulty: 1 },
  { emojis: '🏠🔑✈️', answer: 'Airbnb', category: 'Marcas', difficulty: 2 },
  { emojis: '📦📱🛒', answer: 'Amazon', category: 'Marcas', difficulty: 1 },
  { emojis: '🎵🎧📱', answer: 'Spotify', category: 'Marcas', difficulty: 1 },
  { emojis: '🔍📧📺', answer: 'Google', category: 'Marcas', difficulty: 1 },
  { emojis: '🎮🍄🔴', answer: 'Nintendo', category: 'Marcas', difficulty: 1 },

  // Series (16)
  { emojis: '🧪👨‍🔬💊💰', answer: 'Breaking Bad', category: 'Series', difficulty: 1 },
  { emojis: '👑⚔️🐉', answer: 'Game of Thrones', category: 'Series', difficulty: 1 },
  { emojis: '🧟‍♂️🔫🌍', answer: 'The Walking Dead', category: 'Series', difficulty: 1 },
  { emojis: '🔦👦🚲🧇', answer: 'Stranger Things', category: 'Series', difficulty: 1 },
  { emojis: '🏠💵📌', answer: 'La Casa de Papel', category: 'Series', difficulty: 2 },
  { emojis: '👩‍⚕️🏥💉', answer: 'Greys Anatomy', category: 'Series', difficulty: 2 },
  { emojis: '🧑‍🔬🤓🎯🏠', answer: 'The Big Bang Theory', category: 'Series', difficulty: 1 },
  { emojis: '☕👫👫👫', answer: 'Friends', category: 'Series', difficulty: 1 },
  { emojis: '🏢📎😐', answer: 'The Office', category: 'Series', difficulty: 2 },
  { emojis: '🍳👨‍🍳🔪⭐', answer: 'MasterChef', category: 'Series', difficulty: 2 },
  { emojis: '🦑🎮💀', answer: 'Round 6', category: 'Series', difficulty: 1 },
  { emojis: '🧛‍♂️🩸📖', answer: 'Diarios do Vampiro', category: 'Series', difficulty: 2 },
  { emojis: '🏝️✈️🔢', answer: 'Lost', category: 'Series', difficulty: 2 },
  { emojis: '♟️👸🇬🇧', answer: 'O Gambito da Rainha', category: 'Series', difficulty: 3 },
  { emojis: '🧑‍🏫🔴🔵', answer: 'La Casa de Papel', category: 'Series', difficulty: 3 },
  { emojis: '🐺🌕🏰', answer: 'Teen Wolf', category: 'Series', difficulty: 2 },

  // Videogames (14)
  { emojis: '🍄🟢🏰👸', answer: 'Super Mario', category: 'Videogames', difficulty: 1 },
  { emojis: '⛏️🟫🌍🧱', answer: 'Minecraft', category: 'Videogames', difficulty: 1 },
  { emojis: '⚽🏟️⚡', answer: 'FIFA', category: 'Videogames', difficulty: 1 },
  { emojis: '🔫🎯🏃‍♂️💣', answer: 'Call of Duty', category: 'Videogames', difficulty: 2 },
  { emojis: '🏎️🍌🏁🌈', answer: 'Mario Kart', category: 'Videogames', difficulty: 1 },
  { emojis: '⚡🟡⚡🐭', answer: 'Pokemon', category: 'Videogames', difficulty: 1 },
  { emojis: '🗡️🛡️🧝‍♂️🏰', answer: 'Zelda', category: 'Videogames', difficulty: 2 },
  { emojis: '🔵🦔💨💎', answer: 'Sonic', category: 'Videogames', difficulty: 1 },
  { emojis: '🏗️🏙️🚗🎮', answer: 'GTA', category: 'Videogames', difficulty: 2 },
  { emojis: '🧱🧱🧱📐', answer: 'Tetris', category: 'Videogames', difficulty: 1 },
  { emojis: '🐔🔫🪖🏝️', answer: 'Fortnite', category: 'Videogames', difficulty: 1 },
  { emojis: '🧙‍♂️📖⚔️🐴', answer: 'The Witcher', category: 'Videogames', difficulty: 2 },
  { emojis: '🚀🌌👨‍🚀🔧', answer: 'Among Us', category: 'Videogames', difficulty: 2 },
  { emojis: '🐉⚔️🗻🏹', answer: 'Skyrim', category: 'Videogames', difficulty: 3 },
];
