export interface EmojiPuzzle {
  emojis: string;
  answer: string;
  category: string;
  difficulty: 1 | 2 | 3;
}

export const EMOJI_PUZZLES_PL: EmojiPuzzle[] = [
  // Filmy (30)
  { emojis: '🦁👑', answer: 'Krol Lew', category: 'Filmy', difficulty: 1 },
  { emojis: '🧊🚢💔', answer: 'Titanic', category: 'Filmy', difficulty: 1 },
  { emojis: '🕷️🧑', answer: 'Spider-Man', category: 'Filmy', difficulty: 1 },
  { emojis: '⭐🔫🌌', answer: 'Gwiezdne Wojny', category: 'Filmy', difficulty: 1 },
  { emojis: '🧙‍♂️💍🌋', answer: 'Wladca Pierscieni', category: 'Filmy', difficulty: 2 },
  { emojis: '🦇🌃🦹', answer: 'Batman', category: 'Filmy', difficulty: 1 },
  { emojis: '🐟🔍', answer: 'Gdzie jest Nemo', category: 'Filmy', difficulty: 1 },
  { emojis: '👻👻👻🔫', answer: 'Pogromcy duchow', category: 'Filmy', difficulty: 2 },
  { emojis: '🧊❄️👸🎵', answer: 'Kraina Lodu', category: 'Filmy', difficulty: 1 },
  { emojis: '🏴‍☠️⚓🗺️', answer: 'Piraci z Karaibow', category: 'Filmy', difficulty: 2 },
  { emojis: '🤖👍🔥', answer: 'Terminator', category: 'Filmy', difficulty: 2 },
  { emojis: '🧪👨‍🔬💚', answer: 'Hulk', category: 'Filmy', difficulty: 2 },
  { emojis: '🏎️💨🔧', answer: 'Auta', category: 'Filmy', difficulty: 1 },
  { emojis: '🐀👨‍🍳🇫🇷', answer: 'Ratatuj', category: 'Filmy', difficulty: 2 },
  { emojis: '🦖🏝️🔬', answer: 'Park Jurajski', category: 'Filmy', difficulty: 1 },
  { emojis: '👽☎️🚲🌕', answer: 'E.T.', category: 'Filmy', difficulty: 2 },
  { emojis: '💀🎃🎄', answer: 'Miasteczko Halloween', category: 'Filmy', difficulty: 3 },
  { emojis: '🐼🥋🏯', answer: 'Kung Fu Panda', category: 'Filmy', difficulty: 1 },
  { emojis: '🧓⬆️🎈🏠', answer: 'Odlot', category: 'Filmy', difficulty: 2 },
  { emojis: '🔵👤👤🌿', answer: 'Avatar', category: 'Filmy', difficulty: 2 },
  { emojis: '🧸🎈🍯', answer: 'Kubus Puchatek', category: 'Filmy', difficulty: 1 },
  { emojis: '🦈🏊‍♂️😱', answer: 'Szczeki', category: 'Filmy', difficulty: 2 },
  { emojis: '🐒🍌👑', answer: 'Tarzan', category: 'Filmy', difficulty: 2 },
  { emojis: '🧪⏰🚗💨', answer: 'Powrot do przyszlosci', category: 'Filmy', difficulty: 2 },
  { emojis: '🎭🌹👻🎵', answer: 'Upiór w Operze', category: 'Filmy', difficulty: 3 },
  { emojis: '🧊🦣🐿️', answer: 'Epoka lodowcowa', category: 'Filmy', difficulty: 1 },
  { emojis: '🏜️🪱🌍', answer: 'Diuna', category: 'Filmy', difficulty: 3 },
  { emojis: '🔫🤠🐴🌵', answer: 'Django', category: 'Filmy', difficulty: 3 },
  { emojis: '👩‍🍳🐀🇫🇷⭐', answer: 'Ratatuj', category: 'Filmy', difficulty: 1 },
  { emojis: '🦸‍♀️🏝️⚔️🛡️', answer: 'Wonder Woman', category: 'Filmy', difficulty: 2 },

  // Piosenki (28)
  { emojis: '🎤💃🕺🇸🇪', answer: 'Dancing Queen', category: 'Piosenki', difficulty: 2 },
  { emojis: '🌧️☔😢', answer: 'Singin\' in the Rain', category: 'Piosenki', difficulty: 2 },
  { emojis: '🎸🤘😈🛣️', answer: 'Highway to Hell', category: 'Piosenki', difficulty: 2 },
  { emojis: '💎🌌🎵', answer: 'Diamonds', category: 'Piosenki', difficulty: 2 },
  { emojis: '🔥🎤👧', answer: 'Girl on Fire', category: 'Piosenki', difficulty: 2 },
  { emojis: '☀️😊', answer: 'Happy', category: 'Piosenki', difficulty: 1 },
  { emojis: '🌈🎵☁️', answer: 'Somewhere Over the Rainbow', category: 'Piosenki', difficulty: 2 },
  { emojis: '👁️🐅', answer: 'Eye of the Tiger', category: 'Piosenki', difficulty: 1 },
  { emojis: '🦊❓', answer: 'What Does the Fox Say', category: 'Piosenki', difficulty: 1 },
  { emojis: '💃🍑', answer: 'Shake It Off', category: 'Piosenki', difficulty: 3 },
  { emojis: '🧱🏗️🎵', answer: 'Another Brick in the Wall', category: 'Piosenki', difficulty: 3 },
  { emojis: '🔔🎄🎅', answer: 'Jingle Bells', category: 'Piosenki', difficulty: 1 },
  { emojis: '🌃🎷🗽', answer: 'New York New York', category: 'Piosenki', difficulty: 2 },
  { emojis: '⏰🕐⏰', answer: 'Time After Time', category: 'Piosenki', difficulty: 3 },
  { emojis: '🎹🎤🔥👨', answer: 'Piano Man', category: 'Piosenki', difficulty: 2 },
  { emojis: '🌊🏄🎵', answer: 'Surfin\' USA', category: 'Piosenki', difficulty: 2 },
  { emojis: '👩‍🚀🚀🌟', answer: 'Rocket Man', category: 'Piosenki', difficulty: 2 },
  { emojis: '💛🌻🎵', answer: 'Sunflower', category: 'Piosenki', difficulty: 2 },
  { emojis: '🎤🎵🌍🙏', answer: 'Imagine', category: 'Piosenki', difficulty: 2 },
  { emojis: '💜🌧️🎵', answer: 'Purple Rain', category: 'Piosenki', difficulty: 2 },
  { emojis: '🏠🛣️🎵', answer: 'Take Me Home Country Roads', category: 'Piosenki', difficulty: 3 },
  { emojis: '👻🎵💀👻', answer: 'Thriller', category: 'Piosenki', difficulty: 1 },
  { emojis: '🌊🏖️👩‍🦰🎵', answer: 'Ocean Eyes', category: 'Piosenki', difficulty: 3 },
  { emojis: '💃🎶🇨🇺', answer: 'Havana', category: 'Piosenki', difficulty: 2 },
  { emojis: '🔔🎅🎄⛄', answer: 'Last Christmas', category: 'Piosenki', difficulty: 1 },
  { emojis: '🌙✨💤🎵', answer: 'Sonata Ksiezycowa', category: 'Piosenki', difficulty: 3 },
  { emojis: '🚗💨🎵🛣️', answer: 'Drive', category: 'Piosenki', difficulty: 3 },
  { emojis: '🧡📞🎵', answer: 'Call Me Maybe', category: 'Piosenki', difficulty: 2 },

  // Przysowia (28)
  { emojis: '🍎🌳🔽', answer: 'Niedaleko pada jablko od jaboni', category: 'Przysowia', difficulty: 1 },
  { emojis: '🐦🖐️🕊️🏠', answer: 'Lepszy wrobel w garci niz golab na dachu', category: 'Przysowia', difficulty: 2 },
  { emojis: '⏰💰', answer: 'Czas to pieniadz', category: 'Przysowia', difficulty: 1 },
  { emojis: '🗣️🥈🤫🥇', answer: 'Mowa jest srebrem milczenie zlotem', category: 'Przysowia', difficulty: 2 },
  { emojis: '👁️👁️🍽️', answer: 'Jemy tez oczami', category: 'Przysowia', difficulty: 1 },
  { emojis: '🔚👍🔚', answer: 'Wszystko dobre co sie dobrze konczy', category: 'Przysowia', difficulty: 1 },
  { emojis: '❤️💧👁️', answer: 'Co z oczu to z serca', category: 'Przysowia', difficulty: 2 },
  { emojis: '🐱🏠🐭💃', answer: 'Gdy kota nie ma myszy harcuja', category: 'Przysowia', difficulty: 3 },
  { emojis: '🌹🔧⚙️', answer: 'Nie ma rozy bez kolcow', category: 'Przysowia', difficulty: 2 },
  { emojis: '🌧️☀️🌈', answer: 'Po deszczu wychodzi slonce', category: 'Przysowia', difficulty: 1 },
  { emojis: '🐕🐕🐕🦴', answer: 'Gdzie kucharek szesc tam nie ma co jesc', category: 'Przysowia', difficulty: 3 },
  { emojis: '🔑🗝️🔓', answer: 'Praktyka czyni mistrza', category: 'Przysowia', difficulty: 3 },
  { emojis: '🐔🥚❓', answer: 'Co bylo pierwsze jajko czy kura', category: 'Przysowia', difficulty: 2 },
  { emojis: '🪨💧🕰️', answer: 'Kropla drazy skale', category: 'Przysowia', difficulty: 2 },
  { emojis: '🙈🙉🙊', answer: 'Nie widze nie slysze nie mowie', category: 'Przysowia', difficulty: 1 },
  { emojis: '🐴🎁🦷', answer: 'Darowanemu koniowi nie zaglada sie w zeby', category: 'Przysowia', difficulty: 3 },
  { emojis: '🧹✨🆕', answer: 'Nowa miotla dobrze zamiata', category: 'Przysowia', difficulty: 2 },
  { emojis: '💪🧠📚', answer: 'Wiedza to potega', category: 'Przysowia', difficulty: 1 },
  { emojis: '🐦🌅🪱', answer: 'Kto rano wstaje temu Pan Bog daje', category: 'Przysowia', difficulty: 1 },
  { emojis: '🏠🔑❤️', answer: 'Wszedzie dobrze ale w domu najlepiej', category: 'Przysowia', difficulty: 2 },
  { emojis: '🍒🍒👫', answer: 'Ciagnie swoj do swego', category: 'Przysowia', difficulty: 3 },
  { emojis: '🧹🏠✨', answer: 'Porzadek to polowa zycia', category: 'Przysowia', difficulty: 2 },
  { emojis: '💰🗣️❌', answer: 'O pieniadzach sie nie rozmawia', category: 'Przysowia', difficulty: 2 },
  { emojis: '🎯🔨💪', answer: 'Cwiczenie czyni mistrza', category: 'Przysowia', difficulty: 1 },
  { emojis: '👀🍲👩‍🍳', answer: 'Gdzie kucharek szesc tam nie ma co jesc', category: 'Przysowia', difficulty: 2 },
  { emojis: '🐕🌳🔔', answer: 'Tu lezy pies pogrzebany', category: 'Przysowia', difficulty: 2 },
  { emojis: '🪵👀🌲', answer: 'Nie widziec lasu za drzewami', category: 'Przysowia', difficulty: 3 },
  { emojis: '🍏🌳⬇️', answer: 'Jaki ojciec taki syn', category: 'Przysowia', difficulty: 1 },

  // Marki (26)
  { emojis: '🍎📱💻', answer: 'Apple', category: 'Marki', difficulty: 1 },
  { emojis: '✔️👟💨', answer: 'Nike', category: 'Marki', difficulty: 1 },
  { emojis: '🟡🟡🟡🟡🚗', answer: 'Audi', category: 'Marki', difficulty: 2 },
  { emojis: '👑🍔🍟', answer: 'Burger King', category: 'Marki', difficulty: 1 },
  { emojis: '🟥🐂🐂', answer: 'Red Bull', category: 'Marki', difficulty: 1 },
  { emojis: '🎮🕹️🍄', answer: 'Nintendo', category: 'Marki', difficulty: 2 },
  { emojis: '📦🏠🔜', answer: 'Amazon', category: 'Marki', difficulty: 1 },
  { emojis: '🔎🌐📊', answer: 'Google', category: 'Marki', difficulty: 1 },
  { emojis: '🧱🔴🟡🟢', answer: 'Lego', category: 'Marki', difficulty: 1 },
  { emojis: '⭐🏨☕', answer: 'Starbucks', category: 'Marki', difficulty: 2 },
  { emojis: '🚗⚡🔋', answer: 'Tesla', category: 'Marki', difficulty: 1 },
  { emojis: '🐦📱💬', answer: 'Twitter', category: 'Marki', difficulty: 1 },
  { emojis: '📸🟪🌅', answer: 'Instagram', category: 'Marki', difficulty: 1 },
  { emojis: '🎵🎧🟢', answer: 'Spotify', category: 'Marki', difficulty: 1 },
  { emojis: '🐻🧊🍬', answer: 'Haribo', category: 'Marki', difficulty: 2 },
  { emojis: '🟫🍫🐄', answer: 'Milka', category: 'Marki', difficulty: 2 },
  { emojis: '🎬🍿❤️', answer: 'Netflix', category: 'Marki', difficulty: 1 },
  { emojis: '🪑🔧🇸🇪', answer: 'IKEA', category: 'Marki', difficulty: 1 },
  { emojis: '🏎️🐎🇮🇹', answer: 'Ferrari', category: 'Marki', difficulty: 1 },
  { emojis: '🎮🍄🔴', answer: 'Nintendo', category: 'Marki', difficulty: 1 },
  { emojis: '📱💬🟢', answer: 'WhatsApp', category: 'Marki', difficulty: 1 },
  { emojis: '☕🧜‍♀️🟢', answer: 'Starbucks', category: 'Marki', difficulty: 1 },
  { emojis: '🏠🔑✈️', answer: 'Airbnb', category: 'Marki', difficulty: 2 },
  { emojis: '📦📱🛒', answer: 'Amazon', category: 'Marki', difficulty: 1 },
  { emojis: '🎵🎧📱', answer: 'Spotify', category: 'Marki', difficulty: 1 },
  { emojis: '🔍📧📺', answer: 'Google', category: 'Marki', difficulty: 1 },

  // Seriale (16)
  { emojis: '🧪👨‍🔬💊💰', answer: 'Breaking Bad', category: 'Seriale', difficulty: 1 },
  { emojis: '👑⚔️🐉', answer: 'Gra o Tron', category: 'Seriale', difficulty: 1 },
  { emojis: '🧟‍♂️🔫🌍', answer: 'The Walking Dead', category: 'Seriale', difficulty: 1 },
  { emojis: '🔦👦🚲🧇', answer: 'Stranger Things', category: 'Seriale', difficulty: 1 },
  { emojis: '🏠💵📌', answer: 'Dom z papieru', category: 'Seriale', difficulty: 2 },
  { emojis: '👩‍⚕️🏥💉', answer: 'Chirurdzy', category: 'Seriale', difficulty: 2 },
  { emojis: '🧑‍🔬🤓🎯🏠', answer: 'Teoria wielkiego podrywu', category: 'Seriale', difficulty: 1 },
  { emojis: '☕👫👫👫', answer: 'Przyjaciele', category: 'Seriale', difficulty: 1 },
  { emojis: '🏢📎😐', answer: 'The Office', category: 'Seriale', difficulty: 2 },
  { emojis: '🍳👨‍🍳🔪⭐', answer: 'MasterChef', category: 'Seriale', difficulty: 2 },
  { emojis: '🦑🎮💀', answer: 'Squid Game', category: 'Seriale', difficulty: 1 },
  { emojis: '🧛‍♂️🩸📖', answer: 'Pamietniki wampirow', category: 'Seriale', difficulty: 2 },
  { emojis: '🏝️✈️🔢', answer: 'Zagubieni', category: 'Seriale', difficulty: 2 },
  { emojis: '♟️👸🇬🇧', answer: 'Gambit krolowej', category: 'Seriale', difficulty: 3 },
  { emojis: '🧑‍🏫🔴🔵', answer: 'Dom z papieru', category: 'Seriale', difficulty: 3 },
  { emojis: '🐺🌕🏰', answer: 'Teen Wolf', category: 'Seriale', difficulty: 2 },

  // Gry wideo (14)
  { emojis: '🍄🟢🏰👸', answer: 'Super Mario', category: 'Gry wideo', difficulty: 1 },
  { emojis: '⛏️🟫🌍🧱', answer: 'Minecraft', category: 'Gry wideo', difficulty: 1 },
  { emojis: '⚽🏟️⚡', answer: 'FIFA', category: 'Gry wideo', difficulty: 1 },
  { emojis: '🔫🎯🏃‍♂️💣', answer: 'Call of Duty', category: 'Gry wideo', difficulty: 2 },
  { emojis: '🏎️🍌🏁🌈', answer: 'Mario Kart', category: 'Gry wideo', difficulty: 1 },
  { emojis: '⚡🟡⚡🐭', answer: 'Pokemon', category: 'Gry wideo', difficulty: 1 },
  { emojis: '🗡️🛡️🧝‍♂️🏰', answer: 'Zelda', category: 'Gry wideo', difficulty: 2 },
  { emojis: '🔵🦔💨💎', answer: 'Sonic', category: 'Gry wideo', difficulty: 1 },
  { emojis: '🏗️🏙️🚗🎮', answer: 'GTA', category: 'Gry wideo', difficulty: 2 },
  { emojis: '🧱🧱🧱📐', answer: 'Tetris', category: 'Gry wideo', difficulty: 1 },
  { emojis: '🐔🔫🪖🏝️', answer: 'Fortnite', category: 'Gry wideo', difficulty: 1 },
  { emojis: '🧙‍♂️📖⚔️🐴', answer: 'Wiedzmin', category: 'Gry wideo', difficulty: 2 },
  { emojis: '🚀🌌👨‍🚀🔧', answer: 'Among Us', category: 'Gry wideo', difficulty: 2 },
  { emojis: '🐉⚔️🗻🏹', answer: 'Skyrim', category: 'Gry wideo', difficulty: 3 },
];
