import { EmojiPuzzle } from './emoji-content-de';

export const EMOJI_PUZZLES_AR: EmojiPuzzle[] = [
  // أفلام (30)
  { emojis: '🦁👑', answer: 'الأسد الملك', category: 'أفلام', difficulty: 1 },
  { emojis: '🧊🚢💔', answer: 'تايتنك', category: 'أفلام', difficulty: 1 },
  { emojis: '🕷️🧑', answer: 'الرجل العنكبوت', category: 'أفلام', difficulty: 1 },
  { emojis: '⭐🔫🌌', answer: 'حرب النجوم', category: 'أفلام', difficulty: 1 },
  { emojis: '🧙‍♂️💍🌋', answer: 'سيد الخواتم', category: 'أفلام', difficulty: 2 },
  { emojis: '🦇🌃🦹', answer: 'باتمان', category: 'أفلام', difficulty: 1 },
  { emojis: '🐟🔍', answer: 'البحث عن نيمو', category: 'أفلام', difficulty: 1 },
  { emojis: '👻👻👻🔫', answer: 'صائدو الأشباح', category: 'أفلام', difficulty: 2 },
  { emojis: '🧊❄️👸🎵', answer: 'ملكة الثلج', category: 'أفلام', difficulty: 1 },
  { emojis: '🏴‍☠️⚓🗺️', answer: 'قراصنة الكاريبي', category: 'أفلام', difficulty: 2 },
  { emojis: '🤖👍🔥', answer: 'المدمر', category: 'أفلام', difficulty: 2 },
  { emojis: '🧪👨‍🔬💚', answer: 'هالك', category: 'أفلام', difficulty: 2 },
  { emojis: '🏎️💨🔧', answer: 'سيارات', category: 'أفلام', difficulty: 1 },
  { emojis: '🐀👨‍🍳🇫🇷', answer: 'راتاتوي', category: 'أفلام', difficulty: 2 },
  { emojis: '🦖🏝️🔬', answer: 'الحديقة الجوراسية', category: 'أفلام', difficulty: 1 },
  { emojis: '👽☎️🚲🌕', answer: 'إي تي', category: 'أفلام', difficulty: 2 },
  { emojis: '💀🎃🎄', answer: 'كابوس قبل عيد الميلاد', category: 'أفلام', difficulty: 3 },
  { emojis: '🐼🥋🏯', answer: 'كونغ فو باندا', category: 'أفلام', difficulty: 1 },
  { emojis: '🧓⬆️🎈🏠', answer: 'فوق', category: 'أفلام', difficulty: 2 },
  { emojis: '🔵👤👤🌿', answer: 'أفاتار', category: 'أفلام', difficulty: 2 },
  { emojis: '🧸🎈🍯', answer: 'ويني الدبدوب', category: 'أفلام', difficulty: 1 },
  { emojis: '🦈🏊‍♂️😱', answer: 'الفك المفترس', category: 'أفلام', difficulty: 2 },
  { emojis: '🐒🍌👑', answer: 'طرزان', category: 'أفلام', difficulty: 2 },
  { emojis: '🧪⏰🚗💨', answer: 'العودة إلى المستقبل', category: 'أفلام', difficulty: 2 },
  { emojis: '🎭🌹👻🎵', answer: 'شبح الأوبرا', category: 'أفلام', difficulty: 3 },
  { emojis: '🧊🦣🐿️', answer: 'العصر الجليدي', category: 'أفلام', difficulty: 1 },
  { emojis: '🏜️🪱🌍', answer: 'كثيب', category: 'أفلام', difficulty: 3 },
  { emojis: '🔫🤠🐴🌵', answer: 'جانغو طليقا', category: 'أفلام', difficulty: 3 },
  { emojis: '👩‍🍳🐀🇫🇷⭐', answer: 'راتاتوي', category: 'أفلام', difficulty: 1 },
  { emojis: '🦸‍♀️🏝️⚔️🛡️', answer: 'ووندر وومان', category: 'أفلام', difficulty: 2 },

  // أغاني (28)
  { emojis: '🎤💃🕺🇸🇪', answer: 'Dancing Queen', category: 'أغاني', difficulty: 2 },
  { emojis: '🌧️☔😢', answer: 'الغناء تحت المطر', category: 'أغاني', difficulty: 2 },
  { emojis: '🎸🤘😈🛣️', answer: 'Highway to Hell', category: 'أغاني', difficulty: 2 },
  { emojis: '💎🌌🎵', answer: 'Diamonds', category: 'أغاني', difficulty: 2 },
  { emojis: '🔥🎤👧', answer: 'Girl on Fire', category: 'أغاني', difficulty: 2 },
  { emojis: '☀️😊', answer: 'Happy', category: 'أغاني', difficulty: 1 },
  { emojis: '🌈🎵☁️', answer: 'Somewhere Over the Rainbow', category: 'أغاني', difficulty: 2 },
  { emojis: '👁️🐅', answer: 'Eye of the Tiger', category: 'أغاني', difficulty: 1 },
  { emojis: '🦊❓', answer: 'What Does the Fox Say', category: 'أغاني', difficulty: 1 },
  { emojis: '💃🍑', answer: 'Shake It Off', category: 'أغاني', difficulty: 3 },
  { emojis: '🧱🏗️🎵', answer: 'Another Brick in the Wall', category: 'أغاني', difficulty: 3 },
  { emojis: '🔔🎄🎅', answer: 'Jingle Bells', category: 'أغاني', difficulty: 1 },
  { emojis: '🌃🎷🗽', answer: 'New York New York', category: 'أغاني', difficulty: 2 },
  { emojis: '⏰🕐⏰', answer: 'Time After Time', category: 'أغاني', difficulty: 3 },
  { emojis: '🎹🎤🔥👨', answer: 'Piano Man', category: 'أغاني', difficulty: 2 },
  { emojis: '🌊🏄🎵', answer: 'Surfin USA', category: 'أغاني', difficulty: 2 },
  { emojis: '👩‍🚀🚀🌟', answer: 'Rocket Man', category: 'أغاني', difficulty: 2 },
  { emojis: '💛🌻🎵', answer: 'Sunflower', category: 'أغاني', difficulty: 2 },
  { emojis: '🎤🎵🌍🙏', answer: 'Imagine', category: 'أغاني', difficulty: 2 },
  { emojis: '💜🌧️🎵', answer: 'Purple Rain', category: 'أغاني', difficulty: 2 },
  { emojis: '🏠🛣️🎵', answer: 'Take Me Home Country Roads', category: 'أغاني', difficulty: 3 },
  { emojis: '👻🎵💀👻', answer: 'Thriller', category: 'أغاني', difficulty: 1 },
  { emojis: '🌊🏖️👩‍🦰🎵', answer: 'Ocean Eyes', category: 'أغاني', difficulty: 3 },
  { emojis: '💃🎶🇨🇺', answer: 'Havana', category: 'أغاني', difficulty: 2 },
  { emojis: '🔔🎅🎄⛄', answer: 'Last Christmas', category: 'أغاني', difficulty: 1 },
  { emojis: '🌙✨💤🎵', answer: 'سوناتا ضوء القمر', category: 'أغاني', difficulty: 3 },
  { emojis: '🚗💨🎵🛣️', answer: 'Drive', category: 'أغاني', difficulty: 3 },
  { emojis: '🧡📞🎵', answer: 'Call Me Maybe', category: 'أغاني', difficulty: 2 },

  // أمثال (18)
  { emojis: '🍎🌳🔽', answer: 'التفاحة لا تسقط بعيدا عن الشجرة', category: 'أمثال', difficulty: 1 },
  { emojis: '🐦🖐️🕊️🏠', answer: 'عصفور في اليد خير من عشرة على الشجرة', category: 'أمثال', difficulty: 2 },
  { emojis: '⏰💰', answer: 'الوقت من ذهب', category: 'أمثال', difficulty: 1 },
  { emojis: '🗣️🥈🤫🥇', answer: 'إذا كان الكلام من فضة فالسكوت من ذهب', category: 'أمثال', difficulty: 2 },
  { emojis: '🔚👍🔚', answer: 'كل شيء ينتهي بخير فهو خير', category: 'أمثال', difficulty: 1 },
  { emojis: '🐱🏠🐭💃', answer: 'إذا غاب القط لعب الفأر', category: 'أمثال', difficulty: 3 },
  { emojis: '🌹🔧⚙️', answer: 'لا وردة بلا أشواك', category: 'أمثال', difficulty: 2 },
  { emojis: '🌧️☀️🌈', answer: 'بعد العسر يسر', category: 'أمثال', difficulty: 1 },
  { emojis: '🙈🙉🙊', answer: 'لا أرى لا أسمع لا أتكلم', category: 'أمثال', difficulty: 1 },
  { emojis: '🪨💧🕰️', answer: 'القطرة تثقب الصخرة', category: 'أمثال', difficulty: 2 },
  { emojis: '💪🧠📚', answer: 'العلم قوة', category: 'أمثال', difficulty: 1 },
  { emojis: '🐦🌅🪱', answer: 'من جد وجد', category: 'أمثال', difficulty: 1 },
  { emojis: '🎯🔨💪', answer: 'التكرار يعلم الحمار', category: 'أمثال', difficulty: 1 },
  { emojis: '👀🍲👩‍🍳', answer: 'كثرة الطباخين تفسد الطبخة', category: 'أمثال', difficulty: 2 },
  { emojis: '🐔🥚❓', answer: 'من جاء أولا الدجاجة أم البيضة', category: 'أمثال', difficulty: 2 },
  { emojis: '🏠🔑❤️', answer: 'البيت حيث القلب', category: 'أمثال', difficulty: 2 },
  { emojis: '❤️💧👁️', answer: 'بعيد عن العين بعيد عن القلب', category: 'أمثال', difficulty: 2 },
  { emojis: '👁️👁️🍽️', answer: 'العين تأكل قبل الفم', category: 'أمثال', difficulty: 1 },

  // علامات تجارية (26)
  { emojis: '🍎📱💻', answer: 'آبل', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '✔️👟💨', answer: 'نايكي', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🟡🟡🟡🟡🚗', answer: 'أودي', category: 'علامات تجارية', difficulty: 2 },
  { emojis: '👑🍔🍟', answer: 'برغر كينغ', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🟥🐂🐂', answer: 'ريد بول', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🎮🕹️🍄', answer: 'نينتندو', category: 'علامات تجارية', difficulty: 2 },
  { emojis: '📦🏠🔜', answer: 'أمازون', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🔎🌐📊', answer: 'غوغل', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🧱🔴🟡🟢', answer: 'ليغو', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '⭐🏨☕', answer: 'ستاربكس', category: 'علامات تجارية', difficulty: 2 },
  { emojis: '🚗⚡🔋', answer: 'تسلا', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🐦📱💬', answer: 'تويتر', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '📸🟪🌅', answer: 'إنستغرام', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🎵🎧🟢', answer: 'سبوتيفاي', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🐻🧊🍬', answer: 'هاريبو', category: 'علامات تجارية', difficulty: 2 },
  { emojis: '🟫🍫🐄', answer: 'ميلكا', category: 'علامات تجارية', difficulty: 2 },
  { emojis: '🎬🍿❤️', answer: 'نتفليكس', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🪑🔧🇸🇪', answer: 'إيكيا', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🏎️🐎🇮🇹', answer: 'فيراري', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '📱💬🟢', answer: 'واتساب', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '☕🧜‍♀️🟢', answer: 'ستاربكس', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🏠🔑✈️', answer: 'إير بي إن بي', category: 'علامات تجارية', difficulty: 2 },
  { emojis: '📦📱🛒', answer: 'أمازون', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🎵🎧📱', answer: 'سبوتيفاي', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🔍📧📺', answer: 'غوغل', category: 'علامات تجارية', difficulty: 1 },
  { emojis: '🎮🍄🔴', answer: 'نينتندو', category: 'علامات تجارية', difficulty: 1 },

  // مسلسلات (16)
  { emojis: '🧪👨‍🔬💊💰', answer: 'بريكنغ باد', category: 'مسلسلات', difficulty: 1 },
  { emojis: '👑⚔️🐉', answer: 'صراع العروش', category: 'مسلسلات', difficulty: 1 },
  { emojis: '🧟‍♂️🔫🌍', answer: 'الموتى السائرون', category: 'مسلسلات', difficulty: 1 },
  { emojis: '🔦👦🚲🧇', answer: 'أشياء غريبة', category: 'مسلسلات', difficulty: 1 },
  { emojis: '🏠💵📌', answer: 'لا كاسا دي بابيل', category: 'مسلسلات', difficulty: 2 },
  { emojis: '👩‍⚕️🏥💉', answer: 'غريز أناتومي', category: 'مسلسلات', difficulty: 2 },
  { emojis: '🧑‍🔬🤓🎯🏠', answer: 'نظرية الانفجار العظيم', category: 'مسلسلات', difficulty: 1 },
  { emojis: '☕👫👫👫', answer: 'فريندز', category: 'مسلسلات', difficulty: 1 },
  { emojis: '🏢📎😐', answer: 'المكتب', category: 'مسلسلات', difficulty: 2 },
  { emojis: '🍳👨‍🍳🔪⭐', answer: 'ماستر شيف', category: 'مسلسلات', difficulty: 2 },
  { emojis: '🦑🎮💀', answer: 'لعبة الحبار', category: 'مسلسلات', difficulty: 1 },
  { emojis: '🧛‍♂️🩸📖', answer: 'يوميات مصاص الدماء', category: 'مسلسلات', difficulty: 2 },
  { emojis: '🏝️✈️🔢', answer: 'لوست', category: 'مسلسلات', difficulty: 2 },
  { emojis: '♟️👸🇬🇧', answer: 'مناورة الملكة', category: 'مسلسلات', difficulty: 3 },
  { emojis: '🧑‍🏫🔴🔵', answer: 'لا كاسا دي بابيل', category: 'مسلسلات', difficulty: 3 },
  { emojis: '🐺🌕🏰', answer: 'تين وولف', category: 'مسلسلات', difficulty: 2 },

  // ألعاب فيديو (14)
  { emojis: '🍄🟢🏰👸', answer: 'سوبر ماريو', category: 'ألعاب فيديو', difficulty: 1 },
  { emojis: '⛏️🟫🌍🧱', answer: 'ماينكرافت', category: 'ألعاب فيديو', difficulty: 1 },
  { emojis: '⚽🏟️⚡', answer: 'فيفا', category: 'ألعاب فيديو', difficulty: 1 },
  { emojis: '🔫🎯🏃‍♂️💣', answer: 'كول أوف ديوتي', category: 'ألعاب فيديو', difficulty: 2 },
  { emojis: '🏎️🍌🏁🌈', answer: 'ماريو كارت', category: 'ألعاب فيديو', difficulty: 1 },
  { emojis: '⚡🟡⚡🐭', answer: 'بوكيمون', category: 'ألعاب فيديو', difficulty: 1 },
  { emojis: '🗡️🛡️🧝‍♂️🏰', answer: 'زيلدا', category: 'ألعاب فيديو', difficulty: 2 },
  { emojis: '🔵🦔💨💎', answer: 'سونيك', category: 'ألعاب فيديو', difficulty: 1 },
  { emojis: '🏗️🏙️🚗🎮', answer: 'جي تي إيه', category: 'ألعاب فيديو', difficulty: 2 },
  { emojis: '🧱🧱🧱📐', answer: 'تتريس', category: 'ألعاب فيديو', difficulty: 1 },
  { emojis: '🐔🔫🪖🏝️', answer: 'فورتنايت', category: 'ألعاب فيديو', difficulty: 1 },
  { emojis: '🧙‍♂️📖⚔️🐴', answer: 'الويتشر', category: 'ألعاب فيديو', difficulty: 2 },
  { emojis: '🚀🌌👨‍🚀🔧', answer: 'أمونغ أس', category: 'ألعاب فيديو', difficulty: 2 },
  { emojis: '🐉⚔️🗻🏹', answer: 'سكايريم', category: 'ألعاب فيديو', difficulty: 3 },
];
