export interface EmojiPuzzle {
  emojis: string;
  answer: string;
  category: string;
  difficulty: 1 | 2 | 3;
}

export const EMOJI_PUZZLES_NL: EmojiPuzzle[] = [
  // Films (30)
  { emojis: '🦁👑', answer: 'De Leeuwenkoning', category: 'Films', difficulty: 1 },
  { emojis: '🧊🚢💔', answer: 'Titanic', category: 'Films', difficulty: 1 },
  { emojis: '🕷️🧑', answer: 'Spider-Man', category: 'Films', difficulty: 1 },
  { emojis: '⭐🔫🌌', answer: 'Star Wars', category: 'Films', difficulty: 1 },
  { emojis: '🧙‍♂️💍🌋', answer: 'In de Ban van de Ring', category: 'Films', difficulty: 2 },
  { emojis: '🦇🌃🦹', answer: 'Batman', category: 'Films', difficulty: 1 },
  { emojis: '🐟🔍', answer: 'Finding Nemo', category: 'Films', difficulty: 1 },
  { emojis: '👻👻👻🔫', answer: 'Ghostbusters', category: 'Films', difficulty: 2 },
  { emojis: '🧊❄️👸🎵', answer: 'Frozen', category: 'Films', difficulty: 1 },
  { emojis: '🏴‍☠️⚓🗺️', answer: 'Pirates of the Caribbean', category: 'Films', difficulty: 2 },
  { emojis: '🤖👍🔥', answer: 'Terminator', category: 'Films', difficulty: 2 },
  { emojis: '🧪👨‍🔬💚', answer: 'Hulk', category: 'Films', difficulty: 2 },
  { emojis: '🏎️💨🔧', answer: 'Cars', category: 'Films', difficulty: 1 },
  { emojis: '🐀👨‍🍳🇫🇷', answer: 'Ratatouille', category: 'Films', difficulty: 2 },
  { emojis: '🦖🏝️🔬', answer: 'Jurassic Park', category: 'Films', difficulty: 1 },
  { emojis: '👽☎️🚲🌕', answer: 'E.T.', category: 'Films', difficulty: 2 },
  { emojis: '💀🎃🎄', answer: 'Nightmare Before Christmas', category: 'Films', difficulty: 3 },
  { emojis: '🐼🥋🏯', answer: 'Kung Fu Panda', category: 'Films', difficulty: 1 },
  { emojis: '🧓⬆️🎈🏠', answer: 'Up', category: 'Films', difficulty: 2 },
  { emojis: '🔵👤👤🌿', answer: 'Avatar', category: 'Films', difficulty: 2 },
  { emojis: '🧸🎈🍯', answer: 'Winnie de Poeh', category: 'Films', difficulty: 1 },
  { emojis: '🦈🏊‍♂️😱', answer: 'Jaws', category: 'Films', difficulty: 2 },
  { emojis: '🐒🍌👑', answer: 'Tarzan', category: 'Films', difficulty: 2 },
  { emojis: '🧪⏰🚗💨', answer: 'Back to the Future', category: 'Films', difficulty: 2 },
  { emojis: '🎭🌹👻🎵', answer: 'Het Spook van de Opera', category: 'Films', difficulty: 3 },
  { emojis: '🧊🦣🐿️', answer: 'Ice Age', category: 'Films', difficulty: 1 },
  { emojis: '🏜️🪱🌍', answer: 'Dune', category: 'Films', difficulty: 3 },
  { emojis: '🔫🤠🐴🌵', answer: 'Django Unchained', category: 'Films', difficulty: 3 },
  { emojis: '👩‍🍳🐀🇫🇷⭐', answer: 'Ratatouille', category: 'Films', difficulty: 1 },
  { emojis: '🦸‍♀️🏝️⚔️🛡️', answer: 'Wonder Woman', category: 'Films', difficulty: 2 },

  // Liedjes (28)
  { emojis: '🎤💃🕺🇸🇪', answer: 'Dancing Queen', category: 'Liedjes', difficulty: 2 },
  { emojis: '🌧️☔😢', answer: 'Singin\' in the Rain', category: 'Liedjes', difficulty: 2 },
  { emojis: '🎸🤘😈🛣️', answer: 'Highway to Hell', category: 'Liedjes', difficulty: 2 },
  { emojis: '💎🌌🎵', answer: 'Diamonds', category: 'Liedjes', difficulty: 2 },
  { emojis: '🔥🎤👧', answer: 'Girl on Fire', category: 'Liedjes', difficulty: 2 },
  { emojis: '☀️😊', answer: 'Happy', category: 'Liedjes', difficulty: 1 },
  { emojis: '🌈🎵☁️', answer: 'Somewhere Over the Rainbow', category: 'Liedjes', difficulty: 2 },
  { emojis: '👁️🐅', answer: 'Eye of the Tiger', category: 'Liedjes', difficulty: 1 },
  { emojis: '🦊❓', answer: 'What Does the Fox Say', category: 'Liedjes', difficulty: 1 },
  { emojis: '💃🍑', answer: 'Shake It Off', category: 'Liedjes', difficulty: 3 },
  { emojis: '🧱🏗️🎵', answer: 'Another Brick in the Wall', category: 'Liedjes', difficulty: 3 },
  { emojis: '🔔🎄🎅', answer: 'Jingle Bells', category: 'Liedjes', difficulty: 1 },
  { emojis: '🌃🎷🗽', answer: 'New York New York', category: 'Liedjes', difficulty: 2 },
  { emojis: '⏰🕐⏰', answer: 'Time After Time', category: 'Liedjes', difficulty: 3 },
  { emojis: '🎹🎤🔥👨', answer: 'Piano Man', category: 'Liedjes', difficulty: 2 },
  { emojis: '🌊🏄🎵', answer: 'Surfin\' USA', category: 'Liedjes', difficulty: 2 },
  { emojis: '👩‍🚀🚀🌟', answer: 'Rocket Man', category: 'Liedjes', difficulty: 2 },
  { emojis: '💛🌻🎵', answer: 'Sunflower', category: 'Liedjes', difficulty: 2 },
  { emojis: '🎤🎵🌍🙏', answer: 'Imagine', category: 'Liedjes', difficulty: 2 },
  { emojis: '💜🌧️🎵', answer: 'Purple Rain', category: 'Liedjes', difficulty: 2 },
  { emojis: '🏠🛣️🎵', answer: 'Take Me Home Country Roads', category: 'Liedjes', difficulty: 3 },
  { emojis: '👻🎵💀👻', answer: 'Thriller', category: 'Liedjes', difficulty: 1 },
  { emojis: '🌊🏖️👩‍🦰🎵', answer: 'Ocean Eyes', category: 'Liedjes', difficulty: 3 },
  { emojis: '💃🎶🇨🇺', answer: 'Havana', category: 'Liedjes', difficulty: 2 },
  { emojis: '🔔🎅🎄⛄', answer: 'Last Christmas', category: 'Liedjes', difficulty: 1 },
  { emojis: '🌙✨💤🎵', answer: 'Maanlichtsonate', category: 'Liedjes', difficulty: 3 },
  { emojis: '🚗💨🎵🛣️', answer: 'Drive', category: 'Liedjes', difficulty: 3 },
  { emojis: '🧡📞🎵', answer: 'Call Me Maybe', category: 'Liedjes', difficulty: 2 },

  // Spreekwoorden (28)
  { emojis: '🍎🌳🔽', answer: 'De appel valt niet ver van de boom', category: 'Spreekwoorden', difficulty: 1 },
  { emojis: '🐦🖐️🕊️🏠', answer: 'Beter een vogel in de hand dan tien in de lucht', category: 'Spreekwoorden', difficulty: 2 },
  { emojis: '⏰💰', answer: 'Tijd is geld', category: 'Spreekwoorden', difficulty: 1 },
  { emojis: '🗣️🥈🤫🥇', answer: 'Spreken is zilver zwijgen is goud', category: 'Spreekwoorden', difficulty: 2 },
  { emojis: '👁️👁️🍽️', answer: 'Het oog wil ook wat', category: 'Spreekwoorden', difficulty: 1 },
  { emojis: '🔚👍🔚', answer: 'Eind goed al goed', category: 'Spreekwoorden', difficulty: 1 },
  { emojis: '❤️💧👁️', answer: 'Uit het oog uit het hart', category: 'Spreekwoorden', difficulty: 2 },
  { emojis: '🐱🏠🐭💃', answer: 'Als de kat van huis is dansen de muizen', category: 'Spreekwoorden', difficulty: 3 },
  { emojis: '🌹🔧⚙️', answer: 'Geen roos zonder doornen', category: 'Spreekwoorden', difficulty: 2 },
  { emojis: '🌧️☀️🌈', answer: 'Na regen komt zonneschijn', category: 'Spreekwoorden', difficulty: 1 },
  { emojis: '🐕🐕🐕🦴', answer: 'Veel honden zijn de haas zijn dood', category: 'Spreekwoorden', difficulty: 3 },
  { emojis: '🔑🗝️🔓', answer: 'Al doende leert men', category: 'Spreekwoorden', difficulty: 3 },
  { emojis: '🐔🥚❓', answer: 'Wat was er eerst de kip of het ei', category: 'Spreekwoorden', difficulty: 2 },
  { emojis: '🪨💧🕰️', answer: 'De druppel holt de steen uit', category: 'Spreekwoorden', difficulty: 2 },
  { emojis: '🙈🙉🙊', answer: 'Niets zien niets horen niets zeggen', category: 'Spreekwoorden', difficulty: 1 },
  { emojis: '🐴🎁🦷', answer: 'Een gegeven paard niet in de bek kijken', category: 'Spreekwoorden', difficulty: 3 },
  { emojis: '🧹✨🆕', answer: 'Nieuwe bezems vegen schoon', category: 'Spreekwoorden', difficulty: 2 },
  { emojis: '💪🧠📚', answer: 'Kennis is macht', category: 'Spreekwoorden', difficulty: 1 },
  { emojis: '🐦🌅🪱', answer: 'De vroege vogel vangt de worm', category: 'Spreekwoorden', difficulty: 1 },
  { emojis: '🏠🔑❤️', answer: 'Oost west thuis best', category: 'Spreekwoorden', difficulty: 2 },
  { emojis: '🍒🍒👫', answer: 'Soort zoekt soort', category: 'Spreekwoorden', difficulty: 3 },
  { emojis: '🧹🏠✨', answer: 'Orde is het halve leven', category: 'Spreekwoorden', difficulty: 2 },
  { emojis: '💰🗣️❌', answer: 'Over geld praat je niet', category: 'Spreekwoorden', difficulty: 2 },
  { emojis: '🎯🔨💪', answer: 'Oefening baart kunst', category: 'Spreekwoorden', difficulty: 1 },
  { emojis: '👀🍲👩‍🍳', answer: 'Veel koks bederven de brij', category: 'Spreekwoorden', difficulty: 2 },
  { emojis: '🐕🌳🔔', answer: 'Daar zit de kneep', category: 'Spreekwoorden', difficulty: 2 },
  { emojis: '🪵👀🌲', answer: 'Door de bomen het bos niet meer zien', category: 'Spreekwoorden', difficulty: 3 },
  { emojis: '🍏🌳⬇️', answer: 'Zo vader zo zoon', category: 'Spreekwoorden', difficulty: 1 },

  // Merken (26)
  { emojis: '🍎📱💻', answer: 'Apple', category: 'Merken', difficulty: 1 },
  { emojis: '✔️👟💨', answer: 'Nike', category: 'Merken', difficulty: 1 },
  { emojis: '🟡🟡🟡🟡🚗', answer: 'Audi', category: 'Merken', difficulty: 2 },
  { emojis: '👑🍔🍟', answer: 'Burger King', category: 'Merken', difficulty: 1 },
  { emojis: '🟥🐂🐂', answer: 'Red Bull', category: 'Merken', difficulty: 1 },
  { emojis: '🎮🕹️🍄', answer: 'Nintendo', category: 'Merken', difficulty: 2 },
  { emojis: '📦🏠🔜', answer: 'Amazon', category: 'Merken', difficulty: 1 },
  { emojis: '🔎🌐📊', answer: 'Google', category: 'Merken', difficulty: 1 },
  { emojis: '🧱🔴🟡🟢', answer: 'Lego', category: 'Merken', difficulty: 1 },
  { emojis: '⭐🏨☕', answer: 'Starbucks', category: 'Merken', difficulty: 2 },
  { emojis: '🚗⚡🔋', answer: 'Tesla', category: 'Merken', difficulty: 1 },
  { emojis: '🐦📱💬', answer: 'Twitter', category: 'Merken', difficulty: 1 },
  { emojis: '📸🟪🌅', answer: 'Instagram', category: 'Merken', difficulty: 1 },
  { emojis: '🎵🎧🟢', answer: 'Spotify', category: 'Merken', difficulty: 1 },
  { emojis: '🐻🧊🍬', answer: 'Haribo', category: 'Merken', difficulty: 2 },
  { emojis: '🟫🍫🐄', answer: 'Milka', category: 'Merken', difficulty: 2 },
  { emojis: '🎬🍿❤️', answer: 'Netflix', category: 'Merken', difficulty: 1 },
  { emojis: '🪑🔧🇸🇪', answer: 'IKEA', category: 'Merken', difficulty: 1 },
  { emojis: '🏎️🐎🇮🇹', answer: 'Ferrari', category: 'Merken', difficulty: 1 },
  { emojis: '🎮🍄🔴', answer: 'Nintendo', category: 'Merken', difficulty: 1 },
  { emojis: '📱💬🟢', answer: 'WhatsApp', category: 'Merken', difficulty: 1 },
  { emojis: '☕🧜‍♀️🟢', answer: 'Starbucks', category: 'Merken', difficulty: 1 },
  { emojis: '🏠🔑✈️', answer: 'Airbnb', category: 'Merken', difficulty: 2 },
  { emojis: '📦📱🛒', answer: 'Amazon', category: 'Merken', difficulty: 1 },
  { emojis: '🎵🎧📱', answer: 'Spotify', category: 'Merken', difficulty: 1 },
  { emojis: '🔍📧📺', answer: 'Google', category: 'Merken', difficulty: 1 },

  // Series (16)
  { emojis: '🧪👨‍🔬💊💰', answer: 'Breaking Bad', category: 'Series', difficulty: 1 },
  { emojis: '👑⚔️🐉', answer: 'Game of Thrones', category: 'Series', difficulty: 1 },
  { emojis: '🧟‍♂️🔫🌍', answer: 'The Walking Dead', category: 'Series', difficulty: 1 },
  { emojis: '🔦👦🚲🧇', answer: 'Stranger Things', category: 'Series', difficulty: 1 },
  { emojis: '🏠💵📌', answer: 'La Casa de Papel', category: 'Series', difficulty: 2 },
  { emojis: '👩‍⚕️🏥💉', answer: 'Grey\'s Anatomy', category: 'Series', difficulty: 2 },
  { emojis: '🧑‍🔬🤓🎯🏠', answer: 'The Big Bang Theory', category: 'Series', difficulty: 1 },
  { emojis: '☕👫👫👫', answer: 'Friends', category: 'Series', difficulty: 1 },
  { emojis: '🏢📎😐', answer: 'The Office', category: 'Series', difficulty: 2 },
  { emojis: '🍳👨‍🍳🔪⭐', answer: 'MasterChef', category: 'Series', difficulty: 2 },
  { emojis: '🦑🎮💀', answer: 'Squid Game', category: 'Series', difficulty: 1 },
  { emojis: '🧛‍♂️🩸📖', answer: 'The Vampire Diaries', category: 'Series', difficulty: 2 },
  { emojis: '🏝️✈️🔢', answer: 'Lost', category: 'Series', difficulty: 2 },
  { emojis: '♟️👸🇬🇧', answer: 'The Queen\'s Gambit', category: 'Series', difficulty: 3 },
  { emojis: '🧑‍🏫🔴🔵', answer: 'La Casa de Papel', category: 'Series', difficulty: 3 },
  { emojis: '🐺🌕🏰', answer: 'Teen Wolf', category: 'Series', difficulty: 2 },

  // Videospellen (14)
  { emojis: '🍄🟢🏰👸', answer: 'Super Mario', category: 'Videospellen', difficulty: 1 },
  { emojis: '⛏️🟫🌍🧱', answer: 'Minecraft', category: 'Videospellen', difficulty: 1 },
  { emojis: '⚽🏟️⚡', answer: 'FIFA', category: 'Videospellen', difficulty: 1 },
  { emojis: '🔫🎯🏃‍♂️💣', answer: 'Call of Duty', category: 'Videospellen', difficulty: 2 },
  { emojis: '🏎️🍌🏁🌈', answer: 'Mario Kart', category: 'Videospellen', difficulty: 1 },
  { emojis: '⚡🟡⚡🐭', answer: 'Pokemon', category: 'Videospellen', difficulty: 1 },
  { emojis: '🗡️🛡️🧝‍♂️🏰', answer: 'Zelda', category: 'Videospellen', difficulty: 2 },
  { emojis: '🔵🦔💨💎', answer: 'Sonic', category: 'Videospellen', difficulty: 1 },
  { emojis: '🏗️🏙️🚗🎮', answer: 'GTA', category: 'Videospellen', difficulty: 2 },
  { emojis: '🧱🧱🧱📐', answer: 'Tetris', category: 'Videospellen', difficulty: 1 },
  { emojis: '🐔🔫🪖🏝️', answer: 'Fortnite', category: 'Videospellen', difficulty: 1 },
  { emojis: '🧙‍♂️📖⚔️🐴', answer: 'The Witcher', category: 'Videospellen', difficulty: 2 },
  { emojis: '🚀🌌👨‍🚀🔧', answer: 'Among Us', category: 'Videospellen', difficulty: 2 },
  { emojis: '🐉⚔️🗻🏹', answer: 'Skyrim', category: 'Videospellen', difficulty: 3 },
];
