export interface TruthQuestion {
  text: string;
  intensity: 1 | 2 | 3;
  category: string;
}

export interface DareChallenge {
  text: string;
  intensity: 1 | 2 | 3;
  category: string;
}

export const TRUTH_QUESTIONS: TruthQuestion[] = [
  // Harmlos (1)
  { text: 'Was ist dein Lieblingslied, das du heimlich hoerst?', intensity: 1, category: 'Harmlos' },
  { text: 'Was war dein Kindheitstraum als Beruf?', intensity: 1, category: 'Harmlos' },
  { text: 'Welches Essen koenntest du jeden Tag essen?', intensity: 1, category: 'Harmlos' },
  { text: 'Was ist dein Guilty-Pleasure-Film?', intensity: 1, category: 'Harmlos' },
  { text: 'Was war das letzte, worueber du gelacht hast?', intensity: 1, category: 'Harmlos' },
  { text: 'Wenn du ein Tier waerst, welches waerst du?', intensity: 1, category: 'Harmlos' },
  { text: 'Was ist die unnuetzeste Faehigkeit, die du hast?', intensity: 1, category: 'Harmlos' },
  { text: 'Welchen Promi wuerdest du gerne treffen?', intensity: 1, category: 'Harmlos' },
  { text: 'Was war das beste Geschenk, das du je bekommen hast?', intensity: 1, category: 'Harmlos' },
  { text: 'Wenn du eine Superkraft haettest, welche waere es?', intensity: 1, category: 'Harmlos' },
  { text: 'Was ist dein Lieblingsort auf der Welt?', intensity: 1, category: 'Harmlos' },
  { text: 'Welche Serie hast du zuletzt gebingewatched?', intensity: 1, category: 'Harmlos' },
  { text: 'Was ist das Beste an deinem Job?', intensity: 1, category: 'Harmlos' },
  { text: 'Hast du ein verstecktes Talent?', intensity: 1, category: 'Harmlos' },
  { text: 'Was wuerdest du mit einer Million Euro machen?', intensity: 1, category: 'Harmlos' },
  { text: 'Welches Lied singst du unter der Dusche?', intensity: 1, category: 'Harmlos' },
  { text: 'Was ist dein Lieblings-Snack um Mitternacht?', intensity: 1, category: 'Harmlos' },
  { text: 'Welche App nutzt du am meisten?', intensity: 1, category: 'Harmlos' },
  { text: 'Was war dein Lieblingsspielzeug als Kind?', intensity: 1, category: 'Harmlos' },
  { text: 'Wohin wuerdest du sofort reisen, wenn du koenntest?', intensity: 1, category: 'Harmlos' },
  // Lustig (1-2)
  { text: 'Was ist das Peinlichste, das dir in der Oeffentlichkeit passiert ist?', intensity: 2, category: 'Lustig' },
  { text: 'Hast du jemals jemanden geghosted?', intensity: 2, category: 'Lustig' },
  { text: 'Was war dein schlimmster Haarschnitt?', intensity: 1, category: 'Lustig' },
  { text: 'Hast du jemals gelogen, um nicht arbeiten zu muessen?', intensity: 2, category: 'Lustig' },
  { text: 'Was ist die duemmste Sache, die du je gegoogelt hast?', intensity: 1, category: 'Lustig' },
  { text: 'Hast du mal jemandem eine Nachricht geschickt, die nicht fuer ihn bestimmt war?', intensity: 2, category: 'Lustig' },
  { text: 'Welche Angewohnheit versuchst du zu verbergen?', intensity: 2, category: 'Lustig' },
  { text: 'Was war dein peinlichster Social-Media-Moment?', intensity: 2, category: 'Lustig' },
  { text: 'Hast du schon mal beim Brettspiel geschummelt?', intensity: 1, category: 'Lustig' },
  { text: 'Was ist die seltsamste Sache in deinem Kuehlschrank?', intensity: 1, category: 'Lustig' },
  { text: 'Hast du jemals einen Witz erzaehlt, den niemand lustig fand?', intensity: 1, category: 'Lustig' },
  { text: 'Was ist die laecherlichste Ausrede, die du je benutzt hast?', intensity: 2, category: 'Lustig' },
  { text: 'Welchen peinlichen Song hast du in deiner Playlist?', intensity: 1, category: 'Lustig' },
  { text: 'Hast du mal im Schlaf geredet? Was hast du gesagt?', intensity: 1, category: 'Lustig' },
  { text: 'Was war dein schlimmstes Date?', intensity: 2, category: 'Lustig' },
  { text: 'Welches Geraeusch machst du, wenn niemand zuhoert?', intensity: 1, category: 'Lustig' },
  { text: 'Hast du schon mal vor Lachen geweint? Warum?', intensity: 1, category: 'Lustig' },
  { text: 'Was ist dein ungewoehnlichstes Hobby?', intensity: 1, category: 'Lustig' },
  { text: 'Hast du schon mal jemanden versehentlich beleidigt?', intensity: 2, category: 'Lustig' },
  { text: 'Was war das Komischste, das du je gegessen hast?', intensity: 1, category: 'Lustig' },
  // Peinlich (2-3)
  { text: 'Was ist dein groesster Crush in dieser Runde?', intensity: 3, category: 'Peinlich' },
  { text: 'Hast du jemals jemandem hinterhergestalkt auf Social Media?', intensity: 2, category: 'Peinlich' },
  { text: 'Was ist die peinlichste Nachricht in deinem Chatverlauf?', intensity: 3, category: 'Peinlich' },
  { text: 'Hast du jemals eine Traene bei einem Werbespot vergossen?', intensity: 1, category: 'Peinlich' },
  { text: 'Was war dein peinlichster Moment auf einer Party?', intensity: 2, category: 'Peinlich' },
  { text: 'Zeig das aelteste Foto auf deinem Handy!', intensity: 2, category: 'Peinlich' },
  { text: 'Wann hast du das letzte Mal geweint und warum?', intensity: 2, category: 'Peinlich' },
  { text: 'Was ist dein geheimster Wunsch?', intensity: 3, category: 'Peinlich' },
  { text: 'Hast du jemals Essen vom Boden aufgehoben und gegessen?', intensity: 1, category: 'Peinlich' },
  { text: 'Was ist die peinlichste Serie, die du heimlich schaust?', intensity: 1, category: 'Peinlich' },
  { text: 'Wer in dieser Runde hat den besten Style?', intensity: 2, category: 'Peinlich' },
  { text: 'Was war das Peinlichste, das du im Unterricht gemacht hast?', intensity: 2, category: 'Peinlich' },
  { text: 'Hast du schon mal im Kino geweint?', intensity: 1, category: 'Peinlich' },
  { text: 'Was ist dein peinlichstes Foto auf dem Handy?', intensity: 2, category: 'Peinlich' },
  { text: 'Hast du jemals einen Liebesbrief geschrieben?', intensity: 2, category: 'Peinlich' },
  { text: 'Was war der peinlichste Moment mit deinen Eltern?', intensity: 2, category: 'Peinlich' },
  { text: 'Hast du schon mal in der Oeffentlichkeit laut gesungen?', intensity: 1, category: 'Peinlich' },
  { text: 'Was ist das Peinlichste in deinem Browserverlauf?', intensity: 3, category: 'Peinlich' },
  { text: 'Hast du schon mal jemandem eine Liebeserklaerung gemacht?', intensity: 2, category: 'Peinlich' },
  { text: 'Was war dein groesster Fashion-Fail?', intensity: 2, category: 'Peinlich' },
  // Mutig (3)
  { text: 'Was wuerdest du aendern, wenn du einen Tag lang unsichtbar waerst?', intensity: 3, category: 'Mutig' },
  { text: 'Hast du jemals etwas Illegales gemacht?', intensity: 3, category: 'Mutig' },
  { text: 'Was war die mutigste Sache, die du je gemacht hast?', intensity: 2, category: 'Mutig' },
  { text: 'Wuerdest du fuer 10.000 Euro nackt durch die Stadt laufen?', intensity: 3, category: 'Mutig' },
  { text: 'Was ist das Gewagteste, das du je auf einer Party gemacht hast?', intensity: 3, category: 'Mutig' },
  { text: 'Hast du jemals jemandem ein Geheimnis verraten?', intensity: 2, category: 'Mutig' },
  { text: 'Was ist das Verrückteste auf deiner Bucket List?', intensity: 2, category: 'Mutig' },
  { text: 'Wuerdest du einen Fallschirmsprung machen?', intensity: 1, category: 'Mutig' },
  { text: 'Was wuerdest du tun, wenn du keine Angst haettest?', intensity: 2, category: 'Mutig' },
  { text: 'Hast du schon mal etwas gemacht, wovon deine Eltern nichts wissen?', intensity: 3, category: 'Mutig' },
];

export const DARE_CHALLENGES: DareChallenge[] = [
  // Harmlos (1)
  { text: 'Mach dein bestes Tiergeraeusch!', intensity: 1, category: 'Harmlos' },
  { text: 'Sing 10 Sekunden lang ein Kinderlied!', intensity: 1, category: 'Harmlos' },
  { text: 'Mach 10 Jumping Jacks!', intensity: 1, category: 'Harmlos' },
  { text: 'Erzaehle einen Witz!', intensity: 1, category: 'Harmlos' },
  { text: 'Sprich 30 Sekunden lang wie ein Roboter!', intensity: 1, category: 'Harmlos' },
  { text: 'Mach ein Selfie mit der Person links von dir!', intensity: 1, category: 'Harmlos' },
  { text: 'Tanze 15 Sekunden lang ohne Musik!', intensity: 1, category: 'Harmlos' },
  { text: 'Steh auf und verbeuge dich vor der Gruppe!', intensity: 1, category: 'Harmlos' },
  { text: 'Mach dein bestes Operngesicht!', intensity: 1, category: 'Harmlos' },
  { text: 'Zeichne mit geschlossenen Augen ein Haus!', intensity: 1, category: 'Harmlos' },
  { text: 'Halte 30 Sekunden lang Augenkontakt mit jemandem!', intensity: 1, category: 'Harmlos' },
  { text: 'Mach eine Planke fuer 20 Sekunden!', intensity: 1, category: 'Harmlos' },
  { text: 'Klatsche rhythmisch und bringe die Gruppe zum Mitmachen!', intensity: 1, category: 'Harmlos' },
  { text: 'Steh auf und dreh dich dreimal im Kreis!', intensity: 1, category: 'Harmlos' },
  { text: 'Fluestere alles fuer die naechste Minute!', intensity: 1, category: 'Harmlos' },
  { text: 'Imitiere einen beruhmten Filmcharakter!', intensity: 1, category: 'Harmlos' },
  { text: 'Buchstabiere deinen Namen rueckwaerts laut!', intensity: 1, category: 'Harmlos' },
  { text: 'Mach ein lustiges Gesicht und halte es 10 Sekunden!', intensity: 1, category: 'Harmlos' },
  { text: 'Erzaehle der Gruppe dein peinlichstes Erlebnis als Kind!', intensity: 1, category: 'Harmlos' },
  { text: 'Sprich fuer die naechste Runde mit Akzent!', intensity: 1, category: 'Harmlos' },
  // Lustig (1-2)
  { text: 'Fuehre einen Moonwalk vor!', intensity: 2, category: 'Lustig' },
  { text: 'Mach eine 30-Sekunden Stand-up Comedy!', intensity: 2, category: 'Lustig' },
  { text: 'Imitiere einen Promi, bis jemand erraat, wer es ist!', intensity: 2, category: 'Lustig' },
  { text: 'Tanze wie ein Dad auf einer Hochzeit!', intensity: 1, category: 'Lustig' },
  { text: 'Rappe 20 Sekunden lang ueber die Person rechts von dir!', intensity: 2, category: 'Lustig' },
  { text: 'Spiele eine Szene aus deinem Lieblingsfilm nach!', intensity: 2, category: 'Lustig' },
  { text: 'Mach eine Nachrichtensprecher-Stimme und lies eine Fake-Nachricht vor!', intensity: 2, category: 'Lustig' },
  { text: 'Bewege dich wie in Zeitlupe fuer 30 Sekunden!', intensity: 1, category: 'Lustig' },
  { text: 'Fuehre den schlechtesten Tanzstil vor, den du kennst!', intensity: 1, category: 'Lustig' },
  { text: 'Erzaehle eine Geschichte, in der jedes Wort mit dem gleichen Buchstaben beginnt!', intensity: 2, category: 'Lustig' },
  { text: 'Steh auf und halte eine Dankesrede wie bei den Oscars!', intensity: 2, category: 'Lustig' },
  { text: 'Mach ein Tik-Tok-Video (ohne es zu posten)!', intensity: 2, category: 'Lustig' },
  { text: 'Singe Happy Birthday fuer die Person gegenueber!', intensity: 1, category: 'Lustig' },
  { text: 'Sprich 1 Minute lang wie Yoda!', intensity: 2, category: 'Lustig' },
  { text: 'Fuehre den beruehmtesten Tanz aus einem Musikvideo vor!', intensity: 2, category: 'Lustig' },
  { text: 'Mach eine dramatische Lesung des letzten Texts auf deinem Handy!', intensity: 2, category: 'Lustig' },
  { text: 'Versuche 30 Sekunden lang nicht zu blinzeln!', intensity: 1, category: 'Lustig' },
  { text: 'Erzaehle einen Zungenbrecher dreimal schnell hintereinander!', intensity: 1, category: 'Lustig' },
  { text: 'Mach einen Handstand (oder versuch es zumindest)!', intensity: 2, category: 'Lustig' },
  { text: 'Imitiere dein Lieblingsemoji mit deinem Gesicht!', intensity: 1, category: 'Lustig' },
  // Peinlich (2-3)
  { text: 'Ruf jemanden an und sag "Ich liebe dich!"', intensity: 3, category: 'Peinlich' },
  { text: 'Poste ein Selfie mit dem duesteren Caption "Montag..."!', intensity: 2, category: 'Peinlich' },
  { text: 'Lass die Gruppe ein Foto von dir machen und es als Profilbild setzen!', intensity: 3, category: 'Peinlich' },
  { text: 'Erzaehle deinen groessten Fail beim Flirten!', intensity: 2, category: 'Peinlich' },
  { text: 'Zeige der Gruppe die letzten 3 Fotos auf deinem Handy!', intensity: 2, category: 'Peinlich' },
  { text: 'Sag jedem in der Runde ein ehrliches Kompliment!', intensity: 2, category: 'Peinlich' },
  { text: 'Lass jemanden eine Nachricht von deinem Handy schicken!', intensity: 3, category: 'Peinlich' },
  { text: 'Stelle dich auf einen Stuhl und singe ein Liebeslied!', intensity: 3, category: 'Peinlich' },
  { text: 'Lass die Gruppe dein Outfit fuer den naechsten Tag bestimmen!', intensity: 2, category: 'Peinlich' },
  { text: 'Lies laut die letzte Nachricht vor, die du gesendet hast!', intensity: 2, category: 'Peinlich' },
  { text: 'Mach ein peinliches Foto und sende es an deinen besten Freund!', intensity: 3, category: 'Peinlich' },
  { text: 'Gib der Person links von dir einen Spitznamen!', intensity: 1, category: 'Peinlich' },
  { text: 'Erzaehle die peinlichste Geschichte aus deiner Schulzeit!', intensity: 2, category: 'Peinlich' },
  { text: 'Mach ein Foto mit dem laecherlichsten Gesichtsausdruck!', intensity: 1, category: 'Peinlich' },
  { text: 'Schreibe und sende eine poetische Nachricht an den letzten Kontakt!', intensity: 3, category: 'Peinlich' },
  { text: 'Fuehre deine beste Model-Pose vor!', intensity: 2, category: 'Peinlich' },
  { text: 'Erzaehle, was du heimlich ueber die Person gegenueber denkst!', intensity: 3, category: 'Peinlich' },
  { text: 'Lass die Gruppe deine Haare stylen!', intensity: 2, category: 'Peinlich' },
  { text: 'Singe den Refrain deines Lieblingssongs vor allen!', intensity: 2, category: 'Peinlich' },
  { text: 'Mach 5 Liegestuetze und zaehle dabei laut auf Franzoesisch!', intensity: 2, category: 'Peinlich' },
  // Mutig (3)
  { text: 'Ruf einen Freund an und tu so, als wuerdest du etwas gestehen!', intensity: 3, category: 'Mutig' },
  { text: 'Geh raus und ruf laut "Ich bin der/die Beste!"', intensity: 3, category: 'Mutig' },
  { text: 'Iss etwas, das die Gruppe fuer dich zusammenmischt!', intensity: 3, category: 'Mutig' },
  { text: 'Mach 30 Sekunden lang Beatbox vor der Gruppe!', intensity: 2, category: 'Mutig' },
  { text: 'Tanz alleine 1 Minute zu einem Song, den die Gruppe waehlt!', intensity: 3, category: 'Mutig' },
  { text: 'Lass die Gruppe eine Nachricht in deinem Status posten!', intensity: 3, category: 'Mutig' },
  { text: 'Sprich die naechsten 3 Runden in Reimen!', intensity: 2, category: 'Mutig' },
  { text: 'Mach ein TikTok-Video und poste es wirklich!', intensity: 3, category: 'Mutig' },
  { text: 'Lauf einmal um das Gebaeude und schrei dabei deinen Namen!', intensity: 3, category: 'Mutig' },
  { text: 'Lass dir von der Gruppe eine Aufgabe geben, die du morgen erledigen musst!', intensity: 3, category: 'Mutig' },
];
