export interface TruthQuestion { text: string; intensity: 1 | 2 | 3; category: string; }
export interface DareChallenge { text: string; intensity: 1 | 2 | 3; category: string; }

export const TRUTH_QUESTIONS: TruthQuestion[] = [
  { text: 'Qual e a musica que ouves em segredo?', intensity: 1, category: 'Inofensivo' },
  { text: 'O que querias ser quando eras crianca?', intensity: 1, category: 'Inofensivo' },
  { text: 'Que comida poderias comer todos os dias?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual e o teu filme culpado favorito?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual foi a ultima coisa que te fez rir?', intensity: 1, category: 'Inofensivo' },
  { text: 'Se fosses um animal, qual serias?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual e a habilidade mais inutil que tens?', intensity: 1, category: 'Inofensivo' },
  { text: 'Que celebridade gostarias de conhecer?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual foi o melhor presente que ja recebeste?', intensity: 1, category: 'Inofensivo' },
  { text: 'Se tivesses um superpoder, qual seria?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual e o teu lugar favorito no mundo?', intensity: 1, category: 'Inofensivo' },
  { text: 'Que serie viste toda de uma vez recentemente?', intensity: 1, category: 'Inofensivo' },
  { text: 'O que e o melhor do teu trabalho?', intensity: 1, category: 'Inofensivo' },
  { text: 'Tens um talento escondido?', intensity: 1, category: 'Inofensivo' },
  { text: 'O que farias com um milhao de euros?', intensity: 1, category: 'Inofensivo' },
  { text: 'Que musica cantas no chuveiro?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual e o teu snack favorito a meia-noite?', intensity: 1, category: 'Inofensivo' },
  { text: 'Que app usas mais?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual era o teu brinquedo favorito em crianca?', intensity: 1, category: 'Inofensivo' },
  { text: 'Para onde viajarias agora se pudesses?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual e a coisa mais embaracosa que te aconteceu em publico?', intensity: 2, category: 'Divertido' },
  { text: 'Ja fizeste ghosting a alguem?', intensity: 2, category: 'Divertido' },
  { text: 'Qual foi o teu pior corte de cabelo?', intensity: 1, category: 'Divertido' },
  { text: 'Ja mentiste para nao ir trabalhar?', intensity: 2, category: 'Divertido' },
  { text: 'Qual e a coisa mais estupida que ja pesquisaste no Google?', intensity: 1, category: 'Divertido' },
  { text: 'Ja mandaste uma mensagem para a pessoa errada?', intensity: 2, category: 'Divertido' },
  { text: 'Que habito tentas esconder?', intensity: 2, category: 'Divertido' },
  { text: 'Qual foi o teu momento mais embaracoso nas redes sociais?', intensity: 2, category: 'Divertido' },
  { text: 'Ja fizeste batota num jogo de tabuleiro?', intensity: 1, category: 'Divertido' },
  { text: 'Qual e a coisa mais estranha no teu frigorifico?', intensity: 1, category: 'Divertido' },
  { text: 'Ja contaste uma piada que ninguem achou graca?', intensity: 1, category: 'Divertido' },
  { text: 'Qual e a desculpa mais ridicula que ja usaste?', intensity: 2, category: 'Divertido' },
  { text: 'Que musica embaracosa tens na tua playlist?', intensity: 1, category: 'Divertido' },
  { text: 'Ja falaste a dormir? O que disseste?', intensity: 1, category: 'Divertido' },
  { text: 'Qual foi o teu pior encontro?', intensity: 2, category: 'Divertido' },
  { text: 'Que som fazes quando ninguem esta a ouvir?', intensity: 1, category: 'Divertido' },
  { text: 'Ja choraste de tanto rir? Porque?', intensity: 1, category: 'Divertido' },
  { text: 'Qual e o teu hobby mais incomum?', intensity: 1, category: 'Divertido' },
  { text: 'Ja insultaste alguem sem querer?', intensity: 2, category: 'Divertido' },
  { text: 'Qual e a coisa mais estranha que ja comeste?', intensity: 1, category: 'Divertido' },
  { text: 'Quem e o teu crush neste grupo?', intensity: 3, category: 'Embaracoso' },
  { text: 'Ja fizeste stalking a alguem nas redes sociais?', intensity: 2, category: 'Embaracoso' },
  { text: 'Qual e a mensagem mais embaracosa no teu chat?', intensity: 3, category: 'Embaracoso' },
  { text: 'Ja choraste com um anuncio de televisao?', intensity: 1, category: 'Embaracoso' },
  { text: 'Qual foi o teu momento mais embaracoso numa festa?', intensity: 2, category: 'Embaracoso' },
  { text: 'Mostra a foto mais antiga no teu telemovel!', intensity: 2, category: 'Embaracoso' },
  { text: 'Quando foi a ultima vez que choraste e porque?', intensity: 2, category: 'Embaracoso' },
  { text: 'Qual e o teu desejo mais secreto?', intensity: 3, category: 'Embaracoso' },
  { text: 'Ja apanhaste comida do chao e comeste?', intensity: 1, category: 'Embaracoso' },
  { text: 'Que serie embaracosa ves em segredo?', intensity: 1, category: 'Embaracoso' },
  { text: 'Quem neste grupo tem o melhor estilo?', intensity: 2, category: 'Embaracoso' },
  { text: 'Qual foi a coisa mais embaracosa que fizeste na aula?', intensity: 2, category: 'Embaracoso' },
  { text: 'Ja choraste no cinema?', intensity: 1, category: 'Embaracoso' },
  { text: 'Qual e a foto mais embaracosa no teu telemovel?', intensity: 2, category: 'Embaracoso' },
  { text: 'Ja escreveste uma carta de amor?', intensity: 2, category: 'Embaracoso' },
  { text: 'Qual foi o momento mais embaracoso com os teus pais?', intensity: 2, category: 'Embaracoso' },
  { text: 'Ja cantaste alto em publico?', intensity: 1, category: 'Embaracoso' },
  { text: 'Qual e a coisa mais embaracosa no teu historico do browser?', intensity: 3, category: 'Embaracoso' },
  { text: 'Ja declaraste os teus sentimentos a alguem?', intensity: 2, category: 'Embaracoso' },
  { text: 'Qual foi o teu maior fail de moda?', intensity: 2, category: 'Embaracoso' },
  { text: 'O que mudarias se fosses invisivel por um dia?', intensity: 3, category: 'Ousado' },
  { text: 'Ja fizeste algo ilegal?', intensity: 3, category: 'Ousado' },
  { text: 'Qual foi a coisa mais corajosa que ja fizeste?', intensity: 2, category: 'Ousado' },
  { text: 'Correrias nu pela cidade por 10.000 euros?', intensity: 3, category: 'Ousado' },
  { text: 'Qual e a coisa mais louca que ja fizeste numa festa?', intensity: 3, category: 'Ousado' },
  { text: 'Ja revelaste o segredo de alguem?', intensity: 2, category: 'Ousado' },
  { text: 'Qual e a coisa mais louca na tua bucket list?', intensity: 2, category: 'Ousado' },
  { text: 'Saltarias de paraquedas?', intensity: 1, category: 'Ousado' },
  { text: 'O que farias se nao tivesses medo?', intensity: 2, category: 'Ousado' },
  { text: 'Ja fizeste algo que os teus pais nao sabem?', intensity: 3, category: 'Ousado' },
  { text: 'Qual foi o teu primeiro pensamento esta manha?', intensity: 1, category: 'Inofensivo' },
  { text: 'Que serie poderias rever infinitamente?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual e a coisa mais romantica que ja fizeste?', intensity: 2, category: 'Divertido' },
  { text: 'Ja apagaste uma mensagem antes de ser lida?', intensity: 2, category: 'Divertido' },
  { text: 'Qual e a coisa mais cara que ja compraste para ti?', intensity: 1, category: 'Inofensivo' },
  { text: 'Que celebridade achas secretamente atraente?', intensity: 2, category: 'Embaracoso' },
  { text: 'Ja copiaste num teste?', intensity: 2, category: 'Divertido' },
  { text: 'Qual e a alcunha mais embaracosa que ja tiveste?', intensity: 1, category: 'Divertido' },
  { text: 'Que habito gostarias de perder?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual e a coisa mais corajosa que fizeste por amor?', intensity: 2, category: 'Ousado' },
  { text: 'Ja culpaste alguem quando a culpa era tua?', intensity: 2, category: 'Divertido' },
  { text: 'O que mudarias se voltasses a ter 16 anos?', intensity: 2, category: 'Inofensivo' },
  { text: 'Que musica te faz sempre chorar?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual e a coisa mais estranha que ja encomendaste online?', intensity: 1, category: 'Divertido' },
  { text: 'Tens um favorito neste grupo?', intensity: 2, category: 'Embaracoso' },
  { text: 'Qual foi o teu maior erro no ultimo ano?', intensity: 2, category: 'Ousado' },
  { text: 'Qual e a mentira que mais repetes?', intensity: 2, category: 'Divertido' },
  { text: 'Qual e o teu ritual secreto antes de dormir?', intensity: 1, category: 'Divertido' },
  { text: 'Ja ligaste para alguem a fingir ser outra pessoa?', intensity: 2, category: 'Divertido' },
  { text: 'O que farias se fosses do genero oposto por um dia?', intensity: 2, category: 'Divertido' },
  { text: 'Quem neste grupo tem a melhor risada?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual foi a comida mais deliciosa que ja comeste?', intensity: 1, category: 'Inofensivo' },
  { text: 'Ja ouviste uma conversa alheia? O que ouviste?', intensity: 2, category: 'Embaracoso' },
  { text: 'Que filme sabes de cor?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual e o teu maior medo?', intensity: 2, category: 'Ousado' },
  { text: 'Ja te esqueceste de um encontro?', intensity: 1, category: 'Divertido' },
  { text: 'O que farias se acordasses famoso amanha?', intensity: 1, category: 'Inofensivo' },
  { text: 'Que som sabes imitar melhor?', intensity: 1, category: 'Divertido' },
  { text: 'Qual e a coisa mais simpática que um desconhecido fez por ti?', intensity: 1, category: 'Inofensivo' },
  { text: 'Ja choraste a dormir?', intensity: 2, category: 'Embaracoso' },
  { text: 'O que farias com 3 desejos?', intensity: 1, category: 'Inofensivo' },
  { text: 'Quem e a pessoa mais engracada que conheces?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual e a aposta mais louca que ja fizeste?', intensity: 2, category: 'Divertido' },
  { text: 'Tens uma palavra favorita secreta?', intensity: 1, category: 'Divertido' },
  { text: 'Qual seria a tua ultima refeicao se pudesses escolher?', intensity: 1, category: 'Inofensivo' },
  { text: 'Quem do grupo seria o melhor colega de casa?', intensity: 2, category: 'Embaracoso' },
  { text: 'O que mais te assustava em crianca?', intensity: 1, category: 'Inofensivo' },
  { text: 'Ja chamaste alguem pelo nome errado?', intensity: 1, category: 'Divertido' },
  { text: 'Qual e o teu maior sonho?', intensity: 2, category: 'Ousado' },
  { text: 'Ja partiste algo valioso e escondeste?', intensity: 2, category: 'Divertido' },
  { text: 'Que personagem historico gostarias de conhecer?', intensity: 1, category: 'Inofensivo' },
  { text: 'Qual e o elogio mais estranho que ja recebeste?', intensity: 1, category: 'Divertido' },
  { text: 'Tens uma conta secreta nas redes sociais?', intensity: 2, category: 'Embaracoso' },
  { text: 'Qual e a tua fobia mais estranha?', intensity: 1, category: 'Divertido' },
  { text: 'Que tendencia achas completamente ridicula?', intensity: 1, category: 'Divertido' },
  { text: 'A quem neste grupo confiarias um segredo?', intensity: 2, category: 'Embaracoso' },
  { text: 'Qual e a coisa mais estranha que ja viste em casa de alguem?', intensity: 2, category: 'Divertido' },
  { text: 'Ja escreveste uma avaliacao falsa na internet?', intensity: 2, category: 'Divertido' },
  { text: 'O que farias se pudesses ser outra pessoa por uma semana?', intensity: 2, category: 'Ousado' },
  { text: 'Qual e a coisa mais embaracosa na tua mesinha de cabeceira?', intensity: 2, category: 'Embaracoso' },
];

export const DARE_CHALLENGES: DareChallenge[] = [
  { text: 'Faz o teu melhor som de animal!', intensity: 1, category: 'Inofensivo' },
  { text: 'Canta uma cancao infantil durante 10 segundos!', intensity: 1, category: 'Inofensivo' },
  { text: 'Faz 10 polichinelos!', intensity: 1, category: 'Inofensivo' },
  { text: 'Conta uma piada!', intensity: 1, category: 'Inofensivo' },
  { text: 'Fala como um robot durante 30 segundos!', intensity: 1, category: 'Inofensivo' },
  { text: 'Tira uma selfie com a pessoa a tua esquerda!', intensity: 1, category: 'Inofensivo' },
  { text: 'Danca 15 segundos sem musica!', intensity: 1, category: 'Inofensivo' },
  { text: 'Levanta-te e faz uma venia ao grupo!', intensity: 1, category: 'Inofensivo' },
  { text: 'Faz a tua melhor cara de opera!', intensity: 1, category: 'Inofensivo' },
  { text: 'Desenha uma casa de olhos fechados!', intensity: 1, category: 'Inofensivo' },
  { text: 'Mantem contacto visual com alguem durante 30 segundos!', intensity: 1, category: 'Inofensivo' },
  { text: 'Faz uma prancha de 20 segundos!', intensity: 1, category: 'Inofensivo' },
  { text: 'Bate palmas com ritmo e faz o grupo acompanhar!', intensity: 1, category: 'Inofensivo' },
  { text: 'Levanta-te e roda tres vezes!', intensity: 1, category: 'Inofensivo' },
  { text: 'Sussurra tudo durante o proximo minuto!', intensity: 1, category: 'Inofensivo' },
  { text: 'Imita um personagem famoso de filme!', intensity: 1, category: 'Inofensivo' },
  { text: 'Soletra o teu nome ao contrario em voz alta!', intensity: 1, category: 'Inofensivo' },
  { text: 'Faz uma cara engracada e aguenta 10 segundos!', intensity: 1, category: 'Inofensivo' },
  { text: 'Conta ao grupo o teu momento mais embaracoso de crianca!', intensity: 1, category: 'Inofensivo' },
  { text: 'Fala com sotaque na proxima ronda!', intensity: 1, category: 'Inofensivo' },
  { text: 'Faz um moonwalk!', intensity: 2, category: 'Divertido' },
  { text: 'Faz 30 segundos de stand-up comedy!', intensity: 2, category: 'Divertido' },
  { text: 'Imita uma celebridade ate alguem adivinhar!', intensity: 2, category: 'Divertido' },
  { text: 'Danca como um pai num casamento!', intensity: 1, category: 'Divertido' },
  { text: 'Rapa 20 segundos sobre a pessoa a tua direita!', intensity: 2, category: 'Divertido' },
  { text: 'Actua uma cena do teu filme favorito!', intensity: 2, category: 'Divertido' },
  { text: 'Faz voz de apresentador de noticias e le uma noticia falsa!', intensity: 2, category: 'Divertido' },
  { text: 'Move-te em camara lenta durante 30 segundos!', intensity: 1, category: 'Divertido' },
  { text: 'Mostra o pior passo de danca que conheces!', intensity: 1, category: 'Divertido' },
  { text: 'Conta uma historia onde cada palavra comeca com a mesma letra!', intensity: 2, category: 'Divertido' },
  { text: 'Levanta-te e faz um discurso de agradecimento como nos Oscares!', intensity: 2, category: 'Divertido' },
  { text: 'Faz um video TikTok (sem publicar)!', intensity: 2, category: 'Divertido' },
  { text: 'Canta Parabens a Voce para a pessoa a frente!', intensity: 1, category: 'Divertido' },
  { text: 'Fala como o Yoda durante 1 minuto!', intensity: 2, category: 'Divertido' },
  { text: 'Reproduz a danca mais famosa de um videoclip!', intensity: 2, category: 'Divertido' },
  { text: 'Faz uma leitura dramatica da ultima mensagem no teu telemovel!', intensity: 2, category: 'Divertido' },
  { text: 'Tenta nao piscar durante 30 segundos!', intensity: 1, category: 'Divertido' },
  { text: 'Diz um trava-linguas tres vezes rapido!', intensity: 1, category: 'Divertido' },
  { text: 'Faz o pino (ou pelo menos tenta)!', intensity: 2, category: 'Divertido' },
  { text: 'Imita o teu emoji favorito com a cara!', intensity: 1, category: 'Divertido' },
  { text: 'Liga a alguem e diz "Amo-te!"', intensity: 3, category: 'Embaracoso' },
  { text: 'Publica uma selfie com a legenda "Segunda-feira..."!', intensity: 2, category: 'Embaracoso' },
  { text: 'Deixa o grupo tirar-te uma foto e coloca-la como foto de perfil!', intensity: 3, category: 'Embaracoso' },
  { text: 'Conta o teu maior fracasso a engatar!', intensity: 2, category: 'Embaracoso' },
  { text: 'Mostra ao grupo as ultimas 3 fotos do teu telemovel!', intensity: 2, category: 'Embaracoso' },
  { text: 'Faz um elogio sincero a cada pessoa do grupo!', intensity: 2, category: 'Embaracoso' },
  { text: 'Deixa alguem enviar uma mensagem do teu telemovel!', intensity: 3, category: 'Embaracoso' },
  { text: 'Sobe para uma cadeira e canta uma musica de amor!', intensity: 3, category: 'Embaracoso' },
  { text: 'Deixa o grupo escolher a tua roupa para amanha!', intensity: 2, category: 'Embaracoso' },
  { text: 'Le em voz alta a ultima mensagem que enviaste!', intensity: 2, category: 'Embaracoso' },
  { text: 'Tira uma foto embaracosa e envia ao teu melhor amigo!', intensity: 3, category: 'Embaracoso' },
  { text: 'Da uma alcunha a pessoa a tua esquerda!', intensity: 1, category: 'Embaracoso' },
  { text: 'Conta a historia mais embaracosa da tua escola!', intensity: 2, category: 'Embaracoso' },
  { text: 'Tira uma foto com a expressao mais ridicula!', intensity: 1, category: 'Embaracoso' },
  { text: 'Escreve e envia uma mensagem poetica ao ultimo contacto!', intensity: 3, category: 'Embaracoso' },
  { text: 'Faz a tua melhor pose de modelo!', intensity: 2, category: 'Embaracoso' },
  { text: 'Diz ao grupo o que pensas secretamente sobre a pessoa a frente!', intensity: 3, category: 'Embaracoso' },
  { text: 'Deixa o grupo pentear-te!', intensity: 2, category: 'Embaracoso' },
  { text: 'Canta o refrão da tua musica favorita em frente a todos!', intensity: 2, category: 'Embaracoso' },
  { text: 'Faz 5 flexoes a contar em frances!', intensity: 2, category: 'Embaracoso' },
  { text: 'Liga a um amigo e finge que estas a confessar algo!', intensity: 3, category: 'Ousado' },
  { text: 'Vai la fora e grita "Eu sou o/a melhor!"', intensity: 3, category: 'Ousado' },
  { text: 'Come algo que o grupo misture para ti!', intensity: 3, category: 'Ousado' },
  { text: 'Faz beatbox durante 30 segundos em frente ao grupo!', intensity: 2, category: 'Ousado' },
  { text: 'Danca sozinho 1 minuto com uma musica escolhida pelo grupo!', intensity: 3, category: 'Ousado' },
  { text: 'Deixa o grupo publicar uma mensagem no teu estado!', intensity: 3, category: 'Ousado' },
  { text: 'Fala em rima nas proximas 3 rondas!', intensity: 2, category: 'Ousado' },
  { text: 'Faz um video TikTok e publica mesmo!', intensity: 3, category: 'Ousado' },
  { text: 'Corre a volta do predio a gritar o teu nome!', intensity: 3, category: 'Ousado' },
  { text: 'Deixa o grupo dar-te uma tarefa para amanha!', intensity: 3, category: 'Ousado' },
  { text: 'Fala como pirata durante 2 minutos!', intensity: 1, category: 'Inofensivo' },
  { text: 'Faz a danca do floss durante 20 segundos!', intensity: 1, category: 'Divertido' },
  { text: 'Liga a alguem e pergunta se o frigorifico esta a correr!', intensity: 2, category: 'Divertido' },
  { text: 'Declara o teu amor a um movel!', intensity: 1, category: 'Divertido' },
  { text: 'Come uma colher de mostarda ou ketchup!', intensity: 2, category: 'Ousado' },
  { text: 'Conta uma piada — se ninguem rir, faz 10 flexoes!', intensity: 1, category: 'Divertido' },
  { text: 'Tira uma foto com a cara mais louca e coloca como perfil!', intensity: 3, category: 'Embaracoso' },
  { text: 'Fala na terceira pessoa nas proximas 2 rondas!', intensity: 2, category: 'Divertido' },
  { text: 'Faz um truque de magia inventado!', intensity: 1, category: 'Divertido' },
  { text: 'Faz um treino de 10 segundos contando em japones!', intensity: 1, category: 'Inofensivo' },
  { text: 'Imita o teu melhor amigo — os outros tem de adivinhar!', intensity: 2, category: 'Divertido' },
  { text: 'Envia um coracao a ultima pessoa a quem ligaste!', intensity: 2, category: 'Embaracoso' },
  { text: 'Faz um striptease — mas so com as meias!', intensity: 2, category: 'Divertido' },
  { text: 'Canta o abecedario o mais rapido possivel!', intensity: 1, category: 'Inofensivo' },
  { text: 'Faz uma venia a cada pessoa do grupo!', intensity: 1, category: 'Inofensivo' },
  { text: 'Deixa o grupo decidir o que bebes a seguir!', intensity: 2, category: 'Ousado' },
  { text: 'Fala disparates 30 segundos como se fosse um telejornal!', intensity: 1, category: 'Divertido' },
  { text: 'Faz sons de alienigena durante 15 segundos!', intensity: 1, category: 'Divertido' },
  { text: 'Levanta-te e faz um discurso eleitoral — es candidato a presidente!', intensity: 2, category: 'Divertido' },
  { text: 'Envia ao 3o contacto da lista "Tenho saudades tuas"!', intensity: 3, category: 'Embaracoso' },
  { text: 'Danca a Macarena!', intensity: 1, category: 'Divertido' },
  { text: 'Fala 1 minuto sem usar a letra E!', intensity: 2, category: 'Divertido' },
  { text: 'Tira uma selfie de olhos fechados e publica!', intensity: 2, category: 'Embaracoso' },
  { text: 'Mostra como acordas de manha — em camara lenta!', intensity: 1, category: 'Divertido' },
  { text: 'Toca bateria imaginaria com uma musica escolhida pelo grupo!', intensity: 1, category: 'Divertido' },
  { text: 'Faz sons de bebe durante 15 segundos!', intensity: 1, category: 'Divertido' },
  { text: 'Faz um discurso de despedida dramatico como se fosses para o exilio!', intensity: 2, category: 'Divertido' },
  { text: 'Deixa a pessoa a tua direita pentear-te!', intensity: 2, category: 'Embaracoso' },
  { text: 'Faz o teu melhor desfile pela sala!', intensity: 2, category: 'Divertido' },
  { text: 'Conta uma historia onde tu es o heroi!', intensity: 1, category: 'Inofensivo' },
  { text: 'Fala como apresentador de noticias e comenta a ultima ronda!', intensity: 2, category: 'Divertido' },
  { text: 'Faz tai chi durante 30 segundos!', intensity: 1, category: 'Inofensivo' },
  { text: 'Passeia um cao invisivel pela sala toda!', intensity: 1, category: 'Divertido' },
  { text: 'Diz "Amo-te" a pessoa a frente sem rir!', intensity: 3, category: 'Embaracoso' },
  { text: 'Danca uma valsa — sozinho!', intensity: 1, category: 'Divertido' },
  { text: 'Tenta um trava-linguas 5 vezes seguidas!', intensity: 1, category: 'Inofensivo' },
  { text: 'Corre ate a arvore mais proxima e volta!', intensity: 1, category: 'Inofensivo' },
  { text: 'Fica pendurado de cabeca para baixo no sofa durante 30 segundos!', intensity: 2, category: 'Divertido' },
  { text: 'Vai a janela e acena aos passantes!', intensity: 2, category: 'Embaracoso' },
  { text: 'Publica uma story no Instagram com um filtro embaracoso!', intensity: 2, category: 'Embaracoso' },
  { text: 'Diz a cada pessoa do grupo o que mais admiras nela!', intensity: 2, category: 'Inofensivo' },
  { text: 'Conta uma piada noutra lingua — com sotaque exagerado!', intensity: 1, category: 'Divertido' },
  { text: 'Faz prancha e aguenta ate responderes a proxima pergunta!', intensity: 2, category: 'Ousado' },
  { text: 'Olha a pessoa a esquerda nos olhos e diz algo querido — sem rir!', intensity: 2, category: 'Embaracoso' },
  { text: 'Dirige uma orquestra invisivel!', intensity: 1, category: 'Divertido' },
  { text: 'Liga ao ultimo contacto e diz: Es o meu heroi!', intensity: 3, category: 'Ousado' },
  { text: 'Faz aquecimento como atleta profissional — 30 segundos!', intensity: 1, category: 'Inofensivo' },
  { text: 'Tenta nao piscar 20 segundos enquanto os outros te distraem!', intensity: 1, category: 'Divertido' },
  { text: 'Canta o refrao de uma cancao infantil com voz de opera!', intensity: 2, category: 'Divertido' },
  { text: 'Deixa alguem escrever uma palavra no teu braco!', intensity: 2, category: 'Embaracoso' },
];
