export interface TruthQuestion {
  text: string;
  intensity: 1 | 2 | 3;
  category: string;
}

export interface DareChallenge {
  text: string;
  intensity: 1 | 2 | 3;
  category: string;
}

export const TRUTH_QUESTIONS: TruthQuestion[] = [
  // Innocuo (1)
  { text: 'Qual e la canzone che ascolti di nascosto?', intensity: 1, category: 'Innocuo' },
  { text: 'Che lavoro sognavi di fare da bambino?', intensity: 1, category: 'Innocuo' },
  { text: 'Quale cibo potresti mangiare ogni giorno?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e il tuo film colpevole preferito?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e l\'ultima cosa che ti ha fatto ridere?', intensity: 1, category: 'Innocuo' },
  { text: 'Se fossi un animale, quale saresti?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e l\'abilita piu inutile che possiedi?', intensity: 1, category: 'Innocuo' },
  { text: 'Quale personaggio famoso vorresti incontrare?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e il miglior regalo che tu abbia mai ricevuto?', intensity: 1, category: 'Innocuo' },
  { text: 'Se avessi un superpotere, quale sarebbe?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e il tuo posto preferito al mondo?', intensity: 1, category: 'Innocuo' },
  { text: 'Quale serie hai visto tutta d\'un fiato di recente?', intensity: 1, category: 'Innocuo' },
  { text: 'Cosa ti piace di piu del tuo lavoro?', intensity: 1, category: 'Innocuo' },
  { text: 'Hai un talento nascosto?', intensity: 1, category: 'Innocuo' },
  { text: 'Cosa faresti con un milione di euro?', intensity: 1, category: 'Innocuo' },
  { text: 'Che canzone canti sotto la doccia?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e il tuo spuntino preferito a mezzanotte?', intensity: 1, category: 'Innocuo' },
  { text: 'Quale app usi di piu?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual era il tuo giocattolo preferito da bambino?', intensity: 1, category: 'Innocuo' },
  { text: 'Dove viaggeresti adesso se potessi?', intensity: 1, category: 'Innocuo' },
  // Divertente (1-2)
  { text: 'Qual e la cosa piu imbarazzante che ti sia successa in pubblico?', intensity: 2, category: 'Divertente' },
  { text: 'Hai mai ghostato qualcuno?', intensity: 2, category: 'Divertente' },
  { text: 'Qual e stato il tuo peggior taglio di capelli?', intensity: 1, category: 'Divertente' },
  { text: 'Hai mai mentito per non andare a lavorare?', intensity: 2, category: 'Divertente' },
  { text: 'Qual e la cosa piu stupida che hai cercato su Google?', intensity: 1, category: 'Divertente' },
  { text: 'Hai mai inviato un messaggio alla persona sbagliata?', intensity: 2, category: 'Divertente' },
  { text: 'Quale abitudine cerchi di nascondere?', intensity: 2, category: 'Divertente' },
  { text: 'Qual e stato il tuo momento piu imbarazzante sui social?', intensity: 2, category: 'Divertente' },
  { text: 'Hai mai barato a un gioco da tavolo?', intensity: 1, category: 'Divertente' },
  { text: 'Qual e la cosa piu strana nel tuo frigo?', intensity: 1, category: 'Divertente' },
  { text: 'Hai mai raccontato una barzelletta che non ha fatto ridere nessuno?', intensity: 1, category: 'Divertente' },
  { text: 'Qual e la scusa piu ridicola che hai mai usato?', intensity: 2, category: 'Divertente' },
  { text: 'Quale canzone imbarazzante hai nella tua playlist?', intensity: 1, category: 'Divertente' },
  { text: 'Hai mai parlato nel sonno? Cosa hai detto?', intensity: 1, category: 'Divertente' },
  { text: 'Qual e stato il tuo peggior appuntamento?', intensity: 2, category: 'Divertente' },
  { text: 'Che rumore fai quando nessuno ti ascolta?', intensity: 1, category: 'Divertente' },
  { text: 'Hai mai pianto dal ridere? Perche?', intensity: 1, category: 'Divertente' },
  { text: 'Qual e il tuo hobby piu strano?', intensity: 1, category: 'Divertente' },
  { text: 'Hai mai insultato qualcuno per sbaglio?', intensity: 2, category: 'Divertente' },
  { text: 'Qual e la cosa piu strana che hai mai mangiato?', intensity: 1, category: 'Divertente' },
  // Imbarazzante (2-3)
  { text: 'Chi e la tua cotta in questo gruppo?', intensity: 3, category: 'Imbarazzante' },
  { text: 'Hai mai stalkato qualcuno sui social?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Qual e il messaggio piu imbarazzante nella tua chat?', intensity: 3, category: 'Imbarazzante' },
  { text: 'Hai mai pianto guardando una pubblicita?', intensity: 1, category: 'Imbarazzante' },
  { text: 'Qual e stato il tuo momento piu imbarazzante a una festa?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Mostra la foto piu vecchia sul tuo telefono!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Quando hai pianto l\'ultima volta e perche?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Qual e il tuo desiderio piu segreto?', intensity: 3, category: 'Imbarazzante' },
  { text: 'Hai mai raccolto cibo da terra e mangiato?', intensity: 1, category: 'Imbarazzante' },
  { text: 'Quale serie imbarazzante guardi di nascosto?', intensity: 1, category: 'Imbarazzante' },
  { text: 'Chi in questo gruppo ha il miglior stile?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Qual e la cosa piu imbarazzante che hai fatto a scuola?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Hai mai pianto al cinema?', intensity: 1, category: 'Imbarazzante' },
  { text: 'Qual e la foto piu imbarazzante sul tuo telefono?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Hai mai scritto una lettera d\'amore?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Qual e stato il momento piu imbarazzante con i tuoi genitori?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Hai mai cantato a voce alta in pubblico?', intensity: 1, category: 'Imbarazzante' },
  { text: 'Qual e la cosa piu imbarazzante nella tua cronologia web?', intensity: 3, category: 'Imbarazzante' },
  { text: 'Ti sei mai dichiarato a qualcuno?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Qual e stato il tuo peggior errore di moda?', intensity: 2, category: 'Imbarazzante' },
  // Audace (3)
  { text: 'Cosa cambieresti se fossi invisibile per un giorno?', intensity: 3, category: 'Audace' },
  { text: 'Hai mai fatto qualcosa di illegale?', intensity: 3, category: 'Audace' },
  { text: 'Qual e la cosa piu coraggiosa che tu abbia mai fatto?', intensity: 2, category: 'Audace' },
  { text: 'Correresti nudo per la citta per 10.000 euro?', intensity: 3, category: 'Audace' },
  { text: 'Qual e la cosa piu pazza che tu abbia mai fatto a una festa?', intensity: 3, category: 'Audace' },
  { text: 'Hai mai rivelato il segreto di qualcuno?', intensity: 2, category: 'Audace' },
  { text: 'Qual e la cosa piu folle sulla tua bucket list?', intensity: 2, category: 'Audace' },
  { text: 'Ti lanceresti con il paracadute?', intensity: 1, category: 'Audace' },
  { text: 'Cosa faresti se non avessi paura?', intensity: 2, category: 'Audace' },
  { text: 'Hai fatto qualcosa che i tuoi genitori non sanno ancora?', intensity: 3, category: 'Audace' },

  // Nuove Verita (50)
  { text: 'Qual e stato il tuo primo pensiero stamattina?', intensity: 1, category: 'Innocuo' },
  { text: 'Quale serie potresti rivedere all\'infinito?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e la cosa piu romantica che hai fatto?', intensity: 2, category: 'Divertente' },
  { text: 'Hai mai cancellato un messaggio prima che fosse letto?', intensity: 2, category: 'Divertente' },
  { text: 'Qual e la cosa piu costosa che ti sei concesso?', intensity: 1, category: 'Innocuo' },
  { text: 'Quale celebrita trovi segretamente attraente?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Hai mai copiato a un esame?', intensity: 2, category: 'Divertente' },
  { text: 'Qual e il soprannome piu imbarazzante che hai avuto?', intensity: 1, category: 'Divertente' },
  { text: 'Quale abitudine vorresti perdere?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e la cosa piu coraggiosa che hai fatto per amore?', intensity: 2, category: 'Audace' },
  { text: 'Hai mai dato la colpa a qualcun altro quando era colpa tua?', intensity: 2, category: 'Divertente' },
  { text: 'Cosa cambieresti se tornassi ad avere 16 anni?', intensity: 2, category: 'Innocuo' },
  { text: 'Quale canzone ti fa sempre piangere?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e la cosa piu strana che hai ordinato online?', intensity: 1, category: 'Divertente' },
  { text: 'Hai un preferito in questo gruppo?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Qual e stato il tuo errore piu grande nell\'ultimo anno?', intensity: 2, category: 'Audace' },
  { text: 'Quale bugia ripeti piu spesso?', intensity: 2, category: 'Divertente' },
  { text: 'Qual e il tuo rituale segreto prima di dormire?', intensity: 1, category: 'Divertente' },
  { text: 'Hai mai chiamato qualcuno fingendo di essere un\'altra persona?', intensity: 2, category: 'Divertente' },
  { text: 'Cosa faresti se fossi del sesso opposto per un giorno?', intensity: 2, category: 'Divertente' },
  { text: 'Chi in questo gruppo ha la risata migliore?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e il cibo piu buono che tu abbia mai mangiato?', intensity: 1, category: 'Innocuo' },
  { text: 'Hai mai origliato qualcuno? Cosa hai sentito?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Quale film conosci a memoria?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e la tua paura piu grande?', intensity: 2, category: 'Audace' },
  { text: 'Hai mai dimenticato un appuntamento?', intensity: 1, category: 'Divertente' },
  { text: 'Cosa faresti se domani ti svegliassi famoso?', intensity: 1, category: 'Innocuo' },
  { text: 'Quale suono sai imitare meglio?', intensity: 1, category: 'Divertente' },
  { text: 'Qual e la cosa piu gentile che uno sconosciuto abbia fatto per te?', intensity: 1, category: 'Innocuo' },
  { text: 'Hai mai pianto nel sonno?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Cosa faresti con 3 desideri?', intensity: 1, category: 'Innocuo' },
  { text: 'Chi e la persona piu divertente che conosci?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e la scommessa piu pazza che tu abbia fatto?', intensity: 2, category: 'Divertente' },
  { text: 'Hai una parola preferita segreta?', intensity: 1, category: 'Divertente' },
  { text: 'Quale sarebbe il tuo ultimo pasto se potessi scegliere?', intensity: 1, category: 'Innocuo' },
  { text: 'Chi nel gruppo sarebbe il miglior coinquilino?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Cosa ti spaventava di piu da bambino?', intensity: 1, category: 'Innocuo' },
  { text: 'Hai mai chiamato qualcuno con il nome sbagliato?', intensity: 1, category: 'Divertente' },
  { text: 'Qual e il tuo sogno piu grande?', intensity: 2, category: 'Audace' },
  { text: 'Hai mai rotto qualcosa di valore e l\'hai nascosto?', intensity: 2, category: 'Divertente' },
  { text: 'Quale personaggio storico vorresti incontrare?', intensity: 1, category: 'Innocuo' },
  { text: 'Qual e il complimento piu strano che hai ricevuto?', intensity: 1, category: 'Divertente' },
  { text: 'Hai un account segreto sui social?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Qual e la tua fobia piu strana?', intensity: 1, category: 'Divertente' },
  { text: 'Quale tendenza trovi assolutamente ridicola?', intensity: 1, category: 'Divertente' },
  { text: 'A chi in questo gruppo affideresti un segreto?', intensity: 2, category: 'Imbarazzante' },
  { text: 'Qual e la cosa piu strana che hai visto a casa di qualcuno?', intensity: 2, category: 'Divertente' },
  { text: 'Hai mai scritto una recensione falsa su internet?', intensity: 2, category: 'Divertente' },
  { text: 'Cosa faresti se potessi essere qualcun altro per una settimana?', intensity: 2, category: 'Audace' },
  { text: 'Qual e la cosa piu imbarazzante sul tuo comodino?', intensity: 2, category: 'Imbarazzante' },
];

export const DARE_CHALLENGES: DareChallenge[] = [
  { text: 'Fai il tuo miglior verso di animale!', intensity: 1, category: 'Innocuo' },
  { text: 'Canta una filastrocca per 10 secondi!', intensity: 1, category: 'Innocuo' },
  { text: 'Fai 10 jumping jacks!', intensity: 1, category: 'Innocuo' },
  { text: 'Racconta una barzelletta!', intensity: 1, category: 'Innocuo' },
  { text: 'Parla come un robot per 30 secondi!', intensity: 1, category: 'Innocuo' },
  { text: 'Fai un selfie con la persona alla tua sinistra!', intensity: 1, category: 'Innocuo' },
  { text: 'Balla 15 secondi senza musica!', intensity: 1, category: 'Innocuo' },
  { text: 'Alzati e fai un inchino al gruppo!', intensity: 1, category: 'Innocuo' },
  { text: 'Fai la tua migliore faccia da opera!', intensity: 1, category: 'Innocuo' },
  { text: 'Disegna una casa ad occhi chiusi!', intensity: 1, category: 'Innocuo' },
  { text: 'Mantieni il contatto visivo con qualcuno per 30 secondi!', intensity: 1, category: 'Innocuo' },
  { text: 'Fai il plank per 20 secondi!', intensity: 1, category: 'Innocuo' },
  { text: 'Batti le mani a ritmo e fai seguire il gruppo!', intensity: 1, category: 'Innocuo' },
  { text: 'Alzati e gira su te stesso tre volte!', intensity: 1, category: 'Innocuo' },
  { text: 'Sussurra tutto per il prossimo minuto!', intensity: 1, category: 'Innocuo' },
  { text: 'Imita un famoso personaggio dei film!', intensity: 1, category: 'Innocuo' },
  { text: 'Compita il tuo nome al contrario ad alta voce!', intensity: 1, category: 'Innocuo' },
  { text: 'Fai una faccia buffa e mantienila per 10 secondi!', intensity: 1, category: 'Innocuo' },
  { text: 'Racconta al gruppo il tuo momento piu imbarazzante da bambino!', intensity: 1, category: 'Innocuo' },
  { text: 'Parla con un accento per il prossimo turno!', intensity: 1, category: 'Innocuo' },
  { text: 'Fai un moonwalk!', intensity: 2, category: 'Divertente' },
  { text: 'Fai 30 secondi di cabaret!', intensity: 2, category: 'Divertente' },
  { text: 'Imita un vip finche qualcuno indovina!', intensity: 2, category: 'Divertente' },
  { text: 'Balla come un papa a un matrimonio!', intensity: 1, category: 'Divertente' },
  { text: 'Rappa per 20 secondi sulla persona alla tua destra!', intensity: 2, category: 'Divertente' },
  { text: 'Recita una scena del tuo film preferito!', intensity: 2, category: 'Divertente' },
  { text: 'Fai la voce di un telegiornalista e leggi una notizia falsa!', intensity: 2, category: 'Divertente' },
  { text: 'Muoviti al rallentatore per 30 secondi!', intensity: 1, category: 'Divertente' },
  { text: 'Mostra il peggior passo di ballo che conosci!', intensity: 1, category: 'Divertente' },
  { text: 'Racconta una storia dove ogni parola inizia con la stessa lettera!', intensity: 2, category: 'Divertente' },
  { text: 'Alzati e tieni un discorso di ringraziamento come agli Oscar!', intensity: 2, category: 'Divertente' },
  { text: 'Fai un video TikTok (senza postarlo)!', intensity: 2, category: 'Divertente' },
  { text: 'Canta Tanti Auguri alla persona di fronte!', intensity: 1, category: 'Divertente' },
  { text: 'Parla come Yoda per 1 minuto!', intensity: 2, category: 'Divertente' },
  { text: 'Rifai il ballo piu famoso di un video musicale!', intensity: 2, category: 'Divertente' },
  { text: 'Fai una lettura drammatica dell\'ultimo messaggio sul tuo telefono!', intensity: 2, category: 'Divertente' },
  { text: 'Prova a non battere le palpebre per 30 secondi!', intensity: 1, category: 'Divertente' },
  { text: 'Di uno scioglilingua tre volte veloce!', intensity: 1, category: 'Divertente' },
  { text: 'Fai la verticale (o almeno provaci)!', intensity: 2, category: 'Divertente' },
  { text: 'Imita la tua emoji preferita con il viso!', intensity: 1, category: 'Divertente' },
  { text: 'Chiama qualcuno e digli "Ti amo!"', intensity: 3, category: 'Imbarazzante' },
  { text: 'Posta un selfie con la didascalia "Lunedi..."!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Lascia che il gruppo ti faccia una foto e la metta come profilo!', intensity: 3, category: 'Imbarazzante' },
  { text: 'Racconta il tuo peggior tentativo di flirtare!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Mostra al gruppo le ultime 3 foto del telefono!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Fai un complimento sincero a ogni persona del gruppo!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Lascia che qualcuno mandi un messaggio dal tuo telefono!', intensity: 3, category: 'Imbarazzante' },
  { text: 'Sali su una sedia e canta una canzone d\'amore!', intensity: 3, category: 'Imbarazzante' },
  { text: 'Lascia che il gruppo scelga il tuo outfit per domani!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Leggi ad alta voce l\'ultimo messaggio che hai inviato!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Fai una foto imbarazzante e mandala al tuo migliore amico!', intensity: 3, category: 'Imbarazzante' },
  { text: 'Dai un soprannome alla persona alla tua sinistra!', intensity: 1, category: 'Imbarazzante' },
  { text: 'Racconta la storia piu imbarazzante della scuola!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Fai una foto con l\'espressione piu ridicola!', intensity: 1, category: 'Imbarazzante' },
  { text: 'Scrivi e invia un messaggio poetico all\'ultimo contatto!', intensity: 3, category: 'Imbarazzante' },
  { text: 'Fai la tua migliore posa da modella!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Di al gruppo cosa pensi segretamente della persona di fronte!', intensity: 3, category: 'Imbarazzante' },
  { text: 'Lascia che il gruppo ti pettini!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Canta il ritornello della tua canzone preferita davanti a tutti!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Fai 5 flessioni contando in francese!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Chiama un amico e fingi di confessare qualcosa!', intensity: 3, category: 'Audace' },
  { text: 'Esci e grida "Sono il/la migliore!"', intensity: 3, category: 'Audace' },
  { text: 'Mangia qualcosa che il gruppo mescola per te!', intensity: 3, category: 'Audace' },
  { text: 'Fai beatbox per 30 secondi davanti al gruppo!', intensity: 2, category: 'Audace' },
  { text: 'Balla da solo 1 minuto con una canzone scelta dal gruppo!', intensity: 3, category: 'Audace' },
  { text: 'Lascia che il gruppo pubblichi un messaggio sul tuo stato!', intensity: 3, category: 'Audace' },
  { text: 'Parla in rima per i prossimi 3 turni!', intensity: 2, category: 'Audace' },
  { text: 'Fai un video TikTok e postalo davvero!', intensity: 3, category: 'Audace' },
  { text: 'Corri intorno all\'edificio gridando il tuo nome!', intensity: 3, category: 'Audace' },
  { text: 'Lascia che il gruppo ti dia un compito per domani!', intensity: 3, category: 'Audace' },
  { text: 'Parla come un pirata per 2 minuti!', intensity: 1, category: 'Innocuo' },
  { text: 'Fai il ballo del floss per 20 secondi!', intensity: 1, category: 'Divertente' },
  { text: 'Chiama qualcuno e chiedi se il suo frigo sta correndo!', intensity: 2, category: 'Divertente' },
  { text: 'Dichiara il tuo amore a un mobile!', intensity: 1, category: 'Divertente' },
  { text: 'Mangia un cucchiaio di senape o ketchup!', intensity: 2, category: 'Audace' },
  { text: 'Racconta una barzelletta — se nessuno ride, fai 10 flessioni!', intensity: 1, category: 'Divertente' },
  { text: 'Fai una foto con la faccia piu pazza e mettila come profilo!', intensity: 3, category: 'Imbarazzante' },
  { text: 'Parla in terza persona per i prossimi 2 turni!', intensity: 2, category: 'Divertente' },
  { text: 'Fai un trucco di magia inventato!', intensity: 1, category: 'Divertente' },
  { text: 'Fai un workout di 10 secondi contando in giapponese!', intensity: 1, category: 'Innocuo' },
  { text: 'Imita il tuo migliore amico — gli altri devono indovinare!', intensity: 2, category: 'Divertente' },
  { text: 'Manda un cuore all\'ultima persona che hai chiamato!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Fai uno striptease — ma solo con i calzini!', intensity: 2, category: 'Divertente' },
  { text: 'Canta l\'alfabeto il piu veloce possibile!', intensity: 1, category: 'Innocuo' },
  { text: 'Fai un inchino a ogni persona del gruppo!', intensity: 1, category: 'Innocuo' },
  { text: 'Lascia che il gruppo decida cosa bevi dopo!', intensity: 2, category: 'Audace' },
  { text: 'Parla a vanvera per 30 secondi come un telegiornale!', intensity: 1, category: 'Divertente' },
  { text: 'Fai suoni da alieno per 15 secondi!', intensity: 1, category: 'Divertente' },
  { text: 'Alzati e tieni un comizio — ti candidi a sindaco!', intensity: 2, category: 'Divertente' },
  { text: 'Manda al 3° contatto della lista "Mi manchi"!', intensity: 3, category: 'Imbarazzante' },
  { text: 'Balla la Macarena!', intensity: 1, category: 'Divertente' },
  { text: 'Parla per 1 minuto senza usare la lettera E!', intensity: 2, category: 'Divertente' },
  { text: 'Fai un selfie ad occhi chiusi e postalo!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Mima come ti alzi la mattina — al rallentatore!', intensity: 1, category: 'Divertente' },
  { text: 'Suona la batteria immaginaria con un brano scelto dal gruppo!', intensity: 1, category: 'Divertente' },
  { text: 'Fai versi da neonato per 15 secondi!', intensity: 1, category: 'Divertente' },
  { text: 'Tieni un discorso d\'addio drammatico come se andassi in esilio!', intensity: 2, category: 'Divertente' },
  { text: 'Lascia che la persona alla tua destra ti pettini!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Fai la tua migliore sfilata per la stanza!', intensity: 2, category: 'Divertente' },
  { text: 'Racconta una storia dove tu sei l\'eroe!', intensity: 1, category: 'Innocuo' },
  { text: 'Parla come un telegiornalista e commenta l\'ultimo turno!', intensity: 2, category: 'Divertente' },
  { text: 'Fai tai chi per 30 secondi!', intensity: 1, category: 'Innocuo' },
  { text: 'Porta a spasso un cane invisibile per tutta la stanza!', intensity: 1, category: 'Divertente' },
  { text: 'Di "Ti amo" alla persona di fronte senza ridere!', intensity: 3, category: 'Imbarazzante' },
  { text: 'Balla un valzer — da solo!', intensity: 1, category: 'Divertente' },
  { text: 'Prova uno scioglilingua 5 volte di fila!', intensity: 1, category: 'Innocuo' },
  { text: 'Corri fino all\'albero piu vicino e torna!', intensity: 1, category: 'Innocuo' },
  { text: 'Penzola a testa in giu dal divano per 30 secondi!', intensity: 2, category: 'Divertente' },
  { text: 'Vai alla finestra e saluta i passanti!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Pubblica una story Instagram con un filtro imbarazzante!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Di a ogni persona del gruppo cosa ammiri di piu di lei!', intensity: 2, category: 'Innocuo' },
  { text: 'Racconta una barzelletta in un\'altra lingua — con accento esagerato!', intensity: 1, category: 'Divertente' },
  { text: 'Fai il plank e mantienilo finche non rispondi alla prossima domanda!', intensity: 2, category: 'Audace' },
  { text: 'Guarda la persona alla tua sinistra negli occhi e dille qualcosa di carino — senza ridere!', intensity: 2, category: 'Imbarazzante' },
  { text: 'Dirigi un\'orchestra invisibile!', intensity: 1, category: 'Divertente' },
  { text: 'Chiama l\'ultimo contatto del telefono e digli: Sei il mio eroe!', intensity: 3, category: 'Audace' },
  { text: 'Fai riscaldamento come un atleta professionista — 30 secondi!', intensity: 1, category: 'Innocuo' },
  { text: 'Prova a non battere le palpebre per 20 secondi mentre gli altri ti distraggono!', intensity: 1, category: 'Divertente' },
  { text: 'Canta il ritornello di una filastrocca con voce da soprano!', intensity: 2, category: 'Divertente' },
  { text: 'Lascia che qualcuno scriva una parola sul tuo braccio!', intensity: 2, category: 'Imbarazzante' },
];
