export interface TruthQuestion {
  text: string;
  intensity: 1 | 2 | 3;
  category: string;
}

export interface DareChallenge {
  text: string;
  intensity: 1 | 2 | 3;
  category: string;
}

export const TRUTH_QUESTIONS: TruthQuestion[] = [
  { text: 'Jaka piosenka jest twoim guilty pleasure?', intensity: 1, category: 'Niewinne' },
  { text: 'Kim chciales byc, jak byles maly?', intensity: 1, category: 'Niewinne' },
  { text: 'Jakie jedzenie moglbys jesc codziennie?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaki jest twoj ulubiony zenujacy film?', intensity: 1, category: 'Niewinne' },
  { text: 'Co ostatnio cie rozsmieszylo?', intensity: 1, category: 'Niewinne' },
  { text: 'Gdybys byl zwierzeciem, jakim bys byl?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaka jest najbardziej bezuzyteczna umiejetnosc, ktora posiadasz?', intensity: 1, category: 'Niewinne' },
  { text: 'Jakiego celebryte chcialbys poznac?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaki byl najlepszy prezent, jaki dostales?', intensity: 1, category: 'Niewinne' },
  { text: 'Gdybys mial supermoce, jakie by to byly?', intensity: 1, category: 'Niewinne' },
  { text: 'Jakie jest twoje ulubione miejsce na swiecie?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaki serial ostatnio obejrzales na raz?', intensity: 1, category: 'Niewinne' },
  { text: 'Co jest najlepsze w twojej pracy?', intensity: 1, category: 'Niewinne' },
  { text: 'Czy masz ukryty talent?', intensity: 1, category: 'Niewinne' },
  { text: 'Co zrobilbys z milionem euro?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaka piosenke spiewasz pod prysznicem?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaki jest twoj ulubiony nocny przekaski?', intensity: 1, category: 'Niewinne' },
  { text: 'Jakiej aplikacji uzywasz najczesciej?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaka byla twoja ulubiona zabawka w dziecinstwie?', intensity: 1, category: 'Niewinne' },
  { text: 'Dokad pojechalbys teraz, gdybys mogl?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaka jest najbardziej zenujaaca rzecz, ktora ci sie przydarza publicznie?', intensity: 2, category: 'Smieszne' },
  { text: 'Czy kiedykolwiek zghosstowales kogos?', intensity: 2, category: 'Smieszne' },
  { text: 'Jaka byla twoja najgorsza fryzura?', intensity: 1, category: 'Smieszne' },
  { text: 'Czy kiedykolwiek skalamales, zeby nie isc do pracy?', intensity: 2, category: 'Smieszne' },
  { text: 'Co najglupszego googlowales?', intensity: 1, category: 'Smieszne' },
  { text: 'Czy kiedykolwiek wyslales wiadomosc do zlej osoby?', intensity: 2, category: 'Smieszne' },
  { text: 'Jaki nawyk proboujesz ukryc?', intensity: 2, category: 'Smieszne' },
  { text: 'Jaki byl twoj najbardziej zenujacy moment w mediach spolecznosciowych?', intensity: 2, category: 'Smieszne' },
  { text: 'Czy kiedykolwiek oszukiwales w grze planszowej?', intensity: 1, category: 'Smieszne' },
  { text: 'Co najdziwniejszego masz w lodowce?', intensity: 1, category: 'Smieszne' },
  { text: 'Czy kiedykolwiek opowiedziales zart, z ktorego nikt sie nie smial?', intensity: 1, category: 'Smieszne' },
  { text: 'Jaka jest najsmieszniejsza wymowka, jakiej uzyles?', intensity: 2, category: 'Smieszne' },
  { text: 'Jaka zenujaca piosenka jest na twojej playliscie?', intensity: 1, category: 'Smieszne' },
  { text: 'Czy kiedykolwiek mowiles przez sen? Co powiedziales?', intensity: 1, category: 'Smieszne' },
  { text: 'Jaka byla twoja najgorsza randka?', intensity: 2, category: 'Smieszne' },
  { text: 'Jaki dzwiek wydajesz, gdy nikt nie slucha?', intensity: 1, category: 'Smieszne' },
  { text: 'Czy kiedykolwiek plakales ze smiechu? Dlaczego?', intensity: 1, category: 'Smieszne' },
  { text: 'Jakie jest twoje najdziwniejsze hobby?', intensity: 1, category: 'Smieszne' },
  { text: 'Czy kiedykolwiek przypadkiem kogos obraziles?', intensity: 2, category: 'Smieszne' },
  { text: 'Co najdziwniejszego jadlez?', intensity: 1, category: 'Smieszne' },
  { text: 'Kto jest twoim crushem w tej grupie?', intensity: 3, category: 'Zenujace' },
  { text: 'Czy kiedykolwiek stalkowales kogos w mediach spolecznosciowych?', intensity: 2, category: 'Zenujace' },
  { text: 'Jaka jest najbardziej zenujaca wiadomosc w twoim czacie?', intensity: 3, category: 'Zenujace' },
  { text: 'Czy kiedykolwiek plakales ogladajac reklame?', intensity: 1, category: 'Zenujace' },
  { text: 'Jaki byl twoj najbardziej zenujacy moment na imprezie?', intensity: 2, category: 'Zenujace' },
  { text: 'Pokaz najstarsze zdjecie na swoim telefonie!', intensity: 2, category: 'Zenujace' },
  { text: 'Kiedy ostatnio plakales i dlaczego?', intensity: 2, category: 'Zenujace' },
  { text: 'Jakie jest twoje najbardziej skryte zyczenie?', intensity: 3, category: 'Zenujace' },
  { text: 'Czy kiedykolwiek podniosles jedzenie z podlogi i zjadles?', intensity: 1, category: 'Zenujace' },
  { text: 'Jaki zenujacy serial ogladas w tajemnicy?', intensity: 1, category: 'Zenujace' },
  { text: 'Kto w tej grupie ma najlepszy styl?', intensity: 2, category: 'Zenujace' },
  { text: 'Co bylo najbardziej zenujaca rzecza, ktora zrobiles na lekcji?', intensity: 2, category: 'Zenujace' },
  { text: 'Czy kiedykolwiek plakales w kinie?', intensity: 1, category: 'Zenujace' },
  { text: 'Jakie jest najbardziej zenujace zdjecie na twoim telefonie?', intensity: 2, category: 'Zenujace' },
  { text: 'Czy kiedykolwiek napisales list milosny?', intensity: 2, category: 'Zenujace' },
  { text: 'Jaki byl najbardziej zenujacy moment z rodzicami?', intensity: 2, category: 'Zenujace' },
  { text: 'Czy kiedykolwiek spiewales glosno publicznie?', intensity: 1, category: 'Zenujace' },
  { text: 'Co jest najbardziej zenujacego w twojej historii przegladarki?', intensity: 3, category: 'Zenujace' },
  { text: 'Czy kiedykolwiek wyznales komus uczucia?', intensity: 2, category: 'Zenujace' },
  { text: 'Jaki byl twoj najwiekszy modowy fail?', intensity: 2, category: 'Zenujace' },
  { text: 'Co zrobilbys, gdybys byl niewidzialny przez jeden dzien?', intensity: 3, category: 'Odwazne' },
  { text: 'Czy kiedykolwiek zrobiles cos nielegalnego?', intensity: 3, category: 'Odwazne' },
  { text: 'Co bylo najodwazniejsza rzecza, jaka zrobiles?', intensity: 2, category: 'Odwazne' },
  { text: 'Czy przebieglbys nago przez miasto za 10 000 euro?', intensity: 3, category: 'Odwazne' },
  { text: 'Co bylo najdziksze, co zrobiles na imprezie?', intensity: 3, category: 'Odwazne' },
  { text: 'Czy kiedykolwiek zdradziles czys sekret?', intensity: 2, category: 'Odwazne' },
  { text: 'Co jest najszalensza rzecza na twojej bucket liscie?', intensity: 2, category: 'Odwazne' },
  { text: 'Czy skoczylebys ze spadochronem?', intensity: 1, category: 'Odwazne' },
  { text: 'Co zrobilbys, gdybys nie mial strachu?', intensity: 2, category: 'Odwazne' },
  { text: 'Czy zrobiles cos, o czym twoi rodzice nie wiedza?', intensity: 3, category: 'Odwazne' },
  { text: 'Jaka byla twoja pierwsza mysl dzis rano?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaki serial moglbys ogladac w kolko?', intensity: 1, category: 'Niewinne' },
  { text: 'Co najbardziej romantycznego zrobiles?', intensity: 2, category: 'Smieszne' },
  { text: 'Czy kiedykolwiek usunales wiadomosc zanim zostala przeczytana?', intensity: 2, category: 'Smieszne' },
  { text: 'Co najdrozszego sobie kupiles?', intensity: 1, category: 'Niewinne' },
  { text: 'Jakiego celebryte potajemnie uwazasz za atrakcyjnego?', intensity: 2, category: 'Zenujace' },
  { text: 'Czy kiedykolwiek sciagales na egzaminie?', intensity: 2, category: 'Smieszne' },
  { text: 'Jaki jest najbardziej zenujacy przezwisko, jakie miales?', intensity: 1, category: 'Smieszne' },
  { text: 'Jakiego nawyku chcialbys sie pozbyc?', intensity: 1, category: 'Niewinne' },
  { text: 'Co najodwazniejszego zrobiles dla milosci?', intensity: 2, category: 'Odwazne' },
  { text: 'Czy kiedykolwiek zwaliles wine na kogos, choc to byla twoja wina?', intensity: 2, category: 'Smieszne' },
  { text: 'Co zmienilebys, gdybys znow mial 16 lat?', intensity: 2, category: 'Niewinne' },
  { text: 'Jaka piosenka zawsze cie rozczula?', intensity: 1, category: 'Niewinne' },
  { text: 'Co najdziwniejszego zamowiles przez internet?', intensity: 1, category: 'Smieszne' },
  { text: 'Masz ulubiona osobe w tej grupie?', intensity: 2, category: 'Zenujace' },
  { text: 'Jaki byl twoj najwiekszy blad w ostatnim roku?', intensity: 2, category: 'Odwazne' },
  { text: 'Jakie klamstwo powtarzasz najczesciej?', intensity: 2, category: 'Smieszne' },
  { text: 'Jaki jest twoj sekretny rytuaal przed snem?', intensity: 1, category: 'Smieszne' },
  { text: 'Czy kiedykolwiek zadzwoniles do kogos udajac inna osobe?', intensity: 2, category: 'Smieszne' },
  { text: 'Co zrobilbys, gdybys na jeden dzien byl plci przeciwnej?', intensity: 2, category: 'Smieszne' },
  { text: 'Kto w tej grupie ma najlepszy smiech?', intensity: 1, category: 'Niewinne' },
  { text: 'Jakie bylo najsmaczniejsze jedzenie, jakie jadless?', intensity: 1, category: 'Niewinne' },
  { text: 'Czy kiedykolwiek podsluchiwales kogos? Co uslyszales?', intensity: 2, category: 'Zenujace' },
  { text: 'Jaki film znasz na pamiec?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaki jest twoj najwiekszy strach?', intensity: 2, category: 'Odwazne' },
  { text: 'Czy kiedykolwiek zapomnialesz o umowionym spotkaniu?', intensity: 1, category: 'Smieszne' },
  { text: 'Co zrobilbys, gdybys jutro obudzil sie slawny?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaki dzwiek potrafisz najlepiej nasledowac?', intensity: 1, category: 'Smieszne' },
  { text: 'Co najszlachetniejszego zrobil dla ciebie obcy czlowiek?', intensity: 1, category: 'Niewinne' },
  { text: 'Czy kiedykolwiek plakales przez sen?', intensity: 2, category: 'Zenujace' },
  { text: 'Co zrobilbys z trzema zyczeniami?', intensity: 1, category: 'Niewinne' },
  { text: 'Kto jest najzabawniejsza osoba, jaka znasz?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaki jest najszaleonszy zaklad, jaki przyjales?', intensity: 2, category: 'Smieszne' },
  { text: 'Masz tajne ulubione slowo?', intensity: 1, category: 'Smieszne' },
  { text: 'Jaki bylby twoj ostatni posilek, gdybys mogl wybrac?', intensity: 1, category: 'Niewinne' },
  { text: 'Kto z grupy bylby najlepszym wspollokatorem?', intensity: 2, category: 'Zenujace' },
  { text: 'Czego najbardziej bales sie jako dziecko?', intensity: 1, category: 'Niewinne' },
  { text: 'Czy kiedykolwiek zwrociles sie do kogos blednym imieniem?', intensity: 1, category: 'Smieszne' },
  { text: 'Jakie jest twoje najwieksze marzenie?', intensity: 2, category: 'Odwazne' },
  { text: 'Czy kiedykolwiek zniszczyles cos cennego i to ukryles?', intensity: 2, category: 'Smieszne' },
  { text: 'Jaka postac historyczna chcialbys poznac?', intensity: 1, category: 'Niewinne' },
  { text: 'Jaki jest najdziwniejszy komplement, jaki dostales?', intensity: 1, category: 'Smieszne' },
  { text: 'Czy masz tajne konto w mediach spolecznosciowych?', intensity: 2, category: 'Zenujace' },
  { text: 'Jaka jest twoja najdziwniejsza fobia?', intensity: 1, category: 'Smieszne' },
  { text: 'Jaki trend uwazasz za calkowicie smieszny?', intensity: 1, category: 'Smieszne' },
  { text: 'Komu z grupy powierzylbys sekret?', intensity: 2, category: 'Zenujace' },
  { text: 'Co najdziwniejszego widziales w czyims domu?', intensity: 2, category: 'Smieszne' },
  { text: 'Czy kiedykolwiek napisales falszywa recenzje w internecie?', intensity: 2, category: 'Smieszne' },
  { text: 'Co zrobilbys, gdybys mogl byc kims innym przez tydzien?', intensity: 2, category: 'Odwazne' },
  { text: 'Co najbardziej zenujacego lezy na twoim stoliku nocnym?', intensity: 2, category: 'Zenujace' },
];

export const DARE_CHALLENGES: DareChallenge[] = [
  { text: 'Zrob swoj najlepszy odglos zwierzecia!', intensity: 1, category: 'Niewinne' },
  { text: 'Spiewaj piosenke dla dzieci przez 10 sekund!', intensity: 1, category: 'Niewinne' },
  { text: 'Zrob 10 pajacykow!', intensity: 1, category: 'Niewinne' },
  { text: 'Opowiedz dowcip!', intensity: 1, category: 'Niewinne' },
  { text: 'Mow jak robot przez 30 sekund!', intensity: 1, category: 'Niewinne' },
  { text: 'Zrob selfie z osoba po lewej!', intensity: 1, category: 'Niewinne' },
  { text: 'Tancz przez 15 sekund bez muzyki!', intensity: 1, category: 'Niewinne' },
  { text: 'Wstan i uklonij sie grupie!', intensity: 1, category: 'Niewinne' },
  { text: 'Zrob swoja najlepsza mine operowa!', intensity: 1, category: 'Niewinne' },
  { text: 'Narysuj dom z zamknietymi oczami!', intensity: 1, category: 'Niewinne' },
  { text: 'Utrzymaj kontakt wzrokowy z kims przez 30 sekund!', intensity: 1, category: 'Niewinne' },
  { text: 'Zrob deske przez 20 sekund!', intensity: 1, category: 'Niewinne' },
  { text: 'Klaszcz rytmicznie i spraw, by grupa dolaczyla!', intensity: 1, category: 'Niewinne' },
  { text: 'Wstan i obróc sie trzy razy w kolko!', intensity: 1, category: 'Niewinne' },
  { text: 'Szeptaj wszystko przez nastepna minute!', intensity: 1, category: 'Niewinne' },
  { text: 'Nasladuj slawna postac z filmu!', intensity: 1, category: 'Niewinne' },
  { text: 'Przeliteruj swoje imie od tylu na glos!', intensity: 1, category: 'Niewinne' },
  { text: 'Zrob smieszna mine i trzymaj ja 10 sekund!', intensity: 1, category: 'Niewinne' },
  { text: 'Opowiedz grupie swoj najbardziej zenujacy moment z dziecinstwa!', intensity: 1, category: 'Niewinne' },
  { text: 'Mow z akcentem przez nastepna runde!', intensity: 1, category: 'Niewinne' },
  { text: 'Zrob moonwalk!', intensity: 2, category: 'Smieszne' },
  { text: 'Zrob 30 sekund stand-up comedy!', intensity: 2, category: 'Smieszne' },
  { text: 'Nasladuj celebryte, az ktos zgadnie!', intensity: 2, category: 'Smieszne' },
  { text: 'Tancz jak tata na weselu!', intensity: 1, category: 'Smieszne' },
  { text: 'Rapuj 20 sekund o osobie po prawej!', intensity: 2, category: 'Smieszne' },
  { text: 'Odegraj scene z ulubionego filmu!', intensity: 2, category: 'Smieszne' },
  { text: 'Zrob glos prezentera wiadomosci i przeczytaj fakeowa wiadomosc!', intensity: 2, category: 'Smieszne' },
  { text: 'Poruszaj sie w zwolnionym tempie przez 30 sekund!', intensity: 1, category: 'Smieszne' },
  { text: 'Pokaz najgorszy krok taneczny, jaki znasz!', intensity: 1, category: 'Smieszne' },
  { text: 'Opowiedz historie, gdzie kazde slowo zaczyna sie ta sama litera!', intensity: 2, category: 'Smieszne' },
  { text: 'Wstan i wyglos przemowienie jak na Oscarach!', intensity: 2, category: 'Smieszne' },
  { text: 'Nagraj filmik na TikToka (nie publikuj go)!', intensity: 2, category: 'Smieszne' },
  { text: 'Zaspiewaj Happy Birthday osobie naprzeciwko!', intensity: 1, category: 'Smieszne' },
  { text: 'Mow jak Yoda przez 1 minute!', intensity: 2, category: 'Smieszne' },
  { text: 'Odtworz najslynniejszy taniec z klipu!', intensity: 2, category: 'Smieszne' },
  { text: 'Zrob dramatyczne czytanie ostatniego SMSa na telefonie!', intensity: 2, category: 'Smieszne' },
  { text: 'Sprobuj nie mrugac przez 30 sekund!', intensity: 1, category: 'Smieszne' },
  { text: 'Powiedz lamaniec jezykowy trzy razy szybko!', intensity: 1, category: 'Smieszne' },
  { text: 'Zrob stojke na rekach (lub sprobuj)!', intensity: 2, category: 'Smieszne' },
  { text: 'Nasladuj swoje ulubione emoji twarz!', intensity: 1, category: 'Smieszne' },
  { text: 'Zadzwon do kogos i powiedz "Kocham Cie!"', intensity: 3, category: 'Zenujace' },
  { text: 'Wrzuc selfie z podpisem "Poniedzialek..."!', intensity: 2, category: 'Zenujace' },
  { text: 'Pozwol grupie zrobic ci zdjecie i ustawic je jako profilowe!', intensity: 3, category: 'Zenujace' },
  { text: 'Opowiedz swoja najwieksza wpadke przy podrywaniu!', intensity: 2, category: 'Zenujace' },
  { text: 'Pokaz grupie 3 ostatnie zdjecia w telefonie!', intensity: 2, category: 'Zenujace' },
  { text: 'Powiedz kazdemu w grupie szczery komplement!', intensity: 2, category: 'Zenujace' },
  { text: 'Pozwol komus wyslac wiadomosc z twojego telefonu!', intensity: 3, category: 'Zenujace' },
  { text: 'Wstan na krzeslo i spiewaj piosenke milosna!', intensity: 3, category: 'Zenujace' },
  { text: 'Pozwol grupie wybrac twoj stroj na jutro!', intensity: 2, category: 'Zenujace' },
  { text: 'Przeczytaj na glos ostatnia wiadomosc, ktora wyslales!', intensity: 2, category: 'Zenujace' },
  { text: 'Zrob zenujace zdjecie i wyslij najlepszemu przyjacielowi!', intensity: 3, category: 'Zenujace' },
  { text: 'Daj przezwisko osobie po lewej!', intensity: 1, category: 'Zenujace' },
  { text: 'Opowiedz najbardziej zenujaca historie ze szkoly!', intensity: 2, category: 'Zenujace' },
  { text: 'Zrob zdjecie z najsmieszniejsza mina!', intensity: 1, category: 'Zenujace' },
  { text: 'Napisz i wyslij poetycka wiadomosc do ostatniego kontaktu!', intensity: 3, category: 'Zenujace' },
  { text: 'Zrob najlepsza poze modelki!', intensity: 2, category: 'Zenujace' },
  { text: 'Powiedz grupie, co naprawde myslisz o osobie naprzeciwko!', intensity: 3, category: 'Zenujace' },
  { text: 'Pozwol grupie ci uczesac!', intensity: 2, category: 'Zenujace' },
  { text: 'Zaspiewaj refren ulubionej piosenki przed wszystkimi!', intensity: 2, category: 'Zenujace' },
  { text: 'Zrob 5 pompek liczac po francusku!', intensity: 2, category: 'Zenujace' },
  { text: 'Zadzwon do przyjaciela i udawaj, ze cos wyznajesz!', intensity: 3, category: 'Odwazne' },
  { text: 'Wyjdz na zewnatrz i krzyknij "Jestem najlepszy/a!"', intensity: 3, category: 'Odwazne' },
  { text: 'Zjedz cos, co grupa ci przygotuje!', intensity: 3, category: 'Odwazne' },
  { text: 'Beatboxuj 30 sekund przed grupa!', intensity: 2, category: 'Odwazne' },
  { text: 'Tancz sam 1 minute do piosenki wybranej przez grupe!', intensity: 3, category: 'Odwazne' },
  { text: 'Pozwol grupie wrzucic wiadomosc na twoj status!', intensity: 3, category: 'Odwazne' },
  { text: 'Mow w rymach przez nastepne 3 rundy!', intensity: 2, category: 'Odwazne' },
  { text: 'Nagraj filmik na TikToka i opublikuj go naprawde!', intensity: 3, category: 'Odwazne' },
  { text: 'Obiedz budynek krzyczac swoje imie!', intensity: 3, category: 'Odwazne' },
  { text: 'Pozwol grupie dac ci zadanie do wykonania jutro!', intensity: 3, category: 'Odwazne' },
  { text: 'Mow jak pirat przez 2 minuty!', intensity: 1, category: 'Niewinne' },
  { text: 'Tancz floss przez 20 sekund!', intensity: 1, category: 'Smieszne' },
  { text: 'Zadzwon do kogos i zapytaj, czy jego lodowka biega!', intensity: 2, category: 'Smieszne' },
  { text: 'Wyznaj milosc meblowi!', intensity: 1, category: 'Smieszne' },
  { text: 'Zjedz lyzke musztardy lub ketchupu!', intensity: 2, category: 'Odwazne' },
  { text: 'Opowiedz dowcip — jesli nikt sie nie zasmieje, zrob 10 pompek!', intensity: 1, category: 'Smieszne' },
  { text: 'Zrob zdjecie z najszalensza mina i ustaw jako profilowe!', intensity: 3, category: 'Zenujace' },
  { text: 'Mow o sobie w trzeciej osobie przez 2 nastepne rundy!', intensity: 2, category: 'Smieszne' },
  { text: 'Wykonaj wymyslona sztuczke magiczna!', intensity: 1, category: 'Smieszne' },
  { text: 'Zrob 10-sekundowy trening liczac po japonsku!', intensity: 1, category: 'Niewinne' },
  { text: 'Nasladuj najlepszego przyjacela — reszta musi zgadnac!', intensity: 2, category: 'Smieszne' },
  { text: 'Wyslij serduszko ostatniej osobie, do ktorej dzwoniles!', intensity: 2, category: 'Zenujace' },
  { text: 'Zrob striptiz — ale tylko ze skarpetkami!', intensity: 2, category: 'Smieszne' },
  { text: 'Zaspiewaj alfabet jak najszybciej!', intensity: 1, category: 'Niewinne' },
  { text: 'Uklonij sie kazdej osobie w grupie!', intensity: 1, category: 'Niewinne' },
  { text: 'Pozwol grupie zdecydowac, co pijesz nastepne!', intensity: 2, category: 'Odwazne' },
  { text: 'Mow bzdury przez 30 sekund jakbys czytaw wiadomosci!', intensity: 1, category: 'Smieszne' },
  { text: 'Wydawaj dzwieki kosmity przez 15 sekund!', intensity: 1, category: 'Smieszne' },
  { text: 'Wstan i wyglos przemowienie wyborcze — kandudujesz na burmistrza!', intensity: 2, category: 'Smieszne' },
  { text: 'Wyslij 3. kontaktowi na liscie "Tesknie za toba"!', intensity: 3, category: 'Zenujace' },
  { text: 'Zatancz Macarene!', intensity: 1, category: 'Smieszne' },
  { text: 'Mow przez 1 minute bez uzywania litery E!', intensity: 2, category: 'Smieszne' },
  { text: 'Zrob selfie z zamknietymi oczami i opublikuj!', intensity: 2, category: 'Zenujace' },
  { text: 'Pokaz jak wstajesz rano — w zwolnionym tempie!', intensity: 1, category: 'Smieszne' },
  { text: 'Zagraj na powietrznej perkusji do piosenki wybranej przez grupe!', intensity: 1, category: 'Smieszne' },
  { text: 'Wydawaj dzwieki niemowlecia przez 15 sekund!', intensity: 1, category: 'Smieszne' },
  { text: 'Wyglos dramatyczna mowe pozegnalna jakbys szedl na wygnanie!', intensity: 2, category: 'Smieszne' },
  { text: 'Pozwol osobie po prawej uczesac ci wlosy!', intensity: 2, category: 'Zenujace' },
  { text: 'Zrob najlepszy catwalk po pokoju!', intensity: 2, category: 'Smieszne' },
  { text: 'Opowiedz historie, w ktorej jestes bohaterem!', intensity: 1, category: 'Niewinne' },
  { text: 'Mow jak prezenter wiadomosci i relacjonuj ostatnia runde!', intensity: 2, category: 'Smieszne' },
  { text: 'Zrob tai chi przez 30 sekund!', intensity: 1, category: 'Niewinne' },
  { text: 'Wyprowadz niewidzialnego psa po calym pokoju!', intensity: 1, category: 'Smieszne' },
  { text: 'Powiedz "Kocham cie" do osoby naprzeciwko bez smiechu!', intensity: 3, category: 'Zenujace' },
  { text: 'Zatancz walca — sam!', intensity: 1, category: 'Smieszne' },
  { text: 'Sprobuj lamaniec jezykowy 5 razy z rzedu!', intensity: 1, category: 'Niewinne' },
  { text: 'Pobiegnij do najblizszego drzewa i wroc!', intensity: 1, category: 'Niewinne' },
  { text: 'Zwis glowa w dol z kanapy przez 30 sekund!', intensity: 2, category: 'Smieszne' },
  { text: 'Idz do okna i pomachaj przechodniom!', intensity: 2, category: 'Zenujace' },
  { text: 'Opublikuj story na Instagramie z zenujacym filtrem!', intensity: 2, category: 'Zenujace' },
  { text: 'Powiedz kazdemu w grupie, co w nim najbardziej podziwiasz!', intensity: 2, category: 'Niewinne' },
  { text: 'Opowiedz dowcip w innym jezyku — z przesadnym akcentem!', intensity: 1, category: 'Smieszne' },
  { text: 'Zrob deske i trzymaj ja, az odpowiesz na nastepne pytanie!', intensity: 2, category: 'Odwazne' },
  { text: 'Spojrz osobie po lewej w oczy i powiedz cos milego — bez smiechu!', intensity: 2, category: 'Zenujace' },
  { text: 'Dyryguj niewidzialna orkiestra!', intensity: 1, category: 'Smieszne' },
  { text: 'Zadzwon do ostatniego kontaktu i powiedz: Jestes moim bohaterem!', intensity: 3, category: 'Odwazne' },
  { text: 'Zrob rozgrzewke jak profesjonalny sportowiec — 30 sekund!', intensity: 1, category: 'Niewinne' },
  { text: 'Sprobuj nie mrugac 20 sekund, gdy inni cie rozpraszaja!', intensity: 1, category: 'Smieszne' },
  { text: 'Zaspiewaj refren dzieciecej piosenki glosem operowym!', intensity: 2, category: 'Smieszne' },
  { text: 'Pozwol komus napisac slowo na twoim ramieniu!', intensity: 2, category: 'Zenujace' },
];
