export interface TruthQuestion {
  text: string;
  intensity: 1 | 2 | 3;
  category: string;
}

export interface DareChallenge {
  text: string;
  intensity: 1 | 2 | 3;
  category: string;
}

export const TRUTH_QUESTIONS: TruthQuestion[] = [
  // Harmless (1)
  { text: 'What is a guilty pleasure song you secretly listen to?', intensity: 1, category: 'Harmless' },
  { text: 'What did you want to be when you grew up?', intensity: 1, category: 'Harmless' },
  { text: 'What food could you eat every single day?', intensity: 1, category: 'Harmless' },
  { text: 'What is your guilty pleasure movie?', intensity: 1, category: 'Harmless' },
  { text: 'What was the last thing that made you laugh?', intensity: 1, category: 'Harmless' },
  { text: 'If you were an animal, which one would you be?', intensity: 1, category: 'Harmless' },
  { text: 'What is the most useless skill you have?', intensity: 1, category: 'Harmless' },
  { text: 'Which celebrity would you love to meet?', intensity: 1, category: 'Harmless' },
  { text: 'What was the best gift you ever received?', intensity: 1, category: 'Harmless' },
  { text: 'If you had a superpower, what would it be?', intensity: 1, category: 'Harmless' },
  { text: 'What is your favorite place in the world?', intensity: 1, category: 'Harmless' },
  { text: 'What series did you last binge-watch?', intensity: 1, category: 'Harmless' },
  { text: 'What is the best thing about your job?', intensity: 1, category: 'Harmless' },
  { text: 'Do you have a hidden talent?', intensity: 1, category: 'Harmless' },
  { text: 'What would you do with a million dollars?', intensity: 1, category: 'Harmless' },
  { text: 'What song do you sing in the shower?', intensity: 1, category: 'Harmless' },
  { text: 'What is your favorite midnight snack?', intensity: 1, category: 'Harmless' },
  { text: 'Which app do you use the most?', intensity: 1, category: 'Harmless' },
  { text: 'What was your favorite toy as a kid?', intensity: 1, category: 'Harmless' },
  { text: 'Where would you travel right now if you could?', intensity: 1, category: 'Harmless' },
  // Funny (1-2)
  { text: 'What is the most embarrassing thing that happened to you in public?', intensity: 2, category: 'Funny' },
  { text: 'Have you ever ghosted someone?', intensity: 2, category: 'Funny' },
  { text: 'What was your worst haircut ever?', intensity: 1, category: 'Funny' },
  { text: 'Have you ever lied to get out of work?', intensity: 2, category: 'Funny' },
  { text: 'What is the dumbest thing you have ever googled?', intensity: 1, category: 'Funny' },
  { text: 'Have you ever sent a text to the wrong person?', intensity: 2, category: 'Funny' },
  { text: 'What habit do you try to hide?', intensity: 2, category: 'Funny' },
  { text: 'What was your most embarrassing social media moment?', intensity: 2, category: 'Funny' },
  { text: 'Have you ever cheated at a board game?', intensity: 1, category: 'Funny' },
  { text: 'What is the weirdest thing in your fridge right now?', intensity: 1, category: 'Funny' },
  { text: 'Have you ever told a joke that nobody laughed at?', intensity: 1, category: 'Funny' },
  { text: 'What is the most ridiculous excuse you have ever used?', intensity: 2, category: 'Funny' },
  { text: 'What embarrassing song is on your playlist?', intensity: 1, category: 'Funny' },
  { text: 'Have you ever talked in your sleep? What did you say?', intensity: 1, category: 'Funny' },
  { text: 'What was your worst date?', intensity: 2, category: 'Funny' },
  { text: 'What sound do you make when nobody is listening?', intensity: 1, category: 'Funny' },
  { text: 'Have you ever cried from laughing? Why?', intensity: 1, category: 'Funny' },
  { text: 'What is your most unusual hobby?', intensity: 1, category: 'Funny' },
  { text: 'Have you ever accidentally insulted someone?', intensity: 2, category: 'Funny' },
  { text: 'What is the weirdest thing you have ever eaten?', intensity: 1, category: 'Funny' },
  // Embarrassing (2-3)
  { text: 'Who is your biggest crush in this group?', intensity: 3, category: 'Embarrassing' },
  { text: 'Have you ever stalked someone on social media?', intensity: 2, category: 'Embarrassing' },
  { text: 'What is the most embarrassing message in your chat history?', intensity: 3, category: 'Embarrassing' },
  { text: 'Have you ever shed a tear during a commercial?', intensity: 1, category: 'Embarrassing' },
  { text: 'What was your most embarrassing moment at a party?', intensity: 2, category: 'Embarrassing' },
  { text: 'Show the oldest photo on your phone!', intensity: 2, category: 'Embarrassing' },
  { text: 'When was the last time you cried and why?', intensity: 2, category: 'Embarrassing' },
  { text: 'What is your most secret wish?', intensity: 3, category: 'Embarrassing' },
  { text: 'Have you ever picked up food from the floor and eaten it?', intensity: 1, category: 'Embarrassing' },
  { text: 'What is the most embarrassing show you secretly watch?', intensity: 1, category: 'Embarrassing' },
  { text: 'Who in this group has the best style?', intensity: 2, category: 'Embarrassing' },
  { text: 'What was the most embarrassing thing you did in class?', intensity: 2, category: 'Embarrassing' },
  { text: 'Have you ever cried in a movie theater?', intensity: 1, category: 'Embarrassing' },
  { text: 'What is the most embarrassing photo on your phone?', intensity: 2, category: 'Embarrassing' },
  { text: 'Have you ever written a love letter?', intensity: 2, category: 'Embarrassing' },
  { text: 'What was the most embarrassing moment with your parents?', intensity: 2, category: 'Embarrassing' },
  { text: 'Have you ever sung loudly in public?', intensity: 1, category: 'Embarrassing' },
  { text: 'What is the most embarrassing thing in your browser history?', intensity: 3, category: 'Embarrassing' },
  { text: 'Have you ever confessed your feelings to someone?', intensity: 2, category: 'Embarrassing' },
  { text: 'What was your biggest fashion fail?', intensity: 2, category: 'Embarrassing' },
  // Bold (3)
  { text: 'What would you change if you were invisible for a day?', intensity: 3, category: 'Bold' },
  { text: 'Have you ever done something illegal?', intensity: 3, category: 'Bold' },
  { text: 'What was the bravest thing you have ever done?', intensity: 2, category: 'Bold' },
  { text: 'Would you run naked through the city for $10,000?', intensity: 3, category: 'Bold' },
  { text: 'What is the wildest thing you have ever done at a party?', intensity: 3, category: 'Bold' },
  { text: 'Have you ever revealed someone else\'s secret?', intensity: 2, category: 'Bold' },
  { text: 'What is the craziest thing on your bucket list?', intensity: 2, category: 'Bold' },
  { text: 'Would you go skydiving?', intensity: 1, category: 'Bold' },
  { text: 'What would you do if you had no fear?', intensity: 2, category: 'Bold' },
  { text: 'Have you done something your parents still don\'t know about?', intensity: 3, category: 'Bold' },

  // New Truths (50)
  { text: 'What was your first thought this morning?', intensity: 1, category: 'Harmless' },
  { text: 'What series could you watch over and over again?', intensity: 1, category: 'Harmless' },
  { text: 'What is the most romantic thing you have ever done?', intensity: 2, category: 'Funny' },
  { text: 'Have you ever deleted a message before it was read?', intensity: 2, category: 'Funny' },
  { text: 'What is the most expensive thing you have ever bought?', intensity: 1, category: 'Harmless' },
  { text: 'Which celebrity do you secretly find attractive?', intensity: 2, category: 'Embarrassing' },
  { text: 'Have you ever cheated on a test?', intensity: 2, category: 'Funny' },
  { text: 'What is the most embarrassing nickname you have ever had?', intensity: 1, category: 'Funny' },
  { text: 'What habit would you like to get rid of?', intensity: 1, category: 'Harmless' },
  { text: 'What is the bravest thing you have ever done for love?', intensity: 2, category: 'Bold' },
  { text: 'Have you ever blamed someone else even though it was your fault?', intensity: 2, category: 'Funny' },
  { text: 'What would you change if you were 16 again?', intensity: 2, category: 'Harmless' },
  { text: 'Which song always makes you cry?', intensity: 1, category: 'Harmless' },
  { text: 'What is the strangest thing you have ever ordered online?', intensity: 1, category: 'Funny' },
  { text: 'Do you have a favorite person in this group?', intensity: 2, category: 'Embarrassing' },
  { text: 'What was your biggest mistake in the last year?', intensity: 2, category: 'Bold' },
  { text: 'What lie do you tell most often?', intensity: 2, category: 'Funny' },
  { text: 'What is your secret bedtime ritual?', intensity: 1, category: 'Funny' },
  { text: 'Have you ever called someone and pretended to be someone else?', intensity: 2, category: 'Funny' },
  { text: 'What would you do if you were the opposite gender for a day?', intensity: 2, category: 'Funny' },
  { text: 'Who in this group has the best laugh?', intensity: 1, category: 'Harmless' },
  { text: 'What was the most delicious food you have ever eaten?', intensity: 1, category: 'Harmless' },
  { text: 'Have you ever eavesdropped on someone? What did you hear?', intensity: 2, category: 'Embarrassing' },
  { text: 'Which movie do you know by heart?', intensity: 1, category: 'Harmless' },
  { text: 'What is your biggest fear?', intensity: 2, category: 'Bold' },
  { text: 'Have you ever forgotten an appointment?', intensity: 1, category: 'Funny' },
  { text: 'What would you do if you woke up famous tomorrow?', intensity: 1, category: 'Harmless' },
  { text: 'What sound can you imitate best?', intensity: 1, category: 'Funny' },
  { text: 'What is the nicest thing a stranger has ever done for you?', intensity: 1, category: 'Harmless' },
  { text: 'Have you ever cried in your sleep?', intensity: 2, category: 'Embarrassing' },
  { text: 'What would you do with 3 wishes?', intensity: 1, category: 'Harmless' },
  { text: 'Who is the funniest person you know?', intensity: 1, category: 'Harmless' },
  { text: 'What is the craziest bet you have ever taken?', intensity: 2, category: 'Funny' },
  { text: 'Do you have a secret favorite word?', intensity: 1, category: 'Funny' },
  { text: 'What would be your last meal if you could choose?', intensity: 1, category: 'Harmless' },
  { text: 'Who in the group would be the best roommate?', intensity: 2, category: 'Embarrassing' },
  { text: 'What scared you the most as a kid?', intensity: 1, category: 'Harmless' },
  { text: 'Have you ever accidentally called someone the wrong name?', intensity: 1, category: 'Funny' },
  { text: 'What is your biggest dream?', intensity: 2, category: 'Bold' },
  { text: 'Have you ever broken something valuable and hidden it?', intensity: 2, category: 'Funny' },
  { text: 'Which historical person would you love to meet?', intensity: 1, category: 'Harmless' },
  { text: 'What was the strangest compliment you have ever received?', intensity: 1, category: 'Funny' },
  { text: 'Do you have a secret social media account?', intensity: 2, category: 'Embarrassing' },
  { text: 'What is your weirdest phobia?', intensity: 1, category: 'Funny' },
  { text: 'Which trend do you find completely ridiculous?', intensity: 1, category: 'Funny' },
  { text: 'Who in this group would you trust with a secret?', intensity: 2, category: 'Embarrassing' },
  { text: 'What is the strangest thing you have seen in someone else\'s home?', intensity: 2, category: 'Funny' },
  { text: 'Have you ever written a fake review online?', intensity: 2, category: 'Funny' },
  { text: 'What would you do if you could be someone else for a week?', intensity: 2, category: 'Bold' },
  { text: 'What is the most embarrassing thing on your nightstand?', intensity: 2, category: 'Embarrassing' },
];

export const DARE_CHALLENGES: DareChallenge[] = [
  // Harmless (1)
  { text: 'Do your best animal impression!', intensity: 1, category: 'Harmless' },
  { text: 'Sing a nursery rhyme for 10 seconds!', intensity: 1, category: 'Harmless' },
  { text: 'Do 10 jumping jacks!', intensity: 1, category: 'Harmless' },
  { text: 'Tell a joke!', intensity: 1, category: 'Harmless' },
  { text: 'Talk like a robot for 30 seconds!', intensity: 1, category: 'Harmless' },
  { text: 'Take a selfie with the person to your left!', intensity: 1, category: 'Harmless' },
  { text: 'Dance for 15 seconds without music!', intensity: 1, category: 'Harmless' },
  { text: 'Stand up and take a bow to the group!', intensity: 1, category: 'Harmless' },
  { text: 'Make your best opera face!', intensity: 1, category: 'Harmless' },
  { text: 'Draw a house with your eyes closed!', intensity: 1, category: 'Harmless' },
  { text: 'Maintain eye contact with someone for 30 seconds!', intensity: 1, category: 'Harmless' },
  { text: 'Hold a plank for 20 seconds!', intensity: 1, category: 'Harmless' },
  { text: 'Clap a rhythm and get the group to join in!', intensity: 1, category: 'Harmless' },
  { text: 'Stand up and spin around three times!', intensity: 1, category: 'Harmless' },
  { text: 'Whisper everything for the next minute!', intensity: 1, category: 'Harmless' },
  { text: 'Imitate a famous movie character!', intensity: 1, category: 'Harmless' },
  { text: 'Spell your name backwards out loud!', intensity: 1, category: 'Harmless' },
  { text: 'Make a funny face and hold it for 10 seconds!', intensity: 1, category: 'Harmless' },
  { text: 'Tell the group your most embarrassing childhood moment!', intensity: 1, category: 'Harmless' },
  { text: 'Speak with an accent for the next round!', intensity: 1, category: 'Harmless' },
  // Funny (1-2)
  { text: 'Do a moonwalk!', intensity: 2, category: 'Funny' },
  { text: 'Do a 30-second stand-up comedy set!', intensity: 2, category: 'Funny' },
  { text: 'Imitate a celebrity until someone guesses who it is!', intensity: 2, category: 'Funny' },
  { text: 'Dance like a dad at a wedding!', intensity: 1, category: 'Funny' },
  { text: 'Rap for 20 seconds about the person to your right!', intensity: 2, category: 'Funny' },
  { text: 'Act out a scene from your favorite movie!', intensity: 2, category: 'Funny' },
  { text: 'Do a news anchor voice and read a fake headline!', intensity: 2, category: 'Funny' },
  { text: 'Move in slow motion for 30 seconds!', intensity: 1, category: 'Funny' },
  { text: 'Show off the worst dance move you know!', intensity: 1, category: 'Funny' },
  { text: 'Tell a story where every word starts with the same letter!', intensity: 2, category: 'Funny' },
  { text: 'Stand up and give an Oscar acceptance speech!', intensity: 2, category: 'Funny' },
  { text: 'Make a TikTok video (without posting it)!', intensity: 2, category: 'Funny' },
  { text: 'Sing Happy Birthday to the person across from you!', intensity: 1, category: 'Funny' },
  { text: 'Speak like Yoda for 1 minute!', intensity: 2, category: 'Funny' },
  { text: 'Perform the most famous dance from a music video!', intensity: 2, category: 'Funny' },
  { text: 'Do a dramatic reading of the last text on your phone!', intensity: 2, category: 'Funny' },
  { text: 'Try not to blink for 30 seconds!', intensity: 1, category: 'Funny' },
  { text: 'Say a tongue twister three times fast!', intensity: 1, category: 'Funny' },
  { text: 'Do a handstand (or at least try)!', intensity: 2, category: 'Funny' },
  { text: 'Imitate your favorite emoji with your face!', intensity: 1, category: 'Funny' },
  // Embarrassing (2-3)
  { text: 'Call someone and say "I love you!"', intensity: 3, category: 'Embarrassing' },
  { text: 'Post a selfie with the caption "Monday..."!', intensity: 2, category: 'Embarrassing' },
  { text: 'Let the group take a photo of you and set it as your profile pic!', intensity: 3, category: 'Embarrassing' },
  { text: 'Tell your biggest flirting fail!', intensity: 2, category: 'Embarrassing' },
  { text: 'Show the group the last 3 photos on your phone!', intensity: 2, category: 'Embarrassing' },
  { text: 'Give everyone in the group an honest compliment!', intensity: 2, category: 'Embarrassing' },
  { text: 'Let someone send a message from your phone!', intensity: 3, category: 'Embarrassing' },
  { text: 'Stand on a chair and sing a love song!', intensity: 3, category: 'Embarrassing' },
  { text: 'Let the group decide your outfit for tomorrow!', intensity: 2, category: 'Embarrassing' },
  { text: 'Read aloud the last message you sent!', intensity: 2, category: 'Embarrassing' },
  { text: 'Take an embarrassing photo and send it to your best friend!', intensity: 3, category: 'Embarrassing' },
  { text: 'Give the person to your left a nickname!', intensity: 1, category: 'Embarrassing' },
  { text: 'Tell the most embarrassing story from your school days!', intensity: 2, category: 'Embarrassing' },
  { text: 'Take a photo with the most ridiculous facial expression!', intensity: 1, category: 'Embarrassing' },
  { text: 'Write and send a poetic message to your last contact!', intensity: 3, category: 'Embarrassing' },
  { text: 'Strike your best model pose!', intensity: 2, category: 'Embarrassing' },
  { text: 'Tell the group what you secretly think about the person across from you!', intensity: 3, category: 'Embarrassing' },
  { text: 'Let the group style your hair!', intensity: 2, category: 'Embarrassing' },
  { text: 'Sing the chorus of your favorite song in front of everyone!', intensity: 2, category: 'Embarrassing' },
  { text: 'Do 5 push-ups and count in French!', intensity: 2, category: 'Embarrassing' },
  // Bold (3)
  { text: 'Call a friend and pretend you are confessing something!', intensity: 3, category: 'Bold' },
  { text: 'Go outside and shout "I am the best!"', intensity: 3, category: 'Bold' },
  { text: 'Eat something the group mixes together for you!', intensity: 3, category: 'Bold' },
  { text: 'Beatbox for 30 seconds in front of the group!', intensity: 2, category: 'Bold' },
  { text: 'Dance alone for 1 minute to a song the group picks!', intensity: 3, category: 'Bold' },
  { text: 'Let the group post a message on your status!', intensity: 3, category: 'Bold' },
  { text: 'Speak in rhymes for the next 3 rounds!', intensity: 2, category: 'Bold' },
  { text: 'Make a TikTok video and actually post it!', intensity: 3, category: 'Bold' },
  { text: 'Run around the building while shouting your name!', intensity: 3, category: 'Bold' },
  { text: 'Let the group give you a task to complete tomorrow!', intensity: 3, category: 'Bold' },

  // New Dares (50)
  { text: 'Talk like a pirate for 2 minutes!', intensity: 1, category: 'Harmless' },
  { text: 'Do the floss dance for 20 seconds!', intensity: 1, category: 'Funny' },
  { text: 'Call someone and ask if their refrigerator is running!', intensity: 2, category: 'Funny' },
  { text: 'Make a love declaration to a piece of furniture!', intensity: 1, category: 'Funny' },
  { text: 'Eat a spoonful of mustard or ketchup!', intensity: 2, category: 'Bold' },
  { text: 'Tell a joke — if nobody laughs, do 10 push-ups!', intensity: 1, category: 'Funny' },
  { text: 'Take a photo with the craziest face and set it as your profile pic!', intensity: 3, category: 'Embarrassing' },
  { text: 'Speak in the third person for the next 2 rounds!', intensity: 2, category: 'Funny' },
  { text: 'Perform a magic trick you just made up!', intensity: 1, category: 'Funny' },
  { text: 'Do a 10-second workout and count in Japanese!', intensity: 1, category: 'Harmless' },
  { text: 'Imitate your best friend — the others have to guess!', intensity: 2, category: 'Funny' },
  { text: 'Send a heart to the last person you called!', intensity: 2, category: 'Embarrassing' },
  { text: 'Do a striptease — but only with your socks!', intensity: 2, category: 'Funny' },
  { text: 'Sing the ABC song as fast as you can!', intensity: 1, category: 'Harmless' },
  { text: 'Take a bow to every person in the group!', intensity: 1, category: 'Harmless' },
  { text: 'Let the group decide what you drink next!', intensity: 2, category: 'Bold' },
  { text: 'Talk nonsense for 30 seconds like it is a news broadcast!', intensity: 1, category: 'Funny' },
  { text: 'Make alien sounds for 15 seconds!', intensity: 1, category: 'Funny' },
  { text: 'Stand up and give a campaign speech — you are running for mayor!', intensity: 2, category: 'Funny' },
  { text: 'Send the third person in your contacts "I miss you"!', intensity: 3, category: 'Embarrassing' },
  { text: 'Do the Macarena!', intensity: 1, category: 'Funny' },
  { text: 'Speak for 1 minute without using the letter E!', intensity: 2, category: 'Funny' },
  { text: 'Take a selfie with your eyes closed and post it!', intensity: 2, category: 'Embarrassing' },
  { text: 'Act out how you get up in the morning — in slow motion!', intensity: 1, category: 'Funny' },
  { text: 'Play air drums to a song the group picks!', intensity: 1, category: 'Funny' },
  { text: 'Make baby sounds for 15 seconds!', intensity: 1, category: 'Funny' },
  { text: 'Give a dramatic farewell speech as if going into exile!', intensity: 2, category: 'Funny' },
  { text: 'Let the person to your right style your hair!', intensity: 2, category: 'Embarrassing' },
  { text: 'Do your best catwalk across the room!', intensity: 2, category: 'Funny' },
  { text: 'Tell a story where you are the hero!', intensity: 1, category: 'Harmless' },
  { text: 'Speak like a news anchor and report on the last round!', intensity: 2, category: 'Funny' },
  { text: 'Do tai chi for 30 seconds!', intensity: 1, category: 'Harmless' },
  { text: 'Walk an invisible dog — through the entire room!', intensity: 1, category: 'Funny' },
  { text: 'Say "I love you" to the person across from you without laughing!', intensity: 3, category: 'Embarrassing' },
  { text: 'Dance a waltz — by yourself!', intensity: 1, category: 'Funny' },
  { text: 'Try a tongue twister 5 times in a row!', intensity: 1, category: 'Harmless' },
  { text: 'Race to the nearest tree and back!', intensity: 1, category: 'Harmless' },
  { text: 'Hang upside down over the couch for 30 seconds!', intensity: 2, category: 'Funny' },
  { text: 'Go to the window and wave at people passing by!', intensity: 2, category: 'Embarrassing' },
  { text: 'Post an Instagram story with an embarrassing filter!', intensity: 2, category: 'Embarrassing' },
  { text: 'Tell everyone in the group what you admire most about them!', intensity: 2, category: 'Harmless' },
  { text: 'Tell a joke in another language — with a silly accent!', intensity: 1, category: 'Funny' },
  { text: 'Hold a plank until you answer the next question!', intensity: 2, category: 'Bold' },
  { text: 'Look the person to your left in the eyes and say something nice — no laughing!', intensity: 2, category: 'Embarrassing' },
  { text: 'Conduct an invisible orchestra!', intensity: 1, category: 'Funny' },
  { text: 'Call the last contact on your phone and say: You are my hero!', intensity: 3, category: 'Bold' },
  { text: 'Do warm-up exercises like a pro athlete — for 30 seconds!', intensity: 1, category: 'Harmless' },
  { text: 'Try not to blink for 20 seconds while the others distract you!', intensity: 1, category: 'Funny' },
  { text: 'Sing the chorus of a nursery rhyme in an opera voice!', intensity: 2, category: 'Funny' },
  { text: 'Let someone write a word on your arm!', intensity: 2, category: 'Embarrassing' },
];
