export interface SharedQuizQuestion { question: string; answers: string[]; correctIndex: number; hint: string; category: string; }

export const SHARED_QUIZ_QUESTIONS: SharedQuizQuestion[] = [
  { question: 'Hangi şehrin Venedik\'ten daha fazla köprüsü var?', answers: ['Amsterdam', 'Hamburg', 'St. Petersburg', 'Stockholm'], correctIndex: 1, hint: 'Bu şehir Kuzey Almanya\'da ve büyük bir limanı var.', category: 'Coğrafya' },
  { question: 'Hangi ülke çizme şeklindedir?', answers: ['Yunanistan', 'Hırvatistan', 'İtalya', 'Portekiz'], correctIndex: 2, hint: 'Pizza, makarna ve Papa\'yı düşün.', category: 'Coğrafya' },
  { question: 'Sahra Çölü ağırlıklı olarak hangi ülkede bulunur?', answers: ['Mısır', 'Cezayir', 'Libya', 'Fas'], correctIndex: 1, hint: 'Afrika\'nın yüz ölçümü olarak en büyük ülkesi.', category: 'Coğrafya' },
  { question: 'Avrupa\'nın en uzun nehri hangisidir?', answers: ['Tuna', 'Ren', 'Volga', 'Elbe'], correctIndex: 2, hint: 'Rusya\'dan akar ve Hazar Denizi\'ne dökülür.', category: 'Coğrafya' },
  { question: 'Avustralya\'nın başkenti neresidir?', answers: ['Sidney', 'Melbourne', 'Kanbera', 'Brisbane'], correctIndex: 2, hint: 'Ülkenin en büyük şehri DEĞİLDİR.', category: 'Coğrafya' },
  { question: 'Avrupa ile Afrika arasında hangi deniz bulunur?', answers: ['Kızıldeniz', 'Akdeniz', 'Karadeniz', 'Kuzey Denizi'], correctIndex: 1, hint: 'Turistler güneş ve plaj için oraya gider.', category: 'Coğrafya' },
  { question: 'Özgürlük Heykeli hangi ülkededir?', answers: ['Fransa', 'ABD', 'İngiltere', 'Kanada'], correctIndex: 1, hint: 'Fransa\'dan bu ülkeye hediye edildi.', category: 'Coğrafya' },
  { question: 'En soğuk kıta hangisidir?', answers: ['Arktik', 'Antarktika', 'Grönland', 'Sibirya'], correctIndex: 1, hint: 'Penguenler orada yaşar, ama kutup ayıları yaşamaz.', category: 'Coğrafya' },
  { question: 'Almanya\'nın en küçük eyaleti hangisidir?', answers: ['Hamburg', 'Saarland', 'Bremen', 'Berlin'], correctIndex: 2, hint: 'Bu Hansa şehri kuzeybatıdadır.', category: 'Coğrafya' },
  { question: 'Angkor Wat hangi ülkededir?', answers: ['Tayland', 'Vietnam', 'Kamboçya', 'Myanmar'], correctIndex: 2, hint: 'Tapınak kompleksi bu ülkenin bayrağında var.', category: 'Coğrafya' },
  { question: 'Dokuzuncu Senfoni\'yi kim besteledi?', answers: ['Mozart', 'Bach', 'Beethoven', 'Schubert'], correctIndex: 2, hint: 'Sağır oldu ama bestelemeye devam etti.', category: 'Tarih' },
  { question: 'Titanik hangi yılda battı?', answers: ['1910', '1912', '1914', '1916'], correctIndex: 1, hint: 'Birinci Dünya Savaşı\'ndan iki yıl önce.', category: 'Tarih' },
  { question: 'İlk Alman Başbakanı kimdi?', answers: ['Willy Brandt', 'Konrad Adenauer', 'Ludwig Erhard', 'Helmut Schmidt'], correctIndex: 1, hint: '1949\'dan 1963\'e kadar yönetti.', category: 'Tarih' },
  { question: '1889\'da Paris\'te hangi yapı inşa edildi?', answers: ['Zafer Takı', 'Louvre', 'Eyfel Kulesi', 'Notre-Dame'], correctIndex: 2, hint: 'Dünya Fuarı için inşa edildi ve demirden yapıldı.', category: 'Tarih' },
  { question: 'Ampulü kim icat etti?', answers: ['Nikola Tesla', 'Thomas Edison', 'Alexander Bell', 'Benjamin Franklin'], correctIndex: 1, hint: 'General Electric\'i de kurdu.', category: 'Tarih' },
  { question: 'Kleopatra\'nın favori evcil hayvanı hangisiydi?', answers: ['Köpek', 'Kedi', 'Yılan', 'Papağan'], correctIndex: 1, hint: 'Bu hayvanlar eski Mısır\'da kutsal kabul edilirdi.', category: 'Tarih' },
  { question: 'İnternet ne zaman halka açıldı?', answers: ['1985', '1991', '1995', '2000'], correctIndex: 1, hint: 'Tim Berners-Lee World Wide Web\'i yayımladı.', category: 'Tarih' },
  { question: 'Roma İmparatorluğu\'nda hangi dil konuşulurdu?', answers: ['Yunanca', 'Latince', 'Aramice', 'Keltçe'], correctIndex: 1, hint: 'Birçok tıp terimi bu dilden gelir.', category: 'Tarih' },
  { question: 'Uzaya giden ilk insan kimdi?', answers: ['Neil Armstrong', 'Yuri Gagarin', 'Buzz Aldrin', 'John Glenn'], correctIndex: 1, hint: 'Sovyetler Birliği\'ndendi ve 1961\'de uçtu.', category: 'Tarih' },
  { question: '1903\'te hangi oyun icat edildi?', answers: ['Satranç', 'Monopoly', 'Kızma Birader', 'Scrabble'], correctIndex: 2, hint: 'Almanya\'dan zarlı ve renkli taşlı bir masa oyunu.', category: 'Tarih' },
  { question: 'Elmaslar neden yapılır?', answers: ['Silikon', 'Karbon', 'Kuvars', 'Kalsiyum'], correctIndex: 1, hint: 'Kurşun kalem uçlarında bulunan aynı element.', category: 'Bilim' },
  { question: 'Güneş\'e en yakın gezegen hangisidir?', answers: ['Venüs', 'Merkür', 'Mars', 'Dünya'], correctIndex: 1, hint: 'Aynı zamanda güneş sistemimizin en küçük gezegenidir.', category: 'Bilim' },
  { question: 'Bir yetişkinin normalde kaç dişi vardır?', answers: ['28', '30', '32', '34'], correctIndex: 2, hint: 'Dört adet yirmi yaş dişi dahil.', category: 'Bilim' },
  { question: 'Hangisi daha ağır: bir kilo tüy mü yoksa bir kilo çelik mi?', answers: ['Tüy', 'Çelik', 'Aynı ağırlıkta', 'Miktara bağlı'], correctIndex: 2, hint: 'İyi düşün — cevap zaten soruda.', category: 'Bilim' },
  { question: 'Hangi hayvanın üç kalbi vardır?', answers: ['Ahtapot', 'Denizanası', 'Köpekbalığı', 'Kaplumbağa'], correctIndex: 0, hint: 'Sekiz kolu ve mavi kanı da var.', category: 'Bilim' },
  { question: 'Soluduğumuz gaz nedir?', answers: ['Azot', 'CO2', 'Oksijen', 'Hidrojen'], correctIndex: 2, hint: 'Bu gaz olmadan hayatta kalamayız — formülü O2.', category: 'Bilim' },
  { question: 'En çok enerji tüketen organ hangisidir?', answers: ['Kalp', 'Beyin', 'Karaciğer', 'Kaslar'], correctIndex: 1, hint: 'Sadece 1,5 kg ağırlığında ama oksijenin %20\'sini kullanır.', category: 'Bilim' },
  { question: 'Ses hızı yaklaşık olarak nedir?', answers: ['340 m/s', '1.200 m/s', '3.000 m/s', '100 m/s'], correctIndex: 0, hint: 'Gök gürültüsü şimşekten sonra gelir — her 3 saniyede yaklaşık 1 km.', category: 'Bilim' },
  { question: 'Oda sıcaklığında hangi metal sıvıdır?', answers: ['Kurşun', 'Cıva', 'Çinko', 'Alüminyum'], correctIndex: 1, hint: 'Eskiden termometrelerde kullanılırdı.', category: 'Bilim' },
  { question: 'İnsan vücudundaki en büyük kemik hangisidir?', answers: ['Kaval kemiği', 'Uyluk kemiği', 'Üst kol kemiği', 'Pelvis'], correctIndex: 1, hint: 'Uylukta bulunur — Latince adı: Femur.', category: 'Bilim' },
  { question: '"Bohemian Rhapsody"yi hangi grup söyledi?', answers: ['The Beatles', 'Queen', 'Led Zeppelin', 'Pink Floyd'], correctIndex: 1, hint: 'Şarkıcının adı Freddie\'ydi ve Zanzibar\'dandı.', category: 'Eğlence' },
  { question: 'Hangi filmde Güç Yüzüğü var?', answers: ['Harry Potter', 'Narnia', 'Yüzüklerin Efendisi', 'Taht Oyunları'], correctIndex: 2, hint: 'Bir hobbit onu Kader Dağı\'na götürmeli.', category: 'Eğlence' },
  { question: 'Simba hangi hayvandır?', answers: ['Kaplan', 'Aslan', 'Leopar', 'Çita'], correctIndex: 1, hint: 'Disney filmi — "… Kral"', category: 'Eğlence' },
  { question: 'Harry Potter\'daki büyücünün tam adı nedir?', answers: ['Harry Potter', 'Albus Dumbledore', 'Gri Gandalf', 'Merlin'], correctIndex: 1, hint: 'Hogwarts\'ın müdürüdür.', category: 'Eğlence' },
  { question: 'Loch Ness Canavarı\'nın rengi ne olduğu söylenir?', answers: ['Yeşil', 'Mavi', 'Siyah', 'Gri-yeşil'], correctIndex: 3, hint: 'Nessie — İskoçya\'da sözde bir deniz canavarı.', category: 'Eğlence' },
  { question: 'Bruce Wayne hangi süper kahramandır?', answers: ['Superman', 'Spider-Man', 'Batman', 'Iron Man'], correctIndex: 2, hint: 'Gotham City\'de yaşar ve süper gücü yoktur — sadece parası.', category: 'Eğlence' },
  { question: 'Hangi dizi Hawkins, Indiana\'da geçer?', answers: ['Breaking Bad', 'Stranger Things', 'The Walking Dead', 'Dark'], correctIndex: 1, hint: 'Çocuklar Ters Dünya\'daki canavarlarla savaşır.', category: 'Eğlence' },
  { question: '"Shape of You"yu kim söyler?', answers: ['Justin Bieber', 'Ed Sheeran', 'Bruno Mars', 'The Weeknd'], correctIndex: 1, hint: 'Kızıl saçlı İngiliz şarkıcı-söz yazarı.', category: 'Eğlence' },
  { question: 'Hangi oyunda bloklarla inşa edilir?', answers: ['Fortnite', 'Roblox', 'Minecraft', 'Terraria'], correctIndex: 2, hint: 'Creeper\'lar, Enderman\'lar ve elmaslar var.', category: 'Eğlence' },
  { question: 'Pikachu\'nun kuyruğu hangi renktir?', answers: ['Sarı', 'Siyah', 'Kahverengi', 'Siyah uçlu sarı'], correctIndex: 3, hint: 'Kırmızı yanaklı elektrik tipi bir Pokémon.', category: 'Eğlence' },
  { question: 'Bir futbol takımında kaç oyuncu var?', answers: ['10', '11', '12', '9'], correctIndex: 1, hint: 'Sahada kaleci dahil.', category: 'Spor' },
  { question: 'Judo hangi ülkede icat edildi?', answers: ['Çin', 'Kore', 'Japonya', 'Tayland'], correctIndex: 2, hint: 'Bu dövüş sanatı 1882\'de Jigoro Kano tarafından kuruldu.', category: 'Spor' },
  { question: 'Hangi tenis kortu kırmızı topraktandır?', answers: ['Wimbledon', 'Roland Garros', 'US Open', 'Avustralya Açık'], correctIndex: 1, hint: 'Bu turnuva Paris\'te yapılır.', category: 'Spor' },
  { question: 'Olimpiyat sembolünde kaç halka vardır?', answers: ['4', '5', '6', '7'], correctIndex: 1, hint: 'Her halka bir kıtayı temsil eder.', category: 'Spor' },
  { question: '2014 Dünya Kupası\'nı hangi ülke kazandı?', answers: ['Arjantin', 'Brezilya', 'Almanya', 'İspanya'], correctIndex: 2, hint: 'Mario Götze finaldeki golü attı.', category: 'Spor' },
  { question: 'Bowling\'de en yüksek skor kaçtır?', answers: ['200', '250', '300', '350'], correctIndex: 2, hint: '12 atışın tamamı strike olmalı.', category: 'Spor' },
  { question: 'Buz üzerinde diskle oynanan spor hangisidir?', answers: ['Curling', 'Buz hokeyi', 'Artistik buz pateni', 'Sürat pateni'], correctIndex: 1, hint: 'Oyuncular paten ve kask giyer.', category: 'Spor' },
  { question: 'Bir maraton ne kadar uzundur?', answers: ['40 km', '42,195 km', '45 km', '38 km'], correctIndex: 1, hint: 'Mesafe antik Yunanistan\'daki bir efsaneye dayanır.', category: 'Spor' },
  { question: 'Hangi sporda "slam dunk" vardır?', answers: ['Voleybol', 'Hentbol', 'Basketbol', 'Tenis'], correctIndex: 2, hint: 'Top yukarıdan potaya sokulur.', category: 'Spor' },
  { question: 'Ferrari logosunun sembolü hangi hayvandır?', answers: ['Boğa', 'Aslan', 'At', 'Kartal'], correctIndex: 2, hint: 'Sarı zemin üzerinde şaha kalkan bir hayvan.', category: 'Spor' },
  { question: 'Gökkuşağında kaç renk vardır?', answers: ['5', '6', '7', '8'], correctIndex: 2, hint: 'Kırmızı, turuncu, sarı, yeşil, mavi, çivit ve …', category: 'Genel Kültür' },
  { question: 'Evrende en yaygın element nedir?', answers: ['Helyum', 'Oksijen', 'Hidrojen', 'Karbon'], correctIndex: 2, hint: 'Güneş ağırlıklı olarak bu gazdan oluşur.', category: 'Genel Kültür' },
  { question: 'Hangi enstrümanın 88 tuşu vardır?', answers: ['Org', 'Piyano', 'Akordeon', 'Sentezleyici'], correctIndex: 1, hint: 'Siyah ve beyaz tuşlar — müzik derslerinin klasiği.', category: 'Genel Kültür' },
  { question: 'Elektrik akımı hangi birimle ölçülür?', answers: ['Volt', 'Watt', 'Amper', 'Ohm'], correctIndex: 2, hint: 'Fransız fizikçi André-Marie\'nin adını taşır.', category: 'Genel Kültür' },
  { question: 'Almanya\'nın kaç eyaleti vardır?', answers: ['14', '15', '16', '17'], correctIndex: 2, hint: 'Üçü şehir-eyalettir: Berlin, Hamburg ve Bremen.', category: 'Genel Kültür' },
  { question: 'Hangi kan grubu evrensel vericidir?', answers: ['A', 'B', 'AB', '0 Rh negatif'], correctIndex: 3, hint: 'Bu kan grubunun kırmızı kan hücrelerinde antijeni yoktur.', category: 'Genel Kültür' },
  { question: 'Japonya\'nın para birimi nedir?', answers: ['Yuan', 'Won', 'Yen', 'Baht'], correctIndex: 2, hint: 'Sembolü ¥.', category: 'Genel Kültür' },
  { question: 'Sevgililer Günü hangi gündür?', answers: ['14 Ocak', '14 Şubat', '14 Mart', '14 Nisan'], correctIndex: 1, hint: 'Aşıkların günü — güller ve çikolatayla.', category: 'Genel Kültür' },
  { question: 'Bir saatte kaç saniye vardır?', answers: ['3.000', '3.600', '4.200', '6.000'], correctIndex: 1, hint: '60 dakika çarpı 60 saniye.', category: 'Genel Kültür' },
  { question: 'Vücut güneş ışığıyla hangi vitamini üretir?', answers: ['A Vitamini', 'C Vitamini', 'D Vitamini', 'B12 Vitamini'], correctIndex: 2, hint: 'Kemikler için önemlidir ve kışın sık takviye edilir.', category: 'Genel Kültür' },
  { question: 'Bir milyonda kaç sıfır vardır?', answers: ['5', '6', '7', '8'], correctIndex: 1, hint: '1.000 çarpı 1.000.', category: 'Genel Kültür' },
  { question: 'Hangi hayvan başını 270 derece çevirebilir?', answers: ['Bukalemun', 'Baykuş', 'Flamingo', 'Papağan'], correctIndex: 1, hint: 'Gece aktif, büyük gözlü kuş.', category: 'Genel Kültür' },
  { question: 'Hangi ülkenin en fazla saat dilimi vardır?', answers: ['Rusya', 'ABD', 'Fransa', 'Çin'], correctIndex: 2, hint: 'Bu ülkenin birçok denizaşırı toprağını düşün.', category: 'Coğrafya' },
  { question: 'En derin okyanus hangisidir?', answers: ['Atlantik', 'Pasifik', 'Hint Okyanusu', 'Kuzey Buz Denizi'], correctIndex: 1, hint: 'Mariana Çukuru bu okyanustadır.', category: 'Coğrafya' },
  { question: 'Au sembolü hangi elemente aittir?', answers: ['Gümüş', 'Alüminyum', 'Altın', 'Argon'], correctIndex: 2, hint: 'Değerli bir metal — Latince "Aurum".', category: 'Bilim' },
  { question: 'Yetişkinin yirmi yaş dişleri dahil kaç dişi vardır?', answers: ['28', '30', '32', '36'], correctIndex: 2, hint: 'Dördü genellikle geç gelir ve bazen çekilir.', category: 'Bilim' },
  { question: '"Sihirli Flüt"ü kim besteledi?', answers: ['Bach', 'Beethoven', 'Mozart', 'Händel'], correctIndex: 2, hint: 'Salzburg\'lu bir harika çocuk.', category: 'Tarih' },
  { question: 'Hangi hayvanın kan basıncı en yüksektir?', answers: ['Fil', 'Zürafa', 'Balina', 'İnsan'], correctIndex: 1, hint: 'Çok uzun bir boynu var ve kanı yukarı pompalamak zorunda.', category: 'Bilim' },
  { question: 'İnsanlar Ay\'a ilk hangi yılda ayak bastı?', answers: ['1965', '1967', '1969', '1971'], correctIndex: 2, hint: 'Neil Armstrong ünlü sözünü söyledi.', category: 'Tarih' },
  { question: 'Stanley Kupası hangi sporda oynanır?', answers: ['Basketbol', 'Amerikan futbolu', 'Buz hokeyi', 'Beyzbol'], correctIndex: 2, hint: 'Diskle buz üzerinde oynanan bir spor.', category: 'Spor' },
  { question: 'İskoçya\'nın ulusal hayvanı nedir?', answers: ['Aslan', 'Tek boynuzlu at', 'Geyik', 'Kartal'], correctIndex: 1, hint: 'Boynuzlu mitolojik bir yaratık.', category: 'Genel Kültür' },
  { question: 'Kahire\'den hangi nehir geçer?', answers: ['Fırat', 'Nil', 'Dicle', 'Ürdün'], correctIndex: 1, hint: 'Afrika\'nın en uzun nehri.', category: 'Coğrafya' },
  { question: 'İnsan vücudundaki en küçük kemik hangisidir?', answers: ['Üzengi', 'Çekiç', 'Örs', 'Ayak parmak kemiği'], correctIndex: 0, hint: 'Kulaktadır ve sadece 3 mm boyundadır.', category: 'Bilim' },
  { question: 'En çok Oscar kazanan film (11) hangisidir?', answers: ['Titanik', 'Ben-Hur', 'Yüzüklerin Efendisi', 'Üçü de'], correctIndex: 3, hint: 'Üç film bu rekoru paylaşır.', category: 'Eğlence' },
  { question: 'Dünyanın en yüksek şelalesi hangisidir?', answers: ['Niagara', 'Angel Şelalesi', 'Victoria Şelalesi', 'Iguazú'], correctIndex: 1, hint: 'Venezuela\'dadır ve yaklaşık 1 km yüksekliğindedir.', category: 'Coğrafya' },
  { question: 'Hangi meyve suda yüzer?', answers: ['Muz', 'Elma', 'Üzüm', 'Kiraz'], correctIndex: 1, hint: '%25 havadan oluşur.', category: 'Genel Kültür' },
  { question: 'Dinamiti kim icat etti?', answers: ['Thomas Edison', 'Alfred Nobel', 'Nikola Tesla', 'Alexander Bell'], correctIndex: 1, hint: 'Dünyanın en ünlü ödülü onun adını taşır.', category: 'Tarih' },
  { question: 'Uçaktaki "kara kutu" hangi renktir?', answers: ['Siyah', 'Turuncu', 'Kırmızı', 'Sarı'], correctIndex: 1, hint: 'Adı yanıltıcıdır — çok görünür olmalıdır.', category: 'Genel Kültür' },
  { question: 'Kadınlara seçme hakkı veren ilk ülke hangisidir?', answers: ['Fransa', 'ABD', 'Almanya', 'Yeni Zelanda'], correctIndex: 3, hint: 'Okyanusya\'da bir ada devleti — 1893.', category: 'Tarih' },
  { question: 'Solucanın kaç kalbi vardır?', answers: ['1', '3', '5', '10'], correctIndex: 2, hint: 'Aslında aort kemerleridir ama kalp gibi çalışırlar.', category: 'Bilim' },
  { question: 'En hızlı dönen gezegen hangisidir?', answers: ['Dünya', 'Mars', 'Jüpiter', 'Satürn'], correctIndex: 2, hint: 'En büyük gezegen — bir günü sadece 10 saat sürer.', category: 'Bilim' },
  { question: 'Hangi enstrüman iki tokmakla çalınır?', answers: ['Keman', 'Davul', 'Gitar', 'Piyano'], correctIndex: 1, hint: 'Vurulur — ritim en önemli şeydir.', category: 'Genel Kültür' },
  { question: 'Tayland\'ın başkenti neresidir?', answers: ['Phuket', 'Bangkok', 'Chiang Mai', 'Pattaya'], correctIndex: 1, hint: 'Tam adı dünyadaki en uzun şehir adıdır.', category: 'Coğrafya' },
  { question: 'İnsan vücudundaki en güçlü kas hangisidir?', answers: ['Pazı', 'Kalp', 'Çene kası', 'Uyluk'], correctIndex: 2, hint: 'Yemek yerken kullanırsın — muazzam güç uygulayabilir.', category: 'Bilim' },
  { question: 'Dünyada en çok aktif oyuncuya sahip oyun hangisidir?', answers: ['Fortnite', 'Minecraft', 'League of Legends', 'Roblox'], correctIndex: 1, hint: '140 milyondan fazla aktif oyuncusu olan bir blok oyunu.', category: 'Eğlence' },
  { question: 'Günde en çok uyuyan hayvan hangisidir?', answers: ['Kedi', 'Koala', 'Tembel hayvan', 'Kahverengi yarasa'], correctIndex: 3, hint: 'Günde 20 saate kadar — baş aşağı asılı.', category: 'Bilim' },
  { question: 'Dünyanın en ünlü elması hangisidir?', answers: ['Hope', 'Koh-i-Noor', 'Afrika Yıldızı', 'Blue Moon'], correctIndex: 1, hint: 'İngiliz Taç Mücevherlerine aittir.', category: 'Genel Kültür' },
  { question: 'En çok peynir üreten ülke hangisidir?', answers: ['Fransa', 'İsviçre', 'ABD', 'Almanya'], correctIndex: 2, hint: 'Peynirle tipik olarak ilişkilendirilen ülke değildir.', category: 'Genel Kültür' },
  { question: '"Romeo ve Juliet"i kim yazdı?', answers: ['Goethe', 'Shakespeare', 'Schiller', 'Molière'], correctIndex: 1, hint: '16. yüzyıldan bir İngiliz oyun yazarı.', category: 'Tarih' },
  { question: 'Hangi gaz sesi daha tiz yapar?', answers: ['Azot', 'Oksijen', 'Helyum', 'Hidrojen'], correctIndex: 2, hint: 'Balon şişirmek için de kullanılır.', category: 'Bilim' },
  { question: 'Futbol hangi ülkede icat edildi?', answers: ['Brezilya', 'Almanya', 'İngiltere', 'İspanya'], correctIndex: 2, hint: 'Premier Lig bu ülkeden gelir.', category: 'Spor' },
  { question: 'En derinden dalabilen kuş hangisidir?', answers: ['Albatros', 'Penguen', 'Pelikan', 'Karabatak'], correctIndex: 1, hint: 'Uçamayan ve Antarktika\'da yaşayan bir kuş.', category: 'Bilim' },
  { question: 'Dünyanın en büyük örümceği hangisidir?', answers: ['Kara dul', 'Tarantula', 'Golyat kuşyiyen', 'Tarantula'], correctIndex: 2, hint: 'Bacak açıklığı 30 cm\'e ulaşabilir.', category: 'Bilim' },
  { question: 'En çok çekirdeğe sahip meyve hangisidir?', answers: ['Karpuz', 'Nar', 'Kivi', 'Çilek'], correctIndex: 3, hint: 'Çekirdekler dışarıda — meyve başına ortalama 200.', category: 'Genel Kültür' },
  { question: 'Yer kabuğunda en bol bulunan metal hangisidir?', answers: ['Demir', 'Alüminyum', 'Bakır', 'Altın'], correctIndex: 1, hint: 'Teneke kutular ve uçaklar için kullanılır.', category: 'Bilim' },
  { question: 'Hangi kıtada çöl yoktur?', answers: ['Avrupa', 'Güney Amerika', 'Avustralya', 'Hiçbiri — hepsinde çöl var'], correctIndex: 0, hint: 'İkinci en küçük kıta.', category: 'Coğrafya' },
  { question: 'Standart bir piyanonun kaç tuşu vardır?', answers: ['76', '82', '88', '92'], correctIndex: 2, hint: '52 beyaz ve 36 siyah tuş.', category: 'Genel Kültür' },
  { question: 'En nadir kan grubu hangisidir?', answers: ['A negatif', 'B negatif', 'AB negatif', 'O negatif'], correctIndex: 2, hint: 'Dünya nüfusunun sadece yaklaşık %1\'i bu kan grubuna sahip.', category: 'Bilim' },
  { question: 'Hangi filmde "Güç seninle olsun" denir?', answers: ['Star Trek', 'Yıldız Savaşları', 'Matrix', 'Yüzüklerin Efendisi'], correctIndex: 1, hint: 'Işın kılıçları ve Jedi\'lar büyük rol oynar.', category: 'Eğlence' },
  { question: 'Hayvanlar aleminde en büyük gözlere sahip hayvan hangisidir?', answers: ['Fil', 'Deve kuşu', 'Dev kalamar', 'Kartal'], correctIndex: 2, hint: 'Gözleri futbol topu kadar büyük olabilir.', category: 'Bilim' },
  { question: 'Almanya\'nın en uzun nehri hangisidir?', answers: ['Elbe', 'Ren', 'Tuna', 'Weser'], correctIndex: 1, hint: 'Köln ve Düsseldorf\'tan geçer.', category: 'Coğrafya' },
  { question: '31 Ekim\'de hangi bayram kutlanır?', answers: ['Noel Baba', 'Cadılar Bayramı', 'Reform Günü', 'B ve C ikisi de'], correctIndex: 3, hint: 'Almanya\'da dini bir bayramdır, uluslararası alanda insanlar kostüm giyer.', category: 'Genel Kültür' },
];
