export interface SharedQuizQuestion {
  question: string;
  answers: string[];
  correctIndex: number;
  hint: string;
  category: string;
}

export const SHARED_QUIZ_QUESTIONS: SharedQuizQuestion[] = [
  // Geografie (10)
  { question: 'Welke stad heeft meer bruggen dan Venetië?', answers: ['Amsterdam', 'Hamburg', 'Sint-Petersburg', 'Stockholm'], correctIndex: 1, hint: 'Deze stad ligt in Noord-Duitsland en heeft een grote haven.', category: 'Geografie' },
  { question: 'Welk land heeft de vorm van een laars?', answers: ['Griekenland', 'Kroatië', 'Italië', 'Portugal'], correctIndex: 2, hint: 'Denk aan pizza, pasta en de paus.', category: 'Geografie' },
  { question: 'In welk land ligt de Sahara voornamelijk?', answers: ['Egypte', 'Algerije', 'Libië', 'Marokko'], correctIndex: 1, hint: 'Het grootste land van Afrika qua oppervlakte.', category: 'Geografie' },
  { question: 'Wat is de langste rivier van Europa?', answers: ['Donau', 'Rijn', 'Wolga', 'Elbe'], correctIndex: 2, hint: 'Hij stroomt door Rusland en mondt uit in de Kaspische Zee.', category: 'Geografie' },
  { question: 'Wat is de hoofdstad van Australië?', answers: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, hint: 'Het is NIET de grootste stad van het land.', category: 'Geografie' },
  { question: 'Welke zee ligt tussen Europa en Afrika?', answers: ['Rode Zee', 'Middellandse Zee', 'Zwarte Zee', 'Noordzee'], correctIndex: 1, hint: 'Toeristen gaan hier naartoe voor zon en strand.', category: 'Geografie' },
  { question: 'In welk land staat het Vrijheidsbeeld?', answers: ['Frankrijk', 'VS', 'Engeland', 'Canada'], correctIndex: 1, hint: 'Het was een geschenk van Frankrijk aan dit land.', category: 'Geografie' },
  { question: 'Welk continent is het koudste?', answers: ['Arctisch', 'Antarctica', 'Groenland', 'Siberië'], correctIndex: 1, hint: 'Pinguïns leven er, maar geen ijsberen.', category: 'Geografie' },
  { question: 'Wat is de kleinste deelstaat van Duitsland?', answers: ['Hamburg', 'Saarland', 'Bremen', 'Berlijn'], correctIndex: 2, hint: 'Deze Hanzestad ligt in het noordwesten.', category: 'Geografie' },
  { question: 'In welk land ligt Angkor Wat?', answers: ['Thailand', 'Vietnam', 'Cambodja', 'Myanmar'], correctIndex: 2, hint: 'Het tempelcomplex staat op de vlag van dit land.', category: 'Geografie' },

  // Geschiedenis (10)
  { question: 'Wie componeerde de Negende Symfonie?', answers: ['Mozart', 'Bach', 'Beethoven', 'Schubert'], correctIndex: 2, hint: 'Hij werd doof maar bleef componeren.', category: 'Geschiedenis' },
  { question: 'In welk jaar zonk de Titanic?', answers: ['1910', '1912', '1914', '1916'], correctIndex: 1, hint: 'Twee jaar voor de Eerste Wereldoorlog.', category: 'Geschiedenis' },
  { question: 'Wie was de eerste Duitse bondskanselier?', answers: ['Willy Brandt', 'Konrad Adenauer', 'Ludwig Erhard', 'Helmut Schmidt'], correctIndex: 1, hint: 'Hij regeerde van 1949 tot 1963.', category: 'Geschiedenis' },
  { question: 'Welk bouwwerk werd in 1889 in Parijs gebouwd?', answers: ['Arc de Triomphe', 'Louvre', 'Eiffeltoren', 'Notre-Dame'], correctIndex: 2, hint: 'Het werd gebouwd voor een Wereldtentoonstelling en is van ijzer.', category: 'Geschiedenis' },
  { question: 'Wie heeft de gloeilamp uitgevonden?', answers: ['Nikola Tesla', 'Thomas Edison', 'Alexander Bell', 'Benjamin Franklin'], correctIndex: 1, hint: 'Hij richtte ook General Electric op.', category: 'Geschiedenis' },
  { question: 'Welk dier was het lievelingshuisdier van Cleopatra?', answers: ['Hond', 'Kat', 'Slang', 'Papegaai'], correctIndex: 1, hint: 'Deze dieren werden in het oude Egypte als heilig vereerd.', category: 'Geschiedenis' },
  { question: 'Wanneer werd het internet openbaar toegankelijk?', answers: ['1985', '1991', '1995', '2000'], correctIndex: 1, hint: 'Tim Berners-Lee publiceerde het World Wide Web.', category: 'Geschiedenis' },
  { question: 'Welke taal werd gesproken in het Romeinse Rijk?', answers: ['Grieks', 'Latijn', 'Aramees', 'Keltisch'], correctIndex: 1, hint: 'Veel medische termen komen uit deze taal.', category: 'Geschiedenis' },
  { question: 'Wie was de eerste mens in de ruimte?', answers: ['Neil Armstrong', 'Joeri Gagarin', 'Buzz Aldrin', 'John Glenn'], correctIndex: 1, hint: 'Hij kwam uit de Sovjet-Unie en vloog in 1961.', category: 'Geschiedenis' },
  { question: 'Welk spel werd in 1903 uitgevonden?', answers: ['Schaken', 'Monopoly', 'Mens erger je niet', 'Scrabble'], correctIndex: 2, hint: 'Een bordspel met dobbelstenen en gekleurde pionnen uit Duitsland.', category: 'Geschiedenis' },

  // Wetenschap (10)
  { question: 'Waarvan zijn diamanten gemaakt?', answers: ['Silicium', 'Koolstof', 'Kwarts', 'Calcium'], correctIndex: 1, hint: 'Hetzelfde element als in potloodstiften.', category: 'Wetenschap' },
  { question: 'Welke planeet staat het dichtst bij de zon?', answers: ['Venus', 'Mercurius', 'Mars', 'Aarde'], correctIndex: 1, hint: 'Het is ook de kleinste planeet in ons zonnestelsel.', category: 'Wetenschap' },
  { question: 'Hoeveel tanden heeft een volwassene normaal?', answers: ['28', '30', '32', '34'], correctIndex: 2, hint: 'Inclusief de vier verstandskiezen.', category: 'Wetenschap' },
  { question: 'Wat is zwaarder: een kilo veren of een kilo staal?', answers: ['Veren', 'Staal', 'Even zwaar', 'Hangt van de hoeveelheid af'], correctIndex: 2, hint: 'Denk goed na — het staat al in de vraag.', category: 'Wetenschap' },
  { question: 'Welk dier heeft drie harten?', answers: ['Octopus', 'Kwal', 'Haai', 'Schildpad'], correctIndex: 0, hint: 'Het heeft ook acht armen en blauw bloed.', category: 'Wetenschap' },
  { question: 'Welk gas ademen we in?', answers: ['Stikstof', 'CO2', 'Zuurstof', 'Waterstof'], correctIndex: 2, hint: 'Zonder dit gas konden we niet overleven — formule O2.', category: 'Wetenschap' },
  { question: 'Welk orgaan verbruikt de meeste energie?', answers: ['Hart', 'Hersenen', 'Lever', 'Spieren'], correctIndex: 1, hint: 'Het weegt maar 1,5 kg maar gebruikt 20% van de zuurstof.', category: 'Wetenschap' },
  { question: 'Hoe snel is geluid ongeveer?', answers: ['340 m/s', '1.200 m/s', '3.000 m/s', '100 m/s'], correctIndex: 0, hint: 'Donder komt na bliksem — ongeveer 1 km per 3 seconden.', category: 'Wetenschap' },
  { question: 'Welk metaal is vloeibaar bij kamertemperatuur?', answers: ['Lood', 'Kwik', 'Zink', 'Aluminium'], correctIndex: 1, hint: 'Het werd vroeger in thermometers gebruikt.', category: 'Wetenschap' },
  { question: 'Wat is het grootste bot in het menselijk lichaam?', answers: ['Scheenbeen', 'Dijbeen', 'Bovenarm', 'Bekken'], correctIndex: 1, hint: 'Het zit in het bovenbeen — Latijn: Femur.', category: 'Wetenschap' },

  // Entertainment & Popcultuur (10)
  { question: 'Welke band zong "Bohemian Rhapsody"?', answers: ['The Beatles', 'Queen', 'Led Zeppelin', 'Pink Floyd'], correctIndex: 1, hint: 'De zanger heette Freddie en kwam uit Zanzibar.', category: 'Entertainment' },
  { question: 'In welke film is er een Ring van Macht?', answers: ['Harry Potter', 'Narnia', 'In de Ban van de Ring', 'Game of Thrones'], correctIndex: 2, hint: 'Een hobbit moet hem naar de Doemberg brengen.', category: 'Entertainment' },
  { question: 'Welk dier is Simba?', answers: ['Tijger', 'Leeuw', 'Luipaard', 'Cheeta'], correctIndex: 1, hint: 'Disney-film — "De … Koning"', category: 'Entertainment' },
  { question: 'Wat is de volledige naam van de tovenaar in Harry Potter?', answers: ['Harry Potter', 'Albus Perkamentus', 'Gandalf de Grijze', 'Merlijn'], correctIndex: 1, hint: 'Hij is het schoolhoofd van Zweinstein.', category: 'Entertainment' },
  { question: 'Welke kleur zou het monster van Loch Ness hebben?', answers: ['Groen', 'Blauw', 'Zwart', 'Grijsgroen'], correctIndex: 3, hint: 'Nessie — zogenaamd een zeemonster in Schotland.', category: 'Entertainment' },
  { question: 'Welke superheld is Bruce Wayne?', answers: ['Superman', 'Spider-Man', 'Batman', 'Iron Man'], correctIndex: 2, hint: 'Hij woont in Gotham City en heeft geen superkrachten — alleen geld.', category: 'Entertainment' },
  { question: 'Welke serie speelt zich af in Hawkins, Indiana?', answers: ['Breaking Bad', 'Stranger Things', 'The Walking Dead', 'Dark'], correctIndex: 1, hint: 'Kinderen vechten tegen monsters uit de Upside Down.', category: 'Entertainment' },
  { question: 'Wie zingt "Shape of You"?', answers: ['Justin Bieber', 'Ed Sheeran', 'Bruno Mars', 'The Weeknd'], correctIndex: 1, hint: 'Een roodharige Britse singer-songwriter.', category: 'Entertainment' },
  { question: 'In welk spel bouw je met blokken?', answers: ['Fortnite', 'Roblox', 'Minecraft', 'Terraria'], correctIndex: 2, hint: 'Er zijn Creepers, Endermen en diamanten.', category: 'Entertainment' },
  { question: 'Welke kleur heeft de staart van Pikachu?', answers: ['Geel', 'Zwart', 'Bruin', 'Geel met zwarte punt'], correctIndex: 3, hint: 'Het is een elektrisch Pokémon met rode wangen.', category: 'Entertainment' },

  // Sport (10)
  { question: 'Hoeveel spelers heeft een voetbalteam?', answers: ['10', '11', '12', '9'], correctIndex: 1, hint: 'Inclusief de keeper op het veld.', category: 'Sport' },
  { question: 'In welk land is judo uitgevonden?', answers: ['China', 'Korea', 'Japan', 'Thailand'], correctIndex: 2, hint: 'De vechtkunst werd in 1882 opgericht door Jigoro Kano.', category: 'Sport' },
  { question: 'Welke tennisbaan is van rood gravel?', answers: ['Wimbledon', 'Roland Garros', 'US Open', 'Australian Open'], correctIndex: 1, hint: 'Dit toernooi vindt plaats in Parijs.', category: 'Sport' },
  { question: 'Hoeveel ringen heeft het olympisch symbool?', answers: ['4', '5', '6', '7'], correctIndex: 1, hint: 'Elke ring vertegenwoordigt een continent.', category: 'Sport' },
  { question: 'Welk land won het WK voetbal 2014?', answers: ['Argentinië', 'Brazilië', 'Duitsland', 'Spanje'], correctIndex: 2, hint: 'Mario Götze scoorde het doelpunt in de finale.', category: 'Sport' },
  { question: 'Wat is de hoogste score bij bowlen?', answers: ['200', '250', '300', '350'], correctIndex: 2, hint: 'Alle 12 worpen moeten strikes zijn.', category: 'Sport' },
  { question: 'Welke sport wordt op ijs gespeeld met een puck?', answers: ['Curling', 'IJshockey', 'Kunstschaatsen', 'Schaatsen'], correctIndex: 1, hint: 'Spelers dragen schaatsen en helmen.', category: 'Sport' },
  { question: 'Hoe lang is een marathon?', answers: ['40 km', '42,195 km', '45 km', '38 km'], correctIndex: 1, hint: 'De afstand gaat terug op een legende uit het oude Griekenland.', category: 'Sport' },
  { question: 'In welke sport is er een "slam dunk"?', answers: ['Volleybal', 'Handbal', 'Basketbal', 'Tennis'], correctIndex: 2, hint: 'De bal wordt van boven in de ring geduwd.', category: 'Sport' },
  { question: 'Welk dier is het symbool van het Ferrari-logo?', answers: ['Stier', 'Leeuw', 'Paard', 'Adelaar'], correctIndex: 2, hint: 'Een steigerend dier op een gele achtergrond.', category: 'Sport' },

  // Algemene Kennis (12)
  { question: 'Hoeveel kleuren heeft een regenboog?', answers: ['5', '6', '7', '8'], correctIndex: 2, hint: 'Rood, oranje, geel, groen, blauw, indigo en …', category: 'Algemene Kennis' },
  { question: 'Wat is het meest voorkomende element in het universum?', answers: ['Helium', 'Zuurstof', 'Waterstof', 'Koolstof'], correctIndex: 2, hint: 'De zon bestaat voornamelijk uit dit gas.', category: 'Algemene Kennis' },
  { question: 'Welk instrument heeft 88 toetsen?', answers: ['Orgel', 'Piano', 'Accordeon', 'Synthesizer'], correctIndex: 1, hint: 'Zwarte en witte toetsen — een klassieker in de muziekles.', category: 'Algemene Kennis' },
  { question: 'In welke eenheid wordt elektrische stroom gemeten?', answers: ['Volt', 'Watt', 'Ampère', 'Ohm'], correctIndex: 2, hint: 'Vernoemd naar de Franse natuurkundige André-Marie.', category: 'Algemene Kennis' },
  { question: 'Hoeveel deelstaten heeft Duitsland?', answers: ['14', '15', '16', '17'], correctIndex: 2, hint: 'Drie ervan zijn stadstaten: Berlijn, Hamburg en Bremen.', category: 'Algemene Kennis' },
  { question: 'Welke bloedgroep is de universele donor?', answers: ['A', 'B', 'AB', 'O negatief'], correctIndex: 3, hint: 'Deze bloedgroep heeft geen antigenen op de rode bloedcellen.', category: 'Algemene Kennis' },
  { question: 'Wat is de munteenheid in Japan?', answers: ['Yuan', 'Won', 'Yen', 'Baht'], correctIndex: 2, hint: 'Het symbool is ¥.', category: 'Algemene Kennis' },
  { question: 'Welke dag is Valentijnsdag?', answers: ['14 januari', '14 februari', '14 maart', '14 april'], correctIndex: 1, hint: 'De dag van de liefde — met rozen en chocolade.', category: 'Algemene Kennis' },
  { question: 'Hoeveel seconden heeft een uur?', answers: ['3.000', '3.600', '4.200', '6.000'], correctIndex: 1, hint: '60 minuten keer 60 seconden.', category: 'Algemene Kennis' },
  { question: 'Welke vitamine maakt het lichaam aan door zonlicht?', answers: ['Vitamine A', 'Vitamine C', 'Vitamine D', 'Vitamine B12'], correctIndex: 2, hint: 'Het is belangrijk voor botten en wordt in de winter vaak gesuppleerd.', category: 'Algemene Kennis' },
  { question: 'Hoeveel nullen heeft een miljoen?', answers: ['5', '6', '7', '8'], correctIndex: 1, hint: '1.000 keer 1.000.', category: 'Algemene Kennis' },
  { question: 'Welk dier kan zijn hoofd 270 graden draaien?', answers: ['Kameleon', 'Uil', 'Flamingo', 'Papegaai'], correctIndex: 1, hint: 'Nachtelijke vogel met grote ogen.', category: 'Algemene Kennis' },

  // Nieuwe Vragen (40)
  { question: 'Welk land heeft de meeste tijdzones?', answers: ['Rusland', 'VS', 'Frankrijk', 'China'], correctIndex: 2, hint: 'Denk aan de vele overzeese gebieden van dit land.', category: 'Geografie' },
  { question: 'Welke oceaan is het diepst?', answers: ['Atlantische', 'Stille', 'Indische Oceaan', 'Noordelijke IJszee'], correctIndex: 1, hint: 'De Marianentrog ligt in deze oceaan.', category: 'Geografie' },
  { question: 'Welk element heeft het symbool Au?', answers: ['Zilver', 'Aluminium', 'Goud', 'Argon'], correctIndex: 2, hint: 'Een edelmetaal — Latijn "Aurum".', category: 'Wetenschap' },
  { question: 'Hoeveel tanden heeft een volwassene inclusief verstandskiezen?', answers: ['28', '30', '32', '36'], correctIndex: 2, hint: 'Vier ervan komen vaak laat en worden soms getrokken.', category: 'Wetenschap' },
  { question: 'Wie componeerde "De Toverfluit"?', answers: ['Bach', 'Beethoven', 'Mozart', 'Händel'], correctIndex: 2, hint: 'Een wonderkind uit Salzburg.', category: 'Geschiedenis' },
  { question: 'Welk dier heeft de hoogste bloeddruk?', answers: ['Olifant', 'Giraffe', 'Walvis', 'Mens'], correctIndex: 1, hint: 'Het heeft een zeer lange nek en moet bloed ver omhoog pompen.', category: 'Wetenschap' },
  { question: 'In welk jaar landden de eerste mensen op de maan?', answers: ['1965', '1967', '1969', '1971'], correctIndex: 2, hint: 'Neil Armstrong sprak zijn beroemde zin uit.', category: 'Geschiedenis' },
  { question: 'Welke sport wordt gespeeld om de Stanley Cup?', answers: ['Basketbal', 'American Football', 'IJshockey', 'Honkbal'], correctIndex: 2, hint: 'Een sport op ijs met een puck.', category: 'Sport' },
  { question: 'Wat is het nationale dier van Schotland?', answers: ['Leeuw', 'Eenhoorn', 'Hert', 'Adelaar'], correctIndex: 1, hint: 'Een mythisch wezen met een hoorn.', category: 'Algemene Kennis' },
  { question: 'Welke rivier stroomt door Caïro?', answers: ['Eufraat', 'Nijl', 'Tigris', 'Jordaan'], correctIndex: 1, hint: 'De langste rivier van Afrika.', category: 'Geografie' },
  { question: 'Wat is het kleinste bot in het menselijk lichaam?', answers: ['Stijgbeugel', 'Hamer', 'Aambeeld', 'Teenkootje'], correctIndex: 0, hint: 'Het zit in het oor en is maar 3 mm lang.', category: 'Wetenschap' },
  { question: 'Welke film won de meeste Oscars (11)?', answers: ['Titanic', 'Ben-Hur', 'In de Ban van de Ring', 'Alle drie'], correctIndex: 3, hint: 'Drie films delen dit record.', category: 'Entertainment' },
  { question: 'Wat is de hoogste waterval ter wereld?', answers: ['Niagara', 'Angelwaterval', 'Victoriawatervallen', 'Iguazú'], correctIndex: 1, hint: 'Hij ligt in Venezuela en is bijna 1 km hoog.', category: 'Geografie' },
  { question: 'Welk fruit drijft op water?', answers: ['Banaan', 'Appel', 'Druif', 'Kers'], correctIndex: 1, hint: 'Het bestaat voor 25% uit lucht.', category: 'Algemene Kennis' },
  { question: 'Wie heeft dynamiet uitgevonden?', answers: ['Thomas Edison', 'Alfred Nobel', 'Nikola Tesla', 'Alexander Bell'], correctIndex: 1, hint: 'De beroemdste prijs ter wereld is naar hem vernoemd.', category: 'Geschiedenis' },
  { question: 'Welke kleur heeft de "zwarte doos" in een vliegtuig?', answers: ['Zwart', 'Oranje', 'Rood', 'Geel'], correctIndex: 1, hint: 'De naam is misleidend — hij moet goed zichtbaar zijn.', category: 'Algemene Kennis' },
  { question: 'Welk land voerde als eerste het vrouwenkiesrecht in?', answers: ['Frankrijk', 'VS', 'Duitsland', 'Nieuw-Zeeland'], correctIndex: 3, hint: 'Een eilandstaat in Oceanië — 1893.', category: 'Geschiedenis' },
  { question: 'Hoeveel harten heeft een regenworm?', answers: ['1', '3', '5', '10'], correctIndex: 2, hint: 'Het zijn eigenlijk aortabogen, maar ze werken als harten.', category: 'Wetenschap' },
  { question: 'Welke planeet draait het snelst?', answers: ['Aarde', 'Mars', 'Jupiter', 'Saturnus'], correctIndex: 2, hint: 'De grootste planeet — een dag duurt er maar 10 uur.', category: 'Wetenschap' },
  { question: 'Welk instrument wordt met twee stokjes bespeeld?', answers: ['Viool', 'Trommel', 'Gitaar', 'Piano'], correctIndex: 1, hint: 'Je slaat erop — ritme is het belangrijkste.', category: 'Algemene Kennis' },
  { question: 'Wat is de hoofdstad van Thailand?', answers: ['Phuket', 'Bangkok', 'Chiang Mai', 'Pattaya'], correctIndex: 1, hint: 'De volledige naam is de langste stadsnaam ter wereld.', category: 'Geografie' },
  { question: 'Welke spier is de sterkste in het menselijk lichaam?', answers: ['Biceps', 'Hart', 'Kauwspier', 'Dijbeen'], correctIndex: 2, hint: 'Je gebruikt het bij het eten — het kan enorme krachten uitoefenen.', category: 'Wetenschap' },
  { question: 'Welk spel heeft de meeste actieve spelers wereldwijd?', answers: ['Fortnite', 'Minecraft', 'League of Legends', 'Roblox'], correctIndex: 1, hint: 'Een blokkenspel met meer dan 140 miljoen actieve spelers.', category: 'Entertainment' },
  { question: 'Welk dier slaapt het meest per dag?', answers: ['Kat', 'Koala', 'Luiaard', 'Bruine vleermuis'], correctIndex: 3, hint: 'Tot 20 uur per dag — ondersteboven hangend.', category: 'Wetenschap' },
  { question: 'Wat is de beroemdste diamant ter wereld?', answers: ['Hope', 'Koh-i-Noor', 'Ster van Afrika', 'Blue Moon'], correctIndex: 1, hint: 'Hij behoort tot de Britse Kroonjuwelen.', category: 'Algemene Kennis' },
  { question: 'Welk land produceert de meeste kaas?', answers: ['Frankrijk', 'Zwitserland', 'VS', 'Duitsland'], correctIndex: 2, hint: 'Het is niet het land dat je typisch met kaas associeert.', category: 'Algemene Kennis' },
  { question: 'Wie schreef "Romeo en Julia"?', answers: ['Goethe', 'Shakespeare', 'Schiller', 'Molière'], correctIndex: 1, hint: 'Een Engelse toneelschrijver uit de 16e eeuw.', category: 'Geschiedenis' },
  { question: 'Welk gas maakt je stem hoger?', answers: ['Stikstof', 'Zuurstof', 'Helium', 'Waterstof'], correctIndex: 2, hint: 'Het wordt ook voor ballonnen gebruikt.', category: 'Wetenschap' },
  { question: 'In welk land is voetbal uitgevonden?', answers: ['Brazilië', 'Duitsland', 'Engeland', 'Spanje'], correctIndex: 2, hint: 'De Premier League komt uit dit land.', category: 'Sport' },
  { question: 'Welke vogel kan het diepst duiken?', answers: ['Albatros', 'Pinguïn', 'Pelikaan', 'Aalscholver'], correctIndex: 1, hint: 'Een vogel die niet kan vliegen en in Antarctica leeft.', category: 'Wetenschap' },
  { question: 'Wat is de grootste spin ter wereld?', answers: ['Zwarte weduwe', 'Vogelspin', 'Goliathvogelspin', 'Tarantula'], correctIndex: 2, hint: 'Hij kan een pootspanwijdte van 30 cm hebben.', category: 'Wetenschap' },
  { question: 'Welk fruit heeft de meeste zaden?', answers: ['Watermeloen', 'Granaatappel', 'Kiwi', 'Aardbei'], correctIndex: 3, hint: 'De zaden zitten aan de buitenkant — gemiddeld zo\'n 200 per vrucht.', category: 'Algemene Kennis' },
  { question: 'Welk metaal komt het meest voor in de aardkorst?', answers: ['IJzer', 'Aluminium', 'Koper', 'Goud'], correctIndex: 1, hint: 'Het wordt gebruikt voor blikjes en vliegtuigen.', category: 'Wetenschap' },
  { question: 'Welk continent heeft geen woestijn?', answers: ['Europa', 'Zuid-Amerika', 'Australië', 'Geen — allemaal hebben ze woestijnen'], correctIndex: 0, hint: 'Het op één na kleinste continent.', category: 'Geografie' },
  { question: 'Hoeveel toetsen heeft een standaardpiano?', answers: ['76', '82', '88', '92'], correctIndex: 2, hint: '52 witte en 36 zwarte toetsen.', category: 'Algemene Kennis' },
  { question: 'Welke bloedgroep is het zeldzaamst?', answers: ['A negatief', 'B negatief', 'AB negatief', 'O negatief'], correctIndex: 2, hint: 'Slechts ongeveer 1% van de wereldbevolking heeft deze bloedgroep.', category: 'Wetenschap' },
  { question: 'In welke film zegt men "Moge de Kracht met je zijn"?', answers: ['Star Trek', 'Star Wars', 'The Matrix', 'In de Ban van de Ring'], correctIndex: 1, hint: 'Lichtzwaarden en Jedi spelen een grote rol.', category: 'Entertainment' },
  { question: 'Welk dier heeft de grootste ogen in het dierenrijk?', answers: ['Olifant', 'Struisvogel', 'Reuzeninktvis', 'Adelaar'], correctIndex: 2, hint: 'Zijn ogen kunnen zo groot zijn als een voetbal.', category: 'Wetenschap' },
  { question: 'Wat is de langste rivier van Duitsland?', answers: ['Elbe', 'Rijn', 'Donau', 'Weser'], correctIndex: 1, hint: 'Hij stroomt door Keulen en Düsseldorf.', category: 'Geografie' },
  { question: 'Welke feestdag wordt op 31 oktober gevierd?', answers: ['Sinterklaas', 'Halloween', 'Hervormingsdag', 'Beide B en C'], correctIndex: 3, hint: 'In Duitsland is het een kerkelijke feestdag, internationaal verkleden mensen zich.', category: 'Algemene Kennis' },
];
