export interface SharedQuizQuestion {
  question: string;
  answers: string[];
  correctIndex: number;
  hint: string;
  category: string;
}

export const SHARED_QUIZ_QUESTIONS: SharedQuizQuestion[] = [
  // Géographie (10)
  { question: 'Quelle ville a plus de ponts que Venise ?', answers: ['Amsterdam', 'Hambourg', 'Saint-Pétersbourg', 'Stockholm'], correctIndex: 1, hint: 'Cette ville est dans le nord de l\'Allemagne et possède un grand port.', category: 'Géographie' },
  { question: 'Quel pays a la forme d\'une botte ?', answers: ['Grèce', 'Croatie', 'Italie', 'Portugal'], correctIndex: 2, hint: 'Pensez à la pizza, aux pâtes et au Pape.', category: 'Géographie' },
  { question: 'Dans quel pays se trouve principalement le Sahara ?', answers: ['Égypte', 'Algérie', 'Libye', 'Maroc'], correctIndex: 1, hint: 'Le plus grand pays d\'Afrique par superficie.', category: 'Géographie' },
  { question: 'Quel est le plus long fleuve d\'Europe ?', answers: ['Danube', 'Rhin', 'Volga', 'Elbe'], correctIndex: 2, hint: 'Il traverse la Russie et se jette dans la mer Caspienne.', category: 'Géographie' },
  { question: 'Quelle est la capitale de l\'Australie ?', answers: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], correctIndex: 2, hint: 'Ce n\'est PAS la plus grande ville du pays.', category: 'Géographie' },
  { question: 'Quelle mer se trouve entre l\'Europe et l\'Afrique ?', answers: ['Mer Rouge', 'Mer Méditerranée', 'Mer Noire', 'Mer du Nord'], correctIndex: 1, hint: 'Les touristes y vont pour le soleil et la plage.', category: 'Géographie' },
  { question: 'Dans quel pays se trouve la Statue de la Liberté ?', answers: ['France', 'États-Unis', 'Angleterre', 'Canada'], correctIndex: 1, hint: 'C\'était un cadeau de la France à ce pays.', category: 'Géographie' },
  { question: 'Quel continent est le plus froid ?', answers: ['Arctique', 'Antarctique', 'Groenland', 'Sibérie'], correctIndex: 1, hint: 'Les pingouins y vivent, mais pas les ours polaires.', category: 'Géographie' },
  { question: 'Quel est le plus petit Land d\'Allemagne ?', answers: ['Hambourg', 'Sarre', 'Brême', 'Berlin'], correctIndex: 2, hint: 'Cette ville hanséatique est au nord-ouest.', category: 'Géographie' },
  { question: 'Dans quel pays se trouve Angkor Wat ?', answers: ['Thaïlande', 'Vietnam', 'Cambodge', 'Myanmar'], correctIndex: 2, hint: 'Le complexe de temples figure sur le drapeau de ce pays.', category: 'Géographie' },

  // Histoire (10)
  { question: 'Qui a composé la Neuvième Symphonie ?', answers: ['Mozart', 'Bach', 'Beethoven', 'Schubert'], correctIndex: 2, hint: 'Il est devenu sourd mais a continué à composer.', category: 'Histoire' },
  { question: 'En quelle année le Titanic a-t-il coulé ?', answers: ['1910', '1912', '1914', '1916'], correctIndex: 1, hint: 'Deux ans avant la Première Guerre mondiale.', category: 'Histoire' },
  { question: 'Qui fut le premier chancelier allemand ?', answers: ['Willy Brandt', 'Konrad Adenauer', 'Ludwig Erhard', 'Helmut Schmidt'], correctIndex: 1, hint: 'Il a gouverné de 1949 à 1963.', category: 'Histoire' },
  { question: 'Quel édifice a été construit à Paris en 1889 ?', answers: ['Arc de Triomphe', 'Louvre', 'Tour Eiffel', 'Notre-Dame'], correctIndex: 2, hint: 'Il a été construit pour une Exposition universelle et est en fer.', category: 'Histoire' },
  { question: 'Qui a inventé l\'ampoule électrique ?', answers: ['Nikola Tesla', 'Thomas Edison', 'Alexander Bell', 'Benjamin Franklin'], correctIndex: 1, hint: 'Il a aussi fondé General Electric.', category: 'Histoire' },
  { question: 'Quel animal était l\'animal de compagnie préféré de Cléopâtre ?', answers: ['Chien', 'Chat', 'Serpent', 'Perroquet'], correctIndex: 1, hint: 'Ces animaux étaient vénérés comme sacrés dans l\'Égypte antique.', category: 'Histoire' },
  { question: 'Quand Internet est-il devenu accessible au public ?', answers: ['1985', '1991', '1995', '2000'], correctIndex: 1, hint: 'Tim Berners-Lee a publié le World Wide Web.', category: 'Histoire' },
  { question: 'Quelle langue parlait-on dans l\'Empire romain ?', answers: ['Grec', 'Latin', 'Araméen', 'Celte'], correctIndex: 1, hint: 'Beaucoup de termes médicaux viennent de cette langue.', category: 'Histoire' },
  { question: 'Qui fut la première personne dans l\'espace ?', answers: ['Neil Armstrong', 'Youri Gagarine', 'Buzz Aldrin', 'John Glenn'], correctIndex: 1, hint: 'Il venait de l\'Union soviétique et a volé en 1961.', category: 'Histoire' },
  { question: 'Quel jeu a été inventé en 1903 ?', answers: ['Échecs', 'Monopoly', 'Jeu des petits chevaux', 'Scrabble'], correctIndex: 2, hint: 'Un jeu de plateau avec des dés et des pions colorés d\'Allemagne.', category: 'Histoire' },

  // Sciences (10)
  { question: 'De quoi sont faits les diamants ?', answers: ['Silicium', 'Carbone', 'Quartz', 'Calcium'], correctIndex: 1, hint: 'Le même élément que l\'on trouve dans les mines de crayon.', category: 'Sciences' },
  { question: 'Quelle planète est la plus proche du Soleil ?', answers: ['Vénus', 'Mercure', 'Mars', 'Terre'], correctIndex: 1, hint: 'C\'est aussi la plus petite planète de notre système solaire.', category: 'Sciences' },
  { question: 'Combien de dents un adulte a-t-il normalement ?', answers: ['28', '30', '32', '34'], correctIndex: 2, hint: 'Y compris les quatre dents de sagesse.', category: 'Sciences' },
  { question: 'Qu\'est-ce qui pèse plus : un kilo de plumes ou un kilo d\'acier ?', answers: ['Plumes', 'Acier', 'Ils pèsent pareil', 'Ça dépend de la quantité'], correctIndex: 2, hint: 'Réfléchissez bien — c\'est déjà dans la question.', category: 'Sciences' },
  { question: 'Quel animal a trois cœurs ?', answers: ['Pieuvre', 'Méduse', 'Requin', 'Tortue'], correctIndex: 0, hint: 'Il a aussi huit bras et du sang bleu.', category: 'Sciences' },
  { question: 'Quel gaz respirons-nous ?', answers: ['Azote', 'CO2', 'Oxygène', 'Hydrogène'], correctIndex: 2, hint: 'Sans ce gaz, nous ne pourrions pas survivre — formule O2.', category: 'Sciences' },
  { question: 'Quel organe consomme le plus d\'énergie ?', answers: ['Cœur', 'Cerveau', 'Foie', 'Muscles'], correctIndex: 1, hint: 'Il ne pèse que 1,5 kg mais utilise 20 % de l\'oxygène.', category: 'Sciences' },
  { question: 'Quelle est la vitesse du son approximativement ?', answers: ['340 m/s', '1 200 m/s', '3 000 m/s', '100 m/s'], correctIndex: 0, hint: 'Le tonnerre arrive après l\'éclair — environ 1 km toutes les 3 secondes.', category: 'Sciences' },
  { question: 'Quel métal est liquide à température ambiante ?', answers: ['Plomb', 'Mercure', 'Zinc', 'Aluminium'], correctIndex: 1, hint: 'Il était autrefois utilisé dans les thermomètres.', category: 'Sciences' },
  { question: 'Quel est le plus grand os du corps humain ?', answers: ['Tibia', 'Fémur', 'Humérus', 'Bassin'], correctIndex: 1, hint: 'Il est dans la cuisse — en latin : Femur.', category: 'Sciences' },

  // Divertissement et Culture Pop (10)
  { question: 'Quel groupe a chanté "Bohemian Rhapsody" ?', answers: ['The Beatles', 'Queen', 'Led Zeppelin', 'Pink Floyd'], correctIndex: 1, hint: 'Le chanteur s\'appelait Freddie et venait de Zanzibar.', category: 'Divertissement' },
  { question: 'Dans quel film y a-t-il un Anneau de Pouvoir ?', answers: ['Harry Potter', 'Narnia', 'Le Seigneur des Anneaux', 'Game of Thrones'], correctIndex: 2, hint: 'Un hobbit doit le porter jusqu\'à la Montagne du Destin.', category: 'Divertissement' },
  { question: 'Quel animal est Simba ?', answers: ['Tigre', 'Lion', 'Léopard', 'Guépard'], correctIndex: 1, hint: 'Film Disney — « Le Roi … »', category: 'Divertissement' },
  { question: 'Quel est le nom complet du sorcier dans Harry Potter ?', answers: ['Harry Potter', 'Albus Dumbledore', 'Gandalf le Gris', 'Merlin'], correctIndex: 1, hint: 'Il est le directeur de Poudlard.', category: 'Divertissement' },
  { question: 'De quelle couleur dit-on que le monstre du Loch Ness est ?', answers: ['Vert', 'Bleu', 'Noir', 'Gris-vert'], correctIndex: 3, hint: 'Nessie — supposément un monstre marin en Écosse.', category: 'Divertissement' },
  { question: 'Quel super-héros est Bruce Wayne ?', answers: ['Superman', 'Spider-Man', 'Batman', 'Iron Man'], correctIndex: 2, hint: 'Il vit à Gotham City et n\'a pas de super-pouvoir — juste de l\'argent.', category: 'Divertissement' },
  { question: 'Quelle série se déroule à Hawkins, Indiana ?', answers: ['Breaking Bad', 'Stranger Things', 'The Walking Dead', 'Dark'], correctIndex: 1, hint: 'Des enfants combattent des monstres de l\'Upside Down.', category: 'Divertissement' },
  { question: 'Qui chante "Shape of You" ?', answers: ['Justin Bieber', 'Ed Sheeran', 'Bruno Mars', 'The Weeknd'], correctIndex: 1, hint: 'Un auteur-compositeur-interprète britannique roux.', category: 'Divertissement' },
  { question: 'Dans quel jeu construit-on avec des blocs ?', answers: ['Fortnite', 'Roblox', 'Minecraft', 'Terraria'], correctIndex: 2, hint: 'Il y a des Creepers, des Endermen et des diamants.', category: 'Divertissement' },
  { question: 'De quelle couleur est la queue de Pikachu ?', answers: ['Jaune', 'Noir', 'Marron', 'Jaune avec une pointe noire'], correctIndex: 3, hint: 'C\'est un Pokémon électrique avec des joues rouges.', category: 'Divertissement' },

  // Sport (10)
  { question: 'Combien de joueurs compte une équipe de football ?', answers: ['10', '11', '12', '9'], correctIndex: 1, hint: 'Y compris le gardien sur le terrain.', category: 'Sport' },
  { question: 'Dans quel pays le judo a-t-il été inventé ?', answers: ['Chine', 'Corée', 'Japon', 'Thaïlande'], correctIndex: 2, hint: 'Cet art martial a été fondé par Jigoro Kano en 1882.', category: 'Sport' },
  { question: 'Quel court de tennis est en terre battue rouge ?', answers: ['Wimbledon', 'Roland-Garros', 'US Open', 'Open d\'Australie'], correctIndex: 1, hint: 'Ce tournoi se déroule à Paris.', category: 'Sport' },
  { question: 'Combien d\'anneaux comporte le symbole olympique ?', answers: ['4', '5', '6', '7'], correctIndex: 1, hint: 'Chaque anneau représente un continent.', category: 'Sport' },
  { question: 'Quel pays a remporté la Coupe du Monde de football 2014 ?', answers: ['Argentine', 'Brésil', 'Allemagne', 'Espagne'], correctIndex: 2, hint: 'Mario Götze a marqué le but en finale.', category: 'Sport' },
  { question: 'Quel est le score maximum au bowling ?', answers: ['200', '250', '300', '350'], correctIndex: 2, hint: 'Les 12 lancers doivent être des strikes.', category: 'Sport' },
  { question: 'Quel sport se joue sur glace avec un palet ?', answers: ['Curling', 'Hockey sur glace', 'Patinage artistique', 'Patinage de vitesse'], correctIndex: 1, hint: 'Les joueurs portent des patins et des casques.', category: 'Sport' },
  { question: 'Quelle est la distance d\'un marathon ?', answers: ['40 km', '42,195 km', '45 km', '38 km'], correctIndex: 1, hint: 'La distance remonte à une légende de la Grèce antique.', category: 'Sport' },
  { question: 'Dans quel sport y a-t-il un « slam dunk » ?', answers: ['Volleyball', 'Handball', 'Basketball', 'Tennis'], correctIndex: 2, hint: 'Le ballon est enfoncé dans le panier par le haut.', category: 'Sport' },
  { question: 'Quel animal est le symbole du logo Ferrari ?', answers: ['Taureau', 'Lion', 'Cheval', 'Aigle'], correctIndex: 2, hint: 'Un animal cabré sur fond jaune.', category: 'Sport' },

  // Culture Générale (12)
  { question: 'Combien de couleurs a un arc-en-ciel ?', answers: ['5', '6', '7', '8'], correctIndex: 2, hint: 'Rouge, orange, jaune, vert, bleu, indigo et …', category: 'Culture Générale' },
  { question: 'Quel est l\'élément le plus abondant dans l\'univers ?', answers: ['Hélium', 'Oxygène', 'Hydrogène', 'Carbone'], correctIndex: 2, hint: 'Le Soleil est principalement composé de ce gaz.', category: 'Culture Générale' },
  { question: 'Quel instrument a 88 touches ?', answers: ['Orgue', 'Piano', 'Accordéon', 'Synthétiseur'], correctIndex: 1, hint: 'Touches noires et blanches — un classique en cours de musique.', category: 'Culture Générale' },
  { question: 'Dans quelle unité mesure-t-on le courant électrique ?', answers: ['Volt', 'Watt', 'Ampère', 'Ohm'], correctIndex: 2, hint: 'Nommé d\'après le physicien français André-Marie.', category: 'Culture Générale' },
  { question: 'Combien de Länder l\'Allemagne a-t-elle ?', answers: ['14', '15', '16', '17'], correctIndex: 2, hint: 'Trois d\'entre eux sont des villes-États : Berlin, Hambourg et Brême.', category: 'Culture Générale' },
  { question: 'Quel groupe sanguin est le donneur universel ?', answers: ['A', 'B', 'AB', 'O négatif'], correctIndex: 3, hint: 'Ce groupe sanguin n\'a pas d\'antigènes sur les globules rouges.', category: 'Culture Générale' },
  { question: 'Quelle est la monnaie du Japon ?', answers: ['Yuan', 'Won', 'Yen', 'Baht'], correctIndex: 2, hint: 'Le symbole est ¥.', category: 'Culture Générale' },
  { question: 'Quel jour est la Saint-Valentin ?', answers: ['14 janvier', '14 février', '14 mars', '14 avril'], correctIndex: 1, hint: 'La fête des amoureux — avec des roses et du chocolat.', category: 'Culture Générale' },
  { question: 'Combien de secondes y a-t-il dans une heure ?', answers: ['3 000', '3 600', '4 200', '6 000'], correctIndex: 1, hint: '60 minutes fois 60 secondes.', category: 'Culture Générale' },
  { question: 'Quelle vitamine le corps produit-il grâce à la lumière du soleil ?', answers: ['Vitamine A', 'Vitamine C', 'Vitamine D', 'Vitamine B12'], correctIndex: 2, hint: 'Elle est importante pour les os et souvent supplémentée en hiver.', category: 'Culture Générale' },
  { question: 'Combien de zéros a un million ?', answers: ['5', '6', '7', '8'], correctIndex: 1, hint: '1 000 fois 1 000.', category: 'Culture Générale' },
  { question: 'Quel animal peut tourner sa tête de 270 degrés ?', answers: ['Caméléon', 'Hibou', 'Flamant rose', 'Perroquet'], correctIndex: 1, hint: 'Oiseau nocturne aux grands yeux.', category: 'Culture Générale' },

  // Nouvelles Questions (40)
  { question: 'Quel pays possède le plus de fuseaux horaires ?', answers: ['Russie', 'États-Unis', 'France', 'Chine'], correctIndex: 2, hint: 'Pensez aux nombreux territoires d\'outre-mer de ce pays.', category: 'Géographie' },
  { question: 'Quel océan est le plus profond ?', answers: ['Atlantique', 'Pacifique', 'Océan Indien', 'Océan Arctique'], correctIndex: 1, hint: 'La fosse des Mariannes se trouve dans cet océan.', category: 'Géographie' },
  { question: 'Quel élément a le symbole Au ?', answers: ['Argent', 'Aluminium', 'Or', 'Argon'], correctIndex: 2, hint: 'Un métal précieux — en latin « Aurum ».', category: 'Sciences' },
  { question: 'Combien de dents un adulte a-t-il, dents de sagesse comprises ?', answers: ['28', '30', '32', '36'], correctIndex: 2, hint: 'Quatre d\'entre elles arrivent souvent tard et sont parfois extraites.', category: 'Sciences' },
  { question: 'Qui a composé « La Flûte enchantée » ?', answers: ['Bach', 'Beethoven', 'Mozart', 'Haendel'], correctIndex: 2, hint: 'Un enfant prodige de Salzbourg.', category: 'Histoire' },
  { question: 'Quel animal a la pression artérielle la plus élevée ?', answers: ['Éléphant', 'Girafe', 'Baleine', 'Humain'], correctIndex: 1, hint: 'Il a un très long cou et doit pomper le sang très haut.', category: 'Sciences' },
  { question: 'En quelle année les premiers humains ont-ils marché sur la Lune ?', answers: ['1965', '1967', '1969', '1971'], correctIndex: 2, hint: 'Neil Armstrong a prononcé sa célèbre phrase.', category: 'Histoire' },
  { question: 'Quel sport se joue pour la Coupe Stanley ?', answers: ['Basketball', 'Football américain', 'Hockey sur glace', 'Baseball'], correctIndex: 2, hint: 'Un sport sur glace avec un palet.', category: 'Sport' },
  { question: 'Quel est l\'animal national de l\'Écosse ?', answers: ['Lion', 'Licorne', 'Cerf', 'Aigle'], correctIndex: 1, hint: 'Une créature mythique avec une corne.', category: 'Culture Générale' },
  { question: 'Quel fleuve traverse Le Caire ?', answers: ['Euphrate', 'Nil', 'Tigre', 'Jourdain'], correctIndex: 1, hint: 'Le plus long fleuve d\'Afrique.', category: 'Géographie' },
  { question: 'Quel est le plus petit os du corps humain ?', answers: ['Étrier', 'Marteau', 'Enclume', 'Os d\'orteil'], correctIndex: 0, hint: 'Il est dans l\'oreille et ne mesure que 3 mm.', category: 'Sciences' },
  { question: 'Quel film a remporté le plus d\'Oscars (11) ?', answers: ['Titanic', 'Ben-Hur', 'Le Seigneur des Anneaux', 'Les trois'], correctIndex: 3, hint: 'Trois films partagent ce record.', category: 'Divertissement' },
  { question: 'Quelle est la plus haute cascade du monde ?', answers: ['Niagara', 'Salto Angel', 'Chutes Victoria', 'Iguazú'], correctIndex: 1, hint: 'Elle se trouve au Venezuela et mesure presque 1 km.', category: 'Géographie' },
  { question: 'Quel fruit flotte sur l\'eau ?', answers: ['Banane', 'Pomme', 'Raisin', 'Cerise'], correctIndex: 1, hint: 'Il est composé de 25 % d\'air.', category: 'Culture Générale' },
  { question: 'Qui a inventé la dynamite ?', answers: ['Thomas Edison', 'Alfred Nobel', 'Nikola Tesla', 'Alexander Bell'], correctIndex: 1, hint: 'Le prix le plus célèbre du monde porte son nom.', category: 'Histoire' },
  { question: 'De quelle couleur est la « boîte noire » d\'un avion ?', answers: ['Noire', 'Orange', 'Rouge', 'Jaune'], correctIndex: 1, hint: 'Le nom est trompeur — elle doit être très visible.', category: 'Culture Générale' },
  { question: 'Quel pays a été le premier à introduire le droit de vote des femmes ?', answers: ['France', 'États-Unis', 'Allemagne', 'Nouvelle-Zélande'], correctIndex: 3, hint: 'Une nation insulaire en Océanie — 1893.', category: 'Histoire' },
  { question: 'Combien de cœurs a un ver de terre ?', answers: ['1', '3', '5', '10'], correctIndex: 2, hint: 'Ce sont en fait des arcs aortiques, mais ils fonctionnent comme des cœurs.', category: 'Sciences' },
  { question: 'Quelle planète tourne le plus vite ?', answers: ['Terre', 'Mars', 'Jupiter', 'Saturne'], correctIndex: 2, hint: 'La plus grande planète — un jour n\'y dure que 10 heures.', category: 'Sciences' },
  { question: 'Quel instrument se joue avec deux baguettes ?', answers: ['Violon', 'Tambour', 'Guitare', 'Piano'], correctIndex: 1, hint: 'On le frappe — le rythme est le plus important.', category: 'Culture Générale' },
  { question: 'Quelle est la capitale de la Thaïlande ?', answers: ['Phuket', 'Bangkok', 'Chiang Mai', 'Pattaya'], correctIndex: 1, hint: 'Son nom complet est le plus long nom de ville au monde.', category: 'Géographie' },
  { question: 'Quel est le muscle le plus puissant du corps humain ?', answers: ['Biceps', 'Cœur', 'Masséter', 'Cuisse'], correctIndex: 2, hint: 'On l\'utilise en mangeant — il peut exercer une force énorme.', category: 'Sciences' },
  { question: 'Quel jeu a le plus de joueurs actifs dans le monde ?', answers: ['Fortnite', 'Minecraft', 'League of Legends', 'Roblox'], correctIndex: 1, hint: 'Un jeu de blocs avec plus de 140 millions de joueurs actifs.', category: 'Divertissement' },
  { question: 'Quel animal dort le plus par jour ?', answers: ['Chat', 'Koala', 'Paresseux', 'Chauve-souris brune'], correctIndex: 3, hint: 'Jusqu\'à 20 heures par jour — suspendu la tête en bas.', category: 'Sciences' },
  { question: 'Quel est le diamant le plus célèbre du monde ?', answers: ['Hope', 'Koh-i-Noor', 'Étoile d\'Afrique', 'Blue Moon'], correctIndex: 1, hint: 'Il fait partie des Joyaux de la Couronne britannique.', category: 'Culture Générale' },
  { question: 'Quel pays produit le plus de fromage ?', answers: ['France', 'Suisse', 'États-Unis', 'Allemagne'], correctIndex: 2, hint: 'Ce n\'est pas le pays typiquement associé au fromage.', category: 'Culture Générale' },
  { question: 'Qui a écrit « Roméo et Juliette » ?', answers: ['Goethe', 'Shakespeare', 'Schiller', 'Molière'], correctIndex: 1, hint: 'Un dramaturge anglais du XVIe siècle.', category: 'Histoire' },
  { question: 'Quel gaz rend la voix plus aiguë ?', answers: ['Azote', 'Oxygène', 'Hélium', 'Hydrogène'], correctIndex: 2, hint: 'On l\'utilise aussi pour les ballons.', category: 'Sciences' },
  { question: 'Dans quel pays le football a-t-il été inventé ?', answers: ['Brésil', 'Allemagne', 'Angleterre', 'Espagne'], correctIndex: 2, hint: 'La Premier League vient de ce pays.', category: 'Sport' },
  { question: 'Quel oiseau peut plonger le plus profondément ?', answers: ['Albatros', 'Manchot', 'Pélican', 'Cormoran'], correctIndex: 1, hint: 'Un oiseau incapable de voler qui vit en Antarctique.', category: 'Sciences' },
  { question: 'Quelle est la plus grande araignée du monde ?', answers: ['Veuve noire', 'Mygale', 'Mygale de Goliath', 'Tarentule'], correctIndex: 2, hint: 'Elle peut avoir une envergure de pattes de 30 cm.', category: 'Sciences' },
  { question: 'Quel fruit a le plus de graines ?', answers: ['Pastèque', 'Grenade', 'Kiwi', 'Fraise'], correctIndex: 3, hint: 'Les graines sont à l\'extérieur — environ 200 par fruit en moyenne.', category: 'Culture Générale' },
  { question: 'Quel métal est le plus abondant dans la croûte terrestre ?', answers: ['Fer', 'Aluminium', 'Cuivre', 'Or'], correctIndex: 1, hint: 'Il est utilisé pour les canettes et les avions.', category: 'Sciences' },
  { question: 'Quel continent n\'a pas de désert ?', answers: ['Europe', 'Amérique du Sud', 'Australie', 'Aucun — tous en ont'], correctIndex: 0, hint: 'Le deuxième plus petit continent.', category: 'Géographie' },
  { question: 'Combien de touches a un piano standard ?', answers: ['76', '82', '88', '92'], correctIndex: 2, hint: '52 blanches et 36 noires.', category: 'Culture Générale' },
  { question: 'Quel est le groupe sanguin le plus rare ?', answers: ['A négatif', 'B négatif', 'AB négatif', 'O négatif'], correctIndex: 2, hint: 'Seulement environ 1 % de la population mondiale a ce groupe.', category: 'Sciences' },
  { question: 'Dans quel film dit-on « Que la Force soit avec toi » ?', answers: ['Star Trek', 'Star Wars', 'Matrix', 'Le Seigneur des Anneaux'], correctIndex: 1, hint: 'Les sabres laser et les Jedi y jouent un rôle important.', category: 'Divertissement' },
  { question: 'Quel animal a les plus grands yeux du règne animal ?', answers: ['Éléphant', 'Autruche', 'Calmar géant', 'Aigle'], correctIndex: 2, hint: 'Ses yeux peuvent être aussi grands qu\'un ballon de football.', category: 'Sciences' },
  { question: 'Quel est le plus long fleuve d\'Allemagne ?', answers: ['Elbe', 'Rhin', 'Danube', 'Weser'], correctIndex: 1, hint: 'Il traverse Cologne et Düsseldorf.', category: 'Géographie' },
  { question: 'Quelle fête est célébrée le 31 octobre ?', answers: ['Saint-Nicolas', 'Halloween', 'Jour de la Réforme', 'Les deux B et C'], correctIndex: 3, hint: 'En Allemagne c\'est un jour férié religieux, à l\'international on se déguise.', category: 'Culture Générale' },
];
